### ISSUE TITLE
Add buffer HTML generation helper

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#1001]
We have the following pattern all over the place:

```lisp
(let* ((buffer (or (find-buffer 'whatever-mode)
                   (whatever-mode
                    :activate t
                    :buffer (make-internal-buffer :title "*My special buffer*"))))
         (content
           (markup:markup
            (:style (style buffer))
            (:h1 "Packages")
            ;; ...
            ))
         (insert-content (ps:ps (setf (ps:@ document body |innerHTML|)
                                      (ps:lisp content)))))
    (ffi-buffer-evaluate-javascript-async buffer insert-content)
    (set-current-buffer buffer)
    buffer)
```

I suggest we factor this into a helper function, e.g. `make-html-buffer`.  Thoughts?

**Comment by Ambrevar** [comment]
@jmercouris: Thoughts?

**Comment by jmercouris** [comment]
Yes, this would be a good candidate for an abstraction, agreed!

**Comment by aartaka** [comment]
It seems we found the first thing to abstract into #946 :) After all, these auto-generated pages are UI that we're trying to build.

**Comment by Ambrevar** [comment]
Indeed!

I also suggest the following helpers, since they keep popping up:

```lisp
(defun html-write (content &optiona (buffer (current-buffer)))
  (ffi-buffer-evaluate-javascript-async
   buffer
   (ps:ps (ps:chain document
                    (write (ps:lisp content))))))

(defun html-set (content &optiona (buffer (current-buffer)))
  (ffi-buffer-evaluate-javascript-async
   buffer
   (ps:ps (setf (ps:@ document body |innerHTML|)
                (ps:lisp content)))))
```

**Comment by jmercouris** [comment]
That is a good start I think! What do you think of specializing a method on buffer?

**Comment by Ambrevar** [comment]
Which use case can you foresee?

**Comment by jmercouris** [comment]
I can anticipate that internal and external buffers may have different ways of writing, we may for example use renderer methods to set the HTML directly in future iterations (without JavaScript)

**Comment by Ambrevar** [comment]
Are we ever _writing HTML_ to web-buffer?

**Comment by jmercouris** [comment]
I still think we should use methods, it is a kind of type checking in a way if you think about it

**Comment by Ambrevar** [comment]
It's not because it's not caught at compilation time.
Type checking must be done with (declaim (ftype ...)).

**Comment by jmercouris** [comment]
well, yes, but IS caught at run time :-D

**Comment by Ambrevar** [comment]
If it wasn't caught, it would only fail later, so this is not very
helpful... :p

**Comment by jmercouris** [comment]
But I like methods :'(
