### ISSUE TITLE
Cursor movements (word-wise)

### ISSUE THREAD

**Issue by aadcg** [atlas-engineer/nyxt#1008]
I'm a new Nyxt user with few expertise in programming.  

Today I used `spell-check-word-at-cursor` and observed that it only works when there are no whitespaces between the last word and the cursor (`word|`, where "|" denotes the cursor).  

~~If I'm correct, all that needs to be done is to redefine `word-separation-characters` to accomodate not only for 1 and only 1 whitespace, but for 1 or more. Most likely, it's possible to use regex syntax to do this. This would also make the behaviour of `cursor-backwards-word` and all of the related methods more intuitive.~~ Well, intuitive is relative of course. To my mind, the behaviour of `M-f` in Emacs makes more sense than the current behaviour in Nyxt. 

Perhaps there's a reason for the current implementation that I didn't grasp.

**Comment by aadcg** [comment]
My analysis above is wrong, sorry.  

My suggestion is to replace the current `move-forward-word`

```lisp
(defmethod move-backward-word ((cursor cursor))
  (unless (cluffer:beginning-of-line-p cursor)
    (values
     (if (find (cluffer:item-before-cursor cursor)
               (word-separation-characters cursor)
               :test #'equal)
         (loop while (find (cluffer:item-before-cursor cursor)
                           (word-separation-characters cursor)
                           :test #'equal)
               do (cluffer:backward-item cursor)
               until (cluffer:beginning-of-line-p cursor))
         (loop while (not (find (cluffer:item-before-cursor cursor)
                                (word-separation-characters cursor)
                                :test #'equal))
               do (cluffer:backward-item cursor)
               until (cluffer:beginning-of-line-p cursor)
               collect (cluffer:item-before-cursor cursor)))
     (cluffer:cursor-position cursor))))
```

with something along these lines:

```lisp
(defmethod move-backward-word ((cursor cursor))
  (progn
    (loop while (find (cluffer:item-before-cursor cursor)
                      (word-separation-characters cursor)
                      :test #'equal)
          do (cluffer:backward-item cursor)
          until (cluffer:beginning-of-line-p cursor)
          )
    (loop while (not (find (cluffer:item-before-cursor cursor)
                           (word-separation-characters cursor)
                           :test #'equal))
          do (cluffer:backward-item cursor)
          until (cluffer:beginning-of-line-p cursor))))
```

The necessary changes would need to be propagated to `move-forward-word`.

**Comment by jmercouris** [comment]
Hello! Thank you for taking the time to write a nice proposal! We appreciate it.

I just want to make sure I understand you correctly. I believe that in the suggested snippet, the following would occur:

+ buffer state: "some word   |"
+ user presses move-backward-word
+ buffer state: "some |word"

whereas in the current implementation:

+ buffer state: "some word   |"
+ user presses move-backward-word
+ buffer state: "some word|"

is that correct?

If so, what are the advantages of the new implementation? Do you think it would be behavior that is more inline with what users are expecting?

**Comment by aadcg** [comment]
John Mercouris <notifications@github.com> writes:

> I just want to make sure I understand you correctly. I believe that in
> the suggested snippet, the following would occur:
>
> * buffer state: "some word |"
> * user presses move-backward-word
> * buffer state: "some |word"
>
> whereas in the current implementation:
>
> * buffer state: "some word |"
> * user presses move-backward-word
> * buffer state: "some word|"
>
> is that correct?

Yes!

> If so, what are the advantages of the new implementation? Do you think
> it would be behavior that is more inline with what users are expecting?

Well, like I said intuitive is always subjective.  In Emacs,
`backward-word` (binded to M-b) is implemented the way I'm suggesting,
and I believe that semantically it does make sense.  Going back by word
means placing the cursor at the beginning of the words, whereas going
forward means placing the cursor at the end of the words.

When I started using Nyxt I noticed it and I found it counter intuitive.
But I thought that perhaps there was a reason behind it.  I don't know
if other text editors have different default behaviors.

I remind you that I started this issue because of
`spell-check-word-at-cursor`, since it didn't work when there were
white-spaces between the last word and the cursor.  It seems that I can't
reproduce this issue since the method is broken in the last release
available on guix (2-pre-release-3).

I can try to have a look at this :)

**Comment by Ambrevar** [comment]
André Alexandre Gomes <notifications@github.com> writes:

> It seems that I can't
> reproduce this issue since the method is broken in the last release
> available on guix (2-pre-release-3).

Oops, that's me, sorry!
I've fixed it with 
79f036c2252d45c412a11e2bb694810ff12f5468.

Thanks for the notice!

**Comment by aadcg** [comment]
Thank you @Ambrevar!  

What do you think about the cursor movements word-wise?

**Comment by Ambrevar** [comment]
Many programs seem to behave differently and there will always be
someone who likes a different behaviour.

But this is Nyxt and we are not stuck with defaults, so I suggest we
make all possible behaviours customizable.
It's easy to introduce configuration knobs for this kind of movements.

Would you like to send a patch for this?

**Comment by aadcg** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> Would you like to send a patch for this?

I will!

-- 
André Alexandre Gomes
"Free Thought, Free World"

**Comment by Ambrevar** [comment]
Thanks!

**Comment by aadcg** [comment]
Addresed in #1027.
