### ISSUE TITLE
Nyxt doesn't start from REPL

### ISSUE THREAD

**Issue by aartaka** [atlas-engineer/nyxt#1012]
**Describe the bug**

Nyxt doesn't start properly when started from REPL -- it just hangs after logging "Initializing GTK Interface" to debug. It seems that it's a problem with `chanl:pexec` that starts soon after the "Initializing GTK Interface" message.

I haven't yet tested commits before the ones introducing `chanl`, though.

**Precise recipe to reproduce the issue**

Run Nyxt from master from the REPL :)

I haven't found other circumstances to narrow it down, unfortunately.

**Information**
- OS name+version: Guix System
```
$ guix describe
]8;;file://paranoidal/var/guix/profiles/per-user/aartaka/current-guix-56-link\Generation 56	Oct 22 2020 22:06:39]8;;\	(current)
  nonguix 02cf886
    repository URL: https://gitlab.com/nonguix/nonguix
    branch: master
    commit: ]8;;https://gitlab.com/nonguix/nonguix/commit/02cf886efac46de75a1226128a7cc4534ef426d2\02cf886efac46de75a1226128a7cc4534ef426d2]8;;\
  guix-gaming-games 3c9a3c4
    repository URL: https://gitlab.com/guix-gaming-channels/games.git
    branch: master
    commit: ]8;;https://gitlab.com/guix-gaming-channels/games/commit/3c9a3c450343b24fb7c27e4986b5da402347c1e3\3c9a3c450343b24fb7c27e4986b5da402347c1e3]8;;\
  chur 8fcb5dd
    repository URL: https://github.com/aartaka/chur-guix
    branch: master
    commit: ]8;;https://github.com/aartaka/chur-guix/commit/8fcb5ddaa15fd10d71c1e50950405bb6d48e4393\8fcb5ddaa15fd10d71c1e50950405bb6d48e4393]8;;\
  guix 3e09453
    repository URL: https://git.savannah.gnu.org/git/guix.git
    branch: master
    commit: ]8;;https://git.savannah.gnu.org/cgit/guix.git/commit/?id=3e09453884efa82ef97b8ec6e34470c67a1206a7\3e09453884efa82ef97b8ec6e34470c67a1206a7]8;;\

$ guix --version
guix (GNU Guix) 3e09453884efa82ef97b8ec6e34470c67a1206a7
Copyright (C) 2020 the Guix authors
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```
- Graphics card and driver: 
```
$ lspci -v
...
00:02.0 VGA compatible controller: Intel Corporation UHD Graphics 620 (rev 07) (prog-if 00 [VGA controller])
	Subsystem: ASUSTeK Computer Inc. Device 1c50
	Flags: bus master, fast devsel, latency 0, IRQ 126
	Memory at ee000000 (64-bit, non-prefetchable) [size=16M]
	Memory at d0000000 (64-bit, prefetchable) [size=256M]
	I/O ports at f000 [size=64]
	Expansion ROM at 000c0000 [virtual] [disabled] [size=128K]
	Capabilities: <access denied>
	Kernel driver in use: i915
...
```
- Desktop environment / Window manager name+version: EXWM (Emacs 27.1)
- How you installed Nyxt: 
Source (created Guix environment with `guix environment --no-grafts -l ~/git-cloned/nyxt/build-scripts/guix.scm --ad-hoc nss-certs -- emacs`), 
with `nyxt/gtk` loaded into SLY REPL.

However, the version installed from Guix (2-pre-release-3) and the one compiled from master do both work flawlessly. It's only REPL-started one that doesn't start.

If you can't run copy-system-information, please provide the following:
- Nyxt version: most recent master (b685a0d)
- Lisp implementation/version (if built from source): 
```
$ sbcl --version
SBCL 2.0.9
```
- Kernel name+version:
```
$ uname -a
Linux paranoidal 5.8.15 #1 SMP 1 x86_64 GNU/Linux
```
- WebKitGTK+ version: 2.30.1

**Output when started from a shell**
```
CL-USER> (nyxt:start '(:verbose t :no-init t :no-auto-config t))
Arguments parsed: (VERBOSE T NO-INIT T NO-AUTO-CONFIG T) and NIL
Nyxt version 2-pre-release-2-185-g5acbbfb6
 <INFO> [00:09:56] nyxt start.lisp (bind-socket-or-quit) -
  Listening to socket "/home/aartaka/.local/share/nyxt/nyxt.socket".
<DEBUG> [00:09:56] nyxt renderer-gtk.lisp (ffi-initialize gtk-browser) -
  Initializing GTK Interface
```

**Comment by Ambrevar** [comment]
Which REPL are you using?  SLIME or SLY?

Out of curiosity, which kernel is `Linux paranoidal`?  Pros & cons compared to `linux-libre` and `linux`?

I'll investigate.  In the meantime, a workaround is to start swank or slynk from the browser, then connect to it with slime-connect / sly-connect.  See the developer's readme for more details.

**Comment by Ambrevar** [comment]
Recipe that works for me:

- guix environment --no-grafts -l build-scripts/guix.scm --ad-hoc nss-certs -- emacs
- M-x sly
- (asdf:load-system :nyxt/gtk)
- (nyxt:start '(:verbose t :no-init t))

Can you try to run Nyxt outside of =guix environment=?
Maybe install a Nyxt profile like this one:

(specifications->manifest
  '("gcc-toolchain"                    ; Needed to compile some Common Lisp FFI.
    "glib-networking"                  ; For Nyxt local dev.
    "gobject-introspection"            ; For Nyxt with GI.
    "gsettings-desktop-schemas"        ; For Nyxt local dev.
    "make"
    "sbcl"
    "webkitgtk"                         ; TODO: Remove when cl-webkit is updated.

    "cl-slynk"                          ; To hack Nyxt from the SLY REPL.

    ;; Direct dependencies:
    "cl-alexandria"
    "cl-bordeaux-threads"
    "cl-chanl"                          
    "cl-css"
    "cl-json"
    "cl-markup"
    "cl-ppcre"
    "cl-prevalence"
    "cl-closer-mop"
    "cl-containers"
    "cl-cluffer"
    "cl-dexador"
    "cl-enchant"
    "cl-fset"
    "cl-hu.dwim.defclass-star"
    "cl-iolib"
    "cl-local-time"
    "cl-log4cl"
    "cl-mk-string-metrics"
    "cl-moptilities"
    "cl-osicat" ; Only Guix package of Nyxt needs SBCL version needed for libosicat.so.
    "cl-parenscript"
    "cl-plump"
    "cl-quri"
    "cl-serapeum"
    "cl-str"
    "cl-slime-swank"
    "cl-trivia"
    "cl-trivial-clipboard"
    "cl-trivial-features"
    "cl-trivial-package-local-nicknames"
    "cl-trivial-types"
    "cl-unix-opts"
    ;; WebKitGTK deps
    "cl-cffi-gtk" ; TODO: Does it have info doc?
    "cl-webkit"))

**Comment by Ambrevar** [comment]
There could be a race condition which occurs depending on your processor
speed.

Can you trace function calls to pinpoint where it freezes?

You can use SLIME/SLY to trace individual functions.  If it's too
cumbersome to trace multiple functions, I wrote this helper which can
trace functions matching a regexp:

--8<---------------cut here---------------start------------->8---
(export 'trace-all)
(defun trace-all (regexp &optional (package *package*))
  (asdf:load-system :cl-ppcre)
  (let ((package (if (packagep package)
                     package
                     (uiop:ensure-package package)))
        (result nil))
    (do-symbols (s package)
      (when (and (eq (symbol-package s) package)
                 (funcall (symbol-function (find-symbol (string 'scan)
                                                        (find-package 'ppcre)))
                          regexp (string s)))
        (push s result)))
    (eval `(trace ,@result))))
--8<---------------cut here---------------end--------------->8---

Alternatively, you can scatter `log:warn`s all over the place :)

**Comment by aartaka** [comment]
> Which REPL are you using? SLIME or SLY?

SLY.

> Out of curiosity, which kernel is `Linux paranoidal`? Pros & cons compared to `linux-libre` and `linux`?

It's not a kernel name, it's the name of my machine xD 

The kernel is the a plain `linux` one, not `linux-libre`.

**Comment by Ambrevar** [comment]
> It's not a kernel name, it's the name of my machine xD 

:P

**Comment by aartaka** [comment]
Some more info: `log:warn`-styled debugging revealed that `chanl:pexec` is entered right, while `current-buffers` doesn't return somewhy.

Here's the `log:warn`-ful `make-startup-function` and its output:
``` lisp
(defun make-startup-function (&key (buffer-fn #'help))
  "Return a function suitable as a `browser' `startup-function'.
To change the default buffer, e.g. set it to a given URL:

  (make-startup-function
   :buffer-fn (lambda () (make-buffer :url \"https://example.org\")))"
  (lambda (&optional urls)
    (let ((window (progn (log:warn "Making a window...") (window-make *browser*)))
          (buffer (progn (log:warn "Choosing a buffer...") (current-buffer))))
      ;; Restore session before opening command line URLs, otherwise it will
      ;; reset the session with the new URLs.
      ;; TODO: If (session-restore-prompt *browser*) is :always-ask, the session
      ;; will be overwritten because if-confirm is asynchronous.
      ;; Implement synchronous minibuffer to fix this.
      (log:warn "Window and buffer created in startup function")
      (when (expand-path (session-path buffer))
        (match (session-restore-prompt *browser*)
          (:always-ask (restore-session-by-name))
          (:always-restore (restore (data-profile buffer) (session-path buffer)))
          (:never-restore (log:info "Not restoring session."))))
      (log:warn "Session restored")
      (if urls
          (open-urls urls)
          (window-set-active-buffer window (funcall-safely buffer-fn)))
      (log:warn "URLs are open"))
    (when (startup-error-reporter-function *browser*)
      (funcall-safely (startup-error-reporter-function *browser*)))))
```
```
CL-USER> (nyxt:start '(:verbose t :no-init t :no-auto-config t))
Arguments parsed: (VERBOSE T NO-INIT T NO-AUTO-CONFIG T) and NIL
Nyxt version 2-pre-release-2-203-g8bf0045f
 <INFO> [14:37:03] nyxt start.lisp (bind-socket-or-quit) -
  Listening to socket "/home/aartaka/.local/share/nyxt/nyxt.socket".
<DEBUG> [14:37:03] nyxt renderer-gtk.lisp (ffi-initialize gtk-browser) -
  Initializing GTK Interface
 <WARN> [14:37:03] nyxt renderer-gtk.lisp (ffi-initialize gtk-browser) -
  GTK Loop entered
 <WARN> [14:37:03] nyxt renderer-gtk.lisp (ffi-initialize gtk-browser) -
  GTK Class set
 <WARN> [14:37:03] nyxt browser.lisp (finalize browser) - Chanl pexec entered
 <WARN> [14:37:03] nyxt start.lisp (make-startup-function) - Making a window...
 <WARN> [14:37:03] nyxt window.lisp (window-make) - Making FFI window...
 <WARN> [14:37:03] nyxt window.lisp (window-make) - Running window-make-hook
 <WARN> [14:37:03] nyxt start.lisp (make-startup-function) -
  Choosing a buffer...
```

The last change in `current-buffer` have happened on 22nd of October, while the bug I experience have started earlier, so it may really be a race condition unrelated to `current-buffer`.

I'll look into `current-buffer` and get to you with how it goes.

**Comment by aartaka** [comment]
We should pass all our globals to `chanl:pexec` to ensure that it won't overwrite them or, even worse, create new thread-local variables.

Just a thought. However, it could be a reason for my bug too.

**Comment by Ambrevar** [comment]
Which globals?

- `*browser*` is safe here because we never reset it.
- `*options*` and `*after-init-hook*` are used only before the `pexec`.

So the globals that could be useful to pass are `*keep-alive*` and `*swank-port*`, but I don't think those are responsible for your bug.

Any other global you can think of?

**Comment by aartaka** [comment]
> Any other global you can think of?

`%buffer`. It's extremely dynamic and changes frequently. However, passing it in `chanl:pexec` doesn't resolve the bug, as far as I've tested.

**Comment by Ambrevar** [comment]
Artyom Bologov <notifications@github.com> writes:

> `%buffer`. It's extremely dynamic and changes frequently. However, passing it in `chanl:pexec` doesn't resolve the bug, as far as I've tested.

Good catch, %buffer should be thread-local.

**Comment by Ambrevar** [comment]
Can you git-bisect and find the first commit that works for you?

You can start from the first commit before the synchronous minibuffer
change.

**Comment by aartaka** [comment]
Hmmmmmm. It stopped starting from REPL on as far as `2-pre-release-1`. It's not a problem of `chanl` then. It's something with my setup :) 

I'll try to use profile instead of environment, but that'll require some time.

**Comment by Ambrevar** [comment]
See the profile I shared above:
https://github.com/atlas-engineer/nyxt/issues/1012#issuecomment-715006134


It's as simple as

  guix package -m path/to/manifest.scm -p path/to/my/nyxt/profile

You may have to relog.

Could you bisect further and find the first commit that fails for you?
You might have found a race condition that's unrelated to chanl:pexec.

**Comment by aartaka** [comment]
I found it! e9a99bddf373843268cda3e9dbc15d7f4d2ecb67 works, while commits after it don't.

It also occurs to be the commit right before the synchronous minibuffer got merged...

> I'll try to use profile instead of environment, but that'll require some time.

Profile seems to make no difference, though.

**Comment by Ambrevar** [comment]
OK, thanks for digging this out.

The good news is that this commit is not too gigantic ;)

In short, it only implements synchronous minibuffer for one command, `set-url`.

The rest of Nyxt is left unchanged, in particular the startup should be
as usual.

If this commits really makes a difference, it should only be in the way
commands are run.

In this commit, "return" only works on the set-url minibuffer.
For other minibuffers "return" should hang.

Can you trace the startup see where it fails?

**Comment by aartaka** [comment]
> Can you trace the startup see where it fails?

Sure! I'll get to that tomorrow.

**Comment by aartaka** [comment]
Okay, it's more work than I expected -- 10-15 commits right after e9a99bddf373843268cda3e9dbc15d7f4d2ecb67 are so intertwined that they don't work unless aplied together. And it's a lot of code when taken as one change.

One potential problem I thought of is that `chanl:pexec` relies on `bt:with-lock-held` and cannot be nested, but it seems that all uses of `chanl:pexec` are properly isolated and cannot be nested in our code.

**Comment by Ambrevar** [comment]
> Okay, it's more work than I expected -- 10-15 commits right after e9a99bddf373843268cda3e9dbc15d7f4d2ecb67 are so intertwined that they don't work unless aplied together. And it's a lot of code when taken as one change.

I haven't tested the first commit, but it seems that it can work on its
own.  It echoes that first test that I did when I started working on the
sync minibuffer.

I cannot test now.  If the commit does not work on its own, let me know,
I'll prepare a branch for you so you can test it.

**Comment by aartaka** [comment]
It started! Just after I pulled d36c367eaf637028365463bcbdd2d499b526098f, I was able to load and start Nyxt from the REPL. It's unlikely to be connected with exactly this commit (several random commits before the mentioned one work too), but I can no more reproduce this.

I haven't changed my system configuration and my list of packages stayed the same since yesterday, when I was unable to start Nyxt. No `guix pull` either. 

That's a bit of Heisenbug...

**Comment by aartaka** [comment]
I think we need to keep this issue open in case the bug re-emerges, in the same way as we do with #808 (By the way, should it be closed now? It seems to be unreproducible for quite a long time...).

**Comment by Ambrevar** [comment]
Both this issue and #808 might actually have to do with the Libsoup bug:

https://gitlab.gnome.org/GNOME/libsoup/-/issues/192

I'll try to work on it.
Anyways, this bug is responsible for long startup times, so we really
need to fix it.

**Comment by jmercouris** [comment]
A little bit of an off-topic comment, but the name "libsoup" doesn't inspire much confidence. It makes me think of spaghetti and spaghetti code :-D

**Comment by Ambrevar** [comment]
I found the other concurrency library I was thinking of: Calispel!

http://www.thoughtcrime.us/software/calispel/

It's a bit dated but:

- Unlike lparallel, it does not require this initialization of some
  kernel.

- Unlike lparallel, sending to a channel is a blocking operating (this
  makes lparallel unusable if I understand correctly).

- It has a blocking SELECT statement (called `fair-alt`), unlike
lparallel which has no such statement, and unlike ChanL which has only a
a non-blocking SELECT statement (which makes it almost useless).

I'll keep playing with it, seems like a great contender!

**Comment by Ambrevar** [comment]
Closing since all (?) startup race conditions should be fixed on master and with 2-pre-release-6.
