### ISSUE TITLE
Buffer freezes on YT / Can't play multiple YT videos at the same time

### ISSUE THREAD

**Issue by minikN** [atlas-engineer/nyxt#1017]
**Describe the bug**
I've noticed a couple problems with Next when browsing YT:
- For some reason, the buffer will often just freeze, resulting in something like this:
[Image](https://i.imgur.com/9mYv9OE.png)
I can still delete the buffer (`d`) and try again. But this will occur 100% of the time if triggered like so:
  - Click on another video while the current video is playing
  - Click on "Skip Ad" after 5s of playing an ad

Another problem I've noticed is that if one video is playing, I can't play another one in a different buffer.
After I click play in the second buffer it will just not start. The buffer will not freeze, I can still click on
hyperlinks ect. The video just won't start.

**Precise recipe to reproduce the issue**
1. Case:
- Start Next
- `o` -> `www.youtube.com`
- Click on random video
- Click play
- Click on random Video in suggestions
Buffer will freeze

2. Case:
- Start Next
- `o` -> `www.youtube.com`
- Click on random video
- Click play
- After ad has played for 5s click "Skip Ad"
Buffer will freeze

3. Case
- Start Next
- `o` -> `www.youtube.com`
- Click on random video
- Click play
- `O` -> `www.youtube.com`
- Click on random video
- Click play
- Video will not play.

**Information**
- OS name+version: Void Linux: `Linux voidwalker 5.8.16_1 #1 SMP Sat Oct 17 12:21:35 UTC 2020 x86_64 GNU/Linux`
- Graphics card and driver: GTX 1050 Ti:
```
024 ~ ➜ xbps-query -s nvidia
[*] linux-firmware-nvidia-20200918_1 Binary firmware blobs for the Linux kernel NVIDIA GPU microcode
[*] nvidia-450.80.02_1               NVIDIA drivers for linux - Libraries and Utilities
[*] nvidia-dkms-450.80.02_1          NVIDIA drivers for linux - DKMS kernel module
[*] nvidia-gtklibs-450.80.02_1       NVIDIA drivers for linux - GTK+ libraries
[*] nvidia-libs-450.80.02_1          NVIDIA drivers for linux - common libraries
[*] nvidia-libs-32bit-450.80.02_1    NVIDIA drivers for linux - common libraries (32bit)
[*] nvidia-opencl-450.80.02_1        NVIDIA drivers for linux - OpenCL implementation
```
- Desktop environment / Window manager name+version:
Emacs 27.1 + EXWM
- How you installed Nyxt (Guix pack, package manager, build from source):
From package manager: `sudo xbps-install -S next`
```
001 ~ ➜ xbps-query -R next  
architecture: x86_64
filename-sha256: e6b9ceb061cff7c35a3421e62236aecbf86483bcb68bed4bd336f7132f8476e8
filename-size: 22MB
homepage: https://next.atlas.engineer/
installed_size: 23MB
license: BSD-3-Clause
maintainer: 0x0f0f0f <sudo-woodo3@protonmail.com>
pkgname: next
pkgver: next-1.5.0_1
repository: https://alpha.de.repo.voidlinux.org/current
run_depends:
        sqlite>=0
        xclip>=0
        libfixposix-devel>=0
        libressl-devel>=0
        webkit2gtk>=2.6.2_1
        gtk+3>=3.0.0_1
        libsoup>=2.34.0_1
        glib>=2.18.0_1
        glibc>=2.29_1
        zlib>=1.2.3_1
shlib-requires:
        libwebkit2gtk-4.0.so.37
        libgtk-3.so.0
        libgdk-3.so.0
        libsoup-2.4.so.1
        libgio-2.0.so.0
        libjavascriptcoregtk-4.0.so.18
        libgobject-2.0.so.0
        libglib-2.0.so.0
        libc.so.6
        libdl.so.2
        libpthread.so.0
        libz.so.1
        libm.so.6
short_desc: Keyboard-oriented, extensible web-browser
source-revisions: next:776e056803
```
- Information from command copy-system-information:

  If you can't run copy-system-information, please provide the following:
  - Nyxt version (from =M-x nyxt-version= or =nyxt --version=): `1.5.0_1`
  - Kernel name+version:  See above
  - WebKitGTK+ | QtWebEngine version: 
```
152 ~ ➜ xbps-query -s webkit2gtk
[*] webkit2gtk-2.30.0_1       GTK+3 port of the WebKit2 browser engine
[*] webkit2gtk-devel-2.30.0_1 GTK+3 port of the WebKit2 browser engine - development files
```
```
216 ~ ➜ xbps-query -s qt5-webengine
[*] python3-PyQt5-webengine-5.15.1_2 Python 3 bindings for the Qt5 toolkit - webengine module
[*] qt5-webengine-5.15.1_1           Cross-platform application and UI framework (QT5) - WebEngine component
```
**Output when started from a shell**
```001 ~ ➜ next &
[1] 6562
002 ~ ➜ Next version 1.5.0
Loading configuration from #P"/home/demis/.local/share/git/dotArch/.config/next/init.lisp"...
 <INFO> [17:50:56] next remote.lisp (initialize-instance :after remote-interface) -
  D-Bus addresses: (#<Unix socket address: @"/tmp/dbus-xmgHv7QcpW">)
 <INFO> [17:50:56] next remote.lisp (initialize-instance :after remote-interface) -
  Bus connection name: :1.3788
 <INFO> [17:50:56] next port.lisp (run-program port) -
  Current directory: /home/demis/
 <INFO> [17:50:56] next port.lisp (run-program port) -
  Platform port path: next-gtk-webkit
 <INFO> [17:50:56] next port.lisp (run-program port) -
  Platform port arguments: NIL
 <INFO> [17:50:56] next port.lisp (run-program port) -
  Platform port log file: /home/demis/.local/share/next/next-gtk-webkit.log
 <WARN> [17:50:56] next remote.lisp (current-buffer) -
  No active window, picking last active buffer.

[1]  + done       next --session nil
```
(I aliased `next` to `next --session nil`)

**Comment by minikN** [comment]
Maybe further useful information:
```
032 ~ ➜ xbps-query -s gstreamer
[*] gst-libav-1.16.2_1               GStreamer libav plugin (1.x)
[*] gst-plugins-bad1-1.16.2_10       GStreamer plugins from the bad set (v1.x)
[*] gst-plugins-bad1-devel-1.16.2_10 GStreamer plugins from the bad set (v1.x) - development files
[*] gst-plugins-base1-1.16.2_1       GStreamer Base Plug-ins (v1.x)
[*] gst-plugins-base1-32bit-1.16.2_1 GStreamer Base Plug-ins (v1.x) (32bit)
[*] gst-plugins-base1-devel-1.16.2_1 GStreamer Base Plug-ins (v1.x) - development files
[*] gst-plugins-good1-1.16.2_2       GStreamer set of well-maintained good plug-ins (1.x)
[*] gst-plugins-ugly1-1.16.2_2       GStreamer plugins from the ugly set (1.x)
[*] gstreamer1-1.16.2_1              Core GStreamer libraries and elements (1.x)
[*] gstreamer1-32bit-1.16.2_1        Core GStreamer libraries and elements (1.x) (32bit)
[*] gstreamer1-devel-1.16.2_1        Core GStreamer libraries and elements (1.x) - development files
```

**Comment by minikN** [comment]
Closing for now. Seems to be gstreamer/webkit related: https://github.com/void-linux/void-packages/issues/25852

**Comment by jmercouris** [comment]
Thank for looking into this, hopefully it can be resolved :-)

**Comment by Ambrevar** [comment]
I gave Epiphany a go: it worked in all the aforementioned cases, but it
was very slow.

Then I closed Epiphany and tried again: it crashed a few seconds after
clicking "Skip Ad".

In Nyxt I get similar issues, the buffer hangs, but Nyxt is still
usable.

I'm not sure Nyxt can do much about it.  I suggest using Invidious, now
that we have an extension for it :)
We could also implement a youtube-dl downloaded or an `mpv` player.

**Comment by minikN** [comment]
> I gave Epiphany a go: it worked in all the aforementioned cases, but it was very slow. Then I closed Epiphany and tried again: it crashed a few seconds after clicking "Skip Ad". In Nyxt I get similar issues, the buffer hangs, but Nyxt is still usable. I'm not sure Nyxt can do much about it. I suggest using Invidious, now that we have an extension for it :) We could also implement a youtube-dl downloaded or an `mpv` player.

youtube-dl / mpv integration would be NICE regardless of this bug.

**Comment by minikN** [comment]
@Ambrevar Are you on Void too?

**Comment by jmercouris** [comment]
No, @Ambrevar is using Guix.
