### ISSUE TITLE
Can't enter text (commands, urls, &c.)

### ISSUE THREAD

**Issue by emacsomancer** [atlas-engineer/nyxt#1018]
**Describe the bug**
Unable to enter text: for urls after `C-l` or commands after `M-x` &c. I can use arrow keys and to enter to select, but it won't accept any other text input. (I'm not sure if there are some old config, cache I should clean out that could be causing this?)

**Precise recipe to reproduce the issue**
Run nyxt/next - whether from Void, Guix, or Nix
**Information**
- OS name+version: Void Linux - 5.8.16
- Graphics card and driver: Intel - linux driver
- Desktop environment / Window manager name+version: stumpwm - head
- How you installed Nyxt (Guix pack, package manager, build from source): tried Void Linux's build, and the build from the standalone Guix package manager and the build from the standalone Nix package manager
- Information from command copy-system-information:

```
Nyxt version: 2-pre-release-3 
Operating system kernel: Linux 5.8.16_1
Lisp implementation: SBCL 2.0.9
Features: (WEBKIT2 WEBKIT2-2.30 WEBKIT2-MUTE WEBKIT2-EMOJI WEBKIT2-MEDIA
           WEBKIT2-SANDBOXING GTK-3-22 GTK-3-20 GTK-3-18 GTK-3-16 GTK-3-14
           GTK-3-12 GTK-3-10 GTK-3-8 GTK-3-6 GTK-3-4 GTK GDK-3-22 GDK-3-20
           GDK-3-18 GDK-3-16 GDK-3-14 GDK-3-12 GDK-3-10 GDK-3-8 GDK-3-6 GDK-3-4
           CAIRO-1-10 CAIRO-1-12 GDK-PIXBUF GLIB-2-30 GLIB-2-32 GLIB-2-34
           GLIB-2-36 GLIB-2-38 GLIB-2-40 GLIB-2-42 GLIB-2-44 GLIB-2-46
           GLIB-2-48 GLIB-2-50 GLIB-2-52 GLIB-2-54 GLIB-2-56 GLIB-2-58 GLIB
           FSET-EXT-STRINGS SWANK PLUMP-UTF-32 GLOBAL-VARS DECLARE-TYPES
           PARENSCRIPT SBCL+SAFE-STANDARD-READTABLE NAMED-READTABLES
           OSICAT-FD-STREAMS 21BIT-CHARS CL-FAD CHUNGA FLEXI-STREAMS CLOSER-MOP
           CL-PPCRE-UNICODE CL-UNICODE CL-PPCRE
           CL-JSON-DOUBLE-FLOAT-IS-SUBSUMED CL-JSON-SINGLE-FLOAT-IS-SUBSUMED
           COMPARE-AND-SWAP-VOPS BORDEAUX-THREADS SPLIT-SEQUENCE GRAY-STREAMS
           FLAT-NAMESPACE X86-64 UNIX CFFI FLAT-NAMESPACE SEQUENCE-EMPTYP
           FAST-IO-SV FAST-IO SBCL-USES-SB-ROTATE-BYTE CL-JSON-CLOS CL-JSON
           THREAD-SUPPORT ASDF3.3 ASDF3.2 ASDF3.1 ASDF3 ASDF2 ASDF OS-UNIX
           NON-BASE-CHARS-EXIST-P ASDF-UNICODE X86-64 GENCGC 64-BIT ANSI-CL
           COMMON-LISP ELF IEEE-FLOATING-POINT LINUX LITTLE-ENDIAN
           PACKAGE-LOCAL-NICKNAMES SB-CORE-COMPRESSION SB-LDB SB-PACKAGE-LOCKS
           SB-THREAD SB-UNICODE SBCL UNIX)

```

**Output when started from a shell**
```
Nyxt version 2-pre-release-3
<INFO> [19:10:56] Listening to socket "/home/slade/.local/share/nyxt/nyxt.socket".
Gtk-Message: 19:10:57.344: Failed to load module "canberra-gtk-module"
Gtk-Message: 19:10:57.345: Failed to load module "colorreload-gtk-module"
Gtk-Message: 19:10:58.243: Failed to load module "canberra-gtk-module"
Gtk-Message: 19:10:58.244: Failed to load module "colorreload-gtk-module"
Gtk-Message: 19:10:58.249: Failed to load module "canberra-gtk-module"
Gtk-Message: 19:10:58.250: Failed to load module "colorreload-gtk-module"
Gtk-Message: 19:11:02.468: Failed to load module "canberra-gtk-module"
Gtk-Message: 19:11:02.468: Failed to load module "colorreload-gtk-module"

```

**Comment by Ambrevar** [comment]
Are you using an input method such as xim? 
Can you try without input method?
Also try from a different window manager.

Is this #905 ?

**Comment by C-Entropy** [comment]
Seems that some gtk module is loss. Looks like different with #905 , which I guess cause by Emacs.

**Comment by huguei** [comment]
I confirm this same behaviour with an Ubuntu system, using LXDE as window manager. No warnings or errors from command line. Switching to gnome everything works.

**Comment by Ambrevar** [comment]
@huguei Are you using an input system?  Are you using GNOME on Wayland or X?  How did you install Nyxt, via the .deb, built from source, or with Nix / Guix?

**Comment by huguei** [comment]
No input system. It's LXDE with Openbox, over Xorg. I tried the "All distributions" binary package and the .deb Ubuntu package with the same result.
Thanks.

**Comment by Ambrevar** [comment]
Should be fixed with the new minibuffer (now called prompt buffer). See #1157.

**Comment by huguei** [comment]
Thanks @Ambrevar ! I'll wait the release of next pre-built binary, and report here.

**Comment by C-Entropy** [comment]
Me too!

**Comment by huguei** [comment]
I confirm everything works now, version 2.0.0 Pre-release 6, build tar.xz GNU/Linux, on Ubuntu 20.10.
Thanks a lot!

**Comment by Ambrevar** [comment]
Fantastic, thanks for reporting!
@C-Entropy Feel free to reopen if you encounter any issue.
