### ISSUE TITLE
internal buffer does not use configured binding

### ISSUE THREAD

**Issue by craftyguy** [atlas-engineer/nyxt#1021]
When the key binding is set to something that is not default (e.g. vi bindings), internal buffers continue to use the browser's default bindings. To reproduce:

1) Launch Nyxt with no custom configuration

2) click on the "Common settings" under the "Quick configuration" section of the default page

3) select the "Use vi" for "Keybind style"

4) Restart browser, vi bindings are not used.

Contents of `~/.config/nyxt/auto-config.lisp`:

```
(DEFINE-CONFIGURATION WEB-BUFFER
  ((DEFAULT-MODES
    '(VI-NORMAL-MODE CERTIFICATE-EXCEPTION-MODE WEB-MODE BASE-MODE))))
```

**Information**
- OS name+version: Arch Linux
- Graphics card and driver: AMD (using Mesa 20.2)
- Desktop environment / Window manager name+version: Sway/Wayland
- How you installed Nyxt (Guix pack, package manager, build from source): Arch Linux AUR, `nyxt-browser-git`
- Information from command copy-system-information:
```
Nyxt version: 2-pre-release-3-36-ga44735e2 
Operating system kernel: Linux 5.8.14-zen1-1-zen
Lisp implementation: SBCL 2.0.8
Features: (WEBKIT2 WEBKIT2-2.30 WEBKIT2-MUTE WEBKIT2-EMOJI WEBKIT2-MEDIA
           WEBKIT2-SANDBOXING GTK-3-22 GTK-3-20 GTK-3-18 GTK-3-16 GTK-3-14
           GTK-3-12 GTK-3-10 GTK-3-8 GTK-3-6 GTK-3-4 GTK GDK-3-22 GDK-3-20
           GDK-3-18 GDK-3-16 GDK-3-14 GDK-3-12 GDK-3-10 GDK-3-8 GDK-3-6 GDK-3-4
           CAIRO-1-10 CAIRO-1-12 GDK-PIXBUF GLIB-2-30 GLIB-2-32 GLIB-2-34
           GLIB-2-36 GLIB-2-38 GLIB-2-40 GLIB-2-42 GLIB-2-44 GLIB-2-46
           GLIB-2-48 GLIB-2-50 GLIB-2-52 GLIB-2-54 GLIB-2-56 GLIB-2-58 GLIB
           FSET-EXT-STRINGS SWANK PLUMP-UTF-32 GLOBAL-VARS DECLARE-TYPES
           PARENSCRIPT NAMED-READTABLES OSICAT-FD-STREAMS 21BIT-CHARS CHUNGA
           FLEXI-STREAMS CLOSER-MOP CL-PPCRE-UNICODE CL-UNICODE CL-PPCRE
           COMPARE-AND-SWAP-VOPS BORDEAUX-THREADS SPLIT-SEQUENCE GRAY-STREAMS
           FLAT-NAMESPACE X86-64 UNIX CFFI FLAT-NAMESPACE SEQUENCE-EMPTYP
           FAST-IO-SV FAST-IO SBCL-USES-SB-ROTATE-BYTE ASDF-SYSTEM-CONNECTIONS
           CL-JSON-CLOS CL-JSON THREAD-SUPPORT QUICKLISP ASDF3.3 ASDF3.2
           ASDF3.1 ASDF3 ASDF2 ASDF OS-UNIX NON-BASE-CHARS-EXIST-P ASDF-UNICODE
           X86-64 GENCGC 64-BIT ANSI-CL COMMON-LISP ELF IEEE-FLOATING-POINT
           LINUX LITTLE-ENDIAN PACKAGE-LOCAL-NICKNAMES SB-CORE-COMPRESSION
           SB-LDB SB-PACKAGE-LOCKS SB-THREAD SB-UNICODE SBCL UNIX)
```

**Comment by Ambrevar** [comment]
Thanks for reporting this, indeed this is a bug!
Should be fixed in 56970e12f730ddcd8ba2c3644db8a0d0657d5616.
Let me know if this works for you! :)

**Comment by craftyguy** [comment]
Hmm, no it doesn't seem to work. Now my config contains this after clicking on the 'use vi' button:

```
(DEFINE-CONFIGURATION WEB-BUFFER
  ((DEFAULT-MODES (APPEND '(VI-NORMAL-MODE) %SLOT-DEFAULT))))
```

But when on the help buffer, vi bindings don't work..

**Comment by Ambrevar** [comment]
Oops, forgot to fix the VI button.
Try master again, should work now.

e7e89b70209a4f57d8a4c25e0196337e2d00db7d

**Comment by craftyguy** [comment]
@Ambrevar so now I can use vi bindings on internal buffers, but not on web buffers (i.e., go to default start page, hit ':', nothing comes up)

**Comment by Ambrevar** [comment]
Argh! :p

OK, this time I hope I got all cases right: see 
0bb874590ff97025c6014373e4bcec66f2a8ad57.

**Comment by craftyguy** [comment]
I think you got it this time, thanks for the quick fix!

**Comment by Ambrevar** [comment]
You're welcome, thanks for your patience!
