### ISSUE TITLE
Improve status and CSS customizability

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#1024]
At the moment customizing the CSS of various elements (mostly the status bar) is tedious because the user needs to repeat the existing CSS.

Besides, it's hard to access a CSS property value, e.g. the background color of the status bar.

What we could do is only apply the `cl-css:css` function when creating the GTK objects.  Thus we would store an alist/plist for the current CSS slots.

The status buffer definition would look like this:

```lisp
(define-class status-buffer (user-internal-buffer)
  ((height 20
           :type integer
           :documentation "The height of the status buffer in pixels.")
   (style '((body
             :background "rgb(200, 200, 200)"
             :font-size "14px"
             :color "rgb(32, 32, 32)"
             :padding 0
             :margin 0
             :line-height "20px")
            ;; ...
            (|.button:hover|
             :color "black"))))
  (:export-class-name-p t)
  (:export-accessor-names-p t)
  (:accessor-name-transformer #'class*:name-identity))
```

For instance, to access the background value of a STATUS-BUFFER object, we can write (untested)

```lisp
(getf (rest (assoc 'body (style STATUS-BUFFER))) :background)
```

To access the default value, replace `(style STATUS-BUFFER)` with

```lisp
(getf (mopu:slot-properties 'status-buffer 'style) :initform)
```

Since the status buffer is a user-class, the user can customize the existing CSS this way (untested):

```lisp
(define-configuration status-buffer
  ((style (setf (alex:assoc-value %slot-default ...) new-value))))
```

**Comment by jmercouris** [comment]
One minor correction: they do not need to repeat the CSS, only need to define the delta, CSS cascades and subsequent definitions override previous ones.

**Comment by jmercouris** [comment]
Therefore they can just append to the slot default value in order to see the CSS to whatever they wish, or they can start from scratch.

**Comment by Ambrevar** [comment]
Good point.

That said the drawback with CSS is that the user does not get language
support (at the Lisp level) against symbols for the CSS path.

For instance, if the user overrides "body" with "boyd" (intended typo)
by mistake, the rule won't apply but the user won't get warned.

With `assoc` this would not be a problem.

**Comment by jmercouris** [comment]
Indeed!

**Comment by aadcg** [comment]
I like your idea @Ambrevar.

**Comment by jmercouris** [comment]
I am still not sold on this. I am concerned it may become too complex.

**Comment by aadcg** [comment]
An annoying layer in the back and forth translation between alists and cl-css? It would make more sense to extend cl-css to suit what @Ambrevar is saying perhaps.

**Comment by Ambrevar** [comment]
@jmercouris Why complex?  Instead of writing CSS, you write alists, there is a trivial 1-to-1 mapping and the cl-css:css call is done in only one spot, by Nyxt (the user needs not care about it).

**Comment by jmercouris** [comment]
For example, how about inspecting the value of the slot? Would we know what the CSS compiles to?

**Comment by aadcg** [comment]
> For example, how about inspecting the value of the slot? Would we know
> what the CSS compiles to?

If I understand @ambrevar correctly, once that 1-to-1 mapping is
implemented, it should be a breeze.

**Comment by jmercouris** [comment]
That would not work. The slot value would still be an alist. I believe the best we could do is:

```
(defmethod style ((xyz xyz))
  (cl:css (slot-value xyz 'style)))
```

This would have a lot of downsides though.

**Comment by aadcg** [comment]
> This would have a lot of downsides though.

Indeed.

**Comment by Ambrevar** [comment]
> For example, how about inspecting the value of the slot? Would we know what the CSS compiles to?

Inspecting should get you the alist, because this is what we want.

To know what is compiles to, simply call `cl-css:css` over it.

**Comment by Ambrevar** [comment]
In other words, no need for the accessor.

But going with an accessor could be fine too.

- The slot value gives us Lisp access.
- The accessor value gives us CSS access.

What would be the drawbacks?

**Comment by Ambrevar** [comment]
@aartaka What's the update on this issue now that we have a `theme` library?

**Comment by Ambrevar** [comment]
Alrighty!
