### ISSUE TITLE
Hard to install on MacOS

### ISSUE THREAD

**Issue by lccambiaghi** [atlas-engineer/nyxt#1025]
I really want to try your browser but I don't want to install MacPorts.

I first tried with `brew cask install next` and it installed a very old, unstable, version.

I then tried with `nix` and I could not build, here the error:
```
...
Project name: gst-plugins-bad
Project version: 1.16.2
Using 'CC_FOR_BUILD' from environment with value: 'clang'

meson.build:1:0: ERROR: Compiler clang can not compile programs.
...
```

Of course, I don't really want to compile from source to have a quick try. It would be great if you made the installation easy for new users.

**Comment by jmercouris** [comment]
Thank you for your interest. We do have a .pkg that does work, but it refuses to render pages on the broader network, no idea why, maybe it is a permissions issue :-/. Perhaps we should just post the pkg and see if anyone can figure it out.

**Comment by neerajbadlani** [comment]
+1 . Easier steps highly recommended

**Comment by yonkeltron** [comment]
Just wanted to drop in and say that the ability to install Nyxt via Homebrew would be a huge plus and greatly aid adoption. Hoping I could even help test it out! I would certainly be willing to pair up with someone on writing the formula, actually.

Looking forward to learning more.

Thanks,
+Jonathan

**Comment by MaxCan-Code** [comment]
@yonkeltron If you haven't, see [../issues/577#issuecomment-861159926](../issues/577#issuecomment-861159926) for recent brew developments (from checking [../issues?q=is:open+label:macos+sort:updated-desc](../issues/?q=is:open+label:macos+sort:updated-desc))

**Comment by aadcg** [comment]
See #577 for a discussion on how to pursue macOS support.

Nyxt plans to support macOS in version 4.0.0.
