### ISSUE TITLE
Allow specifying the set of characters used for generating link hints

### ISSUE THREAD

**Issue by craftyguy** [atlas-engineer/nyxt#1028]
This is a feature request to implement a way for users to change the set of characters that Nyxt uses when generating hints on a page (`follow-hint`). I noticed that Nyxt only seems to use two characters, however other browsers with similar features (qutebrowser, luakit) will use anywhere between 1 and 4 (or more?) characters per hint label depending on whether there are enough visible links to warrant it. This would also allow users to specify a shorter set of characters (for accessibility purposes, for example) to use when labels are generated for hints, at the expense of maybe having to type more characters to select the hint they want.

For reference, Luakit (another webkit browser) has a nice system for changing the set of characters used: https://luakit.github.io/docs/modules/select.html

For example I can specify only allowing hints using keys on the home row with:
```
select.label_maker = function (s)
    return s.sort(interleave("asdfg", "hjkl"))
end
```

(please don't kill me for referencing Lua on a project that uses Lisp :smile: )

**Comment by Ambrevar** [comment]
No worries, in many ways Luakit is the sanest browser after Nyxt in terms of extensibility, too bad they chose a suboptimal language ;)

I believe this issue is a duplicate of #527.
If you confirm, would you mind referencing the luakit example over there?

Also, since this is a "good-first-issue", would you be interested in contributing? :)

**Comment by craftyguy** [comment]
Ah sorry, I searched but failed to find that before filing this. I added the info from my comment to that issue.

> Also, since this is a "good-first-issue", would you be interested in contributing? :)

I guess we have different definitions of 'good-first-issue', I'm still stumbling around basic configuration using lisp right now, but maybe one day I'll get to the point where I feel like I might have a chance of implementing this :P

**Comment by Ambrevar** [comment]
clayton craft <notifications@github.com> writes:

> I guess we have different definitions of 'good-first-issue', I'm still stumbling around basic configuration using lisp right now, but maybe one day I'll get to the point where I feel like I might have a chance of implementing this :P

No worries, take your time and don't hesitate to ask if you need help! :)
