### ISSUE TITLE
Support <select> HTML tags with follow-hint

### ISSUE THREAD

**Issue by aartaka** [atlas-engineer/nyxt#1029]
`<select>` elements (i.e. dropdown menus) are not supported by `follow-hint` as of 2ed878cf85e0c68405e6dfc82ee992e12d8d40a2, so one needs mouse to fill these elements in.

Identifying these in `follow-hint` will bring us closer to mouse-less future :star_struck: 

Adding to that, using minibuffer to filter dropdown elements can be a cool feature in terms of Accessibility (if we are ever to focus on that) and convenient interfaces. Imagine: incrementally searching a 200-element dropdown (e.g. list of countries) with minibuffer instead of mouse-scrolling it...

**Comment by Ambrevar** [comment]
Artyom Bologov <notifications@github.com> writes:

> Adding to that, using minibuffer to filter dropdown elements can be a cool feature in terms of Accessibility (if we are ever to focus on that) and convenient interfaces. Imagine: incrementally searching a 200-element dropdown (e.g. list of countries) with minibuffer vs. mouse-scrolling it...

Absolutely!  I remember bringing up this idea about a year ago, not sure
it's in an issue though.

@aartaka: Are you interested in working on this?
Otherwise I'll tag this as "good-first-issue".

**Comment by aartaka** [comment]
Let's mark it as "good-first-issue" for now. This is a good entry point for understanding how our JS-CL interoperation is working (I'll be happy to dig into that someday), but there are higher-priority issues to complete :)

**Comment by aartaka** [comment]
Oh wait, this issue is a duplicate of #218, isn't it?

**Comment by Ambrevar** [comment]
Indeed!  Shall we close this one in favour of #218 then?
Maybe mention `<select>` in the title of #218?

**Comment by aartaka** [comment]
> Indeed! Shall we close this one in favour of #218 then?
> Maybe mention `<select>` in the title of #218?

Yes and yes. Can you please rename #218 then?

**Comment by Ambrevar** [comment]
Done!
