### ISSUE TITLE
GUI customization should allow for child mode creation

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#1032]
See #1031, we need a way to create child modes.

After all, it's almost the exact same thing as `define-configuration` except that we would not redefine the user class but a new class.

**Comment by aartaka** [comment]
#1005 is something that we might need to integrate into this system, as it's deeply related to the idea of mode inheritance.

**Comment by Ambrevar** [comment]
In #1031 I've just pushed a fix to class-star.  Before that defining an inherited mode in nyxt-user would fail.

**Comment by aadcg** [comment]
I believe we're able to define modes that inherits from others. Closing.
