### ISSUE TITLE
Fork quri and add to submodules?

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#1033]
We have at least 2 important issues due to quri: #964 and #974. 

#974 has had a fix in a pull request from July: https://github.com/fukamachi/quri/pull/35
I've asked Quri's author about the status of the project, no answer yet: https://github.com/fukamachi/quri/pull/37#issuecomment-725298209

In the meantime, I suggest we fork Quri and merge the fixes.  Thoughts?  @jmercouris

**Comment by jmercouris** [comment]
That sounds reasonable. I take it Eitaro does not have the time available. He can merge things, or-not, at his own pace.

**Comment by Ambrevar** [comment]
Done: https://github.com/atlas-engineer/nyxt/commit/c850cd2d624e198a7a7ddc8bb6930c02f4cacd12

**Comment by jmercouris** [comment]
It is currently causing problems for our CI and results in a breakage. Could you please check it out?

**Comment by Ambrevar** [comment]
Done.

**Comment by jmercouris** [comment]
Thank you :-)
