### ISSUE TITLE
copy-password fails silently with keepassxc

### ISSUE THREAD

**Issue by DominikM** [atlas-engineer/nyxt#1053]
When using keepassxc as my password manager, running copy-password fails silently.

After a little bit of debugging, it seems to me that the class in password-keepassxc.lisp has two slots that are never initalized, "password-file" and "master-password". When I manually initalize these values in the REPL, copy password works (there are some other small bugs before it works though). Is this expected behavior? Unless I'm missing a step, that would mean that the keepassxc database file and master password would need to be kept in plaintext in init.lisp in order to use the password feature, which isn't something that should be done.

If this isn't expected behavior, I'd be happy to take swing at fixing it, but since I'm new to the project, I wanted to check first. 

As an aside keepassxc can be accessed through libsecret clients. It seems that it may be easier on linux for nyxt to interface through that, as it would prevent the user from having to type in the master password repeatedly or save it in plaintext. I'd be happy to hack on that as well.

System details:
Nyxt version: 2-pre-release-4-94-g20887075 
Operating system kernel: Linux 5.9.1-arch1-1
Lisp implementation: SBCL 2.0.8
Features: (WEBKIT2 WEBKIT2-2.30 WEBKIT2-TRACKING WEBKIT2-MUTE WEBKIT2-EMOJI
           WEBKIT2-MEDIA WEBKIT2-SANDBOXING GTK-3-22 GTK-3-20 GTK-3-18 GTK-3-16
           GTK-3-14 GTK-3-12 GTK-3-10 GTK-3-8 GTK-3-6 GTK-3-4 GTK GDK-3-22
           GDK-3-20 GDK-3-18 GDK-3-16 GDK-3-14 GDK-3-12 GDK-3-10 GDK-3-8
           GDK-3-6 GDK-3-4 CAIRO-1-10 CAIRO-1-12 GDK-PIXBUF GLIB-2-30 GLIB-2-32
           GLIB-2-34 GLIB-2-36 GLIB-2-38 GLIB-2-40 GLIB-2-42 GLIB-2-44
           GLIB-2-46 GLIB-2-48 GLIB-2-50 GLIB-2-52 GLIB-2-54 GLIB-2-56
           GLIB-2-58 GLIB FSET-EXT-STRINGS SWANK PLUMP-UTF-32 GLOBAL-VARS
           DECLARE-TYPES PARENSCRIPT NAMED-READTABLES OSICAT-FD-STREAMS
           21BIT-CHARS CHUNGA FLEXI-STREAMS CLOSER-MOP CL-PPCRE-UNICODE
           CL-UNICODE CL-PPCRE COMPARE-AND-SWAP-VOPS BORDEAUX-THREADS
           SPLIT-SEQUENCE GRAY-STREAMS FLAT-NAMESPACE X86-64 UNIX CFFI
           FLAT-NAMESPACE SEQUENCE-EMPTYP FAST-IO-SV FAST-IO
           SBCL-USES-SB-ROTATE-BYTE ASDF-SYSTEM-CONNECTIONS CL-JSON-CLOS
           CL-JSON THREAD-SUPPORT QUICKLISP ASDF3.3 ASDF3.2 ASDF3.1 ASDF3 ASDF2
           ASDF OS-UNIX NON-BASE-CHARS-EXIST-P ASDF-UNICODE X86-64 GENCGC
           64-BIT ANSI-CL COMMON-LISP ELF IEEE-FLOATING-POINT LINUX
           LITTLE-ENDIAN PACKAGE-LOCAL-NICKNAMES SB-CORE-COMPRESSION SB-LDB
           SB-PACKAGE-LOCKS SB-THREAD SB-UNICODE SBCL UNIX)

**Comment by jmercouris** [comment]
Thank you for the report! What would you expect, to be prompted for the master password, or to set it via some configuration file? I have looked in the source code, and you are right, there is no prompt for the master password. If you could make it so that it prompts you when the master password is missing, that would be a most welcome contribution!

As an aside; you can have encrypted init/configuration files. If you encrypt them with GPG, Nyxt can decrypt them automatically. 

:-)

**Comment by DominikM** [comment]
Ah, the encrypted config files is cool! I didn't know about that. Thanks for the pointer.

As for the failure of copy-password I think a prompt or at the very least a notice that the keepassxc settings haven't be configured correctly would be useful. I had no idea what I needed to do when it was failing.

I can work on that sometime this week!

**Comment by jmercouris** [comment]
Great, I look forward to your pull request :-)

**Comment by Ambrevar** [comment]
Wait, this used to work _and_ to prompt for the KeepassXC master
password.
Maybe something  broke with the synchronous minibuffer.  I'll investigate.

**Comment by Ambrevar** [comment]
I found an old email between @noogie13 and I that mentioned the following
remaining task:

> - Replace `with-password' by a method which is identity by default, and
>   queries the master password for keepassxc.

Turns out this was forgotten...

@DominikM If you are interested, you could tweak `with-password` to prompt the
user for the master password when keepassxc is used.  The result can be stored
in the master-password slot and then everything should work as expected.

Does that make sense?  Let me know if you have any question!

Thanks for reporting the issue!

**Comment by DominikM** [comment]
Sure that sounds good!

**Comment by Ambrevar** [comment]
Is this fixed on master?  @aartaka @DominikM

**Comment by aartaka** [comment]
KeePassXC works, but I experience delays for up to ten seconds after pressing RET on the entry I want to cpy the password of.

**Comment by aartaka** [comment]
Most of things should be fixed. 

libsecret integration is interesting, I'll open another issue about it.
