### ISSUE TITLE
Parenscript functions defined in pflet return wrong values

### ISSUE THREAD

**Issue by kssytsrk** [atlas-engineer/nyxt#1056]
When I define a function that returns any value and call it in `define-parenscript`, it returns normally. Here's an example:
```common-lisp
(define-parenscript %foo ()
  (defun foo ()
    t)
  (foo))

(define-command foo ()
  (echo "~a" (%foo)))
```

This echoes "true" for me. But when I define that same function in pflet, it returns some number instead of the required value:
```common-lisp
(define-command foo-pflet ()
  (pflet ((%foo-pflet ()
                      t))
    (echo "~a" (%foo-pflet))))
```

This echoed 62591 last time I called it, but the number changes every time. After reading the definition of the `pflet` macro, I still don't really understand what those numbers may mean and why they are there. Is it expected that `pflet` works that way, should I just use `define-parenscript` for functions that have to return something?

**Comment by jmercouris** [comment]
The value that it is giving you is a reference to a callback, eventually the Javascript will complete asynchronously and callback the callback with some ID. For now, just don't use Pflet as they aren't yet engineered to handle that use case :-)

They should be able to though, we can give it a try later, or you can too, the macro for Pflet could use some improvement!

**Comment by kssytsrk** [comment]
Oh, I get it now. Okay, for now I'll just use `define-parenscript`, I may look at this after I finish visual-mode.

**Comment by jmercouris** [comment]
The pflet macro has now been enhanced, and it WILL give you the correct value :-)

try:

```
(define-command foo-pflet ()
  (pflet ((%foo-pflet ()
                      (+ 5 5)))
    (echo "~a" (%foo-pflet))))
```
