### ISSUE TITLE
Support view-source URI scheme?

### ISSUE THREAD

**Issue by aartaka** [atlas-engineer/nyxt#1059]
`view-source` is just a simple scheme that shows a source code of the page in the URI path (e.g. `view-source:http://example.org`). It's quite widespread in other browsers and is a convenient way to quickly skim through the markup of the page.

One substantial problem is that this scheme, although registered by IANA, [is vulnerable](https://web.archive.org/web/20070814075238/http://www.milw0rm.com/id.php?id=1007), so it can be dangerous to support it. An alternative can be to implement a `view-source` command that will just show the source for the page in a different, possibly internal, buffer.

More references can be found on [Wikipedia](https://en.wikipedia.org/wiki/View-source_URI_scheme).

WebKit doesn't support this scheme out of the box, so we need to do it ourselves in case we need it.

@jmercouris have said that one can use inspector to view the source of the page, but I don't really want to use a complicated mouse-driven interface -- plaintext buffer sounds better to me :)

**Comment by Ambrevar** [comment]
Sounds good to me!

A naive approach is easy to implement: load the resource e.g. with dex,
then display the string :)

It's naive because it won't show the source of the elements loaded by
Javascript.
To do that, I'm guessing we need to let WebKit load the page, then get
the whole page e.g. using Javascript, and dump the result as a string in
a new buffer.

**Comment by bqv** [comment]
Given there are sites that modify their page AFTER load, perhaps it's better to do so before running any javascript?

**Comment by bqv** [comment]
Maybe it's best to provide both options.

**Comment by Ambrevar** [comment]
Implemented in https://github.com/atlas-engineer/nyxt/commit/69dbf721b39749f518b07899244ab258ecbc5043 ?
@aartaka

**Comment by aartaka** [comment]
Yes, in a sense. I'm hesitating, though: the issue is about URI scheme, while what I've done is a command. 

Adding a scheme is much harder and has much more security caveats -- not worth doing if we have commands to view source (and we do).

I'll close this.

**Comment by jmercouris** [comment]
Agreed with Artyom.
