### ISSUE TITLE
next doesn't contain version numbers on macOS

### ISSUE THREAD

**Issue by core-code** [atlas-engineer/nyxt#1060]
both the CFBundleVersion and CFBundleShortVersionString entries in your Info.plist are missing therefore it is impossible to check the version number in the Finder, and there are problems when multiple versions are installed.

while these 2 entries should be added, the CFBundleGetInfoString entry needs to be removed this has been deprecated for more than 10 years

<img width="347" alt="Screenshot 2020-12-02 at 00 15 29" src="https://user-images.githubusercontent.com/1261954/100808037-b3d52980-3433-11eb-89dc-392cc0b3dfcb.png">

**Comment by jmercouris** [comment]
Thank you for this report! Would you be willing to submit a PR to fix this?

thanks,

-John

**Comment by core-code** [comment]
sorry would be happy to help but i've never seen your build-system before and actually only have 'negative time' available. 

if that build-system can't properly set the Info.plist variables itself i'd recommend just post-processing the generated app before signing/deployment:

`/usr/libexec/PlistBuddy -c "Set :CFBundleVersion $buildVersion next.app/Contents/Info.plist`

**Comment by aadcg** [comment]
Stale.
