### ISSUE TITLE
lfp.h not found                  [Condition of type IOLIB/GROVEL::GROVEL-ERROR

### ISSUE THREAD

**Issue by m4zzz** [atlas-engineer/nyxt#1062]
I am using ubuntu.
I already installed libfixposix.
How should I proceed?
![lfp-h](https://user-images.githubusercontent.com/74712937/101121011-0e79ab80-3615-11eb-8ecc-553557fd29ce.png)

**Comment by m4zzz** [comment]
Do you have any instructions for how to correctly install libfixposix on linux?

**Comment by Ambrevar** [comment]
Looks like you are on a Debian-based system.  You need to install the "-dev" version of libfixposix, should be called `libfixposix-dev`.
