### ISSUE TITLE
Feature request: Support Hypercore/IPFS

### ISSUE THREAD

**Issue by aartaka** [atlas-engineer/nyxt#1064]
Now that [Beaker](https://beakerbrowser.com/) got 1.0 release, it seems that [Hypercore](https://hypercore-protocol.org/) protocol (a decentralized content publishing system with non-erasable hash-checked history) can be a good thing to support in a browser. Given that we're trying to replace Emacs, we can do a good job of creating an environment for decentralized publishing, comparable to Beaker's built-in editor.

However, implementing this protocol and accompanying handlers doesn't sound as a thing to add to Nyxt core. It rather sounds like independent extension on top of what Nyxt provides.

Implementation problem: list of valid schemes is hard-coded in `valid-url-p` and one cannot alter it. An author of the extension for Hypercore will need to add `hyper://` scheme to the valid schemes list, but won't be able to do so. Should we make it global/`*browser*`-based?

**Comment by Ambrevar** [comment]
Beaker is built on top of Electron, so I assume it's leveraging WebEngine for
the rendering.  (I haven't looked more than that, really, so please correct me
if I'm wrong!)

Hypercore looks very cool.  Also very similar to IPFS.  Any idea about the
differences between the two?

I don't have a strong opinion about making this an extension or integrating it
into the core.  Can you expand on why you'd rather keep it out?

About valid-url-p: no problem in moving this to a BROWSER class slot.  Good catch!

**Comment by aartaka** [comment]
> Beaker is built on top of Electron, so I assume it's leveraging WebEngine for
> the rendering. (I haven't looked more than that, really, so please correct me
> if I'm wrong!)

It is using WebEngine, you're right.

> Hypercore looks very cool. Also very similar to IPFS. Any idea about the
> differences between the two?

Hmmmm. I'm not sure -- they look similar conceptually, so it's only an implementation and particular hashing algorithms that differ, probably. 

One thing that I noticed is that IPFS computes the hash of the data, and stores it in a global hash table indexed by this exact hash. Hypercore uses sequential structure that doesn't rely on hashes. So, potentially, IPFS may have difficulties with hash collisions in the future, while Hypercore will not have these. However, I haven't looked that deep into the these, so my reasoning can be flawed.

> I don't have a strong opinion about making this an extension or integrating it
> into the core. Can you expand on why you'd rather keep it out?

There are two strategies for implementing it -- requiring a JS library dependency or writing our own Hypercore client. Whatever strategy we use, it will take some space in the source tree (and possibly introduce optional dependencies!), distracting the potential code reader from the core of Nyxt.

**Comment by jmercouris** [comment]
I believe this should be an extension.

**Comment by defaultxr** [comment]
> One thing that I noticed is that IPFS computes the hash of the data, and stores it in a global hash table indexed by this exact hash. Hypercore uses sequential structure that doesn't rely on hashes. So, potentially, IPFS may have difficulties with hash collisions in the future, while Hypercore will not have these.

IPFS doesn't require just one specific hashing algorithm, it actually uses what's called [multihash](https://multiformats.io/multihash/) which is basically a string that includes the hash algorithm along with the hash itself, so in theory if collisions were a problem with one type of hash, it would just be a matter of using a different type for the item you're trying to refer to.

**Comment by jmercouris** [comment]
Again, probably an extension. :-D
