### ISSUE TITLE
Replace Quicklisp with CLPM?

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#1065]
CLPM is a Common Lisp package manager: https://www.clpm.dev/

It seems that we could use it to fetch pinned dependency versions.  So instead of relying on an external distribution (Quicklisp) which we don't control (and thus may break Nyxt), we could use CLPM both for the setup and the runtime Lisp system management.

**Comment by Ambrevar** [comment]
The issue https://github.com/atlas-engineer/nyxt/issues/1217 emphasizes the urgency to have our own distribution: Quicklisp is a moving target and it makes Nyxt unreproducible.

On the Guix front, everything is fine, but as soon as we leave Guix the build robustness blows up.

**Comment by jmercouris** [comment]
Indeed, hence my original bringing up of CLPM :-)

**Comment by crocket** [comment]
Does CLPM support offline build if dependencies are already present?

Can CLPM rely on dependencies installed by linux distribution package manager?

**Comment by Ambrevar** [comment]
I don't enough about CLPM to give you good answers.

For now, we are going to rely on Git submodules to fix the urgent Quicklisp issues.
https://github.com/atlas-engineer/nyxt/pull/1802

If we get more comfortable with CLPM and it proves to be the right tool, we might switch to it.

**Comment by jmercouris** [comment]
Well, we are no longer using QL :-)

**Comment by Ambrevar** [comment]
But we are not using CLPM yet, so I suggest we reopen this!

**Comment by jmercouris** [comment]
Why do we need CLPM though? I think pinning things the way we've done is probably the most robust, and doesn't require the user to install any other software.

**Comment by Ambrevar** [comment]
In the future, when Nyxt becomes more of a full-featured CL development
environment, having a proper Common Lisp package manager would be good!

**Comment by crocket** [comment]
Can CLPM build nyxt offline? Gentoo Linux builds programs offline. All dependencies should either be specified in gentoo package or exist as a separate gentoo package.

**Comment by Ambrevar** [comment]
I don't know yet, but that's indeed a critical requirement.

**Comment by ohmree** [comment]
The `--local` and maybe the `--no-resolve` flags to `clpm bundle install` might be of interest here.
Note that I'm not at all an experienced clpm user, I just did a super quick search using the cli because I remembered seeing a flag for this.
If it is a direction you're willing to investigate then maybe you could try contacting clpm's maintainer and/or opening issues [on its repo](https://gitlab.common-lisp.net/clpm/clpm).

```
$ clpm bundle install --help
clpm bundle install - Common Lisp Project Manager Bundle Install

USAGE: clpm bundle install [options]

Install a bundle described in a clpmfile.

If no clpmfile.lock file exists, one is created by first syncing all sources in
the clpmfile and using the requirements to resolve a set of project releases
that satisfy them all. All of the releases are then installed locally and the
lock file is written.

If a lock file does exist, all sources are synced and the requirements
re-resolved, but preference is given to installing the releases that already
exist in the lock file.

Options:
  --local               Do not sync remote sources, use only the data located in
                        the local cache
  -y, --yes             Answer yes to all questions
  --no-resolve          Do not attempt to resolve any requirements. Use
                        requirements exactly as given in lock file.
...
```

**Comment by Ambrevar** [comment]
Interesting, thanks for sharing!

@jmercouris Re-opening then if the above arguments convince you?

**Comment by jmercouris** [comment]
I'm not yet convinced, but we shall see.

**Comment by BlueFlo0d** [comment]
My 5 cents: I also see some success from maintaining one's own quicklisp dist. For example, most projects from https://github.com/borodust uses their own quicklisp dist. See https://github.com/borodust.
The tool they use seems to be https://github.com/orivej/quickdist.

IMO the quicklisp dist model looks very suitable for building a self containing Lisp environment, which looks like the direction of Nyxt core. But I don't have a strong preference towards either Quicklisp or a somewhat traditional package manager.

**Comment by Ambrevar** [comment]
I'd rather not use a Quickdist because we would still depend on
Quicklisp:

- it does not support HTTPS;
- it must be installed by the user while many Nyxt users don't have it;
  installing it for them is tricky, we've been there in the past and bit
  the dust :p

**Comment by jmercouris** [comment]
We no longer use QL :-)

**Comment by aartaka** [comment]
But wait, the issue of runtime extension loading is not yet addressed...

**Comment by jmercouris** [comment]
That is not related to this issue. That is a different one!

**Comment by aartaka** [comment]
>That is not related to this issue. That is a different one!

All good then. Which one, out of curiosity?

**Comment by jmercouris** [comment]
Any issue at all, it is not mentioned anywhere in this thread. I am saying we can make an issue or discuss it in another issue. This place here is simply irrelevant.
