### ISSUE TITLE
Command to "Save Page As"

### ISSUE THREAD

**Issue by danrobi11** [atlas-engineer/nyxt#1067]
I havent found any ```Save Page As``` command. Is there any?
Would be nice to be prompted to set PATH /to/save/here
Thank you for Nyxt

**Comment by Ambrevar** [comment]
We have download-url, but it won't save any asset.
While I suppose we could save assets with WebKitGTK, maybe a better
option would be to integrate with Monolith, see #1063.

**Comment by danrobi11** [comment]
Cool, that be nice to save the asset. I'll close this issue.
