### ISSUE TITLE
C-p / print window freezes Nyxt on Pop_OS

### ISSUE THREAD

**Issue by blakeshaw** [atlas-engineer/nyxt#1069]
**Describe the bug**

Hi, just want to give you a quick heads up of a bug i'm experiencing. If I press `C-p`, the print window pops up and it freezes Nyxt, as well as the entire XWindows (xmonad) workspace. I can confirm this happens every time I press C-p

**Precise recipe to reproduce the issue**
`C-p`, at any moment in Nyxt will produce the same result.

**Information**
- OS name+version: Pop!-OS 20.10
- Graphics card and driver: Nvidia GeForce GTX 680MX, proprietary drivers
- Desktop environment / Window manager name+version: XMonad 0.15
- How you installed Nyxt (Guix pack, package manager, build from source): .deb from website, then dpkg (it was not appearing in either Guix or Nix, unfortunately)
- Information from command copy-system-information:
Nyxt version: 2-pre-release-4 
Operating system kernel: Linux 5.8.0-7630-generic
Lisp implementation: SBCL 2.0.10
Features: (WEBKIT2 WEBKIT2-2.28 WEBKIT2-EMOJI WEBKIT2-MEDIA WEBKIT2-SANDBOXING
           GTK-3-22 GTK-3-20 GTK-3-18 GTK-3-16 GTK-3-14 GTK-3-12 GTK-3-10
           GTK-3-8 GTK-3-6 GTK-3-4 GTK GDK-3-22 GDK-3-20 GDK-3-18 GDK-3-16
           GDK-3-14 GDK-3-12 GDK-3-10 GDK-3-8 GDK-3-6 GDK-3-4 CAIRO-1-10
           CAIRO-1-12 GDK-PIXBUF GLIB-2-30 GLIB-2-32 GLIB-2-34 GLIB-2-36
           GLIB-2-38 GLIB-2-40 GLIB-2-42 GLIB-2-44 GLIB-2-46 GLIB-2-48
           GLIB-2-50 GLIB-2-52 GLIB-2-54 GLIB-2-56 GLIB FSET-EXT-STRINGS SWANK
           PLUMP-UTF-32 GLOBAL-VARS DECLARE-TYPES PARENSCRIPT NAMED-READTABLES
           OSICAT-FD-STREAMS 21BIT-CHARS CHUNGA FLEXI-STREAMS CLOSER-MOP
           CL-PPCRE-UNICODE CL-UNICODE COMPARE-AND-SWAP-VOPS BORDEAUX-THREADS
           SPLIT-SEQUENCE GRAY-STREAMS FAST-IO-SV FAST-IO
           SBCL-USES-SB-ROTATE-BYTE ASDF-SYSTEM-CONNECTIONS CL-JSON-CLOS
           CL-JSON THREAD-SUPPORT CL-PPCRE FLAT-NAMESPACE X86-64 UNIX CFFI
           FLAT-NAMESPACE SEQUENCE-EMPTYP QUICKLISP ASDF3.3 ASDF3.2 ASDF3.1
           ASDF3 ASDF2 ASDF OS-UNIX NON-BASE-CHARS-EXIST-P ASDF-UNICODE X86-64
           GENCGC 64-BIT ANSI-CL COMMON-LISP ELF IEEE-FLOATING-POINT LINUX
           LITTLE-ENDIAN PACKAGE-LOCAL-NICKNAMES SB-CORE-COMPRESSION SB-LDB
           SB-PACKAGE-LOCKS SB-THREAD SB-UNICODE SBCL UNIX)

  If you can't run copy-system-information, please provide the following:
  - Nyxt version (from =M-x nyxt-version= or =nyxt --version=): 
  - Lisp implementation/version (if built from source):
  - Kernel name+version:
  - WebKitGTK+ | QtWebEngine version:

**Output when started from a shell**
<INFO> [02:28:19] Listening to socket "/home/proletkultura/.local/share/nyxt/nyxt.socket". -- I can confirm just now that attempting to quit from shell with `^z` also crashed nyxt

**Comment by Ambrevar** [comment]
I believe this is #756.

**Comment by Ambrevar** [comment]
This is fixed with the new gobject-introspection renderer coming soon.  It's on master, you can test it by building `nyxt/gobject/gtk`.
