### ISSUE TITLE
Overiding vim mode maps.

### ISSUE THREAD

**Issue by clonex10100** [atlas-engineer/nyxt#1074]
I use colemak layout for vi with neio for movements. I'm trying to rebind the nyxt vi layer to work with this. It works fine until I enter insert mode, then when I return to normal mode vi-mode's i binding overwrites my i binding and causes it to take me to insert mode instead of scrolling up. I can't find much keybinding documentation so I'd appreciate any advice.

```
(in-package :nyxt-user)

(defvar *colemak* (make-keymap "colemak"))
(define-key *colemak*
  "n" 'nyxt/web-mode:scroll-left
  "e" 'nyxt/web-mode:scroll-down
  "i" 'nyxt/web-mode:scroll-up
  "o" 'nyxt/web-mode:scroll-right
  "h" 'nyxt/vi-mode:vi-insert-mode

  "N" 'nyxt/web-mode:history-backwards
  "L" 'nyxt/web-mode:history-forwards)

(define-mode colemak-mode ()
  "Dummy mode for the custom key bindings in `*colemak*'."
  ((keymap-scheme (keymap:make-scheme
                   scheme:vi-normal *colemak*))))

(define-configuration (buffer web-buffer)
  ((default-modes (append '(colemak-mode vi-normal-mode) %slot-default))))

```

**Comment by Ambrevar** [comment]
Thanks for reporting!

The problem is that "i" brings you to vi-insert-mode, but in this mode
"escape" is bound to vi-normal-mode, and not colemak-mode.

I guess the right fix would be to bind escape to a new command
"quit-vi-insert-mode" which would _just_ call the vi-insert-mode
desctructor, which should bring us back to the previous mode, namely
colemak-mode for you.

Does it seem like a sound design?
Thoughts?

**Comment by aartaka** [comment]
Sorry, let it be open until we come up with a way to define the mode inherited from `vi-normal-mode` now that `vi-insert-mode` can switch back to `vi-normal-mode`-like modes.

I will hopefully come up with a working example of `colemak-mode` inheriting form `vi-normal-mode` by Tuesday (got a loaded weekend (\~_\~;) ). @Ambrevar, if you can come up with it faster then me -- I'll be glad to see it :)

**Comment by Ambrevar** [comment]
With FOSDEM tomorrow, sorry, I won't be your guy :)

**Comment by aartaka** [comment]
No problem :) Good luck there!

**Comment by aartaka** [comment]
@clonex10100, while this is not exactly the same as what you tried to do, and neither it is what Pierre suggested, here's the working piece of configuration that achieves what you need:
``` lisp
(in-package #:nyxt-user)

(define-configuration nyxt/vi-mode:vi-normal-mode
  ((keymap-scheme
    (let ((scheme %slot-default))
      (define-key (gethash scheme:vi-normal scheme)
        "h" 'nyxt/vi-mode:vi-insert-mode
        "n" 'nyxt/web-mode:scroll-left
        "e" 'nyxt/web-mode:scroll-down
        "i" 'nyxt/web-mode:scroll-up
        "o" 'nyxt/web-mode:scroll-right
        "N" 'nyxt/web-mode:history-backwards
        "L" 'nyxt/web-mode:history-forwards)
      scheme))))

(define-configuration web-buffer
  ((default-modes `(vi-normal-mode ,@%slot-default))))
```

The reason for `colemak-mode` dismissal there is that we need to modify `vi-normal-mode` directly to change the `vi-insert-mode` invoking key. I'm still not sure how to define a proper `colemak-vi-mode`, though. Thanks for a new idea to think about!

**Comment by aadcg** [comment]
The user's request has been provided.

**Comment by recallthis** [comment]
This solution to override i/insert seemingly didn't work for me (2025). I get a message that package NYXT/VI-MODE does not exist.

Other than being unable to rebind insert, my vim-keys are working in my regular configuration. 

```
(define-configuration :document-mode  
  "Add basic keybindings."  
  ((keyscheme-map  
    (keymaps:define-keyscheme-map  
     "custom" (list :import %slot-value%)  
     nyxt/keyscheme:vi-normal  
     (list "i" 'scroll-up  #still enters insert mode
           "h" 'vi-insert-mode  
           "k" 'scroll-down  
           "o" 'scroll-page-up  
           "d" 'scroll-page-down)))))
```
