### ISSUE TITLE
Restore session buffers on demand

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#1076]
Follow up to #1072.

Sesson restoration can hang the browser for a few seconds when there are 10-20 buffers or more to restore.
The issue stems from a libsoup bug, which is unlikely to be resolved soon:

https://gitlab.gnome.org/GNOME/libsoup/-/issues/192

I suggest the following: instead of adding the unrestored buffers to the list of `buffers`, add the session
histories to a new `*browser*` slot, say "unrestored buffers". Then with the new minibuffer
multi-source support, we can list these entries alongside the other buffers.  The action of switching to an `unrestored buffer` would first create the buffer, then switch to it.
This would give us clean data separation and not break any of the existing code.

Thoughts?

**Comment by jmercouris** [comment]
I think that the gtk-buffer slot could have a "restored" slot instead of a list of unrestored buffers

**Comment by Ambrevar** [comment]
> I think that the gtk-buffer slot could have a "restored" slot instead of a list of unrestored buffers

What would you but in this "restored" slot?

Note that gtk-buffers' gtk-object is instantiated in the
`initialized-instance` after method, which is our main issue here.  Thus
adding a slot to gtk-buffer cannot fix the problem.

**Comment by jmercouris** [comment]
Right, that is the problem. If you had a `restored` slot, you could take action in intialize instance to either CREATE or NOT create depending on the slot value passed in by make-instance

Therefore there are two cases:

1. initialize-instance decides NOT to make the GTK objects
2. initialize-instances MAKES the GTK objects

which one happens would depend upon the value of that slot.

**Comment by jmercouris** [comment]
You might be wondering, OK, then *when* do we make the GTK objects?

We can create methods for them that when they are accessed, they are created just in time. For example, (gtk-object buffer) will check to see if it has been restored or not. If it is unrestored, make the GTK objects.

**Comment by Ambrevar** [comment]
> Right, that is the problem. If you had a `restored` slot, you could take action in intialize instance to either CREATE or NOT create depending on the slot value passed in by make-instance
>
> Therefore there are two cases:
>
> 1. initialize-instance decides NOT to make the GTK objects
> 2. initialize-instances MAKES the GTK objects
>
> which one happens would depend upon the value of that slot.

OK, I understand what you mean now.

**Comment by Ambrevar** [comment]
> You might be wondering, OK, then *when* do we make the GTK objects?
>
> We can create methods for them that when they are accessed, they are created just in time. For example, (gtk-object buffer) will check to see if it has been restored or not. If it is unrestored, make the GTK objects.

This is my first attempt.  The problem is that modes are instantiated on
buffer creation at the moment, and some modes depend on gtk-object
(e.g. proxy-mode).

Like I said, we could postpone mode creation too, but then we have to
deal with half-complete buffers and I'm not sure we want that.

I like the minibuffer multi-source approach.

**Comment by jmercouris** [comment]
Then modes need to be created on-demand as well.

**Comment by jmercouris** [comment]
What I am not understanding is how this is related to the minibuffer. How are the two connected? Is this required for the minibuffer reimplementation?

**Comment by Ambrevar** [comment]
John Mercouris <notifications@github.com> writes:

> How are the two connected? Is this required for the minibuffer reimplementation?

No, the other way around.  I believe we need the multi-source support
to fix session restoration.

This is connected with the previous work on trying to fix all startup
race conditions.

> What I am not understanding is how this is related to the minibuffer.

Allow me to re-state the context: we are talking session restoration on
10+ buffers with this setting:

```lisp
(define-configuration browser
  ((session-restore-prompt :always-restore)))
```

With the above context, the user will sometimes experience (in my case 1
time out of 3) a huge hang on startup (talking > 3s, sometimes even 10
seconds).

A long time back I had made session restoration lazy in the sense that
web pages would only be loaded when the buffer would be switched to.

While this trick saves bandwidth on startup, it does not fix the hang.
This is because even though the web pages are not loaded, the many GTK
WebViews are still instantiated when the session is restored.

I suggest we change what we mean by "restoring session".  Instead of
making the buffers right away, we only store the history entries
somewhere, and expose this list in an extra source in the
switch-to-buffer minibuffer.

**Comment by jmercouris** [comment]
Ah, I finally understand the context! Hm, maybe... It seems like a task the computer could do for you. It is in my opinion an implementation detail that the user need not be exposed to.

**Comment by aadcg** [comment]
Hmmm, I believe this is quite outdated. Should we keep it open? @jmercouris @Ambrevar.

**Comment by aartaka** [comment]
It's actually completed, because we restore all the history buffers as `:load-url-p nil`, except for the last opened one which is loaded synchronously. I'm closing this, feel free to reopen if I missed some part of discussion.

The only thing that we might have is generating the `gtk-object` on demand too, but that's a low priority and uncertain benefit, I guess.
