### ISSUE TITLE
Nyxt won't display, maybe hangs on Google sign-on page

### ISSUE THREAD

**Issue by dannyob** [atlas-engineer/nyxt#1081]
**Describe the bug**

**Precise recipe to reproduce the issue**

1. Go to https://drive.google.com
2. Click on "Goto Drive".
3. You'll go to https://accounts.google.com/signing/v2/identifier" with some parameters.
4. WHAT SHOULD HAPPEN: A login page, where you can enter your google address etc.
5. WHAT HAPPENS INSTEAD: A blank page. If I resize the window, I can sometimes get it to display the page, but I am unable to enter text into the login.

**Information**
- OS name+version: 
Linux 5.9.0-4-amd64 #1 SMP Debian 5.9.11-1 (2020-11-27) x86_64 GNU/Linux

  guix 6d1160d
    repository URL: https://git.savannah.gnu.org/git/guix.git
    branch: master
    commit: 6d1160db8e16ee0da5b38c5297cf22cd6dd230d6

name: nyxt
version: 2-pre-release-5

- Graphics card and driver:
Intel Corporation UHD Graphics 620 (Whiskey Lake)
i915 driver

- Desktop environment / Window manager name+version:
sway 1.5.1 (wayland)

- How you installed Nyxt (Guix pack, package manager, build from source):
guix package --install

- Information from command copy-system-information:
NYXT::NYXT-INFORMATION: "Nyxt version: 2-pre-release-5 
Operating system kernel: Linux 5.9.0-4-amd64
Lisp implementation: SBCL 2.0.11
Features: (WEBKIT2 WEBKIT2-2.30 WEBKIT2-TRACKING WEBKIT2-MUTE WEBKIT2-EMOJI
           WEBKIT2-MEDIA WEBKIT2-SANDBOXING GTK-3-22 GTK-3-20 GTK-3-18 GTK-3-16
           GTK-3-14 GTK-3-12 GTK-3-10 GTK-3-8 GTK-3-6 GTK-3-4 GTK GDK-3-22
           GDK-3-20 GDK-3-18 GDK-3-16 GDK-3-14 GDK-3-12 GDK-3-10 GDK-3-8
           GDK-3-6 GDK-3-4 CAIRO-1-10 CAIRO-1-12 GDK-PIXBUF GLIB-2-30 GLIB-2-32
           GLIB-2-34 GLIB-2-36 GLIB-2-38 GLIB-2-40 GLIB-2-42 GLIB-2-44
           GLIB-2-46 GLIB-2-48 GLIB-2-50 GLIB-2-52 GLIB-2-54 GLIB-2-56
           GLIB-2-58 GLIB FSET-EXT-STRINGS SWANK PLUMP-UTF-32 GLOBAL-VARS
           DECLARE-TYPES PARENSCRIPT NAMED-READTABLES OSICAT-FD-STREAMS
           21BIT-CHARS CL-FAD CHUNGA FLEXI-STREAMS CLOSER-MOP CL-PPCRE-UNICODE
           CL-UNICODE CL-PPCRE BORDEAUX-THREADS SPLIT-SEQUENCE GRAY-STREAMS
           FLAT-NAMESPACE X86-64 UNIX CFFI FLAT-NAMESPACE SEQUENCE-EMPTYP
           FAST-IO-SV FAST-IO SBCL-USES-SB-ROTATE-BYTE CL-JSON-CLOS CL-JSON
           THREAD-SUPPORT ASDF3.3 ASDF3.2 ASDF3.1 ASDF3 ASDF2 ASDF OS-UNIX
           NON-BASE-CHARS-EXIST-P ASDF-UNICODE X86-64 GENCGC 64-BIT ANSI-CL
           COMMON-LISP ELF IEEE-FLOATING-POINT LINUX LITTLE-ENDIAN
           PACKAGE-LOCAL-NICKNAMES SB-CORE-COMPRESSION SB-LDB SB-PACKAGE-LOCKS
           SB-THREAD SB-UNICODE SBCL UNIX)
" 

  If you can't run copy-system-information, please provide the following:
  - Nyxt version (from =M-x nyxt-version= or =nyxt --version=):
  - Lisp implementation/version (if built from source):
  - Kernel name+version:
  - WebKitGTK+ | QtWebEngine version:

**Output when started from a shell**

**Comment by Ambrevar** [comment]
Can you reproduce with Epiphany (GNOME Web)?

**Comment by dannyob** [comment]
I can, sadly (i.e. it doesn’t work on epiphany either).

**Comment by jmercouris** [comment]
That is most unfortunate, that means it probably will not work on the GTK renderer... please be patient with us while we update our Qt renderer! :-)

**Comment by Ambrevar** [comment]
@dannyob: Can you file a bug to the WebKitGTK project?
See https://webkitgtk.org/: There is a link "File a bug" on the bottom right.

**Comment by dannyob** [comment]
I just tried the flatpak version of the latest Epiphany, and that doesn't have this problem, so I'm thinking it may be a Guix packaging issue. I'll look into it.

**Comment by brown121407** [comment]
I encountered this too. It seems that if I reload the page after it's stuck on https://accounts.google.com/signing/v2/identifier I displays the login form, but the page doesn't look responsive at all. Yet it does function behind the scenes, even though I can't see them.

If I click into the box to write my username, write it and click to go to the next step, then refresh the page, it actually changes into a form asking me to enter the password. That page doesn't seem to work also, but has the same behaviour: click into the box, write your password and press enter or click to login and it will work even though the letters didn't appear in the box.

**Comment by dannyob** [comment]
This works now, on 2-pre-release-6

**Comment by Ambrevar** [comment]
If I'm not mistaken, this is thanks to the latest version of WebKitGTK:

https://webkitgtk.org/2021/02/11/webkitgtk2.30.5-released.html
https://webkitgtk.org/2021/03/18/webkitgtk2.30.6-released.html
