### ISSUE TITLE
Confusion about default new buffer URL

### ISSUE THREAD

**Issue by vallode** [atlas-engineer/nyxt#1083]
**Describe the bug**

The `Quick Configuration` "Default new buffer URL" function seems to do nothing.
I'm sure I might be missing something or there is another better way of setting it but it has be entirely confused currently :) 

**Precise recipe to reproduce the issue**

1. Launch Nyxt
2. `C + space help`
3. Press "Common settings"
4. Press "Set default new buffer URL"
5. Enter any URL
6. URL is not saved/New buffers keep opening the atlas duckduckgo website.

**Information**
- OS name+version: Debian 10 Unstable
- Graphics card and driver: Nvidia 860m with nvidia 450.80.02-2
- Desktop environment / Window manager name+version: i3-gaps
- How you installed Nyxt (Guix pack, package manager, build from source): Ubuntu .deb package
- Information from command copy-system-information:

```
Nyxt version: 2-pre-release-4 
Operating system kernel: Linux 5.9.0-5-amd64
Lisp implementation: SBCL 2.0.10
Features: (WEBKIT2 WEBKIT2-2.28 WEBKIT2-EMOJI WEBKIT2-MEDIA WEBKIT2-SANDBOXING
           GTK-3-22 GTK-3-20 GTK-3-18 GTK-3-16 GTK-3-14 GTK-3-12 GTK-3-10
           GTK-3-8 GTK-3-6 GTK-3-4 GTK GDK-3-22 GDK-3-20 GDK-3-18 GDK-3-16
           GDK-3-14 GDK-3-12 GDK-3-10 GDK-3-8 GDK-3-6 GDK-3-4 CAIRO-1-10
           CAIRO-1-12 GDK-PIXBUF GLIB-2-30 GLIB-2-32 GLIB-2-34 GLIB-2-36
           GLIB-2-38 GLIB-2-40 GLIB-2-42 GLIB-2-44 GLIB-2-46 GLIB-2-48
           GLIB-2-50 GLIB-2-52 GLIB-2-54 GLIB-2-56 GLIB FSET-EXT-STRINGS SWANK
           PLUMP-UTF-32 GLOBAL-VARS DECLARE-TYPES PARENSCRIPT NAMED-READTABLES
           OSICAT-FD-STREAMS 21BIT-CHARS CHUNGA FLEXI-STREAMS CLOSER-MOP
           CL-PPCRE-UNICODE CL-UNICODE COMPARE-AND-SWAP-VOPS BORDEAUX-THREADS
           SPLIT-SEQUENCE GRAY-STREAMS FAST-IO-SV FAST-IO
           SBCL-USES-SB-ROTATE-BYTE ASDF-SYSTEM-CONNECTIONS CL-JSON-CLOS
           CL-JSON THREAD-SUPPORT CL-PPCRE FLAT-NAMESPACE X86-64 UNIX CFFI
           FLAT-NAMESPACE SEQUENCE-EMPTYP QUICKLISP ASDF3.3 ASDF3.2 ASDF3.1
           ASDF3 ASDF2 ASDF OS-UNIX NON-BASE-CHARS-EXIST-P ASDF-UNICODE X86-64
           GENCGC 64-BIT ANSI-CL COMMON-LISP ELF IEEE-FLOATING-POINT LINUX
           LITTLE-ENDIAN PACKAGE-LOCAL-NICKNAMES SB-CORE-COMPRESSION SB-LDB
           SB-PACKAGE-LOCKS SB-THREAD SB-UNICODE SBCL UNIX)
```

**Output when started from a shell**

**Comment by vallode** [comment]
I got it working via the `init.lisp` file, but it does still seem the button on the help screen doesn't work :)

For anyone struggling as well, I added the following into my `/home/me/.config/nyxt/init.lisp` file:

```lisp
;; Sets the default buffer URL
(define-configuration buffer 
  ((default-new-buffer-url "file:///.config/startpage/index.html")))```

**Comment by jmercouris** [comment]
Hi @vallode thank you for the resolution! Can you please post the contents of your auto-config file located at `/home/me/.config/nyxt/auto-config.lisp`?

I would be interested to see if it is malformed or why it isn't being loaded for you!

**Comment by jmercouris** [comment]
I have a hunch about what may have happened. Can you please try clearing your configuration in your init.lisp and trying to set the default new buffer URL, but this time EXACTLY like this:

`"https://www.example.com"`,

notice the quotes, they MUST exist, otherwise you are not supplying a string. I know that our prompt isn't exactly very helpful right now when you enter in a invalid type, and it should probably prompt you until it is of the correct type. I just want to however confirm that is your problem before adding that functionality in.

**Comment by vallode** [comment]
Thanks for the reply @jmercouris.

`auto-config.lisp` contains:
```
(DEFINE-CONFIGURATION (BUFFER WEB-BUFFER)
  ((DEFAULT-MODES %SLOT-DEFAULT)))
(DEFINE-CONFIGURATION (BUFFER WEB-BUFFER)
  ((DEFAULT-MODES %SLOT-DEFAULT)))
(DEFINE-CONFIGURATION BUFFER
  ((CURRENT-ZOOM-RATIO 1)))
(DEFINE-CONFIGURATION BUFFER
  ((CURRENT-ZOOM-RATIO 200)))
(DEFINE-CONFIGURATION BUFFER
  ((CURRENT-ZOOM-RATIO 2)))
(DEFINE-CONFIGURATION BUFFER
  ((CURRENT-ZOOM-RATIO 1)))
```
Looks like your suspicions are absolutely correct, after clearing my `init.lisp` file and going back to the `common settings` page I input _exactly_ `"https://www.example.com"` and it was set in `auto-config.lisp` correctly.

I then tried it for a different website, using quotation marks and it worked.

Would absolutely be helpful to have this mentioned somewhere, sounds great. Thank you for the help :)

**Comment by jmercouris** [comment]
No problem for the help! That is what we are here for :-)

We'll make the setting of input smarter for all input fields! Let's please keep this issue open until then!

**Comment by aadcg** [comment]
If the issue can be reproduced in the latest Nyxt release, please create a new issue.
