### ISSUE TITLE
Feature request: inspect objects in lisp-repl

### ISSUE THREAD

**Issue by aartaka** [atlas-engineer/nyxt#1084]
It'd be cool to have an object inspection ability similar to how SLIME/SLY repl does it -- you have clickable printed representation of the object. Once you click it -- it opens a new window with slots of the object that you can add/delete/modify. We already have all the building blocks for this:
- `describe-class` is a good template for this `describe-object` inspection window.
- `lisp-url` with this `describe-object` function call can be embedded into the output of `lisp-repl`.
- MOP makes it easy to get all the necessary information about object at runtime.
- All the slots can be configurable in the same vein as `configure-slot` does, with `setf` used instead of `define-configuration` to modify the object.

Having this and pretty HTML output makes for a decent Nyxt hacking environment, I think. How does it sound to you?

**Comment by Ambrevar** [comment]
Totally, agreed with all your points!

I'd really like to boost the currently underpowered lisp-repl, it would
make for a fantastic tool, + a great helper for Common Lisp newcomers,
especially for those of us who don't use Emacs.

**Comment by aartaka** [comment]
Done with #2099.
