### ISSUE TITLE
follow-hint visual elements issues

### ISSUE THREAD

**Issue by chama-chomo** [atlas-engineer/nyxt#1085]
**Describe the bug**

So far I've experienced 2 problems with follow-hint (triggered by pressing "f" key)
1. sometimes visual hints are not at the right spot, so it's hard to recognize where they point to
2. for some pages shortcuts are not visible at all

**Precise recipe to reproduce the issue**
1. press "f" on nyxt github page, e.g. "DH" shortcut element pointing to "Issues" is misplaced by quite a lot
![image](https://user-images.githubusercontent.com/34240896/103175774-d4df3d80-486c-11eb-8203-4e047430b798.png)
2. scroll to very bottom and press "f" on zive.cz page, there are no element shortcuts shown at all
![image](https://user-images.githubusercontent.com/34240896/103175870-a3b33d00-486d-11eb-81ff-c48f1729ae36.png)

**Information**
- OS Manjaro (up-to-date)
- Graphics card and driver: Intel HD530
- Desktop environment / Window manager name+version: Gnome 3.38
- How you installed Nyxt (Guix pack, package manager, build from source): AUR, package-manager
- Information from command copy-system-information:
Nyxt version: 2-pre-release-5 
Operating system kernel: Linux 5.8.18-1-MANJARO
Lisp implementation: SBCL 2.0.10
Features: (WEBKIT2 WEBKIT2-2.30 WEBKIT2-TRACKING WEBKIT2-MUTE WEBKIT2-EMOJI
           WEBKIT2-MEDIA WEBKIT2-SANDBOXING GTK-3-22 GTK-3-20 GTK-3-18 GTK-3-16
           GTK-3-14 GTK-3-12 GTK-3-10 GTK-3-8 GTK-3-6 GTK-3-4 GTK GDK-3-22
           GDK-3-20 GDK-3-18 GDK-3-16 GDK-3-14 GDK-3-12 GDK-3-10 GDK-3-8
           GDK-3-6 GDK-3-4 CAIRO-1-10 CAIRO-1-12 GDK-PIXBUF GLIB-2-30 GLIB-2-32
           GLIB-2-34 GLIB-2-36 GLIB-2-38 GLIB-2-40 GLIB-2-42 GLIB-2-44
           GLIB-2-46 GLIB-2-48 GLIB-2-50 GLIB-2-52 GLIB-2-54 GLIB-2-56
           GLIB-2-58 GLIB FSET-EXT-STRINGS SWANK PLUMP-UTF-32 GLOBAL-VARS
           DECLARE-TYPES PARENSCRIPT NAMED-READTABLES OSICAT-FD-STREAMS
           21BIT-CHARS CHUNGA FLEXI-STREAMS CLOSER-MOP CL-PPCRE-UNICODE
           CL-UNICODE CL-PPCRE BORDEAUX-THREADS SPLIT-SEQUENCE GRAY-STREAMS
           FLAT-NAMESPACE X86-64 UNIX CFFI FLAT-NAMESPACE SEQUENCE-EMPTYP
           FAST-IO-SV FAST-IO SBCL-USES-SB-ROTATE-BYTE ASDF-SYSTEM-CONNECTIONS
           CL-JSON-CLOS CL-JSON THREAD-SUPPORT QUICKLISP ASDF3.3 ASDF3.2
           ASDF3.1 ASDF3 ASDF2 ASDF OS-UNIX NON-BASE-CHARS-EXIST-P ASDF-UNICODE
           X86-64 GENCGC 64-BIT ANSI-CL COMMON-LISP ELF IEEE-FLOATING-POINT
           LINUX LITTLE-ENDIAN PACKAGE-LOCAL-NICKNAMES SB-CORE-COMPRESSION
           SB-LDB SB-PACKAGE-LOCKS SB-THREAD SB-UNICODE SBCL UNIX)

**Comment by jmercouris** [comment]
Thank you for the report! The hints are actually exactly in the correct position. The problem is here the percieved target. For example, on GitHub, the exclamation point in the circle is actually part of the issues button (and it has some extra padding as well). We are always 10px above and to the left of the actual link hint.

As per the second website, I have no idea, perhaps they are doing some CSS styling preventing the hints from appearing, I will look into it, thank you!

**Comment by aartaka** [comment]
Second website seems to be zoomed in. Can this be #430?

**Comment by chama-chomo** [comment]
I tested this and it looks it is indeed #430 . I'll close this one.
Duplicate of #430
