### ISSUE TITLE
libraries/class-star: Make define-class anaphoric?

### ISSUE THREAD

**Issue by aartaka** [atlas-engineer/nyxt#1089]
Anaphoric class definitions can save us code lines and bring more power in class definions. One of the use-cases is the issue of resizing `status-buffer` recently brought up on IRC. CSS of `status-buffer` is not dependent on `height` of it, while it ideally should, so that if user redefines height of `status-buffer`, font gets resized too. That's how I imagine definition of `status-buffer` then (`%this-class` is an anaphoric variable referring to the class being defined):

``` lisp
(define-class status-buffer (user-internal-buffer)
  ((height 20
           :type integer
           :documentation "The height of the status buffer in pixels.")
   (style #.(cl-css:css
             `((body
                :background "rgb(200, 200, 200)"
                :font-size ,(str:concat (object-string (- (height %this-class) 6)) "px")
                :color "rgb(32, 32, 32)"
                :padding 0
                :margin 0
                :line-height ,(str:concat (object-string (height %this-class)) "px"))
               (".arrow"
                :width ,(str:concat (object-string (/ (height %this-class) 2)) "px")
                :height ,(str:concat (object-string (height %this-class)) "px"))
               (".arrow-right"
                :clip-path "polygon(0 100%, 100% 50%, 0 0)")
               (".arrow-left"
                :clip-path "polygon(0 50%, 100% 100%, 100% 0)")
               ("#container"
                :display "grid"
                ;; Columns: controls, arrow, url, arrow, tabs, arrow, modes
                :grid-template-columns ,(format nil "115px ~apx 1fr ~apx 2fr ~apx 250px"
                                                (/ (height %this-class) 2)
                                                (/ (height %this-class) 2)
                                                (/ (height %this-class) 2))
                :overflow-y "hidden")
               ;; Other slots...
               ))))
  (:export-class-name-p t)
  (:export-accessor-names-p t)
  (:export-predicate-name-p t)
  (:accessor-name-transformer #'class*:name-identity))
```

Other possible features/applications:
- MOP and slot initform rewriting would be used under the hood.
- If the slot is not present in class declaration, we can look at the slots of parent classes that the defined one inherits.
- Having this, we can set the style of all internal/web buffers through buffer slots and style slots referring to them (e.g. having `background-color`, `foreground-color` slots of buffer referenced  in `style` slot definition of the same class), all in lispy syntax with good type-checking and simple redefinitions. A good step towards Nyxt theming :)
- An alternative, simpler-to-parse syntax of `(%this-class-slot 'height)` can be used instead on `(height %this-class)`. It can be even defined as macro via `macrolet`, probably.

How does it sound to you?

**Comment by Ambrevar** [comment]
Good points, thanks for bringing it up!

I like the use case, but I'm not a big fan of the auto-generated symbol `%this-class`.
What about this workaround instead: add a new `:initializer` slot keyword which is a lambda of one argument, the class instance.

So your example would look like this for the `style` slot:

```lisp
   (style  :initializer (lambda (%this-class)
              #.(cl-css:css
             `((body
                :background "rgb(200, 200, 200)"
                :font-size ,(str:concat (object-string (- (height %this-class) 6)) "px")
                :color "rgb(32, 32, 32)"
                :padding 0
                :margin 0
                :line-height ,(str:concat (object-string (height %this-class)) "px"))
               (".arrow"
                :width ,(str:concat (object-string (/ (height %this-class) 2)) "px")
                :height ,(str:concat (object-string (height %this-class)) "px"))
               (".arrow-right"
                :clip-path "polygon(0 100%, 100% 50%, 0 0)")
               (".arrow-left"
                :clip-path "polygon(0 50%, 100% 100%, 100% 0)")
               ("#container"
                :display "grid"
                ;; Columns: controls, arrow, url, arrow, tabs, arrow, modes
                :grid-template-columns ,(format nil "115px ~apx 1fr ~apx 2fr ~apx 250px"
                                                (/ (height %this-class) 2)
                                                (/ (height %this-class) 2)
                                                (/ (height %this-class) 2))
                :overflow-y "hidden")
               ;; Other slots...
               )))))
```

Thoughts?

**Comment by aartaka** [comment]
Sounds good to me!

**Comment by jmercouris** [comment]
I agree with Pierre's approach. I also think it should just be the class name as in `(lambda (status-buffer) ....`.

**Comment by Ambrevar** [comment]
What do you mean with "just be the class name"?

**Comment by jmercouris** [comment]
instead of using `%this`, a generic name/relic from single dispatch, use `status-buffer` or whatever (depending).

**Comment by Ambrevar** [comment]
To clarify, I just used %this-??? because I was too lazy to change
Artyom's example.

Ultimately, the point of the lambda is that it's up to the caller (the
user) to choose the name of the lambda parameter.  So it can be
`status-buffer`, `buffer`, `foo`, anything you like!

**Comment by jmercouris** [comment]
Of course it can be anything, even `potato`, I am suggesting a convention for us to follow :-D

**Comment by Ambrevar** [comment]
This raises one issue though: in which order to we initialize slots with
this `:initializer`?  Worse: what about cycles?

Example where order matters:

``` common-lisp
(define-class foo ()
 ((name :initializer (lambda (foo) (format nil "foo-~a" (slot-value foo 'age))))
  (age :initializer (lambda (foo) (declare (ignore foo)) 17))))
```

Example with cycle:

``` common-lisp
(define-class foo ()
 ((name :initializer (lambda (foo) (format nil "foo-~a" (slot-value foo 'age))))
  (age :initializer (lambda (foo) (length (slot-value foo 'name))))))
```

In the above examples, the issues are obvious.  But it's less obvious when
inheritance comes into play.

Suggestions:
- Use a default, pre-initializer value.  Might yield results unexpected by the users.
- Error out on cycles.
- Maybe better: use our own `slot-value*` function which would call the
  initializer if the slot hasn't been initialized yet.
  This `slot-value*` function would be in charge of detecting cycles.
  
With all that said, is this feature still worth it?

**Comment by Ambrevar** [comment]
So instead of opening this pandora box, what about adding a
`:constructor` (or `:initializer`) class option?

This would act the same as `initialize-instance :after`, it would just
be a shortcut.

**Comment by jmercouris** [comment]
I guess that would suffice. I wonder why we don't utilize initialize-instance more frequently. Defclass should only be treated as the class definition, not the initialization. I suggest we leverage initialize-instance more.

**Comment by aadcg** [comment]
Are we still pursing this?

**Comment by aartaka** [comment]
As a low priority, maybe. But then, it rather belongs to `nclasses`, so I'll move the issue there.

**Comment by aadcg** [comment]
Thanks!
