### ISSUE TITLE
Auto-mode does not handle restored buffers

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#1095]
Recipe:

- Open a URL for which you have an auto-mode rule.
- Restart the browser.

Result: The buffer has all default modes, the rule is not applied.

The same problem happens with `reopen-last-buffer` and `reopen-buffer`.

Any idea, @aartaka?

**Comment by aartaka** [comment]
Hmmmm. Just checked. In my case it stored a `#<nyxt/reading-line-mode:user-reading-line-mode {1004F57EA3}>` instead of `reading-line-mode` in the rule. Was there a deserialization error in logs in your case? If so, then something's getting wrong with serialization of mode names.

**Comment by aartaka** [comment]
Does b75c6bc solve that for you? I've tested and it seems problem indeed was in serialization.

**Comment by Ambrevar** [comment]
I'll test later (possibly this weekend), working on the FOSDEM
presentation at the moment :)

**Comment by Ambrevar** [comment]
Thanks for looking into it ;)

**Comment by aartaka** [comment]
As discussed with @jmercouris, b75c6bc does not solve the problem -- while everything is serialized fine, there are still mode objects in memory, and auto-mode cannot process these.

**Comment by Ambrevar** [comment]
I can still reproduce... :(

**Comment by Ambrevar** [comment]
And... I can still reproduce! xD

**Comment by Ambrevar** [comment]
Maybe related to #1875.

**Comment by aartaka** [comment]
Done in 0d5ceadf9887b3bb805bb6106d8b44dec0033245.

**Comment by Ambrevar** [comment]
Thanks!
