### ISSUE TITLE
Package for Arch32?

### ISSUE THREAD

**Issue by doolio** [atlas-engineer/nyxt#1096]
So users of distributions such as Parabola which includes packages from Arch and Arch32 can easily enjoy Nyxt. Thanks for your time.

**Comment by Ambrevar** [comment]
Doesn't Parabola support Arch's AUR?

Then wouldn't these 2 packages work for Parabola?

- https://aur.archlinux.org/packages/nyxt/
- https://aur.archlinux.org/packages/nyxt-browser-git/

**Comment by doolio** [comment]
> Doesn't Parabola support Arch's AUR?

Yes, I believe it does but isn't AUR packages just for x86_64? I'm using an i686 machine and so for such platforms Parabola takes packages from the Arch32 project.

**Comment by Ambrevar** [comment]
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=nyxt#n9

Should work on i686 too.  Let us know if you experience any difficulty.

**Comment by doolio** [comment]
The `libfixposix` dependency doesn't seem to exist in the Parabola repositories nor the Arch repositories for that matter. I found it on the AUR and installed it first then proceeded to attempt to install `nyxt` however it failed. I could try again and try to capture the backtrace if that would help. Is that possible with the `makepkg -si` command?

Thanks for your time.

**Comment by Ambrevar** [comment]
Yes, please do :)

**Comment by aadcg** [comment]
Stale.
