### ISSUE TITLE
Renderer switching

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#1105]
Now that we have 2 renderers, we need a user function to easily switch between them.

At the very least, we should be able to

- Start a renderer from the REPL.
- Quit Nyxt, without quitting the REPL.
- Change renderer using a single function call.
- Start Nyxt again.

Even better would be to be able to spawn a new window in a new renderer :)

Also see discussion in https://github.com/atlas-engineer/nyxt/commit/937262ec53bfedd2d1cf645a57af775a01d568b6

**Comment by aadcg** [comment]
Superseded by #2619.
