### ISSUE TITLE
FreeBSD status report

### ISSUE THREAD

**Issue by nayuki-d** [atlas-engineer/nyxt#1111]
I've successfully compiled Nyxt/GTK (master/main branch) with SBCL 2.1.0 on FreeBSD 13-Stable natively and on Linux emulation. All dependencies (except from Cluffer) grabbed from Quicklisp.
You can reproduce the lisp compilation process of the docs just fine.
For make compile instructions, you'll need to use "gmake" instead of "make" and edit Makefile (I've replaced Linux for FreeBSD in line 101).
Sly integration also works.
![screenshot](https://user-images.githubusercontent.com/70187554/106088366-bd220000-611d-11eb-88eb-def020c22abf.png)

**Comment by Ambrevar** [comment]
Excellent!
Thank you so much for your report!
I've updated the Makefile and the documentation to reflect this:
e0846f7900ff4c9a17f7244cad70352122e9ca01

@wahjava Shall we close #800 then?

**Comment by jmercouris** [comment]
This is great! Thank you for figuring this out! Maybe now I will uninstall NixOS and go back to BSD :-D

**Comment by wahjava** [comment]
Thanks for working on it. This works great now for me too on `12.2-RELEASE`
