### ISSUE TITLE
website: broken links in Quick Start section

### ISSUE THREAD

**Issue by AlbertoGP** [atlas-engineer/nyxt#1115]
https://source.atlas.engineer/view/repository/nyxt#getting-started

The links to “developer readme”, “documents/README.org” (same link), and “CHANGELOG.org” do not work:

- https://source.atlas.engineer/view/repository/documents/README.org
- https://source.atlas.engineer/view/repository/documents/CHANGELOG.org

I think the correct links are:

- https://github.com/atlas-engineer/nyxt/blob/master/documents/README.org
- https://github.com/atlas-engineer/nyxt/blob/master/documents/CHANGELOG.org

**Comment by Ambrevar** [comment]
@jmercouris Can you look into this?

**Comment by jmercouris** [comment]
They are broken because they are formatted for github. We do not allow viewing of anything but the README on Source. This is not something we will update.

**Comment by jmercouris** [comment]
That said, thank you @AlbertoGP for calling attention to this! It is unfortunately more or less unfixable.

**Comment by AlbertoGP** [comment]
Ah, all right. I must have gone to the website, then clicked on *Download* → *Download Source* which took me to that page:

> The latest source is available from https://source.atlas.engineer/view/repository/nyxt where you **c**an clone it with Git.

At that point, it’s not obvious that I could have gone back, click on the GitHub mirror and find the *developer readme* there. It looked like a dead end.

**Comment by jmercouris** [comment]
I see, thank you! I will update the links on the website!

**Comment by jmercouris** [comment]
Website links have been updated!
