### ISSUE TITLE
Question: how to discover the minibuffer keybindings?

### ISSUE THREAD

**Issue by franburstall** [atlas-engineer/nyxt#1122]
How do I discover the contents of the minibuffer keymap?

In particular, I want to know what bindings (if any) there are for `mini-buffer-toggle-mark` and similar.

What I have tried:
1. `C-h b`: there is no entry for `mini-buffer-toggle-mark`.
2. `C-h c toggle`: this leads me to the help page for `mini-buffer-toggle-mark` but no bindings are listed.

However, there are bindings present: `M-m` and `M-a` both seem to mark all entries.

If it is relevant, I have emacs-mode enabled for buffer and web-buffer and sly reports that "cua" is the name in the KEYMAP-SCHEME-NAME slot of the current mini-buffer.  (Aside: interrogate the browser state from emacs---this is *so* cool!)

Nyxt version: 2-pre-release-5-109-g30c8b395 
Operating system kernel: Linux 4.19.0-14-amd64
Lisp implementation: SBCL 2.1.1
Features: (SLYNK WEBKIT2 WEBKIT2-2.30 WEBKIT2-TRACKING WEBKIT2-MUTE
           WEBKIT2-EMOJI WEBKIT2-MEDIA WEBKIT2-SANDBOXING GTK-3-22 GTK-3-20
           GTK-3-18 GTK-3-16 GTK-3-14 GTK-3-12 GTK-3-10 GTK-3-8 GTK-3-6 GTK-3-4
           GTK GDK-3-22 GDK-3-20 GDK-3-18 GDK-3-16 GDK-3-14 GDK-3-12 GDK-3-10
           GDK-3-8 GDK-3-6 GDK-3-4 CAIRO-1-10 CAIRO-1-12 GDK-PIXBUF GLIB-2-30
           GLIB-2-32 GLIB-2-34 GLIB-2-36 GLIB-2-38 GLIB-2-40 GLIB-2-42
           GLIB-2-44 GLIB-2-46 GLIB-2-48 GLIB-2-50 GLIB-2-52 GLIB-2-54
           GLIB-2-56 GLIB-2-58 GLIB FSET-EXT-STRINGS SWANK PLUMP-UTF-32
           GLOBAL-VARS DECLARE-TYPES PARENSCRIPT NAMED-READTABLES
           OSICAT-FD-STREAMS 21BIT-CHARS CHUNGA FLEXI-STREAMS CLOSER-MOP
           CL-PPCRE-UNICODE CL-UNICODE CL-PPCRE BORDEAUX-THREADS SPLIT-SEQUENCE
           GRAY-STREAMS FLAT-NAMESPACE X86-64 UNIX CFFI FLAT-NAMESPACE
           SEQUENCE-EMPTYP FAST-IO-SV FAST-IO SBCL-USES-SB-ROTATE-BYTE
           ASDF-SYSTEM-CONNECTIONS CL-JSON-CLOS CL-JSON THREAD-SUPPORT
           QUICKLISP ASDF3.3 ASDF3.2 ASDF3.1 ASDF3 ASDF2 ASDF OS-UNIX
           NON-BASE-CHARS-EXIST-P ASDF-UNICODE X86-64 GENCGC 64-BIT ANSI-CL
           COMMON-LISP ELF IEEE-FLOATING-POINT LINUX LITTLE-ENDIAN
           PACKAGE-LOCAL-NICKNAMES SB-LDB SB-PACKAGE-LOCKS SB-THREAD SB-UNICODE
           SBCL UNIX)

**Comment by Ambrevar** [comment]
Indeed, this is missing and should be implemented as part of #1054.
Let's not forget about it :)

**Comment by Ambrevar** [comment]
Fixed on master: you can now press `C-h b` in the minibuffer (now called `prompt-buffer`) to display all the bindings.
