### ISSUE TITLE
Extremely high memory used inspite of having only 1 tab open

### ISSUE THREAD

**Issue by chahak13** [atlas-engineer/nyxt#1129]
Hi,

I've just started to use nyxt for a couple of days and I've noticed that whenever I start any site, it starts taking up a lot of memory, in spite of not doing anything on the site. For example, having just one tab of reddit opened increased my RAM usage to 5.4GBs and it even hanged up the laptop. 

If it helps, I'm using the AUR build on Arch, version 2.pre.release.5-2. Is there anything that I need to do on my end for this?

PS: I'm really excited to start looking at nyxt for my first-choice browser. Thanks for all the work :)

**Comment by Ambrevar** [comment]
Thanks for your report!
This is certainly not expected, something is wrong at a lower level, probably with WebKitGTK on your system.
(For reference, I have 28 buffers open and Nyxt occupies <700 MiB of resident memory, which seems fair.)

We've had a very similar report in the past, also from someone using the AUR: #347.  Can you have a look at the discussion and see if something helps?

**Comment by chahak13** [comment]
Based on the thread that you linked, I checked a few things, but I'm not sure if that helps:

1. webkit2gtk - 2.30.4-3
2. libwebkit2gtk-4.0.so=37-64
3. nyxt - 2.pre.release.5-2

I'm using BSPWM as my Window Manager, and I haven't run across such an issue with any other program on it. I don't have guix installed right now so I'll take some time tomorrow to check if there's any difference in performance between the guix installation and the AUR installation. Thanks!

**Comment by jmercouris** [comment]
You need not install Guix, you can use the Guix pack as a standalone bundle like a flatpak. It is available here: https://nyxt.atlas.engineer/download

**Comment by chahak13** [comment]
Thanks for that. I downloaded the tarball under the "All distributions", and when I tried to extract it, it showed me an error in extracting the files.

![image](https://user-images.githubusercontent.com/29800965/107143252-0b26d700-695a-11eb-985f-fdfeb8d0aab6.png)

The error comes directly on extracting, so I'm not sure if it is the kernel namespace issue either, since it doesn't even reach that point.

**Comment by chahak13** [comment]
I also looked for nyxt executables in the `usr` folder and fount these two:

1. `gnu/store/2k3mgwaz8rcpzr4aqng72cnyprbjlv06-nyxt-2-pre-release-5R/bin/nyxt`
2. `gnu/store/nxk318smx266b4dz5gbybd4l8pjwgd6q-nyxt-2-pre-release-5/bin/nyxt`

Should I use any of these 2? Are both the same?

**Comment by Ambrevar** [comment]
Only one executable would work.
But actually you should not have to dig this far down, instead you
should start Nyxt from usr/bin/nyxt that got extracted with the archive.

**Comment by Ambrevar** [comment]
Sorry, `usr/local/bin/nyxt`.

In the error you shared above (by the way, please share copy-pasted text
instead of a picture, it's easier for everyone ;p), this file failed to
be extracted.

Can you post the command you've used to extract the archive?

**Comment by chahak13** [comment]
Sorry about the photo, I'll keep that in mind :)

> Only one executable would work.
Yes, as you suggested, only the first executable worked. 

> Can you post the command you've used to extract the archive?
I used `tar xvf nyxt-linux-2-pre-release-5-1-gf1637b47.tar.xz` for extracting the archive (used the v option for verbosity to see what's happening). I did just two things, downloaded the compressed file from the website and then ran the command.

**Comment by Ambrevar** [comment]
I guess I'll have to try this in a virtual machine.

Maybe fixing the memory leaks would fix this as well.

**Comment by Ambrevar** [comment]
See #1114 for the discussion on memory leaks.

**Comment by chahak13** [comment]
Thanks. I did look at that issue before creating this one because of the main difference being that I did not create multiple buffers in the first place. It was just one tab open that seemed to accumulate the memory. I've tried it multiple times with different websites (youtube, reddit, etc) and I faced this issue in all of them. It could be because of the other memory leaks mentioned in #1114 though, but I don't know enough to comment.

Also, do you have any idea why the tar file did not extract the binary in `usr/local/bin/nyxt`?

**Comment by Ambrevar** [comment]
I just tried the following:

- Download
  https://nyxt.atlas.engineer/static/release/nyxt-linux-2-pre-release-5-1-gf1637b47.tar.xz

- Ran `sha256sum nyxt-linux-2-pre-release-5-1-gf1637b47.tar.xz` and got
  `caa9a83abba81c3eced70b454562369917b788ba2e872ceaa99f661399dc3824`.

- Run `tar xvf nyxt-linux-2-pre-release-5-1-gf1637b47.tar.xz`

I got `usr/local/bin/nyxt` in the current directory.

**Comment by chahak13** [comment]
Okay, let me try and do that again. Maybe something went wrong the last time I did it.

**Comment by chahak13** [comment]
Thanks @Ambrevar. I'll look at it over the week and report if there are any anomalies!

**Comment by Ambrevar** [comment]
Thank you!

**Comment by chahak13** [comment]
Hey @Ambrevar 
Sorry for the late response, I got stuck in something. I see that 2.0.0 is already out, so congrats on that!

Anyway, for my case, I installed pre-release 7.3 on Arch (since the AUR has that) and am glad to say that I did not see the memory creep that I saw earlier. Thanks for the work! :)

**Comment by Ambrevar** [comment]
Fantastic, thanks for the feedback!
