### ISSUE TITLE
Implement a REST/SOAP client

### ISSUE THREAD

**Issue by montaropdf** [atlas-engineer/nyxt#1131]
Hi,

Following the presentation at FOSDEM'21, here is my take on a "front-end" for interacting with services over REST and/or soap API.

Take the expression 'front-end" broadly. I am referring to any means, functions, classes, widgets, etc providing a way to interact with an API over HTTP.

I am more thinking about a set of functions and classes for programming some logic and a set of widgets to display the result in a buffer. I would have a practical case at work, where this could fit in.

As a devops/sysadmins, I have to deal with a lot of services provided over HTTP, and I find their webUI annoying. In parallel, they all provide an API over HTTP, so being able to "short-circuit" the UI to get straight to the point and recover only the data I need.

Yet other use cases, are, but not limited to:
- to discover an API of a webservice
- to test a webservice you are developing
- provide a way to help your colleagues be more productive, by providing tools improving their efficiency.

For the first point, I suppose a classic REST client, like we can find in firefox, could be provided as a dedicated mode, but I am not so sure for the 2 other points. I really do need to get used to Nyxt to improve on this idea.

**Comment by Ambrevar** [comment]
@jmercouris What do you think?

**Comment by montaropdf** [comment]
I discover recently that Nyxt offer the possibility to execute javascript code snippets. Would it be possible to create a very primitve REST client just using that Nyxt feature?

If yes, how?

I don't have experience at all with javascript.

**Comment by jmercouris** [comment]
I don't have experience with Javascript either. I'm sorry I haven't yet chimed in on this topic. A short explanation of what I envision would be a clone of restclient for emacs: https://github.com/pashky/restclient.el . I find this tool incredibly useful. I think we could apply many of the ideas here, but improve the rendering of course :-)

**Comment by montaropdf** [comment]
Could be interesting, but for what I know of it, you would need some kind of text editor.

I was thinking about this article, from @Ambrevar,  as a starting point: https://ambrevar.xyz/lisp-repl-shell/index.html

I think, that something like a repl would be well suited for interacting with a REST/SOAP service.

In my experience as a sysadmin/devops, there are are more and more tools and services relying on REST API to allow interaction and administration with them. So a shell/REPL-like approach could make the trick.

**Comment by jmercouris** [comment]
I have no experience as a sys admin. I am only looking at it from the perspective of a programmer who has to integrate with an API. As per we need a 'text editor' yes, yes we do :-)

**Comment by montaropdf** [comment]
I don't think they are very different with regard to interacting/integrating an API. The only difference is the purpose.

As a programmer, we need such tool to understand if the API works according to the doc, and so, is predictable, for the purpose of plugin it into another piece of software, with strict rules and use cases.

As a sysadmin/devops, the goal is to monitor, explore, inspect a system and to modify its state, to ensure it behave correctly and to fix problems. However, we do it interactively, and without (very) strict rules, as we must be sure to be able to collect every data necessary to diagnose a problem and solve it quickly.

When it is 3am, you don't have time to patch a client program and run it through a CI/CD pipeline, just to free up some space on a full disk ;)

You free space, collect any data pertaining to the incident, send it to your team mates for further study and go back to bed ;)

**Comment by pdelfino** [comment]
So, maybe the dream is becoming a reality! We are building a new Nyxt application as a REST Client. Check out [a post about it](https://discourse.atlas.engineer/t/interested-in-being-an-alpha-tester/488).

**Comment by jmercouris** [comment]
I think this is outside of the core scope of Nyxt, but could definitely be an application as we were developing.
