### ISSUE TITLE
Hover option for follow-hint

### ISSUE THREAD

**Issue by g1smo** [atlas-engineer/nyxt#1133]
It would be useful to have a follow-hint that hovers instead of clicking elements; some websites have menus that need to be hovered to click sub-entries.

Additionally (this may belong to a separate issue?), I've noticed that some clickable elements are not hinted. An example is the file/folder list view on nextcloud or the feature list at https://nyxt.atlas.engineer/features

That is, the features cannot be toggled using the keyboard; vimium extension for chromium/firefox properly hints them.

Version: Nyxt version 2-pre-release-5 on debian testing

**Comment by aartaka** [comment]
Yes, we don't (yet!) hint the `<details>` tags. Thanks for reporting!

**Comment by aartaka** [comment]
Regarding hoverable elements, I'm not that sure they are even actionable from keyboard. Does Vimium work with these?

**Comment by ivangrozni** [comment]
Nope, vimium doesn't work with hoverable elements.

**Comment by g1smo** [comment]
Sorry I was a bit unclear in my issue; one thing is hintable details and another hover hinting.
As ivan mentioned, no, vimium does not support it. It's a feature that would be very nice but I haven't seen elsewhere. Not sure how technically feasible it is, either.

**Comment by aartaka** [comment]
Alright, we now hint `<details>` tags and have a hovering action. Closing this.

**Comment by Ambrevar** [comment]
I tried to hover over the "Princing" menu on GitHub top bar and got
this:

The value
  "true"
is not of type
  LIST
   [Condition of type TYPE-ERROR]

Restarts:
 0: [ABORT] abort thread (#<THREAD "Nyxt anonymous thread" RUNNING {100B412333}>)

Backtrace:
 0: ((LAMBDA (NYXT/WEB-MODE::RESULTS) :IN NYXT/WEB-MODE:FOLLOW-HINT) "true")
 1: (NYXT/WEB-MODE:FOLLOW-HINT)
 2: ((LAMBDA NIL :IN NYXT::RUN-ASYNC))
 3: ((LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS))

**Comment by aartaka** [comment]
The error is fixed now (see commits b5e8b0eceb2d565b3838262128e10189e6cad88e and 388423ed83aeae7dca6af689413fb9a3086da918), but the hovering is still unstable. I'll look into it tomorrow.

**Comment by aadcg** [comment]
Is this still an issue @aartaka?

**Comment by aartaka** [comment]
@aadcg, yes, hovering is still not happening for some of the elements. However, I doubt we can do any better there :(

**Comment by aartaka** [comment]
So, it seems that there's no portable way to hover over any element, even the hintable one. Closing this as not planned and removing the action in 29f1fa6689d6558463f63e6cbeec94b6c443ea05.
