### ISSUE TITLE
[FR] Tooltip/menu showing enabled modes on the right-hand side of the modeline

### ISSUE THREAD

**Issue by edgar-vincent** [atlas-engineer/nyxt#1137]
Hello everyone,

I think it would be nice if one could be able to see graphically which modes are enabled in the current buffer, for example by showing a tooltip or contextual menu in the modeline, similarly to what Emacs does.

Thanks a lot for your work!

**Comment by jmercouris** [comment]
Thank you for the idea!

**Comment by Ambrevar** [comment]
The default status view (modeline) already displays the list of enabled modes.

Do you mean that we should be able to see the whole list instead of just the ellipsis when the list of mode is too long?

Side question: Does `FR` stand for "feature request"?

**Comment by Ambrevar** [comment]
Also see #904.

**Comment by jmercouris** [comment]
DONE!
5355f34e

**Comment by jmercouris** [comment]
Yes, @Ambrevar that is what the user said on IRC. Anyways, this should be a feature, and does not conflict with #904, I think they are a good combination together!

**Comment by edgar-vincent** [comment]
> Side question: Does `FR` stand for "feature request"?

@Ambrevar Yes. Sorry if it was unclear; since there's no template for feature requests, I resorted to using this abbreviation.

@jmercouris Gosh, that was quick! Thanks!
