### ISSUE TITLE
Navigating the minibuffer when entries span through multiple lines

### ISSUE THREAD

**Issue by aadcg** [atlas-engineer/nyxt#1143]
Way easier seen than explained so take a look below.

![output](https://user-images.githubusercontent.com/45483512/107609689-c8fadf80-6c50-11eb-9863-96b4b091e61d.gif)

I'm wondering if there are plans to address this in #777.

**Comment by Ambrevar** [comment]
You mean that the selection at the bottom is not visible?  Yeah, that's a long standing bug and it's fixed #1054.

**Comment by aadcg** [comment]
> You mean that the selection at the bottom is not visible? Yeah, that's a long standing bug and it's fixed #1054.

Yes.  Great!

**Comment by Ambrevar** [comment]
I believe this is fixed on master since #1157 has been merged.
