### ISSUE TITLE
Infinite https redirection loop with force-https-mode

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#1150]
The issue mentioned in the title happened to me quite a few times.
Sadly, I forgot to take note of the offending websites.

Has anyone else experience it, and if so, where?

**Comment by edgar-vincent** [comment]
I've had it too. Obviously, I don't remember on which website either, but I'll let you know if it happens again.

**Comment by aartaka** [comment]
How about pinging the website with `dex:get` before altering the url in `force-https-handler`? Dexador errors out if you try to access the HTTP-only website via HTTPS. It takes some time, though... 

Filtering URLs already in history will save lots of time on similar requests.

Creating `auto-mode` rules excluding `force-https-mode` is the intuitive action on error.

**Comment by Ambrevar** [comment]
dex:get on all queries seems overkill and it would dramatically slow
down browsing.

Instead, force-https-mode could hold a new slot, `last-url`, against
which we compare the current URL being hi-jacked.
If it's the same, it means we are probably looping, so we should stop
the load and suggest the user to use auto-mode to disable
force-https-handler, or just disable it for now.

Thoughts?

**Comment by aartaka** [comment]
Yes, that sounds better!

**Comment by Ambrevar** [comment]
I still need an example URL to reproduce this.

Anyone?

**Comment by aartaka** [comment]
lispworks.com!

**Comment by Ambrevar** [comment]
I can reproduce indeed, thanks!

**Comment by Ambrevar** [comment]
Fixed with bb674b9123c4bc2eee8b6856448f2d6903c2fac2.
