### ISSUE TITLE
Remove OSICAT and other dependencies.

### ISSUE THREAD

**Issue by jmercouris** [atlas-engineer/nyxt#1161]
In the interest of removing as many dependencies as possible, I would like to remove OSICAT. Additionally, it would be nice if we could get rid of our dependency on iolib.

**Comment by jmercouris** [comment]
Especially since they are operating system specific.

**Comment by jmercouris** [comment]
usocket as well, if possible, it is only used in one place insofar as I can tell.

**Comment by Ambrevar** [comment]
I don't know how to get rid of usocket and we use it at a very important spot.

Osicat: We could use the darwin trick, seems to work well enough.

Iolib: I dont' think we can remove it without losing the single-instance feature.

**Comment by jmercouris** [comment]
I'll investigate removing Osicat. As per usocket, I'll have to look into it more.

**Comment by jmercouris** [comment]
Well, removing Osicat worked just fine on my system. I'll see what can be done about iloib and usocket (I'll make PRs if they are complex/have trade-offs).

**Comment by jmercouris** [comment]
So far I have come to the conclusion that one would need a 'trivial-get-hosts-by-name` library to replace usocket... which I've not been able to find.

**Comment by Ambrevar** [comment]
> So far I have come to the conclusion that one would need a 'trivial-get-hosts-by-name` library to replace usocket... which I've not been able to find.

Exactly! :p

**Comment by jmercouris** [comment]
There is good news though, please see my PR!

**Comment by jmercouris** [comment]
I removed everything except iolib. That I think we will not be able to so easily remove, so closing this.

**Comment by Ambrevar** [comment]
Osicatis still used by OSPM.  It needs `osicat:read-link` to follow a symlink.
Any idea how to do this without Osicat?

**Comment by jmercouris** [comment]
Hm, perhaps it is enough to probe the file to get the path?

**Comment by Ambrevar** [comment]
Nope, because CL standard functions resolve links recursively, while
here we want to resolve the link only once.
