### ISSUE TITLE
Fix global history tree slow suggestion filter

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#1162]
At the moment `set-url` and friends which use `history-suggestion-filter` take a long time to show the prompt buffer when the history grows big (1000+ items, it's very noticeable on my laptop with 5000+ entries).

There are a few spots where performance could be improved:

1. The history `key` and `test` functions could be tuned.

```lisp
(defun make-history-tree (&optional (buffer (current-buffer)))
  "Return a new global history tree for `history-entry' data."
  (htree:make :key #'url 
              :test #'quri:uri=
              :current-owner-id (id buffer)))
```

2.  Internally, the history tree could use a list to store the entries instead of a hash table.  It's unclear whether this would improve performance, we need to benchmark.

3. The filter could be improved why not getting the data but `htree:entries` instead, scoring these entries then getting the `history-entry`s.

**Comment by Ambrevar** [comment]
I believe I've addressed the biggest bottleneck here: e3dc229fdbb6ca52b5358586ae74a643e97d67e8

**Comment by aartaka** [comment]
>     1. Internally, the history tree could use a list to store the entries instead of a hash table.  It's unclear whether this would improve performance, we need to benchmark.

Vectors/arrays are a valid choice too -- `find`, `remove` etc. work on them, while having faster random access.

**Comment by Ambrevar** [comment]
> Vectors/arrays are a valid choice too -- `find`, `remove` etc. work on them, while having faster random access.

Just tried it: it's much slower than hash tables.

Weird, when I try on a number list, it's super fast, but with history
entries performance collapses.

**Comment by Ambrevar** [comment]
So 2 performance issues have been addressed:

- The scoring is much faster with https://github.com/atlas-engineer/nyxt/commit/e3dc229fdbb6ca52b5358586ae74a643e97d67e8.
- The prompt buffer is now asynchronous.

I'm closing this since the rest is probably not going to cause any slow down.
We can reopen this if someone encounters an issue, for instance on low-end hardware, with slow Lisp compilers (e.g. ECL) or with huge histories (> 100,000 entries).
