### ISSUE TITLE
Remember all buffer positions in history

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#1164]
Currently going backward and forward in history restores the buffer position.
This does not work when we restart the browser, or when we visit another history branch.

The fix is straightforward: store the buffer position in the history entry.

**Comment by jmercouris** [comment]
edited easy -> straightforward :-D

**Comment by Ambrevar** [comment]
https://github.com/atlas-engineer/nyxt/commit/c9398328886031449c6f9d79c9e5b7e8c2524c68
