### ISSUE TITLE
passthrough mode?

### ISSUE THREAD

**Issue by skallinen** [atlas-engineer/nyxt#1167]
is there a simple way to evoke/configure a qutebrowser style passthrough mode where all keystrokes including those with modifiers, with the exception of some mode escape sequence (esc+shift in qutebrowser), are temporarily sent to the web app? ie. C-x, C-q, C-x C-c, M-x, ESC etc

**Comment by jmercouris** [comment]
Please see "application-mode", that should do what you want :-)

**Comment by skallinen** [comment]
perfect,  cheers
