### ISSUE TITLE
Make Nyxt configurable as headless

### ISSUE THREAD

**Issue by aartaka** [atlas-engineer/nyxt#1168]
Headless (GUI-less) browsers are the most reliable way to script the Web-based activity (one use-case is web scraping, as in #1163), so Nyxt can benefit from having a headless option. For this, we just need to not create GUI frames and run in the background, while rendering webpages to the non-displayable WebView.

**Comment by Ambrevar** [comment]
Great idea!

**Comment by Ambrevar** [comment]
On master!
