### ISSUE TITLE
search-buffer fails to return occurrences

### ISSUE THREAD

**Issue by aadcg** [atlas-engineer/nyxt#1169]
Steps to reproduce:

- open [Nyxt's github page](https://github.com/atlas-engineer/nyxt)
- run `search-buffer`
- type "you are " (notice the last whitespace)

As soon as you type the last whitespace the search result vanishes. 

**Edit:** I understand that is due to its corresponding html page.  I wonder tho, why are there two whitespaces between "are" and "looking" if there's a single whitespace in the corresponding `.org` file?

And, more generally, is this an "uphill battle" that makes little sense to try to win?

**Comment by aadcg** [comment]
I also noticed the following:

- open [this page](https://learnxinyminutes.com/docs/html/)
- run `search-buffer`
- type "outdated" 

There's a match comming from a commented out part of the body of the html.

**Comment by Ambrevar** [comment]
I can confirm both bugs! :/

Any taker?

**Comment by aadcg** [comment]
I will take it.

**Comment by jmercouris** [comment]
I will take a look when I can

**Comment by jmercouris** [comment]
OK, looks like Andre beat me :-D

**Comment by aadcg** [comment]
Take a second look at this after #2529.

**Comment by aadcg** [comment]
#2529 will close this.
