### ISSUE TITLE
Guix: Use cl-* inputs and document snippet to build in container

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#1176]
Currently our guix.scm uses sbcl-* inputs.  While it allows for a faster build the first time the Guix SBCL package is updated, it has the drawback that if CL deps are also found in ~/common-lisp, it will break the build process because SBCL will try to rebuild the Guix packages in the store.

But maybe there is no need for cl-* inputs and we could just build in a container, using `guix environment --container...`.

We also need to support the build against another compiler like CCL for testing purposes.

**Comment by aadcg** [comment]
@Ambrevar Beautiful, thank you!

**Comment by Ambrevar** [comment]
You're welcome! :)
