### ISSUE TITLE
Style: Leverage more of Serapeum

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#1185]
Serapeum has lots of cool features and it feels that Nyxt code quality could benefit from it.

I suggest we start using more of the following, in the order of the reference documentation:

## Macro tools

[unsplice](https://github.com/ruricolist/serapeum/blob/master/REFERENCE.md#unsplice-form)

[with-thunnk](https://github.com/ruricolist/serapeum/blob/master/REFERENCE.md#with-thunk-var-rest-args-body-body)

[callf](https://github.com/ruricolist/serapeum/blob/master/REFERENCE.md#callf-function-place-rest-args)

[with-read-only-vars](https://github.com/ruricolist/serapeum/blob/master/REFERENCE.md#with-read-only-vars-rest-vars-body-body)

## Types

[->](https://github.com/ruricolist/serapeum/blob/master/REFERENCE.md#--function-args-values)

[true](https://github.com/ruricolist/serapeum/blob/master/REFERENCE.md#true-x)

## Defining Types

[defunit](https://github.com/ruricolist/serapeum/blob/master/REFERENCE.md#defunit-name-optional-docstring)

[defunion](https://github.com/ruricolist/serapeum/blob/master/REFERENCE.md#defunion-union-body-variants)

## Binding

[lret](https://github.com/ruricolist/serapeum/blob/master/REFERENCE.md#lret-rest-bindings-body-body)

[receive](https://github.com/ruricolist/serapeum/blob/master/REFERENCE.md#receive-formals-expr-body-body) (Safer.)

[mvlet](https://github.com/ruricolist/serapeum/blob/master/REFERENCE.md#mvlet-rest-bindings-body-body)
(Less verbose.)

## Control Flow

[nor](https://github.com/ruricolist/serapeum/blob/master/REFERENCE.md#nor-rest-forms)

[eif](https://github.com/ruricolist/serapeum/blob/master/REFERENCE.md#eif-test-then-optional-else-nil-else)
(Replace all `if`s?)

[ensure](https://github.com/ruricolist/serapeum/blob/master/REFERENCE.md#ensure-place-body-newval)

[~>](https://github.com/ruricolist/serapeum/blob/master/REFERENCE.md#-needle-rest-holes)

[nest](https://github.com/ruricolist/serapeum/blob/master/REFERENCE.md#nest-rest-things)
(Reduce indentation.)

[eq*](https://github.com/ruricolist/serapeum/blob/master/REFERENCE.md#eq-rest-xs)

## Threads

[synchronized](https://github.com/ruricolist/serapeum/blob/master/REFERENCE.md#synchronized-optional-object-nil-objectp-body-body)
(This one seems particularly useful for us, like in data-storage.lisp and maybe
the prompt buffer.)

[monitor](https://github.com/ruricolist/serapeum/blob/master/REFERENCE.md#monitor-object)

## Iter

[collecting](https://github.com/ruricolist/serapeum/blob/master/REFERENCE.md#collecting-body-body)

## Conditions

[ignoring](https://github.com/ruricolist/serapeum/blob/master/REFERENCE.md#ignoring-type-body-body)
(Replace all `ignore-errors` and some `handler-case`?)

## Op

[op](https://github.com/ruricolist/serapeum/blob/master/REFERENCE.md#op)
(Nice shorthand for all the trivial lambdas that we have.)

## Functions

[eqs](https://github.com/ruricolist/serapeum/blob/master/REFERENCE.md#eqs-x)

[partial](https://github.com/ruricolist/serapeum/blob/master/REFERENCE.md#partial-fn-rest-args)
(Replace all `alex:curry`s?)

[flip](https://github.com/ruricolist/serapeum/blob/master/REFERENCE.md#flip-f)

[throttle](https://github.com/ruricolist/serapeum/blob/master/REFERENCE.md#throttle-fn-wait-key-synchronized-memoized)
(May be useful for some of our threading stuff, like delayed serialization or downloads.)

[once](https://github.com/ruricolist/serapeum/blob/master/REFERENCE.md#once-fn)

## Trees

[walk-tree](https://github.com/ruricolist/serapeum/blob/master/REFERENCE.md#walk-tree-fun-tree-key-tag-traversal)
(For the GHT?)

## Hash Tables

[dict](https://github.com/ruricolist/serapeum/blob/master/REFERENCE.md#dict-rest-keys-and-values)
[@](https://github.com/ruricolist/serapeum/blob/master/REFERENCE.md#-table-rest-keys)
(So much nicer to read than `make-hash-table` and `gethash`!)

[maphash-return](https://github.com/ruricolist/serapeum/blob/master/REFERENCE.md#maphash-return-fn-hash-table)

[merge-tables](https://github.com/ruricolist/serapeum/blob/master/REFERENCE.md#merge-tables-rest-tables)

## Box

[box](https://github.com/ruricolist/serapeum/blob/master/REFERENCE.md#box)
(We sometimes box values, but maybe always with additional data.  Investigate.)

## CLOS

[make](https://github.com/ruricolist/serapeum/blob/master/REFERENCE.md#make-class-rest-initargs-key-allow-other-keys)
(Seems that Eldoc cannot show the initargs though, can we fix this?)

[class-name-of](https://github.com/ruricolist/serapeum/blob/master/REFERENCE.md#class-name-of-x)
(Oh, this could replace many instances of `(class-name (class-of ...))`.)

## Packages

[package-exports](https://github.com/ruricolist/serapeum/blob/master/REFERENCE.md#package-exports-optional-package)
(Replace the manual symbol listing we are doing.)

## Lists

[filter-map](https://github.com/ruricolist/serapeum/blob/master/REFERENCE.md#filter-map-fn-list-rest-lists)
(Replace our `(delete nil...)`.)

[in](https://github.com/ruricolist/serapeum/blob/master/REFERENCE.md#in-x-rest-items)
(Replace most `(find ... :test #'equal)` and `(member ... :test #'equal)`.)

[pop-assoc](https://github.com/ruricolist/serapeum/blob/master/REFERENCE.md#pop-assoc-key-alist-rest-args)
(I believe we have a few occurrences of this.)

## Sequences

[filter](https://github.com/ruricolist/serapeum/blob/master/REFERENCE.md#filter-pred-seq-rest-args-key-count-allow-other-keys)
[keep](https://github.com/ruricolist/serapeum/blob/master/REFERENCE.md#keep-item-seq-rest-args-key-test-from-end-key-count-allow-other-keys)
(Replace some `remove-if-not` or `(remove-if (complement ...) ...)`.)

[single](https://github.com/ruricolist/serapeum/blob/master/REFERENCE.md#single-seq)
(Replace our `(= 1 (length ...))`.)

[slice](https://github.com/ruricolist/serapeum/blob/master/REFERENCE.md#slice-seq-start-optional-end)
(Replace our `subseq` that rely on the sequence length to count from the end.)

[take](https://github.com/ruricolist/serapeum/blob/master/REFERENCE.md#take-n-seq)
[drop](https://github.com/ruricolist/serapeum/blob/master/REFERENCE.md#drop-n-seq)
(And so on.  Replace some of our `subseq`.)

[seq=](https://github.com/ruricolist/serapeum/blob/master/REFERENCE.md#seq-rest-xs)
(Deep sequence comparison.)

## Strings

[blankp](https://github.com/ruricolist/serapeum/blob/master/REFERENCE.md#blankp-seq)

[words](https://github.com/ruricolist/serapeum/blob/master/REFERENCE.md#words-string-key-start-end)
[tokens](https://github.com/ruricolist/serapeum/blob/master/REFERENCE.md#tokens-string-key-start-end)
[lines](https://github.com/ruricolist/serapeum/blob/master/REFERENCE.md#lines-string-key-eol-style-honor-crlf-keep-eols-count)
(Replace some of our `str:split " " ...` and `str:split (string #\newline) ...`.)

[fmt](https://github.com/ruricolist/serapeum/blob/master/REFERENCE.md#fmt-control-string-rest-args)
(Replace our `(format nil ...)`.)

[ellipsize](https://github.com/ruricolist/serapeum/blob/master/REFERENCE.md#ellipsize-string-n-key-ellipsis)
(Replace our manual ellipsis formatting.)

## Internal Definitions

[local](https://github.com/ruricolist/serapeum/blob/master/REFERENCE.md#local-body-body)
(Replace some of our deeply nested `flet` and `labels`.)

**Comment by Ambrevar** [comment]
Thoughts about this?  I'd like to start using / converting some of these.

I'd get started with `lines`, `words`, `fmt`, `in`, `blankp`.
`class-name-of` is mostly useful when imported, that is, without package prefix.

Thoughts?

**Comment by jmercouris** [comment]
I prefer to use standard CL whenever possible. I think converting to these constructs does not provide significant improvement to the codebase. For example, I would use `(format )` whenever possible instead of `str:join`.

Of course if you find places in the code where you think these are better, no problem :-D.

**Comment by Ambrevar** [comment]
In some cases, Serapeum can replace other libraries, for instance
`words` replace `(str:split " " ...)`.

`format` is not really equivalent to `str:join`, in particular is
_renders_ objects, which can be undesirable (plus there is a performance
penalty).
The CL alternative to `str:join` is `concatenate 'string` which is very
verbose :p

**Comment by jmercouris** [comment]
You can take a list of strings and join them with format. Format can definitely replicate the behavior of str:join :-D. I'm not saying it will be obvious or readable, but it is possible!

**Comment by Ambrevar** [comment]
I'd like to replace all the verbose `(declaim (ftype ...))` with Serapeum's shorter and more natural equivalent.

Compare:

```lisp
(declaim (ftype (function (&key (:id string) (:current-is-last-p boolean)))
                switch-buffer))
```

with

```
(-> switch-buffer (&key (:id string) (:current-is-last-p boolean)) t)
```

Cool?  @jmercouris @aartaka

**Comment by jmercouris** [comment]
That's fine with me, I was never a fan of the function type declarations anyway :-D

**Comment by aartaka** [comment]
Cool!

**Comment by Ambrevar** [comment]
See https://github.com/atlas-engineer/nyxt/pull/1669.

**Comment by jmercouris** [comment]
Lots of good ideas in here. However, it should come up naturally as we refactor. There is no reason to force all of the code to use serapeum style everywhere.

**Comment by jmercouris** [comment]
In other words, we should use the best function for the job, whenever we see a place something can be replaced, lets do it, but I don't think we need an issue for it.
