### ISSUE TITLE
Enable (read-only) bookmarks in nosave-mode?  History?

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#1187]
Thoughts? @aartaka?

**Comment by aartaka** [comment]
I don't see any particular reason for why not. It's convenient and it's what user means in most cases (case of computer sharing is an exception, but one can rebind data paths at startup for that).

Removing the nil-returning `restore` specific to the `nosave-data-profile` should do the job.

**Comment by Ambrevar** [comment]
Wanna send a patch?
Don't hesitate to let me know if you don't have the time ;)

**Comment by aartaka** [comment]
Done in dd3199f2. It did actually require only one method removal :D

**Comment by Ambrevar** [comment]
That makes perfect sense.  This is the kind of commits that hint at great design decisions behind the data-storage library :)
Thanks for the patch!
