### ISSUE TITLE
Allow on-the-fly command definition (like hook handlers)

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#1192]
Commands are very much like hook handlers (from the Serapeum library).

We don't want to allow users to bind keys / prompt buffer actions to lambdas or function objects, because:

- Lambdas are unnamed blackboxes and are hard to manipulated (e.g. can't really list them with meaningful names).
- When a function is updated, the bound function object still refers to the old function.

But hook handlers don't suffer from this problem since they can wrap around lambdas which can use function _symbols_ + they always have a name.

So I suggest we update our `command` API this way:

- Rename `sym` to `fn` for consistency with handlers.
  Allow both lambdas and symbols there.
- Add a `name` slot.
- Add a `make-command` macro which would be just like `define-command` except that it would not define a top-level `defun`.

**Comment by Ambrevar** [comment]
It would also be convenient to have funcallable commands.
We can use this opportunity to do it.

See
https://www.gnu.org/software/clisp/impnotes/mop-slot-access.html#mop-sa-funcallable
for an example.

**Comment by aadcg** [comment]
@Ambrevar I'm trying to follow you, but could you help understand what do you mean by:

> Commands are very much like hook handlers (from the Serapeum library).

Could you point me somewhere to understand this connection?

**Comment by Ambrevar** [comment]
https://github.com/ruricolist/serapeum/blob/master/contrib/hooks.lisp

A command is a wrapper around a function.  So is a hook handler.  Does
that make more sense?

**Comment by aadcg** [comment]
I see. Seems like a good idea.
