### ISSUE TITLE
Mode togglers should be optional

### ISSUE THREAD

**Issue by aadcg** [atlas-engineer/nyxt#1198]
The `define-mode` macro defines a command matching the name of the mode,
so that users can toggle it interactively in the current buffer.

While that makes sense for most modes, it doesn't for `diff-mode`, or
other future modes such as `occur-mode` (the reader can infer its
behaviour).

These are modes that are active in newly created buffers.  Its
corresponding toggler is useless in arbitrary buffers, in particular
within the buffer it spawned.  The function associated with the command,
however, is very useful.  It provides a programmatic (as opposed to
interactive) way to enable the mode in a buffer that can be specified as
a keyword argument.

I think there should be an extra slot for modes, say `toggler` that
would be set to `t` by default.  In those cases, the command should be
defined, otherwise a function suffices.

**Comment by Ambrevar** [comment]
While we are at it, we could add a `toggler` slot to root-mode that would point to the toggler command.

This would allow us to get rid of the `mode-command` juggling and all its helper functions.

**Comment by Ambrevar** [comment]
`make-mode` and `mode-list` need to be overhauled to work without public toggler.

**Comment by aadcg** [comment]
What's the status here? Have you started any draft @Ambrevar? I could give it a try.

**Comment by Ambrevar** [comment]
Not started yet.
I want to finish the prompt-buffer first, and this is going to take a
week at least.

If you want to give this a shot, you're more than welcome! :)

**Comment by aadcg** [comment]
I get the feeling that working on this would help me understanding lots of things.

**Comment by Ambrevar** [comment]
Indeed, modes are quite central to Nyxt! :)

**Comment by aadcg** [comment]
> I suggest we add a class option to define-mode, something like :define-toggler-p.

I've been thinking about this and I have the following idea. The toggler is always needed. In fact, I even think that `root-mode` should have a toggler! This way you could have hooks handlers that run for all modes. 

The only detail that is annoying is that the toggler uses the `define-command` macro, which always exports its `name`.  What about tweaking that? When omitted, the `name` would be exported.

@jmercouris  @Ambrevar

**Comment by jmercouris** [comment]
Seems a reasonable solution.

**Comment by aadcg** [comment]
I couldn't find a way to achieve this without messing with the current syntax of `define-command`, which is a no-go.

I had another idea, which was to simply add `(unexport 'diff-mode (symbol-package 'diff-mode))` to packages where the export of the toggler is undesired. But it doesn't seem to work. Any idea why?

**Comment by jmercouris** [comment]
In a REPL when you unexport, does it work?

**Comment by aadcg** [comment]
On second thoughts, the issue isn't that the symbol is exported. But rather, that the command gets added to `*command-list*`. So a `foo-mode` could so this very hacky thing to remove the generated command.

Perhaps the right thing to do would be to define either a `define-command` or a `defun` in the `define-mode` macro. Will keep thinking.

**Comment by Ambrevar** [comment]
> Perhaps the right thing to do would be to define either a `define-command` or a `defun` in the `define-mode` macro. Will keep thinking.

Yes, seems right to me.

**Comment by aadcg** [comment]
Another issue is the fact that `get-commands` only lists commands for the active modes of the current buffer.  This is why `diff-mode` was written with `(in-package :nyxt/diff-mode)`, instead of `(in-package :nyxt)`.

**Comment by Ambrevar** [comment]
Why is this an issue?

**Comment by aadcg** [comment]
It's an issue in the sense that it breaks the symmetry with other modes.

**Comment by Ambrevar** [comment]
Most modes are defined in their own package.

Exceptions include `download-mode`, but these are wrong and should be fixed.

**Comment by Ambrevar** [comment]
Done with #2200.
