### ISSUE TITLE
Test startup

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#1199]
Our startup test suite is very limited for now.
It's critical and it's broken many times in the past, and I expect it will break again.

We need to test the combination of the following.

- nosave data profile
- dev data profile
- init.lisp errors
- no socket
- custom socket
- multi instance
- remote execution
- remote URL query
- default package
- REPL startup
- binary startup

If I forgot something, please mention it! :)

**Comment by aadcg** [comment]
A shy draft was started at #2718.

This is indeed a high priority.

**Comment by aadcg** [comment]
Closing since this is a duplicate of #2710.
