### ISSUE TITLE
Clicking on links while the minibuffer is active

### ISSUE THREAD

**Issue by aadcg** [atlas-engineer/nyxt#1203]
- run `execute-command`
- click any link in the current web buffer

It seems reasonable to me that this should work. Thoughts?

**Comment by Ambrevar** [comment]
It's tricky, because some minibuffers expect the current page to remain
what it is, such as the hinting commands.

It's simpler to forbid clicking while the minibuffer is up, but if we
can come up with a better behaviour I'm all ears! :)

**Comment by aadcg** [comment]
I see. I wasn't suggesting that minibuffers should enable the user to get back to it later (like it is in the case in Emacs). I was wondering if some events could lead to the "destruction" of the minibuffer.

Actually I'm a bit confused now because I've binded `C-g` to `nyxt/web-mode:remove-search-hints` and I use this all the time to get out of the minibuffer. In general, what's the "proper" way? Say I run `search-buffer` but then I just want to leave it (well, hitting `RET` does it in this case, but you get my question).

**Comment by Ambrevar** [comment]
> I see. I wasn't suggesting that minibuffers should enable the user to get back to it later (like it is in the case in Emacs). I was wondering if some events could lead to the "destruction" of the minibuffer.

Yup, calling `noop` or pressing `esc` while in the minibuffer destroys it.

> Actually I'm a bit confused now because I've binded `C-g` to `nyxt/web-mode:remove-search-hints` and I use this all the time to get out of the minibuffer. In general, what's the "proper" way? Say I run `search-buffer` but then I just want to leave it (well, hitting `RET` does it in this case, but you get my question).

C-g is bound to `noop` by default and should do just that, no?

**Comment by aadcg** [comment]
Right. I remember now.  I use that hack so that `noop` gets rid of the minibuffer and of those highlighted selections.

Can't say much about the issue for now.  Will think about this.

**Comment by Ambrevar** [comment]
The new prompt-buffer allows clicking in the web buffer.

So, should we forbid it or not?

We can if we intercept mouse buttons.
Maybe we should make this a prompt-buffer option so that users can eventually decide whether they want their prompt buffer to force focus or not.

Thoughts?

**Comment by jmercouris** [comment]
I would say that the user should be allowed to click in the web buffer while the prompt-buffer is open.

**Comment by Ambrevar** [comment]
Most of the times, yes, but what about prompt buffers like
`search-buffer` and `follow-hint`?

**Comment by jmercouris** [comment]
Well, in that case, the user has made those commands pointless. The same could be said for many other things though. For example, the user invokes `delete-windows` and then uses their mouse to click `x` on every window. Now what? There are a bunch of no longer valid entries within the prompt buffer!

**Comment by aadcg** [comment]
Doing what I've described in the top post is now possible.

The only thing missing is a keybinding to switch focus between the prompt buffer and other buffer, which I have drafted in #2774.
