### ISSUE TITLE
Style: Replace (string #\newline) by +newline+ constant

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#1207]
We are using (string #\newline) too many times, which is unfortunately verbose.
OK with introducing a `+newline+` defconstant?

**Comment by jmercouris** [comment]
I prefer something verbose to adding another global. I think (string #\newline) is immediately clear. If you need it many times within a function, perhaps let bind?

**Comment by Ambrevar** [comment]
Global constants are fine since they are immutable.
What do you think?

**Comment by jmercouris** [comment]
I didn't notice you said defconstant, good point!

**Comment by Ambrevar** [comment]
So OK with this change?

**Comment by jmercouris** [comment]
OK!

**Comment by Ambrevar** [comment]
Fixed with 252cdeeb2acc093d54d0f649c94d70f5609f8acb.
