### ISSUE TITLE
Rename `paste-from-ring` to `paste-from-clipboard`

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#1209]
For consistency.  I also suggest we rename `clipboard-ring` to `clipboard`.  It already has the `ring` type.

**Comment by jmercouris** [comment]
I like the ring actually, clipboards are typically NOT rings. Therefore I prefer the specificity.

**Comment by Ambrevar** [comment]
`paste-from-ring` is very unfamiliar to newcomers.

So what about `paste-from-clipboard-ring` instead?

I still like `clipboard` better, the user can inspect the documentation
and directly see that it's a ring.

**Comment by jmercouris** [comment]
I think the alternative you've presented is a good compromise! `paste-from-clipboard-ring`.

**Comment by Ambrevar** [comment]
Fixed with f566fa895abfc16d59d416ae3915684feda5b79a.
