### ISSUE TITLE
prompt-buffer: urgent fixes

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#1212]
1. [x] `switch-buffer` loses focus because `follow-mode` is on.
    We need to maintain focus on the input when following buffer.

2. [x] The `bookmark-url` related commands should pre-mark the tags of existing bookmarks (easy).

3. (Not actually urgent) Element-hinting functions need a custom filter to match against the hints.

4. [x] Re-introduce tab-insert, especially for `set-url`.

**Comment by Ambrevar** [comment]
@jmercouris Indeed, I cannot reproduce "3".  I think the issue occurs when a title has the same word as a hint, e.g. `at`.  The `hint-source` does not take any provision to match hint first, so I guess there is still an issue, but it's no longer urgent since it works most of the time.

**Comment by jmercouris** [comment]
I would say that is a likely explanation, yes.

**Comment by Ambrevar** [comment]
I've fixed the missing tab-insert.

For bookmark pre-marks, I've implemented it but it seems to work only rarely.
Any idea why?

**Comment by jmercouris** [comment]
What are bookmark "pre-marks"?

**Comment by jmercouris** [comment]
Do you mean pre-marked tags within the prompt buffer? Are they marked by not rendering as marked? Could it be that we need to run an update-display event after some processing?

**Comment by Ambrevar** [comment]
> Do you mean pre-marked tags within the prompt buffer?

Yes.

> Are they marked by not rendering as marked? Could it be that we need to run an update-display event after some processing?

I don't think that's the problem, because upon inspecting I see
that if I mark "foo" which is already premarked, the marks value is
'("foo" "foo").

It's as if the test function didn't work.  Am I using `eq` instead of
`equal`?
I'll check tomorrow.

**Comment by Ambrevar** [comment]
Fixed with 9d1b48dba27fd2c72a918587d77d52930ccb9bbf.
Moving the optional item to #1213.
