### ISSUE TITLE
When many windows of Nyxt are open, the history of any given window is that of the Main window

### ISSUE THREAD

**Issue by mariari** [atlas-engineer/nyxt#1214]
**Describe the bug**

When one creates a new window in nyxt, the newely created window is considered the main window (the window in which any url open will hop to). However when one tries to browse the history or go to a previous entry in the history, they are instead brought to the main windows history

EDIT :: it seems this behavior is unrelated to main/sub window, but rather what was the last window which changed the buffer URL.

**Precise recipe to reproduce the issue**

Take any buffer with a history on the main window, spawn a new window with `make-window`, go to the window which spawned the window, and view the history with navigate backwards, you'll see it's blank.

Note this persists even if you kill the window, as the window doesn't yet realize it's the main window again, this is simply fixed by switching the buffer on the main window. 

**Information**
- OS name+version:
    - Arch Linux
- Graphics card and driver:
- Desktop environment / Window manager name+version:
    - Xmonad 0.15
- How you installed Nyxt (Guix pack, package manager, build from source):
    - `make all` from master
- Information from command copy-system-information:

  If you can't run copy-system-information, please provide the following:
  - Nyxt version (from =M-x nyxt-version= or =nyxt --version=):
      - Version 2-pre-release-5-925-g5db56c8f 
  - Lisp implementation/version (if built from source):
      - SBCL 2.1.1.1 
  - Kernel name+version:
  - WebKitGTK+ | QtWebEngine version:

**Output when started from a shell**

**Comment by Ambrevar** [comment]
I can reproduce.
In the original window, if I switch buffer back and forth, the history
shows up properly again.

@aartaka Any idea?

I'll give it a closer look later.

**Comment by aartaka** [comment]
> I can reproduce. In the original window, if I switch buffer back and forth, the history shows up properly again. @aartaka Any idea? I'll give it a closer look later.

No idea yet. I forgot about multi-window setup when drafting GHT :(

**Comment by Ambrevar** [comment]
It's probably a missing `current-buffer` let-binding somewhere.

**Comment by chrisboeg** [comment]
@Ambrevar I can take a look at this tomorrow and see if I can come up with a patch.

**Comment by Ambrevar** [comment]
That'd be fantastic! :)

**Comment by chrisboeg** [comment]
Just a little update, since I haven't fix it yet. It seems to be a general problem with multiple windows. Whenever there are more than one window open, history navigation doesn't work as expected. I have tried figuring out what is happening, but it's very sneaky to debug. The buffer id's are correct, but the history that is produced is not when there are two windows for some reason. Very sneaky indeed.

**Comment by Ambrevar** [comment]
I believe the history suffers from incorrectness with 1 window as well.

Can't you reproduce this issue with just 1 window?
Do you have a recipe?

I'll get down to this as soon as possible, this is an important bug.

**Comment by chrisboeg** [comment]
I haven’t observed the problem with 1 window but I will give it a shot later.

**Comment by Ambrevar** [comment]
See #1692 for a fix.  Can you test?
