### ISSUE TITLE
Restore file-manager-mode and open-file as an extension (for now)

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#1219]
We've removed file-manager-mode when working on the prompt buffer.

**Comment by aartaka** [comment]
affcf5278f0049340ad88e3315f826874145b81b is the commit it was removed in(just to not get lost).

**Comment by Ambrevar** [comment]
With your recent work I don't think there is much left to restore.

What missing, if I'm not mistaken:

- A binding to go back.  I need to work on the prompt-buffer keymaps beforehand.
- An action to open files externally, e.g. with xdg-open.  The download source already does that, but we may want to make this accessible everywhere.

Bonus: Add a source the prompt for a program to open the file with.
Programs can be looked up in PATH.
Maybe add another source for desktop applications, e.g. those with a .desktop file as listed in GNOME, etc.
