### ISSUE TITLE
Add tests for `manual` and `tutorial`

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#1221]
A couple of times our `manual` and `tutorial` broke (which is a big no-no) simply because some commands were unbound or mispelled.

Ideally, we would catch these errors at compile time.
If we can't, then let's add a test suite which runs these commands.

**Comment by aadcg** [comment]
Does #1240 cover such a case?

**Comment by Ambrevar** [comment]
Sadly no, #1240 is to catch errors at run-time.

**Comment by Ambrevar** [comment]
@aartaka Can you explain how this is fixed?  Does it mean that `:ncode` snippets catch misspelling errors/

**Comment by aartaka** [comment]
Yes. The improperly read symbols or syntax errors will error out of `:ncode` now. I'm not sure we can do much better than that.

**Comment by Ambrevar** [comment]
Can you point at the code that does this?

**Comment by aartaka** [comment]
> Can you point at the code that does this?

I mean, it's just that forms in `:ncode` are being `read` by both Spinneret and regular compiler.

Adding to that, there's now a `tests/executable/config.lisp` in our tests that checks the validity and error-less-ness of all the `:ncode` snippets in the manual.

**Comment by Ambrevar** [comment]
Nice, but why did you say

> I don't understand how to run it and whether it works, though :D

in commit 573442a9c9c66bd576b1778f8ff675d8d1bef701 ?

**Comment by aartaka** [comment]
I did! :D I don't understand how to make ASDF run this exact set of tests.

**Comment by Ambrevar** [comment]
Call `asdf:test-system` on `nyxt/application/tests`, as usual.  What exactly is it that you don't understand?  Can you share what you tried, what you expected and what you got?

**Comment by aartaka** [comment]
In my case, the executable was missing from Nyxt checkout, and it failed because of executable absence. Right now, it passes just fine (with one failed assertion elsewhere), so I guess that was a random breakage back then...

**Comment by Ambrevar** [comment]
Well, the ASD system has this:

```lisp
(if (file-exists-p (system-relative-pathname :nyxt "nyxt"))
                        (call-next-method)
                        (warn "`nyxt' executable missing, skipping tests."))
```

So that should have given you a good indication.  Maybe it's not so obvious then.  Do you have a suggestion to improve this workflow?

**Comment by aartaka** [comment]
No, it's just enough. I just wonder if we maybe can build it if it's absent.

**Comment by Ambrevar** [comment]
The problem is the renderer choice.  The `nyxt/application/tests` does not specify which renderer it depends on, but to build a binary we must specify one.  Considering we only have 2 usable renderers, it's reasonable to pick one, but at the same time it's really easy to build the executable manually (it has to be done just once anyways).
