### ISSUE TITLE
docs: README AUR deadlink

### ISSUE THREAD

**Issue by EvansJahja** [atlas-engineer/nyxt#1224]
In the readme, the AUR package (the non-git) should link to 

https://aur.archlinux.org/packages/nyxt

instead of

https://aur.archlinux.org/packages/nyxt-browser

**Comment by Ambrevar** [comment]
Good catch, thanks for reporting!
Fixed with 25fc94ec43e6eaa69a80fd1f8f40c1283eaea6a0.
