### ISSUE TITLE
can i do regular web dev in nyxt browser?

### ISSUE THREAD

**Issue by molleweide** [atlas-engineer/nyxt#1225]
Hi,

Okay so I am a total beginner with  lisp and nyxt. I am trying to  understand how to install which is quite interesting because I have never used macports on my mac. But my question is if it is possible
to do web dev and other stuff that I can do in a regular browser? I am sort of trying to wrap my head around what nyxt is. It seems really cool and like a completely new world to me.

Cheers,

**Comment by jmercouris** [comment]
Yes, of course :-) You can run `open-inspector` and  a typical web inspector like the ones available in other browsers will come up.

thanks for the kind words. Good luck with the install. It is not easy on macOS!

**Comment by molleweide** [comment]
Thanks for replying! Do you mind if I ask why it is harder on macOS? What is the main culprit sort of?

**Comment by jmercouris** [comment]
I encourage you to try things outside of your comfort zone, that's how you become a pro :-)

Why is installation hard on macOS? Succinctly put: webkitgtk+ is developed within the context of Linux and needs to be significantly patched!

**Comment by molleweide** [comment]
Cool thanks!

**Comment by jmercouris** [comment]
Please feel free to reopen if you have any more questions!

**Comment by molleweide** [comment]
Hi again!

I have one more question. Will I be able to follow the development and issues if I run on macos? Or will I be mostly "on my own". I haven't used lisp before so I want check before I get to deep. Does my question make sense?

**Comment by jmercouris** [comment]
You will be mostly on your own. I have a mac still, but I am not using it as my main machine anymore. The issues you will have would not be Lisp specific issues.

**Comment by molleweide** [comment]
Great!!

**Comment by molleweide** [comment]
yooo! I learnt how to use virtualbox to test linux etc. so I finally got to try it out for real! I am about
to read through the tuts and manual. this is very cool!

**Comment by molleweide** [comment]
yeah i hope i can get into lisp and functional dev now. I also installed kmonad just now which is haskell also.
