### ISSUE TITLE
Unable to Install on macOS via nix-env

### ISSUE THREAD

**Issue by gurjeet** [atlas-engineer/nyxt#1232]
**Describe the bug**

The readme says installation via nix-env is possible, and that macOS is a supported OS. But when I try to install it on macOS using the Nix CLI, I get an error that the package is not supported on macOS/Darwin.

```shell
$ nix-env --install nyxt
installing 'nyxt-2020-10-23'
error: Package ‘nyxt-2020-10-23’ in /nix/store/l8jnvwgjm8wh723nxr2pardzwbpykgh0-nixpkgs-21.05pre272788.870dbb751f4/nixpkgs/pkgs/applications/networking/browsers/nyxt/default.nix:51
is not supported on ‘x86_64-darwin’, refusing to evaluate.
```

**Information**
```
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-darwin"`
 - host os: `Darwin 18.7.0, macOS 10.14.6`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.7`
 - channels(gurjeet): `""`
 - channels(root): `"nixpkgs-21.05pre272788.870dbb751f4"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`

```

**Comment by Ambrevar** [comment]
Hi!

> The readme says installation via nix-env is possible, and that macOS is a supported OS. But when I try to install it on macOS using the Nix CLI, I get an error that the package is not supported on macOS/Darwin.

Sorry if this was confusing, indeed the two statements don't compose:
macOS is non-officially supported but _not_ via Nix.  You can install
webkitgtk via MacPorts.  That said, the process is convoluted.

My guts tell me that the way forward for macOS support is Nix, so we'd
need to work in that direction.

Any takers to get the webkitgtk Nix package to work on macOS?
@jmercouris has some patches I believe.

**Comment by jmercouris** [comment]
There is somebody working on this already, let me try to find the information.

**Comment by jmercouris** [comment]
Here it is: https://github.com/NixOS/nixpkgs/pull/116233#pullrequestreview-611647931

**Comment by jmercouris** [comment]
Hopefully that is useful :-)

**Comment by Ambrevar** [comment]
Fantastic news!

**Comment by teehemkay** [comment]
FWIW, the MacPorts kind of manages to build. It took about 2h30 on a Late 2012 Mac mini, 2,6 GHz Quad-Core Intel Core i7, 16 GB RAM, macOS Catalina 10.15.7.

I had a couple of issues. The main one was ensuring that `gtk3` was built using its `quartz` variant (i.e. NOT the `X11` one). Which I did by adding `-x11 +no_x11 +quartz` to MacPorts [`variants.conf'](https://guide.macports.org/#internals.configuration-files) config file.

Although the build process [errors out](https://gist.github.com/teehemkay/643fbd82c7bf865e0ee67052b047795c) towards the end, the command line `nyxt` executable produced seems (at least somewhat) functional. The GUI Mac app seems broken though.

Running that executable from the terminal (`$ ./nyxt` after `cd'ing` into the build directory) opens a window with the *Help* buffer displaying the "Welcome to Nyxt :-)" message :-).

The internal documentation (tutorial, help, etc) loads normally.

Trying to open an external URL fails with a "WebKit encountered an internal error" message displayed in the buffer.
Here's what's logged in the terminal used to launch  `nyxt`

```
(process:61761): GLib-GIO-ERROR **: 10:27:45.528: No GSettings schemas are installed on the system
<INFO> [10:27:45] Saving session to "/Users/<username>/.local/share/nyxt/sessions/default.lisp".
<INFO> [10:27:45] Finished loading "https://duckduckgo.com/?q=help".
<INFO> [10:27:45] Saving session to "/Users/<username>/.local/share/nyxt/sessions/default.lisp".
<INFO> [10:27:46] Loading "https://nyxt.atlas.engineer/start".
<INFO> [10:27:46] Finished loading "https://nyxt.atlas.engineer/start".
```

**Comment by jmercouris** [comment]
The dreaded "internal error" message! :-D

thank you for this thorough reporting!

**Comment by tastyminerals** [comment]
> FWIW, the MacPorts kind of manages to build. It took about 2h30 on a Late 2012 Mac mini, 2,6 GHz Quad-Core Intel Core i7, 16 GB RAM, macOS Catalina 10.15.7.
> 
> I had a couple of issues. The main one was ensuring that `gtk3` was built using its `quartz` variant (i.e. NOT the `X11` one). Which I did by adding `-x11 +no_x11 +quartz` to MacPorts [`variants.conf'](https://guide.macports.org/#internals.configuration-files) config file.
> 
> Although the build process [errors out](https://gist.github.com/teehemkay/643fbd82c7bf865e0ee67052b047795c) towards the end, the command line `nyxt` executable produced seems (at least somewhat) functional. The GUI Mac app seems broken though.
> 
> Running that executable from the terminal (`$ ./nyxt` after `cd'ing` into the build directory) opens a window with the _Help_ buffer displaying the "Welcome to Nyxt :-)" message :-).
> 
> The internal documentation (tutorial, help, etc) loads normally.
> 
> Trying to open an external URL fails with a "WebKit encountered an internal error" message displayed in the buffer.
> Here's what's logged in the terminal used to launch `nyxt`
> 
> ```
> (process:61761): GLib-GIO-ERROR **: 10:27:45.528: No GSettings schemas are installed on the system
> <INFO> [10:27:45] Saving session to "/Users/<username>/.local/share/nyxt/sessions/default.lisp".
> <INFO> [10:27:45] Finished loading "https://duckduckgo.com/?q=help".
> <INFO> [10:27:45] Saving session to "/Users/<username>/.local/share/nyxt/sessions/default.lisp".
> <INFO> [10:27:46] Loading "https://nyxt.atlas.engineer/start".
> <INFO> [10:27:46] Finished loading "https://nyxt.atlas.engineer/start".
> ```

I followed the instructions here: https://source.atlas.engineer/view/repository/macports-port
However, after `sudo port install nyxt` I get `Error: Port nyxt not found`.
How did you manage to do it via MacPorts?

**Comment by Gira-X** [comment]
> However, after sudo port install nyxt I get Error: Port nyxt not found.
> How did you manage to do it via MacPorts?

Are you sure you ran `portindex` in the `macports-port` directory (see step 3)?

It outputs something like:

```
Creating port index in /Users/Gira/macports-port
Adding port devel/libfixposix
Adding port python/py-gobject
Adding subport py27-gobject
Adding subport py35-gobject
Adding subport py36-gobject
Adding subport py37-gobject
Adding subport py38-gobject
Adding port www/Nyxt
Adding port www/webkit2-gtk-devel
```

**Comment by tastyminerals** [comment]
> /Users/Gira/macports-port

Ah, I cloned the nyxt git repo instead of the `macports-port` one. It works now, although it doesn't compile for M1 yet.

**Comment by joelmccracken** [comment]
Hi, I'm interested in helping with this. I would really like to use nyxt as my daily driver browser - there are many reasons this makes sense for me. However, I would probably need some guidance in fixing some things -- I am not very experienced with CL, and I am not super experienced with i.e. GTK, etc. Thoughts?

**Comment by jmercouris** [comment]
Hello Joel, thank you for your interest. It isn't exactly about having good experience, it is about having a lot of perseverance. At some point, it seems you are trying random things, and searching cryptic error messages until you can get it to work. There is a lot of machinery that makes no sense. I wish you the best of luck!

**Comment by aadcg** [comment]
Stale.

Nyxt 3.0.0 should land on Nix soon. See https://github.com/NixOS/nixpkgs/issues/217888.

Please open an issue if that will fail to work on macOS.
