### ISSUE TITLE
Add command to jump to first input field

### ISSUE THREAD

**Issue by edgar-vincent** [atlas-engineer/nyxt#1233]
Hi all,

It has been requested many times, including by myself, so I thought it should be mentioned here.
It would be nice to have a command which focuses the first input field in a given buffer, similar to the one bound to `gi` in Tridactyl and, I assume, other similar implementations. It would make it easier to quickly jump to a search field, for instance in a search engine.

Thanks a lot!

EV

**Comment by Ambrevar** [comment]
Good idea!  This is relatively easy to implement, so I've tagged this issue appropriately.
Any taker? ;)

**Comment by aadcg** [comment]
I can take a look.  Should there be a keybinding for it @Ambrevar?

**Comment by Ambrevar** [comment]
I suppose `tab` should do?
Seems to be the default in most browsers.

**Comment by aadcg** [comment]
@edgar-vincent your request has been fulfilled.  You will be able to do that by hitting `M-i`, or `Alt+i`.

**Comment by edgar-vincent** [comment]
Thanks a lot! I'll do some testing.

**Comment by edgar-vincent** [comment]
Unfortunately, it doesn't seem to be working on Duck Duck Go.

**Comment by Ambrevar** [comment]
It's a known issue indeed.
The good news: TAB works :)

**Comment by aadcg** [comment]
Indeed, this flaw was documented when it was developed.  The inputs fields in duckduckgo behave rather strange. They lose the focus after events such as switch tab/buffer. You can use `h` to get to duckduckgo's search bar. This functionality is embedded in it.

**Comment by edgar-vincent** [comment]
@Ambrevar @aadcg Sorry about that. Now I remember you mentioning it at the time. At least it's out in the open now :)
