### ISSUE TITLE
toggle-hints-transparency is unbound

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#1235]
@jmercouris I believe this used to be bound, I don't see when this got disabled.
Any idea?

**Comment by jmercouris** [comment]
That's correct. I wasn't sure how to bind it in the new prompt buffer design. That is why it is unbound :-D

**Comment by jmercouris** [comment]
If you can bind it that would be very nice!

**Comment by Ambrevar** [comment]
Oh I see, it was part of a minibuffer-mode.
The new prompt-buffer design accepts keymaps.  I need to work it out.

**Comment by Ambrevar** [comment]
Fixed with 88f16d5c41864e887a308d3b0ae968ec5c571d84.
