### ISSUE TITLE
The startup screen asks me for a buffer to switch to, then URLs won't load

### ISSUE THREAD

**Issue by bzg** [atlas-engineer/nyxt#1241]
**Describe the bug**

Hopefully this gif explains the issue topic:

![out](https://user-images.githubusercontent.com/63500/112478912-c376d600-8d74-11eb-8d41-7743c65789c9.gif)

**Precise recipe to reproduce the issue**

This is with latest Nyxt installed from the guix.scm source file in the master branch on Ubuntu 20.4 using i3 as a wm.

```
Nyxt version: draft-do-not-use-me-71-gd9fae27c 
Operating system kernel: Linux 5.8.0-48-generic
Lisp implementation: SBCL 2.1.2
Features: (WEBKIT2 WEBKIT2-2.30 WEBKIT2-TRACKING WEBKIT2-MUTE WEBKIT2-EMOJI
           WEBKIT2-MEDIA WEBKIT2-SANDBOXING GTK-3-22 GTK-3-20 GTK-3-18 GTK-3-16
           GTK-3-14 GTK-3-12 GTK-3-10 GTK-3-8 GTK-3-6 GTK-3-4 GTK GDK-3-22
           GDK-3-20 GDK-3-18 GDK-3-16 GDK-3-14 GDK-3-12 GDK-3-10 GDK-3-8
           GDK-3-6 GDK-3-4 CAIRO-1-10 CAIRO-1-12 GDK-PIXBUF GLIB-2-30 GLIB-2-32
           GLIB-2-34 GLIB-2-36 GLIB-2-38 GLIB-2-40 GLIB-2-42 GLIB-2-44
           GLIB-2-46 GLIB-2-48 GLIB-2-50 GLIB-2-52 GLIB-2-54 GLIB-2-56
           GLIB-2-58 GLIB FSET-EXT-STRINGS CUSTOM-HASH-TABLE-NATIVE SWANK
           PLUMP-UTF-32 GLOBAL-VARS DECLARE-TYPES PARENSCRIPT
           SBCL+SAFE-STANDARD-READTABLE NAMED-READTABLES 21BIT-CHARS CHUNGA
           FLEXI-STREAMS CLOSER-MOP CL-PPCRE-UNICODE CL-UNICODE CL-PPCRE
           CL-JSON-DOUBLE-FLOAT-IS-SUBSUMED CL-JSON-SINGLE-FLOAT-IS-SUBSUMED
           BORDEAUX-THREADS SPLIT-SEQUENCE GRAY-STREAMS FLAT-NAMESPACE X86-64
           UNIX CFFI FLAT-NAMESPACE SEQUENCE-EMPTYP FAST-IO-SV FAST-IO
           SBCL-USES-SB-ROTATE-BYTE CL-JSON-CLOS CL-JSON THREAD-SUPPORT ASDF3.3
           ASDF3.2 ASDF3.1 ASDF3 ASDF2 ASDF OS-UNIX NON-BASE-CHARS-EXIST-P
           ASDF-UNICODE X86-64 GENCGC 64-BIT ANSI-CL COMMON-LISP ELF
           IEEE-FLOATING-POINT LINUX LITTLE-ENDIAN PACKAGE-LOCAL-NICKNAMES
           SB-CORE-COMPRESSION SB-LDB SB-PACKAGE-LOCKS SB-THREAD SB-UNICODE
           SBCL UNIX)
```

**Output when started from a shell**

Sorry I lost it, but the gif may give some information.

**Comment by Ambrevar** [comment]
I can reproduce, and it looks like there are a couple of bugs here :/

Thanks for reporting, I'll look into it.

**Comment by Ambrevar** [comment]
Can you try building against master, _without grafts_?
Master includes a small fix for the prompter, but I don't think that's the problem here.
My guess is that it's grafts again, because of the GParam errors which seems to indicate that your prompt is not understood at all.

**Comment by bzg** [comment]
Thanks!

I pulled the repo and tried two installation methods: the one with `make all && make install` and the other one with `guix package --install-from-file=build-scripts/guix.scm` (per [these instructions](https://github.com/atlas-engineer/nyxt/blob/master/build-scripts/guix.scm#L6)), without the `--no-grafts` option.

Both `nyxt-version` are `draft-do-not-use-me-95-ge1cb463d`.

The GParam errors are gone with `/usr/local/bin/nyxt` (from the `make install` way) but not from the guix installation.

For both binary files, the init bugs are gone.

`xdg-open` works fine when calling the `/usr/local/bin/nyxt` binary, but not when calling the guix binary: `xdg-open http://perdu.com` creates a blank page, confirming that the GParam errors may have something to do with this.

**Comment by Ambrevar** [comment]
Why did you choose to install without `--no-grafts`?  Can you compare
with an installation _with_ `--no-grafts`?

**Comment by bzg** [comment]
> Why did you choose to install without `--no-grafts`? 

Sorry, I misread your earlier message. I just reinstalled *with* `--no-grafts` and both binary files now work the same, the GParam errors are gone and `xdg-open` works fine.

Thanks again!

**Comment by Ambrevar** [comment]
Thanks for confirming!

For future reference, here is the upstream issue with Guix: https://issues.guix.gnu.org/33848

We'd really need to adress it at some point.

Feel free to close this if there is nothing else.

**Comment by bzg** [comment]
I'll follow the discussion on guix.gnu.org, thanks for the pointer.

Closing this now, thanks again.
