### ISSUE TITLE
Recommend checking out to (xdg-data-home "common-lisp/systems/")

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#1245]
When building Nyxt with Quicklisp, we fetch external dependencies _inside_ the Nyxt checkout:

- The Git submodules.
- The Quicklisp distribution.

This may cause conflicts with other systems if `nyxt` is checked out in a PATH that's looked up recursively by ASDF.

Both `~/common-lisp` and `~/.local/share/common-lisp/source` are looked up recursively.

What about recommending checking out Nyxt to `~/.local/share/common-lisp/systems` instead, since this one is not looked up recursively?

**Comment by jmercouris** [comment]
Are you suggesting that users clone Nyxt into the path: `~/.local/share/common-lisp/systems` OR are you suggesting that we fetch external dependencies to said path?

**Comment by Ambrevar** [comment]
Clone Nyxt there.
I think all the Quicklisp mumbo jumbo we are doing should stay inside Nyxt and not pollute the user file system.

**Comment by jmercouris** [comment]
I know that as a user, I would certainly not like doing that. I want the freedom to put the source wherever. If it is a suggestion, that is fine I think.

**Comment by Ambrevar** [comment]
Of course it's a suggestion, how could we force the user to check out
nyxt in a specific place? :p
Misunderstanding?

The point is that checking out to ~/common-lisp may result in library
version conflicts which is confusing for people new to Common Lisp.

I can recall at least 2 cases where I asked a user to clear their
~/common-lisp/nyxt/quicklisp-libraries and things started working again.

**Comment by jmercouris** [comment]
I'm saying that I am OK with it insofar as we do not change our logic to rely on this path. No misunderstanding :-D

**Comment by aadcg** [comment]
> I can recall at least 2 cases where I asked a user to clear their
~/common-lisp/nyxt/quicklisp-libraries and things started working again.

I might have been one of those.

**Comment by Ambrevar** [comment]
To clarify, we don't have any logic about where `nyxt` is stored, it can
be put anywhere.

I'll edit the documentation then.

**Comment by Ambrevar** [comment]
Done in 80d478fe637c81a4546ffbf74519a63609129e17.

**Comment by jmercouris** [comment]
Thank you!
