### ISSUE TITLE
Emacs Integration

### ISSUE THREAD

**Issue by Pitometsu** [atlas-engineer/nyxt#125]
Is there a way to integrate it with Emacs, as described here: https://www.emacswiki.org/emacs/EmacsApplicationFramework ?

**Comment by jmercouris** [comment]
Hi Yuriy,

Thank you for your interest,

To answer your question, I don’t know. I think the integration will have to work in a quite different way. In the meantime, you can already communicate with next via Slime. You’ll find the directions here: https://github.com/atlas-engineer/next/blob/master/documents/MANUAL.org#slime-with-a-compiled-version-of-next <https://github.com/atlas-engineer/next/blob/master/documents/MANUAL.org#slime-with-a-compiled-version-of-next>

**Comment by Pitometsu** [comment]
It's more about same common hotkey as in current emacs setup and auto-completion UI like ivy/helm integration. And modes for bookmarks (org-mode, etc)...

**Comment by fbob** [comment]
Emacs integration could be indeed an awesome feature !

**Comment by jmercouris** [comment]
@Pitometsu 

those are things we are working on, sorry for the lack of response, this must have slipped underneath my radar, but be sure that I agree fully, these are great ideas and I really want to see them happen!

**Comment by fbob** [comment]
Great thanks :+1:

**Comment by jmercouris** [comment]
No problem!

**Comment by fbob** [comment]
Any news on this feature ?
Thanks for your feedback :)

**Comment by Ambrevar** [comment]
Let's get started with a feature list.  @Pitometsu mentioned some:
- Ivy/Helm integration.
- Shared hotkeys.
- Bookmarks (shared?).
- Org-mode integration.

A lot of it is already doable.

- With EXWM, you can get the Next windows displayed in your buffer list.

- With Swank, you can fetch the list of buffers from Emacs.

- Next has its own minibuffer and we intend to improve it to the level of Ivy/Helm in the future.

- Bookmarks are also going to be improved, and I intend to make them backward compatible with EWW bookmarks.

- Org captures can be done rather easily: https://next.atlas.engineer/article/emacs-hacks.org

Anything else in particular?  Any feature that someone would like to pick up?  This could be a great starting point for a first pull request! :)

**Comment by fbob** [comment]
Thanks for you valuable feedback :)

My idea was more on a tighter integration like EAF as @Pitometsu  already mentioned:  https://www.emacswiki.org/emacs/EmacsApplicationFramework
because not everyone wants to use EXWM (it's awesome but it has also its own limitations)

**Comment by Ambrevar** [comment]
In which way?
Do you have examples?

As I understand it, EAF is a framework / library for Emacs.  I don't
think EAF can talk to Next directly (beside Swank).

**Comment by vindarel** [comment]
The integration with EAF seems possible because we now have a PyQt port, but it is specific work.

**Comment by fbob** [comment]
@Ambrevar  by tighter integration I mean that with EAF framework you can "launch" application directly inside emacs and by such you are able to "manage" them as regular windows/buffers with all the emacs ecosystem goodies  

@vindarel that's a good news, maybe some of the core developers can contact manateelazycat (https://github.com/manateelazycat) if they are interested to integrate Next or enhance EAF

**Comment by Ambrevar** [comment]
I don't know enough about either EAF and the PyQt port, but this is an interesting idea indeed.
@manateelazycat Any thought on this?

**Comment by manateelazycat** [comment]
Not every PyQt program can integrate in EAF, it need follow EAF framework interface like https://github.com/manateelazycat/emacs-application-framework/blob/master/docs/HACKING.md

Well, any patch are welcome that make Next build with EAF interface. ;)

**Comment by aadcg** [comment]
There's no actionable conclusion to extract from this thread. Thanks for the discussion.
