### ISSUE TITLE
Default delete-buffer target should be current buffer

### ISSUE THREAD

**Issue by tg-x** [atlas-engineer/nyxt#1252]
Currently the default target for `delete-buffer` is another buffer, similarly to `switch-buffer`.

For `delete-buffer` it would make more sense to default to the current buffer, however.

nyxt-2-pre-6

**Comment by aadcg** [comment]
Indeed! Thank you for reporting @tg-x. 

#1254 should address it.

**Comment by Ambrevar** [comment]
Fixed, thank you @tg-x for reporting and thank you @aadcg for fixing it!
