### ISSUE TITLE
Downloads polishing

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#1255]
Downloading in Nyxt is still a bit inaccessible I believe.  I've noted a few points:

1. [x] Downloaded small file show a filled bar but a completion of 0%.  I guess an HTML update is missing.
2. [x] Cancelled downloads just stop, they don't display that they are cancelled.  This can be confusing because there is no visual difference between a download that's cancelled and one that hung.
3. The `open file` icon `🗁` displays as a square on my system (I use the DejaVu font).  Should we replace it with a more widely available symbol?  EDIT: Or just with "Open".
4. We should display the destination name, because it's not necessarily the same as the download URL plus long URLs are quite unreadable.
5. I think the word "completion" is superfluous.  Besides, I'd put the percentage on the same line as the progress bar: currently, downloads take too make vertical space.
6. I'd print the download directory at the top.

@jmercouris Thoughts?

**Comment by Ambrevar** [comment]
7\. To save more vertical space, we could put the 2 buttons next to the URL.

**Comment by jmercouris** [comment]
Bonjour PIerre,

This is where differ ideologically in our design thinking. I am afraid that some of these issues are untenable :-D

1. No signal is emitted by WebKitGTK in this case. It is not a bug in our implementation... I don't know exactly how to work around it. We /could/ always start at "100%" and then update from there, THEN small downloads would look completed.
2. That is a good point! We can display an icon or something next to them.
3. I think we should supply a font with Nyxt that includes all of the icons, they are quite nice. OR we could find a more commonly available icon.
4. I don't see why that is necessary, if the user can click to open, why would they need to know the destination? How about a "i" button they can click for more information about a download?
5. Vertical space is not an issue, things can scroll down. Better clarity than "less vertical space"! I don't think we should be MAXIMIZING for space efficiency. We should be MAXIMIZING for clarity and ease of use. I don't believe space efficiency is a goal of Nyxt :-D
6. If we know the path that each download is going to, AND we can open up downloads with a button, why would we need to know the download directory? Additionally, each download could be going to a different directory. There is no single download directory.
7. Again, I do not think saving vertical space is a good goal- especially when it conflicts with readability and accessibility.

We had the same discussion with regards to listing bookmarks :-D

**Comment by Ambrevar** [comment]
John Mercouris ***@***.***> writes:

> 1. No signal is emitted by WebKitGTK in this case. It is not a bug in our implementation... I don't know exactly how to work around it. We /could/ always start at "100%" and then update from there, THEN small downloads would look completed.

Epiphany does not have this issue, so there must be a way.

> 3. I think we should supply a font with Nyxt that includes all of the
> icons, they are quite nice.

I believe this would be ideal, yes, but not trivial in terms of
deployment.  For the time being, I suggest we stick to more widely
available symbols and go fancy later.

> 4. I don't see why that is necessary, if the user can click to open, why would they need to know the destination? How about a "i" button they can click for more information about a download?

"info" button is OK, although I don't know what else to display.
The use case of knowing the name is two fold:

- When the user wants to browse and open their downloaded files outside
  Nyxt.
- More importantly: simply identify the downloads!  Currently, downloads
  are listed as (often) unreadable URLs.  I believe the users would
  primarily identify a download by their file name.

> 5. Vertical space is not an issue, things can scroll down. Better clarity than "less vertical space"! I don't think we should be MAXIMIZING for space efficiency. We should be MAXIMIZING for clarity and ease of use. I don't believe space efficiency is a goal of Nyxt :-D

Don't get me wrong, I'm not suggesting we sacrifice accessibility,
readability or cosmetic.  The opposite, actually.

Vertical efficiency can also increase accessibility for a simple reason:
you get to see more item on screen.  For instance, if we had only one
download item per "page", we would obviously lose the ability to _list_
the downloads.

Currently on my 1200 pixel high screen, I can only display about 6
downloads.  This is very low and we could easily display twice as much
without sacrificing on cosmetic, accessibility, readability.

> 6. If we know the path that each download is going to,

This is not display on the page.

> AND we can open up downloads with a button, why would we need to know
> the download directory?

For the same 2 reasons as above:
- If the user wants to browse and open their downloads outside of Nyxt.
- Simply to readily present the most trivial information.

> Additionally, each download could be going to a different
> directory. There is no single download directory.

This would be ideal, unfortunately for now there is no user-facing way
to change the download directory :p

> We had the same discussion with regards to listing bookmarks :-D

And I still believe bookmark listing could be improved a bit ;)

**Comment by aartaka** [comment]
> Bonjour PIerre,
> 
> This is where differ ideologically in our design thinking. I am afraid that some of these issues are untenable :-D
> 
>     1. No signal is emitted by WebKitGTK in this case. It is not a bug in our implementation... I don't know exactly how to work around it. We /could/ always start at "100%" and then update from there, THEN small downloads would look completed.
> 
>     2. That is a good point! We can display an icon or something next to them.
> 
>     3. I think we should supply a font with Nyxt that includes all of the icons, they are quite nice. OR we could find a more commonly available icon.

[FontAwesome](https://fontawesome.com/)?

**Comment by Ambrevar** [comment]
Neat!

**Comment by Ambrevar** [comment]
I've just pushed fixed for the first two issues with dd0c59d2e345e399246d13e0a101190863cb76d6 and before.

- Completed downloads should now always show a completion of 100%.
- Canceled downloads also show a status.

Additionally, download errors are handled and reported.

Finally, I've added automatic renaming of existing files.
Previously, existing files would be clobbered by Nyxt or WebKit (!), but download would still fail to start.  I don't know why the file gets deleted, any idea?

The workaround I've implemented appends a number to the filename, but there is a potential race condition if a file with the same generated name gets created right after and before download actually starts.

We would need a better way to lock access to file in a safe way.

**Comment by Ambrevar** [comment]
Status reporting is a bit ugly, the problem is that I don't know how to toggle visibility of elements.

@jmercouris: Could we add support for the `hidden` attribute in the user-interface library?  This would make it easy to toggle elements on and off.

**Comment by Ambrevar** [comment]
8\. Disable / hide buttons when they don't make sense:
  - A failed / canceled download cannot be opened.
  - A finished / canceled / failed download cannot be canceled.

**Comment by Ambrevar** [comment]
9.\ Make sure point 1. and 2 are fixed for the Lisp renderer as well.

**Comment by jmercouris** [comment]
@Ambrevar I can do that. I think that it looks fine in the interface!

**Comment by Ambrevar** [comment]
Sometime the progress cannot be estimated (this is normal when the server does not mention the size in the header).
In this case, we need to report something or else the user might be led to believe that the download is stuck.

I suggest we report the download speed.

**Comment by jmercouris** [comment]
OR we suggest the current amount downloaded so far?

**Comment by Ambrevar** [comment]
Both are useful I think :)

**Comment by Ambrevar** [comment]
Could also have a toggle to display extra details.

**Comment by jmercouris** [comment]
I've added the bytes downloaded. I think this will help when the server does not mention the size in the header.

**Comment by Kabouik** [comment]
Not sure if this is the right place to mention it, but I saw now other issue on it, `save as` and `save image as` don't do anything on my end, the only way to download something is to download in the default location.

**Comment by Ambrevar** [comment]
Indeed, thanks for pointing it out!
