### ISSUE TITLE
Unexport / remove `dirname` and `basename` accessors from `data-path`

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#1270]
https://github.com/atlas-engineer/nyxt/commit/3676b8e47525b2d5b0215d56d60a65d013981419 may highlight a potential misuse of our data-path library: if the user gets `dirname` manually instead of calling `expand-path`, the result may be wrong.

What about unexporting `dirname` and `basename` then?
Or removing the accessor, so that not even internal Nyxt code would be tempted to access these slot values?

**Comment by aartaka** [comment]
Yes, that's a fair point. Unexporting is totally fine by me.

Removing accessors is... tricky. If we remove the accessor, how will it differ from storing string pathname? Adding to that, `dirname` and `basename` are a convenient API to allow pathname copying (see `store-history-by-name` for `dirname` being useful) and creation (it's easy to think about file as a directory and a basename). While latter is covered by initargs, the former isn't possible without accessors.

-------------------------------------------------------------------------------------

Side note: how about moving to pathnames for file references inside `data-path`? Pros:
- we can conveniently construct them out of dirnames and basenames (there can always be a custom constructor); 
- they are easy to take apart;
- they are definitely more powerful than custom dirname+basename combo;
- they are more portable, probably: think Windows porting where there are separate "drives" directories can belong to -- pathnames support that;

This doesn't solve the problem with accidental breaches of `data-storage` API, but looks quite useful otherwise. Am I missing something?

**Comment by Ambrevar** [comment]
> Removing accessors is... tricky. If we remove the accessor, how will it differ from storing string pathname? Adding to that, `dirname` and `basename` are a convenient API to allow pathname copying (see `store-history-by-name` for `dirname` being useful) and creation (it's easy to think about file as a directory and a basename). While latter is covered by initargs, the former isn't possible without accessors.

Couldn't we use `(slot-value OBJ 'dirname)`?

> Side note: how about moving to pathnames for file references inside `data-path`? Pros:

Which "file references" do you mean?

> - we can conveniently construct them out of dirnames and basenames (there can always be a custom constructor); 
> - they are easy to take apart;

What do you mean with taking them apart?
Example?

> - they are definitely more powerful than custom dirname+basename combo;

In which sense are they more powerful?

> - they are more portable, probably: think Windows porting where there are separate "drives" directories can belong to -- pathnames support that;

True we need to fix the portability part.
I think the only thing we are doing wrong is the assumption of "/" as
directory separator, while we should be using
`(uiop:directory-separator-for-host)`.


Personally I don't like the pathname API, I find it needlessly hard to
use and riddled with pitfalls.

I'd rather use https://github.com/fourier/ppath or
https://gitlab.com/ambrevar/fof (the latter only works for existing
files, not for manipulating fictitious paths).

**Comment by aartaka** [comment]
> Couldn't we use `(slot-value OBJ 'dirname)`?

We could, but that's breaking the abstraction :) In other words, why removing accessors, if we're _accessing_ the slot anyway?

>> Side note: how about moving to pathnames for file references inside `data-path`? Pros:

> Which "file references" do you mean?

I mean files/directories that `data-path` was created to represent. Right now these are represented by a union of `dirname` and `basename`.

>> - we can conveniently construct them out of dirnames and basenames (there can always be a custom constructor); - they are easy to take apart;

> What do you mean with taking them apart? Example?

Pathname is an object with dedicated slots and methods for path parts access, i.e. you can take the directory, file extension, file name, host (drive in Windows lingo) etc. through short method call.

Example: We can easily take the parent-directory of the parent-directory of the pathname (`uiop:pathname-directory-pathname` applied twice). Doing this with the current `data-path` is quite hard. Not that there's a case it was needed in, but there for sure can be one :)

>> - they are definitely more powerful than custom dirname+basename combo;

> In which sense are they more powerful?

See above about dedicated parts and methods. That's the main point.

> Personally I don't like the pathname API, I find it needlessly hard to use and riddled with pitfalls. 

Yes, I agree it's quite complex. Historic reasons and compatibility with any filesystem ever existing ¯\\\_(ツ)\_/¯

> I'd rather use https://github.com/fourier/ppath or https://gitlab.com/ambrevar/fof (the latter only works for existing files, not for manipulating fictitious paths).

I have the assumption that strings shouldn't be used for the structured data (think URLs, files) storage and that dedicated structures (like `quri:uri` and pathnames) should be used for that. Both `ppath` and `fof` seem to conflict with that.

I can see the advantages these libraries bring, but I still prefer portable, relatively convenient (given several additional API layers added by UIOP & friends), and highly structured pathnames.

**Comment by Ambrevar** [comment]
Modern file system paths need only the following structure if I'm not
mistaken:

- Directory separator.
  Can be queried dynamically and paths can be constructed on-demand.
- Optional: basename to tell whether it's a file or a directory, but if
  you allow a dir terminator at the end then you are good.
- Optional: drive (only for Windows -- but we could conflate it as the first
  element of the path)

The file extension is a convention, so I think it should remain a
method, not be part of the structure.

So in effect, a path only need to be a list of strings, where the
strings are the path elements, and some indicator telling whether it's a
directory or a file.

```lisp
(defclass my-path ()
 ((elements :type (cons string *))
  (directory? :type boolean)))
```

or

```lisp
(defclass my-path2 ()
  ((directories :type (cons string *))
   (basename :type (or null string))))
```

> We could, but that's breaking the abstraction :) In other words, why removing accessors, if we're _accessing_ the slot anyway?

Removing the accessor has its uses, it's like a very private variable.
You may use it, but at your own risk.  It indicates that it is not how
the API is meant to be used, which seems to be what we want here.

> Example: We can easily take the parent-directory of the parent-directory of the pathname (`uiop:pathname-directory-pathname` applied twice). Doing this with the current `data-path` is quite hard. Not that there's a case it was needed in, but there for sure can be one :)

Actually uiop:pathname-directory-pathname only works on if your path
does not end with a directory separator.

```lisp
> (uiop:pathname-directory-pathname "/home/")
#P"/home/"
> (uiop:pathname-directory-pathname "/home")
#P"/"
```

This kind of issues are bound to happen when we use the pathname API.
Especially if we expose it to newcomers.
This is why I'm against using it in Nyxt, it's too dangerous.

> I have the assumption that strings shouldn't be used for the structured data (think URLs, files) storage and that dedicated structures (like `quri:uri` and pathnames) should be used for that. Both `ppath` and `fof` seem to conflict with that.

I could fix FOF to store the path using the structure outlined in `my-path` or `my-path2`.

> I can see the advantages these libraries bring, but I still prefer portable, relatively convenient (given several additional API layers added by UIOP & friends), and highly structured pathnames.

FOF should be portable (minus the occasional bug).
Or simply the structures outlines above should be.

I don't believe pathnames are convenient.

Another big pain point of pathnames is that the encode wildcards by
default.

```
> (uiop:truename* #p"[foo")
```

raise a condition.  This means that you must wrap almost all UIOP
pathname calls with something that calls `uiop:parse-native-namestring` conditionally.

**Comment by aartaka** [comment]
Fair points these are! The sequence-of-dirnames structure looks alright to me :)

`slot-value` as private API is all good too.

**Comment by Ambrevar** [comment]
Alrighty!

It seems simple enough to introduce the aforementioned class instead of
relying on an external library.  Unless such library already exists in
the CL community.

Thoughts?

**Comment by aartaka** [comment]
How about merging this class with `data-path` (so that `data-path` has `ref`, `directories`, and `basename`)? It's the only application and sensible place for it, after all.

I'm not aware of any library implementing this approach ¯\\\_(ツ)\_/¯

**Comment by Ambrevar** [comment]
Sounds good to me!

**Comment by aartaka** [comment]
Another two cents on representing files and what we need to have: 
- There should be a distinction between absolute and relative files and/or notion of root directory (`/` on *nix, for example).
- We may need to either force the trailing slash for directory-names (Lisp-style) or leave it out (*nix-style). First is a good convention, while second is a necessity when communicating with external programs.

**Comment by Ambrevar** [comment]
Artyom Bologov ***@***.***> writes:

> Another two cents on representing files and what we need to have: 
> - There should be a distinction between absolute and relative files and/or notion of root directory (`/` on *nix, for example).

Good point.

But on Windows, there is no root, just drive letters.  So we need a way
to store them, but this raises portability issues.

Question: how do we deserialize on Windows an absolute path that was
serialized on Unix?
It can't know which drive corresponds to "root".  Maybe there is a
default drive on Windows?

This question has certainly been asked before.  CL pathname might have
an answer.

> - We may need to either force the trailing slash for directory-names (Lisp-style) or leave it out (*nix-style). First is a good convention, while second is a necessity when communicating with external programs.

Also good point.

This needs not be stored in the data structure though, we can defer it
to the "rendering" function, e.g.

(write-path STREAM path :separator t)

**Comment by aartaka** [comment]
> Good point. But on Windows, there is no root, just drive letters. So we need a way to store them, but this raises portability issues. Question: how do we deserialize on Windows an absolute path that was serialized on Unix? It can't know which drive corresponds to "root". Maybe there is a default drive on Windows? This question has certainly been asked before. CL pathname might have an answer.

There is a default drive, at least in my experience: `C:`. It was present on all Windows PCs/laptops I encountered, and it almost always was the one programs are installed on (although that's configurable).

> Also good point. This needs not be stored in the data structure though, we can defer it to the "rendering" function, e.g. (write-path STREAM path :separator t)

Right. The idea came to me when thinking on #1376. I've almost added `unix-style-p` keyword argument to `expand-path` but decided to discuss it first :)

I believe that there are more complications like these we can encounter when working with files. I'm leaning to pathnames again :D

**Comment by Ambrevar** [comment]
> There is a default drive, at least in my experience: `C:`.

If I'm not mistaken, this is purely accidental.
You can install Windows on a different drive, and C: may not exist.

>> Also good point. This needs not be stored in the data structure though, we can defer it to the "rendering" function, e.g. (write-path STREAM path :separator t)
>
> Right. The idea came to me when thinking on #1376. I've almost added `unix-style-p` keyword argument to `expand-path` but decided to discuss it first :)
>
> I believe that there are more complications like these we can encounter when working with files. I'm leaning to pathnames again :D

I'd like to address the aforementioned flaws of cl-pathname though.
Not urgent, but I think the CL community would benefit from a good
pathname library.

**Comment by Ambrevar** [comment]
If we move `data-path` (`data-storage`) to a separate library, we should rename a few things.  In particular, I find that `user-file` is a much better name than `data-path`.

A few other classes should be renamed.

- `data-profile` -> `user-profile`
- `user-data` -> `data-safe`?
- `get-user-data` -> (get-)`data-safe`?
- `get-data` -> `data-from-safe`, `safe-data`?

**Comment by aartaka** [comment]
It feels unclear what `-safe` should convey, but I cannot think of any alternative. Other than that, it's good :)

**Comment by Ambrevar** [comment]
Agree, I don't like the `safe` naming, it's confusing.  What I had in mind is a safe, as in the object where you put your precious belongings.

**Comment by aartaka** [comment]
How about staying with `user-data` then? It seems more consistent with `user-profile`.

**Comment by Ambrevar** [comment]
I don't like `data`, it does not convey much that is meaningul.  `content` is a bit better, because it refers to the file content.

**Comment by Ambrevar** [comment]
In
https://github.com/atlas-engineer/nyxt/commit/bbd2d2e1ef00663b81e19f92fb1fcc5e9a14b813#commitcomment-52457381
we discussed the re-architecture of this library.

We need the following features:

- Recursively-locked access to the content for modification.
- Unlocked access to the content for reading.
- Content should probably be automatically restored on demand.
- The ability to store and restore from arbitrary files.

About this last point: we can have high-level functions to do this, which would
basically be what our `restore-history-from-name` does.
Then the low-level stuff would be done by the customizable method `restore`.
We can rename the methods to avoid any ambiguity.

With `restore` being low-level, then the method would _return_ the deserialized
data, and the caller would be in charge of setting it.  Thus `restore` would not
have access to the `data-path`, which would free us from accidental infinite
loops.

`get-data` and `get-user-data` should probably we implementation details.
Initially, `get-data` was introduced as a high-level helper.  I suggest removing
it then, and forward the automatic store / restore to `get-user-data`.

The caching logic should also be done automatically and systematically I think.
Then `get-user-data` does not need to be a method anymore.

In the end, there would remain only these custumizable methods:

- `restore`
- `store`
- `expand-data-path` (to rename to `expand-user-path`?)

**Comment by Ambrevar** [comment]
Other nomenclature question: rename `expand-data-path` to just `expand*` and `expand-path` to `expand`?

**Comment by aartaka** [comment]
All of this feels right!

`expand(*)` feels too generic, but I can make sense of it.

**Comment by Ambrevar** [comment]
If we are going to move this to a separate library, then it would read,
say, `user-file:expand`.

**Comment by aartaka** [comment]
That makes sense then. All fine by me!

**Comment by Ambrevar** [comment]
Note by Artyom: " make a macro controlling the expansion of data paths. Something like:

```
(with-paths-allowed (path1 path2 ...)
  ... Code requiring paths ...)
```
"

This is handy in case some paths expand to NIL or the empty string. Should we allow NIL as results by the way?

**Comment by aartaka** [comment]
> This is handy in case some paths expand to NIL or the empty string. Should we allow NIL as results by the way?

Why not? All of Lisp is built on `nil` :)

**Comment by Ambrevar** [comment]
This makes typing a bit more complex (but not much).
Instead of having just PATHNAME we would now have (OR NULL PATHNAME).

Also we need to clarify the difference between `""` and `nil`.  I'd say
there is probably none :)

If we allow `""` (how can we disallow it?) then we need to handle it
when we check for existence, so in all cases we probably want to create
a boolean like user-file-empty-p.  And we have a boolean, then we don't
need `nil` at all.

So I'm leaning towards not supporting `nil` ;)

**Comment by aartaka** [comment]
Yes, that is a fair reasoning :)

**Comment by Ambrevar** [comment]
See #2072 for a fix that took a rather different approach from what's discussed here.
In particular, I've opted to keep cl-pathname ;)
