### ISSUE TITLE
Cannot hint links at the bottom of a given webview

### ISSUE THREAD

**Issue by watkinsr** [atlas-engineer/nyxt#1271]
**Describe the bug**
When I try to hint links, the suggestions buffer is covering the link I want to hint at the bottom of the "previously viewable screen"
**Precise recipe to reproduce the issue**
Try to hint a link at the bottom of a given page, cannot see which prefix chars to use to hint the link
**Information**
- OS name+version:
Debian 11 testing
- Graphics card and driver:
Intel
- Desktop environment / Window manager name+version:
KDE
- How you installed Nyxt (Guix pack, package manager, build from source):
can't remember, I think it's one of the latest releases.
- Information from command copy-system-information:

  If you can't run copy-system-information, please provide the following:
  - Nyxt version (from =M-x nyxt-version= or =nyxt --version=):
  Version 2 pre-release 5 
  - Lisp implementation/version (if built from source):
 N/A (I think I installed via guix)
  - Kernel name+version:
  5.10.x
  - WebKitGTK+ | QtWebEngine version:
  Not sure how to check.

**Output when started from a shell**

**Comment by progfolio** [comment]
see #354

**Comment by jmercouris** [comment]
You can now scroll down the window and see the link hints, a bit of a pain, but it is possible!

**Comment by aartaka** [comment]
Buffer scrolling when in prompt and #2419 (that is likely to merged soon) are fixing this in the best way possible. Closing.
