### ISSUE TITLE
Fix manual: list-downloads is a command no more

### ISSUE THREAD

**Issue by aartaka** [atlas-engineer/nyxt#1277]
We need to rephrase the manual about downloads and the fact that there is no dedicated command for downloads-listing (is there?) anymore.

**Comment by Ambrevar** [comment]
I think @jmercouris removed it when we've remove the file manager, right?

**Comment by Ambrevar** [comment]
Is this superseded by `download-open-file`?

The commit that removed the command is 8ff82a0488fbde9bc1c8ed2c7e2fa70a111e9641.

**Comment by Ambrevar** [comment]
Oh wait, just got it, there is no more command to list downloads.

@jmercouris Why did you turn `list-downloads` into a function?  Looks like we are missing a feature here.

**Comment by jmercouris** [comment]
I'm not sure why I did that. I think probably I had a way to invoke `download-mode` to just create the list of downloads, anyways, I've put it back to being a command.

**Comment by Ambrevar** [comment]
Thanks!
