### ISSUE TITLE
edit-with-external-editor duplicates existing content

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#1279]
Recipe:

- Write "foo" in a text field.
- Call `edit-with-external-editor`.
- Append "bar": the editor content should be "foobar".
- Close the editor.

The HTML view now has "foofoobar" instead of "foobar".

@aadcg Any clue about this?

**Comment by aadcg** [comment]
I can't reproduce. Does it happen for all URLs?

**Comment by Ambrevar** [comment]
I experience this in GitHub comments at least, but I can't reproduce right now.
Weird...

Let's keep this open for a little while.

**Comment by Ambrevar** [comment]
OK, I know how to reproduce: when the result is _shorter_ than the initial content!

**Comment by Ambrevar** [comment]
foo
foo

**Comment by Ambrevar** [comment]
Should be fixed with c6a3b03112fc0ae015aeb8d78fa8d8b66ed079ae.

**Comment by aadcg** [comment]
Thanks!
