### ISSUE TITLE
Allow the access to WebKitResponsePolicyDecision from request-data?

### ISSUE THREAD

**Issue by aartaka** [atlas-engineer/nyxt#1285]
Pasing this FFI object in the user-facing `request-data` gives us a significant advantage:
+ It allows inspecting the MIME type, headers, status codes, and filenames of the loaded files (all through the `WebKitURIResponse` and `webkit_response_policy_decision`).
    + This could be used for a fine-grained filtering on par with sophisticated JS blockers, like Firefox's NoScript.
+ `WebKitURIRequest` is inspectable too, although less exciting things here.

The biggest disadvantage is that it's an 
- opaque 
- renderer-specific 
- C object.

**Comment by Ambrevar** [comment]
Indeed!
What about wrapping all these advantages with methods?

Nit: I prefer to use the `feature` tag over the `[FR]` prefix.  What do you think?

**Comment by aartaka** [comment]
> What about wrapping all these advantages with methods?

This still requires passing this object, at least as an accessor-less slot :)

But yes, that sounds much better than WebKit guts exposure!

> Nit: I prefer to use the `feature` tag over the `[FR]` prefix. What do you think?

Yes, that resonates with me :)

**Comment by aartaka** [comment]
Okay, we now store `gtk-request`, `gtk-response`, and `gtk-resource` in the `request-data`. Closing this as complete.
