### ISSUE TITLE
(Plaintext) editor and file-manager polishing

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#1286]
I've noticed a few things:

- Having the raw source above hinders tab-completion because it forces the user to systematically press `C-n` to complete against the first entry.
But if we move the raw source to the bottom, it gets way less obvious that it's there.  This is what Helm does though.  I suggest making explicit how many sources are present.

- `write-file` raises a condition when the file exists.  This does not seems right.
  Instead, we should overwrite the file without asking, since the user already selected the file to edit.

Thoughts?

**Comment by jmercouris** [comment]
I explicitly set it to raise a condition when the file exists so that new users do not accidentally destroy files on their system. I think that we could make it a editor-mode configurable variable. E.g., add a slot titled "overwrite-p" or something.

**Comment by Ambrevar** [comment]
write-file writes the file associated to the buffer, that's is.  How
could the user accidentally destroy files on their system?

**Comment by jmercouris** [comment]
Let's say they open a file, and they don't realize what they are doing and then save the file, thereby destroying the original contents of the file.

**Comment by Ambrevar** [comment]
Why would they save the file if they don't want to save the file?

Currently, C-s only works for new file.  It seems to be impossible to
save an already existing file.  Am I missing something?

**Comment by jmercouris** [comment]
You are correct, you are not missing anything. I wanted to make it so that one EXPLICITLY specifies they wish to overwrite a file.

**Comment by Ambrevar** [comment]
But how?

**Comment by jmercouris** [comment]
Currently they must run a extended command to be prompted for the value :overwrite.

**Comment by Ambrevar** [comment]
But why not asking the user at least for confirmation?

I'm not sure I understand your intention.  Can you detail a scenario?

**Comment by jmercouris** [comment]
We could ask the user for a confirmation, that might be an easier workflow for users.

**Comment by Ambrevar** [comment]
Yes! :)

**Comment by jmercouris** [comment]
Closing this for now, please feel free to reopen if necessary.
