### ISSUE TITLE
Build Fails on FreeBSD (GTK)

### ISSUE THREAD

**Issue by CodeJoule** [atlas-engineer/nyxt#1289]
**Describe the bug**
Building Nyxt fails on both GTK and Qt render settings on FreeBSD. I get the following error for GTK (a snip of what I think may be relevant:)
```
While evaluating the form starting at line 129, column 0
  of #P"/usr/home/tom/.local/share/common-lisp/nyxt/_build/quicklisp-client/setup.lisp":
Unhandled UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING
                                                          {1001558203}>:
  COMPILE-FILE-ERROR while compiling #<CL-SOURCE-FILE "quicklisp" "impl">

Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {1001558203}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<UIOP/LISP-BUILD:COMPILE-FILE-ERROR {10044D5E23}> #<unused argument> :QUIT T)
```
**Precise recipe to reproduce the issue**

1. Be on FreeBSD.
2. Install SBCL from the package repository.
3. Follow the instructions at https://github.com/atlas-engineer/nyxt/blob/master/documents/README.org#standard-developer-installation for the GTK rendering option.
4. Error (hopefully.)

I haven't done anything very unique, so I cannot imagine the problem.

**Information**
- OS name+version: FreeBSD 12.2-RELEASE-p4 GENERIC amd64
 - Lisp implementation/version (if built from source): SBCL 2.1.2 (from packages)
 - WebKitGTK+ version: 2.30.2

Complete stack trace as requested by @jmercouris in IRC: https://pastebin.com/JBPbxeXJ (it's really long)

**Comment by Ambrevar** [comment]
This is most probably due to the Makefile / .asd changes I've merged
yesterday.

Can anyone else reproduce?

**Comment by Ambrevar** [comment]
Can you share the exact recipe, i.e. the exact set of commands you've run?

**Comment by CodeJoule** [comment]
> Can you share the exact recipe, i.e. the exact set of commands you've run?

Sure. I tried it again just now after figuring out a simpler method of installation, but now I'm getting a different error which was the central problem before (`Can't create directory /usr/local/lib/common-lisp/alexandria/sbclfasl/`) I basically follow everything necessary for a simple GTK frontend compilation outlined here: https://github.com/atlas-engineer/nyxt/blob/master/documents/README.org#standard-developer-installation

```
# pkg install sbcl webkit2-gtk3 glib-networking libfixposix xclip enchant
$ mkdir -p ~/common-lisp
$ git clone https://github.com/atlas-engineer/nyxt ~/common-lisp/nyxt
$ cd ~/common-lisp/nyxt
$ gmake all
```

I think the problem is that it's trying to install libraries to system-level directories without permission. I got this same error when trying to install them by hand or run Nyxt from source. Someone else online group told me Quicklisp libraries should be installing to my home directory, which doesn't seem to be happening.

**Comment by Ambrevar** [comment]
Can you post the full shell output?

**Comment by CodeJoule** [comment]
Yes: https://pastebin.com/raw/n7qs8NhF

**Comment by Ambrevar** [comment]
Wait, have you installed alexandria with FreeBSD's `pkg`?

**Comment by Ambrevar** [comment]
Or any other Common Lisp package?

**Comment by CodeJoule** [comment]
> Wait, have you installed alexandria with FreeBSD's `pkg`?
> Or any other Common Lisp package?

Shoot! I didn't think to check for lisp libraries in the package manager. (I assumed the makefile would figure things out.) I am a newbie to Lisp, so I didn't have any other Common Lisp packages installed -- I'm eager to learn though!

I added `cl-alexandria-sbcl` to the list of packages to install from the first command I ran, and it built successfully! Maybe add that as a dependency to the "FreeBSD and derivatives" [dependency list](https://github.com/atlas-engineer/nyxt/blob/master/documents/README.org#gnulinux-freebsd-gtk-dependencies) in the list of packages with the `pkg` command?

**Comment by jmercouris** [comment]
You are not supposed to need `cl-alexandria-sbcl`, that is supposed to compiled automatically by the makefile in a local quicklisp dist! Something strange happened with your system! At least it works now :-)

**Comment by CodeJoule** [comment]
If I may ask here: So far, I'm noticing that running some commands in Nyxt are extremely slow (the whole program lags for about 8-10 seconds each time.) Otherwise, not running commands, it's very smooth. For an example, `C-l` to open a URL took about 10 seconds to load the "Open URL" screen with the text bar and page history at the bottom. It does the same for `C-Space`. Did I do something else wrong? :)

The few exceptions I know of are `C-[` and `C-]` which work just fine and snappy.

**Comment by jmercouris** [comment]
That should not be that slow, bringing up the prompt buffer should be almost instantaneous

**Comment by Ambrevar** [comment]
Could be a rendering issue.  Which driver do you use and do you have
direct rendering?
You can probably see this by inspecting the output of `glxinfo` in a
shell.

About Alexandria: to clarify, I meant that you should have uninstalled
the package, not the other way around :)

Can you give us a list of CL packages that got installed by FreeBSD `pkg`?

@jmercouris: I suggest we tweak our Makefile to nullify the ASDF
registries (by default -- make it configurable), so that ASDF only finds
the internal Quicklisp packages and the submodules.  This will need some testing.

**Comment by jmercouris** [comment]
I concur with your suggestion!

**Comment by CodeJoule** [comment]
>Could be a rendering issue. Which driver do you use and do you have direct rendering?
>You can probably see this by inspecting the output of `glxinfo` in a shell.

I had to install the package `glx-utils` to get this command. Here is part of the output that seems related:
`direct rendering: Yes`
Judging from `kldstat` it looks like I'm using the `i915kms.ko` driver from the `drm-fbsd12.0-kmod` package.

But I saw no issue with the graphics at all. It was very smooth scrolling and switching tabs. It just took a while for actions to happen.

>Can you give us a list of CL packages that got installed by FreeBSD `pkg`?

```
% pkg info | grep ^cl-
cl-alexandria-1.2,1            Collection of portable public domain utilities for Common Lisp
cl-alexandria-sbcl-1.2_3,1     Collection of portable public domain utilities for Common Lisp
cl-asdf-3.3.4.7,2              System definition facility for Common Lisp
%
```

**Comment by Ambrevar** [comment]
> But I saw no issue with the graphics at all. It was very smooth scrolling and switching tabs. It just took a while for actions to happen.

Strange.
If you are you familiar with Common Lisp, you could profile the
execution from a REPL.
But this is a bit involved if you've never dealt with Common Lisp before.

Ideally Nyxt would include a profiler at some point, so that regular
users could easily report performance issue.

My other hunch is that threading is super slow because SBCL was not
compiled with threading support.
Can you run the `copy-system-information` and report?

>>Can you give us a list of CL packages that got installed by FreeBSD `pkg`?
>
> ```
> % pkg info | grep ^cl-
> cl-alexandria-1.2,1            Collection of portable public domain utilities for Common Lisp
> cl-alexandria-sbcl-1.2_3,1     Collection of portable public domain utilities for Common Lisp
> cl-asdf-3.3.4.7,2              System definition facility for Common Lisp
> %
> ```

Ha!  This was your issue!  Indeed, you had cl-alexandria (the non SBCL
version) installed, and ASDF tried to build it in its installation
folder.
I don't know how cl-alexandria is meant to be used on FreeBSD, could be
a packaging mistake.

**Comment by CodeJoule** [comment]
> Strange. If you are you familiar with Common Lisp, you could profile the execution from a REPL. But this is a bit involved if you've never dealt with Common Lisp before.

I'm not familiar, but I may try at some point. This involves running Nyxt from source, right?

> My other hunch is that threading is super slow because SBCL was not compiled with threading support. Can you run the `copy-system-information` and report?

In the small "minibuffer" at the bottom:
`Warning: Error on separate thread: Subprocess # with command ("wl-copy") exited with error code 1`
Huh. That doesn't look right. Anyways, should we move this to a new issue?

> Ha! This was your issue! Indeed, you had cl-alexandria (the non SBCL version) installed, and ASDF tried to build it in its installation folder.

Maybe, but I installed both together where I previously had neither. (I don't know why I did so, it was silly of me.) I don't know what the non-SBCL version does, but when removing both of these packages, it also now works, surprisingly, when I rebuild Nyxt from scratch using the commands I posted previously. Someone must have fixed the build problems recently (or my system magically snapped into working order?) The response-lag still remains however.

**Comment by Ambrevar** [comment]
> I'm not familiar, but I may try at some point. This involves running Nyxt from source, right?

Indeed!

> In the small "minibuffer" at the bottom:
> `Warning: Error on separate thread: Subprocess # with command ("wl-copy") exited with error code 1`
> Huh. That doesn't look right. 

Are you on Wayland?

You need wl-copy on Wayland or xclip/xsel on Xorg for to copy
text to the clipboard.

Anyways, the information I'd like to have is what this command returns
in a shell:

    sbcl --noinform --eval '(print *features*)' --quit && echo

> Anyways, should we move this to a new issue?

If you don't mind, yes! :)
