### ISSUE TITLE
Faster hint-generating function

### ISSUE THREAD

**Issue by wsgac** [atlas-engineer/nyxt#1290]
I've recently been working on a simple hint generator for Eww and came up with a closure-based solution ([here](https://gist.github.com/wsgac/8893149c55d3e2684d87b622418be6bb)). I thought I'd have a look at how this is done in Nyxt. So I took a dive, refreshed my Parenscript slightly and found the relevant bit. I was curious which approach was faster and so I extracted the Nyxt code, converted it to pure CL and timed both on identical data. On a repeated sample of generating 250 hints my code turned out to be 3.5-4x faster. 

I don't know how important you deem performance in this area (keyboard-driven link selection is high on my personal priority list and among my favorite features of Nyxt). If you think it's worthwhile, I can prepare a PR incorporating my mechanism. The only thing I found troublesome is translating my code to Parenscript, so it would probably have to be called from within `(ps:lisp)`.

I'm attaching my code below, together with a usage example:
```
(defun gen-lexicographic-sequence (&key (starting-sequence "a")
				     (uppercase t))
  "Return a lambda for generating sequential, lexicographically ordered
  strings. When STARTING-SEQUENCE is provided, start with that, otherwise use
  \"a\" as a starting point. UPPERCASE controls the case of the sequences. The
  lambda produced by this function is meant to be invoked repetedly with
  FUNCALL."
  (labels ((string-to-dec (str)
	     (reduce #'(lambda (acc d) (+ (* acc 26) d))
		     (mapcar #'(lambda (c) (- (char-code c) (char-code #\a) -1))
			     (coerce str 'list))
		     :initial-value 0))
	   (dec-to-string (dec)
	     (loop
	       with dec = dec
	       with digit = nil
	       with chars = ()
	       while (plusp dec)
	       do (multiple-value-setq (dec digit)
		    (truncate (1- dec) 26))
	       do (push (code-char (+ (char-code #\a) digit)) chars)
	       finally (return (coerce chars 'string)))))
    (let ((current (string-to-dec (string-downcase starting-sequence))))
      #'(lambda ()
	  (prog1 (funcall (if uppercase #'string-upcase #'string-downcase)
			  (dec-to-string current))
	    (incf current))))))

;; Usage
(loop
 repeat 26
 with gen = (gen-lexicographic-sequence :starting-sequence "AB")
 collect (funcall gen))
=> ("AB" "AC" "AD" "AE" "AF" "AG" "AH" "AI" "AJ" "AK" "AL" "AM" "AN" "AO" "AP"
 "AQ" "AR" "AS" "AT" "AU" "AV" "AW" "AX" "AY" "AZ" "BA")
```

**Comment by Ambrevar** [comment]
Looking great!

Please send a PR!

If it's possible to pass a list of strings to JavaScript, then no need
to rewrite this in Parenscript, you can just (ps:lisp) your function.

**Comment by Ambrevar** [comment]
You contribution is very much appreciated! :)

**Comment by jmercouris** [comment]
I don't think that is a major bottleneck within our element hinting code, in any case, it wouldn't hurt to extract more of it to Lisp if possible!

**Comment by wsgac** [comment]
Thanks guys! I'll get back with a PR (or further questions) soon.

**Comment by wsgac** [comment]
I'm still a little confused about CL->JS translation. I was using `console.log` to inspect the results of `(ps:lisp)` calls. I first tried:
```
(ps:chain console (log (ps:lisp (apply #'vector (hints-generate 10)))))
```
which produced `["AB","AC","AD","AE","AF","AG","AH","AI","AJ","AK"]` as a JS object, i.e. it did not work when plugged into the hints machinery. I then tried a more desperate approach with:
```
(ps:chain console (log (ps:lisp (progn (format ps::*psw-stream*
					       "[~{\"~a\"~^,~}]"
					       (hints-generate 10))
				       (values)))))
```
the `*psw-stream*`/`(values)` being a trick I looked up in the PS test files. I'm temporarily out of ideas for how to pass the list of hints.

**Comment by wsgac** [comment]
Ok, solved the CL->JS path, the only remaining problem is how to pass a PS-generated variable (`elements-length`) to the Lisp code. When I do:
```
(ps:lisp (apply #'vector (hints-generate (ps:ps elements-length))))
```
my `hints-generate` function gets the string `elementsLength` instead of the variable value. Any ideas?

**Comment by Ambrevar** [comment]
Just guessing, but since `ps:ps` is a macro, so maybe you can quote
`ps:lisp` and unquote `(ps:ps elements-length)`.

@jmercouris Any idea?

**Comment by wsgac** [comment]
Tried that and a couple of variations. Didn't work. Meanwhile I'm trying to better understand how Parenscript works.

**Comment by Ambrevar** [comment]
Sorry if I can't help more right now.  Maybe try IRC or https://www.reddit.com/r/Common_Lisp/.

**Comment by wsgac** [comment]
Sorry for the delay. I've been away. @jmercouris I'm not really sure what you mean by jumping between renderer and core here. Could you please elaborate?

**Comment by jmercouris** [comment]
We have two processes:

1. A lisp process (the core)
2. A process that runs the web view (the renderer)

These two processes communicate via CFFI. You will have to communicate back and forth between the web view and the lisp code to generate variables based on some javascript calculations.

If you please rephrase your original question, I may be able to more effectively help you :-)

**Comment by wsgac** [comment]
Ok, let me summarize to remove confusion :)

- I have a CL function `gen-lexicographic-sequence` that generates sequence elements.

- My `hints-generate` function (also in CL) calls `gen-lexicographic-sequence` in a loop, collecting the desired number of hints (specified by function argument).

- I replace the original Parenscript function `hints-generate` by a call to my version: `(ps:lisp (apply #'vector (hints-generate ...)))`. This works fine when I pass an integer instead of `...`.

- I want to feed the call to `hints-generate` with the Parenscript variable `elements-length`. So I need a way to translate `elements-length` from the Parenscript domain to CL.

**Comment by jmercouris** [comment]
I see the problem. You will need to do the following:

1. Run a PS function to figure out how many elements exist
2. Run your hints-generate function to generate hints based on the amount of elements that exist
3. Take your list of hints, and run another PS function that will create the hint markers on the page

Does that make sense?

As I said in my earlier post, you need to go in/out of the PS/Lisp context. They are separate worlds. The only thing that they can share is return values, or arguments.

We can:

+ Call PS with any Lisp values
```
(define-parenscript xyz (a)
  (ps:chain console (log (ps:lisp a)))
```

+ Return any value from PS
```
(define-parenscript xyz ()
  10)

(setf a (xyz))
```

We cannot:
```
(defun qwe ()
  "hello")
(define-parenscript xyz ()
   (ps:lisp (qwe))
```

They are different contexts. You can think of it like CFFI if that helps. I hope that is useful!

**Comment by aartaka** [comment]
#1365 is merged and it has a hinting function heavily inspired by the one listed in this issue. Closing this issue then?
