### ISSUE TITLE
Rename enable-mode-for-buffer, etc.

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#1294]
I suggest the following renames for consistency:

- enable-mode-for-buffer -> enable-mode
- disable-mode-for-buffer -> disable-mode
- enable-mode-for-current-buffer -> enable-mode-current-buffer
- disable-mode-for-current-buffer -> disable-mode-current-buffer

Thoughts?

**Comment by jmercouris** [comment]
I don't see the advantage. I see these as simply less verbose. Can you explain how that would be improving consistency? If anything I see it as the opposite.

**Comment by aartaka** [comment]
Modes are already tied to buffers, and commands are often working on them too, so no need for extraneous `-for-buffer` suffix there. I agree with Pierre's suggestion here, as it results in less typing without meaning loss.

I can guess that consistency is about name of the command (`enable-mode`) matching the name of the underlying function (`enable-modes`). @Ambrevar, is that so?

**Comment by jmercouris** [comment]
Are modes tied to buffers though? This is a question that I do not think we have thoroughly answered!

**Comment by Ambrevar** [comment]
By consistency, I meant with almost all other commands:

- reload-buffer / reload-current-buffer
- delete-buffer / delete-current-buffer
- bookmark-url / bookmark-current-page (should we rename these ones too?)
- delete-window / delete-current-window

Another inconsistency is with

`history-tree` / `buffer-history-tree`.  I believe this last command
should be `history-tree-current`.

**Comment by Ambrevar** [comment]
Second thoughts?

**Comment by jmercouris** [comment]
My thoughts remain the same, I disagree with this change, but I am willing to accept it! :-)

**Comment by Ambrevar** [comment]
You haven't explained why you disagree.  Can you elaborate?

**Comment by jmercouris** [comment]
I think it is less verbose. Consider this:

`enable-mode`. Does this simply enable a mode? enable a mode for a buffer? Allow a mode to be enabled? What does it mean? However `enable-mode-for-buffer` is very clear.

**Comment by Ambrevar** [comment]
I find it very clear, considering modes only make sense in the context
of a buffer.

If the user does not know what a mode is, `enable-mode-for-buffer` won't
make more sense.

Finally, the docstring is displayed in M-x and says "Enable queried mode(s) for
select buffer(s)".

My approach to command naming is that the priority is on consistency
with names, while documentation is done in the docstring.

**Comment by jmercouris** [comment]
Again back to my earlier point, do modes only make sense in the context of a buffer? What if we have window modes? What if we have session modes?

In either case, I am OK with this change, I don't agree, but I accept :-D

**Comment by Ambrevar** [comment]
> Again back to my earlier point, do modes only make sense in the context of a buffer? What if we have window modes? What if we have session modes?

It's currently not the case though.

We might never have window modes, in which case "enable-mode-for-buffer"
would be a redundant name.

Should we add window modes some day, we could change the command names
then, or better, simply prompt the user for 2 sources, one the buffers
the other one the windows.

**Comment by Ambrevar** [comment]
Another idea: what if had just one `toggle-modes` (or `toggle-modes-for-buffer`) where we list all modes and pre-mark the enabled modes?

**Comment by jmercouris** [comment]
This is done now, closing.

**Comment by jmercouris** [comment]
With commit: 3ab5590f

**Comment by Ambrevar** [comment]
Actually, I'd still like to suggest some renaming mentioned in this thread

- `enable-mode-for-buffer` -> `enable-mode`
- `disable-mode-for-buffer` -> `disable-mode`
- `bookmark-current-page` -> `bookmark-current-buffer`
- `unzoom-page` -> `unzoom`
- `zoom-page` -> `zoom`
- `zoom-images-in` -> `zoom-images`
- `zoom-images` -> `unzoom-images`

**Comment by jmercouris** [comment]
I agree with the following exceptions:

Zoom-page and unzoom-page should stay, because they are about zooming the page and not the complete UI.

Bookmark should be about bookmarking the current page, we are not bookmarking a buffer.

**Comment by Ambrevar** [comment]
> Zoom-page and unzoom-page should stay, because they are about zooming the page and not the complete UI.

OK.

> Bookmark should be about bookmarking the current page, we are not bookmarking a buffer.

We are not bookmarking a "page" either, we are bookmarking the buffer
URL.

Then what about "bookmark-current-url" instead?

Also note that we ambiguously use "page" for the displayed portion of
the view (as in `scroll-page-up`), for the web view as a whole and maybe
as well in place of URLs.

**Comment by jmercouris** [comment]
All renamings have been done!
