### ISSUE TITLE
Leverage Plump for link hinting & virtual DOM?

### ISSUE THREAD

**Issue by aartaka** [atlas-engineer/nyxt#1295]
[Plump](https://github.com/Shinmera/plump) is a good parser that can allow us to produce page models really fast, and traverse these without resorting to Parenscript. Several applications there:
- Element hinting, the procedure is:
  - Call Parenscript function that will add `nyxt-identifier` attribute to _all_ the nodes in the DOM.
  - Fetch the document with `ffi-buffer-get-document` and parse it with `plump:parse`.
  - Recursively traverse Plump-produced tree, matching the hintable elements by tag name and attributes (can use [CLSS](https://shinmera.github.io/CLSS/) for that).
  - Hint the elements by the `nyxt-identifier`s stored in Plump nodes.
- Visual mode, the procedure is the same as with element hints, what changes are actions and matching criteria.
- Building a virtual DOM for page prettification / change tracking / assistive tech / anything else. We can call Parenscript functions to add/delete/modify elements with matching `nyxt-identifier`s.

The main advantage is that we'll stay in Lisp land both syntactically and semantically (not the case with Parenscript) while managing all these cases. Code will most probably shorten too.

EDIT: ad -> add.
EDIT: Add links to Plump and CLSS.

**Comment by aartaka** [comment]
#1290 can be a part of this almost-pure-Lisp transition.

**Comment by Ambrevar** [comment]
Looks like a very good idea to me!

Indeed, Parenscript can be a bit complex to grasp, while being a niche language that not many people understand well.

If Plump could cut down the amount of Parenscript and simplify our code base, it could be a net win for Nyxt!

**Comment by aadcg** [comment]
When is the white smoke coming out from your chimney, @jmercouris? I think you might have some justified concerns about this. 

If my understanding is correct, does it make sense to fetch the document with `ffi-buffer-get-document` (which runs JS) and then manipulating it with an HTML parser? What's the benefit? You could just run the JS you need.  Not to mention that web pages are a zoo of dynamic content, so perhaps we'd have to run `ffi-buffer-get-document` before each hinting/visual-mode/whatever call. 

I have no idea what I'm talking about, so these are just impressions. It is also my impression that parenscript is a jewel that I don't understand it, not even superficially.

**Comment by aartaka** [comment]
> If my understanding is correct, does it make sense to fetch the document with `ffi-buffer-get-document` (which runs JS) and then manipulating it with an HTML parser? What's the benefit? You could just run the JS you need. Not to mention that web pages are a zoo of dynamic content, so perhaps we'd have to run ffi-buffer-get-document before each hinting/visual-mode/whatever call.

There's some sense to it, as in our current state we're calling lots of JS that does lots of small actions (and some JSON-exporting) that sum up to slow-ish hinting, while the idea I suggest runs only one big action (document fetching) and then does everything in Lisp. This, I believe, should be faster, even if we fetch page source at every hinting (which can be optimized away).

The benefit of parsing things with Plump is that:
- We won't need to come up with our own `hint` classes -- we can just use (and dispatch methods over) Plump's `tag`s that are more complete and DOM-truthful.
- We already do parsing -- it's just that we parse JS-produced JSON and create non-optimized classes from it. Plump manages creating classes from markup better (i.e. faster) than we do.
- Iterating Lispy structure is simpler than having an added cognitive load of thinking about JS structure.
  - Having a lispy structure, even somewhat outdated, is still better, as it enables us to do simple page queries without constantly resorting to JS.
    - I.e., it saves us a lot more JS calls than it brings!

> I have no idea about what I'm talking about, so these are just impressions. It is also my impression that parenscript is a jewel that I don't understand, not even superficially.

These are fair concerns! Parenscript is indeed a jewel, but staying in List syntax _and_ Lisp semantics is better than only one of the two.

**Comment by jmercouris** [comment]
There are a couple of problems :-O

The common aspect shared by all of these problems is this: the DOM is stateful, taking the whole page, modifying it in Lisp and replacing it will not result in the exact same document.

Unfortunately there is significant state on a web page that is contained in elements beyond what is written in the source. For example, let's say we have an input field in which the user has entered the text "tomato". If we make some changes in Lisp and replace the whole DOM, the text "tomato" will be gone.

Another example, more tricky to solve: Let's say we have a HTML canvas element. We replace the complete DOM, the canvas element is now completely blank.

Another example: JS handlers (onclick listeners, onmouseover listeners, etc) that a website has tied to specific nodes no longer function, since the nodes they are tied to are no longer present.

This was also one of my first thoughts, however, due to limitations in how we can interact with the renderer, I do not think it is possible :-(

**Comment by aartaka** [comment]
Oh, I guess I've been unclear. What I meant was adding `nyxt-identifier` attributes to _real_ DOM, then parsing it, and calling JS functions over the `nyxt-identifier`s in _real_ DOM, based on what we infer from the _virtual_ (Plump-based) one. 

So imagine we decided to delete all the `alt-text`-less images (for whatever reason). The procedure is like that:
```
real <--- adding `nyxt-identifier`s
real --- parsing ---> virtual
virtual ---> find the `nyxt-identifier`s of all images with empty `alt-text`
real <--- delete images with given `nyxt-identifiers`
```
and not like that:
```
real --- parsing ---> virtual 
virtual <--- deleting all images with empty alt text
virtual --- serialization ---> real
```

No DOM-swapping there, we only change things that we need to change, instead of the whole page.

**Comment by aadcg** [comment]
@aartaka, if your reasoning is sound, it seems very exciting. Sadly, I can't follow it. Where can I get a grasp of what is meant by _real_ and _virtual_ DOM?

**Comment by aartaka** [comment]
The real DOM -- the one and only, the one that browser renders.
The virtual DOM -- our snapshot of the real DOM, made through Plump.

**Comment by aadcg** [comment]
Understood!
