### ISSUE TITLE
Support subbookmarks?

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#1309]
In the paper "Web Page Revisitation Revisited: Implications of a
Long-term Click-stream Study of Browser Usage" by Overdorf et al., it's suggested that bookmarks for "hub pages" (e.g. github.com has many different subsites which are the different users and projects) would be more useful if they supported _subbookmarks_.

I'm not sure yet what kind of UX we could get in practice.  Time to brainstorm!

**Comment by hendursaga** [comment]
Well, if we implement a graph or hypergraph data storage for bookmarks, history, etc, like I [suggested here](https://discourse.atlas.engineer/t/artyoms-survey-question/439), "subbookmarks" would automagically be implemented, although I suppose you'd have to make sure it's a directed and/or weighted graph, to tell which ones are more "hubs" or "subs"..

**Comment by aadcg** [comment]
Amazing idea for exploratory programming and a Nyxt extension.
