### ISSUE TITLE
Package management

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#131]
Nyxt would need a package management system for two reasons:

- Ensuring reproducible builds (since Quicklisp does not fit the bill here).
- Distributing third-party extensions.

This issue was briefly discussed in #92.

Options include:

- A custom Quicklisp distribution: it's Common Lisp so it's well integrated.

- [Qlot](https://github.com/fukamachi/qlot): similar but might introduce more dependencies.

- [Ultralisp](https://ultralisp.org/).

- For proper reproducible builds, [Guix](https://guix.info) is an (the?) ideal manager.  It could also package Nyxt's extensions.  The language is Scheme and not Common Lisp. As of now, it still requires root access to be installed (unprivileged install is a work in progress).  It does not work on macOS / BSD (yet).

We should also start thinking of a GUI.  Actually, Nyxt itself could be the GUI!

**Comment by jmercouris** [comment]
Hi Pierre, you are absolutely right about needing a package management system. From the options that you have mentioned:

I'm in favor of a custom Quicklisp distribution, it'll be the most frictionless across different OS', it is well integrated, it keeps the whole system in Lisp, and it is a proven and reliable system.

**Comment by sirikid** [comment]
In this case, Nix is gonna be better than Guix, just because it works on macOS.

**Comment by jmercouris** [comment]
@sirikid I understand your point of view, and it makes sense with regard to providing broader cross-platform support. However, I still think we should stick with a pure lisp system, and bundle all dependencies in quicklisp.

**Comment by aadcg** [comment]
Too early to think about this topic since there are still relatively few extensions and not all of them are actively maintained; Nyxt's API is likely to change and we need to move light and fast; Nyxt's audience are still advanced users who can easily setup extensions manually.

We'll return to the issue when the time is right.
