### ISSUE TITLE
Move mode files to `source/mode`?

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#1327]
This would make it a bit easier to glance at the source tree.

What's more:

- To respect the ASDF conventions (in particular to be inferred-package friendly), we could / should rename the mode packages to `nyxt/mode/MODE-NAME`, e.g. `nyxt/mode/web`.
- Same for mode tests: store them in `tests/mode`.
- Move the few remaining package-less modes to their own package.

**Comment by jmercouris** [comment]
I wanted to do this, but decided to leave it for after 2.0.0 :-)

**Comment by Ambrevar** [comment]
Sure!

**Comment by jmercouris** [comment]
In the name of consistency, shall I also move `renderers` to `renderer`?

**Comment by Ambrevar** [comment]
Fine with me.

**Comment by jmercouris** [comment]
This is done! :-)
