### ISSUE TITLE
Remove search engines from bookmarks

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#1330]
Currently bookmarks have the option to store a "search-url" (and a "shortcut"): this effectively adds the capability for each bookmark to be a search engine entry.

Thus we have a dedicated function `all-search-engines` to return the list of search engines from the 2 main sources: the buffer `search-engines` slot and the bookmarks.

But bookmark search engines don't have any interface right now, they must be added manually to the file.
So I doubt that anyone is using this feature.

In the past, I had introduced this feature because we didn't have multiple source in the minibuffer.
But now that we do, I believe that bookmark search engines are obsolete: instead, the user should define all search engines in the `search-engines` buffer slot, and we can add a new source to `set-url-from-bookmarks` to also list the fallback URLs of the search engines.

Thoughts?

**Comment by Ambrevar** [comment]
Bonus: it would simplify some code and the logic in the `search-engine.lisp` file.

**Comment by Ambrevar** [comment]
Now that #1331 is merged, I'd like to apply this change.
Should I send a patch?  @jmercouris @aadcg @aartaka ?

**Comment by aadcg** [comment]
All good from me. I don't use bookmarks, and all I need from search engines are the bangs from duckduckgo.

**Comment by aartaka** [comment]
Sound alright!

**Comment by jmercouris** [comment]
OK!

**Comment by Ambrevar** [comment]
See #1346.
