### ISSUE TITLE
Refactor buffer-list

### ISSUE THREAD

**Issue by aadcg** [atlas-engineer/nyxt#1333]
When working on #1246, I extended `buffer-list` in [this way](https://github.com/atlas-engineer/nyxt/pull/1246/commits/5f0ba564a70e005de3fe5ca763371c49a8e6aece).

My question is if it's a good pattern to continue adding keys to this method.  In `master`, it's called with keyword arguments 5 times. From those 5 times, only twice it's called with both `:sort-by-time` and `:domain`.  

The way I see it, `buffer-list` is nothing besides `(alex:hash-table-values (buffers *browser*))`. Perhaps `buffer-list` could be extended to be passed functions that could be composed and act on `(alex:hash-table-values (buffers *browser*))`, but I can't think of any clean way to do it.

EDIT: Ignore all of the changes in the title and open/closed states of this issue. All due to my silly mistakes.

**Comment by Ambrevar** [comment]
I agree that the key parameters don't compose nor grow so well.

Instead, I suggest extracting all the predicates, then filter the buffers in `buffer-list` with `alex:conjoin PREDICATES` over the unique PREDICATES &rest argument.

Wanna send a patch? :)

**Comment by aadcg** [comment]
> Wanna send a patch? :)

Sure.

**Comment by aadcg** [comment]
#1337
