### ISSUE TITLE
Replace URL with URI?

### ISSUE THREAD

**Issue by jmercouris** [atlas-engineer/nyxt#1342]
All URLs are URIs. I suggest we replace all references to "URL" in the codebase with "URI" for consistency. I suggest this for post 2.0.0.

**Comment by aadcg** [comment]
Not long ago @Ambrevar told me:

> Also we adopted the convention to always use "URL" and not "URI".

I'm confused.

**Comment by jmercouris** [comment]
I don't remember that, perhaps it happened :-D

**Comment by Ambrevar** [comment]
John, we decided the other way around ;)

**Comment by jmercouris** [comment]
Ah, so we replace all references to URI with URL? Something something getting old :-D

**Comment by Ambrevar** [comment]
Which ones?  We've been using "URL" for a while now, there should be
very few "URI" occurrences left.

**Comment by jmercouris** [comment]
For example, ffi-buffer-load, uses URI instead of URL in the defgeneric.

**Comment by jmercouris** [comment]
To be clear this is *not* about replacing URL strings with Quri:URI objects. I am talking about the usage of the word "URL" within the codebase vs "URI".

**Comment by Ambrevar** [comment]
Yes, that's what I had understood.

Let's fix ffi-buffer-load then :)

**Comment by jmercouris** [comment]
I am a little bit surprised that we voted for URL. Quri makes URIs and we are using it. They may be URLs, but they are ALWAYS URIs. Oh well, we can always change it later.

**Comment by Ambrevar** [comment]
If I recall correctly, one of the elements of the rationale was that URL
is more widespread among browsers and a more familiar terms for newcomers.

**Comment by jmercouris** [comment]
That is a good rationale. I think that at the time we were not making extensive use of `quri:uri`. Now that we are, it strikes me as a logical inconsistency!

**Comment by Ambrevar** [comment]
Yup, but there is little we can do about external libraries.
I guess it's the price to pay for leveraging other projects :)

**Comment by jmercouris** [comment]
I am still unsettled by this. I keep wanting to use a singular term, and while URI is less known, it is the semantically correct term to use. This can wait until after 2.0.0.

**Comment by Ambrevar** [comment]
URL are specific kinds of URI.
In the context of Nyxt, almost all (if not all?) are URLs.

**Comment by jmercouris** [comment]
You're correct, but we can say URI to be more general.

**Comment by Ambrevar** [comment]
If we only targeted tech-minded users, we should go with URI.

But "URI" may put back our audience a bit, so if we have to choose
between "familiarity" and "vocabulary generality", I'd go for the former.

**Comment by jmercouris** [comment]
A good point, I'm talking about in the codebase though, not in the UI.

**Comment by Ambrevar** [comment]
John Mercouris ***@***.***> writes:

> A good point, I'm talking about in the codebase though, not in the UI.

Then we would have to deal with both, and this would be confusing, since
we would always have to ponder "should I use URL or URI here?"

Right now we never write "URI", so it's simpler for us.

**Comment by aadcg** [comment]
I'd use URL in the codebase.

**Comment by aartaka** [comment]
I'm on the side of URL too! Closing this then?

**Comment by Ambrevar** [comment]
Maybe we should first remove the last occurences of "URI" in the code, as in the ffi-methods.
Does someone have time to send a patch?

**Comment by aadcg** [comment]
> Does someone have time to send a patch?

I can do that.
