### ISSUE TITLE
set-url-nosave-buffer should not set URL of non-nosave buffer, right?

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#1345]
Current, if I'm in a regular buffer and call `set-url-nosave-buffer`, confirm on a URL, it loads this URL in the current, non-nosave buffer.

This does not seem to be the intended behaviour.
Instead, I think the first action should test whether the current URL is a nosave buffer:
- if it is, call buffer-load.
- if it is not, call `new-nosave-buffer-load`.

Thoughts? @aartaka

**Comment by jmercouris** [comment]
Correct, we should fix this.

**Comment by aartaka** [comment]
I remember fixing this 0_o

In any way, yes, we should fix this!

**Comment by aartaka** [comment]
I'd simply remove the `buffer-load` from `set-url-nosave-buffer`, though. Reason is that user will most probably rely on plain `set-url` to set URL of a current buffer, even when in nosave one, because muscle memory.

**Comment by aartaka** [comment]
This was resolved by #1348.
