### ISSUE TITLE
How to select nothing in the prompt buffer?

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#1352]
There is a little "hole" in our prompt buffer user experience: some prompt buffer are meant to return a list of things, possibly an empty one, but there is no way to return "nothing".

An example of this can be seen with `toggle-attributes-display` (`C-]` in a prompt-buffer).

Another example, with a workaround this time, is when selecting a tag for bookmarks: I've added a special source for new tags, including the empty one.  If the user select just the empty tag, since the caller discard the empty string (`""`) it amounts to no tag at all.

We need a better UX.  Even the workaround seems a bit clunky. 
Any suggestion?

**Comment by aadcg** [comment]
Thanks for writing this up.  I noticed it when working on recursive search but didn't write it up.

I'm afraid I don't have any suggestions.

**Comment by jmercouris** [comment]
I think we could add a source called the "empty source" that has an option "return nothing". What do you think?

**Comment by Ambrevar** [comment]
That could do, but this would only work if there is no mark.

I'm afraid this use case would be a bit confusing:

- C-space
- C-]
- It shows 2 sources:
  - The empty source at the top
  - The source with some marked attributes at the bottom.
- The user selects the first element empty source element.

Expectation: disable all attributes but the default one.
Result: no change, since some attributes were marked.

Can we avoid this ambiguity and make the behaviour explicit?

**Comment by jmercouris** [comment]
What if the text said "unmark all and select nothing"?

**Comment by Ambrevar** [comment]
Ha!  That's interesting: a source with an action that discards all other
elements.

I'll send a pull request so we can test this.
