### ISSUE TITLE
Non-web-buffer (editor, lisp REPL) should re-use bindings

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#1355]
Currently enabling VI or Emacs bindings for web-browsers does not enable them for other buffers, like the editor or the Lisp REPL.

Maybe we should make that more "do what I want".  Thoughts?

**Comment by aadcg** [comment]
I think we might want to discuss smth more general. The modes we have (which we can think of them as `minor-modes` in Emacs' parlance), could be local or global. What we have, afaik, are local minor modes.

Indeed, some modes (like this one) could be global, i.e. enabled for all buffers.

**Comment by Ambrevar** [comment]
Indeed, this could be one way to handle it.
Sadly I'm not sure we have time to introduce it before 2.0.

Another option would be to have `nyxt::lisp-repl', `make-editor-buffer`
or `editor-buffer`, etc., _append to the list of modes / default modes_
on instantiation.

This would, it would properly inherit from the `buffer` default-modes which would result
in the intended behaviour.

Does that make sense?

**Comment by aadcg** [comment]
Given the time constraint, that seems a sound way to approach it.

**Comment by edgar-vincent** [comment]
Note: this should include the prompt buffer :)

**Comment by Ambrevar** [comment]
> In other words, allow the user to configure the general case, and optionally override it in the more specific case. What do you think?

This is sound, but isn't it what we already do?

The problem is that web-buffers, prompt-buffers, REPL buffers, etc. all
_specify_ their own default modes, thus overriding the default.

**Comment by jmercouris** [comment]
I've been thinking about this, and I've come up with no resolution beyond removing the default-modes.

**Comment by jmercouris** [comment]
That is not to say I've not come up with other solutions, but they've been quite unsatisfactory...

**Comment by jmercouris** [comment]
Perhaps we need another new slot like `user-modes` or something?

**Comment by Ambrevar** [comment]
> Perhaps we need another new slot like `user-modes` or something?

I think that would only postpone the problem.  Example:

- A set default-modes.
- B inherits from A and sets user-modes
- C inherits from B.

At this point, C must set either default modes or user modes, thus
overriding the user configuration of B or A.

I have an idea in mind, I'll send a proposal later.

**Comment by Ambrevar** [comment]
See #1411 for my proposal using regular CLOS.

**Comment by jmercouris** [comment]
I believe this has been fixed :-)
