### ISSUE TITLE
Rename gobject-gtk to gi-gtk or gigtk

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#1361]
gobject-gtk is inaccurate, since the renderer is not about gobject but rather "GObject Introspect" (the relationship between the two is like what MOP is to CLOS).

What about renaming it to `gi-gtk` instead or even shorter, `gigtk`?

Besides, the system naming is inconsistent: the original renderer is named "gtk" but the gobject-gtk renderer is named "gobject/gtk" (notice the slash).  Beside being inconsistent, the slash means "subsystem" for ASDF, but there is no "gobject" parent system here.

Thoughts?

**Comment by jmercouris** [comment]
I thought there might also be a gobject/qt at some point which motivated my original decision. I'm OK with "gi-gtk".

**Comment by Ambrevar** [comment]
> I thought there might also be a gobject/qt at some point which motivated my original decision. I'm OK with "gi-gtk".

"gobject/qt" would in fact also use GObject Introspection.  So same
problem there :)

I'll send a patch for gi-gtk.

**Comment by jmercouris** [comment]
Well, the "Nyxt/gobject" system need not exist in my head, it was just a "virtual" class we were inheriting from... anyways :-D

**Comment by Ambrevar** [comment]
> Well, the "Nyxt/gobject" system need not exist in my head, it was just a "virtual" class we were inheriting from... anyways :-D

Even then, why would we have a "nyxt/gobject" virtual system, and not
one for "gtk"?
I find it confusing :p

**Comment by jmercouris** [comment]
well, we could have had "nyxt/cffi/gtk", but I did not have enough foresight!

**Comment by Ambrevar** [comment]
Exactly :)

In all cases, I prefer flat hierarchies, unless there is an actual
benefit in having a dedicated level.  In this case, the intermediary
level "cffi" or "gi" is never used, so I'd rather get rid of it, it
makes things simpler in my opinion.
