### ISSUE TITLE
Nyxt extension storage location

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#1367]
Something that completely slipped my mind: we need to decide where extensions ought to be loaded from by default.  `~/common-lisp` is no good since it's not Nyxt-specific and could conflict with CL devs local libraries.

`~/.local/share/nyxt/extensions/`?

Any better suggestion?

**Comment by jmercouris** [comment]
Anywhere on `D I S K` is OK I think. Why should we put them in a specific directory?

**Comment by Ambrevar** [comment]
Because we need to tell our users where to put them, and this location cannot change after 2.0.

Storing to ~/common-lisp or any default ASDF location can raise conflicts.

Users should be free to set wherever they want extensions to be loaded, but we need a default to make it as simple as "download it to FOO/PATH and that's it!".

**Comment by Ambrevar** [comment]
Example registry we could push to `asdf:*default-source-registries*`:

```lisp
(defun nyxt-source-registry ()
    `(:source-registry
      (:tree ,(uiop:xdg-data-home "nyxt/extensions/"))
      :inherit-configuration))
```

**Comment by jmercouris** [comment]
I believe that is deprecated, no?

**Comment by Ambrevar** [comment]
What is deprecated?

**Comment by jmercouris** [comment]
The usage of `asdf:*default-source-registries*`. I may be incorrect of course, but I remember something of that nature.

**Comment by Ambrevar** [comment]
The opposite actually :)
asdf:*default-source-registries* is the modern way to do things,
It's `asdf:*central-registry*` that's deprecated.

**Comment by jmercouris** [comment]
Aha! Whoops!
