### ISSUE TITLE
Review and maybe move out notification.lisp

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#1369]
notification.lisp has ancient code that's been rotting for a while.

It's rather trivial though, so it probably does not cost much to review it, test it and keep it for 2.0.

**Comment by Ambrevar** [comment]
In any case, notify-osd should be at least an _optional_ dependency (e.g. in the .deb, etc.).

**Comment by jmercouris** [comment]
It needs to be rethought actually. I think we can just remove notification.lisp and remove the one place it appears in the codebase (during init file errors).

**Comment by Ambrevar** [comment]
> It needs to be rethought actually.

Can you expand?

**Comment by jmercouris** [comment]
I've expanded a little bit upon it in the pull request, basically it assumes all notification programs have the exact same interface.
