### ISSUE TITLE
.deb file installation requires removal of rofication

### ISSUE THREAD

**Issue by scmbradley** [atlas-engineer/nyxt#1373]
Trying to install nyxt using the deb file (using `gdebi`) warned me that installation would require the removal of the `i3xrocks-rofication` package. Why would a browser require the removal of a notification app?

This is with ubuntu and the `regolith` window manager.

**Comment by jmercouris** [comment]
I can't imagine either.. you can see that our .deb only adds packages... perhaps there is some conflict.

**Comment by scmbradley** [comment]
I noticed that the dependencies included `notify-osd` which might be the conflict?

**Comment by jmercouris** [comment]
Perhaps, I'm not sure we will keep `notify-osd`, I believe we were thinking about removing it.

**Comment by jmercouris** [comment]
Sorry about the issues, hopefully we can figure it out!

**Comment by Ambrevar** [comment]
Indeed, notify-osd should be an optional dependency.  This needs to be fixed in the .deb generation.

**Comment by scmbradley** [comment]
I had actually been meaning to try out another notification app anyway, so the issue prompted me to try `dunst`! Thanks for the quick reply and thanks for developing `nyxt`

**Comment by Ambrevar** [comment]
Glad you like it ;)

**Comment by jmercouris** [comment]
I'm working on this now.

**Comment by jmercouris** [comment]
This has now been fixed on master! Thank you for reporting!
