### ISSUE TITLE
Bookmark tag filtering from the prompt-buffer

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#1375]
I've recently removed the bookmark search-engine feature, preferring to list search-engine URLs as a set-url source instead.

However, it could be useful to still have bookmark shortcuts, e.g. typing "wiki" would match the bookmark with the "wiki" shorcut at the top.

In otherwords, this would allow the user to open a known bookmark by typing some known characters.

Thoughts?

**Comment by jmercouris** [comment]
What would be the semantic difference between that and a unique tag?

**Comment by aartaka** [comment]
+1 on tags :)

**Comment by Ambrevar** [comment]
Good point.

We lack a good interface for tags.  We need to work it out.

**Comment by jmercouris** [comment]
You can filter bookmark tags from the prompt buffer, today :-)
