### ISSUE TITLE
Clarify extension-loading in the manual / fix *extensions-path*

### ISSUE THREAD

**Issue by aartaka** [atlas-engineer/nyxt#1376]
Right now, for extensions to be loaded, one needs to copy extension files (i.e., extension.lisp, package.lisp, extension.asd) to the `*extensions-path*`. This is
- non-obvious, as one'd (or is it just me) expects copying directories with checked-out extensions (i.e., `~/git/extension` -> `~/.local/share/nyxt/extensions/extension`).
- Error-prone, as there is package.lisp in almost every extension.

We either need to expand the manual on extension loading or change the `*extensions-path*` definition to allow sub-directories. As an example, here's how ASDF itself does it with one of default registries:
``` lisp
(defun default-system-source-registry ()
    `(:source-registry
      ,@(loop :for dir :in (xdg-data-dirs "common-lisp/")
              :collect `(:directory (,dir "systems/"))
              :collect `(:tree (,dir "source/")))
      :inherit-configuration))
```

Am I missing something?

**Comment by Ambrevar** [comment]
Our source registry already allows for trees:

```lisp
(defun nyxt-source-registry ()
  `(:source-registry
    (:tree ,(expand-path *extensions-path*))
    :inherit-configuration))
```

It works for me.

Can you share your 
`asdf:*default-source-registries*`?

**Comment by aartaka** [comment]
i.e. putting this
```
(load-after-system :nx-search-engines (nyxt-init-file "search-engines.lisp"))
(load-after-system :nx-kaomoji (nyxt-init-file "kaomoji.lisp"))
(load-after-system :nx-ace (nyxt-init-file "ace.lisp"))
```
in the init.lisp does not load extensions.

**Comment by Ambrevar** [comment]
What if you just asdf:load-system?  Does it work?

What does `asdf:locate-system :nx-kaomoji` return from a REPL where Nyxt
is loaded?

**Comment by aartaka** [comment]
> What if you just asdf:load-system? Does it work? 

Same result -- nothing loads.

> What does `asdf:locate-system :nx-kaomoji` return from a REPL where Nyxt is loaded?

``` lisp
CL-USER> (asdf:locate-system :nx-kaomoji)
NIL
NIL
NIL
NIL
NIL
NIL
```

**Comment by Ambrevar** [comment]
Can you run (nyxt:nyxt-source-registry) in this REPL?

**Comment by aartaka** [comment]
Sure! Here it is:
```
CL-USER> (nyxt:nyxt-source-registry)
(:SOURCE-REGISTRY (:TREE "/home/aartaka/.local/share/nyxt/extensions")
 :INHERIT-CONFIGURATION)
```

**Comment by Ambrevar** [comment]
I know what's wrong!  The trailing "/" is missing.
Can you try again and ensure a trailing slash at the end of the path?

**Comment by aartaka** [comment]
But wait, it's what `expand-path` generates!

**Comment by aartaka** [comment]
Strange... ASDF does not find packages even if the pathname does have a trailing slash :confused:

**Comment by Ambrevar** [comment]
I've tested again: the slash is not the problem indeed and it does not work for me either by default.
Running `(asdf:clear-configuration)` after startup fixes it though, which is expected.

Shall we run it automatically then?  Only when an init file is found?
Thoughts?

**Comment by aartaka** [comment]
Sounds around right!

**Comment by Ambrevar** [comment]
Done in b619dcf3345c63a9d6e9de245dec7689613a4426.

**Comment by aartaka** [comment]
It works, thanks!

**Comment by Ambrevar** [comment]
You're welcome :)
(Gotta say, I like 1-liner fixes!)
