### ISSUE TITLE
Build error: ASDF tries to compile system-installed CL libraries

### ISSUE THREAD

**Issue by etclub** [atlas-engineer/nyxt#1377]
I tried to build it on Archlinux, but failed.

It reports:

```
Unhandled SB-INT:SIMPLE-FILE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING

                                                {10018803D3}>:

  Failed to find the TRUENAME of /usr/share/common-lisp/source/cl-ppcre/cl-ppcre-unicode/packages.lisp:

    No such file or directory
```

**Comment by Ambrevar** [comment]
Can you report the full error output?
Which AUR package did you use?  Which version?

**Comment by etclub** [comment]
After uninstalling the `cl-ppcre` package, now I can install `aur/nyxt 2.pre.release.7-3` without any error.

**Comment by Ambrevar** [comment]
Thanks for confirming.  I'll to fix this bug as soon as possible.

**Comment by Ambrevar** [comment]
@etclub Can you try to reinstall the `cl-ppcre` package with pacman and then install the latest `nyxt-browser-git`?

**Comment by jmercouris** [comment]
I just installed `cl-ppcre` on Ubuntu which also installed flexi-streams etc. I then reinstalled from our Deb, and it worked fine. No problems.

**Comment by Ambrevar** [comment]
The test is to build Nyxt, not to install the prebuilt version from the
.deb :)

**Comment by Ambrevar** [comment]
Also I don't know if Ubuntu has this issue, because the cl-ppcre package
might be packaged in a way that it does not trigger this bug.

So far only Arch Linux users have reported this issue.

**Comment by jmercouris** [comment]
I'm not going to install Arch Linux to test. It sounds to me like a packaging issue with their system.

**Comment by Ambrevar** [comment]
Whatever issue their cl-ppcre package may have, it shows that our
Makefile is not setting ASDF registries to NIL properly.

This means that we still have the same old issue in our build system
where the libraries that get picked up are the ones found in
~/common-lisp, /usr/share, etc.  Which would lead to a broken build, for
instance if cl-webkit is out of date.

My hunch is that it's Quicklisp that's finding the libs on the system.

**Comment by edgar-vincent** [comment]
It seems to work fine here when building `nyxt-browser-git` after installing the `cc-ppcre` Arch package.

**Comment by Ambrevar** [comment]
@jmercouris: OK, problem solved, no need to test yourself!

**Comment by jmercouris** [comment]
Great! I asked @edgar-vincent on IRC, and he was very helpful, thank you so much!!!
