### ISSUE TITLE
Deleting a buffer should switch back to the previous one

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#1379]
Instead it seems that we are put back to the one before.

**Comment by jmercouris** [comment]
Not sure what you mean, can you please rephrase?

**Comment by Ambrevar** [comment]
Example recipe:

- Have 3 buffers, A, B and C.
- Go to B.
- Go to C.
- Delete current buffer (C).

Expected result: B should be displayed.
Actual result: it's A.

**Comment by aartaka** [comment]
I cannot reproduce on master.

**Comment by Ambrevar** [comment]
Me neither...
