### ISSUE TITLE
emacs-mode in lisp repl

### ISSUE THREAD

**Issue by franburstall** [atlas-engineer/nyxt#1381]
**Describe the bug**

I have `emacs-mode` set for internal-buffers via `define-configuration`.   However,  when I fire the lisp repl, `emacs-mode` is not active.  

**Information**
- OS name+version: Debian 10
- Graphics card and driver: GeForce GTX 1050 Ti]
- Desktop environment / Window manager name+version: EXWM
- How you installed Nyxt (Guix pack, package manager, build from source): Source
- Information from command copy-system-information:

Nyxt version: 2-pre-release-7-8-g0214c7c7
Renderer: GI-GTK
Operating system kernel: Linux 4.19.0-16-amd64
Lisp implementation: SBCL 2.1.1
Features: (SLYNK WEBKIT2 WEBKIT2-2.30 WEBKIT2-TRACKING WEBKIT2-MUTE
           WEBKIT2-EMOJI WEBKIT2-MEDIA WEBKIT2-SANDBOXING GTK-3-22 GTK-3-20
           GTK-3-18 GTK-3-16 GTK-3-14 GTK-3-12 GTK-3-10 GTK-3-8 GTK-3-6 GTK-3-4
           GTK GDK-3-22 GDK-3-20 GDK-3-18 GDK-3-16 GDK-3-14 GDK-3-12 GDK-3-10
           GDK-3-8 GDK-3-6 GDK-3-4 CAIRO-1-10 CAIRO-1-12 GDK-PIXBUF GLIB-2-30
           GLIB-2-32 GLIB-2-34 GLIB-2-36 GLIB-2-38 GLIB-2-40 GLIB-2-42
           GLIB-2-44 GLIB-2-46 GLIB-2-48 GLIB-2-50 GLIB-2-52 GLIB-2-54
           GLIB-2-56 GLIB-2-58 GLIB FSET-EXT-STRINGS CUSTOM-HASH-TABLE-NATIVE
           SWANK PLUMP-UTF-32 CL-PPCRE-UNICODE GLOBAL-VARS DECLARE-TYPES
           PARENSCRIPT SBCL+SAFE-STANDARD-READTABLE NAMED-READTABLES
           21BIT-CHARS CHUNGA GRAY-STREAMS FAST-IO-SV FAST-IO
           SBCL-USES-SB-ROTATE-BYTE ASDF-SYSTEM-CONNECTIONS CLOSER-MOP
           SPLIT-SEQUENCE CL-UNICODE FLEXI-STREAMS CL-PPCRE
           CL-JSON-DOUBLE-FLOAT-IS-SUBSUMED CL-JSON-SINGLE-FLOAT-IS-SUBSUMED
           CL-JSON-CLOS CL-JSON BORDEAUX-THREADS THREAD-SUPPORT FLAT-NAMESPACE
           X86-64 UNIX CFFI FLAT-NAMESPACE SEQUENCE-EMPTYP QUICKLISP ASDF3.3
           ASDF3.2 ASDF3.1 ASDF3 ASDF2 ASDF OS-UNIX NON-BASE-CHARS-EXIST-P
           ASDF-UNICODE X86-64 GENCGC 64-BIT ANSI-CL COMMON-LISP ELF
           IEEE-FLOATING-POINT LINUX LITTLE-ENDIAN PACKAGE-LOCAL-NICKNAMES
           SB-LDB SB-PACKAGE-LOCKS SB-THREAD SB-UNICODE SBCL UNIX)

**Comment by Ambrevar** [comment]
This is #1355 I believe.

**Comment by franburstall** [comment]
Agreed.  I will close this one then.
