### ISSUE TITLE
Ensure set-permissions works when file-attributes fails

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#1382]
I've recently added a provision to `set-permissions for when file-attributes would fail (e.g. running the Ubuntu 20.04 deb on a Ubuntu 18.04).  It does not seems to work though (I don't get why), this needs to be investigated.

**Comment by Ambrevar** [comment]
We can replace `file-attributes` with `iolib/os:file-permissions`.
It's setf-able.

We just need to test on both ubuntu 18.04 and 20.04 again.

**Comment by Ambrevar** [comment]
Fixed with ae7010a4c0e2e68ae618297f181ade0600d321d2.

**Comment by jmercouris** [comment]
I demand the puntos!

**Comment by jmercouris** [comment]
I was just joking about demanding credit for the idea :-D

**Comment by Ambrevar** [comment]
You deserve it, I was going a much more complicated road :/

That said, it would still be nice to see if the 20.04 .deb works on
other distributions like Ubuntu 18.04.

**Comment by Ambrevar** [comment]
If you've got the time to test it, that'd be great! :)
