### ISSUE TITLE
Make VI and Emacs mode work in follow-hint & friends

### ISSUE THREAD

**Issue by aartaka** [atlas-engineer/nyxt#1383]
It's about `element-hint-mode` that we hard-code in `query-hints` (element-hint.lisp, L133):
``` lisp
(let ((result (prompt
                   :prompt prompt
                   ;; Here!         vvvvvvvvvvvvvvvvv
                   :default-modes '(element-hint-mode prompt-buffer-mode)
                   :history nil
                   :sources
                   (make-instance
                    'hint-source
                    :multi-selection-p multi-selection-p
                    :constructor (add-element-hints))
                   :after-destructor
                   (lambda ()
                     (with-current-buffer buffer
                       (remove-element-hints))))))
      (funcall function result))
```

This overrides any mode configuration one might have had for `prompt-buffer` including keybindings.

How do we go around this? MOP? 

This can be a wider problem, though: how do we add a specific mode to the prompt-buffer while retaining user configuration? Maybe add an `:additional-modes` argument to `prompt` and use it instead of `:default-modes`?

**Comment by Ambrevar** [comment]
I think this is linked to #1355 (but the fix is not the same).

I think :additional-modes is a good option.
I'll sleep over it.

**Comment by Ambrevar** [comment]
Can be closed now, right?

**Comment by aartaka** [comment]
Right!
