### ISSUE TITLE
Add a (setf actions) method to mirror actions

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#1385]
See discussion in https://github.com/atlas-engineer/nyxt/pull/1371#issuecomment-833504558.

**Comment by aadcg** [comment]
It's possible to move issues from one repository to the other as well. Should we keep this issue open in this repo (Nyxt's)?

**Comment by aartaka** [comment]
No, implementing this logic is a matter of adjusting to Prompter APIs (if they change in this regard).
