### ISSUE TITLE
Cut-off Modeline on HighDPI settings

### ISSUE THREAD

**Issue by nagy** [atlas-engineer/nyxt#1388]
**Describe the bug**
Cut-off Modeline on HighDPI settings

**Precise recipe to reproduce the issue**
On a HighDPI display and on a recent `nixos-unstable` channel I get a cut-off modeline when I run this:

```sh
nix-shell -p nyxt --run nyxt
```

In case you dont have a HighDPI settings enabled, I think you can switch it on for only one call with

```sh
GDK_DPI_SCALE=2 nyxt
```
![nyxt](https://user-images.githubusercontent.com/692274/117656869-298ab180-b199-11eb-81a5-eb68abcf3bf2.png)

**Information**
- OS name+version: NixOS unstable
- Graphics card and driver:
- Desktop environment / Window manager name+version:
- How you installed Nyxt (Guix pack, package manager, build from source): `nix-shell -p nyxt --run nyxt`
- Information from command copy-system-information:

  If you can't run copy-system-information, please provide the following:
  - Nyxt version (from =M-x nyxt-version= or =nyxt --version=): Nyxt version 2
  - Lisp implementation/version (if built from source):
  - Kernel name+version:
  - WebKitGTK+ | QtWebEngine version:

**Output when started from a shell**

**Comment by jmercouris** [comment]
Thank you for your interest in Nyxt! I think you'll have to update your configuration to change the height of the status area.

Something along the lines of:

```
(define-configuration status-buffer
  ((height 40)))

```

**Comment by nagy** [comment]
> Thank you for your interest in Nyxt!

And thank you for this interesting project!

Your suggested config worked much better:

![nyxt2](https://user-images.githubusercontent.com/692274/117659780-a66b5a80-b19c-11eb-9701-8892ded7d111.png)

Would it make sense to adjust the status-buffer scale depending on the DPI scale per default, so that new users dont have to configure anything?

**Comment by jmercouris** [comment]
That sounds too hard to do now, but we can try it in the future :-)

**Comment by tulth** [comment]
I have a similar issue; i am using ```.Xresources```:
```
Xft.dpi: 192
```

Some screen shots of cutoff text in various areas:
modeline:
![image](https://user-images.githubusercontent.com/11246388/140613799-b44e5cc4-2d12-49f1-a532-66ce203f5799.png)

top of github issues bar is sized strangely:
![image](https://user-images.githubusercontent.com/11246388/140613818-c5a8769f-130d-462a-8ea6-a3d95be37533.png)

It is almost as if widget sizes are computed to the value before scaling is applied
