### ISSUE TITLE
M-return should do nothing in the action prompt buffer

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#1396]
Press M-return twice, and you end up with a prompt buffer showing `identity`.

You can even press M-return more than that twice, it goes on ad infinitum.

This is confusing to say the least, if not useless.

Shall we make `M-return` a no-op in the action prompt buffer?

**Comment by jmercouris** [comment]
Yes, that would be a good solution. It may impose unforseen limitations- should that time come around, we can change it.

**Comment by Ambrevar** [comment]
Fixed with d8dfba624c522c8efbc92fd49113bcf6dcee5fbe.
