### ISSUE TITLE
HiDPI displays

### ISSUE THREAD

**Issue by aadcg** [atlas-engineer/nyxt#1401]
Setting the GDK variables, as suggested in the manual, doesn't resize the UI anymore. 

Any ideas?

**Comment by jmercouris** [comment]
I guess you could change font sizes, and the prompt buffer height etc

**Comment by Ambrevar** [comment]
Could it be because we've switched renderer and are using
GObject-Introspection now?

@aadcg: Can you reproduce with the old renderer?

**Comment by aadcg** [comment]
Sorry, my mistake here.  Setting the variables does make a difference.  For some reason I was under the impression that the result would be more noticeable. All good!

**Comment by Ambrevar** [comment]
Thanks!
