### ISSUE TITLE
Move bookmarklets to nyxt/web-mode?

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#1406]
By definition they are javascript, so they run over the _content_ of the web page, thus they should belong to nyxt/web-mode, nah?

**Comment by jmercouris** [comment]
Hm, you could make that argument, I'm not very convinced

**Comment by Ambrevar** [comment]
Can you elaborate?

The issue with putting them in `nyxt` is that they become global, so
it's a bit polluting.

Secont point is consistency: all bookmarklets related to content
manipulation, like zooming.  That's what web mode commands do
(zoom-in-page, etc.).

The rationale of the separation between base-mode and web-mode is the
following:

- Base mode is for anything global that does not relate to the _content_
  of a buffer.

- Web mode is for the (HTML) content of a buffer.

**Comment by jmercouris** [comment]
The rationale is clear. If they belong to a mode, web mode is the logical choice. I guess I am just not as concerned about polluting the namespace. It is our own namespace after all :-O!

**Comment by Ambrevar** [comment]
See my suggestion in #1408.

**Comment by Ambrevar** [comment]
>  It is our own namespace after all 

`:nyxt` is `:use`d by `:nyxt-user`, so we must be careful about what we export in there.  This is the critical API part that carries all the technical debts of Nyxt :p
