### ISSUE TITLE
Nyxt is not loading a local valid HTML file

### ISSUE THREAD

**Issue by pdelfino** [atlas-engineer/nyxt#1412]
**Describe the bug**

Expected: Nyxt would execute/interpret a local valid HTML file.

Returned: "page could not be loaded"

Control group: the same file under the same conditions is successfully loaded using Firefox

**Precise recipe to reproduce the issue**

After running on the shell:
`nyxt index.html`

Nyxt returns:
<INFO> [16:16:19] Nyxt already started, requesting to open URL(s): index.html

However, it fails to load the **local** file, and the browser's GUI shows:

> Page could not be loaded.
> 
> URL: index.html
> 
> Please check:
> 
> Your Internet connection.
> That the URL is valid.
> That the resource at the URL is reachable.
> 

To reproduce you need to use a valid HTML file and run `nyxt example.html` on your shell.

**Information**

- OS name+version: 
       Ubuntu 20.04.2 LTS
       
- Graphics card and driver: 
       product: Iris Plus Graphics 640
       configuration: driver=i915 latency=0

- Desktop environment / Window manager name+version:
       Name: GNOME Shell 3.36.7
       Window manager's "showing the desktop" mode: OFF

- How you installed Nyxt (Guix pack, package manager, build from source): 
       package manager

- Information from command copy-system-information: 
     Nyxt version: 2-pre-release-7
     Renderer: GI-GTK
     Operating system kernel: Linux 5.8.0-53-generic
     Lisp implementation: SBCL 2.1.0.0.HEAD.1-46cb065
     Features: (WEBKIT2 WEBKIT2-2.30 WEBKIT2-TRACKING WEBKIT2-MUTE WEBKIT2-EMOJI
           WEBKIT2-MEDIA WEBKIT2-SANDBOXING GTK-3-22 GTK-3-20 GTK-3-18 GTK-3-16
           GTK-3-14 GTK-3-12 GTK-3-10 GTK-3-8 GTK-3-6 GTK-3-4 GTK GDK-3-22
           GDK-3-20 GDK-3-18 GDK-3-16 GDK-3-14 GDK-3-12 GDK-3-10 GDK-3-8
           GDK-3-6 GDK-3-4 CAIRO-1-10 CAIRO-1-12 GDK-PIXBUF GLIB-2-30 GLIB-2-32
           GLIB-2-34 GLIB-2-36 GLIB-2-38 GLIB-2-40 GLIB-2-42 GLIB-2-44
           GLIB-2-46 GLIB-2-48 GLIB-2-50 GLIB-2-52 GLIB-2-54 GLIB-2-56
           GLIB-2-58 GLIB FSET-EXT-STRINGS CUSTOM-HASH-TABLE-NATIVE SWANK
           PLUMP-UTF-32 GLOBAL-VARS DECLARE-TYPES PARENSCRIPT NAMED-READTABLES
           21BIT-CHARS CHUNGA FLEXI-STREAMS CLOSER-MOP CL-PPCRE-UNICODE
           CL-UNICODE BORDEAUX-THREADS SPLIT-SEQUENCE GRAY-STREAMS FAST-IO-SV
           FAST-IO SBCL-USES-SB-ROTATE-BYTE ASDF-SYSTEM-CONNECTIONS
           CL-JSON-CLOS CL-JSON THREAD-SUPPORT CL-PPCRE FLAT-NAMESPACE X86-64
           UNIX CFFI FLAT-NAMESPACE SEQUENCE-EMPTYP QUICKLISP ASDF3.3 ASDF3.2
           ASDF3.1 ASDF3 ASDF2 ASDF OS-UNIX NON-BASE-CHARS-EXIST-P ASDF-UNICODE
           X86-64 GENCGC 64-BIT ANSI-CL COMMON-LISP ELF IEEE-FLOATING-POINT
           LINUX LITTLE-ENDIAN PACKAGE-LOCAL-NICKNAMES SB-CORE-COMPRESSION
           SB-LDB SB-PACKAGE-LOCKS SB-THREAD SB-UNICODE SBCL UNIX)

**Output when started from a shell**
     $ nyxt
     <INFO> [16:31:30] Listening to socket "/home/pedro/.local/share/nyxt/nyxt.socket".
     Nyxt version 2-pre-release-7
     <INFO> [16:31:31] Loading Lisp file "/home/pedro/.config/nyxt/auto-config.lisp".
     WARNING: Key was bound to LOAD-FILE
     WARNING: Key was bound to SET-URL-NEW-NOSAVE-BUFFER

**Speculation**

     I am still a noob around Nyxt but maybe this problem is connected to this [issue](https://github.com/atlas-engineer/nyxt/issues/1258)

**Comment by pdelfino** [comment]
Hi,

I was trying to test this and especially ** learn how it was fixed **. Unfortunately, it did not work out for me. Not sure if it is something wrong that I did. But the bug seems to persist. In addition, I had a hard time with the documentation.

After fetching and pulling the source code, I run the current master version of Nyxt using SLY's REPL inside Emacs:


    CL-USER> (require: asdf)
    NIL
    CL-USER> (asdf: load-asd "/home/pedro/common-lisp/nyxt/nyxt.asd")
    # <ASDF / FIND-SYSTEM: DEFINE-OP>
    # <ASDF / PLAN: SEQUENTIAL-PLAN {10030B14A3}>
    CL-USER> (ql: quickload: nyxt / gi-gtk)
    To load "nyxt / gi-gtk":
      Load 1 ASDF system:
        nyxt / gi-gtk
    ; Loading "nyxt / gi-gtk"
    .....................................
    (: NYXT / GI-GTK)
    CL-USER> (nyxt: start)
    <INFO> [11:09:55] Listening to socket "/run/user/1000/nyxt/nyxt.socket".
    Nyxt version 2.0.0-4-g3cbc8a5a
    <INFO> [11:09:55] Loading Lisp file "/home/pedro/.config/nyxt/auto-config.lisp".
    NIL


With Nyxt being open, I used the function `open-file` to open the same file described on the issue. As a consequence, the file was indeed *successfully* opened. However, it was opened externally ** with firefox **! (despite the fact that I was inside Nyxt asking it to open).

I should highlight that this is different from the ** initial ** issue report scenario. There I used the `$ nyxt index.html` shell to open a file. However, if I use `$ nyxt ...` on shell I will be using the 2.0 stable download version which has the bug. This is why I used the fetched and pulled version from github. So, here I was running Nyxt newest version with SLY's REPL.

OK. After making the difference clear, I tried to solve the _internally_ versus _externally_ openness point with the manual. According to the built-in document, the `open-file` function opens a file * externally * or * internally *. I was willing to open it internally!

I tried to find out how to use Nyxt to open a file internally. After investigating the `describe-function open-file-function`, it showed that only` file-source` was on the argument's list. So I could not understand if there was some optional argument to use in order to force open-file to use Nyxt as an application to open it ... Sorry if I missed something about the manual / docs.

Finally, giving up on the manual, I tried ** a lower level approach **. Since `open-file` seems to be based on` xdg-open`, I changed my configurations on Ubuntu with:

``
$ xdg-settings set default-web-browser nyxt.desktop
``
It works with Nyxt opening stuff as:
``
$ xdg-open "http://example.com"
``
Thus, I re-started everything (which might have not been actually necessary). I re-started emacs, SLY, and "reloaded" Nyxt fetched version just like it was described above.

What was the result?

After executing `open-file` (C-x C-f) inside Nyxt and choosing on the prompt the always used HTML file, Nyxt opens the file with a new ** Nyxt's browser ** (instead of firefox - which seems to be an advancement). Unfortunately, Nyxt gives the same error message it was giving before:

> # Page could not be loaded.
>
> ## URL: /home/pedro/my-blog/my-blog/index.html
>
> Please check:
>
> - Your Internet connection.
> - That the URL is valid.
> - That the resource at the URL is reachable.


Did I miss something? Is my test wrong in some sense?
What would have been the best way to test this?

A few days ago, @Ambrevar  even asked if I was willing to test it (I think he deleted the comment later). I wanna do it. Sorry for being late.

**Comment by Ambrevar** [comment]
> with Nyxt being open, I used the function open-file to open the same file 

`open-file` opens a file leveraging `xdg-open` by default, which finds the right application depending on your user configuration.  So if Firefox is set to open your HTML files, then this is expected.

**Comment by Ambrevar** [comment]
I'm confused by your report.
Do you still have this issue wth Nyxt 2.0.0?
