### ISSUE TITLE
Is there a problem on the instructions to clone cl-webengine?

### ISSUE THREAD

**Issue by pdelfino** [atlas-engineer/nyxt#1420]
Hi, 

I am trying to follow the **Standard Developer Installation** [Readme](https://github.com/atlas-engineer/nyxt/blob/master/documents/README.org#standard-developer-installation) in order to run Nyxt locally from the source code.

On the **cl-webengine** installation part, there is the following instruction:

`git clone git@github.com:atlas-engineer/cl-webengine.git`

It did not work for me. I received this error message:

> Warning: Permanently added the RSA host key for IP address '#{Some IP address} ' to the list of known hosts.
> git@github.com: Permission denied (publickey).
> fatal: Could not read from remote repository.
> Please make sure you have the correct access rights
> and the repository exists.
> 

Instead, I did just:

`$ git clone https://github.com/atlas-engineer/cl-webengine.git
`

It seems to work. I downloaded the files and the version control history.

Is it problematic to do the way I did?

Why the approach by the book did not work? Did I miss something with cryptography?

Thanks.

**Comment by Ambrevar** [comment]
Good catch, fixed with 74b210f4be1a3dd15df1772837ffe9b9f9143967.

To answer your question: the "git@" URL is for SSH-anthenticated
checkouts.
Only members of the atlas-engineer group have access.

**Comment by Ambrevar** [comment]
Note that the cl-webengine is completely outdated at the moment.
We plan to work on it as soon as possible though ;)
