### ISSUE TITLE
Cannot configure buffer-source 

### ISSUE THREAD

**Issue by franburstall** [atlas-engineer/nyxt#1425]
**Describe the bug**
I try to set the slot `follow-p` of `buffer-source` to nil by hitting the *Configure* button for that slot after `C-h C buffers-source`.  This writes the following form to `auto-config.lisp`:
````common-lisp
(DEFINE-CONFIGURATION BUFFER-SOURCE
  ((FOLLOW-P nil)))
````
I restart nyxt and this silently fails to have an affect.  Well, almost silently: there is nothing in the messages buffer but you can see a truncated attempt to complain in the terminal output:
````
<INFO> [17:41:23] Loading Lisp file "/home/fran/.config/nyxt/auto-config.lisp".
While evaluating the form starting at line 1, column 0
  of <INFO> [17:41:23] Loading Lisp file "/home/fran/.config/nyxt/init.lisp".
SLYNK's ASDF loader finished.<INFO> [17:41:26] Loading history of 636 URLs from "/home/fran/.local/share/nyxt/history/default.lisp".
````
If I put the same form in my `init.lisp` instead, the error is apparent (and predictable): I get:
````
Error occured:

Could not load the init file: define-configuration argument USER-BUFFER-SOURCE is not a known class.
````
(though still nothing in the message buffer and truncated output on the terminal).

Looking at the code, I see that I cannot configure class `foo` unless class `user-foo` exists and this is not the case for many values of `foo`!  (Have I misunderstood something here?)

**Information**
- OS name+version: Debian-10
- Graphics card and driver:
- Desktop environment / Window manager name+version: EXWM
- How you installed Nyxt (Guix pack, package manager, build from source): Source
- Information from command copy-system-information:

Nyxt version: 2-pre-release-7-98-g0248af96
Renderer version: GI-GTK
Operating system kernel: Linux 4.19.0-16-amd64
Lisp implementation: SBCL 2.1.1
Features: (SLYNK WEBKIT2 WEBKIT2-2.30 WEBKIT2-PASTE-PLAINTEXT WEBKIT2-TRACKING
 WEBKIT2-MUTE WEBKIT2-EMOJI WEBKIT2-MEDIA WEBKIT2-SANDBOXING GTK-3-22 GTK-3-20
 GTK-3-18 GTK-3-16 GTK-3-14 GTK-3-12 GTK-3-10 GTK-3-8 GTK-3-6 GTK-3-4 GTK
 GDK-3-22 GDK-3-20 GDK-3-18 GDK-3-16 GDK-3-14 GDK-3-12 GDK-3-10 GDK-3-8 GDK-3-6
 GDK-3-4 CAIRO-1-10 CAIRO-1-12 GDK-PIXBUF GLIB-2-30 GLIB-2-32 GLIB-2-34
 GLIB-2-36 GLIB-2-38 GLIB-2-40 GLIB-2-42 GLIB-2-44 GLIB-2-46 GLIB-2-48
 GLIB-2-50 GLIB-2-52 GLIB-2-54 GLIB-2-56 GLIB-2-58 GLIB NYXT-2 FSET-EXT-STRINGS
 CUSTOM-HASH-TABLE-NATIVE SWANK PLUMP-UTF-32 GLOBAL-VARS DECLARE-TYPES
 PARENSCRIPT NAMED-READTABLES 21BIT-CHARS CHUNGA FLEXI-STREAMS CLOSER-MOP
 CL-PPCRE-UNICODE CL-UNICODE CL-PPCRE BORDEAUX-THREADS SPLIT-SEQUENCE
 GRAY-STREAMS FAST-IO-SV FAST-IO SBCL-USES-SB-ROTATE-BYTE
 ASDF-SYSTEM-CONNECTIONS CL-JSON-CLOS CL-JSON THREAD-SUPPORT FLAT-NAMESPACE
 X86-64 UNIX CFFI FLAT-NAMESPACE SEQUENCE-EMPTYP QUICKLISP ASDF3.3 ASDF3.2
 ASDF3.1 ASDF3 ASDF2 ASDF OS-UNIX NON-BASE-CHARS-EXIST-P ASDF-UNICODE X86-64
 GENCGC 64-BIT ANSI-CL COMMON-LISP ELF IEEE-FLOATING-POINT LINUX LITTLE-ENDIAN
 PACKAGE-LOCAL-NICKNAMES SB-LDB SB-PACKAGE-LOCKS SB-THREAD SB-UNICODE SBCL UNIX)

ASDF version: 3.3.1
Critical dependencies: (/home/fran/common-lisp/nyxt/_build/submodules/cl-cffi-gtk/gtk/cl-cffi-gtk.asd
 /home/fran/common-lisp/nyxt/_build/quicklisp-client/dists/quicklisp/software/cl-gobject-introspection-20210124-git/cl-gobject-introspection.asd
 /home/fran/common-lisp/nyxt/_build/submodules/cl-webkit/webkit2/cl-webkit2.asd)

Quicklisp dist version: 2021-04-11
Quicklisp client version: 2020-01-04
Local project directories: (/home/fran/common-lisp/nyxt/_build/submodules/
 /home/fran/common-lisp/nyxt/_build/quicklisp-client/local-projects/)
Critical dependencies(#<SYSTEM cl-cffi-gtk / cl-cffi-gtk-20201220-git / quicklisp 2021-04-11>
 #<SYSTEM cl-gobject-introspection / cl-gobject-introspection-20210124-git / quicklisp 2021-04-11>
 #<SYSTEM cl-webkit2 / cl-webkit-20210411-git / quicklisp 2021-04-11>)

**Comment by Ambrevar** [comment]
See #1428.

**Comment by Ambrevar** [comment]
#1428 got merged.
