### ISSUE TITLE
M-i binding conflict in VI mode

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#1426]
When VI mode is enabled in the prompt buffer, by default we can't toggle hint transparency in `follow-hint` because `M-i` is bound to `vi-focus-first-input-field`, which has priority since `vi-normal-mode` comes first.

Any clue how to work around this?

Rebind `M-i`?  Any suggestion?

**Comment by jmercouris** [comment]
Just rebind it to anything at all :-D. There is no precedent here!

**Comment by Ambrevar** [comment]
So rebind "M-i"?

Note that I would have to rebind the CUA binding as well.

To what?

**Comment by jmercouris** [comment]
I don't know, just pick something :-D

**Comment by Ambrevar** [comment]
Fixed with #1499.
