### ISSUE TITLE
Overhaul user-classes

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#1431]
Commits a276091fa0f55daf1400c9a0ee1380982cccf676 and 17f7b7f2d903082b5b0308b07cdad8311a81dadc show how painful it is to consistently define and use "user classes".

We can do better.
Here is what I suggest:

- Remove our `libraries/class-star` and use an up-to-date Git submodule of `defclass-star` instead.
- Define a `define-class` macro which just adds the `:user-class-p` option.
- User classes should be remembered in some unexported list, like we do with `*command-list*`.  We should not rely on the name to identify user classes (this is what we do now and it's brittle).  Add a predicate `user-class-p`.
- Reverse the logic: instead of having the virtual class prefix with "user-", name the virtual class using the given name and prefix the defining parent class with something like `%`.  The parent class should be unexported even if the user class is exported.
- `define-configuration` generated classes can follow the same logic and be named `%foo17` for the `foo` user class.
- For the rare cases where we need to redefine the superclasses of a user class, we can use `defclass` manually, e.g.

  ```lisp
  (defclass browser (gtk-browser %browser))
  ```

  But then `browser` would lose its docstring (which is in `%browser`).
  So maybe keep `define-user-class` (unexported) for these cases?  It expands to

  ```lisp
  > (macroexpand-1  '(define-user-class browser (gtk-browser)))
  (PROGN
   (EXPORT-ALWAYS 'USER-BROWSER (SYMBOL-PACKAGE 'USER-BROWSER))
   (SB-MOP:ENSURE-CLASS 'USER-BROWSER :DIRECT-SUPERCLASSES '(GTK-BROWSER BROWSER)
                        :DOCUMENTATION (DOCUMENTATION 'BROWSER 'TYPE)))
  ```

  Or just call the above `ensure-class` manually, no need for `define-user-class`.

- `describe-class` would no longer list both user-classes and the defining parent class.

**Comment by Ambrevar** [comment]
After some thinking here is a revised proposal: what about using metaclasses to add a user-reserved method to customize instances?

The original reason why we created this user-class macro is because users can't use `initialize-instance :after` since it's already used by the code.  But then, I propose this (now) obvious fix; leverage MOP to add a new method executed after initialization, which leaves full control to the user what to do when the instance has been initialized.

In practice, it would look like this from the `init.lisp`:
```lisp
(defmethod user-class-init ((buffer buffer))
  (do whatever)
  (setf (default-modes buffer) '(foo bar))
  (do more stuff))
```

Note that since it's not a macro, it's not a DSL either, thus the user can really do whatever they want, not just set slots unlike in our current implementation.

Thoughts?  @jmercouris @pdelfino @aadcg @aartaka 

For reference, the initial design motivation is detailed in #419.

**Comment by Ambrevar** [comment]
Draft:

```lisp
(defclass user-class (standard-class)
  ())

(defmethod closer-mop:validate-superclass ((class user-class)
                                           (superclass standard-class))
  t)


(defmethod user-class-init ((c person))  ; TODO: Better name?
  nil)

(defmethod make-instance :around ((class user-class) &key)
  (let ((initialized-object (call-next-method)))
    (user-class-init initialized-object)
    initialized-object))

(defclass person ()
  ((name
    :initarg :name
    :accessor name))
  (:metaclass user-class))

(defmethod user-class-init ((c person))
  (log:info (name c) "SUCCESS!"))

(make-instance 'person :name "donald")
```

**Comment by jmercouris** [comment]
The user class motivation is also about simplicity. I'm ok with changing the underlying implementation details so long as we provide a simple and consistent user interface.

**Comment by Ambrevar** [comment]
The example I gave above is that the new user-class-init (name to be
changed) is the only API.  It would effectively replace
define-configuration and be simpler since it's regular Common Lisp.

**Comment by aartaka** [comment]
How about using a similar approach for modes, so that we don't have to edit the inheritance list of a mode? Maybe even get rid of `root-mode`...

**Comment by Ambrevar** [comment]
Yes, I was planning on getting rid of root-mode.

What do you mean with "edit the inheritance list"?

**Comment by aartaka** [comment]
I mean the thing that `define-mode` documentation puts as
```
When DIRECT-SUPERCLASSES is T, then the mode has no parents.
Otherwise, the mode's parents are ROOT-MODE and DIRECT-SUPERCLASSES.
```

**Comment by Ambrevar** [comment]
Absolutely, all this will go, but as part of #1836.  This is not related to define-class, or is it?

**Comment by Ambrevar** [comment]
@aartaka I had misunderstood you before: metaclass are by default not inherited.  So if I define 

```lisp
(defclass subperson (person)
         ((age :initarg :age :accessor age)))
```

it won't be a user-class unless we specify the metaclass explicitly.
But this is a feature, isn't it?

**Comment by Ambrevar** [comment]
Other considerations:

- To enable inheritance of the "user-class" attribute, we could have specified it as a superclass instead of a metaclass.  But then it's impossible to remove the attribute from a subclass.

- The metaclass is immutable.  It's impossible to change a class metaclass once it's defined.

**Comment by Ambrevar** [comment]
Another consideration:

- The "method" approach means it's completely standard Common Lisp, in particular the customization of a parent class is only propagated to a subclass that also has a customization method if the latter is an `:around` method that calls `(call-next-method)`.  Benefit: it gives ultimate control.  Drawback: it may trip the user.

In my opinion, the "automatic propagation of changes" like we do with `define-configuration` may also trip the user, depending on what they expect.  It's a matter of angle.

Thoughts?

**Comment by aartaka** [comment]
> @aartaka I had misunderstood you before: metaclass are by default not inherited. So if I define
> 
> ```lisp
> (defclass subperson (person)
>          ((age :initarg :age :accessor age)))
> ```
> 
> it won't be a user-class unless we specify the metaclass explicitly. 

I wonder why that is and how to enforce metaclass inheritance... We don't need it, but my curiosity is tinkled :D

> But this is a feature, isn't it?

Yes, it is :)

**Comment by aartaka** [comment]
> * To enable inheritance of the "user-class" attribute, we could have specified it as a superclass instead of a metaclass.  But then it's impossible to remove the attribute from a subclass.

I guess we don't need it much, given that `user-class` metaclass is opt-in.

> * The metaclass is immutable.  It's impossible to change a class metaclass once it's defined.

Well, that's a restriction, yet the one we can safely live with. We only rely on methods specializing over the metaclass, not the structure of the metaclass itself, right?

**Comment by aartaka** [comment]
> * The "method" approach means it's completely standard Common Lisp, in particular the customization of a parent class is only propagated to a subclass that also has a customization method if the latter is an `:around` method that calls `(call-next-method)`.  Benefit: it gives ultimate control.  Drawback: it may trip the user.

It's a shame one cannot define several `:around` or `:after` methods for a class. But then, we don't define much of those, so it shouldn't hurt us in any sensible way :)

> In my opinion, the "automatic propagation of changes" like we do with `define-configuration` may also trip the user, depending on what they expect. It's a matter of angle.

Yes, a definitely obscure thing this `define-configuration` is at times! I guess methods would make more sense, especially for those used to conventional imperative OO languages like Python/C++.

**Comment by Ambrevar** [comment]
Left to do once #2194 is merged:

- [ ] Fork defclass-star.
- [ ] Unexport some GTK slots.

**Comment by Ambrevar** [comment]
@jmercouris convinced me to restore `define-configuration` to ease the transition from 2-series to 3-series.  Indeed, it'd be now trivial to write a macro that expands to `configure-instance`.  The main limitation is that now it won't stack up.

Previously, calling `define-configure (buffer)...` to times in a row for different slots worked.  Now this would effectively discard the first call.  Better than nothing!  We can also detect the override and produce a warning.

**Comment by aartaka** [comment]
I mean, making a deprecatino warning when using `define-configuration` is a must, the consequences are on those still using it :p

**Comment by aartaka** [comment]
But yes, restoring it would be useful.

**Comment by aadcg** [comment]
@Ambrevar what's the status here? Is something missing for 3.0?

**Comment by Ambrevar** [comment]
I think mostly good, maybe we could have a last look at the renderer and unexport some GTK slots that were mistakenly exported.

**Comment by jmercouris** [comment]
Which slots?

**Comment by Ambrevar** [comment]
See

```lisp
(define-class gtk-window ()
  ((gtk-object)
   (handler-ids
    :documentation "See `gtk-buffer' slot of the same name.")
   (root-box-layout)
   (horizontal-box-layout)
   (panel-buffer-container-left)
   (panel-buffer-container-right)
   (panel-buffers-left)
   (panel-buffers-right)
   (main-buffer-container)
   (prompt-buffer-container)
   (prompt-buffer-view
    :documentation "Shared web view between all prompt buffers of this window.")
   (status-container)
   (message-container)
   (message-view)
   (key-string-buffer))
  (:export-class-name-p t)
  ;; TODO: Unexport?
  (:export-accessor-names-p t))
```

I believe none of these accessors should be exported, except may be `gtk-object`.

In `gtk-buffer`, `handler-ids` is exported and should not be.

In `gtk-request-data`, should the slots  be exported? @aartaka Any idea?

**Comment by aartaka** [comment]
> I believe none of these accessors should be exported, except may be `gtk-object`.

Yes.

> In `gtk-buffer`, `handler-ids` is exported and should not be.

Yes.

> In `gtk-request-data`, should the slots be exported?

All of them should be exported, because they allow the user to inspect the guts of request. It's a stable enough of an API and it should be exposed for additional utility, I'd say.
