### ISSUE TITLE
Utilize XMLSerializer in ffi-buffer-get-document

### ISSUE THREAD

**Issue by aartaka** [atlas-engineer/nyxt#1433]
[XMLSerializer](https://developer.mozilla.org/en-US/docs/Web/API/XMLSerializer) is an API that allows to serialize the current DOM state with all the attributes (all the `style`, `class`-es etc.) as they are, even when changed by JavaScript. This gives us much more info about the opened page and allows for more cool modifications :)

XML serialization is not a problem -- XMLSerializer actually produces XML that is extremely close to HTML and even has a proper DOCTYPE.

**Comment by aartaka** [comment]
Just tested XMLSerializer against our method. Seems to produce HTML similar to what we already have. Runs faster than our iteration, though, but that is on purpose -- we need to ensure WebKit doesn't hang because of overly long HTML string :)

**Comment by Ambrevar** [comment]
So if I get you right, you deem unnecessary to leverage XMLSerializer because what we have is good enough?

**Comment by aartaka** [comment]
> So if I get you right, you deem unnecessary to leverage XMLSerializer because what we have is good enough?

Exactly :)
