### ISSUE TITLE
what is the keybinding to launch other commands

### ISSUE THREAD

**Issue by MAliNaqvi** [atlas-engineer/nyxt#1436]
OS: MacOS
Installation: `brew install next`

I tried M-x, :, [space]

Nothing worked...

**Comment by jmercouris** [comment]
Sorry, that's a very old version, I don't remember 😀

**Comment by Ambrevar** [comment]
It's always been `M-x` or `C-space`.  If it does not work, it's probably broken with `brew`.

@MAliNaqvi The good news is that some folks are working on fixing WebKitGTK on macOS with Nix, which means that the latest Nyxt should be available to macOS Nix user hopefully very soon!

**Comment by aadcg** [comment]
Stale.
