### ISSUE TITLE
Enable prompt-buffer Emacs/VI keybingings through quick configuration options

### ISSUE THREAD

**Issue by tmplt** [atlas-engineer/nyxt#1437]
With the new v2.0.0 release:

1. ```
    $ rm -rf .local/share/nyxt .config/nyxt
    $ nyxt
    ```
2. Common Settings -> Use Emacs
3. `<C-Space>`
4. Observe prompt-buffer scrolling via up/down arrows

I want to bind this functionality to `<C-n>` and `<C-p>` but I do now know what function to bind. I expect the bind to be listed in `*Help-bindings`, but that is not the case.

**Comment by edgar-vincent** [comment]
You can enable Emacs bindings, which include the ones you mention, in the prompt buffer with this:
```
(define-configuration prompt-buffer
    ((default-modes (append '(emacs-mode) %slot-default%)))
```
If you wand to bind these keys manually, you can use this:
```
(defvar *my-keymap* (make-keymap "my-map"))
(define-key *my-keymap*
  "C-p" 'nyxt/prompt-buffer-mode:select-previous
  "C-n" 'nyxt/prompt-buffer-mode:select-next)

(define-mode my-mode ()
  "Dummy mode for the custom key bindings in `*my-keymap*'."
  ((keymap-scheme (keymap:make-scheme
                   scheme:cua *my-keymap*
                   scheme:emacs *my-keymap*
                   scheme:vi-normal *my-keymap*))))

(define-configuration (prompt-buffer)
    ((default-modes (append '(my-mode) %slot-default%))))
```

I don't seem to be able to run `describe-bindings` in the prompt-buffer and did have to look at the source to find the name of the `select-*` functions - I'll have a closer look.

**Comment by aartaka** [comment]
Do keybindings stay non-Emacsy after you restart Nyxt?

**Comment by tmplt** [comment]
@edgar-vincent On my machine `auto-config.lisp` contained
```lisp
(define-configuration (buffer web-buffer)
  ((default-modes (append '(emacs-mode) %slot-default%))))
```
Adding
```lisp
(define-configuration prompt-buffer
    ((default-modes (append '(emacs-mode) %slot-default%))))
```
Fixed it.

**Comment by edgar-vincent** [comment]
Should this issue be closed?

**Comment by aartaka** [comment]
> @jmercouris @Ambrevar @aartaka Should this issue be closed?

I'm not sure. It's actually necessary that configuration customizes both prompt-buffer and regular buffers to use the same bindings. I'll change the name of the issue.

**Comment by Ambrevar** [comment]
Strange, I can't reproduce.  Configuring `buffer` should be enough since all buffers including the prompt-buffer inherit from it.

@aartaka Can you reproduce?

**Comment by Ambrevar** [comment]
@aartaka Friendly ping!

If no one can reproduce this issue, I believe it can be closed.

**Comment by aartaka** [comment]
> @aartaka Friendly ping!
> 
> If no one can reproduce this issue, I believe it can be closed.

I cannot reproduce, no.

**Comment by Ambrevar** [comment]
Closing then, thanks!
