### ISSUE TITLE
Support external-editor-program with parameters

### ISSUE THREAD

**Issue by lbolla** [atlas-engineer/nyxt#1438]
**Describe the bug**

If VISUAL or EDITOR env var is set to a command with spaces, e.g. "emacsclient --socket-name mysocket", Nyxt fails (can't find the command). 

**Precise recipe to reproduce the issue**

Run `VISUAL="emacsclient -nx" nyxt` and then try to edit with external editor "C-c '".

I think the problem is here: https://github.com/atlas-engineer/nyxt/blob/master/source/external-editor.lisp#L19-L20 and here: https://github.com/atlas-engineer/nyxt/blob/master/source/browser.lisp#L172-L174
`external-editor-program` is of type "string", but it could really be a "list of strings", as `uiop.run-program` would support it.

**Comment by Ambrevar** [comment]
Good catch, thanks for reporting!
Fixed with 21ea43286be08591aaa59ca481dab3cf7182ad8b.
