### ISSUE TITLE
`division-by-zero` error when running `reduce-to-buffer` on buffer visiting IP address

### ISSUE THREAD

**Issue by edgar-vincent** [atlas-engineer/nyxt#1442]
**Recipe**
1. `set-url`  `https://127.0.0.1`
2. Run `reduce-to-buffer`, set mark on the aforementioned buffer, press RET

**Output**
Error message: `Warning: Error on separate thead: arithmetic error DIVISION-BY-ZERO signalled
Operation was (/ 1 0).`

**Comment by aartaka** [comment]
6b2d76c65f6ead13bdc58114a1ad7915cd23199f could fix that.

**Comment by aartaka** [comment]
Should be fixed.
