### ISSUE TITLE
Is the Developer Manual suggesting to load the *old* gtk? Shouldn't it be the newer one?

### ISSUE THREAD

**Issue by pdelfino** [atlas-engineer/nyxt#1445]
Hi,

The Developer Manual on Hacking/Running from source/ suggests as the fourth step that:

> 4 - Execute (ql:quickload :nyxt/gtk) to load the Nyxt system into your Lisp image.

Based on a recent private communication via email with @Ambrevar, I think the documentation should indicate the newer one to load:  **:nyxt/gi-gtk** 

I will do a PR for that. If I got something wrong (maybe his comments were particular to my case), you guys can reject it.

**Comment by jmercouris** [comment]
You are correct, it should say `(ql:quickload :nyxt/gi-gtk)`. Good eye!
