### ISSUE TITLE
Scroll page when needed with visual-mode

### ISSUE THREAD

**Issue by edgar-vincent** [atlas-engineer/nyxt#1459]
Currently, the page doesn't get scrolled when the top or bottom of the visible part of the page has been reached when using visual-mode, which makes the selection of large chunks of text impractical.

**Comment by jmercouris** [comment]
Ah, that is a good point! Thank you for opening this issue!

**Comment by edgar-vincent** [comment]
Thank you both @jmercouris @aaron-tan!
