### ISSUE TITLE
What the hell??

### ISSUE THREAD

**Issue by 0Karakurt0** [atlas-engineer/nyxt#1461]
Sorry, this will be quite a ragepost, but what a bloody mess of frustration my first not even expirience but impression is...
First of all, why the hell I can not type g in "execute-comand" ... dialog? Whatever the hell it is bound to ":" key.
Secondly, why on earth there is no freaking indication what mode are you in?? Who in his right mind thought that white text in light-gray background is a freaking good indication???
And why the hell opening in new window opens site in this abomination of a tab???
It hasn't been 20 minutes but I alreqady want to trow nyxt into trash can...

*inhale-in, inhale-out*

I'll be first to admit, these all quite emotionally filled statements from a guy who hadn't even a day with this new browser, yes.
But that same guy tested a lot of other "power-browsers", with qutebrowser staying as favorite for like a year already, if not more. And not being able to use another one feels really out of place. Espetially because of weird keybindings that interfere with system ones.

I'll give it another try, but I asked around my friends and they had similar first impression - strange, non-intuiteive thing that pretends to be a power browser. None of them tried to use.

I'm not sure of intentions behind this issue, but I do want to help nyxt become at least something

PS: there's not even a slight glimpse of Vi style. If you want to make that clame, implement modes correctly. Examples - qutebrowser, vimb

**Comment by jmercouris** [comment]
Hi, thank for your interest in Nyxt! I appreciate that you are interested in the success of the project!

> Sorry, this will be quite a ragepost, but what a bloody mess of frustration my first not even expirience but impression is...
> First of all, why the hell I can not type g in "execute-comand" ... dialog? Whatever the hell it is bound to ":" key.

When you are in `execute-command` with Vi bindings, the default mode is vi-normal. If you want to type in the letter 'g', you'll need to enter `vi-insert` mode. Others have commented that they exepct the first mode when entering the prompt buffer to be `vi-insert`, perhaps we will change it. We always try to engage with the community and do what is best!

> Secondly, why on earth there is no freaking indication what mode are you in?? Who in his right mind thought that white text in light-gray background is a freaking good indication???

There is an indication. You can change the color scheme if you like. It isn't a flashing red light, but it doesn't need to be either. If you know where to look, it is clear. We also have a PR in the pipeline to make it a little bit more obvious!

> And why the hell opening in new window opens site in this abomination of a tab???

I'm not sure what you are saying here.

> It hasn't been 20 minutes but I alreqady want to trow nyxt into trash can...

This is unnecessary and mean.

> _inhale-in, inhale-out_
> 
> I'll be first to admit, these all quite emotionally filled statements from a guy who hadn't even a day with this new browser, yes.
> But that same guy tested a lot of other "power-browsers", with qutebrowser staying as favorite for like a year already, if not more. And not being able to use another one feels really out of place. Espetially because of weird keybindings that interfere with system ones.

Everyone's system is different. We don't use hyper or super- specifically to avoid interferring with system keybindings. If it interferes with yours, that is OK, everything in Nyxt can be rebound in any way you like. This is the gift we give you, unlimited choice.

> I'll give it another try, but I asked around my friends and they had similar first impression - strange, non-intuiteive thing that pretends to be a power browser. None of them tried to use.

What is the value of an opinion without experience?

> I'm not sure of intentions behind this issue, but I do want to help nyxt become at least something

That's kind of you. Also, if you are interested, I have a brief feedback: I'm not sure from where this anger comes from. I don't know you, and I don't know what drives you. I personally know that anger can often be an indication of suffering. If that is the case, I hope that you can resolve whatever may be troubling you. I'll leave you with a quote I heard some time ago that has resonated deeply with me: Holding onto anger is like drinking poison and expecting the other person to die.

Best of luck,

-John

**Comment by alejandrogallo** [comment]
Just to give some feedback here, I have been also quite frustrated at
the beginning with `nyxt`, but the project is so promising that I'm
also willing to help make ist better. I guess the main authors are
neither vim nor evil nor qutebrowser users, so they might not
understand the frustration. It's important to help now and maybe it
would be a good idea to have a repo with example configurations of vi
users, this works very well in projects like
[qmk](https://github.com/qmk/qmk_firmware/tree/master/keyboards).

I think this is one of the reasons of the frustration, we need
more examples of vi power users and couple of tutorials more,
but this will come with time, *hopefully*;

**Comment by elais** [comment]
If you want to default to using vi-insert mode in the prompt buffer then you need to add the following to your `init.lisp`

```lisp
(define-configuration (prompt-buffer)
  ((default-modes (append
                   '(vi-insert-mode)
                   %slot-default%))))
```

**Comment by edgar-vincent** [comment]
> If you want to default to using vi-insert-mode in the prompt-buffer then you need to add the following to your `init.lisp`
> 
> ```lisp
> (define-configuration (prompt-buffer)
>   ((default-modes (append
>                    '(vi-insert-mode)
>                    %slot-default%))))
> ```

This is now set through the quick settings since https://github.com/atlas-engineer/nyxt/commit/31935b2c6fba870ce39d7f0c98f5b778184f7c9f.

**Comment by Zwo1in** [comment]
> This is now set through the quick settings since 31935b2.

This snippet is so useful that I'd make it default :)

**Comment by elais** [comment]
I agree. I think by default users want to be in insert mode when opening prompt buffers especially with `o`

**Comment by Ambrevar** [comment]
Maybe a misunderstanding: this is now the default in Nyxt 2.1.  Isn't it working as expected for you, @Zwo1in @elais ?

**Comment by ericdrgn** [comment]
@jmercouris and everyone else involved with this project. 

I happened upon this and felt compelled to leave a quick (or maybe not)note due to how this particular issue started.

As you may have noticed by my questions everywhere I have been using Nyxt for a couple of days now. I have been switching between every browser under the sun for around a year now. Sometimes on a daily basis changing my main driver. I dislike them all greatly. Somehow Nyxt (and I know previously Next) flew under my radar and I didn't find this project until going deep down a reddit-hole a few nights ago. 

Since then I've been shouting praises of Nyxt to anyone that will listen. Already have three friends using it and my config(s). It definitely is not for everyone. The documentation leaves a lot to be desired atm for sure. But seriously this vision for how we can view the internet and customize essentially everything is incredible and was previously a pipe dream for me.

Thank you all devs and contributors alike hope to join you all going forward. As I learn lisp and this browser I look forward to all the future frustrations. Because honestly even stock this is 100% worth it.

**Comment by Ambrevar** [comment]
Thank you for all the compliments.  I'm thrilled that some people like
Nyxt, as niche as it may be :D

About the documentation: you're true, it's lots of work and it's hard,
but it's also high priority!

See
https://github.com/atlas-engineer/nyxt/issues?q=is%3Aissue+is%3Aopen+label%3Adoc

Please report everything you find confusing, and if you want to
contribute to the manual don't hesitate to send patches :)

**Comment by elais** [comment]
I had a chance to try out just with the setting removed from my config for vi-insert in the prompt bufferand when I activated the quick settings for vi mode it did not set the prompt buffer default to insert.

**Comment by Ambrevar** [comment]
Can you open a new issue with a precise recipe and your exact config files?
