### ISSUE TITLE
How to configure nyxt without being a "lisp-wizard"

### ISSUE THREAD

**Issue by LamprosPitsillos** [atlas-engineer/nyxt#1466]
Is it impossible for someone to configure nyxt by knowing nothing about lisp? I am not talking about complex stuff just for example changing the hinting letters, which sounds simple enough.
Emacs has the `customize-*` function, which makes it easy for everyone to configure everything. Could we get something like that? It sure would help new and non lisp-wizard users get used to nyxt.
Let's say that i could understand lisp, how do I know what to modify? How do i get started?

**Comment by jmercouris** [comment]
It is not impossible! There is an equivalence to the customize-*. When you you describe a class or a slot, you'll see a button that says 'customize'. Simply click on it and set that value!

A great place to get started is the tutorial and built-in manual. Give them a look! :-)
