### ISSUE TITLE
Crash when inputting `#\\` character into file prompt

### ISSUE THREAD

**Issue by szos** [atlas-engineer/nyxt#1468]
When within the open file dialog (bound to `C-x C-f`) inputting the character `#\\` will crash Nyxt, signalling the (unhandled) condition `SB-KERNEL:NAMESTRING-PARSE-ERROR` from within the prompter update thread. This is due to an escape char being in an unexpected place. 

To reproduce, open Nyxt, open the open-file dialog (for emacs bindings this is C-x C-f), and enter the character `#\\`. Tested on Nyxt `2.0.0-18-gd8236fdf` built from source on Void Linux using SBCL `2.1.4`.

**Comment by Ambrevar** [comment]
Good catch, fixed with d91940729b3d9d5de2cd376d871a306bf09a89a4.  Thanks for reporting!
