### ISSUE TITLE
How would I map "C-m" to Enter?

### ISSUE THREAD

**Issue by alejandrogallo** [atlas-engineer/nyxt#1469]
How would I go about in nyxt to remap for all modes
`<C-m>` to `<Enter>`?

**Comment by jmercouris** [comment]
Add it to the override map, please see the manual for more details.

**Comment by jmercouris** [comment]
The override map is a user reserved map, a way you could do this is to make a PR to the vi maps, please feel free to do so!

**Comment by aadcg** [comment]
Stale.
