### ISSUE TITLE
freeze on site like youtube/reddit/etc

### ISSUE THREAD

**Issue by ixzh** [atlas-engineer/nyxt#1473]
**Describe the bug**
buffer freezes when any of these sites loads. No other choice but to quit Nyxt as other text based buffers also freeze

**Precise recipe to reproduce the issue**
as above
**Information**
- OS name+version:
- Graphics card and driver:
- Desktop environment / Window manager name+version:
- How you installed Nyxt (Guix pack, package manager, build from source):
- Information from command copy-system-information:

  If you can't run copy-system-information, try `nyxt --system-information` from
  a shell.  It this still does not work, please provide the following:
  - Nyxt version (from =M-x nyxt-version= or =nyxt --version=):
  - Lisp implementation/version (if built from source):
  - Kernel name+version:
  - WebKitGTK+ | QtWebEngine version:

**Output when started from a shell**

**Comment by K1D77A** [comment]
I have also experienced freezing when pages are loading. I would click on a link and if my internet is being slow the buffer would sometimes completely freeze, sometimes I have had to completely restart.

**Comment by ixzh** [comment]
> freezing when pages are loading

loading Wikipedia frontpage is also slow...is it because of hardware specs?

**Comment by Ambrevar** [comment]
Can you both share as much system information as possible, in particular your CPU architecture and your GPU driver?

**Comment by ixzh** [comment]
> Can you both share as much system information as possible,

here is mine:

![image](https://user-images.githubusercontent.com/14981695/121501076-76201180-ca11-11eb-9426-6d4452349b71.png)

**Comment by Ambrevar** [comment]
Are you using proxy-mode or Tor maybe?
Note: please share text if you can, screenshots are difficult to deal with (can't copy/paste, etc.).

**Comment by ixzh** [comment]
> Are you using proxy-mode or Tor maybe

I'm not using any proxy or Tor... the same set of sites opens smoothly in Firefox chrome etc...

**Comment by aadcg** [comment]
Probably related to the web renderer, WebKitGTK, and not Nyxt per se.

Feel free to re-open with more accurate information.
