### ISSUE TITLE
Provide a 3rd party repo for devuan/(debian)

### ISSUE THREAD

**Issue by Kreyren** [atlas-engineer/nyxt#1477]
Currently it's painful to keep this updated as it requires to perform the updated manually through cron.

**Comment by edgar-vincent** [comment]
This is a duplicate of https://github.com/atlas-engineer/nyxt/issues/1485

**Comment by Ambrevar** [comment]
Ideally, it'd be great to see Nyxt packaged in upstream Debian / Ubuntu, it would lift a lot of maintenance work off our backs :)

**Comment by Kreyren** [comment]
Agree with duplicate of #1485
