### ISSUE TITLE
Open a new window from a CLI

### ISSUE THREAD

**Issue by Kreyren** [atlas-engineer/nyxt#1478]
**Context:** I use customized firefox that opens a window on Super+T for me to have fast access to multiple pages on demand.

I want this functionality with nyxt, but nyxt can only do this from the internal shell -> Make a CLI argument that opens new window?

**Comment by K1D77A** [comment]
In emacs-mode C-t creates a new buffer.

**Comment by edgar-vincent** [comment]
This can be done with:

init.lisp:
```
(define-configuration browser ((remote-execution-p :t)))
```

and running, with nyxt already running: 
`nyxt --remote --eval '(make-window)'`

There are security implications though!

**Comment by Kreyren** [comment]
@edgar-vincent That doesn't work for me

```console
[kreyren@leonid:~]$  nyxt --remote --eval '(make-window)'
<INFO> [11:41:46] Nyxt already started.
```

> In emacs-mode C-t creates a new buffer. @K1D77A

I am not aware of that being callable from CLI?

**Comment by Ambrevar** [comment]
Depends what you call a third-party.  The socket is only accessible to the user who started Nyxt, but this does not protect your from:

- user with higher privileges (e.g. root),
- your own programs.

In other words, do you trust the system you are on and the programs you use?

There is a solution to this though: using some kind of secure athentication when communication over the socket.  I don't know if there is an easy solution here, help welcome!

**Comment by Kreyren** [comment]
> In other words, do you trust the system you are on and the programs you use? @Ambrevar 

i trust my systems

Access by root is expected

Access by my own programs is expected, but i would like to have an option to hide the traffic from other programs in case i am on untrusted system.

**Comment by Ambrevar** [comment]
Which traffic?  With the socket?

I wonder if Emacs has such an authentication measure.  I guess we could ask on Emacs-devel.

**Comment by Kreyren** [comment]
@Ambrevar The internet traffic where the concern is unknown malware sending secrets and requests to unwanted party

**Comment by Ambrevar** [comment]
Maybe there is a misunderstanding: Internet traffic is not related to
the Nyxt socket security.
Were we talking about different things?

**Comment by Kreyren** [comment]
Oh i though the socket can be used to expose the traffic? What is the security concern then?

**Comment by Ambrevar** [comment]
The socket allows you to fully control the browser via Lisp code.
It can capture key presses, page content, basically anything.

Well, if a program or a user can access the socket, they can probably
capture key presses and screen display anyways.  The security concern is
debatable, but you must understand it before using the socket.

**Comment by Kreyren** [comment]
I see O.o

**Comment by Ambrevar** [comment]
@Kreyren Did you manage to request a new window externally as per the suggestion in https://github.com/atlas-engineer/nyxt/issues/1478#issuecomment-855752985 ?

**Comment by Ambrevar** [comment]
@jmercouris @aartaka Many users have requested the possibility to request a new window externally.  It's currently not possible without a specific snippet in `init.lisp`, the accessibility is rather weak here.

Shall we add a new command line flag?

**Comment by jmercouris** [comment]
Are we sure they want a new window, and not just a new instance?

**Comment by Ambrevar** [comment]
If they've configured Nyxt to run in multi-instance mode, then calling
`nyxt` is enough to fire up a new instance.

If they run Nyxt in single-instance mode, shall we add an option to force-start
a new instance?  Maybe.

If so, then we need 2 new options I think:
- one to open a new window (--new-window, -n)
- one to open a new instance (--new-instance, -N)

Thoughts?

**Comment by jmercouris** [comment]
I think most people want multi-instance mode. I am pretty sure that is the expectation. I think the single instance mode is actually the problem. If we just change the default, most people will probably be quite happy.

**Comment by Ambrevar** [comment]
I disagree: popular browsers like Chromium and Firefox use
single-instance mode by default.

**Comment by jmercouris** [comment]
Well, it really depends on what you are used to. I guess I am thinking back to the days when I had multiple Netscape navigator windows/instances open :-D

**Comment by jmercouris** [comment]
If you are correct, then we really only need one new option `--new-window`, the reason is, if you want a new instance you can just run `nyxt -S`

**Comment by Kreyren** [comment]
> @Kreyren Did you manage to request a new window externally as per the suggestion in [#1478 (comment)](https://github.com/atlas-engineer/nyxt/issues/1478#issuecomment-855752985) ? @Ambrevar 

I responded on it in https://github.com/atlas-engineer/nyxt/issues/1478#issuecomment-856624533 - I wasn't able to get the new window that way

**Comment by Ambrevar** [comment]
Good point!

To see what I mean, you can easily install Firefox / Chromium on Nix.
Here which Guix:

```shell
# shell 1
$ chromium 
[29726:29726:0616/125053.323828:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.

# Busy...
```

```shell
# shell 2
$ chromium
Opening in existing browser session.
# Returns.
```

**Comment by Ambrevar** [comment]
@Kreyren I've just tried on master and it works for me.
Can you share you init.lisp?

**Comment by Ambrevar** [comment]
@edgar-vincent Note that it's supposed to be `t`, not `:t`.

**Comment by Kreyren** [comment]
> @Kreyren I've just tried on master and it works for me.
> Can you share you init.lisp?

https://git.dotya.ml/kreyren/nyxt-config

**Comment by Ambrevar** [comment]
Can you try with a new init file with just the configuration that was
shared?

Also make sure you are starting Nyxt without loading the auto-config
file, i.e. with the `-C` flag.

Then please share your shell output.

**Comment by Kreyren** [comment]
Ah sorry! though i synced the config x.x

![image](https://user-images.githubusercontent.com/11302521/122986214-6ef8ec00-d39f-11eb-9b48-4c56a4a409a8.png)


```console
[kreyren@leonid:~]$ nyxt -C ~/.config/nyxt/init.lisp --remote --eval '(make-window)'
<INFO> [21:18:15] Listening to socket "/run/user/1000/nyxt/nyxt.socket".
Nyxt version 2.0.0
<INFO> [21:18:15] Loading Lisp file "/home/kreyren/.config/nyxt/init.lisp".
1624389495 WARNING torsocks[244618]: [syscall] Unsupported syscall number 315. Denying the call (in tsocks_syscall() at syscall.c:567)
1624389495 WARNING torsocks[244640]: [syscall] Unsupported syscall number 315. Denying the call (in tsocks_syscall() at syscall.c:567)
1624389496 WARNING torsocks[244667]: [syscall] Unsupported syscall number 315. Denying the call (in tsocks_syscall() at syscall.c:567)
1624389496 WARNING torsocks[244669]: [syscall] Unsupported syscall number 315. Denying the call (in tsocks_syscall() at syscall.c:567)
1624389496 WARNING torsocks[244693]: [syscall] Unsupported syscall number 315. Denying the call (in tsocks_syscall() at syscall.c:567)
1624389496 WARNING torsocks[244712]: [syscall] Unsupported syscall number 315. Denying the call (in tsocks_syscall() at syscall.c:567)
<INFO> [21:18:24] External evaluation request: "(NYXT:OPEN-EXTERNAL-URLS)"
<INFO> [21:18:24] Externally pinged.
NIL
```


```console
[kreyren@leonid:~]$ nyxt -C ~/.config/nyxt/init.lisp --remote --eval '(make-window)'
<INFO> [21:18:24] Nyxt already started
```

**Comment by Ambrevar** [comment]
A few notes:

- `-C` means "don't read the auto-config file".
  It does not expect anything after it, so ~/.config/nyxt/init-lisp is
  understood as a URL to load.

- The first instance of Nyxt should not be started with `--remote --eval ...`.

- This is very strange:

```
> <INFO> [21:18:24] External evaluation request: "(NYXT:OPEN-EXTERNAL-URLS)"
```

it should read "make-window", not "nyxt:open-external-urls".

**Comment by aadcg** [comment]
Stale.
