### ISSUE TITLE
getting-input-from-the-user is outdated

### ISSUE THREAD

**Issue by Kreyren** [atlas-engineer/nyxt#1479]
https://github.com/atlas-engineer/nyxt/blob/1.5.0/documents/MANUAL.org#getting-input-from-the-user

**Comment by aartaka** [comment]
But wait, you're looking at 1.5.0 branch. It was relevant back then.

 We are at 2.0 now, so 1.5.0 docs do not really describe the thing -- there were too much changes. Refer to built-in documentation.

For this particular goal, you can use new `prompter` API in 2.0:
``` lisp
(let ((result (first (prompt :prompt "Input something"
                             :input "Hello there"
                             :sources (list (make-instance 'prompter:raw-source))))))
  (print result))
```

Am I misunderstanding the thing?

**Comment by Kreyren** [comment]
Agree with not a bug
