### ISSUE TITLE
Add syntax highlighting for code examples

### ISSUE THREAD

**Issue by K1D77A** [atlas-engineer/nyxt#1480]
This is just a suggestion but you could use a library like this:
https://prismjs.com/
To add Common Lisp syntax highlighting :+1:

**Comment by edgar-vincent** [comment]
That would be very nice indeed!

**Comment by aartaka** [comment]
We can even do better: inspect a running Nyxt and infer type informaation and other runtime things to do a _good_ highlighting.

**Comment by jmercouris** [comment]
Very non trivial Artyom, I remember Robert Strandh talking about it a couple years ago. I spoke to him again on IRC today, he gave some tips. I can email you a transcript of the conversation if you want.

I think we may be better off first with a simple dumb regex. We can probably copy the rules from Emacs.

**Comment by aartaka** [comment]
> Very non trivial Artyom, I remember Robert Strandh talking about it a couple years ago. I spoke to him again on IRC today, he gave some tips. I can email you a transcript of the conversation if you want.

That won't hurt, I guess (^人^)

> I think we may be better off first with a simple dumb regex. We can probably copy the rules from Emacs.

Indeed!

**Comment by Ambrevar** [comment]
> We can probably copy the rules from Emacs.

If I'm not mistaken, SLIME and SLY perform part of their syntax highlighting (e.g. for macro symbols) by leveraging the underlying Lisp.  Regexp won't do here.

Since Nyxt _is_ a Lisp, it's trivial to get the type of the various symbols in an s-exp.

**Comment by jmercouris** [comment]
You are mistaken, it is very much not trivial :-D

**Comment by Ambrevar** [comment]
I beg to differ, unless you mean something else:

```lisp
(defun foo ()
  "Docstring"
  17)

(let ((sym (first (read-from-string "(foo)"))))
	(values (symbol-function sym)
					(documentation sym 'function)))
```

**Comment by jmercouris** [comment]
That is a simple affair, I do mean something else

**Comment by Ambrevar** [comment]
Which is?

**Comment by jmercouris** [comment]
As far as I am aware, one would need a code walker and effectively a complete compiler to determine what each atom in a form is and what it points to.

**Comment by Ambrevar** [comment]
True, if you want functions like "go to definition", etc.
But you don't need this for simple syntax highlighting.

**Comment by jmercouris** [comment]
Consider macros. How would you know what each atom in a macro expands to? How would you approriately color things? How about reader macros?

**Comment by Ambrevar** [comment]
Macro expansion is not related to syntax highlighting, I believe.
What do you mean?  Do you have an example?

**Comment by jmercouris** [comment]
for example, let's say we make a macro called `defcommand`. How would we know that `defcommand` is a macro?

**Comment by Ambrevar** [comment]
(macro-function 'defcommand)

`macro-function` returns the function for macros, nil for regular functions.

**Comment by jmercouris** [comment]
Sure, but we still need to compile said form into the image. That doesn't seem wise to me. Compiling/reading anything we want to syntax highlight.

**Comment by Ambrevar** [comment]
I think we need examples! :)

What you are saying is that if we have the following docstring:

```
(defmacro foo ())
(foo)
```

You'd like the _second_ foo to be highlighted as a macro.

Indeed, `cl:read`-ing would not be enough here.

As you said, one way to do this (assuming that `foo` is not already
defined) is to compile, which we should of course not do (at least not
naively).

All I'm saying is that using the reader and the current image
information is better than regexp parsing.

**Comment by jmercouris** [comment]
That may be so. I think regex will be easier though.

**Comment by Ambrevar** [comment]
How so?  `cl:read` is just one function call and you get the whole tree
of atoms.

Regexps are much harder.  Just processing strings with escapes is hard.

**Comment by jmercouris** [comment]
OK, I leave it to you then :-D

**Comment by Ambrevar** [comment]
It's not very high priority for me right now, so if anyone wants to take over this issue, please do :)
