### ISSUE TITLE
Volunteering to type down the "Radio Student Interview" with translated questions

### ISSUE THREAD

**Issue by pdelfino** [atlas-engineer/nyxt#1483]
Hi,

I really enjoyed this [interview to the Radio Student](https://nyxt.atlas.engineer/article/radiostudent.org). I think it is one of the best parts of Nyxt's content marketing!  

Differently from other articles, this one gives more details about the competitive landscape, background context and long-term ideas/sketches about the project. It is more opinionated too. Which is interesting.

However, the half Slovenian part was a little bit annoying since I do not speak Slovenian (few people do. I wish I did, it would be exotic). Even the questions were not translated. 

In addition, the audio content will not be indexed by Google or Duckduckgo search engines. It would be better to have it as text.

Hence, I am volunteering to type it down **if you guys think the effort would be useful**. Also, it would be great if you could give me the original questions translated to English. Maybe they sent you before the interview.

I can reverse engineer the questions based on the answers. But it would be better to have this provided by the interviewer.

**Comment by jmercouris** [comment]
That could be quite cool! We were given just a list of topics in advance, but our conversation was recorded. Perhaps I can ask them for a copy of the original recording!

**Comment by pdelfino** [comment]
Great, John. I am glad you find it a good idea! In my free time, I will start typing the answers provided by you and Pierre. After you get the original recording, I will work on the questions delivered.

**Comment by pdelfino** [comment]
Hi guys,

Here is an `.org` file with the interview typed. It was harder than I thought! 

I guessed the questions since they were in Slovenian. In addition, there were 20 words from John/Pierre that I could not grasp.

I put (inaudible) when this happened. I am also new to org mode. Not sure if this was the best way to organize the content. It would be cool to have feedback on that too. See the file [here](https://github.com/pdelfino/public-notes/blob/main/radio-student-interview-typed.org).

**Comment by jmercouris** [comment]
Thank you Pedro!

**Comment by jmercouris** [comment]
Updated the article: https://nyxt.atlas.engineer/article/radiostudent.org

thanks again!
