### ISSUE TITLE
request package for mx linux or snap or debian

### ISSUE THREAD

**Issue by pannet1** [atlas-engineer/nyxt#1485]
hi,
mx linux was no 1 linux distro as per distrowatch.com. is it possible for you to package Nyxt for Mx Linux, Debian or Snap. I hope this help me and many other users. I came to know about Nyxt through linuxgram.
thanks.

**Comment by jmercouris** [comment]
Hi thanks for your interest! I'm not knowledgeable about those things, but I'm sure we can figure something out together! Thanks for making us aware of this!

Do you happen to know any packagers of the aforementioned distributions?

**Comment by jmercouris** [comment]
To be clear, when I say packagers, I mean individuals involved in packaging things.

**Comment by pannet1** [comment]
jim, 
this is fantastic. i will let someone in the package management of mx linux to get in touch with you. i guess you can close this thread, if a seperate thread is opened by that user.
thanks for the awesome Nyxt browser.

**Comment by jmercouris** [comment]
No problem! Also, my name is not jim ;-)

**Comment by SwampRabbit** [comment]
@jmercouris I can help with preparing the basic debianization, but I am not familiar with sbcl.

But let's get things moving at least.  ;)

**Comment by jmercouris** [comment]
We have a .deb file already, of course this is made to work with Ubuntu, but it should be a good start. You can also check out our workflow in the .GitHub directory that produces this deb file. Our generic developer instructions may also be useful, you can find them in the documents directory. Please let me know if there is anything I can help with as you are trying to package :-)

**Comment by SwampRabbit** [comment]
@jmercouris yes I saw the .deb, I think the biggest thing that hinders .deb packages via these workflows are that its nearly impossible for developers to address Distro/Version specific runtime dependencies and tweaks.  Sooner or later, not always, it leads to GitHub or Distro Forums getting issues open that could be addressed by a maintainer just picking up and sponsoring the application in the actual Distros' repositories.

One option to get into upstream Debian is to get it into [Debian Salsa](https://salsa.debian.org/explore).
I'm not a Debian maintainer, I'm on the MX Linux team.

Taking a look through everything here, like you said, much of the needed bits are there to get the Debian packaging going.
I just need some time, already have a ton of packages I maintain.

**Comment by pannet1** [comment]
@jmercouris,
i think nyxt is qualified enough to  become the main browser of many distro out there. as @SwampRabbit said getting into debian upstream is a great idea. if the work was done to support debain, i think lot of distros could use it. i may be wrong but i cannot wait to put my hands on the nyxt.

**Comment by SwampRabbit** [comment]
@jmercouris sorry just getting around to this more, if you make a empty branch called "debian_packaging" I'll work on the Debian source package files in there

**Comment by jmercouris** [comment]
@SwampRabbit I'm not sure how that helps, but I'll push an empty branch off the 2-series branch titled `debian_packaging`: https://github.com/atlas-engineer/nyxt/tree/debian_packaging

good luck :-D

**Comment by pannet1** [comment]
@SwampRabbit 
Thanks for taking this up amidst the upcoming next release of MX Linux. You might be having a crazy work schedule. Shiny new MX linux with Nyxt browser in it. I am already fantasizing it :100:

**Comment by aadcg** [comment]
Stale and not planned.

The Nyxt team can't maintain the distribution of its software on all platforms. We distribute a flatpak and self-contained bundle that works on any GNU/Linux distribution, [please find them here](https://github.com/atlas-engineer/nyxt/releases). We also maintain the packaging for the Guix package manager.
