### ISSUE TITLE
Nyxt fails to start on 32-bit / i686 (mmap: Cannot allocate memory)

### ISSUE THREAD

**Issue by TheKostins** [atlas-engineer/nyxt#1494]
**Information**
- OS name+version: Guix System 1.3.0rc1-1.6fd7f16 i686 
- Graphics card and driver: Intel Mobile 945GM/GMS, 943/940GML Express (xf86-video-intel & xf86-video-nouveau)
- Desktop environment / Window manager name+version: awesomewm v4.3
- How you installed Nyxt: Guix pack
- Information from command copy-system-information: 
  - Kernel name+version: Linux guix 5.11.15-gnu #1 SMP 1 i686 GNU/Linux
  - WebKitGTK+ | QtWebEngine version: 2.32.0

**Output when started from a shell**

mmap: Cannot allocate memory
fatal error encountered in SBCL pid 19255 tid 19255:
Can't allocate 0xc0000000 bytes for space 1

**Comment by Ambrevar** [comment]
This is odd, but why are you installing from the Guix pack if you are running Guix System?  Nyxt is available in Guix, you can just

```
guix install nyxt
```

and it should work :)

**Comment by TheKostins** [comment]
Tried it, same error

**Comment by Ambrevar** [comment]
Aha, I see you are running an i686 system, this may have to do with it.
What's your CPU?

**Comment by TheKostins** [comment]
Intel Core Duo T2300 2 x 1.7 GHz

**Comment by Ambrevar** [comment]
OK, so it's a i686 processor.  We've never tested Nyxt on this architecture before.  The issue could be with CFFI.
Can you share the exact shell output?

Can you run this, see if Guix can build and pass the tests?

```
$ guix build --check --no-grafts sbcl-cffi
$ guix build --check --no-grafts sbcl-cl-cffi-gtk
```

@jmercouris @aartaka Any idea how to test on i686?

**Comment by Ambrevar** [comment]
The Guix CI reports that `sbcl-cl-cffi-gtk` builds on i686: https://ci.guix.gnu.org/build/605136/details

**Comment by jmercouris** [comment]
It is not a priority to support 32 bit machines.
