### ISSUE TITLE
Warning: Error on separate thead: The function NYXT::LIST-BUFFERS is undefined.

### ISSUE THREAD

**Issue by SteveF4** [atlas-engineer/nyxt#1496]
**Describe the bug**

When I click on the Buffers icon (hamburger), Nyxt 2.0.0 displays the message: "Warning: Error on separate thead: The function NYXT::LIST-BUFFERS is undefined." and no list of buffers is displayed. It happens for me on Linux Lite (a distro based on Ubuntu 20.04 LTS with X Server) and on Ubuntu 20.04 with Wayland (though I'm using WSLg on a Windows developer build, which is definitely not ready for prime-time). No list of buffers is displayed for either.

Also, is "thead" in that message mean to be "thread?" (Maybe it’s a Common Lisp structure though: “t-head”? Last time I wrote any serious Lisp we used car and cdr instead of fancy terms like head and tail).

I have been unable to find anything online related to Nyxt or Lisp in general that tells me what it means. I installed the 2.0.0 .deb file using dpkg, and was unable to list buffers. I removed the package and installed the .zip archive and ran that instead, same result. I removed the folders in .config/nyxt, .local/nyxt, and .cache/nyxt, and I still get the same error when I click on the buffer icon. Does anyone know what might be going on?

One thing I should mention is that I am running in virtual machines using VMware Workstation 15, hosted on Windows 10 (21H1). I have a Linux Lite VM (basically Xubuntu 20.04) and a Windows insider developer build with Ubuntu 20.04 installed on top of WSLg (alpha software!) however, I get the same result in both VMs. Maybe something to do with running in a VM? I would be very grateful for any tips on how to fix this, or it may just be an obscure bug. I don't have a system running Linux bare metal, but may be able to set one up if needed.

**Precise recipe to reproduce the issue**
1. Start nyxt through desktop icon or on command-line.
2. Click the hamburger icon (buffers). The error in the title of this issue appears in the status bar, and in the console.

See full console debug output and .gif screen capture below.

**Information**
- OS name+version: Linux Lite x64 (similar to Xubuntu, based on Ubuntu 20.04.2 LTS)
- Graphics card and driver: driver=vmwgfx latency=64 (VMware Workstation 15.5.7 virtual machine without 3D acceleration enabled)
- Desktop environment / Window manager name+version: Xfce 4.14, distributed by Xubuntu, window manager xfwm4
- How you installed Nyxt (Guix pack, package manager, build from source): tried both .deb and .zip file, same result.
- Information from command copy-system-information:
```
Nyxt version: 2.0.0
Renderer version: GI-GTK
Operating system kernel: Linux 5.4.0-73-generic
Lisp implementation: SBCL 2.1.4
Features: (WEBKIT2 WEBKIT2-2.32 WEBKIT2-PASTE-PLAINTEXT WEBKIT2-TRACKING WEBKIT2-MUTE
 WEBKIT2-EMOJI WEBKIT2-MEDIA WEBKIT2-SANDBOXING GTK-3-22 GTK-3-20 GTK-3-18
 GTK-3-16 GTK-3-14 GTK-3-12 GTK-3-10 GTK-3-8 GTK-3-6 GTK-3-4 GTK GDK-3-22
 GDK-3-20 GDK-3-18 GDK-3-16 GDK-3-14 GDK-3-12 GDK-3-10 GDK-3-8 GDK-3-6 GDK-3-4
 CAIRO-1-10 CAIRO-1-12 GDK-PIXBUF GLIB-2-30 GLIB-2-32 GLIB-2-34 GLIB-2-36
 GLIB-2-38 GLIB-2-40 GLIB-2-42 GLIB-2-44 GLIB-2-46 GLIB-2-48 GLIB-2-50
 GLIB-2-52 GLIB-2-54 GLIB-2-56 GLIB-2-58 GLIB NYXT-2 FSET-EXT-STRINGS
 CUSTOM-HASH-TABLE-NATIVE SWANK PLUMP-UTF-32 GLOBAL-VARS DECLARE-TYPES
 PARENSCRIPT NAMED-READTABLES 21BIT-CHARS CHUNGA FLEXI-STREAMS CLOSER-MOP
 CL-PPCRE-UNICODE CL-UNICODE CL-PPCRE BORDEAUX-THREADS SPLIT-SEQUENCE
 GRAY-STREAMS FLAT-NAMESPACE X86-64 UNIX CFFI FLAT-NAMESPACE SEQUENCE-EMPTYP
 FAST-IO-SV FAST-IO SBCL-USES-SB-ROTATE-BYTE CL-JSON-CLOS CL-JSON
 THREAD-SUPPORT ASDF3.3 ASDF3.2 ASDF3.1 ASDF3 ASDF2 ASDF OS-UNIX
 NON-BASE-CHARS-EXIST-P ASDF-UNICODE X86-64 GENCGC 64-BIT ANSI-CL COMMON-LISP
 ELF IEEE-FLOATING-POINT LINUX LITTLE-ENDIAN PACKAGE-LOCAL-NICKNAMES
 SB-CORE-COMPRESSION SB-LDB SB-PACKAGE-LOCKS SB-THREAD SB-UNICODE SBCL UNIX)

ASDF version: 3.3.4
Critical dependencies: (/gnu/store/mk4pqs9ajxxizvh59xh69pyicxaw0xzv-sbcl-cl-cffi-gtk-0.11.2-2.e9a46df/share/common-lisp/sbcl/cl-cffi-gtk/gtk/cl-cffi-gtk.asd
 /gnu/store/1ngd71niv0rb2r0wphz5xf4anvj8m9jx-sbcl-cl-gobject-introspection-0.3-1.d0136c8/share/common-lisp/sbcl/cl-gobject-introspection/cl-gobject-introspection.asd
 /gnu/store/6414hy7gdlf3q15p7349hfrklq0qjq90-sbcl-cl-webkit-2.4-15.891bcd2/share/common-lisp/sbcl/cl-webkit/webkit2/cl-webkit2.asd)
```

**Output when started from a shell**
```
user@host:~/bin/nyxt$ ./usr/local/bin/nyxt --verbose

(process:28349): Gtk-WARNING **: 22:22:21.713: Locale not supported by C library.
	Using the fallback 'C' locale.
Gtk-Message: 22:22:21.715: Failed to load module "canberra-gtk-module"
Arguments parsed: (VERBOSE T URLS NIL) and NIL
 <INFO> [22:22:21] nyxt start.lisp (listen-or-query-socket) -
  Listening to socket "/run/user/1000/nyxt/nyxt.socket".
Nyxt version 2.0.0
 <INFO> [22:22:21] nyxt start.lisp (load-lisp unsafe-load) -
  Loading Lisp file "/home/user/.config/nyxt/auto-config.lisp".
<DEBUG> [22:22:21] nyxt start.lisp (load-lisp unsafe-load) -
  Lisp file "/home/user/.config/nyxt/init.lisp" does not exist.
<DEBUG> [22:22:21] nyxt renderer-gi-gtk.lisp (ffi-initialize gtk-browser) -
  Initializing GI-GTK Interface
<DEBUG> [22:22:22] nyxt base-mode.lisp (base-mode form-fun-20) -
  BASE-MODE enabled.
<DEBUG> [22:22:22] nyxt/web-mode web-mode.lisp (web-mode form-fun-28) -
  WEB-MODE enabled.
<DEBUG> [22:22:22] nyxt/emacs-mode emacs-mode.lisp (emacs-mode form-fun-30) -
  EMACS-MODE enabled.
<DEBUG> [22:22:22] nyxt/help-mode help-mode.lisp (help-mode form-fun-16) -
  HELP-MODE enabled.

(process:28389): Gtk-WARNING **: 22:22:22.273: Locale not supported by C library.
	Using the fallback 'C' locale.
Gtk-Message: 22:22:22.276: Failed to load module "canberra-gtk-module"

(process:28391): Gtk-WARNING **: 22:22:22.305: Locale not supported by C library.
	Using the fallback 'C' locale.
Gtk-Message: 22:22:22.310: Failed to load module "canberra-gtk-module"
<DEBUG> [22:22:22] nyxt/emacs-mode emacs-mode.lisp (emacs-mode form-fun-30) -
  EMACS-MODE enabled.
<DEBUG> [22:22:22] nyxt/prompt-buffer-mode prompt-buffer-mode.lisp (prompt-buffer-mode form-fun-19) -
  PROMPT-BUFFER-MODE enabled.

(process:28407): Gtk-WARNING **: 22:22:22.433: Locale not supported by C library.
	Using the fallback 'C' locale.
Gtk-Message: 22:22:22.435: Failed to load module "canberra-gtk-module"

(process:28431): Gtk-WARNING **: 22:22:24.185: Locale not supported by C library.
	Using the fallback 'C' locale.
Gtk-Message: 22:22:24.187: Failed to load module "canberra-gtk-module"
<DEBUG> [22:22:26] nyxt browser.lisp (preprocess-request) -
  Evaluate Lisp code from internal buffer: (NYXT::LIST-BUFFERS)/
<DEBUG> [22:22:26] nyxt renderer-gtk.lisp (on-signal-decide-policy gtk-buffer) -
  Don't forward to #<USER-STATUS-BUFFER {100B498433}>'s renderer (non request data).
; in: NYXT::LIST-BUFFERS
;     (NYXT::LIST-BUFFERS)
; 
; caught STYLE-WARNING:
;   undefined function: NYXT::LIST-BUFFERS
; 
; compilation unit finished
;   Undefined function:
;     NYXT::LIST-BUFFERS
;   caught 1 STYLE-WARNING condition
 <WARN> [22:22:26] nyxt message.lisp (echo-warning form-fun-6) -
  Warning: Error on separate thead: The function NYXT::LIST-BUFFERS is undefined.
```

**Screenshot recording**
![FCVMwDS4ij](https://user-images.githubusercontent.com/50889087/121469823-07d84200-c972-11eb-8e67-c5c114c3e1a5.gif)

Thanks to everyone working on Nyxt. It's fantastic.

**Comment by Ambrevar** [comment]
> Also, is "thead" in that message mean to be "thread?"

Good catch, fixed with 9d916bc64c4c64aebf10112310123925e8feb2c4.

**Comment by Ambrevar** [comment]
This issue is already fixed on master (9d916bc64c4c64aebf10112310123925e8feb2c4) next version will include it.

Feel free to reopen if there is anything else.

**Comment by SteveF4** [comment]
Thanks @Ambrevar! That was fast. What was the problem with NYXT::LIST-BUFFERS being undefined? Is it something in Nyxt 2.0.0, my system configuration, or something else...? Looking forward to the next release!

**Comment by Ambrevar** [comment]
Sorry, I previously shared the wrong commit, I've just updated the message.
The commit that fixes it is 4e2efb5a456d8d647f3eeaeb52cb21f96c92471c.

The issue comes from us moving `list-buffers` to `buffer-listing-mode` and forgetting to change the package prefix at the call sites.

**Comment by SteveF4** [comment]
Many thanks @Ambrevar! I was just able to get a developer build working, and it is indeed fixed in the local build.

**Comment by Ambrevar** [comment]
No worries :)
