### ISSUE TITLE
Restore some links in help startup page

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#1497]
Commit https://github.com/atlas-engineer/nyxt/commit/80ba244b11dcb7e509711d62d3cf834635fc3aca @jmercouris removed the link to Patreon and GitHub.

Interestingly, we never provided our home page! :p 
So instead, I suggest adding a reference to our home page and specify what users will find there:

- community platform
- bug report
- support the project.

Thoughts?

**Comment by jmercouris** [comment]
I am hesitant, URLs change, I think most users can do a search and find us very easily

**Comment by Ambrevar** [comment]
We do use nyxt.atlas.engineer as our reference point, e.g. in the manual
"Learn Lisp" links.

I think it's OK to refer to this one URL.
