### ISSUE TITLE
Have to type g twice in vi-insert mode

### ISSUE THREAD

**Issue by arjaz** [atlas-engineer/nyxt#1500]
**Describe the bug**
I need to type `g` twice to insert the letter while in the vi-insert mode in the prompt buffer and other input fields. 

**Precise recipe to reproduce the issue**
Type `gg` in the prompt buffer having `vi-insert` mode on: `M-x g g`

**Information**
- OS name+version: Arch Linux 5.12.9-arch1-1
- Graphics card and driver: NVIDIA GeForce GTX 1660 SUPER
- Desktop environment / Window manager name+version: Xmonad 0.15
- How you installed Nyxt (Guix pack, package manager, build from source): AUR
- Information from command copy-system-information: https://pastebin.com/k63W3sHF

**Output**
<INFO> [11:38:25] Pressed keys: g

**Comment by Ambrevar** [comment]
I can't reproduce.  Can you share your `init.lisp` file?

**Comment by arjaz** [comment]
https://pastebin.com/Ny90vTfP
Huh, guess that's because I'm binding `g i`, my bad.

**Comment by jmercouris** [comment]
There is then an ambiguity, Nyxt cannot know what to do :-)
