### ISSUE TITLE
Add command `show-clipboard`

### ISSUE THREAD

**Issue by pdelfino** [atlas-engineer/nyxt#1503]
While @jmercouris was instructing me on how to solve issue #765 , a new idea for a command emerged: the `show-clipboard`.

The command should indicate in the Nyxt mini-buffer what is inside the clipboard. The step-by-step to solve this _might_ be similar to PR #1501. For instance, the `(echo ...)` expression could be used.

The tags "good first issue" and "feature" might be appropriate.

**Comment by aartaka** [comment]
Given our reliance on `trivial-clipboard`, it can be hard to do -- the only thing this library provides in copying the top-most thing from the clipboard. But this is a nice feature to have (and, in fact, the one I dreamt about for a long time)!

**Comment by pdelfino** [comment]
PR #1506 was merged. Thus, I am closing this issue :)
