### ISSUE TITLE
Feature: mouse hover to see overlong text on prompt-fields

### ISSUE THREAD

**Issue by pdelfino** [atlas-engineer/nyxt#1517]
For instance, it is hard to read the `Docstring` info:

![image](https://user-images.githubusercontent.com/7698207/122287435-53857100-cec7-11eb-91d5-3f481a4d042f.png)

 Something like this would help:
![image](https://user-images.githubusercontent.com/7698207/122287530-6a2bc800-cec7-11eb-8c49-7bb6198c222c.png)

This could be useful for other prompt-fields, such as hint-descriptions. 

It is possible to find the information (e.g., what a command does), it just takes more actions, which hinders productivity.

I discussed this feature with "waleee" on IRC and he made great comments. I guess his user on Github  is @dtw-waleee

**Comment by Ambrevar** [comment]
This is a good idea!

As a side note, you can press `C-]` to toggle the display of some columns, which can give more space to display the largest columns.

**Comment by aartaka** [comment]
Fixed in 15f03f933459f996f4f065769b6a01d51a589b5e.
