### ISSUE TITLE
Soundcloud doesn't play

### ISSUE THREAD

**Issue by titibandit** [atlas-engineer/nyxt#1518]
**Describe the bug**
Playing a song from soundcloud.com plays just like half a second and then stops.

**Precise recipe to reproduce the issue**
Browse soundcloud.com and try to play any song from there.

**Information**
- OS name+version: Archlinux
- Graphics card and driver: 
- Desktop environment / Window manager name+version: i3
- How you installed Nyxt (Guix pack, package manager, build from source): AUR
- Information from command copy-system-information:

  If you can't run copy-system-information, try `nyxt --system-information` from
  a shell.  It this still does not work, please provide the following:
  - Nyxt version (from =M-x nyxt-version= or =nyxt --version=):
  - Lisp implementation/version (if built from source):
  - Kernel name+version:
  - WebKitGTK+ | QtWebEngine version:

**Output when started from a shell**
There is no error output

I have no idea how to debug this further. Is it an engine issue?

**Comment by Ambrevar** [comment]
Can you reproduce with Epiphany (GNOME Web)?

**Comment by titibandit** [comment]
Oh yeah, exactly the same happens in Gnome Web.

Pierre Neidhardt writes:

> Can you reproduce with Epiphany (GNOME Web)?

**Comment by jmercouris** [comment]
Then it is an engine issue!

**Comment by titibandit** [comment]
Yes you're right, it seems to be
https://bugs.webkit.org/show_bug.cgi?id=191419
So I guess we can close this issue since it's not nyxt related.
But in the webkit bug report, they say this can be circumvented by
changing the user-agent header string. How do I go about that in Nyxt?
Cheers

**Comment by jmercouris** [comment]
huh, I wonder if that could fix other issues as well... You'd have to reach out to cl-webkit to change the user agent string. We haven't easily exposed that in Nyxt. Perhaps we haven't even bound it in cl-webkit. I'm not sure actually.

**Comment by titibandit** [comment]
Hmmm okay... that's a little bit involved right now considering my nyxt
skill level :D Hopefully the webkit people can fix this bug, otherwise
I'll come back to this at a later point. Thanks for the help!

**Comment by titibandit** [comment]
oh yes, that

**Comment by jmercouris** [comment]
No problem! Thanks for the heads up, that would be a good feature for Nyxt indeed (changing the user agent)

**Comment by titibandit** [comment]
I mean, in that case, it really looks like an awful workaround, but
other than that, yes I think it is a nice feature to have!

**Comment by Ambrevar** [comment]
The discussion on user agent customization is here: https://github.com/atlas-engineer/nyxt/issues/1014

**Comment by titibandit** [comment]
They seem to have corrected that 2.5 years old bug in webkit just a few days ago!
https://bugs.webkit.org/attachment.cgi?id=431772&action=diff

**Comment by Ambrevar** [comment]
Fantastic, thanks for sharing!
