### ISSUE TITLE
How do I choose the exact user input from a prompt?

### ISSUE THREAD

**Issue by Zwo1in** [atlas-engineer/nyxt#1520]
Many times I have a problem of choosing an exact thing that I've typed into prompt. This happens mostly when (I think) nyxt doesn't recognize something as an url during opening a website, like on the screen below where I feel kinda forced to use ddg.
![user-input2](https://user-images.githubusercontent.com/34972409/122438799-61a4c180-cf9b-11eb-8e92-8951c70e9497.png)

Or here I have the same problem with add-domain-to-certificate-exception:
![user-input](https://user-images.githubusercontent.com/34972409/122438938-80a35380-cf9b-11eb-8578-c6451d863b20.png)

Is there a way to force choice of exact input? Or if not, could it become a feature request to do so? I think it is safe to assume that it cannot be 'smart' enough to always meet user expectations, there will always be a corner case.

**Comment by Zwo1in** [comment]
Second screenshot was supposed to be this:
![user-input](https://user-images.githubusercontent.com/34972409/122439840-48e8db80-cf9c-11eb-8973-89b14bd30a0f.png)

**Comment by dtw-waleee** [comment]
Do your system have/use the ~~/etc/hosts~~-file? Some linux-distributions use (nss)[https://man7.org/linux/man-pages/man5/nsswitch.conf.5.html] and one of the packages that nyxt depends upon had a bug when ~~/etc/hosts~~ didn't exist, https://github.com/atlas-engineer/nyxt/issues/1495. Which is fixed, but hasn't yet been pushed through to a quicklisp release yet.

**Comment by Zwo1in** [comment]
Hmmm, yes, I do have `/etc/hosts` file and also have `/etc/nsswitch.conf`. I'm sure that the latter is used by my system, but also hosts that I enter to `/etc/hosts` seems to be used (I can use aliases from there). This issue however is not regarding the `TLS Certificate Error` from the top of the screenshots but rather the prompt boxes which doesn't enter what I'd like them to.

**Comment by dtw-waleee** [comment]
It is your prompt-issue that can be caused by a missing `/etc/hosts`, but since you have the file and your system uses `nsswitch.conf`, I think you might be affected by an issue @edgar-vincent had/has, where his dns-setup caused/causes similar issues.

**Comment by jmercouris** [comment]
We should probably still include a raw input or something... not sure.

**Comment by Zwo1in** [comment]
> dns-setup caused/causes similar issues

Yeah, what you say is really likely. I already have some strange issues with name resolving while connected to corpo network with vpn, and there is a chance that I already messed something up trying to fix them.

> We should probably still include a raw input or something... not sure.

I feel such a need but maybe I'm biased because of issues I'm having. Can't say if I would still need this with ideal setup.

**Comment by Ambrevar** [comment]
John Mercouris ***@***.***> writes:

> We should probably still include a raw input or something... not sure.

Indeed,  add-domain-to-certificate-exception lacks a raw-input.  Will
fix as soon as possible.

For set-url, @Zwo1in you can prefix your URL with https:// and it should
work even if your DNS config is broken somehow.

**Comment by Ambrevar** [comment]
Done in 286b3f1da47f36abdb7356b85567aa24f5972252.

**Comment by Zwo1in** [comment]
I've also managed to fix my url prompt. It looks like I've got `dns` as a first choice in `hosts:` entry in my `/etc/nsswitch.conf`. Thanks :)

**Comment by Ambrevar** [comment]
Thanks for the update!
