### ISSUE TITLE
nyxt doesn't start up properly after build

### ISSUE THREAD

**Issue by D0nnieD4rk0** [atlas-engineer/nyxt#1531]
i get this

<WARN>  Warning: Error on separate thead: The variable %SLOT-DEFAULT is unbound.

**Comment by Ambrevar** [comment]
Do you have an existing ~/.config/nyxt/init.lisp?
If so, replace all the %SLOT-DEFAULT by %SLOT-DEFAULT% (trailing '%').

**Comment by D0nnieD4rk0** [comment]
why isn't this the default ???

**Comment by D0nnieD4rk0** [comment]
ok why does y not work while typing now ?

**Comment by Ambrevar** [comment]
Sorry, I didn't understand your question about the default.  Feel free to ask if there is any problem :)
