### ISSUE TITLE
"Open in new window" link context menu should be "open in new tab"

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#1535]
Indeed, the link is opened in a new tab.  

We could also have 2 entries, one for new windows, one for new tabs.

**Comment by TheCatster** [comment]
Two entries would definitely be convenient. There are times out of habit where I click instead of using keybindings, and that always confuses me. Having an option to also open in a new window would be quite convenient!

**Comment by jiggie42** [comment]
present behavior appears to be two entries
Open Link   #in new tab
Open Link in New Window

recommend closing as this appears to have been fixed some time ago 👍

**Comment by Ambrevar** [comment]
Yes, @aartaka fixed it a few days ago in https://github.com/atlas-engineer/nyxt/commit/72967d462c5295fbcced38854cc52eb499c6811d.

**Comment by Ambrevar** [comment]
Thanks for the heads up, @jiggie42 !
