### ISSUE TITLE
Set status bar links context menu entries to sensible actions

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#1536]
Copying or opening the status bar links yields things like `lisp://%28NYXT%3A%3ASWITCH-BUFFER-OR-QUERY-DOMAIN%20%22github.com%22%29` which is not very useful.

We should add better actions.

**Comment by jmercouris** [comment]
How so? Is switch-buffer-or-query not a sensible action for clicking on a ilnk?

**Comment by Ambrevar** [comment]
This issue is not with the left blick but the right click (which is called "context menu").  Actions like "Open link in new window" don't do what's intended.

**Comment by jmercouris** [comment]
I see, so you want to remove the context menu for the status buffer. That makes sense, we can do that relatively easily.

**Comment by jmercouris** [comment]
This is fixed on master. The context menu has been changed.
