### ISSUE TITLE
Host manual on nyxt.atlas.engineer

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#1538]
And make sure the version is mentioned explicitly at the top.

**Comment by Ambrevar** [comment]
https://nyxt.atlas.engineer/documentation is online!

@PhilHudson Which source do you mean?

**Comment by PhilHudson** [comment]
The source for the manual. I can't be more precise because I don't know where it is yet, and thus I also don't know what markup it uses. Hence the suggestion.

**Comment by jmercouris** [comment]
The manual is a dynamically compiled Lisp expression, it's not an RTF or a MD or ORG file we are converting, so I am not certain how valuable the source would be. What do you imagine a user may wish to do with the source?

**Comment by PhilHudson** [comment]
Contribute.

**Comment by Ambrevar** [comment]
This is the source:

https://github.com/atlas-engineer/nyxt/blob/master/source/manual.lisp

In short, you can contribute like you'd contribute with the rest of the
code, that is, by sending a pull request here on GitHub.

Do you think it's satisfactory?

**Comment by jmercouris** [comment]
The documentation now exists at : https://nyxt.atlas.engineer/documentation

I think anyone who wishes to contribute will probably look at the source on GitHub anyways :-)

Closing this for now unless you think there is something we haven't covered!
