### ISSUE TITLE
`delete-history-entry` is not showing the list of options in prompt-buffer

### ISSUE THREAD

**Issue by pdelfino** [atlas-engineer/nyxt#1542]
**Describe the bug**

A picture is worth a thousand words. In `Version 2.0.0-160-gdf425e5f` (current on master) the  `delete-history-entry` listing does **not** work :

![image](https://user-images.githubusercontent.com/7698207/122805391-6ae5a500-d29f-11eb-97d0-42ad6314931a.png)

Using the same environment and doing a downgrade,  it **does work** in version `Version 2.0.0-61-gf0ff09dd` :

![image](https://user-images.githubusercontent.com/7698207/122804996-ebf06c80-d29e-11eb-99aa-2b57c976cb6f.png)

This might be connected to this issue #1533 

**Precise recipe to reproduce the issue**
- `C-space`;
- `delete-history-entry`;
- see the absence options.

 **OS name+version:**
    Ubuntu 20.04.2 LTS

**Graphics card and driver:**
    product: Iris Plus Graphics 640
    configuration: driver=i915 latency=0

**Desktop environment / Window manager name+version:**
    Name: GNOME Shell 3.36.7
    Window manager's "showing the desktop" mode: OFF

**How you installed Nyxt (Guix pack, package manager, build from source):**
  Running from the source fetched/pulled from GitHub a few minutes ago.

  **Information from command copy-system-information:**
    Nyxt version: Version 2.0.0-160-gdf425e5f
    Renderer: GI-GTK
    Operating system kernel: Linux 5.8.0-53-generic
    Lisp implementation: SBCL 2.1.0.0.HEAD.1-46cb065
    Features: (WEBKIT2 WEBKIT2-2.30 WEBKIT2-TRACKING WEBKIT2-MUTE WEBKIT2-EMOJI
    WEBKIT2-MEDIA WEBKIT2-SANDBOXING GTK-3-22 GTK-3-20 GTK-3-18 GTK-3-16
    GTK-3-14 GTK-3-12 GTK-3-10 GTK-3-8 GTK-3-6 GTK-3-4 GTK GDK-3-22
    GDK-3-20 GDK-3-18 GDK-3-16 GDK-3-14 GDK-3-12 GDK-3-10 GDK-3-8
    GDK-3-6 GDK-3-4 CAIRO-1-10 CAIRO-1-12 GDK-PIXBUF GLIB-2-30 GLIB-2-32
    GLIB-2-34 GLIB-2-36 GLIB-2-38 GLIB-2-40 GLIB-2-42 GLIB-2-44
    GLIB-2-46 GLIB-2-48 GLIB-2-50 GLIB-2-52 GLIB-2-54 GLIB-2-56
    GLIB-2-58 GLIB FSET-EXT-STRINGS CUSTOM-HASH-TABLE-NATIVE SWANK
    PLUMP-UTF-32 GLOBAL-VARS DECLARE-TYPES PARENSCRIPT NAMED-READTABLES
    21BIT-CHARS CHUNGA FLEXI-STREAMS CLOSER-MOP CL-PPCRE-UNICODE
    CL-UNICODE BORDEAUX-THREADS SPLIT-SEQUENCE GRAY-STREAMS FAST-IO-SV
    FAST-IO SBCL-USES-SB-ROTATE-BYTE ASDF-SYSTEM-CONNECTIONS
    CL-JSON-CLOS CL-JSON THREAD-SUPPORT CL-PPCRE FLAT-NAMESPACE X86-64
    UNIX CFFI FLAT-NAMESPACE SEQUENCE-EMPTYP QUICKLISP ASDF3.3 ASDF3.2
    ASDF3.1 ASDF3 ASDF2 ASDF OS-UNIX NON-BASE-CHARS-EXIST-P ASDF-UNICODE
    X86-64 GENCGC 64-BIT ANSI-CL COMMON-LISP ELF IEEE-FLOATING-POINT
    LINUX LITTLE-ENDIAN PACKAGE-LOCAL-NICKNAMES SB-CORE-COMPRESSION
    SB-LDB SB-PACKAGE-LOCKS SB-THREAD SB-UNICODE SBCL UNIX)

**Output when started from a shell**

I do not start Nyxt from a shell. I start it inside the SLIME REPL with:
```
CL-USER> (nyxt:start)
<INFO> [14:45:07] Listening to socket "/run/user/1000/nyxt/nyxt.socket".
Nyxt version 2.0.0-160-gdf425e5f
<INFO> [14:45:07] Loading Lisp file "/home/pedro/.config/nyxt/auto-config.lisp".
<INFO> [14:45:07] Loading Lisp file "/home/pedro/.config/nyxt/init.lisp".
NIL
<INFO> [14:45:10] Pressed keys: C-m
<INFO> [14:45:10] Loading 40 bookmarks from "/home/pedro/.local/share/nyxt/bookmarks.lisp".
<WARN> [14:45:11] History version "2.0.0-61-gf0ff09dd" differs from current version "2.0.0-160-gdf425e5f"
<INFO> [14:45:11] Loading history of 1382 URLs from "/home/pedro/.local/share/nyxt/history/default.lisp".
<INFO> [14:45:12] Loading "https://blog.samaltman.com/".
<INFO> [14:45:13] Finished loading "https://blog.samaltman.com/".
```

**Comment by Ambrevar** [comment]
Thanks for reporting, fixed with 19f9f5a93aa82e97be33a65f1639d02c9db077ed.
