### ISSUE TITLE
vim-mode keymap conflict(s) in set-url-new-buffer input

### ISSUE THREAD

**Issue by jbenden** [atlas-engineer/nyxt#1544]
**Describe the bug**

I am unable to type certain keys into the `set-url-new-buffer` input dialog, as they are caught at [source/input.lisp:112](https://github.com/atlas-engineer/nyxt/blob/30a4e02bc8665e7d4119d4d1a54e963848d3bfdd/source/input.lisp#L112).

**Precise recipe to reproduce the issue**

1. Enable Vim keybindings.
2. Use the <kbd>O</kbd> binding, to trigger `set-url-new-buffer`.
3. Try to visit: `noaa.gov`
4. You should be unable to enter the <kbd>g</kbd> key.

**Information**
- OS name+version: Void Linux
- Graphics card and driver: Intel HD Graphics 630 (i915)
- Desktop environment / Window manager name+version: i3wm 4.19.1
- How you installed Nyxt (Guix pack, package manager, build from source): Guix pack and Source
- Information from command copy-system-information:
```
Nyxt version: 2.1.0
Renderer version: GI-GTK
Operating system kernel: Linux 5.12.12-tkg-pds_1
Lisp implementation: SBCL 2.1.5
Features: (WEBKIT2 WEBKIT2-2.32 WEBKIT2-PASTE-PLAINTEXT WEBKIT2-TRACKING WEBKIT2-MUTE
 WEBKIT2-EMOJI WEBKIT2-MEDIA WEBKIT2-SANDBOXING GTK-3-22 GTK-3-20 GTK-3-18
 GTK-3-16 GTK-3-14 GTK-3-12 GTK-3-10 GTK-3-8 GTK-3-6 GTK-3-4 GTK GDK-3-22
 GDK-3-20 GDK-3-18 GDK-3-16 GDK-3-14 GDK-3-12 GDK-3-10 GDK-3-8 GDK-3-6 GDK-3-4
 CAIRO-1-10 CAIRO-1-12 GDK-PIXBUF GLIB-2-30 GLIB-2-32 GLIB-2-34 GLIB-2-36
 GLIB-2-38 GLIB-2-40 GLIB-2-42 GLIB-2-44 GLIB-2-46 GLIB-2-48 GLIB-2-50
 GLIB-2-52 GLIB-2-54 GLIB-2-56 GLIB-2-58 GLIB NYXT-2 FSET-EXT-STRINGS
 CUSTOM-HASH-TABLE-NATIVE SWANK PLUMP-UTF-32 GLOBAL-VARS DECLARE-TYPES
 PARENSCRIPT NAMED-READTABLES 21BIT-CHARS CHUNGA FLEXI-STREAMS CLOSER-MOP
 CL-PPCRE-UNICODE CL-UNICODE CL-PPCRE BORDEAUX-THREADS SPLIT-SEQUENCE
 GRAY-STREAMS FLAT-NAMESPACE X86-64 UNIX CFFI FLAT-NAMESPACE SEQUENCE-EMPTYP
 FAST-IO-SV FAST-IO SBCL-USES-SB-ROTATE-BYTE CL-JSON-CLOS CL-JSON
 THREAD-SUPPORT ASDF3.3 ASDF3.2 ASDF3.1 ASDF3 ASDF2 ASDF OS-UNIX
 NON-BASE-CHARS-EXIST-P ASDF-UNICODE X86-64 GENCGC 64-BIT ANSI-CL COMMON-LISP
 ELF IEEE-FLOATING-POINT LINUX LITTLE-ENDIAN PACKAGE-LOCAL-NICKNAMES
 SB-CORE-COMPRESSION SB-LDB SB-PACKAGE-LOCKS SB-THREAD SB-UNICODE SBCL UNIX)

ASDF version: 3.3.4
Critical dependencies: (/gnu/store/7yrp5l3hrqv7ni7jwn5g8a40j802ymmy-sbcl-cl-cffi-gtk-0.11.2-2.e9a46df/share/common-lisp/sbcl/cl-cffi-gtk/gtk/cl-cffi-gtk.asd
 /gnu/store/d9r2l7zml4sihyg6z9yfndiqh2kdkia7-sbcl-cl-gobject-introspection-0.3-1.d0136c8/share/common-lisp/sbcl/cl-gobject-introspection/cl-gobject-introspection.asd
 /gnu/store/q1426jkrq4jw1hm40p8x8r86qw0hpk12-sbcl-cl-webkit-2.4-16.cfc4f01/share/common-lisp/sbcl/cl-webkit/webkit2/cl-webkit2.asd)
```

**Output when started from a shell**

**Comment by dtw-waleee** [comment]
Hello! (I meant to answer you on IRC but you had quit).

The issue you have is because the default vi-mode for the prompt-buffer is `vi-normal-mode` (... even if you can enter text), so `g` is used as a prefix for eg. `gg` , `gG` and some others. The current workaround would either be to switch to `vi-insert-mode` each time with `i`, or change the default vi-mode in the prompt-buffer to `vi-insert-mode` in your `init.lisp` configuration for nyxt.

**Comment by Ambrevar** [comment]
Note that if you configure Nyxt 2.1 graphically to use VI bindings, this
is now done automatically for you.

**Comment by jbenden** [comment]
Thanks!

**Comment by Ambrevar** [comment]
Thanks for reporting :)
