### ISSUE TITLE
Possible bug: I cannot delete all bookmarks with `delete-bookmark`, `M-a`, `return`

### ISSUE THREAD

**Issue by pdelfino** [atlas-engineer/nyxt#1545]
Hi guys,

I came across this accidentally as I was doing some tests for issue #1310. I think there is a possible bug. 

**Describe the bug**

I cannot delete all of the bookmarks at once using `delete-bookmark`, `M-a`, `return`. Even doing, quitting Nyxt, emacs, and re-starting the PC won't solve. This is my [current local bookmarks](https://github.com/pdelfino/public-notes/blob/main/bookmarks-back-up.lisp) file if you wanna have a look.

Observation: if I press `list-bookmarks` and if I click on the button `delete` I can delete a single bookmark, for instance. The problem is when I try to delete everything with the command.

**Precise recipe to reproduce the issue**

(if you care about your bookmarks, it would be better to do a back-up first)
- execute command `delete-bookmark`;
- select all `M-a`;
- press `return`
- close Nyxt, emacs, and restart your PC;
- execute command `set-url-from-bookmark` to see how many options are available OR execute command `list-bookmarks`.

**OS name+version:**
    Ubuntu 20.04.2 LTS

**Graphics card and driver:**
    product: Iris Plus Graphics 640
    configuration: driver=i915 latency=0

**Desktop environment / Window manager name+version:**
    Name: GNOME Shell 3.36.7
    Window manager's "showing the desktop" mode: OFF

**How you installed Nyxt (Guix pack, package manager, build from source):**
  Running from the source fetched/pulled from GitHub today.

  **Information from command copy-system-information:**
Nyxt version: 2.1.0-8-gfd219899
Renderer version: GI-GTK
Operating system kernel: Linux 5.8.0-55-generic
Lisp implementation: SBCL 2.0.1.debian
Features: (WEBKIT2 WEBKIT2-2.32 WEBKIT2-PASTE-PLAINTEXT WEBKIT2-TRACKING WEBKIT2-MUTE
 WEBKIT2-EMOJI WEBKIT2-MEDIA WEBKIT2-SANDBOXING GTK-3-22 GTK-3-20 GTK-3-18
 GTK-3-16 GTK-3-14 GTK-3-12 GTK-3-10 GTK-3-8 GTK-3-6 GTK-3-4 GTK GDK-3-22
 GDK-3-20 GDK-3-18 GDK-3-16 GDK-3-14 GDK-3-12 GDK-3-10 GDK-3-8 GDK-3-6 GDK-3-4
 CAIRO-1-10 CAIRO-1-12 GDK-PIXBUF GLIB-2-30 GLIB-2-32 GLIB-2-34 GLIB-2-36
 GLIB-2-38 GLIB-2-40 GLIB-2-42 GLIB-2-44 GLIB-2-46 GLIB-2-48 GLIB-2-50
 GLIB-2-52 GLIB-2-54 GLIB-2-56 GLIB-2-58 GLIB NYXT-2 FSET-EXT-STRINGS
 CUSTOM-HASH-TABLE-NATIVE PLUMP-UTF-32 GLOBAL-VARS DECLARE-TYPES PARENSCRIPT
 NAMED-READTABLES 21BIT-CHARS CHUNGA FLEXI-STREAMS CLOSER-MOP CL-PPCRE-UNICODE
 CL-UNICODE CL-PPCRE BORDEAUX-THREADS SPLIT-SEQUENCE GRAY-STREAMS
 FLAT-NAMESPACE X86-64 UNIX CFFI FLAT-NAMESPACE SEQUENCE-EMPTYP FAST-IO-SV
 FAST-IO SBCL-USES-SB-ROTATE-BYTE ASDF-SYSTEM-CONNECTIONS CL-JSON-CLOS CL-JSON
 THREAD-SUPPORT SWANK QUICKLISP SB-BSD-SOCKETS-ADDRINFO ASDF3.3 ASDF3.2 ASDF3.1
 ASDF3 ASDF2 ASDF OS-UNIX NON-BASE-CHARS-EXIST-P ASDF-UNICODE X86-64 64-BIT
 ANSI-CL COMMON-LISP ELF GENCGC IEEE-FLOATING-POINT LINUX LITTLE-ENDIAN
 PACKAGE-LOCAL-NICKNAMES SB-CORE-COMPRESSION SB-LDB SB-PACKAGE-LOCKS SB-THREAD
 SB-UNICODE SBCL UNIX)

ASDF version: 3.3.1
Critical dependencies: (/home/pedro/.quicklisp/dists/quicklisp/software/cl-cffi-gtk-20201220-git/gtk/cl-cffi-gtk.asd
 /home/pedro/.quicklisp/dists/quicklisp/software/cl-gobject-introspection-20210124-git/cl-gobject-introspection.asd
 /home/pedro/common-lisp/cl-webkit/webkit2/cl-webkit2.asd)

Quicklisp dist version: 2021-05-31
Quicklisp client version: 2021-02-13
Local project directories: (/home/pedro/.quicklisp/local-projects/)
Critical dependencies(#<SYSTEM cl-cffi-gtk / cl-cffi-gtk-20201220-git / quicklisp 2021-05-31>
 #<SYSTEM cl-gobject-introspection / cl-gobject-introspection-20210124-git / quicklisp 2021-05-31>
 #<SYSTEM cl-webkit2 / cl-webkit-20210531-git / quicklisp 2021-05-31>)

**Output when started from a shell**

I do not start Nyxt from a shell. I start it inside the SLIME REPL with:
```
CL-USER> (nyxt:start)
<INFO> [16:39:34] Listening to socket "/run/user/1000/nyxt/nyxt.socket".
Nyxt version 2.1.0-8-gfd219899
<INFO> [16:39:34] Loading Lisp file "/home/pedro/.config/nyxt/auto-config.lisp".
<INFO> [16:39:34] Loading Lisp file "/home/pedro/.config/nyxt/init.lisp".
NIL
```

**Comment by Ambrevar** [comment]
Good catch!  Fixed with c5b38e02ff629fbcb074f3207ddb6fde0d63c437.
