### ISSUE TITLE
Sort and indent headings

### ISSUE THREAD

**Issue by phw** [atlas-engineer/nyxt#155]
The jump to heading feature is one of the coolest feature of this browser. However, the heading listing seems to be sorted rather randomly and has no indication of the structure of headings.

It would be great if headings could be sorted in the order they appear (or at least document order) and indicate their level e.g. by indenting sub headings

**Comment by jmercouris** [comment]
That is a very good suggestion! I assume H1 at the top level, and then H2 indented further etc etc. I really like your idea! Thank you!

With regards to sort order, I have no idea honestly what it is based on, somehow JS decides to traverse the document, I am really not sure how.

I would also like to make it a little bit more intelligent and be able to type in keywords or something, so type "Jump to heading" and start typing phrases, like "fish, food, salmon" and it suggests to me headings that have paragraphs below it containing those words. A little bit of a smarter jump, do you know what I mean?

Lastly, I would like to implement a "jump across all buffers" which I think would be really cool, allowing you to jump anywhere within all of your open buffers, but that is quite a bit more complex!

**Comment by Ambrevar** [comment]
That'd be awesome indeed!

**Comment by vindarel** [comment]
About the sort order, where do you experience this ? It is ok for me here:

- https://next.atlas.engineer/quickstart
- https://lispcookbook.github.io/cl-cookbook/editor-support.html
- http://wikemacs.org/
- https://en.wikipedia.org/wiki/Lisp_(programming_language)

**Comment by aartaka** [comment]
4df71688e7a49809353527e4404ef40edb5e2eb3 should finally get us sorted headings, given that our `document-model` has clear ordered idntifiers matching the structure of the DOM.
