### ISSUE TITLE
"Owner with identifier x does not exist" - constant crashing

### ISSUE THREAD

**Issue by ncryptid** [atlas-engineer/nyxt#1550]
**Describe the bug**

Nyxt crashes on loading a session while trying to switch to one of my open buffers and will give an error like this (the number varies):

```
<WARN> [22:32:03] Warning: Failed to restore history from /home/nyx/.local/share/nyxt/history/default.lisp: Owner with identifier "8" does not exist
Unhandled SIMPLE-ERROR in thread #<SB-THREAD:THREAD "Prompter follow selection thread" RUNNING
                                    {10070E8D23}>:
  Owner with identifier "8" does not exist
```

If I manually restore the session by running `restore-history-by-name`, I can continue to browse and switch buffers etc., but it seems noticeably unstable and will crash frequently and seemingly randomly while trying to load a new URL. The site in question doesn't seem to affect it, but it returns an error like this, which seems to indicate that it's related to this problem:

```
<WARN> [22:32:59] Warning: Error on GTK thread: There is no applicable method for the generic function
                       #<STANDARD-GENERIC-FUNCTION HISTORY-TREE:DATA (2)>
                     when called with arguments
                       (NIL).
```

This may have been related to an issue I had where Nyxt was trying to load a URL and taking a long time to do so (I think it was Reddit), and then became unresponsive to the point where I could open the prompt buffer but it wouldn't let me run any comands and would stay on the same page it was trying to load. I had to kill the process manually but that's when I started to notice this issue. 

I could probably just delete my history file and start fresh, but I would prefer not to lose my entire browsing history.

**Precise recipe to reproduce the issue**

1. Go to ~some site that Nyxt can't load
2. Kill Nyxt while it's hung up and can't run any commands
3. Restore the session, receiving an error about an owner with identifier x not existing
4. Attempt to switch buffers by scrolling through the open ones
5. crash

**Information**
- OS name+version: Devuan Beowulf
- Graphics card and driver: whatever integrated Intel GPU a Thinkpad X230 has
- Desktop environment / Window manager name+version: StumpWM 20.11
- How you installed Nyxt (Guix pack, package manager, build from source): build from source
- Information from command copy-system-information:

```
Nyxt version: 2.1.0
Renderer version: GI-GTK
Operating system kernel: Linux 4.19.0-16-amd64
Lisp implementation: SBCL 2.1.4
Features: (SLYNK WEBKIT2 WEBKIT2-2.30 WEBKIT2-PASTE-PLAINTEXT WEBKIT2-TRACKING
 WEBKIT2-MUTE WEBKIT2-EMOJI WEBKIT2-MEDIA WEBKIT2-SANDBOXING GTK-3-22 GTK-3-20
 GTK-3-18 GTK-3-16 GTK-3-14 GTK-3-12 GTK-3-10 GTK-3-8 GTK-3-6 GTK-3-4 GTK
 GDK-3-22 GDK-3-20 GDK-3-18 GDK-3-16 GDK-3-14 GDK-3-12 GDK-3-10 GDK-3-8 GDK-3-6
 GDK-3-4 CAIRO-1-10 CAIRO-1-12 GDK-PIXBUF GLIB-2-30 GLIB-2-32 GLIB-2-34
 GLIB-2-36 GLIB-2-38 GLIB-2-40 GLIB-2-42 GLIB-2-44 GLIB-2-46 GLIB-2-48
 GLIB-2-50 GLIB-2-52 GLIB-2-54 GLIB-2-56 GLIB-2-58 GLIB NYXT-2 FSET-EXT-STRINGS
 CUSTOM-HASH-TABLE-NATIVE SWANK PLUMP-UTF-32 CL-PPCRE-UNICODE GLOBAL-VARS
 DECLARE-TYPES PARENSCRIPT SBCL+SAFE-STANDARD-READTABLE NAMED-READTABLES
 21BIT-CHARS CHUNGA GRAY-STREAMS FAST-IO-SV FAST-IO SBCL-USES-SB-ROTATE-BYTE
 ASDF-SYSTEM-CONNECTIONS CLOSER-MOP SPLIT-SEQUENCE CL-UNICODE FLEXI-STREAMS
 CL-PPCRE CL-JSON-DOUBLE-FLOAT-IS-SUBSUMED CL-JSON-SINGLE-FLOAT-IS-SUBSUMED
 CL-JSON-CLOS CL-JSON BORDEAUX-THREADS THREAD-SUPPORT FLAT-NAMESPACE X86-64
 UNIX CFFI FLAT-NAMESPACE SEQUENCE-EMPTYP QUICKLISP ASDF3.3 ASDF3.2 ASDF3.1
 ASDF3 ASDF2 ASDF OS-UNIX NON-BASE-CHARS-EXIST-P ASDF-UNICODE X86-64 GENCGC
 64-BIT ANSI-CL COMMON-LISP ELF IEEE-FLOATING-POINT LINUX LITTLE-ENDIAN
 PACKAGE-LOCAL-NICKNAMES SB-LDB SB-PACKAGE-LOCKS SB-THREAD SB-UNICODE SBCL UNIX)

ASDF version: 3.3.1
Critical dependencies: (/home/nyx/common-lisp/nyxt/_build/submodules/cl-cffi-gtk/gtk/cl-cffi-gtk.asd
 /home/nyx/common-lisp/nyxt/_build/quicklisp-client/dists/quicklisp/software/cl-gobject-introspection-20210124-git/cl-gobject-introspection.asd
 /home/nyx/common-lisp/nyxt/_build/submodules/cl-webkit/webkit2/cl-webkit2.asd)

Quicklisp dist version: 2021-05-31
Quicklisp client version: 2020-01-04
Local project directories: (/home/nyx/common-lisp/nyxt/_build/submodules/
 /home/nyx/common-lisp/nyxt/_build/quicklisp-client/local-projects/)
Critical dependencies(#<SYSTEM cl-cffi-gtk / cl-cffi-gtk-20201220-git / quicklisp 2021-05-31>
 #<SYSTEM cl-gobject-introspection / cl-gobject-introspection-20210124-git / quicklisp 2021-05-31>
 #<SYSTEM cl-webkit2 / cl-webkit-20210531-git / quicklisp 2021-05-31>)

Guix version: f7d2ae57543ae6afe14434877d7480b15dcbb5b7
```

**Comment by Ambrevar** [comment]
Yes, I've experience this as well and I believe it's a 0-day bug that
I've fixed with 5bdc58fed8ce96f5fb718229e7420acb84d8620f.

Are you able to test master and confirm this fixes it for you?

If so, I suggest we release 2.1.1 as soon as possible.  @jmercouris.

**Comment by ncryptid** [comment]
Just compiled from master and it does indeed appear to be working :sparkles:

**Comment by jmercouris** [comment]
Agreed Pierre

**Comment by Ambrevar** [comment]
Also see #1564 for a related bug fix.
