### ISSUE TITLE
Delete copy-username now that we have a 2nd action

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#1551]
In 6f0b9b612fdc996b7020441fa15beb2a504445e4 I added a second action to the password source.   It clips the username, just like the `copy-username` command.

Shall we remove the `copy-username` command now that it's largely obsoleted?

**Comment by jmercouris** [comment]
Let's hold off on this. I am still not sold on how we decompose actions into single commands.

**Comment by Ambrevar** [comment]
Note that copy-username was just introduced post 2.1, so if we remove it now then
users won't see any change.

**Comment by Ambrevar** [comment]
No longer true, so now we either wait for 3.0, or... Just keep it actually, username copying is the most frequent action with password copying.  Other fields don't need dedicated commands, but it makes sense to have one for username so that users can easily bind a key to it.
