### ISSUE TITLE
Not able to add a new search engine

### ISSUE THREAD

**Issue by Blade6570** [atlas-engineer/nyxt#1554]
**Describe the bug**
I followed this https://github.com/atlas-engineer/nyxt/issues/735 and tried to add my new search engines in my init.lisp file but no success. I tried 
```
(defvar *my-search-engines* nil)
(setf *my-search-engines*
      (list
       '("google" "https://www.google.com/search?q=~a" "https://www.google.com/")
       '("quickdocs" "http://quickdocs.org/search?q=~a" "http://quickdocs.org/")
       '("wiki" "https://en.wikipedia.org/w/index.php?search=~a" "https://en.wikipedia.org/")
       '("define" "https://en.wiktionary.org/w/index.php?search=~a" "https://en.wiktionary.org/")
       '("python3" "https://docs.python.org/3/search.html?q=~a" "https://docs.python.org/3")
       '("doi" "https://dx.doi.org/~a" "https://dx.doi.org/")))

(define-configuration browser
  ((search-engines (append (mapcar #'make-search-engine *my-search-engines*)
                           %slot-default%))))
```
Also, I tried 

```
(define-configuration browser
  ((search-engines (list "google" (append (make-search-engine "gg" "http://quickdocs.org/search?q=~a" "http://quickdocs.org/") %slot-default%)))))

```
with no success. When I try to add the above snippet to the search-engine buffer slot from the browser, it shows a warning message as search-engine expects (CONS, sear-engine *), while you provided only CONS. A proper manual on adding new search engine is also missing. 

**Precise recipe to reproduce the issue**

**Information**
- OS name+version: Ubuntu 20.04
- Graphics card and driver: Nvidia 42**
- Desktop environment / Window manager name+version: DWM 6.3
- How you installed Nyxt (Guix pack, package manager, build from source): build from source
- Information from command copy-system-information:

  If you can't run copy-system-information, try `nyxt --system-information` from
  a shell.  It this still does not work, please provide the following:
  - Nyxt version (from =M-x nyxt-version= or =nyxt --version=):
  - Lisp implementation/version (if built from source):
  - Kernel name+version:
  - WebKitGTK+ | QtWebEngine version:

**Output when started from a shell**

**Comment by ericdrgn** [comment]
Glad I'm not alone. FWIW I asked for related help on the forum (https://discourse.atlas.engineer/t/search-engine-help/190) though you gave more detail and I am looking for general guidance around it. I have also tried the above (and a lot of other random things) with no luck.

**Comment by AP2008** [comment]
Shouldn't it be `%slot-default` instead of `%slot-default%` ?

**Comment by jmercouris** [comment]
It is `%slot-default%` in the latest version of Nyxt :-)

**Comment by jmercouris** [comment]
Also @ericdrgn I saw your post on the forum right before I fell asleep but did not have time to answer, I will try to help ASAP!

**Comment by AP2008** [comment]
Does this work : `(mapcar #'(lambda (x) (apply #'make-search-engine x)) *my-search-engines*)` ?

**Comment by jmercouris** [comment]
Here is the correct code:

```
(defvar *my-search-engines*
  (list
   '("google" "https://www.google.com/search?q=~a" "https://www.google.com/")
   '("quickdocs" "http://quickdocs.org/search?q=~a" "http://quickdocs.org/")
   '("wiki" "https://en.wikipedia.org/w/index.php?search=~a" "https://en.wikipedia.org/")
   '("define" "https://en.wiktionary.org/w/index.php?search=~a" "https://en.wiktionary.org/")
   '("python3" "https://docs.python.org/3/search.html?q=~a" "https://docs.python.org/3")
   '("doi" "https://dx.doi.org/~a" "https://dx.doi.org/")))

(define-configuration buffer
  ((search-engines (append (mapcar (lambda (engine) (apply 'make-search-engine engine))
                                   *my-search-engines*)
                           %slot-default%))))

```

**Comment by jmercouris** [comment]
@AP2008 You were very close, part of the problem was indeed the apply, the other part was that it is a slot of the buffer class, not the browser class :-)

**Comment by edgar-vincent** [comment]
I think this should be mentioned in the manual, as I'm sure many users will want to know how to do this.

**Comment by Blade6570** [comment]
@jmercouris It is working now.  Thanks a lot. I like this browser a lot but the lack of proper documentation is a kind of pain. Anyway for now everything is at peace. :)

**Comment by jmercouris** [comment]
Perhaps it should be added to the manual. Anyone willing to submit a pull request?

**Comment by Blade6570** [comment]
I can add this example under `search-engine` heading in manual.lisp. If this is okay then I will submit the pull request.

**Comment by jmercouris** [comment]
Sure, please make it nice and explain a little bit :-)

**Comment by ericdrgn** [comment]
@jmercouris No worries at all! It seems we are on opposite schedules for sleep so I expect a delay. Thanks for all the work you're doing on this and being so helpful! I'll get it all tested on my end tonight.

@Blade6570 Thanks for submitting the thorough request and helping out with updating the manual. Love to see devs and communities like this (found nyxt literally days ago so just starting to get involved)

**Comment by Blade6570** [comment]
Thanks a lot for the help. Closing it now :)

**Comment by jmercouris** [comment]
Merci!
