### ISSUE TITLE
Selecting `search-buffer` candidates doesn't bring them into focus on certain pages

### ISSUE THREAD

**Issue by edgar-vincent** [atlas-engineer/nyxt#1555]
- Go to https://github.com/ndwarshuis/org-ml/blob/master/docs/api-reference.md
- Call `search-buffer` and type "build"
- Candidates appear in the prompt-buffer, but selecting them doesn't bring them into focus.

Moreover, the order of search candidate ID's seems to be wrong:
- On the same page, search for "string"
- The "Secondary strings" candidate has ID 2 although it is not the second candidate.

It seems that internal links are displayed first.

**Comment by Ambrevar** [comment]
The problem is that Nyxt matches non-visible elements.

For instance if you search `build` and go past the first 80 matches or so, the it starts focussing.

The second issue with ID ordering might be the same problem.

@jmercouris Do you know how to fix this?

**Comment by jmercouris** [comment]
I do know how to fix this, kind of. Determining whether an element is visible or not can depend on many factors.
