### ISSUE TITLE
Selecting the first candidate of a `search-buffer` search doesn't make it visible

### ISSUE THREAD

**Issue by edgar-vincent** [atlas-engineer/nyxt#1556]
- Open https://github.com/ndwarshuis/org-ml/blob/master/docs/api-reference.md
- Search for `conversion`
- Move down to the last candidate, then back up to the first one.
- The first candidate is not visible on the page.

**Comment by Ambrevar** [comment]
I believe this is the same as #1555.

**Comment by Ambrevar** [comment]
Closing in favour of #1555.
