### ISSUE TITLE
A command to duplicate buffer OR make related buffer?

### ISSUE THREAD

**Issue by aartaka** [atlas-engineer/nyxt#1557]
Firefox has such a thing as "Duplicate Tab" action, though I'm not sure how it's implemented. We can make our `make-duplicate-buffer` to copy a current-buffer (I've had several moments I needed this). 

What can be even better is to implement a `make-related-buffer` command that'd rely on [renderer-level resource sharing](https://webkitgtk.org/reference/webkit2gtk/stable/WebKitWebView.html#webkit-web-view-new-with-related-view) to lower the resource consumption. 

Tighter buffer interrelations can come in handy in history too.

How's that looking?

**Comment by Ambrevar** [comment]
Good idea.

For the GHT, I suppose that a duplicate buffer would share the same
parent.

About the WebKit related view, I think we ought to abstract this well
enough and ensure it's an impmlementation detail.  Not all renderers
might be able to do this.

**Comment by Ambrevar** [comment]
In particular, it could be nice to duplicate the modes.

A related feature would be to "open link in duplicate buffer": only too often I browse a buffer with special modes, but when I want to open a link in a new buffer I need to set the modes again.

**Comment by aartaka** [comment]
That I can relate to, yes!

**Comment by shaunsingh** [comment]
I believe this can be closed now `duplicate-buffer` and `duplicate-buffer-with-current-modes`

**Comment by jmercouris** [comment]
You're absolutely correct, good catch :-)
