### ISSUE TITLE
Allow arbitrary HTML in mode glyphs.

### ISSUE THREAD

**Issue by aartaka** [atlas-engineer/nyxt#1558]
There were several requests for such thing on IRC, especially with ability to use images intead of textual glyphs. 

This is also backwards-compatible, as current textual glyphs are perfectly fine as HTML text.

**Comment by Ambrevar** [comment]
Agreed!

After one, it's one of the places where Nyxt really shines compared to
Emacs :)

**Comment by aartaka** [comment]
Done in 4a72f251c17566a82d494f11af1f4cea79c58c3f.
