### ISSUE TITLE
Feature request: make `bookmark-url` work as `bookmark-current-url` concerning the extraction of the **title**

### ISSUE THREAD

**Issue by pdelfino** [atlas-engineer/nyxt#1559]
Hi,

While I was implementing @jmercouris suggestions on PR #1548 I realized the command `bookmark-url` does not automatically get the title of the page. This **already works** for `bookmark-current-url`.

I think this is an important data since the *fuzzy search* acts on it. Moreover, it could be automatically added without extra effort from the user. I reckon I know how to do it. I can do it after or while improving PR #1548 for issue #1310. 

Curious about your thoughts.

**Comment by Ambrevar** [comment]
bookmark-url takes an arbitrary URL, not a buffer, so it cannot know the
title without loading the URL first, which might not be desirable.

Does that make sense?  Do you suggest something else?

**Comment by pdelfino** [comment]
> so it cannot know the title without loading the URL first, which might not be desirable. 

Oh, sorry. I thought loading the URL would not be a problem since the user is typing the whole address. Why it might not be desirable to load the URL? Decreasing speed? Security?  

Maybe, it could be a tweaked "loading". For instance, loading it without JS (using noscript-mode) or getting just the raw HTML without renderization (not sure if this is already possible).

"Losing" the title for this manual bookmark seems worse. At least in my experience, the titles really help me find what I want.

As I become a heavy user of Nyxt, I think my bookmark list tends to be bigger since it is so easier and better to bookmark stuff (in comparison to firefox).

**Comment by Ambrevar** [comment]
Isn't it just easier to first load the URL you want to bookmark, then
call `bookmark-current-url`?

**Comment by pdelfino** [comment]
> Isn't it just easier to first load the URL you want to bookmark, then call `bookmark-current-url`?

Well, yeah. But, why having the command `bookmark-url` then? 

It would be possible to use exactly the same argument to remove it completely from code base, right?

Maybe I misunderstood something about why this command exists. Could you please explain what is the purpose of `bookmark-url`?
Also, why is the webpage title **irrelevant** for this goal?


Just to provide some background, this occurred to me while implementing [this suggestion](https://github.com/atlas-engineer/nyxt/pull/1548#discussion_r657959532) from @jmercouris 's code review. 

My original implementation was catching the **title** of web pages frequently visited but not yet bookmarked. As he suggested the use of `bookmark-url` as a change (that I already coded), I noticed that with the new change the code stopped getting the page title which is a relevant data to bookmarks (imho).

**Comment by Ambrevar** [comment]
> Maybe I misunderstood something about why this command exists. Could you please explain what is the purpose of `bookmark-url`?

To bookmark an arbitrary URL, not just the URL of an existing buffer.

> My original implementation was catching the **title** of web pages
> frequently visited but not yet bookmarked.

Never rely on titles.  Titles are prone to change from one visit to the
next.  You should always rely on the URL instead.
Bookmarks are indexed by URLs, not by title.

**Comment by pdelfino** [comment]
OK. Thanks for the explanation! 

I am closing this issue.
