### ISSUE TITLE
FR/Help No undo/redo command

### ISSUE THREAD

**Issue by florhizome** [atlas-engineer/nyxt#1561]
I just found that during writing stuff in the issues here, I can't find a way of undoing text input/editing? (If there was a way to do that, redoing would be needed, too, I guess).

**Comment by florhizome** [comment]
I'm in emacs mode in nyxt 2.1.0, btw.

**Comment by Ambrevar** [comment]
True, `C-z` does not work.  I thought it was a native WebKitGTK binding, so either something is wrong on Nyxt's side, or we need to enable it.

**Comment by Ambrevar** [comment]
Got it, we need to leverage https://webkitgtk.org/reference/webkit2gtk/2.9.3/WebKitWebView.html#webkit-web-view-can-execute-editing-command.

Can we do it in pure JavaScript?

**Comment by florhizome** [comment]
Uhm I think I can't really help there if this was a question for me ^^

**Comment by Ambrevar** [comment]
Maybe a question for @jmercouris @aartaka then :)

**Comment by aartaka** [comment]
No way to implement it in JS except severely modifying inputs and writing a lot of Parenscript.

Editing actions are what we need, yes.

**Comment by aartaka** [comment]
Editing command, I mean.

**Comment by aartaka** [comment]
It's done in #1858.
