### ISSUE TITLE
Allow external editor in any HTML editable element

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#1565]
See https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/isContentEditable.

Looks like we need to use JavaScript to check whether an element is editable or not.

**Comment by ag91** [comment]
To add a bit of context, this is the bit of code (I found so far) that enumerates the tags for which external editing is allowed: https://github.com/atlas-engineer/nyxt/blob/master/source/external-editor.lisp#L26

**Comment by Ambrevar** [comment]
Example where it does not work: https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_input_test

**Comment by primeTanM** [comment]
what exactly is the issue?

**Comment by primeTanM** [comment]
What exactly is the issue? Do you want to not check ```contenteditable=true``` everytime you want to edit a element.Please elaborate

**Comment by ag91** [comment]
The fact that you cannot use this functionality in every input fields. Only INPUT and TEXTAREA are allowed so far. I mentioned that above with a link.
