### ISSUE TITLE
Customize search engines graphically

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#1569]
This is one of the most frequently asked customization, so I guess we should add a "customize" menu for it.

**Comment by jmercouris** [comment]
I would suggest we think about how to enhance the generic customization interface such that it can cope with customizing something as sophisticated as setting the search engines.

**Comment by Ambrevar** [comment]
Absolutely!

**Comment by Ambrevar** [comment]
See #2351 .

**Comment by jmercouris** [comment]
Correct. Closing. Indeed the previous point I made still stands, but not for search engines.
