### ISSUE TITLE
Generate cheatsheets

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#1570]
We can already print any page to PDF, so we can print the `describe-bindings` buffer.  But it's not space-optimized.

Can we make it so that it fits into the smallest number of pages?  Maybe print the bindings in a 2-column table and shrink the font?

**Comment by pdelfino** [comment]
PR #1764 was merged. Thus, I guess this issue could be closed. I do not have the "right" to do so, though. I can only close my own issues.

Could you do the trick @jmercouris?

It would be nice to check with Pierre if the implementation really met his original. But, if it did not, we can always re-open it and fixed it.
