### ISSUE TITLE
Tiny fonts and other elements on Wayland

### ISSUE THREAD

**Issue by bhankas** [atlas-engineer/nyxt#1571]
**Describe the bug**
Incorrect DPI detection on Wayland. 
Xorg renders appropriately, the problem only happens with Wayland, and so far only for Nyxt.

**Precise recipe to reproduce the issue**
Start plasma shell under Wayland and open Nix.
To compare, start plasma shell under Xorg and open Nix.

**Information**
- OS name+version: NixOS unstable
- Graphics card and driver: Intel UHD 630 (Same result with Nvidia 1050Ti)
- Desktop environment / Window manager name+version: KDE Plasma desktop 5.21
- How you installed Nyxt (Guix pack, package manager, build from source): Nix package manager (default on NixOS)
- Information from command copy-system-information: (from unstable branch)
```
Nyxt version: 2.0.0
Renderer version: GTK
Operating system kernel: Linux 5.12.12
Lisp implementation: SBCL 2.1.2.nixos
Features: (WEBKIT2 WEBKIT2-2.32 WEBKIT2-TRACKING WEBKIT2-MUTE WEBKIT2-EMOJI WEBKIT2-MEDIA
 WEBKIT2-SANDBOXING GTK-3-22 GTK-3-20 GTK-3-18 GTK-3-16 GTK-3-14 GTK-3-12
 GTK-3-10 GTK-3-8 GTK-3-6 GTK-3-4 GTK GDK-3-22 GDK-3-20 GDK-3-18 GDK-3-16
 GDK-3-14 GDK-3-12 GDK-3-10 GDK-3-8 GDK-3-6 GDK-3-4 CAIRO-1-10 CAIRO-1-12
 GDK-PIXBUF GLIB-2-30 GLIB-2-32 GLIB-2-34 GLIB-2-36 GLIB-2-38 GLIB-2-40
 GLIB-2-42 GLIB-2-44 GLIB-2-46 GLIB-2-48 GLIB-2-50 GLIB-2-52 GLIB-2-54
 GLIB-2-56 GLIB-2-58 GLIB NYXT-2 FSET-EXT-STRINGS CUSTOM-HASH-TABLE-NATIVE
 SWANK PLUMP-UTF-32 GLOBAL-VARS DECLARE-TYPES PARENSCRIPT NAMED-READTABLES
 21BIT-CHARS CHUNGA FLEXI-STREAMS CLOSER-MOP CL-PPCRE-UNICODE CL-UNICODE
 CL-PPCRE BORDEAUX-THREADS SPLIT-SEQUENCE GRAY-STREAMS FLAT-NAMESPACE X86-64
 UNIX CFFI FLAT-NAMESPACE SEQUENCE-EMPTYP FAST-IO-SV FAST-IO
 SBCL-USES-SB-ROTATE-BYTE ASDF-SYSTEM-CONNECTIONS CL-JSON-CLOS CL-JSON
 THREAD-SUPPORT ASDF3.3 ASDF3.2 ASDF3.1 ASDF3 ASDF2 ASDF OS-UNIX
 NON-BASE-CHARS-EXIST-P ASDF-UNICODE X86-64 GENCGC 64-BIT ANSI-CL COMMON-LISP
 ELF IEEE-FLOATING-POINT LINUX LITTLE-ENDIAN PACKAGE-LOCAL-NICKNAMES SB-LDB
 SB-PACKAGE-LOCKS SB-THREAD SB-UNICODE SBCL UNIX)

ASDF version: 3.3.4
Critical dependencies: (/nix/store/bb7q1npa1jll6c2c7sh2n3wfnlijj9z4-lisp-cl-cffi-gtk-20201220-git/lib/common-lisp/cl-cffi-gtk/gtk/cl-cffi-gtk.asd
 /nix/store/0dxd3ni37xjrd9l90j115zzki2imlcsl-lisp-cl-gobject-introspection-20210124-git/lib/common-lisp/cl-gobject-introspection/cl-gobject-introspection.asd
 /nix/store/jqyydak3cy84k3vp7l5id7ryk36vfy0d-lisp-cl-webkit2-cl-webkit-20210411-git/lib/common-lisp/cl-webkit2/webkit2/cl-webkit2.asd)

```

Dev build for Nyxt 2.1.0 : 
```
Nyxt version: 2
Renderer: GTK
Operating system kernel: Linux 5.12.12
Lisp implementation: SBCL 2.1.2.nixos
Features: (WEBKIT2 WEBKIT2-2.32 WEBKIT2-TRACKING WEBKIT2-MUTE WEBKIT2-EMOJI
           WEBKIT2-MEDIA WEBKIT2-SANDBOXING GTK-3-22 GTK-3-20 GTK-3-18 GTK-3-16
           GTK-3-14 GTK-3-12 GTK-3-10 GTK-3-8 GTK-3-6 GTK-3-4 GTK GDK-3-22
           GDK-3-20 GDK-3-18 GDK-3-16 GDK-3-14 GDK-3-12 GDK-3-10 GDK-3-8
           GDK-3-6 GDK-3-4 CAIRO-1-10 CAIRO-1-12 GDK-PIXBUF GLIB-2-30 GLIB-2-32
           GLIB-2-34 GLIB-2-36 GLIB-2-38 GLIB-2-40 GLIB-2-42 GLIB-2-44
           GLIB-2-46 GLIB-2-48 GLIB-2-50 GLIB-2-52 GLIB-2-54 GLIB-2-56
           GLIB-2-58 GLIB FSET-EXT-STRINGS CUSTOM-HASH-TABLE-NATIVE SWANK
           PLUMP-UTF-32 GLOBAL-VARS DECLARE-TYPES PARENSCRIPT NAMED-READTABLES
           21BIT-CHARS CHUNGA FLEXI-STREAMS CLOSER-MOP CL-PPCRE-UNICODE
           CL-UNICODE CL-PPCRE BORDEAUX-THREADS SPLIT-SEQUENCE GRAY-STREAMS
           FLAT-NAMESPACE X86-64 UNIX CFFI FLAT-NAMESPACE SEQUENCE-EMPTYP
           FAST-IO-SV FAST-IO SBCL-USES-SB-ROTATE-BYTE ASDF-SYSTEM-CONNECTIONS
           CL-JSON-CLOS CL-JSON THREAD-SUPPORT ASDF3.3 ASDF3.2 ASDF3.1 ASDF3
           ASDF2 ASDF OS-UNIX NON-BASE-CHARS-EXIST-P ASDF-UNICODE X86-64 GENCGC
           64-BIT ANSI-CL COMMON-LISP ELF IEEE-FLOATING-POINT LINUX
           LITTLE-ENDIAN PACKAGE-LOCAL-NICKNAMES SB-LDB SB-PACKAGE-LOCKS
           SB-THREAD SB-UNICODE SBCL UNIX)
```

**Output when started from a shell**

**Comment by jmercouris** [comment]
Hm, does it suffice for you to change the default zoom ratio and change the font sizes?

**Comment by jmercouris** [comment]
I can see why small fonts would be problematic! :-)

**Comment by p3s** [comment]
Hi, thanks for quick response.
By zoom ratio do you mean the default zoom page action, then no, that doesn't fix it. I'm not sure what needs to be adjusted because this only happens with Wayland. Screenshot (with increased page zoom) for reference:

![image](https://user-images.githubusercontent.com/24254289/123975295-d7b51980-d9da-11eb-8527-5fe4e94cad3f.png)

**Comment by jmercouris** [comment]
Hm, very odd. Why are the images zooming in, but not the text?

**Comment by jmercouris** [comment]
I guess you could use a style-mode that sets a minimum font-size for all elements on the page. That would work.

**Comment by jmercouris** [comment]
Still, images would be incredibly small.

**Comment by p3s** [comment]
so set a default zoom to higher than 100% AND use style-mode to set custom font size?

But will that work for all sites by default without any side effects? This is also a hacky fragile way. I'm not against it, as long as we know what the real issue is and it gets logged as bug either in NixOS, Plasma or Nyxt.

**Comment by p3s** [comment]
Okay, I'll bring this up in NixOS matrix channels.

**Comment by babariviere** [comment]
As a workaround, you can force the use of `x11` as a backend. Just run:
```
GDK_BACKEND=x11 nyxt
```

**Comment by aartaka** [comment]
Or use `GDK_SCALE=2`, for example. Closing this as the problem seems to be solvable with environment variables, and is beyond the layer Nyxt works on.
