### ISSUE TITLE
Can't customize search engine according to manual

### ISSUE THREAD

**Issue by novoid** [atlas-engineer/nyxt#1574]
I am running Nyxt 2.1.1.

My `~/.config/nyxt/init.lisp` is:

```
(defvar `*my-search-engines*'
"list of search engines."
  (list
   '("python3" "https://docs.python.org/3/search.html?q=~a" "https://docs.python.org/3")
   '("doi" "https://dx.doi.org/~a" "https://dx.doi.org/")
   '("we" "https://en.wikipedia.org/w/index.php?search=~a" "https://en.wikipedia.org/")
   '("wd" "https://de.wikipedia.org/w/index.php?search=~a" "https://de.wikipedia.org/")
   '("osm" "https://www.openstreetmap.org/search?query=~a" "https://www.openstreetmap.org/")
   '("l" "https://dict.leo.org/german-english/~a" "https://dict.leo.org/german-english/")
   '("s" "https://www.startpage.com/do/dsearch?query=~a" "https://startpage.com/")
   ))

(define-configuration buffer
  ((search-engines (append (mapcar (lambda (engine) (apply 'make-search-engine engine))
                                   *my-search-engines*)
                           %slot-default%))))

```

... following the manual code.

When I do `C-SPC load-init-file RET` I get: 
```
Error occured:

Could not load the init file: The NAME argument to DEFVAR, `*MY-SEARCH-ENGINES*, is not a symbol.
```

I then modified the code according to the second example of the manual (without the backticks):

```
(defvar *my-search-engines*
"list of search engines."
  (list
   '("python3" "https://docs.python.org/3/search.html?q=~a" "https://docs.python.org/3")
   '("doi" "https://dx.doi.org/~a" "https://dx.doi.org/")
   '("we" "https://en.wikipedia.org/w/index.php?search=~a" "https://en.wikipedia.org/")
   '("wd" "https://de.wikipedia.org/w/index.php?search=~a" "https://de.wikipedia.org/")
   '("osm" "https://www.openstreetmap.org/search?query=~a" "https://www.openstreetmap.org/")
   '("l" "https://dict.leo.org/german-english/~a" "https://dict.leo.org/german-english/")
   '("s" "https://www.startpage.com/do/dsearch?query=~a" "https://startpage.com/")
   ))

(define-configuration buffer
  ((search-engines (append (mapcar (lambda (engine) (apply 'make-search-engine engine))
                                   *my-search-engines*)
                           %slot-default%))))

```

In this case, I get:
```
Error occured:

Could not load the init file because of a type error: The value (LIST '("python3" "https://docs.python.org/3/search.html?q=~a" "https://docs.python.org/3") '("doi" "https://dx.doi.org/~a" "https://dx.doi.org/") '("we" "https://en.wikipedia.org/w/index.php?search=~a" "https://en.wikipedia.org/") '("wd" "https://de.wikipedia.org/w/index.php?search=~a" "https://de.wikipedia.org/") '("osm" "https://www.openstreetmap.org/search?query=~a" "https://www.openstreetmap.org/") '("l" "https://dict.leo.org/german-english/~a" "https://dict.leo.org/german-english/") '("s" "https://www.startpage.com/do/dsearch?query=~a" "https://startpage.com/")) is not of type (OR STRING NULL) when binding STRING
```

Same error appears when I remove the asterisks around `my-search-engines` (twice).

So far, the examples provided differ in format and both are not resulting in a syntax my Nyxt is able to process.

**Information**
- OS name+version: Xubuntu 20.04 LTS (latest)
- Graphics card and driver: -
- Desktop environment / Window manager name+version: xfce
- How you installed Nyxt (Guix pack, package manager, build from source): deb package
- Information from command copy-system-information:

`nyxt --system-information` 

Nyxt version: 2.1.1
Renderer version: GI-GTK
Operating system kernel: Linux 5.4.0-77-generic
Lisp implementation: SBCL 2.1.0.0.HEAD.1-46cb065
Features: (WEBKIT2 WEBKIT2-2.32 WEBKIT2-PASTE-PLAINTEXT WEBKIT2-TRACKING WEBKIT2-MUTE
 WEBKIT2-EMOJI WEBKIT2-MEDIA WEBKIT2-SANDBOXING GTK-3-22 GTK-3-20 GTK-3-18
 GTK-3-16 GTK-3-14 GTK-3-12 GTK-3-10 GTK-3-8 GTK-3-6 GTK-3-4 GTK GDK-3-22
 GDK-3-20 GDK-3-18 GDK-3-16 GDK-3-14 GDK-3-12 GDK-3-10 GDK-3-8 GDK-3-6 GDK-3-4
 CAIRO-1-10 CAIRO-1-12 GDK-PIXBUF GLIB-2-30 GLIB-2-32 GLIB-2-34 GLIB-2-36
 GLIB-2-38 GLIB-2-40 GLIB-2-42 GLIB-2-44 GLIB-2-46 GLIB-2-48 GLIB-2-50
 GLIB-2-52 GLIB-2-54 GLIB-2-56 GLIB-2-58 GLIB NYXT-2 FSET-EXT-STRINGS
 CUSTOM-HASH-TABLE-NATIVE SWANK PLUMP-UTF-32 GLOBAL-VARS DECLARE-TYPES
 PARENSCRIPT NAMED-READTABLES 21BIT-CHARS CHUNGA FLEXI-STREAMS CLOSER-MOP
 CL-PPCRE-UNICODE CL-UNICODE BORDEAUX-THREADS SPLIT-SEQUENCE GRAY-STREAMS
 FAST-IO-SV FAST-IO SBCL-USES-SB-ROTATE-BYTE ASDF-SYSTEM-CONNECTIONS
 CL-JSON-CLOS CL-JSON THREAD-SUPPORT CL-PPCRE FLAT-NAMESPACE X86-64 UNIX CFFI
 FLAT-NAMESPACE SEQUENCE-EMPTYP QUICKLISP ASDF3.3 ASDF3.2 ASDF3.1 ASDF3 ASDF2
 ASDF OS-UNIX NON-BASE-CHARS-EXIST-P ASDF-UNICODE X86-64 GENCGC 64-BIT ANSI-CL
 COMMON-LISP ELF IEEE-FLOATING-POINT LINUX LITTLE-ENDIAN
 PACKAGE-LOCAL-NICKNAMES SB-CORE-COMPRESSION SB-LDB SB-PACKAGE-LOCKS SB-THREAD
 SB-UNICODE SBCL UNIX)

ASDF version: 3.3.4
Critical dependencies: (/home/runner/work/nyxt/nyxt/_build/submodules/cl-cffi-gtk/gtk/cl-cffi-gtk.asd
 /home/runner/work/nyxt/nyxt/_build/quicklisp-client/dists/quicklisp/software/cl-gobject-introspection-20210124-git/cl-gobject-introspection.asd
 /home/runner/work/nyxt/nyxt/_build/submodules/cl-webkit/webkit2/cl-webkit2.asd)

Quicklisp dist version: 2021-05-31
Quicklisp client version: 2020-01-04
Local project directories: (/home/runner/work/nyxt/nyxt/_build/quicklisp-client/local-projects/)
Critical dependencies(#<SYSTEM cl-cffi-gtk / cl-cffi-gtk-20201220-git / quicklisp 2021-05-31>
 #<SYSTEM cl-gobject-introspection / cl-gobject-introspection-20210124-git / quicklisp 2021-05-31>
 #<SYSTEM cl-webkit2 / cl-webkit-20210531-git / quicklisp 2021-05-31>)

**Comment by Ambrevar** [comment]
Oops, fixed the spurious quotes in f213fde3a980612034eac1567dba9146b5f528a8.

I just tried the second example and it works for me. Can you share your whole `init.lisp` as well as `auto-config.lisp`?

**Comment by Ambrevar** [comment]
Oh, got it, the docstring is not at the right place!  Fixed too.  Sorry that we let that slip before releasing 2.1.1. 

https://github.com/atlas-engineer/nyxt/issues/1580

@novoid If you remove `"list of search engines."` it should work!

**Comment by novoid** [comment]
My `auto-config.lisp`:

```
(DEFINE-CONFIGURATION (BUFFER WEB-BUFFER)
  ((DEFAULT-MODES (APPEND '(NYXT::EMACS-MODE) %SLOT-DEFAULT%))))
```

`init.lisp`:
```
(defvar my-search-engines
  (list
   '("python3" "https://docs.python.org/3/search.html?q=~a" "https://docs.python.org/3")
   '("doi" "https://dx.doi.org/~a" "https://dx.doi.org/")
   '("we" "https://en.wikipedia.org/w/index.php?search=~a" "https://en.wikipedia.org/")
   '("wd" "https://de.wikipedia.org/w/index.php?search=~a" "https://de.wikipedia.org/")
   '("osm" "https://www.openstreetmap.org/search?query=~a" "https://www.openstreetmap.org/")
   '("l" "https://dict.leo.org/german-english/~a" "https://dict.leo.org/german-english/")
;;   '("" "" "")
   '("s" "https://www.startpage.com/do/dsearch?query=~a" "https://startpage.com/")
   ))

(define-configuration buffer
  ((search-engines (append (mapcar (lambda (engine) (apply 'make-search-engine engine))
                                   my-search-engines)
                           %slot-default%))))
```

I can confirm that the error message seems to be gone now. The new search engines are registered such that I'm able to type "we test" which looks up "test" in the Wikipedia.

When I press `C-l` and type in "foo bar", the DuckDuckGo search engine is still used and not my new default startpage.com. Either I don't understand how to use the default search engine or there is a bug.

Additionally, `make-buffer` still uses DuckDuckGo which I understand since this is a normal web page Nyxt is loading. However, other users might be irritated because they changed their search engine to something different.

**Comment by jmercouris** [comment]
Note that you are appending to the `%slot-default%` therefore the original search engines exist before your search engines. Remember it is only the last one that is the default one. Therefore, you could remove the append, or reorder the arguments and it would behave as you expect.

**Comment by jmercouris** [comment]
Therefore

```
(define-configuration buffer
  ((search-engines (append %slot-default% (mapcar (lambda (engine) (apply 'make-search-engine engine))
                                   my-search-engines)))))
```

OR:

```
(define-configuration buffer
  ((search-engines (mapcar (lambda (engine) (apply 'make-search-engine engine))
                                   my-search-engines))))
```

**Comment by novoid** [comment]
Thanks @jmercouris ,

With the second snippet of yours, I get the desired changed search engine.
However, related to your explanation it should have worked before as well because when I _append_ the list, the _last_ one should have been the default search engine (which was not true). So I'm still puzzled what happened here.

**Comment by jmercouris** [comment]
Append perhaps does not work the way you think :-)
