### ISSUE TITLE
Possible bug: I cannot revert `dark-mode`, however, `invert-color` works as expected

### ISSUE THREAD

**Issue by pdelfino** [atlas-engineer/nyxt#1575]
**Describe the bug**

![bug-dark-mode-2](https://user-images.githubusercontent.com/7698207/124017438-1a67f900-d9bd-11eb-8c6f-aefcbb3cf34a.gif)

Before posting this here, I talked about it on IRC. @jmercouris made some comments:
> Dark mode has side effects. Those side effects cannot be easily undone. It’s a problem that CSS is not functional, but stateful.
There may be a way to fix this, but it would be hard I believe. I think it may be a GitHub issue already

Since I could not find an issue, I am posting it here. It is surprising for me that is possible to disable the changes provided by the `invert-color` bookmarklet  (but `dark-mode` does not work). Both commands seem to mutate CSS values.

**Precise recipe to reproduce the issue**
- Enable dark-mode: `M-x` `dark-mode`
- Try to disable it executing the command again: `M-x` `dark-mode`

**Information**
- OS name+version:  
Ubuntu 20.04.2 LTS

- Graphics card and driver:
product: Iris Plus Graphics 640
configuration: driver=i915 latency=0

- Desktop environment / Window manager name+version:
Name: GNOME Shell 3.36.7
Window manager's "showing the desktop" mode: OFF

- How you installed Nyxt (Guix pack, package manager, build from source):
Source

- Information from command copy-system-information:
Nyxt version: 2.1.0-18-g04b86064
Renderer version: GI-GTK
Operating system kernel: Linux 5.8.0-59-generic
Lisp implementation: SBCL 2.0.1.debian
Features: (WEBKIT2 WEBKIT2-2.32 WEBKIT2-PASTE-PLAINTEXT WEBKIT2-TRACKING WEBKIT2-MUTE
 WEBKIT2-EMOJI WEBKIT2-MEDIA WEBKIT2-SANDBOXING GTK-3-22 GTK-3-20 GTK-3-18
 GTK-3-16 GTK-3-14 GTK-3-12 GTK-3-10 GTK-3-8 GTK-3-6 GTK-3-4 GTK GDK-3-22
 GDK-3-20 GDK-3-18 GDK-3-16 GDK-3-14 GDK-3-12 GDK-3-10 GDK-3-8 GDK-3-6 GDK-3-4
 CAIRO-1-10 CAIRO-1-12 GDK-PIXBUF GLIB-2-30 GLIB-2-32 GLIB-2-34 GLIB-2-36
 GLIB-2-38 GLIB-2-40 GLIB-2-42 GLIB-2-44 GLIB-2-46 GLIB-2-48 GLIB-2-50
 GLIB-2-52 GLIB-2-54 GLIB-2-56 GLIB-2-58 GLIB NYXT-2 FSET-EXT-STRINGS
 CUSTOM-HASH-TABLE-NATIVE PLUMP-UTF-32 GLOBAL-VARS DECLARE-TYPES PARENSCRIPT
 NAMED-READTABLES 21BIT-CHARS CHUNGA FLEXI-STREAMS CLOSER-MOP CL-PPCRE-UNICODE
 CL-UNICODE CL-PPCRE BORDEAUX-THREADS SPLIT-SEQUENCE GRAY-STREAMS
 FLAT-NAMESPACE X86-64 UNIX CFFI FLAT-NAMESPACE SEQUENCE-EMPTYP FAST-IO-SV
 FAST-IO SBCL-USES-SB-ROTATE-BYTE ASDF-SYSTEM-CONNECTIONS CL-JSON-CLOS CL-JSON
 THREAD-SUPPORT SWANK QUICKLISP SB-BSD-SOCKETS-ADDRINFO ASDF3.3 ASDF3.2 ASDF3.1
 ASDF3 ASDF2 ASDF OS-UNIX NON-BASE-CHARS-EXIST-P ASDF-UNICODE X86-64 64-BIT
 ANSI-CL COMMON-LISP ELF GENCGC IEEE-FLOATING-POINT LINUX LITTLE-ENDIAN
 PACKAGE-LOCAL-NICKNAMES SB-CORE-COMPRESSION SB-LDB SB-PACKAGE-LOCKS SB-THREAD
 SB-UNICODE SBCL UNIX)

ASDF version: 3.3.1
Critical dependencies: (/home/pedro/.quicklisp/dists/quicklisp/software/cl-cffi-gtk-20201220-git/gtk/cl-cffi-gtk.asd
 /home/pedro/.quicklisp/dists/quicklisp/software/cl-gobject-introspection-20210124-git/cl-gobject-introspection.asd
 /home/pedro/common-lisp/cl-webkit/webkit2/cl-webkit2.asd)

Quicklisp dist version: 2021-05-31
Quicklisp client version: 2021-02-13
Local project directories: (/home/pedro/.quicklisp/local-projects/)
Critical dependencies(#<SYSTEM cl-cffi-gtk / cl-cffi-gtk-20201220-git / quicklisp 2021-05-31>
 #<SYSTEM cl-gobject-introspection / cl-gobject-introspection-20210124-git / quicklisp 2021-05-31>
 #<SYSTEM cl-webkit2 / cl-webkit-20210531-git / quicklisp 2021-05-31>)

**Output when started from a shell**
I do not start Nyxt from a shell. I start it inside the SLIME REPL with:
```lisp
NYXT> (start)
<INFO> [15:59:23] Listening to socket "/run/user/1000/nyxt/nyxt.socket".
Nyxt version 2.1.0-18-g04b86064
<INFO> [15:59:23] Loading Lisp file "/home/pedro/.config/nyxt/auto-config.lisp".
<INFO> [15:59:23] Loading Lisp file "/home/pedro/.config/nyxt/init.lisp".
NIL
```

**Comment by aartaka** [comment]
Well, `invert-color` simply does a math to colors. Math can be undone.

`dark-mode` sets colors to new, absolutely unrelated values. In this case, there's no rule to restore them by. The only way to restore changes would be to store _all the colors on the page_ into the memory and reconstruct them somehow after  `dark-mode` is disabled. That's too much work.

**Comment by Ambrevar** [comment]
Artyom Bologov ***@***.***> writes:

> Well, `invert-color` simply does a math to colors. Math can be undone.

To be picky, invert-color is "easily" invertible.  Not all mathematical
functions can be inverted, and among those can be inverted, not all are
"easy" to invert (think crypto).

> `dark-mode` sets colors to new, absolutely unrelated values. In this case, there's no rule to restore them by. The only way to restore changes would be to store _all the colors on the page_ into the memory and reconstruct them somehow after  `dark-mode` is disabled. That's too much work.

**Comment by Kabouik** [comment]
I've had the same issue with `dark-mode` for months while I was testing Nyxt be:fore really committing to making it my daily browser. Only recently I realized that you can use `toggle-mode`, delesect `dark-mode` from the list, press <keyboard>Return</keyboard>, and then reload the page.

**Comment by pdelfino** [comment]
>Still, it's a lot of work for something that could be done by a simple page reload.

Oh, I did not know that simply reloading it would work out. Ok, then. Maybe this could be mentioned in the manual. Dark mode itself and this peculiarity on how to disable it.

>Only recently I realized that you can use `toggle-mode`, delesect `dark-mode` from the list, press Return, and then reload the page. 

Using the gif already sent, you just need to reload the page after disabling it and it will work. There is no need for toggle mode.

1 - Enable dark-mode: `C-spc dark-mode`
2 - Disable it executing the command again: `C-spc dark-mode`
3 - **Reload** with `C-r` (in CUA).
