### ISSUE TITLE
Documentation: instruct the user on tutorial about the various possibilities of copying and pasting in Nyxt

### ISSUE THREAD

**Issue by pdelfino** [atlas-engineer/nyxt#1577]
Unlike other browsers, Nyxt goes way beyond `control c + control v` concerning copying and pasting. Based on [this](https://github.com/atlas-engineer/nyxt/commit/2716a69bbf54eb38480de27cf6ccc08c181e37fd#commitcomment-52850352) discussion, the tutorial should introduce the multiple ways of copying and pasting while using Nyxt. 

Mimicking the approach used on tutorial about `Visual-mode`, laconic definitions about the following commands could be written in bullet points:
-  `copy`
- `copy-url`
- `copy-title`
- `copy-username`
- `copy-password`
- `copy-placeholder`
- `copy-system-information`
- `copy-passowrd-prompt-details`
- `copy-hint-url`
- `paste`
- `paste-from-clipboard-ring` (name may change soon)
- `paste-or-set-url`

**Comment by Ambrevar** [comment]
`paste-or-set-url` seems to be no longer used.  @jmercouris Any idea?  If it's bitrot, I'll deprecate it then.

Beside this, 2 paste commands seems good. `paste-from-clipboard-ring` is the general version that offers everything for pasting, while `paste` only pastes the last element, without prompting the user.

Proposed bindings:
- `C-v`: `paste`
- `C-V`: `paste-from-clipboard-ring`.

About `copy`: could we conflate some of them?  For instance, we could have a `copy-page-metadata` that prompts which of the URL, title, whatever header we want to copy.

Finally, what do do about the doc?  I would suggest to lookup the commands that start with `copy` and `paste`, then refer to their docstrings.

**Comment by jmercouris** [comment]
I seem to recall we were using it when we had a different prompt architecture. For what though, I don't know. At this point, yes, let's deprecate it.

**Comment by Ambrevar** [comment]
Found it, it's commit 23050f63192ff4dfc1998ede91b1a749cb887988.
It was needed when pasting used to crash the renderer.
I'll deprecate it.

**Comment by pdelfino** [comment]
> Proposed bindings:
>     * `C-v`: `paste`
>     * `C-V`: `paste-from-clipboard-ring`.

Great. I would add:

-  `C-c`: `copy`

On:

> About `copy`: could we conflate some of them? For instance, we could have a `copy-page-metadata` that prompts which of the URL, title, whatever header we want to copy.

If you change the name to `copy-page-data` you could also include
`copy-placeholder`

And on:

> Finally, what to do about the doc? I would suggest to look up the commands that start with `copy` and `paste`, then refer to their docstrings.

I did that [here](https://github.com/atlas-engineer/nyxt/pull/1589). Should we make some automation to use the docstrings? The information
is already in the source code. 

There is already automation to get the key bindings, like
`(command-markup 'copy-url)`. Why not something like
`(command-docstring 'some-command)`. I can open an issue (feature
request) for this idea if you also think it is valuable.

**Comment by Ambrevar** [comment]
> There is already automation to get the key bindings, like
> `(command-markup 'copy-url)`. Why not something like
> `(command-docstring 'some-command)`. I can open an issue (feature
> request) for this idea if you also think it is valuable.

Good idea, we can actually automatically insert the first sentence of
the docstring into the manual.
Don't bother opening an issue, I'll implement it just now.

**Comment by Ambrevar** [comment]
I've implemented this in 511585480b1f647a19a208ae49efac757e8ec280.

**Comment by pdelfino** [comment]
> I've implemented this in [5115854](https://github.com/atlas-engineer/nyxt/commit/511585480b1f647a19a208ae49efac757e8ec280).

Cool!

in the case you mentioned, it seems to be generating two final dots "..". I tried to fix it [here](https://github.com/atlas-engineer/nyxt/commit/511585480b1f647a19a208ae49efac757e8ec280).

>Good idea, we can actually automatically insert the first sentence of
the docstring into the manual.

Why just the first sentence? Is there a reason?

**Comment by Ambrevar** [comment]
Pedro Delfino ***@***.***> writes:

> in the case you mentioned, it seems to be generating two final dots "..". I tried to fix it [here](https://github.com/atlas-engineer/nyxt/commit/511585480b1f647a19a208ae49efac757e8ec280).

Fixed!
>
>>Good idea, we can actually automatically insert the first sentence of
> the docstring into the manual.
>
> Why just the first sentence? Is there a reason?

Yes, docstrings may be very long and we don't want to clutter the manual
with too many details.

**Comment by pdelfino** [comment]
I am closing this issue since the suggestions have now been [merged](https://github.com/atlas-engineer/nyxt/commit/2fae1c48eb16717f10be03f36dc94f6ebc91d8fd#diff-7fc060f35486ad5d7b157169b48eb9c658c59d60d59bbfb67462e94e7e94e9d5).

**Comment by jmercouris** [comment]
Thank you!
