### ISSUE TITLE
make-buffer does not open a new buffer in foreground

### ISSUE THREAD

**Issue by novoid** [atlas-engineer/nyxt#1583]
When I remember correctly, previous versions did open new buffers via `C-SPC make-buffer` in the foreground. 

However, when I do `C-SPC make-buffer` a new buffer showing https://nyxt.atlas.engineer/start is opened in the _background_ instead.

Furthermore, when I customize with `(setq default-new-buffer-url "about:blank")` this does not seem to have an effect on the content of the new buffer. It still shows the URL above.

**Information**
- OS name+version: Xubuntu 20.04 LTS (latest)
- Graphics card and driver: -
- Desktop environment / Window manager name+version: xfce
- How you installed Nyxt (Guix pack, package manager, build from source): deb package
- Information from command copy-system-information:

Nyxt version: 2.1.1
Renderer version: GI-GTK
Operating system kernel: Linux 5.4.0-77-generic
Lisp implementation: SBCL 2.1.0.0.HEAD.1-46cb065
Features: (WEBKIT2 WEBKIT2-2.32 WEBKIT2-PASTE-PLAINTEXT WEBKIT2-TRACKING WEBKIT2-MUTE
WEBKIT2-EMOJI WEBKIT2-MEDIA WEBKIT2-SANDBOXING GTK-3-22 GTK-3-20 GTK-3-18
GTK-3-16 GTK-3-14 GTK-3-12 GTK-3-10 GTK-3-8 GTK-3-6 GTK-3-4 GTK GDK-3-22
GDK-3-20 GDK-3-18 GDK-3-16 GDK-3-14 GDK-3-12 GDK-3-10 GDK-3-8 GDK-3-6 GDK-3-4
CAIRO-1-10 CAIRO-1-12 GDK-PIXBUF GLIB-2-30 GLIB-2-32 GLIB-2-34 GLIB-2-36
GLIB-2-38 GLIB-2-40 GLIB-2-42 GLIB-2-44 GLIB-2-46 GLIB-2-48 GLIB-2-50
GLIB-2-52 GLIB-2-54 GLIB-2-56 GLIB-2-58 GLIB NYXT-2 FSET-EXT-STRINGS
CUSTOM-HASH-TABLE-NATIVE SWANK PLUMP-UTF-32 GLOBAL-VARS DECLARE-TYPES
PARENSCRIPT NAMED-READTABLES 21BIT-CHARS CHUNGA FLEXI-STREAMS CLOSER-MOP
CL-PPCRE-UNICODE CL-UNICODE BORDEAUX-THREADS SPLIT-SEQUENCE GRAY-STREAMS
FAST-IO-SV FAST-IO SBCL-USES-SB-ROTATE-BYTE ASDF-SYSTEM-CONNECTIONS
CL-JSON-CLOS CL-JSON THREAD-SUPPORT CL-PPCRE FLAT-NAMESPACE X86-64 UNIX CFFI
FLAT-NAMESPACE SEQUENCE-EMPTYP QUICKLISP ASDF3.3 ASDF3.2 ASDF3.1 ASDF3 ASDF2
ASDF OS-UNIX NON-BASE-CHARS-EXIST-P ASDF-UNICODE X86-64 GENCGC 64-BIT ANSI-CL
COMMON-LISP ELF IEEE-FLOATING-POINT LINUX LITTLE-ENDIAN
PACKAGE-LOCAL-NICKNAMES SB-CORE-COMPRESSION SB-LDB SB-PACKAGE-LOCKS SB-THREAD
SB-UNICODE SBCL UNIX)

ASDF version: 3.3.4
Critical dependencies: (/home/runner/work/nyxt/nyxt/_build/submodules/cl-cffi-gtk/gtk/cl-cffi-gtk.asd
/home/runner/work/nyxt/nyxt/_build/quicklisp-client/dists/quicklisp/software/cl-gobject-introspection-20210124-git/cl-gobject-introspection.asd
/home/runner/work/nyxt/nyxt/_build/submodules/cl-webkit/webkit2/cl-webkit2.asd)

Quicklisp dist version: 2021-05-31

**Comment by Ambrevar** [comment]
I think you are looking for `make-buffer-focus` instead, no?

`default-new-buffer-url` is not a global variable.  In general, Nyxt uses very few global variables, which makes for a more robust API.

What you want instead is (untested):

```lisp
(define-configuration (web-buffer)
  ((default-new-buffer-url (quri:uri "about:blank"))))
```

**Comment by Ambrevar** [comment]
Note: You can configure the default URL graphically from the `common-settings`.

**Comment by novoid** [comment]
Yes, I was looking for `make-buffer-focus` and probably did not remember the behavior from before.

Ad `default-new-buffer-url`: `Help-MAKE-BUFFER` says: "If URL is empty, use `default-new-buffer-url'.
To load nothing, set it to about:blank."

So I used my Emacs knowledge and did the `setq` accordingly. If this is not appropriate, how can I learn how to avoid this mistake with Nyxt? It seems to be the case that I don't know when Emacs/Elisp knowledge should be transferred to Nyxt and when not ... Kind of a bad situation for a user like me ...

**Comment by Ambrevar** [comment]
I've just clarified the docstring of make-buffer, hope that helps.

`setq` exists in CL but it's superseded by `setf`.

I hope to introduce cross-references as soon as possible so that you
could directly go to the documentation of default-new-buffer-url,
hopefully that'll help.
