### ISSUE TITLE
Shoudn't execute-extended-command run command asynchronously?

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#1586]
I noticed that `execute-extended-command` runs commands directly instead of leveraing `run-async` like `execute-command` does.

Is this intentional?  A mistake?
@jmercouris ?

**Comment by jmercouris** [comment]
I can't remember. Perhaps a mistake. We would need to test to be sure.

**Comment by Ambrevar** [comment]
I'm on it.

I think know what it was not run asynchronous: there was a bug in
run-async, we didn't rebind the arguments, but since it's a separate
thread, the binding would run stale which would cause the function to be
called over a random memory location.

I have a fix, will send soon.

**Comment by Ambrevar** [comment]
Closing since the fix is in #1587.
