### ISSUE TITLE
Request for  documentation to link pass to nyxt

### ISSUE THREAD

**Issue by eklebanow** [atlas-engineer/nyxt#1594]
**Describe the bug**
I am unable to link pass password manager to nyxt 

**Precise recipe to reproduce the issue**

**Information**
- OS name+version: Linux
- Graphics card and driver:
- Desktop environment / Window manager name+version:Gentoo/DWM
- How you installed Nyxt: installed Nyxt using guix package manager which I installed into Gento:

`nyxt --system-information:
`Nyxt version: 2.1.1
Renderer version: GI-GTK
Operating system kernel: Linux 5.4.60-gentoo
Lisp implementation: SBCL 2.1.6
Features: (WEBKIT2 WEBKIT2-2.32 WEBKIT2-PASTE-PLAINTEXT WEBKIT2-TRACKING WEBKIT2-MUTE
 WEBKIT2-EMOJI WEBKIT2-MEDIA WEBKIT2-SANDBOXING GTK-3-22 GTK-3-20 GTK-3-18
 GTK-3-16 GTK-3-14 GTK-3-12 GTK-3-10 GTK-3-8 GTK-3-6 GTK-3-4 GTK GDK-3-22
 GDK-3-20 GDK-3-18 GDK-3-16 GDK-3-14 GDK-3-12 GDK-3-10 GDK-3-8 GDK-3-6 GDK-3-4
 CAIRO-1-10 CAIRO-1-12 GDK-PIXBUF GLIB-2-30 GLIB-2-32 GLIB-2-34 GLIB-2-36
 GLIB-2-38 GLIB-2-40 GLIB-2-42 GLIB-2-44 GLIB-2-46 GLIB-2-48 GLIB-2-50
 GLIB-2-52 GLIB-2-54 GLIB-2-56 GLIB-2-58 GLIB NYXT-2 FSET-EXT-STRINGS
 CUSTOM-HASH-TABLE-NATIVE SWANK PLUMP-UTF-32 GLOBAL-VARS DECLARE-TYPES
 PARENSCRIPT NAMED-READTABLES 21BIT-CHARS CHUNGA FLEXI-STREAMS CLOSER-MOP
 CL-PPCRE-UNICODE CL-UNICODE CL-PPCRE BORDEAUX-THREADS SPLIT-SEQUENCE
 GRAY-STREAMS FLAT-NAMESPACE X86-64 UNIX CFFI FLAT-NAMESPACE SEQUENCE-EMPTYP
 FAST-IO-SV FAST-IO SBCL-USES-SB-ROTATE-BYTE CL-JSON-CLOS CL-JSON
 THREAD-SUPPORT ASDF3.3 ASDF3.2 ASDF3.1 ASDF3 ASDF2 ASDF OS-UNIX
 NON-BASE-CHARS-EXIST-P ASDF-UNICODE X86-64 GENCGC 64-BIT ANSI-CL COMMON-LISP
 ELF IEEE-FLOATING-POINT LINUX LITTLE-ENDIAN PACKAGE-LOCAL-NICKNAMES
 SB-CORE-COMPRESSION SB-LDB SB-PACKAGE-LOCKS SB-THREAD SB-UNICODE SBCL UNIX)

ASDF version: 3.3.5
Critical dependencies: (/gnu/store/nfz5pmmjpyz819z7a5sx2g49ldwxgk2k-sbcl-cl-cffi-gtk-0.11.2-2.e9a46df/share/common-lisp/sbcl/cl-cffi-gtk/gtk/cl-cffi-gtk.asd
 /gnu/store/ic8jf1s6i695z9s72kjpgkryhq9n58m4-sbcl-cl-gobjec-introspection-0.3-1.d0136c8/share/common-lisp/sbcl/cl-gobject-introspection/cl-gobject-introspection.asd
 /gnu/store/m2mh77ps01hz20wvxv4kb80bffr6h79g-sbcl-cl-webkit-2.4-16.cfc4f01/share/common-lisp/sbcl/cl-webkit/webkit2/cl-webkit2.asd)
`
From aartaka's config:
[https://github.com/aartaka/nyxt-config/blob/master/passwd.lisp](url)

`(define-configuration password:keepassxc-interface
  ((password:password-file "/home/aartaka/Documents/p.kdbx")))

(define-configuration buffer
  ((password-interface (make-instance 'password:user-keepassxc-interface))))`

I cannot tell what files to plug into the above 4 lines of code
It would be helpful if there was more documentation (especially for a noob like me....)

**Comment by Ambrevar** [comment]
Are you trying to use `pass` as in https://www.passwordstore.org/ or https://www.keepassxc.org?

Aartaka's config is for the latter.  For password store, you don't need any configuration.

**Comment by eklebanow** [comment]
password store (pass)

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by eklebanow** [comment]
Pierre,

When I put in command copy password my password store items are listed but when I select one I am not prompted for my master password..

Thanks in advance for any suggestions you may be able to provide
________________________________

**Comment by Ambrevar** [comment]
If you use password-store, then your password entries are
GPG-encrypted.  Thus your GPG agent is in charge of prompting you for
your GPG key.

Maybe https://wiki.archlinux.org/title/Gpg can give you some guideline
on how to set up GPG.

**Comment by eklebanow** [comment]
That's the problem.....I am not being asked by the gig agent for my password.  Go you think I need coffee to do this in my nyxt config?

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by eklebanow** [comment]
Sorry for the typos ....gpg agent.  Do you thinki need code

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by jmercouris** [comment]
No idea what you are saying. In any case, you will need something like a gpg pinentry program.

**Comment by aartaka** [comment]
@eklebanow, does using `password:user-password-store-interface` sove your problem?

``` lisp
(define-configuration buffer
  ((password-interface (make-instance 'password:user-password-store-interface))))
```

**Comment by jmercouris** [comment]
Closing due to lack of follow up. If you are trying again, please let us know :-)
