### ISSUE TITLE
Possible bug: Changes on `tutorial.lisp` with `command-docstring-first-sentence` crash Nyxt

### ISSUE THREAD

**Issue by pdelfino** [atlas-engineer/nyxt#1600]
**Describe the bug**

After inserting changes on manual using `command-docstring-first-sentence` and recompiling the system, Nyxt crashes.
This happened while doing this [PR](https://github.com/atlas-engineer/nyxt/pull/1589).

**Precise recipe to reproduce the issue**
- be on this [branch](https://github.com/atlas-engineer/nyxt/pull/1589) or use version  Version 2.1.1-41-g643fe92a (commit 42946c6459e3)
- insert on `tutorial.lisp` the following:
```lisp
   (:h3 "Copying and Pasting")
   (:p "Unlike other web browsers, Nyxt provides powerful ways of copying
   and pasting content via different commands. Starting from:")
   (:ul
    (:li (command-markup 'nyxt/web-mode:copy) ": " (command-docstring-first-sentence 'nyxt/web-mode:copy))
    (:li (command-markup 'nyxt/web-mode:paste) ": " (command-docstring-first-sentence 'nyxt/web-mode:paste)))
   (:p "Passing through webpage's data:")
   (:ul
    (:li (command-markup 'copy-url) ": " (command-docstring-first-sentence 'copy-url))
    (:li (command-markup 'copy-title) ": " (command-docstring-first-sentence 'copy-title))
    (:li (command-markup 'nyxt/web-mode:copy-placeholder) ": " (command-docstring-first-sentence 'nyxt/web-mode:copy-placeholder))
    (:li (command-markup 'nyxt/web-mode:copy-hint-url) ": " (command-docstring-first-sentence 'nyxt/web-mode:copy-hint-url)))
   (:p "Leveraging password managers: ")
   #+nil
   (:ul 
    (:li (command-markup 'copy-username) ": " (command-docstring-first-sentence 'copy-username))
    (:li (command-markup 'copy-password) ": " (command-docstring-first-sentence 'copy-password))
    (:li (command-markup 'copy-password-prompt-details) ": " (command-docstring-first-sentence 'copy-password-prompt-details)))
   (:p "And more: ")
   #+nil 
   (:ul
    (:li (command-markup 'nyxt/web-mode:paste-from-clipboard-ring) ": " (command-docstring-first-sentence 'nyxt/web-mode:paste-from-clipboard-ring))
    (:li (command-markup 'copy-system-information) ": " (command-docstring-first-sentence 'copy-system-information)))
```
- compile it and see it works;
- now, remove the `#+nil` and re-compile
- it crashes and it should have worked.

@jmercouris could reproduce it while we were doing the live code review. If my memory is not tricking me, he said something about SBCL limitation and the stack.

For website-specific issues:
Can you reproduce this issue with Epiphany / GNOME Web (https://wiki.gnome.org/Apps/Web)?
Not related

**Information**
- OS name+version:  
Ubuntu 20.04.2 LTS

- Graphics card and driver:
product: Iris Plus Graphics 640
configuration: driver=i915 latency=0

- Desktop environment / Window manager name+version:
Name: GNOME Shell 3.36.7
Window manager's "showing the desktop" mode: OFF

- How you installed Nyxt (Guix pack, package manager, build from source):
Source

- Information from command copy-system-information:
Nyxt version: 2.1.1-41-g643fe92a
Renderer version: GI-GTK
Operating system kernel: Linux 5.8.0-59-generic
Lisp implementation: SBCL 2.0.1.debian
Features: (WEBKIT2 WEBKIT2-2.32 WEBKIT2-PASTE-PLAINTEXT WEBKIT2-TRACKING WEBKIT2-MUTE
 WEBKIT2-EMOJI WEBKIT2-MEDIA WEBKIT2-SANDBOXING GTK-3-22 GTK-3-20 GTK-3-18
 GTK-3-16 GTK-3-14 GTK-3-12 GTK-3-10 GTK-3-8 GTK-3-6 GTK-3-4 GTK GDK-3-22
 GDK-3-20 GDK-3-18 GDK-3-16 GDK-3-14 GDK-3-12 GDK-3-10 GDK-3-8 GDK-3-6 GDK-3-4
 CAIRO-1-10 CAIRO-1-12 GDK-PIXBUF GLIB-2-30 GLIB-2-32 GLIB-2-34 GLIB-2-36
 GLIB-2-38 GLIB-2-40 GLIB-2-42 GLIB-2-44 GLIB-2-46 GLIB-2-48 GLIB-2-50
 GLIB-2-52 GLIB-2-54 GLIB-2-56 GLIB-2-58 GLIB NYXT-2 FSET-EXT-STRINGS
 CUSTOM-HASH-TABLE-NATIVE PLUMP-UTF-32 GLOBAL-VARS DECLARE-TYPES PARENSCRIPT
 NAMED-READTABLES 21BIT-CHARS CHUNGA FLEXI-STREAMS CLOSER-MOP CL-PPCRE-UNICODE
 CL-UNICODE CL-PPCRE BORDEAUX-THREADS SPLIT-SEQUENCE GRAY-STREAMS
 FLAT-NAMESPACE X86-64 UNIX CFFI FLAT-NAMESPACE SEQUENCE-EMPTYP FAST-IO-SV
 FAST-IO SBCL-USES-SB-ROTATE-BYTE ASDF-SYSTEM-CONNECTIONS CL-JSON-CLOS CL-JSON
 THREAD-SUPPORT SWANK QUICKLISP SB-BSD-SOCKETS-ADDRINFO ASDF3.3 ASDF3.2 ASDF3.1
 ASDF3 ASDF2 ASDF OS-UNIX NON-BASE-CHARS-EXIST-P ASDF-UNICODE X86-64 64-BIT
 ANSI-CL COMMON-LISP ELF GENCGC IEEE-FLOATING-POINT LINUX LITTLE-ENDIAN
 PACKAGE-LOCAL-NICKNAMES SB-CORE-COMPRESSION SB-LDB SB-PACKAGE-LOCKS SB-THREAD
 SB-UNICODE SBCL UNIX)

ASDF version: 3.3.1
Critical dependencies: (/home/pedro/.quicklisp/dists/quicklisp/software/cl-cffi-gtk-20201220-git/gtk/cl-cffi-gtk.asd
 /home/pedro/.quicklisp/dists/quicklisp/software/cl-gobject-introspection-20210124-git/cl-gobject-introspection.asd
 /home/pedro/common-lisp/cl-webkit/webkit2/cl-webkit2.asd)

Quicklisp dist version: 2021-05-31
Quicklisp client version: 2021-02-13
Local project directories: (/home/pedro/.quicklisp/local-projects/)
Critical dependencies(#<SYSTEM cl-cffi-gtk / cl-cffi-gtk-20201220-git / quicklisp 2021-05-31>
 #<SYSTEM cl-gobject-introspection / cl-gobject-introspection-20210124-git / quicklisp 2021-05-31>
 #<SYSTEM cl-webkit2 / cl-webkit-20210531-git / quicklisp 2021-05-31>)

**Output when started from a shell**
I do not start Nyxt from a shell. I start it inside the SLIME REPL with:
```lisp
CL-USER> (nyxt:start)
<INFO> [18:56:48] Listening to socket "/run/user/1000/nyxt/nyxt.socket".
Nyxt version 2.1.1-41-g643fe92a
<INFO> [18:56:48] Loading Lisp file "/home/pedro/.config/nyxt/auto-config.lisp".
<INFO> [18:56:48] Loading Lisp file "/home/pedro/.config/nyxt/init.lisp".
NIL
<INFO> [18:56:57] Version 2.1.1-41-
```
**Output when started from a shell**

**Comment by Ambrevar** [comment]
I can't reproduce.

Please report the stacktraces or the shell output.

My guess is that you have some stale .fasls because
command-docstring-first-sentence is a macro.

Try cleaning up the fasls.  With SLY, you can run this in a REPL:

```
(slynk-asdf:delete-system-fasls :nyxt)
```

**Comment by pdelfino** [comment]
Please, in your environment, starting from fresh.

What happens if you add this to the tutorial.lisp file on **line 125** (note that I removed the `#+nil` expression):

```lisp
   (:h3 "Copying and Pasting")
   (:p "Unlike other web browsers, Nyxt provides powerful ways of copying
   and pasting content via different commands. Starting from:")
   (:ul
    (:li (command-markup 'nyxt/web-mode:copy) ": " (command-docstring-first-sentence 'nyxt/web-mode:copy))
    (:li (command-markup 'nyxt/web-mode:paste) ": " (command-docstring-first-sentence 'nyxt/web-mode:paste)))
   (:p "Passing through webpage's data:")
   (:ul
    (:li (command-markup 'copy-url) ": " (command-docstring-first-sentence 'copy-url))
    (:li (command-markup 'copy-title) ": " (command-docstring-first-sentence 'copy-title))
    (:li (command-markup 'nyxt/web-mode:copy-placeholder) ": " (command-docstring-first-sentence 'nyxt/web-mode:copy-placeholder))
    (:li (command-markup 'nyxt/web-mode:copy-hint-url) ": " (command-docstring-first-sentence 'nyxt/web-mode:copy-hint-url)))
   (:p "Leveraging password managers: ")
   (:ul 
    (:li (command-markup 'copy-username) ": " (command-docstring-first-sentence 'copy-username))
    (:li (command-markup 'copy-password) ": " (command-docstring-first-sentence 'copy-password))
    (:li (command-markup 'copy-password-prompt-details) ": " (command-docstring-first-sentence 'copy-password-prompt-details)))
   (:p "And more: ")
   (:ul
    (:li (command-markup 'nyxt/web-mode:paste-from-clipboard-ring) ": " (command-docstring-first-sentence 'nyxt/web-mode:paste-from-clipboard-ring))
    (:li (command-markup 'copy-system-information) ": " (command-docstring-first-sentence 'copy-system-information)))
```

I **cannot compile** the system successfully enough to start Nyxt. There is no shell output. It keeps going on in an infinite evaluation. This is what happens with me:

![bug-report](https://user-images.githubusercontent.com/7698207/124793710-a54c7480-df24-11eb-8d5b-0f9a2c2f2b63.gif)

Can you compile the system after adding this code snippet?


What is the appropriate way to report the stacktraces considering that I am using Slime? 
Could you give me a hint?

**Comment by Ambrevar** [comment]
I can't reproduce.

In your case, it seems that it's looping indefinitely on tutorial.lisp because of `command-docstring-first-sentence`.  But `command-docstring-first-sentence` is already used in non-`#+nil` blocks, so it's working there at least.

Can you delete ~/.cache/common-lisp and start over?

Can you report the output of `git status`?

**Comment by jmercouris** [comment]
Pierre do you have anything in your sbclrc that may be influencing this?

**Comment by Ambrevar** [comment]
Nope.

John, can you reproduce?
Can you share an exact recipe?

**Comment by jmercouris** [comment]
I can reproduce. One of my first instincts was also deleting all of the fasls...

Reproduce:
1. Load system
2. Execute (nyxt:start)
3. Observe perpetual waiting

**Comment by Ambrevar** [comment]
> Reproduce:
> 1. Load system
> 2. Execute (nyxt:start)
> 3. Observe perpetual waiting

Your recipe is different from Pedro's.  Pedro cannot even load the
system.

Please report:

- The Nyxt commit / branch.
- If you've done any change to the source.
- Your SBCL version.
- Since you can start Nyxt, what's the output with :verbose t?

**Comment by jmercouris** [comment]
- Branch: pdelfino:documentation-copy-paste
- Remove #+nil from `tutorial.lisp`
- SBCL 2.0.0

I was mistaken. I had been typing in `(nyxt:start)` before the system finished loading. Just like Pedro, my system freezes at:

```
; compiling (DEFUN TUTORIAL-CONTENT ...)
```

**Comment by jmercouris** [comment]
In fact.. the inferior lisp reports:

```
WARNING:
   redefining THREAD-FOR-EVALUATION (#<STRUCTURE-CLASS SWANK::MULTITHREADED-CONNECTION>
                                     #<SB-MOP:EQL-SPECIALIZER :FIND-EXISTING>) in DEFMETHOD
Heap exhausted during garbage collection: 0 bytes available, 32 requested.
Gen  Boxed   Code    Raw  LgBox LgCode  LgRaw  Pin       Alloc     Waste        Trig      WP GCs Mem-age
 1    8196      0   9926      0      0      0   22   531129920  62691776   326688202   18122   1  1.3923
 2    5125      1   6009      5      0      0   28   303596592  61438928    55742970   11140   1  0.1482
 3    1651      6    906    111      0     57   91    87374592   2114816     2000000    2731   0  0.0000
 4       0      0      0      0      0      0    0           0         0     2000000       0   0  0.0000
 5       0      0      0      0      0      0    0           0         0     2000000       0   0  0.0000
 6     426      2    183     55      0     10    0    21604464    546704     2000000     676   0  0.0000
           Total bytes allocated    =     943705568
           Dynamic-space-size bytes =    1073741824
GC control variables:
   *GC-INHIBIT* = true
   *GC-PENDING* = true
   *STOP-FOR-GC-PENDING* = false
fatal error encountered in SBCL pid 22527(tid 0x7f5c37507700):
Heap exhausted, game over.

Error opening /dev/tty: No such device or address
Welcome to LDB, a low-level debugger for the Lisp runtime environment.
ldb> 
```

which is why I asked if you had anything in your SBCLRC.

**Comment by jmercouris** [comment]
Now, I COULD override this in my SBCLRC, but should I? Is that really a good solution. I've seen some projects request that you do that. Seems wrong.

**Comment by Ambrevar** [comment]
You mean the dynamic-space-size?

Mine is:

```
CL-USER> (SB-EXT:DYNAMIC-SPACE-SIZE)
3221225472 (32 bits, #xC0000000)
```

(3 GiB)

The Guix packages uses a higher dyn space size indeed because some
libraries require it.

Good catch, John.
I'll do 2 things:
- fix this bug (I still don't understand what's happening)
- Add the dyn space size value to the system information.

**Comment by Ambrevar** [comment]
I can't reproduce even with a dynamic-space-size of 512 MiB.
I'll try to make the expansion cheaper nonetheless.

**Comment by Ambrevar** [comment]
Have you tried waiting like 1 minute?

**Comment by jmercouris** [comment]
Lol, I have tried, but I can wait longer, sure :-)

**Comment by Ambrevar** [comment]
Either we are using cl-markup wrong, or it's buggy.

I'll try with cl-who see if it makes any difference.

**Comment by jmercouris** [comment]
Or perhaps spinneret.

**Comment by Ambrevar** [comment]
cl-who is already an indirect dependency of Nyxt, while spinneret is
not.  I'll go with cl-who for testing.

**Comment by pdelfino** [comment]
> Can you delete ~/.cache/common-lisp and start over?

Do I need to delete everything? 
Anyway, I did. I have now:

```bash
~/.cache/common-lisp$ ls -la -l
total 8
drwxrwxr-x  2 pedro pedro 4096 jul  8 11:47 .
drwxr-xr-x 29 pedro pedro 4096 jun 19 15:33 ..
```


> Can you report the output of `git status`?

Sure 
```bash
$ git status
On branch documentation-copy-paste
Your branch is up to date with 'origin/documentation-copy-paste'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   _build/submodules/cl-webkit (new commits)

no changes added to commit (use "git add" and/or "git commit -a")

```

After doing it, It took much more time to load-system again. I guess things were really clean on cache.
But, as I did, the same infinite evaluation reported [here](https://github.com/atlas-engineer/nyxt/issues/1600#issuecomment-875736449) happened again.

**Comment by pdelfino** [comment]
If this helps, my dynamic space size is:

```lisp
CL-USER> (SB-EXT:DYNAMIC-SPACE-SIZE)
1073741824```

**Comment by Ambrevar** [comment]
Please try the patch I've sent.

**Comment by pdelfino** [comment]
> Please try the patch I've sent.

_Magnifique_ , it works now! :clap:

**Comment by pdelfino** [comment]
[PR](https://github.com/atlas-engineer/nyxt/pull/1611) fixes this.
