### ISSUE TITLE
Feature request: scroll until the end

### ISSUE THREAD

**Issue by pdelfino** [atlas-engineer/nyxt#1603]
Think about the UX of reading all the tweets from a specific person. 
The number of tweets is **finite**. It can be big, but it is finite.

The twitter UX treats it as a stream. As you scroll down, they show you more older tweets.

In cases like that, I would like to have a command `scroll-to-end`. After executing it, the stream would be over and I would have all tweets in a single page.

Besides creating an specific command for this purpose, it would be also possible to have a general command to execute an iteration over `scroll-to-bottom`.

Thus, this could be a particular case and a third application of the more general feature request described [here](https://github.com/atlas-engineer/nyxt/issues/1601). It is also possible to have this as an independent command.

**Comment by aartaka** [comment]
Doesn't `cruise-control-mode` or `repeat-mode` + `scroll-down` do the trick?

**Comment by pdelfino** [comment]
> Doesn't `cruise-control-mode` do the trick?

I knew `cruise-control-mode` before your comment was made but this approach did not occur to me, thanks. I just tried using it [here](https://twitter.com/srlm) and it works! :)

I guess it is not obvious to people how powerful `cruise-control mode` can be.  It is not useful **only** for reading long articles (which seems to be the original intention).

1 - Should we mention this possibility of cruise-mode use in Nyxt's manual? (first, mention it at all and then add this. I can send a patch.)

2 - Should we append this information on the release [article](https://nyxt.atlas.engineer/article/cruise-control-mode.org) about the feature written by @jmercouris?

By the way,

3 - Do you think the name is self-explanatory/good? 
Why `cruise`? A metaphor for boats/ships moving around? 
Why not `scroll-control-mode`?

**Comment by jmercouris** [comment]
The name cruise control is derived from here: https://en.wikipedia.org/wiki/Cruise_control

Of course you can use cruise control mode to achieve this, but how does cruise control mode know when to stop? It doesn't konw that the page has reached its end. We would need to provide it with a condition to check.

**Comment by jmercouris** [comment]
That could still be quite useful!

**Comment by pdelfino** [comment]
@aartaka also said:

> `repeat-mode` + `scroll-down` do the trick?

Again, I have tried this on this page from a Twitter [user](https://twitter.com/srlm). And it works! :)

The manual does not mention `repeat-mode`. This example with `scroll-to-bottom` seems great to **illustrate** the docstring:

> Mode to repeat a simple action/function repetitively until stopped.

On John's comment:

> but how does cruise control mode know when to stop?

When Nyxt reaches the first tweet (last on the stack) shown by Twitter, the bottom of the page, it simply stops loading more things. Does the mode need to know it has reached the end of the page? The user will easily know that, right?

@jmercouris, your opinion seems clear on my feature request (`scroll-until-the-end`) versus `cruise-control`. 

What about my feature request (`scroll-until-the-end`) versus `repeat-mode` + `scroll-to-bottom`?


Imho, @aartaka has a good point. People (including me) just need to know better what is already possible to do with Nyxt.

**Comment by Ambrevar** [comment]
@aartaka Why did you close this?

**Comment by aartaka** [comment]
> @aartaka Why did you close this?

Because 
- there's a section about `process-mode` and derivatives in the manual, 
- and an article about `repeat-mode` etc. on our blog,
- and the request for the feature is fully satisfied with `repeat-mode` and `scroll-down`.

**Comment by Ambrevar** [comment]
Roger that!
