### ISSUE TITLE
Panels don't accept key input

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#1604]
Example: `show-bookmarks-panel` links are not clickable when vi-mode is on.

**Comment by chrisboeg** [comment]
I am working on this, should have something to show tomorrow.

**Comment by jmercouris** [comment]
@chrisboeg is it OK if I take over this issue?

**Comment by chrisboeg** [comment]
Yes it’s fine - I am finally not sick anymore but will not be able to do any work until Monday anyways, so just go ahead.

**Comment by Ambrevar** [comment]
@jmercouris Any update on this?  Would be nice to merge a fix for 2.2.4.

**Comment by jmercouris** [comment]
No progress so far. I wouldn't hold my breath for 2.2.4!

**Comment by Ambrevar** [comment]
Should I work on it then?

**Comment by jmercouris** [comment]
Maybe. I have a very clear and strong opinion about how it should be done. If you don't mind how critical I will be about that specific patch, then go ahead :-D

**Comment by aartaka** [comment]
Closing this. Panels do accept keys now. The only thing that's lacking is tighter integration with commands (there's no intuitive way to do what commands do to regular buffers, but on panels). But then, this is already beyond this issue.

**Comment by Ambrevar** [comment]
Which commit fixed it?

**Comment by aartaka** [comment]
> Which commit fixed it?

The one that made `panel-buffer` inherit from `input-buffer`, I guess. No clear idea thogh—it just works.

**Comment by Ambrevar** [comment]
OK :)
