### ISSUE TITLE
Capitalize Readme consistently

### ISSUE THREAD

**Issue by jmercouris** [atlas-engineer/nyxt#1607]
I've noticed for quite sometime the lowercase readme in some of our libraries. Let's try to agree on a standard. I propose all uppercase because it is attention grabbing and sorted at the top on some terminals.

**Comment by Ambrevar** [comment]
Can you point at an offending use of "readme"?

**Comment by Ambrevar** [comment]
More precisely, you mean in file names or in file contents?

**Comment by jmercouris** [comment]
File names, here is an example: https://github.com/atlas-engineer/nyxt/blob/master/libraries/keymap/readme.org

note that 'readme.org' is entirely lowercase.

**Comment by Ambrevar** [comment]
Done 4615627db8a35af8eb6da53602e40a1484b074dd.
