### ISSUE TITLE
ASSERT failure in QWidget

### ISSUE THREAD

**Issue by dglb** [atlas-engineer/nyxt#1609]
**Describe the bug**

I launch nyxt-qt and I get the following error

ASSERT failure in QWidget: "Widgets must be created in the GUI thread.", file /homeloc/dbonnafo/qt5/qtbase/src/widgets/kernel/qwidget.cpp, line 999

**Information**
- OS name+version: Debian 10
- Graphics card and driver: NVIDIA NVS 315
- Desktop environment / Window manager name+version: dwm
- How you installed Nyxt (Guix pack, package manager, build from source): from source
- Information from command copy-system-information:

  If you can't run copy-system-information, try `nyxt --system-information` from
  a shell.

dbonnafo@yotta:~/tmp$ ~/common-lisp/nyxt/nyxt-qt --system-information
Nyxt version: 2.1.1-31-gb445b4fd
Renderer version: 
Operating system kernel: Linux 4.19.0-16-amd64
Lisp implementation: SBCL 2.1.6
Features: (NYXT-2 FSET-EXT-STRINGS CUSTOM-HASH-TABLE-NATIVE SWANK PLUMP-UTF-32
 GLOBAL-VARS DECLARE-TYPES PARENSCRIPT NAMED-READTABLES 21BIT-CHARS CHUNGA
 FLEXI-STREAMS CLOSER-MOP CL-PPCRE-UNICODE CL-UNICODE CL-PPCRE BORDEAUX-THREADS
 SPLIT-SEQUENCE GRAY-STREAMS FAST-IO-SV FAST-IO SBCL-USES-SB-ROTATE-BYTE
 ASDF-SYSTEM-CONNECTIONS CL-JSON-CLOS CL-JSON THREAD-SUPPORT FLAT-NAMESPACE
 X86-64 UNIX CFFI FLAT-NAMESPACE SEQUENCE-EMPTYP QUICKLISP ASDF3.3 ASDF3.2
 ASDF3.1 ASDF3 ASDF2 ASDF OS-UNIX NON-BASE-CHARS-EXIST-P ASDF-UNICODE X86-64
 GENCGC 64-BIT ANSI-CL COMMON-LISP ELF IEEE-FLOATING-POINT LINUX LITTLE-ENDIAN
 PACKAGE-LOCAL-NICKNAMES SB-LDB SB-PACKAGE-LOCKS SB-THREAD SB-UNICODE SBCL UNIX)

ASDF version: 3.3.2
Critical dependencies: (/home/dbonnafo/quicklisp/dists/quicklisp/software/cl-cffi-gtk-20201220-git/gtk/cl-cffi-gtk.asd
 /home/dbonnafo/quicklisp/dists/quicklisp/software/cl-gobject-introspection-20210124-git/cl-gobject-introspection.asd
 /home/dbonnafo/quicklisp/dists/quicklisp/software/cl-webkit-20210630-git/webkit2/cl-webkit2.asd)

Quicklisp dist version: 2021-06-30
Quicklisp client version: 2021-02-13
Local project directories: (/home/dbonnafo/quicklisp/local-projects/)
Critical dependencies(#<SYSTEM cl-cffi-gtk / cl-cffi-gtk-20201220-git / quicklisp 2021-06-30>
 #<SYSTEM cl-gobject-introspection / cl-gobject-introspection-20210124-git / quicklisp 2021-06-30>
 #<SYSTEM cl-webkit2 / cl-webkit-20210630-git / quicklisp 2021-06-30>)

  - QtWebEngine version: 5.15.2, from source

**Output when started from a shell**

dbonnafo@yotta:~/tmp$ ~/common-lisp/nyxt/nyxt-qt 
<INFO> [16:48:35] Listening to socket "nyxt/nyxt.socket".
Nyxt version 2.1.1-31-gb445b4fd
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-dbonnafo'
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-dbonnafo'
ASSERT failure in QWidget: "Widgets must be created in the GUI thread.", file /homeloc/dbonnafo/qt5/qtbase/src/widgets/kernel/qwidget.cpp, line 999
fatal error encountered in SBCL pid 46863 tid 46870:
SIGABRT received.

Welcome to LDB, a low-level debugger for the Lisp runtime environment.
ldb>

**Comment by Ambrevar** [comment]
QtWebengine support is currently experimental and it won't start
properly on master, so this is expected, sorry.

I've updated the README and the doc to reflect this.

**Comment by Ambrevar** [comment]
Closing now, but if you are up for some hacking, you are more than welcome to help us take the QtWengengine renderer up to speed :)
