### ISSUE TITLE
Loading history causes nyxt freeze

### ISSUE THREAD

**Issue by franburstall** [atlas-engineer/nyxt#1614]
**Describe the bug**

I have a customised status bar that queries the history status of the buffer to colour the forward and back arrows when there is history to move forward or back to.

Since commit 700e42fdab71229f6abafa09658b5debd72f3a3a, this causes nyxt to freeze completely at startup after the history is loaded (SIGTERM has no effect, you need to SIGKILL).  The functions that do the querying are:
````common-lisp
(defun forward-history-p (&optional (buffer (current-buffer)))
  (with-data-unsafe (history (history-path buffer))
     (ignore-errors (htree:children (htree:current-owner-node history)))))

(defun backward-history-p (&optional (buffer (current-buffer)))
  (with-data-unsafe (history (history-path buffer))
      (ignore-errors (htree:all-parents history))))
````
Any ideas how I can successfully query history?

**Information**
- OS name+version: Debian 10
- Graphics card and driver:
- Desktop environment / Window manager name+version: EXWM
- How you installed Nyxt (Guix pack, package manager, build from source): build from source
- Information from command copy-system-information:
Nyxt version: 2.1.1-109-g23db3e0d
Renderer version: GI-GTK
Operating system kernel: Linux 4.19.0-17-amd64
Lisp implementation: SBCL 2.1.1 (Dynamic space size: 1073741824)
Features: (WEBKIT2 WEBKIT2-2.32 WEBKIT2-PASTE-PLAINTEXT WEBKIT2-TRACKING WEBKIT2-MUTE
 WEBKIT2-EMOJI WEBKIT2-MEDIA WEBKIT2-SANDBOXING GTK-3-22 GTK-3-20 GTK-3-18
 GTK-3-16 GTK-3-14 GTK-3-12 GTK-3-10 GTK-3-8 GTK-3-6 GTK-3-4 GTK GDK-3-22
 GDK-3-20 GDK-3-18 GDK-3-16 GDK-3-14 GDK-3-12 GDK-3-10 GDK-3-8 GDK-3-6 GDK-3-4
 CAIRO-1-10 CAIRO-1-12 GDK-PIXBUF GLIB-2-30 GLIB-2-32 GLIB-2-34 GLIB-2-36
 GLIB-2-38 GLIB-2-40 GLIB-2-42 GLIB-2-44 GLIB-2-46 GLIB-2-48 GLIB-2-50
 GLIB-2-52 GLIB-2-54 GLIB-2-56 GLIB-2-58 GLIB NYXT-2 FSET-EXT-STRINGS
 CUSTOM-HASH-TABLE-NATIVE SWANK PLUMP-UTF-32 GLOBAL-VARS DECLARE-TYPES
 PARENSCRIPT NAMED-READTABLES 21BIT-CHARS CHUNGA FLEXI-STREAMS CLOSER-MOP
 CL-PPCRE-UNICODE CL-UNICODE CL-PPCRE BORDEAUX-THREADS SPLIT-SEQUENCE
 GRAY-STREAMS FAST-IO-SV FAST-IO SBCL-USES-SB-ROTATE-BYTE
 ASDF-SYSTEM-CONNECTIONS CL-JSON-CLOS CL-JSON THREAD-SUPPORT FLAT-NAMESPACE
 X86-64 UNIX CFFI FLAT-NAMESPACE SEQUENCE-EMPTYP QUICKLISP ASDF3.3 ASDF3.2
 ASDF3.1 ASDF3 ASDF2 ASDF OS-UNIX NON-BASE-CHARS-EXIST-P ASDF-UNICODE X86-64
 GENCGC 64-BIT ANSI-CL COMMON-LISP ELF IEEE-FLOATING-POINT LINUX LITTLE-ENDIAN
 PACKAGE-LOCAL-NICKNAMES SB-LDB SB-PACKAGE-LOCKS SB-THREAD SB-UNICODE SBCL UNIX)

ASDF version: 3.3.1
Critical dependencies: (/home/fran/common-lisp/nyxt/_build/submodules/cl-cffi-gtk/gtk/cl-cffi-gtk.asd
 /home/fran/common-lisp/nyxt/_build/quicklisp-client/dists/quicklisp/software/cl-gobject-introspection-20210124-git/cl-gobject-introspection.asd
 /home/fran/common-lisp/nyxt/_build/submodules/cl-webkit/webkit2/cl-webkit2.asd)

Quicklisp dist version: 2021-06-30
Quicklisp client version: 2020-01-04
Local project directories: (/home/fran/common-lisp/nyxt/_build/submodules/
 /home/fran/common-lisp/nyxt/_build/quicklisp-client/local-projects/)
Critical dependencies(#<SYSTEM cl-cffi-gtk / cl-cffi-gtk-20201220-git / quicklisp 2021-06-30>
 #<SYSTEM cl-gobject-introspection / cl-gobject-introspection-20210124-git / quicklisp 2021-06-30>
 #<SYSTEM cl-webkit2 / cl-webkit-20210630-git / quicklisp 2021-06-30>)

**Output when started from a shell**
(<INFO> [18:54:52] Listening to socket "/run/user/1000/nyxt/nyxt.socket".
Nyxt version 2.1.1-109-g23db3e0d
<INFO> [18:54:52] Loading Lisp file "/home/fran/.config/nyxt/init.lisp".
;; Slynk started at port: 4006.
SLYNK's ASDF loader finished.<INFO> [18:54:52] Slynk server started at port 4006
<INFO> [18:54:53] Loading history of 1134 URLs from "/home/fran/.local/share/nyxt/history/default.lisp".
<INFO> [18:55:15] Loading history of 1134 URLs from "/home/fran/.local/share/nyxt/history/default.lisp".
<INFO> [18:55:15] Restoring 13 buffers from history.
fish: “nyxt” terminated by signal SIGKILL (Forced quit)

**Comment by Ambrevar** [comment]
Thanks for reporting, this is certainly a critical issue.

Can you share a minimal init.lisp to reproduce this?

**Comment by franburstall** [comment]
Here is a minimal init.lisp:
```common-lisp
(in-package #:nyxt-user)

(defun forward-history-p (&optional (buffer (current-buffer)))
  (with-data-unsafe (history (history-path buffer))
    ;; the following errors out on a new buffer or window
    (ignore-errors (htree:children (htree:current-owner-node history)))))

(defun backward-history-p (&optional (buffer (current-buffer)))
  (with-data-unsafe (history (history-path buffer))
    ;; the following errors out on a new buffer or window
    (ignore-errors (htree:all-parents history))))

(defun my-format-status-unsafe-buttons ()
  (markup:markup
   (:a :class (if (backward-history-p) "has-history" "button")
       :title "Backwards" :href (lisp-url '(nyxt/web-mode:history-backwards)) "❮")
   (:a :class (if (forward-history-p) "has-history" "button")
       :title "Forwards" :href (lisp-url '(nyxt/web-mode:history-forwards)) "❯")))

(defun my-format-status (window)
  (declare (ignore window))
  (markup:markup
   (:div :id "container"
	 (:div :id "controls"
	       (markup:raw (my-format-status-unsafe-buttons))))))

(define-configuration window 
  ((status-formatter #'my-format-status)))
````

More data: after such a freeze, nyxt leaves an empty profile of the form `default-tmp31RWPSX2.lisp`.  If I choose one of these to load, instead of the default history, then the freeze does not occur.   In this case, the default history is loaded but *no* buffers are restored.  So it looks like the freeze is caused by restoring the buffers from the history.

**Comment by Ambrevar** [comment]
I'll look into it as soon as possible.

**Comment by Ambrevar** [comment]
I tried this on master and it does not freeze for me.
I've adapted your minimal example to use Spinneret:

```lisp
 (in-package #:nyxt-user)

(defun forward-history-p (&optional (buffer (current-buffer)))
  (with-data-unsafe (history (history-path buffer))
    ;; the following errors out on a new buffer or window
    (ignore-errors (htree:children (htree:current-owner-node history)))))

(defun backward-history-p (&optional (buffer (current-buffer)))
  (with-data-unsafe (history (history-path buffer))
    ;; the following errors out on a new buffer or window
    (ignore-errors (htree:all-parents history))))

(defun my-format-status-unsafe-buttons ()
  (spinneret:with-html
    (:a :class (if (backward-history-p) "has-history" "button")
        :title "Backwards" :href (lisp-url '(nyxt/web-mode:history-backwards)) "❮")
    (:a :class (if (forward-history-p) "has-history" "button")
        :title "Forwards" :href (lisp-url '(nyxt/web-mode:history-forwards)) "❯")))

(defun my-format-status (window)
  (declare (ignore window))
  (spinneret:with-html-string
    (:div :id "container"
          (:div :id "controls"
                (my-format-status-unsafe-buttons)))))

(define-configuration window
  ((status-formatter #'my-format-status)))
```

**Comment by Ambrevar** [comment]
Could be a race condition, but first can you reproduce on master
yourself?

If so, what triggers the hang?  Clicking on a button?  Which one?  From
which buffer?

Can you provide a minimal, exact recipe when starting Nyxt from an empty history?

**Comment by franburstall** [comment]
> Could be a race condition, but first can you reproduce on master yourself? 

Yes, I can reproduce on Nyxt version 2.1.1-315-gf5c13e7c, see below

>If so, what triggers the hang? Clicking on a button? Which one? From which buffer? Can you provide a minimal, exact recipe when starting Nyxt from an empty history?

I am not sure how to start Nyxt from an empty history but this is what I tried with nyxt built from master.
1. Make an empty file  `~/.local/share/nyxt/history/test.lisp`.
2. Fire nyxt with ` nyxt -i ~/.config/nyxt/mwe/init.lisp -v`.
3. I am confronted with the "The name of the history to restore" prompt.
4. I choose "test" and hit return.
5. I see that my history has been loaded (why?):
```
  <INFO> [11:58:41] nyxt message.lisp (echo form-fun-6) -
  Loading history of 1307 URLs from "/home/fran/.local/share/nyxt/history/default.lisp".
```
6. I am left at the welcome buffer (buttons for Manual, Tutorial etc) .  In particular, no buffers from a previous session are opened and there is NO freeze.

To get a freeze, I do the same thing with my usual history:
1. Fire nyxt with ` nyxt -i ~/.config/nyxt/mwe/init.lisp -v`.
2. I am confronted with the "The name of the history to restore" prompt.
3. I choose "default" and hit return.
4. At this point, I am shown an empty buffer and nyxt freezes completely.  I need to kill -9 to end it.

The only detectable difference between these two runs is that, in the broken one, an attempt is made to restore buffers from a previous session:
```
 <INFO> [11:53:00] nyxt history.lisp (restore-history-buffers with-recursive-lock-thunk) -
  Restoring 14 buffers from history.
```
It seems that this is what provokes the freeze.

NB: the minimal init.lisp in use here is your one with spinneret replacing markup.

**Comment by Ambrevar** [comment]
Could you produce a history file and share it with me?
If you don't want to share it publicly, you can send it by email.
Of course you can edit the URLs in the history and replace them with
whatever, just make sure they are different URLs.

**Comment by Ambrevar** [comment]
Maybe the easiest way to produce  this history file would be to start a
new and create a dozen of buffers (enough until it gets Nyxt to hang on
restart).

**Comment by franburstall** [comment]
> Maybe the easiest way to produce this history file would be to start a new and create a dozen of buffers (enough until it gets Nyxt to hang on restart).

Turns out you only need one buffer!  Here is a small history file [default.lisp](https://github.com/atlas-engineer/nyxt/files/6884107/default.txt).

Here is the transcript of a run that froze:
```
demoulin:~/c/nyxt% nyxt -i ~/.config/nyxt/mwe/init.lisp -v
Arguments parsed: (INIT /home/fran/.config/nyxt/mwe/init.lisp VERBOSE T URLS
                   NIL) and NIL
 <INFO> [09:42:57] nyxt start.lisp (listen-or-query-socket) -
  Listening to socket "/run/user/1000/nyxt/nyxt.socket".
Nyxt version 2.1.1-315-gf5c13e7c
<DEBUG> [09:42:57] nyxt start.lisp (load-lisp unsafe-load) -
  Lisp file "/home/fran/.config/nyxt/auto-config.lisp" does not exist.
 <INFO> [09:42:57] nyxt start.lisp (load-lisp unsafe-load) -
  Loading Lisp file "/home/fran/.config/nyxt/mwe/init.lisp".
<DEBUG> [09:42:57] nyxt renderer-gi-gtk.lisp (ffi-initialize gtk-browser) -
  Initializing GI-GTK Interface
 <INFO> [09:42:57] nyxt message.lisp (echo form-fun-6) -
  Loading history of 1 URLs from "/home/fran/.local/share/nyxt/history/default.lisp".
<DEBUG> [09:42:57] nyxt base-mode.lisp (base-mode form-fun-20) -
  BASE-MODE enabled.
<DEBUG> [09:42:57] nyxt/web-mode web-mode.lisp (web-mode form-fun-32) -
  WEB-MODE enabled.
<DEBUG> [09:42:57] nyxt/help-mode help-mode.lisp (help-mode form-fun-16) -
  HELP-MODE enabled.
<DEBUG> [09:42:57] nyxt/prompt-buffer-mode prompt-buffer-mode.lisp (prompt-buffer-mode form-fun-19) -
  PROMPT-BUFFER-MODE enabled.
<DEBUG> [09:42:59] nyxt renderer-gtk.lisp (on-signal-key-press-event gtk-window) -
  NYXT::KEY-STRING: "return" NYXT::KEYCODE: 36 CHARACTER: #\Return
  NYXT::KEYVAL-NAME: "Return" 
<DEBUG> [09:42:59] nyxt input.lisp (dispatch-input-event) -
  Found key binding "return" [#36] to RETURN-SELECTION
 <INFO> [09:42:59] nyxt message.lisp (echo form-fun-6) -
  Loading history of 1 URLs from "/home/fran/.local/share/nyxt/history/default.lisp".
 <INFO> [09:42:59] nyxt history.lisp (restore-history-buffers with-recursive-lock-thunk) -
  Restoring 1 buffers from history.
<DEBUG> [09:42:59] nyxt base-mode.lisp (base-mode form-fun-20) -
  BASE-MODE enabled.
<DEBUG> [09:42:59] nyxt/web-mode web-mode.lisp (web-mode form-fun-32) -
  WEB-MODE enabled.
<DEBUG> [09:42:59] nyxt/certificate-exception-mode certificate-exception-mode.lisp (certificate-exception-mode form-fun-26) -
  CERTIFICATE-EXCEPTION-MODE enabled.
fish: “nyxt -i ~/.config/nyxt/mwe/init…” terminated by signal SIGKILL (Forced quit)
```

**Comment by Ambrevar** [comment]
What's your `session-restore-prompt`?

**Comment by Ambrevar** [comment]
Never mind, I can reproduce! Hooray!

**Comment by Ambrevar** [comment]
Should be fixed with b665471bb7829f5e0f4092340a037dbfa82b43c2, can you confirm?

**Comment by franburstall** [comment]
Yup: fix confirmed!  Many thanks!

**Comment by Ambrevar** [comment]
Thank _you_ for reporting this and your patience, this bug was lurking in a very dark corner.
I've opened https://github.com/atlas-engineer/nyxt/issues/1684 to discuss concurrency issues in general if you are interested.
