### ISSUE TITLE
Possible bug: "Warning: JavaScript error: invalid number of arguments: 2" and odd behavior

### ISSUE THREAD

**Issue by pdelfino** [atlas-engineer/nyxt#1629]
**Describe the bug**
After starting Nyxt, the mini-buffer keeps returning a message: "Warning: JavaScript error: invalid number of arguments: 2". In addition, the behavior of Nyxt is odd. For instance, the fuzzy search on prompt buffer does not work at all.

**Precise recipe to reproduce the issue**
 - To reproduce this you need to run Nyxt from source. First, check out on commit id 8e8b751c43c3affb6df3519e542507bca8a607f9 
 - Be inside the Lisp REPL (I used Slime);
 - Load the system nyxt/gi-gtk;
 - Start Nyxt `CL-USER> (nyxt:start)`;
 - See the message "<WARN> [11:56:44] Warning: JavaScript error: invalid number of arguments: 2"
 - Every keystroke generates the mentioned message on REPL;
 - Call the prompt-buffer with `C-space` or `M-x`;
 - Try calling any command on prompt buffer, the fuzzy search does not work at all, prompt buffer remains static

For website-specific issues:
Can you reproduce this issue with Epiphany / GNOME Web (https://wiki.gnome.org/Apps/Web)?
Not relevant for this problem

**Information**
- OS name+version: 
Ubuntu 20.04 LTS

- Graphics card and driver:
product: Iris Plus Graphics 640
configuration: driver=i915 latency=0

- Desktop environment / Window manager name+version:
Name: GNOME Shell 3.36.7
Window manager's "showing the desktop" mode: OFF

- How you installed Nyxt (Guix pack, package manager, build from source):
Source

- Information from command copy-system-information:
NYXT> (copy-system-information)
<INFO> [11:59:46] NYXT-INFORMATION: "Nyxt version: 2.1.1-226-g8e8b751c
Renderer version: GI-GTK
Operating system kernel: Linux 5.8.0-59-generic
Lisp implementation: SBCL 2.0.1.debian (Dynamic space size: 1073741824)
Features: (WEBKIT2 WEBKIT2-2.32 WEBKIT2-PASTE-PLAINTEXT WEBKIT2-TRACKING WEBKIT2-MUTE
 WEBKIT2-EMOJI WEBKIT2-MEDIA WEBKIT2-SANDBOXING GTK-3-22 GTK-3-20 GTK-3-18
 GTK-3-16 GTK-3-14 GTK-3-12 GTK-3-10 GTK-3-8 GTK-3-6 GTK-3-4 GTK GDK-3-22
 GDK-3-20 GDK-3-18 GDK-3-16 GDK-3-14 GDK-3-12 GDK-3-10 GDK-3-8 GDK-3-6 GDK-3-4
 CAIRO-1-10 CAIRO-1-12 GDK-PIXBUF GLIB-2-30 GLIB-2-32 GLIB-2-34 GLIB-2-36
 GLIB-2-38 GLIB-2-40 GLIB-2-42 GLIB-2-44 GLIB-2-46 GLIB-2-48 GLIB-2-50
 GLIB-2-52 GLIB-2-54 GLIB-2-56 GLIB-2-58 GLIB NYXT-2 FSET-EXT-STRINGS
 CUSTOM-HASH-TABLE-NATIVE PLUMP-UTF-32 GLOBAL-VARS DECLARE-TYPES PARENSCRIPT
 NAMED-READTABLES 21BIT-CHARS CHUNGA FLEXI-STREAMS CLOSER-MOP CL-PPCRE-UNICODE
 CL-UNICODE CL-PPCRE BORDEAUX-THREADS SPLIT-SEQUENCE GRAY-STREAMS
 FLAT-NAMESPACE X86-64 UNIX CFFI FLAT-NAMESPACE SEQUENCE-EMPTYP FAST-IO-SV
 FAST-IO SBCL-USES-SB-ROTATE-BYTE ASDF-SYSTEM-CONNECTIONS CL-JSON-CLOS CL-JSON
 THREAD-SUPPORT SWANK QUICKLISP SB-BSD-SOCKETS-ADDRINFO ASDF3.3 ASDF3.2 ASDF3.1
 ASDF3 ASDF2 ASDF OS-UNIX NON-BASE-CHARS-EXIST-P ASDF-UNICODE X86-64 64-BIT
 ANSI-CL COMMON-LISP ELF GENCGC IEEE-FLOATING-POINT LINUX LITTLE-ENDIAN
 PACKAGE-LOCAL-NICKNAMES SB-CORE-COMPRESSION SB-LDB SB-PACKAGE-LOCKS SB-THREAD
 SB-UNICODE SBCL UNIX)

ASDF version: 3.3.1
Critical dependencies: (/home/pedro/.quicklisp/dists/quicklisp/software/cl-cffi-gtk-20201220-git/gtk/cl-cffi-gtk.asd
 /home/pedro/.quicklisp/dists/quicklisp/software/cl-gobject-introspection-20210124-git/cl-gobject-introspection.asd
 /home/pedro/common-lisp/cl-webkit/webkit2/cl-webkit2.asd)

Quicklisp dist version: 2021-05-31
Quicklisp client version: 2021-02-13
Local project directories: (/home/pedro/.quicklisp/local-projects/)
Critical dependencies(#<SYSTEM cl-cffi-gtk / cl-cffi-gtk-20201220-git / quicklisp 2021-05-31>
 #<SYSTEM cl-gobject-introspection / cl-gobject-introspection-20210124-git / quicklisp 2021-05-31>
 #<SYSTEM cl-webkit2 / cl-webkit-20210531-git / quicklisp 2021-05-31>)

  If you can't run copy-system-information, try `nyxt --system-information` from
  a shell.  It this still does not work, please provide the following:
  - Nyxt version (from =M-x nyxt-version= or =nyxt --version=):
  - Lisp implementation/version (if built from source):
  - Kernel name+version:
  - WebKitGTK+ | QtWebEngine version:

I could execute copy-system-information on REPL. It did not work on the GUI, though.

**Output when started from a shell**
; SLIME 2.26.1WARNING: System definition file #P"/home/pedro/.quicklisp/dists/quicklisp/software/calispel-20170830-git/calispel.asd" contains definition for system "calispel-test". Please only define "calispel" and secondary systems with a name starting with "calispel/" (e.g. "calispel/test") in that file.
WARNING: System definition file #P"/home/pedro/.quicklisp/dists/quicklisp/software/cl-json-20141217-git/cl-json.asd" contains definition for system "cl-json.test". Please only define "cl-json" and secondary systems with a name starting with "cl-json/" (e.g. "cl-json/test") in that file.
WARNING: System definition file #P"/home/pedro/.quicklisp/dists/quicklisp/software/cl-ppcre-20190521-git/cl-ppcre.asd" contains definition for system "cl-ppcre-test". Please only define "cl-ppcre" and secondary systems with a name starting with "cl-ppcre/" (e.g. "cl-ppcre/test") in that file.
WARNING: System definition file #P"/home/pedro/.quicklisp/dists/quicklisp/software/cl-ppcre-20190521-git/cl-ppcre-unicode.asd" contains definition for system "cl-ppcre-unicode-test". Please only define "cl-ppcre-unicode" and secondary systems with a name starting with "cl-ppcre-unicode/" (e.g. "cl-ppcre-unicode/test") in that file.
WARNING: System definition file #P"/home/pedro/.quicklisp/dists/quicklisp/software/s-xml-20150608-git/s-xml.asd" contains definition for system "s-xml.test". Please only define "s-xml" and secondary systems with a name starting with "s-xml/" (e.g. "s-xml/test") in that file.
WARNING: System definition file #P"/home/pedro/.quicklisp/dists/quicklisp/software/s-xml-20150608-git/s-xml.asd" contains definition for system "s-xml.examples". Please only define "s-xml" and secondary systems with a name starting with "s-xml/" (e.g. "s-xml/test") in that file.
WARNING: System definition file #P"/home/pedro/.quicklisp/dists/quicklisp/software/flexi-streams-20200925-git/flexi-streams.asd" contains definition for system "flexi-streams-test". Please only define "flexi-streams" and secondary systems with a name starting with "flexi-streams/" (e.g. "flexi-streams/test") in that file.
;;; Computing Hangul syllable names
WARNING: redefining S-SERIALIZATION::SERIALIZE-SEXP-INTERNAL in DEFGENERIC
WARNING: redefining CL-PREVALENCE:GET-ID in DEFGENERIC
WARNING: redefining CL-PREVALENCE:GET-NAME in DEFGENERIC
WARNING: redefining (COMMON-LISP:SETF CL-PREVALENCE:GET-NAME) in DEFGENERIC
WARNING: redefining CL-PREVALENCE:GET-SIZE in DEFGENERIC
WARNING: redefining CL-PREVALENCE:GET-MIME-TYPE in DEFGENERIC
WARNING: redefining (COMMON-LISP:SETF CL-PREVALENCE:GET-MIME-TYPE) in DEFGENERIC
WARNING: redefining CL-PREVALENCE:GET-KEYWORDS in DEFGENERIC
WARNING: redefining (COMMON-LISP:SETF CL-PREVALENCE:GET-KEYWORDS) in DEFGENERIC
WARNING: redefining LOG4CL-IMPL:APPENDER-ADDED in DEFGENERIC
WARNING: redefining LOG4CL-IMPL:APPENDER-REMOVED in DEFGENERIC
WARNING: redefining LOG4CL-IMPL::PROPERTY-ALIST in DEFGENERIC
WARNING:
   The new FTYPE proclamation for CLSS:MATCH-SELECTOR
     (FUNCTION (LIST (OR PLUMP-DOM:NODE VECTOR LIST) KEYWORD)
      (VALUES (AND (VECTOR PLUMP-DOM:NODE) (NOT SIMPLE-ARRAY))))
   does not match the old FTYPE proclamation
     (FUNCTION (LIST (OR PLUMP-DOM:NODE VECTOR CONS NULL) &OPTIONAL KEYWORD)
      (VALUES (AND (VECTOR PLUMP-DOM:NODE) (NOT SIMPLE-ARRAY)) &REST T))
WARNING: SWANK/BACKEND also exports the following symbols:
  (SWANK/BACKEND:SLDB-STEP-NEXT SWANK/BACKEND:CALL-WITH-LOCK-HELD
                                SWANK/BACKEND:WHO-BINDS
                                SWANK/BACKEND:MAKE-WEAK-KEY-HASH-TABLE
                                SWANK/BACKEND:FIND-DEFINITIONS
                                SWANK/BACKEND:FORMAT-STRING-EXPAND
                                SWANK/BACKEND:FRAME-CALL
                                SWANK/BACKEND:MAKE-AUTO-FLUSH-THREAD
                                SWANK/BACKEND:FIND-REGISTERED
                                SWANK/BACKEND:PACKAGE-LOCAL-NICKNAMES
                                SWANK/BACKEND:INITIALIZE-MULTIPROCESSING
                                SWANK/BACKEND:DESCRIBE-SYMBOL-FOR-EMACS
                                SWANK/BACKEND:CALL-WITH-DEBUGGER-HOOK
                                SWANK/BACKEND:SET-DEFAULT-INITIAL-BINDING
                                SWANK/BACKEND:WAKE-THREAD
                                SWANK/BACKEND:WHO-CALLS
                                SWANK/BACKEND:CALL-WITH-DEBUGGING-ENVIRONMENT
                                SWANK/BACKEND:COMPILER-MACROEXPAND-1
                                SWANK/BACKEND:TYPE-SPECIFIER-P
                                SWANK/BACKEND:DESCRIBE-PRIMITIVE-TYPE
                                SWANK/BACKEND:DISASSEMBLE-FRAME
                                SWANK/BACKEND:THREAD-ID SWANK/BACKEND:WRAP
                                SWANK/BACKEND:FLOAT-INFINITY-P
                                SWANK/BACKEND:SAVE-IMAGE
                                SWANK/BACKEND:WHO-REFERENCES
                                SWANK/BACKEND:PRINT-FRAME
                                SWANK/BACKEND:GRAY-PACKAGE-NAME
                                SWANK/BACKEND:CALL-WITH-SYNTAX-HOOKS
                                SWANK/BACKEND:GUESS-EXTERNAL-FORMAT
                                SWANK/BACKEND:SWANK-COMPILE-FILE
                                SWANK/BACKEND:LISP-IMPLEMENTATION-PROGRAM
                                SWANK/BACKEND:SOCKET-FD
                                SWANK/BACKEND:INSTALL-DEBUGGER-GLOBALLY
                                SWANK/BACKEND:BACKGROUND-SAVE-IMAGE
                                SWANK/BACKEND:VALID-FUNCTION-NAME-P
                                SWANK/BACKEND:WHO-MACROEXPANDS
                                SWANK/BACKEND:EMACS-CONNECTED
                                SWANK/BACKEND:SLDB-STEP-INTO
                                SWANK/BACKEND:FIND-SOURCE-LOCATION
                                SWANK/BACKEND:ACTIVATE-STEPPING
                                SWANK/BACKEND:WAIT-FOR-INPUT SWANK/BACKEND:DUP
                                SWANK/BACKEND:UNPROFILE SWANK/BACKEND:PROFILE
                                SWANK/BACKEND:SLDB-STEPPER-CONDITION-P
                                SWANK/BACKEND:WHO-SPECIALIZES
                                SWANK/BACKEND:FUNCTION-NAME
                                SWANK/BACKEND:SLDB-STEP-OUT
                                SWANK/BACKEND:INSTALL-SIGINT-HANDLER
                                SWANK/BACKEND:THREAD-STATUS
                                SWANK/BACKEND:MAKE-LOCK
                                SWANK/BACKEND:ALL-THREADS
                                SWANK/BACKEND:CLOSE-SOCKET
                                SWANK/BACKEND:WHO-SETS
                                SWANK/BACKEND:FIND-LOCALLY-NICKNAMED-PACKAGE
                                SWANK/BACKEND:COMPUTE-BACKTRACE
                                SWANK/BACKEND:THREAD-ATTRIBUTES
                                SWANK/BACKEND:RECEIVE SWANK/BACKEND:EXEC-IMAGE
                                SWANK/BACKEND:CREATE-SOCKET
                                SWANK/BACKEND:DESCRIBE-DEFINITION
                                SWANK/BACKEND:SWANK-COMPILE-STRING
                                SWANK/BACKEND:RECEIVE-IF SWANK/BACKEND:SEND
                                SWANK/BACKEND:KILL-THREAD
                                SWANK/BACKEND:CALLS-WHO
                                SWANK/BACKEND:FILENAME-TO-PATHNAME
                                SWANK/BACKEND:LIST-CALLEES
                                SWANK/BACKEND:ADD-SIGIO-HANDLER
                                SWANK/BACKEND:CALL-WITH-USER-BREAK-HANDLER
                                SWANK/BACKEND:DEFAULT-READTABLE-ALIST
                                SWANK/BACKEND:COMPILER-MACROEXPAND
                                SWANK/BACKEND:REGISTER-THREAD
                                SWANK/BACKEND:LOCAL-PORT
                                SWANK/BACKEND:FIND-EXTERNAL-FORMAT
                                SWANK/BACKEND:THREAD-ALIVE-P
                                SWANK/BACKEND:COLLECT-MACRO-FORMS
                                SWANK/BACKEND:SET-STREAM-TIMEOUT
                                SWANK/BACKEND:INTERRUPT-THREAD
                                SWANK/BACKEND:FRAME-PACKAGE
                                SWANK/BACKEND:CONDITION-EXTRAS
                                SWANK/BACKEND:UNWRAP
                                SWANK/BACKEND:FRAME-VAR-VALUE
                                SWANK/BACKEND:EVAL-IN-FRAME
                                SWANK/BACKEND:STRING-TO-UTF8
                                SWANK/BACKEND:PRINT-CONDITION
                                SWANK/BACKEND:LISP-IMPLEMENTATION-TYPE-NAME
                                SWANK/BACKEND:MAKE-WEAK-VALUE-HASH-TABLE
                                SWANK/BACKEND:ADD-FD-HANDLER
                                SWANK/BACKEND:UTF8-TO-STRING
                                SWANK/BACKEND:PREFERRED-COMMUNICATION-STYLE
                                SWANK/BACKEND:THREAD-NAME
                                SWANK/BACKEND:FRAME-RESTARTABLE-P
                                SWANK/BACKEND:WRAPPED-P
                                SWANK/BACKEND:FIND-THREAD
                                SWANK/BACKEND:MACROEXPAND-ALL
                                SWANK/BACKEND:LIST-CALLERS
                                SWANK/BACKEND:PATHNAME-TO-FILENAME
                                SWANK/BACKEND:MAKE-INPUT-STREAM
                                SWANK/BACKEND:REMOVE-FD-HANDLERS
                                SWANK/BACKEND:ARGLIST
                                SWANK/BACKEND:FRAME-LOCALS
                                SWANK/BACKEND:EVAL-CONTEXT
                                SWANK/BACKEND:RETURN-FROM-FRAME
                                SWANK/BACKEND:FLOAT-NAN-P
                                SWANK/BACKEND:MAKE-FD-STREAM
                                SWANK/BACKEND:MAKE-OUTPUT-STREAM
                                SWANK/BACKEND:TOGGLE-TRACE
                                SWANK/BACKEND:CALL-WITH-COMPILATION-HOOKS
                                SWANK/BACKEND:GETPID
                                SWANK/BACKEND:SLDB-BREAK-AT-START
                                SWANK/BACKEND:SPAWN
                                SWANK/BACKEND:HASH-TABLE-WEAKNESS
                                SWANK/BACKEND:CHARACTER-COMPLETION-SET
                                SWANK/BACKEND:ACCEPT-CONNECTION
                                SWANK/BACKEND:CURRENT-THREAD
                                SWANK/BACKEND:FRAME-CATCH-TAGS
                                SWANK/BACKEND:REMOVE-SIGIO-HANDLERS
                                SWANK/BACKEND:COMMAND-LINE-ARGS)
See also:
  The ANSI Standard, Macro DEFPACKAGE
  The SBCL Manual, Variable *ON-PACKAGE-VARIANCE*
WARNING: SWANK also exports the following symbols:
  (SWANK:TOGGLE-PROFILE-FDEFINITION SWANK:INSPECT-IN-FRAME
                                    SWANK:DEBUG-NTH-THREAD
                                    SWANK:FIND-SOURCE-LOCATION-FOR-EMACS
                                    SWANK:COMPILE-MULTIPLE-STRINGS-FOR-EMACS
                                    SWANK:DESCRIBE-DEFINITION-FOR-EMACS
                                    SWANK:INIT-INSPECTOR
                                    SWANK:SWANK-MACROEXPAND SWANK:LOAD-FILE
                                    SWANK:SLDB-BREAK-WITH-DEFAULT-DEBUGGER
                                    SWANK:TOGGLE-DEBUG-ON-SWANK-ERROR
                                    SWANK:PACKAGE= SWANK:SIMPLE-COMPLETIONS
                                    SWANK:SLDB-NEXT SWANK:COMPLETIONS
                                    SWANK:ARGLIST-DISPATCH
                                    SWANK:SDLB-PRINT-CONDITION
                                    SWANK:SWANK-MACROEXPAND-1
                                    SWANK:FIND-DEFINITION-FOR-THING
                                    SWANK:COMPILE-FILE-FOR-EMACS
                                    SWANK:DESCRIBE-SYMBOL SWANK:AUTODOC
                                    SWANK:LOOKUP-PRESENTED-OBJECT-OR-LOSE
                                    SWANK:EVAL-STRING-IN-FRAME
                                    SWANK:INSPECT-PRESENTATION SWANK:SLDB-OUT
                                    SWANK:VALUE-FOR-EDITING
                                    SWANK:INSPECT-FRAME-VAR
                                    SWANK:INTERACTIVE-EVAL-REGION
                                    SWANK:SLDB-DISASSEMBLE SWANK:SIMPLE-BREAK
                                    SWANK:SWANK-EXPAND
                                    SWANK:ASDF-DETERMINE-SYSTEM
                                    SWANK:CONNECTION-INFO
                                    SWANK:EXPORT-SYMBOL-FOR-EMACS
                                    SWANK:OPERATOR-ARGLIST
                                    SWANK:*FUZZY-DUPLICATE-SYMBOL-FILTER*
                                    SWANK:PROFILE-BY-SUBSTRING
                                    SWANK:LIST-ASDF-SYSTEMS
                                    SWANK:FLOW-CONTROL-TEST
                                    SWANK:FRAME-LOCALS-AND-CATCH-TAGS
                                    SWANK:INVOKE-NTH-RESTART
                                    SWANK:SWANK-EXPAND-1
                                    SWANK:EVAL-AND-GRAB-OUTPUT
                                    SWANK:FUZZY-COMPLETION-SELECTED
                                    SWANK:INSPECT-NTH-PART SWANK:XREFS
                                    SWANK:SWANK-DELETE-PACKAGE
                                    SWANK:UNDEFINE-FUNCTION
                                    SWANK:COMMIT-EDITED-VALUE
                                    SWANK:PPRINT-EVAL-STRING-IN-FRAME
                                    SWANK:INSPECTOR-NTH-PART
                                    SWANK:DESCRIBE-FUNCTION
                                    SWANK:EXPORT-STRUCTURE
                                    SWANK:THROW-TO-TOPLEVEL
                                    SWANK:INSPECTOR-REINSPECT SWANK:SLDB-ABORT
                                    SWANK:INIT-PRESENTATIONS
                                    SWANK:SWANK-PROFILE-PACKAGE
                                    SWANK:DEBUGGER-INFO-FOR-EMACS
                                    SWANK:COMPILE-FILE-IF-NEEDED
                                    SWANK:START-SWANK-SERVER-IN-THREAD
                                    SWANK:COMPLETE-FORM SWANK:INSPECTOR-HISTORY
                                    SWANK:INSPECT-CURRENT-CONDITION
                                    SWANK:WHO-DEPENDS-ON
                                    SWANK:QUIT-THREAD-BROWSER
                                    SWANK:SWANK-TOGGLE-TRACE SWANK:PPRINT-EVAL
                                    SWANK:FRAME-PACKAGE-NAME
                                    SWANK:COMPILE-STRING-FOR-EMACS
                                    SWANK:INVOKE-NTH-RESTART-FOR-EMACS
                                    SWANK:FUZZY-COMPLETIONS
                                    SWANK:RE-EVALUATE-DEFVAR
                                    SWANK:QUIT-INSPECTOR
                                    SWANK:DELETE-SYSTEM-FASLS
                                    SWANK:FIND-DEFINITIONS-FOR-EMACS
                                    SWANK:SWANK-MACROEXPAND-ALL
                                    SWANK:RELOAD-SYSTEM SWANK:KILL-NTH-THREAD
                                    SWANK:XREF SWANK:INSPECTOR-RANGE
                                    SWANK:PPRINT-INSPECTOR-PART
                                    SWANK:SET-PACKAGE
                                    SWANK:ASDF-SYSTEM-DIRECTORY
                                    SWANK:APROPOS-LIST-FOR-EMACS
                                    SWANK:LOOKUP-AND-SAVE-PRESENTED-OBJECT-OR-LOSE
                                    SWANK:ASDF-SYSTEM-FILES
                                    SWANK:LIST-ALL-SYSTEMS-KNOWN-TO-ASDF
                                    SWANK:LIST-ALL-SYSTEMS-IN-CENTRAL-REGISTRY
                                    SWANK:DISASSEMBLE-FORM SWANK:MOP
                                    SWANK:SLDB-CONTINUE SWANK:INSPECTOR-POP
                                    SWANK:LOOKUP-PRESENTED-OBJECT
                                    SWANK:LIST-THREADS SWANK:DESCRIBE-INSPECTEE
                                    SWANK:IO-SPEED-TEST
                                    SWANK:SWANK-FORMAT-STRING-EXPAND
                                    SWANK:OPERATE-ON-SYSTEM-FOR-EMACS
                                    SWANK:UPDATE-INDENTATION-INFORMATION
                                    SWANK:COMPLETIONS-FOR-KEYWORD
                                    SWANK:COMPLETIONS-FOR-CHARACTER
                                    SWANK:SWANK-REQUIRE
                                    SWANK:UNEXPORT-SYMBOL-FOR-EMACS
                                    SWANK:INSPECTOR-NEXT
                                    SWANK:ASDF-SYSTEM-LOADED-P
                                    SWANK:UNINTERN-SYMBOL SWANK:PING
                                    SWANK:SWANK-COMPILER-MACROEXPAND
                                    SWANK:INTERACTIVE-EVAL
                                    SWANK:SWANK-COMPILER-MACROEXPAND-1
                                    SWANK:UNTRACE-ALL
                                    SWANK:LIST-ALL-PACKAGE-NAMES
                                    SWANK:CLEAR-REPL-RESULTS
                                    SWANK:TOGGLE-BREAK-ON-SIGNALS
                                    SWANK:INSPECTOR-CALL-NTH-ACTION
                                    SWANK:BACKTRACE SWANK:INSPECTOR-EVAL
                                    SWANK:DOCUMENTATION-SYMBOL
                                    SWANK:INSPECTOR-TOGGLE-VERBOSE
                                    SWANK:SLDB-RETURN-FROM-FRAME)
See also:
  The ANSI Standard, Macro DEFPACKAGE
  The SBCL Manual, Variable *ON-PACKAGE-VARIANCE*
WARNING:
   redefining EMACS-INSPECT (#<SB-PCL:SYSTEM-CLASS COMMON-LISP:T>) in DEFMETHOD
WARNING:
   redefining EMACS-INSPECT (#<SB-PCL:SYSTEM-CLASS COMMON-LISP:T>) in DEFMETHOD
WARNING:
   redefining THREAD-FOR-EVALUATION (#<STRUCTURE-CLASS SWANK::MULTITHREADED-CONNECTION>
                                     #<SB-MOP:EQL-SPECIALIZER :FIND-EXISTING>) in DEFMETHOD
WARNING: redefining SWANK::SYMBOL-INDENTATION in DEFUN
WARNING: redefining SWANK::MACRO-INDENTATION in DEFUN
WARNING: redefining HU.DWIM.DEFCLASS-STAR::PROCESS-SLOT-DEFINITION in DEFUN
STYLE-WARNING:
   Generic function FSET:ITERATOR clobbers an earlier FTYPE proclamation
   (FUNCTION (T &KEY &ALLOW-OTHER-KEYS) (VALUES FUNCTION &REST T)) for the same
   name with (FUNCTION (T &KEY &ALLOW-OTHER-KEYS) *).
WARNING:
   redefining FFI-DISPLAY-URL (#<SB-PCL:SYSTEM-CLASS COMMON-LISP:T>) in DEFMETHOD

CL-USER> (nyxt:start)
<INFO> [11:56:36] Listening to socket "/run/user/1000/nyxt/nyxt.socket".
Nyxt version 2.1.1-226-g8e8b751c
<INFO> [11:56:36] Loading Lisp file "/home/pedro/.config/nyxt/auto-config.lisp".
<INFO> [11:56:36] Loading Lisp file "/home/pedro/.config/nyxt/init.lisp".
NIL
<WARN> [11:56:37] Warning: JavaScript error: invalid number of arguments: 2
<WARN> [11:56:37] Warning: JavaScript error: invalid number of arguments: 2

**Comment by jmercouris** [comment]
Perhaps you updated cl-webkit? In which case you would also have to apply this patch: https://github.com/atlas-engineer/nyxt/pull/1619

we haven't merged it in yet!

**Comment by pdelfino** [comment]
Exactly. I have just updated cl-webkit.

Before updating cl-webkit, I was unable to load Nyxt and this error was being returned:

> Component ASDF/USER::CLSS not found, required by #<SYSTEM "nyxt">

I cannot provide a specific recipe to reproduce this error message because I do not remember exactly what were the conditions and things have changed. Maybe, just looking at it you will figure things out.

Since I saw some changes on cl-webkit, I thought it was the root of the problem. Thus, I updated cl-webkit. After updating cl-webkit, the CLSS message disappeared but other problems arised.

**Comment by jmercouris** [comment]
Well, you'll also need to quickload clss on your system. You can try that and then go from there!

**Comment by pdelfino** [comment]
Ok, Nyxt is back. Thanks for making things clear!

If someone faces the same problem, being on commit [ffb033db](https://github.com/joachifm/cl-webkit/commit/ffb033db602b5df5bd62e26ad446d7d033ae5f75) in [cl-webkit](https://github.com/joachifm/cl-webkit) repository will make things work as expected in Nyxt master commit-id 8e8b751.
