### ISSUE TITLE
Rename ffi-window-remove-panel-buffer to ffi-window-delete-panel-buffer

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#1631]
And `window-remove-panel-buffer` to `window-delete-panel-buffer`.

It would be more consistent with:
- `delete-panel-buffer`
- The CL standard distinction between `delete` and `remove`: `delete` alters existing data, `remove` does not.

@jmercouris ?

**Comment by Ambrevar** [comment]
Fixed with https://github.com/atlas-engineer/nyxt/commit/6a1c6e4325c31933613cbd440372951d51a92cf0, no?

**Comment by jmercouris** [comment]
Correct.
