### ISSUE TITLE
Handling mailto:links

### ISSUE THREAD

**Issue by ag91** [atlas-engineer/nyxt#1634]
Thanks a lot for this amazing piece of software! I am having a lot of fun programming my browsing tool :D 

I decided to check how Nyxt handles mailto links and I find it doesn't: it tries to follow the hyperlink as if it were an url.
Naturally on navigation it cannot find a page mailto:xxx@xxx
To reproduce just try to click [on this link](mailto:somebody-i-dont-know@mail.com) while using Nyxt.

I think I have an idea for where to fix this: https://github.com/atlas-engineer/nyxt/blob/master/source/browser.lisp#L441
Still when I try to override that function in a REPL my definition is not picked up.
If somebody could point me to the place that is handling navigating URLs, I would be happy to open a PR that handles mailto links and let's the user set the program to open.
(Actually, now that I think about it, I could generalize that for other link types with a association list `(("mailto" "my mail program") ("other-protocol" "other program"))`

Thanks again for your work!

**Comment by Ambrevar** [comment]
From the user config, new scheme handlers can be added via `request-resource-hook`.

But we could and probably should make it more accessible, e.g. via a scheme -> handler map.  I suggest adding such a map to `preprocess-request`, after all this is where we currently process the `lisp://` URLs.
We would need to deduplicate some code with `buffer-load`.

Thoughts?  @jmercouris @aartaka

**Comment by aartaka** [comment]
There's also a `url-dispatching-handler`. 

The current state feels OK, only a bit underdocumented. I don't see much use in adding such a map -- it's another level of indirection for a minor config simplification. Having good configuration examples would work better here.

**Comment by Ambrevar** [comment]
But shouldn't we provide a default behaviour for schemes such as
`mailto`?  If so, where would we set this behaviour?  `preprocess-request`?

`url-dispatching-handler` can only be used from the user config.

**Comment by ag91** [comment]
Ah! Indeed that seems just what I need. I was wondering the same as @Ambrevar: if the user is supposed to customize as much as possible, should we provide some basic configuration for the new users? I like the autoconfig mechanism, and I guess we could have a button to set a general basic configuration. It may be a bit opaque, but make it easier to setup for new users? Too many options in the autoconfig would also make things opaque, I think.

**Comment by ag91** [comment]
> There's also a `url-dispatching-handler`

For reference this code solves my issue for Emacs users (tested with a Mu4e setup):
``` lisp
(define-configuration buffer
  ((request-resource-hook (reduce #'hooks:add-hook
                                  (list ;; see docs of request-resource-hook for more hooks
                                        (url-dispatching-handler
                                         'emacs-mail
                                         (match-scheme "mailto")
                                         "/usr/bin/emacsclient --eval '(browse-url-mail \"~a\")'"
                                         ))
                                  :initial-value %slot-default%))))
```

**Comment by jmercouris** [comment]
I agree with Artyom's assessment, this is a documentation issue.

**Comment by jmercouris** [comment]
That said, Pierre's argument for default behavior is compelling...!

**Comment by Ambrevar** [comment]
Have you people thought through this issue?
Should Nyxt provide sane defaults for various schemes?

**Comment by aartaka** [comment]
We already do `xdg-open`, so yes, defaults for some schemes do make sense.

**Comment by Ambrevar** [comment]
The quick and easy way would be to have our request-resource-hook
include a default handler that handles some schemes like `mailto:`.  But
this may break some user configs.

Otherwise, as I suggested above, we can add a configurable knob to
`preprocess-request`.

**Comment by PhilHudson** [comment]
I like the Conkeror approach:

modules/utils.js
652: * set_protocol_handler takes a protocol and a handler spec.  If the
661:function set_protocol_handler (protocol, handler) {

Used thus:

    set_protocol_handler("mailto", find_file_in_path("my_mail"));

Where the `my_mail` file is my own custom script that does some URI cleanup and tailoring before launching my MUA.

Reading the above thread, the top relevant match in a DDG search for 'nyxt protocol handler', as a Nyxt newbie, I'm still not sure what I need to do where in order to duplicate this. A similar one-liner in `init.lisp` or `auto-config.lisp` would be ideal.

**Comment by PhilHudson** [comment]
Sorry @Ambrevar, I should use `%slot-default%`...?

**Comment by jmercouris** [comment]
That's correct `%slot-default%` is the new way of representing the default slot value.
