### ISSUE TITLE
Documentation: create a section about Automation covering multiple commands (`cruise-control`, `repeat-mode`, `watch-mode`, `process-mode` , and others)

### ISSUE THREAD

**Issue by pdelfino** [atlas-engineer/nyxt#1636]
This is a powerful command and useful not only for reading long articles, as discussed [here](https://github.com/atlas-engineer/nyxt/issues/1603) it can be handy to achieve the bottom of web pages behaving like a stream (e.g., all tweets from a specific user). 

The manual should also indicate how granular the speed control can be with `velocity-incf` and `velocity-decf`.  Their use gets especially comfortable with the use of the associated keybindings.

**Comment by jmercouris** [comment]
Agreed. This would be a good addition. Perhaps the manual should automatically list all modes and what they do? Could we not somehow gather the documentation from all modes, and all of their commands and automatically group them in the manual?

**Comment by Ambrevar** [comment]
But shouldn't we have a `describe-mode` command instead?  An auto-generated manual seems like the wrong thing to do.

**Comment by edgar-vincent** [comment]
I agree with Pierre. I think there should be a `describe-mode` command like in Emacs. However, most, if not all, modes should be mentioned in the manual. The latter should be comprehensive as far as user-facing modes are concerned. Users look for a feature, not a mode name. Users unfamiliar with Nyxt have no idea what `application-mode` is, and I don't think they should have to look up each mode's docstring in order to find which ones they might need. It is preferable for them to be able to look in up in the manual.

**Comment by jmercouris** [comment]
I concur with Alex!

**Comment by Ambrevar** [comment]
> Users unfamiliar with Nyxt have no idea what `application-mode` is,
> and I don't think they should have to look up each mode's docstring in
> order to find which ones they might need.

Note that `execute-command` displays the docstring next to the command,
so in this case it's really easy to understand what application-mode is,
without looking at the manual.

Keep in mind that we need to strike the right balance between
explorable, dynamic documentation and a walkthrough (the manual).

Too much stuff in the walkthrough would make it less accessible and
increase the chances of going out-of-sync and writing inaccurate documentation.

**Comment by edgar-vincent** [comment]
> Note that `execute-command` displays the docstring next to the command, so in this case it's really easy to understand what application-mode is, without looking at the manual.

It does, but how does one find out that the mode one is looking for is `application-mode`? The docstring, while helpful, has to be kept short: in this case, it is: `Mode that forwards all keys to the renderer.`. I doubt that one would be able to stumble upon it by searching terms included in it. For instance, both Kabouik and I follow the development of Nyxt closely, and neither of us found out about it without asking other users.

> Keep in mind that we need to strike the right balance between explorable, dynamic documentation and a walkthrough (the manual). Too much stuff in the walkthrough would make it less accessible and increase the chances of going out-of-sync and writing inaccurate documentation.

You are right. Perhaps the documentation about the different modes should not be included in the manual, but in a separate file/buffer?

**Comment by jmercouris** [comment]
It should be in the manual, but as a collapsible list, a reference at the end! Thoughts?

**Comment by Ambrevar** [comment]
What would be the benefit compared to a `describe-mode` command?

**Comment by edgar-vincent** [comment]
Maybe you have something else in mind, but in Emacs, `describe-mode` only describes the enabled modes.

**Comment by Ambrevar** [comment]
Prompt-buffer for the win!

In Nyxt, we can list all modes and pre-select the currently enabled
modes.  Multi-selection is a bliss!

**Comment by jmercouris** [comment]
The benefit would be that the users who click `manual`, expect to see a list of all of the modes there. This is the same reason we have a command called `manual` and not `tomato-recipes` that links to the manual. It is about putting things where the user can expect to find them :-D

**Comment by edgar-vincent** [comment]
Indeed! That would be very cool. However, I still think a more accessible list of features/modes would be good as well.

**Comment by Ambrevar** [comment]
> The benefit would be that the users who click `manual`, expect to see a list of all of the modes there. This is the same reason we have a command called `manual` and not `tomato-recipes` that links to the manual. It is about putting things where the user can expect to find them :-D

Sorry, I'm confused.

Why would the user expect to see the list of modes in the manual?

Maybe we have different expectations of what the manual should do.

You seem to imply it should be exhaustive.  If so, I disagree: listing
all modes, all commands, etc. would only be redundant with what the
dynamic documentation already provides.  Plus it would add a lot of
clutter to the manual and distract the reader from where the manual
really shines: being a walkthrough.

The manual sections are organized around various themes, such as
bookmarks, customization, navigation, etc.  Modes are thus split across
these themes.  A list of modes would lose this sectioning.

**Comment by pdelfino** [comment]
I agree with Pierre's argument.

> Plus it would add a lot of clutter to the manual and distract the reader from where the manual really shines: being a walkthrough. The manual sections are organized around various themes, such as bookmarks, customization, navigation, etc. Modes are thus split across these themes. A list of modes would lose this sectioning.

Sectioning is really didactic. And, actually, I think it could be like way more rich than what we have now in tutorial.

Nyxt already has many features available. I have been using it almost daily for > 8 weeks and I am still getting surprised and finding new things.

There are possibly many unexplored and **creative** ways to explain Nyxt as a walkthrough for new users blending modes, and commands together in a section, for instance. The suggested automatic list of modes will not address this.

**Comment by pdelfino** [comment]
I have just updated the title. If my understanding of the comments on this issue and on issue #1637 is correct, we should create a **section** on the tutorial about **Automation**.

It could have a similar style and purpose to the section *Copying and Pasting* already on master, id. est. laconic definitions clustering Nyxt's features that share a similar scope of application.

The *Automation*'s section in the tutorial is hugely important considering Nyxt's value proposition of **power**. Thus,  the following commands/modes should be covered (imho):

- `process-mode`;
- `repeat-mode`;
- `cruise-control-mode`;
- `watch-mode`;
- `repeat-every`;
- `toggle-all-check-boxes`;
- `macro-edit` (this one is new and even more powerful);
- `bookmark-frequent-visits-mode` (still under development, but soon merged - hopefully);

Artyom's [article](https://nyxt.atlas.engineer/article/process-mode-and-repeat-mode.org) and John's [article](https://nyxt.atlas.engineer/article/macro-edit.org) can be both be used as references or inspiration.

Did I forget some command/mode? Would you remove any of them?

I will send a patch about this soon.

**Comment by Ambrevar** [comment]
Looks all good to me! :)

**Comment by pdelfino** [comment]
Since PR #1704 was merged, I am closing this issue.
