### ISSUE TITLE
Documentation: manual should cover `repeat-mode`

### ISSUE THREAD

**Issue by pdelfino** [atlas-engineer/nyxt#1637]
This command can be useful in creative ways. As stated [here](https://nyxt.atlas.engineer/article/process-mode-and-repeat-mode.org), `cruise-control-mode` and `watch-mode` are both extensions of `repeat-mode`.

I think the manual could go a little bit beyond the docstring, mentioning these extensions so that users could be inspired to create new modes, and, finally, include  at least 1 or 2 creative/useful examples of raw `repeat-mode` use. 

Example #1  -   `repeat-mode` and `scroll-to-bottom` in a web page that behaves like a stream (e.g., seeing all tweets from a Twitter user). 

Example #2 - suggestions are welcome.

**Comment by Ambrevar** [comment]
Same as #1636, no?

**Comment by pdelfino** [comment]
> Same as #1636, no?

Well, I guess it is possible to cover only `repeat-mode` on manual. Or, it is possible to write on manual about `repeat-mode` and `cruise-control-mode` which is an extension.

I guess it depends on how thorough you guys think the tutorial should be.

**Comment by Ambrevar** [comment]
I don't think it belongs to the tutorial :p

I suppose that we could embed part of @aartaka's article in the manual
as a section on automatization.  Then both repeat-mode and
cruise-control-mode would be mentioned there.

**Comment by pdelfino** [comment]
Closing this issue in favor of #1636 .
