### ISSUE TITLE
Documentation: manual should cover dark-mode, and briefly mention its peculiarity concerning the disable process

### ISSUE THREAD

**Issue by pdelfino** [atlas-engineer/nyxt#1638]
The discussion [here](https://github.com/atlas-engineer/nyxt/issues/1575) motivated this issue.

The disabling process involves re-loading the page. This was a tricky point for at least 2 users (myself and @Kabouik) and an exception in comparison to other commands. Thus, I think the manual should mention it.

**Comment by Ambrevar** [comment]
This might be too specific for the manual.  I'd rather add this peculiarity to the dark-mode docstring.

**Comment by pdelfino** [comment]
I am closing this issue since the suggestions have now been merged with PR #1650.
