### ISSUE TITLE
Feature request: create commands `go-up` and `go-homepage` to improve Nyxt as a doc overview tool

### ISSUE THREAD

**Issue by pdelfino** [atlas-engineer/nyxt#1643]
A few days ago (maybe 10 days), user @mariari was talking about their use of Nyxt as a documentation overview tool in the IRC channel.

It was mentioned how useful the command `jump-to-heading` was. I feel the same. I have been using GNU manuals a lot with Nyxt.

Actually, I have been using `go-next` and `go-previous` too. Not sure if @mariari already tested those "new" commands.

`go-next` and `go-previous` were suggested by @jellelicht based on his experience with Vimium.

Vimium also has 2 other commands that would be useful for me in Nyxt:

```
gu      go up one level in the URL hierarchy
gU      go up to root of the URL hierarchy

```

They could be new Nyxt commands as `go-up` and `go-root`. I think this would be a low-hanging fruit for me considering the previous effort with parenscript.

**Comment by pdelfino** [comment]
After talking with @jmercouris, he endorsed the idea of this feature request. He just suggested using `try-to-go-home` instead of `go-root`.

**Comment by Ambrevar** [comment]
I don't understand try-to-go-home, what is "home"?
Also why "try"?

**Comment by pdelfino** [comment]
Oh, sorry for not being clear, Pierre.

The command `try-to-go-home` would navigate to the "most basic URL on that domain". Usually, this is the **home page**. Vimium calls this the **root** in URL hierarch (which seems to be technically imprecise).

For instance, suppose you are at [https://ambrevar.xyz/articles.html](https://ambrevar.xyz/articles.html). After invoking `try-to-go-home`, the buffer would navigate to [https://ambrevar.xyz/](https://ambrevar.xyz/). The string "articles.html" would be removed.

In general, this "basic address" (root in URL hierarchy) is the **home page**. Unfortunately, some websites use other patterns as home pages, such as domain-name/index.html.

> I don't understand `try-to-go-home`, what is "home"? Also why "try"?

"home" -> homepage
"try" -> in general, it does take you to the homepage, but sometimes it does not take you to the homepage

We were insecure about the name. Home seems to be widely used as a shortcut for the homepage. Do you have a better suggestion?

`try-to-go-homepage` would be better?  `maybe-go-to-homepage`? `probably-go-to-homepage`?

**Comment by Ambrevar** [comment]
I prefer "go-root" or "go-homepage".

About "try": why doesn't it take you to the homepage?
If it's because we are already visiting the homepage, that's fine, I
don't think the "try" is necessary.
Following that logic, we could have added "try" to all commands that
have exceptions :p

**Comment by jmercouris** [comment]
`go-to-homepage` then it is!

**Comment by pdelfino** [comment]
Since PR #1673 was merged, I am closing this issue.
