### ISSUE TITLE
Delete data-manager cache on buffer deletion?

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#1645]
If you look into ~/.cache/nyxt, you'll see a bunch of `nyxt-data-manager-N` directories, with `N` being a buffer ID.

It seems that we are never deleting these directories and they tend to grow rather big (the sum in the ballpark of hundreds of MiB).

Something else: when creating a buffer with an ID that matches an existing directory, we tell WebKitGTK to reuse this directory.  Is this the right thing to do?

We could delete the cache on buffer deletion.  Would we lose some cache optimization then?

**Comment by jmercouris** [comment]
Could this be why we are experiencing frequent logouts on Nyxt?

**Comment by Ambrevar** [comment]
Oh!  Yes!  Good point!
If only we had a reproducible way to verify this!

**Comment by aartaka** [comment]
Reusing existing directory doesn't sound right -- after all, the session might be totally different and user might expect cookies to not exist at all, for example.

Deleting the the cache sounds right for me. Better err on the side of caution and free all the resources used :)

**Comment by Ambrevar** [comment]
We've been looking at this issue the wrong way: a _missing_ cache is
what causes the apparent disconnect when switching buffers.

In commit 88d0c5e3757f25566d0a2fe52db006402ae33138 @aartaka implement
per-buffer data storage.  This change included per-buffer data-manager
storage, but after a second look it seems that we should not do this by
default.

It's a great option to have for users who want to separate data-manager
storage, say, on a per-domain basis.  But by default we should store
everything in the same directory, shouldn't we?

Thus I suggest the following patch in renderer-gtk.lisp:

```diff
 (defmethod initialize-instance :after ((buffer gtk-buffer) &key)
-  (let ((path (data-manager-path buffer)))
-    (when (id buffer)
-      (setf (data-manager-path buffer)
-            (make-instance 'data-manager-data-path
-                           :dirname (pathname (str:concat (namestring (dirname path))
-                                                          "/nyxt-data-manager-"
-                                                          (id buffer)))))))
   (ffi-buffer-make buffer))
```

Thoughts?

**Comment by Ambrevar** [comment]
Maybe we should set the default dir of the data manager to `~/.cache/nyxt/data-manager/`.  Something like

```lisp
(define-class data-manager-data-path (data-path)
  ((dirname (uiop:xdg-cache-home +data-root+ "data-manager"))
   (ref "data-manager"))
  (:export-class-name-p t)
  (:accessor-name-transformer (hu.dwim.defclass-star:make-name-transformer name)))
```

**Comment by aartaka** [comment]
Fair ideas, both with removing per-buffer data-managers (although I feel somewhat wrong about it -- there were reasons to make it buffer-local, I guess) and moving things to `~/.cache/`!

**Comment by Ambrevar** [comment]
From the git log, the reason to make it buffer-local as far as I
understand was to pave the way for nosave mode.  The reasoning was that
we had to make everything buffer-local (download-path, etc.).

But since the data-manager is a buffer slot, it is buffer-local anyways
so the user can customize it to their needs.

Note that the data-manager cache is already in `~/.cache/nyxt`, I'm only
suggesting to use a singe directory.
