### ISSUE TITLE
Feature Request: Password hasher

### ISSUE THREAD

**Issue by swedebugia** [atlas-engineer/nyxt#165]
Hi :)

I use [password hasher](https://milliways.cryptomilk.org/passhash.html) extensively. Thus a browser without a password hash function is worthless in my world as it makes logging in to all the places too cumbersome.

Password Hasher is free software from 2015. The JS code for generating the hash is here: https://github.com/renatolfc/quantum-hasher/blob/master/js/passhash-common.js, python and nodejs port here: https://github.com/renatolfc/quantum-hasher/tree/master/tools

I like this specific password hasher implementation because: it is avaliable in chrome & firefox in all versions and is quite widely used it seems.

In short: 
it computes the site-tag by stripping the url to basename-url: e.g. "gitlab.com"
it enables bumping by adding ":1" to the site-tag.
it takes a master password
it computes a b64_hmac_sha1 hash based and cut the string-length to the first x characters. (default is now 16 in newer implementations but was 8 before.)
Based on the settings of restrictions it injects digits, punctuation, and adjust case)
Very rarely I encountered a site requiring at least 2 digits or 2 punctuations which it does not support.

Because various sites have various password requirements the original implementation implemented the following:
Requirements
￼ Digit
￼ Punctuation
￼ Mixed Case
Restrictions
￼ No Special
￼ Digits Only

<script language="JavaScript" type="text/javascript">

var browser = new Object();
browser.version = parseInt(navigator.appVersion);
browser.isNetscape = false;
browser.isMicrosoft = false;
if (navigator.appName.indexOf("Netscape") != -1) 
    browser.isNetscape = true;
else if (navigator.appName.indexOf("Microsoft") != -1)
    browser.isMicrosoft = true;

var siteTagLast = '';
var masterKeyLast = '';

function onLoad()
{
    if (browser.isMicrosoft)
    {
        document.getElementById('reveal').disabled = true;
        document.getElementById('reveal-text').disabled = true;
    }
    document.getElementById('site-tag').focus();
    setTimeout('checkChange()',1000);
}

function validate(form) 
{
    var siteTag   = document.getElementById('site-tag');
    var masterKey = document.getElementById('master-key');
    if (!siteTag.value)
    {
        siteTag.focus();
        return false;
    }
    if (!masterKey.value)
    {
        masterKey.focus();
        return false;
    }
    return true;
}

function update() 
{
    var siteTag   = document.getElementById('site-tag');
    var masterKey = document.getElementById('master-key');
    var hashWord  = document.getElementById('hash-word');
    var submit    = document.getElementById('submit');
    if (submit.value == 'Another')
    {
        siteTag.focus();
        submit.value = 'OK';
        hashWord.value = '';
    }
    else
    {
        //var hashapass = b64_hmac_sha1(masterKey.value, siteTag.value).substr(0,8);
        var hashWordSize       = 8;
        var requireDigit       = document.getElementById("digit").checked;
        var requirePunctuation = document.getElementById("punctuation").checked;
        var requireMixedCase   = document.getElementById("mixedCase").checked;
        var restrictSpecial    = document.getElementById("noSpecial").checked;
        var restrictDigits     = document.getElementById("digitsOnly").checked;
        if      (document.getElementById("s6" ).checked) hashWordSize = 6;
        else if (document.getElementById("s8" ).checked) hashWordSize = 8;
        else if (document.getElementById("s10").checked) hashWordSize = 10;
        else if (document.getElementById("s12").checked) hashWordSize = 12;
        else if (document.getElementById("s14").checked) hashWordSize = 14;
        else if (document.getElementById("s16").checked) hashWordSize = 16;
        else if (document.getElementById("s18").checked) hashWordSize = 18;
        else if (document.getElementById("s20").checked) hashWordSize = 20;
        else if (document.getElementById("s22").checked) hashWordSize = 22;
        else if (document.getElementById("s24").checked) hashWordSize = 24;
        else if (document.getElementById("s26").checked) hashWordSize = 26;
        hashWord.value = PassHashCommon.generateHashWord(
                siteTag.value,
                masterKey.value,
                hashWordSize,
                requireDigit,
                requirePunctuation,
                requireMixedCase,
                restrictSpecial,
                restrictDigits);
        hashWord.focus();
        submit.value = 'Another';
    }
    siteTagLast = siteTag.value;
    masterKeyLast = masterKey.value;
}

**Comment by Ambrevar** [comment]
Just to be clear: what would you like from Next?

**Comment by swedebugia** [comment]
Good question Pierre :)
I would like to know if it is possible to make a plugin that provides this functionality (to hash passwords in password input fields).
Are there any plugins at the moment? 
Would it be practical/possible to write the plugin in Guile? (I never used common lisp before).

**Comment by Ambrevar** [comment]
This should be quite easy to implement indeed!

Next is a regular Common Lisp application, and as it accepts extensions as regular Common Lisp packages!  Which is extremely powerful, obviously! :)

Common Lisp will be quite familiar if you know Guile, and even more so if you know Emacs.
To get started, have a look at Next's own code.  It's short and it should be quite readable.

To go further, have a look at https://lispcookbook.github.io/cl-cookbook/.

You can start implementing your own functions / commands in `~/.config/next/init.lisp`.

I see two possible approaches to this problem:

- Either you pass the JavaScript you've quoted _as is_ to the "platform port", it should work directly,

- or, if you want to be more "lispy", you fetch/set some values with Parenscript (
https://common-lisp.net/project/parenscript/), then implement the algorithm in Common Lisp, then set the result with Parenscript again.

I suggest you go with the first approach as a first step, then we can work on the second later :)

Let me know if you need more help!

**Comment by Ambrevar** [comment]
A quick lookup gave me this: http://quickdocs.org/cl-pass/
It does not seem to be exactly what you want, be it could get you started :)

There is also http://quickdocs.org/cl-password-store/, a wrapper to 
https://www.passwordstore.org/.

**Comment by vindarel** [comment]
We now support KeypassXC and Pass, do they fill your need?

**Comment by Ambrevar** [comment]
The password hasher described here is a bit different.  I think it's
worth integrating as well as some point.
