### ISSUE TITLE
"WebKitJavascriptError", Code: 699, Message:

### ISSUE THREAD

**Issue by flusq** [atlas-engineer/nyxt#1657]
When I try to start video on youtube, nyxt sends me to adobe:blank

In logs: error
    <WARN> [02:38:53] Warning: Web process crashed for buffer 2
    <WARN> [02:38:53] Warning: JavaScript error: GError: Domain:
    "WebKitJavascriptError", Code: 699, Message:
    <INFO> [02:38:53] Loading "about:blank".

Info:
~>nyxt  --system-information
Nyxt version: 2.1.1
Renderer version: GI-GTK
Operating system kernel: Linux 5.12.14
Lisp implementation: SBCL 2.1.6
Features: (WEBKIT2 WEBKIT2-2.32 WEBKIT2-PASTE-PLAINTEXT WEBKIT2-TRACKING WEBKIT2-MUTE
 WEBKIT2-EMOJI WEBKIT2-MEDIA WEBKIT2-SANDBOXING GTK-3-22 GTK-3-20 GTK-3-18
 GTK-3-16 GTK-3-14 GTK-3-12 GTK-3-10 GTK-3-8 GTK-3-6 GTK-3-4 GTK GDK-3-22
 GDK-3-20 GDK-3-18 GDK-3-16 GDK-3-14 GDK-3-12 GDK-3-10 GDK-3-8 GDK-3-6 GDK-3-4
 CAIRO-1-10 CAIRO-1-12 GDK-PIXBUF GLIB-2-30 GLIB-2-32 GLIB-2-34 GLIB-2-36
 GLIB-2-38 GLIB-2-40 GLIB-2-42 GLIB-2-44 GLIB-2-46 GLIB-2-48 GLIB-2-50
 GLIB-2-52 GLIB-2-54 GLIB-2-56 GLIB-2-58 GLIB NYXT-2 FSET-EXT-STRINGS
 CUSTOM-HASH-TABLE-NATIVE SWANK PLUMP-UTF-32 GLOBAL-VARS DECLARE-TYPES
 PARENSCRIPT NAMED-READTABLES 21BIT-CHARS CHUNGA FLEXI-STREAMS CLOSER-MOP
 CL-PPCRE-UNICODE CL-UNICODE CL-PPCRE BORDEAUX-THREADS SPLIT-SEQUENCE
 GRAY-STREAMS FLAT-NAMESPACE X86-64 UNIX CFFI FLAT-NAMESPACE SEQUENCE-EMPTYP
 FAST-IO-SV FAST-IO SBCL-USES-SB-ROTATE-BYTE CL-JSON-CLOS CL-JSON
 THREAD-SUPPORT ASDF3.3 ASDF3.2 ASDF3.1 ASDF3 ASDF2 ASDF OS-UNIX
 NON-BASE-CHARS-EXIST-P ASDF-UNICODE X86-64 GENCGC 64-BIT ANSI-CL COMMON-LISP
 ELF IEEE-FLOATING-POINT LINUX LITTLE-ENDIAN PACKAGE-LOCAL-NICKNAMES
 SB-CORE-COMPRESSION SB-LDB SB-PACKAGE-LOCKS SB-THREAD SB-UNICODE SBCL UNI

**Comment by jmercouris** [comment]
The problem appears to be: 

```
     [02:38:53] Warning: Web process crashed for buffer 2
```

do you have all of the lib-gst plugins installed for media?

**Comment by flusq** [comment]
@jmercouris 
I have guix gst-libav and gstreamer packages

**Comment by Ambrevar** [comment]
@flusq Some of the system information is missing, could you report it all?
What's your OS and how did you install Nyxt?

If you are using Guix, try the following plugins:

gst-libav
gst-plugins-bad
gst-plugins-base
gst-plugins-good
gst-plugins-ugly

**Comment by flusq** [comment]
@Ambrevar 
Thanks! I install all gst packages, and its work!

**Comment by Ambrevar** [comment]
Thanks for the update. Don't forget to check out the manual, it has a
troubleshooting section which include this exact issue :)

**Comment by jmercouris** [comment]
Perhaps we should include a link to the manual on the messages page?

**Comment by Ambrevar** [comment]
You mean the `*Messages*` buffer?  Then it would only forward the
problem to another buffer, since we can't assume that everyone is
reading this buffer.

**Comment by jmercouris** [comment]
Yes, some may look at stdout. Still, some will look at the messages buffer when they have a problem, and a link to the manual may invite them to click it at that time.

**Comment by Ambrevar** [comment]
Fair enough, does not cost much after all.

**Comment by Ambrevar** [comment]
Done with 71980027f1892f989c24bcd962d42e2fd41bf597.
