### ISSUE TITLE
Naming: use hyphenating convention in command names pre-fixed with `no`, e.g.: changing from `nosound` to `no-sound`

### ISSUE THREAD

**Issue by pdelfino** [atlas-engineer/nyxt#1660]
Currently, Nyxt has as command names:
- `nowebgl-mode`;
- `nosound-mode`;
- `noimage-mode`;
- `noscript-mode`;

Maybe, I missed something valuable about this approach, but it seems to be inconsistent with the Common Lisp conventions on [naming](https://www.cliki.net/naming+conventions) and inconsistent with everything else in Nyxt. 

Even the predicates in Nyxt's source code are written as `foo-p` although in classical books they use `foop`. [1] 

Thus, I would suggest using **hyphenating**:

- `nowebgl-mode` -> `no-webgl-mode`;
- `nosound-mode` -> `no-sound-mode`;
- `noimage-mode` -> `no-image-mode`;
- `noscript-mode` -> `no-script-mode`;

I would be glad to send a patch. The case of `noop` is special and treated [here](https://github.com/atlas-engineer/nyxt/issues/1659).

[1] - By the way, I think `foo-p` is better :smile: . hyphenating rocks :guitar:

**Comment by Ambrevar** [comment]
Fair to me.

@jmercouris @aartaka?

**Comment by Ambrevar** [comment]
Issues #1660 #1659 and #1658 could have been just one issue ;)  It's also helpful to gather things that belong together and not clutter the issue tracker too much :)

**Comment by aartaka** [comment]
I prefer the no-hyphen version more here. It looks and reads shorter without the pause hyphen introduces. In case with `noscript` and `nosound` it's even a valid piece of language.

**Comment by Ambrevar** [comment]
You mean "nosound" is in the English dictionary?

Can't find it :p
https://en.wiktionary.org/wiki/Special:Search?search=nosound&ns0=1

**Comment by jmercouris** [comment]
I am ambivalent, I don't think the success of Nyxt hinges upon the presence of hyphens. :-D

**Comment by pdelfino** [comment]
> Issues #1660 #1659 and #1658 could have been just one issue ;) It's also helpful to gather things that belong together and not clutter the issue tracker too much :)

Interesting. It was actually harder for me to split things. It would have been easier for me to write just one.

I was reading about good practices in FOSS and the recommendation was to try splitting things into atomic/independent and small changes.

It turns out, you guys said kind of a "yes" for all of suggestions. But since they are different, you could have said "no" to one or two without affecting the other. 

Then, the PR would also be decomposed with **small** branches only aiming each issue that received a "yes" for the suggestions. Then, there would be pointers in PR text mentioning the issues and et cetera.

I guess this might be more critical in projects with thousands of contributors. Or the advice I read might be based on personal/subjective grounds.

I will follow your guideline from now on.

**Comment by pdelfino** [comment]
> I am ambivalent, I don't think the success of Nyxt hinges upon the presence of hyphens. :-D

Honestly, I was insecure about suggesting this. I have mixed feelings, questioning myself if I was being picky or unproductively detail-oriented. Not sure if I would suggest something like that in other projects.

But, the source code shows a concern with software aesthetics (which is cool). Considering the value proposition of Nyxt, it is expected that users will read the code (which is rare). Also, the code reviews on PRs have pretty high standards in details like this. 

Thus, I thought it would just keep the bar high not just for new code, but for code that already exists.

**Comment by Ambrevar** [comment]
> I was reading about good practices in FOSS and the recommendation was to try splitting things into atomic/independent and small changes.

This is true of commits, but necessarily of discussions.
Especially for simple ones :)

> It turns out, you guys said kind of a "yes" for all of suggestions. But since they are different, you could have said "no" to one or two without affecting the other. 

We can also say "yes no yes" in one discussion, it's fine to discuss a list
of things.

Note that GitHub allows for extended Markdown, for instance you can
write

```
- [ ] Task 1
- [x] Task 2
```

and GitHub will appropriately display the 1/2 tasks have been completed.

> I guess this might be more critical in projects with thousands of contributors. Or the advice I read might be based on personal/subjective grounds.

Not just this, bear in mind that we have hundreds of issues that are
currently opened, and we are only a handful of people who are addressing
them.

Thanks!

**Comment by aartaka** [comment]
> You mean "nosound" is in the English dictionary? Can't find it :p https://en.wiktionary.org/wiki/Special:Search?search=nosound&ns0=1

I mean that "noscript" is not there either, but it, for example, is a valid slang. I'm not extremely sure about "nosound", but I have sure read something like that a couple of times.

**Comment by pdelfino** [comment]
I am closing this issue since the suggestions have now been merged with PR #1665 .
