### ISSUE TITLE
Typo in article

### ISSUE THREAD

**Issue by franburstall** [atlas-engineer/nyxt#1664]
**Describe the bug**

I am not sure this is the right venue for this (if not, tell me what is!) but the latest version of the article /Hooks in practice/ has two occurrences of the old `%slot-default` instead of the modern `%slot-default%`.

**Comment by Ambrevar** [comment]
@jmercouris True, we don't have a dedicated place for contributions to our website.
Ideally, we would open it up, what do you think?

**Comment by Ambrevar** [comment]
@franburstall Thanks for reporting the issue, I've just fixed it!

**Comment by jmercouris** [comment]
Ideally we would open it up? Release the source of the website? I don't believe that will be possible. There are too many secrets we have to keep in the repository.

**Comment by Ambrevar** [comment]
Ideally the public facing parts of the website should be decomposed from
the private parts.

In other words, the code and the content should be separate from the
database and other private data.

**Comment by jmercouris** [comment]
I also don't see why we should. This situation comes up very rarely.

**Comment by Ambrevar** [comment]
We could have more people contributing articles for instance.

**Comment by pdelfino** [comment]
> We could have more people contributing articles for instance.

I think this is true. Probably, more people see stuff. It is just too much friction to let the maintainers know.

There is a web-based book called [Beautiful Racket](https://beautifulracket.com/stacker/intro.html) that did a cool thing for this problem. We could use it as a benchmark.

There is a flag icon next to each paragraph. If you spot a mistake, you click on it and a small box with the comment is opened. Thus, you just need to type the error. I guess a tiny vanilla JS would do the trick.
