### ISSUE TITLE
prompt-buffer: do-what-I-mean selection position during a single update

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#1666]
It's OK to reset the current suggestion when the input changes, but we can do better: if the new input includes the former current suggestion, it should be re-set if the user hasn't changed it in the mean time.

Conversely, some suggestion updates may be slow for a single input change and take multiple "cycles".  In this case, the user should be able to set the current suggestion while the suggestions are still updating, and each update cycle should not change the current suggestion.

**Comment by aadcg** [comment]
If I understood this correctly, we already provide this feature. See the clip below.


https://github.com/atlas-engineer/nyxt/assets/45483512/f05a9913-c4eb-4ffc-9d50-592f45806abc

**Comment by Ambrevar** [comment]
I'ts not about marking but about the current selection.

**Comment by aadcg** [comment]
I'll update the original post with the new prompt buffer terminology.
