### ISSUE TITLE
Setting Title for Nyxt Windows

### ISSUE THREAD

**Issue by joshcho** [atlas-engineer/nyxt#1667]
Is there a way to set window title on Nyxt browser?
For instance, with alacritty and emacsclient, I can do:
`alacritty -t myterm`
or
`emaccsclient -c --frame-parameters='(quote (name . "myemacs"))`
to set their titles.

I am using this for [NamedScratchpad](https://hackage.haskell.org/package/xmonad-contrib-0.16/docs/XMonad-Util-NamedScratchpad.html) in XMonad. I want to be able to reference Nyxt and toggle its visibility in XMonad.

**Comment by Ambrevar** [comment]
Yes, it's possible on master (and the upcoming 2.2).
See the window `titler` slot.

**Comment by Ambrevar** [comment]
Closing, feel free to reopen if this answer is not satisfactory.
