### ISSUE TITLE
Nyxt cannot open a page if the server's hostname cannot be resolved by DNS protocol.

### ISSUE THREAD

**Issue by shamazmazum** [atlas-engineer/nyxt#1674]
Hi! I use my own multicast DNS system (https://github.com/shamazmazum/zero-dns) for my local network. It works system-wide in conjuction with NSS (name service switch) plugin. Unfortunately nyxt cannot show pages hosted by LAN hosts if I use domain names rather than IP addresses.

Look at this REPL session:

~~~~
CL-USER> (iolib:lookup-hostname "vonbraun.local")
; Evaluation aborted on #<IOLIB/SOCKETS:RESOLVER-NO-NAME-ERROR {102A711DC3}>.
CL-USER> (nyxt::valid-url-p "http://vonbraun.local/")
NIL
CL-USER> (require 'sb-bsd-sockets)
NIL
CL-USER> (sb-bsd-sockets:host-ent-address (sb-bsd-sockets:get-host-by-name "vonbraun.local"))
#(192 168 20 10)
~~~~

As you can see, `get-host-by-name` can resolve hostname `vonbraun.local`, but nyxt says `http://vonbraun.local/` is not a valid URL because iolib cannot resolve it.

**How to reproduce**:
Try to visit a site using a hostname which is not resolvable by DNS protocol (e.g. it can be resolved via mDNS only).

**OS name, graphics card, etc.**
Irrelevant

I am unable to find a portable replacement to `sb-bsd-sockets:get-host-by-name`. Can you suggest something? It can be used instead of `iolib/sockets:lookup-hostname` in `sources/urls.lisp`. If you do not know a portable replacement, I can write a function which uses `sb-bsd-sockets:get-host-by-name` if using SBCL and falls back to `iolib/sockets:lookup-hostname` otherwise.

**Comment by Ambrevar** [comment]
I don't know a good alternative either.

Osicat has `osicat-posix:gethostname`, but
- It would (re-)introduce this difficult-to-package dependency.
- It has other portability issues, since it only works on POSIX.

The simplest course of action seems to be what you suggest.  Wanna send
a pull request?
