### ISSUE TITLE
Element Hints Delay

### ISSUE THREAD

**Issue by jmercouris** [atlas-engineer/nyxt#1676]
**Describe the bug**

When you type in the element hint binding, the hints appear. However, there is often  SIGNIFICANT (3-4 seconds) delay between when the prompt-buffer source gets populated.

**Precise recipe to reproduce the issue**

Visit any page on Wikipedia with a sufficient quantity of links, invoke element hints. Observe the latency.

Please see the attached video.

https://user-images.githubusercontent.com/1691662/127142486-edf4e486-3dfe-4294-b125-f3bff007d13a.mp4

**Comment by jmercouris** [comment]
@aartaka @Ambrevar any ideas why this might be?

**Comment by jmercouris** [comment]
What's really odd is that the constructor finishes the operation sometimes a LONG time before the prompt buffer is updated. I've timed it across many runs.

**Comment by jmercouris** [comment]
Making the following change:

```
(defun add-element-hints (&key selector)
  (let* ((dom (document-model (current-mode 'web)))
         (hintable-elements (clss:select selector dom))
         (hints (generate-hints (length hintable-elements)))
         )
    (run-thread "stylesheet adder"
      (add-stylesheet))
    (run-thread "element hint drawing"
      (hint-elements (map 'list #'get-nyxt-id hintable-elements) hints))
    (loop for elem across hintable-elements
          for hint in hints
          do (plump:set-attribute elem "nyxt-hint" hint)
          ;; collect elem
          )
    (loop for i from 1 to 10000 collect "tomato")
    ))
```

somehow drastically improves the performance. I do not understand.

**Comment by jmercouris** [comment]
Even the following improves performance:

```
(defun add-element-hints (&key selector)
  (let* ((dom (document-model (current-mode 'web)))
         (hintable-elements (clss:select selector dom))
         (hints (generate-hints (length hintable-elements))))
    (run-thread "stylesheet adder"
      (add-stylesheet))
    (run-thread "element hint drawing"
      (hint-elements (map 'list #'get-nyxt-id hintable-elements) hints))
    (loop for elem across hintable-elements
          for hint in hints
          do (plump:set-attribute elem "nyxt-hint" hint)
          collect elem
          )
    (loop for i from 1 to 10000 collect "tomato")
    ))

```

perhaps it is the automatic creation of the columns or something delaying rendering in the prompt buffer?

**Comment by jmercouris** [comment]
OK, I've reduced a lot of the problem to the object-attribute specializations. `str:` operations are probably not cheap!

**Comment by aartaka** [comment]
Yes, I'm aware of that. Had no chance to profile it in detail, though.

**Comment by jmercouris** [comment]
I will profile, no problem!

**Comment by Ambrevar** [comment]
str:join was slow (got fixed on str master), maybe that's the bottleneck here.

**Comment by jmercouris** [comment]
`str:join` does not appear here, unless it is part of `str:shorten`.

**Comment by jmercouris** [comment]
Removing the usage of str seems to create a small improvement. Something else is going on with this usage of CLOS that is making the call:

```
(defmethod prompter:object-attributes ((a nyxt/dom:a-element))
  (append
   (when (url a)
     `(("URL" ,(url a))))
   (when (nyxt/dom:body a)
    `(("Body" ,(str:shorten 80 (nyxt/dom:body a)))))))

```
super expensive. Whenever I remove this, everything loads infinitely faster.

**Comment by Ambrevar** [comment]
@aartaka We previously discussed a `follow-hint` and we introduce a memoize version of `lookup-hostname`.  Wasn't it enough?

**Comment by aartaka** [comment]
> @aartaka We previously discussed a `follow-hint` and we introduce a memoize version of `lookup-hostname`. Wasn't it enough?

Seems like it wasn't. Several thousand hintable elements (there are often that much) seem to slow things down dramatically.

**Comment by Ambrevar** [comment]
I'll have a look later.
If the issue is with slow object-properties functions, I suggest the
following strategies:

- Return the result in 2 passes:
  - First without calling object-properties
  - Second after having called object-properties.

  This way the user can already see the default display (the first
  column) of all suggestions before the other columns display.

- Alternative strategy: evaluate object-properties lazily.

- Cache the results.
  Or maybe better: memoize them!

**Comment by jmercouris** [comment]
We can't evaluate object-properties lazily, can we? They are used as part of the matching process if I remember correctly.

**Comment by jmercouris** [comment]
So, I've done a little bit more research on this:

```
(sb-profile:report)
  seconds  |     gc     |    consed   | calls |  sec/call  |  name  
---------------------------------------------------------
     2.827 |      0.222 | 209,214,960 | 4,493 |   0.000629 | PROMPTER:OBJECT-ATTRIBUTES
     0.113 |      0.022 |   5,415,392 | 4,502 |   0.000025 | QURI:RENDER-URI
---------------------------------------------------------
     2.939 |      0.244 | 214,630,352 | 8,995 |            | Total

estimated total profiling overhead: 0.01 seconds
overhead estimation parameters:
  5.2180003e-9s/call, 9.83482e-7s total profiling, 5.3332195e-7s internal profiling
; No value
CL-USER> 
```

when you have the following form evaluated:

```
(defmethod prompter:object-attributes ((a nyxt/dom:a-element))
  (append
   (when (url a)
     `(("URL" ,(render-url (url a)))))
   (when (nyxt/dom:body a)
    `(("Body" ,(str:shorten 80 (nyxt/dom:body a)))))))
```

I don't understand what is so expensive about this. I guess a key part is that there are MOSTLY anchor objects, and so as soon as you have a method specializing on them, you have a significant increase in the amount of processing that must be done. I tried substituting `render-url` for `quri:render-uri` with no appreciable difference. The profiler says a very small amount of time is being spent rendering the URI, the same for `nyxt/dom:body`.

```
CL-USER> (sb-profile:report)
  seconds  |     gc     |    consed   |  calls |  sec/call  |  name  
----------------------------------------------------------
     4.284 |      0.247 | 289,729,296 |  4,493 |   0.000954 | PROMPTER:OBJECT-ATTRIBUTES
     0.082 |      0.000 |   5,471,616 |  4,456 |   0.000018 | QURI:RENDER-URI
     0.044 |      0.000 |   1,901,840 |  8,933 |   0.000005 | NYXT/DOM:BODY
----------------------------------------------------------
     4.411 |      0.247 | 297,102,752 | 17,882 |            | Total

estimated total profiling overhead: 0.02 seconds
overhead estimation parameters:
  5.2180003e-9s/call, 9.83482e-7s total profiling, 5.3332195e-7s internal profiling
; No value
CL-USER> 
```

all in all, I am a little bit stumped!

**Comment by jmercouris** [comment]
Something very suspicious is going on here for sure!

**Comment by Ambrevar** [comment]
Thanks for the detailed report, I'm on it, hopefully I can help rooting
this out.

**Comment by aadcg** [comment]
Is it still an issue @jmercouris?

**Comment by jmercouris** [comment]
This is not an issue! Thank you for the reminder!
