### ISSUE TITLE
Feature request: Extend `command-docstring-first-sentence` to cover modes

### ISSUE THREAD

**Issue by pdelfino** [atlas-engineer/nyxt#1685]
I am trying to solve [this issue](https://github.com/atlas-engineer/nyxt/issues/1636#issuecomment-885888991).

In order to write laconic definitions clustering Nyxt's features that share a similar scope of application, I need to use the handy: `command-docstring-first-sentence`.

Sorry if I get something wrong, but I think it does **not** work for *modes*.

For instance, I can do:

```
NYXT> (command-docstring-first-sentence 'copy-url)
<span>Save current URL to clipboard.</span>
NIL
```

However, it does not work for modes such as:

```
NYXT> (command-docstring-first-sentence 'nyxt/nosound-mode)
<span>; Evaluation aborted on #<SIMPLE-ERROR "Undocumented function ~a." {100F5484F3}>.
NYXT> (command-docstring-first-sentence 'emacs-mode)
<span>; Evaluation aborted on #<SIMPLE-ERROR "Undocumented function ~a." {100F5484F3}>.
NYXT> (command-docstring-first-sentence 'web-mode)
<span>; Evaluation aborted on #<SIMPLE-ERROR "Undocumented function ~a." {100F8634D3}>.
```
Despite the error message, the modes mentioned above **do have** docstrings. I can access them with `describe-command`.

I am not sure if this is issue reporting a bug on the current implementation or a feature request to extend it. Probably, the latter.

**Comment by Ambrevar** [comment]
This is because you are in the NYXT package and there 'emacs-mode is not
a function, you must prepend the nyxt/emacs-mode package.

Anyways, I've clarified the error handling to make the error message
more explicit:

51e4a0fc870e65c664804a6f99e409d20e044e5a

**Comment by pdelfino** [comment]
Ok, thanks for the explanation and for improving the error message. I am closing this issue.
