### ISSUE TITLE
Document Model

### ISSUE THREAD

**Issue by jmercouris** [atlas-engineer/nyxt#1690]
Currently in Web mode we have a very useful `document-model` slot. I suggest we move this to `web-buffer` so that it can be easily used by more modes and more functionality. Is there any opposition to this?

@Ambrevar @aartaka ?

**Comment by aartaka** [comment]
Why not :)

**Comment by jmercouris** [comment]
Agreed!

**Comment by jmercouris** [comment]
Done!
