### ISSUE TITLE
How to swap renderer from webkit to webengine? 

### ISSUE THREAD

**Issue by flusq** [atlas-engineer/nyxt#1691]
How to swap rendere from webkit to webengine? 
When i scroll, its lag 
When i watching video it freezes
I think its because of the render.

**Comment by jmercouris** [comment]
AT this time you would have to use Nyxt 1.5 to use Webengine. I don't believe it is worth it. You are welcome to submit pull requests to update cl-webengine :-)

**Comment by flusq** [comment]
@jmercouris 
But how to fix this bugs?

**Comment by jmercouris** [comment]
They are getting fixed naturally over time. If you want, you could contribute to webkitgtk+ development, that would help a lot.

**Comment by aartaka** [comment]
@flusq
Regarding scrolling: Scrolling is laggy in WebKit, there's nothing to do with it.
Regarding videos: See Nyxt manual, namely "Troubleshooting" and "Playing videos". In essence, you need to install gstreamer plugins.

**Comment by flusq** [comment]
@aartaka I install all gdtreamer plugins. And nyxt show videos. But video very lag.

**Comment by jmercouris** [comment]
Depending on your machine, graphics card, how things are configured WebKitGTK+ can perform very slowly. You can try different graphics card drivers or using different settings with your Web browser. For example, if you have a dual GPU Nvidia, you may use prime to offload Nyxt onto your discrete GPU.

**Comment by aartaka** [comment]
@flusq, any other feedback? Closing the issue then?
