### ISSUE TITLE
nyxt:binding-keys problem with emacs key scheme

### ISSUE THREAD

**Issue by franburstall** [atlas-engineer/nyxt#1693]
**Describe the bug**

I use the emacs key scheme:
```common-lisp
(define-configuration (buffer)
  ((default-modes `(emacs-mode ,@%slot-default%))
   ;; (download-engine :renderer)
   (password-interface (make-instance 'password:user-password-store-interface))
   (override-map (let ((map (make-keymap "override-map")))
		   (define-key map
		     "M-x" 'execute-command
		     "M-n" 'switch-buffer-next
		     "M-p" 'switch-buffer-previous)))))
 ```

If I look at the tutorial, the *Quickstart keys* section says
```
UNBOUND: Load URL
UNBOUND: Reload buffer
UNBOUND: Load URL in new buffer
C-x left, C-x right: Switch buffer
C-b: Backwards history
C-f: Forwards history
M-g M-g: Follow link in current buffer
C-u M-g M-g: Follow link in new buffer
C-x C-c: Quit
M-x: Run a command by name
C-h b: List all bindings for the current buffer
```

From a repl, I see that `nyxt:binding-keys` fails to find the usual binding of `set-url` and friends:
```
NYXT-USER> (nyxt::binding-keys 'set-url)
"UNBOUND"
```

**Information**
- OS name+version: Debian-10
- Graphics card and driver:
- Desktop environment / Window manager name+version: EXWM
- How you installed Nyxt (Guix pack, package manager, build from source): source
- Information from `show-system-information`:
Nyxt version: 2.1.1-401-g18fe3895
Renderer version: GI-GTK
Operating system kernel: Linux 4.19.0-17-amd64
Lisp implementation: SBCL 2.1.1 (Dynamic space size: 1073741824)
Features: (:SLYNK :WEBKIT2 :WEBKIT2-2.32 :WEBKIT2-PASTE-PLAINTEXT :WEBKIT2-TRACKING
 :WEBKIT2-MUTE :WEBKIT2-EMOJI :WEBKIT2-MEDIA :WEBKIT2-SANDBOXING :GTK-3-22
 :GTK-3-20 :GTK-3-18 :GTK-3-16 :GTK-3-14 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6
 :GTK-3-4 :GTK :GDK-3-22 :GDK-3-20 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12
 :GDK-3-10 :GDK-3-8 :GDK-3-6 :GDK-3-4 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF
 :GLIB-2-30 :GLIB-2-32 :GLIB-2-34 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42
 :GLIB-2-44 :GLIB-2-46 :GLIB-2-48 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56
 :GLIB-2-58 :GLIB :NYXT-2 :FSET-EXT-STRINGS :CUSTOM-HASH-TABLE-NATIVE :SWANK
 :PLUMP-UTF-32 :GLOBAL-VARS :DECLARE-TYPES :PARENSCRIPT :NAMED-READTABLES
 :21BIT-CHARS :CHUNGA :FLEXI-STREAMS :CLOSER-MOP :CL-PPCRE-UNICODE :CL-UNICODE
 :CL-PPCRE :BORDEAUX-THREADS :SPLIT-SEQUENCE CHIPZ-SYSTEM:GRAY-STREAMS
 :FAST-IO-SV :FAST-IO :SBCL-USES-SB-ROTATE-BYTE :ASDF-SYSTEM-CONNECTIONS
 :CL-JSON-CLOS :CL-JSON :THREAD-SUPPORT CFFI-FEATURES:FLAT-NAMESPACE
 CFFI-FEATURES:X86-64 CFFI-FEATURES:UNIX :CFFI CFFI-SYS::FLAT-NAMESPACE
 ALEXANDRIA::SEQUENCE-EMPTYP :QUICKLISP :ASDF3.3 :ASDF3.2 :ASDF3.1 :ASDF3
 :ASDF2 :ASDF :OS-UNIX :NON-BASE-CHARS-EXIST-P :ASDF-UNICODE :X86-64 :GENCGC
 :64-BIT :ANSI-CL :COMMON-LISP :ELF :IEEE-FLOATING-POINT :LINUX :LITTLE-ENDIAN
 :PACKAGE-LOCAL-NICKNAMES :SB-LDB :SB-PACKAGE-LOCKS :SB-THREAD :SB-UNICODE
 :SBCL :UNIX)

ASDF version: 3.3.1
Critical dependencies: (/home/fran/common-lisp/nyxt/_build/submodules/cl-cffi-gtk/gtk/cl-cffi-gtk.asd
 /home/fran/common-lisp/nyxt/_build/quicklisp-client/dists/quicklisp/software/cl-gobject-introspection-20210124-git/cl-gobject-introspection.asd
 /home/fran/common-lisp/nyxt/_build/submodules/cl-webkit/webkit2/cl-webkit2.asd)

Quicklisp dist version: 2021-06-30
Quicklisp client version: 2020-01-04
Local project directories: (/home/fran/common-lisp/nyxt/_build/submodules/
 /home/fran/common-lisp/nyxt/_build/quicklisp-client/local-projects/)
Critical dependencies(#<SYSTEM cl-cffi-gtk / cl-cffi-gtk-20201220-git / quicklisp 2021-06-30>
 #<SYSTEM cl-gobject-introspection / cl-gobject-introspection-20210124-git / quicklisp 2021-06-30>
 #<SYSTEM cl-webkit2 / cl-webkit-20210630-git / quicklisp 2021-06-30>)

**Comment by Ambrevar** [comment]
Wow, good catch, looks like a very old (benine) bug had escape the test
suite of libraries/keymap for ages!

Should be fixed with f65f74d8e50be08d525edf7947d3686e3295db5f.

**Comment by franburstall** [comment]
This is definitely an improvement but not perfect.  The tutorial is now showing me cua bindings rather than emacs ones for things like `execute-command`:
```
C-l: Load URL
C-r: Reload buffer
M-l: Load URL in new buffer
C-[, C-]: Switch buffer
C-b: Backwards history
C-f: Forwards history
C-j: Follow link in current buffer
C-J: Follow link in new buffer
C-q: Quit
C-space: Run a command by name
C-h b: List all bindings for the current buffer
```

**Comment by Ambrevar** [comment]
Thanks for your feedback.
9166dd4d0c427489d476cad236232a5d81ff356f should fix this keymap priority issue.

**Comment by franburstall** [comment]
Yup.  That fixes things completely for me.  Many thanks.

**Comment by Ambrevar** [comment]
You're welcome!
