### ISSUE TITLE
URL method should consistently return a `quri:uri`

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#1694]
Otherwise it trips us with bugs like the one fixed in https://github.com/atlas-engineer/nyxt/commit/aee379b4b777bce795b893208e34614d14ae988e.

@aartaka Can we arrange all DOM-related `url` methods to return `quri:uri`?

**Comment by aartaka** [comment]
Yes, that is possible. Will be more consistent this way. 

I remember there was a reason to use strings, though. Maybe because of prompt-buffer?

In any way, I'll do that tomorrow.

**Comment by aartaka** [comment]
Done in 9ce46f5e352fe03b04dcc561fef91b049c1dc125.

**Comment by Ambrevar** [comment]
Perfect, thanks!
