### ISSUE TITLE
Possible bug: `watch-mode` is not prompting me about units of time

### ISSUE THREAD

**Issue by pdelfino** [atlas-engineer/nyxt#1702]
**Describe the bug**
`watch-mode` is supposed to prompt  the user about units of time. This would be used to reload the buffer in specific time intervals. Unfortunately, I am not being prompted about time.

**Precise recipe to reproduce the issue**
- be on commit 865e5d65...;
- start nyxt;
- load a web page (I used [this one](https://en.wikipedia.org/wiki/Kiteboarding));
- enable watch-mode;
- see that the prompt buffer does **not** appear asking for the time interval in which the reload should happen.

For website-specific issues:
Can you reproduce this issue with Epiphany / GNOME Web (https://wiki.gnome.org/Apps/Web)?
Not relevant

**Information**
- OS name+version: 
Ubuntu 20.04 LTS

- Graphics card and driver:
product: Iris Plus Graphics 640
configuration: driver=i915 latency=0

- Desktop environment / Window manager name+version:
Name: GNOME Shell 3.36.7
Window manager's "showing the desktop" mode: OFF

- How you installed Nyxt (Guix pack, package manager, build from source):
Source

- Information from command copy-system-information:

- Information from `show-system-information`:
System information

Nyxt version: 2.1.1-370-g865e5d65
Renderer version: GI-GTK
Operating system kernel: Linux 5.8.0-63-generic
Lisp implementation: SBCL 2.0.1.debian (Dynamic space size: 1073741824)
Features: (:WEBKIT2 :WEBKIT2-2.32 :WEBKIT2-PASTE-PLAINTEXT :WEBKIT2-TRACKING
 :WEBKIT2-MUTE :WEBKIT2-EMOJI :WEBKIT2-MEDIA :WEBKIT2-SANDBOXING :GTK-3-22
 :GTK-3-20 :GTK-3-18 :GTK-3-16 :GTK-3-14 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6
 :GTK-3-4 :GTK :GDK-3-22 :GDK-3-20 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12
 :GDK-3-10 :GDK-3-8 :GDK-3-6 :GDK-3-4 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF
 :GLIB-2-30 :GLIB-2-32 :GLIB-2-34 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42
 :GLIB-2-44 :GLIB-2-46 :GLIB-2-48 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56
 :GLIB-2-58 :GLIB :NYXT-2 :FSET-EXT-STRINGS :CUSTOM-HASH-TABLE-NATIVE
 :PLUMP-UTF-32 :GLOBAL-VARS :DECLARE-TYPES :PARENSCRIPT :NAMED-READTABLES
 :21BIT-CHARS :CHUNGA :FLEXI-STREAMS :CLOSER-MOP :CL-PPCRE-UNICODE :CL-UNICODE
 :CL-PPCRE :BORDEAUX-THREADS :SPLIT-SEQUENCE CHIPZ-SYSTEM:GRAY-STREAMS
 CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64 CFFI-FEATURES:UNIX :CFFI
 CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP :FAST-IO-SV :FAST-IO
 :SBCL-USES-SB-ROTATE-BYTE :ASDF-SYSTEM-CONNECTIONS :CL-JSON-CLOS :CL-JSON
 :THREAD-SUPPORT :SWANK :QUICKLISP :SB-BSD-SOCKETS-ADDRINFO :ASDF3.3 :ASDF3.2
 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX :NON-BASE-CHARS-EXIST-P :ASDF-UNICODE
 :X86-64 :64-BIT :ANSI-CL :COMMON-LISP :ELF :GENCGC :IEEE-FLOATING-POINT :LINUX
 :LITTLE-ENDIAN :PACKAGE-LOCAL-NICKNAMES :SB-CORE-COMPRESSION :SB-LDB
 :SB-PACKAGE-LOCKS :SB-THREAD :SB-UNICODE :SBCL :UNIX)

ASDF version: 3.3.1
Critical dependencies: (/home/pedro/.quicklisp/dists/quicklisp/software/cl-cffi-gtk-20201220-git/gtk/cl-cffi-gtk.asd
 /home/pedro/.quicklisp/dists/quicklisp/software/cl-gobject-introspection-20210124-git/cl-gobject-introspection.asd
 /home/pedro/common-lisp/cl-webkit/webkit2/cl-webkit2.asd)

Quicklisp dist version: 2021-05-31
Quicklisp client version: 2021-02-13
Local project directories: (/home/pedro/.quicklisp/local-projects/)
Critical dependencies(#<SYSTEM cl-cffi-gtk / cl-cffi-gtk-20201220-git / quicklisp 2021-05-31>
 #<SYSTEM cl-gobject-introspection / cl-gobject-introspection-20210124-git / quicklisp 2021-05-31>
 #<SYSTEM cl-webkit2 / cl-webkit-20210531-git / quicklisp 2021-05-31>)

**Output when started from a shell**
```
CL-USER> (nyxt:start)
<INFO> [18:53:11] Listening to socket "/run/user/1000/nyxt/nyxt.socket".
Nyxt version 2.1.1-370-g865e5d65
<INFO> [18:53:11] Loading Lisp file "/home/pedro/.config/nyxt/auto-config.lisp".
<INFO> [18:53:11] Loading Lisp file "/home/pedro/.config/nyxt/init.lisp".
NIL
<INFO> [18:53:16] Loading 3 bookmarks from "/home/pedro/.local/share/nyxt/bookmarks.lisp".
<WARN> [18:53:16] History version "2.1.1-356-g0fcee132" differs from current version "2.1.1-370-g865e5d65"
<INFO> [18:53:16] Loading history of 217 URLs from "/home/pedro/.local/share/nyxt/history/default.lisp".
<INFO> [18:53:21] Loading "https://en.wikipedia.org/wiki/Kiteboarding".
```

**Comment by pdelfino** [comment]
Oh, apparently, `watch-mode` does not work as it [was originally designed](https://nyxt.atlas.engineer/article/watch-mode.org) anymore. It does not prompt the user anymore for a time interval.

Now, it only works with a default of 5 minutes interval between the reload. Is this correct?

**Comment by aartaka** [comment]
Yes, that is correct.

**Comment by aartaka** [comment]
Did we forget to update the documentation?

**Comment by pdelfino** [comment]
> Did we forget to update the documentation?

I think the problem was more the fact that the article nudged me. Sorry for that.

Moreover, I was not aware of `watch-buffer`. I only thought watch-mode existed.

`watch-buffer` docstring is pretty clear:

> Reload BUFFER at a prompted interval, instead of default 5 minutes.

`watch-mode` docstring is:

> Reload the current buffer at regular time intervals.

I think it could be: "Reload the current buffer every 5 minutes". I will send a patch and close the issue.

**Comment by pdelfino** [comment]
PR #1710
