### ISSUE TITLE
Cannot compile on macOS Big Sur

### ISSUE THREAD

**Issue by theHedgehog0** [atlas-engineer/nyxt#1718]
**Describe the bug**
When Building Nyxt, the compilation fails on the first step.

**Precise recipe to reproduce the issue**
1. `git clone` the repo, following the developer docs.
2. `cd` into the repo folder.
3. run `git submodule update --init`
4. run `make all`

**Information**
- OS name+version: macOS Big Sur 11.4
- Graphics card and driver: Intel HD Graphics 6000 1536 MB

<details>
<summary>Make Output</summary>
<code>
sbcl --no-userinit --non-interactive --eval '(require "asdf")' --eval '(when (string= "true" "true") (setf asdf:*default-source-registries* nil) (asdf:clear-configuration) (asdf:load-asd "/Users/993390/software/common-lisp/nyxt//nyxt-quicklisp.asd") (asdf:load-system :nyxt-quicklisp))' --eval '(asdf:load-asd "/Users/993390/software/common-lisp/nyxt//nyxt.asd")' --eval '(when (find-package :ql) (funcall (read-from-string "ql:quickload") :cffi))' --eval '(when (and (find-package :cffi) (uiop:getenv "GUIX_ENVIRONMENT")) (pushnew (pathname (format nil "~a/lib/" (uiop:getenv "GUIX_ENVIRONMENT"))) (symbol-value (read-from-string "cffi:*foreign-library-directories*" )) :test (quote equal)))' --eval '(ql:quickload :nyxt/gi-gtk-application)' \
                --eval '(asdf:make :nyxt/gi-gtk-application)' \
                --eval '(uiop:quit)' || (printf "\n%s\n%s\n" "Compilation failed, see the above stacktrace." && exit 1)
This is SBCL 2.1.7, an implementation of ANSI Common Lisp.
More information about SBCL is available at http://www.sbcl.org/.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
Unhandled SB-INT:BUG in thread #SB-THREAD:THREAD "main thread" RUNNING
                                  {1001538143}:
    failed AVER: (NOT (LOGTEST 96 SB-FASL::OPERAND))
  This is probably a bug in SBCL itself. (Alternatively, SBCL might have been
  corrupted by bad user code, e.g. by an undefined Lisp operation like
  (FMAKUNBOUND 'COMPILE), or by stray pointers from alien code or from unsafe
  Lisp code; or there might be a bug in the OS or hardware that SBCL is running
  on.) If it seems to be a bug in SBCL itself, the maintainers would like to
  know about it. Bug reports are welcome on the SBCL mailing lists, which you
  can find at http://sbcl.sourceforge.net.

Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {1001538143}>
0: (SB-FASL::DECODE-FOP #S(SB-FASL::FASL-INPUT :STREAM #<SB-SYS:FD-STREAM for "file /Users/993390/.brew/Cellar/sbcl/2.1.7/lib/sbcl/contrib/uiop.fasl" {1001579043}> :TABLE #(12737 #<PACKAGE "SB-IMPL"> SB-IMPL::%DEFPACKAGE "UIOP/PACKAGE" #1="COMMON-LISP" (#1#) "FIND-PACKAGE*" "FIND-SYMBOL*" "SYMBOL-CALL" "INTERN*" "EXPORT*" "IMPORT*" ...) :STACK #(27 SB-IMPL::%DEFUN XDG-DATA-DIRS SB-VM::CONS->R11 108929 SB-VM::CONS->R11 107393 SB-VM::CONS->RNN 105729 SB-VM::CONS->R11 104193 PARSE-UNIX-NAMESTRING ...) :NAME-BUFFER #("XDG-DATA-DIRSMERATIONURATION-HOOKVE-PNENTS" "MOREON-APPDATANENT-PESGURATIONQUOTESUOTES") :DEPRECATED-STUFF NIL :SKIP-UNTIL NIL))
1: (SB-FASL::LOAD-FASL-GROUP #S(SB-FASL::FASL-INPUT :STREAM #<SB-SYS:FD-STREAM for "file /Users/993390/.brew/Cellar/sbcl/2.1.7/lib/sbcl/contrib/uiop.fasl" {1001579043}> :TABLE #(12737 #<PACKAGE "SB-IMPL"> SB-IMPL::%DEFPACKAGE "UIOP/PACKAGE" #1="COMMON-LISP" (#1#) "FIND-PACKAGE*" "FIND-SYMBOL*" "SYMBOL-CALL" "INTERN*" "EXPORT*" "IMPORT*" ...) :STACK #(27 SB-IMPL::%DEFUN XDG-DATA-DIRS SB-VM::CONS->R11 108929 SB-VM::CONS->R11 107393 SB-VM::CONS->RNN 105729 SB-VM::CONS->R11 104193 PARSE-UNIX-NAMESTRING ...) :NAME-BUFFER #("XDG-DATA-DIRSMERATIONURATION-HOOKVE-PNENTS" "MOREON-APPDATANENT-PESGURATIONQUOTESUOTES") :DEPRECATED-STUFF NIL :SKIP-UNTIL NIL) NIL)
2: (SB-FASL::LOAD-AS-FASL #<SB-SYS:FD-STREAM for "file /Users/993390/.brew/Cellar/sbcl/2.1.7/lib/sbcl/contrib/uiop.fasl" {1001579043}> NIL NIL)
3: ((LABELS SB-FASL::LOAD-STREAM-1 :IN LOAD) #<SB-SYS:FD-STREAM for "file /Users/993390/.brew/Cellar/sbcl/2.1.7/lib/sbcl/contrib/uiop.fasl" {1001579043}> T)
4: (SB-FASL::CALL-WITH-LOAD-BINDINGS #<FUNCTION (LABELS SB-FASL::LOAD-STREAM-1 :IN LOAD) {A9BF20B}> #<SB-SYS:FD-STREAM for "file /Users/993390/.brew/Cellar/sbcl/2.1.7/lib/sbcl/contrib/uiop.fasl" {1001579043}> T #<SB-SYS:FD-STREAM for "file /Users/993390/.brew/Cellar/sbcl/2.1.7/lib/sbcl/contrib/uiop.fasl" {1001579043}>)
5: (LOAD #P"/Users/993390/.brew/Cellar/sbcl/2.1.7/lib/sbcl/contrib/uiop.fasl" :VERBOSE NIL :PRINT NIL :IF-DOES-NOT-EXIST T :EXTERNAL-FORMAT :DEFAULT)
6: (SB-IMPL::MODULE-PROVIDE-CONTRIB :UIOP)
7: ((FLET "WRAPPER4" :IN REQUIRE) SB-IMPL::MODULE-PROVIDE-CONTRIB)
8: (SB-KERNEL:%MAP-FOR-EFFECT-ARITY-1 #<FUNCTION (FLET "WRAPPER4" :IN REQUIRE) {A9BF40B}> (SB-IMPL::MODULE-PROVIDE-CONTRIB))
9: (REQUIRE :UIOP NIL)
10: (SB-FASL::LOAD-FASL-GROUP #S(SB-FASL::FASL-INPUT :STREAM #<SB-SYS:FD-STREAM for "file /Users/993390/.brew/Cellar/sbcl/2.1.7/lib/sbcl/contrib/asdf.fasl" {1001574603}> :TABLE #(2 REQUIRE :UIOP 0 0 0 0 0 0 0 0 0 ...) :STACK #(0 REQUIRE :UIOP 0 0 0 0 0 0 0 0 0 ...) :NAME-BUFFER #("" "UIOPIRE") :DEPRECATED-STUFF NIL :SKIP-UNTIL NIL) NIL)
11: (SB-FASL::LOAD-AS-FASL #<SB-SYS:FD-STREAM for "file /Users/993390/.brew/Cellar/sbcl/2.1.7/lib/sbcl/contrib/asdf.fasl" {1001574603}> NIL NIL)
12: ((LABELS SB-FASL::LOAD-STREAM-1 :IN LOAD) #<SB-SYS:FD-STREAM for "file /Users/993390/.brew/Cellar/sbcl/2.1.7/lib/sbcl/contrib/asdf.fasl" {1001574603}> T)
13: (SB-FASL::CALL-WITH-LOAD-BINDINGS #<FUNCTION (LABELS SB-FASL::LOAD-STREAM-1 :IN LOAD) {A9BF71B}> #<SB-SYS:FD-STREAM for "file /Users/993390/.brew/Cellar/sbcl/2.1.7/lib/sbcl/contrib/asdf.fasl" {1001574603}> T #<SB-SYS:FD-STREAM for "file /Users/993390/.brew/Cellar/sbcl/2.1.7/lib/sbcl/contrib/asdf.fasl" {1001574603}>)
14: (LOAD #P"/Users/993390/.brew/Cellar/sbcl/2.1.7/lib/sbcl/contrib/asdf.fasl" :VERBOSE NIL :PRINT NIL :IF-DOES-NOT-EXIST T :EXTERNAL-FORMAT :DEFAULT)
15: (SB-IMPL::MODULE-PROVIDE-CONTRIB "asdf")
16: ((FLET "WRAPPER4" :IN REQUIRE) SB-IMPL::MODULE-PROVIDE-CONTRIB)
17: (SB-KERNEL:%MAP-FOR-EFFECT-ARITY-1 #<FUNCTION (FLET "WRAPPER4" :IN REQUIRE) {A9BF91B}> (SB-IMPL::MODULE-PROVIDE-CONTRIB))
18: (REQUIRE "asdf" NIL)
19: (SB-INT:SIMPLE-EVAL-IN-LEXENV (REQUIRE "asdf") #<NULL-LEXENV>)
20: (EVAL (REQUIRE "asdf"))
21: (SB-IMPL::PROCESS-EVAL/LOAD-OPTIONS ((:EVAL . "(require \"asdf\")") (:EVAL . #<(SIMPLE-ARRAY CHARACTER (214)) (when (string= "true" "true") (setf asdf:*default-source-registries* nil) (asdf:clear-configuration) (asdf:load-asd "/Users/993390/software/common-lisp/nyxt//nyxt-quicklisp.asd") (asdf:load-system :ny... {100154034F}>) (:EVAL . "(asdf:load-asd \"/Users/993390/software/common-lisp/nyxt//nyxt.asd\")") (:EVAL . "(when (find-package :ql) (funcall (read-from-string \"ql:quickload\") :cffi))") (:EVAL . #<(SIMPLE-ARRAY CHARACTER (235)) (when (and (find-package :cffi) (uiop:getenv "GUIX_ENVIRONMENT")) (pushnew (pathname (format nil "~a/lib/" (uiop:getenv "GUIX_ENVIRONMENT"))) (symbol-value (read-from-string "cffi:*foreign-library-dir... {10015409AF}>) (:EVAL . "(ql:quickload :nyxt/gi-gtk-application)") (:EVAL . "(asdf:make :nyxt/gi-gtk-application)") (:EVAL . "(uiop:quit)") (:QUIT)))
22: (SB-IMPL::TOPLEVEL-INIT)
23: ((FLET SB-UNIX::BODY :IN SB-IMPL::START-LISP))
24: ((FLET "WITHOUT-INTERRUPTS-BODY-1" :IN SB-IMPL::START-LISP))
25: (SB-IMPL::START-LISP)

unhandled condition in --disable-debugger mode, quitting

Compilation failed, see the above stacktrace.
</code>
</details>

**Comment by ModdedGamers** [comment]
I have given all the context I have. Is there anything else I can provide to help debug this problem?

**Comment by Ambrevar** [comment]
@jmercouris Do you have Big Sur?

Maybe related to https://github.com/atlas-engineer/nyxt/issues/1470.

**Comment by jmercouris** [comment]
I don't have big sur, and I have no idea I am afraid. Seems like a problem with the homebrew specification of SBCL. Perhaps we are making some assumptions that don't hold true.

**Comment by aadcg** [comment]
See #577 for a discussion on how to pursue macOS support. 

Nyxt plans to support macOS in version 4.0.0.
