### ISSUE TITLE
Sandboxing not actually enabled

### ISSUE THREAD

**Issue by tiberious726** [atlas-engineer/nyxt#1726]
Sandboxing is enabled by the `web-context` method:

https://github.com/atlas-engineer/nyxt/blob/master/source/renderers/gtk.lisp#L83
```
(defmethod web-context ((browser gtk-browser))
  (or (slot-value *browser* 'web-context)
      (let ((context (make-instance 'webkit:webkit-web-context)))
        (webkit:webkit-web-context-set-sandbox-enabled context t)
        (setf (slot-value *browser* 'web-context) context))))
```

Which is called by the `make-context` function:

https://github.com/atlas-engineer/nyxt/blob/master/source/renderers/gtk.lisp#L615
```
(defun make-context (&optional buffer)
  ;; This is to ensure that paths are not expanded when we make
  ;; contexts for `nosave-buffer's.
  (with-current-buffer buffer
    (let* ((context (if (and buffer
                             ;; Initial window buffer or replacement/temp buffers
                             ;; may have no ID.
                             (not (str:emptyp (id buffer))))
                        (let ((manager (make-data-manager buffer)))
                          (make-instance 'webkit:webkit-web-context
                                         :website-data-manager manager))
                        (web-context *browser*)))
...
```

`web-context` is only called on the else-branch of the conditional about the buffer having an ID number, otherwise the context is created without calling `webkit-web-context-set-sandbox-enabled`

This can be verified by patching `make-context` with the following (to actually set the web-context slot (I found this when trying to add the favicon database stuff, and couldn't get to the web-context)):

```
(let* ((context (if (and buffer
                             ;; Initial window buffer or replacement/temp buffers
                             ;; may have no ID.
                             (not (str:emptyp (id buffer))))
                        (let* ((manager (make-data-manager buffer))
                              (context (make-instance 'webkit:webkit-web-context
                                                      :website-data-manager manager)))
                          (setf (slot-value *browser* 'web-context) context))
                        (web-context *browser*)))
...

```
And then running `(webkit:webkit-web-context-get-sandbox-enabled (slot-value *browser* nyxt::'web-context))` from a REPL

**Comment by tiberious726** [comment]
Here's a fix: https://github.com/atlas-engineer/nyxt/pull/1727

**Comment by tiberious726** [comment]
Understanding the `web-context` slot on *browser* more now, here's a more direct demonstration of the issue (that doesn't require patching `make-context`):

```(mapcar #'(lambda (buffer) (webkit:webkit-web-context-get-sandbox-enabled (slot-value (gtk-object buffer) 'webkit::web-context)) ) (buffer-list))
```

**Comment by tiberious726** [comment]
It looks like this has always been the case since sandboxing was intended to be introduced in https://github.com/atlas-engineer/nyxt/commit/91f5f3efd444db8e28208ad9cca8b33ccdac82ea

**Comment by jmercouris** [comment]
I see, very fascinating. I will have to see where we went wrong here. I believe we wanted a singleton web context because it led to fewer crashes in Nyxt. It may also have something to do with logins getting randomly deleted. I wish I could remember the details. @Ambrevar do you remember why we did this?

**Comment by tiberious726** [comment]
I see some discussion about it here: https://github.com/atlas-engineer/nyxt/issues/188#issuecomment-823439713

My current understanding of the git master code is that the singleton web-context isn't actually used at all anymore. If you want, I can add a commit to that PR pulling out the web-context slot altogether (it certainly confused me, as you can see above).

**Comment by jmercouris** [comment]
Aha I see. I wonder why we were trying to reuse a single web context then. I wonder if that was an incorrect assumption on our part.

**Comment by jmercouris** [comment]
I've removed the singleton web context since you are right, it appears we are not using it.

**Comment by Ambrevar** [comment]
Closing this in favour of #1733.
