### ISSUE TITLE
[Feature Request] Single Help buffer instead of new help buffer each time

### ISSUE THREAD

**Issue by Inc0n** [atlas-engineer/nyxt#1728]
Using decsribe- functions will open a new help buffer every time, wouldn't it be better to collectively control the help buffer with a single one, where it can be history navigated.

**Comment by jmercouris** [comment]
Thank you for the idea!

That is subject to preference of course, but I think we might be able to figure something out :-). I'm sure we could make it an option.

In order to do so, we first we would need to add history support for internal buffers.

**Comment by franburstall** [comment]
> In order to do so, we first we would need to add history support for internal buffers.

Yes please for history support in internal buffers!  Right now `C-b` and `C-f` throw errors in such buffers.
