### ISSUE TITLE
Webkit web-context sharing / isolation

### ISSUE THREAD

**Issue by tiberious726** [atlas-engineer/nyxt#1733]
Breaking off from https://github.com/atlas-engineer/nyxt/issues/1726

Reading up on the webkit documentation, it looks like cookies and cache are shared within a web context, with the intention of different browser "tabs"/windows sharing it. (It would be interesting to have different buffer-groups with different web-contexts., similar to Firefox's "Multi Account Container".)

It looks like some kind of sharing is currently happening in nyxt, even though every buffer gets a new web-context, because the different contexts happen to be backed to the same two locations on disk (`~/.cache/nyxt/data-manager` for "external" buffers and `~/.cache/nyxt/WebKitCache/` for buffers that satisfy `internal-buffer-p` (since by not setting a `website-data-manager` for it, we just use the defaults)), but I imagine it would be pretty janky/unreliable without them being shared in-memory too

(looking at my cache from old versions of nyxt, it looks like they used to be separated into `data-manager-1` , `data-manager-2` , etc, changing from this to backing them to the same file location was probably when session sharing started working at all)

It makes sense to me to use a different context, with different settings, for internal buffers than ones presenting actual web content, as well as eventually allowing users to define their own context groups, so a singleton like was tried before doesn't make sense anymore. I think what we want is a set of contexts in a slot on the browser class, keyed by strings, so users can easily name their own, and two "default" contexts: "internal" and "default-external".

I'll put together some code later, I want to understand the `data-profile` class and how the user is meant to interact with it a bit more first

**Comment by jmercouris** [comment]
A very salient observation, I look forward to your pull request :-)

**Comment by tiberious726** [comment]
https://github.com/atlas-engineer/nyxt/pull/1757

**Comment by Ambrevar** [comment]
And see #1987 for an update.

**Comment by Ambrevar** [comment]
Fixed with #2050.  Thanks for your awesome work, @tiberious726 !
