### ISSUE TITLE
Idea: glyph representation for buffers

### ISSUE THREAD

**Issue by jmercouris** [atlas-engineer/nyxt#1736]
It would be cool if we had a glyph representation for buffers that we could show in the prompt buffer. This could take many forms:

1. it could be a little icon showing the primary colors on the website of the buffer
2. It could be a copy of the favicon
3. it could be a minified screenshot of the page

the whole point is that we have a visual reference for each buffer.

**Comment by Ambrevar** [comment]
The `webkit` API point for favicons is `cl-webkit2:webkit-web-view-get-favicon`.
Would be trivial to add it!  Then we would be able to squeeze tabs in the status area.

Cc @aadcg With that implemented, the tabs would occupy less space and the mode list could be expanded.

**Comment by aadcg** [comment]
This is done.
