### ISSUE TITLE
Any chance of supporting aarch64 architecture? [Feaute Request]

### ISSUE THREAD

**Issue by chookity-pokk** [atlas-engineer/nyxt#1742]
Was hoping to use this on my [Pine Phone](https://www.pine64.org/pinephone/) but it seems like you only have a `.deb` file for `amd64` and not `arm/aarch64` and was curious if maybe that would be coming in the future?

**Comment by aartaka** [comment]
That is possible, but there's some effort that one needs to put into that. See #932 for the relevant discussion.

**Comment by aadcg** [comment]
I'm able to run Nyxt on aarch64, so you should be able to run Nyxt on your Pine Phone.

Feel free to re-open if you get stuck.
