### ISSUE TITLE
How to unbind a key?

### ISSUE THREAD

**Issue by franburstall** [atlas-engineer/nyxt#1743]
**Describe the bug**

I have the GTK emacs key-theme enabled in my desktop environent and this means that `C-a` and `C-e` should move the cursor to the end or beginning of the line in textboxes.  This works fine in nyxt for `C-a` but not for `C-e` because there is a binding of `C-e '` to `edit-with-external-editor`.  This turns `C-e` into a prefix key.  A work-around is to hit `C-e` twice but this is a little irritating.

Folllowing this [discussion](https://discourse.atlas.engineer/t/how-to-unset-a-key-binding/115), I tried binding `C-e '` to `nothing` in the buffer class's `override-map` slot but this still leaves `C-e` as a prefix key.  

So how can I unbind `C-e '` so that `C-e` is passed to the browser unmolested by nyxt?

Failing that, can I respectfully suggest that `C-e '` is a rather unfortunate choice for an emacs keyscheme and something else be chosen instead?

**Information**
- OS name+version: Debian-10
- Graphics card and driver:
- Desktop environment / Window manager name+version: EXWM
- How you installed Nyxt (Guix pack, package manager, build from source): source
- Information from `show-system-information`:
Nyxt version: 2.1.1-526-g256a1b07
Renderer version: GI-GTK
Operating system kernel: Linux 4.19.0-17-amd64
Lisp implementation: SBCL 2.1.1 (Dynamic space size: 1073741824)
Features: (:SLYNK :WEBKIT2 :WEBKIT2-2.32 :WEBKIT2-PASTE-PLAINTEXT :WEBKIT2-TRACKING
 :WEBKIT2-MUTE :WEBKIT2-EMOJI :WEBKIT2-MEDIA :WEBKIT2-SANDBOXING :GTK-3-22
 :GTK-3-20 :GTK-3-18 :GTK-3-16 :GTK-3-14 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6
 :GTK-3-4 :GTK :GDK-3-22 :GDK-3-20 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12
 :GDK-3-10 :GDK-3-8 :GDK-3-6 :GDK-3-4 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF
 :GLIB-2-30 :GLIB-2-32 :GLIB-2-34 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42
 :GLIB-2-44 :GLIB-2-46 :GLIB-2-48 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56
 :GLIB-2-58 :GLIB :NYXT-2 :FSET-EXT-STRINGS :CUSTOM-HASH-TABLE-NATIVE :SWANK
 :PLUMP-UTF-32 :GLOBAL-VARS :DECLARE-TYPES :PARENSCRIPT :NAMED-READTABLES
 :LPARALLEL :21BIT-CHARS :CHUNGA :FLEXI-STREAMS :CLOSER-MOP :CL-PPCRE-UNICODE
 :CL-UNICODE :CL-PPCRE :BORDEAUX-THREADS :LPARALLEL.WITH-CLTL2
 :LPARALLEL.WITH-CAS :LPARALLEL.WITH-STEALING-SCHEDULER :SPLIT-SEQUENCE
 CHIPZ-SYSTEM:GRAY-STREAMS :FAST-IO-SV :FAST-IO :SBCL-USES-SB-ROTATE-BYTE
 :ASDF-SYSTEM-CONNECTIONS :CL-JSON-CLOS :CL-JSON :THREAD-SUPPORT
 CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64 CFFI-FEATURES:UNIX :CFFI
 CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP :QUICKLISP :ASDF3.3
 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX :NON-BASE-CHARS-EXIST-P
 :ASDF-UNICODE :X86-64 :GENCGC :64-BIT :ANSI-CL :COMMON-LISP :ELF
 :IEEE-FLOATING-POINT :LINUX :LITTLE-ENDIAN :PACKAGE-LOCAL-NICKNAMES :SB-LDB
 :SB-PACKAGE-LOCKS :SB-THREAD :SB-UNICODE :SBCL :UNIX)

ASDF version: 3.3.1
Critical dependencies: (/home/fran/common-lisp/nyxt/_build/submodules/cl-cffi-gtk/gtk/cl-cffi-gtk.asd
 /home/fran/common-lisp/nyxt/_build/quicklisp-client/dists/quicklisp/software/cl-gobject-introspection-20210124-git/cl-gobject-introspection.asd
 /home/fran/common-lisp/nyxt/_build/submodules/cl-webkit/webkit2/cl-webkit2.asd)

Quicklisp dist version: 2021-08-07
Quicklisp client version: 2020-01-04
Local project directories: (/home/fran/common-lisp/nyxt/_build/submodules/
 /home/fran/common-lisp/nyxt/_build/quicklisp-client/local-projects/)
Critical dependencies(#<SYSTEM cl-cffi-gtk / cl-cffi-gtk-20201220-git / quicklisp 2021-08-07>
 #<SYSTEM cl-gobject-introspection / cl-gobject-introspection-20210124-git / quicklisp 2021-08-07>
 #<SYSTEM cl-webkit2 / cl-webkit-20210807-git / quicklisp 2021-08-07>)

**Comment by jmercouris** [comment]
There is a way to unbind keys, however it is a problem when a key depends on a prefix. Consider:

```
C-x C-s -> save
C-x -> something
```

now, the user presses C-x, what happens? The user unbinds C-x, what happens? How should we handle this ambiguity? In fact, C-x was a `illegal` binding to begin with.

All this said, I would be more than glad to change the keybinding. I've rebound it to `C-u C-x C-f`. Please let me know if you have any better ideas :-).

**Comment by franburstall** [comment]
Thanks for changing the binding.

Are you will to share how to unbind a key also or is that a work in progress given the issues you have raised?

**Comment by Ambrevar** [comment]
Sorry for taking so long to come back to this.

If you pass `nil` as a bound-value to `keymap:define-key`, it will undefine the key.  Example:

```lisp
(define-key (override-map (current-buffer)) "C-e" nil)
```

Replace `(override-map ...)` with the desired keymap and "C-e" with the desired binding.

Now where it gets tricky is if you want to unbind a key everywhere!
As suggested, you can bind a key to `nothing`, so you could bind `C-e` to `nothing`, but that would not forward it to the renderer.

So instead, I suggest we add a special command which forwards a binding to the render, say `forward-to-renderer`.  Would that solve the problem?  

What do you people think?

**Comment by Ambrevar** [comment]
See #1922 for a suggestion.

**Comment by Ambrevar** [comment]
I believe #1922 fixes it, so closing this now.  Feel free to reopen if there is anything else.

**Comment by jcguu95** [comment]
By unbinding by setting `"O"` to `NIL`, using

(define-key (override-map (current-buffer)) "O" nil)

returns the following error.

```
WARN - Warning: Error on separate thread: The value
                            NIL
                          is not of type
                            NYXT::NYXT-KEYMAP-VALUE
```

**Comment by Ambrevar** [comment]
Which Nyxt version are you running?

**Comment by Ambrevar** [comment]
Wait, @jcguu95 did you put this line in your init file?  If so, it's normal it does not work, it's meant to be run from a REPL.

From your init file, you want something like this instead:

```lisp
(define-configuration buffer
  ((override-map (let ((map (make-keymap \"override-map\")))
                   (define-key map
                     \"O\" nil)))))
```
