### ISSUE TITLE
G key stuck in minibuffer and open url buffer

### ISSUE THREAD

**Issue by jgarte** [atlas-engineer/nyxt#1751]
When I try to type the letter g in the minibuffer or the "Open URL buffer" I get the following message triggered:

[Pressed keys:](https://github.com/atlas-engineer/nyxt/blob/6db5c866c7b26ad540ec20c96f759cb05e6d93a6/source/input.lisp#L125) g
  ```
$ nyxt --system-information

(process:32024): Gtk-WARNING **: 15:10:09.814: Locale not supported by C library.
	Using the fallback 'C' locale.

(sbcl:32024): dbind-WARNING **: 15:10:09.837: AT-SPI: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
Nyxt version: 2.0.0
Renderer version: GTK
Operating system kernel: Linux 5.13.12_1
Lisp implementation: SBCL 2.1.2.nixos
Features: (WEBKIT2 WEBKIT2-2.32 WEBKIT2-TRACKING WEBKIT2-MUTE WEBKIT2-EMOJI WEBKIT2-MEDIA
 WEBKIT2-SANDBOXING GTK-3-22 GTK-3-20 GTK-3-18 GTK-3-16 GTK-3-14 GTK-3-12
 GTK-3-10 GTK-3-8 GTK-3-6 GTK-3-4 GTK GDK-3-22 GDK-3-20 GDK-3-18 GDK-3-16
 GDK-3-14 GDK-3-12 GDK-3-10 GDK-3-8 GDK-3-6 GDK-3-4 CAIRO-1-10 CAIRO-1-12
 GDK-PIXBUF GLIB-2-30 GLIB-2-32 GLIB-2-34 GLIB-2-36 GLIB-2-38 GLIB-2-40
 GLIB-2-42 GLIB-2-44 GLIB-2-46 GLIB-2-48 GLIB-2-50 GLIB-2-52 GLIB-2-54
 GLIB-2-56 GLIB-2-58 GLIB NYXT-2 FSET-EXT-STRINGS CUSTOM-HASH-TABLE-NATIVE
 SWANK PLUMP-UTF-32 GLOBAL-VARS DECLARE-TYPES PARENSCRIPT NAMED-READTABLES
 21BIT-CHARS CHUNGA FLEXI-STREAMS CLOSER-MOP CL-PPCRE-UNICODE CL-UNICODE
 CL-PPCRE BORDEAUX-THREADS SPLIT-SEQUENCE GRAY-STREAMS FLAT-NAMESPACE X86-64
 UNIX CFFI FLAT-NAMESPACE SEQUENCE-EMPTYP FAST-IO-SV FAST-IO
 SBCL-USES-SB-ROTATE-BYTE ASDF-SYSTEM-CONNECTIONS CL-JSON-CLOS CL-JSON
 THREAD-SUPPORT ASDF3.3 ASDF3.2 ASDF3.1 ASDF3 ASDF2 ASDF OS-UNIX
 NON-BASE-CHARS-EXIST-P ASDF-UNICODE X86-64 GENCGC 64-BIT ANSI-CL COMMON-LISP
 ELF IEEE-FLOATING-POINT LINUX LITTLE-ENDIAN PACKAGE-LOCAL-NICKNAMES SB-LDB
 SB-PACKAGE-LOCKS SB-THREAD SB-UNICODE SBCL UNIX)

ASDF version: 3.3.4
Critical dependencies: (/nix/store/wbqqn03vdysi9301lnq2xicydq6b7vdq-lisp-cl-cffi-gtk-20201220-git/lib/common-lisp/cl-cffi-gtk/gtk/cl-cffi-gtk.asd
 /nix/store/n5mxx5dl2n7wvljv660841k9byxqjnjp-lisp-cl-gobject-introspection-20210124-git/lib/common-lisp/cl-gobject-introspection/cl-gobject-introspection.asd
 /nix/store/sncisd9rn08j3hv24w93cvnn68r44z7n-lisp-cl-webkit2-cl-webkit-20210411-git/lib/common-lisp/cl-webkit2/webkit2/cl-webkit2.asd)

Guix version:
```

I installed nyxt with nix package manager:

```
$ whereis nyxt
nyxt: /nix/store/hyzs42y5ib0ik251p9fv7fh2mnzzcv4k-user-environment/bin/nyxt

$ which nyxt
/home/jgart/.nix-profile/bin/nyxt
```

I'm also running stumpwm. Not sure if that might be a factor in this issue. I'm able to input the letter "g" into firefox, chromium, etc...

**Comment by jmercouris** [comment]
Hm, very odd, I don't know how to begin debugging this, perhaps @Ambrevar has an idea!

**Comment by Ambrevar** [comment]
@jgart Are you using VI bindings?

The symptom you describe indicates that your prompt buffer is in VI normal mode.  If you press `i` it should bring you to VI insert mode and `g` should work.

**Comment by jgarte** [comment]
![2021-09-08-115330_1600x900_scrot](https://user-images.githubusercontent.com/47760695/132543172-7953147f-0c85-4cd5-90b6-6cd7d30e7978.png)

**Comment by jgarte** [comment]
hmmm, didn't capture the cursor, but I was *already* in vi insert mode when typing the [bang](https://duckduckgo.com/bang) for wikipedia.

Right when I was going to type `g` in the minibuffer, then it got stuck and echoed `Pressed keys: g`

**Comment by jgarte** [comment]
On a different topic, how do I set the minibuffer to be insert mode by default?

**Comment by Ambrevar** [comment]
This should do:

(define-configuration prompt-buffer
  ((default-modes (append '(vi-insert-mode) %slot-default%))))

**Comment by jmercouris** [comment]
@jgarte based on your profile picture here, I think you will appreciate this video: https://www.youtube.com/watch?v=A5L8bdYY9FY

**Comment by jgarte** [comment]
> @jgarte based on your profile picture here, I think you will appreciate this video: https://www.youtube.com/watch?v=A5L8bdYY9FY

Hahaha, funny vid. 

I picked a profile pic rather hastily. 

It serves its purpose, I guess.

**Comment by jgarte** [comment]
> This should do: (define-configuration prompt-buffer ((default-modes (append '(vi-insert-mode) %slot-default%))))

@Ambrevar Thanks! That works like a charm.

I think the issue in this thread still happens in certain edge cases. In other words, it feels like switching to and from normal/insert mode in the minibuffer trips up some times.

I'd have to test more and see where it breaks. 

One observed example/situation,

If I press `o` to open the minibuffer and then start typing `!w g`.

I'm able to type `!w ` (including the space character) but when I get to the `g` it locks up and I have to press `i` to get into insert mode.

**Comment by Ambrevar** [comment]
@aartaka Do you use VI bindings in Nyxt?  If so, did you experience the issue reported in the last post?

**Comment by aartaka** [comment]
> @aartaka Do you use VI bindings in Nyxt? If so, did you experience the issue reported in the last post?

No, I'm not using VI bindings yet :(

**Comment by jmercouris** [comment]
Can't reproduce anymore.
