### ISSUE TITLE
Better JSON en/decoding?

### ISSUE THREAD

**Issue by aartaka** [atlas-engineer/nyxt#1758]
I'm making some final adjustments before opening a PR for WebExtensions support prototype, and one thing that was bugging me out was working with JSON. JSON is everywhere in WebExtensions, so any quirk in deserialization library is getting severely annoying. CL-JSON doesn't cut it for me anymore. Issues I had with it:
- You cannot distinguish deserialized objects from arrays: objects are alists, arrays are plain lists. Ideally we should have separate types for objects and arrays: lists and vectors or hash-tables and lists/vectors. Even better: have it to be configurable for cases we need performance/type correctness in.
- Objects' keywords are... keywords (i.e. symbols in `:keyword` package). These should ideally be strings, because that's much saner, and it's [safer](https://sabracrolleton.github.io/json-review.html#security).
- `nil` translates to `null`, no way to get `false` in JSON when translating from Lisp.
- Both `null` and `false` get translated to Lisp `nil`. Too ambiguous. Ideally one of those should be a keyword/string/a separate type.
- It doesn't play well with the optimum of JSON deserialization we had in cl-webkit. The optimum (I believe) is: 
  - null -> :NULL
  - false -> nil (as an opposite of true -> t)
  - object -> hash-table
  - array -> list
  - undefined -> :undefined

Our options are:
- Other libraries from [Comparison of CL JSON libraries](https://sabracrolleton.github.io/json-review.html).
  - Author suggests st-json for null/false issues. It's described as not-quite-the-smartest-library, though.
- Customizing cl-json to our needs. It's methods-based, so we can probably hook into it somehow. The blogpost above claims it's possible. cl-json is the most mature solution out there. Maybe no use in ditching it without trying to customize it.
- Leveraging cl-webkit: `(webkit:jsc-value-to-lisp (webkit:jsc-value-from-json (webkit:jsc-context-new) "value there"))` should cut it. 
  - It's extremely configurable.
  - It's compatible with... cl-webkit xD
  - WebKit people have most probably worked a lot on their parser -- I had no problems with it in the last two months (and I used it _a lot_).
  - The ffi call overhead, though.
  - It's kind of wrong semantically -- we're creating an object just for the sake of deserializing it.

**Comment by Ambrevar** [comment]
Your analysis seems sane and you have more experience than me in this area, so I'm afraid I don't have much to offer, sorry :) 

So you'd like to try extending cl-json first?

**Comment by aartaka** [comment]
Exactly.
