### ISSUE TITLE
Add more features to the start page

### ISSUE THREAD

**Issue by aaron-tan** [atlas-engineer/nyxt#1761]
At the moment, the start page seems to be very blank. It's just a white page and some links to the website, forum etc.

I propose that we add a few things to make the start page a bit more livelier.

- (Minor suggestion) Add the nyxt logo on the start page and in the top left icon box on the window
- Add a search bar that links straight to a search engine? Like with Chrome and Firefox. Or even perhaps just a search bar to input URLs
- Again this is kind of like in Firefox and Chrome, list some commonly used links e.g. Facebook, Youtube etc or even just the last 5 URLs that were opened?

I'm happy to hear any thoughts on this.

**Comment by aartaka** [comment]
Point-by-point:
1. Logo could work, yes.
2. Sear bar is not possible to embed in internal buffer (which our start page is) for security reasons.
3. This is covered by dashboard. You can set the dashboard as your start page, instead of the default one.

**Comment by 7reont5pao** [comment]
Hey @aartaka, apologies for pin pointing your comment, but how would one go about doing 3? Would it essentially take overriding the existing `startup` method and create a dashboard buffer instead of a help buffer [here](https://github.com/atlas-engineer/nyxt/blob/1d57a5e78709ad1a14a7ef759a27bf19dc879efa/source/browser.lisp#L345)?

**Comment by jmercouris** [comment]
There is a slight confusion here, the start page the original poster is referring to is the URL at Nyxt.atlas.engineer/start

**Comment by jmercouris** [comment]
Why not a search bar? Because you can search with C-l instantly. A logo may be a good idea. I was just trying to keep the page as light as possible!

**Comment by aaron-tan** [comment]
Thanks @jmercouris we don't need a search bar then, C-l works perfectly fine.

How about we merge the start page with the dashboard or help page instead? It seems to me at least that the dashboard and help page are much more useful and helpful than the start page. We could move all of the links on the start page (website, forum, chat etc) to the dashboard/help page instead.

**Comment by aartaka** [comment]
> Hey @aartaka, apologies for pin pointing your comment, but how would one go about doing 3? Would it essentially take overriding the existing `startup` method and create a dashboard buffer instead of a help buffer [here](https://github.com/atlas-engineer/nyxt/blob/1d57a5e78709ad1a14a7ef759a27bf19dc879efa/source/browser.lisp#L345)?

@7reont5pao Yes, that could be the way to go. Alternatively, you can define an `:around`/`:after` method for `startup` and change buffers there. Something like (tested on `web-extensions` branch, but should work on `master` too:
``` lisp
(defmethod nyxt::startup :after ((browser browser) urls)
  (let ((help-buffer (find "*Help*" (buffer-list) :key #'title :test #'equal)))
    (window-set-buffer (current-window) (dashboard) :focus t)
    ;; Delete the help buffer if you want to.
    ;; (nyxt::buffers-delete (id help-buffer))
    ))
```

**Comment by triveo** [comment]
Thanks @aartaka! It works like a charm.
