### ISSUE TITLE
Possible bug: It is not possible to change the value of `spell-check-language` slot (default is "en_US")

### ISSUE THREAD

**Issue by pdelfino** [atlas-engineer/nyxt#1768]
**Describe the bug**
The default value of `spell-check-language` (class `user-browser`) is "en_US". Initially, I tried "pt_BR". But not sure if this exists. Reading [cl-enchant doc](https://github.com/tlikonen/cl-enchant), there is an example with "en_GB" and "en_US". I tried testing it with words such as flavor/flavour, but it does not seem to react to the change.

**Precise recipe to reproduce the issue**
- execute the command `describe-slot`;
- type `spell-check-language`;
- there are two options, select the one from `user-browser` class;
- press `M-return`(return selection over action);
- execute action `describe-slot-1`;
- click on `configure`
- insert the string "en_GB";
- echo returns "Update slot SPELL-CHECK-LANGUAGE to "en_GB";
- test the change with command `spell-check-word`, insert `colour`. Echo returns `colour` is incorrect. I was expecting it to say it is correct after the change to "en_GB" based on [this](https://www.oxfordinternationalenglish.com/differences-in-british-and-american-spelling/). Other words such as `humour` and `flavour``are treated the same problematic way.

For website-specific issues:
Can you reproduce this issue with Epiphany / GNOME Web (https://wiki.gnome.org/Apps/Web)?
Not relevant

- OS name+version: 
Ubuntu 20.04 LTS

- Graphics card and driver:
product: Iris Plus Graphics 640
configuration: driver=i915 latency=0

- Desktop environment / Window manager name+version:
Name: GNOME Shell 3.36.7
Window manager's "showing the desktop" mode: OFF

- How you installed Nyxt (Guix pack, package manager, build from source):
Source

- Information from command `show-system-information`:

Nyxt version: 2.1.1-586-g6dd9306b
Renderer version: GI-GTK
Operating system kernel: Linux 5.11.0-27-generic
Lisp implementation: SBCL 2.0.1.debian (Dynamic space size: 1073741824)
Features: (:WEBKIT2 :WEBKIT2-2.32 :WEBKIT2-PASTE-PLAINTEXT :WEBKIT2-TRACKING
 :WEBKIT2-MUTE :WEBKIT2-EMOJI :WEBKIT2-MEDIA :WEBKIT2-SANDBOXING :GTK-3-22
 :GTK-3-20 :GTK-3-18 :GTK-3-16 :GTK-3-14 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6
 :GTK-3-4 :GTK :GDK-3-22 :GDK-3-20 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12
 :GDK-3-10 :GDK-3-8 :GDK-3-6 :GDK-3-4 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF
 :GLIB-2-30 :GLIB-2-32 :GLIB-2-34 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42
 :GLIB-2-44 :GLIB-2-46 :GLIB-2-48 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56
 :GLIB-2-58 :GLIB :NYXT-2 :FSET-EXT-STRINGS :CUSTOM-HASH-TABLE-NATIVE
 :PLUMP-UTF-32 :GLOBAL-VARS :DECLARE-TYPES :PARENSCRIPT :NAMED-READTABLES
 :LPARALLEL :21BIT-CHARS :CHUNGA :FLEXI-STREAMS :CLOSER-MOP :CL-PPCRE-UNICODE
 :CL-UNICODE :CL-PPCRE :BORDEAUX-THREADS :LPARALLEL.WITH-CLTL2
 :LPARALLEL.WITH-CAS :LPARALLEL.WITH-STEALING-SCHEDULER :SPLIT-SEQUENCE
 CHIPZ-SYSTEM:GRAY-STREAMS CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64
 CFFI-FEATURES:UNIX :CFFI CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP
 :FAST-IO-SV :FAST-IO :SBCL-USES-SB-ROTATE-BYTE :ASDF-SYSTEM-CONNECTIONS
 :CL-JSON-CLOS :CL-JSON :THREAD-SUPPORT :SWANK :QUICKLISP
 :SB-BSD-SOCKETS-ADDRINFO :ASDF3.3 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF
 :OS-UNIX :NON-BASE-CHARS-EXIST-P :ASDF-UNICODE :X86-64 :64-BIT :ANSI-CL
 :COMMON-LISP :ELF :GENCGC :IEEE-FLOATING-POINT :LINUX :LITTLE-ENDIAN
 :PACKAGE-LOCAL-NICKNAMES :SB-CORE-COMPRESSION :SB-LDB :SB-PACKAGE-LOCKS
 :SB-THREAD :SB-UNICODE :SBCL :UNIX)

ASDF version: 3.3.1
Critical dependencies: (/home/pedro/.quicklisp/dists/quicklisp/software/cl-cffi-gtk-20201220-git/gtk/cl-cffi-gtk.asd
 /home/pedro/.quicklisp/dists/quicklisp/software/cl-gobject-introspection-20210124-git/cl-gobject-introspection.asd
 /home/pedro/common-lisp/cl-webkit/webkit2/cl-webkit2.asd)

Quicklisp dist version: 2021-05-31
Quicklisp client version: 2021-02-13
Local project directories: (/home/pedro/.quicklisp/local-projects/)
Critical dependencies(#<SYSTEM cl-cffi-gtk / cl-cffi-gtk-20201220-git / quicklisp 2021-05-31>
 #<SYSTEM cl-gobject-introspection / cl-gobject-introspection-20210124-git / quicklisp 2021-05-31>
 #<SYSTEM cl-webkit2 / cl-webkit-20210531-git / quicklisp 2021-05-31>)

 
**Output when started from a shell**

```lisp
CL-USER> (in-package :nyxt)
#<PACKAGE "NYXT">
NYXT> (start)
<INFO> [19:46:28] Listening to socket "/run/user/1000/nyxt/nyxt.socket".
Nyxt version 2.1.1-586-g6dd9306b
<INFO> [19:46:28] Loading Lisp file "/home/pedro/.config/nyxt/auto-config.lisp".
<INFO> [19:46:28] Loading Lisp file "/home/pedro/.config/nyxt/init.lisp".
NIL
<INFO> [19:46:30] Loading history of 530 URLs from "/home/pedro/.local/share/nyxt/history/default.lisp".
<INFO> [19:46:32] Loading 1 bookmarks from "/home/pedro/.local/share/nyxt/bookmarks.lisp".
<INFO> [19:51:23] Update slot SPELL-CHECK-LANGUAGE to "pt_BR".
<INFO> [19:51:23] Appending to "/home/pedro/.config/nyxt/auto-config.lisp":
(DEFINE-CONFIGURATION USER-BROWSER
  ((SPELL-CHECK-LANGUAGE "pt_BR")))
<INFO> [19:51:33] "teste" is incorrect.
<INFO> [19:51:40] "test" spelled correctly.
<INFO> [19:55:52] Update slot SPELL-CHECK-LANGUAGE to "en_GB".
<INFO> [19:55:52] Appending to "/home/pedro/.config/nyxt/auto-config.lisp":
(DEFINE-CONFIGURATION USER-BROWSER
  ((SPELL-CHECK-LANGUAGE "en_GB")))
<INFO> [19:56:00] "wrking" is incorrect.
<INFO> [19:56:07] "working" spelled correctly.
<INFO> [19:57:30] "flavor" spelled correctly.
<INFO> [19:57:34] "flavour" is incorrect.
<WARN> [19:58:03] Warning: There's a type mismatch: SPELL-CHECK-LANGUAGE should be a STRING, while you provided SYMBOL
<INFO> [19:58:12] Update slot SPELL-CHECK-LANGUAGE to "en_GB".
<INFO> [19:58:12] Appending to "/home/pedro/.config/nyxt/auto-config.lisp":
(DEFINE-CONFIGURATION USER-BROWSER
  ((SPELL-CHECK-LANGUAGE "en_GB")))
<INFO> [19:58:21] "flavor" spelled correctly.
<INFO> [19:58:27] "flavour" is incorrect.

```

**Comment by guojing0** [comment]
HI Pedro,

I am currently working on `spell-check`-related things. Does it work when you select `browser` (instead of `user-browser`) class in your third step? From the code it seems that `spell-check-language` is part of `browser` class.

**Comment by pdelfino** [comment]
> Friendly ping, @pdelfino :)

Thanks, Pierre. I forgot about this.

> HI Pedro,
> 
> I am currently working on `spell-check`-related things. Does it work when you select `browser` (instead of `user-browser`) class in your third step? From the code it seems that `spell-check-language` is part of `browser` class.

jing, sorry for answering this just now. 

I **cannot** reproduce the original bug anymore on Nyxt version 2.1.1-1423-gff069192.

When trying to follow my own recipe:
- [x] 1) execute the command describe-slot;
- [x] 2) type spell-check-language;
- [x] 3) there are two options, select the one from user-browser class;
- [x] 4) press M-return(return selection over action);
- [ ] 5) execute action describe-slot-1; -> It is **not** possible. After pressing M-return, there is just one option: the `IDENTITY`` function. 

If i try to follow your suggestion, I achieve the same scenario previous mentioned after executing `return selecion over action`, there is only the identity function available. No more opportunity for configuration.

Besides the Nyxt's version being different, my OS is not the same anymore. I migrated from Ubuntu to NixOS. Not sure if this is relevant for the problem.

**Comment by aartaka** [comment]
So, closing it then? :P
