### ISSUE TITLE
Nyxt for macOS

### ISSUE THREAD

**Issue by Raghav-Dixit** [atlas-engineer/nyxt#1772]
First of all, this is not an issue with the existing application and it has been said before.
I think making an up to date version of the browser through Homebrew or MacPorts would mean more happy users.

Right now, the three ways that I have tried to install is through `brew install --cask next`, which installs a very old version, through [this](https://github.com/incidentist/homebrew-nyxt), which resulted in a very long permission error (Homebrew cannot be run through root), and through the official MacPorts installation, which also returns an error.

**Comment by jmercouris** [comment]
Did you try the Docker image? https://github.com/deddu/nyxt-docker

**Comment by jmercouris** [comment]
That's really the best I can offer at this time... we're working hard to make it better for macOS!
