### ISSUE TITLE
Feature request: preserve tha backtick-quote notation `example' in source-code but remove it from the compiled manual (tutorial included)

### ISSUE THREAD

**Issue by pdelfino** [atlas-engineer/nyxt#1776]
In `manual.lisp`'s source code we have the following pattern with backtick-quote notation :

```lisp
(:p "A `internal-buffer' is used for Nyxt-specific, internal pages such as the
tutorial and the description pages.  A `web-buffer' is used for web pages.  Both
the `web-buffer' and the `internal-buffer' classes inherit from the `buffer'
class.")
```

This notation is useful when writing code about manual/tutorial since `slime-edit-definition` and `slime-pop-find-definition-stack` work and they are handy commands. But this notation looks like a typo when the tutorial/manual is compiled to html.

Ideally, this backtick-quote notation should be preserved in source code but omitted when compiled into HTML. I can think of some ways to do it. But they are all not elegant.

This is **not** a **priority**. But I will leave it noted here.

**Comment by aartaka** [comment]
Part of this is done for `describe-*` commands in ed97f71e66c7a4b3eea481d3bb7e5951fb88df76, but manual and tutorial will require some more work :)

**Comment by aartaka** [comment]
Manual has `:nxref`s now, and all the backtick-quote notation is removed. Closing this.
