### ISSUE TITLE
WARNING: lparallel: Replacing lost or dead worker.

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#1779]
I get the aforementioned warning on 2-series.  Any idea what's going on?  @jmercouris

**Comment by jmercouris** [comment]
I've not experienced this warning.

**Comment by Ambrevar** [comment]
I think I know where this comes from: the message is prompter with an Lparallel worker is killed manually.
This might happen because we are not using it properly, also because we have many manual threads and do some manual clean up.

If we fully switch to Lparallel it should fix this problem.

**Comment by jmercouris** [comment]
Can't reproduce.
