### ISSUE TITLE
Crashes when navigating to URLs (I only tried a couple, but most of them cause the crash)

### ISSUE THREAD

**Issue by anonimitoraf** [atlas-engineer/nyxt#1782]
**Precise recipe to reproduce the issue**
* `nyxt --verbose`
* Go to https://www.facebook.com or https://www.youtube.com
* Get "Warning Web process crashed for buffer 3"
* See these error messages in stderr/stdout:
(WebKitWebProcess:6967): Gdk-ERROR **: 21:22:10.767: The program 'WebKitWebProcess' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadValue (integer parameter out of range for operation)'.
  (Details: serial 201 error_code 2 request_code 53 (core protocol) minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
 <WARN> [21:22:11] nyxt message.lisp (echo-warning form-fun-6) -
  Warning: Web process crashed for buffer 3
<DEBUG> [21:22:11] nyxt renderer-gtk.lisp (ffi-buffer-make gtk-buffer) -
  Web process crashed for web view #<WEBKIT-WEB-VIEW {100FE721F3}>
<DEBUG> [21:22:11] nyxt base-mode.lisp (base-mode form-fun-20) -
  BASE-MODE enabled.
<DEBUG> [21:22:11] nyxt/web-mode web-mode.lisp (web-mode form-fun-28) -
  WEB-MODE enabled.
<DEBUG> [21:22:11] nyxt/certificate-exception-mode certificate-exception-mode.lisp (certificate-exception-mode form-fun-26) -
  CERTIFICATE-EXCEPTION-MODE enabled.
<DEBUG> [21:22:11] nyxt/vi-mode vi-mode.lisp (vi-normal-mode form-fun-32) -
  VI-NORMAL-MODE enabled.
<DEBUG> [21:22:11] nyxt/web-mode web-mode.lisp (add-url-to-history) -
  Notify URL about:blank for buffer #<USER-WEB-BUFFER {100A0901F3}> with load status LOADING
 <WARN> [21:22:11] nyxt message.lisp (echo-warning form-fun-6) -
  Warning: JavaScript error: GError: Domain: "WebKitJavascriptError", Code: 699, Message:

For website-specific issues:
Can you reproduce this issue with Epiphany / GNOME Web (https://wiki.gnome.org/Apps/Web)?
No

**Information**
- OS name+version: Manjaro 21.1.0 Pahvo
- Graphics card and driver: 
NVIDIA GeForce GTX 1060 6GB
VGA compatible controller: NVIDIA Corporation GP106 [GeForce GTX 1060 6GB] (rev a1)
	Subsystem: Micro-Star International Co., Ltd. [MSI] Device 8c94
	Kernel driver in use: nvidia
	Kernel modules: nouveau, nvidia_drm, nvidia
- Desktop environment / Window manager name+version: i3 version 4.19.1 (2021-02-01) © 2009 Michael Stapelberg and contributors
- How you installed Nyxt (Guix pack, package manager, build from source): Guix
- Information from `show-system-information`:
Nyxt version: 2.1.1
Renderer version: GI-GTK
Operating system kernel: Linux 5.12.19-1-MANJARO
Lisp implementation: SBCL 2.1.6
Features: (WEBKIT2 WEBKIT2-2.32 WEBKIT2-PASTE-PLAINTEXT WEBKIT2-TRACKING WEBKIT2-MUTE
 WEBKIT2-EMOJI WEBKIT2-MEDIA WEBKIT2-SANDBOXING GTK-3-22 GTK-3-20 GTK-3-18
 GTK-3-16 GTK-3-14 GTK-3-12 GTK-3-10 GTK-3-8 GTK-3-6 GTK-3-4 GTK GDK-3-22
 GDK-3-20 GDK-3-18 GDK-3-16 GDK-3-14 GDK-3-12 GDK-3-10 GDK-3-8 GDK-3-6 GDK-3-4
 CAIRO-1-10 CAIRO-1-12 GDK-PIXBUF GLIB-2-30 GLIB-2-32 GLIB-2-34 GLIB-2-36
 GLIB-2-38 GLIB-2-40 GLIB-2-42 GLIB-2-44 GLIB-2-46 GLIB-2-48 GLIB-2-50
 GLIB-2-52 GLIB-2-54 GLIB-2-56 GLIB-2-58 GLIB NYXT-2 FSET-EXT-STRINGS
 CUSTOM-HASH-TABLE-NATIVE SWANK PLUMP-UTF-32 GLOBAL-VARS DECLARE-TYPES
 PARENSCRIPT NAMED-READTABLES 21BIT-CHARS CHUNGA FLEXI-STREAMS CLOSER-MOP
 CL-PPCRE-UNICODE CL-UNICODE CL-PPCRE BORDEAUX-THREADS SPLIT-SEQUENCE
 GRAY-STREAMS FLAT-NAMESPACE X86-64 UNIX CFFI FLAT-NAMESPACE SEQUENCE-EMPTYP
 FAST-IO-SV FAST-IO SBCL-USES-SB-ROTATE-BYTE CL-JSON-CLOS CL-JSON
 THREAD-SUPPORT ASDF3.3 ASDF3.2 ASDF3.1 ASDF3 ASDF2 ASDF OS-UNIX
 NON-BASE-CHARS-EXIST-P ASDF-UNICODE X86-64 GENCGC 64-BIT ANSI-CL COMMON-LISP
 ELF IEEE-FLOATING-POINT LINUX LITTLE-ENDIAN PACKAGE-LOCAL-NICKNAMES
 SB-CORE-COMPRESSION SB-LDB SB-PACKAGE-LOCKS SB-THREAD SB-UNICODE SBCL UNIX)

ASDF version: 3.3.5
Critical dependencies: (/gnu/store/60lf8x0pl4rn2w847j2r8c6xqdcjj8g3-sbcl-cl-cffi-gtk-0.11.2-2.e9a46df/share/common-lisp/sbcl/cl-cffi-gtk/gtk/cl-cffi-gtk.asd
 /gnu/store/r7m9m734fcr6s6gabspghmin0vbx90dn-sbcl-cl-gobject-introspection-0.3-1.d0136c8/share/common-lisp/sbcl/cl-gobject-introspection/cl-gobject-introspection.asd
 /gnu/store/69y0dsbz47vnyv2yzj62jnxq37rjkraa-sbcl-cl-webkit-2.4-16.cfc4f01/share/common-lisp/sbcl/cl-webkit/webkit2/cl-webkit2.asd)

Guix version: 
(Yes, the Guix version is empty for some reason)

**Comment by aartaka** [comment]
Do you have `glib-networking` installed?

**Comment by anonimitoraf** [comment]
Yep
```
 $  pacman -Qi glib-networking
Name            : glib-networking
Version         : 1:2.68.1-1
Description     : Network extensions for GLib
Architecture    : x86_64
URL             : https://gitlab.gnome.org/GNOME/glib-networking
Licenses        : GPL2
Groups          : None
Provides        : None
Depends On      : glib2  libproxy  gnutls  gsettings-desktop-schemas
Optional Deps   : None
Required By     : lib32-glib-networking  libsoup
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 548.40 KiB
Packager        : Jan Alexander Steffens (heftig) <heftig@archlinux.org>
Build Date      : Fri 23 Apr 2021 06:13:09
Install Date    : Thu 29 Apr 2021 00:54:58
Install Reason  : Installed as a dependency for another package
Install Script  : No
Validated By    : Signature
```

**Comment by aartaka** [comment]
That is weird. Usually website access problems were caused by glib-networking.

Can you try installing in a different way and see whether the issue is reproduced there? I've a hunch that the empty Guix version has something to do with the crashes. Maybe your Guix installation got corrupted?

**Comment by anonimitoraf** [comment]
Ok, I'll try reinstalling via pacman/AUR. Would you know if there was an easy way to verify my Guix installation? (I've actually never used it before)

**Comment by anonimitoraf** [comment]
Ok, so installing nyxt via AUR doesn't cause the crashes. But when I try to connect to swank via emacs/slime, I get this error:

```
Can't locate module: SWANK-IO-PACKAGE::SWANK-INDENTATION
   [Condition of type SIMPLE-ERROR]

Restarts:
 0: [*ABORT] Return to SLIME's top level.
 1: [ABORT] abort thread (#<THREAD "worker" RUNNING {10090038B3}>)

Backtrace:
  0: (SWANK::MODULE-FILENAME SWANK-IO-PACKAGE::SWANK-INDENTATION)
  1: (SWANK:SWANK-REQUIRE (SWANK-IO-PACKAGE::SWANK-INDENTATION SWANK-IO-PACKAGE::SWANK-TRACE-DIALOG SWANK-IO-PACKAGE::SWANK-PACKAGE-FU SWANK-IO-PACKAGE::SWANK-PRESENTATIONS SWANK-IO-PACKAGE::SWANK-MACROSTE..
  2: (SB-INT:SIMPLE-EVAL-IN-LEXENV (SWANK:SWANK-REQUIRE (QUOTE (SWANK-IO-PACKAGE::SWANK-INDENTATION SWANK-IO-PACKAGE::SWANK-TRACE-DIALOG SWANK-IO-PACKAGE::SWANK-PACKAGE-FU SWANK-IO-PACKAGE::SWANK-PRESENTAT..
  3: (EVAL (SWANK:SWANK-REQUIRE (QUOTE (SWANK-IO-PACKAGE::SWANK-INDENTATION SWANK-IO-PACKAGE::SWANK-TRACE-DIALOG SWANK-IO-PACKAGE::SWANK-PACKAGE-FU SWANK-IO-PACKAGE::SWANK-PRESENTATIONS SWANK-IO-PACKAGE::S..
  4: (SWANK:EVAL-FOR-EMACS (SWANK:SWANK-REQUIRE (QUOTE (SWANK-IO-PACKAGE::SWANK-INDENTATION SWANK-IO-PACKAGE::SWANK-TRACE-DIALOG SWANK-IO-PACKAGE::SWANK-PACKAGE-FU SWANK-IO-PACKAGE::SWANK-PRESENTATIONS SWA..
  5: ((LAMBDA NIL :IN SWANK::SPAWN-WORKER-THREAD))
  6: (SWANK/SBCL::CALL-WITH-BREAK-HOOK #<FUNCTION SWANK:SWANK-DEBUGGER-HOOK> #<FUNCTION (LAMBDA NIL :IN SWANK::SPAWN-WORKER-THREAD) {52D5B93B}>)
  7: ((FLET SWANK/BACKEND:CALL-WITH-DEBUGGER-HOOK :IN "/home/anonimito/.cache/yay/nyxt/src/nyxt/_build/quicklisp-client/dists/quicklisp/software/slime-v2.26.1/swank/sbcl.lisp") #<FUNCTION SWANK:SWANK-DEBUG..
  8: ((LAMBDA NIL :IN SWANK::SPAWN-WORKER-THREAD))
  9: ((FLET SB-UNIX::BODY :IN SB-THREAD::RUN))
 10: ((FLET "WITHOUT-INTERRUPTS-BODY-11" :IN SB-THREAD::RUN))
 11: ((FLET SB-UNIX::BODY :IN SB-THREAD::RUN))
 12: ((FLET "WITHOUT-INTERRUPTS-BODY-4" :IN SB-THREAD::RUN))
 13: (SB-THREAD::RUN)
 14: ("foreign function: call_into_lisp")
 15: ("foreign function: funcall1")
```

**Comment by anonimitoraf** [comment]
No problems when installing from source :)

**Comment by aartaka** [comment]
> Ok, I'll try reinstalling via pacman/AUR. Would you know if there was an easy way to verify my Guix installation? (I've actually never used it before)

No, I haven't dug that deep, sorry.

Glad to know it's resolved now!
