### ISSUE TITLE
Nyxt installation fails on OS X Mojave: gtk3 must be installed with +quartz

### ISSUE THREAD

**Issue by mijn-design** [atlas-engineer/nyxt#1783]
System: OS X Mojave on a 2012 MacPro, 
- installed MacPorts (normally use Homebrew for all my needs), 
- installed necessary repos from Github for Nyxt installation via MacPorts,
- Nyxt installation failed 

[..]
--->  Fetching archive for webkit2-gtk-devel
--->  Attempting to fetch webkit2-gtk-devel-2.27.3_1+minibrowser+quartz.darwin_18.x86_64.tbz2 from https://packages.macports.org/webkit2-gtk-devel
--->  Attempting to fetch webkit2-gtk-devel-2.27.3_1+minibrowser+quartz.darwin_18.x86_64.tbz2 from http://aus.us.packages.macports.org/macports/packages/webkit2-gtk-devel
--->  Attempting to fetch webkit2-gtk-devel-2.27.3_1+minibrowser+quartz.darwin_18.x86_64.tbz2 from http://cph.dk.packages.macports.org/webkit2-gtk-devel
--->  Fetching distfiles for webkit2-gtk-devel
--->  Attempting to fetch webkitgtk-2.27.3.tar.xz from https://distfiles.macports.org/webkit-gtk
--->  Verifying checksums for webkit2-gtk-devel
--->  Extracting webkit2-gtk-devel
--->  Applying patches to webkit2-gtk-devel
--->  Configuring webkit2-gtk-devel
Error: Failed to configure webkit2-gtk-devel: gtk3 must be installed with +quartz.
Error: See /opt/local/var/macports/logs/_private_tmp_ports_www_webkit2-gtk-devel/webkit2-gtk-devel/main.log for details.
Error: Follow https://guide.macports.org/#project.tickets if you believe there is a bug.
Error: Processing of port nyxt failed
[..]

**Comment by tkimnguyen** [comment]
I have macOS Catalina (10.15.7) and ran into this too. The workaround was to install `gtk3 +quartz` then try the Nyxt install again:

```
sudo port install gtk3 +quartz
sudo port install www/Nyxt
```

**Comment by guojing0** [comment]
Can you run and use Nyxt after these? I am on High Sierra and couldn't.

**Comment by aadcg** [comment]
Stale.
