### ISSUE TITLE
Link hint slow-down investigation

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#1784]
It seems that the slow down is still (!) `url :around` (in `dom.lisp`), more precisely this chunk:

```lisp
      (if (valid-url-p result)
          url
          (merge-url* url (url (current-buffer))))
```

1. If we just put `(merge-url* url (url (current-buffer)))` instead, it seems to work fine since WebKitGTK understands relative URL.  @aartaka why did you deem necessary to check if the URL is valid?  Is there another case?

2. We should make `valid-url-p` faster.  Currently it checks the DNS to see if a hostname exists.  Should we have two versions, or maybe an option to skip the domain name resolution for cases where we don't need it?

3. `(defmethod prompter:object-attributes ((a nyxt/dom:a-element))` calls `url` and then renders it.  Basically, this instantiates a `quri:uri` object from a string, only to re-render it right after.  This wastes precious CPU cycles, so we can skip the `url` call and directly return the `dom:a-element` href.

Thoughts?  @jmercouris @aartaka.

**Comment by aartaka** [comment]
>     1. If we just put `(merge-url* url (url (current-buffer)))` instead, it seems to work fine since WebKitGTK understands relative URL.  @aartaka why did you deem necessary to check if the URL is valid?  Is there another case?

Well, I thought about opening things in a new buffer. If we open a relative URL in a new buffer, it will error out that URL is not right. Thus we need to complete it. However, `merge-url*` should do this check automatically, so it's really unnecessary.

>     2. We should make `valid-url-p` faster.  Currently it checks the DNS to see if a hostname exists.  Should we have two versions, or maybe an option to skip the domain name resolution for cases where we don't need it?

Yes we should! Sometimes what we need to check is the URI syntax correctness, not the existence of a location.

>     3. `(defmethod prompter:object-attributes ((a nyxt/dom:a-element))` calls `url` and then renders it.  Basically, this instantiates a `quri:uri` object from a string, only to re-render it right after.  This wastes precious CPU cycles, so we can skip the `url` call and directly return the `dom:a-element` href.

Agreed.

**Comment by Ambrevar** [comment]
Fix merged, thanks Artyom for your feedback!
