### ISSUE TITLE
how to configure init.lisp file

### ISSUE THREAD

**Issue by csfreebird** [atlas-engineer/nyxt#1791]
I want to use dark theme following this article:
https://nyxt.atlas.engineer/article/dark-theme.org

when I put three pieces of code into ~/.init.lisp, ~/.config/nyxt/init.lisp, ~/config/next/init.lisp and ~/.local/share/nyxt/init.lisp

All failed, do not work.

I cannot find the information from documentation about the location of init.lisp file for 2.x version.

**Comment by jmercouris** [comment]
The default path is located at `~/.config/nyxt/init.lisp`, the problem with that article is that it may be for a different version of Nyxt than you are running. For example `%slot-default` has been changed to `%slot-default%`.

If you look at the top right of the page, you can see that it says "Tested with Nyxt 2 pre-release 5", for different versions, we cannot guarantee that the article is correct until we update it :-D

I hope that helps!

**Comment by csfreebird** [comment]
thannk you, I changed to %slot-default%, still cannot make dark theme work.

**Comment by jmercouris** [comment]
Please take a look at some example configurations from other users, they may help you: https://discourse.atlas.engineer/c/nyxt/configuration-expose/8

**Comment by jmercouris** [comment]
The article has now been updated, please take a look again, it should work! Please feel free to reopen this issue if you have any problems.
