### ISSUE TITLE
Feature Request: Add More Options for Advanced Build Time Configuration

### ISSUE THREAD

**Issue by FOSSilizedDaemon** [atlas-engineer/nyxt#1798]
Hello,

I am becoming more and more interested in the Nyxt web browser, but there is one thing bugging me. As Nyxt grows it will undoubtedly gather more and more features and have a bigger and bigger codebase, this is only natural. That said, some users, such as myself, may not want features X, Y, and Z which are non-essential "extras".  Due to this I wanted to ask if there was any chance that more advanced build-time options for configuration could be added? Lets say, for example, someone didn't want the built-in password manager, they could simply run `./configure --disable-password-manager` causing the build system to not compile those features.

**Comment by Ambrevar** [comment]
Indeed, we've discussed such things in the past.  Other obvious examples also include support for Quicklisp or OSPM (which currently only wraps Guix).

It's easy to add such togglers with ASDF, all we need now is to agree on a workflow:

- What should the command line interface be?  Environment variables?
- We should be able to list all flags dynamically.

**Comment by Ambrevar** [comment]
@FOSSilizedDaemon Note that Nyxt major dependency is WebKitGTK.  Everything else, including the password managers, are currently optional and only looked up at runtime.  Removing _Lisp_ code from Nyxt at build time won't have a noticeable impact on size nor performance.

**Comment by Ambrevar** [comment]
Now that we've removed OSPM and Lisp-system-mode from Nyxt 3-series, this is not of much use.
However it will become relevant again once the Chrome renderer is in.

**Comment by aadcg** [comment]
I agree with you. Let's create an issue when the new renderer lands so that the new issue will have a more focused scope.

**Comment by aadcg** [comment]
I will not forget, you have my word!

 I'd rather not open an issue before the problem arises. The new renderer didn't land yet. So we'd making a bit of futurology here by getting ahead of ourselves. Who knows what can happen up till that moment.
