### ISSUE TITLE
State of the Debian package

### ISSUE THREAD

**Issue by Mestelan** [atlas-engineer/nyxt#1801]
The download page offers a package for Ubuntu, stating that:

> It will probably not work on other Debian-based distributions.

On the other hand, the 'Releases' page offers this [package](https://github.com/atlas-engineer/nyxt/releases/download/2.2.0/nyxt_2.2.0_amd64.deb), which installed all right on this 'Debian stable' box, and works fine.

Is this intended? Maybe because this package is offered as a convenience, but not fully supported?

I should also state that I was glad to locate this release package, because installing from the complete [bundle](https://nyxt.atlas.engineer/static/release/nyxt-linux-2.2.0.tar.xz) leads to various sites not working or crashing (I suspect, because of media issues). I will detail in a later comment, if relevant.

**Comment by jmercouris** [comment]
Correct, it is a convenience, but not fully supported. A user of Pop OS once reported issues with the deb installer. Do you think it is unclear where to find? Do you think we should list distributions that support Deb files?

**Comment by Mestelan** [comment]
Indeed, it is a tad confusing. Even my question was unclear, because I had not realised that the file I have linked to is the same as the Ubuntu installer. In retrospect, it is obvious, since I notice now that the link is the same; but I had thought it was maybe a 'hidden' or forsaken Debian-specific installer.

So, yes, since the Ubuntu deb installer appears to work on Debian stable (whereas the bundle has some problems, in my case), it might be worth rephrasing that warning to 'It is not guaranteed to work on all Debian-based distributions'?

**Comment by Ambrevar** [comment]
Agreed, I've just adapted the text to include your suggestion. Thanks!
Feel free to reopen if there is anything else!

**Comment by marek22k** [comment]
Is the Nyxt browser also available in the official Debian repo or does the Nyxt browser have its own repo?

**Comment by marek22k** [comment]
Ubuntu and Debian use different repos. It would therefore not be wrong to track progress in two different issues.
