### ISSUE TITLE
Feature request: make Nyxt's Lisp REPL prompt indicate the current package

### ISSUE THREAD

**Issue by pdelfino** [atlas-engineer/nyxt#1806]
The Nyxt's REPL does not indicate the package being used. It just lists
`>`. It has a similar approach to raw SBCL which indicates the prompt with `*`.

I think it would be better to have a REPL interface with the package name
being explicit, just like SLIME/Sly does, e.g. "CL-USER> ".

By leveraging Slime, this and other REPL features could be achieved.

**Comment by Ambrevar** [comment]
Done in 8cd4487ff87de6aa14ef281c51f16bb26dc7b945, thanks for the suggestion!
