### ISSUE TITLE
Feature request: create a `copy as org mode` command converting web pages (html+css) to org

### ISSUE THREAD

**Issue by pdelfino** [atlas-engineer/nyxt#1808]
Someone mentioned this experimental Firefox add-on on the nyxt IRC channel called [Copy as Org-Mode](https://addons.mozilla.org/en-US/firefox/addon/copy-as-org-mode/). I can't remember who mentioned it, sorry.

It seems to be used by few people. Also, it has the label experimental and Mozilla says this add-on "is not actively monitored for security".

I think it can serve as a good inspiration. However, with `document-model` I **guess** we can build something better (or an easier code to read). It would be possible to integrate it with #1762. But in this case, maybe it would be worth it to build our own version.

**Comment by aartaka** [comment]
There are examples of Org-compatible commands [on our Discourse](https://discourse.atlas.engineer/t/org-protocol-command/306). I'm not sure this idea belongs to Nyxt core. 

Closing this. Feel free to reopen or ping me if that doesn't feel right.
