### ISSUE TITLE
Error with slime when compiling Nyxt

### ISSUE THREAD

**Issue by aaron-tan** [atlas-engineer/nyxt#1810]
I'm facing some issues when I'm compiling my Nyxt and I'm not sure what is wrong with it.

When I run `make all` I get an end-of-file issue while loading the nyxt/gi-gtk-application with quicklisp:

```
To load "cffi":
  Load 1 ASDF system:
    cffi
; Loading "cffi"
.
To load "nyxt/gi-gtk-application":
  Load 1 ASDF system:
    nyxt/gi-gtk-application
; Loading "nyxt/gi-gtk-application"
...............;; 
;; Error loading /home/aaron/.slime/fasl/2.26.1/sbcl-2.1.7-linux-x86-64/backend.fasl:
;;   end of file on #<SB-SYS:FD-STREAM for "file /home/aaron/.slime/fasl/2.26.1/sbcl-2.1.7-linux-x86-64/backend.fasl" {10070A4643}>
;; 
Unhandled END-OF-FILE in thread #<SB-THREAD:THREAD "main thread" RUNNING
                                   {1001840173}>:
  end of file on #<SB-SYS:FD-STREAM for "file /home/aaron/.slime/fasl/2.26.1/sbcl-2.1.7-linux-x86-64/backend.fasl" {10070A4643}>

Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {1001840173}>
```
If my understanding is correct it seems that the gi-gtk-application is trying to read more data than what my backend.fasl file has hence why it gives an end-of-file error but I could be wrong. Any thoughts would be appreciated.

**Comment by Ambrevar** [comment]
Can you share the exact commands you type to trigger this issue?  Also how did you fetch Nyxt source code?

**Comment by aaron-tan** [comment]
@Ambrevar I simply tried to compile it using `make all` and that's the error that it throws. The lisp repl I'm using is sbcl.



I fetched the source code from here on GitHub. I made a fork of it and I cloned it into my local repository
