### ISSUE TITLE
FreeBSD build failure: lfp.h not found even with libfixposix installed

### ISSUE THREAD

**Issue by steewbsd** [atlas-engineer/nyxt#1820]
**Describe the bug**
I cannot succesfully compile nyxt on FreeBSD 13.0 STABLE amd64, after installing all dependencies as the wiki says.
It complains about not finding the lfp.h library, corresponding to libfixposix, which is indeed installed (and I reinstalled it to be sure) and present in /usr/local/include/lfp.h
**Precise recipe to reproduce the issue**
1. clone a clean repo
2. gmake all
3. build fails with lfp.h not found
For website-specific issues:
Can you reproduce this issue with Epiphany / GNOME Web (https://wiki.gnome.org/Apps/Web)?
Does not apply
**Information**
- OS name+version: FreeBSD 13.0 STABLE amd64 (custom kernel)
- Graphics card and driver: AMD Renoir integrated graphics, drm-kmod
- Desktop environment / Window manager name+version: Wayland/Wayfire
- How you installed Nyxt (Guix pack, package manager, build from source): Build from source
- Information from `show-system-information`:

  If you can't run `show-system-information`, try `nyxt --system-information` from
  a shell.  It this still does not work, please provide the following:
  - Nyxt version (from the `nyxt-version` command or `nyxt --version` from a shell):
  - Lisp implementation/version (if built from source): scbl 2.1.9,1
  - Kernel name+version: FreeBSD 13.0 STABLE
  - WebKitGTK+ | QtWebEngine version: webkit2-gtk3 2.34.0

**Output when started from a shell**
![libfixposix output](http://0x0.st/-kJ4.png)
![error message](http://0x0.st/-kJJ.png)

**Comment by Ambrevar** [comment]
` cffi:*foreign-library-directories*` is for the library object files (the `.so`), not the headers (the `lph.h` here).
The problem does not seem to be with Lisp but with your C compiler which does not know the `/usr/local/include` path.  Refer to your FreeBSD manual on how to fix this.

In the meantime, try the following hack:

```sh
export C_INCLUDE_PATH="/usr/local/include:$C_INCLUDE_PATH"
```

then repeat the build commands (in the same shell).

**Comment by shiorid** [comment]
As a matter of fact, `/usr/local` (known on BSDs as LOCALBASE) isn't part of the default `clang` include path.
This problem affects both FreeBSD and OpenBSD, since DragonFly uses `gcc` (which includes LOCALBASE on path) and NetBSD uses `pkgsrc` (which I know nothing about).

I've submitted a [merge request](https://github.com/sionescu/iolib/pull/74) with the fix on `iolib`. Feel free to try the patch!

Sorry for the _necrobumping_.
