### ISSUE TITLE
Can't build from source: function make-search-completion-function specified with the invalid * type-specifier

### ISSUE THREAD

**Issue by lpaviets** [atlas-engineer/nyxt#1822]
**Describe the bug**
Trouble building Nyxt from source, using Ubuntu 20.04
Error comes from the file `search-engine.list`, where the function `make-search-completion` uses an invalid type specifier:

; compiling file "/home/my-user-name/from_source/nyxt/source/search-engine.lisp" (written 17 OCT 2021 09:18:42 PM):
; processing (IN-PACKAGE :NYXT)
; processing (DEFINE-CLASS SEARCH-ENGINE ...)
; processing (DEFMETHOD FALLBACK-URL ...)
; processing (EXPORT-ALWAYS (QUOTE MAKE-SEARCH-ENGINE))
; processing (DEFUN MAKE-SEARCH-ENGINE ...)
; processing (EXPORT-ALWAYS (QUOTE MAKE-SEARCH-COMPLETION-FUNCTION))
; processing (-> MAKE-SEARCH-COMPLETION-FUNCTION ...)Unhandled SIMPLE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING
                                    {10018682D3}>:
  * is not permitted as an argument to the FUNCTION type specifier

If we check the code, we indeed have, in the aforementioned file:
```
(-> make-search-completion-function
    (&key (:base-url string)
          (:request-function (function (string &rest *) *))
          (:request-args list)
          (:processing-function (function (*) list-of-strings)))
    (function (string) list-of-strings))
 ```
(Compiling `master` branch)

I was not aware of this specific restriction for type specifiers, but it seems that it is indeed correct: the following toy example produces the same error, using SBCL 2.1.9
```
(defun test-fun (x)
           (declare (ftype (function (*) list) test-fun))
           (list x))
```

**Precise recipe to reproduce the issue**
Compile master branch from source using SBCL 2.1.9, with the `make all` command. 

For website-specific issues:
Can you reproduce this issue with Epiphany / GNOME Web (https://wiki.gnome.org/Apps/Web)?

**Information**
- OS name+version: Ubuntu 20.04 focal
- Graphics card and driver: GeForce GTX 970 - nvidia-470.63.01
- Desktop environment / Window manager name+version: Gnome 3.36.5
- How you installed Nyxt (Guix pack, package manager, build from source): Build from source
- Information from `show-system-information`:

  If you can't run `show-system-information`, try `nyxt --system-information` from
  a shell.  It this still does not work, please provide the following:
  - Nyxt version (from the `nyxt-version` command or `nyxt --version` from a shell):
  - Lisp implementation/version (if built from source): SBCL 2.1.9
  - Kernel name+version: 
  - WebKitGTK+ | QtWebEngine version:

**Output when started from a shell**

**Comment by aartaka** [comment]
Done in 3fbcdb5.
