### ISSUE TITLE
blocker-mode (Ad-blocking) not working

### ISSUE THREAD

**Issue by e0a6** [atlas-engineer/nyxt#1824]
I enabled `blocker-mode` (as indicated by the built in Tutorial and Manual) but I still get ads on all websites I visit.
Am I missing some step (ie some configuraton, etc) that needs to be completed for ad-blocking to work?

**Precise recipe to reproduce the issue**
1. Install GNU Guix (OS)
2. Install Nyxt via Guix Package manager (`guix install nyxt`)
3. Open Nyxt and enable `blocker-mode`
4. Navigate to a webpage with ads

**Some Examples**
- [BBC](https://user-images.githubusercontent.com/76806725/137902027-dba76f47-d3e1-4f67-ac48-81658f32003e.png)
- [EuroNews](https://user-images.githubusercontent.com/76806725/137902053-07d55157-768a-46af-8955-92101b96d157.png)

**Information**
- GNU Guix
- XFCE
- Installed via Guix package manager (`guix intall nyxt`)

**Output from `nyxt --system information` command**
`Nyxt version: 2.2.0`
`Renderer version: GI-GTK`
`Operating system kernel: Linux 5.14.8`
`Lisp implementation: SBCL 2.1.9 (Dynamic space size: 3221225472)`
`Features: (:WEBKIT2 :WEBKIT2-2.32 :WEBKIT2-PASTE-PLAINTEXT :WEBKIT2-TRACKING`
` :WEBKIT2-MUTE :WEBKIT2-EMOJI :WEBKIT2-MEDIA :WEBKIT2-SANDBOXING :GTK-3-22`
` :GTK-3-20 :GTK-3-18 :GTK-3-16 :GTK-3-14 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6`
` :GTK-3-4 :GTK :GDK-3-22 :GDK-3-20 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12`
` :GDK-3-10 :GDK-3-8 :GDK-3-6 :GDK-3-4 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF`
` :GLIB-2-30 :GLIB-2-32 :GLIB-2-34 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42`
` :GLIB-2-44 :GLIB-2-46 :GLIB-2-48 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56`
` :GLIB-2-58 :GLIB :NYXT-2 :FSET-EXT-STRINGS :CUSTOM-HASH-TABLE-NATIVE :SWANK`
` :PLUMP-UTF-32 :GLOBAL-VARS :DECLARE-TYPES :PARENSCRIPT :NAMED-READTABLES`
` :LPARALLEL :21BIT-CHARS :CHUNGA :FLEXI-STREAMS :CLOSER-MOP :CL-PPCRE-UNICODE`
` :CL-UNICODE :CL-PPCRE :BORDEAUX-THREADS :LPARALLEL.WITH-CLTL2`
` :LPARALLEL.WITH-CAS :LPARALLEL.WITH-STEALING-SCHEDULER :SPLIT-SEQUENCE`
` CHIPZ-SYSTEM:GRAY-STREAMS CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64`
` CFFI-FEATURES:UNIX :CFFI CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP`
` :FAST-IO-SV :FAST-IO :SBCL-USES-SB-ROTATE-BYTE :CL-JSON-CLOS :CL-JSON`
` :THREAD-SUPPORT :ASDF3.3 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX`
` :NON-BASE-CHARS-EXIST-P :ASDF-UNICODE :X86-64 :GENCGC :64-BIT :ANSI-CL`
` :COMMON-LISP :ELF :IEEE-FLOATING-POINT :LINUX :LITTLE-ENDIAN`
` :PACKAGE-LOCAL-NICKNAMES :SB-CORE-COMPRESSION :SB-LDB :SB-PACKAGE-LOCKS`
` :SB-THREAD :SB-UNICODE :SBCL :UNIX)`

`ASDF version: 3.3.5`
`Critical dependencies: (/gnu/store/drmb9c35fm70d1xl67mvdr03swq4lljj-sbcl-cl-cffi-gtk-0.11.2-2.e9a46df/share/common-lisp/sbcl/cl-cffi-gtk/gtk/cl-cffi-gtk.asd`
` /gnu/store/qw6gj6xy7vsmw6117096dr96q4l6iwbr-sbcl-cl-gobject-introspection-0.3-1.d0136c8/share/common-lisp/sbcl/cl-gobject-introspection/cl-gobject-introspection.asd`
` /gnu/store/yqwj0dnpplkgfvhh3pmmp5589ykqlww3-sbcl-cl-webkit-3.0.0/share/common-lisp/sbcl/cl-webkit/webkit2/cl-webkit2.asd)`

`Guix version: `

**Output when started from a shell**
`<INFO> [05:32:00] Listening to socket "/run/user/1000/nyxt/nyxt.socket".`
`Nyxt version 2.2.0`
`<INFO> [05:32:00] Loading Lisp file "/home/ak/.config/nyxt/init.lisp".`

**Comment by aartaka** [comment]
`blocker-mode` most probably does work. It's just that it's host based and cannot block everything on the page.

**Comment by Ambrevar** [comment]
#1869 also fixes many more issues.  Feel free to reopen if there is anything else.
