### ISSUE TITLE
Nyxt makefile not installing submodules

### ISSUE THREAD

**Issue by WilliamBehrens** [atlas-engineer/nyxt#1829]
**Describe the bug**
When running `make all` in version 2.0.0 nyxt would fetch all it's own submodules but now in version 2.2.1 I get an error saying that the module Alexadria cannot be found as well as no indecation that the make file installed any other modules. I'm not sure if this is a bug or if the build system between the versions changed. 

**Precise recipe to reproduce the issue**
`make all`

**Information**
- OS name+version: Voidlinux
- Desktop environment / Window manager name+version: sway
- How you installed Nyxt (Guix pack, package manager, build from source): source

**Comment by dtw-waleee** [comment]
@WilliamBehrens ping new release with the mentioned submodule src tarball :)

**Comment by WilliamBehrens** [comment]
@dtw-waleee updating the package now :)
