### ISSUE TITLE
Next do not remember last position of a just visited page

### ISSUE THREAD

**Issue by easbarbosa** [atlas-engineer/nyxt#183]
Hi, As we go back in history (c-b), most browsers recall the last position of the just visited page the user was reading. 

Next seems not be able to do it or it's a bug! 

:hamster:

**Comment by Ambrevar** [comment]
I think this has to be implemented explicitly, it just hasn't  been done yet! ;)

**Comment by jmercouris** [comment]
@Ambrevar you are correct

**Comment by jmercouris** [comment]
This is now fixed by using the renderer cache.

**Comment by Ambrevar** [comment]
I suggest we leave this open, or open a new issue so that we remember the position of all pages in history.
Should be trivial.

**Comment by jmercouris** [comment]
I don't like having so many issues open, I find it paralyzing, this issue is more or less solved in my opinion.

**Comment by jmercouris** [comment]
Ay yai yai :-D
