### ISSUE TITLE
Redirects are mistakenly not stored into history

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#1843]
Recipe:

- `set-url` to `wiki tomato`
- Run `history-all-query` and notice that the current URL is missing.

@aartaka This is due to https://github.com/atlas-engineer/nyxt/commit/99c8f81a5164a11709ea7eb820b841f9c946f29d.  Indeed, `:webkit-load-redirected` may be sent for the final URL (I don't know why, either a server thing or a WebKit bug).

That said, I don't understand your patch.  We only store to history on `load-finished`, that is, with the final URL, so why would we need to blacklist redirected URLs?

**Comment by aartaka** [comment]
Oh wait! I've got it wrong! The `:webkit-load-redirected` URL is the final result of redirection, while the URL to not store in history is the one that came before the redirection. It's more complex than I thought. I suggest we revert 99c8f81 and approach redirections in a smarter way, altering history after the fact of redirection.

**Comment by aartaka** [comment]
> That said, I don't understand your patch. We only store to history on `load-finished`, that is, with the final URL, so why would we need to blacklist redirected URLs?

Do we? We also do it in `nyxt:on-signal-notify-uri`/`notify::uri`, where the filtering is most needed, as notified URLs often contain redirection URLs and other junk, as contrasted to those in `load-finished` signal.

**Comment by aartaka** [comment]
So, what I suggest is:
- When we get a `:webkit-load-redirected` load status, we look at most recent URL in the buffer history.
- We delete this most recent URL.
- Westore to history the URL that came along with `:webkit-load-redirected` signal, as this is most likely the final result of redirection.

While this breaks the immutability of `htree`, we need to do the change after we actually added a redirection URL to history. The information on it being a redirection URL is only available later, when `:webkit-load-redirected` happens, thus the delay.

**Comment by Ambrevar** [comment]
> Do we? We also do it in nyxt:on-signal-notify-uri/notify::uri, where the filtering is most needed, as notified URLs often contain redirection URLs and other junk, as contrasted to those in load-finished signal.

Good point!
