### ISSUE TITLE
Nyxt 2.2.2 crashes when making a search on void linux

### ISSUE THREAD

**Issue by WilliamBehrens** [atlas-engineer/nyxt#1845]
**Describe the bug**
I built nyxt from source on void linux and ran the resulting binary, I then tried to open a new url by searching something in the prompt. I then get the error 
```
** (nyxt:19374): ERROR **: 14:19:56.352: GApplication is required for xdg-desktop-portal access in the WebKit sandbox.
<WARN> [14:19:56] Warning: Error on GTK thread: The value
                       NIL
                     is not of type
                       SB-KERNEL:CODE-COMPONENT

** (process:19374): ERROR (recursed) **: GApplication is required for xdg-desktop-portal access in the WebKit sandbox.fatal error encountered in SBCL pid 19374 tid 19407:
SIGABRT received.

   0: fp=0x2 pc=0x7f572338ff81 Foreign function gsignal
```
and upon pressing enter again it crashes

**Precise recipe to reproduce the issue**
build nyxt 2.2.2 from source
with vi keybinds press `o` to open a new search prompt
look something up and press enter

**Information**
- OS name+version: Voidlinux, kernel 5.13.19_1
- Graphics card and driver: radeon 5500xt, xf86-video-amdgpu-21.0.0_1
- Desktop environment / Window manager name+version: sway-1.6.1_1
- How you installed Nyxt (Guix pack, package manager, build from source): from source
- Information from `show-system-information`:
```
Nyxt version: 2.2.2
Renderer version: GI-GTK
Operating system kernel: Linux 5.13.19_1
Lisp implementation: SBCL 2.1.9 (Dynamic space size: 1073741824)
Features: (:WEBKIT2 :WEBKIT2-2.34 :WEBKIT2-PASTE-PLAINTEXT :WEBKIT2-TRACKING
 :WEBKIT2-MUTE :WEBKIT2-EMOJI :WEBKIT2-MEDIA :WEBKIT2-SANDBOXING :GTK-3-22
 :GTK-3-20 :GTK-3-18 :GTK-3-16 :GTK-3-14 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6
 :GTK-3-4 :GTK :GDK-3-22 :GDK-3-20 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12
 :GDK-3-10 :GDK-3-8 :GDK-3-6 :GDK-3-4 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF
 :GLIB-2-30 :GLIB-2-32 :GLIB-2-34 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42
 :GLIB-2-44 :GLIB-2-46 :GLIB-2-48 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56
 :GLIB-2-58 :GLIB :NYXT-2 :FSET-EXT-STRINGS :CUSTOM-HASH-TABLE-NATIVE :SWANK
 :PLUMP-UTF-32 :GLOBAL-VARS :DECLARE-TYPES :PARENSCRIPT
 :SBCL+SAFE-STANDARD-READTABLE :NAMED-READTABLES :LPARALLEL :21BIT-CHARS
 :CHUNGA :CLOSER-MOP :CL-PPCRE-UNICODE :FLEXI-STREAMS :CL-UNICODE :CL-PPCRE
 :CL-JSON-DOUBLE-FLOAT-IS-SUBSUMED :CL-JSON-SINGLE-FLOAT-IS-SUBSUMED
 :BORDEAUX-THREADS :LPARALLEL.WITH-CLTL2 :LPARALLEL.WITH-CAS
 :LPARALLEL.WITH-STEALING-SCHEDULER :SPLIT-SEQUENCE CHIPZ-SYSTEM:GRAY-STREAMS
 CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64 CFFI-FEATURES:UNIX :CFFI
 CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP :FAST-IO-SV :FAST-IO
 :SBCL-USES-SB-ROTATE-BYTE :CL-JSON-CLOS :CL-JSON :THREAD-SUPPORT :ASDF3.3
 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX :NON-BASE-CHARS-EXIST-P
 :ASDF-UNICODE :X86-64 :GENCGC :64-BIT :ANSI-CL :COMMON-LISP :ELF
 :IEEE-FLOATING-POINT :LINUX :LITTLE-ENDIAN :PACKAGE-LOCAL-NICKNAMES
 :SB-CORE-COMPRESSION :SB-LDB :SB-PACKAGE-LOCKS :SB-THREAD :SB-UNICODE :SBCL
 :UNIX)

ASDF version: 3.3.1
ASDF registries: (NYXT-SOURCE-REGISTRY ENVIRONMENT-SOURCE-REGISTRY)
Critical dependencies: (/home/will/Code/Temp/_build/cl-cffi-gtk/gtk/cl-cffi-gtk.asd
 /home/will/Code/Temp/_build/cl-gobject-introspection/cl-gobject-introspection.asd
 /home/will/Code/Temp/_build/cl-webkit/webkit2/cl-webkit2.asd)
```
**Output when started from a shell**
```
<INFO> [14:19:52] Listening to socket "/run/user/1000/nyxt/nyxt.socket".
Nyxt version 2.2.2
<INFO> [14:19:52] Loading Lisp file "/home/will/.config/nyxt/init.lisp".

(process:19447): GLib-Net-WARNING **: 14:19:52.440: ../tls/gnutls/gtlscertificate-gnutls.c:161: invalid property id 4 for "private-key-pem" of type 'GParamString' in 'GTlsCertificateGnutls'
<INFO> [14:19:53] Loading 5 bookmarks from "/home/will/.local/share/nyxt/bookmarks.lisp".
<WARN> [14:19:53] History version "2.0.0" differs from current version "2.2.2"
<INFO> [14:19:53] Loading history of 509 URLs from "/home/will/.local/share/nyxt/history/default.lisp".
```

**Comment by fbmnds** [comment]
Same here. I suspect that the reason is relateed to the following update per 02.11.2021:

```
Start-Date: 2021-11-02  18:33:59
Commandline: apt upgrade
Requested-By: 
Upgrade: libjavascriptcoregtk-4.0-dev:amd64 (2.32.4-0ubuntu0.20.04.1, 2.34.1-0ubuntu0.20.04.1), libwebkit2gtk-4.0-37:amd64 (2.32.4-0ubuntu0.20.04.1, 2.34.1-0ubuntu0.20.04.1), gir1.2-webkit2-4.0:amd64 (2.32.4-0ubuntu0.20.04.1, 2.34.1-0ubuntu0.20.04.1), libjavascriptcoregtk-4.0-18:amd64 (2.32.4-0ubuntu0.20.04.1, 2.34.1-0ubuntu0.20.04.1), libwebkit2gtk-4.0-dev:amd64 (2.32.4-0ubuntu0.20.04.1, 2.34.1-0ubuntu0.20.04.1), gir1.2-javascriptcoregtk-4.0:amd64 (2.32.4-0ubuntu0.20.04.1, 2.34.1-0ubuntu0.20.04.1)
End-Date: 2021-11-02  18:34:04
```

**Comment by Ambrevar** [comment]
Probably the same as #1840, stay tuned we are going to post a patch soon.

**Comment by dtw-waleee** [comment]
@WilliamBehrens @fbmnds I had the exact same error on clearlinux after it updated webkit2gtk to 2.34 and introduced a compatibility `.so` for 2.33. The stopgap measure that worked for me was to  build nyxt with the gtk-renderer instead of the gi-gtk one, (if you build with the makefile, `NYXT_RENDERER=gtk make ... `).

**Comment by WilliamBehrens** [comment]
@dtw-waleee That didn't fix it, same issue. I'll wait for the patch

**Comment by WilliamBehrens** [comment]
@Ambrevar When you say you're going to post a patch where do you post them? like a patch file or is it just going to be a pr?

**Comment by fbmnds** [comment]
@dtw-waleee same issue with `gtk` like @WilliamBehrens. Is there perhaps an additional dependency to be considered?

**Comment by fbmnds** [comment]
I had to update `quicklisp` in order to have the dependency on `cluffer` resolved, but still no success with version 2.2.2. I decided to downgrade to 2.2.0 which works.

I guess, issue #1855 is related.

**Comment by guojing0** [comment]
I downgraded to 2.2.0 and still could not get X11 window displayed when building from source :)

**Comment by fbmnds** [comment]
I had to clean up the `fasl` files under `/home/dev/.cache/common-lisp/sbcl-2.0.1.debian-linux-x64/home/dev/projects/nyxt/_build/` in order to get a working binary.

**Comment by guojing0** [comment]
@fbmnds Thank you for the advice. Still same as I mentioned in #1855 :)

**Comment by Ambrevar** [comment]
@WilliamBehrens The fix is going to be posted as a PR or directly merged onto `master` / `2-series`.

**Comment by Ambrevar** [comment]
The issue seems to be related to the recent WebKitGTK 2.34 update.

**Comment by ag91** [comment]
as a workaround, run this in your terminal `export WEBKIT_FORCE_SANDBOX=0`

**Comment by Ambrevar** [comment]
All WebKitGTK 2.34-related hangs / crashes should be fixed on master since https://github.com/atlas-engineer/nyxt/commit/c2f1e613f34f1f24d83ab715de2bcb5914f2736e.

We had to stop enforcing the sandboxing though.  We are tackling this in a separate issue, see https://github.com/atlas-engineer/nyxt/issues/1781.
