### ISSUE TITLE
Abilty to hook into other tools for downloading and other stuff

### ISSUE THREAD

**Issue by PlasmaShift** [atlas-engineer/nyxt#185]
I nice feature that I don't really see that would be nice to see is the ability to hook into other projects for more flexability / performance enhancements. An Idea for downloads would be something similar to https://addons.mozilla.org/en-US/firefox/addon/aria2-integration/ using aria2 for speed performance and https://github.com/mayswind/AriaNg for the UI. This shouldn't exclude the reason to have a native download manager though for less dependices, although the ability to change it to change the download to something like this would be nice.

Other examples of this in Emacs would be using ripgrep to increase grep speed like here https://oremacs.com/2017/08/04/ripgrep/

Mostly I want this idea out there before all the work is set in stone for downloading

**Comment by jmercouris** [comment]
@PlasmaShift this is an interesting idea for consideration! Thank you for bringing it up! When designing how the download manager will work, we’ll try to think of how we can make it extensible and connectible with other tools. After all the “EXT” in “nEXT” used to stand for “extension” :D

**Comment by jmercouris** [comment]
@PlasmaShift on a completely unrelated note, but since I have no other way of contacting you, I remember that you were one of the first people to star the project. How has your experience been with Next? have you had a chance to try it out?

**Comment by PlasmaShift** [comment]
A little bit on my thinkpad using guix, maybe an hour so far and only on stock settings. Mostly I am keeping an eye on it. At the moment I don't have a linux computer my thinkpad got water damage :( so I have to bring up my desktop on linux or bsd, don't think bsd has guix support though.

But so far I like it just rough around the edges

**Comment by jmercouris** [comment]
That would be actually very interesting to know if you can get it to compile on BSD, it should work, and you should be able to build it rather easily from source, not using guix or anything

**Comment by Ambrevar** [comment]
Generally speaking, Next can be plugged onto any program since it's a full-blown
Common Lisp program.  For instance, you can use `(uiop:run-program ...)` from
the user configuration file.

Regarding download management, I can imagine the following implementation:  the
download buffer would display a list of downloads in progress, and each download
uses a specific download source (HTTP, torrent, etc.).  The supported download
sources could then easily be extended (e.g. to use Aria2 instead of pure Common Lisp).

**Comment by Ambrevar** [comment]
We now have a native download manager integrated into Next.  Note that it supports multiple backends, using a Common Lisp native backend by default.
Patches to add support for other backends (wget/curl, aria, transmission, etc.) are welcome!

**Comment by Ambrevar** [comment]
And we now have hooks, including the `after-download-hook` and `before-download-hook` which should allow you to do anything you want.

**Comment by impaktor** [comment]
(possibly this might be closed, depending on what functionality currently is available compared to original post)

**Comment by jmercouris** [comment]
What is suggested in the original post is currently possible!

**Comment by Ambrevar** [comment]
It would be nice to document / implement the suggested examples though.

**Comment by jmercouris** [comment]
Agreed.

**Comment by QiangF** [comment]
Just for your info, there is a firefox plugin that does this
https://github.com/RossWang/Aria2-Integration/

**Comment by Ambrevar** [comment]
Our current download manager is very ad-hoc.
I suggest a complete rewrite with support for multiple backends, e.g.
- Next (pure Common Lisp)
- The renderer (e.g. WebKitGTK)
- curl, wget
- youtube-dl
- your torrent downloader
- etc.

We need a uniform way to start, stop, list, show progress for all downloads.

**Comment by jmercouris** [comment]
That sounds like quite a task, not sure it is a 'good-first-issue', it is however well isolated in terms of the fact that we can declare a clear API.

**Comment by Ambrevar** [comment]
Indeed!

**Comment by jmercouris** [comment]
We've done most things here.
