### ISSUE TITLE
"Page could not be loaded" when going back and forth in history

### ISSUE THREAD

**Issue by Shadesfear** [atlas-engineer/nyxt#1854]
Sometimes when going back and forth in history I get the "Page could not be loaded"

This does not happen when going to new links, only when invoking history-backwards or history-forwards. It doesnt seem to be concistent over all websites / sessions. 

I can reproduce the error by doing the follow:

- Go to https://google.com
- Do a search (I searched 'aur')
- Invoke set-url-new-buffer to navigate to top hit
- invoke history-backwards

OS: Manjaro Linux x86_64 
Host: 20UH001GMX ThinkPad T14s Gen 1 
Kernel: 5.10.70-1-MANJARO 
WM: i3 
CPU: AMD Ryzen 5 PRO 4650U with Radeon Graphics (12) @ 2.100GHz 
                               GPU: AMD ATI 06:00.0 Renoir 
                               

Nyxt was installed through the aur

When running nyxt from the terminal when I get the "Page could not be loaded" message I see a 'Failed to load URL', and afterwards a 'Finished loading' message

Nyxt version output:

Nyxt version: 2.2.2
Renderer version: GI-GTK
Operating system kernel: Linux 5.10.70-1-MANJARO
Lisp implementation: SBCL 2.1.9 (Dynamic space size: 1073741824)
Features: (:WEBKIT2 :WEBKIT2-2.32 :WEBKIT2-PASTE-PLAINTEXT :WEBKIT2-TRACKING
 :WEBKIT2-MUTE :WEBKIT2-EMOJI :WEBKIT2-MEDIA :WEBKIT2-SANDBOXING :GTK-3-22
 :GTK-3-20 :GTK-3-18 :GTK-3-16 :GTK-3-14 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6
 :GTK-3-4 :GTK :GDK-3-22 :GDK-3-20 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12
 :GDK-3-10 :GDK-3-8 :GDK-3-6 :GDK-3-4 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF
 :GLIB-2-30 :GLIB-2-32 :GLIB-2-34 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42
 :GLIB-2-44 :GLIB-2-46 :GLIB-2-48 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56
 :GLIB-2-58 :GLIB :NYXT-2 :FSET-EXT-STRINGS :CUSTOM-HASH-TABLE-NATIVE :SWANK
 :PLUMP-UTF-32 :GLOBAL-VARS :DECLARE-TYPES :PARENSCRIPT
 :SBCL+SAFE-STANDARD-READTABLE :NAMED-READTABLES :LPARALLEL :21BIT-CHARS
 :CHUNGA :CLOSER-MOP :CL-PPCRE-UNICODE :FLEXI-STREAMS :CL-UNICODE :CL-PPCRE
 :CL-JSON-DOUBLE-FLOAT-IS-SUBSUMED :CL-JSON-SINGLE-FLOAT-IS-SUBSUMED
 :BORDEAUX-THREADS :LPARALLEL.WITH-CLTL2 :LPARALLEL.WITH-CAS
 :LPARALLEL.WITH-STEALING-SCHEDULER :SPLIT-SEQUENCE CHIPZ-SYSTEM:GRAY-STREAMS
 CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64 CFFI-FEATURES:UNIX :CFFI
 CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP :FAST-IO-SV :FAST-IO
 :SBCL-USES-SB-ROTATE-BYTE :CL-JSON-CLOS :CL-JSON :THREAD-SUPPORT :ASDF3.3
 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX :NON-BASE-CHARS-EXIST-P
 :ASDF-UNICODE :X86-64 :GENCGC :64-BIT :ANSI-CL :COMMON-LISP :ELF
 :IEEE-FLOATING-POINT :LINUX :LITTLE-ENDIAN :PACKAGE-LOCAL-NICKNAMES
 :SB-CORE-COMPRESSION :SB-LDB :SB-PACKAGE-LOCKS :SB-THREAD :SB-UNICODE :SBCL
 :UNIX)

ASDF version: 3.3.1
ASDF registries: (NYXT-SOURCE-REGISTRY ENVIRONMENT-SOURCE-REGISTRY)
Critical dependencies: (/home/chris/.cache/yay/nyxt/src/nyxt/_build/cl-cffi-gtk/gtk/cl-cffi-gtk.asd
 /home/chris/.cache/yay/nyxt/src/nyxt/_build/cl-gobject-introspection/cl-gobject-introspection.asd
 /home/chris/.cache/yay/nyxt/src/nyxt/_build/cl-webkit/webkit2/cl-webkit2.asd)

**Comment by Ambrevar** [comment]
Thanks for reporting and good news, I believe this has just been fixed.
You can try it out on the `2-series` branch or just wait for the next release, shouldn't take long :)

**Comment by Ambrevar** [comment]
2.2.3 released!
Closing this since it should be fixed now.  Feel free to reopen if there is anything else.
