### ISSUE TITLE
Feature idea: Having a FAQ page for users and developers?

### ISSUE THREAD

**Issue by guojing0** [atlas-engineer/nyxt#1857]
Hi,

In the process of building and installing Nyxt, I found [the developer README](https://github.com/atlas-engineer/nyxt/blob/master/documents/README.org) to be really useful. The [issues](https://github.com/atlas-engineer/nyxt/issues) also contain many helpful hints and solutions.

However, I found out that similar questions and answers have appeared several times, such as

1. Installing `webkit2-gtk(-devel)` instead of `webkit-gtk3` 
2. Put `(ql:quickload :cffi)
(pushnew "/opt/local/lib/" cffi:*foreign-library-directories* :test #'equal)` inside `.sbclrc` file

and so on...

So I was wondering that, to help future users and developers save time from searching the issues, maybe we could set up a FAQ page under either the README or developer README? So that before a new user/developer asks another issue, he could have the chance to test out possible solutions that were carried out in the past?

Example: [MacPorts FAQ](https://trac.macports.org/wiki/FAQ)

**Comment by Ambrevar** [comment]
Should the developer's readme just be extended to include these frequently occurring bumps?

**Comment by guojing0** [comment]
Yes, it's another approach.
