### ISSUE TITLE
README: Broken link in "Getting started - Install Nyxt" to "MacPorts"

### ISSUE THREAD

**Issue by guojing0** [atlas-engineer/nyxt#1860]
Similar to the issue in #1115, the link to MacPorts in the main README is

https://source.atlas.engineer/view/repository/macports-port

which seems to be broken. I think correct link is the following?

https://github.com/atlas-engineer/ports

Update: Fixed https://github.com/atlas-engineer/nyxt/pull/1859/commits/341fbf900875dc1ff91cd69830c32422c2893ae2 in PR #1859

**Comment by Ambrevar** [comment]
Fixed with #1859.
