### ISSUE TITLE
Introspection?

### ISSUE THREAD

**Issue by daraul** [atlas-engineer/nyxt#1864]
The emacs crowd will know this is when the application affords users the ability to inspect functions, variables, etc. Does nyxt have this? I did a quick searx and couldn't find any relevant docs. If not then I believe some functions like these could be invaluable.

**Comment by aartaka** [comment]
The functions are `describe-function`, `describe-variable`, `describe-class`, `describe-slot`, `describe-command`, `describe-key`, and `describe-any`. In case of commands (and functions/methods Nyxt has access to the source code of), it lists the source code. There are things to improve there, obviously, and for that there is for example #1084.

**Comment by daraul** [comment]
Cool! I'll close this, then.
