### ISSUE TITLE
Fetching hostlists for blocker-mode hangs Nyxt for a short moment

### ISSUE THREAD

**Issue by aartaka** [atlas-engineer/nyxt#1867]
We need to offload hostlist updating to a separate thread to avoid interface unresponsiveness.

**Comment by guojing0** [comment]
By "offload" do you mean to create another thread (for updating hostlist), so that it would not cause interface unresponsiveness?

**Comment by aartaka** [comment]
> By "offload" do you mean to create another thread (for updating hostlist), so that it would not cause interface unresponsiveness?

Exactly.

**Comment by aartaka** [comment]
An alternative/addition that we discussed with @jmercouris on IRC is to use a faster data structure (e.g. hash table). Storing hostlists in a faster structure will speed up the host search and all the `blocker-mode` uses consequently.

**Comment by Ambrevar** [comment]
In my experience, it hangs Nyxt indefinitely.  See for a fix: https://github.com/atlas-engineer/nyxt/pull/1869.

**Comment by aartaka** [comment]
Wow, thanks for that, Pierre!

**Comment by Ambrevar** [comment]
Fixed with #1869.
