### ISSUE TITLE
Inconsistent URL-related bindings

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#1870]
`C-l` stands for `set-url` and it matches what popular browsers bind `C-l` to.
`l` could be argued to stand for "location".

This is why we've got `M-c l` for `copy-url`.

But then we are not consistent elsewhere, like with `C-m u` and `C-x r u` which are bound to `bookmark-url`.

Any other inconsistent bindings?
Thoughts about how to make them consistent?
@jmercouris @pdelfino @aartaka

**Comment by aartaka** [comment]
`base-mode` has `C-M-i` for `copy-title` in Emacs bindings. This is inconsistent with other bindings' `t`.

**Comment by aartaka** [comment]
The reasoning about `l` does make sense, let's stick with it!

**Comment by Ambrevar** [comment]
Good catch!

Shall we update these bindings on `2-series` as well?  I'd lean towards a "yes", but on `2-series` we could also keep the old bindings for backward-compatibility.

**Comment by aartaka** [comment]
> Good catch!
> 
> Shall we update these bindings on `2-series` as well? I'd lean towards a "yes", but on `2-series` we could also keep the old bindings for backward-compatibility.

The sooner the better! #1858 is merged and it has some rebinds already, so no reason to hold it off :)

**Comment by jmercouris** [comment]
I agree with `C-m l` for saving the current URL as a bookmark.

**Comment by jmercouris** [comment]
I know of no other inconsistent bindings. Though, I'm sure we will find them!

**Comment by Ambrevar** [comment]
While we are at it, we can also fix https://github.com/atlas-engineer/nyxt/issues/1687.

**Comment by Ambrevar** [comment]
Fixed with aad422c6e2966a33ae827be17fb28c7bb973f8b7.
