### ISSUE TITLE
Resumed prompt is not cancellable/closeable

### ISSUE THREAD

**Issue by aartaka** [atlas-engineer/nyxt#1873]
Steps to reproduce:
- Run Nyxt, use prompt buffer command.
  - Example: do `set-url github.com RET`.
- Run `resume-prompt`.
- Choose the previously invoked `set-url` prompt.
- In the prompt opened by `resume-prompt`, try pressing `ESC`, `C-g` (if in Emacs mode) etc. It won't close the prompt.
- Try choosing any option out of the resumed prompts -- actions will run, but prompt will not close.

Nyxt commit 6283b8c88c978abac145c0d83cd31af9b2ff9116, installed via `nyxt.scm` Guix definition.

**Comment by Ambrevar** [comment]
I can reproduce.  Any idea when this started happening?

**Comment by aartaka** [comment]
> I can reproduce. Any idea when this started happening?

No idea, I haven't used this feature for several months.

**Comment by Ambrevar** [comment]
I don't know if it's related, but reopen-buffer sometimes shows me `Execute command` as a suggestion, as if it were a `resume-prompt` suggestion.

**Comment by Ambrevar** [comment]
I can't reproduce now on 2.2.3.  Any idea?

**Comment by Ambrevar** [comment]
@jmercouris @aartaka @pdelfino @guojing0 Can you reproduce?

**Comment by aartaka** [comment]
Another note: it's the resumed prompt that's not cancellable, not `resume-prompt` prompt :)
