### ISSUE TITLE
Use history-forwards-maybe-query as default forward action?

### ISSUE THREAD

**Issue by aartaka** [atlas-engineer/nyxt#1874]
`history-forwards-maybe-query` is a cool command -- it mostly behaves like a usual `history-forwards`, but, if there are several forward children, it prompts the user to choose one. Binding it to where `history-forwards` usually is will make our tree-like history more useful and visible.

I bound `history-forwards-maybe-query` to `C-f` (Emacs mode binding) instead of `history-forwards`, and it's often making me aware and productive about the branching that I do while browsing. As a side effect, it often prevents occasional `C-f` presses from silently going through.

How about we rebind `history-forwards-maybe-query` in the place of `history-forwards` by default?

**Comment by Ambrevar** [comment]
I agree, I think it'd be a good idea.  Maybe bind it just in Emacs / VI as the default, since they target more advanced users?

All that said, wait for 3.0 for this one?

**Comment by aartaka** [comment]
> I agree, I think it'd be a good idea. Maybe bind it just in Emacs / VI as the default, since they target more advanced users?

I'm not sure. It's even CUA users that can benefit from it. But I'm totally fine with it being exclusive for Emacs/VI maps too!

> All that said, wait for 3.0 for this one?

Sure!
