### ISSUE TITLE
Delete buffer broken?

### ISSUE THREAD

**Issue by jmercouris** [atlas-engineer/nyxt#1878]
**Describe the bug**

When typing C-x C-k, or C-w, or invoking via M-x 'delete-current-buffer', or invoking via M-x 'delete-buffer' I am unable to successfully delete a buffer. The webview goes gray, and then Nyxt freezes.

Is the same problem present in newer versions of WebKit? I am running the older version on NixOS.

**Comment by aartaka** [comment]
Hmmmmmm. Is the buffer fully loaded when you do it?

I can reproduce, but only when the buffer had just started loading. 

I'm sure it's some case I haven't tested for in #1872.

**Comment by aartaka** [comment]
@Ambrevar, do no release before this one is fixed :)

**Comment by Ambrevar** [comment]
No worries, noticed it too! :/

**Comment by Ambrevar** [comment]
I can reproduce systematically.

**Comment by Ambrevar** [comment]
I can reproduce on `2-series`.
I've bissected the history and @aartaka 's intuition is right, the issue is with cfad632913cbd2bc34b173bb1fd92f79eb96fcf2.

Any idea?

**Comment by Ambrevar** [comment]
First suspected bug: `buffer-delete` calls `ffi-buffer-delete` which calls `buffer-hide` which calls `buffer-delete`...

**Comment by Ambrevar** [comment]
Got it!

Turns out we needed `define-ffi-method` for `define-ffi-method` after all... :)  It would have surprised me otherwise, because this does act on GTK objects from the renderer.  So this makes sense.

@aartaka Can you confirm it works?  Have really managed to get `ffi-buffer-delete` to work as a simple `defmethod`?

I also tried with and without `(buffers-delete (id buffer))` in `buffer-hide`, seems to make no difference, but the infinite recursion should be a problem.
Any idea why it works nonetheless?

**Comment by aartaka** [comment]
> First suspected bug: `buffer-delete` calls `ffi-buffer-delete` which calls `buffer-hide` which calls `buffer-delete`...

It's `buffer-delete` -> `ffi-buffer-delete` -> `buffer-hide` - `bufferS-delete` :) `buffers-delete` is a simple remhash thus no recursion.

**Comment by aartaka** [comment]
> Turns out we needed `define-ffi-method` for `define-ffi-method` after all... :) It would have surprised me otherwise, because this does act on GTK objects from the renderer. So this makes sense.
> 
> @aartaka Can you confirm it works? Have really managed to get `ffi-buffer-delete` to work as a simple `defmethod`?

Aaaaah, so that's what it was! Replacing `defmethod` with `define-ffi-method` does indeed fix it.

**Comment by aartaka** [comment]
OK, so 19ce32ed80aa604dd2975950da70604456bb76fc should fix it.

**Comment by Ambrevar** [comment]
> buffers-delete is a simple remhash thus no recursion.

Oops! :)

Thanks for the fix!
