### ISSUE TITLE
Have additional prompt-trespassing arguments to prompt-reliant commands

### ISSUE THREAD

**Issue by aartaka** [atlas-engineer/nyxt#1882]
This way we will make it easier to control nyxt programmatically/headlessly. Adding to that, one would be able to query Nyxt for some values via swank/slynk connection or command line, which will make Nyxt-communicating scripts easier to compose.

**Comment by Ambrevar** [comment]
What do you mean with `additional` and `trespassing`?
Can you give an example?

Also isn't this what https://github.com/atlas-engineer/nyxt/pull/1354 aims to achieve?

**Comment by aartaka** [comment]
Oh, so #1354 has prompt input setting? 0_o

That's cool, and that's what I meant, but not all of it.

In addition to what #1354 has, it'd be cool to have more args to all the functions using prompt buffer, so that `prompt` is not even called.

Example:

Have `set-url` no have a keyword/optional arg `url` to simply load the URL, without even prompting the user. 

This way, one can use the familliar command from the config file. Knowing that it will do exactly what they want. Not needing to search for the low-level function/method internal to Nyxt. I.e., one does not need to know of `buffer-load` if they know of `set-url` that they can explore interactively.

**Comment by Ambrevar** [comment]
This is reminiscent of Emacs `(interactive ...)` API.
The drawback of `interactive` is that you can have only one prompt per function.

Otherwise we can just go through all commands and make sure all the prompts have parameters.

**Comment by aartaka** [comment]
Closing in favor of #1421.
