### ISSUE TITLE
Search engine completions ought to use a direct URL

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#1885]
When selecting a search engine completion, say, of Wikipedia, the resulting URL is _still_ a search query, instead of being the direct Wikipedia URL.

This probably results in an HTTP redirection which makes the query slower.
We should use the URL provided either by the completion API or, if lacking, a URL format provided manually.

@aartaka Thoughts?

**Comment by aartaka** [comment]
Agreed, it does make sense.

**Comment by guojing0** [comment]
So, say, we search `Nyx` via Wikipedia, then the URL should be https://en.wikipedia.org/wiki/Nyx instead of `Nyx` itself?

**Comment by aartaka** [comment]
> So, say, we search `Nyx` via Wikipedia, then the URL should be https://en.wikipedia.org/wiki/Nyx instead of `Nyx` itself?

Yes, if the completion API suggests it.
