### ISSUE TITLE
follow-hint-new-buffer(-focus) doesn't work while C-button1 is working

### ISSUE THREAD

**Issue by daehwannam** [atlas-engineer/nyxt#1886]
`follow-hint-new-buffer(-focus)` doesn't work over the search result page by google.
The command directs to the error page "404. That’s an error.".
However, C-button1 action works properly (I cannot find what function the binding is mapped to because `describe-key` says 'Unbound: "C-button1"').
The bug also occurs with empty init.lisp.

**Information**
- OS name+version: Ubuntu Desktop 20.04 (with Minimal Installation option)
- Graphics card and driver: Intel Corporation UHD Graphics 620 (rev 07)
- Desktop environment / Window manager name+version: GNOME Shell
- How you installed Nyxt (Guix pack, package manager, build from source): installed by nyxt_2.2.3_amd64.deb
- Information from `show-system-information`:

Nyxt version: 2.2.3
Renderer version: GI-GTK
Operating system kernel: Linux 5.11.0-40-generic
Lisp implementation: SBCL 2.1.0.0.HEAD.1-46cb065 (Dynamic space size: 1073741824)
Features: (:WEBKIT2 :WEBKIT2-2.34 :WEBKIT2-PASTE-PLAINTEXT :WEBKIT2-TRACKING
 :WEBKIT2-MUTE :WEBKIT2-EMOJI :WEBKIT2-MEDIA :WEBKIT2-SANDBOXING :GTK-3-22
 :GTK-3-20 :GTK-3-18 :GTK-3-16 :GTK-3-14 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6
 :GTK-3-4 :GTK :GDK-3-22 :GDK-3-20 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12
 :GDK-3-10 :GDK-3-8 :GDK-3-6 :GDK-3-4 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF
 :GLIB-2-30 :GLIB-2-32 :GLIB-2-34 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42
 :GLIB-2-44 :GLIB-2-46 :GLIB-2-48 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56
 :GLIB-2-58 :GLIB :NYXT-2 :FSET-EXT-STRINGS :CUSTOM-HASH-TABLE-NATIVE :SWANK
 :PLUMP-UTF-32 :GLOBAL-VARS :DECLARE-TYPES :PARENSCRIPT :NAMED-READTABLES
 :LPARALLEL :21BIT-CHARS :CHUNGA :FLEXI-STREAMS :CLOSER-MOP :CL-PPCRE-UNICODE
 :CL-UNICODE :BORDEAUX-THREADS :LPARALLEL.WITH-CLTL2 :LPARALLEL.WITH-CAS
 :LPARALLEL.WITH-STEALING-SCHEDULER :SPLIT-SEQUENCE CHIPZ-SYSTEM:GRAY-STREAMS
 :FAST-IO-SV :FAST-IO :SBCL-USES-SB-ROTATE-BYTE :CL-JSON-CLOS :CL-JSON
 :THREAD-SUPPORT :CL-PPCRE CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64
 CFFI-FEATURES:UNIX :CFFI CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP
 :ASDF3.3 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX
 :NON-BASE-CHARS-EXIST-P :ASDF-UNICODE :X86-64 :GENCGC :64-BIT :ANSI-CL
 :COMMON-LISP :ELF :IEEE-FLOATING-POINT :LINUX :LITTLE-ENDIAN
 :PACKAGE-LOCAL-NICKNAMES :SB-CORE-COMPRESSION :SB-LDB :SB-PACKAGE-LOCKS
 :SB-THREAD :SB-UNICODE :SBCL :UNIX)

ASDF version: 3.3.4
ASDF registries: (NYXT-SOURCE-REGISTRY ENVIRONMENT-SOURCE-REGISTRY USER-SOURCE-REGISTRY
                      USER-SOURCE-REGISTRY-DIRECTORY
                      DEFAULT-USER-SOURCE-REGISTRY SYSTEM-SOURCE-REGISTRY
                      SYSTEM-SOURCE-REGISTRY-DIRECTORY
                      DEFAULT-SYSTEM-SOURCE-REGISTRY)
Critical dependencies: (/home/runner/work/nyxt/nyxt/_build/cl-cffi-gtk/gtk/cl-cffi-gtk.asd
 /home/runner/work/nyxt/nyxt/_build/cl-gobject-introspection/cl-gobject-introspection.asd
 /home/runner/work/nyxt/nyxt/_build/cl-webkit/webkit2/cl-webkit2.asd)

**Output when started from a shell**
```
(default) user@user-pc:~$ nyxt
<INFO> [04:29:19] Listening to socket "/run/user/1000/nyxt/nyxt.socket".
Nyxt version 2.2.3
<INFO> [04:29:19] Loading Lisp file "/home/user/.config/nyxt/init.lisp".
<INFO> [04:29:35] Deleting socket "/run/user/1000/nyxt/nyxt.socket".
(default) user@user-pc:~$ 
```

**Comment by daehwannam** [comment]
Sorry for not providing the recipe in the initial post.

**Precise recipe to reproduce the issue**
1. Run SET-URL and enter "google.com"
2. Type "emacs" as the search query then enter
3. Run FOLLOW-HINT-NEW-BUFFER-FOCUS then open the following web page:
    "GNU Emacs - GNU Project - GNU.org www.gnu.org › emacs"
    (In addition, the copied URL of the page by COPY-HINT-URL is https://www.google.com/url?q=emacs
    and this URL also directs to the error page below)
4. The directed web page include the following content:
    "404. That’s an error. The requested URL /emacs was not found on this server. That’s all we know."
4. Run COPY-URL then the content is "https://www.google.com/emacs"

For website-specific issues:
Can you reproduce this issue with Epiphany / GNOME Web (https://wiki.gnome.org/Apps/Web)?
=> Epiphany doesn't have the same problem, and Nyxt can open the copied link by Epiphany
where Epiphany can copy the link by clicking the page's link with right button of mouse and run "Copy LInk Address" command.

Actually, my Nyxt cannot correctly open any search result regardless of the search query via FOLLOW-HINT-NEW-BUFFER(-FOCUS).

**Comment by Ambrevar** [comment]
I still can't reproduce from a vanilla configuration on Nyxt 2.2.3.

COPY-HINT-URL returns the correct URL.
This is very odd, as if your WebKitGTK was doing the wrong stuff.

Can you report the exact version of the webkit2gtk package that's
installed on your system?

@pdelfino @aartaka Can you reproduce?

**Comment by aartaka** [comment]
No, I cannot reproduce either. What I can suppose is that we don't resolve al the types of relative URLs there are (we don't cover a `..` wildcard at least, and there can be more).

**Comment by daehwannam** [comment]
@Ambrevar, My system is installed with two webkit2gtk packages and their versions are 4.0-*.
Here is the terminal output:
```
(default) user@user-pc:~$ apt list --installed | grep libwebkit2gtk

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libwebkit2gtk-4.0-37/focal-updates,focal-security,now 2.34.1-0ubuntu0.20.04.1 amd64 [installed,automatic]
libwebkit2gtk-4.0-dev/focal-updates,focal-security,now 2.34.1-0ubuntu0.20.04.1 amd64 [installed]
(default) user@user-pc:~$ 
```

**Comment by Ambrevar** [comment]
The webkit2gtk version looks alright.

**Comment by aartaka** [comment]
@daehwannam, can you reproduce with 2.2.4?

**Comment by aartaka** [comment]
Does 1e1d71bc3a6f1eb4439b3a5f8bcb8e086ed1f5a7 fix it?

**Comment by daehwannam** [comment]
@aartaka, I installed 2.2.4 version by "nyxt_2.2.4_amd64.deb" and the wrong URL problem doesn't occur!
However, I've just found that when I call SET-URL then **fast** type "google.com" and Enter, it directs to a search result of DuckDuckGo ( https://duckduckgo.com/?q=google.com&ia=web )
The SET-URL problem doesn't occurs if I type slowly or the version is 2.2.3 (although I didn't try 1e1d71b)

For testing 1e1d71b, do I need to compile nyxt from source ?

**Comment by aartaka** [comment]
> @aartaka, I installed 2.2.4 version by "nyxt_2.2.4_amd64.deb" and the wrong URL problem doesn't occur! However, I've just found that when I call SET-URL then **fast** type "google.com" and Enter, it directs to a search result of DuckDuckGo ( https://duckduckgo.com/?q=google.com&ia=web ) The SET-URL problem doesn't occurs if I type slowly or the version is 2.2.3 (although I didn't try [1e1d71b](https://github.com/atlas-engineer/nyxt/commit/1e1d71bc3a6f1eb4439b3a5f8bcb8e086ed1f5a7))

Yes, that's a known issue. Here, we decided to err on the side of caution and do DNS-validation of the hosts you input, thus the lag.

However, I just got an idea of checking history instead of pinging addresses — that could yield a significant speedup :D

> For testing [1e1d71b](https://github.com/atlas-engineer/nyxt/commit/1e1d71bc3a6f1eb4439b3a5f8bcb8e086ed1f5a7), do I need to compile nyxt from source ?

Yes, compiling from source checked out at this commit is preferable. But then, if 2.2.4 fixes it, then recent commits should have a similar behavior retained. So no need to test it if the issue is resolved. Closing then?

**Comment by daehwannam** [comment]
Ok, I close this issue as the posted problem is soloved.
Thank you for your help and hard work!

**Comment by Ambrevar** [comment]
> However, I just got an idea of checking history instead of pinging addresses — that could yield a significant speedup :D

@aartaka This is a great idea!  Wanna implement it?  Otherwise let's
open an issue about it so we don't forget!

**Comment by aartaka** [comment]
> @aartaka This is a great idea! Wanna implement it? Otherwise let's open an issue about it so we don't forget!

I'll open an issue :)
