### ISSUE TITLE
Delete documents/CHANGELOG ?

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#1887]
The file is now outdated and may confuse our readers.
Delete it?

If so, we need to replace the link in the README.org to point to, say, tag 2.1.1, when the file was last used.

**Comment by aartaka** [comment]
Yes, that sounds sane. However, we should also have the most recent copy of changelog hosted on Nyxt website, in the same fashion to how we do it with manual and tutorial.

**Comment by Ambrevar** [comment]
Technically we do in the form of release articles: https://nyxt.atlas.engineer/articles/release

**Comment by aartaka** [comment]
Yes, that's a good point.

**Comment by jmercouris** [comment]
Yes, we should probably delete the changelog file. As we've done with https://github.com/atlas-engineer/nyxt/blob/master/documents/MANUAL.org , we can do the same. No?

**Comment by Ambrevar** [comment]
Yes!
