### ISSUE TITLE
ffi-set-tracking-prevention does not use VALUE

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#1888]
@aartaka CCL rightfully complains the VALUE is not used in `ffi-set-tracking-prevention`.
Indeed, the function seems to always set it to `T`. Bug?

**Comment by aartaka** [comment]
Yes, a bug it is!

**Comment by aartaka** [comment]
I'll push a fix in a minute!

**Comment by aartaka** [comment]
Done in 3a8245837ffe8db55cda721a59eec1642e0a8c53.

**Comment by Ambrevar** [comment]
Thanks!
