### ISSUE TITLE
Touch scrolling not working in vi-*-modes but working fine in CUA and emacs modes

### ISSUE THREAD

**Issue by GorrillaRibs** [atlas-engineer/nyxt#1892]
Mouse input still works fine in vi-*-modes, is this a bug or the intended behaviour? If it's intended, where should I look to try to restore the old behaviour? I think it's been this way for a while but haven't pinpointed the exact commit where it stopped working yet. Thanks in advance!

I'm on linux + wayland if that changes anything

**Comment by GorrillaRibs** [comment]
Any mouse input (clicking or anything with the touch screen) in vi-insert-mode switches to vi-normal, so it seems like something's going on there? Regular mouse events work fine in vi-normal-mode though, I can highlight text & stuff normally.

**Comment by aartaka** [comment]
Closing this, as it is now tracked in #2000.
