### ISSUE TITLE
Support Gopher, Gopher+ & Gemini protocols

### ISSUE THREAD

**Issue by hendursaga** [atlas-engineer/nyxt#1893]
[Gopher](https://en.wikipedia.org/wiki/Gopher_(protocol))/[Gopher+](https://github.com/gopher-protocol/gopher-plus) as well as [Gemini](https://geminiquickst.art/) would be great to support eventually! Emacs' [Elpher mode](https://thelambdalab.xyz/elpher/) is not as satisfying as an integration for Nyxt would be!

**Comment by nyx-land** [comment]
Gemini/Gopher are very simple protocols and there are libraries that already exist for cl for both I believe, so it would be relatively easy to do this. The thing I'm unclear on is how to even build a UI on Nyxt since the [UI library](https://github.com/atlas-engineer/nyxt/tree/master/libraries/user-interface) that @jmercouris was working on seems like it's not had much work done on it. If I could get some pointers on how to do that I would maybe take a shot at it.

**Comment by hendursaga** [comment]
I'm not really familiar with this UI library, but wouldn't converting Gemtext to HTML be a good way to go about this? [Apparently it isn't that hard](https://codegolf.stackexchange.com/questions/220044/convert-gemtext-to-html) to do. [cl-yag](https://tildegit.org/radiofreqs/cl-yag/src/branch/master) is an SSG that can output to Gopher, I'm not sure about Gemtext though. There's [germinal](https://git.carcosa.net/jmcbray/germinal) and [tinmop](https://www.autistici.org/interzona/tinmop.html) we could look into.. thoughts?

**Comment by jmercouris** [comment]
@nyx-land what kind of questions do you have specifically? The UI library is meant to map some arbitrary object to an HTML representation of said object. It is just a thin wrapper around that concept :-)

we will add more widgets as we need them, but thus far we've not needed them!

**Comment by nyx-land** [comment]
I see. I was mostly wondering what the recommended way of building the UI for a Nyxt extension is, if the UI library is usable or if it's just a matter of using spinneret/parenscript, which is what mainly seems to be the case? So this gives me a better idea of what I can try with this after I finish getting Nyxt working on OpenBSD.

**Comment by jmercouris** [comment]
The UI library is usable, we do use it internally. The API has crystallized quite a bit. What it mostly needs now is just extension/implementation.

I look forward to seeing what we can come up with :-)

**Comment by aartaka** [comment]
Gopher support (#1994) is mostly complete and merged to master!

Left to do:
- [ ] Complete Gopher support:
  - [ ] Support telnet lines in plain Gopher (pages with telnet line examples will be much appreciated!)
  - [ ] Support DNS lines in plain Gopher (examples will be much appreciated too!)
  - [ ] Support unspecified yet popular lines (e.g. document lines) in plain Gopher (where do we find a list of those?).
- [ ] Gopher+ support.
  - [ ] Contribute Gopher+ parsing and loading to `cl-gopher`. 
  - [ ] Expand `gopher-mode` to support Gopher+ lines.
- [ ] Gemini support.
  - [ ] Find/write the Gemini support library.
  - [ ] Make an intuitive interface for Gemini pages.

**Comment by hendursaga** [comment]
Oh, and support for the [Titan protocol](https://transjovian.org:1965/titan) (which is basically an extension to Gemini) would be neat, although not high-priority.

**Comment by hendursaga** [comment]
No update on upstream issue, but if / when we add the functionality, we could use gopher://magicalxot2nosefso27zfzuujuaphtznzn3ng7q44u426s6bkiuvzqd.onion for testing, it seems rather stable.

**Comment by jmercouris** [comment]
We have pretty good support for now. Of course there is always more to do, but that is for another night, another dream.

**Comment by aartaka** [comment]
Right—I'm still having trougle understanding Gopher+ 😅
