### ISSUE TITLE
Some keys are wrongly captured by Nyxt

### ISSUE THREAD

**Issue by rdrg109** [atlas-engineer/nyxt#1894]
**Describe the bug**

When Alt+Shift+G is pressed in Wikipedia articles, the corresponding WIkidata item is opened. For example, pressing Alt+Shift+G in https://en.wikipedia.org/wiki/Submediant opens https://www.wikidata.org/wiki/Q2482085 in Firefox and in Epiphany. However, pressing the same key combination in Nyxt shows the following message in the message area instead of opening the WIkidata item

```
Pressed keys: M-s-G
```

**Precise recipe to reproduce the issue**

For website-specific issues:
Can you reproduce this issue with Epiphany / GNOME Web (https://wiki.gnome.org/Apps/Web)? Alt+Shift+G has an effect in Wikipedia when using Epiphany.

**Information**
- Desktop environment / Window manager name+version: Emacs EXWM
- How you installed Nyxt (Guix pack, package manager, build from source): build from source
- Information from `show-system-information`:
```
Nyxt version: 2.1.1-852-g4f95d4cc
Renderer version: GI-GTK
Operating system kernel: Linux 5.15.4-arch1-1
Lisp implementation: SBCL 2.1.9 (Dynamic space size: 1073741824)
Features: (:WEBKIT2 :WEBKIT2-2.34 :WEBKIT2-PASTE-PLAINTEXT :WEBKIT2-TRACKING
 :WEBKIT2-MUTE :WEBKIT2-EMOJI :WEBKIT2-MEDIA :WEBKIT2-SANDBOXING :GTK-3-22
 :GTK-3-20 :GTK-3-18 :GTK-3-16 :GTK-3-14 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6
 :GTK-3-4 :GTK :GDK-3-22 :GDK-3-20 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12
 :GDK-3-10 :GDK-3-8 :GDK-3-6 :GDK-3-4 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF
 :GLIB-2-30 :GLIB-2-32 :GLIB-2-34 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42
 :GLIB-2-44 :GLIB-2-46 :GLIB-2-48 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56
 :GLIB-2-58 :GLIB :NYXT-2 :FSET-EXT-STRINGS :CUSTOM-HASH-TABLE-NATIVE :SWANK
 :PLUMP-UTF-32 :GLOBAL-VARS :DECLARE-TYPES :PARENSCRIPT
 :SBCL+SAFE-STANDARD-READTABLE :NAMED-READTABLES :LPARALLEL :21BIT-CHARS
 :CHUNGA :FLEXI-STREAMS :CLOSER-MOP :CL-PPCRE-UNICODE :CL-UNICODE :CL-PPCRE
 :BORDEAUX-THREADS :LPARALLEL.WITH-CLTL2 :LPARALLEL.WITH-CAS
 :LPARALLEL.WITH-STEALING-SCHEDULER :SPLIT-SEQUENCE CHIPZ-SYSTEM:GRAY-STREAMS
 CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64 CFFI-FEATURES:UNIX :CFFI
 CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP :FAST-IO-SV :FAST-IO
 :SBCL-USES-SB-ROTATE-BYTE :ASDF-SYSTEM-CONNECTIONS :CL-JSON-CLOS :CL-JSON
 :THREAD-SUPPORT :ASDF3.3 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX
 :NON-BASE-CHARS-EXIST-P :ASDF-UNICODE :X86-64 :GENCGC :64-BIT :ANSI-CL
 :COMMON-LISP :ELF :IEEE-FLOATING-POINT :LINUX :LITTLE-ENDIAN
 :PACKAGE-LOCAL-NICKNAMES :SB-CORE-COMPRESSION :SB-LDB :SB-PACKAGE-LOCKS
 :SB-THREAD :SB-UNICODE :SBCL :UNIX)

ASDF version: 3.3.1
ASDF registries: (NYXT-SOURCE-REGISTRY ENVIRONMENT-SOURCE-REGISTRY)
Critical dependencies: (/home/myusername/SourceCode/nyxt/_build/cl-cffi-gtk/gtk/cl-cffi-gtk.asd
 /home/myusername/SourceCode/nyxt/_build/cl-gobject-introspection/cl-gobject-introspection.asd
 /home/myusername/SourceCode/nyxt/_build/cl-webkit/webkit2/cl-webkit2.asd)
```

**Comment by rdrg109** [comment]
> Does that do the trick for you?

@Ambrevar Yes.

I I'm a heavy user of Wikipedia and Wikidata. Therefore, I constantly use Alt+Shift+g and some other keys where this same issue happens. I have thought in the following solutions to overcome this issue

1. Map all the keys where this issue occurs in Wikipedia pages so that whenever they are pressed, passthrough-mode is temporarily enabled.
    + Honestly, I don't like this idea because I would need to hardcode the domain of Wikipedia in my configuration as well as those keys. 
2. Find a way to make Nyxt stop translating Shift
    + I think this is the most reasonable

Do you know how to do no. 2?

**Comment by Ambrevar** [comment]
Yes, but that would require a change in the keymap library.  I'll work
on it.

**Comment by Ambrevar** [comment]
Sorry, actually this is already supported.

The control know is `keymap:*translator*`.  You can set it to `nil` to disable all forms of translation.  

There are many translators enabled by default and you can choose any combination you like.  See `translate-shift-control-combinations` for an example combination.

**Comment by rdrg109** [comment]
> You can set it to nil to disable all forms of translation.

Thanks! This worked!

**Comment by jmercouris** [comment]
Closing this then, please feel free to reopen if you think there is something we missed!

**Comment by Ambrevar** [comment]
I'll document it in the manual.
