### ISSUE TITLE
Fix/replace insecure git submodule URLs

### ISSUE THREAD

**Issue by sochotnicky** [atlas-engineer/nyxt#1899]
**Describe the bug**
Currently there are 5 git submodules referenced in .gitmodules which use http instead of https:
http://git.kpe.io/rt.git
http://git.kpe.io/cl-base64.git/
http://git.kpe.io/ptester.git
http://git.kpe.io/kmrcl.git/
http://git.kpe.io/puri.git

I have reached out two weeks ago to the owner/author of the domain/repos to see if he'd add https support. This would prevent potential MITM attacks (though arguably this is less likely with git but still...). I have not heard back yet though so filing this bug here after chatting on IRC.

We discussed a few other options - such as mirroring those repos to github and referencing those (the mirroring process would still be susceptible, but possibly less so).

**Comment by Ambrevar** [comment]
Thanks for pointing this out.
Another issue with these repos is that they don't support shallow cloning.

We could mirror them to https://gitlab.common-lisp.net/nyxt like we already do with 2 abandoned libs.

Thoughts?

**Comment by sochotnicky** [comment]
That would work too - gitlab does support self-service mirroring (I believe it pulls once an hour) and might be easier to set up than hacking with github actions :-)

**Comment by Ambrevar** [comment]
Are these kpe.io projects still maintained?

**Comment by Ambrevar** [comment]
Done with 217b2a785b1f53e8877454eada041113676b5a5b.
Note that I haven't been able to use the mirroring feature of GitLab, for an unknown reason it failed to recognize the KPE repos as valid Git URL.
