### ISSUE TITLE
Building for OpenBSD

### ISSUE THREAD

**Issue by nyx-land** [atlas-engineer/nyxt#1901]
I've been trying to get Nyxt to compile on OpenBSD, with middling success. I realize that OpenBSD isn't currently supported but I think it should be and am currently working on it, but am having some issues.

The main things that I can determine are blocking me from being able to build this on OpenBSD are that iolib and cl-cffi-gtk both look for libraries (libfixposix and pango, respectively) that they for some reason don't know how to find on OpenBSD. Both of these are relatively easy to fix by adding some declarations in the source code for both to look in `/usr/local/include/` and `/usr/local/lib/`, but those changes would have to be pushed upstream to those projects.

Anyway, the part that's relevant to Nyxt is after getting all the dependencies loaded in the REPL (and I've even tried adding the `_build/` directory where Nyxt stores its submodules to make sure it's using the exact versions it expects for the dependencies), I then build it using `(asdf:make :nyxt/gtk-application)`, because if I use the makefile it'll just try to pull the submodules and erase my patches to iolib and cl-cffi-gtk. After doing this, it works!... for about a minute.

Just doing normal browsing on sites that don't have a ton of JS like Github will cause my build of Nyxt to start using a ton of CPU and become unresponsive very quickly. I've tried debugging it from the command line using the verbose flag but it doesn't indicate that anything is wrong, otherwise I'd include the logs after Nyxt crashes. So I'm stumped now.

I'm not sure if anyone here will be able to help with this at all, because I realize no one so far has seemingly had any interest in getting Nyxt on OpenBSD, but this is what I'm stuck on right now so if anyone has any suggestions for how to proceed with getting Nyxt working on OpenBSD so I can make a port that'd be great.

Nyxt version: 2.2.3
SBCL version: 2.1.10
OpenBSD version: 7.0

**Comment by Ambrevar** [comment]
I suggest you query "freebsd" in the GitHub search of this repo, it might be insightful.
In particular, @shiorid and @shamazmazum have contributed FreeBSD support for Nyxt, they might be able to help.

About the CFFI lookup: finding in `/usr/local` is supported by default if I'm not mistaken.  Can you report what you had to patch?

About the hog: this rings a bell! See https://github.com/atlas-engineer/nyxt/pull/800 for a discussion.
According to https://github.com/atlas-engineer/nyxt/issues/1111 it's fixed now.

Does the issue occur exactly always after the same delay?

**Comment by shamazmazum** [comment]
Hi! Pango seems to be present in OpenBSD port collection, check [this](https://openports.se/devel/pango). Also, I suspect it's a direct dependency for gtk3. libfixposix is present in FreeBSD's port collection, but not in OpenBSD's as I suspect. But to work properly, it also should be [patched](https://github.com/sionescu/libfixposix/pull/18). The patch is there for years, the author just won't merge. Good things, only sendfile(2) is affected and I am not sure if this system call is used by nyxt directly (i.e. not via WebKit). This is true for FreeBSD, but may be true for OpenBSD too.

Though this is not a recommended way to build, I just download all dependencies with Ultralisp. This is good alternative to submodules, as I think.

Does OpenBSD have DTrace or alternatives? The first step to debug nyxt would be measuring how much time nyxt spends in system calls.

**Comment by Ambrevar** [comment]
Nyxt does not use `sendfile` directly.  I don't believe it's used
indirectly, but I could be wrong.

**Comment by nyx-land** [comment]
I would think that looking in `/usr/local/` should just work and was looking in the Nyxt documentation for installing on FreeBSD. I also saw this issue #1820 where it was recommended to push the path to `cffi:*foreign-library-directories*`, which is what I have currently set in my `.sbclrc`. For whatever reason though, that didn't affect anything. I found this [iolib issue](https://github.com/sionescu/iolib/issues/62) where it was recommended to add `(push "-I/usr/local/include" cffi-toolchain:*cc-flags*)` to .sbclrc, which fixes the iolib issue. I patched these locally in the packages themselves and it'd probably be good to commit them upstream instead of recommending that users on non-Linux systems edit their .sbclrc, but editing .sbclrc was enough for now to get me to the next step.

For cl-cffi-gtk, I had to make these changes in `pango.init.lisp` to get the build to work because for some reason on OpenBSD the shared lib I have is `libpango-1.0.so.3801.2`, not a filename it's expecting. It's possible I'm doing something stupid with this quick and dirty fix or don't have the library installed correctly, I don't know the first thing about C or CFFI:

```diff
diff --git a/pango/pango.init.lisp b/pango/pango.init.lisp
index 6f5009b..9c784e0 100644
--- a/pango/pango.init.lisp
+++ b/pango/pango.init.lisp
@@ -30,7 +30,8 @@
 (glib::at-init ()
   (eval-when (:compile-toplevel :load-toplevel :execute)
     (define-foreign-library pango
-      ((:and :unix (:not :darwin)) "libpango-1.0.so.0")
+      ((:and :unix (:not (or :openbsd :darwin))) "libpango-1.0.so.0")
+      (:openbsd "libpango-1.0.so.3801.2")
       (:darwin (:or "libpango-1.0.0.dylib" "libpango-1.0.dylib"))
       (:windows "libpango-1.0-0.dll")
       (t (:default "libgpango-1.0"))))
@@ -40,7 +41,8 @@
 (glib::at-init ()
   (eval-when (:compile-toplevel :load-toplevel :execute)
     (define-foreign-library pangocairo
-      ((:and :unix (:not :darwin)) "libpangocairo-1.0.so.0")
+      ((:and :unix (:not (or :openbsd :darwin))) "libpangocairo-1.0.so.0")
+      (:openbsd "libpangocairo-1.0.so.3801.2")
       (:darwin (:or "libpangocairo-1.0.0.dylib" "libpangocairo-1.0.dylib"))
       (:windows "libpangocairo-1.0-0.dll")
       (t (:default "libgpangocairo-1.0"))))
```

Anyways, I tried to also just quickload all the dependencies and build it just now -- same problem, but probably not related to not using the refs that `_build/` downloads if @shamazmazum has done the same thing with Ultralisp.

OpenBSD has ktrace, though I have no idea what to make of this 8 million line long kernel trace since I've never had to debug one of these before. The last few lines before I kill -9 Nyxt are this, repeated over and over again, so whatever is causing Nyxt to start spinning out is probably related to whatever this means:

```
 11049 nyxt     RET   nanosleep 0
 11049 nyxt     CALL  nanosleep(0x22d964f92f0,0x22d964f92e0)
 11049 nyxt     STRU  struct timespec { 0.100000000 }
 11049 nyxt     STRU  struct timespec { 0 }
 11049 nyxt     RET   nanosleep 0
 11049 nyxt     CALL  nanosleep(0x22dbef174d0,0x22dbef174c0)
 11049 nyxt     STRU  struct timespec { 0.100000000 }
 11049 nyxt     STRU  struct timespec { 0 }
 11049 nyxt     RET   nanosleep 0
 11049 nyxt     STRU  struct timespec { 0 }
 11049 nyxt     CALL  nanosleep(0x22d49eb7100,0x22d49eb70f0)
 11049 nyxt     RET   nanosleep 0
 11049 nyxt     STRU  struct timespec { 0.100000000 }
 11049 nyxt     CALL  nanosleep(0x22d524cf100,0x22d524cf0f0)
 11049 nyxt     STRU  struct timespec { 0.100000000 }
 11049 nyxt     STRU  struct timespec { 0 }
 11049 nyxt     RET   nanosleep 0
 11049 nyxt     CALL  nanosleep(0x22d323c70f0,0x22d323c70e0)
 11049 nyxt     STRU  struct timespec { 0.100000000 }
 11049 nyxt     STRU  struct timespec { 0.029999979 }
 11049 nyxt     PSIG  SIGKILL SIG_DFL
```

>Does the issue occur exactly always after the same delay?
Yep, always happens after about a minute of browsing after navigating to a few links, regardless of what I'm navigating to.

I also forgot to mention that the version of webkit installed from OpenBSD is webkitgtk4-2.32.4

**Comment by Ambrevar** [comment]
The pango issue is with the OpenBSD package: it should have a symlink
libpango-1.0.so to libpango-1.0.so.3801.2.

Thanks about the trace.  It's indeed entering a loop that's polling
something and waiting 0.1s between each poll.

Now guess what?  We do have a (sleep 0.1) in our code!
It's when something is downloaded, but it should not be triggered if you
haven't started a download.

That said, there could be a bug with MIME detection on OpenBSD which
gets WebKitGTK to see a resource as a download.

@nix-land Are you comfortable enough with Nyxt and Lisp to comment these
two lines in browser.lisp and try again?

```lisp
(run-thread
  (download-watch download-render download))
```

Maybe comment the whole download-watch definition as well just to be sure.

**Comment by Ambrevar** [comment]
Could you also report the output of `nyxt --system-information`?

I'm particularly eager to know if SBCL is built with threading support.  If not, then that's probably your issue!

**Comment by nyx-land** [comment]
I figured the pango thing was probably not intended to be that way. I'll have to see about getting that fixed upstream in the OpenBSD package.

So I commented out the lines and recompiled Nyxt. The CPU spinning out doesn't seem to be happening anymore, so that's progress, but maddeningly it's still becoming unresponsive for some reason.

Here's a snippet from before kill -9'ing the process that I get after running another ktrace:

```
 14607 nyxt     CALL  futex(0x66a4059e400,0x81<FUTEX_WAIT|FUTEX_PRIVATE_FLAG>,24,0,0)
 14607 nyxt     CALL  sched_yield()
 14607 nyxt     RET   sched_yield 0
 14607 nyxt     CALL  thrkill(160457,SIGUSR1,0x66a01bbfa00)
 14607 nyxt     RET   thrkill 0
 14607 nyxt     PSIG  SIGUSR1 caught handler=0x669de17d430 mask=0x4000000<SIGPROF>
 14607 nyxt     RET   futex -1 errno 88 Operation canceled
 14607 nyxt     CALL  futex(0x669de2b5d68,0x2<FUTEX_WAKE>,1,0,0)
 14607 nyxt     RET   futex 0
 14607 nyxt     CALL  sigreturn(0x6697a5aef20)
 14607 nyxt     RET   sigreturn JUSTRETURN
 14607 nyxt     CALL  futex(0x66a4059e400,0x81<FUTEX_WAIT|FUTEX_PRIVATE_FLAG>,24,0,0)
 14607 nyxt     CALL  sched_yield()
 14607 nyxt     RET   sched_yield 0
 14607 nyxt     CALL  thrkill(160457,SIGUSR1,0x66a01bbfa00)
 14607 nyxt     RET   thrkill 0
 14607 nyxt     PSIG  SIGUSR1 caught handler=0x669de17d430 mask=0x4000000<SIGPROF>
 14607 nyxt     RET   futex -1 errno 88 Operation canceled
 14607 nyxt     CALL  futex(0x669de2b5d68,0x2<FUTEX_WAKE>,1,0,0)
 14607 nyxt     RET   futex 0
 14607 nyxt     CALL  sigreturn(0x6697a5aef20)
 14607 nyxt     RET   sigreturn JUSTRETURN
 14607 nyxt     CALL  futex(0x66a4059e400,0x81<FUTEX_WAIT|FUTEX_PRIVATE_FLAG>,24,0,0)
 14607 nyxt     CALL  sched_yield()
 14607 nyxt     RET   sched_yield 0
 14607 nyxt     CALL  thrkill(160457,SIGUSR1,0x66a01bbfa00)
 14607 nyxt     RET   thrkill 0
 14607 nyxt     PSIG  SIGUSR1 caught handler=0x669de17d430 mask=0x4000000<SIGPROF>
 14607 nyxt     RET   futex -1 errno 88 Operation canceled
 14607 nyxt     CALL  futex(0x669de2b5d68,0x2<FUTEX_WAKE>,1,0,0)
 14607 nyxt     RET   futex 0
 14607 nyxt     CALL  sigreturn(0x6697a5aef20)
 14607 nyxt     RET   sigreturn JUSTRETURN
 14607 nyxt     CALL  futex(0x66a4059e400,0x81<FUTEX_WAIT|FUTEX_PRIVATE_FLAG>,24,0,0)
 14607 nyxt     PSIG  SIGKILL SIG_DFL
```

There's more or less one block here that seems to be repeating when it becomes unresponsive where it looks like something that uses futex is entering a loop? Perhaps this is related in some way to multithreading.

**Comment by nyx-land** [comment]
Oh I just saw your other comment @Ambrevar, this is the output of `nyxt --system-information`. I do remember specifically building SBCL to have threads but the ktrace I just posted related to futex is making me wonder if something weird is happening with threading.

```
Nyxt version: 2.2.3
Renderer version: GTK
Operating system kernel: OpenBSD 7.0
Lisp implementation: SBCL 2.1.10 (Dynamic space size: 466550784)
Features: (:WEBKIT2 :WEBKIT2-2.32 :WEBKIT2-PASTE-PLAINTEXT :WEBKIT2-TRACKING
 :WEBKIT2-MUTE :WEBKIT2-EMOJI :WEBKIT2-MEDIA :WEBKIT2-SANDBOXING :GTK-3-22
 :GTK-3-20 :GTK-3-18 :GTK-3-16 :GTK-3-14 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6
 :GTK-3-4 :GTK :GDK-3-22 :GDK-3-20 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12
 :GDK-3-10 :GDK-3-8 :GDK-3-6 :GDK-3-4 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF
 :GLIB-2-30 :GLIB-2-32 :GLIB-2-34 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42
 :GLIB-2-44 :GLIB-2-46 :GLIB-2-48 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56
 :GLIB-2-58 :GLIB :NYXT-2 :FSET-EXT-STRINGS :CUSTOM-HASH-TABLE-NATIVE :SWANK
 :PLUMP-UTF-32 :GLOBAL-VARS :DECLARE-TYPES :PARENSCRIPT :NAMED-READTABLES
 :LPARALLEL :LPARALLEL.WITH-CLTL2 :LPARALLEL.WITH-CAS
 :LPARALLEL.WITH-STEALING-SCHEDULER :21BIT-CHARS :CHUNGA :FLEXI-STREAMS
 CHIPZ-SYSTEM:GRAY-STREAMS :FAST-IO-SV :FAST-IO :SBCL-USES-SB-ROTATE-BYTE
 :ASDF-SYSTEM-CONNECTIONS :CLOSER-MOP :SPLIT-SEQUENCE :CL-PPCRE-UNICODE
 :CL-UNICODE :CL-PPCRE :CL-JSON-CLOS :CL-JSON :BORDEAUX-THREADS :THREAD-SUPPORT
 CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64 CFFI-FEATURES:UNIX :CFFI
 CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP :QUICKLISP :ASDF3.3
 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX :NON-BASE-CHARS-EXIST-P
 :ASDF-UNICODE :X86-64 :GENCGC :64-BIT :ANSI-CL :BSD :COMMON-LISP :ELF
 :IEEE-FLOATING-POINT :LITTLE-ENDIAN :OPENBSD :PACKAGE-LOCAL-NICKNAMES :SB-LDB
 :SB-PACKAGE-LOCKS :SB-THREAD :SB-UNICODE :SBCL :UNIX)

ASDF version: 3.3.1
ASDF registries: (NYXT-SOURCE-REGISTRY ENVIRONMENT-SOURCE-REGISTRY USER-SOURCE-REGISTRY
                      USER-SOURCE-REGISTRY-DIRECTORY
                      DEFAULT-USER-SOURCE-REGISTRY SYSTEM-SOURCE-REGISTRY
                      SYSTEM-SOURCE-REGISTRY-DIRECTORY
                      DEFAULT-SYSTEM-SOURCE-REGISTRY)
Critical dependencies: (/home/n1x/code/src/cl/cl-cffi-gtk/gtk/cl-cffi-gtk.asd NIL
 /home/n1x/code/src/cl/cl-webkit/webkit2/cl-webkit2.asd)

Quicklisp dist version: 2021-10-21
Quicklisp client version: 2021-02-13
Local project directories: (/home/n1x/quicklisp/local-projects/)
Critical dependencies(#<SYSTEM cl-cffi-gtk / cl-cffi-gtk-20201220-git / quicklisp 2021-10-21>
 #<SYSTEM cl-gobject-introspection / cl-gobject-introspection-20210124-git / quicklisp 2021-10-21>
 #<SYSTEM cl-webkit2 / cl-webkit-20211020-git / quicklisp 2021-10-21>)
```

**Comment by Ambrevar** [comment]
Your SBCL is fine since it has the SB-THREAD feature.

So we do have a multiple bugs here:

- The download watch is triggered while it should not.
- The download watch loops indefinitely, but that could be the same bug
  as above since it's watching something that may not exist.
- The last trace is almost certainly a race condition.

@nix-land: Does this happen if you start Nyxt and do _nothing_?
Wait, say, 15 minutes, then see if the interface is still responsibe
(hover with the mouse over the status area).

Do you know how to use a Lisp REPL like SLIME or SLY?

**Comment by shiorid** [comment]
`sendfile(2)` problem in libfixposix is now  [fixed upstream.](https://github.com/sionescu/libfixposix/commit/fc5bbe41a574e668ccfafb0f15dddd28f6decd31)

**Comment by shiorid** [comment]
`lfp.h` problem in `iolib` is now [fixed upstream.](https://github.com/sionescu/iolib/commit/548537ed0c764ed00f7dfa703e5e51506c19460f)

**Comment by Ambrevar** [comment]
Thanks for the heads up, Felipe.

**Comment by Ambrevar** [comment]
Sorry for the typo, Filipe :)

**Comment by nyx-land** [comment]
@Ambrevar so I tried just running Nyxt without doing anything, ran into the same problem. And yes I'm fairly competent with CL, was going to ask if you had any suggestions for debugging this from SLY.

**Comment by Ambrevar** [comment]
First you can try running it from SLY (start it with `(nyxt:start)`) and
see if a condition is raised.

**Comment by nyx-land** [comment]
Sorry about the silence, I'm still working on this it just got sidelined for a bit. 

I didn't get any obvious errors from running nyxt from the REPL, so at the moment I'm just stuck at investigating it further to see what's causing the race condition. Again if you have any suggestions for debugging @Ambrevar do let me know.

**Comment by Ambrevar** [comment]
So if you start Nyxt from the REPL and just wait, the performance issue pops up automatically, is that right?
Is there anything displayed in the REPL?

Are you loading the `nyxt/gi-gtk` or the `nyxt/gtk` system?  Try both and see if the behaviour changes.

The bug could be with GTK garbage collection, because otherwise I don't see why it would happen on its own.

**Comment by aadcg** [comment]
Stale.
