### ISSUE TITLE
manual.html    --- and kkbd  ambiguity

### ISSUE THREAD

**Issue by tvraman** [atlas-engineer/nyxt#1905]
After doing make doc, the manual.html claims that C-space is the
equivalent of M-x in emacs; but later it also claims that it sets the
Mark -- which is correct?

**Comment by jmercouris** [comment]
It depends on the mode. In `visual-mode` it will set the mark, but elsewhere it will be a `M-x` equivalency. Indeed, this is a bit ambiguous!

**Comment by Ambrevar** [comment]
@jmercouris Can you fix it?

**Comment by jmercouris** [comment]
I'm not certain how to fix it.

**Comment by Ambrevar** [comment]
I meant to clarify the doc and remove the ambiguity.

**Comment by jmercouris** [comment]
I see. Perhaps. No comittment!

**Comment by aadcg** [comment]
Stale.

I don't think that the ambiguity exists.
