### ISSUE TITLE
X   error

### ISSUE THREAD

**Issue by tvraman** [atlas-engineer/nyxt#1906]
(WebKitWebProcess:46597): Gdk-ERROR **: 13:13:02.514: The program 'WebKitWebProcess' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadMatch (invalid parameter attributes)'.
  (Details: serial 150 error_code 8 request_code 1 (core protocol) minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)

**Comment by jmercouris** [comment]
Maybe it does, maybe it doesn't, it would be helpful if you could please provide the information from the nyxt system information command :-)

**Comment by Ambrevar** [comment]
More precisely, you can report the output of `nyxt --system-information` from the command line.

**Comment by aadcg** [comment]
Stale.
