### ISSUE TITLE
How to support the Chinese font?

### ISSUE THREAD

**Issue by vanniuner** [atlas-engineer/nyxt#1907]
How to support the Chinese font? I just use nyxt with docker.

**Comment by vanniuner** [comment]
<img width="1022" alt="截屏2021-12-04 上午8 58 45" src="https://user-images.githubusercontent.com/7248023/144690466-3d812d27-32f6-4efa-a373-75dcd52f0d50.png">

**Comment by guojing0** [comment]
Out of curiosity, did you build from source on Mac and then run it inside Docker?

**Comment by Ambrevar** [comment]
Nyxt is not responsible for the fonts, it's GTK.  You need to install the right font on your system for GTK to find it.
Can you report the output of the `show-system-information` command?

**Comment by vanniuner** [comment]
> Out of curiosity, did you build from source on Mac and then run it inside Docker?

yes docker

**Comment by aadcg** [comment]
> Nyxt is not responsible for the fonts, it's GTK. You need to install the right font on your system for GTK to find it.
