### ISSUE TITLE
tts-mode

### ISSUE THREAD

**Issue by tvraman** [atlas-engineer/nyxt#1908]
Intrigued to see tts.lisp implements tts-mode, read the code, but I have no idea how to turn it on; help please:-)

**Comment by edgar-vincent** [comment]
I'm working on an article to explain how to use it, but I'm struggling myself :)

**Comment by Ambrevar** [comment]
TTS-mode was contributed by @chrisboeg with #1734.  Chris, can you help?  Looks like we need to expand the documentation ;)

**Comment by aadcg** [comment]
`tts-mode` [will probably be deleted soon](https://github.com/atlas-engineer/nyxt/issues/1633#issuecomment-1543751189), so it would make little sense to pursue this goal.
