### ISSUE TITLE
Build error Couldn't execute "guix": No such file or directory

### ISSUE THREAD

**Issue by ycpei** [atlas-engineer/nyxt#1910]
**Describe the bug**

Hello,

I am having some problem building nyxt on an Arch GNU/Linux system (pacman -Syu from about two weeks ago).

I tried both AUR and manual build (clone from this repo and make all), but they both result in the same error of not finding nyxt (the stderr is pasted at the end)

In makepkg, the dependencies check passed.

Let me know if you have any clue how to proceed, thanks!

**Precise recipe to reproduce the issue**

git clone https://github.com/atlas-engineer/nyxt/ && cd nyxt && make all

--- stderr ---

; wrote /home/foo/.cache/common-lisp/sbcl-2.1.9-linux-x64/home/foo/nyxt/source/global-tmpODT9XID6.fasl
; compilation finished in 0:00:00.116
Unhandled SIMPLE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING
                                    {10018582C3}>:
  Couldn't execute "guix": No such file or directory

Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {10018582C3}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<SIMPLE-ERROR "Couldn't execute ~S: ~A" {100939B423}> #<unused argument> :QUIT T)
1: (SB-DEBUG::RUN-HOOK SB-EXT:*INVOKE-DEBUGGER-HOOK* #<SIMPLE-ERROR "Couldn't execute ~S: ~A" {100939B423}>)
2: (INVOKE-DEBUGGER #<SIMPLE-ERROR "Couldn't execute ~S: ~A" {100939B423}>)
3: (ERROR "Couldn't execute ~S: ~A" "guix" "No such file or directory")
4: (SB-EXT:RUN-PROGRAM "guix" ("--version") :ENV NIL :ENVIRONMENT NIL :WAIT NIL :SEARCH T :PTY NIL :INPUT NIL :IF-INPUT-DOES-NOT-EXIST :ERROR :OUTPUT :STREAM :IF-OUTPUT-EXISTS :APPEND :ERROR NIL :IF-ERROR-EXISTS :APPEND :STATUS-HOOK NIL :EXTERNAL-FORMAT :UTF-8 :DIRECTORY NIL :PRESERVE-FDS NIL)
5: (UIOP/LAUNCH-PROGRAM:LAUNCH-PROGRAM ("guix" "--version") :INPUT NIL :OUTPUT :STREAM :ERROR-OUTPUT NIL :OUTPUT :STRING)
6: ((LAMBDA (UIOP/RUN-PROGRAM::REDUCED-INPUT UIOP/RUN-PROGRAM::INPUT-ACTIVITY) :IN UIOP/RUN-PROGRAM::%USE-LAUNCH-PROGRAM) NIL NIL)
7: (UIOP/RUN-PROGRAM::%USE-LAUNCH-PROGRAM ("guix" "--version") :OUTPUT :STRING)
8: (SB-FASL::LOAD-FASL-GROUP #S(SB-FASL::FASL-INPUT :STREAM #<SB-SYS:FD-STREAM for "file /home/foo/.cache/common-lisp/sbcl-2.1.9-linux-x64/home/foo/nyxt/source/global.fasl" {1009388B03}> :TABLE #(104 SET *PACKAGE* "NYXT" EXPORT #<PACKAGE "NYXT"> *OPTIONS* #<PACKAGE "SB-IMPL"> SB-IMPL::%DEFVAR #1="/home/foo/nyxt/source/global.lisp" #<SB-KERNEL:WRAPPER (ID=-7) for SB-C:DEFINITION-SOURCE-LOCATION {50201773}> #S(SB-C:DEFINITION-SOURCE-LOCATION :NAMESTRING #1# :INDICES 98305) ...) :STACK #(9 SB-IMPL::%DEFVAR +GUIX-BUILD-INFORMATION+ #S(SB-C:DEFINITION-SOURCE-LOCATION :NAMESTRING #1# :INDICES 557057) SB-IMPL::|List| :VERSION FOURTH SERA:TOKENS FIRST SERA:LINES UIOP/RUN-PROGRAM:RUN-PROGRAM ("guix" "--version") ...) :NAME-BUFFER #("RUN-PROGRAMEM" "STRINGE-EXECUTABLEATION+IES+\0\0\0") :DEPRECATED-STUFF NIL :SKIP-UNTIL NIL) NIL)
9: (SB-FASL::LOAD-AS-FASL #<SB-SYS:FD-STREAM for "file /home/foo/.cache/common-lisp/sbcl-2.1.9-linux-x64/home/foo/nyxt/source/global.fasl" {1009388B03}> NIL NIL)
10: ((LABELS SB-FASL::LOAD-STREAM-1 :IN LOAD) #<SB-SYS:FD-STREAM for "file /home/foo/.cache/common-lisp/sbcl-2.1.9-linux-x64/home/foo/nyxt/source/global.fasl" {1009388B03}> T)
11: (SB-FASL::CALL-WITH-LOAD-BINDINGS #<FUNCTION (LABELS SB-FASL::LOAD-STREAM-1 :IN LOAD) {7F824AD9697B}> #<SB-SYS:FD-STREAM for "file /home/foo/.cache/common-lisp/sbcl-2.1.9-linux-x64/home/foo/nyxt/source/global.fasl" {1009388B03}> T #<SB-SYS:FD-STREAM for "file /home/foo/.cache/common-lisp/sbcl-2.1.9-linux-x64/home/foo/nyxt/source/global.fasl" {1009388B03}>)
12: (LOAD #P"/home/foo/.cache/common-lisp/sbcl-2.1.9-linux-x64/home/foo/nyxt/source/global.fasl" :VERBOSE NIL :PRINT NIL :IF-DOES-NOT-EXIST T :EXTERNAL-FORMAT :DEFAULT)
13: (UIOP/UTILITY:CALL-WITH-MUFFLED-CONDITIONS #<FUNCTION (LAMBDA NIL :IN UIOP/LISP-BUILD:LOAD*) {100938860B}> ("Overwriting already existing readtable ~S." #(#:FINALIZERS-OFF-WARNING :ASDF-FINALIZERS)))
14: ((SB-PCL::EMF ASDF/ACTION:PERFORM) #<unused argument> #<unused argument> #<ASDF/LISP-ACTION:LOAD-OP > #<ASDF/LISP-ACTION:CL-SOURCE-FILE "nyxt" "global">)
15: ((LAMBDA NIL :IN ASDF/ACTION:CALL-WHILE-VISITING-ACTION))
16: ((:METHOD ASDF/ACTION:PERFORM-WITH-RESTARTS (ASDF/LISP-ACTION:LOAD-OP ASDF/LISP-ACTION:CL-SOURCE-FILE)) #<ASDF/LISP-ACTION:LOAD-OP > #<ASDF/LISP-ACTION:CL-SOURCE-FILE "nyxt" "global">) [fast-method]
17: ((:METHOD ASDF/ACTION:PERFORM-WITH-RESTARTS :AROUND (T T)) #<ASDF/LISP-ACTION:LOAD-OP > #<ASDF/LISP-ACTION:CL-SOURCE-FILE "nyxt" "global">) [fast-method]
18: ((:METHOD ASDF/PLAN:PERFORM-PLAN (T)) #<ASDF/PLAN:SEQUENTIAL-PLAN {10036A9DD3}>) [fast-method]
19: ((FLET SB-C::WITH-IT :IN SB-C::%WITH-COMPILATION-UNIT))
20: ((:METHOD ASDF/PLAN:PERFORM-PLAN :AROUND (T)) #<ASDF/PLAN:SEQUENTIAL-PLAN {10036A9DD3}>) [fast-method]
21: ((:METHOD ASDF/OPERATE:OPERATE (ASDF/OPERATION:OPERATION ASDF/COMPONENT:COMPONENT)) #<ASDF/LISP-ACTION:LOAD-OP > #<ASDF/SYSTEM:SYSTEM "nyxt/gi-gtk-application"> :PLAN-CLASS NIL :PLAN-OPTIONS NIL) [fast-method]
22: ((SB-PCL::EMF ASDF/OPERATE:OPERATE) #<unused argument> #<unused argument> #<ASDF/LISP-ACTION:LOAD-OP > #<ASDF/SYSTEM:SYSTEM "nyxt/gi-gtk-application">)
23: ((LAMBDA NIL :IN ASDF/OPERATE:OPERATE))
24: ((:METHOD ASDF/OPERATE:OPERATE :AROUND (T T)) #<ASDF/LISP-ACTION:LOAD-OP > #<ASDF/SYSTEM:SYSTEM "nyxt/gi-gtk-application">) [fast-method]
25: ((SB-PCL::EMF ASDF/OPERATE:OPERATE) #<unused argument> #<unused argument> ASDF/LISP-ACTION:LOAD-OP :NYXT/GI-GTK-APPLICATION)
26: ((LAMBDA NIL :IN ASDF/OPERATE:OPERATE))
27: ((:METHOD ASDF/OPERATE:OPERATE :AROUND (T T)) ASDF/LISP-ACTION:LOAD-OP :NYXT/GI-GTK-APPLICATION) [fast-method]
28: (ASDF/SESSION:CALL-WITH-ASDF-SESSION #<FUNCTION (LAMBDA NIL :IN ASDF/OPERATE:OPERATE) {10036A702B}> :OVERRIDE T :KEY NIL :OVERRIDE-CACHE T :OVERRIDE-FORCING NIL)
29: ((LAMBDA NIL :IN ASDF/OPERATE:OPERATE))
30: (ASDF/SESSION:CALL-WITH-ASDF-SESSION #<FUNCTION (LAMBDA NIL :IN ASDF/OPERATE:OPERATE) {10036865AB}> :OVERRIDE NIL :KEY NIL :OVERRIDE-CACHE NIL :OVERRIDE-FORCING NIL)
31: ((:METHOD ASDF/OPERATE:OPERATE :AROUND (T T)) ASDF/LISP-ACTION:LOAD-OP :NYXT/GI-GTK-APPLICATION) [fast-method]
32: (ASDF/OPERATE:LOAD-SYSTEM :NYXT/GI-GTK-APPLICATION)
33: (SB-INT:SIMPLE-EVAL-IN-LEXENV (ASDF/OPERATE:LOAD-SYSTEM :NYXT/GI-GTK-APPLICATION) #<NULL-LEXENV>)
34: (EVAL (ASDF/OPERATE:LOAD-SYSTEM :NYXT/GI-GTK-APPLICATION))
35: (SB-IMPL::PROCESS-EVAL/LOAD-OPTIONS ((:EVAL . "(require \"asdf\")") (:EVAL . #<(SIMPLE-ARRAY CHARACTER (259)) (when (string= "true" "true") (setf asdf:*default-source-registries* (list (quote asdf/source-registry:environment-source-registry))) (asdf:clear-configuration) (asdf:load-asd "/home/foo/nyxt... {100295549F}>) (:EVAL . "(asdf:load-asd \"/home/foo/nyxt//nyxt.asd\")") (:EVAL . "(when (find-package :ql) (funcall (read-from-string \"ql:quickload\") :cffi))") (:EVAL . #<(SIMPLE-ARRAY CHARACTER (235)) (when (and (find-package :cffi) (uiop:getenv "GUIX_ENVIRONMENT")) (pushnew (pathname (format nil "~a/lib/" (uiop:getenv "GUIX_ENVIRONMENT"))) (symbol-value (read-from-string "cffi:*foreign-library-dir... {1002955B0F}>) (:EVAL . "(asdf:load-system :nyxt/gi-gtk-application)") (:EVAL . "(asdf:make :nyxt/gi-gtk-application)") (:EVAL . "(uiop:quit)") (:QUIT)))
36: (SB-IMPL::TOPLEVEL-INIT)
37: ((FLET SB-UNIX::BODY :IN SB-IMPL::START-LISP))
38: ((FLET "WITHOUT-INTERRUPTS-BODY-1" :IN SB-IMPL::START-LISP))
39: (SB-IMPL::START-LISP)

unhandled condition in --disable-debugger mode, quitting
; 
; compilation unit aborted
;   caught 1 fatal ERROR condition
;   caught 1 WARNING condition
;   caught 73 STYLE-WARNING conditions
;   printed 3847 notes

Compilation failed, see the above stacktrace.

make: *** [makefile:36: nyxt] Error 1

**Comment by Ambrevar** [comment]
Do you have the `guix` executable in your path?

Do you have Quicklisp?

Do you have some libraries in ~/common-lisp?

Do you have Serapeum installed?

**Comment by ycpei** [comment]
> Do you have the `guix` executable in your path?

No, I don't have guix in the system and I don't see guix mentioned as a dependency to build nyxt anywhere.

> 
> Do you have Quicklisp?

No.

> 
> Do you have some libraries in ~/common-lisp?

No, but I have some libraries deep in the hiarachies under ~/.cache/common-lisp

> 
> Do you have Serapeum installed?

No, what is serapeum?

**Comment by Ambrevar** [comment]
No worries, you don't need Guix.

Serapeum is a Common Lisp library that's used here to test whether
"guix" is found in your path.  According to the error message, it is!

How did you check out the Nyxt repository?

**Comment by ycpei** [comment]
On Mon, Dec 06 2021, Pierre Neidhardt wrote:

> No worries, you don't need Guix.
>
> Serapeum is a Common Lisp library that's used here to test whether
> "guix" is found in your path. According to the error message, it is!

Which part of the error message implies I have guix in my path?  I just
did a `which guix` and it did not find anything.

>
> How did you check out the Nyxt repository?

git clone https://github.com/atlas-engineer/nyxt

>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
>


Best,
Yuchen

-- 
PGP Key: 47F9 D050 1E11 8879 9040  4941 2126 7E93 EF86 DFD0
          <https://ypei.me/assets/ypei-pubkey.txt>

**Comment by Ambrevar** [comment]
This error message:

>  Couldn't execute "guix": No such file or directory

Can you share the full trace?

**Comment by ycpei** [comment]
On 7 December 2021 21:39:26 GMT+11:00, Pierre Neidhardt ***@***.***> wrote:
>This error message:
>
>>  Couldn't execute "guix": No such file or directory
>
>Can you share the full trace?

It's in the original post of this issue[1].  Would you like me to paste it again?

[1] https://github.com/atlas-engineer/nyxt/issues/1910#issue-1071578755

>


-- 
Best,
Yuchen

Sent from a mobile device. Please excuse my brevity, typos and lack of pgp.

**Comment by Ambrevar** [comment]
It's not the full trace. how come so much is missing?  Are you sure you
didn't miss something?

**Comment by ycpei** [comment]
On Tue, Dec 07 2021, Pierre Neidhardt wrote:

> It's not the full trace. how come so much is missing? Are you sure you
> didn't miss something?

It did contain the full backtrace.  Or by "trace" did you want the full
stdout / stderr?  It was 61k+ lines.

>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
>


Best,
Yuchen

-- 
PGP Key: 47F9 D050 1E11 8879 9040  4941 2126 7E93 EF86 DFD0
          <https://ypei.me/assets/ypei-pubkey.txt>

**Comment by jmercouris** [comment]
Yes, the full stdout/stderr, probably as an attachment.

**Comment by aadcg** [comment]
Stale. Not enough information provided.
