### ISSUE TITLE
Understanding And Working With Nyxt Codebase

### ISSUE THREAD

**Issue by tvraman** [atlas-engineer/nyxt#1912]
* How To Read Nyxt Source Code

I have nyxt installed and am connected to the running instance from
slime and emacs. However I'm making very little progress in
understanding the codebase  with  the final goal of being able to
extend it to speak sensibly.

Note that I have not programmed in Common Lisp for a long time, but
that said, I did once write a fairly large system (codebase about 3X
that of nyxt) a long time ago.

Here is a summary of  some of what I tried  --- typing this up in the
hope that it gives the developers some pointers on how we might be
able to grow the dev community.

** Understanding A Mode (emacs-mode)

So in the hope of /learning by following my nose/, I tried to find
where keybindings were defined, in the hope that I'd then find the
implementations of specific commands that I could then extend to
produce speech, perhaps via an appropriate hook. AKA Use Case: make
the act of pressing the key that jumps to the next heading speak that
heading.

  1. Opened mode/emacs-mode.lisp and read the code.
  2. Nice and succinct but it told me nothing.
  3. Then I dove into the defining function for that mode and used
     _M-._ to jump around in the code base.
  4. I saw that magic appeared to happen in something called _scheme:emacs_.
  5. So _M-._ again on that symbol.
  6. That landed me on a defvar after which I had no where to go!

     I had similar experiences with the various other files in the
     mode directory.

     Next, I tried to follow my nose from the Slime-Repl buffer, again
     no luck.

  7. Package: nyxt-user
  8. Evaluate *browser* --- there is the browser handle!
  9. So next I navigated to the _browser_ class, and read the code.
  10. Clear code, readable, but doesn't tell me how it works or how to
      go twiddle with it.
  11. As an example, I see that that class has a _document-model_ slot
      as well as a _document-model_ defmethod.
  12. So in the repl, I tried various variants of (document-model
      *browser*) all of which threw a no-applicable-method error.

      Other things that are confusing when new to the codebase:

  13. The package structure --hierarchical names like _nyxt/foo_ are
    hard to guess.

  14. All in all I'm still lost. It looks deceptively simple, Nyxt is
      just about 10,000 lines of lisp, but here *deceptive* is the key
      --- somehow I feel that it's impossible to find one's way around
      without understanding all the package dependencies underneath!

      * Final Summary

        What might help would be some documentation that describes the
        overall architecture with reference to the codebase, alongside
        some illustrative examples. As it stands, the large dependency
        chain of sub-modules, the heavy use of CLOS extended by more
        packages, and a large number of extension macros turns the
        NYXT code base into 10,000 lines  written in what amounts to a
        foreign dialect.

**Comment by Ambrevar** [comment]
Hi @tvraman and thanks a lot for your feedback!

The developer documentation needs to be extended indeed.  We already have lots of docstrings but as you pointed out, we lack an overarching architectural description of the program.

Some of the core concepts are introduced in the manual.  Things like `mode`, `scheme`, etc.

Allow me to try to address some of your points:

6\. What do you mean with "nowhere to go"?  Where would you like to go, what did you expect?

10\. You seem to be expecting something specific, can you detail what that would be?

12\. You may have misread, `document-model` is a `buffer` slot, not a `browser` slot.  So if you try again with `(current-buffer)` as argument, it should work.

13\. Packages are mostly just `nyxt` and `nyxt/MODE-NAME`.  It's going to change with 3.0 though.  That said, why would you need to guess a package name?  Do you have a specific use case?  With SLY / SLIME you can lookup symbols across packages so that you never have to guess.

14\. You mention a large dependency chain of sub-modules, what do you mean exactly?  We have just a couple of "sub libraries" in the `libraries` folder, most of which are cleanly decoupled I believe.  Did you mean something else?  CLOS is heavily used indeed and it's a critical part of Nyxt and this would need a tutorial indeed.  The manual does cover it somewhat and the docstrings may help.  The "user class" architecture will be rewritten for 3.0.
Finally you mention a heavy use of macro that make Nyxt look like an extension language: can you give some examples?

**Comment by tvraman** [comment]
Pierre Neidhardt ***@***.***> writes:
Hi Pierre,

I'll inline my responses; please dont consider any of this as criticism,
I think Nyxt is an awesome piece of work.



> Hi @tvraman and thanks a lot for your feedback!
>
> The developer documentation needs to be extended indeed. We already
> have lots of docstrings but as you pointed out, we lack an overarching
> architectural description of the program.
Actually the embedded docstrings in many cases are redundant since a lot
of the identifier names are self-describing, so it just feels verbose
and cargo-cultish at times.


>
> Some of the core concepts are introduced in the manual. Things like
> mode, scheme, etc.
Yes, and I read that multiple times.

Yet, when I came down to trying my task; namely, find a command that I
can try to extend, perhaps via a hook to make it speak, I failed!



>
> Allow me to try to address some of your points:
>
> 6. What do you mean with "nowhere to go"? Where would you like to go,
> what did you expect?

I  meant where in the codebase to go to attempt my task described in my
write-up -- I have no clue.

>
> 10. You seem to be expecting something specific, can you detail what
> that would be?

Let me take emacs and my experience 25+ years ago when I started the
emacspeak project.
1. I knew that down-arrow or C-n invoked command next-line.
   2. I was able to find the next-line function.
      3. I knew about advice (replace advice here with hook or generic
         MOP in CLOS) and I now had everything in hand to attach a
         speak-line function to run at the end of the execution of
         command next-line.

         so in about 30 minutes from starting, I had some instant
         gratification.

         Now, compare the experience with attempting to make
         next-heading talk --
         

>
> 12. You may have misread, document-model is a buffer slot, not a
> browser slot. So if you try again with (current-buffer) as argument,

So the above explanation  buffer-slot vs browser-slot makes 0 sense to
me, so without understanding it, I'm likely to  treat it as voodoo, use
your (current-buffer) tip, but never understand why, which means I'll
also forget it fairly soon.

> it should work.
>

As another example of this type of cargo-cultism being dangerous -- long
time ago you showed me how to add emacs-mode to my init.lisp. When I
returned to nyxt a couple of weeks ago, my init.lisp failed because it
now needs a trailing '%' sign that it did not need before --- but I had
no clue why (still dont).
So I started fresh, deleted all of the lines in my init.lisp (wasn't
much there), then looked in the documentation of emacs-mode and again
with a bit of cargo-cult obedience, copied over the line from there into
my init.lisp -- it worked -- and it still took me a minute of staring at
it to realize that the difference was a '%'.

> 13. Packages are mostly just nyxt and nyxt/MODE-NAME. It's going to
> change with 3.0 though. That said, why would you need to guess a
> package name? Do you have a specific use case? With SLY / SLIME you

I attributed my no-applicable-method error mentioned earlier to perhaps
the result of my not using the right package name. I couldn't care less
about the package names:-)

> can lookup symbols across packages so that you never have to guess.
>
> 14. You mention a large dependency chain of sub-modules, what do you

I'll address above and the next point re heavy in macros -- note that
defclass is standard CLOS; define-class though a shorthand, and likely a
very convenient one once you know the package/module/lib that defines it
--- it makes the  language of Nyxt a very specific dialect -- think
Parisian vs Montreal French;-)

> mean exactly? We have just a couple of "sub libraries" in the
> libraries folder, most of which are cleanly decoupled I believe. Did

They're decoupled yes -- but see the comment re define-class above.

There is a *lot of magic* in the nyxt code base that takes more than an
understanding of CL and CLOS (already a huge language) to unravel the
mysteries of Nyxt.

> you mean something else? CLOS is heavily used indeed and it's a
> critical part of Nyxt and this would need a tutorial indeed. The

I dont think you need a CLOS tutorial
but you need a tutorial for the dialect of Lisp that Nyxt is today.

> manual does cover it somewhat and the docstrings may help. The "user
> class" architecture will be rewritten for 3.0.

That sounds nice, but each rearchitecture frightens me because it means
I have to relearn the little I learned.

> Finally you mention a heavy use of macro that make Nyxt look like an

See the define-class example above.

I think at this point the Nyxt developers are so familiar with the nyxt
code base that you might well be blind to some of these

> extension language: can you give some examples?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
>

-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♈ Id: kg:/m/0285kf1  🦮

**Comment by Ambrevar** [comment]
> Actually the embedded docstrings in many cases are redundant since a lot
> of the identifier names are self-describing, so it just feels verbose
> and cargo-cultish at times.

Feel free to point out those that seemed redundant and would need
fixing.  Help with documentation is always welcome, as it's a hard and
time-consuming task.

> Let me take emacs and my experience 25+ years ago when I started the
> emacspeak project.
> 1. I knew that down-arrow or C-n invoked command next-line.
> 	 2. I was able to find the next-line function.
> 			3. I knew about advice (replace advice here with hook or generic
> 				 MOP in CLOS) and I now had everything in hand to attach a
> 				 speak-line function to run at the end of the execution of
> 				 command next-line.
>
> 				 so in about 30 minutes from starting, I had some instant
> 				 gratification.
>
> 				 Now, compare the experience with attempting to make
> 				 next-heading talk --

It's very similar in Nyxt.

If you call `describe-variable` and type "jump" you'll find a bunch of
Serapeum hooks, among which NYXT/WEB-MODE:JUMP-TO-HEADING-AFTER-HOOK`.  (All this is
mentioned in the manual, feel free to correct it if you think it's not
clear.)

You can then add a hook as per the Serapeum API (see the manual for an example).

> buffer-slot vs browser-slot makes 0 sense to
> me, so without understanding it

Can you detail what is confusing you?

A buffer is a web view with state (like an Emacs buffer).

The browser is the object that holds all the global, non-buffer-specific
information.

You can find documentation about this using `describe-class` then select
`buffer` or `browser`.

> define-class

It's a wrapper (details don't matter) around hu.dwim.defclass-star,
which is a fairly popular library in the Common Lisp ecosystem.  It
extends the default CLOS syntax and is backward-compatible.
The main difference is that the second element in the slot declaration
is optionally the :initform.  It's fairly intuitive when you read the code I
believe.

That's it really :)

What else do you find strange in the Nyxt use of Common Lisp?

> There is a *lot of magic* in the nyxt code base that takes more than an
> understanding of CL and CLOS (already a huge language) to unravel the
> mysteries of Nyxt.

I'm a bit surprised by this statement.  Can you provide some examples?

> That sounds nice, but each rearchitecture frightens me because it means
> I have to relearn the little I learned.

We made mistakes for 2.0 (or simply didn't have the time to polish
everything) which must be fixed for 3.0.  We will try to make the
transition as smooth as possible and hopefully backward-compatible.

We try to document all these changes in the Change Log.

> I think at this point the Nyxt developers are so familiar with the nyxt
> code base that you might well be blind to some of these

We welcome third-party feedback anytime! :)

**Comment by aadcg** [comment]
Stale.
