### ISSUE TITLE
Cannot load history or save history

### ISSUE THREAD

**Issue by franburstall** [atlas-engineer/nyxt#1914]
**Describe the bug**

I rebuilt and fired nyxt for the first time in a few months and get the following error on startup:
```
WARN - Warning: Failed to restore history from /home/fran/.local/share/nyxt/history/default.lisp: Symbol "CURRENT-OWNER-ID" not found in the HISTORY-TREE package. Line: 19239, Column: 20, File-Position: 4636955 Stream: #
```
On exiting and trying again, I get no error but the first page displayed is about:blank and it looks like my history has been wiped.  Not so friendly!

On a third attempt, I open a url, the page displays fine and then I exit.  On reopening nyxt, I again get about:blank and no other page loaded.

**Information**
- OS name+version: debian 11
- Graphics card and driver: 
- Desktop environment / Window manager name+version: exwm
- How you installed Nyxt (Guix pack, package manager, build from source): source
- Information from `show-system-information`:

Nyxt version: 2.1.1-876-g79c5aef9
Renderer version: GI-GTK
Operating system kernel: Linux 5.10.0-9-amd64
Lisp implementation: SBCL 2.1.1 (Dynamic space size: 1073741824)
Features: (:WEBKIT2 :WEBKIT2-2.34 :WEBKIT2-PASTE-PLAINTEXT :WEBKIT2-TRACKING
 :WEBKIT2-MUTE :WEBKIT2-EMOJI :WEBKIT2-MEDIA :WEBKIT2-SANDBOXING :GTK-3-22
 :GTK-3-20 :GTK-3-18 :GTK-3-16 :GTK-3-14 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6
 :GTK-3-4 :GTK :GDK-3-22 :GDK-3-20 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12
 :GDK-3-10 :GDK-3-8 :GDK-3-6 :GDK-3-4 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF
 :GLIB-2-30 :GLIB-2-32 :GLIB-2-34 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42
 :GLIB-2-44 :GLIB-2-46 :GLIB-2-48 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56
 :GLIB-2-58 :GLIB :NYXT-2 :FSET-EXT-STRINGS :CUSTOM-HASH-TABLE-NATIVE :SWANK
 :PLUMP-UTF-32 :GLOBAL-VARS :DECLARE-TYPES :PARENSCRIPT
 :SBCL+SAFE-STANDARD-READTABLE :NAMED-READTABLES :LPARALLEL :21BIT-CHARS
 :CHUNGA :CLOSER-MOP :CL-PPCRE-UNICODE :FLEXI-STREAMS :CL-UNICODE :CL-PPCRE
 :CL-JSON-DOUBLE-FLOAT-IS-SUBSUMED :CL-JSON-SINGLE-FLOAT-IS-SUBSUMED
 :BORDEAUX-THREADS :LPARALLEL.WITH-CLTL2 :LPARALLEL.WITH-CAS
 :LPARALLEL.WITH-STEALING-SCHEDULER :SPLIT-SEQUENCE CHIPZ-SYSTEM:GRAY-STREAMS
 CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64 CFFI-FEATURES:UNIX :CFFI
 CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP :FAST-IO-SV :FAST-IO
 :SBCL-USES-SB-ROTATE-BYTE :ASDF-SYSTEM-CONNECTIONS :CL-JSON-CLOS :CL-JSON
 :THREAD-SUPPORT :ASDF3.3 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX
 :NON-BASE-CHARS-EXIST-P :ASDF-UNICODE :X86-64 :GENCGC :64-BIT :ANSI-CL
 :COMMON-LISP :ELF :IEEE-FLOATING-POINT :LINUX :LITTLE-ENDIAN
 :PACKAGE-LOCAL-NICKNAMES :SB-LDB :SB-PACKAGE-LOCKS :SB-THREAD :SB-UNICODE
 :SBCL :UNIX)

ASDF version: 3.3.1
ASDF registries: (NYXT-SOURCE-REGISTRY ENVIRONMENT-SOURCE-REGISTRY)
Critical dependencies: (/home/fran/common-lisp/nyxt/_build/cl-cffi-gtk/gtk/cl-cffi-gtk.asd
 /home/fran/common-lisp/nyxt/_build/cl-gobject-introspection/cl-gobject-introspection.asd
 /home/fran/common-lisp/nyxt/_build/cl-webkit/webkit2/cl-webkit2.asd)

**Comment by Ambrevar** [comment]
@jmercouris @aartaka I also get this on master, what's going on?

**Comment by Ambrevar** [comment]
Note that `2-series` is fine.

**Comment by aartaka** [comment]
I cannot reproduce 0_o

**Comment by aartaka** [comment]
The only history-related change I can think of is e0259a78f750b73b764da93a15c77651bfee57ce, but it shoudn't break history loading (⊙…⊙ )

**Comment by Ambrevar** [comment]
As Fran noted, we should also avoid overwriting on error.  We already discussed this in the past.  Maybe automatically create rolling backups?

**Comment by jmercouris** [comment]
I get this error when I first run 2.0.0 on my machine, and then I use latest master. I usually just press the continue restart at the prompt and overwrite my history.

**Comment by Ambrevar** [comment]
Really 2.0.0, or the latest 2.2.3?

For me I can reproduce with 2.2.3 as John explained.
Did someone change the data structure on master?

**Comment by jmercouris** [comment]
Technically 2.1.1, but Nixpkgs I believe only has 2.0.0.

The data structure did not change on master. I have had this problem since I can remember.
