### ISSUE TITLE
Emacs-mode and vi-normal-mode should be commands, not modes

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#1915]
In https://github.com/atlas-engineer/nyxt/issues/1871#issuecomment-986839343 @mariari was confused about how emacs-mode and vi-normal-mode worked, in particular that the order of activation changed the inheritance, which is indeed counter-intuitive,

The way Nyxt bindings are looked up is by navigating a bidimensional matrix: 
- 1 dimension is the mode keymaps,
- the other one the schemes.

While it makes sense to toggle modes to also toggle their keymaps, it looks like a cognitive dissonance that we also have to toggle a mode to change scheme.
Also note that we can have both vi-normal-mode and emacs-mode enabled at the same time, while only one scheme is set, so this does not make much sense.

What we could do instead is have a command that lists the known schemes and sets the chosen one.  The current scheme would be displayed in the status area, just like we display the VI indicator today.

The only remaining question is what we do of the code that's in `emacs.lisp` and, most importantly, `vi.lisp`?  Some state must be stored, where?
We also specialize `on-signal-load-finished` against `vi-insert-mode`, so if we remove the mode, what do we specialize it against?

@jmercouris @aartaka ?

**Comment by Ambrevar** [comment]
Ping! :)

**Comment by aartaka** [comment]
> The only remaining question is what we do of the code that's in `emacs.lisp` and, most importantly, `vi.lisp`? Some state must be stored, where? 

`*browser*`? :D It's the most "global" space for settings that we have. Alternatively, store it in the `base-mode` as the most general mode.

>We also specialize `on-signal-load-finished` against `vi-insert-mode`, so if we remove the mode, what do we specialize it against?

Not sure about it. If we store it in `base-mode`, then we can specialize against `base-mode`. Maybe move it to the `buffer`-specialized method? Feels wrong, though. Having it isolated in it's own mode sounds like a nice solution here, but yes, it does indeed have its own deficiencies.

**Comment by jmercouris** [comment]
I'm afraid I don't have a good answer to your question about storing the state.

**Comment by Ambrevar** [comment]
See also #1841.

**Comment by aadcg** [comment]
Seems like a good plan.

This is a minor thing, but why was the name `scheme` chosen?

**Comment by Ambrevar** [comment]
For the lack of a more inspired one... Less confusing names are welcome :)

**Comment by aadcg** [comment]
> X uses the terms "layout" and "variant". The benefit of "layout" compared
to "family" is that it hints at this is about the disposition of
something (here keys), so it's a bit more specific than "family".

Careful. "layout" and "variant" are completely different things. The way keys are bound is not related to spacial (keyboard) disposition. 

I don't see what prevent us from being explicit and use "keybinding-family". Informally, in discussions, we may simply say "family", but that would be ok.

**Comment by aadcg** [comment]
It's worth noting that we use the concept of `scheme` for two completely different things - "keybinding-family" and URL schemes. 

I'd like to ask for a consensus to rename `scheme` (in the context of keybindings), whatever it might be :)

**Comment by Ambrevar** [comment]
Yes, "family" is OK, I was simply explaining how confusions can arise
from the dropping of terms.  "keybinding-scheme" is unambiguous, but
"scheme" is not, and this is precisely what happened to Nyxt :/

I'm with "family".

**Comment by Ambrevar** [comment]
Actually there are two terms here: a `scheme-name` like `scheme:cua` or `scheme:emacs`.  And then the "keymap schemes" per se, which are pairs of (scheme-name keymaps).

Switching to `family` and `family-name` won't help here, because the pairs are not really "families" (actually "scheme" fits better here).

Proposal 1: Rename `scheme-name` to `family` and `keymap-scheme` to `familymap`.

Other proposal, anyone?  @jmercouris @pdelfino @aadcg @aartaka ?

**Comment by pdelfino** [comment]
> Proposal 1: Rename `scheme-name` to `family` and `keymap-scheme` to `familymap`.

Seems like an improvement! My minor suggestion would just be to keep the hyphenation. 

So, from `keymap-scheme` to `family-map` instead of `familymap`. Not sure why you omitted `-`.  Typo? Did I miss some convention on when to hyphenate?

**Comment by aartaka** [comment]
Indeed, `keymap` is familliar and sensible enough -- it mentions keys and mapping those to something.

**Comment by aadcg** [comment]
Ok, I'll get it after #2297 is merged.

**Comment by Ambrevar** [comment]
@pdelfino I didn't put the hyphen intentionally to be consistent with `keymap`.

@aadcg @aartaka That wouldn't do, `keymap` is already the contained object!  A family contains multiple keymaps.

See my comment above:

> And then the "keymap schemes" per se, which are pairs of (scheme-name keymaps).

**Comment by aadcg** [comment]
Ahh, I see it now! 

I spent some time trying to think about this the other way around: what should be written in the mode's slot?

Today it looks roughly like this:

```lisp
(keymap-scheme (define-scheme "foo"
                 scheme:cua (list "key1" 'command)
                 scheme:emacs (list "key2" 'command)
                 scheme:vi-normal (list "key3" 'command)
                 ...)
             :type keymap:scheme)

(defmacro define-scheme (scheme-specifier name bindings &rest more-name+bindings-pairs)
  ...)
```

My suggestion:
```lisp
(keybindings (define-key-lookup "foo"
               kind/pattern/genre/variety:cua (list "key1" 'command)
               kind/pattern/genre/variety:emacs (list "key2" 'command)
               kind/pattern/genre/variety:vi-normal (list "key3" 'command)
               ...)
             :type keymap:key-lookup)

(defmacro define-key-lookup (handler kind/pattern/genre/variety keymap
                             &rest more-kind/pattern/genre/variety+keymap-pairs)
  ...)
```

Indeed, I now see that `family` was a bad idea. My favorite among kind, pattern, genre and variety is kind.

Our keybindings are defined by 2 data structure: the `keymap` and the `key-lookup`. Both are maps (or a product in the language of category theory); the former associates keys to commands or other keymaps (we don't do it yet AFAIK), while the latter associates a kind/pattern/genre/variety to keymaps.

**Comment by Ambrevar** [comment]
>  or other keymaps (we don't do it yet AFAIK),

Yes we do, it's how we support key sequences like "C-x C-s".

`key-lookup` sounds much more like an action (a function?) than a data structure.  I find it counter-intuitive.

"kind/pattern/genre" are all too generic.  "variety" is also generic but less used in programming languages.  But that's not too different from "family", which I was OK with.

**Comment by aadcg** [comment]
I agree to go with `family` and `familymap`.

```lisp
(keybindings (define-familymap "foo"
               family:cua (list "key1" 'command
                                ...)
               family:emacs (list "key2" 'command
                                  ...)
               family:vi-normal (list "key3" 'command
                                      ...)
               ...)
             :type keymap:familymap)

(defmacro define-familymap (handler family keymap &rest more-family+keymap-pairs)
  ...)
```

**Comment by Ambrevar** [comment]
I like @aadcg last suggestion.

Anyone else?

**Comment by aartaka** [comment]
Yes, looks good to me.

**Comment by jmercouris** [comment]
I am at peace with the consensus :-)

**Comment by Ambrevar** [comment]
And... let's bring up the bikeshed again!

More seriously, it's API-breaking, so let's try to get this right.

While I agree with how consistent the new names are, I don't like "family" that much:
- It's a generic term that could be introduce in another context some day and thus create ambiguities.
- More importantly, it does not make it obvious that we are  talking about _keys_ here.

Take this sentence: "Do you use the CUA family?"  If the reader does not know what CUA is, they won't be able to guess that we are talking about _keys_.

Yet worse: "Which family do you use?  Emacs?"  Am I being asked if I use Emacs or XEmacs or Lucid Emacs? O.o

I believe the word "key" should appear.  Now what term do we use in our "Common settings"?  _Keybinding style_.  That's right, we do not even talk about schemes or family :p 

So what about **keystyle** instead?

Then we would have

```lisp
(keybindings (define-keystylemap "foo"
               keystyle:cua (list "key1" 'command
                                ...)
               keystyle:emacs (list "key2" 'command
                                  ...)
               keystyle:vi-normal (list "key3" 'command
                                      ...)
               ...)
             :type keymap:keystylemap)

(defmacro define-keystylemap (handler keystyle keymap &rest more-keystyle+keymap-pairs)
  ...)
```

Thoughts?

**Comment by aadcg** [comment]
>  I believe the word "key" should appear. 

That's the key observation. I defended that from day 1 :)

Style is indeed the usual concept people use. "Do you use vi/emacs style keybindings?". Honestly, it doesn't sound correct to me, but we should be on the side of familiarity here (pun intended)!

The "correct" concept would actually be `keybindings-style`, but that would be perhaps too verbose. 

All that to say that I agree.

**Comment by Ambrevar** [comment]
Yes, you mentioned `keybinding-family`, etc. but my concern was that just as with `keybinding-scheme` or `keymap-scheme`, the prohibitive length of the term would push us to drop the prefix and thus lose the meaning.  With `keystyle`, we are short enough that we would stick to it.

> "Do you use vi/emacs style keybindings?". Honestly, it doesn't sound correct to me, 

It does to me, actually, I've seen this kind of phrasings many times around.

**Comment by Ambrevar** [comment]
Other suggestions: `keytheme` (from John) or `keyscheme` to stick to what we have.

**Comment by aadcg** [comment]
`keyscheme` would be ok, it's an improvement over `scheme` alone!

**Comment by Ambrevar** [comment]
Pfeeeew, we're finally done with this!  Hooray!

**Comment by aadcg** [comment]
Yup! Thank you for the persistence @Ambrevar.

**Comment by Ambrevar** [comment]
Yes, "family" is OK, I was simply explaining how confusions can arise
from the dropping of terms.  "keybinding-scheme" is unambiguous, but
"scheme" is not, and this is precisely what happened to Nyxt :/

**Comment by Ambrevar** [comment]
The full name of `scheme' is actually `binding-scheme`.  But obviously,
since it's too long, we've loosely used `scheme', which clashes with
many other uses of the word.

Similary, "keybinding-family" is bound to be dropped in favour of just "family".

Still, I like "family" (more than "scheme") because it (currently)
doesn't clash with anything.  The drawback is that it's such a generic
term that it may very well be used later on by another library.

X uses the terms "layout" and "variant".  The benefit of "layout" compared
to "family" is that it hints at this is about the disposition of
something (here keys), so it's a bit more specific than "family".
