### ISSUE TITLE
Nyxt cannot find slynk

### ISSUE THREAD

**Issue by franburstall** [atlas-engineer/nyxt#1916]
**Describe the bug**

In my init.lisp, I have the line:
```
(load-after-system :slynk "~/.config/nyxt/my-slynk.lisp")
```
This newly errors out:
```
Warning: Could not load system SLYNK: Component :SLYNK not found
```
Is this an artifact of the new submodules rather than quicklisp build mechanism?  What must I do to get slynk/sly working again?

**Information**
- OS name+version: debian-11
- Graphics card and driver:
- Desktop environment / Window manager name+version: exwm
- How you installed Nyxt (Guix pack, package manager, build from source): source
- Information from `show-system-information`:

Nyxt version: 2.1.1-876-g79c5aef9
Renderer version: GI-GTK
Operating system kernel: Linux 5.10.0-9-amd64
Lisp implementation: SBCL 2.1.1 (Dynamic space size: 1073741824)
Features: (:WEBKIT2 :WEBKIT2-2.34 :WEBKIT2-PASTE-PLAINTEXT :WEBKIT2-TRACKING
 :WEBKIT2-MUTE :WEBKIT2-EMOJI :WEBKIT2-MEDIA :WEBKIT2-SANDBOXING :GTK-3-22
 :GTK-3-20 :GTK-3-18 :GTK-3-16 :GTK-3-14 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6
 :GTK-3-4 :GTK :GDK-3-22 :GDK-3-20 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12
 :GDK-3-10 :GDK-3-8 :GDK-3-6 :GDK-3-4 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF
 :GLIB-2-30 :GLIB-2-32 :GLIB-2-34 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42
 :GLIB-2-44 :GLIB-2-46 :GLIB-2-48 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56
 :GLIB-2-58 :GLIB :NYXT-2 :FSET-EXT-STRINGS :CUSTOM-HASH-TABLE-NATIVE :SWANK
 :PLUMP-UTF-32 :GLOBAL-VARS :DECLARE-TYPES :PARENSCRIPT
 :SBCL+SAFE-STANDARD-READTABLE :NAMED-READTABLES :LPARALLEL :21BIT-CHARS
 :CHUNGA :CLOSER-MOP :CL-PPCRE-UNICODE :FLEXI-STREAMS :CL-UNICODE :CL-PPCRE
 :CL-JSON-DOUBLE-FLOAT-IS-SUBSUMED :CL-JSON-SINGLE-FLOAT-IS-SUBSUMED
 :BORDEAUX-THREADS :LPARALLEL.WITH-CLTL2 :LPARALLEL.WITH-CAS
 :LPARALLEL.WITH-STEALING-SCHEDULER :SPLIT-SEQUENCE CHIPZ-SYSTEM:GRAY-STREAMS
 CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64 CFFI-FEATURES:UNIX :CFFI
 CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP :FAST-IO-SV :FAST-IO
 :SBCL-USES-SB-ROTATE-BYTE :ASDF-SYSTEM-CONNECTIONS :CL-JSON-CLOS :CL-JSON
 :THREAD-SUPPORT :ASDF3.3 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX
 :NON-BASE-CHARS-EXIST-P :ASDF-UNICODE :X86-64 :GENCGC :64-BIT :ANSI-CL
 :COMMON-LISP :ELF :IEEE-FLOATING-POINT :LINUX :LITTLE-ENDIAN
 :PACKAGE-LOCAL-NICKNAMES :SB-LDB :SB-PACKAGE-LOCKS :SB-THREAD :SB-UNICODE
 :SBCL :UNIX)

ASDF version: 3.3.1
ASDF registries: (NYXT-SOURCE-REGISTRY ENVIRONMENT-SOURCE-REGISTRY)
Critical dependencies: (/home/fran/common-lisp/nyxt/_build/cl-cffi-gtk/gtk/cl-cffi-gtk.asd
 /home/fran/common-lisp/nyxt/_build/cl-gobject-introspection/cl-gobject-introspection.asd
 /home/fran/common-lisp/nyxt/_build/cl-webkit/webkit2/cl-webkit2.asd)

**Comment by Ambrevar** [comment]
Indeed, by default Nyxt does not load load libraries from the default ASDF registries (since 2.0 if I recall correctly).

See the line

> ASDF registries: (NYXT-SOURCE-REGISTRY ENVIRONMENT-SOURCE-REGISTRY)

?

This means .asd files are found in the NYXT-SOURCE-REGISTRY (~/.local/share/nyxt/extensions by default) and from the CL_SOURCE_REGISTRY environment variable (as per the ASDF manual).

We did this because many users reported breakages due to system/user-installed libraries.

You can either install SLY / SLYNK to ~/.local/share/nyxt/extensions or restore the ASDF source registry to the default value, namely

```lisp
(NYXT:NYXT-SOURCE-REGISTRY
 ASDF/SOURCE-REGISTRY:ENVIRONMENT-SOURCE-REGISTRY
 ASDF/SOURCE-REGISTRY:USER-SOURCE-REGISTRY
 ASDF/SOURCE-REGISTRY:USER-SOURCE-REGISTRY-DIRECTORY
 ASDF/SOURCE-REGISTRY:DEFAULT-USER-SOURCE-REGISTRY
 ASDF/SOURCE-REGISTRY:SYSTEM-SOURCE-REGISTRY
 ASDF/SOURCE-REGISTRY:SYSTEM-SOURCE-REGISTRY-DIRECTORY
 ASDF/SOURCE-REGISTRY:DEFAULT-SYSTEM-SOURCE-REGISTRY)
```

I think we should document this and maybe add a helper function.  What do you people think?
@jmercouris @aartaka @pdelfino

**Comment by franburstall** [comment]
Some documentation is needed as the developer's README has not changed and that treats swank and slynk on an equal footing.  However, slynck now needs installation while swank is built-in.

**Comment by jmercouris** [comment]
Yes, this could use documentation, but only in the developer README I think. For other use cases, I don't think it will be necessary.

**Comment by Ambrevar** [comment]
Fran, did you manage to get Slynk to work then?

**Comment by franburstall** [comment]
Yup: I cloned the sly repo into ~/.local/share/nyxt/extensions and all was
good.  However, this means I am maintaining a copy of sly: exactly the
problem I would want quicklisp to solve.

**Comment by Ambrevar** [comment]
I'm not sure what you mean.  How would Quicklisp help here?

The default ASDF settings (without Quicklisp) should be enough to find
your local SLY install.  Is that what you meant?

**Comment by franburstall** [comment]
What I mean is that if sly/slynk needs an update, I must notice this fact
and do it myself by pulling from the repo.  Before, I could simply update
quicklisp once a month and know that all the lisp libraries I use were
current.

**Comment by Ambrevar** [comment]
How do you install SLY?  Via Quicklisp?
I would expect that it would be installed via Emacs.

How does one install SLY via Quicklisp and have it loaded into Emacs?

**Comment by franburstall** [comment]
I install sly to emacs from MELPA via the emacs package manager.  But that
does not seem to make the slynk component available to sbcl (as sbcl knows
nothing about my emacs installation).  I therefore have slynk installed
into sbcl by quicklisp.  All this Just Worked with nyxt until recently...

If there is a better way to do this, please share!

**Comment by Ambrevar** [comment]
SLY automatically exposes its Slynk to ASDF when you run the REPL.

In other words, you only need to install Slynk manually if you intend to
run your Lisp compiler manually, outside of SLY.

**Comment by franburstall** [comment]
So I must run sly first in emacs before firing nyxt?  I had been firing
nyxt first and getting the slynk server running from my init.lisp and then,
if I wanted a repl, doing sly-connect in emacs.  But this means that
nyxt/sbcl needs to know how to load slynk before I open a repl in emacs
(hence this ticket).

**Comment by Ambrevar** [comment]
There are multiple ways to connect SLY to Nyxt for sure.

The benefit of loading Slynk into Nyxt (like you intend to do in this
ticket) is that you can run SLY after-the-fact, that is, after starting
Nyxt normally (like any desktop application).

If you spend your time in a SLY REPL, however, there are benefits
starting Nyxt directly from there using `(nyxt:start)` (like finer
control).

Can you report the output of `asdf:*default-source-registries*` when you
run SBCL from a shell (with Quicklisp loaded)?

**Comment by franburstall** [comment]
(ASDF/SOURCE-REGISTRY:ENVIRONMENT-SOURCE-REGISTRY
 ASDF/SOURCE-REGISTRY:USER-SOURCE-REGISTRY
 ASDF/SOURCE-REGISTRY:USER-SOURCE-REGISTRY-DIRECTORY
 ASDF/SOURCE-REGISTRY:DEFAULT-USER-SOURCE-REGISTRY
 ASDF/SOURCE-REGISTRY:SYSTEM-SOURCE-REGISTRY
 ASDF/SOURCE-REGISTRY:SYSTEM-SOURCE-REGISTRY-DIRECTORY
 ASDF/SOURCE-REGISTRY:DEFAULT-SYSTEM-SOURCE-REGISTRY)

**Comment by Ambrevar** [comment]
Thanks for confirming, I'll send a patch suggestion soon!

**Comment by Ambrevar** [comment]
@franburstall Can you try #1928 see if it does the trick for you?

**Comment by edgar-vincent** [comment]
FWIW, in order to avoid having to keep two copies of Sly up-to-date, I simply made a symlink in `~/.local/share/nyxt/extensions/` to the `slynk` subdirectory of the `sly` package in my Emacs installation.

**Comment by franburstall** [comment]
> @franburstall Can you try #1928 see if it does the trick for you?

Yup: works perfectly.

**Comment by franburstall** [comment]
> FWIW, in order to avoid having to keep two copies of Sly up-to-date, I simply made a symlink in `~/.local/share/nyxt/extensions/` to the `slynk` subdirectory of the `sly` package in my Emacs installation. This allows me to make sure that Nyxt is not "contaminated" by other Lisp libraries I might have installed locally, as I only need it to load `slynk`.

Good idea but I get the emacs sly from MELPA and so the location of the sly package changes with the version number which would break the symlink.

**Comment by Ambrevar** [comment]
Thanks for your feedback, Fran.
Closing now, feel free to reopen if there is anything else.
