### ISSUE TITLE
Documentation: clarify panel buffers | Feature Request: create a button to close panel buffers

### ISSUE THREAD

**Issue by pdelfino** [atlas-engineer/nyxt#1918]
This [question](https://discourse.atlas.engineer/t/how-to-close-the-bookmark-panel/364/2) motivated the issue.
Tasks:
- [ ] clarify documentation
- [ ] create the button to close panel buffers

**Comment by aartaka** [comment]
Even better: clarify the documentation AND add a close button to all the panel buffers!

**Comment by pdelfino** [comment]
Indeed, Artyom. I will split the tasks in this issue.

**Comment by guojing0** [comment]
By "documentation" do you mean documentation in the code, beacuse I could not find any mentions of it in the [manual](https://nyxt.atlas.engineer/documentation)?

**Comment by jmercouris** [comment]
Any documentation in the code is available to the user by using one of our "describe-*" type commands. These commands show the documentation interactively to the user. Therefore, something not appearing in the manual does not mean it is not in the documentation.

**Comment by guojing0** [comment]
@pdelfino Do you have some idea as to where to put the close-panel button?

**Comment by pdelfino** [comment]
![close-button-panel-buffer](https://user-images.githubusercontent.com/7698207/147753098-ecdbd9b7-7aa7-41f9-b1bb-9e2ea3b82145.jpg)

@guojing0 , what do you think on putting it on the upper right corner of the panel buffer?  

Check out the image with a rudimentary drawing.

**Comment by guojing0** [comment]
@pdelfino I agree with your suggestion. Somewhere below "Buffers" and above "Update" can also be good.

**Comment by guojing0** [comment]
After giving it some more thoughts today, I think even if we currently only have three kinds of panel buffers (bookmarks, buffers, and headings), it's still possible that we will have more in the future. Looking at their implementations, I think it's possible that panel buffers in the future may not look all the same given their tasks. It then implies that what works for current condition (like the button place we agreed on in the image) may not work for different panels in the future.

So, should the responsibility of creating such button falls to the one who defines that panel?

**Comment by aadcg** [comment]
The button already exits. With respect to docs, it's an on going effort. Thanks.
