### ISSUE TITLE
Feature request related to documentation: introduce a button in the manual to create an init-file, in case there is not one available

### ISSUE THREAD

**Issue by pdelfino** [atlas-engineer/nyxt#1923]
The manual does not indicate that the `init.lisp` is **not** dynamically created.  It needs to be created by the user.

Even if the file is not created, the manual will show something like: "Nyxt configuration can be persisted in the user file `/home/pedro/.config/nyxt/init.lisp`." This leaves the impression the file was already created just like bookmarks or history which  can be especially confusing for new users. 

Talking to @jmercouris, an idea emerged: inserting in the manual a function that indicates if the file was already created or not. In case it was not created, show a button like `Create init file`. There is already a comment "(create the parent folders if necessary)" but the function to identify and the button seem better, especially for newcomers.

I will send a PR about it soon.

**Comment by guojing0** [comment]
Hi, after seeing that you haven't sent a PR yet, so I was working on this.

During the process, I realize something: Instead of letting the user press the button, would it be OK to just let Nyxt automatically create `init.lisp`, if said file had not existed yet.

@jmercouris What do you think of this option?

**Comment by jmercouris** [comment]
I think we should leave it in control of the user to create this file. I don't think the user would appreciate new files in `~/.config/` without explicit consent (this is of different than `~/.local/share/` (a directory in which we do automatically create files)).

**Comment by jmercouris** [comment]
Jing pointed out that `auto-conf.lisp` is automatically created AND located in `~/.config`. This is of course a problem if the above comment makes nay sense. It is of my opinion therefore that we either prompt the user before the creation of the `auto-config.lisp` file OR move its location to `~/.local/share`.

**Comment by pdelfino** [comment]
I am closing this since @guojing0's work was squashed and merged by Pierre as https://github.com/atlas-engineer/nyxt/commit/1b57e8c71f8351f3e75041d562a04b246479cd3f. 

Thanks!
