### ISSUE TITLE
Bug: Nyxt stable release (2.0.0) does not load

### ISSUE THREAD

**Issue by pdelfino** [atlas-engineer/nyxt#1935]
**Describe the bug**
Downloaded Nyxt (verison 2.0.0) does not launch successfully.  **Observation**: Under the same env, I **can run** from source the current version of Nyxt.

**Precise recipe to reproduce the issue**
- after installing Nyxt, open terminal
- try to open Nyxt with the command: `$ nyxt
- Nyxt does not launch succesfully, the terminal only indicates forever:
```lisp
$ nyxt
<INFO> [14:51:31] Listening to socket "/run/user/1000/nyxt/nyxt.socket".
Nyxt version 2.0.0
<INFO> [14:51:31] Loading Lisp file "/home/pedro/.config/nyxt/init.lisp".
<WARN> [14:51:31] Warning: Error on GTK thead: unknown type specifier: LAMBDA
```                        

For website-specific issues:
Can you reproduce this issue with Epiphany / GNOME Web (https://wiki.gnome.org/Apps/Web)?
Not related

**Information**
- OS name+version: NixOS  21.05. You can see my NixOS config file [here](https://github.com/pdelfino/my-nixos-config/blob/main/configuration.nix). 

- Graphics card and driver:
product: Iris Plus Graphics 640
configuration: driver=i915 latency=0

- Desktop environment / Window manager name+version: GNOME 40.1.0

- Window System: Wayland

- How you installed Nyxt (Guix pack, package manager, build from source): package manager

- Information from `show-system-information`:
Not possible

**Output when started from a terminal**

```bash
$ nyxt
<INFO> [14:51:31] Listening to socket "/run/user/1000/nyxt/nyxt.socket".
Nyxt version 2.0.0
<INFO> [14:51:31] Loading Lisp file "/home/pedro/.config/nyxt/init.lisp".
<WARN> [14:51:31] Warning: Error on GTK thead: unknown type specifier: LAMBDA
```

**Comment by pdelfino** [comment]
I found out it was a silly problem.  With `nyxt -IC` it **does** work. With `nyxt -C` it **does not** work. With `nyxt -I` it **does** work.Thus... the problem is this part in my init file:

``` lisp
(define-configuration buffer
  ((override-map (let ((map (make-keymap "override-map")))
                   (define-key map
                      ;; "C-space" 'nothing
                      "C-x C-b" 'switch-buffer
                      "M-x" 'execute-command
                      "C-n" 'nyxt/web-mode:scroll-down
                      "C-p" 'nyxt/web-mode:scroll-up
                      "C-f" 'nyxt/web-mode:scroll-right
                      "C-b" 'nyxt/web-mode:scroll-left
                      "C-g" 'query-selection-in-search-engine
                      "M-s->" 'nyxt/web-mode:scroll-to-bottom
                      "M-s-<" 'nyxt/web-mode:scroll-to-top
                      "C-s" 'nyxt/web-mode:search-buffer
                      "M-w" 'nyxt/web-mode:copy
                      "C-y" 'nyxt/web-mode:paste
                      "C-Y" 'nyxt/web-mode:paste-from-clipboard-ring)))))

```

The line commented out is the one problematic. The stable release 2.0.0.0 does not handle the `'nothing` command.

**Comment by Ambrevar** [comment]
> <WARN> [14:51:31] Warning: Error on GTK thead: unknown type specifier: LAMBDA

This indicates your error.

Why did you close the issue?  Is this resolved then?  I don't understand what fixed it since 2.0.0.

**Comment by pdelfino** [comment]
> > [14:51:31] Warning: Error on GTK thead: unknown type specifier: LAMBDA
> 
> This indicates your error.
> 
> Why did you close the issue? Is this resolved then? I don't understand what fixed it since 2.0.0.

Sorry. The backward compatibility of the problem on version 2.0.0.0 with command names changing in future versions was not fixed. 

Since I solved the problem by tweaking my init file, I thought it would be appropriate to close the issue. I will let it open then.

**Comment by aartaka** [comment]
But wait, it was `noop` instead of `nothing` in 2.0, wasn't it? Opening the old version of Nyxt with the never initfile is not guaranteed to succeed, as some things have most probably changed. Am I misunderstanding something?

**Comment by pdelfino** [comment]
> @pdelfino What do you mean with "does not launch successfully?" Does it hang? Does it crash? It should report an error and then launch properly.

Not sure if _hang_ or _crash_ are the best words. Nyxt simply was not booting. The GUI was not even appearing on the screen. The behavior was like "waiting for it to launch forever". There was no error message. There is no pop-up with a message on "force quitting or waiting".

So, it _freezes as an infinite long initial boot of the application_, without ever showing off the GUI. For me, it feels weird to use hang/freeze if the GUI is not apparent. But it can a weirdness just to me.

Would you call what a describe as a hang/freeze or crash?

**Comment by jmercouris** [comment]
I would call it a hang, insofar as you are concerned, the application is running, but frozen, even if no GUI is present.

**Comment by pdelfino** [comment]
> I would call it a hang, insofar as you are concerned, the application is running, but frozen, even if no GUI is present.

Ok, then. It was indeed running. I did `ps -aux`to see it and `pkill nyxt` to kill it.

**Comment by aartaka** [comment]
> Then we have a bug, because Nyxt should success to start, even when the init file is flawed.

But wait, wasn't this feature of init file error ignores introduced after 2.0.0 too?

**Comment by aartaka** [comment]
I'm not sure, though -- it's been too much time since 2.0 xD

**Comment by jmercouris** [comment]
I believe we tried to do it for 2.0.0, but there may be some cases that we missed at the time! Let me consult the changelog/source...

**Comment by Ambrevar** [comment]
Makes sense, thanks for clarifying that, John!

**Comment by Ambrevar** [comment]
Good to close then?

**Comment by aartaka** [comment]
Good to close then (~^.^)~
