### ISSUE TITLE
Memory fault and load failures

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#1938]
Since today I'm experiencing a strange issue, both on `master` and `2-series`: usually after some minutes of browsing, pages fail to load.  It's particularly visible when opening a URL in a new buffer: if that buffer shows a "load failed" message, then an immediate reload usually fails.  If I wait a few minutes, then the reload may just work!

Another and possibly related issue is that I get a memory fault when loading a page.  It occurs at random, usually within 10 minutes of usage:

```
Unhandled memory fault at #x0.
   [Condition of type SB-SYS:MEMORY-FAULT-ERROR]

Restarts:
 0: [RETURN-FROM-CALLBACK] GLIB::RETURN-FROM-CALLBACK
 1: [ABORT] abort thread (#<THREAD "Nyxt renderer thread" RUNNING {1001060213}>)

Backtrace:
 0: (SB-SYS:MEMORY-FAULT-ERROR #<unused argument> #.(SB-SYS:INT-SAP #X00000000))
 1: ("foreign function: call_into_lisp")
 2: ("foreign function: funcall2")
 3: ("foreign function: handle_memory_fault_emulation_trap")
 4: ("foreign function: handle_trap")
 5: ("foreign function: #x41944E")
 6: ((FLET SB-THREAD::WITH-RECURSIVE-LOCK-THUNK :IN GOBJECT::ACTIVATE-GC-HOOKS))
 7: ((FLET "WITHOUT-INTERRUPTS-BODY-11" :IN SB-THREAD::CALL-WITH-RECURSIVE-LOCK))
 8: (SB-THREAD::CALL-WITH-RECURSIVE-LOCK #<FUNCTION (FLET SB-THREAD::WITH-RECURSIVE-LOCK-THUNK :IN GOBJECT::ACTIVATE-GC-HOOKS) {52B73F2B}> #<SB-THREAD:MUTEX "gobject-gc-hooks-lock" owner: #<SB-THREAD:THRE..
 9: (GOBJECT::ACTIVATE-GC-HOOKS)
10: ((LAMBDA (GLIB::DATA) :IN "/gnu/store/2b2bj6mwxk615yj3iwxc3qiscs6gnx4i-cl-cffi-gtk-0.11.2-2.e9a46df/share/common-lisp/source/cl-cffi-gtk/glib/glib.main-loop.lisp") #.(SB-SYS:INT-SAP #X00000004))
11: ((LAMBDA (SB-ALIEN::ARGS-POINTER SB-ALIEN::RESULT-POINTER FUNCTION) :IN "/gnu/store/2b2bj6mwxk615yj3iwxc3qiscs6gnx4i-cl-cffi-gtk-0.11.2-2.e9a46df/share/common-lisp/source/cl-cffi-gtk/glib/glib.main-lo..
12: ("foreign function: funcall_alien_callback")
13: ("foreign function: callback_wrapper_trampoline")
14: ("foreign function: #x50100352")
15: ((LAMBDA (&REST GIR::ARGS-IN) :IN GIR::BUILD-FUNCTION))
16: ((FLET MAIN-FUNC :IN FFI-INITIALIZE))
17: ((LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS))
18: ((FLET SB-UNIX::BODY :IN SB-THREAD::RUN))
19: ((FLET "WITHOUT-INTERRUPTS-BODY-10" :IN SB-THREAD::RUN))

```

@aartaka You were telling me you had similar issues recently.  Is this related to what I'm describing?

**Comment by aartaka** [comment]
> @aartaka You were telling me you had similar issues recently. Is this related to what I'm describing?

In my case it was failing right at startup, crashing the whole browser.

But it could well be related. Or some WebKit misuse slipped through with #1762 :(

**Comment by aartaka** [comment]
Maybe yet another lagacy API use that stopped working with 2.34.1? xD

**Comment by aartaka** [comment]
Oh, and my crash has a different stack trace! `g-object::activate-gc-hooks` wasn't there for sure!

**Comment by mac230** [comment]
I'm having a lot of crashing issues w/ version 2.2.3.  Trace:

`CORRUPTION WARNING in SBCL pid 541501 tid 541516:
Memory fault at (nil) (pc=0x7fb8f8f00675, fp=0x4034000000000000, sp=0x7fb8e5b25b88) tid 541516
The integrity of this image is possibly compromised.
Continuing with fingers crossed.
<WARN> [10:53:01] Warning: Error on GTK thread: Unhandled memory fault at #x0.
`

**Comment by Ambrevar** [comment]
How did you install Nyxt? Did you build from source?

**Comment by Ambrevar** [comment]
Please share your `nyxt --system-information` details.

**Comment by mac230** [comment]
Yes, I built from source.  I upgraded from 2.1.1 to address the issue w/ pages not loading when calling "history-backwards" and have had the issues w/ crashing since.  System information:

```Nyxt version: 2.2.3
Renderer version: GI-GTK
Operating system kernel: Linux 5.4.0-90-generic
Lisp implementation: SBCL 2.1.0 (Dynamic space size: 1073741824)
Features: (:WEBKIT2 :WEBKIT2-2.34 :WEBKIT2-PASTE-PLAINTEXT :WEBKIT2-TRACKING
 :WEBKIT2-MUTE :WEBKIT2-EMOJI :WEBKIT2-MEDIA :WEBKIT2-SANDBOXING :GTK-3-22
 :GTK-3-20 :GTK-3-18 :GTK-3-16 :GTK-3-14 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6
 :GTK-3-4 :GTK :GDK-3-22 :GDK-3-20 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12
 :GDK-3-10 :GDK-3-8 :GDK-3-6 :GDK-3-4 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF
 :GLIB-2-30 :GLIB-2-32 :GLIB-2-34 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42
 :GLIB-2-44 :GLIB-2-46 :GLIB-2-48 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56
 :GLIB-2-58 :GLIB :NYXT-2 :FSET-EXT-STRINGS :CUSTOM-HASH-TABLE-NATIVE :SWANK
 :PLUMP-UTF-32 :GLOBAL-VARS :DECLARE-TYPES :PARENSCRIPT
 :SBCL+SAFE-STANDARD-READTABLE :NAMED-READTABLES :LPARALLEL :21BIT-CHARS
 :CHUNGA :CLOSER-MOP :CL-PPCRE-UNICODE :FLEXI-STREAMS :CL-UNICODE :CL-PPCRE
 :CL-JSON-DOUBLE-FLOAT-IS-SUBSUMED :CL-JSON-SINGLE-FLOAT-IS-SUBSUMED
 :BORDEAUX-THREADS :LPARALLEL.WITH-CLTL2 :LPARALLEL.WITH-CAS
 :LPARALLEL.WITH-STEALING-SCHEDULER :SPLIT-SEQUENCE CHIPZ-SYSTEM:GRAY-STREAMS
 CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64 CFFI-FEATURES:UNIX :CFFI
 CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP :FAST-IO-SV :FAST-IO
 :SBCL-USES-SB-ROTATE-BYTE :CL-JSON-CLOS :CL-JSON :THREAD-SUPPORT :ASDF3.3
 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX :NON-BASE-CHARS-EXIST-P
 :ASDF-UNICODE :X86-64 :GENCGC :64-BIT :ANSI-CL :COMMON-LISP :ELF
 :IEEE-FLOATING-POINT :LINUX :LITTLE-ENDIAN :PACKAGE-LOCAL-NICKNAMES :SB-LDB
 :SB-PACKAGE-LOCKS :SB-THREAD :SB-UNICODE :SBCL :UNIX)

ASDF version: 3.3.1
ASDF registries: (NYXT-SOURCE-REGISTRY ENVIRONMENT-SOURCE-REGISTRY)
Critical dependencies: (/home/mahlon/common-lisp/nyxt/_build/cl-cffi-gtk/gtk/cl-cffi-gtk.asd
 /home/mahlon/common-lisp/nyxt/_build/cl-gobject-introspection/cl-gobject-introspection.asd
 /home/mahlon/common-lisp/nyxt/_build/cl-webkit/webkit2/cl-webkit2.asd)
```

**Comment by Ambrevar** [comment]
Are you saying that 2.1.1 does not crash?
Can you provide a precise recipe that crashes on 2.2.3 ?

**Comment by mac230** [comment]
Yes, 2.1.1 does not crash.  Unfortunately, I haven't been able to produce a precise sequence of events that reproducibly causes crashes w/ 2.2.3.  I can confirm the crashing occurs w/ nyxt started w/ no init file or history restored.  Sorry to not be more helpful, but if I can reproduce crashes I will report back.

**Comment by Ambrevar** [comment]
Thanks for the details, this definitely needs more investigation.

**Comment by Ambrevar** [comment]
I haven't been able to reproduce this in a while now. @mac230 Do you still experience crashes?

**Comment by mac230** [comment]
I ended up reverting to 2.1.1 because the crashes in 2.2.3 were too frequent.  They're still unpredictable and irreproducible, unfortunately.  One thing I'm wondering about: I heavily use a custom function inspired by:

[https://github.com/hrs/engine-mode](url)

The code for it is below.  Is there anything in it that might be causing my issues?

```
(define-command engine-mode-emulator ()
  "Function for emulating emacs engine-mode in nyxt."
  (let ((entry (first (prompt
                       :prompt "Which input: "
                       :sources (make-instance 'prompter:raw-source))))
        (search (first (prompt
                        :prompt "Search term: "
                        :sources (make-instance 'prompter:raw-source)))))
		(cond 
		 ((string= entry "d")
                  (make-buffer-focus :url
                   (url (str:concat "https://duckduckgo.com/?q=" search))))

		 ((string= entry "p")
                  (make-buffer-focus :url
                   (url 
		   (str:concat
		    "https://pubmed.ncbi.nlm.nih.gov/?term="
		    search
		    "&sort=pubdate&size=200"))))
           
		 ((string= entry "g")
                  (make-buffer-focus :url
                   (url (str:concat 
                         "http://www.google.com/search?ie=utf-8&oe=utf-8&q="
                                    search))))
                  
		 ((string= entry "m")
                  (make-buffer-focus :url
                   (url (str:concat "http://maps.google.com/maps?q="
                                    search))))
                 
		 ((string= entry "w")
		  (make-buffer-focus :url
		   (url (str:concat
		    "http://www.wikipedia.org/search-redirect.php?language=en&go=Go&search="
		    search))))
                 
		 (t
		  (make-buffer-focus :url
		   (url (str:concat
		    "https://duckduckgo.com/?q="
		    search)))))
		))
```

**Comment by aartaka** [comment]
I see no immediate issue with this command. Does removing it from your config mitigate the crashes?

**Comment by aartaka** [comment]
@mac230, and yet another thing: is the error message same as the one listed by @Ambrevar? 

If not, try moving your history file (`~/.local/share/nyxt/history/default.lisp` by default) elsewhere and see whether it crashes. It might be an issue with corrupted history file, but I'm doing wild guesses here :)

**Comment by mac230** [comment]
@Ambrevar and @aartaka , after some preliminary testing, I'm pleased to report no crashes so far w/ 2.2.4!  I didn't move the history file, but will try that first if I have any issues subsequent to this message.  Thank you for your input on the issue.

Unrelated to the issue, but wanted to mention I'm enjoying the massive improvements in speed and responsiveness with this version.  Thank you for all the effort to keep improving Nyxt!

**Comment by Ambrevar** [comment]
Fantastic!  And thanks for the kind words :)
