### ISSUE TITLE
Good location to introducing show-headings-panel command?

### ISSUE THREAD

**Issue by guojing0** [atlas-engineer/nyxt#1942]
**Context**: I originally wanted to have a Wikipedia's Table of Contents-style summary for our manual and documentation. After a meeting with John, he suggested that said feature could be generalized to any websites with HTML headings.

**Goal**: I want to implement the command `show-headings-panel` (with its panel buffer) which shows a panel on the right side of the window, much like in the style of Table of Contents of [some Wikipedia entry](https://en.wikipedia.org/wiki/Common_Lisp).

**What I have done**: The only two places that use `define-panel` are `bookmark.lisp` and `mode/buffer-listing.lisp`, and the latter one seems to be created specifically for this purpose. It then prompts the following **question**: _I am not sure if I should create a mode for this specifically or add it to some existing file, like `mode/web.lisp` or `buffer.lisp`?_

The word "panel" appears in the following files:
![Snip20211217_99](https://user-images.githubusercontent.com/3425792/146567085-85b2e493-f898-4b81-8536-e12fe3a3d1ea.png)

**Comment by jmercouris** [comment]
I think you should make a mode for this. I would also probably make a new file for this. Alternatively, you could put this in the same file as `jump-headings.lisp`. The choice is yours, either way is perfectly OK!

**Comment by guojing0** [comment]
I think I will make a mode for this. I thought of using `jump-headings.lisp` as well, but it seemed a little strange to me, so I did not mention it in the post.
