### ISSUE TITLE
_jsc_value_new_from_json and _jsc_value_to_json not found on macOS

### ISSUE THREAD

**Issue by BlueFlo0d** [atlas-engineer/nyxt#1943]
**Describe the bug**
Doesn't load or build.
**Precise recipe to reproduce the issue**
`(asdf:load-system :nyxt/gtk)` from dd03a7a2805828f77ff4b4e050edbca20916e704.

**Information**
- OS name+version: macOS 10.14.6
- How you installed Nyxt (Guix pack, package manager, build from source): source

  If you can't run `show-system-information`, try `nyxt --system-information` from
  a shell.  It this still does not work, please provide the following:
  - Nyxt version (from the `nyxt-version` command or `nyxt --version` from a shell):
  - Lisp implementation/version (if built from source): sbcl 2.1.11
  - Kernel name+version:
  - WebKitGTK+ | QtWebEngine version: webkit2-gtk-devel              @2.27.3 

I think this is probably not system related? `cl-webkit2` just doesn't seem to contain this symbol.

**Comment by jmercouris** [comment]
Are you using Quicklisp to fetch `cl-webkit` or are you using the submodules?

**Comment by BlueFlo0d** [comment]
Ah I see, I `grep`ed the `cl-webkit` in the `_build` and found the symbol.
Sorry for spam, but could you enlighten me on how to let `asdf` use the submodules instead of quicklisp? Thanks.

**Comment by BlueFlo0d** [comment]
Also if I try to `make all` it then gives
```
Undefined symbols for architecture x86_64:
  "_jsc_value_new_from_json", referenced from:
      _extensions_data_add_from_json in globals.o
      _has_permission in globals.o
      _get_result in globals.o
      _user_message_received_callback in nyxt.o
      _runtime_get_manifest_callback in runtime.o
  "_jsc_value_to_json", referenced from:
      _browser_reply_message_callback in browser.o
      _runtime_send_message_callback in runtime.o
      _storage_local_set_callback in storage.o
      _storage_local_remove_callback in storage.o
      _storage_local_get_callback in storage.o
      _tabs_query_callback in tabs.o
      _tabs_create_callback in tabs.o
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Unhandled UIOP/RUN-PROGRAM:SUBPROCESS-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING
                                                         {10018305B3}>:
  Subprocess #<UIOP/LAUNCH-PROGRAM::PROCESS-INFO {1007282753}>
 with command ("clang" "-L/opt/local/lib" "-lwebkit2gtk-4.0" "-lgtk-3"
               "-lgdk-3" "-Wl,-framework,Cocoa" "-lpangocairo-1.0"
               "-lpango-1.0" "-lharfbuzz" "-latk-1.0" "-lcairo-gobject"
               "-lcairo" "-lgdk_pixbuf-2.0" "-lsoup-2.4" "-lgio-2.0"
               "-ljavascriptcoregtk-4.0" "-lgobject-2.0" "-lglib-2.0" "-lintl"
               "-fPIC" "-shared" "-o" "libnyxt.so"
               "/Users/me/common-lisp/nyxt/libraries/web-extensions/alarms.o"
               "/Users/me/common-lisp/nyxt/libraries/web-extensions/bookmarks.o"
               "/Users/me/common-lisp/nyxt/libraries/web-extensions/browser.o"
               "/Users/me/common-lisp/nyxt/libraries/web-extensions/browser_action.o"
               "/Users/me/common-lisp/nyxt/libraries/web-extensions/commands.o"
               "/Users/me/common-lisp/nyxt/libraries/web-extensions/extension.o"
               "/Users/me/common-lisp/nyxt/libraries/web-extensions/extevent.o"
               "/Users/me/common-lisp/nyxt/libraries/web-extensions/globals.o"
               "/Users/me/common-lisp/nyxt/libraries/web-extensions/history.o"
               "/Users/me/common-lisp/nyxt/libraries/web-extensions/management.o"
               "/Users/me/common-lisp/nyxt/libraries/web-extensions/notifications.o"
               "/Users/me/common-lisp/nyxt/libraries/web-extensions/nyxt.o"
               "/Users/me/common-lisp/nyxt/libraries/web-extensions/permissions.o"
               "/Users/me/common-lisp/nyxt/libraries/web-extensions/runtime.o"
               "/Users/me/common-lisp/nyxt/libraries/web-extensions/storage.o"
               "/Users/me/common-lisp/nyxt/libraries/web-extensions/tabs.o"
               "/Users/me/common-lisp/nyxt/libraries/web-extensions/web_navigation.o"
               "/Users/me/common-lisp/nyxt/libraries/web-extensions/web_request.o")
 exited with error code 1
```

**Comment by jmercouris** [comment]
There are some options in the makefile for defining it, you can see them in `make help`. I don't want to copy them here, as they will go out of date!

**Comment by BlueFlo0d** [comment]
Yes `make` default to use the submodules, but not sure how to let `asdf` in repl do that.
Anyway, all ways still stumble upon that linker error...

**Comment by BlueFlo0d** [comment]
It seems that webkit2-gtk-devel from macport doesn't have _jsc_value_new_from_json and _jsc_value_to_json in JSCValue.h.

The latest webkit2-gtk-devel on macport is 2.27.3 which is 2 years old, maybe the functions are added only at a later version?

**Comment by BlueFlo0d** [comment]
It's finally working!! Using webkit2-gtk (w/o devel) from mac ports, and manually
do
```
(setf asdf:*default-source-registries* (list (quote asdf/source-registry:environment-source-registry)))
(asdf:load-system :nyxt/submodules)
(asdf:load-system :nyxt/gtk)
```
in the REPL.
(`make all` won't do because it fails to find `ql-dist`, and even if I remove this blocker by removing `--no-userinit` from `LISP_FLAGS`, it eventually doesn't produce a binary `./nyxt` at the last step).

**Comment by jmercouris** [comment]
Congratulations!
