### ISSUE TITLE
Possibility for a new macro `define-private-mode`

### ISSUE THREAD

**Issue by guojing0** [atlas-engineer/nyxt#1945]
When I was testing for https://github.com/atlas-engineer/nyxt/pull/1941, I found out that even if I am on a normal website, say http://neversll.com/, I could still enable certain modes, like `buffer-listing-mode`, where it makes little to no sense for such website.

So I was wondering that given current architecture, do you think would it be possible and/or necessary to have another macro, `define-private-mode` (in the sense of *private* function)? Such that some mode (like `buffer-listing-mode`) is for that purpose only and cannot be selected by the users.

**Comment by aartaka** [comment]
This is somewhat reselmblant of #1198 in that the command should not be seen by the user.

**Comment by Ambrevar** [comment]
I agree that this may be just #1198.  @guojing0 Do you confirm?

**Comment by guojing0** [comment]
I confirm, hence closing this issue. I will add it to my to-do/think list.
