### ISSUE TITLE
shell.nix doesn't work

### ISSUE THREAD

**Issue by johnrichardrinehart** [atlas-engineer/nyxt#1947]
**Describe the bug**
I tried to follow the instructions in [the developer docs for nix](https://github.com/atlas-engineer/nyxt/blob/master/documents/README.org#developer-installation-with-nix) but running `nix-shell` immediately failed with
```
$ nix-shell                                        
error: attribute 'lib' missing

       at /home/john/code/repos/others/atlas-engineer/nyxt/build-scripts/shell.nix:57:26:

           56|
           57|   LD_LIBRARY_PATH = with stdenv.lib; "${makeLibraryPath [ pkgs.gsettings-desktop-schemas.out
             |                          ^
           58|                                                           pkgs.enchant.out
(use '--show-trace' to show detailed location information)
```

I seemed to get around this problem by changing `stdenv.lib` to just `lib` on l57.

**Precise recipe to reproduce the issue**

Patch the `shell.nix` in the above way and then run the S-expression from the `nyxt` docs in the `sbcl` REPL:
```lisp
$ nix-shell --run sbcl 
This is SBCL 2.1.9.nixos, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
* (asdf:load-system :nyxt/gtk-application)

debugger invoked on a SB-INT:SIMPLE-READER-PACKAGE-ERROR in thread
#<THREAD "main thread" RUNNING {1001538103}>:
  Package ASDF does not exist.

    Stream: #<SYNONYM-STREAM :SYMBOL SB-SYS:*STDIN* {100001D163}>

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [CONTINUE ] Use the current package, COMMON-LISP-USER.
  1: [RETRY    ] Retry finding the package.
  2: [USE-VALUE] Specify a different package
  3: [UNINTERN ] Read the symbol as uninterned.
  4: [SYMBOL   ] Specify a symbol to return
  5: [ABORT    ] Exit debugger, returning to top level.

(SB-IMPL::READER-FIND-PACKAGE "ASDF" #<SYNONYM-STREAM :SYMBOL SB-SYS:*STDIN* {100001D163}> T)
0] 
```

I guess `Package ASDF does not exist.`?

For website-specific issues:
Can you reproduce this issue with Epiphany / GNOME Web (https://wiki.gnome.org/Apps/Web)?

**Information**
- OS name+version: NixOS built with Linux kernel `5.15.10`
- Graphics card and driver: N/A
- Desktop environment / Window manager name+version: X11/Xorg+xmonad (no desktop environment)
- How you installed Nyxt (Guix pack, package manager, build from source): `shell.nix` experiment
- Information from `show-system-information`: I don't have this command. Where can I find it?

  If you can't run `show-system-information`, try `nyxt --system-information` from
  a shell.  It this still does not work, please provide the following:
  - Nyxt version (from the `nyxt-version` command or `nyxt --version` from a shell): N/A
  - Lisp implementation/version (if built from source): Not sure...
  - Kernel name+version: linux-x86_64 5.15.10
  - WebKitGTK+ | QtWebEngine version: N/A

**Output when started from a shell**

**Comment by aartaka** [comment]
@jmercouris?

**Comment by OliverEvans96** [comment]
I didn't have this issue today/yesterday on master. Maybe it's been resolved?

**Comment by jmercouris** [comment]
Ah yes, I resolved it, but forgot to update! Thank you @OliverEvans96
