### ISSUE TITLE
Is it necessary for document-model to be an :around method?

### ISSUE THREAD

**Issue by BlueFlo0d** [atlas-engineer/nyxt#1955]
`buffer.lisp` defines an `:around` method for `document-model`, which checks for changes and updates `document-model` heuristically. However, `:around` method can't be easily disabled by subclasses and this creates trouble when I try to make a subclass of `buffer` that maintains DOM from Lisp side. Is it better to use an ordinary primary method instead?

**Comment by aartaka** [comment]
I remember we talked on IRC, and I wasn't sure that I was able to communicate this point: `document-model-delta-threshold` is configurable via `define-configuration`, e.g.,
``` lisp
(define-configuration buffer 
  ((document-model-delta-threshold 100)))
```
And it will change the threshold for all the buffers Nyxt creates and all the subclasses you might have for `buffer`. So, if you only need to chang this small thing, you needn't rewrite all of `buffer`, just use `define-configuration`.

However, I agree that the use of `:around` method where a non-qualified method would suffice is not an optimal thing. 2579f9576881471700d6807860f825a42a393cdc addresses that.

**Comment by aartaka** [comment]
On a related note: there should be a way to disable/delete methods via MOP, although I'm not one hundred percent sure about it.

**Comment by BlueFlo0d** [comment]
The problem is the scope -- either `define-configuration` (it seems) or MOP affect the behavior globally, while I want to limit it to one particular buffer. Also changing `document-model-delta-threshold` doesn't prevent the element counting from happening, which is sort of a waste of CPU.

Thanks for 2579f9576881471700d6807860f825a42a393cdc!
