### ISSUE TITLE
Why does Nyxt have Alpine support but says "GNU/Linux"

### ISSUE THREAD

**Issue by ergpopler** [atlas-engineer/nyxt#1958]
Not trying to be annoying, but just saying, Alpine Linux isn't a GNU/Linux distribution, nor is it MacOS or FreeBSD, yet it is supported clearly, as it is in the Alpine repositories. Alpine is for the most part GNU-less, so...

**Comment by aartaka** [comment]
> Not trying to be annoying, but just saying, Alpine Linux isn't a GNU/Linux distribution, nor is it MacOS or FreeBSD, yet it is supported clearly, as it is in the Alpine repositories. Alpine is for the most part GNU-less, so...

Wait, where exactly is this GNU/Linux claim? Can you reference which document it's in? README cleanly separates GNU/Linux from MacOS and BSD, at least.

**Comment by opalvault** [comment]
I am assuming @ergpopler is referencing the Downloads page:

"Download for GNU/Linux
Nyxt is currently packaged for:

Alpine
Arch Linux (AUR)
Guix... etc"

It would appear that Alpine does not contain any GNU software in its base install. However I think GNU/Linux is still appropriate as Alpine is Linux. It can be one or the other and still fall under the umbrella term GNU/Linux.

**Comment by aartaka** [comment]
Indeed, that's a fair point :thinking:

**Comment by Ambrevar** [comment]
@ergpopler Are you satisfied with this answer?  Or would you suggest another term?

**Comment by MagicRB** [comment]
Couldn't we have GNU,musl/Linux?

**Comment by aartaka** [comment]
I mean, we could, but GNU/Linux is good enough of an umbrella term, I suppose...

**Comment by MagicRB** [comment]
Tbh I agree, the people that even know what musl means will check compatibility themselves since we all know musl can be a pita to work with.
