### ISSUE TITLE
Account for asynchronous attribute computation everywhere

### ISSUE THREAD

**Issue by aartaka** [atlas-engineer/nyxt#1960]
Right now `prompter::attribute-value` and `prompter:active-attributes` don't account for the function-based attributes, and it breaks e.g. `switch-buffer` due to `prompter` functions expecting strings where functions are.

**Comment by Ambrevar** [comment]
What is broken exactly?  The async attributes were made specially for `switch-buffer`, so it's odd that it's broken for you :)  
Works fine for me.  Do you have a recipe?  Which commit?

**Comment by aartaka** [comment]
I cannot reproduce anymore. I guess it was some intermediate commit that I tested when debugging #1964. Closing this, then.
