### ISSUE TITLE
Nyxt process hangs when modifying request data via auto-mode

### ISSUE THREAD

**Issue by efimerspan** [atlas-engineer/nyxt#1964]
**Describe the bug**
Nyxt hangs when I modify the request data of a manually added request resource hook in a user-defined mode constructor.

**Precise recipe to reproduce the issue**
EDIT: As discussed, this only occurs when one sets the `nyxt/auto-mode:prompt-on-mode-toggle` slot to true in the `auto-mode` class. Any type of hint command will also generate a freeze.

Suppose one creates a `foo-mode` and wishes to invoke it via an `auto-mode` rule of the following form.

```lisp
((match-domain "eff.org") :included ((foo-mode :visible-in-status-p nil)))
```

Now, the definition of `foo-mode` involves what follows.

```lisp
(define-mode foo-mode ()
  ((constructor
     (lambda (mode)
       (hooks:add-hook (request-resource-hook (buffer mode))
           (make-handler-resource
             (lambda (request-data)
               (let ((url (url request-data)))
                 (setf (quri:uri-host url) "fsf.org")
                 (setf (url request-data) url))
               request-data)
               :name 'foo-handler))))))
```

When I navigate to https://www.eff.org, instead of being redirected to https://www.fsf.org, my Nyxt process will hang completely, throwing the following error log when Nyxt is started via `nyxt -vvv`:

```sh
<DEBUG> [22:04:02] nyxt browser.lisp (preprocess-request) -
  Forwarding https://www.eff.org/ for buffer #<USER-WEB-BUFFER 2 {100704A073}>
<DEBUG> [22:04:02] nyxt-user linb18c4bgbbl1454laa5l6wg47idapx-foo-mode.lisp (foo-mode) -
  FOO-MODE enabled.
<DEBUG> [22:04:02] nyxt browser.lisp (combine-composed-hook-until-nil hook compose-handlers) -
  Handler (#<FUNCTION NYXT/AUTO-MODE::AUTO-MODE-HANDLER> #<REQUEST-DATA {10109692C3}>): #<REQUEST-DATA {10109692C3}>
<DEBUG> [22:04:02] nyxt browser.lisp (combine-composed-hook-until-nil hook compose-handlers) -
  Handler (#<FUNCTION FOO-HANDLER> #<REQUEST-DATA {10109692C3}>): #<REQUEST-DATA {10109692C3}>
<DEBUG> [22:04:02] nyxt browser.lisp (combine-composed-hook-until-nil hook compose-handlers) -
  Handler (#<FUNCTION NYXT/BLOCKER-MODE::REQUEST-RESOURCE-BLOCK> #<REQUEST-DATA {10109692C3}>): #<REQUEST-DATA {10109692C3}>
<DEBUG> [22:04:02] nyxt gtk.lisp (on-signal-decide-policy gtk-buffer form-fun-431) -
  Don't forward to #<USER-WEB-BUFFER 2 {100704A073}>'s renderer (resource request replaced with "https://fsf.org/").
<DEBUG> [22:04:02] nyxt browser.lisp (preprocess-request) -
  Forwarding https://fsf.org/ for buffer #<USER-WEB-BUFFER 2 {100704A073}>
```

Do note the request data modification is effectuated as per the log, but the Nyxt process freezes and I have to close it by force killing the EXWM window. Also, it should be mentioned that if I take the `(setf (quri:uri-host url) "fsf.org")` from the `foo-handler` defined above, the request seems to get through (but not redirected anymore).

Nevertheless, I tried reproducing this issue without the mode having to be initialized on a new page request by reversing the scenario.
I restarted Nyxt, navigated to https://www.w3.org and changed the aforementioned `auto-mode` rule to the following.

```lisp
((match-domain "w3.org") :included ((foo-mode :visible-in-status-p nil)))
```

Now, I reingested the `auto-mode` rules via `(restore (current-data-profile) (auto-mode-rules-path (current-buffer)))` and I manually toggled `foo-mode` in the current buffer. I reloaded the buffer and I was properly redirected to https://www.fsf.org . Thereby, I'm unsure if the new page request is what might be affecting the mode instantiation or if this might be an underlying issue with the renderer.

For website-specific issues:
Can you reproduce this issue with Epiphany / GNOME Web (https://wiki.gnome.org/Apps/Web)?
No, I don't think this is applicable.

**Information**
- OS name+version: GNU Guix 7682145b9b05a500a3a6509960be22b865ca4154
- Graphics card and driver: Integrated Intel® Iris® Xe Graphics
- Desktop environment / Window manager name+version: EXWM 0.26
- How you installed Nyxt (Guix pack, package manager, build from source): Guix pack
- Information from `show-system-information`: 

```
Nyxt version: 2.2.3
Renderer version: GI-GTK
Operating system kernel: Linux 5.15.7
Lisp implementation: SBCL 2.1.9 (Dynamic space size: 3221225472)
Features: (:SERIES :SERIES-ANSI :SLYNK :QUICKLISP :WEBKIT2 :WEBKIT2-2.34
 :WEBKIT2-PASTE-PLAINTEXT :WEBKIT2-TRACKING :WEBKIT2-MUTE :WEBKIT2-EMOJI
 :WEBKIT2-MEDIA :WEBKIT2-SANDBOXING :GTK-3-22 :GTK-3-20 :GTK-3-18 :GTK-3-16
 :GTK-3-14 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6 :GTK-3-4 :GTK :GDK-3-22
 :GDK-3-20 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12 :GDK-3-10 :GDK-3-8 :GDK-3-6
 :GDK-3-4 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF :GLIB-2-30 :GLIB-2-32 :GLIB-2-34
 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42 :GLIB-2-44 :GLIB-2-46 :GLIB-2-48
 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56 :GLIB-2-58 :GLIB :NYXT-2
 :FSET-EXT-STRINGS :CUSTOM-HASH-TABLE-NATIVE :SWANK :PLUMP-UTF-32 :GLOBAL-VARS
 :DECLARE-TYPES :PARENSCRIPT :NAMED-READTABLES :LPARALLEL :21BIT-CHARS :CHUNGA
 :FLEXI-STREAMS :CLOSER-MOP :CL-PPCRE-UNICODE :CL-UNICODE :CL-PPCRE
 :BORDEAUX-THREADS :LPARALLEL.WITH-CLTL2 :LPARALLEL.WITH-CAS
 :LPARALLEL.WITH-STEALING-SCHEDULER :SPLIT-SEQUENCE CHIPZ-SYSTEM:GRAY-STREAMS
 CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64 CFFI-FEATURES:UNIX :CFFI
 CFFI-SYS::FLAT-NAMESPACE ALEX::SEQUENCE-EMPTYP :FAST-IO-SV :FAST-IO
 :SBCL-USES-SB-ROTATE-BYTE :CL-JSON-CLOS :CL-JSON :THREAD-SUPPORT :ASDF3.3
 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX :NON-BASE-CHARS-EXIST-P
 :ASDF-UNICODE :X86-64 :GENCGC :64-BIT :ANSI-CL :COMMON-LISP :ELF
 :IEEE-FLOATING-POINT :LINUX :LITTLE-ENDIAN :PACKAGE-LOCAL-NICKNAMES
 :SB-CORE-COMPRESSION :SB-LDB :SB-PACKAGE-LOCKS :SB-THREAD :SB-UNICODE :SBCL
 :UNIX)

ASDF version: 3.3.5
ASDF registries: (NYXT-SOURCE-REGISTRY ENVIRONMENT-SOURCE-REGISTRY USER-SOURCE-REGISTRY
                      USER-SOURCE-REGISTRY-DIRECTORY
                      DEFAULT-USER-SOURCE-REGISTRY SYSTEM-SOURCE-REGISTRY
                      SYSTEM-SOURCE-REGISTRY-DIRECTORY
                      DEFAULT-SYSTEM-SOURCE-REGISTRY)
Critical dependencies: (/gnu/store/x4jgpsgq4w6xa0pbg5y7xh6ppyky5l6b-sbcl-cl-cffi-gtk-0.11.2-2.e9a46df/share/common-lisp/sbcl/cl-cffi-gtk/gtk/cl-cffi-gtk.asd
 /gnu/store/bdfnmkxaxsgq5a2073hgjsb700yhbjlb-sbcl-cl-gobject-introspection-0.3-1.d0136c8/share/common-lisp/sbcl/cl-gobject-introspection/cl-gobject-introspection.asd
 /gnu/store/rhk1jbyb3szhrwgrv82i4lkvr6vvh0x4-sbcl-cl-webkit-3.4.0/share/common-lisp/sbcl/cl-webkit/webkit2/cl-webkit2.asd)

Guix version:
```

  If you can't run `show-system-information`, try `nyxt --system-information` from
  a shell.  It this still does not work, please provide the following:
  - Nyxt version (from the `nyxt-version` command or `nyxt --version` from a shell): 2.2.3
  - Lisp implementation/version (if built from source):
  - Kernel name+version: Linux guix 5.15.7 SMP 1 x86_64 GNU/Linux
  - WebKitGTK+ | QtWebEngine version: 

**Output when started from a shell**

**Comment by aartaka** [comment]
Does 81e19ebd3060bcb1739e42927fb7d574012e9b69 fix it?

**Comment by efimerspan** [comment]
Unfortunately, it doesn't. As mentioned, it keeps occurring when I have `nyxt/auto-mode:prompt-on-mode-toggle` set to `t` in the `auto-mode` class.

**Comment by aartaka** [comment]
@efimerspan, I think I found the reason: your mode had no `destructor` and thus `request-resource-hook` was constantly redirecting to fsf.org, even when already on fsf.org. Addding the destructor fixes the hang:
``` lisp
(define-mode foo-mode ()
  ((constructor
    (lambda (mode)
      (hooks:add-hook (request-resource-hook (buffer mode))
                      (make-handler-resource
                       (lambda (request-data)
                         (let ((url (url request-data)))
                           (setf (quri:uri-host url) "fsf.org")
                           (setf (url request-data) url))
                         request-data)
                       :name 'foo-handler))))
   (destructor
    (lambda (mode)
      (hooks:remove-hook
       (request-resource-hook (buffer mode))
       'foo-handler)))))
```

**Comment by aartaka** [comment]
It wasn't obvious for me, but let it be a lesson to all of us: `destructor` and `hooks:remove-hook` are there for a reason :D

**Comment by efimerspan** [comment]
Indeed, thanks for clearing this up :)
