### ISSUE TITLE
Nyxt crashing (Stack traces included using nyxt -vvv)

### ISSUE THREAD

**Issue by ghost** [atlas-engineer/nyxt#1965]
**Describe the bug**
On occasion, usually when loading a website Nyxt will crash. I'm not a wizard enough to decode SBCL Compiler traces so I've provided them. I hope they are helpful. It appears to be a memory issue.

**Precise recipe to reproduce the issue**
Unable to reproduce consistently.

For website-specific issues:
Can you reproduce this issue with Epiphany / GNOME Web (https://wiki.gnome.org/Apps/Web)?

**Information**
- OS name+version: GNU GUIX
- Graphics card and driver: AMD Ryzen 5 3400G with Radeon Vega Graphics // xf86-video-amdgpu
- Desktop environment / Window manager name+version: Sway WM 1.6.1 // Wayland // SDDM
- How you installed Nyxt (Guix pack, package manager, build from source):
- Information from `show-system-information`: Guix Package Repository

  If you can't run `show-system-information`, try `nyxt --system-information` from
  a shell.  It this still does not work, please provide the following:

  - Nyxt version (from the `nyxt-version` command or `nyxt --version` from a shell): 2.2.3
  - Lisp implementation/version (if built from source): N/A
  - Kernel name+version: Linux borges 5.15.10 #1 SMP 1 x86_64 GNU/Linux
  - WebKitGTK+ | QtWebEngine version: sbcl-cl-webkit version 3.4.0

**Output when started from a shell**
[These have expired, I will attempt to get new traces tomorrow -opalvault 12/27]
First Crash
http://paste.debian.net/plain/1224859
Second Crash
http://paste.debian.net/plain/1224864

**[New Crash, 12/28]**
https://paste.debian.net/1225100/

**Comment by guojing0** [comment]
I could not open the last two paste.debian.net links, are they still valid?

@Ambrevar It seems like some of the crashing situations that we have seen before?

**Comment by opalvault** [comment]
My apologies @guojing0, I will attempt to wait for the crash tomorrow in my regular browsing experience and put them in new pastes. I must not have set the correct expiry time for them to last more than 24-48 hours.

**Comment by opalvault** [comment]
This one was quite a rough crash. 
https://paste.debian.net/1225100/

I've also edited the original post to reflect this new paste

**Comment by Ambrevar** [comment]
@guojing0 I suppose you mean #1938 ?  Looks similar, but in my case it would crash on the first error.  Here @opalvault seem to have multiple critical errors before it effectively crashes.

**Comment by aadcg** [comment]
Stale.
