### ISSUE TITLE
Can I open the terminal in the browser

### ISSUE THREAD

**Issue by jetwolf** [atlas-engineer/nyxt#1968]
Hello! Can I open the terminal in the browser?

**Comment by guojing0** [comment]
Can you provide some details or specify what you mean? I believe there is REPL where you could evaluate Lisp expressions.

**Comment by glyh** [comment]
Maybe he means shell.

**Comment by aartaka** [comment]
@jetvolkov right now you cannot easily open the terminal in the browser, like you would do in e.g. Emacs. However, this is definitely possible to do (should it be an extension? is there enough people wanting this for us to do this, or can someone individually hack up something cool?)

**Comment by jetwolf** [comment]
> @jetvolkov right now you cannot easily open the terminal in the browser, like you would do in e.g. Emacs. However, this is definitely possible to do (should it be an extension? is there enough people wanting this for us to do this, or can someone individually hack up something cool?)

I apologize for disappearing and leaving this issue) Yes, I meant opening the terminal in the browser as in Emacs. At the time of opening the issue, it seemed like a cool idea to me. I'm not sure about it now😅

**Comment by jetwolf** [comment]
I got an answer, so I think we can close the issue. Thanks)

**Comment by Ambrevar** [comment]
Note that our `lisp-repl` has greatly improved now and in the future I'd like the API to host other languages, like Bash for instance!  Then you'd effectively have an overpowered shell (without graphical support though...).
