### ISSUE TITLE
Some sites trigger download-mode and fail to load

### ISSUE THREAD

**Issue by efimerspan** [atlas-engineer/nyxt#1969]
**Describe the bug**
Upon navigation to https://uk.huel.com/ , I was prompted with a `download-mode` buffer with the site in question as the download name and a `Status` of `Failed`. I coincidentally stumbled across another site for which I experienced the same behavior, and given as both of them were e-commerce sites, I've drawn the theoretical conclusion that this might be related to the [Shopify](https://en.wikipedia.org/wiki/Shopify) platform using background scripts which ultimately trigger `download-mode`. The following are the logs when running `nyxt -vvv`.

```sh
<DEBUG> [22:35:55] nyxt/web-mode web-mode.lisp (add-url-to-history) -
  Notify URL https://uk.huel.com/ for buffer #<USER-WEB-BUFFER 2 {100693EF63}> with load status FINISHED
 <INFO> [22:35:55] nyxt message.lisp (echo form-fun-6) -
  Finished loading "https://uk.huel.com/".
 <INFO> [22:35:55] nyxt message.lisp (echo form-fun-6) -
  Download failed for "https://uk.huel.com/".
```

Furthermore, while I couldn't reproduce it, another user reported he experienced the following backtrace.

```sh
<INFO> [10:33:50] Loading "https://uk.huel.com/".
**
libsoup-http2:ERROR:../libsoup-3.0.3/libsoup/http2/soup-client-message-io-http2.c:760:on_data_chunk_recv_callback: assertion failed: (msgdata->body_istream != NULL)
Bail out! libsoup-http2:ERROR:../libsoup-3.0.3/libsoup/http2/soup-client-message-io-http2.c:760:on_data_chunk_recv_callback: assertion failed: (msgdata->body_istream != NULL)
<INFO> [10:33:50] Destination "/home/user/Downloads/" exists, saving as "/home/user/Downloads/".
<INFO> [10:33:50] Finished loading "https://uk.huel.com/".
<INFO> [10:33:50] Finished loading "https://uk.huel.com/".
```

**Precise recipe to reproduce the issue**
Navigate to https://uk.huel.com or similar e-commerce sites such as the ones described in [this blog post](https://sixads.net/shopify/stores/).

For website-specific issues:
Can you reproduce this issue with Epiphany / GNOME Web (https://wiki.gnome.org/Apps/Web)?
No.

**Information**
- OS name+version: guix (GNU Guix) 7682145b9b05a500a3a6509960be22b865ca4154
- Graphics card and driver: Intel Corporation UHD Graphics
- Desktop environment / Window manager name+version: EXWM 0.26
- How you installed Nyxt (Guix pack, package manager, build from source): Guix pack
- Information from `show-system-information`:

Nyxt version: 2.2.3
Renderer version: GI-GTK
Operating system kernel: Linux 5.15.7
Lisp implementation: SBCL 2.1.9 (Dynamic space size: 3221225472)
Features: (:SERIES :SERIES-ANSI :SLYNK :QUICKLISP :WEBKIT2 :WEBKIT2-2.34
 :WEBKIT2-PASTE-PLAINTEXT :WEBKIT2-TRACKING :WEBKIT2-MUTE :WEBKIT2-EMOJI
 :WEBKIT2-MEDIA :WEBKIT2-SANDBOXING :GTK-3-22 :GTK-3-20 :GTK-3-18 :GTK-3-16
 :GTK-3-14 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6 :GTK-3-4 :GTK :GDK-3-22
 :GDK-3-20 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12 :GDK-3-10 :GDK-3-8 :GDK-3-6
 :GDK-3-4 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF :GLIB-2-30 :GLIB-2-32 :GLIB-2-34
 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42 :GLIB-2-44 :GLIB-2-46 :GLIB-2-48
 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56 :GLIB-2-58 :GLIB :NYXT-2
 :FSET-EXT-STRINGS :CUSTOM-HASH-TABLE-NATIVE :SWANK :PLUMP-UTF-32 :GLOBAL-VARS
 :DECLARE-TYPES :PARENSCRIPT :NAMED-READTABLES :LPARALLEL :21BIT-CHARS :CHUNGA
 :FLEXI-STREAMS :CLOSER-MOP :CL-PPCRE-UNICODE :CL-UNICODE :CL-PPCRE
 :BORDEAUX-THREADS :LPARALLEL.WITH-CLTL2 :LPARALLEL.WITH-CAS
 :LPARALLEL.WITH-STEALING-SCHEDULER :SPLIT-SEQUENCE CHIPZ-SYSTEM:GRAY-STREAMS
 CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64 CFFI-FEATURES:UNIX :CFFI
 CFFI-SYS::FLAT-NAMESPACE ALEX::SEQUENCE-EMPTYP :FAST-IO-SV :FAST-IO
 :SBCL-USES-SB-ROTATE-BYTE :CL-JSON-CLOS :CL-JSON :THREAD-SUPPORT :ASDF3.3
 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX :NON-BASE-CHARS-EXIST-P
 :ASDF-UNICODE :X86-64 :GENCGC :64-BIT :ANSI-CL :COMMON-LISP :ELF
 :IEEE-FLOATING-POINT :LINUX :LITTLE-ENDIAN :PACKAGE-LOCAL-NICKNAMES
 :SB-CORE-COMPRESSION :SB-LDB :SB-PACKAGE-LOCKS :SB-THREAD :SB-UNICODE :SBCL
 :UNIX)

ASDF version: 3.3.5
ASDF registries: (NYXT-SOURCE-REGISTRY ENVIRONMENT-SOURCE-REGISTRY USER-SOURCE-REGISTRY
                      USER-SOURCE-REGISTRY-DIRECTORY
                      DEFAULT-USER-SOURCE-REGISTRY SYSTEM-SOURCE-REGISTRY
                      SYSTEM-SOURCE-REGISTRY-DIRECTORY
                      DEFAULT-SYSTEM-SOURCE-REGISTRY)
Critical dependencies: (/gnu/store/x4jgpsgq4w6xa0pbg5y7xh6ppyky5l6b-sbcl-cl-cffi-gtk-0.11.2-2.e9a46df/share/common-lisp/sbcl/cl-cffi-gtk/gtk/cl-cffi-gtk.asd
 /gnu/store/bdfnmkxaxsgq5a2073hgjsb700yhbjlb-sbcl-cl-gobject-introspection-0.3-1.d0136c8/share/common-lisp/sbcl/cl-gobject-introspection/cl-gobject-introspection.asd
 /gnu/store/rhk1jbyb3szhrwgrv82i4lkvr6vvh0x4-sbcl-cl-webkit-3.4.0/share/common-lisp/sbcl/cl-webkit/webkit2/cl-webkit2.asd)

Guix version: 

  If you can't run `show-system-information`, try `nyxt --system-information` from
  a shell.  It this still does not work, please provide the following:
  - Nyxt version (from the `nyxt-version` command or `nyxt --version` from a shell):
  - Lisp implementation/version (if built from source):
  - Kernel name+version:
  - WebKitGTK+ | QtWebEngine version:

**Output when started from a shell**

**Comment by Ambrevar** [comment]
I cannot reproduce on Guix with 2.2.3.  I tried loading 5 of the listed e-commerce links, it worked all fine here.

Any idea?

**Comment by efimerspan** [comment]
I'm not certain of what could be the underlying cause of this, but another user pointed out he faced the same behavior on ad-ridden websites. Even though I still get the `download-mode` buffer on the aforementioned sites, sometimes I'll find others will act differently from time to time. If you can't reproduce it, I wonder if this might be a locale-specific issue.

**Comment by efimerspan** [comment]
Closing since this does not happen anymore.

**Comment by aartaka** [comment]
Does it not? But we didn't change anything...
