### ISSUE TITLE
Build failed on archlinux, wayland

### ISSUE THREAD

**Issue by glyh** [atlas-engineer/nyxt#1972]
**Describe the bug**

**Precise recipe to reproduce the issue**

1. `paru -S nyxt-browser-git`(I use AUR helpers, it's equvalent to manually download PKGBUILD and build it) 
2. This would fail and produce:
```
ld: unrecognized option '-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now'
ld: use the --help option for usage information
make[1]: *** [Makefile:10: libnyxt.so] Error 1
make[1]: Leaving directory '/home/lyh/.cache/paru/clone/nyxt-browser-git/src/nyxt-browser/libraries/web-extensions'
make: *** [makefile:41: web-extensions] Error 2
```

**Information**
- OS name+version:`Linux arch 5.15.11-arch2-1 #1 SMP PREEMPT Wed, 22 Dec 2021 09:23:54 +0000 x86_64 GNU/Linux`
- Graphics card and driver: 
```
  *-display
       description: VGA compatible controller
       product: Renoir
       vendor: Advanced Micro Devices, Inc. [AMD/ATI]
       physical id: 0
       bus info: pci@0000:03:00.0
       logical name: /dev/fb0
       version: c1
       width: 64 bits
       clock: 33MHz
       capabilities: pm pciexpress msi msix vga_controller bus_master cap_list fb
       configuration: depth=32 driver=amdgpu latency=0 mode=2560x1600 visual=truecolor xres=2560 yres=1600
       resources: iomemory:40-3f iomemory:40-3f irq:56 memory:460000000-46fffffff memory:470000000-4701fffff ioport:1000(size=256) memory:fd300000-fd37ffff
```
- Desktop environment / Window manager name+version:`sway version 1.6.1`
- How you installed Nyxt (Guix pack, package manager, build from source): AUR, `nyxt-browser-git`
- Information from `show-system-information`: Can't compile
  If you can't run `show-system-information`, try `nyxt --system-information` from
  a shell.  It this still does not work, please provide the following:
  - Nyxt version (from the `nyxt-version` command or `nyxt --version` from a shell): can't compile
  - Lisp implementation/version (if built from source): `SBCL 2.1.11`
  - Kernel name+version: `Linux 5.15.11-arch2-1`
  - WebKitGTK+ | QtWebEngine version: `webkit2gtk 2.34.3-1`(output by `pacman -Qi`)

**Comment by MithicSpirit** [comment]
Dupe of #1967

**Comment by glyh** [comment]
@MithicSpirit Alright, I'll close this.
