### ISSUE TITLE
Keybindings from recently enabled modes are not prioritized over the old modes' ones

### ISSUE THREAD

**Issue by aartaka** [atlas-engineer/nyxt#1973]
As mentioned in #1971, bindings from `visual-mode` don't work if there are similar bindings from the `web-mode` enabled earlier. Should it be the other way around---recent modes shadowing the older modes? It does make sense, especially in the context of such one-shot modes as `visual-mode`.

EDIT: like -> as.

**Comment by jmercouris** [comment]
Indeed that is a bug! :-O

**Comment by Ambrevar** [comment]
That's how it already works it seems.  Beware to not be confused by the different schemes: binding in the current schemes have priority over those in parent modes.

Can you exhibit a precise recipe?

**Comment by aartaka** [comment]
> That's how it already works it seems. Beware to not be confused by the different schemes: binding in the current schemes have priority over those in parent modes.
> 
> Can you exhibit a precise recipe?

An example could be `M->` Emacs binding (`forward-document`) from `visual-mode` conflicting with the same (`M->`) `web-mode` Emacs binding (bound to `scroll-to-bottom`) with `web-mode` one winning somewhy.

**Comment by Ambrevar** [comment]
Just tested: the problem is with key translation because

```lisp
(keymap:lookup-key "M->" (current-keymaps))
```
gets the right visual-mode command, while

```lisp
(keymap:lookup-key "M-shift->" (current-keymaps))
```
doesn't!

The fix is simple: remove

```diff
-       "M-s->" 'scroll-to-bottom
-       "M-s-<" 'scroll-to-top
```

from `web.lisp`.

Would that do, @aartaka?

**Comment by aartaka** [comment]
> Just tested: the problem is with key translation because
> 
> ```lisp
> (keymap:lookup-key "M->" (current-keymaps))
> ```
> 
> gets the right visual-mode command, while
> 
> ```lisp
> (keymap:lookup-key "M-shift->" (current-keymaps))
> ```
> 
> doesn't!
> 
> The fix is simple: remove
> 
> ```diff
> -       "M-s->" 'scroll-to-bottom
> -       "M-s-<" 'scroll-to-top
> ```
> 
> from `web.lisp`.
> 
> Would that do, @aartaka?

Yes, it would, given that it's the only place that causes us problems :)

**Comment by Ambrevar** [comment]
Done with ce3f2110c6929a26869a82f27a2d604e238c1572.

**Comment by aartaka** [comment]
Thanks, Pierre!
