### ISSUE TITLE
Unhandled USOCKET:TIMEOUT-ERROR in thread 

### ISSUE THREAD

**Issue by glyh** [atlas-engineer/nyxt#1976]
**Describe the bug**

1. Install nyxt from `nyxt-browser-git` AUR package
2. start nyxt
3. Open some random pages
4. Crashes 

**Information**
- OS name+version: `Linux arch 5.15.11-arch2-1 #1 SMP PREEMPT Wed, 22 Dec 2021 09:23:54 +0000 x86_64 GNU/Linux`
- Graphics card and driver:`AMD ATI 03:00.0 Renoir`
- Desktop environment / Window manager name+version:`sway version 1.6.1`
- How you installed Nyxt (Guix pack, package manager, build from source): AUR package, `nyxt-browser-git`
- Information from `show-system-information`:

```
Nyxt version: 2.1.1-1192-g5cd7dbdd
Renderer version: GI-GTK
Operating system kernel: Linux 5.15.11-arch2-1
Lisp implementation: SBCL 2.1.11 (Dynamic space size: 1073741824)
Features: (:WEBKIT2 :WEBKIT2-2.34 :WEBKIT2-PASTE-PLAINTEXT :WEBKIT2-TRACKING
 :WEBKIT2-MUTE :WEBKIT2-EMOJI :WEBKIT2-MEDIA :WEBKIT2-SANDBOXING :GTK-3-22
 :GTK-3-20 :GTK-3-18 :GTK-3-16 :GTK-3-14 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6
 :GTK-3-4 :GTK :GDK-3-22 :GDK-3-20 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12
 :GDK-3-10 :GDK-3-8 :GDK-3-6 :GDK-3-4 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF
 :GLIB-2-30 :GLIB-2-32 :GLIB-2-34 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42
 :GLIB-2-44 :GLIB-2-46 :GLIB-2-48 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56
 :GLIB-2-58 :GLIB :NYXT-2 :FSET-EXT-STRINGS :CUSTOM-HASH-TABLE-NATIVE :SWANK
 :PLUMP-UTF-32 :GLOBAL-VARS :DECLARE-TYPES :PARENSCRIPT
 :SBCL+SAFE-STANDARD-READTABLE :NAMED-READTABLES :LPARALLEL :21BIT-CHARS
 :CHUNGA :CLOSER-MOP :CL-PPCRE-UNICODE :FLEXI-STREAMS :CL-UNICODE :CL-PPCRE
 :CL-JSON-DOUBLE-FLOAT-IS-SUBSUMED :CL-JSON-SINGLE-FLOAT-IS-SUBSUMED
 :BORDEAUX-THREADS :LPARALLEL.WITH-CLTL2 :LPARALLEL.WITH-CAS
 :LPARALLEL.WITH-STEALING-SCHEDULER :SPLIT-SEQUENCE CHIPZ-SYSTEM:GRAY-STREAMS
 CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64 CFFI-FEATURES:UNIX :CFFI
 CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP :FAST-IO-SV :FAST-IO
 :SBCL-USES-SB-ROTATE-BYTE :CL-JSON-CLOS :CL-JSON :THREAD-SUPPORT :ASDF3.3
 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX :NON-BASE-CHARS-EXIST-P
 :ASDF-UNICODE :X86-64 :GENCGC :64-BIT :ANSI-CL :COMMON-LISP :ELF
 :IEEE-FLOATING-POINT :LINUX :LITTLE-ENDIAN :PACKAGE-LOCAL-NICKNAMES
 :SB-CORE-COMPRESSION :SB-LDB :SB-PACKAGE-LOCKS :SB-THREAD :SB-UNICODE :SBCL
 :UNIX)

ASDF version: 3.3.1
ASDF registries: (NYXT-SOURCE-REGISTRY ENVIRONMENT-SOURCE-REGISTRY)
Critical dependencies: (/home/lyh/.cache/paru/clone/nyxt-browser-git/src/nyxt-browser/_build/cl-cffi-gtk/gtk/cl-cffi-gtk.asd
 /home/lyh/.cache/paru/clone/nyxt-browser-git/src/nyxt-browser/_build/cl-gobject-introspection/cl-gobject-introspection.asd
 /home/lyh/.cache/paru/clone/nyxt-browser-git/src/nyxt-browser/_build/cl-webkit/webkit2/cl-webkit2.asd)
```

**Output when started from a shell**
```
<INFO> [21:40:16] Listening to socket "/run/user/1000/nyxt/nyxt.socket".
Nyxt version 2.1.1-1192-g5cd7dbdd
<INFO> [21:40:19] Loading history of 7 URLs from "/home/lyh/.local/share/nyxt/history/default.lisp".
<INFO> [21:40:21] Loading "https://duckduckgo.com/".
Unhandled USOCKET:TIMEOUT-ERROR in thread #<SB-THREAD:THREAD "Prompter update thread" RUNNING
                                             {1006D37443}>:
  Condition USOCKET:TIMEOUT-ERROR was signalled.

Backtrace for: #<SB-THREAD:THREAD "Prompter update thread" RUNNING {1006D37443}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<USOCKET:TIMEOUT-ERROR {10074EB153}> #<unused argument> :QUIT T)
1: (SB-DEBUG::RUN-HOOK SB-EXT:*INVOKE-DEBUGGER-HOOK* #<USOCKET:TIMEOUT-ERROR {10074EB153}>)
2: (INVOKE-DEBUGGER #<USOCKET:TIMEOUT-ERROR {10074EB153}>)
3: (ERROR USOCKET:TIMEOUT-ERROR :SOCKET #<USOCKET:STREAM-USOCKET {10074DEBC3}>)
4: (USOCKET::HANDLE-CONDITION #<SB-EXT:TIMEOUT {10074E3FA3}> #<USOCKET:STREAM-USOCKET {10074DEBC3}> "duckduckgo.com")
5: (SB-KERNEL::%SIGNAL #<SB-EXT:TIMEOUT {10074E3FA3}>)
6: (ERROR SB-EXT:TIMEOUT)
7: (USOCKET:SOCKET-CONNECT "duckduckgo.com" 443 :PROTOCOL :STREAM :ELEMENT-TYPE (UNSIGNED-BYTE 8) :TIMEOUT 10 :DEADLINE NIL :NODELAY T :LOCAL-HOST NIL :LOCAL-PORT NIL)
8: ((LABELS DEXADOR.BACKEND.USOCKET::MAKE-NEW-CONNECTION :IN DEXADOR.BACKEND.USOCKET:REQUEST) #<QURI.URI.HTTP:URI-HTTPS https://#1=duckduckgo.com/ac/?q=https%3A%2F%2Fwiki.gnome.org%2FApps%2FWeb>)
9: (DEXADOR.BACKEND.USOCKET:REQUEST #<unavailable argument> :METHOD :GET)
10: ((LAMBDA (URL &REST NYXT::ARGS) :IN "/home/lyh/.cache/paru/clone/nyxt-browser-git/src/nyxt-browser/source/search-engine.lisp") "https://duckduckgo.com/ac/?q=https%3A%2F%2Fwiki.gnome.org%2FApps%2FWeb")
11: ((LAMBDA (NYXT::INPUT) :IN MAKE-SEARCH-COMPLETION-FUNCTION) "https://wiki.gnome.org/Apps/Web")
12: (NYXT::INPUT->QUERIES "https://wiki.gnome.org/Apps/Web" :CHECK-DNS-P T :ENGINE-COMPLETION-P T)
13: ((LAMBDA NIL :IN PROMPTER::UPDATE))
14: ((LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS))
15: ((FLET SB-UNIX::BODY :IN SB-THREAD::RUN))
16: ((FLET "WITHOUT-INTERRUPTS-BODY-10" :IN SB-THREAD::RUN))
17: ((FLET SB-UNIX::BODY :IN SB-THREAD::RUN))
18: ((FLET "WITHOUT-INTERRUPTS-BODY-3" :IN SB-THREAD::RUN))
19: (SB-THREAD::RUN)
20: ("foreign function: call_into_lisp")
21: ("foreign function: funcall1")

unhandled condition in --disable-debugger mode, quitting
<WARN> [21:40:31] Warning: Error: Joining thread failed: thread #&lt;THREAD &quot;Nyxt renderer thread&quot; ABORTED {10081E2A53}&gt; did not return normally.
```

**Comment by aartaka** [comment]
Oh, we should catch errors in completion retrieval functions, yes!

**Comment by Ambrevar** [comment]
@aartaka Can you send a patch?

**Comment by aartaka** [comment]
> @aartaka Can you send a patch?

I'm really confused, as I seem to have fixed the problem already in c595f1b53cbc7259f7e121b37cb3a789d2079521, f45aa8f1868a5a00d56aaea0376e781871a11e9f, and b7da572213de9faf34cd253728439627be27d242. Are those on `2-series`?

**Comment by aartaka** [comment]
But then, `nyxt-browser-git` builds from `master`, so I'm twice confused...

**Comment by Ambrevar** [comment]
The commits you listed are on `2-series`.  And indeed, the original post is on 5cd7dbdd56fe9eb3bc0aae6da36158cfbd963eee which is 1 week old on `master`.

**Comment by Ambrevar** [comment]
I wonder why it crashes considering that it's supposed to run "protected".

That said, I've spotted some potential pitfalls:

- In `input->queries`, one `(funcall (completion-function engine))` is protected, but the other one isn't.  Mistake?  Also why does it need to be protected?   Isn't this function called from a protected thread anyways?
- `make-search-completion-function` only catches `usocket:ns-host-not-found-error` from the  `dex:get` call, it does not catch other errors.  Maybe we could catch `T` here and report that there was an unknown network error.  But then, shouldn't this be done in the body of `make-search-completion-function` so that all conditions would be handled regardless of what the caller sets as `request-function`?

**Comment by aartaka** [comment]
> * In `input->queries`, one `(funcall (completion-function engine))` is protected, but the other one isn't.  Mistake? 


Wait, there's another place? 0_o 

It should be the one erroring out then!

> Also why does it need to be protected?  Isn't this function called from a protected thread anyways?

What is the protected thread here? Prompter update one?

> But then, shouldn't this be done in the body of `make-search-completion-function` so that all conditions would be handled regardless of what the caller sets as `request-function`?

No, it shouldn't. One can make a search completion function with no help form `make-search-completion-function` and we won't be able to catch errors there. That's why we need to muffle errors exactly in `input->queries`.

**Comment by aartaka** [comment]
OK, d05114778657ca2bc2de0b363b06f20be3a3727f should muffle any error/warning there could be in the default search euto-completion that didn't have error-handling before.

**Comment by Ambrevar** [comment]
Indeed, `input->queries` is called in the prompter preprocessor and postprocessor, which are not protected.

Funny that it's never been a problem so far.  Can you exhibit a case where it would cause Nyxt to hang or crash?

Shall we copy `run-thread` to the `prompter` library and replace all `bt:make-thread` calls with it?

**Comment by aartaka** [comment]
> Indeed, `input->queries` is called in the prompter preprocessor and postprocessor, which are not protected.

0_o

> Funny that it's never been a problem so far. Can you exhibit a case where it would cause Nyxt to hang or crash?

Well, `update` is run at every input. If the update thread crashes because of preprocessor/postprocessor error and loses one or two anomalous inputs, it could pass unnoticed. That could be the reason we didn't see any problem until now.

> Shall we copy `run-thread` to the `prompter` library and replace all `bt:make-thread` calls with it?

That will also require copying `with-protect` and, surprizingly, depending on Plump. It can still be helpful, though.

**Comment by Ambrevar** [comment]
See #2008 for a fix.

**Comment by Ambrevar** [comment]
Fix merged!
