### ISSUE TITLE
Documentation for WebExtensions feature (in the manual)?

### ISSUE THREAD

**Issue by guojing0** [atlas-engineer/nyxt#1978]
I am working on Issue https://github.com/atlas-engineer/nyxt/issues/1918 and saw a post on r/nyxt [asking about configuring Nyxt](https://www.reddit.com/r/Nyxt/comments/rsoq9u/its_hard_to_configure_nyxt_isnt_it/). I skimmed [Nyxt documentation](https://nyxt.atlas.engineer/documentation) and noticed that there was no documentation for WebExtensions, yet.

While there is an [useful README](https://github.com/atlas-engineer/nyxt/blob/master/libraries/web-extensions/README.org) in WebExtensions library, I was wondering that would it be helpful to normal users to have something added to the main documentation/manual?

**Comment by aartaka** [comment]
Indeed, it can be useful.

**Comment by guojing0** [comment]
See https://github.com/atlas-engineer/nyxt/issues/1985.
