### ISSUE TITLE
Safety aspect of Nyxt's built-in Lisp REPL?

### ISSUE THREAD

**Issue by guojing0** [atlas-engineer/nyxt#1980]
While it's all nice and cool to have a Lisp REPL inside Nyxt, I was wondering that if an user could arbitrarily evaluate any Lisp codes, would it be potentially unsafe?

I currently do not have any real examples other than evaluating `(setf *browser* nil)` crashed the browser. I think my thinking may more lean towards [this SO question](https://stackoverflow.com/questions/2571401/why-exactly-is-eval-evil).

**Comment by pdelfino** [comment]
@Ambrevar, @jmercouris, and @aartaka have better answers... The only thing I can think about is this famous quote (which have become a meme) from Uncle Ben (Peter Parker's (Spider Man) Uncle)  :smiley: 

![image](https://user-images.githubusercontent.com/7698207/147834133-261f447d-1484-4dd6-ad01-65122d9ea6f4.png)
 
Happy New Year, @guojing0!

**Comment by BlueFlo0d** [comment]
FWIW, here’s an example of the Emacs way:
https://emacs.stackexchange.com/questions/2935/how-can-i-bring-back-nil

**Comment by guojing0** [comment]
@BlueFlo0d Thank you for the link, though I referred to something more like safe sand-box type mechanism.

The issue is closed since it's moved to [Discourse](https://discourse.atlas.engineer/t/safety-aspect-of-nyxts-built-in-lisp-repl/391).
