### ISSUE TITLE
Clicking an item in Buffers panel crashes Nyxt

### ISSUE THREAD

**Issue by guojing0** [atlas-engineer/nyxt#1991]
**Describe the bug**

On latest `master` branch, after running `(nyxt:start)`, I go to manual and run `buffers-panel` command. I click "Manual" item and Nyxt crashes.

**Information**
- OS name+version: Debian
- How you installed Nyxt (Guix pack, package manager, build from source): Source

**Output when started from a shell**

Sly: `Lisp connection closed unexceptedly: connection broken by remote user`

**Comment by Ambrevar** [comment]
I can confirm this on `master` but I can't reproduce on `2-series`.  My guess is that it's an issue with Nyxt URLs.

@jmercouris @aartaka can you have a look?

**Comment by guojing0** [comment]
Yeah that's my guess as well.

**Comment by aartaka** [comment]
Yes, should be Nyxt URLs. Cannot test, as I'm not near my machine at the moment.

Will test in six hours :)

**Comment by aartaka** [comment]
It was all because of error while JSON-serializing the return value of `switch-buffer` a `buffer` object. CL-JSON error made the whole `lisp:` URL handler err and crash WebKit process.

**Comment by aartaka** [comment]
824f1f74def8a81e44bfb6e869d5eb6b3ef26808 should fix it.

**Comment by Ambrevar** [comment]
Thanks!
