### ISSUE TITLE
Move search-auto-complete-p and friends to `browser` or `prompt-buffer`?

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#1992]
I think we had discussed this with @aartaka but then forgot about it.

In my understanding, the following buffer slots impact the prompt buffer and not the buffer, so they should be moved to the `prompt-buffer` class.  Or maybe someone would prefer the `browser` class?

- `search-auto-complete-p`
- `search-always-auto-complete-p`
- `search-engines`
- `bookmarks-path`
- `error-output-path`
- `standard-output-path`

In the above, only `search-always-auto-complete-p` was introduced after 2.2.3 if I'm not mistaken, so this one can be moved for 2.2.4.

The rest will have to wait for 3.0.

**Comment by aartaka** [comment]
Why `bookmarks-path`? I mean, it feels right in the `browser`, but... it is part of our `data-storage` API, and this API is buffer-dependent. Revamping the `data-storage` library to not be buffer-dependent will solve this problem, though.

What are `error-output-path` and `standard-output-path` used for, actually? :sweat_smile: 

For most others, `browser` feels like the proper place, as `prompt-buffer` is a mere interface (at least in regards to search a bookmarks) to the `browser`-belonging data.

**Comment by Ambrevar** [comment]
The data-storage API is _profile dependent_, and we have a global profile, so we can have a data path that is not buffer dependent.

`error-output-path` and `standard-output-path` are used in `write-output-to-log` which is there for debug purposes.  It's admittedly under-used, if not misused.  Can we do better to let the user easily set where stdout and stderr are written? 
From the command line?  From the init file?

I agree with your last point that `bookmarks-path`, `standard-output-path` and `error-output-path` belong to `browser`.

However the first 3 only control the behaviour of prompt-buffer sources.  Shouldn't it belong to the prompt-buffer then?  Or maybe even the source itself?

**Comment by aartaka** [comment]
> However the first 3 only control the behaviour of prompt-buffer sources. Shouldn't it belong to the prompt-buffer then? Or maybe even the source itself?

Hmmmmmm. It sounds logical, but I feel that `prompt-buffer` restrictedness of these slots is just a coincidence and they belong to the `browser` as more general user-facing settings.

**Comment by Ambrevar** [comment]
Can you expand on what you mean with "coincidence"?  Are you saying that
we could very well have another interface in the future with completion
that would need these settings?

What about moving it to the source then?

**Comment by aartaka** [comment]
> Can you expand on what you mean with "coincidence"? Are you saying that we could very well have another interface in the future with completion that would need these settings? What about moving it to the source then?

Yes, that's exactly what I mean. Search engines can come in handy in different places. I remember that `nx-search-engine` once had a `search-image` command that used to fetch search engines from the current buffer and search the given image with this engine. Such a use-case would still work if we base search engines and search completion into prompt-buffer or decidated source, but it won't be as flexible as it could be.

**Comment by Ambrevar** [comment]
What about moving the slots to the `window` class instead of `browser`?
The benefit of this is that it would allow for more locality, namely to have per-window specialization, a bit like Firefox private mode.

Thoughts?

**Comment by aartaka** [comment]
Search-related slots belong to `browser`, that's for sure. Search engines are browser-level thing in all the browsers I know of. So, we move `search-engines` from `context-buffer` to `browser` and `search(-always)-auto-complete-p` from `document-buffer` (how did they even end up here?) to `browser`.
