### ISSUE TITLE
Unused `extension` argument in `remove-content-script`

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#1993]
@aartaka The CI fails because `remove-content-script` does not use `extension`.  Can you have a look?

**Comment by aartaka** [comment]
I've ignored it in d4fe7cc71f789727dfd27d1e506f1ce1187be212. Removing it is fine too, but I like the symmetry between `inject-content-script` and `remove-content-script` arguments. Adding to that, It's likely to grow and need extension some day.

Am I over-engineering here? :)

**Comment by Ambrevar** [comment]
No worries, the CI now passes, perfect!
