### ISSUE TITLE
libraries/password-manager: allow key files for KeePassXC interface

### ISSUE THREAD

**Issue by aartaka** [atlas-engineer/nyxt#1997]
KeePassXC has two ways to authenticate the owner of the password database:
- Master password (that we support in out `keepassxc-interface`).
- Key files (that we don't support yet).

It emerged on IRC today and I remember it emerging on different platforms before. Given that there are people using KeePassXC with key files, we need to have support for this use-case.

**Comment by aartaka** [comment]
Done in 5be9ee687fc1eb4fc99deee30ab2042a177c0fff.

**Comment by Ambrevar** [comment]
Nice, thanks!
