### ISSUE TITLE
New internal-page commands do not work in most of the cases.

### ISSUE THREAD

**Issue by shamazmazum** [atlas-engineer/nyxt#1998]
Hi! Commit c247e82 introduces a new macro called `define-internal-page-command`. When an internal page command is called, an URL in `nyxt://` scheme is opened in a new internal buffer. 

Consider this command from `mode/web.lisp`:

~~~~
(nyxt::define-internal-page-command view-source (&key (buffer (current-buffer)))
  (source-buffer (format nil "*Source of ~a" (render-url (url buffer))) 'base-mode)
  "View source of the current page in a separate buffer."
  (spinneret:with-html-string
    (:pre (if (web-buffer-p buffer)
              (plump:serialize (document-model buffer) nil)
	      (ffi-buffer-get-document buffer)))))
~~~~

This worked fine before c247e82, but now it generates an URL `nyxt//:nyxt/web-mode:view-source?buffer=%23%3Cuser-web-buffer%201178%20%7B100A3C00E3%7D%3E`, URI-decodes it and tries to read it as an S-expression

~~~~
<DEBUG> [17:42:13] NYXT::KEY-STRING: "v" NYXT::KEYCODE: 55 CHARACTER: #\v NYXT::KEYVAL-NAME: "v"
<DEBUG> [17:42:13] Forward key "\"v\" [#55]"
<DEBUG> [17:42:13] NYXT::KEY-STRING: "i" NYXT::KEYCODE: 31 CHARACTER: #\i NYXT::KEYVAL-NAME: "i"
<DEBUG> [17:42:13] Forward key "\"i\" [#31]"
<DEBUG> [17:42:13] NYXT::KEY-STRING: "e" NYXT::KEYCODE: 26 CHARACTER: #\e NYXT::KEYVAL-NAME: "e"
<DEBUG> [17:42:13] Forward key "\"e\" [#26]"
<DEBUG> [17:42:13] NYXT::KEY-STRING: "w" NYXT::KEYCODE: 25 CHARACTER: #\w NYXT::KEYVAL-NAME: "w"
<DEBUG> [17:42:13] Forward key "\"w\" [#25]"
<DEBUG> [17:42:14] NYXT::KEY-STRING: "hyphen" NYXT::KEYCODE: 20 CHARACTER: #\- NYXT::KEYVAL-NAME: "minus"
<DEBUG> [17:42:14] Forward key "\"hyphen\" [#20]"
<DEBUG> [17:42:15] NYXT::KEY-STRING: "return" NYXT::KEYCODE: 36 CHARACTER: #\Return NYXT::KEYVAL-NAME: "Return"
<DEBUG> [17:42:15] Found key binding "return" [#36] to RETURN-SELECTION
<DEBUG> [17:42:15] BASE-MODE enabled.
<DEBUG> [17:42:15] WEB-MODE enabled.
<DEBUG> [17:42:15] CERTIFICATE-EXCEPTION-MODE enabled.
<DEBUG> [17:42:15] REDUCE-TRACKING-MODE enabled.
<DEBUG> [17:42:15] EMACS-MODE enabled.
amdgpu: os_same_file_description couldn't determine if two DRM fds reference the same file description.
If they do, bad things may happen!
<DEBUG> [17:42:15] Forwarding nyxt:nyxt/web-mode:view-source?buffer=%23%3Cuser-web-buffer%201178%20%7B100A3C00E3%7D%3E for buffer #<USER-WEB-BUFFER 1179 {10021BFEB3}>
<DEBUG> [17:42:15] Forward to #<USER-WEB-BUFFER 1179 {10021BFEB3}>'s renderer (no request-resource-hook handlers).

debugger invoked on a SB-INT:SIMPLE-READER-ERROR in thread
#<THREAD "Anonymous thread" RUNNING {1008F13D03}>:
  illegal sharp macro character: #\<
~~~~

Needless to say that buffers are not readable, hence the command fails. There are many commands affected by the mentioned commit: `view-source`, `show-qr-code-of-current-url`, `buffer-history-tree`, etc. Either this commit must be reverted or all of these commands rewritten by passing buffer ID as an argument.

Sorry if it's obvious for developers, but I thought nyxt is more or less stable on master branch :) Was a bit disappointed when many commands just stopped working.

**P.S.**
Maybe it really is a known bug. Just saw in the commit message:

~~~~
 Not a merge-ready state! nyxt: URLs fail when clicked. This needs to
 be resolved somehow.
~~~~

I wonder why it is merged :)

**Comment by shamazmazum** [comment]
Also, is using `nyxt://` or `lisp://` schemes secure at all? What will happen if I follow such a link from an ordinary web page?

**Comment by aartaka** [comment]
Thanks for flagging this! Indeed, internal pages weren't tested in their entirety, and that's partly my fault. However, it's all fixable, and I (or someone else, if they do it faster than me) will fix it in a week, I believe.

**Comment by aartaka** [comment]
> Also, is using `nyxt://` or `lisp://` schemes secure at all? What will happen if I follow such a link from an ordinary web page?

It is quite secure, as `nyxt:` URLs
- are not linkable from outside Web, and 
- restrict the type of content one can pass into those (testing is welcome!).

`lisp:` URLs can only be ran on `nyxt:` pages, so it all should be contained nicely.

**Comment by shamazmazum** [comment]
Thanks!

**Comment by aartaka** [comment]
Commits 3be56b7fc2820e1422a4da45d4cbc61dbf28baf8 to ec086be40bf68f4f9f15ad05bf9038c4d248431b should fix all the commands I've looked at (and I am pretty confident I looked through all of them). @shamazmazum, if there's something else you observe, I'll be glad to know :)

Otherwise this issue can be closed, I believe.

**Comment by shamazmazum** [comment]
Thanks! It seems everything is working, closing.

**Comment by aartaka** [comment]
Thank you for reporting it -- it would't have been fixed that fast without command listing you provided (/^▽^)/
