### ISSUE TITLE
GitHub repo: more labels?

### ISSUE THREAD

**Issue by aartaka** [atlas-engineer/nyxt#1999]
We now have quite a natural separation of different Nyxt subsystems, and every one of those grows to become half-independent. Because of that, there are owners for those, and there are certain ways of doing things for every such subsystem. Having separate GitHub labels for issues related to these subsystems can help maintainers and contributors to understand whether they can help with this issue.

The subsystems that I can clearly state as more or less autonomous, in no particular order:
- `auto-mode`.
- element hints, element frame and `visual-mode` (although I'm not sure about this one).
  - `dom.lisp`?
- `history-tree`.
- `prompt-buffer` (we already have a label for this one).
- WebExtensions support.
- `data-storage` library.
- Configuration system (`define-configuration`, `configure-slot` and other configuration helpers).
- Help system (`describe-*` and manual).
- Renderers.
- User interface (including the `user-interface` library and `nyxt:` URLs).
- `ospama` (OS package manager).
- `libraries/analysis`.
- `libraries/keymap`.

Does this look like a good list to add to labels? Are some of those irrelevant?

**Comment by jmercouris** [comment]
I suggest we first investigate the premise:

1. Should we have owners for each part of the codebase?

Naturally one presumes that specialization makes us more effective. If we were a large organization, and we did not know who knows what, I can imagine it would be useful to be able to tag `ospm`. However, since we are a little tomato, we know who knows what, and we can always use git blame. Therefore, I think this may be a premature optimization!

The second premise:

2. Having separate GitHub labels helps maintainers understand whether they can help.

I think this concern is orthogonal to the existence of labels. If the goal is to understand whether if/how user can help, we should do a better job of communicating in the comments section. By either saying "Hey, I'm working on this". Or "Hey, I need help with this, here is my attempt", and then opening a pull request.

What do you think? Thoughts?

**Comment by Ambrevar** [comment]
I think this concern may and will be partly alleviated when we move some parts of the code to external libraries (at https://github.com/atlals-engineer).

OSPM is already there (though the submodule needs updating), data-storage will end up there Very Soon©, `keymap` is now battle tested and ready to be moved.  `history-tree` could probably be moved as well.

**Comment by aartaka** [comment]
> I think this concern may and will be partly alleviated when we move some parts of the code to external libraries (at https://github.com/atlals-engineer).

Indeed. But still, some things are integral to Nyxt and yet relatively isolated. Think `auto-mode` and element hints. Those might need labels.

> `keymap` is now battle tested and ready to be moved. 

With the exception of #2000 -- it requires `keymap` support too, I suppose :)

> `history-tree` could probably be moved as well.

No problem with it!

I'm dreaming about `prompter` becoming independent someday. I itch to plug it into StumpWM completion code o(^▽^)o

`libraries/web-extensions` should be extracted someday too, as it can benefit any WebKitGTK browser that responds to `WebKitUserMessage`s properly.

**Comment by Ambrevar** [comment]
`prompter` is independent in the sense that it does not depend on Nyxt, but it may be a bit immature still.  Some of 

https://github.com/atlas-engineer/nyxt/issues?q=is%3Aissue+is%3Aopen+label%3Aprompt-buffer

should be addressed first.

It's not very clear to me why #2000 would require an update in `keymap`.  Can you expand?

**Comment by aartaka** [comment]
> It's not very clear to me why #2000 would require an update in `keymap`. Can you expand?

It might be a use-case for `keymap` to allow these half-fall-through events that both trigger a bound command and pass it through to the underlying mechanism. But yes, #2000 may be resolved without `keymap` changes.

**Comment by Ambrevar** [comment]
How would you define "underlying mechanism" in the context of `keymap`?

**Comment by aartaka** [comment]
> How would you define "underlying mechanism" in the context of `keymap`?

Well, in the case of GTK port, it's GTK keys that we process to the `keymap`-understandable form. I guess "underlying mechanism" is not the best phrase for it :sweat_smile:

**Comment by Ambrevar** [comment]
But then `keymap' would have to depend on GTK...
Otherwise we could expose a configurable knob, but it's not very clear
to me where.  Any idea?

**Comment by aartaka** [comment]
> But then `keymap' would have to depend on GTK... Otherwise we could expose a configurable knob, but it's not very clear to me where. Any idea?

I guess the requirements will become clearer when I get to fixing #2000 :)

**Comment by Ambrevar** [comment]
@aartaka Wanna start adding some more labels?  Which ones for now?

**Comment by aartaka** [comment]
> @aartaka Wanna start adding some more labels? Which ones for now?

I'd say `keymap`, `ui`, `history`, and `dom` as the generic versions of some of the above.

**Comment by Ambrevar** [comment]
`ui` could be confusing, don't you think?

**Comment by aartaka** [comment]
> `ui` could be confusing, don't you think?

Why so? 0_o

**Comment by Ambrevar** [comment]
For instance, are "nyxt" URLs part of the UI?
The configuration system?

**Comment by aartaka** [comment]
> For instance, are "nyxt" URLs part of the UI? The configuration system?

Indeed, those are hard to delineate. I'd say if those are (parts of) what user interacts with -- it's UI.
