### ISSUE TITLE
Youtube/google login not happning..page stuck there for infinty

### ISSUE THREAD

**Issue by unixbhaskar** [atlas-engineer/nyxt#2007]
Look like I am the only one suffering from this annoyance. It is simply not allowing or completing login .

Nyxt build from source ......runs on Gentoo, Slackware,Debian and Arch .....

The page stuck there for infinity....

**Comment by aartaka** [comment]
I cannot reproduce, unfortunately :(

Can you, please, provide the full information: what is your system, what is the shell output, what does `show-system-information` provide in Nyxt? The "Bug Report" issue template lists all the information that can help us better understand your problem.

**Comment by unixbhaskar** [comment]
> I cannot reproduce, unfortunately :(
> 
> Can you, please, provide the full information: what is your system, what is the shell output, what does `show-system-information` provide in Nyxt? The "Bug Report" issue template lists all the information that can help us better understand your problem.

@aartaka My sincere apology for the airy-fairy stuff. Here are something which might help 

`
System information

Nyxt version: 2.2.3
Renderer version: GI-GTK
Operating system kernel: Linux 5.15.13-arch1-1
Lisp implementation: SBCL 2.1.4 (Dynamic space size: 1073741824)
Features: (:WEBKIT2 :WEBKIT2-2.30 :WEBKIT2-PASTE-PLAINTEXT :WEBKIT2-TRACKING
 :WEBKIT2-MUTE :WEBKIT2-EMOJI :WEBKIT2-MEDIA :WEBKIT2-SANDBOXING :GTK-3-22
 :GTK-3-20 :GTK-3-18 :GTK-3-16 :GTK-3-14 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6
 :GTK-3-4 :GTK :GDK-3-22 :GDK-3-20 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12
 :GDK-3-10 :GDK-3-8 :GDK-3-6 :GDK-3-4 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF
 :GLIB-2-30 :GLIB-2-32 :GLIB-2-34 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42
 :GLIB-2-44 :GLIB-2-46 :GLIB-2-48 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56
 :GLIB-2-58 :GLIB :NYXT-2 :FSET-EXT-STRINGS :CUSTOM-HASH-TABLE-NATIVE :SWANK
 :PLUMP-UTF-32 :GLOBAL-VARS :DECLARE-TYPES :PARENSCRIPT
 :SBCL+SAFE-STANDARD-READTABLE :NAMED-READTABLES :LPARALLEL :21BIT-CHARS
 :CHUNGA :FLEXI-STREAMS :CLOSER-MOP :CL-PPCRE-UNICODE :CL-UNICODE :CL-PPCRE
 :BORDEAUX-THREADS :LPARALLEL.WITH-CLTL2 :LPARALLEL.WITH-CAS
 :LPARALLEL.WITH-STEALING-SCHEDULER :SPLIT-SEQUENCE CHIPZ-SYSTEM:GRAY-STREAMS
 CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64 CFFI-FEATURES:UNIX :CFFI
 CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP :FAST-IO-SV :FAST-IO
 :SBCL-USES-SB-ROTATE-BYTE :CL-JSON-CLOS :CL-JSON :THREAD-SUPPORT :ASDF3.3
 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX :NON-BASE-CHARS-EXIST-P
 :ASDF-UNICODE :X86-64 :GENCGC :64-BIT :ANSI-CL :COMMON-LISP :ELF
 :IEEE-FLOATING-POINT :LINUX :LITTLE-ENDIAN :PACKAGE-LOCAL-NICKNAMES :SB-LDB
 :SB-PACKAGE-LOCKS :SB-THREAD :SB-UNICODE :SBCL :UNIX)

ASDF version: 3.3.1
ASDF registries: (NYXT-SOURCE-REGISTRY ENVIRONMENT-SOURCE-REGISTRY)
Critical dependencies: (/home/bhaskar/Downloads/nyxt/_build/cl-cffi-gtk/gtk/cl-cffi-gtk.asd
 /home/bhaskar/Downloads/nyxt/_build/cl-gobject-introspection/cl-gobject-introspection.asd
 /home/bhaskar/Downloads/nyxt/_build/cl-webkit/webkit2/cl-webkit2.asd)
`
It is also strage to me ..that the specific thing is not going ...everything else almost alright ...wondering...

**Comment by aartaka** [comment]
Can you reproduce in Epiphany? Can you try compiling Nyxt against another WebKitGTK version?

**Comment by Ambrevar** [comment]
After testing @aartaka's suggestion, could you test https://github.com/atlas-engineer/nyxt/pull/1987 see if it changes anything?

**Comment by unixbhaskar** [comment]
> After testing @aartaka's suggestion, could you test #1987 see if it changes anything?

Well, tell me , where do I see the log what is happening behind the seen?? I want to see what is going on ...system log doesn't show anything ....any flags ...any method....because I failed to discover that. 

@Ambrevar

**Comment by unixbhaskar** [comment]
> Can you reproduce in Epiphany? Can you try compiling Nyxt against another WebKitGTK version?

Hey, recompiling for this to discover??? Do you think that is the sane way of finding stuff? It is looooooooong route and I am reluctant to take it.  

Plus my lacuna.

@aartaka

**Comment by aartaka** [comment]
> > Can you reproduce in Epiphany? Can you try compiling Nyxt against another WebKitGTK version?
> 
> Hey, recompiling for this to discover??? Do you think that is the sane way of finding stuff? It is looooooooong route and I am reluctant to take it.

Indeed, I should've clarified why I suggest recompiling. It seems you're using a relatively old WebKitGTK version (2.30 is a year old). That could be the reason for some things working improperly. There are several ways to test it:
- Try to do the same procedure in Epiphany. 
  - If it doesn't log you in in Epiphany and Epiphany is built against the same WebKitGTK version, then it might well be WebKitGTK problem and updating it can help. 
  - If it works fine in Epiphany, and WebKitGTK version is the same then it's not WebKitGTK problem but us doing something incorrectly.
  - If it works in Epiphany, but Epiphany uses a newer WebKitGTK version, then updating might help too.
- Recompiling Nyxt with another WebKitGTK version. Tests the same thing, but is harder, that's why I suggested it only after suggesting to try reproducing in Epiphany.

I still lack information on shell output (preferably with `nyxt -vvv` call), precise recipe for reproduction, and how you installed Nyxt. I have no choice but to do wild guesses here. You'd help me a lot if you provide more information :)

**Comment by unixbhaskar** [comment]
> > > Can you reproduce in Epiphany? Can you try compiling Nyxt against another WebKitGTK version?
> > 
> > 
> > Hey, recompiling for this to discover??? Do you think that is the sane way of finding stuff? It is looooooooong route and I am reluctant to take it.
> 
> Indeed, I should've clarified why I suggest recompiling. It seems you're using a relatively old WebKitGTK version (2.30 is a year old). That could be the reason for some things working improperly. There are several ways to test it:
> 
> * Try to do the same procedure in Epiphany.
>   
>   * If it doesn't log you in in Epiphany and Epiphany is built against the same WebKitGTK version, then it might well be WebKitGTK problem and updating it can help.
>   * If it works fine in Epiphany, and WebKitGTK version is the same then it's not WebKitGTK problem but us doing something incorrectly.
>   * If it works in Epiphany, but Epiphany uses a newer WebKitGTK version, then updating might help too.
> * Recompiling Nyxt with another WebKitGTK version. Tests the same thing, but is harder, that's why I suggested it only after suggesting to try reproducing in Epiphany.
> 
> I still lack information on shell output (preferably with `nyxt -vvv` call), precise recipe for reproduction, and how you installed Nyxt. I have no choice but to do wild guesses here. You'd help me a lot if you provide more information :)

**Thanks for your patience and rallying along.**

nyxt -vvv   -----> shell produce this : 
```
>nyxt -vvv
Arguments parsed: (VERBOSE T VERBOSE T VERBOSE T URLS NIL) and NIL
 <INFO> [06:49:46] nyxt start.lisp (listen-or-query-socket) -
  Nyxt already started.
```
 I have build and installed it from source .

**This is only happening with google login ......everything else is fine and I can get along smoothly ..no problem whatsoever...reading the manual helps me a lot too. But ....but ...that specific wesite ...i.e google login ....youtube login ....specifically not going ...nothing else.** 


..About upgrading WebKitGTK ...I need to see that ...many other things on the system depend on that and I don't want break that because runnning one particular stuff and faill 30 others. 

Why I am not so "upbeat" about the WebKitGTK upgrade is that , why this specific page stuck?? Why other stuffs are working fine on the same base? 

It seems I am failing to understand the basics somewhere ...sorry about my noobness.  

Well, I will try the route you mentioned ...that will take time ...once I found out something ....will knock you here. 

Again thank you so much for your attention and suggestion...truely appreciate.

**Comment by unixbhaskar** [comment]
> > > > Can you reproduce in Epiphany? Can you try compiling Nyxt against another WebKitGTK version?
> > > 
> > > 
> > > Hey, recompiling for this to discover??? Do you think that is the sane way of finding stuff? It is looooooooong route and I am reluctant to take it.
> > 
> > 
> > Indeed, I should've clarified why I suggest recompiling. It seems you're using a relatively old WebKitGTK version (2.30 is a year old). That could be the reason for some things working improperly. There are several ways to test it:
> > 
> > * Try to do the same procedure in Epiphany.
> >   
> >   * If it doesn't log you in in Epiphany and Epiphany is built against the same WebKitGTK version, then it might well be WebKitGTK problem and updating it can help.
> >   * If it works fine in Epiphany, and WebKitGTK version is the same then it's not WebKitGTK problem but us doing something incorrectly.
> >   * If it works in Epiphany, but Epiphany uses a newer WebKitGTK version, then updating might help too.
> > * Recompiling Nyxt with another WebKitGTK version. Tests the same thing, but is harder, that's why I suggested it only after suggesting to try reproducing in Epiphany.
> > 
> > I still lack information on shell output (preferably with `nyxt -vvv` call), precise recipe for reproduction, and how you installed Nyxt. I have no choice but to do wild guesses here. You'd help me a lot if you provide more information :)
> 
> **Thanks for your patience and rallying along.**
> 
> nyxt -vvv -----> shell produce this :
> 
> ```
> >nyxt -vvv
> Arguments parsed: (VERBOSE T VERBOSE T VERBOSE T URLS NIL) and NIL
>  <INFO> [06:49:46] nyxt start.lisp (listen-or-query-socket) -
>   Nyxt already started.
> ```
> 
> I have build and installed it from source . And I run it on Slackware, Gentoo , Debian and Arch ...no problem with that ...
> 
> **This is only happening with google login ......everything else is fine and I can get along smoothly ..no problem whatsoever...reading the manual helps me a lot too. But ....but ...that specific wesite ...i.e google login ....youtube login ....specifically not going ...nothing else.**
> 
> ..About upgrading WebKitGTK ...I need to see that ...many other things on the system depend on that and I don't want break that because runnning one particular stuff and faill 30 others.
> 
> Why I am not so "upbeat" about the WebKitGTK upgrade is that , why this specific page stuck?? Why other stuffs are working fine on the same base?
> 
> It seems I am failing to understand the basics somewhere ...sorry about my noobness.
> 
> Well, I will try the route you mentioned ...that will take time ...once I found out something ....will knock you here.
> 
> Again thank you so much for your attention and suggestion...truely appreciate.

Yay!!!!!!!!!!!!! Due to some pure luck ...I am able to log in in google and youtube . **I haven't change anything in the system or specifically in Nyxt.**

Don't know what was bugging me these days ...but at last I can log in, like you people. 

But ...but ...I am still wondering how could I see the nyxt log? Is there any way?? I want to see the log what nyxt is doing behind the scene .

I am closing this thread just beacsue it solves the mere problem I was badly facing ..again, you can tell me , how I can see nyxt spitting out log what it is doing ...any specific file to look for the log text ...any specific flag to pass on to see what it is doing on terminal .... I am probably missing out ...but kindly let me , if you can. That will help in the future. I am sure , there will be roadblock ...it happend with every damn software out there and all I wanted to see , easy interface to spitting out "text" log what it is trying to achieve ...not fancy stuff ...plain text log.

**Comment by jmercouris** [comment]
I'm glad you got it working :-)

to see the log run: `nyxt -vvv` in a terminal, and all will be outputted to the console as it is happening!

**Comment by Ambrevar** [comment]
To clarify, `nyxt -vvv` does nothing more than `nyxt -v`.

It seems that the `-vvv` flag has mysteriously become part of the Nyxt folklore since everyone seems to be mentioning it! :)

**Comment by aartaka** [comment]
> It seems that the `-vvv` flag has mysteriously become part of the Nyxt folklore since everyone seems to be mentioning it! :)

Indeed xD I'm pretty sure it originated on IRC with @dtw-waleee debuggin Nyxt with this magic formula :)

**Comment by dtw-waleee** [comment]
Oops :). But I think I got it from the repo or manual somewhere. And assumed a progression of log level from -v to -vvv (many programs do this).

**Comment by jmercouris** [comment]
If one `v` is good, then certainly three `v`s is even better!
