### ISSUE TITLE
Allow toggling status-bar and message-area

### ISSUE THREAD

**Issue by aartaka** [atlas-engineer/nyxt#2009]
Commands toggling status bar and message area could come in handy for those that want to maximize screen real estate. They can help our internal use too: right now, when Nyxt enters fullscreen mode, status bar and message area are still there, which is not nice for a fullscreen mode. Thus, we should ideally toggle those off on fullscreen and toggle them back on on unfullscreen.

The signatures for these commands could be 
``` lisp
(define-command-global toggle-status-bar
    (&key (window (current-window)) (enable-p nil enable-provided)
     (height (height (status-buffer window)))))

(define-command-global toggle-message-area
    (&key (window (current-window)) (enable-p nil enable-provided) height))
```

**Comment by aartaka** [comment]
By status bar i mean what is `status-buffer` in our code and modeline in common sense — the place where URL, modes etc. are displayed.

By message area I mean the blank area below status bar where messages are echoed.

Both of those are below the prompt buffer when it appears, yes.

I'm not sure they should re-appear when prompt buffer is invoked, if they were disabled prior to that. Why would one need those while in prompt-buffer?

**Comment by guojing0** [comment]
To give an example, when one uses the spell checker, the result would `echo` on the message area.

**Comment by aartaka** [comment]
Yes, that is tricky. But then, if one disables those, they'd probably understand what they're doing. It works much the same way as Emacs users doing `(scroll-bar-mode -1)` to disable a (relatively useful) scrollbar to get some more screen space.

**Comment by guojing0** [comment]
Well, I am in the group thinking that "people sometimes may do things but later do not realize what they have done". In other words, I usually perfer presenting the least confusing option(s) to users, advanced or not. I will think about this when implementing said features.

**Comment by aartaka** [comment]
I mean, we're not going to force this on anyone, as disabling interface elements leads to information loss. The only case where I'd suggest actually disabling status bar and message area is the one I mentioned in the original post -- fullscreening page/video.

In all the other cases, it's user's conscious choice to disable/enable those.

**Comment by guojing0** [comment]
Oh, my bad. I must have missed this part ("fullscreening page/video").

**Comment by aartaka** [comment]
> EDIT: One usually does not interact much with Emacs sccroll bar, in that it only tells the user limited information, i.e., where they are in the buffer.

Yes, that is fair. However, it could be useful for e.g. new Emacs users familliar with scrollbars from everywhere else. What I'm getting at there is that everyone has different interface needs and the best we can do is to provide good handles to control the interface with :)

**Comment by guojing0** [comment]
Hi I just found `toggle-toolbars` does this (toggling status buffer and message buffer).

**Comment by aartaka** [comment]
`(un)present-window` functions responsible for interface hiding are now toggled on `(enter|leave)-fullscreen` WebKitGTK signals with 746f2fe78c42b2023a535ef1722e5a43ffce9184! 

The other thing persists: we need user-awailable commands to toggle status bar and message bar separately. And, most importantly, those should have an argument to control whether to enable or disable it unconditionally.

**Comment by aartaka** [comment]
Closing, as #2019 resolves it.
