### ISSUE TITLE
Have more nyxt-* version features?

### ISSUE THREAD

**Issue by aartaka** [atlas-engineer/nyxt#2010]
While we retain the backwards-compatibility only for major releases, minor and even patch ones still carry some new features in them, and one can find those handy. However, these features can make configuration one has backwards-incompatible with the major version. It'd be handy when one can just use a feature reader macro and depend on a certain version of Nyxt. E.g., one may wish to do something like

```lisp
#+(and nyxt-1 (not nyxt-2-2-3))
(do-something-the-old-way)
#+nyxt-2-2-3
(do-something-the-new-way-from-2.2.3)
```

How should we approach feature reader macros? Should we have `nyxt-2` only, or `nyxt-2-2` (or `nyxt-2.2`, the notation is to be discussed), `nyxt-2-2-2`? Should we also include previous versions (`cl-cffi-gtk` does that for Glib bindings), so that code for e.g. `nyxt-2-1` is included in 2.2.4 release alongside `nyxt-2-2-4`? Maybe introduce `#>` and `#<` reader macros to allow working only before/after a certain version?

Does this make sense?

**Comment by jmercouris** [comment]
This makes a lot of sense! I think we should push the full version name, and then decompose it by section within semver:

E.g. Nyxt 5.3.28 will push:

nyxt-5.3.28
nyxt-5.3
nyxt-5

that way the user can have the freedom to decide which feature flags to use.

**Comment by Ambrevar** [comment]
Note that there is `uiop:version<=` which may help here.

I'm in favour of the leaving the periods in the version number, it's less code and what's expected.  After all, one of the perks of Lisp as opposed to other languages is to allow for any character in the symbols!

**Comment by aartaka** [comment]
With  d9c6dbb1e8d5c733e0e4514e60164bfc2f4fb165, 4001156e3a99a8b53db98087b2b0c2c68c6412e5, abea8743316c71d549ceb28d79f2f3d046013498, and f3d7e5eae57a00c8af617680c8451758384aa01e, it should be pretty complete with `nyxt-MAJOR-MINOR-PATCH`, `nyxt-MAJOR-MINOR`, `nyxt-MAJOR`, `nyxt-unstable`, and `nyxt-COMMIT` depending on how Nyxt it built.

Closing this, feel free to reopen in case I've missed something :)

**Comment by Ambrevar** [comment]
Thanks!
