### ISSUE TITLE
headings panel outputs mangled characters sometimes

### ISSUE THREAD

**Issue by aartaka** [atlas-engineer/nyxt#2011]
See https://github.com/atlas-engineer/nyxt/pull/1990#issuecomment-1009768618

**Comment by aartaka** [comment]
It seems to be caused by how we transform Lisp strings into C strings in `cl-webkit`. Those half-decoded strings break exactly where we go outside ASCII, with characters like em dash and non-latin letters.

Is there a way to cleanly transform Lisp strings into UTF-8 arrays to pass to `cffi`, except for `slynk-backend:string-to-utf8`?

**Comment by guojing0** [comment]
Do you think [flexi-streams](https://edicl.github.io/flexi-streams/), [babel](https://babel.common-lisp.dev/), and/or [trivial-utf-8](https://gitlab.common-lisp.net/trivial-utf-8/trivial-utf-8) can be helpful?

**Comment by aartaka** [comment]
Yes, those can help! Will try those out in `cl-webkit` :)
