### ISSUE TITLE
lisp-repl command does not work properly

### ISSUE THREAD

**Issue by shamazmazum** [atlas-engineer/nyxt#2016]
Hi! My nyxt version is #<QL-DIST:RELEASE atlas-engineer-nyxt-20220113114424 / ultralisp 20220113114500>.

`lisp-repl` fails to switch to a new buffer with REPL. That's because `ffi-buffer-load` tries to access `status` slot of a buffer, but `internal-buffer` does not have this slot. Moving this slot to `buffer` just causes more problems.

I checked that `make-internal-buffer` is only used in three places: `source/mode/os-package-manager.lisp`, `source/mode/diff.lisp` and `source/mode/repl.lisp`. Are internal buffers deprecated? What's the alternative? `define-internal-page-command`, maybe? I don't know how to fix this properly. Again, sorry, if this is a known bug :)

**Comment by aartaka** [comment]
I can reproduce, and yes, internal buffer should not be there! We need to rewrite `lisp-repl` using the new `define-internal-page-command`, yes.

**Comment by shamazmazum** [comment]
Sent a PR. BTW, is it a good idea to export `define-internal-page-command`? It seems to be used in many places outside of `nyxt` package.

**Comment by aartaka** [comment]
> Sent a PR.

Wow, that was fast ＼（＾▽＾）／

> BTW, is it a good idea to export `define-internal-page-command`? It seems to be used in many places outside of `nyxt` package.

Yes, exporting it is the right move, I'm sure :)
