### ISSUE TITLE
How to load JavaScript? (With bookmarklets?)

### ISSUE THREAD

**Issue by alexherbo2** [atlas-engineer/nyxt#202]

**Comment by jmercouris** [comment]
You can take a look at the `define-parenscript` macro which you can use. It is used several times in the codebase, you can then wrap it in a `define-command` to invoke it interactively. If you like I can expand upon it more.

**Comment by Ambrevar** [comment]
By the way: currently keys can be bound to any function, not just command.
Should we restrict keys to commands just like in Emacs?

**Comment by jmercouris** [comment]
I don't think we need to make this distinction between (interactive) and not like Emacs does. I can't think of a good reason to do it really (except for maybe enforcing the existence of docstrings for commands or something).

**Comment by alexherbo2** [comment]
Can you show me how to source a file and execute a function from a key-binding?

**Comment by Ambrevar** [comment]
@jmercouris: Off the top of my head, some good reasons:
- Interactive functions cannot take arguments (at least for now), so restricting bindings to argument-less commands is a way to ensure the bindings won't be broken.
- Some functions are inherently too low-level to be called interactively.  Commands can be seen as a way of telling the user "this can be used as a bingind" while other functions are not support to be.

We could probably avoid a lot of headache in the community if we make this distinction.  Thoughts?

**Comment by Ambrevar** [comment]
@alexherbo2: You can load a file with

```
M-x load-file RET
```
It must be a valid Common Lisp file.
Example:

``` lisp
(in-package :next)

(define-command play-video-in-current-page ()
  "Play video in the currently open buffer."
  (with-result (url (buffer-get-url))
    (uiop:run-program (list "mpv" url))))

(define-key (key "C-M-c v") 'play-video-in-current-page)
```

The documentation is in the process of being updated, stay tuned! :)

**Comment by alexherbo2** [comment]
@Ambrevar I mean how to source a JavaScript file in the context of web pages, and execute a JavaScript function from a mapping.

**Comment by jmercouris** [comment]
Hi @alexherbo2 , do you mean something like the following?

```
(define-parenscript invoke-some-js ()
    (javascript-function))
```

You would then create a command to invoke that parenscript.

**Comment by jmercouris** [comment]
@Ambrevar that is a good point. If a function accepts arguments it can't exactly be called interactively- YET! What if we had interactive functions that can accept argument values by prompting the user for the value of each argument?

E.g. weI could write something like

```
(define-command scroll-down (distance)
   ...
```

then when I M-x "scroll-down", I would get a prompt in the minibuffer like "Distance?"

**Comment by Ambrevar** [comment]
@jmercouris: Yes, we could prompt for the arguments.  This would require
a bit of work though, I'm not sure if it's possible to introspect the
function arguments in Common Lisp.

Something to keep on the table for sure.

Anyways, for now I've pushed a commit turning all commands to mode
methods, and as such bindings can only execute methods on modes now.
We can still change this behaviour later.

**Comment by jmercouris** [comment]
@ambrevar fantastic! agreed

**Comment by easye** [comment]
>  I'm not sure if it's possible to introspect the function arguments in Common Lisp. 

There is indeed no portable way to inspect function arguments.  

q.v. https://stackoverflow.com/a/8363279/450422

**Comment by jmercouris** [comment]
So, the define-command macro needs to become more sophisticated, and then we have a class to store the meta data :D

**Comment by alexherbo2** [comment]
@jmercouris Can you give me some concrete examples?

**Comment by Ambrevar** [comment]
Try the following from a REPL:

``` lisp
(%%buffer-evaluate-javascript
 *interface*
 (active-buffer *interface*)
 (uiop:read-file-string "/path/to/my/javascript.js"))
```

**Comment by Ambrevar** [comment]
@jmercouris Should we document how to do this?  I believe this is a common use case, so adding an example in the manual would be welcome!

**Comment by jmercouris** [comment]
We can do that, I think the article about bookmarklets covers it well enough. What do you think?

**Comment by Ambrevar** [comment]
It does not tell how to load an external JavaScript file.
I think it'd be nice to document it.

**Comment by jmercouris** [comment]
Better yet, it would be cool if Bookmarklets allowed specification of a file path for some JS!

**Comment by Ambrevar** [comment]
> Better yet, it would be cool if Bookmarklets allowed specification of a file path for some JS!

Absolutely!

**Comment by Ambrevar** [comment]
Reopening so we remember to add this feature to bookmarklets.

**Comment by jmercouris** [comment]
You can now do this:

```
(define-bookmarklet-command fish
  "Color internal links red, external links blue, and in-page links orange."
  "file:///home/jmercouris/Downloads/fish.js")
```

on master.
