### ISSUE TITLE
Search terms are deleted in visual-mode after searching in a page.

### ISSUE THREAD

**Issue by taiju** [atlas-engineer/nyxt#2020]
Search terms are deleted in visual-mode after searching in a page. From #2015 

**Steps to Reproduce**

1. Open https://nyxt.atlas.engineer/ in Nyxt.
2. Execute the search-buffer command to search for "nyxt".
3. Execute visual-mode command.

**Expected behavior**

Able to use visual-mode, including search terms.

**Actual behavior**

Search terms are removed when switching to visual-mode.

**Information**
- OS name+version: GNU Guix
- Graphics card and driver: AMD Renoir
- Desktop environment / Window manager name+version: GNOME 40.4
- How you installed Nyxt (Guix pack, package manager, build from source): guix install
- Information from `show-system-information`: 

```
Nyxt version: 2.2.3
Renderer version: GI-GTK
Operating system kernel: Linux 5.15.13
Lisp implementation: SBCL 2.1.9 (Dynamic space size: 3221225472)
Features: (:WEBKIT2 :WEBKIT2-2.34 :WEBKIT2-PASTE-PLAINTEXT :WEBKIT2-TRACKING
 :WEBKIT2-MUTE :WEBKIT2-EMOJI :WEBKIT2-MEDIA :WEBKIT2-SANDBOXING :GTK-3-22
 :GTK-3-20 :GTK-3-18 :GTK-3-16 :GTK-3-14 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6
 :GTK-3-4 :GTK :GDK-3-22 :GDK-3-20 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12
 :GDK-3-10 :GDK-3-8 :GDK-3-6 :GDK-3-4 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF
 :GLIB-2-30 :GLIB-2-32 :GLIB-2-34 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42
 :GLIB-2-44 :GLIB-2-46 :GLIB-2-48 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56
 :GLIB-2-58 :GLIB :NYXT-2 :FSET-EXT-STRINGS :CUSTOM-HASH-TABLE-NATIVE :SWANK
 :PLUMP-UTF-32 :GLOBAL-VARS :DECLARE-TYPES :PARENSCRIPT :NAMED-READTABLES
 :LPARALLEL :21BIT-CHARS :CHUNGA :FLEXI-STREAMS :CLOSER-MOP :CL-PPCRE-UNICODE
 :CL-UNICODE :CL-PPCRE :BORDEAUX-THREADS :LPARALLEL.WITH-CLTL2
 :LPARALLEL.WITH-CAS :LPARALLEL.WITH-STEALING-SCHEDULER :SPLIT-SEQUENCE
 CHIPZ-SYSTEM:GRAY-STREAMS CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64
 CFFI-FEATURES:UNIX :CFFI CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP
 :FAST-IO-SV :FAST-IO :SBCL-USES-SB-ROTATE-BYTE :CL-JSON-CLOS :CL-JSON
 :THREAD-SUPPORT :ASDF3.3 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX
 :NON-BASE-CHARS-EXIST-P :ASDF-UNICODE :X86-64 :GENCGC :64-BIT :ANSI-CL
 :COMMON-LISP :ELF :IEEE-FLOATING-POINT :LINUX :LITTLE-ENDIAN
 :PACKAGE-LOCAL-NICKNAMES :SB-CORE-COMPRESSION :SB-LDB :SB-PACKAGE-LOCKS
 :SB-THREAD :SB-UNICODE :SBCL :UNIX)

ASDF version: 3.3.5
ASDF registries: (NYXT-SOURCE-REGISTRY ENVIRONMENT-SOURCE-REGISTRY USER-SOURCE-REGISTRY
                      USER-SOURCE-REGISTRY-DIRECTORY
                      DEFAULT-USER-SOURCE-REGISTRY SYSTEM-SOURCE-REGISTRY
                      SYSTEM-SOURCE-REGISTRY-DIRECTORY
                      DEFAULT-SYSTEM-SOURCE-REGISTRY)
Critical dependencies: (/gnu/store/x4jgpsgq4w6xa0pbg5y7xh6ppyky5l6b-sbcl-cl-cffi-gtk-0.11.2-2.e9a46df/share/common-lisp/sbcl/cl-cffi-gtk/gtk/cl-cffi-gtk.asd
 /gnu/store/bdfnmkxaxsgq5a2073hgjsb700yhbjlb-sbcl-cl-gobject-introspection-0.3-1.d0136c8/share/common-lisp/sbcl/cl-gobject-introspection/cl-gobject-introspection.asd
 /gnu/store/lafbdh898qdyrjrqb1d30ykgz9rnfnbs-sbcl-cl-webkit-3.4.0/share/common-lisp/sbcl/cl-webkit/webkit2/cl-webkit2.asd)

Guix version: 
```

**Comment by taiju** [comment]
I would like to continue trying to fix it.
I have two ideas in mind.
1. Remove search highlighting when moving to `.visual-mode`.
2. Of the elements with `.nyxt-hint`, if the parent element is an element with `.nyxt-search-node`, keep the content of the parent element and remove the tag (remove the rest of the elements)

Which would be better? Or is another method better?

**Comment by aartaka** [comment]
The all-encompasing fix would be to make our search hinting non-destructive, so that adding a hint and not running the proper cleaning procedure doesn't leave us with the page with matching parts deleted. This, however, requires quite some digging in both JavaScript ways of doing search hints and our own Parenscript search implementation (in source/mode/search-buffer.lisp).

The option I've been thinking about since we started using Plump for our document model was using the same document model for search -- it will all be pure Lisp with occasional JavaScript calls, instead of current pile of Parenscript code that's hard to debug and reason about (it works fine most of the time, though).

Removing a certain set of search elements when moving to `visual-mode` sounds like too temporary of a fix. Cleaning the hints when doing something else that is not searching sounds like a good idea! I wonder why we didn't do it earlier :thinking:

**Comment by aartaka** [comment]
Oh wait, so you want search hints to _stay_ after the search is over?

**Comment by taiju** [comment]
> Oh wait, so you want search hints to stay after the search is over?
I am aware that the current specification is that the search hint stay after the search.
Perhaps we should revise this specification.
Personally, I don't think there is much inconvenience if the search hints are removed after a search.

**Comment by taiju** [comment]
By the way, I just noticed that the number of search results is different when I do a page search in Firefox and Chromium, and when I do a page search in Nyxt.
In some cases, it seems that Nyxt has more search results than Firefox or Chromium.
Try searching for "fork" on this page.
Nyxt's search results seem to include some words that are not visible, but I think they are unnecessary for many users.

**Comment by taiju** [comment]
The request of #1949 also needs to be considered.

**Comment by aartaka** [comment]
> > Oh wait, so you want search hints to stay after the search is over?
> 
> I am aware that the current specification is that the search hint stay after the search. Perhaps we should revise this specification. Personally, I don't think there is much inconvenience if the search hints are removed after a search.

I'm gravitating towards removing search hints unconditionally when the search prompt is closed, like other browsers do. @jmercouris, @Ambrevar, @pdelfino, @guojing0, any opinion on it?

**Comment by Ambrevar** [comment]
At least have an option for it ;)

**Comment by taiju** [comment]
Sorry for the late comment.
I see, in order to improve this feature, it would be desirable to have an option to turn off or keep search highlighting.
I may not be able to send a pull request right away, but if this issue is low priority, would you mind if I, a Common Lisp newbie, continue to work on solving this issue?

**Comment by aartaka** [comment]
No one would mind, I believe :)

Good luck with this issue and learning Common Lisp!

**Comment by taiju** [comment]
@aartaka Is it OK to close this issue?

**Comment by aartaka** [comment]
Yes, thanks for pinging!
