### ISSUE TITLE
Local internal page?

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#2026]
Currently `define-internal-page` generates a global command.

However, what about mode-local commands, i.e. internal pages that are only available from an internal page with a specific mode?

Shouldn't we allow the local equivalent of `define-internal-page`?  @aartaka ?

**Comment by aartaka** [comment]
Yes we should!

**Comment by aartaka** [comment]
Done with 7c8746ef98349f6529f09703313eb120f4888a6d.
