### ISSUE TITLE
Create a Nyxt theme with a style inspired by the visual identity of the Nyxt Academy slides

### ISSUE THREAD

**Issue by pdelfino** [atlas-engineer/nyxt#2043]
It would be interesting to use it in some videos. And it would be fun :)

**Comment by pdelfino** [comment]
The designer who did the visual identity suggested these material for us. 
![3](https://user-images.githubusercontent.com/7698207/150614405-b106b8c0-3da5-427e-8e12-c971f8a6fbbf.jpeg)
![2](https://user-images.githubusercontent.com/7698207/150614407-a257b4cb-518d-4a82-a5b8-6eba665aab0e.jpeg)
![WhatsApp Image 2022-01-21 at 20 37 44](https://user-images.githubusercontent.com/7698207/150614409-2a604ce3-f0b7-4484-98f4-c95931c672eb.jpeg)

She uses [this website ](https://coolors.co/a45c30-ffffff-000000-247ba0-3e78b2) to generate combinations.

**Comment by aartaka** [comment]
I like the second combination -- this shade of yellow would look insanely cook in element hints!

**Comment by aartaka** [comment]
I've played a bit this Coolors, and here's a combinations that could work:

![nyxt-academy](https://user-images.githubusercontent.com/57838654/150635081-43afb4b3-2020-4e45-ba7e-afb18203f2f8.png)

Or, as a configuration snippet that you could try out in your config file:

```
(define-configuration browser
  ((theme (make-instance
           'theme:theme
           :dark-p t
           :background-color "black"
           :text-color "white"
           :accent-color "#FCBA04"
           :primary-color "#A45C30"
           :secondary-color "#DB9665"
           :tertiary-color "#AD693E"
           :quaternary-color "#7D3509"))))
```

It has some Greek amphora vibe to it, hasn't it?

![E5965B75](https://user-images.githubusercontent.com/57838654/150634995-fd9d24ed-2f76-4b3a-a188-c86115a6b84b.png)

**Comment by aartaka** [comment]
What I don't like about the theme that I suggested is:
- The yellow is a bit too bright, maybe use some lighter shade?
- Primary and tertiary colors are too close. This could cause confusion.

**Comment by aartaka** [comment]
@pdelfino, @jmercouris, any feedback?

**Comment by pdelfino** [comment]
> @pdelfino, @jmercouris, any feedback?

I think it is great! Good job, Artyom.

I showed this to Nivea (the designer) and she liked it :slightly_smiling_face:

 For me, it is ready to go :)

Since you did some self-assessment, I tried giving some contribution:

```lisp
(define-configuration browser
  ((theme (make-instance
           'theme:theme
           :dark-p t
           :background-color "black"
           :text-color "white"
           :accent-color "#7E5D01"
           :primary-color "#A45C30"
           :secondary-color "#DB9665"
           :tertiary-color "#AD693E"
           :quaternary-color "#7D3509"))))
```

I inserted `#FCBA04` on this feature of the above mentioned tool: [Color Picker generation](https://coolors.co/fcba04).     

They show a roll of options to add "darkness" to a specific color.  I picked one to reduce the brightness and this is the result:

![Screenshot from 2022-01-31 14-26-45](https://user-images.githubusercontent.com/7698207/151842781-0349b7f4-b86a-416d-b36a-7e7b627ce053.png)

What do you think? An improvement?

For me, your version is better. The bright yellow fits well with the purpose of the "select" color on the prompt-buffer.

> Primary and tertiary colors are too close. This could cause confusion.

Not sure if this could really cause any damage considering how the UI is divided. Maybe I missed something. What could be a possible concrete problem? Can you think of a concrete example of confusion a user could have?


Thanks!

**Comment by aartaka** [comment]
Indeed, the bright yellow seems to be optimal here. After all, accent color is made to be noticeable :)

The closeness of primary and tertiary colors can cause confusion in complex interfaces with a lot of theming baked in. We do not yet have such interfaces, but it's better to prepare for it. However, I may be over-engineering here -- colors are relatively distinguishable, so it should not cause much problems.

I wonder if there are tools for interface color audits, like there are tools for text color contrast checking...

@pdelfino, would you be interested is implementing theme settings, as we discussed via email (`+dark-theme+` and `+light-theme+` variables, Common Settings page with color samples and ability to change the theme). If not, I can do it sometime this week :)

**Comment by unixbhaskar** [comment]
Well, as this still active(holding my breath) .....can some of you smart people get us a "Dark Solarized theme"...please! @Ambrevar @aartaka @pdelfino

**Comment by aartaka** [comment]
@unixbhaskar, if you're on master, then you can see the snippet above, alter it to the colors you like, and use is as the `theme` of the `browser`.

As far as I understand, you're using my config as the base for yours. If so, then you'll find the theme definition in style.lisp. Should be easy replacing colors and observing the change after restarting Nyxt :)

**Comment by unixbhaskar** [comment]
> @unixbhaskar, if you're on master, then you can see the snippet above, alter it to the colors you like, and use is as the `theme` of the `browser`.
> 
> As far as I understand, you're using my config as the base for yours. If so, then you'll find the theme definition in style.lisp. Should be easy replacing colors and observing the change after restarting Nyxt :)

I am using stable i.2.4 and I tried to put the above code snippet in style.lisp ...but it errors out. I am doing something wrong for sure.

**Comment by aartaka** [comment]
Theming will only be part of 3.0, unfortunately. It's non-existent on 2-series :(

**Comment by aartaka** [comment]
It is indeed hard to configure Nyxt in between versions. But, well, we cannot freeze Nyxt forever for the sake of config compatibility :)

The APIs and changes coming in 3.0 (including theming) will help in both using and extending Nyxt :)

**Comment by pdelfino** [comment]
This task was delivered with #2116. Thus, I am closing the issue :v:
