### ISSUE TITLE
There is no annotation related command ,what am I missing???

### ISSUE THREAD

**Issue by unixbhaskar** [atlas-engineer/nyxt#2046]
**Describe the bug**
Could not find annotation related commands 
**Precise recipe to reproduce the issue**
M-x or ctrl-space execute-command minibuffer fuzzy search not showing any annotate command 
For website-specific issues:
Can you reproduce this issue with Epiphany / GNOME Web (https://wiki.gnome.org/Apps/Web)?
Not relevent
**Information**
- OS name+version:  Gentoo, Slackware, Debian, Arch
- Graphics card and driver: i915 INTEL 
- Desktop environment / Window manager name+version: i3(No underlying DE)
- How you installed Nyxt (Guix pack, package manager, build from source): build from source
- Information from `show-system-information`:
Nyxt version: 2.2.4
Renderer version: GI-GTK
Operating system kernel: Linux 5.16.1-Gentoo
Lisp implementation: SBCL 2.1.4 (Dynamic space size: 3221225472)
Features: (:WEBKIT2 :WEBKIT2-2.34 :WEBKIT2-PASTE-PLAINTEXT :WEBKIT2-TRACKING
 :WEBKIT2-MUTE :WEBKIT2-EMOJI :WEBKIT2-MEDIA :WEBKIT2-SANDBOXING :GTK-3-22
 :GTK-3-20 :GTK-3-18 :GTK-3-16 :GTK-3-14 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6
 :GTK-3-4 :GTK :GDK-3-22 :GDK-3-20 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12
 :GDK-3-10 :GDK-3-8 :GDK-3-6 :GDK-3-4 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF
 :GLIB-2-30 :GLIB-2-32 :GLIB-2-34 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42
 :GLIB-2-44 :GLIB-2-46 :GLIB-2-48 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56
 :GLIB-2-58 :GLIB :NYXT-2 :FSET-EXT-STRINGS :CUSTOM-HASH-TABLE-NATIVE :SWANK
 :PLUMP-UTF-32 :GLOBAL-VARS :DECLARE-TYPES :PARENSCRIPT
 :SBCL+SAFE-STANDARD-READTABLE :NAMED-READTABLES :LPARALLEL :21BIT-CHARS
 :CHUNGA :CLOSER-MOP :CL-PPCRE-UNICODE :FLEXI-STREAMS :CL-UNICODE :CL-PPCRE
 :CL-JSON-DOUBLE-FLOAT-IS-SUBSUMED :CL-JSON-SINGLE-FLOAT-IS-SUBSUMED
 :BORDEAUX-THREADS :LPARALLEL.WITH-CLTL2 :LPARALLEL.WITH-CAS
 :LPARALLEL.WITH-STEALING-SCHEDULER :SPLIT-SEQUENCE CHIPZ-SYSTEM:GRAY-STREAMS
 CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64 CFFI-FEATURES:UNIX :CFFI
 CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP :FAST-IO-SV :FAST-IO
 :SBCL-USES-SB-ROTATE-BYTE :CL-JSON-CLOS :CL-JSON :THREAD-SUPPORT :ASDF3.3
 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX :NON-BASE-CHARS-EXIST-P
 :ASDF-UNICODE :X86-64 :GENCGC :64-BIT :ANSI-CL :COMMON-LISP :ELF
 :IEEE-FLOATING-POINT :LINUX :LITTLE-ENDIAN :PACKAGE-LOCAL-NICKNAMES :SB-LDB
 :SB-PACKAGE-LOCKS :SB-THREAD :SB-UNICODE :SBCL :UNIX)

ASDF version: 3.3.1
ASDF registries: (NYXT-SOURCE-REGISTRY ENVIRONMENT-SOURCE-REGISTRY)
Critical dependencies: (/home/bhaskar/Downloads/nyxt2.4/_build/cl-cffi-gtk/gtk/cl-cffi-gtk.asd
 /home/bhaskar/Downloads/nyxt2.4/_build/cl-gobject-introspection/cl-gobject-introspection.asd
 /home/bhaskar/Downloads/nyxt2.4/_build/cl-webkit/webkit2/cl-webkit2.asd)
  If you can't run `show-system-information`, try `nyxt --system-information` from
  a shell.  It this still does not work, please provide the following:
  - Nyxt version (from the `nyxt-version` command or `nyxt --version` from a shell):
  - bhaskar@Gentoo_18:39:03_Sun Jan 23: :~>nyxt --version
WARNING:
   Type initializer for class 'WebKitMediaKeySystemPermissionRequest' (GType 'WEBKIT-MEDIA-KEY-SYSTEM-PERMISSION-REQUEST') is invalid: foreign symbol 'webkit_media_key_system_permission_request_get_type'
Nyxt version 2.2.4
  - Lisp implementation/version (if built from source):
  - Kernel name+version: 5.16.1 
  - WebKitGTK+ | QtWebEngine version: 

**Output when started from a shell**

**Comment by Ambrevar** [comment]
Can you share an _exact_ recipe (telling us exactly which key you pressed and what you typed)?

**Comment by unixbhaskar** [comment]
> Can you share an _exact_ recipe (telling us exactly which key you pressed and what you typed)?

While on a web page I selected a few texts then M-x to get the command prompt then while searching annotation ...nothing shows up. Wondering something I might have missed while building.

**Comment by unixbhaskar** [comment]
> Please share an _exact_ recipe, exact to the keys that you typed. I cannot reproduce otherwise.

I didn't press any key ..but type annotation on "Execute commnd" text area , but the fuzzy search didn't show me any result related to annonation.  This is exact steps I did. 

1) open a webpage
2) select few text with 
3) Type M-x to open "Execute command" text area
4) Type "annotate" and the fuzzy search result in minibuffer NOT showing any command related to annotation. 

This is the complete process I followed ...no other key press .

**Comment by Ambrevar** [comment]
Can you share a screenshot displaying the issue?
Your Nyxt does not seem to be built correctly.

**Comment by aartaka** [comment]
But wait, annotation-related commands are not part of 2-series branch, aren't they?

**Comment by unixbhaskar** [comment]
> But wait, annotation-related commands are not part of 2-series branch, aren't they?

It seems so.

**Comment by unixbhaskar** [comment]
> Can you share a screenshot displaying the issue?
> Your Nyxt does not seem to be built correctly.

:) That's wild guess and incorrect.

**Comment by aartaka** [comment]
Are you sure that you built the most recent Nyxt version? It seems that you're still running a stable 2.2.4.

**Comment by unixbhaskar** [comment]
> Are you sure that you built the most recent Nyxt version? It seems that you're still running a stable 2.2.4.

yes I do running stable version.....but I have built it from master branch and it had the same problem exibited . And you probably , suggested me somewhere else do that ,...so I followed and the outcome was the same as stable ....means the similar activity resulted in same result .

**Comment by unixbhaskar** [comment]
> Can you share a screenshot displaying the issue?
> Your Nyxt does not seem to be built correctly.

@aartaka  @Ambrevar 

This is a mundane script to build nyxt from git master branch ...

https://raw.githubusercontent.com/unixbhaskar/AdminScripts/master/build_nyxt_from_git_master_branch.sh

**Comment by unixbhaskar** [comment]
@aartaka @Ambrevar  I can confirm, that I can see the **annotate-this-url** in the build of master branch.

I am closing this thread, because ,that feature is for future release. Thanks for your patience.

**Comment by aartaka** [comment]
Good luck using annotations :)
