### ISSUE TITLE
Spurious warning on lisp-eval when form returns un-serializable data?

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#2055]
In Demeter we return a list of feeds in `add-rss-feed`, and this triggers:

```log
<WARN> [11:41:24] Warning: Error while routing "lisp:" URL: The value
                                   NIL
                                 is not of type
                                   ARRAY
```

@aartaka Should we be more silent here?  Or does `lisp-eval` expect explicit `nil` or `(values)` return vaues?

**Comment by aartaka** [comment]
We can supress these warnings, no problem. It is quite unsettling to see lots of these errors, I suppose.

**Comment by Ambrevar** [comment]
Maybe add an open to lisp-eval that triggers warning on serialization
error.
This could be useful for callers who expect something.

Alternative, have a lisp-eval* alter-ego which silences the warnings.

**Comment by aartaka** [comment]
Or we can use `log:debug` insted of `log:warn` :)

**Comment by Ambrevar** [comment]
Agreed!

**Comment by aartaka** [comment]
See #2049 (and 9885304d2f35d964f2680d3f2a9d4074dd4525f3) for the fix.

**Comment by Ambrevar** [comment]
Looks good!
