### ISSUE TITLE
lisp-eval broken?

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#2059]
No `lisp-eval` call seems to do anything on master (1d88381513cf0469583febcd6fb070841fd614eb).  @aartaka Regression?

**Comment by aartaka** [comment]
You sure? "Edit user files button" works for me at ed97f71e66c7a4b3eea481d3bb7e5951fb88df76 :upside_down_face:

**Comment by Ambrevar** [comment]
Commit d3f7ca64c600818c8e938ad80da9a67e8c823f2b works for me.

**Comment by Ambrevar** [comment]
My bad, there is an issue when I load my init file.  I presume something to do with the modes.

**Comment by Ambrevar** [comment]
Got it!  It's noscript-mode :p 

I guess we should change noscript-mode to not do anything on internal page.  What do you think?

**Comment by aartaka** [comment]
> Got it! It's noscript-mode :p 

Wow, what an unexpected move :D

> I guess we should change noscript-mode to not do anything on internal page. What do you think?

Yes, that sounds reasonable :)

**Comment by Ambrevar** [comment]
Will do!
