### ISSUE TITLE
Move auto-mode to a first class browser feature

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#2066]
Having auto-mode as a mode is confusing and raises too many questions (for instance what happens when auto-mode disables itself?).

Moving it to a first class feature would fix a few design issues, for instance with gemini/gopher schemes that need the mode automatically enabled on their scheme.

On the other hand, having everything as a mode is also cool.

Thoughts?

**Comment by hendursaga** [comment]
#2004 would be relevant, wouldn't it?

**Comment by Ambrevar** [comment]
Yes indeed!
