### ISSUE TITLE
Include the external symbols of any package in the `describe-*` commands.

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#2067]
We could even prompt for which package we want to include in the search.

**Comment by guojing0** [comment]
So if we import/load, say, "alexandria", then e.g. `describe-make-gensym` would appear in the commands and its result would be its docstring? I'm slightly curious about the use cases...

**Comment by Ambrevar** [comment]
No no no, that would be crazy! :p

I mean if the package Alexandria is loaded (which it is), then
describe-function, descriabe-variable, etc. should also include symbols
from Alexandria, not just from the Nyxt package.

**Comment by aartaka** [comment]
Already on master, under the `C-h u` key prefix!

**Comment by aartaka** [comment]
The package search should be more or less covered by fuzzy matching of package prefixes.

**Comment by Ambrevar** [comment]
Excellent, thanks a lot!
