### ISSUE TITLE
Inconsistent `auto-init-data-path` type and `auto-config` file name. 

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#2074]
I think the `auto-*` file should be named like the `init` file but with the `auto-` suffix.

By the way, should we seize the 3.0 opportunity to rename our config files?
The benefit is that migration would be smoother since Nyxt 3 would not load the 2.* config by default.

I suggestion full-word names:

- `settings.lisp`
- `configuration.lisp`
- `initialization.lisp`

Thoughts?

**Comment by jmercouris** [comment]
I agree that we should use full english words as the names. There is no need to confuse he user.

My vote is for `initialization.lisp`. I also strongly suggest we alias `init.lisp` and also check the existence.

**Comment by guojing0** [comment]
Do you mean we keep all these names or just pick one or two of them?

As someone whose second language is English, `initialization.lisp` looks like a file that's loaded upon launch, while `settings.lisp` and `configuration.lisp` are ones where we keep the setting changes.

**Comment by Ambrevar** [comment]
I've updated my rationale a bit:

- One word is less confusing than many.
- `auto-initialization` sounds wrong.

With that in mind, I'd go for `configuration.lisp` and `auto-configuration.lisp`.

**Comment by jmercouris** [comment]
I have been swayed to agree with `configuration.lisp` and `auto-configuration.lisp`. We will (as discussed by Pierre and I) allow the user to use alias `init.lisp`.
