### ISSUE TITLE
nyxt-2.2.3 OR lisp-nyxt-2.2.3

### ISSUE THREAD

**Issue by haroldcarr** [atlas-engineer/nyxt#2076]
In Nix I see:

```
> nix-env -qa | grep -i nyxt
lisp-nyxt-2.2.3
nyxt-2.2.3
```

What is the difference?
Which one should I install?

**Comment by jmercouris** [comment]
That is a good question, and I don't know. I personally run a nix shell on my machine with the latest compiled. You can see it in the build-scripts directory.

**Comment by haroldcarr** [comment]
I'll try `nyxt-2.2.3` and see what happens.
