### ISSUE TITLE
Cannot compile from source on Debian stable

### ISSUE THREAD

**Issue by Mestelan** [atlas-engineer/nyxt#2082]
Hello, 
I can no longer compile the Nyxt project from source.
Here is a link to the compilation error: https://gist.github.com/Mestelan/f08354f64aded73e5d71e21945a39de9

- Kernel name+version:
Linux 5.10.0-11-amd64 SMP Debian 5.10.92-1 (2022-01-18) x86_64 GNU/Linux

I have just built this with no problem on an Ubuntu box. Am I missing a package? Would you please have a hint to share?

**Comment by aartaka** [comment]
Can you try fetching tags, i.e. `git fetch -t`?

**Comment by Mestelan** [comment]
Thank you @aartaka.
Indeed, everything compiled OK after running  `git fetch -t`.
