### ISSUE TITLE
Centered Cursor Mode

### ISSUE THREAD

**Issue by dcunited001** [atlas-engineer/nyxt#2085]
#### Is your feature request related to a problem? Please describe.

So when I'm using `C-s s` search, it's easy to navigate up and down the search hits using the table that pops up. however, quite often there are search results where the context is off screen and I must reach over and grab the mouse to scroll down a bit.

This is problematic for large documents with sparse search results, since they will tend to always appear at the top/bottom of the visible buffer, masking the context.

#### Describe the solution you'd like

Emacs has a mode called `centered-cursor-mode`, which is a default that I use. I like being able to toggle it off & on (sometimes it's useful to turn off for buffers), but I start Emacs with it enabled.

#### Describe alternatives you've considered

If there's a way to scroll the buffer while the search hits table is highlighted. However, since the cursor is focused on the table, that makes the default up/down keybinds move between search hits.  This makes sense. 

Is there a separate set of keybinds for moving the buffer while search is focused?

#### Additional context

I'm a new user, but thanks for hearing me out.

**Comment by aartaka** [comment]
There are indeed keybindings for what you want: `C-M-p` and `C-M-n` (in both Emacs and VI bindings) will scroll the buffer behind the search prompt/table up and down (respectively).

Search hints misbehave sometimes, and that's a thing I am personally irritated with. Hopefully, someday we'll make their behavior more intuitive, likely getting closer to what you described :)

**Comment by jmercouris** [comment]
I wish we could make them appear in the center. We'd have to do some JS wizardry to do so. Right now we only check if they are in viewport, and if they are not, move them into the viewport.
