### ISSUE TITLE
"cannot redirect in an iframe" message when handling link clicks

### ISSUE THREAD

**Issue by Anomalocaridid** [atlas-engineer/nyxt#2091]
**Describe the bug**
If I click on a link that would be handled by a `request-resource-hook` handler, I get sent to the original URL and a message saying "Cannot redirect to __ in an iframe, forwarding to the original url (___) ", where the blanks are the redirected url and the original, non-redirected url, respectively. This appears to occur using both handlers from nx-freestance-handler and with custom-written handlers.

**Precise recipe to reproduce the issue**
1. Install nx-freestance-handler.
2. Set up one or more of its handlers.
3. Manually enter a URL handled by one of the handlers.
4. You should be redirected as expected.
5. Search on Google or DuckDuckGo for a page that would be handled and click its link.
6. You should get the aforementioned message and be sent to the non-redirected web page.

For website-specific issues:
Can you reproduce this issue with Epiphany / GNOME Web (https://wiki.gnome.org/Apps/Web)?
This is not website-specific

**Information**
- OS name+version: EndeavourOS Rolling
- Graphics card and driver: AMD Radeon RX 580 and AMDGPU
- Desktop environment / Window manager name+version: Sway 1.7
- How you installed Nyxt (Guix pack, package manager, build from source): nyxt-browser-git AUR package
- Information from `show-system-information`:
```
Nyxt version: 2.1.1-1577-g38ea3234
Renderer version: GI-GTK
Operating system kernel: Linux 5.16.7-arch1-1
Lisp implementation: SBCL 2.2.1 (Dynamic space size: 3221225472)
Features: (:WEBKIT2 :WEBKIT2-2.34 :WEBKIT2-CORS-ALLOWLIST :WEBKIT2-PASTE-PLAINTEXT
 :WEBKIT2-TRACKING :WEBKIT2-MUTE :WEBKIT2-EMOJI :WEBKIT2-MEDIA
 :WEBKIT2-SANDBOXING :GTK-3-22 :GTK-3-20 :GTK-3-18 :GTK-3-16 :GTK-3-14
 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6 :GTK-3-4 :GTK :GDK-3-22 :GDK-3-20
 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12 :GDK-3-10 :GDK-3-8 :GDK-3-6 :GDK-3-4
 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF :GLIB-2-30 :GLIB-2-32 :GLIB-2-34
 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42 :GLIB-2-44 :GLIB-2-46 :GLIB-2-48
 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56 :GLIB-2-58 :GLIB :NYXT-UNSTABLE
 :NYXT-G38EA3234 :NYXT-2.1.1 :NYXT-2.1 :NYXT-2 :FSET-EXT-STRINGS
 :CUSTOM-HASH-TABLE-NATIVE :SWANK :PLUMP-UTF-32 :GLOBAL-VARS :DECLARE-TYPES
 :PARENSCRIPT :SBCL+SAFE-STANDARD-READTABLE :NAMED-READTABLES :LPARALLEL
 :21BIT-CHARS :CLOSER-MOP :CL-PPCRE-UNICODE :CL-UNICODE
 :CL-JSON-DOUBLE-FLOAT-IS-SUBSUMED :CL-JSON-SINGLE-FLOAT-IS-SUBSUMED :CL-PPCRE
 :CHUNGA :FLEXI-STREAMS :BORDEAUX-THREADS :LPARALLEL.WITH-CLTL2
 :LPARALLEL.WITH-CAS :LPARALLEL.WITH-STEALING-SCHEDULER :SPLIT-SEQUENCE
 CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64 CFFI-FEATURES:UNIX :CFFI
 CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP :FAST-IO-SV :FAST-IO
 :CL-JSON-CLOS :CL-JSON :SBCL-USES-SB-ROTATE-BYTE CHIPZ-SYSTEM:GRAY-STREAMS
 :THREAD-SUPPORT :ASDF3.3 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX
 :NON-BASE-CHARS-EXIST-P :ASDF-UNICODE :X86-64 :GENCGC :64-BIT :ANSI-CL
 :COMMON-LISP :ELF :IEEE-FLOATING-POINT :LINUX :LITTLE-ENDIAN
 :PACKAGE-LOCAL-NICKNAMES :SB-CORE-COMPRESSION :SB-LDB :SB-PACKAGE-LOCKS
 :SB-THREAD :SB-UNICODE :SBCL :UNIX)

ASDF version: 3.3.1
ASDF registries: (NYXT-SOURCE-REGISTRY ENVIRONMENT-SOURCE-REGISTRY)
Critical dependencies: (/home/anomalocaris/.cache/paru/clone/nyxt-browser-git/src/nyxt-browser/_build/cl-cffi-gtk/gtk/cl-cffi-gtk.asd
 /home/anomalocaris/.cache/paru/clone/nyxt-browser-git/src/nyxt-browser/_build/cl-gobject-introspection/cl-gobject-introspection.asd
 /home/anomalocaris/.cache/paru/clone/nyxt-browser-git/src/nyxt-browser/_build/cl-webkit/webkit2/cl-webkit2.asd)
```

  If you can't run `show-system-information`, try `nyxt --system-information` from
  a shell.  It this still does not work, please provide the following:
  - Nyxt version (from the `nyxt-version` command or `nyxt --version` from a shell):
  - Lisp implementation/version (if built from source):
  - Kernel name+version:
  - WebKitGTK+ | QtWebEngine version:

**Output when started from a shell**
```
<INFO> [18:58:48] Listening to socket "/run/user/1000/nyxt/nyxt.socket".
Nyxt version 2.1.1-1577-g38ea3234
<INFO> [18:58:48] Loading Lisp file "/home/anomalocaris/.config/nyxt/auto-config.lisp".
<INFO> [18:58:48] Loading Lisp file "/home/anomalocaris/.config/nyxt/init.lisp".
<INFO> [18:58:48] Loading history of 182 URLs from "/home/anomalocaris/.local/share/nyxt/history/default.lisp".
<INFO> [18:58:48] Not restoring session.
<INFO> [18:58:48] Loading "nyxt:dashboard".
<INFO> [18:58:48] Loading 3 bookmarks from "/home/anomalocaris/.local/share/nyxt/bookmarks.lisp".
<INFO> [18:58:49] Finished loading "nyxt:dashboard".
<INFO> [18:58:49] Deleting socket "/run/user/1000/nyxt/nyxt.socket".
```

**Comment by aartaka** [comment]
I can reproduce.

**Comment by aartaka** [comment]
It seems WebKit automatically accepts any link clicks it gets -- it does not even fire a `decide-policy` signal (that we hook into for redirections) for those. I'm afraind we can't do much here.

A potential way would be to re-load the URL of the buffer in `notify::uri` signal, but that's too late -- it usually fires when the page is already half-loaded, so no use in redirecting at this point. I wouldn't put the code for this in the browser core, but it should be possible to do in an extension -- `nyxt::on-signal-notify-uri` is easy to specify or extend, as it's a CLOS method.

Closing this, sorry for bad news :(
