### ISSUE TITLE
Bring more clarity and consistency into FFI methods

### ISSUE THREAD

**Issue by aartaka** [atlas-engineer/nyxt#2097]
There are several problems with our FFI methods:

# Inconsistent getters/setters

Two methods, side-by side in browser.lisp, lines 755-757
``` lisp
(define-ffi-generic ffi-buffer-user-agent (buffer &optional value))
(define-ffi-generic ffi-buffer-set-proxy (buffer &optional proxy-url ignore-hosts))
(define-ffi-generic ffi-buffer-get-proxy (buffer))
```
`ffi-buffer-user-agent` relies on the optional value to undertand whehter to behave as getter/setter, while `ffi-buffer-(set|get)-proxy` splits getter and setter into separate methods. This is inconsistent. We need to adopt just one style for such a case of get/set methods. Possible styles are:
- Optional args (one function to write, easy to use).
- Separate getters/setters (clear and maps well onto C/C++ renderers, but a lot of boilerplate).
- `setf` methods (idiomatic and (almost) zero-cost, yet wordy).

# Naming

Names like `ffi-buffer-enable-javascript-markup` and `ffi-buffer-auto-load-image` are directly inherited from WebKitGTK [WebKitSettings](https://webkitgtk.org/reference/webkit2gtk/stable/WebKitSettings.html), which is likely to get uncomfortable if we add another renderer. We should use uniform naming, like `ffi-buffer-javascript-markup` (without enable, simply the subject) or always use `-enable`. Matter of preference here (I prefer the former). This is also connected with getters/setters inconsistency.

# Lack of documentation

When one asks us where to look when implementing a new port, we usually point them at browser.lisp and at the list of methods therein. What we constantly forget pointing people at it is that there's almost no documentation for methods. We need to write clear documentation of what every method does, so that one trying to implement a port clearly understands what are the renderer-side analogues to what our methods do.

Thoughts?

**Comment by Ambrevar** [comment]
Good summary, thanks!

I prefer to use setf-methods, it's more idiomatic and less naming issues to deal with.

Also agreed with your `ffi-buffer-javascript-markup` proposal.  I suggest we put this rationale in writing in the file.

**Comment by Ambrevar** [comment]
Shall we move the defgenerics to a file other than `browser.lisp`?  Say `ffi.lisp` or `foreign-interface`?

**Comment by aartaka** [comment]
Yes!

**Comment by aartaka** [comment]
Maybe make it accept a `proxy` object instead? A high time we abstract all the informal and half-specified renderer communication into classes :D

**Comment by Ambrevar** [comment]
Good point.

Something else: shall we define the `nyxt/ffi` package and remove the `ffi-` prefix?

**Comment by Ambrevar** [comment]
Nearly done: #2263.
