### ISSUE TITLE
Another issue related to what nyxt saves on a disk

### ISSUE THREAD

**Issue by shamazmazum** [atlas-engineer/nyxt#2100]
Hi! This is directly related to #2084. Prior to `nfiles` I could control what is saved to disk by defining `expand-data-path` and/or `store` for my profile. For example, I could save bookmarks to disk, but no cookies and cache.

Now, I don't have any idea how to do this with `nfiles`. This is what I tried. My `init.lisp`:

~~~~
(define-class my-profile (nyxt-profile)
  ((nfiles:name "nyxt")
   (ephemeral-p t))
  (:export-class-name-p t)
  (:export-accessor-names-p t)
  (:accessor-name-transformer (class*:make-name-transformer name))
  (:documentation "Light version of nosave-profile"))

(setq *global-profile*
      (make-instance 'my-profile))

(defmethod nfiles:resolve ((profile my-profile)
                           (file cookies-file))
  #p"")

(define-configuration browser
  ((session-restore-prompt :never-restore)))

(define-configuration buffer
  ((search-always-auto-complete-p nil)))

(define-configuration web-buffer
  ((profile (make-instance 'my-profile))))

(define-configuration buffer
  ((override-map (let ((map (make-keymap "override-map")))
                   (define-key map
                     "C-x C-k" 'nyxt/web-mode:cut)))))

(define-configuration buffer
  ((default-modes (append '(nyxt/emacs-mode:emacs-mode
                            nyxt/reduce-tracking-mode:reduce-tracking-mode)
                          %slot-default%))))
~~~~

and also a patch to nyxt:

~~~~
diff --git a/source/renderer/gtk.lisp b/source/renderer/gtk.lisp
index 210228ba..ae6c9a9b 100644
--- a/source/renderer/gtk.lisp
+++ b/source/renderer/gtk.lisp
@@ -331,7 +331,7 @@ the same naming rules as above."
   (let ((internal-p (or (not buffer)
                         (internal-buffer-p buffer)))
         (ephemeral-p (or ephemeral-p
-                         (when buffer (typep (profile buffer) 'nosave-profile))
+                         (when buffer (ephemeral-p (profile buffer)))
                          (typep buffer 'nosave-buffer))))
     (make-instance (if ephemeral-p
                        'webkit-web-view-ephemeral
diff --git a/source/user-files.lisp b/source/user-files.lisp
index 32235bb5..79d576e6 100644
--- a/source/user-files.lisp
+++ b/source/user-files.lisp
@@ -6,7 +6,11 @@
 ;; We define our own 'default profile' (instead of using `nfiles:profile'
 ;; directly) so that we can specialize the methods
 (define-class nyxt-profile (nfiles:profile)
-  ((nfiles:name "nyxt"))
+  ((nfiles:name "nyxt")
+   (ephemeral-p
+    nil
+    :type          boolean
+    :documentation "Should we create ephemeral web views for buffers with this profile?"))
   (:export-class-name-p t)
   (:export-accessor-names-p t)
   (:accessor-name-transformer (class*:make-name-transformer name))
~~~~

Now I don't have cookies or cache saved, but I cannot open bookmarks, manual, help and so on (any URL which has `nyxt` scheme). I cannot understand why it's so.

Proposal: Make it possible to use different kinds of data profiles. It seems, now you can only choose between `nyxt-profile` and `nosave-profile` without much customisation. Or at least can you show me the right direction for solution of my problem? I want only to keep bookmarks on disk.

**Comment by shamazmazum** [comment]
Aha, I see why I cannot use commands like `list-bookmarks` in ephemeral-buffers. This functionality is disabled in `make-context` in `source/renderer/gtk.lisp`.

With [this](https://github.com/shamazmazum/nyxt/commit/66c268f63b73f3c796120398e9909ffa220b982b) commit I can disable cache&cookies. I don't understand yet how history works.

I can add now

~~~~
(setq *global-profile*
      (make-instance 'nyxt-profile :ephemeral-p t))
~~~~

to `init.lisp` to disable writing to disk.

**Comment by jmercouris** [comment]
@Ambrevar ? Shall we add information about how to do this in the manual?

**Comment by Ambrevar** [comment]
@shamazmazum Have you had a look at the readme of nfiles?  https://github.com/atlas-engineer/nfiles/
It should clarify some of your questions.

In short, if you want to _read_ but not write, you can simply specialize `nfiles:write-file` on `my-profile` to not do anything.

This would apply to everything.  Then if you want only some files to be written, say, bookmarks, then you can specialize `nfiles:write-file` against `my-profile` and `bookmarks-file` to write as usual.

Does that make sense?

Finally, you can set the `global-profile` to `nosave-profile` which should do what you want.
Except maybe for the bookmarks, but you can specialize `write-file` as mentioned above for `nosave-profile` and you should be good to go.

**Comment by shamazmazum** [comment]
@Ambrevar OK, I understand now how can I configure nfiles. But it seems that ephemeral contexts are not of much use. Look at [this commit](https://github.com/shamazmazum/nyxt/commit/66c268f63b73f3c796120398e9909ffa220b982b) more closely, please. Now schemes like `nyxt:` are not accessible if a web context is ephemeral. So you either get an ephemeral context (associated with `nosave-profile` or `nosave-buffer`) or can use bookmarks/history/anything else defined with `define-internal-page-command(-global)`. This seems quite unfair. I may want both! Should I send a PR like that commit?

**Comment by aartaka** [comment]
> @Ambrevar OK, I understand now how I can configure nfiles. But it seems that ephemeral contexts are not of much use. Look at [this commit](https://github.com/shamazmazum/nyxt/commit/66c268f63b73f3c796120398e9909ffa220b982b) more closely, please. Now schemes like `nyxt:` are not accessible if a web context is ephemeral. So you either get an ephemeral context (associated with `nosave-profile` or `nosave-buffer`) or can use bookmarks/history/anything else defined with `define-internal-page-command(-global)`. This seems quite unfair. I may want both! Should I send a PR like that commit?

a73c610cc70ef59f2b9832342498c423def7e091 should fix it, I guess :)

**Comment by shamazmazum** [comment]
Oh, my. This is just in time! Closing this issue, then

**Comment by Ambrevar** [comment]
Thanks Artyom!

Vasily, to clarify the issue with the `nyxt:` protocol in ephemeral
buffers has nothing to do with nfiles, although it may have been
introduced by a bad rebase.
