### ISSUE TITLE
File upload prompt is broken.

### ISSUE THREAD

**Issue by shamazmazum** [atlas-engineer/nyxt#2101]
When I try to upload a file I do not see any files in the prompter and get I lot of warnings in the terminal from where nyxt is started:

~~~~
Attributes of #P"/home/vasily/.wolf/" should be a non-dotted alist instead of (("Name"
   Attributes of #P"/home/vasily/.wolf/" should be a non-dotted alist instead of (("Name"
                                                                                          NIL)
                                                                                   NIL)
                                                                                   NIL)
"
                                                                                          NIL)
WARNING:
                                                                                         ("Ext
                                                                                         ("Extension"/

                                                                                        ("Extension"/                es/" shoul  be a non-dotted alist instead of (("Name"
                                                                                        ("Extension"/                es/" shoul  be a non-dotted alist instead of (("Name" 
~~~~

The bug is introduced in 4f639c50b489820235a0ace438c10aaf84a58fa5 and can be fixed by using the old method for `promter:object-attributes`:

~~~~
(defmethod prompter:object-attributes ((path pathname))
  `(("Path" ,(uiop:native-namestring path))))

#+nil
(defmethod prompter:object-attributes ((path pathname))
  `(("Name" ,(pathname-name path))
    ("Extension" ,(or (nfiles:pathname-type* path) ""))
    ("Directory" ,(uiop:native-namestring (nfiles:parent path)))))
~~~~

I can send a patch unless you have better solution.

**Comment by shamazmazum** [comment]
I think `(or (pathname-name path) "")` can work.

**Comment by aartaka** [comment]
> I think `(or (pathname-name path) "")` can work.

Yes, that sounds most reasonable. Maybe even use UNIX-y dot (`(or (pathname-name path) ".")`) so that directories are not just a confusing empty space?

**Comment by shamazmazum** [comment]
Thanks!

**Comment by shamazmazum** [comment]
I was too eager to close it. I have `~/Downloads/` directory and want to upload file from that directory. Unfortunatelly I cannot autocomplete `Downloads` as you can see on screenshots.

![20220214_07h28m31s_grim](https://user-images.githubusercontent.com/812069/153801586-e7aed769-3f94-4e5b-88b5-9d886e4023a5.png)
![20220214_07h28m37s_grim](https://user-images.githubusercontent.com/812069/153801594-318bca32-3e92-4c04-8072-5f104c646483.png)
![20220214_07h28m43s_grim](https://user-images.githubusercontent.com/812069/153801593-a15cd727-eb5d-46d6-ab4b-e95fa537a9f1.png)

Also tons of `/home/vasily/` seems bad. This can be avoided by defining

~~~~
(defmethod prompter:object-attributes ((path pathname))
  `(("Name" ,(or (pathname-name path) ""))
    ("Extension" ,(or (nfiles:pathname-type* path) ""))
    ("Directory" ,(uiop:native-namestring
			(if (uiop:directory-pathname-p path)
		   	path
		    	(nfiles:parent path))))))
~~~~

I'll send a PR if I can fix autocompletion.

P.S. I like the former version with just `Path` column ;)

**Comment by shamazmazum** [comment]
PR #2103 fixes this issue.

**Comment by jmercouris** [comment]
Merged, thank you!
