### ISSUE TITLE
Only search query suggestions for local domain

### ISSUE THREAD

**Issue by midgethoen** [atlas-engineer/nyxt#2107]
**Describe the bug**
When `set-url`ing a exact .local url there are only search query suggestions and no option to use the url. 

![image](https://user-images.githubusercontent.com/4599476/154067358-59a4f6c2-c2e9-4065-9923-9e6fe2214fa0.png)

![image](https://user-images.githubusercontent.com/4599476/154069229-3620a5d1-005f-41ef-83af-42995d3167bc.png)

when entering anything that is technically a valid url i expect to always have an option to use that url. As a new user im not sure how to visit this url at all right now...

**Precise recipe to reproduce the issue**
- invoke set-url
- enter a .local url (for instance: http://nextcloud.local)

**Information**
- OS name+version: ubuntu
- Graphics card and driver: nvidea
- Desktop environment / Window manager name+version: gnome
- How you installed Nyxt (Guix pack, package manager, build from source): apt
- Information from `show-system-information`:

Nyxt version: 2.2.4
Renderer version: GI-GTK
Operating system kernel: Linux 5.13.0-28-generic
Lisp implementation: SBCL 2.1.0.0.HEAD.1-46cb065 (Dynamic space size: 3221225472)
Features: (:WEBKIT2 :WEBKIT2-2.34 :WEBKIT2-PASTE-PLAINTEXT :WEBKIT2-TRACKING
 :WEBKIT2-MUTE :WEBKIT2-EMOJI :WEBKIT2-MEDIA :WEBKIT2-SANDBOXING :GTK-3-22
 :GTK-3-20 :GTK-3-18 :GTK-3-16 :GTK-3-14 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6
 :GTK-3-4 :GTK :GDK-3-22 :GDK-3-20 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12
 :GDK-3-10 :GDK-3-8 :GDK-3-6 :GDK-3-4 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF
 :GLIB-2-30 :GLIB-2-32 :GLIB-2-34 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42
 :GLIB-2-44 :GLIB-2-46 :GLIB-2-48 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56
 :GLIB-2-58 :GLIB :NYXT-2 :FSET-EXT-STRINGS :CUSTOM-HASH-TABLE-NATIVE :SWANK
 :PLUMP-UTF-32 :GLOBAL-VARS :DECLARE-TYPES :PARENSCRIPT :NAMED-READTABLES
 :LPARALLEL :21BIT-CHARS :CHUNGA :FLEXI-STREAMS :CLOSER-MOP :CL-PPCRE-UNICODE
 :CL-UNICODE :BORDEAUX-THREADS :LPARALLEL.WITH-CLTL2 :LPARALLEL.WITH-CAS
 :LPARALLEL.WITH-STEALING-SCHEDULER :SPLIT-SEQUENCE CHIPZ-SYSTEM:GRAY-STREAMS
 :FAST-IO-SV :FAST-IO :SBCL-USES-SB-ROTATE-BYTE :CL-JSON-CLOS :CL-JSON
 :THREAD-SUPPORT :CL-PPCRE CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64
 CFFI-FEATURES:UNIX :CFFI CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP
 :ASDF3.3 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX
 :NON-BASE-CHARS-EXIST-P :ASDF-UNICODE :X86-64 :GENCGC :64-BIT :ANSI-CL
 :COMMON-LISP :ELF :IEEE-FLOATING-POINT :LINUX :LITTLE-ENDIAN
 :PACKAGE-LOCAL-NICKNAMES :SB-CORE-COMPRESSION :SB-LDB :SB-PACKAGE-LOCKS
 :SB-THREAD :SB-UNICODE :SBCL :UNIX)

ASDF version: 3.3.4
ASDF registries: (NYXT-SOURCE-REGISTRY ENVIRONMENT-SOURCE-REGISTRY USER-SOURCE-REGISTRY
                      USER-SOURCE-REGISTRY-DIRECTORY
                      DEFAULT-USER-SOURCE-REGISTRY SYSTEM-SOURCE-REGISTRY
                      SYSTEM-SOURCE-REGISTRY-DIRECTORY
                      DEFAULT-SYSTEM-SOURCE-REGISTRY)
Critical dependencies: (/home/runner/work/nyxt/nyxt/_build/cl-cffi-gtk/gtk/cl-cffi-gtk.asd
 /home/runner/work/nyxt/nyxt/_build/cl-gobject-introspection/cl-gobject-introspection.asd
 /home/runner/work/nyxt/nyxt/_build/cl-webkit/webkit2/cl-webkit2.asd)

**Comment by midgethoen** [comment]
as a workaround tried to open the url via the os using xdg-open. to my surprise nyxt is unable to open this url at all.

![image](https://user-images.githubusercontent.com/4599476/154070982-53c35f78-a9f1-45a6-9563-9f7e8ba1e0aa.png)

![image](https://user-images.githubusercontent.com/4599476/154071183-daaad9a5-4412-4fc5-9905-bed751f5f583.png)

another browser on the same machine for completeness:
![image](https://user-images.githubusercontent.com/4599476/154071442-ce301641-b5fc-4728-8dba-7e0f2e9dab05.png)

**Comment by Ambrevar** [comment]
Indeed, `valid-url-p` does not know about the `.local` TLD.

https://en.wikipedia.org/wiki/.local

@aartaka What do you think, shall we add it?

**Comment by Ambrevar** [comment]
As well as the other TLDs listed here:
https://en.wikipedia.org/wiki/Special-use_domain_name

- invalid
- test
- localhost
- example
- onion (cl-tld supports this one)

**Comment by Ambrevar** [comment]
I've opened an issue about it: https://github.com/lu4nx/cl-tld/issues/2

**Comment by aartaka** [comment]
Thanks, Pieere! It should indeed be there :)

**Comment by Ambrevar** [comment]
Fixed with 759d86afd85af9a85560af66cafd17fb3c02ed85.
