### ISSUE TITLE
Big RAM utilization

### ISSUE THREAD

**Issue by kovalev94** [atlas-engineer/nyxt#2108]
**Describe the bug**
Big ram usage when using nyxt browser. Even if one buffer is open.
**Precise recipe to reproduce the issue**

I used htop to monitor cpu usage.
Before test(no browser opened) i have 392Mib used RAM.

I did 2 tests for 2 browsers(Nyxt vs Luakit, because both browsers use webkitgtk)

First test is emulating my daily using my local IPAM/DCIM system provided by "Nautobot" site.
To emulate this I used demo "Nautobot" instance(demo.nautobot.com).

- Open a browser(Do not restore session). At this step i have 703Mib used RAM.
- go to google.com and search "Nautobot demo" (in current buffer).
- go to demo.nautobot.com, log in, and go to devices link. (in current buffer). At this step i have 825Mib used RAM.
- follow some different links and open them in new buffers, until your buffers count = 28.
  (I have seen #1129 and @Ambrevar provide example with 28 buffers that uses < 700Mib). At this step i have 3.45Gib used RAM.
RAM usage compared to Luakit:
479 Mib- one tab with luakit home page.
539Mib - one tab with nautobot devices page.
1,63Gib with 28 tab with nautobot pages.

Second test is emulating simple web serfing.

- Open a browser(Do not restore session).
- go to google.com and search "Some important stuff" (in current buffer).
- go to trendingus.com and follow some different links and open them in new buffers, until your buffers count = 28.
  At this step i have 4.30Gib used RAM.
RAM usage compared to Luakit:
2.20Gib with 28 tabs.

**Information**
- OS name+version:
GNU Guix SD:
```
kovalev@mirage ~$ guix --version
guix (GNU Guix) 0
Copyright (C) 2022 the Guix authors
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```
Linux kernel:
```
kovalev@mirage ~$ uname -r
5.16.8
```
- Graphics card and driver:
```
00:02.0 VGA compatible controller: Intel Corporation UHD Graphics (rev 02)
	DeviceName: Onboard IGD
	Subsystem: Hewlett-Packard Company Device 869d
	Kernel driver in use: i915
	Kernel modules: i915
```
- Desktop environment / Window manager name+version:
Herbstluftwm:
```
kovalev@mirage ~$ herbstluftwm --version
herbstluftwm 0.9.3
Copyright (c) 2011-2021 Thorsten Wißmann
Released under the Simplified BSD License
xrandr support: on
xinerama support: on
```
- How you installed Nyxt (Guix pack, package manager, build from source):
`guix package install nyxt`
- Information from `show-system-information`:
```
kovalev@mirage ~$ nyxt --system-information
Nyxt version: 2.2.4
Renderer version: GI-GTK
Operating system kernel: Linux 5.16.8
Lisp implementation: SBCL 2.1.9 (Dynamic space size: 3221225472)
Features: (:WEBKIT2 :WEBKIT2-2.34 :WEBKIT2-CORS-ALLOWLIST :WEBKIT2-PASTE-PLAINTEXT
 :WEBKIT2-TRACKING :WEBKIT2-MUTE :WEBKIT2-EMOJI :WEBKIT2-MEDIA
 :WEBKIT2-SANDBOXING :GTK-3-22 :GTK-3-20 :GTK-3-18 :GTK-3-16 :GTK-3-14
 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6 :GTK-3-4 :GTK :GDK-3-22 :GDK-3-20
 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12 :GDK-3-10 :GDK-3-8 :GDK-3-6 :GDK-3-4
 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF :GLIB-2-30 :GLIB-2-32 :GLIB-2-34
 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42 :GLIB-2-44 :GLIB-2-46 :GLIB-2-48
 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56 :GLIB-2-58 :GLIB :NYXT-2
 :FSET-EXT-STRINGS :CUSTOM-HASH-TABLE-NATIVE :SWANK :PLUMP-UTF-32 :GLOBAL-VARS
 :DECLARE-TYPES :PARENSCRIPT :NAMED-READTABLES :LPARALLEL :21BIT-CHARS :CHUNGA
 :FLEXI-STREAMS :CLOSER-MOP :CL-PPCRE-UNICODE :CL-UNICODE :CL-PPCRE
 :BORDEAUX-THREADS :LPARALLEL.WITH-CLTL2 :LPARALLEL.WITH-CAS
 :LPARALLEL.WITH-STEALING-SCHEDULER :SPLIT-SEQUENCE CHIPZ-SYSTEM:GRAY-STREAMS
 CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64 CFFI-FEATURES:UNIX :CFFI
 CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP :FAST-IO-SV :FAST-IO
 :SBCL-USES-SB-ROTATE-BYTE :CL-JSON-CLOS :CL-JSON :THREAD-SUPPORT :ASDF3.3
 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX :NON-BASE-CHARS-EXIST-P
 :ASDF-UNICODE :X86-64 :GENCGC :64-BIT :ANSI-CL :COMMON-LISP :ELF
 :IEEE-FLOATING-POINT :LINUX :LITTLE-ENDIAN :PACKAGE-LOCAL-NICKNAMES
 :SB-CORE-COMPRESSION :SB-LDB :SB-PACKAGE-LOCKS :SB-THREAD :SB-UNICODE :SBCL
 :UNIX)

ASDF version: 3.3.5
ASDF registries: (NYXT-SOURCE-REGISTRY ENVIRONMENT-SOURCE-REGISTRY USER-SOURCE-REGISTRY
                      USER-SOURCE-REGISTRY-DIRECTORY
                      DEFAULT-USER-SOURCE-REGISTRY SYSTEM-SOURCE-REGISTRY
                      SYSTEM-SOURCE-REGISTRY-DIRECTORY
                      DEFAULT-SYSTEM-SOURCE-REGISTRY)
Critical dependencies: (/gnu/store/ivf4gksxdn5r1dcglsx5lkrcg18y9a1h-sbcl-cl-cffi-gtk-0.11.2-2.e9a46df/share/common-lisp/sbcl/cl-cffi-gtk/gtk/cl-cffi-gtk.asd
 /gnu/store/4nrlqby4j2zh0x08y5zd2xcr80rmvs27-sbcl-cl-gobject-introspection-0.3-1.d0136c8/share/common-lisp/sbcl/cl-gobject-introspection/cl-gobject-introspection.asd
 /gnu/store/r4f57f39r61ygb1fm6cy2fpby4vwyh0a-sbcl-cl-webkit-3.5.0/share/common-lisp/sbcl/cl-webkit/webkit2/cl-webkit2.asd)
```
P.S. Thanks for your great job. I'm really excited with Nyxt browser. I think it can be the best browser for me.
Just want to use it without memory overhead)
P.P.S. Also i have some render issues(some freezes when scrolling) but I have them in both browsers(Luakit and Nyxt). Maybe someone who also use guix know - how can I fix it?

**Comment by Ambrevar** [comment]
Thanks for the compliments, glad you like Nyxt!

The rendering issue is probably due to an issue with your graphics card driver.  Try using a different kernel see if that changes anything.

I'm not familiar with https://demo.nautobot.com/.  There is no `devices` link there.  Can you expand?

To be honest, Nyxt memory management is not great at this point, but there is a lot of room for improvement, just gotta work on it! 
Anyone else experiencing high RAM usage?

**Comment by kovalev94** [comment]
I have had rendering issues since 5.14, but thanks, i will check graphics direction.
https://demo.nautobot.com/dcim/devices/ - this is a devices link, it should be available after you log in(login:demo, password: nautobot)
@Ambrevar 
Your example (from #1129) of memory usage is pretty acceptable. I will be very happy if I see such figures.
Can you reproduce my tests?

**Comment by Kabouik** [comment]
> Anyone else experiencing high RAM usage?

I do, but it seems to be highly buffer-dependent; same for CPU use. I don't often get to 100% memory use so I don't monitor it very closely. However, on my mobile device where I have only 6GB of RAM, I noticed a few months ago that Nyxt started to saturate RAM use more often than it used to, to the point that the OS itself becomes unresponsive. I don't know if that is because I now have more demanding buffers in my session, or because of this 2.2.4 change: "Nyxt is compiled with SBCL set to use a dynamic-space-size of at least 3GiB."

**Comment by Ambrevar** [comment]
I'd be surprised that dynamic-space-size is the culprit here.  If you know how to build Nyxt, could you try by setting the space size to a lower value and compare?

For what it's worth, more recent versions of Nyxt should be less memory intensive since we've fixed a bunch of unfreed objects.

That said, it's also possible the updates of WebKitGTK are _more_ memory intensive.

So the first thing we need to do is figure out what's the culprit here exactly.

**Comment by Ambrevar** [comment]
@kovalev94 I can confirm that each buffer of an nautobot page takes about 100 MiB, which is ridiculous!

Enabling no-script-mode does no help much.

**Comment by Ambrevar** [comment]
I can reproduce this issue with Epiphany.  WebKitGTK is at fault here.

**Comment by Ambrevar** [comment]
I can also reproduce with Luakit.  @kovalev94 are you sure about your Luakit test?  Is Luakit installed the same way Nyxt is, e.g. from Guix?  Are they using the same WebKitGTK?

**Comment by kovalev94** [comment]
> I can also reproduce with Luakit. @kovalev94 are you sure about your Luakit test? Is Luakit installed the same way Nyxt is, e.g. from Guix? Are they using the same WebKitGTK?
I don't find version in guix package definition(web-browsers.scm), but both nyxt and luakit have webkitgtk without version in their inputs.
Therefore. Here is output from `luakit --version`
```
kovalev@mirage ~$ luakit --version
luakit 2.3
  built with webkit 2.34.6 (installed version: 2.34.6)
```
Yes, I have installed luakit in the same way `guix install luakit`






> @kovalev94 I can confirm that each buffer of an nautobot page takes about 100 MiB, which is ridiculous!
> 
> Enabling no-script-mode does no help much.

For mor accuracy, I did another test. Both luakit and nyxt with 10 tabs/buffers with nautobot devices page.
Luakit:
337 Mib - before opening
422 Mib - One tab with luakit(empty tab also have the same size)
480 Mib - One tab with nautobot devices page
985 Mib - 10 tabs with nautobot devices page

Nyxt: 
343 Mib - before opening
694 Mib - one empty buffer
818 Mib - one buffer with nautobot devices page
2.12 Gib - 10 buffers with nautobot devices page
Also, I think there is an issue with memory freeing - because after closing all buffers, memory utilization is 1.31 Gib(There is no such behavior in Luakit).

As I understand we should to do the following calculations for buffer/tab size: 
Luakit: (985-422)/10 = 56.3 Mib
Nyxt: (2.12*1024- 694)/10 = 147.688 Mib
And the following calculations for browser memory footprint: 
Luakit: 422-337=85 Mib
Nyxt: 694-343=341 Mib

@Ambrevar Can you share your results?

**Comment by Ambrevar** [comment]
I will, but first can you report as precisely as possible how you
measure the memory use?  Also _which_ memory are you measuring?
(resident, virtual?)

**Comment by Ambrevar** [comment]
Also are you using an init file?  If so, try with `nyxt -I`.

**Comment by Ambrevar** [comment]
On my machine:

- Nyxt 2.2.4 takes about 1.3 GiB of memory for 10 nautobot buffers.  `master` eats slightly less then 1 GiB.
- Memory frees alright, but 2.2.4 is worse than `master`.

Can you try `master` see if that helps?  (It's trivial to build it with `build-scripts/nyxt.scm` if you have Guix.)

**Comment by bubbleguuum** [comment]
On current openSUSE Tumbleweed, latest Git nyxt, running `nyxt -I` 10 nautobot buffers results in 477MB RSS (or 412MB PSS) according to `smem`.
It uses WebKitGTK  2.34.6.

**Comment by jmercouris** [comment]
That seems to be a significant improvement!

**Comment by kovalev94** [comment]
> I will, but first can you report as precisely as possible how you measure the memory use? Also _which_ memory are you measuring? (resident, virtual?)

I use htop for memory checking, mem bar at the top.
[https://postimg.cc/mhwyRrNw](url)

**Comment by kovalev94** [comment]
> On my machine:
> 
> * Nyxt 2.2.4 takes about 1.3 GiB of memory for 10 nautobot buffers.  `master` eats slightly less then 1 GiB.
> * Memory frees alright, but 2.2.4 is worse than `master`.
> 
> Can you try `master` see if that helps? (It's trivial to build it with `build-scripts/nyxt.scm` if you have Guix.)

Sorry for a long answer. I'll try it this week.

**Comment by aadcg** [comment]
Stale.
