### ISSUE TITLE
A better manual on installing systemwide.

### ISSUE THREAD

**Issue by lockywolf** [atlas-engineer/nyxt#2109]
**Is your feature request related to a problem? Please describe.**

I would like to make a nyxt.SlackBuild for Slackware 15.0

**Describe the solution you'd like**
Provide a manual how to install nyxt into a dedicated directory for further packaging.

**Describe alternatives you've considered**
So far I have tried to follow Arch's PKGBUILD: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=nyxt-browser-git

It basically amounts to
```
make all
make install PREFIX=/usr DESTIDIR=$PKG
```
This approach seem to be failing in my case. The `make install` command is generating a tree withe a `nyxt` binary, but that binary starts an sbcl interpreter:

```
* (LIST-ALL-PACKAGES) 
(#<PACKAGE "COMMON-LISP"> #<PACKAGE "SB-SYS"> #<PACKAGE "SB-DEBUG">
 #<PACKAGE "SB-X86-64-ASM"> #<PACKAGE "SB-C"> #<PACKAGE "SB-WALKER">
 #<PACKAGE "SB-KERNEL"> #<PACKAGE "SB-APROF"> #<PACKAGE "SB-IMPL">
 #<PACKAGE "SB-UNIX"> #<PACKAGE "SB-GRAY"> #<PACKAGE "SB-PROFILE">
 #<PACKAGE "SB-PRETTY"> #<PACKAGE "SB-ALIEN"> #<PACKAGE "SB-SEQUENCE">
 #<PACKAGE "SB-FASL"> #<PACKAGE "SB-RBTREE"> #<PACKAGE "SB-ASSEM">
 #<PACKAGE "COMMON-LISP-USER"> #<PACKAGE "SB-DISASSEM"> #<PACKAGE "SB-EVAL">
 #<PACKAGE "SB-PCL"> #<PACKAGE "SB-LOCKLESS"> #<PACKAGE "SB-THREAD">
 #<PACKAGE "SB-MOP"> #<PACKAGE "SB-BIGNUM"> #<PACKAGE "SB-FORMAT">
 #<PACKAGE "SB-VM"> #<PACKAGE "SB-LOOP"> #<PACKAGE "SB-REGALLOC">
 #<PACKAGE "SB-INT"> #<PACKAGE "SB-EXT"> #<PACKAGE "SB-UNICODE">
 #<PACKAGE "SB-ALIEN-INTERNALS"> #<PACKAGE "SB-DI"> #<PACKAGE "KEYWORD">)
```

The "real" nyxt executable, when run as `nyxt --eval '(LIST-ALL-PACKAGES)'`, print many more packages.

**Comment by Ambrevar** [comment]
Can you share your Slack recipe?

> The "real" nyxt executable, when run as nyxt --eval '(LIST-ALL-PACKAGES)', print many more packages.

What do you mean?

Why did you tag this with `feature`?  Looks more like a `build` issue, isn't it?

**Comment by Ambrevar** [comment]
I think I know what's going on: Slack may be auto-compressing the executable.  You must disable ELF compression, it breaks SBCL binaries.

**Comment by lockywolf** [comment]
>Why did you tag this with feature? Looks more like a build issue, isn't it?

There is no "build" issue template, there are only "bug", "feature", and "security vulnerability".

>What do you mean?

Well, I literally mean that I have just ran `nyxt --eval '(LIST-ALL-PACKAGES)'` with two different nyxt binaries, and compared the outputs.

>I think I know what's going on: Slack may be auto-compressing the executable. You must disable ELF compression, it breaks SBCL binaries.

That is it, actually. The line that broke the binary was:

```
find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF \
  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true
```

Apparently, "unneeded" is not that unneeded. :)
