### ISSUE TITLE
Support using hardware security keys with KeePassXC

### ISSUE THREAD

**Issue by Anomalocaridid** [atlas-engineer/nyxt#2111]
**Is your feature request related to a problem? Please describe.**
I use a hardware security key with my KeePassXC database. However, I cannot seem to open it using Nyxt's password manager commands. Instead, I am prompted for a password file, which I do not have set on my database.

**Describe the solution you'd like**
I would like to be able to use my hardware security key to open my KeePassXC database so that I can take advantage of Nyxt's KeePassXC integration.

**Describe alternatives you've considered**
I could remove the security key from my KeepassXC database, but I would like to avoid that.
I could just manually open KeepassXC and manually copy-paste login information, which I currently do, but this is inconvenient.

**Additional context**
No additional context.

**Comment by Ambrevar** [comment]
Duplicate of #495 ?

**Comment by hendursaga** [comment]
@Ambrevar I'm not entirely sure it's a duplicate - I haven't quite set-up KeePassXC with my new keys yet, but I believe they're meaning, when Nyxt shells out to KeePassXC and then it needs a security key, to somehow let the latter deal with that side of things. Thus, this doesn't have anything to do with, say, WebAuthn.

**Comment by Anomalocaridid** [comment]
@hendursaga Yeah that's exactly what I meant.

**Comment by Anomalocaridid** [comment]
It looks like to use security keys with keypassxc's cli interface, `keepass-cli`, you just need to pass either `-y #` or `--yubikey #`, where `#` is the number of the yubikey slot to use.

**Comment by aartaka** [comment]
@Anomalocaridid, just a small set of questions before I get to implementing this change: 
- Is Yubikey replacing the master password or is it added on top? 
- Is the hierarchy of `master-password -> master-password + key-file OR master-password + yubikey -> master-password + key-file + yubikey` correct, or can something like `key-file + yubikey` happen?

The tutorials I read are extremely vague on these point, and I need to understand it to properly implement DB lock checking when using Yubikey. I'm implying you have a Yubikey and can check or understand the use-case better than I do :P Feel free to ignore my questions if I'm mistaken.

**Comment by Anomalocaridid** [comment]
@aartaka, you are correct that I have a Yubikey. I did a quick check for both of your questions.

- Yubikey is added on top, but you can have a yubikey replace it instead if you want.
- You can do `key-file + yubikey`.

I also confirmed you need at least one encryption key, so you can't create a database without either a password, key file, yubikey, or some combination thereof.
