### ISSUE TITLE
Bring more contrast into the default color scheme

### ISSUE THREAD

**Issue by aartaka** [atlas-engineer/nyxt#2115]
# Analysis

Right now, based on the results of [color contrast checking](https://webaim.org/resources/contrastchecker/) our default theme, one can find _a lot_ of not-contrasting-enough colors. This poses comprehensibility problems [that we encounter already](https://github.com/atlas-engineer/nyxt/pull/2099#issuecomment-1041457822). Constrast values:
```
text+primary = AAA
background+primary = fail
text+secondary = AA
background+tertiary = AA, but only for large text and graphics
text+quaternary = AAA

accent+text = fail
accent+background = AAA
accent+primary = AA, but only for large text and graphics
accent+secondary = fail
accent+tertiary = fail
accent+quaternary = fail
```

# Plan
The contrast of the text/background with primary/secondary/tertiary/quaternary colors we should fix, as 
- We commit to it in the `theme` documentation.
- It's much easier on the eyes this way.

Accent color's I'm not that certain about fixing. It's implied to stand out hue-wise, so contrast issues should be mostly ruled our given its brightness and hue. But there should be some other precautions for e.g., color-blind people and monochrome screens. What Trello (for instance) does in this case is [using colors+geometric patterns](https://wearecolorblind.com/examples/trello-colorblind-friendly-mode/).

# Suggestions:
Make the primary color lighter. I suggest using `rgb(100,100,100)` as it has a good contrast with backgroud color and a bearable contrast with the text color. We mostly use primary with background color (think buttons and structural elements, so should be no harm leaning more to constrasting background first.

Make tertiary color a bit darker. A value of `rgb(115, 115, 115)` works well here. However, it's too close to secondary color. How about moving secondary color up a bit to something like `rgb(150, 150, 150)`? This swaps the colors, so maybe we should just change the value/documentation of `theme` slots in this case?

Am I over-engineering here?

EDIT: Add link to Trello example, clarify.

**Comment by Ambrevar** [comment]
Sounds good to me!

**Comment by aartaka** [comment]
#2099 should've fixed it.
