### ISSUE TITLE
describe-variable should allow setting values and slot values

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#2120]
For instance, run `describe-variable` on `*browser*`.  Wouldn't it be nice if we could set `remote-execution-p` from there?

Of course, we could also break anything :)  But since we have a REPL, we can break anything from the browser itself anyways.

**Comment by aartaka** [comment]
Yes, that sounds cool!

**Comment by aartaka** [comment]
Should be done with 8482594960cdcec1399d68817f3d89d26cd583d1 and c088e28fbc63c570f6d0b7cdc5d9110e1a5bf38a. I just set `*browser*` to `nil` and had a lot of fun ＼(^▽^＠)ノ

**Comment by jmercouris** [comment]
Thanks so much again Artyom :-)
