### ISSUE TITLE
Leverage existing JavaScript libraries

### ISSUE THREAD

**Issue by alexherbo2** [atlas-engineer/nyxt#213]
It could be cool to be able to source JavaScript and CSS into the web pages from the configuration file, similarly to the [content scripts].

[Content Scripts]: https://developer.chrome.com/extensions/content_scripts

**Comment by alexanderbarbosa** [comment]
Dark theme :D

**Comment by aartaka** [comment]
This should be possible with the addition of user scripts, as they allow re-using existing JS libraries.

**Comment by Ambrevar** [comment]
To clarify, it's possible now starting from `3-pre-release-1`.
