### ISSUE TITLE
Use Pseudo XDG Directories That Follow the XDG Naming Scheme

### ISSUE THREAD

**Issue by FOSSilizedDaemon** [atlas-engineer/nyxt#2131]
**Is your feature request related to a problem? Please describe.**

Currently when looking for a user set download directory `nyxt` checks for `XDG_DOWNLOAD_DIR`. This directory naming scheme does not follow the XDG naming scheme and therefore really stands out. 

**Describe the solution you'd like**

I suggest that this project move to `XDG_DOWNLOAD_HOME` as it follows the XDG naming scheme. Additionally, I suggest that any directories being checked anywhere also use XDG directories such as `XDG_DATA_HOME`.

**Comment by Ambrevar** [comment]
According to Freedesktop (https://freedesktop.org/wiki/Software/xdg-user-dirs/), it's indeed `XDG_DOWNLOAD_DIR`.

The other directories / files used by Nyxt follow the XDG standard.  If you noticed a case where it does not, please share a recipe :)

**Comment by FOSSilizedDaemon** [comment]
Oh I had no idea they named it that my bad! I shall keep an eye out :)

**Comment by Ambrevar** [comment]
No problem, feel free to reopen if there is anything else.
