### ISSUE TITLE
C-x doesn't work on Mac

### ISSUE THREAD

**Issue by carkat** [atlas-engineer/nyxt#2132]
I'm on MacOS, just got nyxt installed, C-x does not work. No combination of Ctrl, option, command, shift, either singularly, or in combination opens the command menu. 

M-l does work to follow links etc, and I'm not sure how to start modifying the behavior if I can't open the command menu to start looking around.  

Also curious as to why the key is C-x and not M-x by default, since M-x is the Emacs default for opening the command menu?

EDIT:

Changed to VI mode does what I expect, but the documentation for opening the command mode by default without changing the input modes is not correct.

**Comment by Nselm** [comment]
It seems like you have not enabled emacs-mode. If I remember correctly, cua-mode is the default, in which case you execute execute-command with C-Space. If you want different keybindings, change your mode to emacs-mode, in which case M-x works perfectly fine. Take a look at Keybinding configuration here: https://nyxt.atlas.engineer/documentation.

**Comment by aartaka** [comment]
> Changed to VI mode does what I expect, but the documentation for opening the command mode by default without changing the input modes is not correct.

Can you clarify (or open another issue even) what you mean there? A recipe to reproduce, maybe?

**Comment by aartaka** [comment]
Closing this. The documentation is dependent on the input mode you're using, and this is a convenient feature. The start page has reference to both manual and common setting to quickly set up the necesary bindings.
