### ISSUE TITLE
Panel buffers not working

### ISSUE THREAD

**Issue by pdelfino** [atlas-engineer/nyxt#2142]
**Describe the bug**
Command `bookmarks-panel` does not work. The message area keeps echoing "loading bookmark-panel" but nothing is loaded, even though **there is bookmark data** to be loaded. A white rectangle for the panel buffer space is loaded, but it is empty. See the picture.

![Screenshot from 2022-03-11 15-41-15](https://user-images.githubusercontent.com/7698207/157931916-56e719f0-30ea-4b43-8814-467d7beb08c3.png)

**Precise recipe to reproduce the issue**
0 - Have some pages already bookmarked
1 - Run Nyxt from source on commit id `773ac8a0`
2 - execute command `list-bookmarks`, see the data
3 - now, execute command `bookmarks-panel`
4 -  a white rectangle empty of content will appear on the left corner of the Nyxt's UI

Obs.:  Similar problems also happen to  `buffers-panel` and `headings-panel`. It seems to be related to panel buffers in general - not bookmarks panel in particular.

For website-specific issues:
Can you reproduce this issue with Epiphany / GNOME Web (https://wiki.gnome.org/Apps/Web)?
Not applicable

**Information**
- OS name+version: NixOS  21.05. You can see my NixOS config file [here](https://github.com/pdelfino/my-nixos-config/blob/main/configuration.nix). 

- Graphics card and driver:
product: Iris Plus Graphics 640
configuration: driver=i915 latency=0

- Desktop environment / Window manager name+version: GNOME 40.1.0

- Window System: Wayland

- How you installed Nyxt (Guix pack, package manager, build from source): source

- Information from `show-system-information`:
To execute `show-system-information`it was necessary to, first, `quit` Nyxt and then `NYXT> (start)` it again

```
Nyxt version: 2.1.1-1818-g773ac8a0
Renderer version: GI-GTK
Operating system kernel: Linux 5.10.94
Lisp implementation: SBCL 2.1.9.nixos (Dynamic space size: 1073741824)
Features: (:WEBKIT2 :WEBKIT2-2.34 :WEBKIT2-CORS-ALLOWLIST :WEBKIT2-PASTE-PLAINTEXT
 :WEBKIT2-TRACKING :WEBKIT2-MUTE :WEBKIT2-EMOJI :WEBKIT2-MEDIA
 :WEBKIT2-SANDBOXING :GTK-3-22 :GTK-3-20 :GTK-3-18 :GTK-3-16 :GTK-3-14
 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6 :GTK-3-4 :GTK :GDK-3-22 :GDK-3-20
 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12 :GDK-3-10 :GDK-3-8 :GDK-3-6 :GDK-3-4
 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF :GLIB-2-30 :GLIB-2-32 :GLIB-2-34
 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42 :GLIB-2-44 :GLIB-2-46 :GLIB-2-48
 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56 :GLIB-2-58 :GLIB :NYXT-UNSTABLE
 :NYXT-G773AC8A0 :NYXT-2.1.1 :NYXT-2.1 :NYXT-2 :FSET-EXT-STRINGS
 :CUSTOM-HASH-TABLE-NATIVE :PLUMP-UTF-32 :PARENSCRIPT :GLOBAL-VARS
 :DECLARE-TYPES :NAMED-READTABLES :LPARALLEL :21BIT-CHARS :CLOSER-MOP
 :CL-PPCRE-UNICODE :CL-UNICODE :CL-PPCRE :CHUNGA :FLEXI-STREAMS
 :BORDEAUX-THREADS :LPARALLEL.WITH-CLTL2 :LPARALLEL.WITH-CAS
 :LPARALLEL.WITH-STEALING-SCHEDULER :SPLIT-SEQUENCE
 CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64 CFFI-FEATURES:UNIX :CFFI
 CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP :FAST-IO-SV :FAST-IO
 :ASDF-SYSTEM-CONNECTIONS :CL-JSON-CLOS :CL-JSON :SBCL-USES-SB-ROTATE-BYTE
 CHIPZ-SYSTEM:GRAY-STREAMS :THREAD-SUPPORT :SWANK :QUICKLISP :ASDF3.3 :ASDF3.2
 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX :NON-BASE-CHARS-EXIST-P :ASDF-UNICODE
 :X86-64 :GENCGC :64-BIT :ANSI-CL :COMMON-LISP :ELF :IEEE-FLOATING-POINT :LINUX
 :LITTLE-ENDIAN :PACKAGE-LOCAL-NICKNAMES :SB-LDB :SB-PACKAGE-LOCKS :SB-THREAD
 :SB-UNICODE :SBCL :UNIX)

ASDF version: 3.3.1
ASDF registries: (NYXT-SOURCE-REGISTRY ENVIRONMENT-SOURCE-REGISTRY USER-SOURCE-REGISTRY
                      USER-SOURCE-REGISTRY-DIRECTORY
                      DEFAULT-USER-SOURCE-REGISTRY SYSTEM-SOURCE-REGISTRY
                      SYSTEM-SOURCE-REGISTRY-DIRECTORY
                      DEFAULT-SYSTEM-SOURCE-REGISTRY)
Critical dependencies: (/home/pedro/quicklisp/dists/quicklisp/software/cl-cffi-gtk-20201220-git/gtk/cl-cffi-gtk.asd
 /home/pedro/quicklisp/dists/quicklisp/software/cl-gobject-introspection-20210124-git/cl-gobject-introspection.asd
 /home/pedro/projects/cl-webkit/webkit2/cl-webkit2.asd)

Quicklisp dist version: 2021-10-21
Quicklisp client version: 2021-02-13
Local project directories: (/home/pedro/quicklisp/local-projects/)
Critical dependencies(#<SYSTEM cl-cffi-gtk / cl-cffi-gtk-20201220-git / quicklisp 2021-10-21>
 #<SYSTEM cl-gobject-introspection / cl-gobject-introspection-20210124-git / quicklisp 2021-10-21>
 #<SYSTEM cl-webkit2 / cl-webkit-20211020-git / quicklisp 2021-10-21>)

```

**Output when started from a shell**

I started Nyxt from source

```lisp
; SLIME 2.26.1
CL-USER> (ql:quickload :nyxt/gi-gtk)
To load "nyxt/gi-gtk":
  Load 1 ASDF system:
    nyxt/gi-gtk
; Loading "nyxt/gi-gtk"
............................................
(:NYXT/GI-GTK)
CL-USER> (in-package :nyxt)
#<PACKAGE "NYXT">
NYXT> (start)
<INFO> [15:33:52] Listening to socket #P"/run/user/1000/nyxt/nyxt.socket".
Nyxt version 2.1.1-1818-g773ac8a0
<INFO> [15:33:52] Loading Lisp file #P"/home/pedro/.config/nyxt/auto-config.lisp".
<INFO> [15:33:52] Loading Lisp file #P"/home/pedro/.config/nyxt/init.lisp".
NIL
<INFO> [15:33:53] Loading #P"/home/pedro/.local/share/nyxt/history/default.lisp".
```

**Comment by aartaka** [comment]
Huh, something broke panel-buffer-specific internal pages 🤔 

I want to blame #2050, but that's a premature guess. Will try to find the cause tomorrow!

**Comment by pdelfino** [comment]
> I want to blame #2050, but that's a premature guess. Will try to find the cause tomorrow!
I almost wrote that! :laughing:

**Comment by aartaka** [comment]
No, it was my mistake when doing internal schemes :D

**Comment by jmercouris** [comment]
Thanks for the fix Artyom :-)
