### ISSUE TITLE
Nyxt multiple libsoup dependency conflict

### ISSUE THREAD

**Issue by PhilHudson** [atlas-engineer/nyxt#2147]
**Describe the bug**
Nyxt errors on launch with output (below) referencing multiple versions of libsoup. The process stays resident in memory but produces no UI.

I believe I have found relevant similar issue resolution here: https://github.com/johnfactotum/foliate/pull/808

**Precise recipe to reproduce the issue**
At a shell prompt: nyxt

**Information**
- OS name+version:
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=21.2.5
DISTRIB_CODENAME=Qonos
DISTRIB_DESCRIPTION="Manjaro Linux"

- Graphics card and driver:
Onboard Intel

- Desktop environment / Window manager name+version:
StumpWM 1.0.1

- How you installed Nyxt (Guix pack, package manager, build from source):

2.2.4 release (not daily) pkg.tar.zst built for *Arch, at https://e-v.srht.site/nyxt-aur-builds.html

- Information from `show-system-information`:

  If you can't run `show-system-information`, try `nyxt --system-information` from
  a shell.  It this still does not work, please provide the following:
  - Nyxt version (from the `nyxt-version` command or `nyxt --version` from a shell):
  - Lisp implementation/version (if built from source):
  - Kernel name+version:
  - WebKitGTK+ | QtWebEngine version:
Nyxt version: 2.2.4
Renderer version: GI-GTK
Operating system kernel: Linux 5.10.105-1-MANJARO
Lisp implementation: SBCL 2.1.11 (Dynamic space size: 3221225472)
Features: (:WEBKIT2 :WEBKIT2-2.34 :WEBKIT2-PASTE-PLAINTEXT :WEBKIT2-TRACKING
 :WEBKIT2-MUTE :WEBKIT2-EMOJI :WEBKIT2-MEDIA :WEBKIT2-SANDBOXING :GTK-3-22
 :GTK-3-20 :GTK-3-18 :GTK-3-16 :GTK-3-14 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6
 :GTK-3-4 :GTK :GDK-3-22 :GDK-3-20 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12
 :GDK-3-10 :GDK-3-8 :GDK-3-6 :GDK-3-4 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF
 :GLIB-2-30 :GLIB-2-32 :GLIB-2-34 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42
 :GLIB-2-44 :GLIB-2-46 :GLIB-2-48 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56
 :GLIB-2-58 :GLIB :NYXT-2 :FSET-EXT-STRINGS :CUSTOM-HASH-TABLE-NATIVE :SWANK
 :PLUMP-UTF-32 :GLOBAL-VARS :DECLARE-TYPES :PARENSCRIPT
 :SBCL+SAFE-STANDARD-READTABLE :NAMED-READTABLES :LPARALLEL :21BIT-CHARS
 :CHUNGA :CLOSER-MOP :CL-PPCRE-UNICODE :FLEXI-STREAMS :CL-UNICODE :CL-PPCRE
 :CL-JSON-DOUBLE-FLOAT-IS-SUBSUMED :CL-JSON-SINGLE-FLOAT-IS-SUBSUMED
 :BORDEAUX-THREADS :LPARALLEL.WITH-CLTL2 :LPARALLEL.WITH-CAS
 :LPARALLEL.WITH-STEALING-SCHEDULER :SPLIT-SEQUENCE CHIPZ-SYSTEM:GRAY-STREAMS
 CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64 CFFI-FEATURES:UNIX :CFFI
 CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP :FAST-IO-SV :FAST-IO
 :SBCL-USES-SB-ROTATE-BYTE :CL-JSON-CLOS :CL-JSON :THREAD-SUPPORT :ASDF3.3
 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX :NON-BASE-CHARS-EXIST-P
 :ASDF-UNICODE :X86-64 :GENCGC :64-BIT :ANSI-CL :COMMON-LISP :ELF
 :IEEE-FLOATING-POINT :LINUX :LITTLE-ENDIAN :PACKAGE-LOCAL-NICKNAMES
 :SB-CORE-COMPRESSION :SB-LDB :SB-PACKAGE-LOCKS :SB-THREAD :SB-UNICODE :SBCL
 :UNIX)

ASDF version: 3.3.1
ASDF registries: (NYXT-SOURCE-REGISTRY ENVIRONMENT-SOURCE-REGISTRY)
Critical dependencies: (/home/build/nyxt/src/nyxt/_build/cl-cffi-gtk/gtk/cl-cffi-gtk.asd
 /home/build/nyxt/src/nyxt/_build/cl-gobject-introspection/cl-gobject-introspection.asd
 /home/build/nyxt/src/nyxt/_build/cl-webkit/webkit2/cl-webkit2.asd)

**Output when started from a shell**
(sbcl:2699640): libsoup-ERROR **: 08:58:42.499: libsoup2 symbols detected. Using libsoup2 and libsoup3 in th
e same process is not supported.

**Comment by Ambrevar** [comment]
I suspect this is a distro or packaging issue.

Nyxt does not load anything itself, however it relies on https://github.com/joachifm/cl-webkit/blob/master/webkit2/webkit2.init.lisp to load webkit (4.0 or 4.1).  Nothing seems wrong there.

@aartaka Any idea?

**Comment by aartaka** [comment]
Yes, the problem's not on our side and we can't do anything about it. It's most likely several libsoup shared library files that conflict for being _the_ libsoup.

**Comment by aartaka** [comment]
> For my understanding, could you please confirm that pinning to a specific version of Webkit (as in the linked Foliate issue) is neither necessary nor sufficient.

I've been inattentive to that issue, sorry (^_^;) 

It seems WebKit version could also be related to the problem!

**Comment by edgar-vincent** [comment]
Hi! I've been having this issue for a long time, and thought I'd reported an issue about it, and just realised I'd never sent it... Sorry about that @PhilHudson.

Waleee has been kind enough to have a look at this some time ago, but I never managed to get it to work. This seems related to https://gitlab.gnome.org/GNOME/libsoup/-/issues/218 

I have the feeling that pinning the right version of WebKit would help. I have 4.1 and 5.0 here but still have the issue.

**Comment by Ambrevar** [comment]
cl-webkit should _not_ pick up webkitgtk 5.
Then any idea how the webkitgtk version could be the problem here?

**Comment by edgar-vincent** [comment]
@PhilHudson: Could you tried again with the latest build of the stable package? It seems to be fixed here.

**Comment by PhilHudson** [comment]
@edgar-vincent Yes, that seems to have done it. Thanks very much for giving this your time and attention and helping to bring it to a satisfactory conclusion.

**Comment by edgar-vincent** [comment]
You're very welcome. Sorry for not having dealt with this sooner.

**Comment by edgar-vincent** [comment]
It seems the package should depend on webkit2gtk-4.1.

**Comment by bqv** [comment]
https://bugs.gentoo.org/899988#c2

**Comment by aadcg** [comment]
> https://bugs.gentoo.org/899988#c2

CC @Ambrevar. What's your view?

**Comment by Ambrevar** [comment]
Oh!  I had completely missed that our web-extension support binds against some libraries too!

See
https://github.com/atlas-engineer/nyxt/blob/master/libraries/web-extensions/Makefile#L4-L5

@aartaka Are we binding against the wrong library here?  Looks like the problem  is on our side.

**Comment by edgar-vincent** [comment]
Could this be related to https://github.com/atlas-engineer/nyxt/issues/2743?

**Comment by Ambrevar** [comment]
Very likely indeed!

**Comment by aartaka** [comment]
> Oh! I had completely missed that our web-extension support binds against some libraries too!
> 
> See https://github.com/atlas-engineer/nyxt/blob/master/libraries/web-extensions/Makefile#L4-L5
> 
> @aartaka Are we binding against the wrong library here? Looks like the problem is on our side.

But then, `glib-2.0` and `gobject-2.0` are still relevant. The only suspect left is the `webkit2gtk-web-extension`. If we hard-code it to `webkit2gtk-web-extension-4.1`, then it should be fine, right?

**Comment by Ambrevar** [comment]
@PhilHudson @bqv @edgar-vincent Can you test if #2846 fixes it?

**Comment by edgar-vincent** [comment]
@Ambrevar Unfortunately, I cannot build Nyxt because of https://github.com/atlas-engineer/nyxt/issues/2743, even with https://github.com/atlas-engineer/nyxt/pull/2846.

**Comment by Ambrevar** [comment]
@edgar-vincent Can you try again with the latest checkout of cl-webkit?
See https://github.com/atlas-engineer/nyxt/issues/2743#issuecomment-1469994009 for the update.

**Comment by edgar-vincent** [comment]
@Ambrevar I still get the same error, unfortunately.

**Comment by Ambrevar** [comment]
You need to tweaks to test this properly:
- switch to the https://github.com/atlas-engineer/nyxt/tree/fix-makefile-with-double-webkit branch.
- Run `git submodule update --remote _build/cl-webkit` from the Nyxt checkout root.

**Comment by edgar-vincent** [comment]
It now builds fine. You were right, I thought I had updated the submodule properly, but I hadn't. I'm terrible with git, sorry about that!
Thanks for your patience, and for the fix.

**Comment by Ambrevar** [comment]
Thanks for confirming!
