### ISSUE TITLE
Make --script load user config.

### ISSUE THREAD

**Issue by aartaka** [atlas-engineer/nyxt#2155]
**Is your feature request related to a problem? Please describe.**

Currently, `--script` option runs the script in Nyxt process, but doesn't fully start Nyxt if it's not started. I guess that lots of users of `--script` and, especially `--headless` might expect initfile loading to happen before the script runs.

**Describe the solution you'd like**
Load initfile before loading the script.

**Describe alternatives you've considered**
An alternative is to use `--init` to load the script as an alternative initfile. This, however, requires some undirect loading of the original init file and looks wrong.

**Additional context**
See https://github.com/atlas-engineer/nyxt/pull/2154#issuecomment-1076181438.

**Comment by Ambrevar** [comment]
I'm confused about the problem.

Is it that the init file is not loaded while you expect it would?

Or is it that Nyxt does not start with you pass `--script`?

In either case, it's by design.  Have you considered using `--load`?  From the `--help` message:

```
  -l, --load ARG        Load the Lisp file.  Can be specified multiple times.
                       Without --quit or --remote, the loading is done after parsing the init file
                       (if any) and before initializing the browser.

  --script ARG          Load the Lisp file (skip #! line if any), skip init file, then exit.
                       Set to '-' to read standard input instead.

```

**Comment by aartaka** [comment]
Huh, I see. I guess it's just my inattentiveness...
