### ISSUE TITLE
SIgnal a condition if no +renderer+ ?

### ISSUE THREAD

**Issue by K1D77A** [atlas-engineer/nyxt#2158]
I dont know if there is a reason why someone would start nyxt without a renderer, but clearly its just bitten me in the arse for the last two days so I was wondering if a check on the variable +renderer+ could be made so that a condition is signalled if gi-gtk or whatever renderer hasn't been loaded? Ofcourse I will make the PR if you think this is acceptable.

Also can I create the headless version so that I can change the startup functionality for my own version locally? WIthout a subclass its not so easy to change the default startup functionality when running in headless. Thanks :)

**Comment by aartaka** [comment]
Done in e273655190b66466e08a9b983fd9a64d2cf4a03c.
