### ISSUE TITLE
Restrict nyxt: URLs to only accept strings for compatibility with web forms

### ISSUE THREAD

**Issue by aartaka** [atlas-engineer/nyxt#2160]
RIght now we parse arguments to internal page commands from URL arguments. For instance `nyxt:nyxt/buffer-listing-mode:list-buffers?cluster=nil&linear-view-p=nil` becomes `(nyxt/buffer-listing-mode:list-buffers :cluster nil :linear-view-p nil)`, which is hella convenient.

However, when I tried to make a search `<form>` in HTML that would redirect to a `nyxt:` URL, I encountered one peculiarity of this approach: whatever string a typical GET request appends, it's now appended in a Lisp reader-friendly format and is interpreted as a symbol. To exemplify, when you make a `<form action="nyxt:whatever" method="GET"><input for="arg"></form>` and input `hello there` it requests `(nyxt:whatever :arg 'hello)` instead of `(nyxt:whatever :arg "hello there")` just because there are no quotes.

All of these peculiarities make me think that, to make it possible mapping from `nyxt:` URLs to Lisp commands and back, we have to restrict the Lisp-side even more: allow only string argumens to Nyxt internal pages. String arguments are the only type of arguments that is fully compatible with the URLs and the Web way of doing things, however sour that sounds to me.

**Comment by Ambrevar** [comment]
Agreed.  It's limiting, but it seems that we have no choice here, do we?

**Comment by aartaka** [comment]
I mean, we can always ignore the Web Way of Doing Thing :tm: and stay in the cozy land of typed Lispy arguments :D 

But yeah, gotta be anoying dealing with web forms in such a scenario.

**Comment by aartaka** [comment]
Alternative suggested by Pierre: Use some special character, like backspace or escape, to mark Lisp-readable queries.

**Comment by jmercouris** [comment]
I like the alternative, rather than limiting ourselves.

**Comment by aartaka** [comment]
I've changed the format. It prefixes Lisp-readabile data with Escape now. It breaks all the history-saved `nyxt:` URLs, but well, we're making a major release :D
