### ISSUE TITLE
Syncing the showcase of features between the repository and website

### ISSUE THREAD

**Issue by aadcg** [atlas-engineer/nyxt#2168]
Currently the "visual demos" available on the website (gifs) contrast with the screenshots from the repository's README.

I'm wondering if it's justified.  Thoughts?

**Comment by Ambrevar** [comment]
They indeed need to be updated.  We are planning on updating them all with the 3.0 release since the overall interface has changed a bit.

**Comment by aadcg** [comment]
@jmercouris I think this is an important one for 3.0.

What do you think?

**Comment by jmercouris** [comment]
I agree, this is very important.

**Comment by jmercouris** [comment]
They are updated.
