### ISSUE TITLE
Requires MacOS 10.14

### ISSUE THREAD

**Issue by fapapa** [atlas-engineer/nyxt#217]
When I download the latest MacOS binary, or install the home-brew cask, and try to run the application, it gives me an error saying that MacOS 10.14 (Mojave) is required. Can support for High-Sierra (and earlier) be added?

**Comment by jmercouris** [comment]
Yes, probably, it will have to wait on the QT port though, so soon!

**Comment by Ambrevar** [comment]
@jmercouris Any idea which version of macOS is going to be required for version 2.0?

**Comment by jmercouris** [comment]
I believe at least 10.12, I don't have any old machines to test and verify this though, I'm sorry!

**Comment by jmercouris** [comment]
Nyxt no longer requires new versions of macOS. The Portfiles work fine on older versions too :-)
