### ISSUE TITLE
using 100% cpu?

### ISSUE THREAD

**Issue by kurokirasama** [atlas-engineer/nyxt#2170]
**Describe the bug**
When using nyxt I have 1 core at 100% use  (13% overall). The process that appears when launching nyxt  (that uses the cpu) is:

`/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitWebProcess`
 
[Here](https://bit.ly/3Dm0Cbw) are my .lisp files in case there is a problem there. But the issue also happens if they are not used.

**Precise recipe to reproduce the issue**
Open nyxt, load last opened websites (3).

For website-specific issues:
Can you reproduce this issue with Epiphany / GNOME Web (https://wiki.gnome.org/Apps/Web)?

**Information**
- OS name+version: Ubuntu 20.04.4 LTS x86_64
- Graphics card and driver: NVIDIA GeForce GTX 1050 3 GB Max-Q nvidia-driver-450
- Desktop environment / Window manager name+version: GNOME Shell 3.36.9
- How you installed Nyxt (Guix pack, package manager, build from source): deb file from official website
- Information from `show-system-information`:
```
Nyxt version: 2.2.4
Renderer version: GI-GTK
Operating system kernel: Linux 5.15.32-xanmod1
Lisp implementation: SBCL 2.1.0.0.HEAD.1-46cb065 (Dynamic space size: 3221225472)
Features: (:WEBKIT2 :WEBKIT2-2.34 :WEBKIT2-PASTE-PLAINTEXT :WEBKIT2-TRACKING
 :WEBKIT2-MUTE :WEBKIT2-EMOJI :WEBKIT2-MEDIA :WEBKIT2-SANDBOXING :GTK-3-22
 :GTK-3-20 :GTK-3-18 :GTK-3-16 :GTK-3-14 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6
 :GTK-3-4 :GTK :GDK-3-22 :GDK-3-20 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12
 :GDK-3-10 :GDK-3-8 :GDK-3-6 :GDK-3-4 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF
 :GLIB-2-30 :GLIB-2-32 :GLIB-2-34 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42
 :GLIB-2-44 :GLIB-2-46 :GLIB-2-48 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56
 :GLIB-2-58 :GLIB :NYXT-2 :FSET-EXT-STRINGS :CUSTOM-HASH-TABLE-NATIVE :SWANK
 :PLUMP-UTF-32 :GLOBAL-VARS :DECLARE-TYPES :PARENSCRIPT :NAMED-READTABLES
 :LPARALLEL :21BIT-CHARS :CHUNGA :FLEXI-STREAMS :CLOSER-MOP :CL-PPCRE-UNICODE
 :CL-UNICODE :BORDEAUX-THREADS :LPARALLEL.WITH-CLTL2 :LPARALLEL.WITH-CAS
 :LPARALLEL.WITH-STEALING-SCHEDULER :SPLIT-SEQUENCE CHIPZ-SYSTEM:GRAY-STREAMS
 :FAST-IO-SV :FAST-IO :SBCL-USES-SB-ROTATE-BYTE :CL-JSON-CLOS :CL-JSON
 :THREAD-SUPPORT :CL-PPCRE CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64
 CFFI-FEATURES:UNIX :CFFI CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP
 :ASDF3.3 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX
 :NON-BASE-CHARS-EXIST-P :ASDF-UNICODE :X86-64 :GENCGC :64-BIT :ANSI-CL
 :COMMON-LISP :ELF :IEEE-FLOATING-POINT :LINUX :LITTLE-ENDIAN
 :PACKAGE-LOCAL-NICKNAMES :SB-CORE-COMPRESSION :SB-LDB :SB-PACKAGE-LOCKS
 :SB-THREAD :SB-UNICODE :SBCL :UNIX)

ASDF version: 3.3.4
ASDF registries: (NYXT-SOURCE-REGISTRY ENVIRONMENT-SOURCE-REGISTRY USER-SOURCE-REGISTRY
                      USER-SOURCE-REGISTRY-DIRECTORY
                      DEFAULT-USER-SOURCE-REGISTRY SYSTEM-SOURCE-REGISTRY
                      SYSTEM-SOURCE-REGISTRY-DIRECTORY
                      DEFAULT-SYSTEM-SOURCE-REGISTRY)
Critical dependencies: (/home/runner/work/nyxt/nyxt/_build/cl-cffi-gtk/gtk/cl-cffi-gtk.asd
 /home/runner/work/nyxt/nyxt/_build/cl-gobject-introspection/cl-gobject-introspection.asd
 /home/runner/work/nyxt/nyxt/_build/cl-webkit/webkit2/cl-webkit2.asd)


```
  If you can't run `show-system-information`, try `nyxt --system-information` from
  a shell.  It this still does not work, please provide the following:
  - Nyxt version (from the `nyxt-version` command or `nyxt --version` from a shell):
  - Lisp implementation/version (if built from source):
  - Kernel name+version:
  - WebKitGTK+ | QtWebEngine version:

**Output when started from a shell**
```
<INFO> [11:05:29] Listening to socket "/run/user/1000/nyxt/nyxt.socket".
Nyxt version 2.2.4
<INFO> [11:05:29] Loading Lisp file "/home/user/.config/nyxt/auto-config.lisp".
<INFO> [11:05:29] Loading Lisp file "/home/user/.config/nyxt/init.lisp".
<INFO> [11:05:29] Loading Lisp file "~/.config/nyxt/statusline.lisp".
<INFO> [11:05:29] Loading Lisp file "~/.config/nyxt/stylesheet.lisp".
```

**Comment by aartaka** [comment]
Hmmmmm, this is definitely something on the WebKit side. Not much we can do on the Nyxt side, I suppose :shrug:

**Comment by kurokirasama** [comment]
ok, thank you!

**Comment by kurokirasama** [comment]
@r3k2 hi. That's exactly my issue, but it's just 100% in 1 core. I also installed it in another machine with same os and I don't have the issue there.
