### ISSUE TITLE
autoload last session buffers (websites)

### ISSUE THREAD

**Issue by kurokirasama** [atlas-engineer/nyxt#2171]
**Is your feature request related to a problem? Please describe.**

It would be really great if the last session (websites opened) could be autoloaded when nyxt starts. Evidently, as an option.

**Describe the solution you'd like**
Have the option that every time nyxt starts, all opened websites from previous sessions could be loaded automatically without passing for the default welcome screen (history).

**Describe alternatives you've considered**

**Additional context**
If this is already possible, please help me out in how to configure it.

**Comment by aartaka** [comment]
``` lisp
(define-configuration browser
  ((session-restore-prompt :always-restore)))
```

Should do it.

**Comment by kurokirasama** [comment]
cool!!, thanks!!
