### ISSUE TITLE
Broken HTML in prompter "prompt"

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#2174]
Commit 75977e76571d1a0075d5bfb57c8748b8627720fa results in the prompter prompt being misaligned.  For instance "Execute command" is displayed is not centered vertically.

@aartaka Any idea how to fix this?

**Comment by aartaka** [comment]
Removing the `:maybe-raw` for the prompt text sound like a proper solution to me -- it's not likely to be an HTML text, I suppose :shrug:

**Comment by aartaka** [comment]
But yeah, we'd better have a reasonable fix for this, instead of removing `:maybe-raw` that empowers one to style the prompt.

**Comment by Ambrevar** [comment]
I'm not sure I understand: why would HTML text be uncentered here?

**Comment by aartaka** [comment]
I found the reason! Spinneret does not recognize `:maybe-raw` tag in prompt-buffer layout code 0_o

**Comment by Ambrevar** [comment]
Fantastic, thanks!
