### ISSUE TITLE
WebExtension support broken?

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#2177]
I tried loading Beastify on master, and if I run

```lisp
(define-configuration web-buffer
  ((default-modes `(beastify ,@%slot-default%))))
```

then the next buffer creation fails with

```log
<WARN> [13:34:52] Warning: JavaScript error: GError: Domain: "WebKitJavascriptError", Code: 699, Message: undefined:1:9: ReferenceError: Can't find variable: browser
<WARN> [13:34:52] Warning: JavaScript error: GError: Domain: "WebKitJavascriptError", Code: 699, Message: undefined:1:9: ReferenceError: Can't find variable: browser
<WARN> [13:34:52] Warning: JavaScript error: GError: Domain: "WebKitJavascriptError", Code: 699, Message: undefined:1:9: ReferenceError: Can't find variable: browser
<WARN> [13:34:52] Warning: JavaScript error: GError: Domain: "WebKitJavascriptError", Code: 699, Message: undefined:1:9: ReferenceError: Can't find variable: browser
<WARN> [13:34:52] Warning: JavaScript error: GError: Domain: "WebKitJavascriptError", Code: 699, Message: undefined:1:9: ReferenceError: Can't find variable: browser
<WARN> [13:34:52] Warning: JavaScript error: GError: Domain: "WebKitJavascriptError", Code: 699, Message: undefined:1:9: ReferenceError: Can't find variable: browser
<WARN> [13:34:52] Warning: JavaScript error: GError: Domain: "WebKitJavascriptError", Code: 699, Message: undefined:1:9: ReferenceError: Can't find variable: browser
<WARN> [13:34:52] Warning: JavaScript error: GError: Domain: "WebKitJavascriptError", Code: 699, Message: undefined:1:9: ReferenceError: Can't find variable: browser
<WARN> [13:34:52] Warning: JavaScript error: GError: Domain: "WebKitJavascriptError", Code: 699, Message: undefined:1:9: ReferenceError: Can't find variable: browser
<WARN> [13:34:52] Warning: JavaScript error: GError: Domain: "WebKitJavascriptError", Code: 699, Message: undefined:1:9: ReferenceError: Can't find variable: browser
<INFO> [13:34:52] Buffer 1337 has no history.
<WARN> [13:34:52] Warning: JavaScript error: GError: Domain: "WebKitJavascriptError", Code: 699, Message: nyxt:help:1:9: ReferenceError: Can't find variable: browser
<WARN> [13:34:52] Warning: JavaScript error: GError: Domain: "WebKitJavascriptError", Code: 699, Message: nyxt:help:1:9: ReferenceError: Can't find variable: browser
<WARN> [13:34:52] Warning: JavaScript error: GError: Domain: "WebKitJavascriptError", Code: 699, Message: nyxt:help:1:9: ReferenceError: Can't find variable: browser
<WARN> [13:34:52] Warning: JavaScript error: GError: Domain: "WebKitJavascriptError", Code: 699, Message: nyxt:help:1:9: ReferenceError: Can't find variable: browser
<WARN> [13:34:52] Warning: JavaScript error: GError: Domain: "WebKitJavascriptError", Code: 699, Message: nyxt:help:1:9: ReferenceError: Can't find variable: browser
```

@aartaka Any idea what's going on?

**Comment by Ambrevar** [comment]
Clarification: If I add the above `define-configuration` to my init.lisp, then it works.  In other words, it breaks if the current buffer does not have beastify enabled.  It works if all buffers have it.

**Comment by Ambrevar** [comment]
About beastify itself, clicking on it in the status area display the frame with the 4 buttons, but then the buttons themselves don't do anything.

**Comment by aartaka** [comment]
This behavior is familiar. It seems that the library is not loaded well. Does it output `WebExtensions support library loaded`? If it does, then d9648bbbedfcb5b83f0184231d4d91524ecb1fbc is to blame and we should revert it.

**Comment by aartaka** [comment]
Then filtering certainly broke it :/

**Comment by Ambrevar** [comment]
So if I get it right, the aforementioned commit only opens up the API to enable filters, but it's only in a89215106a054b531313f42bac45fe9756670fca that a filter is used which possibly breaks everything.

Is my analysis correct?

**Comment by aartaka** [comment]
Yes, sounds correct!

**Comment by aartaka** [comment]
I found it! It seems that WebExtensions APIs are not being injected for panel-buffers, as those (after #2050) have a shared internal context with no extensions pre-configured, and thus are not recognized as worthy of WebExtensions APIs. APIs get injected into the isolated extension-named world, instead of the default one, thus failing the popup script loading relying on default world having `browser` object and all the other niceties.

A solution could be a hack from one of the initial designs of WebExtensions support (removed in 9504cf7f73126935690dfd3d205a14b682bb30a8): send the `injectAPIs` message to the page when the extensions-related mode is activated, instead of pre-computing extension list at buffer creation. This is more flexible, although arguably a dirtier approach.

**Comment by Ambrevar** [comment]
@aartaka Wanna send a proposal?

**Comment by aartaka** [comment]
Done in be7801dc0ce1af5c028035e4dd4febafc9c033c3, although there are definitely some segfaults to clean out xD

**Comment by Ambrevar** [comment]
Tag this issues as 3.0 then?

**Comment by aartaka** [comment]
Yes.

I'd even say that we should try the Lisp-based WebExtensions library before 3.0 too. That's so that we understand the implications and can plan for moving forward with it :)

**Comment by Ambrevar** [comment]
@aartaka I see that the `extension` mode in `source/web-extensions.lisp` is still using `constructor` and `destructor`.  Did we forget to update this?

**Comment by aartaka** [comment]
Yes, we did :D

**Comment by aadcg** [comment]
Can we achieve this by 3.0?

**Comment by aartaka** [comment]
I'd suggest a radical move: dropping (deleting) `libraries/web-extensions` altogether before 3.0, so that it doesn't:
- Cause false expectations,
- And fail builds and runtime (because if there's something wrong in the lib, all of WebKit views segfault).

**Comment by Ambrevar** [comment]
I agree.
