### ISSUE TITLE
Prompt buffer text suppression 

### ISSUE THREAD

**Issue by aadcg** [atlas-engineer/nyxt#2179]
![2022-04-06_16:34:34](https://user-images.githubusercontent.com/45483512/162013133-814d227e-682c-4818-818f-7f9ca2863f7c.png)

In these situations it seems reasonable that the "Name" column should be given priority to show the complete name of the command.

**Comment by aartaka** [comment]
I'm not sure whether it's a `wontfix` or `help-needed`. Nyxt is somewhat implied to be used fullscreen and having lots of space for the prompt. If there's not enough space, you can always disable some of the attributes.

But yes, the general problem of prompt not resising/adjusting is a valid one!

**Comment by jmercouris** [comment]
I did at some point make it so that the columns would be adjustable/take as much space as they need. However, the problem was, as the user would scroll up/down the list, the columns would resize! As such, I have not found a satisfactory solution...yet!

**Comment by Ambrevar** [comment]
There must be some CSS magic for this, no?

**Comment by aartaka** [comment]
Take your pick:
- Media queries.
- Flexboxes with wrapping.
- (not exacty CSS, but still) looking at the screen width and excluding columns on the Lisp side.

**Comment by jmercouris** [comment]
There is no magic for this. We would need to know the length of all prompt buffer entries to make this calculation. However, for performance reasons we only render X entries. We could do some sort of rough calculation on the Lisp side of the average length of a column and set the column widths CSS as percentages.

**Comment by aadcg** [comment]
I don't think there's anything we can do about this topic, closing.
