### ISSUE TITLE
Support for drop-down buttons (<select> HTML tags) in element hinting

### ISSUE THREAD

**Issue by nshamaev** [atlas-engineer/nyxt#218]
Hello! Great idea with emacs like browser.
Do you think about adding navigation with keys by inputs, as it was in Vimperator and Surfingkeys, for example?
In NEXT:
![image](https://user-images.githubusercontent.com/838566/58213252-17887d80-7cfa-11e9-829b-50927d9a53e3.png)
In Surfingkeys:
![image](https://user-images.githubusercontent.com/838566/58213268-296a2080-7cfa-11e9-92cb-d355ffb20217.png)

**Comment by alexanderbarbosa** [comment]
You mean scrolling up/down the page with keybinds? If so, for, now, only emacs binding: c-n/c-p

**Comment by Ambrevar** [comment]
@nshamaev I'm not sure I understand your question, could you give a detailed example?

**Comment by Ambrevar** [comment]
OK, I got it: you mean that Next does not place hints on buttons or input fields?
Yes, this is a known limitation.  It's not too hard to fix (see `link-hint.lisp`).  I'll work on it later, but if anyone has time to fix it I'll happily take a pull request! :D

**Comment by alexanderbarbosa** [comment]
@Ambrevar 
There is any "open hinted linked in a new tab"? ... could not find... ty.

**Comment by Ambrevar** [comment]
Yup, it's `go-anchor-new-buffer-focus`, bound to `M-l` by default.

**Comment by Ambrevar** [comment]
Update: Many more elements are now supported, but input fields and drop-down buttons don't work (e.g. the Watch button on GitHub).

**Comment by Ambrevar** [comment]
Input fields are supported, but you need to press tab before you can start typing.

**Comment by Ambrevar** [comment]
Awesome!
Thank you so much, @aartaka, this sure was a massive endeavour!
