### ISSUE TITLE
Supply our own font for special symbols (Awesome Font?)

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#2181]
As mentioned [here](https://github.com/atlas-engineer/nyxt/issues/1255#issuecomment-813380352), we need a special font to handle the special symbols on all platforms.

Font Awesome (https://fontawesome.com/) is a good contender.

To ship it is easy, just install it along other resources in the `nyxt.asd` file.

The main question is, how do we load it at run time?  In a portable fashion?  Maybe GTK should do this.

**Comment by aartaka** [comment]
What Epiphany does is introducing `ephy-resource:` CORS-enabled scheme for all the bundled resources, resolving their paths and returning their contents. We can do the same here.

**Comment by aartaka** [comment]
More icons can be found here: https://react-icons.github.io/react-icons

**Comment by jmercouris** [comment]
We are able to internally load SVGs now. We don't need to supply a whole font. We also do use our own custom font.
