### ISSUE TITLE
Thumbnails in Nyxt-native file chooser

### ISSUE THREAD

**Issue by aartaka** [atlas-engineer/nyxt#2183]
**Is your feature request related to a problem? Please describe.**
Thumbnails in file pickers are a basic yet a rare feature. [Just look at this blog post for an example of the irritation cause by the file picker WebKit uses](https://jayfax.neocities.org/mediocrity/gnome-has-no-thumbnails-in-the-file-picker.html).

**Describe the solution you'd like**
Showing thumbnails for images in `file-manager-mode` prompt. Not necessarily huge ones -- even the icon-size ones would work. Smal thumbnails will still cause some associative thoughts and help with navigation.

**Comment by Ambrevar** [comment]
Nice idea!

**Comment by aadcg** [comment]
I have 2 observations:

(1) Fitting thumbnails in the prompt buffer would account to a subpar UI. Prompt buffer space is precious and the height of each line should be allocated to text only.

(2) Adding thumbnails to other interfaces would be interesting. But the subject for an external extension.

**Comment by aartaka** [comment]
> (1) Fitting thumbnails in the prompt buffer would account to a subpar UI. Prompt buffer space is precious and the height of each line should be allocated to text only.

If we make thumbnails to be the same height as text, that will have all the convenience with retained space efficiency.

**Comment by aadcg** [comment]
Good point! When the day comes to improve the file manager facilities, we should consider highly consider it.

**Comment by aadcg** [comment]
Worth exploring in an extension.
