### ISSUE TITLE
Rationale behind `switch-buffer`

### ISSUE THREAD

**Issue by aadcg** [atlas-engineer/nyxt#2184]
What is the rationale behind commit c61c17dd?

I know it's easy to configure otherwise, but I'm wondering about the motivation.

**Comment by jmercouris** [comment]
The reason being that when you press C-x b, your context would be immediately switched with follow-mode. It is much less jarring to press C-x b and then be able to type where you want to go.

**Comment by aadcg** [comment]
I see it now!
