### ISSUE TITLE
Running Nyxt inside of a container

### ISSUE THREAD

**Issue by aadcg** [atlas-engineer/nyxt#2186]
I'm running Nyxt inside a container using Guix using the following Bash script:

```bash
guix shell \
     --container \
     --network \
     --no-cwd \
     --preserve='^DISPLAY$|^GDK_SCALE$' \
     --expose=/etc/ssl/certs \
     --expose="$HOME/.config/nyxt/" \
     --share="$HOME/.local/share/nyxt"="$HOME/.local/share/nyxt/" \
     nss-certs glib glib-networking gsettings-desktop-schemas coreutils emacs nyxt \
     -- nyxt
```

But I get the following error when I run `nyxt-version` - `WARN - Warning: Error on separate thread: None of the commands are installed: (wl-copy" "/gnu/store/qkx80nwl511mfp0ml1dv258gzcr2y36i-xclip-0.13/bin/xclip" "xsel")`.

I'm a bit confused as I thought that Guix would bring all of Nyxt's dependencies into this shell/environment. What am I missing?

**Comment by aartaka** [comment]
Clipboard commands are not hard dependencies, so we don't include them directly. Those are up to the user to install.

**Comment by jmercouris** [comment]
Maybe we should make them hard dependencies. Is there a downside to doing so?

**Comment by aartaka** [comment]
Well, forcing `xclip` to the one using `wl-copy` on Wayland doesn't sound too good. Bundling more than one of those is wasting space (not that it's too bad, but there are valid objections to that).

**Comment by aadcg** [comment]
@aartaka has a point.

What I don't understand is why adding `xclip` doesn't fix it for me, while `xsel` does.

**Comment by jmercouris** [comment]
Ah right, I forgot that the clipboard is magically tied to the window environment. Thanks for the clarification.
