### ISSUE TITLE
Nyxt fails to start on commit 6461d6ba (related to GPG support)

### ISSUE THREAD

**Issue by pdelfino** [atlas-engineer/nyxt#2190]
**Describe the bug**
After commit 6461d6ba, I can't successfully start Nyxt.

**Precise recipe to reproduce the issue**
1 - being on commit 6461d6ba, execute the steps to run Nyxt from source 

```lisp
; SLIME 2.26.1
CL-USER> (ql:quickload :nyxt/gi-gtk)
To load "nyxt/gi-gtk":
  Load 1 ASDF system:
    nyxt/gi-gtk
; Loading "nyxt/gi-gtk"
..................................................
[package class-star]..............................
.................................................
(:NYXT/GI-GTK)
CL-USER> (in-package :nyxt)
#<PACKAGE "NYXT">
NYXT> (start)
<INFO> [16:37:13] Listening to socket #P"/run/user/1000/nyxt/nyxt.socket.gpg".
Nyxt version 2.1.1-1877-g6461d6ba
NIL

```
 2- Nyxt's GUI does not start and slime throws the following error message:
```lisp
error while trying to create a directory pathname for
#1=#<PATHNAME (with no namestring)
              :HOST #<SB-IMPL::UNIX-HOST {100010C2D3}>
              :DEVICE NIL
              :DIRECTORY (:ABSOLUTE "home" "pedro" ".local"
                          "share" "nyxt" "extensions")
              :NAME NIL
              :TYPE "gpg"
              :VERSION NIL>:
The pathname #1# does not have a namestring because
there is a :TYPE component but no :NAME component
``` 

Obs. 1.: Being on the previous commit (fc5c2e54) everything works fine

Obs. 2: The error message seems to indicate something related to my extensions. This is what I have:
```lisp
[pedro@system:~/.local/share/nyxt/extensions]$ ls -l
total 8
drwxr-xr-x 3 pedro users 4096 Jan 24 16:04 charon
drwxr-xr-x 5 pedro users 4096 Nov 13 19:40 demeter
```
Demeter directory is on commit ID 88546ffa83ad7f328aa0d26966139eaf4aa1b49f. Charon directory is on commit ID 359327f08b4de0a2268e6b926a62dde3a7b1b780

For website-specific issues:
Can you reproduce this issue with Epiphany / GNOME Web (https://wiki.gnome.org/Apps/Web)?
N/A

**Information**

- OS name+version: NixOS  21.05. You can see my NixOS config file [here](https://github.com/pdelfino/my-nixos-config/blob/main/configuration.nix). 

- Graphics card and driver:
product: Iris Plus Graphics 640
configuration: driver=i915 latency=0

- Desktop environment / Window manager name+version: GNOME 40.1.0

- Window System: Wayland

- How you installed Nyxt (Guix pack, package manager, build from source): source

- Information from `show-system-information`:
I can't do it since Nyxt is not starting.

**Output when started from a shell**

I started Nyxt from source

**Comment by pdelfino** [comment]
I tried deleting the extensions `demeter` and `charon`, but the problem persists.

**Comment by jmercouris** [comment]
You don't need to delete any extensions, it should suffice to call Nyxt with no-init. So `(nyxt:start :no-init t)`

**Comment by aartaka** [comment]
Load the most recent version of nfiles and it will work just fine :)

**Comment by pdelfino** [comment]
> You don't need to delete any extensions, it should suffice to call Nyxt with no-init. So `(nyxt:start :no-init t)`

I tried with ` NYXT> (start :no-init t)`. Unfortunately, the problem persisted, John...

**Comment by pdelfino** [comment]
> Load the most recent version of nfiles and it will work just fine :)

This solved the problem! Thanks, Artyom :)
