### ISSUE TITLE
Typo in `shell.nix` -> are `propagatedBuildInputs` even used?

### ISSUE THREAD

**Issue by kenranunderscore** [atlas-engineer/nyxt#2193]
This is a typo:
https://github.com/atlas-engineer/nyxt/blob/214d3cd4ca5a82ebb57d4f47982f7301c75a112c/build-scripts/shell.nix#L43
It should be `propagatedBuildInputs` instead.

But: since like this it shouldn't have any effect, I tried `make all` without it and it succeeded (with a 1-2 week-old `nixpkgs-unstable`). The resulting binary seemed usable as before.

So my question is: Is there a reason to keep this attribute around?
(I could of course open a trivial PR for this if you'd prefer that.)

**Comment by aartaka** [comment]
Indeed, [Nix manual mentions `propagatedBuildInputs` as quite a special case of inputs](https://nixos.org/manual/nixpkgs/stable/#ssec-stdenv-dependencies), I suppose we don't need them.
