### ISSUE TITLE
Leverage `selection-actions` as a list

### ISSUE THREAD

**Issue by aadcg** [atlas-engineer/nyxt#2198]
The documentation of `selection-actions` suggests that it could be a list, but there's no mechanism to handle it as a list of multiple elements.

Also, I can't think of an example where it could be used as a list. Anyone? @Ambrevar @aartaka @jmercouris @pdelfino

**Comment by Ambrevar** [comment]
Aaaah, thank you for bringing this up, completely forgot about it and
the "TODO:" comment disappeared a while ago when refactoring.

What was originally meant with this is the ability to run multiple
"persistent actions" (in Helm parlance -- actions that don't close the
prompt buffer).

Indeed, we are missing a way to run these actions.  I'll work on it.

**Comment by aadcg** [comment]
Ok!  It makes perfect sense now.  It's not a priority :)

**Comment by aadcg** [comment]
@Ambrevar do you still think this is a priority for 3.0? I think this arrive later during the `3-series`.

**Comment by Ambrevar** [comment]
I'm unsure it would break the API.  That said, it's easy to implement, so I wouldn't worry too much about it.
