### ISSUE TITLE
Could Not Load the Init File

### ISSUE THREAD

**Issue by fictitiousexistence** [atlas-engineer/nyxt#2204]
Running Nyxt version 3-641-gc3aec762

Nyxt no longer is able to read my config files. 

Starts up with error "could not load the init file.

I moved all my configs and created a blank init and auto-config. Ran nyxt and tried to use the settings buttons but they don't write into auto-config either. 

Tried using git package builds on arch, gentoo, and directly from git.

P.S. This occurred after updating around Thursday or Friday last week. I'm very slow to getting around to posting. 

Thanks!

**Comment by Ambrevar** [comment]
We've revamped the auto-config as well as the class configuration process.

Can you post:

- a minimal `init.lisp` that does not work,
- a precise recipe of the slot setting that does not get written

?

**Comment by fictitiousexistence** [comment]
Here are 3 options that were in my auto-config before:
`(define-configuration buffer
  ((default-modes (append '(nyxt::vi-normal-mode) %slot-default%))))
(define-configuration browser
  ((theme theme::+dark-theme+)))
(setf (uiop/os:getenv "WEBKIT_DISABLE_COMPOSITING_MODE") "1")`

I created a blank auto-config.lisp and loaded nyxt. Clicked on Settings > Use vi. It does not save to the config file.

If I put just the below in init.lisp it fails to load.
(define-configuration buffer
  ((default-modes (append '(nyxt::vi-normal-mode) %slot-default%))))

**Comment by Anomalocaridid** [comment]
@Ambrevar Is there documentation on what has changed somewhere? I am having trouble figuring out how to migrate my config using Nyxt's built-in documentation and I cannot seem to find much information on this repo or Nyxt's website.

**Comment by jmercouris** [comment]
There is no documentation as of yet! We are working hard to polish things up, and will hopefully have a nice little macro that will solve your woes :-)

Sorry for the temporary problems!

**Comment by Ambrevar** [comment]
Yes, there is documentation in the manual! :)

In short, instead of using the define-configuration macro you can now
specialize the `customize-instance` method.

That said, we are working on a backward compatible
`define-configuration` macro,
so if you wait for https://github.com/atlas-engineer/nyxt/pull/2205/ to
be merged your configuration should start working again.

Sorry for the trouble, don't forget that `master` is bleeding edge and
it breaks :p

**Comment by fictitiousexistence** [comment]
Thanks!

I now have only the below in init.lisp and each time a page loads the buffer prompt comes up and says Enable mode(s) for buffer(s)


 (defmethod customize-instance ((buffer web-buffer) &key)
  (nyxt/vi-mode:vi-normal-mode :buffer buffer))

**Comment by aartaka** [comment]
`define-configuration` is back with #2229! Closing this, as the initial set of settings should work just fine on the most recent `master`.

To respond to your last comment @fictitiousexistence, mode settings are better handled with `default-modes` method specialization (`define-configuration` does that for you). I.e.
``` lisp
(defmethod default-modes :around ((buffer buffer))
  (append '(nyxt/vi-mode:vi-normal-mode) (call-next-method)))
```
