### ISSUE TITLE
element-hint-mode broken file structure / package structure

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#2206]
In commit 531682f1aa6849e9ba04d1f11b3418ee4bdc71e5 @jmercouris merged `source/more/element-hint-mode.lisp` and `source/mode/element-hint.lisp`.

This seems wrong: now we have non-mode code together with mode code.  Besides, the last part of the file is not in the same package as the first part.  

It's strongly discouraged to have multiple packages in one file because it confuses both the user and SLIME/SLY.

So what about moving the whole file to `nyxt/element-hint-mode`?

**Comment by jmercouris** [comment]
Hm. I guess I am OK with that. Not a huge fan, but it is acceptable!

**Comment by aartaka** [comment]
But then, element hints and `element-hint-mode` are two different things -- the former is responsible for hint generation and actions, while the latter is responsible for the prompt buffer keybindings specific to hint prompts. Maybe split them into mode/hinting.lisp and mode/element-hint.lisp (hints and `element-hints-mode` respectively)?

**Comment by Ambrevar** [comment]
Shouldn't the hint generation belong to `source/hint.lisp` then?

**Comment by aartaka** [comment]
Yes, that could work too. The reason element-hint.lisp was in mode/ initially was that it belonged to web-mode, but I guess we can move it elsewhere now, especially given that web-mode is no longer a thing :)

**Comment by Ambrevar** [comment]
Fixed with #2253.
