### ISSUE TITLE
Missing CA Certs in pure nix shell

### ISSUE THREAD

**Issue by OliverEvans96** [atlas-engineer/nyxt#2207]
# Describe the bug

The current `shell.nix` does not include `pkgs.cacert` in `buildInputs`. As a result, TLS fails in a pure shell.

![2022-04-27-160603_956x510_scrot](https://user-images.githubusercontent.com/15915043/165645717-afc37fdd-0e99-45a3-b6a8-758dd94b2644.png)

This is not really Nyxt-specific, as a similar issue can be produced with curl:

```
$ nix-shell --pure -p curl --command 'curl https://jsonplaceholder.typicode.com/todos/1'
curl: (77) error setting certificate verify locations:  CAfile: /no-cert-file.crt CApath: none
```

However, this is easily fixed by including the `cacert` package.
```
$ nix-shell --pure -p cacert curl --command 'curl https://jsonplaceholder.typicode.com/todos/1'
{
  "userId": 1,
  "id": 1,
  "title": "delectus aut autem",
  "completed": false
}
```

Similarly, adding `pkgs.cacert` to `buildInputs` in `shell.nix` fixes the issue for Nyxt.

I'm raising this issue mainly to ask the question: **Should `pkgs.cacert` be included in `buildInputs`?**

I'm not a nix expert, so I'm not sure one way or the other, but I thought it was worth bringing up.

# Precise recipe to reproduce the issue

```
nix-shell --pure build-scripts/shell.nix --command 'make all && ./nyxt -v'
```
**NOTE**: I did add `pkgs.git` to `nativeBuildInputs` to get this to work :point_up: 

# Information
- OS name+version: **NixOS**
- How you installed Nyxt (Guix pack, package manager, build from source): **build from source with make**

**Output when started from a shell**

With `-v` flag, the following relevant output is produced:
```
(process:255861): GLib-Net-WARNING **: 16:05:06.779: Failed to load TLS database: Failed to load system trust store: Error while reading file.
WARNING:
   Couldn't handle multiple interfaces for #.(SB-SYS:INT-SAP #X7FB650328240) of type GTlsCertificateGnutls: NIL.
```

# Related
- https://github.com/NixOS/nixpkgs/issues/66716
- https://github.com/NixOS/nix/issues/921

**Comment by Ambrevar** [comment]
Cc @jmercouris

**Comment by aadcg** [comment]
Stale. 

See https://github.com/NixOS/nixpkgs/issues/217888. Nyxt 3.0.0 should land on Nix soon.
