### ISSUE TITLE
nyxt::mode-status for extensions should be independent of glyphs

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#2218]
We need to change the logic.  This is relatively easy.

**Comment by aadcg** [comment]
Could someone explain in more detail the problem?

**Comment by Ambrevar** [comment]
status.lisp should be general-purpose and extensible via modes.

Currently it hard-codes reference to vi-mode.  Ideally it should be up to vi-mode to add defmethods that change how the status-buffer behaves.

This goes together with #2219.

Anyways, I'll work on it today! :)

**Comment by Ambrevar** [comment]
Sorry, I was just explaining another problem, that of `format-status`.

For the problem mentioned in the original post, see `web-extensions.lisp`:
```lisp
;; TODO: This is not the right point where to hook into the status bar, since it
;; won't work if glyphs are on.
(defmethod nyxt::mode-status ((extension extension))
  (spinneret:with-html-string
    (:button :class "button"
             :onclick (ps:ps (nyxt/ps:lisp-eval `(toggle-extension-popup ',(sera:class-name-of extension))))
             :title (format nil "Open the browser action of ~a" extension)
             (name extension))))
```

**Comment by Ambrevar** [comment]
See #2321 for a potential fix.
