### ISSUE TITLE
Spontaneous hang when build with SBCL 2.2.4

### ISSUE THREAD

**Issue by shamazmazum** [atlas-engineer/nyxt#2221]
**Describe the bug**
Hi! Nyxt hangs spontaneously when built with SBCL 2.2.4. I get something like this + high CPU consumption
![20220503_08h35m47s_grim](https://user-images.githubusercontent.com/812069/166507700-37cac6dd-b675-4db5-a123-b2ec62e4d22f.png)

**Version 2.2.3 is OK!** All other build conditions are the same.

I tried to compare build logs (2.2.3 vs 2.2.4) and found the same amount of warnings and style warnings:
~~~~
@@ -75808,4 +75722,4 @@
 ;     S-XML:*IGNORE-NAMESPACES* PARENSCRIPT:*JS-TARGET-VERSION*
 ;   caught 2 WARNING conditions
 ;   caught 82 STYLE-WARNING conditions
-;   printed 3801 notes
+;   printed 3848 notes
~~~~

SBCL was bootstrapped with SBCL 1.2.7 or CCL 1.12 (tried both).

**Precise recipe to reproduce the issue**
I get this situation when logged into github and having some other pages in another buffers (opened with `M-l`). After that you need to browse the web a bit and maybe switch buffers. There is no precise recipe, this happens spontaneously.

**Information**
- OS name+version: FreeBSD 13.1-RC2
- Graphics card and driver: drm-fbsd13-kmod-5.4.144.g20220223 + mesa 21.3.8 + Radeon RX 500 series card
- Desktop environment / Window manager name+version: sway 1.7
- How you installed Nyxt (Guix pack, package manager, build from source): Ultralisp version `atlas-engineer-nyxt-20220502215621`.
- Information from `show-system-information`: this command does not work for me :)

Webkit 2.34.6

~~~~
NYXT-USER> *features*
(:WEBKIT2 :WEBKIT2-2.34 :WEBKIT2-CORS-ALLOWLIST :WEBKIT2-PASTE-PLAINTEXT
 :WEBKIT2-TRACKING :WEBKIT2-MUTE :WEBKIT2-EMOJI :WEBKIT2-MEDIA
 :WEBKIT2-SANDBOXING :GTK-3-22 :GTK-3-20 :GTK-3-18 :GTK-3-16 :GTK-3-14
 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6 :GTK-3-4 :GTK :GDK-3-22 :GDK-3-20
 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12 :GDK-3-10 :GDK-3-8 :GDK-3-6 :GDK-3-4
 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF :GLIB-2-30 :GLIB-2-32 :GLIB-2-34
 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42 :GLIB-2-44 :GLIB-2-46 :GLIB-2-48
 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56 :GLIB-2-58 :GLIB :NYXT-3
 :FSET-EXT-STRINGS :CUSTOM-HASH-TABLE-NATIVE :SWANK :PLUMP-UTF-32 :PARENSCRIPT
 :SBCL+SAFE-STANDARD-READTABLE :NAMED-READTABLES :LPARALLEL :21BIT-CHARS
 :CLOSER-MOP :CL-PPCRE-UNICODE :CL-UNICODE :CL-JSON-DOUBLE-FLOAT-IS-SUBSUMED
 :CL-JSON-SINGLE-FLOAT-IS-SUBSUMED :CL-PPCRE :CHUNGA :FLEXI-STREAMS
 :BORDEAUX-THREADS :GLOBAL-VARS :LPARALLEL.WITH-CLTL2 :LPARALLEL.WITH-CAS
 :LPARALLEL.WITH-STEALING-SCHEDULER :SPLIT-SEQUENCE
 CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64 CFFI-FEATURES:UNIX :CFFI
 CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP :FAST-IO-SV :FAST-IO
 :ASDF-SYSTEM-CONNECTIONS :CL-JSON-CLOS :CL-JSON :SBCL-USES-SB-ROTATE-BYTE
 CHIPZ-SYSTEM:GRAY-STREAMS :THREAD-SUPPORT :QUICKLISP :ASDF3.3 :ASDF3.2
 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX :NON-BASE-CHARS-EXIST-P :ASDF-UNICODE
 :SINGLE-FLOAT-TRAN :X86-64 :GENCGC :64-BIT :ANSI-CL :BSD :COMMON-LISP :ELF
 :FREEBSD :IEEE-FLOATING-POINT :LITTLE-ENDIAN :PACKAGE-LOCAL-NICKNAMES
 :SB-CORE-COMPRESSION :SB-LDB :SB-PACKAGE-LOCKS :SB-THREAD :SB-UNICODE :SBCL
 :UNIX)
~~~~
 
**Output when started from a shell**

Just a regular output, even with `(log:config :debug)`.

Can you test on SBCL 2.2.4? I am not even sure if this is a nyxt issue, an SBCL issue or a FreeBSD issue. Default configuration is OK for testing purposes.

**Comment by aadcg** [comment]
Thank you for the heads-up.

I can give it a try with guix. The other day I've sent a patch to update sbcl to 2.4.4. (@ambrevar, I belive you have commit access, care to apply it? bug#55198 :D).

**Comment by Ambrevar** [comment]
@shamazmazum After roughly how much time does the hang happen?  Does it happen if you do nothing, just wait?

@aadcg I'll merge it later, need to test the build of all deps first.

**Comment by shamazmazum** [comment]
@Ambrevar Like two or three minutes. I encounter this bug when I do something. When I just wait all is seemingly OK.

**Comment by Ambrevar** [comment]
Is it when you call the prompt-buffer, or does it happen also, say when
you hover over the status area or links?

**Comment by shamazmazum** [comment]
I bisected the problem to this commit: https://github.com/sbcl/sbcl/commit/485265

@Ambrevar When I bisected nyxt hanged right on startup sometimes.

I remember my first issue here: #1630.  Also related to `run-program` and also FreeBSD specific, as it seems.

**Comment by shamazmazum** [comment]
Removing one call to `run-program` masks this problem:

~~~~
diff --git a/source/user-files.lisp b/source/user-files.lisp
index 56d9dc8f..83d20c37 100644
--- a/source/user-files.lisp
+++ b/source/user-files.lisp
@@ -151,10 +151,7 @@ Example: when passed command line option --with-file foo=bar,

 (export-always 'xdg-download-dir)
 (defun xdg-download-dir ()
-  (let ((dir (ignore-errors (uiop:run-program '("xdg-user-dir" "DOWNLOAD")
-                                              :output '(:string :stripped t)))))
-    (when (or (null dir) (uiop:pathname-equal dir (user-homedir-pathname)))
-      (setf dir (uiop:getenv "XDG_DOWNLOAD_DIR")))
+  (let ((dir (uiop:getenv "XDG_DOWNLOAD_DIR")))
     (unless dir
       (setf dir (uiop:merge-pathnames* #p"Downloads/" (user-homedir-pathname))))
     (uiop:ensure-pathname dir :ensure-directory t)))
~~~~

When I run this code in newly started REPL all is OK, though.

**Comment by Ambrevar** [comment]
Wow, this is very odd!   Could you report this to the SBCL bugtracker?  
Report the bisected commit, I suspect this is going to be useful :)

**Comment by Ambrevar** [comment]
@aadcg I guess SBCL 2.2.4 won't be merged because it has bugs, see https://github.com/glv2/cl-lzlib/issues/1.

**Comment by Ambrevar** [comment]
@shamazmazum I've just tested Nyxt 2.2.4 on SBCL 2.2.4 on Guix for a couple of minutes, it worked fine here.

**Comment by shamazmazum** [comment]
@Ambrevar Sure, I'll report it. I can also try to create some minimal test case. Clearly this is not a bug in nyxt, but in the worst case we can remove invocation of `run-programm` when on FreeBSD and SBCL.

**Comment by Ambrevar** [comment]
That'd be too bad, since it would mean you could no longer leverage external third-party tools (`git`, text editor, etc.).

**Comment by shamazmazum** [comment]
This seems to be fixed in SBCL 2.2.5 even without my reports. I am just too tired to do some lisp development right now :(

So closing this issue then.

**Comment by shamazmazum** [comment]
Release notes say:

    bug fix: streams opened from RUN-PROGRAM but left unclosed because of a non-local exit no longer cause unrelated streams to be closed later.

**Comment by jmercouris** [comment]
Thank you for the update! I am glad it was fixed in any case!
