### ISSUE TITLE
Avoid `with-current-buffer` pattern when evaluating JS

### ISSUE THREAD

**Issue by aadcg** [atlas-engineer/nyxt#2227]
This is follow-up to #2220.

@aartaka and I noticed there's a frequent pattern in the codebase that goes along the lines of:

```lisp
(with-current-buffer buffer-object (peval|pflet ...) ...)
```

Notice that the macros `peval` and `pflet` execute JS synchronously in the `current-buffer`. 

We suggest that these macros should support a keyword argument that would specify the buffer.

What do you think? @jmercouris @Ambrevar @pdelfino

**Comment by jmercouris** [comment]
Yes, it is a good point! It seems a suitable addition for peval, but not pflet. I can't imagine how the syntax would look for pflet!

**Comment by Ambrevar** [comment]
`(pflet :buffer BUFFER (BINDINGS) BODY)`?

**Comment by jmercouris** [comment]
Feels wrong, but it's OK I guess :-D

**Comment by aadcg** [comment]
> Feels wrong, but it's OK I guess :-D

Care to expand?

**Comment by jmercouris** [comment]
It just bothers me because it breaks with the expectation of it functioning purely as a let/flet type binding.

**Comment by aartaka** [comment]
> It just bothers me because it breaks with the expectation of it functioning purely as a let/flet type binding.

Well, that's a part of how it works, so we better be explicit about it being buffer-dependent than reinforce a faulty expectation :)

**Comment by aartaka** [comment]
I've added the 
``` lisp
(peval :async t :buffer buffer (ps:chain document active-element value))
``` 
syntax for `peval` and 
``` lisp
(pflet ((foo :buffer b ()
             (ps:chain window (prompt "How are you?")))
        (bar :async t :buffer b2 ()
             (alert "hello")))
  (do-something-here))
```

See https://github.com/atlas-engineer/nyxt/pull/2419#issuecomment-1219403939 for the syntax reasoning.
