### ISSUE TITLE
On the concepts of `actions` and `follow-mode-functions` of `prompt-buffer`

### ISSUE THREAD

**Issue by aadcg** [atlas-engineer/nyxt#2234]
While the difference between the two is clear, they actually share a lot conceptually. In short, `follow-mode-functions` run while navigating suggestions and `actions` run on selections.

I would suggest that the naming would reflect this affinity. 

Also, as of today, `follow-mode` can't be turned off (and the toggle wouldn't be very useful) so perhaps it's not really a mode. 

A humble suggestion:
- `actions` -> `actions-on-selections`
- `follow-mode-functions` -> `actions-on-suggestions`

**Comment by Ambrevar** [comment]
I agree that the names are not ideal, however `actions-on-selections` and `actions-on-suggestions` is too similar and I'm sure it's going to confuse users.

Note that there is no such thing as `selections` (plural), what you meant here are `marks`.
Also `suggestions` is always used to mean the whole list of elements, not just the marked suggestions.

I understand the naming is a bit confusing and should be clarified, but it's not very easy to get this right.  Suggestions (haha) welcome.

We should emphasize that the `follow-mode-functions` are actions that are run when changing the selection.

So what about this:
- `return-actions`
- `selection-actions`
?

**Comment by aadcg** [comment]
@Ambrevar, I fully agree with all of your points!

I'm ready to do the renaming unless someone disagrees :)

**Comment by jmercouris** [comment]
I can agree with them as well. Please feel free to do it Andre :-D

**Comment by Ambrevar** [comment]
Yup!

**Comment by aadcg** [comment]
I'm struggling with renaming the `follow-p` slot. I thought about `auto-return-selection-action-p`, what do you think?

**Comment by Ambrevar** [comment]
But it does not return, so `auto-selection-action-p` would make more sense, no?

**Comment by aadcg** [comment]
> But it does not return, so auto-selection-action-p would make more
> sense, no?

Absolutely!

**Comment by aadcg** [comment]
`prompt-buffer`'s README mentions:

> - Follow function (executed without closing the prompter).
> - Follow-mode (automatically run the persistent action on selection change).

Both points basically refer to the fact to `selection-actions` (in the new parlance) and to the fact that these don't return/interrupt the prompter. Am I right?

**Comment by Ambrevar** [comment]
Yes, that's correct.  First point is about the manual invocation, second one about the automatic invocation.

**Comment by aadcg** [comment]
Closed by #2249.
