### ISSUE TITLE
Emacs -> Nyxt Buffer

### ISSUE THREAD

**Issue by jmercouris** [atlas-engineer/nyxt#2235]
I would like a simple way to take the output of an Emacs variable, string, etc, and simply put it into a Nyxt buffer. What is the easiest way to do that? We should document this, and provide a way for users to utilize this in their Emacs workflows! The solution to this feature request could be as something simple as documentation for existing functionality, or an article :-)

@montaropdf

**Comment by aadcg** [comment]
I'm not sure if I understand the question.  What's "put it into a Nyxt buffer" exactly?

**Comment by Ambrevar** [comment]
And what do you mean with `the output of a variable / string`?

**Comment by Ambrevar** [comment]
Does this answer your question?

```lisp
(uiop:run-program (list "emacsclient" "--eval" "fill-column" ) :output '(:string :stripped t))
```

**Comment by aadcg** [comment]
I still don't get exactly what you're looking for. You want a Nyxt buffer, which I see it as generating an HTML document that expands Elisp s-exps. How accurate is that? When you say display from within Emacs, do you mean evaluating an Elisp s-exp on the lines of `(open-nyxt-buffer html-document)` that does the obvious?

**Comment by jmercouris** [comment]
Correct Andre. I should be able to evaluate an Elisp SEXP or a Lisp SEXP that I can pipe to Slime. I don't care how the mechanism works, I just want an easy way to render HTML from Emacs in Nyxt.

**Comment by Ambrevar** [comment]
You should not pipe to Slime then, because
- The user may not have slime.
- Nyxt may not be started via slime.

Nyxt can be communicated to via its own socket.  We have `nyxt --eval` for that.

So what you want is something like 

```elisp
(call-process "nyxt" nil nil nil "--eval" ARGS)
```

**Comment by aadcg** [comment]
I don't know if it helps but there's `htmlize`, which basically takes an Emacs buffer as inputs and outputs HTML. Or you also make use of `org`'s export abilities, which would generate HTML with arbitrary code (in the supported languages) expanded as needed. There are just hacks of course.

I think @Ambrevar is providing good solutions, but they're take perhaps Nyxt as the starting point. I'm wondering if you're thinking about Emacs as the starting point.

**Comment by montaropdf** [comment]
Hello,

I notice, that, I manage to make my case unclear during the meeting.

Without discarding the idea presented here, it was more about getting access to an API, and a mode, from Nyxt, to be able to display the result of the evaluation of a piece of common lisp code, from within a slime/sly session. When dealing with huge or complex output, using Nyxt as a visualizer, seems pertinent.

I was also asking myself if it could be possible to redirect the stream displaying the result of a code evaluation, in the repl, to a stream linked to a Nyxt buffer. I suppose, this imply, at least, a specific mode attached to the Nyxt buffer, plus some function to glue the 2 streams together.

I hope, now, it is clearer.

**Comment by aartaka** [comment]
@montaropdf, what you want (well, at least based on how I understood you, I may be mistaken) is one line of code on most recent Nyxt:
``` lisp
;; X is the value to inspect in Nyxt
(nyxt:buffer-load-internal-page-focus 'nyxt::describe-value :id (nyxt::ensure-inspected-id X))
```

It's kinda long-ish, but well, it's not intended to be used with something outside Nyxt in the first place, thus the unprettiness. You can easily abstract it to a function like
``` lisp
(defun inspect-in-nyxt (value)
  "Open the pretty rendering of VALUE is Nyxt inspector."
  (nyxt:buffer-load-internal-page-focus
   'nyxt::describe-value
   :id (nyxt::ensure-inspected-id value)))
```
and it will be much easier to use.

**Comment by aadcg** [comment]
I don't think we should keep this one open. Closing?

**Comment by aartaka** [comment]
Yes. There's a dozen ways to load HTML into Nyxt from anywhere outside, be it Emacs or not.
