### ISSUE TITLE
`nhooks` and `nfiles` nicknames

### ISSUE THREAD

**Issue by aadcg** [atlas-engineer/nyxt#2241]
We have a nickname for the former, `hooks`, but not for the latter.

For consistency, we could go either way (drop the `hooks` nickname or add the `files` nickname). WDYT?

**Comment by jmercouris** [comment]
I would add the files nickname. I believe it offers more flexibility. It'll be less of a change should the name of the underlying libraries change for any reason.

**Comment by aartaka** [comment]
+1 for `files`! 

I'm against removing `hooks` nickname, as it's there for backwards-compatibility...

**Comment by Ambrevar** [comment]
But we are releasing a new major version, so we can always break it!

No strong opinion on my end.

**Comment by aartaka** [comment]
> But we are releasing a new major version, so we can always break it!

I mean, we can, but why break what works fine :D The less changes one needs to make to their config, the better (and I say that as a person with ~1K lines of config -- a huge area for breakage :P)
