### ISSUE TITLE
`element-hints` on start page

### ISSUE THREAD

**Issue by aadcg** [atlas-engineer/nyxt#2257]
Notice that the "Start searching!" moves to an upper position when the prompt buffer pops up, thus the bug.

![2022-05-15_16:39:16](https://user-images.githubusercontent.com/45483512/168481258-21bbc6e8-8746-498c-8b23-91d68c4b78ec.png)
![2022-05-15_16:39:23](https://user-images.githubusercontent.com/45483512/168481260-998d7749-e00f-48b0-aab0-dcc34aaca6eb.png)

**Comment by Ambrevar** [comment]
I can reproduce.  Cc @aartaka

**Comment by aadcg** [comment]
@aartaka, I confess I didn't look into it, as I'm sure you'd fix this much faster. It must be something related to CSS I assume.
