### ISSUE TITLE
Some internal pages (e.g. annotations) display blank buffer on no data | Allow running code before internal page display

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#2259]
Which is confusing to the user.

We should display an HTML title at least, or echo a message, or both.

**Comment by aadcg** [comment]
I didn't understand it. Could you give an example? Thanks!

**Comment by aartaka** [comment]
Better: we should allow running arbitrary code *before* and *after* the page code is generated/loaded. This way, all the prompting for e.g. annotations can happen before the actual buffer is open/focused and can (ideally) even prevent it from happening if something's gone wrong.

One simple way to achieve this would be to use `:before` and `:after` (or a single `:around`) methods for those commands that need it.

**Comment by Ambrevar** [comment]
@aadcg Take annotations for instance.  If there is none, `show-annotations` displays a blank buffer.

**Comment by Ambrevar** [comment]
I've added the missing titles in a816a0c39df7e2e75920d33fb265b7dc16ce5e66.

The said we should probably still implement @aartaka suggestion.

Removing 3.0 tag since it's less urgent now.

**Comment by jmercouris** [comment]
The core issue here has been solved.
