### ISSUE TITLE
UI disparity due to `GDK_SCALE` and `GDK_DPI_SCALE`

### ISSUE THREAD

**Issue by aadcg** [atlas-engineer/nyxt#2260]
Both variables set to default values.

![none](https://user-images.githubusercontent.com/45483512/168583326-093407f4-9309-4e1d-8fcc-b098414184e4.png)

`GDK_SCALE` set to 2 and `GDK_DPI_SCALE` set to default.

![gdk-scale](https://user-images.githubusercontent.com/45483512/168583489-1b7b9a4b-47d1-46d2-adf1-ae1e5224210b.png)

`GDK_SCALE` set to 2 and `GDK_DPI_SCALE` set to 0.5. 

![gdk-scale-and-dpi](https://user-images.githubusercontent.com/45483512/168583582-180ba8c9-9257-4638-a0df-2ca9c00b30ec.png)

Proposal:
- Setting `GDK_DPI_SCALE` to a non-default value seems bad, so I'd take it out from the manual;
- Find a more reliable way to set the `prompt-buffer` height, since it seems not very sensible to occupy such a big proportion of the screen (as in screenshot 2).

**Comment by Ambrevar** [comment]
You are not saying what the problem is.  Is it that the prompt buffer should occupy a constant fraction of the vertical space?  If so, it's a simple GTK fix I believe.

**Comment by aartaka** [comment]
@aadcg, ping -- so what's the exact problem?

**Comment by aadcg** [comment]
As it can be read from the proposal in the original post, I think that `GDK_DPI_SCALE` is useless for high DPI screens. In the past it did help, but it seems to me that something changed in GTK. As suggested, we should get rid of references to it.

The second issue is whether it's sensible to set the prompt-buffer height to a constant proportion of the window's height by default. And should that be done at the level of GTK or JS?

**Comment by aadcg** [comment]
See 557446f6e.

**Comment by aartaka** [comment]
> The second issue is whether it's sensible to set the prompt-buffer height to a constant proportion of the window's height by default. And should that be done at the level of GTK or JS?

GTK manages window positioning and sizes, so prompt-buffer height is a GTK-side issue.

**Comment by aadcg** [comment]
What would be a good default? 1/4, 1/3? 

Would this make sense when the window isn't fully expanded?

**Comment by aadcg** [comment]
Pierre Neidhardt ***@***.***> writes:

> You are not saying what the problem is. Is it that the prompt buffer
> should occupy a constant fraction of the vertical space? If so, it's a
> simple GTK fix I believe.

That is one of the problems, yes.  I think the prompt buffer shouldn't
occupy more than 30% of the vertical space.

**Comment by aadcg** [comment]
The height of the prompt buffer was deliberately set by @jmercouris in 79782fdb29dab77163a2fdbaa923e099e2ee20fd.

It's also exactly a third of the default window height (768:256).

Closing, see 0e6ca14396d46904ecf619a5cd69781a5aab80b7.

**Comment by aartaka** [comment]
But then, maybe we should set it to one third of the actual window height?

**Comment by aadcg** [comment]
@aartaka I don't know how to do that. Does GTK give us that?

**Comment by aartaka** [comment]
> @aartaka I don't know how to do it. Does GTK give us that?

Yes (mostly copy-pasted from renderer/gtk implementation of `ffi-buffer-height`):
``` lisp
(gdk:gdk-rectangle-height
   (gtk:gtk-widget-get-allocation (nyxt/renderer/gtk::gtk-object (current-window))))
```
