### ISSUE TITLE
nyxt.socket in the wrong location

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#2261]
Recently I started noticing that nyxt.socket was put in `CURRENT-DIR/nyxt/nyxt.socket` instead of the usual spot.

However I can't reproduce right now.
Has anyone else experienced this?

**Comment by aadcg** [comment]
> Recently I started noticing that nyxt.socket was put in
> CURRENT-DIR/nyxt/nyxt.socket instead of the usual spot.
>
> However I can't reproduce right now.
> Has anyone else experienced this?

I never experienced it.

**Comment by aartaka** [comment]
I haven't experienced it either, but feels like some `uiop:getenv` plus `uiop:merge-pathname` somewhere deep in the path expansion logic :P

**Comment by jmercouris** [comment]
I've also not experienced this.

**Comment by Ambrevar** [comment]
Haven't seen this in more than a week, closing.

**Comment by Ambrevar** [comment]
Can you share the full trace / log?

Is this really about the socket file though?

**Comment by aadcg** [comment]
Not seeing it anymore...
