### ISSUE TITLE
Create file management features, something like Emacs' `dired` for Nyxt (left to do: (de)archivation)

### ISSUE THREAD

**Issue by pdelfino** [atlas-engineer/nyxt#2264]
**Is your feature request related to a problem? Please describe.**
I'm frustrated that I can't fully do file management tasks using Nyxt as an interface. I wish there was something like Emacs' dired available in Nyxt.

**Describe the solution you'd like**
`Dired` features such as:
- marking files
- copying and renaming files
- deleting files
- creating and extracting archives

**Describe alternatives you've considered**
Honestly, my alternatives have been using `dired` in Emacs or GNOME's Nautilus. I can't think of an alternative in Nyxt.

**Additional context**
There is a `file-manager-mode` available in Nyxt. But after doing a `describe-command` on it, it seems to be empty. Nyxt displays no source and bindings around it. Manual does not cover it. Not sure if it is a bug. I might be missing something, but I am not sure why it is available on master with the current content.

**Comment by Ambrevar** [comment]
Our file-manager indeed handles already quite a lot.
Might be broken on master though...

Archive extraction is missing, pull request welcome!

**Comment by jmercouris** [comment]
Right, but it is only in a prompt buffer interface, no? I think this is asking for something closer to dired!

I do not believe that we can do any of the things listed in the original request outside of the prompt buffer/open-file.

**Comment by Ambrevar** [comment]
Indeed, but like many other "prompt-buffer only" features, an easy fix which would be very cool to add is the ability to have a persistent prompt-buffer in place of a buffer!  This needs some thinking though...

**Comment by jmercouris** [comment]
Probably as an extension!
