### ISSUE TITLE
Backport nyxt.atlas.engineer articles to the manual

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#2266]
For 3.0 it'd be nice if our manual were more exhaustive with all the content that we ever wrote.

Some are obviously outdated.
We also need to adapt the style of course.  Some of the documentation may go into docstrings.

Lots of articles there. Any takes?

Cc @aadcg

**Comment by jmercouris** [comment]
This is a rather abstract task, and it is hard to say *when* it would be considered done, as we are constantly writing new articles. I suggest we use the issue tracker for concrete tasks that have finite considerations. 

There is a practice in goal setting that I believe we can adopt it is called S.M.A.R.T

https://www.atlassian.com/blog/productivity/how-to-write-smart-goals
