### ISSUE TITLE
Refactor clipboard and ring

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#2269]
`ring-source`  is not filled it anywhere. Maybe make an :after method for ffi-buffer-copy and ffi-buffer-paste and add trivial-clipboard:text to the ring?

But then we have multiple clipboard functions, some in source/clipboard, others in source/mode/document, others in source/renderer/gtk.

We need to trim some code!

**Comment by aartaka** [comment]
I've trimmed the clipboard API in 4f115db65668b2e0fd761593a87c804ec300768e and 57b6ebe8258ddd208c173361bbdaa46fd25bc8b3. Feel free to reopen if we can do better!

**Comment by Ambrevar** [comment]
Then I'll reopen! :)

- `%paste`, `%copy`, `%cut` should never be called directly, right?
  I suggest we replace all the calls with the corresponding `ffi-*` function.
  We could also merge their content into the default FFI method and not have a global parenscript.

Thoughts?

Thanks a lot for moving forward with this!

**Comment by Ambrevar** [comment]
- What about `copy-to-clipboard`?  Can we replace its calls with `ffi-buffer-copy`?  Maybe not because it takes a string as argument and does not rely on buffer content.

**Comment by aartaka** [comment]
> * What about `copy-to-clipboard`?  Can we replace its calls with `ffi-buffer-copy`?  Maybe not because it takes a string as argument and does not rely on buffer content.

Better: we can replace it with plain `(trivial-clipboard:text input)` :D 

I wish that `trivial-clipboard:text` was a method instead, so that we can have an `:around` or `:after` method for it...

**Comment by Ambrevar** [comment]
Nice, thank you!

**Comment by aartaka** [comment]
Follow-up: [my PR adding a hookable `content` method to `trivial-clipboard`](https://github.com/snmsts/trivial-clipboard/pull/13) had just gotten merged to upstream, which means that we can use/hook it given enough `trivial-clipboard` updates in distributions.

**Comment by aartaka** [comment]
Thanks :)
