### ISSUE TITLE
Loading libnyxt.so hogs the CPU

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#2271]
Today upon rebuilding the binaries I noticed that Nyxt hogs a CPU.
This is because of libnyxt.so.  If I remove the file, Nyxt works just fine.

@aartaka Any idea?

**Comment by aartaka** [comment]
Never experienced that, but I can guess that there's some segfault or memory mismanagement in libnyxt.so 😅

**Comment by Ambrevar** [comment]
You can't reproduce on master?  I'm building afresh, no config, and I experience it on every startup.

**Comment by aartaka** [comment]
No, not on master, I'm running Nyxt from sone 100 commits before master. But the libnyxt is pretty fresh, quite close to master.

**Comment by Ambrevar** [comment]
What's your commit?

**Comment by Ambrevar** [comment]
OK, the offending commit is between these 2.

After a bisect, I found it: be7801dc0ce1af5c028035e4dd4febafc9c033c3.

Any idea?

**Comment by aartaka** [comment]
Maybe lack of a callback? (҂⌣̀_⌣́)

**Comment by Ambrevar** [comment]
Can you reproduce?

In any case, can we revert or comment the offending code for the time being?

**Comment by aartaka** [comment]
Done in f88149b571c572beee3107c5c1459973b46efa11.

**Comment by aadcg** [comment]
Since WebExtension support will be optional for the 3.0 release, maybe this is not a priority anymore?

**Comment by jmercouris** [comment]
Agreed.

**Comment by jmercouris** [comment]
It is no longer part of the core.
