### ISSUE TITLE
Prompt(:?) - to colon or not to colon?

### ISSUE THREAD

**Issue by aadcg** [atlas-engineer/nyxt#2282]
It seems we're not consistent in the use of colons in our prompt messages. 

Any strong opinions?

**Comment by Ambrevar** [comment]
Examples?

**Comment by aadcg** [comment]
describe-any uses colon, whereas switch-buffer doesn't.

**Comment by Ambrevar** [comment]
Oh, I see, this is a remnant from old times.  I'll fix it.

**Comment by Ambrevar** [comment]
Done with c425e1bae8275be0401bb81e962c2b6b303a3abd.

**Comment by aadcg** [comment]
Did you push it?

**Comment by Ambrevar** [comment]
Oops!  Should be done now.
