### ISSUE TITLE
integration with ibus for multi-lingual input 

### ISSUE THREAD

**Issue by vanangamudi** [atlas-engineer/nyxt#2285]
**Is your feature request related to a problem? Please describe.**
I have been trying to move from firefox to nyxt for most of my workflow. Text-entry or input-method in nyxt is not integrated with ibus(in ubuntu/linux in general). nyxt can render Tamil script very well albeit in a poor font but it works nonetheless. 

**Describe the solution you'd like**
enable text entry via ibus to enter non english text and restrict text entry to editable text widgets to avoid triggering shortcut unwantedly(not sure if it possible, emacs integrates with ibus but this causes issues when giving commands via shortcuts/key-chords)

**Describe alternatives you've considered**
so far I have been typing in external editor or firefox for Tamil text and copy pasting it in(very tedious)

**Additional context**
![Screenshot from 2022-05-21 12-30-04-m](https://user-images.githubusercontent.com/1615718/169640284-1ab75f61-30f8-4ce6-8188-8634ff5d11ec.png)

**Comment by Ambrevar** [comment]
This is odd, the prompt buffer input is a regular GTK input, so it should work.  Are you able to input Tamil in another GTK3 program?  Which one?

About the font: this actually suggests that GTK3 supports is not fully operational on your system.
What's your OS / version?  Desktop environment?

**Comment by vanangamudi** [comment]
I am able to input Tamil into other applications. Please look at the screenshot.

"தமிழ் மொழி - Tamil language" typed into gedit editor

![Screenshot from 2022-05-21 15-13-53](https://user-images.githubusercontent.com/1615718/169645887-96883a79-abef-4655-a90e-6dd66e37f472.png)

**Comment by aadcg** [comment]
It seems not to be related to Nyxt, as I can use the russian input method.

**Comment by vanangamudi** [comment]
> It seems not to be related to Nyxt, as I can use the russian input method.

which input method do you use? ibus?

**Comment by aadcg** [comment]
> which input method do you use? ibus?

No idea honestly.  How can I check it?

**Comment by vanangamudi** [comment]
you check what is selected in Input Methods dialog under ubuntu.
![Screenshot from 2022-05-23 16-15-11](https://user-images.githubusercontent.com/1615718/169815815-5a3a8171-2a20-4335-92a6-b801cabee34e.png)

**Comment by aadcg** [comment]
I'm user a window manager and I'm not sure how to check it. Also, I don't have any DE installed.

@Ambrevar, do you use `exwm-xim`?

**Comment by Ambrevar** [comment]
This page may help: https://wiki.archlinux.org/title/Input_method

**Comment by aadcg** [comment]
Perhaps @pdelfino could confirm if he can use the portuguese input method in Nyxt, and confirm if he's using `ibux`.

`xim` doesn't seem to work in Nyxt, but I have no idea why.

**Comment by pdelfino** [comment]
> Perhaps @pdelfino could confirm if he can use the Portuguese input method in Nyxt, and confirm if he's using `ibus`.

I am using GNOME (as DKE) in NixOS. This is my OS [config file](https://github.com/pdelfino/my-nixos-config). Gnome's default input method is ibus. I did not change the default.

I have done a few tests in Nyxt with André, such as: writing an email with multiple characters used in Portuguese (â,ã,ó,çã, etc), opened a file called `andré.org` with Nyxt. And there was no problem.

Following André's suggestion, I am adding a `non-reproducible` tag here.

**Comment by aadcg** [comment]
Not reproducible.
