### ISSUE TITLE
Help function is not found

### ISSUE THREAD

**Issue by Gavinok** [atlas-engineer/nyxt#2287]
I haven't determined what this should be calling however the base-mode has a binding to a function called `help` which doesn't seem to exist. There are multiple references to it however.

https://github.com/atlas-engineer/nyxt/blob/b6020ef4c06d0dd40097c9dd530303ade334a00a/source/mode/base.lisp#L34

This is likely the same kind of issue seen in https://github.com/atlas-engineer/nyxt/pull/2274 assuming there was a previouse command called `help`

**how to reproduce**

Simply open nyxt and type `f1 f1`

**Comment by aadcg** [comment]
The command was removed in c247e8282.

Would you like to clean up all of these references and send open a PR? :)
