### ISSUE TITLE
Names of predicates

### ISSUE THREAD

**Issue by aadcg** [atlas-engineer/nyxt#2290]
It is common practice to add the `-p` suffix to predicates. However, the dash is not necessary when the name has a single syllable. 

Think of `numberp`, `listp`, etc. I'd prefer if we'd follow the same convection is our codebase.

Anyone opposes? @jmercouris @aartaka @Ambrevar @pdelfino

**Comment by Ambrevar** [comment]
We did discuss this in the past, and we decided to always use a dash.
Rational: it's more readable.  Some single-word-predicates can be jarring to read otherwise.

**Comment by aadcg** [comment]
Ok, I can agree with that!

**Comment by Ambrevar** [comment]
(Note: Personally I did vote to end predicates with `?` as in Scheme since it's the most readable.)

**Comment by pdelfino** [comment]
> (Note: Personally I did vote to end predicates with `?` as in Scheme since it's the most readable.)

I was not working for Atlas when the discussion happened, but for the record, I agree with `?`. Racket also [uses it](https://docs.racket-lang.org/predicates/index.html).

For me, the aesthetics hierarchy would be, first, `number?` better than `number-p` which is better than `numberp`.

At the end of the day... They are all reasonable notations... Better focus on the features to build and bugs to solve :)

**Comment by jmercouris** [comment]
I like to refer to one of our key decision making metrics: will the existing solution kill us? No, then we can agree to it 🙃
