### ISSUE TITLE
Function nyxt-init-file no longer exists?

### ISSUE THREAD

**Issue by hendursaga** [atlas-engineer/nyxt#2294]
In the latest Nyxt, `nyxt-init-file` no longer appears to exist, but it is still referenced in the README. Whatever happened to it?

**Comment by aadcg** [comment]
Thank you for reporting! We now call it `nyxt-config-file`, see a3af4169a.

We're going to review all of the documentation just before 3.0, so that we only need to fully review it once. Hang tight!
