### ISSUE TITLE
Rename `visual-mode`?

### ISSUE THREAD

**Issue by aadcg** [atlas-engineer/nyxt#2300]
The name is very general, thus hard to guess what it does. 

Firefox calls a similar feature `caret-mode`.  We could also go with `cursor-mode`. Thoughts?

**Comment by aartaka** [comment]
Note that Caret mode is extremely basic in all browsers, while our `visual-mode` allows easier initial navigation and additional commands to move between e.g. paragraphs.

**Comment by aadcg** [comment]
Oh, so the name comes from the editor of the beast. No wonder I didn't know about it!

Your second observation doesn't convince me. You put a cursor/caret on the screen and you define the motions you want. 

If you mean that using a familiar term from other projects (caret mode) doesn't do justice to what we do, then we agree!

**Comment by aartaka** [comment]
We've changed too much already, ahah (>_<)

**Comment by aadcg** [comment]
I agree, we can all live with it for now.

**Comment by edgar-vincent** [comment]
I think `visual-mode` is fine. Users of Emacs' `evil-mode` will be familiar with it too.
