### ISSUE TITLE
Add 2-series -> 3->series migration guide?

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#2301]
Considering _configuration_ is the main selling point of Nyxt, having a configuration / extensions migration guide would not be too much to ask for...

Just like the manual and the changelog, I can see how embedding it as a .lisp file would be more appropriate than an article that's prone to go quickly out-of-date (not mentioning that it wouldn't be accessible offline, etc.).

Agreed?
Thoughts?

There is lot's of stuff to add in there!

**Comment by aartaka** [comment]
Definitely!

**Comment by Ambrevar** [comment]
I got started with f8a3bcadbd729ca544260bd32126d73d0c807ef2.

Everyone, feel free to complete it as you update your `config.lisp` :)

**Comment by jmercouris** [comment]
A fascinating suggestion.

**Comment by Ambrevar** [comment]
#2410 is merged, but we still need to fill in the guide before 3.0.0.

**Comment by aadcg** [comment]
We should re-read `migration.lisp` release before the new release to make sure we didn't forget anything.
