### ISSUE TITLE
Restore `(in-package ...)` everywhere

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#2304]
In https://github.com/atlas-engineer/nyxt/commit/23dbd0924c755ba43b570931e184aab02eececfc I replaced all the `(in-package ...)` with `nyxt:define-and-set-package`.

Problem: this breaks SLIME and SLY:
- `C-c C-c` will evaluate the form in the REPL's current package instead of the one of the file.
- `C-c ~` (`sly-mrepl-sync`) won't switch package.

I propose to re-add the `(in-package ...)` expressions everywhere.
Shall we not switch package in `nyxt:define-and-set-package` then?  If so, we should probably rename it to `nyxt:define-package`.

Thoughts?

**Comment by aadcg** [comment]
I switch packages manually, but I understand the concern.

Your suggestion seems good to me.

**Comment by aartaka** [comment]
Yes, `define-and-set-package` should've been just `nyxt:define-package` in the first place :P

**Comment by Ambrevar** [comment]
Fixed with c5406683c0aba2e8d7444c8bd73ce8a84f07f2f8.

**Comment by jmercouris** [comment]
Thanks Pierre!
