### ISSUE TITLE
Fix history test to use new file

### ISSUE THREAD

**Issue by aadcg** [atlas-engineer/nyxt#2309]
If I run the tests locally from SLY/SLIME (by pressing `,test-system RET nyxt/tests RET`) I see that some tests related to global history fail. However our CI (Github actions) doesn't complain when pushing changes.

I didn't look into it at all, but it seems odd.

**Comment by Ambrevar** [comment]
The tests need fixing: basically, they are not containerized and they will load _your_ local history.
In the CI, there is no history so everything is fine.

**Comment by Ambrevar** [comment]
Done in #2465.
