### ISSUE TITLE
Status buffer and status area

### ISSUE THREAD

**Issue by aadcg** [atlas-engineer/nyxt#2310]
The former concept appears in the codebase, whereas the latter appears in the documentation.

Aren't they synonyms? Could we stick to status buffer?

@pdelfino @jmercouris @aartaka @Ambrevar

**Comment by aartaka** [comment]
"Status buffer" is more correct entity-wise, while "status area" is easier to understand. If I were to choose, I'd pick status buffer for no particular reason.

**Comment by Ambrevar** [comment]
Agreed to stick to "status buffer" everywhere.  For now at least.

Some blessed day we will rename all "buffer" to "view" and then everyone will be happy again! :D
