### ISSUE TITLE
Lock package :nyxt and all subpackages?

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#2316]
Seems like a good idea to prevent accidental modification of the :nyxt package and its packages. 

Thoughts?

Note: Only supported on SBCL.

**Comment by aadcg** [comment]
What does locking mean here? Users should always hack on `nyxt-user`, doesn't that suffice?

**Comment by aartaka** [comment]
We should programmatically reprocude the convention here, I suppose :)

**Comment by Ambrevar** [comment]
> We should programmatically reproduce the convention here, I suppose :)

What do you mean?

**Comment by aartaka** [comment]
I mean enforcing the convention of not polluting `nyxt` via the means that compiler/language provides.

**Comment by Ambrevar** [comment]
So you're OK with this change?

**Comment by aartaka** [comment]
Yes!

**Comment by Ambrevar** [comment]
See #2320.
