### ISSUE TITLE
Pressing `return` in lisp-repl does nothing

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#2323]
@aartaka Looks like `lisp-repl` is broken on master :p

**Comment by aartaka** [comment]
Wait, why do you press `return` there? Press `C-return` :D

**Comment by aadcg** [comment]
Right @aartaka.

Suggestions about the REPL:
- call `focus-first-input-field` when the REPL starts by default (or something that has the equivalent behaviour)
- how do I insert a line? Can we bind `RET` to that by default? 

Personally, I like (multi-line) prompts to behave the way they do in a text file. `C-j` sends send input and `RET` inserts a newline (and may indent).

**Comment by Ambrevar** [comment]
Yup, having `ret` do nothing is _very_ confusing :p 

Other bug: on inserting `(` I get this error:

```
<WARN> [18:39:21] Warning: JavaScript error: GError: Domain: "WebKitJavascriptError", Code: 699, Message: nyxt:nyxt/repl-mode:lisp-repl:1:40: TypeError: null is not an object (evaluating 'document.querySelector('#input-buffer').selectionStart')
```

**Comment by Ambrevar** [comment]
Something else (sorry for the report spam): clicking on the arrows is a bit hard, one has to hit the character very precisely.  If you hit the box but not the character, it won't do anything.

**Comment by aadcg** [comment]
@Ambrevar, the hints help a bit :p

**Comment by aartaka** [comment]
Oh wait, now I get it! Indeed, the `input` in `lisp-repl` is not a multi-line one. Maybe we should use `textarea`s then...

**Comment by Ambrevar** [comment]
Definitely! :)

**Comment by Ambrevar** [comment]
See #2343 for a bunch of fixes which should address the aforementioned concerns.

**Comment by aadcg** [comment]
> shouldn't we make past inputs immutable?

In #2223 I made a reference to it. Quote:

> A richer interface (think Emacs' comint) gives the user's caret complete freedom across all inputs and outputs. A (hard) question immediately arises: should older inputs and outputs be read-only (Emacs today says no, for instance)?

I think older inputs shouldn't be immutable, but you must be able to re-run that input that replace the corresponding output.

**Comment by aadcg** [comment]
In my opinion, it's ok. If you were to reproduce a REPL session, you'd re-run the inputs.

**Comment by Ambrevar** [comment]
Not necessarily about sessions, but what about simply "at a glance"?  Seeing inconsistent input / output pairs is unfortunate.

**Comment by aadcg** [comment]
I think the only thing we should do would be to trigger a visual sign of that inconsistency.
