### ISSUE TITLE
Move `command-information` and friends from `input.lisp` to `help.lisp`

### ISSUE THREAD

**Issue by aadcg** [atlas-engineer/nyxt#2326]
`command-markup`, `command-docstring-first-sentence`, `command-information` and `list-command-information` are just helpers to our `help` system.

Do we agree? @aartaka @Ambrevar @jmercouris @pdelfino

**Comment by aartaka** [comment]
Yes, it belongs to help, I guess.

**Comment by aadcg** [comment]
I'm expanding it to be more general.

**Comment by Ambrevar** [comment]
@aadcg Mind that I'm already moving lots of help-related stuff in #2320.

**Comment by aadcg** [comment]
Ok @Ambrevar!

**Comment by jmercouris** [comment]
I am also in accord!

**Comment by aadcg** [comment]
Just to clarify, expanding means having `class-markup` and friend so that we can enrich the interactivity of our manual.

**Comment by aadcg** [comment]
Partly addressed with ee35994de.

[Note to self.]
> Expanding means having class-markup and friends so that we can enrich the interactivity of our manual.
The idea would be that a significant part of the manual would be generated from docstrings.
