### ISSUE TITLE
Review visibility of all modes on status buffer

### ISSUE THREAD

**Issue by aadcg** [atlas-engineer/nyxt#2331]
Following #2314, we must check that our visibility defaults make sense for all modes so that it's consistent throughout the `3-series` releases.

**Comment by aadcg** [comment]
Personally I think it would make sense to hide from the status buffer all modes related to keyschemes, except vi since it has a insert and normal mode.

Thoughts?

**Comment by Ambrevar** [comment]
I disagree, as I often switch between them and it can be very confusing to not know in which scheme you are.

**Comment by aadcg** [comment]
Fair enough! I think our defaults are ok then. Feel free to re-open if needed.
