### ISSUE TITLE
Fails to read any init.lisp file i make

### ISSUE THREAD

**Issue by jdpedersen1** [atlas-engineer/nyxt#2334]
**Describe the bug**
nyxt installs, launches, and runs fine, however; no auto-config.lisp is created, and when I create a init.lisp file in my $HOME/.config/nyxt/ dir, nyxt does not read it.
shows it is loading the files but the settings do not take effect.

**Precise recipe to reproduce the issue**

For website-specific issues:
Can you reproduce this issue with Epiphany / GNOME Web (https://wiki.gnome.org/Apps/Web)?

**Information**
- OS name+version:Void linux glibc x86-64
- Graphics card and driver:
- Desktop environment / Window manager name+version:herbstluftwm 0.9.4
- How you installed Nyxt (Guix pack, package manager, build from source):package manager, (wont build from source, get makefile:70: error 1)
- Information from `show-system-information`:

  If you can't run `show-system-information`, try `nyxt --system-information` from
  a shell.  It this still does not work, please provide the following:
  - Nyxt version (from the `nyxt-version` command or `nyxt --version` from a shell): 2.2.4
  - Lisp implementation/version (if built from source):sbcl 2.2.2 void 1
  - Kernel name+version:linux 5.15.41_1
  - WebKitGTK+ | QtWebEngine version:webkit2

**Output when started from a shell**
<INFO> [14:54:05] Listening to socket "/run/user/1000/nyxt/nyxt.socket".
Nyxt version 2.2.4
<INFO> [14:54:05] Loading Lisp file "/home/jake/.config/nyxt/init.lisp".
<INFO> [14:54:05] Loading Lisp file "~/.config/nyxt/statusline.lisp".
<INFO> [14:54:05] Loading Lisp file "~/.config/nyxt/stylesheet.lisp".

**Comment by jdpedersen1** [comment]
my mistake somewhere with syntax, works now

**Comment by jmercouris** [comment]
Thank you for the update :-)
