### ISSUE TITLE
ffi-display-url should specialize against browser?

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#2340]
`ffi-display-url` is the only FFI method which does not specialize against anything.

So when we define it in `gtk.lisp`, we actually redefine the default method (which triggers a warning by the way).

This means that if we introduce a new renderer in the future, we won't be able to switch between renderers.  Just because of 1 method which is called just 1 time in the entire code base!

So I suggest to specialize it against `browser`.  Agreed?

**Comment by aadcg** [comment]
Yes!

**Comment by jmercouris** [comment]
This is assuming that both renderers are loaded at the same time and switchable. An unlikely scenario due to many constraints. In any case, it could specialize against browser, why not :-)

**Comment by Ambrevar** [comment]
Done with d79bbe50c3c6d4e0e6ac98ffd69962c9ce346fc0.
