### ISSUE TITLE
Manual: Document programming conventions

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#2345]
@aartaka underlined that in Nyxt we use a bunch of idioms and conventions that we could be useful, if not necessary to document.  In particular for extension writers and new contributors.

Here are a few I can think of, please add yours!

- Prefer `first` and `rest` over `car` and `cdr` respectively.
- Use `define-class` instead of `defclass`.
- Use `nyxt:define-package` if you want the default imports and the default package nicknames (e.g. `alex`, `sera`, etc.).
- Use the `maybe` and `maybe*` types instead of `(or null ...)` and `(or null (array * (0)) ...)` respectively.
- Prefer `defmethod` over `defun` if one of the arguments is a user-class.
  This allows for writing specialization of subclasses.
- Use `funcall*` to not error when function does not exist.
- `customize-instance` is reserved for users.
   Initialize slots in `initialize-instance :after`.  Set up the rest of the class in `customize-instance :after`.  Bear in mind that anything in this last method won't be customizable.
- Almost all files should be handled via the `nfiles` library.
- Specialize `print-object` for recurring class instances.
- (Coming soon) `(setf SLOT-WRITER) :after` is reserved for "watchers", i.e. handlers that are run whenver the slot is set.  The `:around` method is not used by watchers, and thus the watcher may be overridden.
- Mention link (or dump?) https://www.cliki.net/Naming+conventions.
- Mention `%foo%` convention for special local variables.
- Explain `-p` predicate convention (not exactly CL).
- Maybe: Conversion functions `FROM->TO` or `->TO` for generic functions.  The only one that comes to mind is `url` which does not follow this  convention :)
- Uses of Serapeum:
  - `sera:eval-always`
  - `export-always`
  - `->` (declaimed types)
- Prefer the term `url` over `uri`.
- All URLs should have the `quri:uri` type.  If you need to manipulate a URL string, call it `url-string`.
- Paths should have the `cl:pathname` type.
- Prefer classes over structs.
Rationale: slots have doc.  Full CLOS.
Struct have read-only slots (but classes can be used in this way), perf (does
not really matter).
- Classes should be usable with just a `make-instance`.

**Comment by aartaka** [comment]
@aadcg has recently asked me about the variable and function naming conventions (earmuffs, percent signs, plus signs, trailing asterisks etc.), that should be there too, I suppose :)

**Comment by Ambrevar** [comment]
Scheme uses "%foo" (single percent), we use "%foo%".

It comes from https://www.cliki.net/Naming+conventions:

> %foo% 	local special variable

**Comment by aartaka** [comment]
We also have `initial->final` and `match?` Scheme-ish conventions, so our particular naming conventions are quite special, no hurt in documenting those :)

**Comment by Ambrevar** [comment]
`initial->final` is indeed from Scheme, we have a few of them in the code base (e.g. `value->html`).
The CL convention is `initial-to-final`, but I personally prefer `->`, it's readable and easier to "grep".

About the `?`: I believe it's not used anywhere but internally (for some local scope names).

Proof (that CL is awesome? :p):

```lisp
(sera:filter
 (lambda (s) (and (or (not (symbol-package s))
                      (subpackage-p (symbol-package s) (find-package :nyxt)))
                  (sera:string-suffix-p "?" (symbol-name s))))
 (package-symbols nil (nyxt-packages)))

(NYXT/DOCUMENT-MODE:%CLICKED-IN-INPUT?
 NYXT/PROMPT-BUFFER-MODE::AOK?
 NYXT/PROMPT-BUFFER-MODE::KEY?
 NYXT/BLOCKER-MODE::COMMENT?
 NYXT/BLOCKER-MODE::CUSTOM-HOSTS?
 NYXT/BLOCKER-MODE::EMPTY-LINE?
 NYXT/DEBUG::SUBSYSTEM?
 NYXT/DEBUG::MATCH?
 NYXT/HINT-MODE::HAS-HREF? VI-MODE?
 MULTILINE-FORM?
 ALL-VALUES-KEYWORDS?
 RESULT?
 EDITABLE?
 AOK?
 EXPLICIT?
 SETTER?
 KEY?
 RECEIVED?)
```

Note that `aok?` and `key?` come from Serapeum.

So we can document the `-p` convention instead since it's the one we are officially using.

If some day we switch to the Scheme one, I'd be all for it! :)

**Comment by Ambrevar** [comment]
Another one that we currently don't have, but we should: a function naming convention that indicates the function is blocking (e.g. waiting on a channel).

Typically we would have a non-blocking function and the blocking alternative.  So what about `FOO` and `FOO-wait`?  Or `FOO-waiting`?  Or `FOO-blocking`?

**Comment by aadcg** [comment]
I personally prefer `wait-on`.

**Comment by Ambrevar** [comment]
Done with c3db25641523f71d1434e7677494d12fd188e45b.  We can always extend it from there.
