### ISSUE TITLE
Extend common-settings to include more

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#2351]
Some very useful settings:

- [ ] keybinding style should be a drop-down menu listing all scheme _dynamically_ (so as to include extensions).
- [ ] Same for theme styles.  Need to display the preview dynamically then.
- [ ] Place "Edit user files" at the top.
- [ ] Restore session: always, ask, never.
- [ ] Make default browser. ~~(Need to program it, see https://stackoverflow.com/questions/57667116/how-do-i-set-the-default-browser-for-xdg-open-on-centos-7-if-xdg-settings-has-no).~~
  Code-ready, see #2439.
- [ ] Spell check language (it's a mode, should we have per-mode settings?)
- [ ] download directory.
- [ ] Default modes.
- [ ] proxy (also a mode)
- [ ] "set default new buffer URL" should have suggestions like "nyxt:new", "nyxt:dashboard".
- [ ] Customize search engines.

See also #2296.

**Comment by aartaka** [comment]
Sone more:
- Cookie settings.
- Intelligent Tracking Protection (it's part of `reduce-tracking-mode`, but maybe we should factor it out).
- [Text editing keybindings](http://tiborsimko.org/emacs-bindings-in-gtk-apps.html).
- Font families (should we add it to `theme`?)

**Comment by aadcg** [comment]
@aartaka, it's on my list but I'm still not actively working on it!

**Comment by aartaka** [comment]
> @aartaka, it's on my list but I'm still not actively working on it!

No pressure then :)

**Comment by aadcg** [comment]
@Ambrevar what can we achieve for 3.0 from this list?

**Comment by Ambrevar** [comment]
#2408 I believe.  Help welcome there... :p

**Comment by aartaka** [comment]
I think that this is actually 3.0-critical, because the current screen is almost useless and we need a robust set of configs in the new release \~_\~

**Comment by aartaka** [comment]
From https://github.com/atlas-engineer/nyxt/commit/e5c8920d2a1284ed0538ecc3738abcebcae77e51: allow configuring prompt buffer keyschemes too.
