### ISSUE TITLE
Certificate-exception mode enabled by default? why

### ISSUE THREAD

**Issue by r3k2** [atlas-engineer/nyxt#2353]
Version 3-1203-g9471313b
To my surprise, trying to troubleshoot my modes I notice this is on in all websites...
This should be off by default and enabled only as needed. I have check my config see if I by mistake have turned on but no.
```
<INFO> [20:10:31] Base mode enabled.
<INFO> [20:10:31] Document mode enabled.
<INFO> [20:10:31] Spell-check mode enabled.
<INFO> [20:10:31] Autofill mode enabled.
<INFO> [20:10:31] Search-buffer mode enabled.
<INFO> [20:10:31] Hint mode enabled.
<INFO> [20:10:31] Base mode enabled.
<INFO> [20:10:31] Document mode enabled.
<INFO> [20:10:31] Password mode enabled.
<INFO> [20:10:31] History mode enabled.
<INFO> [20:10:31] Bookmark mode enabled.
<INFO> [20:10:31] Annotate mode enabled.
<INFO> [20:10:31] Certificate-exception mode enabled.
<INFO> [20:10:31] Vi-normal mode enabled.
<INFO> [20:10:31] Reduce-tracking mode enabled.
<INFO> [20:10:31] Reload the buffer for no-script-mode to take effect.
<INFO> [20:10:31] No-script mode enabled.
<INFO> [20:10:31] Force-https mode enabled.
<INFO> [20:10:31] Blocker mode enabled.
```

**Comment by Ambrevar** [comment]
Note to myself: Turn mode enabling to `log:debug`, since this is way too verbose!

`certificate-exception-mode` has been the default since Nyxt 2.0.0.
Why do you think it's a bad idea to have it on by default?  Most browsers do handle certificate exceptions by default.

**Comment by r3k2** [comment]
@Ambrevar Hello, hmmm in this case maybe I am confused of what it does on nyxt, I though it will enable for expired and bad certs to be allowed, as when a site cert is expired or not valid, has a self-cert on it etc. On other browsers by default this is all denied and you have to "create a exception" to enable it.

**Comment by aadcg** [comment]
@r3k2, it's my fault due to commit d5fdf0134. The idea was that toggling a mode would notify the user in the echo area, but I didn't take into account that the message would also be triggered everytime the modes are instantiated.

**Comment by aadcg** [comment]
@Ambrevar you went ahead and did it on 20fe551a0 :p

Thanks!

**Comment by r3k2** [comment]
@Ambrevar ha ha ha ok that clears it up, :100:  thank you for the details.
