### ISSUE TITLE
Render text/gemini documents served via HTTP

### ISSUE THREAD

**Issue by slondr** [atlas-engineer/nyxt#2356]
**Is your feature request related to a problem? Please describe.**
Nyxt is one of the only user-agents out there that handles both HTTP/HTML and gemini/gemtext really well. However, support for those protocols and document formats is segregated right now. Connecting to an HTTP server which serves a gemini document, with the correct mime type, results in Nyxt rendering the source of the document as plain text rather than rendering the gemtext into an HTML document, like it does when the exact same document is accessed via gemini://

**Describe the solution you'd like**
Bring support for rendering gemtext to the HTTP world!

**Comment by Ambrevar** [comment]
CC @aartaka

**Comment by aartaka** [comment]
That's gotta be complicated, given that WebKit does not allow us handling MIME types, except for redirecting the URLs or setting some special HTML for the yet-to-be-loaded page. The best course of action would be a `request-resource-handler` that, when the `mime-type` of the `request-data` is `text/gemini`, uses `webkit_web_view_load_html`, processing the Gemtext into HTML and setting it into the view.

**Comment by aartaka** [comment]
3427eb97a389c41025903c3e8a97bb265d006651 should enable this, but I cannot test as I know no websites serving `text/gemini` over plain HTTP. @slondr, any suggestions?

**Comment by slondr** [comment]
Wow, that was pretty amazing turnaround!

@aartaka, try: https://ericlondr.es/gmi

**Comment by aartaka** [comment]
@slondr, I tested it on this page and fixed some logic flaws in the implementation. Now it should work perfectly :)

**Comment by slondr** [comment]
Stellar! Thanks!

**Comment by aartaka** [comment]
Closing as completed then.
