### ISSUE TITLE
Buffer ID type should probably not be uninterned symbols (gensym)

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#2361]
In commit e176a24636a9377a3af9b931740efb4a95a8b5a8 we switched from `string` `ID` to `gensym` / uninterned symbols.

While it makes sense use symbols (see https://github.com/atlas-engineer/nyxt/issues/2098), being uninterned they are not comparable.  Thus

```lisp
> (eq '#:|1| '#:|1|)
NIL
```

As a result, `buffers-get` always fails :(

What shall we do then?  Turn `new-id` to this?

```lisp
(intern (symbol-name (gensym "")))
```

Drawback: it pollutes the obarray.
Or else @aartaka 's suggestion:

```lisp
(parse-integer (symbol-name (gensym "")))
```

**Comment by Ambrevar** [comment]
See #2357.

**Comment by aadcg** [comment]
@aartaka's suggestion seems sound, but I might not have the best overview.

**Comment by Ambrevar** [comment]
Yup, I'll apply the change.

**Comment by jmercouris** [comment]
Thanks :-)
