### ISSUE TITLE
Version auto-config?

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#2373]
auto-config is likely to not be compatible across major versions of Nyxt.
So it makes sense to version it, a bit like we do with the history.

There are some differences though:
- The history is a serialized data-structure which we wrap with a `(list VERSION HISTORY)`.  We cannot do that for auto-config.
- The history is something that's we prompt the user to load (or not), so it's easy to report a version mismatch and the user can decide if they still want to try to load it.
- Error handling is also different: with the history, in case of error we just set the history to the default value.  With auto-config, we potentially restart the browser!

All things considered, I believe that 

- the versioning should be done in the filename, so we would have `auto-config.3.lisp` for the upcoming version 3.
- We can detect previous versions and ask to import it if no auto-config.CURRENT-VERSION exists.  We can use some smart importer (which we can tie to our migration guide). 
  -  On import failure, report the fail and start as usual (with no auto-config).    
  - On import success, try to start.  
    - After startup completes (without error) only then we write the new auto-config.  
    - If there is an error during startup, restart the browser with an error message, but this time do not ask to import the auto-config.

**Comment by Ambrevar** [comment]
I really meant it with a dot, so `auto-config.3.lisp`, since periods can be used to separate the parts of the file name, semantically, so here "NAME.VERSION.EXTENSION".

**Comment by jmercouris** [comment]
A well reasoned argument. You could also make the same argument for the init/config file.

**Comment by Ambrevar** [comment]
I'm wondering this as well... Should we?  Because the user could very well use the same file with reader macros, like `#+(or NYXT-3 NYXT-4)`, etc.

**Comment by aadcg** [comment]
But then, couldn't the auto-config be generated with reader macros as well?

**Comment by Ambrevar** [comment]
We cannot guess the future! :p 

For instance, in version 3 we use `FOO`.  Version 4 removes it.  But `FOO` was already written without a feature macro, so the auto-config will fail to load.

**Comment by Ambrevar** [comment]
Auto-config is now suffixed with the major version number in 6844481dbad1144a3e6b23d83e18c81f69cfee3b.

I believe we won't version the path of `*config-file*` for the aforementioned reason, thus I'm closing this.  If you disagree, feel free to reopen.
