### ISSUE TITLE
Allmost all bookmarks are removed when you remove just one

### ISSUE THREAD

**Issue by shamazmazum** [atlas-engineer/nyxt#2376]
**Precise recipe to reproduce the issue**
Collect some bookmarks (like 10-20). Try to remove one bookmark in the `*Bookmarks*` buffer (shown by `list-bookmarks` command) by pressing a cross. After a while you will get almost all bookmarks removed. Maybe you need to remove two bookmarks for this to work.

Nyxt built from f4acb71 with bundled dependencies.

**Comment by shamazmazum** [comment]
Pure code inside `files:with-file-content` in `delete-bookmark` works fine. So this must be effects of `files:with-file-content` which destroy bookmarks file.

**Comment by shamazmazum** [comment]
Sorry, that was a bit older commit. Now I get something like

    <WARN> [21:22:20] Warning: Error when running NIL: The function COMMON-LISP:NIL is undefined.

similar to #2377. That must be fixed first.

**Comment by shamazmazum** [comment]
Oops, I was wrong, the error is in pure code :) Fixed in #2377

**Comment by Ambrevar** [comment]
To clarify, is this fixed in #2377?  I've just tested and it seems to work fine on my side when deleting a dozen bookmarks.

**Comment by shamazmazum** [comment]
Oh, this issue can be closed now.
