### ISSUE TITLE
Mixin metaclass naming issue

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#2382]
I'm realizing that I misnamed `mixin-class`: it's actually more of a dereference class, since the "mixin class" is that one that's inherited from, not the other way around.

How shall we name this, then?  Is there a conventional name for this use cases?

**Comment by aartaka** [comment]
What we do with `mixin-class`es is loosely what conventional object oriented programming gurus call [Dependency Injection](https://en.m.wikipedia.org/wiki/Dependency_injection). Maybe `injected-class`?

**Comment by aartaka** [comment]
Or a mere `interface-class`?

**Comment by Ambrevar** [comment]
`interface-class`, in my understanding, exposes protocols and the like.  Here `renderer-buffer`, etc. is only meant to create a dereference to the future `gtk-buffer` class.

`injected-class` is fine.
Or else `dereference-class`?

**Comment by aartaka** [comment]
I expect that we'd have to have protocol specs for our mixins someday, so `interface-class` could make sense then. 

In the meanwhile, `injected-class` sounds most reasonable.

**Comment by hendursaga** [comment]
"There are only two hard things in Computer Science: cache invalidation and naming things." - Phil Karlton

**Comment by Ambrevar** [comment]
Sure thing! :p 

Done with 1f73b949dad8e2e94d175e49cfd95e7035a67c85.  I went for "interface class" in the end, because I think you are right @aartaka , it might serve as interfaces some day, plus "injected-class" sounded really confusing.

**Comment by aartaka** [comment]
> Done with [1f73b94](https://github.com/atlas-engineer/nyxt/commit/1f73b949dad8e2e94d175e49cfd95e7035a67c85). I went for "interface class" in the end, because I think you are right @aartaka , it might serve as interfaces some day, plus "injected-class" sounded really confusing.

It could be a mere `interface`, as it's a valid term on its own.

**Comment by Ambrevar** [comment]
You mean `interface` instead of `interface-class`?  But since it's a metaclass, I believe it's good practice to suffix it with `-class`.

**Comment by aartaka** [comment]
But then, are interfaces actually classes?

Just joking, I'm too tired of semantic discussions to proceed with this one :D But in this case it feels right to call it `interface`.
