### ISSUE TITLE
Buggy nyxt-config-file

### ISSUE THREAD

**Issue by hendursaga** [atlas-engineer/nyxt#2384]
**Describe the bug**

`nyxt-config-file` appears to always return the config file that Nyxt was launched with, regardless of if a subpath is given. It is possible this is a bug in `nfiles` but not entirely sure yet. 

**Precise recipe to reproduce the issue**

It does not really matter what the config file's are, so `touch /tmp/empty.lisp`, `nyxt -C -i /tmp/empty.lisp`, and then, going into the Lisp REPL, you can run the following:

NYXT-USER> (nyxt-config-file)
#P"/tmp/empty.lisp"
NYXT-USER> (nyxt-config-file "slynk")
#P"/tmp/empty.lisp"
NYXT-USER> (nyxt-config-file "slynk.lisp")
#P"/tmp/empty.lisp"

**Information**

```
Nyxt version: 2.1.1-2720-g232eddcf
Renderer version: GI-GTK
Operating system kernel: Linux 5.10.0-15-amd64
Lisp implementation: SBCL 2.2.5 (Dynamic space size: 3221225472)
Features: (:WEBKIT2 :WEBKIT2-2.36 :WEBKIT2-CORS-ALLOWLIST :WEBKIT2-PASTE-PLAINTEXT :WEBKIT2-TRACKING :WEBKIT2-MUTE :WEBKIT2-EMOJI :WEBKIT2-MEDIA :WEBKIT2-SANDBOXING :GTK-3-22 :GTK-3-20 :GTK-3-18 :GTK-3-16 :GTK-3-14 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6 :GTK-3-4 :GTK :GDK-3-22 :GDK-3-20 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12 :GDK-3-10 :GDK-3-8 :GDK-3-6 :GDK-3-4 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF :GLIB-2-30 :GLIB-2-32 :GLIB-2-34 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42 :GLIB-2-44 :GLIB-2-46 :GLIB-2-48 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56 :GLIB-2-58 :GLIB :NYXT-UNSTABLE :NYXT-G232EDDCF :NYXT-2.1.1 :NYXT-2.1 :NYXT-2 :FSET-EXT-STRINGS :CUSTOM-HASH-TABLE-NATIVE :SWANK :PLUMP-UTF-32 :PARENSCRIPT :GLOBAL-VARS :DECLARE-TYPES :NAMED-READTABLES :LPARALLEL :21BIT-CHARS :CLOSER-MOP :CL-PPCRE-UNICODE :CL-UNICODE :CL-PPCRE :CHUNGA :FLEXI-STREAMS :BORDEAUX-THREADS :LPARALLEL.WITH-CLTL2 :LPARALLEL.WITH-CAS :LPARALLEL.WITH-STEALING-SCHEDULER :SPLIT-SEQUENCE CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64 CFFI-FEATURES:UNIX :CFFI CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP :FAST-IO-SV :FAST-IO :CL-JSON-CLOS :CL-JSON :SBCL-USES-SB-ROTATE-BYTE CHIPZ-SYSTEM:GRAY-STREAMS :THREAD-SUPPORT :ASDF3.3 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX :NON-BASE-CHARS-EXIST-P :ASDF-UNICODE :X86-64 :GENCGC :64-BIT :ANSI-CL :COMMON-LISP :ELF :IEEE-FLOATING-POINT :LINUX :LITTLE-ENDIAN :PACKAGE-LOCAL-NICKNAMES :SB-CORE-COMPRESSION :SB-LDB :SB-PACKAGE-LOCKS :SB-THREAD :SB-UNICODE :SBCL :UNIX)

ASDF version: 3.3.1
ASDF registries: (NYXT-SOURCE-REGISTRY ENVIRONMENT-SOURCE-REGISTRY)
Critical dependencies: (/home/user/Repos/nyxt-git/_build/cl-cffi-gtk/gtk/cl-cffi-gtk.asd /home/user/Repos/nyxt-git/_build/cl-gobject-introspection/cl-gobject-introspection.asd /home/user/Repos/nyxt-git/_build/cl-webkit/webkit2/cl-webkit2.asd)
```

**Output when started from a shell**

Irrelevant.

**Comment by Ambrevar** [comment]
Thanks for reporting.

Should be fixed with 8fee5754ae7448c84af22d0e91ecd888d04aee3e.

**Comment by hendursaga** [comment]
On a related note: it took me too long to find this bug, because I got sidetracked with a "too many open files" error and several thousand lines of backtrace, because I was loading the config file recursively until resource exhaustion. Perhaps we should disallow, say, `load-after-system` calls to the config file, at least?

**Comment by Ambrevar** [comment]
Good call!

Can you share the exact line that was causing the problem for you?

**Comment by Ambrevar** [comment]
Common Lisp `load` does not catch circular loads indeed.

ASDF can catch them, but asking users to write an .asd file for their config seems too much.

Is there a library out there to detect circular loads?

Also while we have `load-after-system` and we can fix it there, we should probably ship our own `load` to "fix" this problem.

**Comment by hendursaga** [comment]
> Can you share the exact line that was causing the problem for you?

Well, prior to 8fee5754ae7448c84af22d0e91ecd888d04aee3e, a line like `(load-after-system :slynk (nyxt-config-file "slynk"))` would keep on loading itself.

> Is there a library out there to detect circular loads?

Not that I'm aware of.

> we should probably ship our own `load`

Not sure about that - might be overkill - but it's not my call to make :upside_down_face:

**Comment by jmercouris** [comment]
> Common Lisp `load` does not catch circular loads indeed.
> 
> 
> 
> ASDF can catch them, but asking users to write an .asd file for their config seems too much.
> 
> 
> 
> Is there a library out there to detect circular loads?
> 
> 
> 
> Also while we have `load-after-system` and we can fix it there, we should probably ship our own `load` to "fix" this problem.

True, but maybe we can make a virtual system to solve the problem? We don't actually create an ASD, but we TELL asdf that we did by piping it a string. That could work?

**Comment by Ambrevar** [comment]
Hmmm, let me think about it and see if I can come up with something.

**Comment by Ambrevar** [comment]
So we could have the following:

```lisp
;; Define on startup to avoid hardcoding the path expansion in the image:
(asdf:defsystem nyxt-user
  :depends-on (nyxt)
  :version "3"
  :pathname #.(nfiles:parent (nfiles:expand nyxt:*config-file*))
  :components ((:file #.(pathname-name (nfiles:expand nyxt:*config-file*)))))

;; Then in the user config file:
(define-nyxt-system nyxt-user/slynk-config
  :depends-on (slynk)                   ; External dep.
  :components ((:file "my-subconfig")))

;; Expands to:
(asdf:defsystem nyxt-user/slynk-config ; <= Raise a warning if not prefixed with nyxt-user.
  :depends-on (nyxt-user slynk)        ; <= Auto-push nyxt-user.
  :pathname #.(nfiles:parent (nfiles:expand nyxt:*config-file*)) ; <= Default value.
  :components ((:file "my-subconfig")))

;; Finally, maybe-load it:
(load-nyxt-system :nyxt-user/subconfig)
;; Exapdns to:
(handler-case (asdf:load-system :nyxt-user/subconfig)
  (asdf:missing-dependency (c)
    (log:warn "Skip loading of ~a: ~a" :nyxt-user/subconfig c)))
```

This should handle circular dependencies.  Can we make it less verbose than 2 s-exps and 4 lines?

Maybe 

```lisp
(define-and-load-system nyxt-user/slynk-config
  :depends-on (slynk)
  :components ((:file "my-subconfig")))
```

**Comment by Ambrevar** [comment]
@jmercouris commented: Simplify `(:file "my-subconfig")` to `("my-subconfig")` (optional) to avoid tripping up people.

**Comment by Ambrevar** [comment]
And we can create modules with `(make-instance 'asdf/component:module :name "foo")`.  This should give us quite some flexibility.

**Comment by Ambrevar** [comment]
Some hiccups:

- Non-system `:depends-on` cannot be systems, thus we cannot create a mere
  module to depend on a system.  In other words, we must create new systems for
  each config file load.
  
- asdf:load-system takes a system _designator_, not a system object: apparently
  it won't accept `(make-instance 'asdf/system:system :name "foo")`.

**Comment by Ambrevar** [comment]
Fixed on `master`.

@hendursaga `load-after-system` is now gone, instead you can use `define-nyxt-user-system-and-load`, which should catch cycles.
