### ISSUE TITLE
Add "noload" profile

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#2386]
In some cases and in particular for testing it's useful to ask Nyxt to not load any file from disk to ensure reproducible behaviour.

We often do `nyxt --no-config` but it's not enough: there is also the auto-config, the history, the bookmarks, and potentially more.

Wouldn't be nice to have a single knob to disable all file reads?  Actually, we can already programmatically do it by adding a profile which does just that.  

Since we have `nosave` already, I suggest we add `noload`.  Then it be enough to call

```lisp
nyxt --profile noload
```

to disable all file loads.

Should `noload` also disable file writes?  I would say yes, since it's not very intuitive to be "write only".

Thoughts?

**Comment by CorruptedVor** [comment]
Not loading any file from disk, including any cached stuff (i.e. stuff webkit caches)? Then I don't see any reason to write anything. Maybe if someone used it as an "incognito mode", but that would have to be more of a "read-only" minus the exception of bookmarks.

**Comment by aartaka** [comment]
But then we have `nosave` as our "incognito mode"...

`noload` is a good idea! Should be useful!

**Comment by aadcg** [comment]
I like the idea! Not sure about `noload` as the name tho. It basically means a stateless start plus no config file. `clean-start`? `fresh-start`? 

Is it possible to "accumulate profiles" btw? Then we could have `nyxt --profile no-config no-state`.

**Comment by jmercouris** [comment]
I am in accord with Andre, the name could definitely be tweaked! Not sure what is best, but yeah.

**Comment by Ambrevar** [comment]
`noload` made sense with regard to `nosave`.  But we can change both names.

It's not possible to accumulate profiles from the command line, however profiles are CLOS classes and as such, you can create a profile that inherits from multiple profiles.

`clean-start` and `fresh-start` are a bit incorrect, because what I'm suggesting would not load any file _ever_, not just on startup.

Any other suggestion?

**Comment by aadcg** [comment]
Correct @Ambrevar. I'd go with `no-config-and-stateless-session`. It's verbose but clearer.

**Comment by aadcg** [comment]
With regards to `nosave`, I could perhaps suggest `nohistory`.

**Comment by Ambrevar** [comment]
> With regards to `nosave`, I could perhaps suggest `nohistory`.

It's not juste about history, but everything else: auto-mode-rules, bookmarks, etc.

> Correct @Ambrevar. I'd go with `no-config-and-stateless-session`. It's verbose but clearer.

Not very convenient to type from the command line though... O.o

**Comment by aadcg** [comment]
Oh, so I'm afraid I don't have a better suggestion.

**Comment by Ambrevar** [comment]
See #2575.
