### ISSUE TITLE
prompter object-attributes elements should be automatically wrapped with `princ-to-string` if not string

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#2389]
If too many places in our code we call `princ-to-string` around `object-attributes` elements.

Shouldn't we do this automatically?  Would be convenient.

I vaguely remember not doing it on purpose though.  Maybe it was for performance reasons?  Indeed, `object-attributes` is called from tight loops, so we want it to be as cheap as possible.  Wrapping it in an `:around` method that calls `princ-to-string` conditionally could be too expansive.

Options:
- Add a `define-object-attributes` macro.
- Memoize the `object-attributes` calls.

Thoughts?

**Comment by Ambrevar** [comment]
@aadcg @jmercouris @aartaka Friendly ping everyone :)

**Comment by aadcg** [comment]
I'd lean towards memoization.

**Comment by aartaka** [comment]
Yep, I'd go with memoization too :)

**Comment by jmercouris** [comment]
Seems I am the only one in favor of the macro. Interesting. What is the rationale for preferring memoization? Is there something that I am not seeing here?

**Comment by Ambrevar** [comment]
"If you can do without macros, do it!" is a reasonable mantra :)

**Comment by jmercouris** [comment]
I'm not sure I believe in the "If you can do without macros, do it". Perhaps I have not yet understood the wisdom of this phrase yet.

**Comment by Ambrevar** [comment]
To quote Serapeum's `with-thunk` docstring:

> Functions are easier to write than macros; you can change the behavior of a function without having to recompile all its callers; functions can be traced, appear in backtraces, etc.

**Comment by aartaka** [comment]
And functions can be composed/mapped/curried, while macros cannot!

**Comment by jmercouris** [comment]
And yet, I find none of those reasons compelling in this context!

**Comment by aartaka** [comment]
But then, wait, if we do it for performance, we can simply `(declare (inline fn))` and it will not spend any time on function call jumps!

**Comment by Ambrevar** [comment]
@jmercouris Could you expand on why?

**Comment by Ambrevar** [comment]
@aartaka Which `fn`? As I understand, the problem is not just extra funcalls but also the extra condition or the extra string conversion / instantiation which must be done at runtime because we do not know the data that's being fed to the `object-attributes` method.

Actually memoization wouldn't help here because the problem is _not_ with calling the same thing multiple times.

Hmm... So at compile time we would need to know the return type of function used as attribute value.

**Comment by jmercouris** [comment]
> @jmercouris Could you expand on why?

I'm just saying I do not need to recompile this at runtime, nor see it in a trace. It is object-attributes, probably we will touch it once, and never again!

**Comment by Ambrevar** [comment]
I think the argument against macro above is in the general sense: if macros are hard to write, you'll make mistakes and you'll need to fix the definition, which won't apply to the rest of the image.

In other words, macros are less friendly to image-based programming.

About trace: I do not see your point here, if you need to debug a problem that involves object-attributes (has happened before), then you may want to trace.

**Comment by Ambrevar** [comment]
Well well well, looks like we may have been wearing blinkers here.

In the original post I said:

> I vaguely remember not doing it on purpose though. Maybe it was for performance reasons?

If this was indeed the reason, then it's actually premature optimization.  

```lisp
(let ((l  (loop for i from 0 to 100000 collect (random 100000))))
  (time (mapl (lambda (e) (rplaca e (princ-to-string (car e)) )) l)))
```

Returns 0.025s on my machine.  Considering this is called once per prompt buffer and this is an extreme example, no need to worry about it.  It's better to provide a good API to the users.

Unless there was some other reason but I cannot think of it now.
So I'll go forward and apply `princ-to-string` automatically from `prompter`.

**Comment by aartaka** [comment]
@Ambrevar, any progress on that? I want to do this one, if you've not yet gotten to it :)

**Comment by Ambrevar** [comment]
Thanks a lot!
