### ISSUE TITLE
Move renderers to their own package

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#2390]
We've need this forever, time we did it!

At the very least, if we want to support multiple renderers they should be in separate packages to avoid name clashes.

I suggest the `nyxt/renderer/gtk` naming convention.

Don't we have an issue about this already?

**Comment by CorruptedVor** [comment]
I would like that. You might be referring to https://github.com/atlas-engineer/nyxt/issues/1105 
Switching without recompiling nyxt sounds great - (assuming that nyxt was compiled with support for both in the first place of course, being able to compile for just one should still be possible).

**Comment by aadcg** [comment]
Completed via #2612.
