### ISSUE TITLE
Feature Request: Let's get `gh` or `jump-to-heading` to work with readthedocs 

### ISSUE THREAD

**Issue by jgarte** [atlas-engineer/nyxt#2392]
**Describe the solution you'd like**
I'd like to be able to type `gh` (`jump-to-heading`) and get a list of sphinx table of contents items to visit in the minibuffer.

**Additional context**
Try typing `gh` on [this page](neoscore.org) to see what I mean.

**Comment by aadcg** [comment]
You can get a TOC while browsing the manual if you run Nyxt from `master`.

**Comment by aadcg** [comment]
Actually this is broken. Still you can press `m` to navigate all of the headings in the prompt buffer.

```
There is no applicable method for the generic function
  #<STANDARD-GENERIC-FUNCTION NYXT:PAGE-MODE (1)>
when called with arguments
  (#<FUNCTION (LAMBDA ()
                :IN
                "/home/aadcg/common-lisp/nyxt/source/mode/document.lisp") {54555CEB}>).
   [Condition of type SB-PCL::NO-APPLICABLE-METHOD-ERROR]

Restarts:
 0: [RETRY] Retry calling the generic function.
 1: [ABORT] abort thread (#<THREAD "Nyxt run-async command" RUNNING {1010D23353}>)

Backtrace:
 0: ((:METHOD NO-APPLICABLE-METHOD (T)) #<STANDARD-GENERIC-FUNCTION NYXT:PAGE-MODE (1)> #<FUNCTION (LAMBDA NIL :IN "/home/aadcg/common-lisp/nyxt/source/mode/document.lisp") {54555CEB}>) [fast-method]
      Locals:
        SB-PCL::ARGS = (#<FUNCTION (LAMBDA () :IN "/home/aadcg/common-lisp/nyxt/source/mode/document.lisp") {54555CEB}>)
        GENERIC-FUNCTION = #<STANDARD-GENERIC-FUNCTION NYXT:PAGE-MODE (1)>
      Locals:
        SB-PCL::ARGS = (#<FUNCTION (LAMBDA () :IN "/home/aadcg/common-lisp/nyxt/source/mode/document.lisp") {54555CEB}>)
        GENERIC-FUNCTION = #<STANDARD-GENERIC-FUNCTION NYXT:PAGE-MODE (1)>
 1: (SB-PCL::CALL-NO-APPLICABLE-METHOD #<STANDARD-GENERIC-FUNCTION NYXT:PAGE-MODE (1)> (#<FUNCTION (LAMBDA NIL :IN "/home/aadcg/common-lisp/nyxt/source/mode/document.lisp") {54555CEB}>))
      Locals:
        ARGS = (#<FUNCTION (LAMBDA () :IN "/home/aadcg/common-lisp/nyxt/source/mode/document.lisp") {54555CEB}>)
        GF = #<STANDARD-GENERIC-FUNCTION NYXT:PAGE-MODE (1)>
 2: (BUFFER-LOAD #<QURI.URI:URI nyxt:nyxt/document-mode:headings-panel> :BUFFER #<PANEL-BUFFER 2201 {1010D2B9D3}>)
      Locals:
        #:.DEFAULTING-TEMP. = #<PANEL-BUFFER 2201 {1010D2B9D3}>
        BUFFER = #<PANEL-BUFFER 2201 {1010D2B9D3}>
        #:N-SUPPLIED-0 = 1
        URL = #<QURI.URI:URI nyxt:nyxt/document-mode:headings-panel>
        URL-DESIGNATOR = #<QURI.URI:URI nyxt:nyxt/document-mode:headings-panel>
 3: ((:METHOD NYXT/DOCUMENT-MODE:HEADINGS-PANEL NIL)) [fast-method]
      Locals:
        PANEL-BUFFER = #<PANEL-BUFFER 2201 {1010D2B9D3}>
 4: (RUN-COMMAND NYXT/DOCUMENT-MODE:HEADINGS-PANEL NIL)
      Locals:
        ARGS = NIL
        #:G7 = NYXT/DOCUMENT-MODE:HEADINGS-PANEL
        OLD-%BUFFER = NIL
```

**Comment by jgarte** [comment]
> Actually this is broken. Still you can press `m` to navigate all of the headings in the prompt buffer.
> 
> ```
> There is no applicable method for the generic function
>   #<STANDARD-GENERIC-FUNCTION NYXT:PAGE-MODE (1)>
> when called with arguments
>   (#<FUNCTION (LAMBDA ()
>                 :IN
>                 "/home/aadcg/common-lisp/nyxt/source/mode/document.lisp") {54555CEB}>).
>    [Condition of type SB-PCL::NO-APPLICABLE-METHOD-ERROR]
> 
> Restarts:
>  0: [RETRY] Retry calling the generic function.
>  1: [ABORT] abort thread (#<THREAD "Nyxt run-async command" RUNNING {1010D23353}>)
> 
> Backtrace:
>  0: ((:METHOD NO-APPLICABLE-METHOD (T)) #<STANDARD-GENERIC-FUNCTION NYXT:PAGE-MODE (1)> #<FUNCTION (LAMBDA NIL :IN "/home/aadcg/common-lisp/nyxt/source/mode/document.lisp") {54555CEB}>) [fast-method]
>       Locals:
>         SB-PCL::ARGS = (#<FUNCTION (LAMBDA () :IN "/home/aadcg/common-lisp/nyxt/source/mode/document.lisp") {54555CEB}>)
>         GENERIC-FUNCTION = #<STANDARD-GENERIC-FUNCTION NYXT:PAGE-MODE (1)>
>       Locals:
>         SB-PCL::ARGS = (#<FUNCTION (LAMBDA () :IN "/home/aadcg/common-lisp/nyxt/source/mode/document.lisp") {54555CEB}>)
>         GENERIC-FUNCTION = #<STANDARD-GENERIC-FUNCTION NYXT:PAGE-MODE (1)>
>  1: (SB-PCL::CALL-NO-APPLICABLE-METHOD #<STANDARD-GENERIC-FUNCTION NYXT:PAGE-MODE (1)> (#<FUNCTION (LAMBDA NIL :IN "/home/aadcg/common-lisp/nyxt/source/mode/document.lisp") {54555CEB}>))
>       Locals:
>         ARGS = (#<FUNCTION (LAMBDA () :IN "/home/aadcg/common-lisp/nyxt/source/mode/document.lisp") {54555CEB}>)
>         GF = #<STANDARD-GENERIC-FUNCTION NYXT:PAGE-MODE (1)>
>  2: (BUFFER-LOAD #<QURI.URI:URI nyxt:nyxt/document-mode:headings-panel> :BUFFER #<PANEL-BUFFER 2201 {1010D2B9D3}>)
>       Locals:
>         #:.DEFAULTING-TEMP. = #<PANEL-BUFFER 2201 {1010D2B9D3}>
>         BUFFER = #<PANEL-BUFFER 2201 {1010D2B9D3}>
>         #:N-SUPPLIED-0 = 1
>         URL = #<QURI.URI:URI nyxt:nyxt/document-mode:headings-panel>
>         URL-DESIGNATOR = #<QURI.URI:URI nyxt:nyxt/document-mode:headings-panel>
>  3: ((:METHOD NYXT/DOCUMENT-MODE:HEADINGS-PANEL NIL)) [fast-method]
>       Locals:
>         PANEL-BUFFER = #<PANEL-BUFFER 2201 {1010D2B9D3}>
>  4: (RUN-COMMAND NYXT/DOCUMENT-MODE:HEADINGS-PANEL NIL)
>       Locals:
>         ARGS = NIL
>         #:G7 = NYXT/DOCUMENT-MODE:HEADINGS-PANEL
>         OLD-%BUFFER = NIL
> ```

`m` looks like a prefix key? Can you elaborate a bit on that?

**Comment by aadcg** [comment]
@Ambrevar commit 5746eea3e101317779aa558b4aa361328d535700 broke the `headings-panel` command.

**Comment by aadcg** [comment]
> > Actually this is broken. Still you can press `m` to navigate all of the headings in the prompt buffer.
> 
> @aadcg Hi, can you elaborate a bit on that? Does your suggestion also work with vi keys enabled?

Hi @jgarte! Sure. The following keybindings work in any `help` buffer. Try them out in the manual, for instance:

- "n" 'nyxt/document-mode:next-heading
- "p" 'nyxt/document-mode:previous-heading
- "m" 'nyxt/document-mode:jump-to-heading
- "s" 'nyxt/search-buffer-mode:search-buffer

These work regardless of the keystyle you're using (`vi`, `emacs` or `CUA`).

Let me know if it works for you, and if it addressed the idea of this feature. Thanks!

**Comment by Ambrevar** [comment]
Panel buffers should be fixed with https://github.com/atlas-engineer/nyxt/pull/2398.

**Comment by aadcg** [comment]
This is fixed. Thanks.
