### ISSUE TITLE
Do we need the `url` method?

### ISSUE THREAD

**Issue by aadcg** [atlas-engineer/nyxt#2394]
`url` is both a slot of the `buffer` class and a method defined in `urls.lisp`.

The method does basically what `quri:uri` does - converts a string to a uri, unless it's already an `uri`.

Therefore, `(url` means two different things. Examples:

```lisp
(setf (url (current-buffer)) (url (url (current-buffer))))
```

The definition of the `buffer` class, while it's not written like that (perhaps to avoid confusion), could very well be written as follows:

```lisp
(define-class buffer (renderer-buffer)
  (...
   (url (url ""))
   (url-at-point (url ""))
   ...)
  ...)
```

My suggestion would be to get rid of the `url` method, and to add `quri:uri` to `*imports*` so that all method calls `(url` would be replaced by `(uri`.

Does this make sense or am I missing something?

EDIT: Notice that having `url` as both a method and a slot works under the assumption that `urls`  will always  be compiled before `buffer`, as it is today (see the module "Core" of `nyxt.asd`).

**Comment by aadcg** [comment]
I am convinced. 

When does it make sense to prefer `quri:uri` over `url` then?

>  You have a query and want the URL from it? Expect (url QUERY) to work.

Can you give an example?

**Comment by Ambrevar** [comment]
> When does it make sense to prefer `quri:uri` over `url` then?

`url` is a "getter", while `quri:uri` is more of a constructor.  But true, since `url` works on scheme, technically it can also construct URLs.


> > You have a query and want the URL from it? Expect (url QUERY) to work.
> 
> Can you give an example?

See `buffer.lisp`:

```lisp
(defmethod url ((query new-url-query))
  (quri:uri
   (cond
     ((and (engine query)
           (not (uiop:emptyp (query query))))
      (format nil (search-url (engine query))
              (str:join ""
                        (mapcar #'encode-url-char
                                (map 'list #'string (query query))))))
     ((engine query)
      (fallback-url (engine query)))
     (t (query query)))))
```

So for every new type where it makes sense to associate a URL, we can specialize the `url` method.

**Comment by Ambrevar** [comment]
While it's equivalent, I find that semantically I prefer to construct URLs with `quri`, and retrieve URLs with `url`.  Just a matter of conventions I guess.

**Comment by aadcg** [comment]
Indeed, that was my observation from the start. We have `url` as a method, but it still makes sense to use `quri:uri`. All clear.
