### ISSUE TITLE
Load spinner spins indefinitely

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#2396]
As @jmercouris reported, it looks like indeed that we are never updating the status-buffer on finished load.

Was this ever working?

Easy fix: add `status` accessor and add watcher on it.

**Comment by aadcg** [comment]
I've noticed it too. It used to work, yes.

**Comment by Ambrevar** [comment]
Any idea when / which commit?

**Comment by aadcg** [comment]
This started to misbehave in one of these commits:

91633db15d90ae2f21529885c98395adba6cac59
07ede9a240596915ecca45d1b94a31536353d82c
396d41c9605852b4c842d160a5482135bce2e5b9
3a2618f921e065ea6f68d94a1bb861c250445abb

**Comment by aadcg** [comment]
If you want to have a look at a commit where it behaves properly, take dcc818b75151a26e69b896218c0b29b07ad835ff.

**Comment by Ambrevar** [comment]
OK, offending commit is 07ede9a240596915ecca45d1b94a31536353d82c.  I'll fix this.

**Comment by Ambrevar** [comment]
Actually, @jmercouris didn't you want to fix it?  Sorry if I almost stepped on your toes :p

**Comment by Ambrevar** [comment]
Fixed with #2401.
