### ISSUE TITLE
Allow lisp:// URL to receive arguments again

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#2397]
As discussed in https://github.com/atlas-engineer/nyxt/pull/2377#issuecomment-1157741439, `lisp://` URLs no longer take arguments and this can be problematic in some cases:

- In delete-bookmark, we have to generate 1 closure per bookmark which is not ideal performance-wise.
- What if we get some data from JS, how do we communicate it to the `lisp://` URL closure?

It's easy to extend the `lisp` scheme to accept argument (for instance as URL query arguments, just like `nyxt://` URLs).

Then the question that remains is how we refer to the lambda-list.

Currently we have this syntax:

```lisp
(ps:ps (nyxt/ps:lisp-eval
        (:title "describe-any")
        (nyxt::describe-any (princ-to-string symbol))))
```

I guess we could have this instead?

```lisp
(ps:ps (nyxt/ps:lisp-eval (&key key-arg1 key-arg2)
        (:title "describe-any")
        (log:info key-arg1 key-arg2)
        (nyxt::describe-any (princ-to-string symbol))))
```

But then we need to change all the `lisp-eval` calls.

Thoughts? @aartaka

**Comment by aartaka** [comment]
What we can do instead is (backwards-compatible) addition of yet another keyword argument to the `lisp-eval` arguments. Your example could then be:
``` lisp
(ps:ps (nyxt/ps:lisp-eval
        (:title "describe-any" :args (&key key-arg1 key-arg2))
        (nyxt::describe-any (princ-to-string symbol))))
```
