### ISSUE TITLE
Move misc utilities to their own files?

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#2399]
It'd be useful to move `funcall*`, `trim-list`, `last-word`, etc. (most are in
`configuration.lisp`) to their own file.

I'd even say their own package, which is then `cl:use`d in `nyxt` and
`nyxt-user`.  This way we can easily list them all by inspecting the package or
through completion.

What shall we call this file?  `utilities` is one that comes to mind, but the
name is rather meaningless.

Thoughts?

**Comment by Ambrevar** [comment]
What about `nyxt/lang`?  Rationale: like Alexandria, it's an extension to the language.  Plus it's shorter than `nyxt/utilities`.

Note: Also include `read-from-stream` in there.

**Comment by CorruptedVor** [comment]
Alexandria also calls them utilities and claims they are not conceptual extensions. So I'd put that under utilities, the conceptual extensions under lang.

**Comment by Ambrevar** [comment]
Do we have "conceptual extensions" though?

**Comment by aartaka** [comment]
Not yet, but who knows :)

**Comment by Ambrevar** [comment]
Addressed in #2403.
