### ISSUE TITLE
Enhance reduce-tracking-mode

### ISSUE THREAD

**Issue by CorruptedVor** [atlas-engineer/nyxt#2406]
**Is your feature request related to a problem? Please describe.**
There are still some unaddressed fingerprinting methods https://panopticlick.eff.org/
-time zone
-canvas
-audiocontext
-webgl

**Describe the solution you'd like**
Do not send the actual time zone, preferably a common one.
If possible, cause canvas and audio fingerprint to change every time or imitate a known one.
I'm not sure what you could do for the canvas and audio, maybe one can fiddle with the renderer settings? Ditto for the WebGL?
More info on canvas fingerprinting: https://hovav.net/ucsd/papers/ms12.html

**Describe alternatives you've considered**
For now, canvas, audio, and timezone fingerprinting should be mitigated by using no-script mode. Webgl can be disabled via no-webgl mode.

**Comment by aartaka** [comment]
#1014 duplicate?

**Comment by Ambrevar** [comment]
Looks like it!

**Comment by CorruptedVor** [comment]
Yep. Closing.
