### ISSUE TITLE
`gopher` URLs don't show on `list-buffers`

### ISSUE THREAD

**Issue by aadcg** [atlas-engineer/nyxt#2409]
![2022-06-23_15:27:14](https://user-images.githubusercontent.com/45483512/175323539-90ed1557-e9f0-4c27-a76f-70b95f7d5a54.png)

Note to self, before I forget.

**Comment by aartaka** [comment]
Indeed, custom scheme pages usually have to title and thus have empty string as their name in the list-buffers!

**Comment by Ambrevar** [comment]
Maybe fall back to `(format nil "Gopher buffer ~a" (id buffer))` ?

**Comment by Ambrevar** [comment]
Thanks!
