### ISSUE TITLE
Do not build web extension support by default

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#2411]
Since our web extension support is currently sub par and possibly insecure, we should disable it by default until the situations gets resolved.

I propose to add an environment variable.  Or maybe better: nothing at all, remove it from `all:` list.

@aartaka ?

**Comment by aartaka** [comment]
Yes, I thought abot that too!

**Comment by Ambrevar** [comment]
Done with 3ca5f457a2e01ac76fcea54832357db6f0843b5c.
