### ISSUE TITLE
Auto-detect slynk

### ISSUE THREAD

**Issue by jgarte** [atlas-engineer/nyxt#2422]
Would it be possible to do something like what eglot does for detecting language servers with [eglot-alternatives](https://github.com/joaotavora/eglot/blob/master/eglot.el#L105) but for slynk and swank?

I'd like to not have to configure nyxt to work with slynk and just have it choose the right server out of the box depending on what it detects in the executable path.

I'm just thinking big picture here and haven't looked deeply into the code yet so feel free to inform me on the logistics of this request. It would be much appreciated.

**Comment by Ambrevar** [comment]
Well, that shouldn't be too hard if we just include slynk as a dependency and provide a `start-slynk` command.

Would that be enough?

**Comment by jgarte** [comment]
Hi, that sounds like a better idea. Yes, that would be enough.

@Ambrevar 

What are the steps involved in completing this ticket if you don't mind outlining them for me.

I'd like to see if I can work on it.

1. Can you elaborate on the steps involved in making slynk as a dependency in the nyxt codebase?
1. Would you require unit tests for this feature?

I'll start by look at the code for `start-swank` to see how it is constructed.

If you have any design decisions I should take into consideration or should be aware of it would be much appreciated if you can share them here.

I am able to use slime and/or sly for developing this feature in emacs.

**Comment by Ambrevar** [comment]
> 1. Can you elaborate on the steps involved in making slynk as a dependency in the nyxt codebase?

Slynk must be added to the Git submodules and the build-scripts/nyxt.scm file.

>     2. Would you require unit tests for this feature?
> 
>     3. Any testing practices that you recommend?

The problem here is that to test this we would need a Slynk client.  Which is most often Emacs.  But Emacs is not a dependency.  So testing this would be quite a hassle, especially considering how simple that `start-slynk` command is.  Not worth it in my opinion.

Let me know if you need more details.

**Comment by aartaka** [comment]
Closing this, as `start-slynk` should be enough for convenience, as @jgarte said.
