### ISSUE TITLE
Cannot move cursor/select suggestions with custom key-bindings

### ISSUE THREAD

**Issue by tipotto** [atlas-engineer/nyxt#2423]
I have some questions about cursor movement and suggestion selection with custom key-bindings.

I'd like to customize some key-bindings to be able to move cursor/select suggestions with C-p (```scroll-up```), C-n (```scroll-down```), C-f (```scroll-right```) and C-b (```scroll-left```).

## What I want to do:
1. Move cursor with C-f (```scroll-right```) and C-b (```scroll-left```) on input bar of prompt buffer
2. Move cursor with C-f (```scroll-right```) and C-b (```scroll-left```) on Google search bar open with open-url command
3. Select suggestions with C-p (```scroll-up```), C-n (```scroll-down```) on prompt buffer
4. Select suggestions with C-p (```scroll-up```), C-n (```scroll-down```) on Google search bar open with open-url command

When I applied emacs mode, only the third one worked, but the others didn't.

### 1. Create custom modes and keymaps
I created two custom modes and keymaps, but none of them above worked at all. 
(When I pressed C-p and C-n on prompt buffer, buffer content on the background was scrolled down, not the one on prompt buffer. Prompt buffer was probably not focused.)

```
(defvar *web-keymap* (make-keymap "web-map"))
(defvar *base-keymap* (make-keymap "base-map"))

(define-key *web-keymap*
  "C-n" 'nyxt/web-mode:scroll-down
  "C-p" 'nyxt/web-mode:scroll-up
  "C-f" 'nyxt/web-mode:scroll-right
  "C-b" 'nyxt/web-mode:scroll-left
  "C-s s" 'nyxt/web-mode:search-buffer
  )

(define-key *base-keymap*
  "C-l" 'set-url
  "M-l" 'set-url-new-buffer
  "C-x k" 'delete-buffer
  "C-x o" 'switch-buffer-next
  "C-x C-c" 'quit
  "C-x C-f" 'open-file
  "C-x C-k" 'delete-all-buffers
  "C-c p" 'switch-buffer-next
  "C-c n" 'switch-buffer-previous
  "C-c C-f" 'nyxt/buffer-listing-mode:list-buffers
  "M-x" 'execute-command
  )

(define-mode web-mode ()
  "Mode for custom key bindings in `*web-keymap*'."
  ((keymap-scheme (keymap:make-scheme
                   scheme:cua *web-keymap*
                   scheme:emacs *web-keymap*
                   scheme:vi-normal *web-keymap*))))

(define-mode base-mode ()
  "Mode for custom key bindings in `*base-keymap*'."
  ((keymap-scheme (keymap:make-scheme
                   scheme:cua *base-keymap*
                   scheme:emacs *base-keymap*
                   scheme:vi-normal *base-keymap*))))

(define-configuration (buffer web-buffer)
  ((default-modes (append '(web-mode base-mode) %slot-default%))))
```

### 2. Extend mode
I also tried to extend emacs mode, but it didn't work either.
To be honest, I have no idea if the config below is correct. Let me know if something is wrong.

```
(define-configuration (buffer web-buffer)
  ((keymap-scheme
    (define-scheme (:name-prefix "my-web" :import %slot-default%)
      scheme:emacs
      (list
       "C-n" 'nyxt/web-mode:scroll-down
       "C-p" 'nyxt/web-mode:scroll-up
       "C-f" 'nyxt/web-mode:scroll-right
       "C-b" 'nyxt/web-mode:scroll-left
       )))))
```

## Question:
1. How to customize some key-bindings on emacs keymap?

2. Is it possible to select suggestions with C-p (```scroll-up```) and C-n (```scroll-down```) on Google open  with ```open-url``` command?
While I can select suggestions on prompt buffer with those keys on emacs mode, I need to press ```keypadup``` and ```keypaddown``` on Google.

3. Is it possible to move cursor with C-f (```scroll-right```) and C-b (```scroll-left```) on input bar of prompt buffer?

## Version
Nyxt: 2.2.4
OS: Kali Linux 5.16

**Comment by aadcg** [comment]
What do you mean by "on Google"?

**Comment by tipotto** [comment]
> What do you mean by "on Google"?

Sorry, I updated the previous post for more details. It means a buffer that opens Google with ```open-url``` command.
I'd like to select suggestions on the buffer with custom key-bindings if possible.

**Comment by aadcg** [comment]
> 
    Move cursor with C-f (scroll-right) and C-b (scroll-left) on input bar of prompt buffer
    Move cursor with C-f (scroll-right) and C-b (scroll-left) on Google search bar open with open-url command
    Select suggestions with C-p (scroll-up), C-n (scroll-down) on prompt buffer
    Select suggestions with C-p (scroll-up), C-n (scroll-down) on Google search bar open with open-url command

To achieve these goals it should be enough to add the following to your `init.lisp`

```lisp
(define-configuration (buffer internal-buffer editor-buffer prompt-buffer)
  ((default-modes `(nyxt/emacs-mode:emacs-mode ,@%slot-default%))))
```

Does that work? 

Notice that it should work for Nyxt 2.2.4. In our future 3.0 release, things will be quite different!

**Comment by aadcg** [comment]
To add keybindings to `emacs-mode` here's some inspiration:

```lisp
(defvar *my-keymap* (make-keymap "my-map"))
(define-key *my-keymap*
  "C-s"   'nyxt/web-mode:search-buffer
  "C-g"   'nyxt/web-mode:remove-search-hints
  "C-h a" 'describe-any)

(define-mode my-mode ()
  "Dummy mode for the custom key bindings in `*my-keymap*'."
  ((keymap-scheme :initform (keymap:make-scheme scheme:emacs *my-keymap*))))

(define-configuration (buffer internal-buffer editor-buffer prompt-buffer)
  ((default-modes `(nyxt/emacs-mode:emacs-mode
                    my-mode
                    ,@%slot-default%))))
```

**Comment by tipotto** [comment]
Thank you for the reply. 
I tried the solution you suggested, but it didn't work unfortunately.

I can select suggestions with C-p (```scroll-up```), C-n (```scroll-down```) on prompt buffer as always, but none of the others below worked.

- [ ] Move cursor with C-f (scroll-right) and C-b (scroll-left) on input bar of prompt buffer
- [ ] Move cursor with C-f (scroll-right) and C-b (scroll-left) on Google search bar open with open-url command
- [x] Select suggestions with C-p (scroll-up), C-n (scroll-down) on prompt buffer
- [ ] Select suggestions with C-p (scroll-up), C-n (scroll-down) on Google search bar open with open-url command

The code in my init.lisp is as follows:

```
(defvar *my-keymap* (make-keymap "my-map"))
(define-key *my-keymap*
  "C-n" 'nyxt/web-mode:scroll-down
  "C-p" 'nyxt/web-mode:scroll-up
  "C-f" 'nyxt/web-mode:scroll-right
  "C-b" 'nyxt/web-mode:scroll-left
  )

(define-mode my-mode ()
  "Dummy mode for the custom key bindings in `*my-keymap*'."
  ((keymap-scheme :initform (keymap:make-scheme scheme:emacs *my-keymap*))))

(define-configuration (buffer internal-buffer editor-buffer prompt-buffer)
  ((default-modes `(nyxt/emacs-mode:emacs-mode
                    my-mode
                    ,@%slot-default%))))
```

I'm currently using a key remapping tool called xkeysnail to solve this issue. However, I'd like to make it work by Nyxt as key-bindings bound by xkeysnail could have bad effects to Nyxt's key-bindings in some cases.

**Comment by aadcg** [comment]
I believe you have some misconceptions regarding `emacs-mode`. Before explaining those in detail, could you please start nyxt with the following config:

```lisp
(define-configuration (buffer internal-buffer editor-buffer prompt-buffer)
  ((default-modes `(nyxt/emacs-mode:emacs-mode ,@%slot-default%))))
```

**Comment by tipotto** [comment]
I started with the config, and was able to select suggestions on prompt buffer with C-n and C-p, which is the third one.
None of the others worked. 

```
1. Move cursor with C-f (scroll-right) and C-b (scroll-left) on input bar of prompt buffer
2. Move cursor with C-f (scroll-right) and C-b (scroll-left) on Google search bar open with set-url command
3. Select suggestions with C-p (scroll-up), C-n (scroll-down) on prompt buffer
4. Select suggestions with C-p (scroll-up), C-n (scroll-down) on Google search bar open with set-url command
```
That's why I tried to extend emacs mode adding some custom key-bindings as in my previous post, but the result was the same as stated above...

**Comment by aadcg** [comment]
If I'm  not misinterpreting what you're looking for, the following should work:

```lisp
(define-configuration (buffer internal-buffer editor-buffer prompt-buffer)
  ((default-modes (append '(nyxt/emacs-mode:emacs-mode) %slot-default%))))

(define-configuration web-buffer
  ((default-modes (append '(nyxt::input-edit-mode) %slot-default%))))
```

Does it help?

**Comment by jmercouris** [comment]
I think that the user wants to move the cursor in the prompt buffer input field using C-f and C-b

**Comment by tipotto** [comment]
@aadcg Thanks, but it didn't work either. Sorry if my description makes you confused.
I'll attach some pictures below to make it clear where and how I want to use Emacs key-bindings.

#### Prompt buffer:
1. Move cursor in the input field of prompt buffer with C-f and C-b. (**Not working**)
2. Select suggestions with C-p and C-n. (Working on emacs mode by default)

![nyxt1](https://user-images.githubusercontent.com/39334151/177240554-0ccfd57e-5f5e-49af-a511-9c488e8690db.png)

#### Google open by Nyxt
1. Move cursor in the input field of prompt buffer with C-f and C-b. (**Not working**)
2. Select suggestions with C-p and C-n. (**Not working**)

![nyxt2](https://user-images.githubusercontent.com/39334151/177240556-356fa32d-5b35-4b9a-9e51-b39a1bb5ea47.png)

**Comment by tipotto** [comment]
@jmercouris That's exactly what I want to do!

**Comment by aadcg** [comment]
> Select suggestions with C-p and C-n. (Not working)

This would be very tricky to make it work.

All of the other things are working for me with the config I attached... Am I missing something?

**Comment by aadcg** [comment]
I'm using the latest release, 2.2.4 (as you are I believe).

Could some program be intercepting those keys before sending then to Nyxt?

**Comment by jmercouris** [comment]
I believe you'll need to enable emacs-input-mode or some such. It turns all input fields into navigable with emacs like keybindings.

**Comment by tipotto** [comment]
@aadcg They could be if enabled.
Sorry, when I tried with the config in [this post](https://github.com/atlas-engineer/nyxt/issues/2423#issuecomment-1174012534) again, I was able to move cursor with C-f and C-b in Google input field. My check process was not enough. It doesn't yet work in the prompt buffer input field though.

I then started with the following config trying to apply input-edit-mode to prompt buffer as well, but some errors occurred.
Any thoughts?

```
(define-configuration (buffer internal-buffer editor-buffer)
  ((default-modes (append '(nyxt/emacs-mode:emacs-mode) %slot-default%))))

(define-configuration (prompt-buffer web-buffer)
  ((default-modes (append '(nyxt::input-edit-mode) %slot-default%))))
```

```
; When C-f is pressed
Warning: Error on separate thread: The value :UNDEFINED is not of type REAL when binding NUMBER

; When C-b is pressed
Warning: Error on separate thread: The value :UNDEFINED is not of type NUMBER when binding SB-KERNEL::X
```

**Comment by aadcg** [comment]
You can't add `input-edit-mode` to the `prompt-buffer`. 

To be able to get `C-f` and `C-b` to work on the prompt-buffer you need to enable `emacs-mode`.

**Comment by tipotto** [comment]
@aadcg Okay, C-f and C-b don't still work with ```emacs-mode``` enabled for some reasons, even if the key remapping tool I use is disabled... I'll keep trying to be able to get the keys to work.

**Comment by jmercouris** [comment]
That's because they are not implemented as far as I am aware :-)

They used to be, but since we moved to the new prompt buffer, we haven't reimplemented such functions!

**Comment by aadcg** [comment]
Everything works for me.

**Comment by aadcg** [comment]
@tipotto feel free to re-open.
