### ISSUE TITLE
Add Suse to list of packages?  Can

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#2428]
@bubbleguuum You previously mentioned https://build.opensuse.org/package/show/home:bobbie424242/nyxt-git

I'm not familiar with build.opensuse.org.  Is this an official package or a user-maintained one?
How is it available to Suse user?  By default?  For all versions?

Would you like that we mention this package in the README of Nyxt?

Finally: Is this recipe adaptable to other rpm-based distros like Fedora?

**Comment by Ambrevar** [comment]
How does 50499ea9e6016bb35f0e1100678895b57ef356a2 look to you?

**Comment by bubbleguuum** [comment]
Looks good but missing the actual command to install the package: `zypper in nyxt`

**Comment by Ambrevar** [comment]
Right, we provide this for the other distros too.  Done in f80f8a0236aa9586a86447c3d150f6ba575f2f7f.
