### ISSUE TITLE
Mode list is very short and badly truncated in the status bar

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#2436]
@aartaka @aadcg Any idea what's happening?

**Comment by aartaka** [comment]
No, probably some CSS magic :(

**Comment by aadcg** [comment]
See 1eea3a03eb77195e3a134d3c93620fdf5ca4c764.

@jmercouris

**Comment by jmercouris** [comment]
Not a bug. I changed this after 99% of the modes were made invisible. I figured the one that's relevant to most people is vi insert/normal mode.

**Comment by Ambrevar** [comment]
And emacs-mode, and no-script, etc.  It's not 99%, quite some modes are important to display in the status area.  I believe this is too short, we should enlarge it a little bit so that at list 4-5 symbols can be displayed.

**Comment by Ambrevar** [comment]
We should also display an ellipsis to signify that not all modes are displayed.  So we need space for this character too.

**Comment by jmercouris** [comment]
Displaying an ellipsis is a good idea. I will see about how this can be done. It will involve some changes to the overflow style of that node entry. Please note that display an ellipsis AND making the view horizontally scrollable are mutually exclusive.

**Comment by Ambrevar** [comment]
We used to have an ellipsis before (see pre 2.2.4 I think), we can just revert to that ;)

**Comment by jmercouris** [comment]
OK!

**Comment by aadcg** [comment]
Isn't the ellipsis the "+" sign?

**Comment by Ambrevar** [comment]
The `+` sign is always there.  The ellipsis is there to mean that more modes are not showing.

**Comment by aadcg** [comment]
I'm claiming that the `+` sign _is_ (or should be regarded as) the ellipsis. Do you use [emacs-minions](https://github.com/tarsius/minions)? I'm advocating for a similar approach.

I think we should follow a similar approach as the surf browser uses. From their `man` page:

```
INDICATORS OF OPERATION
       Surf is showing indicators of operation in front  of  the  site  title.
       For  all  indicators,  unless  otherwise specified, a lower case letter
       means disabled and an upper case letter means enabled.

       A      all cookies accepted

       a      no cookies accepted

       @      all except third-party cookies accepted

       c C    caret browsing

       g G    geolocation

       d D    disk cache

       i I    images

       s S    scripts

       m M    styles

       f F    frame flattening

       x X    custom certificates

       t T    strict TLS

INDICATORS OF WEB PAGE
       The second part of the indicators specifies modes of the web  page  it‐
       self.

   First character: encryption
       -      unencrypted

       T      encrypted (TLS)

       U      attempted encryption but failed

   Second character: proxying
       -      no proxy

       P      using proxy
```

Concretely, I'm saying that ll modes should have a glyph and the full name should NEVER be displayed in the status buffer (if you want to see the full name, then click "+").

**Comment by aadcg** [comment]
>  How does + convey that some glyphs are not showing?

I see where you're going.

**Comment by aadcg** [comment]
[Shameless plug] If we get rid of the open "tabs" in the status bar and provide a button to get `buffer-list` as a side buffer, then we'd have plenty of space :)

**Comment by hendursaga** [comment]
I noticed this too, I was hoping to display most of the modes by designating a single glyph for each mode, perhaps even add color to make it easier to see??

**Comment by Ambrevar** [comment]
Feel free to commit this :)

**Comment by jmercouris** [comment]
Percentages is not a good idea. Please do not commit this! 10% of a small display and 10% of a large display do not scale in a way that makes sense for the amount of content.

**Comment by Ambrevar** [comment]
We can set an absolute upper bound, I believe.

**Comment by aartaka** [comment]
Or use media queries ¯\_(ツ)_/¯

**Comment by Ambrevar** [comment]
Nice!
