### ISSUE TITLE
Best practice to configure default modes

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#2453]
What's special about modes is that they can only be enabled once the buffer is ready to display, so after `customize-instance :after`.

So we can't enable them in `customize-instance` from the config file.  Try with `no-image-mode`, it will fail to enable.

So what can we do?  One option is to only instantiate the mode without enabling it, like so:

```lisp
(defmethod customize-instance ((buffer web-buffer) &key)
  (call-next-method)
  (alex:appendf (modes buffer)
                (mapcar (lambda (mode) (make-instance mode :buffer buffer))
                        '(nyxt/auto-mode:auto-mode
                          nyxt/no-image-mode:no-image-mode
                          nyxt/force-https-mode:force-https-mode
                          nyxt/no-image-mode:no-image-mode
                          nyxt/no-script-mode:no-script-mode
                          nyxt/proxy-mode:proxy-mode
                          nyxt/reduce-tracking-mode:reduce-tracking-mode))))
```

But it's not very obvious and yet quite verbose.  Can we do better?

We should at least document this.

**Comment by Ambrevar** [comment]
Note that the above only works since 122002c36ad2f03133c223a55735fe5168de1429.

**Comment by Ambrevar** [comment]
It would be great if we could make the design foolproof, e.g. by finalizing the instance just-in-time.
Maybe we could make use of `slot-unbound` or the like.

A difficulty is that the class can only be finalized during the next renderer loop cycle, thus asynchronously.

Note: This all could be redesigned together with the concurrency overhaul #2381.

**Comment by aartaka** [comment]
> The problem is that currently modes can specialize the generic function to make themselves a default. See for instance `mode/prompt-buffer`:
> 
> ```lisp
> (defmethod default-modes append ((buffer prompt-buffer))
>   '(prompt-buffer-mode))
> ```
> 
> How do you implement this with a slot?

You can always define a slot and make a reader method for it with additional combination etc.

I.e.

``` lisp
(define-class buffer ()
 ...
 (default-modes)
 ...)

(defgeneric default-modes (buffer)
  (:method-combination append))

(defmethod default-modes ((buffer buffer))
  (slot-value buffer 'default-modes))

(defmethod (setf default-modes) (new-value (buffer buffer))
  (setf (slot-value buffer 'default-modes) new-value))

(defmethod default-modes append ((buffer prompt-buffer))
 '(prompt-buffer-mode))
```

**Comment by Ambrevar** [comment]
Oh right, then it seems completely fair to have both indeed!

One last concern: this could tempt the user (or extension writers) to overwrite the list.  For instance `third-party-extension1` sets `default-modes` to `(third-party-mode1 base-mode)` and `third-party-extension1` sets it to `(third-party-mode2 base-mode)`.  Enabling both extensions means only 1 mode will be enabled.

Can we somehow mitigate this?

**Comment by aartaka** [comment]
I mean, if it's something a person is willingly installing as a set of extensions, then why should we interfere?

**Comment by Ambrevar** [comment]
So, here is what we can do:

- `define-configuration` should follow the practice of using the writer if it's available.  We can get it from `closer-mop:slot-definition-writers`.  If the writer is missing, fall back to the slot but print a warning.
- Then `default-modes` could only have a reader and no writer.  

Problem solved :)
