### ISSUE TITLE
Some buffers endlessly load and error WebKitJavascriptError with code 699 is reported when trying to kill them

### ISSUE THREAD

**Issue by rdrg109** [atlas-engineer/nyxt#2455]
**Describe the bug**

Some buffers endlessly load and they can't be closed because the following error is reported in the message area when trying to execute `delete-buffer` 

```
Warning: JavaScript error: GError: Domain: "WebKitJavascriptError", Code: 699, Message: 
```

The error is reported in the message area as shown in the image below.

![image](https://user-images.githubusercontent.com/74389646/178661581-cd97b254-75ad-4a99-935c-bd73893888b1.png)

**Precise recipe to reproduce the issue**

I was able to reproduce the issue by performing the following steps.

1. Launch Nyxt
2. Execute `make-window` in the current window (window no. 1) to create a new window (window no. 2)
3. From the new window (window no. 2), open a URL in the current buffer (buffer no. 2)
4. Kill window no. 2
5. Visit buffer no. 2 in window no. 1
6. Execute `delete-buffer`

At this point, the following message must be reported in the message area.

```
Warning: JavaScript error: GError: Domain: "WebKitJavascriptError", Code: 699, Message: 
```

At the bottom of this message, I've provided a video recording of the steps to reproduce this issue.

**Information**
- OS name+version: Arch Linux 5.18.10-arch1-1
- Graphics card and driver: NVIDIA GeForce RTX 2070 SUPER. NVIDIA Driver 515.57
- Desktop environment / Window manager name+version: EXWM 0.26
- How you installed Nyxt: build from source.
- Information from `show-system-information`:

```
Nyxt version: 2.2.5-1625-gc9a98dd7
Renderer version: GI-GTK
Operating system kernel: Linux 5.18.10-arch1-1
Lisp implementation: SBCL 2.2.5 (Dynamic space size: 3221225472)
Features: (:WEBKIT2 :WEBKIT2-2.36 :WEBKIT2-CORS-ALLOWLIST :WEBKIT2-PASTE-PLAINTEXT :WEBKIT2-TRACKING :WEBKIT2-MUTE :WEBKIT2-EMOJI :WEBKIT2-MEDIA :WEBKIT2-SANDBOXING :GTK-3-22 :GTK-3-20 :GTK-3-18 :GTK-3-16 :GTK-3-14 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6 :GTK-3-4 :GTK :GDK-3-22 :GDK-3-20 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12 :GDK-3-10 :GDK-3-8 :GDK-3-6 :GDK-3-4 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF :GLIB-2-30 :GLIB-2-32 :GLIB-2-34 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42 :GLIB-2-44 :GLIB-2-46 :GLIB-2-48 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56 :GLIB-2-58 :GLIB :NYXT-UNSTABLE :NYXT-GC9A98DD7 :NYXT-2.2.5 :NYXT-2.2 :NYXT-2 :CUSTOM-HASH-TABLE-NATIVE :SWANK :SLYNK :PLUMP-UTF-32 :FSET-EXT-STRINGS :PARENSCRIPT :GLOBAL-VARS :DECLARE-TYPES :NAMED-READTABLES :LPARALLEL :21BIT-CHARS :CLOSER-MOP :CL-PPCRE-UNICODE :CL-UNICODE :CL-PPCRE :CHUNGA :FLEXI-STREAMS :BORDEAUX-THREADS :LPARALLEL.WITH-CLTL2 :LPARALLEL.WITH-CAS :LPARALLEL.WITH-STEALING-SCHEDULER :SPLIT-SEQUENCE CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64 CFFI-FEATURES:UNIX :CFFI CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP :FAST-IO-SV :FAST-IO :CL-JSON-CLOS :CL-JSON :SBCL-USES-SB-ROTATE-BYTE CHIPZ-SYSTEM:GRAY-STREAMS :THREAD-SUPPORT :ASDF3.3 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX :NON-BASE-CHARS-EXIST-P :ASDF-UNICODE :X86-64 :GENCGC :64-BIT :ANSI-CL :COMMON-LISP :ELF :IEEE-FLOATING-POINT :LINUX :LITTLE-ENDIAN :PACKAGE-LOCAL-NICKNAMES :SB-CORE-COMPRESSION :SB-LDB :SB-PACKAGE-LOCKS :SB-THREAD :SB-UNICODE :SBCL :UNIX)

ASDF version: 3.3.1
ASDF registries: (NYXT-SOURCE-REGISTRY ENVIRONMENT-SOURCE-REGISTRY)
Critical dependencies: (/home/myusername/SourceCode/nyxt/_build/cl-cffi-gtk/gtk/cl-cffi-gtk.asd /home/myusername/SourceCode/nyxt/_build/cl-gobject-introspection/cl-gobject-introspection.asd /home/myusername/SourceCode/nyxt/_build/cl-webkit/webkit2/cl-webkit2.asd)

```

**Output when started from a shell**

The following output is from the actions shown in the video below the following code block.

```
$ rm -rf ~/.local/share/nyxt ~/.config/nyxt ~/.cache/nyxt
$ nyxt
Nyxt version 2.2.5-1625-gc9a98dd7
<INFO> [00:34:43] Source location: #P"/home/myusername/SourceCode/nyxt/"
<INFO> [00:34:43] Listening to socket #P"/run/user/1000/nyxt/nyxt.socket".
<INFO> [00:34:43] GTK extensions directory: #P"/usr/local/lib/nyxt/"
<INFO> [00:34:44] GTK extensions directory: #P"/usr/local/lib/nyxt/"
<INFO> [00:34:44] Loading #P"/home/myusername/.local/share/nyxt/history/default.lisp".
<INFO> [00:34:45] Loading #P"/home/myusername/.local/share/nyxt/bookmarks.lisp".
<INFO> [00:34:49] Loading "https://gentoo.org/".
<INFO> [00:34:50] Finished loading "https://www.gentoo.org/".
<INFO> [00:35:10] Loading "https://archlinux.org/".
<INFO> [00:35:12] Finished loading "https://archlinux.org/".
WARNING:WWARNING:WARNING:
   Attributes of #<WINDOW 588 {1010963F73}> should be a non-dotted alist instead of (("ID"
                                                                                      588)
                                                                                      588)
   Attributes of #<WINDOW 1885 {1011417B23}> should be a non-dotted alist instead of (("ID"
                                                                                     ("Active buffer"
                                                                                       1885)
                                                                                       1885)
                                                                                      "Welcome – Gentoo Linux"))
                                                                                      ("Active buffer"
                                                                                       "Arch Linux"))
<WARN> [00:35:18] Warning: JavaScript error: GError: Domain: "WebKitJavascriptError", Code: 699, Message: 
<WARN> [00:35:18] Warning: JavaScript error: GError: Domain: "WebKitJavascriptError", Code: 699, Message: 
<WARN> [00:35:22] Warning: JavaScript error: GError: Domain: "WebKitJavascriptError", Code: 699, Message: 
<WARN> [00:35:34] Cannot quit browser #<BROWSER {1007A74D13}> that is not ready.
<INFO> [00:35:34] Deleting socket #P"/run/user/1000/nyxt/nyxt.socket".
$ echo $?
0
```

In the video shown below, the error can be seen in the message area in the last seconds. The screenshot below the video shows the error.

[video.webm](https://user-images.githubusercontent.com/74389646/178661733-2b9ebd4e-314b-48f6-aa2a-a7dd147a4ec5.webm)

![image](https://user-images.githubusercontent.com/74389646/178661581-cd97b254-75ad-4a99-935c-bd73893888b1.png)

**Comment by Ambrevar** [comment]
I can reproduce even on 2.2.4 when built on a  recent Guix.

This didn't happen in the past, so I'm unsure what triggered it.  Maybe a cl-webkit update?

@aartaka Any idea?

**Comment by aartaka** [comment]
Maybe also detach the buffer from the window box, to be certain?

**Comment by aartaka** [comment]
Oh wait, that's exactly what we do already...

**Comment by aartaka** [comment]
@Ambrevar, see the [Gtk.Container.remove](https://docs.gtk.org/gtk3/method.Container.remove.html) docs:

> Removes widget from container. widget must be inside container. Note that container will own a reference to widget, and that this may be the last reference held; so removing a widget from its container can destroy that widget. If you want to use widget again, you need to add a reference to it before removing it from a container, using g_object_ref(). If you don’t want to use widget again it’s usually more efficient to simply destroy it directly using gtk_widget_destroy() since this will remove it from the container and help break any circular reference count cycles.

It may be that the `gtk-object` of the buffer loses the last reference it has and gets deleted :thinking: 

Maybe then reference it before removing from the container?

**Comment by rdrg109** [comment]
I can confirm this has been fixed. I tried reproducing the issue with 2.2.5-1696-gcd632f0e and it didn't happen anymore.

**Comment by Ambrevar** [comment]
Thanks a lot, @aartaka , this bug really got me worried :/
