### ISSUE TITLE
`return-actions` of `hint-mode`

### ISSUE THREAD

**Issue by aadcg** [atlas-engineer/nyxt#2457]
It seems that hovering or focusing doesn't always work. Navigate to https://en.wikipedia.org/wiki/Eudicots, run `follow-hints` and try to hover/focus a hint outside viewport.

Also, what's the difference between the `identity` action and `click*`?

**Comment by aartaka** [comment]
- Focusing is only defined for inputs.
- Hovering seems to be unreliable working on the JavaScript side.
- The difference between the default action and `click*` is that default action doe the most sensible thing for every particular type of an element. For example, it clicks `<button>`s, focuses `<input>`s and prompts for the `<select>` value.
