### ISSUE TITLE
nyxt 3-pre-release-1 (.deb package): Warning about ASDF older than 2.27 at start up

### ISSUE THREAD

**Issue by johanwiden** [atlas-engineer/nyxt#2459]
When starting nyxt it complains I have an older version of ASDF installed, but I do not have ASDF installed as far as I am aware. I did not have this problem with nyxt 2.2.4.

I am using Ubuntu 22.4. I did not have package cl-asdf installed. I then installed it, but it made no difference.
Running "locate asdf.asd" turns up nothing.

Here is the warning:
WARNING:
   You are using ASDF version 3.3.4 from
   #P"/home/runner/common-lisp/asdf/asdf.asd" and have an older version of ASDF
   (and older than 2.27 at that) registered at
   #P"/home/runner/common-lisp/asdf/asdf.asd". Having an ASDF installed and
   registered is the normal way of configuring ASDF to upgrade itself, and
   having an old version registered is a configuration error. ASDF will ignore
   this configured system rather than downgrade itself. In the future, you may
   want to either: (a) upgrade this configured ASDF to a newer version, (b)
   install a newer ASDF and register it in front of the former in your
   configuration, or (c) uninstall or unregister this and any other old version
   of ASDF from your configuration. Note that the older ASDF might be
   registered implicitly through configuration inherited from your system
   installation, in which case you might have to specify
   :ignore-inherited-configuration in your in your
   ~/.config/common-lisp/source-registry.conf or other source-registry
   configuration file, environment variable or lisp parameter. Indeed, a likely
   offender is an obsolete version of the cl-asdf debian or ubuntu package,
   that you might want to upgrade (if a recent enough version is available) or
   else remove altogether (since most implementations ship with a recent asdf);
   if you lack the system administration rights to upgrade or remove this
   package, then you might indeed want to either install and register a more
   recent version, or use :ignore-inherited-configuration to avoid registering
   the old one. Please consult ASDF documentation and/or experts.

; 
; compilation unit aborted
;   caught 1 fatal ERROR condition
Nyxt version 3-pre-release-1
<INFO> [09:50:28] Source location: #P"/usr/local/share/nyxt/"
<INFO> [09:50:28] Listening to socket #P"/run/user/1000/nyxt/nyxt.socket".
<INFO> [09:50:28] GTK extensions directory: #P"/usr/local/share/nyxt/libraries/web-extensions/"
<INFO> [09:50:28] Loading #P"/home/jw/.local/share/nyxt/history/default.lisp".
<INFO> [09:50:29] Restoring 1 buffer from history.
<INFO> [09:50:29] GTK extensions directory: #P"/usr/local/share/nyxt/libraries/web-extensions/"
<INFO> [09:50:29] Loading "https://lwn.net/Articles/900299/".
<INFO> [09:50:31] Finished loading "https://lwn.net/Articles/900299/".

I do not have the directory /home/runner on my computer, so I guess this is in some container or chroot-ed directory.

I am able to use nyxt, so this issue is not a show stopper. But it is annoying and I can no longer start nyxt from emacs.

**Comment by Ambrevar** [comment]
This is very odd since the .deb package is explicitly built with ASDF 3.3.4.  From `build-scripts/build-ubuntu-package.sh`:

```sh
## Modern ASDF needed.
git clone --depth=1 --branch=3.3.4 https://gitlab.common-lisp.net/asdf/asdf.git ~/common-lisp/asdf/ &> /dev/null
```

The message complains that about 2 different ASDF at the same path!! How is this possible?

I need to investigate.

> But it is annoying and I can no longer start nyxt from emacs.

Out of curiosity, why?

**Comment by Ambrevar** [comment]
Which communication?  Nyxt does not depends on Emacs, what do you mean?

**Comment by Ambrevar** [comment]
You may be mixing up `DESTDIR` with `PREFIX` ;)

**Comment by johanwiden** [comment]
About PREFIX/DESTDIR: The file INSTALL does not mention PREFIX, but there seems to be some use of it further down in the directories.
I realized later that I did not specify DESTDIR from the start, only when executing "make install". This might have caused the problem.
It might be a good idea to add a default declaration of DESTDIR to the top level makefile. It could perhaps be commented out. This would encourage users to provide a consistent value for DESTDIR, if needed.

**Comment by johanwiden** [comment]
I now specified DESTDIR in the top level makefile (with an export statement). It still installed in the same unexpected place.
I was unable to "make clean":
  git submodule deinit  --all
  fatal: not a git repository (or any of the parent directories): .git
  make: *** [makefile:92: clean-submodules] Error 128
Instead I extracted the tar file in a new directory and copied over the makefile from the old directory.
Then:
- make all
- make install

**Comment by johanwiden** [comment]
I downloaded https://github.com/atlas-engineer/nyxt/releases/download/3-pre-release-1/nyxt-3-pre-release-1-source-with-submodules.tar.xz
I extracted this tar archive in an empty directory. I modified the makefile according to the file INSTALL, then built, and then did make install DESTDIR=...
This installed in an unexpected place, so I added the DESTDIR specification to the makefile.
I now tried to do make clean, but that errored out, according to my previous message.
So I now created a new directory, extracted the tar archive there, copied the old (modified) makefile to the new directory, then did make all, make install.

Perhaps the README in the release directory should include a description of how to, as an alternative, clone the Nyxt repo, and build the intended version there.

**Comment by Ambrevar** [comment]
Sorry, I do not clearly understand the problem.

What you want to do, I think, is set `DESTDIR` to your home, and `PREFIX` to `""`.

That said, you seem to be building Nyxt as if it was using the autotools (`./configure` and friends), but it's not, so installing to your home this way is really not recommended, as you'd have no way of keeping track of the files.

Instead,  you are much better off either

- using the .deb package (the ASDF warning is completely benign but I'll work on it anyways)
- or, if you build from source, just don't install anything and symlink `nyxt` to your `PATH` (or add the Nyxt checkout to your `PATH`).

That `make clean` does not work with the `tar.xz` archive is expected.

**Comment by johanwiden** [comment]
Thanks for the info! I will symlink to the nyxt in the build directory as you suggest.
I think some info about that should be included in the INSTALL file.

Though I do not think it is so difficult to keep track of the files: Almost everything installs under share/nyxt/libraries and share/nyxt/source. The exceptions are the binary, the icons, and the .desktop file.

**Comment by Ambrevar** [comment]
But this may change in the future ;)

In all cases, Nyxt is not meant to be installed like this.  `INSTALL` is useful for packagers, but really if you want to install Nyxt you are much better of installing it as a package for your OS.

**Comment by aadcg** [comment]
@Ambrevar I don't think there's anything left to do from our side.

Please re-open if I've misunderstood it.
