### ISSUE TITLE
Installing the 3-pre-release-1 from a DEB package fails with an unmet dependencies error

### ISSUE THREAD

**Issue by ska80** [atlas-engineer/nyxt#2468]
**Describe the bug**
Installing the 3-pre-release-1 from a DEB package on Ubuntu 22.04 LTS (Jammy) fails with the following unmet dependencies error:

```
$ sudo apt install ./nyxt_3_amd64.deb 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'nyxt' instead of './nyxt_3_amd64.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 nyxt : Depends: libssl1.1 but it is not installable
        Depends: libssl1.1 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

By the way, installing the previous stable Nyxt 2.x.x succeeds without any problems.

**Precise recipe to reproduce the issue**
1. Download the [3-pre-release-1](https://github.com/atlas-engineer/nyxt/releases/download/3-pre-release-1/nyxt_3_amd64.deb) DEB package
2. Install with the following command: `sudo apt install ./nyxt_3_amd64.deb`

**Information**
- OS name+version: Ubuntu 22.04 LTS (Jammy)
- Graphics card and driver: Mesa Intel® Xe Graphics (TGL GT2)
- Desktop environment / Window manager name+version: Gnome 42.2
- How you installed Nyxt (Guix pack, package manager, build from source): APT package manager
- Information from `show-system-information`: n/a

**Comment by Ambrevar** [comment]
> Note, selecting 'nyxt' instead of './nyxt_3_amd64.deb'

This is odd, is nyxt in a one of your repos?  What does `apt search nyxt` return?

This is the list of deps for the .deb package:

```lisp
("libfixposix-dev" ; Because we need libfixposix.so, not just libfixposix.so.3.
                            "libwebkit2gtk-4.0-dev" ; Same.
                            "glib-networking"
                            "gsettings-desktop-schemas"
                            "xclip"
                            "enchant-2")
```

No libssl there :p 

Can you share the exact recipe you've used to install Nyxt 2.*?

**Comment by ska80** [comment]
> > Note, selecting 'nyxt' instead of './nyxt_3_amd64.deb'

I am not sure, and it might be somehow related to previously installing Nyxt 2 on the same machine...  But it is completely removed from my OS now with `apt autoremove --purge nyxt` command.
 
> This is odd, is nyxt in a one of your repos?

Nope.  `dpkg -l | grep -i nyxt` shows nothing.

> What does `apt search nyxt` return?

It returns nothing as I use only standard Ubuntu repos plus two third-party repos for OBS and Firefox. ESR.

> This is the list of deps for the .deb package:
> 
> ```lisp
> ("libfixposix-dev" ; Because we need libfixposix.so, not just libfixposix.so.3.
>                             "libwebkit2gtk-4.0-dev" ; Same.
>                             "glib-networking"
>                             "gsettings-desktop-schemas"
>                             "xclip"
>                             "enchant-2")
> ```
> 
> No libssl there :p

Hmmm...

> Can you share the exact recipe you've used to install Nyxt 2.*?

Well, I just downloaded the latest Nyxt 2 DEB package from this GitHub repo at https://github.com/atlas-engineer/nyxt/releases/download/2.2.4/nyxt_2.2.4_amd64.deb and installed it the same way I am trying to install the new Nyxt 3 DEB package.

Anyway, thanks a lot for looking into this issue :)

**Comment by ska80** [comment]
> > apt autoremove --purge nyxt
> 
> This could be your problem. I'm not an APT expert, but in the past I've run into issues where a package wasn't removed because of abusing some `--purge` parameters or the like. I could be wrong though.
> 
> Other Ubuntu users seem to be installing the .deb package just fine, so I'm suspecting the issue is on your side. Could you try reaching out to your favourite Ubuntu community?

Thanks, I will do that.

**Comment by ska80** [comment]
Apparently, Ubuntu 22.04 has upgraded libssl to 3, and does not propose libssl1.1.  But here is a workaround:

```shell
$ wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.0g-2ubuntu4_amd64.deb
$ sudo dpkg -i ./libssl1.1_1.1.0g-2ubuntu4_amd64.deb
```

After that, I can install the latest Nyxt 3.

**Comment by Ambrevar** [comment]
Thanks for sharing!  I see 22.04 is an LTS, so I'll update the build for it then.

**Comment by Ambrevar** [comment]
Or is it too soon?  I'm not sure now...

**Comment by Ambrevar** [comment]
In the meantime, I've added the aforementioned commands to the instructions for the next release.
