### ISSUE TITLE
Polish the interactive/non-interactive distinction handling

### ISSUE THREAD

**Issue by aartaka** [atlas-engineer/nyxt#2470]
In 92a7bf24c44124f36937f627e376fbcf62a0527c, there appeared an `*interactive-p*` flag, which caused me many countless hours of debugging with no error reports and clues to why the prompt doesn't appear and the code silently fails. The reasoning behind the `*interactive-p*`—separating the calls stemming from user interaction from those that are scripted—does make sense, but the implementation interferes with lots of workflows, thus making me put a magical `(let ((*interactive-p* t)) ...)` everywhere to make things work (see 62b7dc93f2fa5b0daf34eb5084f02cbaa15399d2, 7ba4b99c229314eecc85e89f1f8ba398257529e4, 1303731feee3dba33ad0e890bf1d9ee1267bb3ee, and possibly other commits that don't mention interactivity in the commit message).

Given the number of opaque and hard-to-debug problems that `*interactive-p*` caused us, is it actually worth retaining, especially in an incomplete state it is in now? By "incomplete state" I mean that right now it simply cuts off all the prompts, while a proper non-interactive use would allow providing some default value or code snippet to replace/return from the prompt. Like... `prompt-buffer-ready-hook`, for example. It's already there, it's perfectly hookable programmatically, and is friendly towards both interactive and non-interactive workflows. 

I don't see what `*interactive-p*` adds to Nyxt, except the necessity to put magic let-bindings everywhere. We have a way to delineate interactive (i.e. user-facing) interactions from the non-interactive (i.e. headless and script) ones. We have ways (`prompt-buffer-ready-hook`, `prompter:all-ready-p` etc.) to handle prompting, and these ways are reliable enough to rely on them in the non-interactive context.

An alternative to removing `*interactive-p*` would be to allow default values, something-instead-of-prompt computation, or any other way to meaningfully replace prompt calls killed by `*interactive-p*`. But still, I don't see how the value `*interactive-p*` brings is worth adding a ton of new code to `prompter` and `prompt-buffer`.

I may be wrong with this rant, though. If there's some part of a picture that I don't see, please explain it to me!

CC @Ambrevar, @jmercouris, @aadcg

**Comment by Ambrevar** [comment]
The intent of `*interactive-p*` is to prevent dead locks, or at least to catch them.

Let me explain: if a blocking portion of code tries to open a prompt buffer while non-interactive, this code will block forever.  This is of course really bad.

Now `*interactive-p*`  would not be such a pain in the ass if it would raise a condition every time such things occur.  In my experience it works.  I don't quite understand why the condition is silenced sometimes.  If we can figure this out, it would help a lot! :)

> An alternative to removing *interactive-p* would be to allow default values, 

This may be a good idea indeed, at least in terms of API.  But I believe it would be equivalent to the current API, if not a bit more convenient.  Indeed, if the programmer didn't provided a default value _and_ we are not interactive, then we would raise a condition.

**Comment by aartaka** [comment]
> Let me explain: if a blocking portion of code tries to open a prompt buffer while non-interactive, this code will block forever. This is of course really bad.

But wait, will it block because of some multithreading issue, or because prompt-buffer does not receive the input/result from the user and thus infinitely waits for it? Because if it's the latter, then it still doesn't make sense -- if some non-interactive code tries to consciously call `prompt`, then it should also simulate input/selection for opened prompt. 

Am I missing something else?

**Comment by aartaka** [comment]
It still feels wrong to me, even though now I see the problem you're trying to solve.

**Comment by Ambrevar** [comment]
I'm not claiming this is a good solution, only that it's a first step and I'm trying to iterate from there.

**Comment by aartaka** [comment]
Yes, sorry :)

**Comment by Ambrevar** [comment]
Nothing to be sorry about :)  I know it sucks, but it's a hard problem we've got to solve one way or the other!

**Comment by hendursaga** [comment]
Whatever you end up with, please please don't end up with some [Emacspeak-esque deep magic](https://github.com/tvraman/emacspeak/blob/a539d65bd4e7072aea29e675bcf16142646cee25/info/ems-interactive-p.org)..
