### ISSUE TITLE
proxy-mode cannot be disabled

### ISSUE THREAD

**Issue by hendursaga** [atlas-engineer/nyxt#2472]
Whenever I attempt to navigate to a site where my auto-mode-rules disables `proxy-mode` it fails with `Error on GI-GTK thread: NIL is not a Lisp string or pointer.` Using the steps I listed in https://github.com/atlas-engineer/nyxt/issues/2466#issue-1306346626 I was able to narrow it down to something with https://github.com/atlas-engineer/nyxt/blob/9ce47b4083a2bb12db271242334352c27d2560a6/source/renderer/gtk.lisp#L1854-L1884 and probably with the CFFI foreign call. I had a better error trace a few days earlier but now the steps above that I used before causes Nyxt to crash.

**Comment by Ambrevar** [comment]
@aartaka Do you understand why this suddenly broke?  Or was it always broken when the proxy-specifier had no ignore-hosts?

**Comment by aartaka** [comment]
No, I don't understand a thing ｜−・;） Maybe it was just a typo or something?

Or maybe it was some CFFI update. I've encountered some errors when trying to thanslate NIL to C NULL recently, even though I vaguely remember it being a valid translation...

No certainty, though :(
