### ISSUE TITLE
Quick Lisp extensions installation

### ISSUE THREAD

**Issue by aartaka** [atlas-engineer/nyxt#2473]
**Is your feature request related to a problem? Please describe.**

Our Lispy extensions installation is quite manual as of July 2022 -- git cloning to a certain directory, then ASDF-loading in the config file. Could use some love & automation there. 

**Describe the solution you'd like**

Make a command (or button) to basically make extension installation easy as one action and Nyxt restart. A prototype can be found in https://github.com/atlas-engineer/nyxt/pull/2093.

**Describe alternatives you've considered**

Relying on package managers?

**Comment by jmercouris** [comment]
Indeed, what Andre said.
