### ISSUE TITLE
Add a toggle-maximize command

### ISSUE THREAD

**Issue by maggiplant** [atlas-engineer/nyxt#2474]
**Is your feature request related to a problem? Please describe.**
Nyxt currently has only toggle-fullscreen, which hides the window's bar and does not allow the user to easily move Nyxt out of the way to interact with other applications.

**Describe the solution you'd like**
I would like Nyxt to have a toggle-maximize function which toggles whether the Nyxt window is maximized or not. This would users to maximize Nyxt without e.g. double-clicking the window bar. This would also make it possible to maximize Nyxt from config.lisp/init.lisp or a REPL.

**Describe alternatives you've considered**
I've considered adding 
```
(define-command-global maximize-window ()
  (gtk:gtk-window-maximize (gtk-object (current-window))))
```

to my init.lisp, but upstreaming this as a toggle command (like toggle-fullscreen is) seemed better.

**Additional context**
None

**Comment by aartaka** [comment]
Indeed, this rather belongs to upstream :D 

I suppose you know how to do that already and can look at `toggle-fullscreen` source. Would you be willing to open a PR with your implementation of this command? :)

**Comment by maggiplant** [comment]
Sure, I was just going to. I'm having a bit of trouble with getting my fork up to date with this repo, though. Never really used git merge before 😅

**Comment by aartaka** [comment]
No pressure, no hurry, good luck with that :)
