### ISSUE TITLE
CEF(Chromium embeded framework)

### ISSUE THREAD

**Issue by LinArcX** [atlas-engineer/nyxt#2476]
There's a thread on reddit that discussing about using another brower engine in nyxt:

https://www.reddit.com/r/Nyxt/comments/sg9yka/comment/huzhcz3/

I'm curious to know why there is no plan to use CEF in nyxt? Is there any issue for using it?

**Comment by Ambrevar** [comment]
It's on the backburner... :)

**Comment by hendursaga** [comment]
I believe @aartaka is the one toying around with a prototype or design..

**Comment by aartaka** [comment]
> I believe @aartaka is the one toying around with a prototype or design..

Yes, but I'm overly conscious of talking about it before I can say it works!

**Comment by aadcg** [comment]
Superseded by #2989.

We may come back to this goal in the future, but it is not planned at the moment.
