### ISSUE TITLE
CLOG and Nyxt coexistence

### ISSUE THREAD

**Issue by montaropdf** [atlas-engineer/nyxt#2478]
I recently found this common lisp project and was wondering if Nyxt could benefit or integrate it, mainly for module developers.

https://github.com/rabbibotton/clog

**Comment by Ambrevar** [comment]
Yes, I've been eyeing it for a while to!  CLOG could potentially be leveraged as a UI library (e.g. for the internal pages).

I haven't used it yet though.

**Comment by montaropdf** [comment]
> Yes, I've been eyeing it for a while to! CLOG could potentially be leveraged as a UI library (e.g. for the internal pages).
> 
> I haven't used it yet though.

I didn't use it neither, yet, some of the demo I have seen are quite enticing.

**Comment by jmercouris** [comment]
Maybe in the future. Probably not. We have our own UI system :-D
