### ISSUE TITLE
Nyxt crashes with `fatal error encountered in SBCL` on startup

### ISSUE THREAD

**Issue by Anomalocaridid** [atlas-engineer/nyxt#2482]
**Describe the bug**
Whenever I try to start Nyxt, I get an error saying `fatal error encountered in SBCL`. The full error is in the terminal shell output at the bottom. However, I can use some commands that just output to the terminal like `nyxt --help` and `nyxt --system-information` just fine. This seems to occur regardless of whether or not my config is loaded. Also, it does not seem to necessarily be a problem with SBCL itself, because I can run that just fine on its own.

**Precise recipe to reproduce the issue**
1. Run `nyxt` in a terminal shell
2. Rather than Nyxt opening, it will crash with the error

For website-specific issues:
Can you reproduce this issue with Epiphany / GNOME Web (https://wiki.gnome.org/Apps/Web)?
N/A

**Information**
- OS name+version: EndeavourOS Sway Rolling
- Graphics card and driver: AMD Radeon RX 580 and AMDGPU
- Desktop environment / Window manager name+version: sway version 1.7
- How you installed Nyxt (Guix pack, package manager, build from source): nyxt-browser-git AUR package
- Information from `show-system-information`:
```
Nyxt version: 3-pre-release-1-129-g65129754c
Renderer version: GI-GTK
Operating system kernel: Linux 5.18.14-arch1-1
Lisp implementation: SBCL 2.2.5 (Dynamic space size: 3221225472)
Features: (:WEBKIT2 :WEBKIT2-2.36 :WEBKIT2-CORS-ALLOWLIST :WEBKIT2-PASTE-PLAINTEXT
 :WEBKIT2-TRACKING :WEBKIT2-MUTE :WEBKIT2-EMOJI :WEBKIT2-MEDIA
 :WEBKIT2-SANDBOXING :GTK-3-22 :GTK-3-20 :GTK-3-18 :GTK-3-16 :GTK-3-14
 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6 :GTK-3-4 :GTK :GDK-3-22 :GDK-3-20
 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12 :GDK-3-10 :GDK-3-8 :GDK-3-6 :GDK-3-4
 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF :GLIB-2-30 :GLIB-2-32 :GLIB-2-34
 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42 :GLIB-2-44 :GLIB-2-46 :GLIB-2-48
 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56 :GLIB-2-58 :GLIB :NYXT-3
 :CUSTOM-HASH-TABLE-NATIVE :SLYNK :PLUMP-UTF-32 :PARENSCRIPT :FSET-EXT-STRINGS
 :GLOBAL-VARS :DECLARE-TYPES :SBCL+SAFE-STANDARD-READTABLE :NAMED-READTABLES
 :SWANK :LPARALLEL :21BIT-CHARS :CLOSER-MOP :CL-PPCRE-UNICODE :CL-UNICODE
 :CL-JSON-DOUBLE-FLOAT-IS-SUBSUMED :CL-JSON-SINGLE-FLOAT-IS-SUBSUMED :CL-PPCRE
 :CHUNGA :FLEXI-STREAMS :BORDEAUX-THREADS :LPARALLEL.WITH-CLTL2
 :LPARALLEL.WITH-CAS :LPARALLEL.WITH-STEALING-SCHEDULER :SPLIT-SEQUENCE
 CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64 CFFI-FEATURES:UNIX :CFFI
 CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP :FAST-IO-SV :FAST-IO
 :CL-JSON-CLOS :CL-JSON :SBCL-USES-SB-ROTATE-BYTE CHIPZ-SYSTEM:GRAY-STREAMS
 :THREAD-SUPPORT :ASDF3.3 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX
 :NON-BASE-CHARS-EXIST-P :ASDF-UNICODE :X86-64 :GENCGC :64-BIT :ANSI-CL
 :COMMON-LISP :ELF :IEEE-FLOATING-POINT :LINUX :LITTLE-ENDIAN
 :PACKAGE-LOCAL-NICKNAMES :SB-CORE-COMPRESSION :SB-LDB :SB-PACKAGE-LOCKS
 :SB-THREAD :SB-UNICODE :SBCL :UNIX)

ASDF version: 3.3.1
ASDF registries: (NYXT-SOURCE-REGISTRY ENVIRONMENT-SOURCE-REGISTRY)
Critical dependencies: (/home/anomalocaris/.cache/paru/clone/nyxt-browser-git/src/nyxt-browser/_build/cl-cffi-gtk/gtk/cl-cffi-gtk.asd
 /home/anomalocaris/.cache/paru/clone/nyxt-browser-git/src/nyxt-browser/_build/cl-gobject-introspection/cl-gobject-introspection.asd
 /home/anomalocaris/.cache/paru/clone/nyxt-browser-git/src/nyxt-browser/_build/cl-webkit/webkit2/cl-webkit2.asd)
```
  If you can't run `show-system-information`, try `nyxt --system-information` from
  a shell.  It this still does not work, please provide the following:
  - Nyxt version (from the `nyxt-version` command or `nyxt --version` from a shell):
  - Lisp implementation/version (if built from source):
  - Kernel name+version:
  - WebKitGTK+ | QtWebEngine version:

**Output when started from a shell**
```
Arguments parsed: (NO-CONFIG T VERBOSE T URLS NIL) and NIL
Nyxt version 3-pre-release-1-129-g65129754c
 <INFO> [11:09:40] nyxt start.lisp (start-browser) -
  Source location: #P"/usr/local/share/nyxt/"
 <INFO> [11:09:40] nyxt start.lisp (listen-or-query-socket) -
  Listening to socket #P"/run/user/1000/nyxt/nyxt.socket".
<DEBUG> [11:09:40] nyxt start.lisp (load-lisp unsafe-load) -
  Lisp file #P"/home/anomalocaris/.config/nyxt/auto-config.3.lisp" does not exist.
<DEBUG> [11:09:40] nyxt gi-gtk.lisp (ffi-initialize gtk-browser) -
  Initializing GI-GTK Interface
fatal error encountered in SBCL pid 23954 tid 23979:
SIGABRT received.

   0: fp=0x7fed1ec6f640 pc=0x7fed40ecb36c Foreign function (null)
```

**Comment by hendursaga** [comment]
So you ran with `nyxt -I -C`?

**Comment by Anomalocaridid** [comment]
I ran it with `nyxt -I --verbose`. Somehow, I wasn't aware of the `-C` flag, so I just temporarily moved my auto config file to another directory. Running `nyxt -I -C --verbose` does not appear to make much of a difference though:

```
Arguments parsed: (NO-CONFIG T NO-AUTO-CONFIG T VERBOSE T URLS NIL) and NIL
Nyxt version 3-pre-release-1-129-g65129754c
 <INFO> [17:47:20] nyxt start.lisp (start-browser) -
  Source location: #P"/usr/local/share/nyxt/"
 <INFO> [17:47:20] nyxt start.lisp (listen-or-query-socket) -
  Listening to socket #P"/run/user/1000/nyxt/nyxt.socket".
<DEBUG> [17:47:20] nyxt gi-gtk.lisp (ffi-initialize gtk-browser) -
  Initializing GI-GTK Interface
fatal error encountered in SBCL pid 6712 tid 6737:
SIGABRT received.

   0: fp=0x7f37f795f640 pc=0x7f3819d8936c Foreign function (null)
```

**Comment by apisandipas** [comment]
I can confirm I'm getting the same issue. My setup is near identical, only I'm on vanilla Arch. This happens with both the Community Arch package and the AUR package.

**Comment by tbreslein** [comment]
Same on my NixOS setup, installed via the nixos-unstable channel. Same error, though it drops me into the list debug prompt afterwards. Also tried running it from the terminal with `-I -C`.

**Comment by Ambrevar** [comment]
I cannot reproduce.  Please everyone can you report your SBCL version?
I suspect this is due to a critical flaw of SBCL 2.2.5.
Try upgrading to 2.2.6 (or downgrading to 2.2.2).

**Comment by jetske-beks** [comment]
Changing SBCL version did not work for me: 2.2.2, 2.2.4, 2.2.5, 2.2.6 and 2.2.7 all resulted in the same crash.
I'm on vanilla Arch, tried with both Nyxt v2.2.4 from the repo and v3 from AUR.

**Comment by hendursaga** [comment]
Not sure if this is related, but I cannot build Nyxt anymore with SBCL 2.2.7.. it crashes, I'm trying to isolate the issue and see how related it is.

For everyone else: perhaps deleting (or at least renaming) your CL cache ($HOME/.cache/common-lisp) for a particular SBCL version and then rebuild might help?? I've found things sometimes "accumulate" over a period of time.

**Comment by Anomalocaridid** [comment]
I tried deleting my common lisp cache and doing a clean build and it does not appear to fix anything. I have SBCL 2.2.5, which appears to be the most recent version packaged on Arch Linix's official repositories.

**Comment by apisandipas** [comment]
I tried running it again randomly and now everything is working. I didnt see anything in my latest update that might have fixed it, but it's working for me again, both the Community Arch Package and the Pre-release from the AUR.

**Comment by Anomalocaridid** [comment]
I can also confirm Nyxt works again for me after updating. I noticed that `webkit2gtk` and `webkit2gtk-4.1` were also updated. Since `webkit2gtk-4.1` appears to be one of Nyxt's dependencies, that might be what changed and fixed everything.

**Comment by Ambrevar** [comment]
Thank you for the update.  Maybe notify the Nix maintainers of the Arch update and the Nyxt issue, they might have to roll out a similar fix.

**Comment by tbreslein** [comment]
Yep, guess we'll wait for the `webkitgtk` version updates, but this isn't an issue for nyxt anymore as far as it concerns me and other NixOS users.

**Comment by Anomalocaridid** [comment]
In that case, if everything's all good on Nyxt's end regarding this issue, I'll go ahead and close it.
