### ISSUE TITLE
Nyxt hangs on quit

### ISSUE THREAD

**Issue by shamazmazum** [atlas-engineer/nyxt#2488]
**Describe the bug**

Hi! I am on commit 02bced0. Nyxt hangs when I press `C-x C-c` (using emacs scheme). Only `killall -9 nyxt` helps to kill it.

**Precise recipe to reproduce the issue**

1. Open nyxt. 
2. Go to any website (I type `M-l example.com RET`)
3. Press `C-x C-c` or invoke `quit` command (I think just closing the window will do).
4. Now nyxt hangs and can be only killed with SIGKILL.

**Information**
- OS name+version: FreeBSD 13.1-RELEASE
- How you installed Nyxt (Guix pack, package manager, build from source): Commit 02bced0 + dependencies via Ultralisp
- WebKitGTK+ | QtWebEngine version: webkit2-gtk3-2.34.6_3 from FreeBSD ports
- SBCL 2.2.6

Nyxt closes normally when I comment out the line `(ffi-kill-browser *browser*) ` in `(define-command quit ...)` (`source/start.lisp`).

**Comment by aadcg** [comment]
I can't reproduce.

**Comment by aartaka** [comment]
Neither can I :cold_sweat:

**Comment by shamazmazum** [comment]
![20220802_11h22m23s_grim](https://user-images.githubusercontent.com/812069/182328786-f4060828-5b76-4ea9-9690-6e666e47ce7a.png)

This is a screenshot of terminal with nyxt after step 3 + top. You can see nyxt and few WebKit processes.

**Comment by shamazmazum** [comment]
@aadcg @aartaka 

Do you use FreeBSD or try it on Linux or something else?

**Comment by shamazmazum** [comment]
This fixed the problem for me. Should I open a PR?

~~~~{.lisp}
vasily@vonbraun:~/.quicklisp/local-projects/nyxt % git diff
diff --git a/source/renderer/gtk.lisp b/source/renderer/gtk.lisp
index f078a45f0..df5cc4875 100644
--- a/source/renderer/gtk.lisp
+++ b/source/renderer/gtk.lisp
@@ -259,7 +259,7 @@ the renderer thread, use `defmethod' instead."
             (finalize browser urls startup-timestamp)))
         (unless *run-from-repl-p*
           (gtk:join-gtk-main)
-          (uiop:quit (slot-value browser 'exit-code))))
+          (uiop:quit (slot-value browser 'exit-code) nil)))
       #+darwin
       (progn
         (setf gtk-running-p t)
diff --git a/source/start.lisp b/source/start.lisp
index a9545d4a9..4acc753a0 100644
--- a/source/start.lisp
+++ b/source/start.lisp
@@ -173,14 +173,7 @@ Example: --with-file bookmarks=/path/to/bookmarks
             (log:info "Deleting socket ~s." socket)
             (uiop:delete-file-if-exists socket))))
       (mapc #'destroy-thread* (non-terminating-threads *browser*))
-      (ffi-kill-browser *browser*)
-      (unless *run-from-repl-p*
-        (run-thread "force-quitter"
-          ;; Force-quit in case `ffi-kill-browser' hangs.  Must be run in a
-          ;; separate thread because the renderer loop is waiting for this
-          ;; function to finish.
-          (sleep 1)
-          (uiop:quit code nil))))))
+      (ffi-kill-browser *browser*))))

 (define-command quit-after-clearing-session (&key confirmation-p) ; TODO: Rename?
   "Close all buffers then quit Nyxt."
~~~~

**Comment by aartaka** [comment]
Hmmm, that is strange. It should work the exact opposite of what you describe 0_o

The `uiop:quit code nil` is safe, this I'm OK with accepting as a PR. The kill thread we have to understand first :thinking:

If it's reproducible on *BSD, then we can add a feature macro so that this thread is not created. But still, better to understand what's going on...

**Comment by aartaka** [comment]
> Do you use FreeBSD or try it on Linux or something else?

Yeah, I'm trying it on Linux :sweat_smile: Same is true of @aadcg, I believe.

**Comment by shamazmazum** [comment]
Actually this fixes the bug for me:

~~~~
vasily@vonbraun:~/.quicklisp/local-projects/nyxt % git diff
diff --git a/source/renderer/gtk.lisp b/source/renderer/gtk.lisp
index f078a45f0..8dabe7a36 100644
--- a/source/renderer/gtk.lisp
+++ b/source/renderer/gtk.lisp
@@ -259,7 +259,7 @@ the renderer thread, use `defmethod' instead."
             (finalize browser urls startup-timestamp)))
         (unless *run-from-repl-p*
           (gtk:join-gtk-main)
-          (uiop:quit (slot-value browser 'exit-code))))
+          (uiop:quit (slot-value browser 'exit-code nil))))
       #+darwin
       (progn
         (setf gtk-running-p t)
~~~~~

When `finish-output` is `t` the process hangs. Creation of the thread is irrelevant, sorry.

**Comment by aartaka** [comment]
Cool!

**Comment by shamazmazum** [comment]
How should I do it in a PR? Do I need something like
`(uiop:quit (slot-value browser 'exit-code #+freebsd nil #-freebsd t))` or just `nil` for all platforms? And is the killer thread really needed then? Maybe the same problems with `force-output = t` hit linux, but cause less damage?

**Comment by aartaka** [comment]
> How should I do it in a PR? Do I need something like `(uiop:quit (slot-value browser 'exit-code) #+freebsd nil #-freebsd t)` or just `nil` for all platforms? 

I'd go with the feature macro there.

> And is the killer thread really needed then? 

Let's leave it, at least for Linux

> Maybe the same problems with `force-output = t` hit linux, but cause less damage?

I don't remember any reports of quit hangs on Linux, and I had none in my own usage, so I'm not sure :)

**Comment by shamazmazum** [comment]
> I don't remember any reports of quit hangs on Linux, and I had none in my own usage, so I'm not sure :)

I mean this comment ;) At least gtk loop thread hanged for someone. But not the whole process, of course.
~~~~
(unless *run-from-repl-p*
	(run-thread "force-quitter"
          ;; Force-quit in case `ffi-kill-browser' hangs.  Must be run in a
          ;; separate thread because the renderer loop is waiting for this
          ;; function to finish.
          (sleep 1)
          (uiop:quit code nil)))))
~~~~

OK, I'll do it with feature macros.

**Comment by Ambrevar** [comment]
See also https://github.com/atlas-engineer/nyxt/issues/2368.

**Comment by shamazmazum** [comment]
Turns out quitting was broken in two commits:
9aa384f — causes 1 second delay before quitting.
63dc76f — causes hang.

Before 9aa384f `(uiop:quit code nil)` was called to quit. I'll go back to this behaviour for FreeBSD although I do not like it.
