### ISSUE TITLE
Turn `*run-from-repl-p*` into a feature macro?

### ISSUE THREAD

**Issue by aartaka** [atlas-engineer/nyxt#2494]
We often dispatch the code based on `*run-from-repl*`, which seems to be this marker for a certain environment. But then, environment markers are better of as features! We use features for debugging and portability, why not distinguish the development/production setup with those?

CC: @Ambrevar, @aadcg, @jmercouris

**Comment by Ambrevar** [comment]
I would say no, because when you run from the REPL you may also want to simulate a "binary run".  I've done this a couple of times for testing in the past.

**Comment by aartaka** [comment]
Well, we can `push` and `pop` to/from `*features*`, can't we?

**Comment by Ambrevar** [comment]
Then you have to redefine all call-sites.  

SLY can do this automatically for macros, but not for feature-macros as far as I can tell, so you'd effectively have to call `,reload-system :nyxt/gi-gtk`.

**Comment by aartaka** [comment]
That'd be ugly 0_o 

OK, closing then :)
