### ISSUE TITLE
Non-returning actions for prompt-buffer?

### ISSUE THREAD

**Issue by aartaka** [atlas-engineer/nyxt#2495]
**Is your feature request related to a problem? Please describe.**

As an active Emacs Helm user, I perceive Nyxt's prompt-buffer as an interface that you can have open for a loooooong time, looking at suggestions and doing something to them. Open problem of this view is that any action that Nyxt applies to the suggestions closes prompt buffer immediately. 

A state-of-art application: file/process manager, allowing you to do rename, delete, copy, kill etc. not even closing the prompt in between those actions.

**Describe the solution you'd like**

Adding an ability to have the actions that don't force prompt-buffer returning result, making it a self-sufficient interface.

**Describe alternatives you've considered**

- Somehow integrating `resume-prompt` into actions? Too hackish...
- Using more persistent of interfaces? Yes, it works, but I want Helm-like experience :/

**Comment by Ambrevar** [comment]
We already have this feature as `selection-actions`.  So to do what you want, it's enough to only have `selection-actions` and no `return-actions`.

We could also rebind `return` to run the default `selection-action`.

The main thing that's missing, in my opinion, is the ability to go fullscreen.

**Comment by aartaka** [comment]
Still, with `selection-actions`, we need a way to make them user-invokable. Right now, those are not exactly easy to bind to a key and are not easy to list from the prompt-buffer.

But I guess here the unexplored API could be to just bind commands to keys in a certain prompt mode. That won't return from the prompt buffer, but will do some action to the accessible selection.

**Comment by Ambrevar** [comment]
Yes, the selection-actions are not fully finished.  See the other `prompt-buffer` issues.

Helm binds f1...f12 to action 1..12.  I don't know if it's a good idea.

We could also have a keymap prefix for selection actions.

**Comment by Ambrevar** [comment]
Why close this issue?

**Comment by aartaka** [comment]
I mean, my use-case seems to be covered by key-bound commands that don't necessarily return from prompt-buffer, so it's a wontfix.
