### ISSUE TITLE
[KeePassXC] `copy-*` commands blocking the UI

### ISSUE THREAD

**Issue by andreystepanov** [atlas-engineer/nyxt#2496]
When KeePassXC used as a default password-manger, all command responsible for information retrieval blocking the UI, due to the way `keepassxc-cli` clearing clipboard after specified `timeout`.

By default `keepassxc-cli`'s `timeout` option is set to 10 seconds, so the UI is blocked for approximately 10-12 seconds.

To reproduce follow these steps:

1. Set KeePassXC as preferred password-manager.
   Use https://github.com/aartaka/nyxt-config/blob/master/passwd.lisp as a template.
2. Open any website and execute `copy-username` command.
   You will be prompted for DB file location and master-password.
3. Select any items from the auto-complition list and it will hand for 10-12 seconds.
4. The minibuffer will then `echo` you back an error `No username found.`.

There's no official fix for that, yet.
For more details see: https://github.com/keepassxreboot/keepassxc/issues/3855.

What is more interesting is that while it's hanging, we can't use username/password in clipboard on the website itself.
By the time UI usable again clipboard have already been cleared.

As a quick fix `timeout` parameter can be added to `copy-*` methods in `password-keepassxc.lisp`.

```common-lisp
(defmethod clip-username ((password-interface keepassxc-interface) &key password-name service)
  (declare (ignore service))
  (with-input-from-string (st (master-password password-interface))
    (execute password-interface (list "clip"
                                      "--attribute" "username"
                                      (password-file password-interface)
                                      password-name "0") ;; <- set timeout to "0"
             :input st)))
```

But by doing this we weakening our personal security posture.

Maybe there's a `uiop:run-program` function that can be executed in the background and not block the UI?

Any suggestions?

**Comment by Ambrevar** [comment]
Why is it weakening security?

In any case, a good fix is indeed to run it in a separate thread (with `uiop:launch-command`).

@aartaka ?

**Comment by andreystepanov** [comment]
> Why is it weakening security?

Password will not be automatically removed from clipboard using default KeePassXC mechanism.

Probably user can set some rules using his clipboard-manager, to exclude certain applications, but such support depends on the software being used.

> In any case, a good fix is indeed to run it in a separate thread (with uiop:launch-command).

I might make a PR, if needed.

Any other commands to look at for this kind of task?

**Comment by Ambrevar** [comment]
> Password will not be automatically removed from clipboard using default KeePassXC mechanism.

Bug in KeepassXC?



> Any other commands to look at for this kind of task?

If you mean "to cancel a process after a timeout", then `uiop:launch-command` is enough.

**Comment by Ambrevar** [comment]
Thanks!

**Comment by andreystepanov** [comment]
@aartaka Thanks!
