### ISSUE TITLE
Failing To Start on Arch

### ISSUE THREAD

**Issue by Gavinok** [atlas-engineer/nyxt#2498]
**Describe the bug**
When starting up nyxt after recently reinstalling in from the AUR I get the following error:

 Nyxt version 3-pre-release-1-180-g0a4ff1a96
<INFO> [14:47:19] Source location: #P"/usr/local/share/nyxt/"
<INFO> [14:47:19] Listening to socket #P"/run/user/1000/nyxt/nyxt.socket".
<INFO> [14:47:19] Loading Lisp file #P"/home/gavinok/.config/nyxt/config.lisp".
fatal error encountered in SBCL pid 23036 tid 23049:
SIGABRT received.

   0: fp=0x7faf6eaf7640 pc=0x7faf7c73336c Foreign function (null)

**Precise recipe to reproduce the issue**

For website-specific issues:
Can you reproduce this issue with Epiphany / GNOME Web (https://wiki.gnome.org/Apps/Web)?

**Information**
Arch Latest Kernel: 5.15.55-2-lts
GPU: Intel WhiskeyLake-U GT2 [UHD Graphics 6
hubstluftwm

Installed from the aur with `yay -S nyxt-browser-git`
- Information from `show-system-information`:
Nyxt version: 3-pre-release-1-180-g0a4ff1a96
Renderer version: GI-GTK
Operating system kernel: Linux 5.15.55-2-lts
Lisp implementation: SBCL 2.2.5 (Dynamic space size: 3221225472)
Features: (:WEBKIT2 :WEBKIT2-2.36 :WEBKIT2-CORS-ALLOWLIST :WEBKIT2-PASTE-PLAINTEXT
 :WEBKIT2-TRACKING :WEBKIT2-MUTE :WEBKIT2-EMOJI :WEBKIT2-MEDIA
 :WEBKIT2-SANDBOXING :GTK-3-22 :GTK-3-20 :GTK-3-18 :GTK-3-16 :GTK-3-14
 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6 :GTK-3-4 :GTK :GDK-3-22 :GDK-3-20
 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12 :GDK-3-10 :GDK-3-8 :GDK-3-6 :GDK-3-4
 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF :GLIB-2-30 :GLIB-2-32 :GLIB-2-34
 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42 :GLIB-2-44 :GLIB-2-46 :GLIB-2-48
 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56 :GLIB-2-58 :GLIB :NYXT-3
 :CUSTOM-HASH-TABLE-NATIVE :SLYNK :PLUMP-UTF-32 :PARENSCRIPT :FSET-EXT-STRINGS
 :GLOBAL-VARS :DECLARE-TYPES :SBCL+SAFE-STANDARD-READTABLE :NAMED-READTABLES
 :SWANK :LPARALLEL :21BIT-CHARS :CLOSER-MOP :CL-PPCRE-UNICODE :CL-UNICODE
 :CL-JSON-DOUBLE-FLOAT-IS-SUBSUMED :CL-JSON-SINGLE-FLOAT-IS-SUBSUMED :CL-PPCRE
 :CHUNGA :FLEXI-STREAMS :BORDEAUX-THREADS :LPARALLEL.WITH-CLTL2
 :LPARALLEL.WITH-CAS :LPARALLEL.WITH-STEALING-SCHEDULER :SPLIT-SEQUENCE
 CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64 CFFI-FEATURES:UNIX :CFFI
 CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP :FAST-IO-SV :FAST-IO
 :CL-JSON-CLOS :CL-JSON :SBCL-USES-SB-ROTATE-BYTE CHIPZ-SYSTEM:GRAY-STREAMS
 :THREAD-SUPPORT :ASDF3.3 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX
 :NON-BASE-CHARS-EXIST-P :ASDF-UNICODE :X86-64 :GENCGC :64-BIT :ANSI-CL
 :COMMON-LISP :ELF :IEEE-FLOATING-POINT :LINUX :LITTLE-ENDIAN
 :PACKAGE-LOCAL-NICKNAMES :SB-CORE-COMPRESSION :SB-LDB :SB-PACKAGE-LOCKS
 :SB-THREAD :SB-UNICODE :SBCL :UNIX)

ASDF version: 3.3.1
ASDF registries: (NYXT-SOURCE-REGISTRY ENVIRONMENT-SOURCE-REGISTRY)
Critical dependencies: (/home/gavinok/.cache/yay/nyxt-browser-git/src/nyxt-browser/_build/cl-cffi-gtk/gtk/cl-cffi-gtk.asd
 /home/gavinok/.cache/yay/nyxt-browser-git/src/nyxt-browser/_build/cl-gobject-introspection/cl-gobject-introspection.asd
 /home/gavinok/.cache/yay/nyxt-browser-git/src/nyxt-browser/_build/cl-webkit/webkit2/cl-webkit2.asd)

**Output when started from a shell**
Nyxt version 3-pre-release-1-180-g0a4ff1a96
<INFO> [14:47:19] Source location: #P"/usr/local/share/nyxt/"
<INFO> [14:47:19] Listening to socket #P"/run/user/1000/nyxt/nyxt.socket".
<INFO> [14:47:19] Loading Lisp file #P"/home/gavinok/.config/nyxt/config.lisp".
fatal error encountered in SBCL pid 23036 tid 23049:
SIGABRT received.

   0: fp=0x7faf6eaf7640 pc=0x7faf7c73336c Foreign function (null)

**Comment by Gavinok** [comment]
A quick update and restart seems to have resolved the issue. My mistake

**Comment by aartaka** [comment]
Oh, this infamous Arch update problem again xD

Glad to see it resolved!
