### ISSUE TITLE
Starting nyxt from the REPL with a bogus config file

### ISSUE THREAD

**Issue by aadcg** [atlas-engineer/nyxt#2507]
Recipe:

Creating the following config file. Notice that the symbol `nyxt/hint-mode:alphabet` doesn't exist.

```lisp
(define-configuration nyxt/hint-mode:hint-mode
  ((nyxt/hint-mode:alphabet "KDJFLSAIEUROWPQCMVXZ")))
```

Start `nyxt` from the REPL, and you'll be greeted with the following error:

```
READ error during LOAD:

  The symbol "ALPHABET" is not external in the NYXT/HINT-MODE package.

    Line: 3, Column: 27, File-Position: 132

    Stream: #<SB-INT:FORM-TRACKING-STREAM for "file /home/aadcg/.config/nyxt/config.lisp" {100F830A73}>
   [Condition of type SB-C::INPUT-ERROR-IN-LOAD]

Restarts:
 0: [ABORT] Abort loading file "/home/aadcg/.config/nyxt/config.lisp".
 1: [RETRY] Retry SLY mREPL evaluation request.
 2: [*ABORT] Return to SLY's top level.
 3: [ABORT] abort thread (#<THREAD "sly-channel-1-mrepl-remote-1" RUNNING {100FF18003}>)
```

If you edit the config file by hand and restart with RETRY, Nyxt won't start.

**Comment by Ambrevar** [comment]
When starting Nyxt from the binary we actually restart the whole process in this case.

But from the REPL, we have a half complete startup stack and I suppose we are not guarding the process properly, which results in the stack being partially unwound, which breaks the whole process.  Just a guess, I'd need to look into this deeper.

**Comment by aadcg** [comment]
That's my intuition as well. I've been avoiding diving into our start logic!

**Comment by aadcg** [comment]
This is relevant for #2710.

**Comment by Ambrevar** [comment]
See #2731.
