### ISSUE TITLE
Broken Download Hooks?

### ISSUE THREAD

**Issue by hendursaga** [atlas-engineer/nyxt#2512]
I cannot for the life of me add a handler to `after-download-hook`, `probe-ftype` won't let me because the types are wrong...

```lisp
(sera:-> test-handler (download-manager:download) *)
(defun test-handler (download)
  (echo "Test handler works!"))

(hooks:add-hook (after-download-hook *browser*) 'test-handler)
```

... which throws...

```
Handler function #<FUNCTION TEST-HANDLER> does not match expected type #'(DOWNLOAD).
Detail: undefined type: NYXT::DOWNLOAD
   [Condition of type SIMPLE-ERROR]
```

The documentation itself is a little confusing...

https://github.com/atlas-engineer/nyxt/blob/25aedd60c3543b8fa941216e972826fd2a15818c/source/browser.lisp#L219-L223

... since it states it takes the URL, but the type is `hook-download`...

https://github.com/atlas-engineer/nyxt/blob/25aedd60c3543b8fa941216e972826fd2a15818c/source/browser.lisp#L7

... which I'm not sure actually points to any actual type, as shown above and confirmed below...

```
NYXT-USER> (hooks:handler-type (after-download-hook *browser*))
#'(NYXT::DOWNLOAD)
```

... but in...

https://github.com/atlas-engineer/nyxt/blob/25aedd60c3543b8fa941216e972826fd2a15818c/source/browser.lisp#L224-L228

... it says it takes `download-manager:download`, which actually exists in comparison to `nyxt::download`... oh, and I (still) really can't debug any of this, because https://github.com/atlas-engineer/nyxt/issues/2466#issuecomment-1193188535

**Comment by aartaka** [comment]
And when something is actually passed to `after-download-hook`, it's either of type `nyxt/download-mode:download` or `quri:uri`...

What a mess :D
