### ISSUE TITLE
Do we need/want :nxref (and other Nyxt-specific niceties) in changelog?

### ISSUE THREAD

**Issue by aartaka** [atlas-engineer/nyxt#2514]
Using `:nxref` in the changelog can be quite useful, as it can help the one looking at the changelog to inspect the exact changed slot/class/function if they are interested. 

The question is: do we actually want `:nxref` in changelog? Or are we better off with the plain HTML changelog that can be shown in any browser?
- Staying with plain HTML means we can publish the changelog right away on atlas.engineer. But it makes us think more on what to put in the text, like in my example above.
- Using `:nxref` (and other niceties from Nyxt) makes changelog nicer to use inside Nyxt, but quirky to host at atlas.engineer.

Trade-offs...

_Originally posted by @aartaka in https://github.com/atlas-engineer/nyxt/issues/2419#issuecomment-1222020322_

**Comment by aadcg** [comment]
It's good that you're raising this question.

The detailed changelog should be read from Nyxt itself, as I see it. We'd be loosing a big opportunity to communicate with the user interactively. 

The release notes that are published on the website could perhaps be shorter, and loosely based on the changelog.

**Comment by Ambrevar** [comment]
Another drawback of `nxref` in the changelog is that it won't work for old entries which refer to symbols that are gone.

Maybe make nxref smart enough to detect undefined symbols and format the HTML accordingly?

**Comment by aartaka** [comment]
`:nxref` already does that: it errors at compile time if you feed it an undefined symbol :)

**Comment by aartaka** [comment]
It would, but only for new symbols that are still available. The symbols that disappear will error out immediately, which may be a virtue -- urges us to update the changelog :P

**Comment by aadcg** [comment]
I guess it would ok change some `nxref`s to `code` every now and then...

**Comment by Ambrevar** [comment]
OK!
