### ISSUE TITLE
Strip Nyxt-Specific Clutter While Editing Page Source

### ISSUE THREAD

**Issue by hendursaga** [atlas-engineer/nyxt#2518]
When I'm calling `view-source-with-external-editor`, I see a whole lot of `nyxt-stylesheet`s, `nyxt-identifier`s, etc in the HTML source. It would be nice if there was at least an option to strip these HTML attributes before passing the file on to the editor.

**Comment by aartaka** [comment]
Indeed, that's not nice. We need to clean DOM up before calling `view-source-*` commands...

**Comment by aadcg** [comment]
Instead of cleaning the DOM, what about having a slot called `original-document-model` that will be kept unchanged?

**Comment by aartaka** [comment]
No, that would still be parsed based on original page. The best thing we can do here is to clean things up before showing the source.

... or we have to ditch `nyxt-identifiers`, as in #2424 :D
