### ISSUE TITLE
Hint overlays style should match prompt buffer's style

### ISSUE THREAD

**Issue by aadcg** [atlas-engineer/nyxt#2519]
![2022-08-26_10:54:42](https://user-images.githubusercontent.com/45483512/186852242-21aa6139-31ce-465f-93d9-6330d1fbb0f8.png)

Prompt buffer distinguishes between marked suggestions and current suggestion, but that isn't propagated to the hint overlays. 

We need to define a style for marked hints. I'd go with a darker grey background.

**Comment by aartaka** [comment]
Do we have darker than that? Maybe use the light gray for regular hints then?

**Comment by aadcg** [comment]
We don't, but we could apply transparency to `on-background-color`.

But let's go with your suggestion, as it's less evil.

**Comment by aadcg** [comment]
This requires implementing `mark-actions` in `promper-source`.

**Comment by aartaka** [comment]
Someday our `prompter` will be able to read emails xD

**Comment by aadcg** [comment]
AHAHA M-x `brew-coffee`.
