### ISSUE TITLE
Mute Tab (microphone)

### ISSUE THREAD

**Issue by easbarbosa** [atlas-engineer/nyxt#252]
Hi,

A neat feature of Chromium and Icecat is muting tab or all tabs.

I know that webkit has that mute feature. Cant say for Webkitgtk

Thanks!

**Comment by Ambrevar** [comment]
Indeed.  Actually this might already be doabe, now that Next can set arbitrary settings on the platform port with the `rpc-buffer-set` method.

Something like `(rpc-buffer-set *interface* (active-buffer *interface*) "enable-webaudio" nil)` (untested).

For a full list of options, see
https://webkitgtk.org/reference/webkit2gtk/unstable/WebKitSettings.html.

**Comment by Ambrevar** [comment]
Make sure we can do this before 2.0, we might need to update cl-webkit.

**Comment by Ambrevar** [comment]
I've updated cl-webkit to support the `enable-media` setting.
https://github.com/joachifm/cl-webkit/commit/e3b4936d5edeee8e8822ff7ff21f156404547c20

Everything else is looking good on the cl-webkit front, so nothing urgent anymore for 2.0.

Sadly I was not able to mute buffers with WebKitGTK, can't find how to do it.  Setting `enable-media` to nil only disables the <audio> and <video> tags, which is not what we want.

Looking for forgiveness I've pushed a `noimage-mode` instead :)
Shall we add a nomedia mode?  How useful would that be?

**Comment by jmercouris** [comment]
I think a no media mode would be super cool personally :-) it would hopefully prevent auto playing media on websites that employ it 

For muting buffers, I think we can also do it with JS, I’ll look into an alternative, there must be a way!

**Comment by Ambrevar** [comment]
WebKitGTK 2.30 can mute tabs!

**Comment by Ambrevar** [comment]
I've added nosound-mode in 001a79aa53da32ac2b3c9873ad33222a9d2b76b1.
The only thing left to do is the ability to mute the microphone.  Does this feature belong to Nyxt however?

**Comment by aartaka** [comment]
> The only thing left to do is the ability to mute the microphone. Does this feature belong to Nyxt however?

No, it doesn't. Implementing the mechanism for permissions (e.g. [WebKitUserMediaPermissionRequest](https://webkitgtk.org/reference/webkit2gtk/stable/WebKitUserMediaPermissionRequest.html) in case of WebKit port) should cover it. After all, no website has access to user's microphone by default -- they needs to ask permission for it.
