### ISSUE TITLE
Migrating from 2.* to 3.* wipes history

### ISSUE THREAD

**Issue by franburstall** [atlas-engineer/nyxt#2523]
**Describe the bug**

I revisited nyxt for the first time in a while and so built nyxt-3 from master and fired it up:
```
nyxt -I
```
On load there was a warning:
```
<WARN> [14:57:04] Warning: Failed to restore history from /home/fran/.local/share/nyxt/history/default.lisp: Symbol &quot;CURRENT-OWNER-ID&quot; not found in the HISTORY-TREE package. Line: 1580, Column: 14, File-Position: 163363 Stream: #&lt;SB-SYS:FD-STREAM for &quot;file /home/fran/.local/share/nyxt/history/default.lisp&quot; {100A8522B3}&gt;
```
and, sure enough, my old session from way back was not restored.  I opened a site or two and then quit.

I then fired nyxt again and this time the session was restored with the site or two I had opened.  On investigation, I discovered that the history file
```
/home/fran/.local/share/nyxt/history/default.lisp
```
had been completely overwritten and my old history wiped.

While I expected some friction after such a long time since I last tried nyxt, silently wiping the history is a little unfriendly!

**Information**
- OS name+version: Debian 11
- Graphics card and driver:
- Desktop environment / Window manager name+version: exwm
- How you installed Nyxt (Guix pack, package manager, build from source): source
- Information from `show-system-information`:
Nyxt version: 3-pre-release-1-273-g5dfb8039
Renderer version: GI-GTK
Operating system kernel: Linux 5.10.0-17-amd64
Lisp implementation: SBCL 2.1.1 (Dynamic space size: 3221225472)
Features: (:WEBKIT2 :WEBKIT2-2.36 :WEBKIT2-CORS-ALLOWLIST :WEBKIT2-PASTE-PLAINTEXT :WEBKIT2-TRACKING :WEBKIT2-MUTE :WEBKIT2-EMOJI :WEBKIT2-MEDIA :WEBKIT2-SANDBOXING :GTK-3-22 :GTK-3-20 :GTK-3-18 :GTK-3-16 :GTK-3-14 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6 :GTK-3-4 :GTK :GDK-3-22 :GDK-3-20 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12 :GDK-3-10 :GDK-3-8 :GDK-3-6 :GDK-3-4 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF :GLIB-2-30 :GLIB-2-32 :GLIB-2-34 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42 :GLIB-2-44 :GLIB-2-46 :GLIB-2-48 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56 :GLIB-2-58 :GLIB :NYXT-3 :CUSTOM-HASH-TABLE-NATIVE :SLYNK :PLUMP-UTF-32 :PARENSCRIPT :FSET-EXT-STRINGS :GLOBAL-VARS :DECLARE-TYPES :SBCL+SAFE-STANDARD-READTABLE :NAMED-READTABLES :SWANK :LPARALLEL :21BIT-CHARS :CLOSER-MOP :CL-PPCRE-UNICODE :CL-UNICODE :CL-JSON-DOUBLE-FLOAT-IS-SUBSUMED :CL-JSON-SINGLE-FLOAT-IS-SUBSUMED :CL-PPCRE :CHUNGA :FLEXI-STREAMS :BORDEAUX-THREADS :LPARALLEL.WITH-CLTL2 :LPARALLEL.WITH-CAS :LPARALLEL.WITH-STEALING-SCHEDULER :SPLIT-SEQUENCE CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64 CFFI-FEATURES:UNIX :CFFI CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP :FAST-IO-SV :FAST-IO :CL-JSON-CLOS :CL-JSON :SBCL-USES-SB-ROTATE-BYTE CHIPZ-SYSTEM:GRAY-STREAMS :THREAD-SUPPORT :ASDF3.3 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX :NON-BASE-CHARS-EXIST-P :ASDF-UNICODE :X86-64 :GENCGC :64-BIT :ANSI-CL :COMMON-LISP :ELF :IEEE-FLOATING-POINT :LINUX :LITTLE-ENDIAN :PACKAGE-LOCAL-NICKNAMES :SB-LDB :SB-PACKAGE-LOCKS :SB-THREAD :SB-UNICODE :SBCL :UNIX)

ASDF version: 3.3.1
ASDF registries: (NYXT-SOURCE-REGISTRY ENVIRONMENT-SOURCE-REGISTRY)
Critical dependencies: (/home/fran/common-lisp/nyxt/_build/cl-cffi-gtk/gtk/cl-cffi-gtk.asd /home/fran/common-lisp/nyxt/_build/cl-gobject-introspection/cl-gobject-introspection.asd /home/fran/common-lisp/nyxt/_build/cl-webkit/webkit2/cl-webkit2.asd)

**Output when started from a shell**
(sbcl:38775): Gtk-WARNING **: 14:57:04.322: Theme parsing error: gtk-contained-dark.css:2871:228: Missing closing bracket for :not()
Nyxt version 3-pre-release-1-273-g5dfb8039
<INFO> [14:57:04] Source location: #P"/home/fran/common-lisp/nyxt/"
<INFO> [14:57:04] Listening to socket #P"/run/user/1000/nyxt/nyxt.socket".
<INFO> [14:57:04] GTK extensions directory: #P"/home/fran/common-lisp/nyxt/libraries/web-extensions/"
<INFO> [14:57:04] Loading #P"/home/fran/.local/share/nyxt/history/default.lisp".
<WARN> [14:57:04] Warning: Failed to restore history from /home/fran/.local/share/nyxt/history/default.lisp: Symbol &quot;CURRENT-OWNER-ID&quot; not found in the HISTORY-TREE package. Line: 1580, Column: 14, File-Position: 163363 Stream: #&lt;SB-SYS:FD-STREAM for &quot;file /home/fran/.local/share/nyxt/history/default.lisp&quot; {100A8522B3}&gt;
<INFO> [14:57:04] GTK extensions directory: #P"/home/fran/common-lisp/nyxt/libraries/web-extensions/"

(WebKitWebProcess:38832): Gtk-WARNING **: 14:57:04.853: Theme parsing error: gtk-contained-dark.css:2871:228: Missing closing bracket for :not()

(WebKitWebProcess:38832): Gtk-WARNING **: 14:57:04.943: Theme parsing error: gtk-contained-dark.css:2871:228: Missing closing bracket for :not()

(WebKitWebProcess:38861): Gtk-WARNING **: 14:57:05.069: Theme parsing error: gtk-contained-dark.css:2871:228: Missing closing bracket for :not()

(WebKitWebProcess:38864): Gtk-WARNING **: 14:57:05.109: Theme parsing error: gtk-contained-dark.css:2871:228: Missing closing bracket for :not()

(WebKitWebProcess:38861): Gtk-WARNING **: 14:57:05.160: Theme parsing error: gtk-contained-dark.css:2871:228: Missing closing bracket for :not()

(WebKitWebProcess:38864): Gtk-WARNING **: 14:57:05.194: Theme parsing error: gtk-contained-dark.css:2871:228: Missing closing bracket for :not()
<INFO> [14:57:16] Loading #P"/home/fran/.local/share/nyxt/bookmarks.lisp".

(WebKitWebProcess:39263): Gtk-WARNING **: 14:57:16.790: Theme parsing error: gtk-contained-dark.css:2871:228: Missing closing bracket for :not()

(WebKitWebProcess:39263): Gtk-WARNING **: 14:57:16.872: Theme parsing error: gtk-contained-dark.css:2871:228: Missing closing bracket for :not()
<INFO> [14:57:30] Loading "https://duckduckgo.com/?q=twistor%20theory".
<INFO> [14:57:33] Finished loading "https://duckduckgo.com/?q=twistor+theory&ia=web".
WARNING:
   Attributes of #<WINDOW 1033 {1010547A13}> should be a non-dotted alist instead of (("ID"
                                                                                       1033)
                                                                                      ("Active buffer"
                                                                                       "twistor theory at DuckDuckGo"))
<INFO> [14:58:08] Dark mode enabled.
<INFO> [15:00:14] Emacs mode enabled.
<INFO> [15:00:23] Pressed keys: C-x
<INFO> [15:01:35] Loading "https://duckduckgo.com/?q=twistor+theory&ia=web".
<INFO> [15:01:37] Finished loading "https://duckduckgo.com/?q=twistor+theory&ia=web".
<INFO> [15:01:45] Loading "https://duckduckgo.com/?q=twistor+theory&ia=web".
<INFO> [15:01:46] Finished loading "https://duckduckgo.com/?q=twistor+theory&ia=web".
<INFO> [15:01:49] Loading "https://duckduckgo.com/?q=twistor+theory&ia=web".
<INFO> [15:01:49] Loading "https://duckduckgo.com/l/?uddg=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FTwistor_theory&notrut=duckduck_in".
<INFO> [15:01:49] Finished loading "https://duckduckgo.com/l/?uddg=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FTwistor_theory&notrut=duckduck_in".
<INFO> [15:01:51] Finished loading "https://en.wikipedia.org/wiki/Twistor_theory".
<INFO> [15:02:11] Dark mode disabled.
<INFO> [15:02:14] Loading "https://en.wikipedia.org/wiki/Twistor_theory".
<INFO> [15:02:15] Finished loading "https://en.wikipedia.org/wiki/Twistor_theory".
<INFO> [15:02:25] Pressed keys: C-x

(WebKitWebProcess:50271): Gtk-WARNING **: 15:02:26.681: Theme parsing error: gtk-contained-dark.css:2871:228: Missing closing bracket for :not()

(WebKitWebProcess:50271): Gtk-WARNING **: 15:02:26.763: Theme parsing error: gtk-contained-dark.css:2871:228: Missing closing bracket for :not()
; in:
;      LAMBDA (&KEY (NYXT/BUFFER-LISTING-MODE::CLUSTER NIL) NYXT/BUFFER-LISTING-MODE::LINEAR-VIEW-P)
;     (NYXT:DELETE-BUFFER :BUFFER NYXT:BUFFER)
; 
; caught STYLE-WARNING:
;   :BUFFER is not a known argument keyword.
; 
; compilation unit finished
;   caught 1 STYLE-WARNING condition
; in:
;      LAMBDA (&KEY (NYXT/BUFFER-LISTING-MODE::CLUSTER NIL) NYXT/BUFFER-LISTING-MODE::LINEAR-VIEW-P)
;     (NYXT:DELETE-BUFFER :BUFFER NYXT:BUFFER)
; 
; caught STYLE-WARNING:
;   :BUFFER is not a known argument keyword.
; 
; compilation unit finished
;   caught 1 STYLE-WARNING condition
; in:
;      LAMBDA (&KEY (NYXT/BUFFER-LISTING-MODE::CLUSTER NIL) NYXT/BUFFER-LISTING-MODE::LINEAR-VIEW-P)
;     (NYXT:DELETE-BUFFER :BUFFER NYXT:BUFFER)
; 
; caught STYLE-WARNING:
;   :BUFFER is not a known argument keyword.
; 
; compilation unit finished
;   caught 1 STYLE-WARNING condition
; in:
;      LAMBDA (&KEY (NYXT/BUFFER-LISTING-MODE::CLUSTER NIL) NYXT/BUFFER-LISTING-MODE::LINEAR-VIEW-P)
;     (NYXT:DELETE-BUFFER :BUFFER NYXT:BUFFER)
; 
; caught STYLE-WARNING:
;   :BUFFER is not a known argument keyword.
; 
; compilation unit finished
;   caught 1 STYLE-WARNING condition
<INFO> [15:40:39] Deleting socket #P"/run/user/1000/nyxt/nyxt.socket".

**Comment by aartaka** [comment]
I see, `current-owner-id` biting us back :/ 

@Ambrevar, should we re-introduce this slot to not break configs? Or can we somehow configure `cl-prevalence` to ignore this slot?

**Comment by Ambrevar** [comment]
Yes, we can specialize the deserializer to ignore the slot for a specific class.

**Comment by Ambrevar** [comment]
@franburstall The erasing issue should be fixed with 363d13f9b52d9fe43b59d2a1eea85a887a35b7c3: now on error the broken history is backed up (in the same directory).  It should be listed with `restore-history-by-name`.

@aartaka Note that @franburstall 's history file was older than 2.2.4, since the `current-owner-node` was already deprecated by then.  What we use to do is still declare the symbol to be backward compatible, but we've removed it since 3.0 breaks backward compatibility.  See commit ac3f55fbbeb714a204917e0f074016512b1ac872.

Let me know if there is anything else, otherwise I believe we can close this issue.

**Comment by franburstall** [comment]
I confirm that this does as you describe when I load nyxt with a broken history file.  Very good!  Many thanks.

**Comment by aartaka** [comment]
> @aartaka Note that @franburstall 's history file was older than 2.2.4, since the `current-owner-node` was already deprecated by then. What we use to do is still declare the symbol to be backward compatible, but we've removed it since 3.0 breaks backward compatibility. See commit [ac3f55f](https://github.com/atlas-engineer/nyxt/commit/ac3f55fbbeb714a204917e0f074016512b1ac872).

I mean, mybe we should resurrect and export it, just to make `cl-prevalence` to not die in agony when it sees `current-owner-node` etc. Maybe this will even allow using the history from 2.* on 3.*?

**Comment by Ambrevar** [comment]
It will.  But when do we eventually remove deprecated content?

**Comment by aartaka** [comment]
Well, if we go with making `cl-prevalence` to somehow ignore meaningless slots (can we?), then we don't have te remove anything.  Then we just ignore this slot, browse the Internet, and overwrite the history file with a new history structure having no deprecated slots at all.

And then this methods listing the meaningful slots can be updated on 4.0, because, by that time, most of people using Nyxt have already switched to 3.* and fixed their histories.

**Comment by Ambrevar** [comment]
Let me see what I can do.

**Comment by Ambrevar** [comment]
See #2567.

**Comment by Ambrevar** [comment]
Should be done for real now.
