### ISSUE TITLE
Rename `marks` to `mark`?

### ISSUE THREAD

**Issue by aadcg** [atlas-engineer/nyxt#2527]
#2520 introduced `marks-actions`, which adds to `return-actions` and `selection-actions`.

However, `marks-actions` sounds really weird and it's hard to pronounce. 

I'd rename `marks` to `mark`. Indeed, `selection` and `mark` are radically different since the former is always a singleton but the latter isn't. They're actually both lists, but for very different reasons related to the way they're implemented. 

It doesn't sound odd to me that `mark` would a be concept defined by a word in the singular form that refers to a set of entities.

**Comment by aadcg** [comment]
On second thoughts, I'd suggest something even more radical.

We have the following concepts: suggestions, selection and marks.

Wouldn't it be saner to have suggestions, current-suggestion and selection?

Suggestions are the prompt options; current-suggestion is a singleton of suggestions; and selection is a subset of suggestions.

**Comment by aartaka** [comment]
I guess the initial naming comes from Helm. If the new naming is drains less cognitive resources, then why not :)

I'll leave that to @Ambrevar, though, as he wanted to abstract `promtper` into a separate library, and that is likely when the renaming should happen.

**Comment by Ambrevar** [comment]
Yes, the naming comes from Helm.  "Mark" is not very familiar outside of this context, so yes, I'm in favour of André's renaming suggestion.

Shall it wait for 4.0 though?  We've already got a lot on our hands...

**Comment by aadcg** [comment]
Yes, this is not particularly important.
