### ISSUE TITLE
List both functions and variables in `execute-command`

### ISSUE THREAD

**Issue by aadcg** [atlas-engineer/nyxt#2544]
It seems that the fact that we omit the parenthesis doesn't allow for the possibility to have both variables and functions listed.

For instance, when inputting "ppcre:" it only lists functions, but there are obviously variables defined in that namespace.

**Comment by aartaka** [comment]
Have you tried `ppcre:*allow-quoting*`? It's properly evaluated...

**Comment by aadcg** [comment]
That's not the point. When you input "ppcre:" I'd expect to see both variables and functions, but only functions are listed.
