### ISSUE TITLE
Best way to shutdown Nyxt when run from REPL?

### ISSUE THREAD

**Issue by hendursaga** [atlas-engineer/nyxt#2549]
So far, whenever I set `*run-from-repl-p*` to `t`, and I wanted to shutdown Nyxt, I've had to `killall -9 nyxt`, but I was wondering if there was a better way to do this, and if it could be documented somewhere, assuming I still have a connected REPL?

Looking at https://github.com/atlas-engineer/nyxt/blob/7e8c1d4fc99e4ab3f46b71c6cd243af37d304311/source/start.lisp#L581 perhaps I should do `(uiop:quit)`?

**Comment by aartaka** [comment]
You can set `*run-from-repl-p*` back to `nil` and exit normally. Well, that feels like the best course of action for your case of binary Nyxt with a connected REPL (if I understood your situation correctly).

**Comment by hendursaga** [comment]
Hmmm, perhaps adding a `toggle-run-from-repl` command might be a good idea, even if not for my particular case?

**Comment by aartaka** [comment]
Well, `*run-from-repl-p*` (much like `*interactive-p*` and `*headless-p*`) is an internal details that ideally shouldn't leak into the interface and commands...

**Comment by Ambrevar** [comment]
Alternatively we could add a parameter to `nyxt:quit`.

**Comment by aadcg** [comment]
Stale.
