### ISSUE TITLE
Sorted lists in describe-* pages

### ISSUE THREAD

**Issue by franburstall** [atlas-engineer/nyxt#2552]
Describe-* pages, especially for classes, have long lists of subclasses/slots/methods etc.

These would be way more readable/useful if they were sorted alphabetically.

This looks easy to implement and I would be happy to make a PR if you thought it would be useful.

**Comment by aartaka** [comment]
Method sorting I can agree with, subclasses—maybe, superclasses—no! Superclasses are ordered in the order they are in the object hierarchy, so we don't want to alter the order. 

PR is welcome, yes!
