### ISSUE TITLE
Display source count

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#2556]
I believe we need a way to display the number of sources in the prompt buffer, otherwise we might be let to believe there is only one source.

The problem is that sources already display the number of suggestions in square brackets.

So how to we display yet another number that's self-explanatory?

**Comment by aartaka** [comment]
Maybe display the names of neighbor sources above and below the current one?

**Comment by Ambrevar** [comment]
Indeed, could fix together with #2033.

**Comment by aadcg** [comment]
> Maybe display the names of neighbor sources above and below the current one?

I don't think I understood your suggestion.

My suggestion is as depicted below. If the sources would be shown right below the input area, it would be clear there are several of them. I suggest a familiar tab-like UI, where it's visible which source is currently active.

![2022-09-12_09:40:16](https://user-images.githubusercontent.com/45483512/189589332-d4633950-0a4d-4d51-b842-928a700f70be.png)

**Comment by aartaka** [comment]
No, not tabs, please ‎(٭°̧̧̧ω°̧̧̧٭) They are a pain to implement in HTML...

What I meant in my previous suggestion is showing the source headers for the next and previous source below and above (respectively) the displayed contents of the current source. This way, we can both show that there's something below, while preserving the simplicity of the current interface.

This is not perfect, though—these ghost headers can confuse one about the contents of the current source being less than in fact.

**Comment by aadcg** [comment]
Actually what doesn't convince me about your suggestions is the fact that you'll have burn precious lines of the prompt buffer.

Fair enough about tabs. I guess we could do something very simple in the vein of "tabs". List the sources horizontally and highlight the current source.

**Comment by jmercouris** [comment]
How about a little button on the left of every source that the user can click on to jump to the next/previous source?

A up and down arrow that they can press?

**Comment by Ambrevar** [comment]
Since we have some padding to the left, I guess John's suggestion addresses André's concern.

**Comment by aadcg** [comment]
Indeed, I like John's idea.

**Comment by jmercouris** [comment]
The buttons now exist.
