### ISSUE TITLE
Search hints padding jittering

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#2559]
Currently searching text makes it move as we type because of the padded box and the different font.  This is particularly jarring when searching words in wrapped text like paragraphs.

Changing the hints to

```lisp
(".nyxt-hint"
       :background-color theme:secondary
       :color theme:on-secondary
       ;; :font-family "monospace,monospace"
       ;; :padding "0px 0.3em"
       ;; :border-radius "0px 0.3em"
       :z-index #.(1- (expt 2 31)))
```

removes the jittering which is very welcome in my opinion.

Thoughts?

**Comment by aadcg** [comment]
I totally agree.

**Comment by aartaka** [comment]
The selector should then mention `nyxt-search-node` to not mess up the regular link hints too!

**Comment by Ambrevar** [comment]
@aadcg, @aartaka Can one of you send a patch?
