### ISSUE TITLE
Compilation Fatal Error: Package libfixposix was not found in the pkg-config search... for nyxt-3-pre-release-1-source-with-submodules tarball

### ISSUE THREAD

**Issue by androclus** [atlas-engineer/nyxt#2562]
Hi folks, total newbie to nyxt (and even CL), so forgive me if this is stupid. :-)

**Describe the bug**

As what seemed like the easiest way in to trying out nyxt v3 on my distro, I downloaded the July version 3 pre-release (with submodules), at

[nyxt-3-pre-release-1-source-with-submodules.tar.xz](https://github.com/atlas-engineer/nyxt/releases/download/3-pre-release-1/nyxt-3-pre-release-1-source-with-submodules.tar.xz)

and read the instructions at INSTALL. I didn't change anything in the makefile, and I have sbcl on my system.  When I ran "make all", I got the fatal error aborting compilation:

> Package libfixposix was not found in the pkg-config search...

**Precise recipe to reproduce the issue**
- Download nyxt-3-pre-release-1-source-with-submodules.tar.xz from [releases page](https://github.com/atlas-engineer/nyxt/releases)
- $ make all

**Information**
- OS name+version: OpenSUSE Tumbleweed latest (Linux x86_64 5.19.8-1-default SMP PREEMPT_DYNAMIC)
- CL implementation: SBCL 2.2.8-1.1-suse

Let me know if I've just missed something obvious, or forgotten to include some info, or if there is anything else you need. Thanks. JS

**Comment by jmercouris** [comment]
Hello and welcome! You'll need to install libfixposix! It should be available for your operating system.

Alternatively, you can:

`zypper ar https://download.opensuse.org/repositories/home:/bobbie424242/openSUSE_Tumbleweed/ nyxt-git`
for tumbleweed!

**Comment by Ambrevar** [comment]
Package where?  It's in the Guix pack, but here the OP downloaded the source.
