### ISSUE TITLE
Regression: Hint Filtering Much Slower

### ISSUE THREAD

**Issue by hendursaga** [atlas-engineer/nyxt#2577]
I've found that the speed between when I, say, execute `follow-hint-new-buffer` and the hints get plastered all over the page and when I can filter things down has increased a lot more lately. Sometimes I'm waiting almost 10 whole seconds before I can select a hint! I don't think it's filtering in general, as, say, narrowing down within `execute-command` or bookmarks or other things are reasonably fast.

How might I begin profiling to see what might be the problem?

**Comment by Ambrevar** [comment]
Already worked on: https://github.com/atlas-engineer/nyxt/pull/2574 ;)

**Comment by aadcg** [comment]
Thanks for reporting @hendursaga. It's fixed on master.
