### ISSUE TITLE
CLOS/class*: Add a DWIM make-instance wrapper?

### ISSUE THREAD

**Issue by aartaka** [atlas-engineer/nyxt#2584]
**Is your feature request related to a problem? Please describe.**
I've done some programming in JavaScript, and it has this nice object initialization syntax ([see MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer#property_definitions)):
``` js
{a, b, c}
// Expanding to:
{a: a, b: b, c: c}
```
which seems like something we can creatively steal :P 

Adding more ideas to this: we often have the idiom of `(apply #'make-instance ... (append (when x (list :x x)) ...))`, which we can also incorporate into this new `make-instance` thingie.

**Describe the solution you'd like**
I suggest a macro, a wrapper around a regular `make-instance`. The use that I envision is:
``` lisp
(make-instance* 'class (a b c) :d 5 (when e (list :e (+ e 8))))
;; Or even something like (notice the :e? quasi-keyword):
(make-instance* 'class (a b c) :d 5 :e? (+ e 8))
;; Expanding to:
(apply #'make-instance 'class :a a :b b :c b :d 5 (append (when e (list :e (+ e 8))))))
```

**Describe alternatives you've considered**
Providing `defstruct`-like `make-*` constructors? Those are a nice'n'lispy non-macro way to shorten object creation, but then, they pollute the packages with one more symbol per class...

EDIT: Add a star after the macro name to distinguish if from the regular `make-instance`.
EDIT: Add `'class` to the `make-instance*` example.

**Comment by Ambrevar** [comment]
There is `sera:dict`, have you tried it?

> `(apply #'make-instance ... (append (when x (list :x x)) ...))`

I wonder if there is not something more idiomatic in Common Lisp.

> ```lisp
> (make-instance* (a b c) :d 5 (when e (list :e (+ e 8))))
> ```

Wait... Where is the class symbol?

It's a good idea, but before working on it we should investigate existing libraries, something similar might already exist.

**Comment by aartaka** [comment]
> There is `sera:dict`, have you tried it?

Yes, I did, but the matter of this issue is not having fast and convenient key-value data structure creation syntax, but rather a convenient class instantiation one. Basically to make `make-instance` a bit less wordy and intimidating.

> > `(apply #'make-instance ... (append (when x (list :x x)) ...))`
> 
> I wonder if there is not something more idiomatic in Common Lisp.

None that I've seen :( This may be because not many projects utilize CLOS to the degree we do, and many just have a restricted set of classes with all slots more or less mandatory.

> > ```lisp
> > (make-instance* (a b c) :d 5 (when e (list :e (+ e 8))))
> > ```
> 
> Wait... Where is the class symbol?

It should be right after the `make-instance*`, sorry (^_^;)

> It's a good idea, but before working on it we should investigate existing libraries, something similar might already exist.

Sure!

**Comment by aartaka** [comment]
- McCLIM makes heavy use of mixins and `(apply #'make-instance ...)`.
- SICL uses `make-instance` and has this interesting macro idiom:
``` lisp
(apply #'make-instance class
                    (loop
                      for (slot value) on (rest form) by #'cddr
                      collect (keywordify slot)
                      collect value))
```
- Alexandria has no utilities for that.
- Serapeum has `make` which does compile-time checking for classes and other niceties, but restricts one to keyword-value pairs in arguments. We also seem to reproduce it word-for-word in Prompter :D

All in all, it seems that everyone uses `make-instance` and goes no further than that minor shortening for it.

**Comment by aartaka** [comment]
This one is covered by https://github.com/atlas-engineer/nclasses/pull/12 and is now available in `nclasses`. Closing as completed.
