### ISSUE TITLE
Add Onion-Location Header / Meta Tag Support

### ISSUE THREAD

**Issue by hendursaga** [atlas-engineer/nyxt#2591]
In the Tor Browser Bundle and other browsers like Brave, if the admin configures the web server to add a `Onion-Location` HTTP header, you have the option to redirect to the onion version of the site. In case the hosting site can't / won't add a non-standard header like that, there's also the option to add a <meta> tag. See the [full spec](http://gzgme7ov25seqjbphab4fkcph3jkobfwwpivt5kzbv3kqx2y2qttl4yd.onion/tor-browser-spec.git/plain/proposals/100-onion-location-header.txt) for more details there.

So, questions: which browser hook should I use to check for the presence of this non-standard header? Perhaps `buffer-before-make-hook`, or is that too early? Or perhaps `prompt-buffer-make-hook`?

As for the second option, the meta tag, what hook should I use, to where I could parse the HTML, and preferably before any JS/ParenScript gets run?

For both options, I presume I'll need to do something akin to what `url-dispatching-handler` does?

**Comment by Ambrevar** [comment]
The right hook is `request-resource-hook`.

Unfortunately for now we don't have any good API to inspect the HTTP header.
cl-webkit has a binding for https://webkitgtk.org/reference/webkit2gtk/stable/method.URISchemeRequest.get_http_headers.html which returns a SoupMessageHeaders.  We need to convert this to Lisp.

**Comment by hendursaga** [comment]
`request-resource-hook` being the correct hook for both options? With the DOM API, we wouldn't need to use ParenScript to grab the special meta tag..

Another idea, though perhaps just as an example to include in the docs, would be to (prompt to?) add an auto-mode rule to redirect for future visits?

**Comment by Ambrevar** [comment]
The DOM API is available too late, after JS is run, so that won't do.

I'm not aware of a WebKitGTK API point that would allow to access the HTML before JS is run.  But maybe I didn't look close enough.

**Comment by Ambrevar** [comment]
> Another idea, though perhaps just as an example to include in the docs, would be to (prompt to?) add an auto-mode rule to redirect for future visits?

While convenient, it would not be good enough to protect the user privacy.

**Comment by aartaka** [comment]
Meta tags I'm not sure we'd ever be able to look at before loading the page. [WebKitWebResource](https://webkitgtk.org/reference/webkit2gtk/stable/class.WebResource.html), maybe?  Still, quite hard of a thing to crack.

Closing this, as 2a8abdc2e589895e680b4bd85ba70de82250e88c adds the ability to inspect headers in `request-resource-hook` and redirect requests based on that.

**Comment by hendursaga** [comment]
> While convenient, it would not be good enough to protect the user privacy.

Could you explain? The user, probably not knowing about the Tor onion mirror, visits the cleartext site, where, if those headers or meta tags are present, Nyxt would prompt, similar to TBB, ".onion available." Go on and try it: open TBB, visit https://www.propublica.org/, and, assuming you haven't already set "Prioritize .onion sites when known." to "Always," it should show a prompt you could click. I think we can do even better!

I was thinking perhaps we should have a `tor-proxy-mode`, with some useful defaults as well as at least a helper function to detect Onion-Location headers / meta tags. Should I open a new issue, perhaps? At any rate, we can also add meta tag support, because even TBB lets the page load (fully?) before prompting. That would be better than nothing, especially if the user can automagically add an auto-mode rule!

**Comment by aartaka** [comment]
> I was thinking perhaps we should have a `tor-proxy-mode`, with some useful defaults as well as at least a helper function to detect Onion-Location headers / meta tags. Should I open a new issue, perhaps? 

Yes, `tor-proxy-mode` (or even `tor-mode`) I'd enjoy!

> At any rate, we can also add meta tag support, because even TBB lets the page load (fully?) before prompting. That would be better than nothing, especially if the user can automagically add an auto-mode rule!

Oh, the part about prompting after the page is loaded I missed. Should be possible with `nyxt/dom` API indeed.

**Comment by Ambrevar** [comment]
Thanks a lot, Artyom!
