### ISSUE TITLE
Remove describe-command in favor of describe-function?

### ISSUE THREAD

**Issue by aartaka** [atlas-engineer/nyxt#2600]
**Is your feature request related to a problem? Please describe.**

With the introduction of things like `function-lambda-string` and other niceties, `describe-function` have quickly outgrown `describe-command` in both size and features. If I was to inspect a command for its source code or argument list, I'd rather use `describe-function` than `describe-command`. And that's fair, given that our commands are essentially functions and there's not much information about them _as commands_. But right now, the only useful bit of information that `describe-command` provides is the key binding of the command you inspect. Which could be possible to actually embed in `describe-function` too...

This kind of domain representation problem irks me as someone who likes removing unnecessary things.

**Describe the solution you'd like**

Maybe remove the `describe-command` and move its binding inspection to `describe-function`? Shouldn't be hard to do...

**Describe alternatives you've considered**
- Making `describe-command` a mere alias for `describe-function`.
- Incorporating/duplicating most of the logic from `describe-function` into `describe-command` to make it more useful and command-specific.

**Comment by aadcg** [comment]
I'm afraid I disagree. 

What you say is true, but the point of having `describe-command` is that you immediately set the convenient search space.

If there are some discrepancies between `describe-command` and `describe-function`, then that needs to be addressed for sure. The former should specialize on the latter.

**Comment by aartaka** [comment]
Okay, another take: how about abstracting all our symbol-listing/inspection things, like `(function|class|variable|package)-(symbols|source)` and `resolve-symbol` into a mini-library with configurable types of listings (`:function`, `:class`, `:variable`, `:package` being the defaults and `:mode`/`:command` being derived from `:class` and `:function` respectively).

This will also ensure we have much less problems resolving thing at compile-time and don't depend on `mode.lisp` for `resolve-symbol`.

**Comment by aadcg** [comment]
That sounds good to me!

**Comment by aartaka** [comment]
Then I get to hacking on yet another library for us :D
