### ISSUE TITLE
Rename `prompter` concepts

### ISSUE THREAD

**Issue by aadcg** [atlas-engineer/nyxt#2601]
While working on #2555, I noticed that `prompter`'s concepts can be difficult to internalize.

I suggest the following rename (reasoning below):

- `selection` -> `current-suggestion`
- `selection-actions` -> `current-suggestion-actions`
- `marks` -> `selection`
- `marks-actions` -> `selection-actions`

The key observation is that `marks` only exist when `multi-selection-p` is non-nil, which immediately makes us think of a selection (a set of items). But that collides with our concept for "the current suggestion", which we call it `selection`...

In #2527 I have proposed `marks` to be a singular concept, and `selection` falls in that category too. This proposal makes #2527 obsolete.

With this rename the overview of the `prompter` library would be as follows.  
 

> The key objects are =prompters=, =sources= and =suggestions=.
> 
> A =prompt= is an interface for user interactions that holds one or more
> =sources=, and each of those are populated by =suggestions=.
> 
> Other central concepts include:
> 
> - =prompt=
>    + =current-suggestion= :: A single =suggestion=, if any.  Think of it as the currently
>      selected =suggestion=, belonging to a =source=.
> - =source=
>    + =selection= :: A list of =suggestions=, when =multi-selection-p= is non-nil.
>    + =actions= :: A list of functions that run on =suggestions=.
>       - =return-actions= :: General purpose.
>       - =selection-actions= :: On =selection= change (event-driven).
>       - =current-suggestion-actions= :: On =current-suggestion= change (event-driven).
>

**Comment by aartaka** [comment]
But then `marks-actions` should be `selection-actions`, no? Which collides with the existing ones...

**Comment by aartaka** [comment]
Other than that, `selection` and `current-suggestion` sound good to me, yes!

**Comment by aadcg** [comment]
Oops, good point @aartaka. I forgot to update the `action`-related concepts. I've edited the top post, please take a look.

`current-suggestion-actions` is perhaps a bit verbose, but I'm afraid we can't do much better...

**Comment by aartaka** [comment]
Well, there can be other shorter terms for current suggestion. Like `cursor`, `focus`, `point`, `locus`?

**Comment by aadcg** [comment]
The issue is that `prompter` is a just a backend libary, so I'm afraid those suggestions might not be the suitable.

**Comment by aartaka** [comment]
I mean, `cursor` is a data structure term as much as UI one, and `focus` is merely a generic word for one's center of attention at a certain moment in time. Those two are kind of suitable, even for a backend library.

**Comment by aadcg** [comment]
Fair. 

Let's wait for @Ambrevar's input.

**Comment by Ambrevar** [comment]
Well, `selection` is a pretty good term for the current suggestion :)
Can also have `selections` and `current-selection`.

Let's sleep over this.

**Comment by aadcg** [comment]
@Ambrevar I'd like to ping on this issue since it's extremely important. 

The prompt buffer entry on the manual is perhaps the most important  one, since this special buffer is the main interface from the user's perspective.

In other to write a proper entry, we need to settle on a set consistent concepts between `prompter` (the external library) and `prompter-buffer` (in nyxt's package).

When we reach consensus, let's incorporate this into #2630.

**Comment by Ambrevar** [comment]
I'm fine with the suggestion from the original post.

**Comment by aadcg** [comment]
Didn't add this bit as part of #2630 so that it would be easier to review. Will open a separate PR on that.
