### ISSUE TITLE
Guix Install Failure

### ISSUE THREAD

**Issue by pierceglenn12345** [atlas-engineer/nyxt#2604]
**Describe the bug**
I have installed Nyxt on the Librem 5 before and was 'guix upgrade nyxt' 'ing just fine.

Now I am having an issue with the process above 'guix install nyxt' or guix upgrade nyxt
 after a 'guix pull' request:

building /gnu/store/xxxxxxxxxxxxxxxxxxxxxxxxxxxxx-inkscape.1.1.1drv... 
35% {############                                                                             ]
guix install: error corrupt input while restoring archive from socket

From here I can no longer use guix without restarting the Librem 5. The hang up is always on inkscape. I have seen before that there is a file location that you can search to look at error messages for times like these, but I don't see it now and can't remember where that location is. If someone knows and can remind me, I will add to this report.

**Precise recipe to reproduce the issue**
guix install nyxt

**Information**
- PureOS - Librem 5
- Graphics card and driver: Vivante GC7000Lite
- Desktop environment / Window manager name+version: GNOME?
- How you installed Nyxt: 'guix install nyxt'
- Information from `show-system-information`:

**Comment by aadcg** [comment]
It doesn't seem to be related to Nyxt.

Could you try to upgrade `nyxt` alone by issuing the following `guix package --upgrade nyxt`?

**Comment by pierceglenn12345** [comment]
Describe the bug
I have installed Nyxt on the Librem 5 before and was 'guix upgrade nyxt' 'ing just fine.

Now I am having an issue while the process above 'guix install nyxt' or guix upgrade nyxt
after a 'guix pull' request:



That is what I have been doing. My most recent attempt has involved 
1.'guix remove nyxt' 
2. guix gc --delete-generations
3. 'guix nyxt install' 

Which gives me the same error. I cannot guix package --upgrade nyxt because it is not installed

**Comment by aadcg** [comment]
Your Guix profile seems to be misbehaving and this is not related to Nyxt.

What happens when you `guix install hello`?

**Comment by pierceglenn12345** [comment]
Installs with out error

**Comment by aartaka** [comment]
I usually get this error when the network is terribly unstable or when substitute servers misbehave. And it's a Guix error, totally unrelated to Nyxt.
