### ISSUE TITLE
Testing the `nyxt/gi-gtk` system seems to be broken

### ISSUE THREAD

**Issue by aadcg** [atlas-engineer/nyxt#2609]
While working on #2605, I noticed that I couldn't test `nyxt/gi-gtk` on master.

From the REPL, I issued `,test-system RET nyxt/gi-gtk` and got:

> WARNING: System definition file #P"/home/aadcg/common-lisp/lisp-unit2/lisp-unit2.asd" contains definition for system "lisp-unit2-test". Please only define "lisp-unit2" and secondary systems with a name starting with "lisp-unit2/" (e.g. "lisp-unit2/test") in that file.
> WARNING: System definition file #P"/gnu/store/r860vmxghysv74435fvjj4g52xzhw41y-cl-symbol-munger-0.0.1-1.97598d4/share/common-lisp/source/cl-symbol-munger/symbol-munger.asd" contains definition for system "symbol-munger-test". Please only define "symbol-munger" and secondary systems with a name starting with "symbol-munger/" (e.g. "symbol-munger/test") in that file.
> WARNING: redefining HU.DWIM.DEFCLASS-STAR::PROCESS-SLOT-DEFINITION in DEFUN
> ; compiling file "/home/aadcg/common-lisp/nyxt/source/renderer/gi-gtk.lisp" (written 17 OCT 2022 03:10:34 PM):
> 
> ; wrote /home/aadcg/.cache/common-lisp/sbcl-2.2.6-linux-x64/home/aadcg/common-lisp/nyxt/source/renderer/gi-gtk-tmpRF6DISR1.fasl
> ; compilation finished in 0:00:00.048
> ; compiling file "/home/aadcg/common-lisp/nyxt/tests/renderer-package.lisp" (written 31 OCT 2022 01:04:22 PM):
> 
> ; wrote /home/aadcg/.cache/common-lisp/sbcl-2.2.6-linux-x64/home/aadcg/common-lisp/nyxt/tests/renderer-package-tmp3OXMRLFZ.fasl
> ; compilation finished in 0:00:00.020
> ; compiling file "/home/aadcg/common-lisp/nyxt/tests/renderer-offline/set-url.lisp" (written 31 OCT 2022 01:04:22 PM):
> 
> ; wrote /home/aadcg/.cache/common-lisp/sbcl-2.2.6-linux-x64/home/aadcg/common-lisp/nyxt/tests/renderer-offline/set-url-tmp2XEJNW23.fasl
> ; compilation finished in 0:00:00.020
> ; compiling file "/home/aadcg/common-lisp/nyxt/tests/renderer-offline/execute-command-eval.lisp" (written 17 OCT 2022 03:10:34 PM):
> 
> ; wrote /home/aadcg/.cache/common-lisp/sbcl-2.2.6-linux-x64/home/aadcg/common-lisp/nyxt/tests/renderer-offline/execute-command-eval-tmpTUBS88ZA.fasl
> ; compilation finished in 0:00:00.004
> ; compiling file "/home/aadcg/common-lisp/nyxt/tests/renderer-online/set-url.lisp" (written 26 SEP 2022 05:07:13 PM):
> 
> ; file: /home/aadcg/common-lisp/nyxt/tests/renderer-online/set-url.lisp
> ; in: DEFMACRO WITH-PROMPT-BUFFER-TEST
> ;     (DEFMACRO NYXT/TESTS/RENDERER::WITH-PROMPT-BUFFER-TEST
> ;               (NYXT/TESTS/RENDERER::COMMAND &BODY NYXT/TESTS/RENDERER::BODY)
> ;       (ALEXANDRIA:WITH-GENSYMS (NYXT/TESTS/RENDERER::THREAD)
> ;         `(LET ((,NYXT/TESTS/RENDERER::THREAD #))
> ;            (CALISPEL:? (NYXT/TESTS/RENDERER::PROMPT-BUFFER-CHANNEL #))
> ;            ,@NYXT/TESTS/RENDERER::BODY
> ;            (NYXT/TESTS/RENDERER::RETURN-SELECTION)
> ;            (BORDEAUX-THREADS:JOIN-THREAD ,NYXT/TESTS/RENDERER::THREAD))))
> ; --> EVAL-WHEN 
> ; ==>
> ;   (SB-C::%DEFMACRO 'NYXT/TESTS/RENDERER::WITH-PROMPT-BUFFER-TEST
> ;                    (SB-INT:NAMED-LAMBDA (MACRO-FUNCTION
> ;                                          NYXT/TESTS/RENDERER::WITH-PROMPT-BUFFER-TEST)
> ;                        (#:EXPR #:ENV)
> ;                      (DECLARE
> ;                       (SB-C::LAMBDA-LIST
> ;                        (NYXT/TESTS/RENDERER::COMMAND &BODY
> ;                         NYXT/TESTS/RENDERER::BODY)))
> ;                      (DECLARE (IGNORE #:ENV))
> ;                      (SB-INT:NAMED-DS-BIND (:MACRO
> ;                                             NYXT/TESTS/RENDERER::WITH-PROMPT-BUFFER-TEST
> ;                                             . DEFMACRO)
> ;                          (NYXT/TESTS/RENDERER::COMMAND &BODY
> ;                           NYXT/TESTS/RENDERER::BODY)
> ;                          (CDR #:EXPR)
> ;                        (DECLARE
> ;                         (SB-C::CONSTANT-VALUE NYXT/TESTS/RENDERER::COMMAND
> ;                                               NYXT/TESTS/RENDERER::BODY))
> ;                        (BLOCK NYXT/TESTS/RENDERER::WITH-PROMPT-BUFFER-TEST
> ;                          (ALEXANDRIA:WITH-GENSYMS #
> ;                            `#))))
> ;                    (SB-C:SOURCE-LOCATION))
> ; 
> ; caught STYLE-WARNING:
> ;   redefining NYXT/TESTS/RENDERER::WITH-PROMPT-BUFFER-TEST in DEFMACRO
> 
> 
> ; wrote /home/aadcg/.cache/common-lisp/sbcl-2.2.6-linux-x64/home/aadcg/common-lisp/nyxt/tests/renderer-online/set-url-tmpUHZBCE1Q.fasl
> ; compilation finished in 0:00:00.008
> WARNING:
>    Lisp compilation had style-warnings while
>    compiling #<CL-SOURCE-FILE "nyxt/gi-gtk/tests" "tests/renderer-online/set-url">
> 
> ------- STARTING Testing: NYXT/TESTS/RENDERER 
> 
> Starting: NYXT/TESTS/RENDERER::SET-OFFLINE-URL
> Nyxt version 3-pre-release-2-205-gf28061005
> <INFO> [13:09:59] Source location: #P"/home/aadcg/common-lisp/nyxt/"
> <INFO> [13:09:59] Profile: "test"
> <INFO> [13:10:00] GTK extensions directory: #P"/tmp/nyxt-tests/home/aadcg/common-lisp/nyxt/libraries/web-extensions/"
> <INFO> [13:10:00] GTK extensions directory: #P"/tmp/nyxt-tests/home/aadcg/common-lisp/nyxt/libraries/web-extensions/"
> <INFO> [13:10:01] Loading #P"/tmp/nyxt-tests/home/aadcg/.local/share/nyxt/bookmarks.lisp".
> <INFO> [13:10:02] Deleting socket #P"/tmp/nyxt-test.socket".
> NYXT/TESTS/RENDERER::SET-OFFLINE-URL - PASSED (2.45s) : 1 assertions passed
> 
> Starting: NYXT/TESTS/RENDERER::EXECUTE-COMMAND-1+
> Nyxt version 3-pre-release-2-205-gf28061005
> <INFO> [13:10:02] Source location: #P"/home/aadcg/common-lisp/nyxt/"
> <INFO> [13:10:02] Profile: "test"
> <INFO> [13:10:02] GTK extensions directory: #P"/tmp/nyxt-tests/home/aadcg/common-lisp/nyxt/libraries/web-extensions/"
> <INFO> [13:10:02] GTK extensions directory: #P"/tmp/nyxt-tests/home/aadcg/common-lisp/nyxt/libraries/web-extensions/"
> WARNING:
>    Error on separate prompter thread: There is no applicable method for the generic function
>                                         #<STANDARD-GENERIC-FUNCTION ANALYSIS::EDGES (2)>
>                                       when called with arguments
>                                         (NIL).
> See also:
>   The ANSI Standard, Section 7.6.6

**Comment by Ambrevar** [comment]
This is the recent merge of the `predict` branch.  @jmercouris Were these tests working?

**Comment by aadcg** [comment]
The culprit is aab4760389f95614db7e2f5c64b597f67ca0abb7 but, by inspecting the commit, I can't make sense of why the tests are failing... @jmercouris, @Ambrevar?

Still, that's not the whole story.

Before the aforementioned commit, the tests don't halt for me and I need to cancel the process from the REPL.

Here's the relevant part of the output:
```
; wrote /home/aadcg/.cache/common-lisp/sbcl-2.2.6-linux-x64/home/aadcg/common-lisp/nyxt/tests/renderer-offline/execute-command-eval-tmpG300S9SF.fasl
; compilation finished in 0:00:00.004
; compiling file "/home/aadcg/common-lisp/nyxt/tests/renderer-online/set-url.lisp" (written 31 OCT 2022 07:08:57 PM):

; file: /home/aadcg/common-lisp/nyxt/tests/renderer-online/set-url.lisp
; in: DEFMACRO WITH-PROMPT-BUFFER-TEST
;     (DEFMACRO NYXT/TESTS/RENDERER::WITH-PROMPT-BUFFER-TEST
;               (NYXT/TESTS/RENDERER::COMMAND &BODY NYXT/TESTS/RENDERER::BODY)
;       (ALEXANDRIA:WITH-GENSYMS (NYXT/TESTS/RENDERER::THREAD)
;         `(LET ((,NYXT/TESTS/RENDERER::THREAD #))
;            (CALISPEL:? (NYXT/TESTS/RENDERER::PROMPT-BUFFER-CHANNEL #))
;            ,@NYXT/TESTS/RENDERER::BODY
;            (NYXT/TESTS/RENDERER::RETURN-SELECTION)
;            (BORDEAUX-THREADS:JOIN-THREAD ,NYXT/TESTS/RENDERER::THREAD))))
; --> EVAL-WHEN 
; ==>
;   (SB-C::%DEFMACRO 'NYXT/TESTS/RENDERER::WITH-PROMPT-BUFFER-TEST
;                    (SB-INT:NAMED-LAMBDA (MACRO-FUNCTION
;                                          NYXT/TESTS/RENDERER::WITH-PROMPT-BUFFER-TEST)
;                        (#:EXPR #:ENV)
;                      (DECLARE
;                       (SB-C::LAMBDA-LIST
;                        (NYXT/TESTS/RENDERER::COMMAND &BODY
;                         NYXT/TESTS/RENDERER::BODY)))
;                      (DECLARE (IGNORE #:ENV))
;                      (SB-INT:NAMED-DS-BIND (:MACRO
;                                             NYXT/TESTS/RENDERER::WITH-PROMPT-BUFFER-TEST
;                                             . DEFMACRO)
;                          (NYXT/TESTS/RENDERER::COMMAND &BODY
;                           NYXT/TESTS/RENDERER::BODY)
;                          (CDR #:EXPR)
;                        (DECLARE
;                         (SB-C::CONSTANT-VALUE NYXT/TESTS/RENDERER::COMMAND
;                                               NYXT/TESTS/RENDERER::BODY))
;                        (BLOCK NYXT/TESTS/RENDERER::WITH-PROMPT-BUFFER-TEST
;                          (ALEXANDRIA:WITH-GENSYMS #
;                            `#))))
;                    (SB-C:SOURCE-LOCATION))
; 
; caught STYLE-WARNING:
;   redefining NYXT/TESTS/RENDERER::WITH-PROMPT-BUFFER-TEST in DEFMACRO


; wrote /home/aadcg/.cache/common-lisp/sbcl-2.2.6-linux-x64/home/aadcg/common-lisp/nyxt/tests/renderer-online/set-url-tmp809IFK9M.fasl
; compilation finished in 0:00:00.012
WARNING:
   Lisp compilation had style-warnings while
   compiling #<CL-SOURCE-FILE "nyxt/gi-gtk/tests" "tests/renderer-online/set-url">
WARNING: redefining NYXT/TESTS/RENDERER::TEST-SET-URL in DEFUN

------- STARTING Testing: NYXT/TESTS/RENDERER 

Starting: NYXT/TESTS/RENDERER::SET-OFFLINE-URL
Nyxt version 3-pre-release-2-110-g527b92e0a
<INFO> [19:17:15] Source location: #P"/home/aadcg/common-lisp/nyxt/"
<INFO> [19:17:15] Profile: "test"
<INFO> [19:17:15] GTK extensions directory: #P"/tmp/nyxt-tests/home/aadcg/common-lisp/nyxt/libraries/web-extensions/"
<INFO> [19:17:16] GTK extensions directory: #P"/tmp/nyxt-tests/home/aadcg/common-lisp/nyxt/libraries/web-extensions/"
<INFO> [19:17:16] Loading #P"/tmp/nyxt-tests/home/aadcg/.local/share/nyxt/bookmarks.lisp".
<INFO> [19:17:17] Deleting socket #P"/tmp/nyxt-test.socket".
NYXT/TESTS/RENDERER::SET-OFFLINE-URL - PASSED (2.25s) : 1 assertions passed

Starting: NYXT/TESTS/RENDERER::EXECUTE-COMMAND-1+
Nyxt version 3-pre-release-2-110-g527b92e0a
<INFO> [19:17:17] Source location: #P"/home/aadcg/common-lisp/nyxt/"
<INFO> [19:17:17] Profile: "test"
<INFO> [19:17:17] GTK extensions directory: #P"/tmp/nyxt-tests/home/aadcg/common-lisp/nyxt/libraries/web-extensions/"
<INFO> [19:17:17] GTK extensions directory: #P"/tmp/nyxt-tests/home/aadcg/common-lisp/nyxt/libraries/web-extensions/"
<INFO> [19:17:24] 4
<INFO> [19:17:24] Deleting socket #P"/tmp/nyxt-test.socket".
<WARN> [19:17:24] Warning: JavaScript error: GError: Domain: "WebKitJavascriptError", Code: 699, Message: 
<WARN> [19:17:24] Failed to echo these args: ("JavaScript error: ~a"
                                              #<GLIB::G-ERROR-CONDITION {100CCB7BF3}>)
Possible improvements:
- Pass multiple arguments and use format strings for untrusted content. Don't pre-construct a single string that could contain tildes.
  Example: do (echo "directory is ~a "~/Downloads/")
           instead of (echo "directory is ~/Downloads/")
- Use the ~s directive.
NYXT/TESTS/RENDERER::EXECUTE-COMMAND-1+ - PASSED (6.58s) : 2 assertions passed

Starting: NYXT/TESTS/RENDERER::SET-ONLINE-URL
Nyxt version 3-pre-release-2-110-g527b92e0a
<INFO> [19:17:24] Source location: #P"/home/aadcg/common-lisp/nyxt/"
<INFO> [19:17:24] Profile: "test"
<INFO> [19:17:24] GTK extensions directory: #P"/tmp/nyxt-tests/home/aadcg/common-lisp/nyxt/libraries/web-extensions/"
<INFO> [19:17:29] Deleting socket #P"/tmp/nyxt-test.socket".
NYXT/TESTS/RENDERER::SET-ONLINE-URL - FAILED (241.47s) : 0 assertions passed
  | FAILED (1)
  | Failed Form: (LISP-UNIT2:ASSERT-STRING= NYXT/TESTS/RENDERER::URL
  |                                         (CALISPEL:?
  |                                          NYXT/TESTS/RENDERER::URL-CHANNEL
  |                                          5))
  | Expected "http://example.org/"
  | but saw NIL; NIL
  |
  |
Test Summary for :NYXT/TESTS/RENDERER (3 tests 250.31 sec)
  | 4 assertions total
  | 3 passed
  | 1 failed
  | 0 execution errors
  | 0 warnings
  | 0 empty
  | 0 missing tests

-------   ENDING Testing: NYXT/TESTS/RENDERER 
; 
; compilation unit aborted
;   caught 1 fatal ERROR condition
;   caught 1 STYLE-WARNING condition
```

**Comment by Ambrevar** [comment]
@aadcg Isn't this fixed?

**Comment by aadcg** [comment]
On my side, it is not.  What makes you think in that way?

**Comment by aadcg** [comment]
If I had to guess I'd say the issues steam from the kind of logic written in `test-set-url` and `execute-command-1+`. The former was written by @Ambrevar, while the latter by @aartaka (but I'm almost sure @aartaka  copied it from you since it was added later :p).

In short, take a quick look at `test-set-url`. If you can immediately figure it out, let me know. Otherwise I will have a closer look myself.

**Comment by Ambrevar** [comment]
The `EDGES` error started occurring recently, maybe around the time the packages got refactored in #2605.

**Comment by Ambrevar** [comment]
No, it's older than that.

**Comment by Ambrevar** [comment]
The command prediction is the culprit: #2593.

**Comment by aadcg** [comment]
> The `EDGES` error started occurring recently, maybe around the time the packages got refactored in #2605.

No. As I've noted above the culprit is commit aab4760389f95614db7e2f5c64b597f67ca0abb7.

**Comment by aadcg** [comment]
> The command prediction is the culprit: #2593.

Yes. [I've narrowed down to the exact commit from the very beginning](https://github.com/atlas-engineer/nyxt/issues/2609#issuecomment-1297433142).

But please don't worry about that.

The more important issue is the other one I mention.  Please take a look at `test-set-url` if you have time.

**Comment by Ambrevar** [comment]
I've pushed some fixes on master.  That said, the renderer tests still don't execute well.

What's noteworthy is that `set-offline-url` works well at all times.  However, running `execute-command-1+` 2 times in a row shows something is off...

@aartaka Any idea?

**Comment by aartaka** [comment]
Ooops, wrong commit number (^_^;)

**Comment by aadcg** [comment]
@Ambrevar could you explain me why do we need `with-headless`? Why isn't let-binding `*headless-p*` enough?

**Comment by aadcg** [comment]
> Could someone explain me why does the following doesn't behave as intended? Is this a bug or by design?
> 
> ```lisp
> (progn (nyxt:start :no-config t :no-auto-config t :no-socket t) 
>        (nyxt:quit))
> ```

I understood why this doesn't work. It's because of the handing of the `ready-p` slot belonging to browser.

**Comment by aadcg** [comment]
Another fun thing. The following displays Nyxt...

```lisp
(with-headless
    (nyxt:start :no-config t :no-auto-config t
                :socket "/tmp/nyxt-test.socket"
                :profile "test"))
```

**Comment by aartaka** [comment]
Graphical Nyxt pops up because by then time Nyxt looks at the `*headless-p*` in your examples, it's already NIL. Note that all the renderer-related actions and even Nyxt-internal actions all happen on threads other than the one `nyxt:start` is invoked on. So, the problem roughly is:
``` 
Start thread:
  *headless-p* is T
  nyxt:start
  unwind-protect -> *headless-p* is NIL

GTK thread (appears after nyxt:start):
  *headless-p* is _already_ NIL because of Start thread
  Graphical initialization because *headless-p* is NIL
``` 

Note that the `remembrance` test doesn't suffer this problem because it uses `wait-on-handler nyxt:*after-startup-hook*` until the startup is done in headless mode.
