### ISSUE TITLE
Unknown GBoxed type 'SoupMessageHeaders'

### ISSUE THREAD

**Issue by hendursaga** [atlas-engineer/nyxt#2616]
Under cf49753a0826a6d97f498d36e0d5acb189021e15, with [my minimal config](https://discourse.atlas.engineer/t/my-bare-minimum-nyxt-config/565?u=hendursaga), when I try to navigate to pretty much any URL, I get `Warning: Error in FFI method: Unknown GBoxed type 'SoupMessageHeaders'`. I cannot figure out how to debug this, although I made some progress by setting `*restart-on-error*` to `T` and getting a little more information:

```
<WARN> [16:03:26] Warning: Restarted without configuration file due to error: Unknown GBoxed type 'SoupMessageHeaders'
<WARN> [16:03:26] Warning: Error on separate thread: The value
  'NYXT::SOUPMESSAGEHEADERS
is not of type
  SYMBOL
```

I'm pretty sure this has to do with the new cl-webkit version and https://github.com/atlas-engineer/nyxt/commit/2a8abdc2e589895e680b4bd85ba70de82250e88c..

**Comment by Ambrevar** [comment]
Cc @aartaka

**Comment by aartaka** [comment]
I am puzzled. @hendursaga, can you try `toggle-debug-on-error` and report the full page with an error?

**Comment by hendursaga** [comment]
Debug on error doesn't really get things closer, but...

```
<WARN> [11:59:59] Warning: Error in FFI method: Unknown GBoxed type 'SoupMessageHeaders'
The WebExtensions support library is loaded
The WebExtensions support library is loaded
<INFO> [12:00:18] Failed to load URL nyxt:new in buffer 946.
<INFO> [12:00:34] Pressed keys: C-x
<INFO> [12:00:38] Loading "https://example.org/".
<WARN> [12:00:38] Warning: Error in FFI method: Unknown GBoxed type 'SoupMessageHeaders'
<INFO> [12:00:53] Failed to load URL https://example.org/ in buffer 946.
<INFO> [12:00:54] Loading "https://example.org/".
<INFO> [12:00:54] Finished loading "https://example.org/".
<INFO> [12:00:54] Finished loading "https://example.org/".
<INFO> [12:01:02] Pressed keys: C-x
<INFO> [12:01:12] Nyxt-native debugging enabled.
<INFO> [12:01:16] Loading "https://example.org/".
<WARN> [12:01:16] Warning: decide policy error: Unknown GBoxed type 'SoupMessageHeaders' <--- switches from FFI to decide policy here
<INFO> [12:01:16] Failed to load URL https://example.org/ in buffer 946.
<INFO> [12:01:16] Loading "https://example.org/".
<INFO> [12:01:16] Finished loading "https://example.org/".
<INFO> [12:01:16] Finished loading "https://example.org/".
<INFO> [12:01:43] Loading "https://example.org/".
<WARN> [12:01:43] Warning: decide policy error: Unknown GBoxed type 'SoupMessageHeaders'
<INFO> [12:01:43] Failed to load URL https://example.org/ in buffer 946.
<INFO> [12:01:43] Loading "https://example.org/".
<INFO> [12:01:44] Finished loading "https://example.org/".
<INFO> [12:01:44] Finished loading "https://example.org/".
;; Slynk started at port: 4006.
<INFO> [12:05:42] Slynk server started at port 4006
WARNING: redefining SLYNK::SYMBOL-INDENTATION in DEFUN
WARNING: redefining SLYNK::MACRO-INDENTATION in DEFUN
<INFO> [12:05:56] Nyxt-native debugging enabled. <--- I also ran (setf nyxt::*run-from-repl-p* t) here
<INFO> [12:06:06] Loading "https://example.org/".
<WARN> [12:06:06] Warning: Error on GI-GTK thread: Unknown GBoxed type 'SoupMessageHeaders' <--- now it's a GI-GTK problem!
[and... CRASH!]
```

See how it can't load even [nyxt:new]() at the start? Once again, the single largest blocking issue for all kinds of issues I'm having is https://github.com/atlas-engineer/nyxt/issues/2466 - can someone add a `high` label to it or something?

**Comment by aartaka** [comment]
Okay, I've encountered this problem too. It's because the auto-generated `webkit-uri-response-http-headers` method implies that `SoupMessageHeaders` are a `GBoxed` structure, which they are not. I've fixed this assertion in `cl-webkit` 3.5.6, but we need to:
- Propagate the fix to Nyxt (done in #2490, but maybe we want to add it to `master` instead).
- Send a patch with `cl-webkit` 3.5.6 to Guix (@Ambrevar? Or I can do it myself tomorrow).

**Comment by Ambrevar** [comment]
Did you send a patch to Guix?

**Comment by aartaka** [comment]
> Did you send a patch to Guix?

No, I didn't へ(゜∇、°)へ

**Comment by Ambrevar** [comment]
Should I update it today?

**Comment by aartaka** [comment]
> Should I update it today?

Yes, that would be cool!

**Comment by Ambrevar** [comment]
Done!

**Comment by aartaka** [comment]
Thanks!
