### ISSUE TITLE
Don't restore session when in `--fail-safe` mode

### ISSUE THREAD

**Issue by aartaka** [atlas-engineer/nyxt#2623]
**Is your feature request related to a problem? Please describe.**
I often use `--fail-safe` mode, because my experimentations with some branches on Nyxt leave my history polluted with URLs unsupported on master. And I often find that a mere `--fail-safe` is insufficient for coping with this borked history file. It's only
``` lisp
(define-configuration browser
  ((restore-session-on-startup-p nil)))
```
that helps.

**Describe the solution you'd like**
How about we set `restore-session-on-startup-p` to NIL if `--fail-safe`?

**Comment by Ambrevar** [comment]
I've pushed a fix for `nfiles`: virtual files were not working when an around method was specified.

Should be working now.  Please confirm and I'll release a new nfiles version.

**Comment by Ambrevar** [comment]
@aartaka Note that it's `--failsafe`, one word :)

**Comment by aartaka** [comment]
> I've pushed a fix for `nfiles`: virtual files were not working when an around method was specified.

Waaaaait, so it actually shouldn't've had restored history, because it used nosave-mode? ヾ(@°▽°@)ノ

**Comment by Ambrevar** [comment]
It uses the `nofile` profile.  See `startup.lisp`:

```lisp
(when failsafe
      (setf
       (getf *options* :verbose) t
       (getf *options* :no-config) t
       (getf *options* :no-auto-config) t
       (getf *options* :no-socket) t
       (getf *options* :profile) (profile-name (find-class 'nofile-profile))))
```
