### ISSUE TITLE
Review all keybindings before releasing `3.0`

### ISSUE THREAD

**Issue by aadcg** [atlas-engineer/nyxt#2628]
Adding it as a reminder.

@aartaka [advocated for rebinding `set-action-on-return` (ex `return-selection-over-actions`)](https://github.com/atlas-engineer/nyxt/pull/2555#issuecomment-1300309695).

> `set-action-on-return` (ex `return-selection-over-action`) should be bound to `shift-return` instead of `M-return`. The latter should be reserved for "strong" actions that close the prompt-buffer, analogous to `return` and `C-return` (return stands either for "activate this now" or "I'm done, commit this action" in CUA). If we dilute the responsibility one takes when pressing `M-return`, then the character of other actions bound to *-return will not be perceived as final and decisive for a given prompt.

**Comment by aartaka** [comment]
Maybe `shift-return` is too strong too, by the way!

**Comment by aadcg** [comment]
Any update here @aartaka? Do we still want to change this keybinding?

**Comment by aartaka** [comment]
I still think we should change the keybinding, and `s-return` sounds good.
