### ISSUE TITLE
Actions jobs are stuck?

### ISSUE THREAD

**Issue by createyourpersonalaccount** [atlas-engineer/nyxt#2638]
I think there is something wrong with the actions jobs, for example https://github.com/atlas-engineer/nyxt/actions/runs/3440346052/jobs/5738705627 is stuck at "Installing Roswell" for over an hour now.

It seems that there are other jobs pending too. I couldn't figure out how to cancel it (I'm not sure if I'm authorized).

**Comment by jmercouris** [comment]
sometimes they do get stuck, not sure why. I think it happens when the servers that we depend on for downloads fail. I wish we could somehow cache the VM that we use for testing.

**Comment by createyourpersonalaccount** [comment]
@jmercouris Why can't roswell be installed on the docker image?

**Comment by aartaka** [comment]
@aadcg, Github Actions are Docker underneath, IIRC :)

**Comment by Ambrevar** [comment]
Yes they are.  We use some pre-existing images which don't have Roswell on by default.
Roswell installation is cached, so in most cases it should be a very cheap operation.

@createyourpersonalaccount It's actually the first time I see this error on the CI.  So I guess it's a very infrequent issue, no need to worry about it.
