### ISSUE TITLE
Unable to start Nyxt when in the previous session a "view-source" was executed and its buffer kept open

### ISSUE THREAD

**Issue by max1701** [atlas-engineer/nyxt#2646]
**Describe the bug**

Nyxt can not be started any more, when in the previous session a "view-source" from e.g. a "describe-class" internal nyxt page was opened and afterwards Nyxt was terminated using "quit".

Seems, the html source page in the history causes the error. To be able to start nyxt again, one has to delete the history under ~/.local/share/nyxt

**Precise recipe to reproduce the issue**

1) start nyxt
2) execute command e.g. "describe-class" with any class, e.g. PROMPT-BUFFER
3) with the describe-xxx buffer opened, execute command "view-source" --> source code buffer is opened
4) execute command "quit" to terminate nyxt
5) start nyxt again --> nyxt does not start anymore

**Information**

(Nyxt Version built from source)

Nyxt version: 3-pre-release-2
Renderer version: GI-GTK
Operating system kernel: Linux 6.0.8-arch1-1
Lisp implementation: SBCL 2.2.9 (Dynamic space size: 3221225472)
Features: (:NYXT-GI-GTK :NYXT-GTK :WEBKIT2 :WEBKIT2-2.38 :WEBKIT2-CORS-ALLOWLIST
 :WEBKIT2-PASTE-PLAINTEXT :WEBKIT2-TRACKING :WEBKIT2-MUTE :WEBKIT2-EMOJI
 :WEBKIT2-MEDIA :WEBKIT2-SANDBOXING :GTK-3-22 :GTK-3-20 :GTK-3-18 :GTK-3-16
 :GTK-3-14 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6 :GTK-3-4 :GTK :GDK-3-22
 :GDK-3-20 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12 :GDK-3-10 :GDK-3-8 :GDK-3-6
 :GDK-3-4 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF :GLIB-2-30 :GLIB-2-32 :GLIB-2-34
 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42 :GLIB-2-44 :GLIB-2-46 :GLIB-2-48
 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56 :GLIB-2-58 :GLIB :NYXT-3.1 :NYXT-3
 :NYXT-3-PRE-RELEASE-2 :CUSTOM-HASH-TABLE-NATIVE :SLYNK :PLUMP-UTF-32
 :PARENSCRIPT :FSET-EXT-STRINGS :GLOBAL-VARS :DECLARE-TYPES :NAMED-READTABLES
 :SWANK :LPARALLEL :21BIT-CHARS :CLOSER-MOP :CL-PPCRE-UNICODE :CL-UNICODE
 :CL-PPCRE :CHUNGA :FLEXI-STREAMS :BORDEAUX-THREADS :LPARALLEL.WITH-CLTL2
 :LPARALLEL.WITH-CAS :LPARALLEL.WITH-STEALING-SCHEDULER :SPLIT-SEQUENCE
 CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64 CFFI-FEATURES:UNIX :CFFI
 CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP :FAST-IO-SV :FAST-IO
 :CL-JSON-CLOS :CL-JSON :SBCL-USES-SB-ROTATE-BYTE CHIPZ-SYSTEM:GRAY-STREAMS
 :THREAD-SUPPORT :ASDF3.3 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX
 :NON-BASE-CHARS-EXIST-P :ASDF-UNICODE :X86-64 :GENCGC :64-BIT :ANSI-CL
 :COMMON-LISP :ELF :IEEE-FLOATING-POINT :LINUX :LITTLE-ENDIAN
 :PACKAGE-LOCAL-NICKNAMES :SB-CORE-COMPRESSION :SB-LDB :SB-PACKAGE-LOCKS
 :SB-THREAD :SB-UNICODE :SBCL :UNIX)

ASDF version: 3.3.1
ASDF registries: (NYXT-SOURCE-REGISTRY ENVIRONMENT-SOURCE-REGISTRY)
Critical dependencies: (/home/ms/common-lisp/nyxt/_build/cl-cffi-gtk/gtk/cl-cffi-gtk.asd
 /home/ms/common-lisp/nyxt/_build/cl-gobject-introspection/cl-gobject-introspection.asd
 /home/ms/common-lisp/nyxt/_build/cl-webkit/webkit2/cl-webkit2.asd)

**Output when started from a shell**

ms@archie~ $ ./common-lisp/nyxt/nyxt
Nyxt version 3-pre-release-2
<INFO> [13:01:27] Source location: #P"/home/ms/common-lisp/nyxt/"
<INFO> [13:01:27] Loading Lisp file #P"/home/ms/.config/nyxt/auto-config.3.lisp".
<INFO> [13:01:27] Loading Lisp file #P"/home/ms/.config/nyxt/config.lisp".
<WARN> [13:01:27] Not found slot OVERRIDE-MAP in class BUFFER, generating the wrapper method for configuration.
<INFO> [13:01:27] GTK extensions directory: #P"/home/ms/common-lisp/nyxt/libraries/web-extensions/"
<INFO> [13:01:27] Loading #P"/home/ms/.local/share/nyxt/history/default.lisp".
<INFO> [13:01:27] Restoring 3 buffers from history.
<INFO> [13:01:27] GTK extensions directory: #P"/home/ms/common-lisp/nyxt/libraries/web-extensions/"
<INFO> [13:01:27] Loading "view-source:nyxt%3Adescribe-class%3Funiversal%3D%251Bnil%26class%3D%251Bnyxt%252Fannotate-mode%253Aannotations-file".
Unhandled SB-PCL::NO-APPLICABLE-METHOD-ERROR in thread #<SB-THREAD:THREAD "Anonymous thread" RUNNING
                                                          {100EB46C13}>:
  There is no applicable method for the generic function
    #<STANDARD-GENERIC-FUNCTION NYXT/DOM:COPY (8)>
  when called with arguments
    (NIL).
See also:
  The ANSI Standard, Section 7.6.6

Backtrace for: #<SB-THREAD:THREAD "Anonymous thread" RUNNING {100EB46C13}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<SB-PCL::NO-APPLICABLE-METHOD-ERROR {100F0075F3}> #<unused argument> :QUIT T)
1: (SB-DEBUG::RUN-HOOK SB-EXT:*INVOKE-DEBUGGER-HOOK* #<SB-PCL::NO-APPLICABLE-METHOD-ERROR {100F0075F3}>)
2: (INVOKE-DEBUGGER #<SB-PCL::NO-APPLICABLE-METHOD-ERROR {100F0075F3}>)
3: (ERROR SB-PCL::NO-APPLICABLE-METHOD-ERROR :GENERIC-FUNCTION #<STANDARD-GENERIC-FUNCTION NYXT/DOM:COPY (8)> :ARGS (NIL))
4: ((:METHOD NO-APPLICABLE-METHOD (T)) #<STANDARD-GENERIC-FUNCTION NYXT/DOM:COPY (8)> NIL) [fast-method]
5: (SB-PCL::CALL-NO-APPLICABLE-METHOD #<STANDARD-GENERIC-FUNCTION NYXT/DOM:COPY (8)> (NIL))
6: (NYXT/DOCUMENT-MODE:GET-URL-SOURCE "nyxt:describe-class?universal=%1Bnil&class=%1Bnyxt%2Fannotate-mode%3Aannotations-file")
7: ((LAMBDA (URL BUFFER) :IN "/home/ms/common-lisp/nyxt/source/mode/document.lisp") "view-source:nyxt%3Adescribe-class%3Funiversal%3D%251Bnil%26class%3D%251Bnyxt%252Fannotate-mode%253Aannotations-file" #<unused argument>)
8: ((LAMBDA (NYXT::REQUEST) :IN NYXT::MAKE-CONTEXT) #<CL-WEBKIT2:WEBKIT-URI-SCHEME-REQUEST {100EB45733}>)
9: ((LAMBDA NIL :IN CL-WEBKIT2::URI-SCHEME-PROCESSED))
10: ((LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS))
11: ((FLET SB-UNIX::BODY :IN SB-THREAD::RUN))
12: ((FLET "WITHOUT-INTERRUPTS-BODY-11" :IN SB-THREAD::RUN))
13: ((FLET SB-UNIX::BODY :IN SB-THREAD::RUN))
14: ((FLET "WITHOUT-INTERRUPTS-BODY-4" :IN SB-THREAD::RUN))
15: (SB-THREAD::RUN)
16: ("foreign function: call_into_lisp_")

unhandled condition in --disable-debugger mode, quitting
<WARN> [13:01:27] Warning: Error: Joining thread failed: thread #&lt;THREAD &quot;Nyxt renderer thread&quot; ABORTED {1007D1FEB3}&gt; did not return normally.

[nyxt-sysinfo.txt](https://github.com/atlas-engineer/nyxt/files/10032112/nyxt-sysinfo.txt)
[nyxt-error.txt](https://github.com/atlas-engineer/nyxt/files/10032113/nyxt-error.txt)

**Comment by max1701** [comment]
Maybe important to mention that i quited nyxt with the view-source buffer active and in my setup nyxt on startup reopens the last URL automatically - in this case the view-source buffer (at least to tries to reopen it :)

However, it looks like it's just a problem with my build of nyxt, so i;ll close the issue.

**Comment by aadcg** [comment]
@max1701, yes, that is clear. I was able to quit Nyxt and re-start it on a view-source buffer though. Both on master and on the latest tagged release `3-pre-release-2`.

If you'll be able to add some more information to your report and reproduce it, please feel free to reopen it.
