### ISSUE TITLE
dock icon confusion

### ISSUE THREAD

**Issue by lansingthomas** [atlas-engineer/nyxt#2651]
### this gear icon confuses me
![image](https://user-images.githubusercontent.com/6666079/202542515-89bd4dbc-e7c7-49cb-8dc9-6ec906391c4b.png)

#### This icon is far too similar to "Settings" across many platforms.
- perhaps an icon/badge would be better
- perhaps the NYXT tile (the tile may have too many letters for good continuity  with the other badges here)
- perhaps an icon with Nyx goddess of night imagery

### Image for context
![image](https://user-images.githubusercontent.com/6666079/202543474-cc1cffc4-d228-425f-83f9-0a53f298b4fe.png)

### to do
- [ ] inform tom if any assets exist for this, or you have ideas about it.
- [ ] inform tom if there are blockers preventing a new icon here.

**Comment by aadcg** [comment]
This is the same as #2647. Let's discuss it in that issue.
