### ISSUE TITLE
Implement gi-gtk renderer

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#2659]
Should not be hard, it's mostly a matter of porting `gtk.lisp` to `gi-gtk.lisp`.

Would obsolete #1251 for good.

Could fix the CCL binary problem in #1057.

It may also significantly reduce the Nyxt executable size.

**Comment by Ambrevar** [comment]
CC @aadcg

**Comment by jmercouris** [comment]
I don't think this is important anymore. I would rather spend more time on the Electron port.
