### ISSUE TITLE
`history-restoration` tests fails 

### ISSUE THREAD

**Issue by aadcg** [atlas-engineer/nyxt#2663]
Defined in `/tests/offline/global-history.lisp`.

Could someone that knows how we manage history fix it?  

Run this single test  `(with-summary () (run-test 'history-restoration))` from the REPL with `*package*` set to `nyxt/test`.

**Comment by Ambrevar** [comment]
It's the weirdest thing: I can not always reproduce.  When it fails, it's because `nyxt:*global-profile*` is set to `test-profile`, and thus the file expands to #p"", so of course there is no history.

But we never set `nyxt:*global-profile*` globally in the tests, so how is this possible at all?

**Comment by Ambrevar** [comment]
Oh, got it!  If you execute nyxt/tests/renderer, then `nyxt:*global-profile*` is indeed set to the test profile.  This is because of this snippet  in `start.lisp`:

```lisp
(when (getf *options* :profile)
    (alex:if-let ((profile-class (find-profile-class (getf *options* :profile))))
      (progn
        (setf *global-profile* (make-instance profile-class))
        (log:info "Profile: ~s" (profile-name profile-class)))
      (log:warn "Profile not found: ~s" (getf *options* :profile))))
```

Ouch!

Will fix.

**Comment by aadcg** [comment]
Ah! That was an interesting one. Thank you @Ambrevar!!

**Comment by Ambrevar** [comment]
Done in #2666.
