### ISSUE TITLE
Sample AppArmor / SELinux Profiles

### ISSUE THREAD

**Issue by hendursaga** [atlas-engineer/nyxt#2664]
For now, if I want some sort of containerization or sandboxing, I'd use Guix containers and/or a VM, but it would be nice to use [AppArmor](https://apparmor.net/) as a lightweight solution. I can't remember what software tools I encountered that had AppArmor profiles included inside their repositories, but there's an [official collection of profiles](https://gitlab.com/apparmor/apparmor-profiles) for inspiration, at any rate.

[SELinux](https://github.com/SELinuxProject/selinux) is much more complex, so I'm not sure about that, however.

**Comment by bubbleguuum** [comment]
An AppArmor profile would be great, as it is used on openSUSE, for which I hope to submit nyxt as an official package at some point when v3 is released.

**Comment by aadcg** [comment]
Feel free to share these profiles and consider contributing them to the project.

It's not a priority at the moment.
