### ISSUE TITLE
Can't build current Nyxt on WSL2/Ubuntu

### ISSUE THREAD

**Issue by hajovonta** [atlas-engineer/nyxt#2667]
**Describe the bug**
After fetching/rebasing the source repo, trying sudo make all.
The following message appears:

```log
SLYNK's ASDF loader finished./home/user/nyxt/nyxt: Is a directory
(sbcl:3078): GLib-GObject-WARNING **: 10:43:23.875: cannot register existing type 'GtkWidget'
(sbcl:3078): GLib-GObject-WARNING **: 10:43:23.877: cannot add class private field to invalid type '<invalid>'
(sbcl:3078): GLib-GObject-WARNING **: 10:43:23.877: cannot add private field to invalid (non-instantiatable) type '<invalid>'
(sbcl:3078): GLib-GObject-WARNING **: 10:43:23.877: cannot register existing type 'AtkImplementorIface'
(sbcl:3078): GLib-GObject-CRITICAL **: 10:43:23.877: g_type_add_interface_static: assertion 'G_TYPE_IS_INSTANTIATABLE (instance_type)' failed

(sbcl:3078): GLib-GObject-CRITICAL **: 10:43:23.877: g_type_add_interface_static: assertion 'G_TYPE_IS_INSTANTIATABLE (instance_type)' failed

(sbcl:3078): GLib-GObject-WARNING **: 10:43:23.879: cannot register existing type 'GtkWidget'
(sbcl:3078): GLib-GObject-WARNING **: 10:43:23.879: cannot add class private field to invalid type '<invalid>'
(sbcl:3078): GLib-GObject-WARNING **: 10:43:23.879: cannot add private field to invalid (non-instantiatable) type '<invalid>'
(sbcl:3078): GLib-GObject-WARNING **: 10:43:23.879: cannot register existing type 'AtkImplementorIface'
(sbcl:3078): GLib-GObject-CRITICAL **: 10:43:23.879: g_type_add_interface_static: assertion 'G_TYPE_IS_INSTANTIATABLE (instance_type)' failed

(sbcl:3078): GLib-GObject-CRITICAL **: 10:43:23.879: g_type_add_interface_static: assertion 'G_TYPE_IS_INSTANTIATABLE (instance_type)' failed
WARNING:
   Declared GType name 'GtkWidget' for class 'GTK-WIDGET' is invalid ('gtk_widget_get_type' returned 0)
Unhandled SIMPLE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING
                                    {10010B8003}>:
  Problem running initialization hook GLIB::RUN-INITIALIZERS:
  The value
    NIL
  is not of type
    GOBJECT:GTYPE

Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {10010B8003}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<SIMPLE-ERROR "Problem running ~A hook ~S:~%  ~A" {100135B5D3}> #<unused argument> :QUIT T)
1: (SB-DEBUG::RUN-HOOK *INVOKE-DEBUGGER-HOOK* #<SIMPLE-ERROR "Problem running ~A hook ~S:~%  ~A" {100135B5D3}>)
2: (INVOKE-DEBUGGER #<SIMPLE-ERROR "Problem running ~A hook ~S:~%  ~A" {100135B5D3}>)
3: (ERROR #<SIMPLE-ERROR "Problem running ~A hook ~S:~%  ~A" {100135B5D3}>)
4: (SB-KERNEL:WITH-SIMPLE-CONDITION-RESTARTS ERROR NIL "Problem running ~A hook ~S:~%  ~A" "initialization" GLIB::RUN-INITIALIZERS #<TYPE-ERROR expected-type: GOBJECT:GTYPE datum: NIL>)
5: (SB-INT:CALL-HOOKS "initialization" (LOG4CL-IMPL::INIT-HOOK GLIB::RUN-INITIALIZERS) :ON-ERROR :ERROR)
6: (SB-IMPL::REINIT NIL)
7: (SAVE-LISP-AND-DIE #P"/home/user/nyxt/nyxt" :TOPLEVEL #<FUNCTION UIOP/IMAGE:RESTORE-IMAGE> :EXECUTABLE T :SAVE-RUNTIME-OPTIONS T :CALLABLE-EXPORTS NIL :PURIFY T :ROOT-STRUCTURES NIL :ENVIRONMENT-NAME #<unused argument> :COMPRESSION NIL)
8: ((SB-PCL::EMF ASDF/ACTION:PERFORM) #<unused argument> #<unused argument> #<ASDF/BUNDLE:PROGRAM-OP > #<NYXT-ASDF:NYXT-SYSTEM "nyxt/gi-gtk-application">)
9: ((LAMBDA NIL :IN ASDF/ACTION:CALL-WHILE-VISITING-ACTION))
10: ((:METHOD ASDF/ACTION:PERFORM-WITH-RESTARTS :AROUND (T T)) #<ASDF/BUNDLE:PROGRAM-OP > #<NYXT-ASDF:NYXT-SYSTEM "nyxt/gi-gtk-application">) [fast-method]
11: ((:METHOD ASDF/PLAN:PERFORM-PLAN (T)) #<ASDF/PLAN:SEQUENTIAL-PLAN {10205C6273}>) [fast-method]
12: ((FLET SB-C::WITH-IT :IN SB-C::%WITH-COMPILATION-UNIT))
13: ((:METHOD ASDF/PLAN:PERFORM-PLAN :AROUND (T)) #<ASDF/PLAN:SEQUENTIAL-PLAN {10205C6273}>) [fast-method]
14: ((:METHOD ASDF/OPERATE:OPERATE (ASDF/OPERATION:OPERATION ASDF/COMPONENT:COMPONENT)) #<ASDF/OPERATE:BUILD-OP > #<NYXT-ASDF:NYXT-SYSTEM "nyxt/gi-gtk-application"> :PLAN-CLASS NIL :PLAN-OPTIONS NIL) [fast-method]
15: ((SB-PCL::EMF ASDF/OPERATE:OPERATE) #<unused argument> #<unused argument> #<ASDF/OPERATE:BUILD-OP > #<NYXT-ASDF:NYXT-SYSTEM "nyxt/gi-gtk-application">)
16: ((LAMBDA NIL :IN ASDF/OPERATE:OPERATE))
17: ((:METHOD ASDF/OPERATE:OPERATE :AROUND (T T)) #<ASDF/OPERATE:BUILD-OP > #<NYXT-ASDF:NYXT-SYSTEM "nyxt/gi-gtk-application">) [fast-method]
18: ((SB-PCL::EMF ASDF/OPERATE:OPERATE) #<unused argument> #<unused argument> ASDF/OPERATE:BUILD-OP :NYXT/GI-GTK-APPLICATION)
19: ((LAMBDA NIL :IN ASDF/OPERATE:OPERATE))
20: ((:METHOD ASDF/OPERATE:OPERATE :AROUND (T T)) ASDF/OPERATE:BUILD-OP :NYXT/GI-GTK-APPLICATION) [fast-method]
21: (ASDF/SESSION:CALL-WITH-ASDF-SESSION #<FUNCTION (LAMBDA NIL :IN ASDF/OPERATE:OPERATE) {102052850B}> :OVERRIDE T :KEY NIL :OVERRIDE-CACHE T :OVERRIDE-FORCING NIL)
22: ((LAMBDA NIL :IN ASDF/OPERATE:OPERATE))
23: (ASDF/SESSION:CALL-WITH-ASDF-SESSION #<FUNCTION (LAMBDA NIL :IN ASDF/OPERATE:OPERATE) {102047AA2B}> :OVERRIDE NIL :KEY NIL :OVERRIDE-CACHE NIL :OVERRIDE-FORCING NIL)
24: ((:METHOD ASDF/OPERATE:OPERATE :AROUND (T T)) ASDF/OPERATE:BUILD-OP :NYXT/GI-GTK-APPLICATION) [fast-method]
25: (ASDF/OPERATE:MAKE :NYXT/GI-GTK-APPLICATION)
26: (SB-INT:SIMPLE-EVAL-IN-LEXENV (ASDF/OPERATE:MAKE :NYXT/GI-GTK-APPLICATION) #<NULL-LEXENV>)
27: (EVAL (ASDF/OPERATE:MAKE :NYXT/GI-GTK-APPLICATION))
28: (SB-IMPL::PROCESS-EVAL/LOAD-OPTIONS ((:EVAL . "(require \"asdf\")") (:EVAL . #<(SIMPLE-ARRAY CHARACTER (298)) (when (string= "true" "true") (setf asdf:*default-source-registries* (list (quote asdf/source-registry:environment-source-registry))) (asdf:clear-configuration) (asdf:load-asd "/home/user/nyxt//ny... {1005DBC7EF}>) (:EVAL . "(asdf:load-asd \"/home/user/nyxt//nyxt-asdf.asd\")") (:EVAL . "(asdf:load-asd \"/home/user/nyxt//nyxt.asd\")") (:EVAL . "(when (find-package :ql) (funcall (read-from-string \"ql:quickload\") :cffi))") (:EVAL . #<(SIMPLE-ARRAY CHARACTER (235)) (when (and (find-package :cffi) (uiop:getenv "GUIX_ENVIRONMENT")) (pushnew (pathname (format nil "~a/lib/" (uiop:getenv "GUIX_ENVIRONMENT"))) (symbol-value (read-from-string "cffi:*foreign-library-dir... {1005DBCF9F}>) (:EVAL . "(asdf:load-system :nyxt/gi-gtk-application)") (:EVAL . "(asdf:make :nyxt/gi-gtk-application)") (:EVAL . "(uiop:quit)") (:QUIT)))
29: (SB-IMPL::TOPLEVEL-INIT)
30: ((FLET SB-UNIX::BODY :IN SB-IMPL::START-LISP))
31: ((FLET "WITHOUT-INTERRUPTS-BODY-3" :IN SB-IMPL::START-LISP))
32: (SB-IMPL::%START-LISP)

unhandled condition in --disable-debugger mode, quitting
; 
; compilation unit aborted
;   caught 1 fatal ERROR condition

Compilation failed, see the above stacktrace.

make: *** [makefile:42: nyxt] Error 1
```

**Information**
- OS name+version: 
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
- Graphics card and driver:
- Desktop environment / Window manager name+version: Windows Subsystem for Linux 2
- How you installed Nyxt (Guix pack, package manager, build from source): built from source
- Information from `show-system-information`:
Nyxt version: 3-pre-release-2-222-g5f4bb11b
Renderer version: GI-GTK
Operating system kernel: Linux 5.10.60.1-microsoft-standard-WSL2
Lisp implementation: SBCL 2.2.10.27-f2216e71a (Dynamic space size: 3221225472)
Features: (:NYXT-GI-GTK :NYXT-GTK :WEBKIT2 :WEBKIT2-2.36 :WEBKIT2-CORS-ALLOWLIST
 :WEBKIT2-PASTE-PLAINTEXT :WEBKIT2-TRACKING :WEBKIT2-MUTE :WEBKIT2-EMOJI
 :WEBKIT2-MEDIA :WEBKIT2-SANDBOXING :GTK-3-22 :GTK-3-20 :GTK-3-18 :GTK-3-16
 :GTK-3-14 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6 :GTK-3-4 :GTK :GDK-3-22
 :GDK-3-20 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12 :GDK-3-10 :GDK-3-8 :GDK-3-6
 :GDK-3-4 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF :GLIB-2-30 :GLIB-2-32 :GLIB-2-34
 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42 :GLIB-2-44 :GLIB-2-46 :GLIB-2-48
 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56 :GLIB-2-58 :GLIB :NYXT-3.1 :NYXT-3
 :NYXT-3-PRE-RELEASE-2 :NYXT-3-PRE-RELEASE-2-222-G5F4BB11B
 :CUSTOM-HASH-TABLE-NATIVE :SLYNK :PLUMP-UTF-32 :PARENSCRIPT :FSET-EXT-STRINGS
 :GLOBAL-VARS :DECLARE-TYPES :SBCL+SAFE-STANDARD-READTABLE :NAMED-READTABLES
 :SWANK :LPARALLEL :21BIT-CHARS :CLOSER-MOP :CL-PPCRE-UNICODE :CL-UNICODE
 :CL-JSON-DOUBLE-FLOAT-IS-SUBSUMED :CL-JSON-SINGLE-FLOAT-IS-SUBSUMED :CL-PPCRE
 :CHUNGA :FLEXI-STREAMS :BORDEAUX-THREADS :LPARALLEL.WITH-CLTL2
 :LPARALLEL.WITH-CAS :LPARALLEL.WITH-STEALING-SCHEDULER :SPLIT-SEQUENCE
 CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64 CFFI-FEATURES:UNIX :CFFI
 CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP :FAST-IO-SV :FAST-IO
 :CL-JSON-CLOS :CL-JSON :SBCL-USES-SB-ROTATE-BYTE CHIPZ-SYSTEM:GRAY-STREAMS
 :THREAD-SUPPORT :ASDF3.3 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX
 :NON-BASE-CHARS-EXIST-P :ASDF-UNICODE :X86-64 :GENCGC :64-BIT :ANSI-CL
 :COMMON-LISP :ELF :IEEE-FLOATING-POINT :LINUX :LITTLE-ENDIAN
 :PACKAGE-LOCAL-NICKNAMES :SB-LDB :SB-PACKAGE-LOCKS :SB-THREAD :SB-UNICODE
 :SBCL :UNIX)

ASDF version: 3.3.1
ASDF registries: (NYXT-SOURCE-REGISTRY ENVIRONMENT-SOURCE-REGISTRY)
Critical dependencies: (/home/user/nyxt/_build/cl-cffi-gtk/gtk/cl-cffi-gtk.asd
 /home/user/nyxt/_build/cl-gobject-introspection/cl-gobject-introspection.asd
 /home/user/nyxt/_build/cl-webkit/webkit2/cl-webkit2.asd)

**Comment by hajovonta** [comment]
I'm not familiar with it. Can you point me to some tutorial?

**Comment by aartaka** [comment]
> I'm not familiar with it. Can you point me to some tutorial?

Installing Guix is https://guix.gnu.org/en/manual/en/guix.html#Installation.
After it installs successfully, it's a matter of doing either 
- `guix install nyxt` to install a stable version of Nyxt, or
- `guix package -f /path/to/nyxt/checkout/build-scripts/nyxt.scm` for the checked-out version.

**Comment by hajovonta** [comment]
Ok I installed guix. But when trying to install Nyxt, I get this:

```
hint: Consider installing the `glibc-utf8-locales' or `glibc-locales' package and
defining `GUIX_LOCPATH', along these lines:

     guix install glibc-utf8-locales
     export GUIX_LOCPATH="$HOME/.guix-profile/lib/locale"

See the "Application Setup" section in the manual, for more info.

guix install: error: failed to connect to `/var/guix/daemon-socket/socket': No such file or directory
```

**Comment by hajovonta** [comment]
And it seems I have no guix-daemon:

1124 19:26:57 /var/guix λ guix-daemon
guix-daemon: command not found

**Comment by aadcg** [comment]
If you were on any GNU/Linux distribution you could install Guix as an additional package manager.  That may not be possible because you're on WSL2.

Instead, I suggest following these [instructions](https://gist.github.com/giuliano108/49ec5bd0a9339db98535bc793ceb5ab4).

**Comment by hendursaga** [comment]
@hajovonta as a side-note, is there a particular reason you use `sudo make install`?

**Comment by hajovonta** [comment]
I struggled with Guix a bit, but haven't got the time and knowledge to overcome the obstacles.
For now, I accept that Nyxt doesn't build on WSL.

**Comment by aadcg** [comment]
@hajovonta note that there are [reports of success running Nyxt in WSL following a different approach](https://discourse.atlas.engineer/t/nyxt-on-windows-10-with-wslg/120).

**Comment by aadcg** [comment]
Stale. See https://github.com/atlas-engineer/nyxt/issues/1086#issuecomment-1566230012.
