### ISSUE TITLE
Fix CI issue with CCL

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#2672]
Turns out that Roswell started to getting confused about which version of CCL to install, trying to install version 1.8 and thus failing.

It's been reported upstream:

https://github.com/roswell/roswell/issues/534

**Comment by Ambrevar** [comment]
Easy workaround:  LISP=ccl-bin/1.12.1

We should do this.  At a later point, I'm wondering if we shouldn't ditch Roswell altogether and stick to Guix only.

Drawbacks:
- Using Roswell gets us a wider range of compiler sources and thus may report issues than we would see if all of us just used Guix / Nix.
- Guix is a bit slower to set up in the CI than Roswell, but this might be alleviated with the right use of CI cache.  This needs some work.

**Comment by CorruptedVor** [comment]
I'd say it's a good idea to keep the CI diverser, just for the occasional bug you find thanks to that. OpenBSD (OS project) does it all the time with obscure platforms to find kernel bugs.

**Comment by aadcg** [comment]
> I'd say it's a good idea to keep the CI diverser, just for the occasional bug you find thanks to that.

@Ambrevar didn't suggest stop testing on some CL implementations. Rather, he suggests that Guix alone can be used to manage all of it (thus ditching Roswell).

**Comment by CorruptedVor** [comment]
Alright then, my interactions with Roswell have been pretty bad, not against it in that case.

**Comment by Ambrevar** [comment]
Workaround is in with e68ce991ab02cf4fe1826240c475e91f1a60ad36.
Closing.

**Comment by aadcg** [comment]
I don't think this is fixed, since the CI still hangs for CCL.

**Comment by aartaka** [comment]
@aadcg, where exactly? It seems to pass for most commits. The hangs are likely the ones with race conditions in tests, which is not a recent problem at all.

**Comment by aadcg** [comment]
Oh, you know what? I'm an idiot. I was probably pushing commits to a remote branch where e68ce99 was still unfetched. Sorry!
