### ISSUE TITLE
Handling of global variables in a multi threaded context; `*headless*`

### ISSUE THREAD

**Issue by aadcg** [atlas-engineer/nyxt#2692]
Handling global variables is always cumbersome, but throwing multi threading into the mix is the perfect cocktail for disaster.

The concrete case of `*headless*` is a good example (though multi threading doesn't play any role in this case).

```lisp
CL-USER> (asdf:load-system "nyxt/gi-gtk")
CL-USER> (nyxt:start :headless t)
CL-USER> (nyxt:quit)
CL-USER> (nyxt:start) 
;; Nyxt starts in headless mode since *headless* has been set to T in the first start.
```

**Comment by aartaka** [comment]
We do use some globals, and most of the use of those really are cases where globals are inevitable. I'm not denying those are quirky, but at this point we can do nothing but being careful with those :)

In this particular case, it's our handling of `*headless-p*` that is incomplete. I'll fix it.

**Comment by aartaka** [comment]
See 726c339deb9c3c5e5df87c037fc099160f090b0f for a deeper solution to the multithreaded variable binding. I doubt we can go much further than that.

**Comment by aartaka** [comment]
> Could someone give an example of a situation where `*interactive-p*` is nil and `*headless-p*` is true, and vice versa?

Calling a command from anywhere by `execute-command` menu or `run` function, while in headless mode.

**Comment by aartaka** [comment]
The reversed example could be calling a command from `execute-command`/`run` while in graphical Nyxt.

**Comment by aadcg** [comment]
Your examples are true with respect to our codebase but I'm not satisfied with the answers.

`*interactive-p*`, although it can be used more generically, basically means `enable-prompt-buffer-p`.

Let me ask it in another way. Say you have Nyxt running as usual (`*headless*` set to `nil`). Can you mention a situation where you'd like to avoid invoking the prompt buffer?

**Comment by aadcg** [comment]
Another thing that looks fishy is the fact that `*headless*` is `nil` by default (makes sense), but `*interactive-p*` is also `nil` by default. 

However, `*intereactive-p*` is let-binded as `t` and never as `nil`. Notice that the condition `prompt-buffer-non-interactive` is raised when `*interactive-p*` is nil.

Conclusion, `*interactive-p*` should be `t` by default in my understanding.

**Comment by aartaka** [comment]
> Why do we let-bind `nyxt::*interactive-p*` in `enable` at `source/mode/repeat.lisp` and other places?

Because mode enablement/disablement is supposed to be interactive. And because it's a hack against an incomplete `*interactive-p*` infrastructure.

**Comment by aadcg** [comment]
> Because mode enablement/disablement is supposed to be interactive. 

Why is it interactive? Even when enabling a mode invokes `prompt`, there are ways to return from that on headless sessions. So toggling a mode can be used in both graphical and non-graphical version.

> And because it's a hack against an incomplete *interactive-p* infrastructure.

I don't understand what problem(s) the hack solves, since as I've noted above I don't see any problem at all.
