### ISSUE TITLE
Open link in new buffer - in background

### ISSUE THREAD

**Issue by fictitiousexistence** [atlas-engineer/nyxt#2700]
**Is your feature request related to a problem? Please describe.**
Cannot open link in new buffer (tab) in the background. 

**Describe the solution you'd like**
Hold down Ctrl and click a link to open it in a new background buffer. 
Works in most other browsers. 

**Additional context**
I stopped using nyxt for awhile but at the start of the year when I was using it I recall being able to click open a link in a buffer that was not focused. 

I cannot recall whether it was ctrl+click or ctrl+shift+click or shift+click but none of the combinations seem to work now. 

I often need to open several links on a page. Usually I just ctrl+click through all of them to open in the background. 

Thanks!

**Comment by hendursaga** [comment]
I believe you're looking for the `follow-hint-new-buffer` command. Now, as to whatever shortcut you think you've used in the past - I'm not sure. I tend to use the keyboard over the mouse when in Nyxt. As a workaround, you could perhaps bind `switch-buffer-last` (I use `C-~` personally) to quickly go back to your original page.

**Comment by aartaka** [comment]
Hmmmm, and Ctrl+scroll does not work for zooming either. Something extremely fishy is going on...

**Comment by fictitiousexistence** [comment]
@aartaka 
I tested in 2.4.4 and it was "ctrl+shift+ click" that opened the link in a background buffer (or whatever the lingo is). 

Although, all other browsers I've used use ctrl+click.

**Comment by Ambrevar** [comment]
It's `Ctrl-click` for me.  Maybe there is an Xorg / Wayland issue.

@fictitiousexistence Do you use Wayland or Xorg?

**Comment by fictitiousexistence** [comment]
@Ambrevar I use just wayland without xwayland.

**Comment by fictitiousexistence** [comment]
@Ambrevar 
If I run "nyxt -CI" I am able to use ctrl+shift+click to open the link in a new unfocused buffer. If I do ctrl click, it opens in a new buffer that's focused.

If I enable either emacs or vi mode then ctrl+shift+click no longer works. It just opens the link, no new buffer at all.

**Comment by Ambrevar** [comment]
It's a Wayland issue.  @aartaka @aadcg Does anyone use Wayland around here?

**Comment by aadcg** [comment]
No. But I can setup an environment running sway if that helps.

**Comment by aartaka** [comment]
No wait, it's not a Wayland issue. I can reproduce it on X: CUA mode has `ctrl+click`, while Emacs mode somewhy doesn't.

**Comment by aartaka** [comment]
See 7cdcc8270f98e8b33bbeb38cc6e68935758f0e64 for the fix and 799e5813011b37452306ac6c5f1242ba4f6ed30b for more familiar mouse actions.
