### ISSUE TITLE
Ditch `cl-custom-hash-table` in `htree`

### ISSUE THREAD

**Issue by aartaka** [atlas-engineer/nyxt#2704]
A follow-up to a conversation with @Ambrevar: it may be beneficial to remove the dependency on `cl-custom-hash-table` from `htree`, because it's
- not bringing much of a performance benefit,
- is somewhat more complex to reason about than the built-in structure.

Alternatives we have are:
- lists, because there's a huge set modelling library (`union`, `find`, `set-difference` etc.) built into CL and lists are terribly optimized until they hit some 100K elements,
- or plain hash-tables, because they are good enough of set modelling too, and we can still try to search things in them without `cl-custom-hash-table`,
- and maybe adjustable vectors with a linear search time and constant insertion time?

One problem with using a different structure is that it will break history serialization, so we'd have to do some more special cases when restoring old histories.

**Comment by aadcg** [comment]
I think it's always a good idea to use lists for prototyping. Using something else beforehand might be premature optimization. So, even if the final implementation will not rely on lists, I believe it would be a nice starting point.

**Comment by Ambrevar** [comment]
Closing in favor of https://github.com/atlas-engineer/history-tree/issues/1 ?

**Comment by aartaka** [comment]
Yes!
