### ISSUE TITLE
URL/Status bars are unreadably narrow

### ISSUE THREAD

**Issue by parszab** [atlas-engineer/nyxt#2711]
**Describe the bug**

The` read URL and Status bars are too narrow to read.

**Precise recipe to reproduce the issue**
I just installed the community version on Arch and started it. 

**Information**
- OS name+version: Arch linux updated.
- Graphics card and driver: VGA compatible controller: Intel Corporation Crystal Well Integrated Graphics Controller
- Desktop environment / Window manager name+version: FVWM
- How you installed Nyxt (Guix pack, package manager, build from source): Arch pacman
- Information from `show-system-information`:

System information

Nyxt version: 2.2.4
Renderer version: GI-GTK
Operating system kernel: Linux 6.0.11-arch1-1
Lisp implementation: SBCL 2.2.9 (Dynamic space size: 3221225472)
Features: (:WEBKIT2 :WEBKIT2-2.38 :WEBKIT2-PASTE-PLAINTEXT :WEBKIT2-TRACKING
 :WEBKIT2-MUTE :WEBKIT2-EMOJI :WEBKIT2-MEDIA :WEBKIT2-SANDBOXING :GTK-3-22
 :GTK-3-20 :GTK-3-18 :GTK-3-16 :GTK-3-14 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6
 :GTK-3-4 :GTK :GDK-3-22 :GDK-3-20 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12
 :GDK-3-10 :GDK-3-8 :GDK-3-6 :GDK-3-4 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF
 :GLIB-2-30 :GLIB-2-32 :GLIB-2-34 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42
 :GLIB-2-44 :GLIB-2-46 :GLIB-2-48 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56
 :GLIB-2-58 :GLIB :NYXT-2 :FSET-EXT-STRINGS :CUSTOM-HASH-TABLE-NATIVE :SWANK
 :PLUMP-UTF-32 :GLOBAL-VARS :DECLARE-TYPES :PARENSCRIPT
 :SBCL+SAFE-STANDARD-READTABLE :NAMED-READTABLES :LPARALLEL :21BIT-CHARS
 :CHUNGA :CLOSER-MOP :CL-PPCRE-UNICODE :FLEXI-STREAMS :CL-UNICODE :CL-PPCRE
 :CL-JSON-DOUBLE-FLOAT-IS-SUBSUMED :CL-JSON-SINGLE-FLOAT-IS-SUBSUMED
 :BORDEAUX-THREADS :LPARALLEL.WITH-CLTL2 :LPARALLEL.WITH-CAS
 :LPARALLEL.WITH-STEALING-SCHEDULER :SPLIT-SEQUENCE CHIPZ-SYSTEM:GRAY-STREAMS
 CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64 CFFI-FEATURES:UNIX :CFFI
 CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP :FAST-IO-SV :FAST-IO
 :SBCL-USES-SB-ROTATE-BYTE :CL-JSON-CLOS :CL-JSON :THREAD-SUPPORT :ASDF3.3
 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX :NON-BASE-CHARS-EXIST-P
 :ASDF-UNICODE :X86-64 :GENCGC :64-BIT :ANSI-CL :COMMON-LISP :ELF
 :IEEE-FLOATING-POINT :LINUX :LITTLE-ENDIAN :PACKAGE-LOCAL-NICKNAMES
 :SB-CORE-COMPRESSION :SB-LDB :SB-PACKAGE-LOCKS :SB-THREAD :SB-UNICODE :SBCL
 :UNIX)

ASDF version: 3.3.1
ASDF registries: (NYXT-SOURCE-REGISTRY ENVIRONMENT-SOURCE-REGISTRY)
Critical dependencies: (/build/nyxt/src/nyxt/_build/cl-cffi-gtk/gtk/cl-cffi-gtk.asd
 /build/nyxt/src/nyxt/_build/cl-gobject-introspection/cl-gobject-introspection.asd
 /build/nyxt/src/nyxt/_build/cl-webkit/webkit2/cl-webkit2.asd)

  If you can't run `show-system-information`, try `nyxt --system-information` from
  a shell.  It this still does not work, please provide the following:
  - Nyxt version (from the `nyxt-version` command or `nyxt --version` from a shell):
  - Lisp implementation/version (if built from source):
  - Kernel name+version:
  - WebKitGTK+ | QtWebEngine version:

**Output when started from a shell**
szabolcs@dax ~ > nyxt          
<INFO> [15:13:50] Listening to socket "/run/user/1000/nyxt/nyxt.socket".
Nyxt version 2.2.4
<INFO> [15:13:53] Deleting socket "/run/user/1000/nyxt/nyxt.socket".

![nyxt](https://user-images.githubusercontent.com/15095671/208445344-76a789f7-721e-493e-9a1d-cf42a98bb1a2.png)

**Comment by aartaka** [comment]
Try 
``` lisp
(define-configuration window
  ((message-buffer-height (* 2 %slot-default%))))
(define-configuration status-buffer
  ((height (* 2 %slot-default%))))
```
Also see the `Troubleshooting > Font size on HiDPI displays` part of the manual.

**Comment by gcentauri** [comment]
The config here worked, but left the "minibuffer" in a hard to use state. Following the GTK instructions on troubleshooting Font size on HiDPI displays solved the issue for me.

is there a recommended way to ensure nyxt starts this way each time? perhaps i should just wrap it in my own startup script?
