### ISSUE TITLE
Dangling `windows` when starting Nyxt from REPL multiple times

### ISSUE THREAD

**Issue by aadcg** [atlas-engineer/nyxt#2721]
Commit 30c91a5be (in the context of PR #2666) introduces a bug.

Steps to reproduce:

- `(asdf:load-system "nyxt/gi-gtk")`
- `(nyxt:start :failsafe t)`
- notice that a single Nyxt window exists
- `(nyxt:quit)`
- notice that no Nyxt windows exist
- `(nyxt:start :failsafe t)`
- notice that 2 Nyxt windows exist

@Ambrevar could you please fix it?

**Comment by aadcg** [comment]
Yes. Are you on EXWM? Are you double checking all of the existing EXWM buffers by calling `ibuffer` in Emacs?

**Comment by Ambrevar** [comment]
I could reproduce now, it seems that the bug does not always happen, there is a race condition.

**Comment by aadcg** [comment]
@aartaka can you reproduce this bug?

**Comment by Ambrevar** [comment]
Could you investigate?  Hard for me to reproduce, so it's probably a race condition and something to do with class update.

**Comment by aadcg** [comment]
After a deeper investigation, this seems related to a WebKitGTK quirk.
