### ISSUE TITLE
vi insert not always getting activated on forms

### ISSUE THREAD

**Issue by r3k2** [atlas-engineer/nyxt#2727]
**Describe the bug**
Many times I select a form entry like login/pass or search bar and nyxt is not on insert so screws up my writing since r and o and other special keys will get triggered and screw up my page or behaving in a way not intended, and I have to manually go into command mode ":" and type "vi-insert.." and enter to be able to finally type correctly

**Precise recipe to reproduce the issue**
Happens more than not, rarely it does what is supposed I will tab, mouse there or  use f to select the form and will auto trigger into vi-insert mode
but most times it does not :(
Screenshots attached with some examples a video will be better but...

OS: Arch GNU/Linux
Wayland/Sway
Nyxt latest nightly from git using AUR Arch.

more info in the nyxt forum: https://discourse.atlas.engineer/t/vim-mode-form-issues/592

[edit] The screenshots did not upload here in order but you  get the idea.
[edit2] Just notice someone posted a similar bug report https://github.com/atlas-engineer/nyxt/issues/2701 sorry

![swappy-20221226-042436](https://user-images.githubusercontent.com/5316229/209616908-82ddbaa6-5c1f-4475-afab-59ec2a983465.png)
![swappy-20221226-042234](https://user-images.githubusercontent.com/5316229/209617000-9183e8cd-8fa5-4c4b-8c41-c8a5f1f60173.png)
![swappy-20221226-001402](https://user-images.githubusercontent.com/5316229/209617026-915b8bf2-ea55-4904-a5c6-d7539fe81b97.png)
![swappy-20221226-042356](https://user-images.githubusercontent.com/5316229/209617057-9ac5b49f-763a-4aaf-8418-eb0246c1c383.png)

**Comment by aadcg** [comment]
CC @Ambrevar.

**Comment by aartaka** [comment]
What we certainly don't handle is keyboard events that lead to form getting focused, yes. Not sure WebKit will ever allow us to reliably track this form association/focus, though...

**Comment by Ambrevar** [comment]
Our form detection is clumsy at best, which is probably why @r3k2 is hitting this issue.

We'd need proper renderer support but like @aartaka mentioned I'm not aware of a WebKit API for this.

**Comment by r3k2** [comment]
Hello @aartaka @Ambrevar is there a workaround? I had moved to use nyxt full time but this issue is getting on my nervs, like many  time I am in a hurry to post something on mastodon or a comment on a peertube video to start getting commands run as I type the characters because is not on insert mode, then I have to ESC and go into command mode and force the insert mode as you can imagen this can get teddious after a while and specially when I forget and slows me down, if this is a issue with the web engine, is a big issue for vim users is there a work around I can use? I think qutebrowser uses qt webengine and that is working for years now just fine.

**Comment by fictitiousexistence** [comment]
Luakit uses webkitgtk as well and I haven't ran into the issue there yet. All forms / input fields get triggered.

**Comment by r3k2** [comment]
@aadcg @aartaka Hello Thank you! I just installed todays git master and even do better is still failing in a lot of places, example in protonmail I try to compose a new msg and I get a pop up and is not working I was trying and it screw my email since it closed the window since is not on insert mode and not all characters can be typed :( also happened in odysee and lemmy :(

**Comment by fictitiousexistence** [comment]
@r3k2 Protonmail seems to work for me. If I open a new message and click in any of the fields it goes to vi insert. If I accidentally am out of insert mode and type D, protonmail prompts to leave or not.

**Comment by r3k2** [comment]
Hello sorry, was out, not for me, only a few, here is one from lemmy.ml currently that got me pissed off and had to open qutebrowser to actually finish login in.
![swappy-20230201-205412](https://user-images.githubusercontent.com/5316229/216149712-a26f91ca-e617-4743-b37e-2c4d273d83c1.png)
Protonmail I have try up to today latest git from the arch aur does not work for me at all.

**Comment by aartaka** [comment]
> Hello sorry, was out, not for me, only a few, here is one from lemmy.ml currently that got me pissed off and had to open qutebrowser to actually finish login in.

Wait, what does it mean that it does not work? Does it not switch to insert? Does it not switch back to normal/command mode when pretting ESC? What are your expectations here?

I'm not much of a VI modes user, that's why I'm asking. Clicking on the input field properly switches to insert-mode for me, much like doing `follow-hint` does. Looks like a properly working thing for me on 185b5921c5687a14663904f6e954b3dd681312cd...

**Comment by r3k2** [comment]
@aartaka please excuse my delayed response, job nowadays requires me to travel too much, it does work, just for some reason, not all places, I notice this last days is working great on mastodon, here(GitHub) etc. but then when I tried on lemmy or other sites it did not, not even when moving the mouse (that I try to avoid at all cause lol) I try using "f" and selecting the letter to select the box, and it does not change to I (Insert mode) then I try with the mouse, same result. But is not always, maybe the Arch AUR is not updated? Is supposed to be from git master, in any case I am as we talk updating and will test again and report back in a couple of days. AND THANK YOU really for helping with all this, when I write here is not really to complain, is to actually make it work nicely so we VI users can enjoy this great project.

**Comment by aartaka** [comment]
> @aartaka please excuse my delayed response, job nowadays requires me to travel too much, 

No problem :)

> it does work, just for some reason, not all places, I notice this last days is working great on mastodon, here(GitHub) etc. but then when I tried on lemmy or other sites it did not, not even when moving the mouse (that I try to avoid at all cause lol) I try using "f" and selecting the letter to select the box, and it does not change to I (Insert mode) then I try with the mouse, same result. 

That is terribly weird...

> But is not always, maybe the Arch AUR is not updated? Is supposed to be from git master, in any case I am as we talk updating and will test again and report back in a couple of days. 

Indeed, https://archlinux.org/packages/community/x86_64/nyxt/ lists version 2.2.4... Are you aware of https://e-v.srht.site/nyxt-aur-builds.html? It should be built from the freshest checkout.

> AND THANK YOU really for helping with all this, when I write here is not really to complain, is to actually make it work nicely so we VI users can enjoy this great project.

Thanks for this, you're helping a lot `( ˘ ³˘)❤`

**Comment by r3k2** [comment]
Hello I have been using it and is much better, but still have some issues here and there, I will take a screenshot next time it happens with website etc, so it helps, just wanted to update and say thank you, @aartaka  PS: yes I think that is the one in the arch AUR right? Oh, wait, that is a new repo not in sync with the one in AUR? I will give it a try

**Comment by aartaka** [comment]
> Hello I have been using it and is much better, but still have some issues here and there, I will take a screenshot next time it happens with website etc, so it helps, just wanted to update and say thank you, @aartaka 

Glad to help!

> PS: yes I think that is the one in the arch AUR right? Oh, wait, that is a new repo not in sync with the one in AUR? I will give it a try

I dunno, AURs are quite an unfamiliar thing to me, so I cannot give any insight on those ¯\\\_(ツ)_/¯

**Comment by r3k2** [comment]
ok,
![swappy-20230305-210446](https://user-images.githubusercontent.com/5316229/222983208-23e0802c-6cc2-462e-8c30-5258cb57fb3b.png)
 I just had the issue again trying to log in to a magazine I am subscribed to, I had to open qutebrowser to be able to log in without using copy/paste

**Comment by aadcg** [comment]
Stale.

**Comment by r3k2** [comment]
@aadcg this is not stale, I just can't use nyxt as a daily driver even I want to use it with all my heart, since VIM keys with no mouse 100% are unusable/broken, so been using qbitwarden that vim keys just work perfectly, today to test stable I re-installed and still can't type anything on forms, only hack I found is to go into "passthrought-mode" but then of course won't let me type they key combo to toggle out of it :( :cry:  I though if this at least worked I will not mind pressing a key combo to type on login/forms and then toggle back to VI mode but under passthrough-mode does just that and can't toggle away, so this is still an issue for VIM users, so is not stale, I just have to use a browser that works and can only come back to nyxt to test if something has changed once in a while.

**Comment by r3k2** [comment]
> @r3k2, hmmmm, that's weird, I cannot reproduce. Can you write out the full recipe, with keys/commands you use to get to the website and move around it?

just got to any mastodon instance with nyxt, try to login on vi mode 100% with no copy/paste if you manage to log in, "copy pasting from somewhere else, so you don't have to type" then try to post something on the toot entry, the "y" and "n" and other chars that are "taken" will not work without having to bypass opening command with ":" and running passthrough-mode, then you can type and post but when done, then no keybinds work whatsoever so no way for me to get into command mode again with ":" to toggle that back off, or with the keybinds that are set by default for it. :(

**Comment by r3k2** [comment]
This is still an issue, vi-insert-mode does not get toggle when on a login/form I just can't use nyxt as much as I will love to so been using qutebrowser since the vi keys work like a charm, I will love to switch, but I can't until I can 100% use my keyboard with vim keys all the time like I do with other browsers. This means I can't be reporting/testing all the time, only when I actually have some work spare time and remember about nyxt. Like I did to test the last release and still having the same issue, go to mastodon any instance or peertube etc and try to log in without copy/paste or using the mouse then posting something on mastodon vi-insert-mode does not work right

**Comment by fictitiousexistence** [comment]
@r3k2 

Can you try removing the default settings nyxt puts in the auto config, these are what the current default settings are:

(defmethod customize-instance ((input-buffer input-buffer) &key)
  (disable-modes* 'nyxt/mode/emacs:emacs-mode input-buffer)
  (enable-modes* 'nyxt/mode/vi:vi-normal-mode input-buffer))


And try putting this instead:

(define-configuration web-buffer
  ((default-modes
    (pushnew 'nyxt/mode/vi:vi-normal-mode %slot-value%))))


This has stopped the strange behaviour for me. 
Also, dunno if vi insert mode is helpful for you in the prompt buffer. For me its not so I disable it using, 

(defmethod customize-instance ((prompt-buffer prompt-buffer) &key)
  (disable-modes* 'nyxt/mode/emacs:emacs-mode prompt-buffer)
  (disable-modes* 'nyxt/mode/vi:vi-normal-mode prompt-buffer))



These settings have made nyxt function better for me. There are still some forms that don't activate when clicked though. That was part of another issue I think. 

Anyway, when I go to https://mastodon.social/auth/sign_in and either click in the form or hit 'i' I can type in my login without issue.

**Comment by r3k2** [comment]
@fictitiousexistence WOW! now is working, I am actually writing this from nyxt!!! <3   the question now resides in why does nyxt create a broken auto config? O_O @aartaka  maybe less hardheaded people like myself will just give up all together :(.
I can confirm I have go into our mastodon instance, I was able to log in and toot one post!!! <3.
[PD] a small issue I just notice I press f to hit "comment" button but the command window is so big it hides the letters I need to press to hit the "comment" button lol  anyways to move it to show up on the top/left/right side instead? thanks

**Comment by aartaka** [comment]
> @fictitiousexistence WOW! now is working, I am actually writing this from nyxt!!! <3 the question now resides in why does nyxt create a broken auto config? O_O @aartaka maybe less hardheaded people like myself will just give up all together :(.

Ohhhhhh, right. This configuration option definitely suffered from a bit rot 😢 I've updated it (and some other options too; although not all of them 😞) in e5c8920d2a1284ed0538ecc3738abcebcae77e51.

> [PD] a small issue I just notice I press f to hit "comment" button but the command window is so big it hides the letters I need to press to hit the "comment" button lol anyways to move it to show up on the top/left/right side instead? thanks

So here are two pre-configured ways to approach this problem:
- Use `:vi` hinting type in `hint-mode`:
``` lisp
(define-configuration :hint-mode
  "Collapses the prompt buffer to a single input area,
and auto-follows the hint once you type in its hint letters."
  ((hinting-type :vi)))
```
- Use the "other buffer" scrolling commands.
  - For Emacs scheme it's:
```
"C-M-n" 'scroll-other-buffer-down
"C-M-p" 'scroll-other-buffer-up
"C-M-v" 'scroll-page-down-other-buffer
"C-M-k" 'scroll-page-up-other-buffer
```
  - For VI normal it's
```
"M-j" 'scroll-other-buffer-down
"M-k" 'scroll-other-buffer-up
"C-M-j" 'scroll-page-down-other-buffer
"C-M-k" 'scroll-page-up-other-buffer
```

**Comment by fictitiousexistence** [comment]
@aadcg #3030
