### ISSUE TITLE
Navigate to URLs from `list-history` is broken

### ISSUE THREAD

**Issue by aadcg** [atlas-engineer/nyxt#2729]
Clicking on URLs from `list-history` doesn't work.

**Comment by aartaka** [comment]
Which commit/branch you're on? Are all the links not navigatable? Does it simply do nothing, or does it error/warn/crash/hang/evaporate your PC?

It seems to work just fine on my machine on 46e278d632323b65e8fc11efa5c2b6cfc6b6ab28 (◎_◎;)

**Comment by aadcg** [comment]
I'm not on the master branch, and I wrongly assumed that the changes on that other branch would not influence `list-history`. Sorry, will make sure to double check next time.

Thanks.
