### ISSUE TITLE
Ensure that Nyxt buils on aarch64 

### ISSUE THREAD

**Issue by aadcg** [atlas-engineer/nyxt#2739]
Just a remainder to make this check before the release.

From my side, I can only test on Termux.

**Comment by shaunsingh** [comment]
I've been using nyxt on aarch64-linux for the past few weeks just fine :+1:

**Comment by bubbleguuum** [comment]
You can also check this on my regular (every week or so) nyxt-git builds on Open Build Service for openSUSE as I recently added aarch64:

https://build.opensuse.org/package/show/home:bobbie424242/nyxt-git

**Comment by aadcg** [comment]
That's helpful @bubbleguuum, thanks!

**Comment by bubbleguuum** [comment]
On the page I linked, you can view the build logs by clicking on the `Succeeded` links (or `Failed` if it does not compile) in the `Build Results` panel on the right.

**Comment by aadcg** [comment]
Nyxt should build and run on aarch64. Please re-open if you find any problems.

**Comment by Arian-D** [comment]
Hey, I'm not able to build nyxt for aarch64.
![image](https://github.com/atlas-engineer/nyxt/assets/40076285/b7b3acda-925a-4eed-8f48-6a923b69bae6)

Any ideas on how to proceed?

**Comment by Arian-D** [comment]
Thank you for the quick response!

Building without `ccl` from master shows the following error:
```
Nyxt version 4
<INFO> [13:09:16] Source location: #P"/gnu/store/snwznbc14iyafxvi2idx5g8aby5wvkva-nyxt-3.0.0-533-ga4e10cb71/share/nyxt/"
<INFO> [13:09:16] Listening to socket: #P"/run/user/30034/nyxt/nyxt.socket"
CORRUPTION WARNING in SBCL pid 5293 tid 5308:
Memory fault at 0x10 (pc=0xffff474159e8)
The integrity of this image is possibly compromised.
Continuing with fingers crossed.
<WARN> [13:09:17] Warning: Error in FFI method: Unhandled memory fault at #x10.
```
and the upstream Guix package follows a similar pattern when I do `guix shell nyxt -- nyxt`:
```
Nyxt version 3.9.0
<INFO> [13:16:52] Source location: #P"/gnu/store/lmv1183hk04nb7n4d4lph682yfgfw846-nyxt-3.9.0/share/nyxt/"
<INFO> [13:16:53] Listening to socket: #P"/run/user/30034/nyxt/nyxt.socket"
CORRUPTION WARNING in SBCL pid 5444 tid 5459:
Memory fault at 0x10 (pc=0xffff394159e8)
The integrity of this image is possibly compromised.
Continuing with fingers crossed.
<WARN> [13:16:53] Warning: Error in FFI method: Unhandled memory fault at #x10.
<WARN> [13:16:53] Warning: Error on separate thread: There is no applicable method for the generic function
  #&lt;STANDARD-GENERIC-FUNCTION NYXT:ID (6)&gt;
when called with arguments
  (NIL).
See also:
  The ANSI Standard, Section 7.6.6
```

Any idea on why this is happening? This doesn't happen with the x86_64 Guix package or the aarch64 Manjaro package.

Also, let me know if I should report this issue elsewhere, since I can build on aarch64 (but not run it).
