### ISSUE TITLE
Use extensible fuzzy-matching everywhere

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#274]
Now that we have fuzzy-matching in the minibuffer, it'd be neat to have it everywhere.
Currently, we don't use it for SQLite data, e.g. when opening a new URL `history-typed-complete` is used.
The latter function has the benefit of sorting by visit frequency, which only makes sense in this context.

Currently, `fuzzy-match` sorts item sequentially.  I don't think it's the right way to do it, because with many sorting rules, it's non-obvious which one should have priority.  Instead, I suggest a scoring system.

Something along those lines: `fuzzy-match` takes a bunch of scoring functions as parameters which score the candidates, then we sort by the scores.

Thoughts?

**Comment by jmercouris** [comment]
Maybe, as we add more scoring functions we may have to begin thinking about how to make it lazily load the list and resort things, which may be jarring for the user depending on how fast it is.

A scoring system is an obvious choice if we want to sort based on multiple dimensions. Despite this, I think we are usually looking for one thing based on one aspect of it. E.G. find me all URLS with this regex pattern.

There is most definitely a use case for multi dimensional sorting. A good example is if we are looking for an item in history, sometimes we are interested in the URL and the date. In this case maybe a very lightweight query language would work, or a way to stack search dimensions. 

I think there is a lot of great things we can do with UX here, so some further investigation is most definitely merited.

**Comment by Ambrevar** [comment]
Update: Fuzzy-matching is now used everywhere and we use sequences of rules.  However, rules are still not extensible.

Suggestion: Move fuzzy-matching to a separate library, or include it in the minibuffer library.

**Comment by Ambrevar** [comment]
We can now customize the prompt-buffer `filter`, which allows the user to specify arbitrary rules for any prompt.
