### ISSUE TITLE
Nyxt crashes when trying to open youtube.

### ISSUE THREAD

**Issue by Mugworth** [atlas-engineer/nyxt#2749]
Just started trying out nyxt and i wanted to open youtube, i got this error after crashing to the last opened website:

![2023-01-19_21-27](https://user-images.githubusercontent.com/62995382/213552798-ae6c8154-95c4-47c4-b1bb-64464aedbf32.png)

For website-specific issues:
I cant reproduce it with epiphany

**Information**
- Linux Mint 21:
- rx 470
- i3wm version 4.22
- i installed it by tar, and just run it from its download path
- Nyxt version: 2.2.4
Renderer version: GI-GTK
Operating system kernel: Linux 5.15.0-58-generic
Lisp implementation: SBCL 2.1.9 (Dynamic space size: 3221225472)
Features: (:WEBKIT2 :WEBKIT2-2.34 :WEBKIT2-PASTE-PLAINTEXT :WEBKIT2-TRACKING
 :WEBKIT2-MUTE :WEBKIT2-EMOJI :WEBKIT2-MEDIA :WEBKIT2-SANDBOXING :GTK-3-22
 :GTK-3-20 :GTK-3-18 :GTK-3-16 :GTK-3-14 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6
 :GTK-3-4 :GTK :GDK-3-22 :GDK-3-20 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12
 :GDK-3-10 :GDK-3-8 :GDK-3-6 :GDK-3-4 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF
 :GLIB-2-30 :GLIB-2-32 :GLIB-2-34 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42
 :GLIB-2-44 :GLIB-2-46 :GLIB-2-48 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56
 :GLIB-2-58 :GLIB :NYXT-2 :FSET-EXT-STRINGS :CUSTOM-HASH-TABLE-NATIVE :SWANK
 :PLUMP-UTF-32 :GLOBAL-VARS :DECLARE-TYPES :PARENSCRIPT
 :SBCL+SAFE-STANDARD-READTABLE :NAMED-READTABLES :LPARALLEL :21BIT-CHARS
 :CHUNGA :FLEXI-STREAMS :CLOSER-MOP :CL-PPCRE-UNICODE :CL-UNICODE :CL-PPCRE
 :CL-JSON-DOUBLE-FLOAT-IS-SUBSUMED :CL-JSON-SINGLE-FLOAT-IS-SUBSUMED
 :BORDEAUX-THREADS :LPARALLEL.WITH-CLTL2 :LPARALLEL.WITH-CAS
 :LPARALLEL.WITH-STEALING-SCHEDULER :SPLIT-SEQUENCE CHIPZ-SYSTEM:GRAY-STREAMS
 CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64 CFFI-FEATURES:UNIX :CFFI
 CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP :FAST-IO-SV :FAST-IO
 :SBCL-USES-SB-ROTATE-BYTE :CL-JSON-CLOS :CL-JSON :THREAD-SUPPORT :ASDF3.3
 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX :NON-BASE-CHARS-EXIST-P
 :ASDF-UNICODE :X86-64 :GENCGC :64-BIT :ANSI-CL :COMMON-LISP :ELF
 :IEEE-FLOATING-POINT :LINUX :LITTLE-ENDIAN :PACKAGE-LOCAL-NICKNAMES
 :SB-CORE-COMPRESSION :SB-LDB :SB-PACKAGE-LOCKS :SB-THREAD :SB-UNICODE :SBCL
 :UNIX)

ASDF version: 3.3.5
ASDF registries: (NYXT-SOURCE-REGISTRY ENVIRONMENT-SOURCE-REGISTRY USER-SOURCE-REGISTRY
                      USER-SOURCE-REGISTRY-DIRECTORY
                      DEFAULT-USER-SOURCE-REGISTRY SYSTEM-SOURCE-REGISTRY
                      SYSTEM-SOURCE-REGISTRY-DIRECTORY
                      DEFAULT-SYSTEM-SOURCE-REGISTRY)
Critical dependencies: (/gnu/store/s7w144g61qsmschm6mzy41bvq0qvjfrs-cl-cffi-gtk-0.11.2-2.e9a46df/share/common-lisp/source/cl-cffi-gtk/gtk/cl-cffi-gtk.asd
 /gnu/store/w5awybp5s66bn7g74mbvlr10ivhr6m2v-cl-gobject-introspection-0.3-1.d0136c8/share/common-lisp/source/cl-gobject-introspection/cl-gobject-introspection.asd
 /gnu/store/70pk09q9my9cb7mlxpgla6h7b2xs3jhd-cl-webkit-3.4.0/share/common-lisp/source/cl-webkit/webkit2/cl-webkit2.asd)

**Comment by Mugworth** [comment]
#2136

**Comment by aartaka** [comment]
Do you have Gstreamer plugins installed? See [Troubleshooting section in Nyxt manual](https://nyxt.atlas.engineer/documentation) or built-in `manual` command.

**Comment by Mugworth** [comment]
Looking at the playing videos section i think i have them installed, but maybe i'm missing something, is out there list of needed dependencies for playing videos on ubuntu-based distributions? Also probably worth mentioning is that i got also xapp-gtk3-module error
![2023-01-21_14-39](https://user-images.githubusercontent.com/62995382/213869486-632b20e2-53af-47a1-9b0c-ac704f8c640d.png)

**Comment by aartaka** [comment]
Well, if something fails silently, then it's likely WebKitGTK not finding some dependency and panicking. So this `xapp-gtk3-module` may be the source of your problems here, actually.

**Comment by rafonseca** [comment]
I had a similar error installing nyxt through guix on manjaro. The following works for me:
`guix shell nyxt gst-plugins-bad gst-plugins-good -- nyxt`

I still get the xapp-gtk3-module error message, but I can see youtube videos.

**Comment by gyps** [comment]
> I had a similar error installing nyxt through guix on manjaro. The following works for me: `guix shell nyxt gst-plugins-bad gst-plugins-good -- nyxt`
> 
> I still get the xapp-gtk3-module error message, but I can see youtube videos.

That's interesting. I'm trying to get video working as well (running guix system) and I cannot see youtube videos. The initial error related to missing gst-modules is gone now but the videos just wouldn't start to play. No error message is printed.

**Comment by Ambrevar** [comment]
You forgot `gst-libav` which Youtube needs.

**Comment by gyps** [comment]
No, I just didn't mention it:
```
$ guix package --list-installed | grep gst
gstreamer           	1.20.3              	out	/gnu/store/j7avnpgnw6xx1l59p1axrpvrpglgnn7m-gstreamer-1.20.3
gst-plugins-base    	1.20.3              	out	/gnu/store/xkh2ymnwr9xm5idvr7r2kbkpiv6zggfg-gst-plugins-base-1.20.3
gst-libav           	1.20.3              	out	/gnu/store/yfgmmb03a06jfwxmp9gv7mywa1g2811x-gst-libav-1.20.3
gst-plugins-good    	1.20.3              	out	/gnu/store/yxr8zfncxhf8yr8zp70wnp0v674yniaa-gst-plugins-good-1.20.3
gst-plugins-bad     	1.20.3              	out	/gnu/store/m8b817d9ir41z1zl4asjlbw8l572wm2x-gst-plugins-bad-1.20.3
gst-plugins-ugly    	1.20.3              	out	/gnu/store/22pqlz4zrbnf53rdhw5w7bapnmcf9wib-gst-plugins-ugly-1.20.3
gst-vosk            	0.3.1               	out	/gnu/store/4idls07lp3pvivgvb6l84rzvyw0p6mxv-gst-vosk-0.3.1
```
