### ISSUE TITLE
REPL cells beyond the first one don't report the result value

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#2760]
CC @aartaka

**Comment by aartaka** [comment]
Okay, seems like yet another problem of symbol bindings: `order` somewhy stays at 0. I'm trying to find out the reason and fix.

**Comment by aartaka** [comment]
#2481 seems to have broken it (◎_◎;)

**Comment by aartaka** [comment]
Macros are dangerous indeed...

**Comment by aartaka** [comment]
That's a marvelous material for a blogpost, I think. We finally hit the complexity level that macros start slipping on :D
