### ISSUE TITLE
Copy and Paste Errors

### ISSUE THREAD

**Issue by jazzbassoon** [atlas-engineer/nyxt#2763]
**Describe the bug**
Running the copy command gives the following error:
Warning: Error on separate thread: Subprocess #<UIOP/LAUNCH-PROGRAM::PROCESS-INFO {1008159DC3}>
with command ("xclip" "-out" "-selection" "clipboard")
exited with error code 1

Copy and pasting works if I right click and use the menu. Incidentally if I copy something with the mouse, the copy command then works as normal. Just not if the clipboard is blank I guess.

**Precise recipe to reproduce the issue**
Launch Nyxt, select text, and run the copy command

**Information**
- OS name+version: Arch Linux
- Graphics card and driver: Intel integrated Iris Xe
- Desktop environment / Window manager name+version: Herbstluftwm 0.9.5-1
- How you installed Nyxt (Guix pack, package manager, build from source): AUR
- Information from `show-system-information`:
`Nyxt version: 3-pre-release-2-834-g5042a2bb4
Renderer: GI-GTK
Operating system kernel: Linux 6.1.8-arch1-1
Lisp implementation: SBCL 2.3.0 (Dynamic space size: 3221225472)
Features: (:NYXT-GI-GTK :NYXT-GTK :NYXT-GI-GTK :NYXT-GTK :NYXT-3.1 :NYXT-3 :NYXT-3-PRE-RELEASE-2 :NYXT-3-PRE-RELEASE-2-834-G5042A2BB4 :SLYNK :PLUMP-UTF-32 :PARENSCRIPT :NSYMBOLS :FSET-EXT-STRINGS :NJSON :GLOBAL-VARS :DECLARE-TYPES :SBCL+SAFE-STANDARD-READTABLE :NAMED-READTABLES :SWANK :CL-FAD :LPARALLEL :21BIT-CHARS :CUSTOM-HASH-TABLE-NATIVE :CL-PPCRE-UNICODE :CL-UNICODE :CL-JSON-DOUBLE-FLOAT-IS-SUBSUMED :CL-JSON-SINGLE-FLOAT-IS-SUBSUMED :CL-PPCRE :CHUNGA :FLEXI-STREAMS :WEBKIT2 :WEBKIT2-2.38 :WEBKIT2-CORS-ALLOWLIST :WEBKIT2-PASTE-PLAINTEXT :WEBKIT2-TRACKING :WEBKIT2-MUTE :WEBKIT2-EMOJI :WEBKIT2-MEDIA :WEBKIT2-SANDBOXING :GTK-3-22 :GTK-3-20 :GTK-3-18 :GTK-3-16 :GTK-3-14 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6 :GTK-3-4 :GTK :GDK-3-22 :GDK-3-20 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12 :GDK-3-10 :GDK-3-8 :GDK-3-6 :GDK-3-4 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF :CLOSER-MOP :GLIB-2-30 :GLIB-2-32 :GLIB-2-34 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42 :GLIB-2-44 :GLIB-2-46 :GLIB-2-48 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56 :GLIB-2-58 :GLIB :BORDEAUX-THREADS :LPARALLEL.WITH-CLTL2 :LPARALLEL.WITH-CAS :LPARALLEL.WITH-STEALING-SCHEDULER :SPLIT-SEQUENCE CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64 CFFI-FEATURES:UNIX :CFFI CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP :FAST-IO-SV :FAST-IO :CL-JSON-CLOS :CL-JSON :SBCL-USES-SB-ROTATE-BYTE CHIPZ-SYSTEM:GRAY-STREAMS :THREAD-SUPPORT :ASDF3.3 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX :NON-BASE-CHARS-EXIST-P :ASDF-UNICODE :ARENA-ALLOCATOR :X86-64 :GENCGC :64-BIT :ANSI-CL :COMMON-LISP :ELF :IEEE-FLOATING-POINT :LINUX :LITTLE-ENDIAN :PACKAGE-LOCAL-NICKNAMES :SB-CORE-COMPRESSION :SB-LDB :SB-PACKAGE-LOCKS :SB-THREAD :SB-UNICODE :SBCL :UNIX)

ASDF version: 3.3.1
ASDF registries: (NYXT-SOURCE-REGISTRY ENVIRONMENT-SOURCE-REGISTRY)
Critical dependencies: (/home/.../Downloads/nyxt-git/src/nyxt/_build/cl-cffi-gtk/gtk/cl-cffi-gtk.asd /home/.../Downloads/nyxt-git/src/nyxt/_build/cl-gobject-introspection/cl-gobject-introspection.asd /home/.../Downloads/nyxt-git/src/nyxt/_build/cl-webkit/webkit2/cl-webkit2.asd)`

**Output when started from a shell**
Nyxt version 3-pre-release-2-834-g5042a2bb4
<INFO> [10:46:07] Source location: #P"/usr/local/share/"
<INFO> [10:46:07] Loading Lisp file #P"/home/.../.config/nyxt/auto-config.3.lisp".
<INFO> [10:46:07] GTK extensions directory: #P"/usr/local/share/libraries/web-extensions/"
<INFO> [10:46:07] GTK extensions directory: #P"/usr/local/share/libraries/web-extensions/"
<INFO> [10:46:07] Loading #P"/home/.../.local/share/nyxt/history/default.lisp".
<INFO> [10:46:08] Loading #P"/home/.../.local/share/nyxt/auto-rules.lisp".
<INFO> [10:46:08] Restoring 2 buffers from history.
<INFO> [10:46:08] Loading "https://www.openstreetmap.org/relation/2683176#map=13/51.6555/-0.3957".
<INFO> [10:46:09] Finished loading "https://www.openstreetmap.org/relation/2683176#map=13/51.6555/-0.3957".
(Then selecting text and running the copy command)
<WARN> [10:46:13] Warning: Error on separate thread: Subprocess #&lt;UIOP/LAUNCH-PROGRAM::PROCESS-INFO {10059E1D63}&gt;
 with command (&quot;xclip&quot; &quot;-out&quot; &quot;-selection&quot; &quot;clipboard&quot;)
 exited with error code 1

**Comment by jazzbassoon** [comment]
Just noticing in the system-show-info output that it is still referencing my Downloads folder, which no longer has any nyxt stuff in it. Is that actually an issue?

**Comment by Ambrevar** [comment]
Installing `xclip` using`pacman` should fix this issue.

**Comment by Ambrevar** [comment]
> Just noticing in the system-show-info output that it is still referencing my Downloads folder, which no longer has any nyxt stuff in it. Is that actually an issue?

No it's not, it's just useful information for devs to know how Nyxt was built.

**Comment by aartaka** [comment]
> Installing `xclip` using`pacman` should fix this issue.

`xclip` is installed already in this case. Note that it does work, but throws error code 1. `xclip` has no documentation on that, but it's pretty safe to guess that this error code if for clipboard being empty. 4b10ce215469ecc8c63436d91c659bf9463a200e should fix that.

**Comment by jazzbassoon** [comment]
Updated to 4b10ce2, and now the error I get is 
Warning: Error on separate thread: Tried to examine first-element from an empty queue.

**Comment by aartaka** [comment]
@jazzbassoon, sorry, should be fixed in bf08aa20a9dc7095652087c61c37ef762148b938.

**Comment by jazzbassoon** [comment]
Perfect thanks!
