### ISSUE TITLE
Hidpi scaling only *sometimes* works on sway/wayland

### ISSUE THREAD

**Issue by shaunsingh** [atlas-engineer/nyxt#2767]
**Describe the bug**

For some reason, only rarely sometimes does the nyxt ui scale properly and pages are displayed correctly, most of the time it doesn't scale at all (and looks quite small). 

**Precise recipe to reproduce the issue**

I don't quite know how to reproduce the issue, apart from closing and re-opening nyxt dozens of times and getting lucky
 
For website-specific issues:
Can you reproduce this issue with Epiphany / GNOME Web (https://wiki.gnome.org/Apps/Web)?

N/A

**Information**
- OS name+version: Linux/asahi 6.1.0
- Graphics card and driver: Apple M1 using the Asahi linux experimental driver (mesa)
- Desktop environment / Window manager name+version: Sway latest
- How you installed Nyxt (Guix pack, package manager, build from source): Build from source from master using nix
- Information from `show-system-information`:

```
Nyxt version: 27ef18a
Renderer: GI-GTK
Operating system kernel: Linux 6.1.0-asahi
Lisp implementation: SBCL 2.2.11.nixos (Dynamic space size: 3221225472)
Features: (:NYXT-GI-GTK :NYXT-GTK :NYXT-GI-GTK :NYXT-GTK :NYXT-27EF18A :CUSTOM-HASH-TABLE-NATIVE :SLYNK :PLUMP-UTF-32 :PARENSCRIPT :NSYMBOLS :FSET-EXT-STRINGS :NJSON :GLOBAL-VARS :DECLARE-TYPES :SBCL+SAFE-STANDARD-READTABLE :NAMED-READTABLES :SWANK :CL-FAD :LPARALLEL :21BIT-CHARS :CL-PPCRE-UNICODE :CL-UNICODE :CL-JSON-DOUBLE-FLOAT-IS-SUBSUMED :CL-JSON-SINGLE-FLOAT-IS-SUBSUMED :CL-PPCRE :CHUNGA :FLEXI-STREAMS :WEBKIT2 :WEBKIT2-2.38 :WEBKIT2-CORS-ALLOWLIST :WEBKIT2-PASTE-PLAINTEXT :WEBKIT2-TRACKING :WEBKIT2-MUTE :WEBKIT2-EMOJI :WEBKIT2-MEDIA :WEBKIT2-SANDBOXING :GTK-3-22 :GTK-3-20 :GTK-3-18 :GTK-3-16 :GTK-3-14 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6 :GTK-3-4 :GTK :GDK-3-22 :GDK-3-20 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12 :GDK-3-10 :GDK-3-8 :GDK-3-6 :GDK-3-4 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF :CLOSER-MOP :GLIB-2-30 :GLIB-2-32 :GLIB-2-34 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42 :GLIB-2-44 :GLIB-2-46 :GLIB-2-48 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56 :GLIB-2-58 :GLIB :BORDEAUX-THREADS :LPARALLEL.WITH-CLTL2 :LPARALLEL.WITH-CAS :LPARALLEL.WITH-STEALING-SCHEDULER :SPLIT-SEQUENCE CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:UNIX :CFFI CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP :FAST-IO-SV :FAST-IO :CL-JSON-CLOS :CL-JSON :SBCL-USES-SB-ROTATE-BYTE CHIPZ-SYSTEM:GRAY-STREAMS :THREAD-SUPPORT :ASDF3.3 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX :NON-BASE-CHARS-EXIST-P :ASDF-UNICODE :ARM64 :GENCGC :64-BIT :ANSI-CL :COMMON-LISP :ELF :IEEE-FLOATING-POINT :LINUX :LITTLE-ENDIAN :PACKAGE-LOCAL-NICKNAMES :SB-CORE-COMPRESSION :SB-LDB :SB-PACKAGE-LOCKS :SB-THREAD :SB-UNICODE :SBCL :UNIX)

ASDF version: 3.3.1
ASDF registries: (NYXT-SOURCE-REGISTRY ENVIRONMENT-SOURCE-REGISTRY)
Critical dependencies: (/home/shauryasingh/Projects/nyxt/_build/cl-cffi-gtk/gtk/cl-cffi-gtk.asd /home/shauryasingh/Projects/nyxt/_build/cl-gobject-introspection/cl-gobject-introspection.asd /home/shauryasingh/Projects/nyxt/_build/cl-webkit/webkit2/cl-webkit2.asd)
```

**Comment by Ambrevar** [comment]
Have you checked the `Font size on HiDPI displays` section in the manual?

**Comment by shaunsingh** [comment]
I did, neither `GDK_SCALE` nor `GDK_DPI_SCALE` seem to fix the issue, maybe because I'm on wayland. Using `GDK_BACKEND=x11` did work, but everything is blurry as xwayland doesn't scale resolution

**Comment by shaunsingh** [comment]
One other weird thing, the cursor is twice as big than it should be. Changing the value of the `GDK_SCALE` or `GDK_DPI_SCALE` env variables doesn't change this

**Comment by aartaka** [comment]
> One other weird thing, the cursor is twice as big than it should be. Changing the value of the `GDK_SCALE` or `GDK_DPI_SCALE` env variables doesn't change this

This one seems to be outside Nyxt scope: https://bbs.archlinux.org/viewtopic.php?id=266948

**Comment by shaunsingh** [comment]
I patched wlroots/xwayland to better support hidpi and it fixed both the issues

**Comment by aartaka** [comment]
Glad to hear it!
