### ISSUE TITLE
Nyxt ignores the actual config directory

### ISSUE THREAD

**Issue by waxcatape** [atlas-engineer/nyxt#2770]
When launching Nyxt with a config.lisp in a directory different from .config/nyxt/, Nyxt looks for any additional files loaded in the body of config.lisp in .config/ instead of the actual directory of config.lisp

**Steps to reproduce**
1. Put a config.lisp file somewhere not in .config/nyxt/ containing other lisp files, and load the lisp files:
    (define-nyxt-user-system-and-load nyxt-user/basic-config
       :components ("file1" "file2"))

2. Start Nyxt from a shell with the --config arg pointing at the config.lisp from step 1.
3. You get a "failed to find a TRUENAME for /home/user/.config/nyxt/file1.lisp" error.

**Information**
- OS name+version: Guix System 6.1.8
- Graphics card and driver:
- Desktop environment / Window manager name+version: xmonad 0.17
- How you installed Nyxt (Guix pack, package manager, build from source): Built from source with Guix
- Information from `show-system-information`:
Nyxt version: 3
Renderer version: GI-GTK
Operating system kernel: Linux 6.1.8
Lisp implementation: SBCL 2.2.11 (Dynamic space size: 3221225472)
Features: (:NYXT-GI-GTK :NYXT-GTK :WEBKIT2 :WEBKIT2-2.38 :WEBKIT2-CORS-ALLOWLIST :WEBKIT2-PASTE-PLAINTEXT :WEBKIT2-TRACKING :WEBKIT2-MUTE :WEBKIT2-EMOJI :WEBKIT2-MEDIA :WEBKIT2-SANDBOXING :GTK-3-22 :GTK-3-20 :GTK-3-18 :GTK-3-16 :GTK-3-14 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6 :GTK-3-4 :GTK :GDK-3-22 :GDK-3-20 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12 :GDK-3-10 :GDK-3-8 :GDK-3-6 :GDK-3-4 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF :GLIB-2-30 :GLIB-2-32 :GLIB-2-34 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42 :GLIB-2-44 :GLIB-2-46 :GLIB-2-48 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56 :GLIB-2-58 :GLIB :NYXT-3 :CUSTOM-HASH-TABLE-NATIVE :CLIPBOARD-CONTENT-METHOD :SLYNK :PLUMP-UTF-32 :PARENSCRIPT :FSET-EXT-STRINGS :SBCL+SAFE-STANDARD-READTABLE :NAMED-READTABLES :GLOBAL-VARS :SWANK :LPARALLEL :21BIT-CHARS :CLOSER-MOP :CL-PPCRE-UNICODE :CL-UNICODE :CL-JSON-DOUBLE-FLOAT-IS-SUBSUMED :CL-JSON-SINGLE-FLOAT-IS-SUBSUMED :CL-PPCRE :CHUNGA :FLEXI-STREAMS :BORDEAUX-THREADS :LPARALLEL.WITH-CLTL2 :LPARALLEL.WITH-CAS :LPARALLEL.WITH-STEALING-SCHEDULER :SPLIT-SEQUENCE CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64 CFFI-FEATURES:UNIX :CFFI CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP :FAST-IO-SV :FAST-IO :ASDF-SYSTEM-CONNECTIONS :CL-JSON-CLOS :CL-JSON :SBCL-USES-SB-ROTATE-BYTE CHIPZ-SYSTEM:GRAY-STREAMS :THREAD-SUPPORT :ASDF3.3 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX :NON-BASE-CHARS-EXIST-P :ASDF-UNICODE :ARENA-ALLOCATOR :X86-64 :GENCGC :64-BIT :ANSI-CL :COMMON-LISP :ELF :IEEE-FLOATING-POINT :LINUX :LITTLE-ENDIAN :PACKAGE-LOCAL-NICKNAMES :SB-CORE-COMPRESSION :SB-LDB :SB-PACKAGE-LOCKS :SB-THREAD :SB-UNICODE :SBCL :UNIX)

ASDF version: 3.3.5
ASDF registries: (NYXT-SOURCE-REGISTRY ENVIRONMENT-SOURCE-REGISTRY USER-SOURCE-REGISTRY USER-SOURCE-REGISTRY-DIRECTORY DEFAULT-USER-SOURCE-REGISTRY SYSTEM-SOURCE-REGISTRY SYSTEM-SOURCE-REGISTRY-DIRECTORY DEFAULT-SYSTEM-SOURCE-REGISTRY)
Critical dependencies: (/gnu/store/vvh336hggdd0wqisakr1nvd1avz8kbi9-cl-cffi-gtk-0.11.2-2.e9a46df/share/common-lisp/source/cl-cffi-gtk/gtk/cl-cffi-gtk.asd /gnu/store/dcnwcmz9qig6s3bij0cmqhzvzcx49ljq-cl-gobject-introspection-0.3-1.d0136c8/share/common-lisp/source/cl-gobject-introspection/cl-gobject-introspection.asd /gnu/store/vnc5xn6rgi510plqca1mcv9h62gl74n7-cl-webkit-3.5.6/share/common-lisp/source/cl-webkit/webkit2/cl-webkit2.asd)

**Shell output**
Nyxt version 3
<INFO> [13:52:10] Source location: #P"/gnu/store/dkxc2ynv6l0ky967kql3607wdpj2cc34-nyxt-3-3-pre-release-2/share/nyxt/"
<INFO> [13:52:10] Loading Lisp file #P"/home/the-great-heron/documents/projects/config/nyxt-config/alt-confg.lisp".
<WARN> [13:52:10] Not found slot OVERRIDE-MAP in class BUFFER, generating the wrapper method for configuration.
While evaluating the form starting at line 25, column 0
  of #P"/home/the-great-heron/documents/projects/config/nyxt-config/alt-confg.lisp":
; 
; compilation unit aborted
;   caught 1 fatal ERROR condition
<INFO> [13:52:10] GTK extensions directory: #P"/gnu/store/dkxc2ynv6l0ky967kql3607wdpj2cc34-nyxt-3-3-pre-release-2/lib/nyxt/"
<INFO> [13:52:10] Loading #P"/home/the-great-heron/.local/share/nyxt/history/default.lisp".
<INFO> [13:52:10] Restoring 4 buffers from history.
<INFO> [13:52:10] GTK extensions directory: #P"/gnu/store/dkxc2ynv6l0ky967kql3607wdpj2cc34-nyxt-3-3-pre-release-2/lib/nyxt/"
<WARN> [13:52:10] Warning: Failed to find the TRUENAME of /home/the-great-heron/.config/nyxt/stylesheet.lisp:

  No such file or directory
<WARN> [13:52:10] Warning: Error on separate thread: There is no applicable method for the generic function
  #&lt;STANDARD-GENERIC-FUNCTION NYXT::LISP-URL-CALLBACKS (1)&gt;
when called with arguments
  (#&lt;DOCUMENT-BUFFER 5115 {100781D713}&gt;).
See also:
  The ANSI Standard, Section 7.6.6
<WARN> [13:52:11] Warning: Error in signal on renderer thread: There is no applicable method for the generic function
  #&lt;STANDARD-GENERIC-FUNCTION NYXT::LISP-URL-CALLBACKS (1)&gt;
when called with arguments
  (#&lt;DOCUMENT-BUFFER 5115 {100781D713}&gt;).
See also:
  The ANSI Standard, Section 7.6.6
<WARN> [13:52:11] Warning: Error on separate thread: There is no applicable method for the generic function
  #&lt;STANDARD-GENERIC-FUNCTION NYXT::LISP-URL-CALLBACKS (1)&gt;
when called with arguments
  (#&lt;DOCUMENT-BUFFER 5115 {100781D713}&gt;).
See also:
  The ANSI Standard, Section 7.6.6

**Comment by Ambrevar** [comment]
The log says

```
[13:52:10] Loading Lisp file #P"/home/the-great-heron/documents/projects/config/nyxt-config/alt-confg.lisp".
[13:52:10] Not found slot OVERRIDE-MAP in class BUFFER, generating the wrapper method for configuration.
While evaluating the form starting at line 25, column 0
of #P"/home/the-great-heron/documents/projects/config/nyxt-config/alt-confg.lisp":
;
; compilation unit aborted
; caught 1 fatal ERROR condition
```

So it properly finds your `alt-confg.lisp` file, but this one contains an error.
I suppose this explains the subsequent errors.

```
[13:52:10] Warning: Failed to find the TRUENAME of /home/the-great-heron/.config/nyxt/stylesheet.lisp:

No such file or directory
```

Where / when do you load this `stylesheet.lisp`?

Can you share more of your config so we can try to reproduce / fix your issue?

**Comment by aadcg** [comment]
@waxcatape Friendly ping :)

**Comment by aadcg** [comment]
Feel free to reopen if you need more help @waxcatape.
