### ISSUE TITLE
Nyxt:New Buffer --please add a navigation object for internal pages to connect me with the status bar navigation system.

### ISSUE THREAD

**Issue by lansingthomas** [atlas-engineer/nyxt#2771]
Gentle Engineers & Super Wizards,
Please help.

When I create a new buffer with an internal page {`New buffer` or `tutorial`}, it would really help me understand my position in the system if the status bar displayed a text object to reflect this new space. 

Please add a text object in the status buffer to represent the creation of these new buffers. 

**Why:**
- consistency (the status bar displays buffers, these are buffers)
- recognition is better than recall (this helps us identify where we are surfing without having to remember that there is some arbitrary internal page between two URLs)
- when users discover internal pages like `History Tree` this fix will help keep them oriented

Thank you : )

**Comment by aadcg** [comment]
I don't think I understand your request Thomas.

Could you please explain what you expect to be displayed in the area encircled in red below?

![2023-02-07_10:34:17](https://user-images.githubusercontent.com/45483512/217193882-5ec2dd5e-9092-4265-82a1-135597daf58d.png)

**Comment by lansingthomas** [comment]
Like this:

![inlcuding nyxt internap pages in status buffer navigation](https://user-images.githubusercontent.com/6666079/217339803-5c6172d9-be5f-48f5-a3bf-eb7fda4defa7.png)

**Comment by aartaka** [comment]
But still, buffer listing area is quite small, so I'd not clutter with anything that isn't a buffer. Adding a chip with internal pages won't hurt, though.
