### ISSUE TITLE
Nyxt failing on old config with bad restart

### ISSUE THREAD

**Issue by franburstall** [atlas-engineer/nyxt#2778]
**Describe the bug**

I fire `nyxt` for the first time in a few months.  Clearly a lot has changed because I get a compilation error early in my config that crashes `nyxt`.  No surprises so far.

BUT, `nyxt` then tries to restart with a `--no-config` flag and this fails too.  First some warnings are reported but no browser window appears and I get my shell prompt  back.  However, `proced`  reveals that there is a `nyxt` process running with a >4500 character argument that starts:
````
--eval (SERAPEUM:ADD-HOOK\ (NYXT:AFTER-INIT-HOOK\ NYXT:*BROWSER*)\^J\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ (MAKE-INSTANCE\ 'NHOOKS:HANDLER\ :FN\^J\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ (LAMBDA\ ()\^J\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ (SETF\ (NYXT::STARTUP-ERROR-REPORTER-FUNCTION\^...
````
Here is what I see from the shell:
````
% nyxt

(sbcl:167694): Gtk-WARNING **: 15:17:52.589: Theme parsing error: gtk-contained-dark.css:2871:228: Missing closing bracket for :not()
Nyxt version 3-pre-release-2-921-g8d71ac19
<INFO> [15:17:52] Source location: #P"/home/fran/common-lisp/nyxt/"
<INFO> [15:17:52] Loading Lisp file #P"/home/fran/.config/nyxt/auto-config.3.lisp".

; file: /home/fran/.config/nyxt/auto-config.3.lisp
; in: DEFMETHOD CUSTOMIZE-INSTANCE (INPUT-BUFFER)
;     (NYXT:DISABLE-MODES '(NYXT/VI-MODE:VI-NORMAL-MODE) NYXT:INPUT-BUFFER)
; 
; caught STYLE-WARNING:
;   The first argument of type CONS cannot be used as a keyword.

;     (NYXT:ENABLE-MODES '(NYXT/EMACS-MODE:EMACS-MODE) NYXT:INPUT-BUFFER)
; 
; caught STYLE-WARNING:
;   The first argument of type CONS cannot be used as a keyword.
; 
; compilation unit finished
;   caught 2 STYLE-WARNING conditions
<INFO> [15:17:52] Loading Lisp file #P"/home/fran/.config/nyxt/config.lisp".
While evaluating the form starting at line 3, column 0
  of #P"/home/fran/.config/nyxt/config.lisp":
; 
; compilation unit aborted
;   caught 1 fatal ERROR condition
<INFO> [15:17:52] Listening to socket: #P"/run/user/1000/nyxt/nyxt.socket"
<WARN> [15:17:52] Restarting with ("nyxt" "--no-config").
<INFO> [15:17:52] Deleting socket #P"/run/user/1000/nyxt/nyxt.socket".
<INFO> [15:17:53] Source location: #P"/home/fran/common-lisp/nyxt/"
<INFO> [15:17:53] Loading Lisp file #P"/home/fran/.config/nyxt/auto-config.3.lisp".
<WARN> [15:17:53] Warning: Error in s-exp evaluation: There is no applicable method for the generic function
  #&lt;STANDARD-GENERIC-FUNCTION NYXT:AFTER-INIT-HOOK (1)&gt;
when called with arguments
  (NIL).
See also:
  The ANSI Standard, Section 7.6.6
<INFO> [15:17:53] Listening to socket: #P"/run/user/1000/nyxt/nyxt.socket"
<WARN> [15:17:53] Warning: Error in FFI method: keyword argument not a symbol: (NYXT/VI-MODE:VI-NORMAL-MODE).
<WARN> [15:17:53] Warning: Error on separate thread: There is no applicable method for the generic function
  #&lt;STANDARD-GENERIC-FUNCTION NYXT:ID (5)&gt;
when called with arguments
  (NIL).
See also:
  The ANSI Standard, Section 7.6.6
````
There is nothing I can see to do except kill that `nyxt` process.

**Information**
- OS name+version: debian-11
- Graphics card and driver:
- Desktop environment / Window manager name+version: EXWM
- How you installed Nyxt (Guix pack, package manager, build from source): source
- Information from `show-system-information`:
Nyxt version: 3-pre-release-2-921-g8d71ac19
Renderer: GI-GTK
Operating system kernel: Linux 5.10.0-21-amd64
Lisp implementation: SBCL 2.1.1 (Dynamic space size: 3221225472)
Features: (:NYXT-GI-GTK :NYXT-GTK :NYXT-3.1 :NYXT-3 :NYXT-3-PRE-RELEASE-2
 :NYXT-3-PRE-RELEASE-2-921-G8D71AC19 :SLYNK :PLUMP-UTF-32 :PARENSCRIPT
 :NSYMBOLS :FSET-EXT-STRINGS :NJSON :GLOBAL-VARS :DECLARE-TYPES
 :NAMED-READTABLES :SWANK :CL-FAD :LPARALLEL :21BIT-CHARS
 :CUSTOM-HASH-TABLE-NATIVE :CL-PPCRE-UNICODE :CL-UNICODE :CL-PPCRE :CHUNGA
 :FLEXI-STREAMS :WEBKIT2 :WEBKIT2-2.38 :WEBKIT2-CORS-ALLOWLIST
 :WEBKIT2-PASTE-PLAINTEXT :WEBKIT2-TRACKING :WEBKIT2-MUTE :WEBKIT2-EMOJI
 :WEBKIT2-MEDIA :WEBKIT2-SANDBOXING :GTK-3-22 :GTK-3-20 :GTK-3-18 :GTK-3-16
 :GTK-3-14 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6 :GTK-3-4 :GTK :GDK-3-22
 :GDK-3-20 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12 :GDK-3-10 :GDK-3-8 :GDK-3-6
 :GDK-3-4 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF :CLOSER-MOP :GLIB-2-30 :GLIB-2-32
 :GLIB-2-34 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42 :GLIB-2-44 :GLIB-2-46
 :GLIB-2-48 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56 :GLIB-2-58 :GLIB
 :BORDEAUX-THREADS :LPARALLEL.WITH-CLTL2 :LPARALLEL.WITH-CAS
 :LPARALLEL.WITH-STEALING-SCHEDULER :SPLIT-SEQUENCE
 CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64 CFFI-FEATURES:UNIX :CFFI
 CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP :FAST-IO-SV :FAST-IO
 :CL-JSON-CLOS :CL-JSON :SBCL-USES-SB-ROTATE-BYTE CHIPZ-SYSTEM:GRAY-STREAMS
 :THREAD-SUPPORT :ASDF3.3 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX
 :NON-BASE-CHARS-EXIST-P :ASDF-UNICODE :X86-64 :GENCGC :64-BIT :ANSI-CL
 :COMMON-LISP :ELF :IEEE-FLOATING-POINT :LINUX :LITTLE-ENDIAN
 :PACKAGE-LOCAL-NICKNAMES :SB-LDB :SB-PACKAGE-LOCKS :SB-THREAD :SB-UNICODE
 :SBCL :UNIX)

ASDF version: 3.3.1
ASDF registries: (NYXT-SOURCE-REGISTRY ENVIRONMENT-SOURCE-REGISTRY)
Critical dependencies: (/home/fran/common-lisp/nyxt/_build/cl-cffi-gtk/gtk/cl-cffi-gtk.asd
 /home/fran/common-lisp/nyxt/_build/cl-gobject-introspection/cl-gobject-introspection.asd
 /home/fran/common-lisp/nyxt/_build/cl-webkit/webkit2/cl-webkit2.asd)

**Comment by aadcg** [comment]
It seems to be that the error is coming the auto-config file located at `/home/fran/.config/nyxt/auto-config.3.lisp`. Could you try to delete it?

**Comment by franburstall** [comment]
Yup.  With that file deleted, nyxt loads moreorless OK.  However, I raised the issue because I thought nyxt was supposed to be more robust about being supplied out-dated config (especially auto-config!) now.

**Comment by aadcg** [comment]
@franburstall I share your opinion and your report is extremely valuable!

I'm not sure what happened here, but @Ambrevar and @aartaka might have some ideas.

Do you know which version/commit were you running before re-building it?

**Comment by franburstall** [comment]
> Do you know which version/commit were you running before re-building it?

Sadly not but the last time I seriously played with nyxt was September 2022 and the out-dated `auto-config.3.lisp` was last modified 29-08-22.

**Comment by Ambrevar** [comment]
My bad, I had forgotten to update the restart code.  Should be fixed with #2779.  @franburstall You confirm?

**Comment by Ambrevar** [comment]
Merged on master.

Feel free to reopen if there is anything else.

**Comment by franburstall** [comment]
A bit late but I confirm that restarts actually work now!

**Comment by Ambrevar** [comment]
Thanks!
