### ISSUE TITLE
OpenSSL problem when multipple versions are installed

### ISSUE THREAD

**Issue by dinkocar** [atlas-engineer/nyxt#2785]
**Describe the bug**
Hostlists can not be updated. Error in log is
 Failed to load #P"/home/xxxx/.local/share/nyxt/hostlist-stevenblack.txt": The alien function "SSL_get1_peer_certificate" is undefined.
I have openssl 3.0, openssl 1.0 and openssl 1.1 installed.
"openssl version" returns 3.0
nyxt is installed from arch aur package
This error also happens in some other situations, but it is easiest to reproduce with update-hostlists.

**Precise recipe to reproduce the issue**
run update-hostlists

**Information**
Nyxt version: 3-pre-release-3-24-g6e567fc63
Renderer: GI-GTK
Operating system kernel: Linux 6.1.9-1-MANJARO
Lisp implementation: SBCL 2.3.0 (Dynamic space size: 3221225472)
Features: (:NYXT-GI-GTK :NYXT-GTK :NYXT-GI-GTK :NYXT-GTK :NYXT-3.1 :NYXT-3 :NYXT-3-PRE-RELEASE-3 :NYXT-3-PRE-RELEASE-3-24-G6E567FC63 :SLYNK :PLUMP-UTF-32 :PARENSCRIPT :NSYMBOLS :FSET-EXT-STRINGS :NJSON :GLOBAL-VARS :DECLARE-TYPES :SBCL+SAFE-STANDARD-READTABLE :NAMED-READTABLES :SWANK :CL-FAD :LPARALLEL :21BIT-CHARS :CUSTOM-HASH-TABLE-NATIVE :CL-PPCRE-UNICODE :CL-UNICODE :CL-JSON-DOUBLE-FLOAT-IS-SUBSUMED :CL-JSON-SINGLE-FLOAT-IS-SUBSUMED :CL-PPCRE :CHUNGA :FLEXI-STREAMS :WEBKIT2 :WEBKIT2-2.38 :WEBKIT2-CORS-ALLOWLIST :WEBKIT2-PASTE-PLAINTEXT :WEBKIT2-TRACKING :WEBKIT2-MUTE :WEBKIT2-EMOJI :WEBKIT2-MEDIA :WEBKIT2-SANDBOXING :GTK-3-22 :GTK-3-20 :GTK-3-18 :GTK-3-16 :GTK-3-14 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6 :GTK-3-4 :GTK :GDK-3-22 :GDK-3-20 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12 :GDK-3-10 :GDK-3-8 :GDK-3-6 :GDK-3-4 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF :CLOSER-MOP :GLIB-2-30 :GLIB-2-32 :GLIB-2-34 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42 :GLIB-2-44 :GLIB-2-46 :GLIB-2-48 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56 :GLIB-2-58 :GLIB :BORDEAUX-THREADS :LPARALLEL.WITH-CLTL2 :LPARALLEL.WITH-CAS :LPARALLEL.WITH-STEALING-SCHEDULER :SPLIT-SEQUENCE CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64 CFFI-FEATURES:UNIX :CFFI CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP :FAST-IO-SV :FAST-IO :CL-JSON-CLOS :CL-JSON :SBCL-USES-SB-ROTATE-BYTE CHIPZ-SYSTEM:GRAY-STREAMS :THREAD-SUPPORT :ASDF3.3 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX :NON-BASE-CHARS-EXIST-P :ASDF-UNICODE :ARENA-ALLOCATOR :X86-64 :GENCGC :64-BIT :ANSI-CL :COMMON-LISP :ELF :IEEE-FLOATING-POINT :LINUX :LITTLE-ENDIAN :PACKAGE-LOCAL-NICKNAMES :SB-CORE-COMPRESSION :SB-LDB :SB-PACKAGE-LOCKS :SB-THREAD :SB-UNICODE :SBCL :UNIX)

ASDF version: 3.3.1
ASDF registries: (NYXT-SOURCE-REGISTRY ENVIRONMENT-SOURCE-REGISTRY)
Critical dependencies: (/home/rade/.cache/yay/nyxt-git/src/nyxt/_build/cl-cffi-gtk/gtk/cl-cffi-gtk.asd /home/rade/.cache/yay/nyxt-git/src/nyxt/_build/cl-gobject-introspection/cl-gobject-introspection.asd /home/rade/.cache/yay/nyxt-git/src/nyxt/_build/cl-webkit/webkit2/cl-webkit2.asd)

**Comment by aartaka** [comment]
It most probably is something with Dexador discovering the wrong OpenSSL version. Not sure how to fix it, though.

**Comment by jmercouris** [comment]
Interesting that Dexador would not use simply the same library it was built with. It would be baked into the image. I don't understand what we could do, other than perhaps force Dexador to use the newest version of the library it can. 

That said, I believe the underlying problem is here: https://github.com/cl-plus-ssl/cl-plus-ssl

this is what Dexador is using via Usocket. I'll have to take a look at the source later.

**Comment by Ambrevar** [comment]
On Guix cl+ssl uses `openssl-1.1.1l`.

Library query is done here: https://github.com/cl-plus-ssl/cl-plus-ssl/blob/master/src/reload.lisp#L173

**Comment by aadcg** [comment]
Stale.
