### ISSUE TITLE
Create flatpak package

### ISSUE THREAD

**Issue by aadcg** [atlas-engineer/nyxt#2789]
We need an additional user-friendly way to install Nyxt.  

These are the issues with the other methods:

- Currently, `.deb` works for some specific versions of Ubuntu;
- Installing via guix pack suffers from #2647. We can't expect that the lay user will be able to fix it manually;
- Installing via the Guix package manager requires some expertise;
- Installing from source requires expertise.

A flatpak would be easy for users to install and it works in most GNU/Linux distributions.

**Comment by aadcg** [comment]
Please confirm, but I believe closing this one would close:

#2647 
#2459 
#2775

**Comment by aadcg** [comment]
Ideally, we should generate our flatpak from guix pack. [It seems to be theoretically possible](https://lists.gnu.org/archive/html/help-guix/2021-05/msg00016.html).

**Comment by Ambrevar** [comment]
> Please confirm, but I believe closing this one would close:
> 
>     * [Launcher for Ubuntu 20.04.1 #2647](https://github.com/atlas-engineer/nyxt/issues/2647)
> 
>     * [nyxt 3-pre-release-1 (.deb package): Warning about ASDF older than 2.27 at start up #2459](https://github.com/atlas-engineer/nyxt/issues/2459)
> 
>     * [nyxt 3 failed to start #2775](https://github.com/atlas-engineer/nyxt/issues/2775)

Looks like it, yes.

**Comment by aadcg** [comment]
This issue can be closed as soon as our flatpak is added to flathub.

**Comment by aadcg** [comment]
Closing since we already ship Flatpak. With regards to Flathub, see #2947.
