### ISSUE TITLE
Should `prompter:actions-on-{return,marks,current-suggestion}` be set to functions?

### ISSUE THREAD

**Issue by aadcg** [atlas-engineer/nyxt#2794]
Look at the following prompt buffer invocation. The action defined is valid, and runs as expected. An error is raised  when issuing command `set-action-on-return`. The reason being that `make-action-suggestion` expects symbols or commands (that's why actions are usually defined via `lambda-command` or `lambda-mapped-command`).

```lisp
(prompt :prompt "Test"
        :sources (make-instance 'prompter:source
                                :name "Test"
                                :constructor (list "Hello")
                                :actions-on-return
                                (list
                                 ;; Defining it with a lambda results in
                                 ;; a error when issuing command
                                 ;; set-action-on-return.
                                 (lambda (suggestion-list)
                                   "Greet world."
                                   (echo (str:concat (first suggestion-list)
                                                     " World!")))
                                 #'identity)))
```

I suggest that the elements of lists `prompter:actions-on-{return,marks,current-suggestion}` should either be symbols or commands.

**Comment by aartaka** [comment]
I'd say that on `prompter` side, then can be anything funcallable, because `prompter` is a general-purpose prompting library. 

BUT on Nyxt side we can and probably should enforce the values in a much stricter way. So we can add accessor watchers (`(setf prompter:actions-on-return) :after`) and additional initialization slot type checks (`initialize-instance :after`) to make sure there's nothing illegal smuggled into intentionally loose `prompter`.

**Comment by Ambrevar** [comment]
But why accept functions?  Don't we want to restrict actions to commands?

**Comment by Ambrevar** [comment]
If the use case is just `#'identity`, then having no return action should be equivalent to identity I believe.

**Comment by aartaka** [comment]
> But why accept functions? Don't we want to restrict actions to commands?

We want, yes! Commands allow more control and have much more auxiliary information attached to them. So in Nyxt we need to force commands everywhere.

But then, once `prompter` is extracted, it should also accept raw functions, to accomodate a variety of use-cases. So the restriction on commands should be only on Nyxt side, not the `prompter` one.

**Comment by aadcg** [comment]
Then we'd need to set all `prompter:actions-on-return` to `nil` in Nyxt since the default (inherited from `prompter`) is `#'identity`. 

The issue is this solution is that when issuing `set-action-on-return` you'll see an empty list, which from the user perspective is quite strange.

```lisp
(prompt :prompt "Prompter"
        :sources (make-instance 'prompter:source
                                :name "Source"
                                :constructor (list "Hello")
                                :actions-on-return nil))
```

I suggest creating a class on the Nyxt side, that inherits from `prompter:source` that sets a default for `prompter:actions-on-return` - a command based on `identity`.

**Comment by aartaka** [comment]
Yes, that would be most structured.

**Comment by aadcg** [comment]
> I suggest creating a class on the Nyxt side, that inherits from prompter:source, that sets a default for prompter:actions-on-return - a command based on identity.

While this would be ideal it would trigger architectural changes that are too risky right now since we're on the verge of a new major release.

We need `prompter:source` very early in Nyxt. For instance, we need it in `gpg.lisp`, but `prompt-buffer.lisp` is compiled later (see `nyxt.asd`).

I suggest fixing `prompter:actions-on-return` at each instance of classes that inherit from `prompter:source` in Nyxt.

**Comment by aartaka** [comment]
> > I suggest creating a class on the Nyxt side, that inherits from prompter:source, that sets a default for prompter:actions-on-return - a command based on identity.
> 
> While this would be ideal it would trigger architectural changes that are too risky right now since we're on the verge of a new major release.

Well, that's the best time to break things, isn't it? If there a set of tests too, then we'd better do the change instead of postponing it.

Subclassing things is a relatively reasonable way to change the functionality that we anticipated long ago, so it should be pretty safe too.

> We need `prompter:source` very early in Nyxt. For instance, we need it in `gpg.lisp`, but `prompt-buffer.lisp` is compiled later (see `nyxt.asd`).

Well, then we'll define it early enough ¯\\\_(ツ)_/¯

> I suggest fixing `prompter:actions-on-return` at each class that inherit from `prompter:source` in Nyxt. It's not ideal but good enough.

Let's try subclassing `prompter:source` first, because it might actually work.

**Comment by Ambrevar** [comment]
Why not set `actions-on-return` to `NIL` in `prompter`, and set its type to `(maybe function)`?

**Comment by aadcg** [comment]
> Why not set `actions-on-return` to `NIL` in `prompter`, and set its type to `(maybe function)`?

As I've mentioned above:

> The issue with this solution is that when issuing set-action-on-return you'll see an empty list which, from the user's perspective, is not satisfactory.

**Comment by Ambrevar** [comment]
I mean, change Nyxt to accept NIL as "don't do anything".

**Comment by aadcg** [comment]
There are several topics being discussed here. Below, I tried to sum up everything that has been discussed thus far.

On the one hand, we have the general `prompter:source`, which allows setting actions to NIL, a funcallable or a list of funcallables. On the other hand, we can subclass the aforementioned class for Nyxt's purposes - let's call it `nyxt:prompt-source`.

1. In the context of `nyxt:prompt-source`, is setting an action to `NIL` acceptable?
2. In the context of `nyxt:prompt-source`, should funcallables be restricted to commands? In other words, in Nyxt's context, should we only allow passing commands defined via `define-command(-global)` and `make-command` (or symbols bounds to those things)?

---

### Question 1

Without loss of generality, consider the case of `actions-on-return`.

```lisp 
(prompt :prompt "Test"
        :sources (make-instance 'prompter:source
                                :name "Test"
                                :constructor (list "Hello")
                                :actions-on-return nil))
```

![nil-actions](https://user-images.githubusercontent.com/45483512/220928930-dca2e43c-9f6c-4f48-9a41-864eea67d980.png)


--- 

### Question 2

Let's look at all the funcallables that are possible to set as actions.

The following snippet only works from the `fix-prompt-buffer-actions`.

```lisp
(prompt :prompt "Test"
        :sources (make-instance 'prompter:source
                                :name "Test"
                                :constructor (list "Hello")
                                :actions-on-return
                                (list ;; compiled fn
                                      #'identity
                                      ;; fn symbol
                                      'identity
                                      ;; lambda
                                      (lambda (x) "No-op" x)
                                      ;; command
                                      #'nothing
                                      ;; command symbol
                                      'nothing
                                      ;; anonymous commands
                                      (lambda-command id (x) "No-op" x)
                                      (lambda-mapped-command identity)
                                      (lambda-unmapped-command identity))))
``` 

![all-actions](https://user-images.githubusercontent.com/45483512/220928962-6c6a5112-9b18-4983-8d32-2f13b3c235dc.png)

**Comment by aadcg** [comment]
Personally, I'd answer no to both of the questions above. 

1. The `nil` action is the `identity` action in disguise. 
2. I'd say that we can suggest setting actions to commands, but we should not limit users in such a dramatic way.

**Comment by aadcg** [comment]
@ambrevar suggests the following with respect to Question 2:

> If it's about the user accidentally setting a function instead of a command, we could handle this in action-on-return-source and display a warning if a function is found instead of a command.

I agree with it.

**Comment by aartaka** [comment]
> 1. The `nil` action is the `identity` action in disguise.

Yes, and with worse UI :D

> 2. I'd say that we can suggest setting actions to commands, but we should not limit users in such a dramatic way.

That's why I suggested using `cerror` and allowed functions in 96a59794daef34bd8d09787bc68fcd441b7b0c1a. We have these errors and warnings for ourselves (to ensure Nyxt core is as polished as it can be), but user may do as they wish and use functions if they have to.

**Comment by Ambrevar** [comment]
> @Ambrevar suggests the following with respect to Question 2:
> 
> > If it's about the user accidentally setting a function instead of a command, we could handle this in action-on-return-source and display a warning if a function is found instead of a command.
> 
> I agree with it.

If we agree with this point, then if I understand correctly it is _not_ the approach that's taken in #2801, right?

**Comment by aadcg** [comment]
> Yes, and with worse UI :D

@aartaka, just to make sure we're on the same page: which UI is the worse?

> That's why I suggested using cerror and allowed functions in 96a5979. 

Off-topic: This is an important commit, but it would have made more sense to be delivered together with a PR that closes this issue.

> If we agree with this point, then if I understand correctly it is not the approach that's taken in #2801, right?

Yes, that is correct. Here's the problem. To take the approach you suggest, I think we need to close #2808. @aartaka is that your understanding too?

**Comment by aadcg** [comment]
Nonetheless, PR #2801, as it stands now, lays the foundation to implement this:

> If it's about the user accidentally setting a function instead of a command, we could handle this in action-on-return-source and display a warning if a function is found instead of a command.

Right now it is more lenient (accepts funcallables), but it's trivial to tweak it once the new commands arrive ( and #2808 is closed).

In that sense, I think that we could merge #2801 even though it does not fully adhere to what we want.

**Comment by Ambrevar** [comment]
I don't like #2801 because it adds a new level of indirection (`prompt-source`) for what seems to me unrelated to the problem.

It's very possible that I misunderstood what you are trying to fix, @aadcg 
For the recipe you gave in the original post, here is my one-liner suggestion: #2814.

If this is not what you are talking about, can you provide a new recipe for your problem?

**Comment by aadcg** [comment]
> I don't like #2801 because it adds a new level of indirection (prompt-source) for what seems to me unrelated to the problem.

I agree. I took that decision in an attempt to try to reach a consensus with @aartaka but, looking back, I regret it.

I think #2814 is moving in the right direction, but I still have some concerns. I'll expand on that in the PR!
