### ISSUE TITLE
Search engine?

### ISSUE THREAD

**Issue by lansingthomas** [atlas-engineer/nyxt#2795]
Dear Nyxt Warlocks,

While navigating with `open-url`
- the attribute `Search engine?` under `New URL or search query` is asking me a question. I don't know what question it is asking, or how to respond to an attribute in Nyxt.

In the spirit of clarity, I propose that we remove the `?` from `Search engine?` --> `Search engine`

IF I am missing something please let me know. 

Cool?

**Comment by aadcg** [comment]
I agree!
