### ISSUE TITLE
Inconsistent behavior between `prompter:next-source` and `prompter:previous-source`

### ISSUE THREAD

**Issue by aadcg** [atlas-engineer/nyxt#2796]
`prompter:next-source` returns NIL when the current source is the last one, while `prompter:previous-source` returns the first one when the current one is the first.

`prompter:previous-source` should return NIL when the current source is the first one.

**Comment by Ambrevar** [comment]
Or the other way around.  Returning a source has the benefit that one can chain function calls.

**Comment by aadcg** [comment]
I'll do it as you suggest!
