### ISSUE TITLE
yank a text string coming from Emacs on a focused field fails

### ISSUE THREAD

**Issue by fenix011** [atlas-engineer/nyxt#2800]
being emacs the text string origin, what might i be missing that is not allowing me  to yank a text
string on a focused field in super Nyxt browser not by means of mouse-clicking but keyboard shortcut ? 
thanks,
thanks, thanks beforehand!

**Comment by aartaka** [comment]
@fenix011?

**Comment by aartaka** [comment]
Does the `paste` command work for you? It's bound to `C-v` in CUA, `C-y` in Emacs mode, and to `p` in VI mode.

**Comment by fenix011** [comment]
No, it doesn't work for me neither  (i'm Guix OS here, Nyxt v 2.2.4 here - FYI )

**Comment by fenix011** [comment]
Uh. it works now... as long as this 'string text comes from an Emacs buffer'

Please, forget it. False alarm.

Thanks, thanks. thanks for the hackers browser !
