### ISSUE TITLE
Demeter is nonfunctional on Nyxt 3_pre3

### ISSUE THREAD

**Issue by supasonix-zuv** [atlas-engineer/nyxt#2806]
**Describe the bug**
Basically the title. On my desktop (Gentoo) and my laptop (Arch).  When I open the execute buffer and type 'demeter' nothing shows up, well, nothing related to Demeter does anyway. Demeter was working on Arch with the latest binary build 2.2.4-5 but in trying to nail down this issue I found the aur nyxt-git package had the same issue.  I know this is probably more of a demeter bug (if not user error) but unless I'm missing something there's no place to report bugs for it.

**Precise recipe to reproduce the issue**
install the package, install demeter to ~/.local/share/nyxt/extensions/Demeter (not nested), run nyxt, no demeter 

**Information**
- OS name+version:Gentoo 6.1.7 / Arch 6.1.12
- Graphics card and driver:6900xt+amdgpu / intel
- Desktop environment / Window manager name+version:Awesome
- How you installed Nyxt (Guix pack, package manager, build from source):Ebuild from source/pkgbuild from source
- Information from `show-system-information`:
`Nyxt version: 3
Renderer: GI-GTK
Operating system kernel: Linux 6.1.7-gentoo
Lisp implementation: SBCL 2.3.1 (Dynamic space size: 3221225472)
Features: (:NYXT-GI-GTK :NYXT-GTK :NYXT-GI-GTK :NYXT-GTK :NYXT-3 :SLYNK :PLUMP-UTF-32 :PARENSCRIPT :NSYMBOLS :FSET-EXT-STRINGS :NJSON :GLOBAL-VARS :DECLARE-TYPES :SBCL+SAFE-STANDARD-READTABLE :NAMED-READTABLES :SWANK :CL-FAD :LPARALLEL :21BIT-CHARS :CUSTOM-HASH-TABLE-NATIVE :CL-PPCRE-UNICODE :CL-UNICODE :CL-JSON-DOUBLE-FLOAT-IS-SUBSUMED :CL-JSON-SINGLE-FLOAT-IS-SUBSUMED :CL-PPCRE :CHUNGA :FLEXI-STREAMS :WEBKIT2 :WEBKIT2-2.38 :WEBKIT2-CORS-ALLOWLIST :WEBKIT2-PASTE-PLAINTEXT :WEBKIT2-TRACKING :WEBKIT2-MUTE :WEBKIT2-EMOJI :WEBKIT2-MEDIA :WEBKIT2-SANDBOXING :GTK-3-22 :GTK-3-20 :GTK-3-18 :GTK-3-16 :GTK-3-14 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6 :GTK-3-4 :GTK :GDK-3-22 :GDK-3-20 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12 :GDK-3-10 :GDK-3-8 :GDK-3-6 :GDK-3-4 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF :CLOSER-MOP :GLIB-2-30 :GLIB-2-32 :GLIB-2-34 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42 :GLIB-2-44 :GLIB-2-46 :GLIB-2-48 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56 :GLIB-2-58 :GLIB :BORDEAUX-THREADS :LPARALLEL.WITH-CLTL2 :LPARALLEL.WITH-CAS :LPARALLEL.WITH-STEALING-SCHEDULER :SPLIT-SEQUENCE CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64 CFFI-FEATURES:UNIX :CFFI CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP :FAST-IO-SV :FAST-IO :CL-JSON-CLOS :CL-JSON :SBCL-USES-SB-ROTATE-BYTE CHIPZ-SYSTEM:GRAY-STREAMS :THREAD-SUPPORT :ASDF3.3 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX :NON-BASE-CHARS-EXIST-P :ASDF-UNICODE :ARENA-ALLOCATOR :X86-64 :GENCGC :64-BIT :ANSI-CL :COMMON-LISP :ELF :IEEE-FLOATING-POINT :LINUX :LITTLE-ENDIAN :PACKAGE-LOCAL-NICKNAMES :SB-CORE-COMPRESSION :SB-LDB :SB-PACKAGE-LOCKS :SB-THREAD :SB-UNICODE :SBCL :UNIX)`

`ASDF version: 3.3.5
ASDF registries: (NYXT-SOURCE-REGISTRY ENVIRONMENT-SOURCE-REGISTRY)
Critical dependencies: (/var/tmp/portage/www-client/nyxt-3_pre3/work/nyxt-3-pre-release-3/_build/cl-cffi-gtk-e9a46df65995d9a16e6c8dbdc1e09b775eb4a966/gtk/cl-cffi-gtk.asd /var/tmp/portage/www-client/nyxt-3_pre3/work/nyxt-3-pre-release-3/_build/cl-gobject-introspection-d0136c8d9ade2560123af1fc55bbf70d2e3db539/cl-gobject-introspection.asd /var/tmp/portage/www-client/nyxt-3_pre3/work/nyxt-3-pre-release-3/_build/cl-webkit-bb0e15b513da28582314dd9efb2df38fee422f7e/webkit2/cl-webkit2.asd)`

**Output when started from a shell** Basically the same for both systems
`<INFO> [23:17:59] Source location: #P"/usr/local/share/"
<INFO> [23:17:59] Loading Lisp file #P"/home/username/.config/nyxt/auto-config.3.lisp".
<INFO> [23:17:59] Loading Lisp file #P"/home/username/.config/nyxt/config.lisp".
<INFO> [23:17:59] Listening to socket: #P"/run/user/1000/nyxt/nyxt.socket"
<INFO> [23:17:59] GTK extensions directory: #P"/usr/local/share/libraries/web-extensions/"
<INFO> [23:17:59] GTK extensions directory: #P"/usr/local/share/libraries/web-extensions/"
<INFO> [23:17:59] Loading #P"/home/username/.local/share/nyxt/history/default.lisp".
`

!
Might that 'Source location:' mean anything? There's nothing there on either system, no folder or files. After switching back to 2.2.4-5 on Arch I get 
`CL_SOURCE_REGISTRY:/home/username/.local/share/nyxt/extensions/Demeter/_build//:/the/same/path/again/nyxt/extensions` among other unimportant looking messages, and Demeter is functional again.

**Init.lisp config**
`(asdf:load-system :demeter)
(asdf:load-system :nx-fruit)`

**auto-config.3.lisp**
`(defmethod customize-instance ((browser browser) &key)`
`   (setf (slot-value browser 'theme) theme:+dark-theme+))`

I was going nearly crazy trying to figure out why I couldn't get Demeter to show up, hopefully it wasn't user error.

**Comment by supasonix-zuv** [comment]
Looks like fruit-of-the-day is also nonfunctional on 3_pre3, same exact scenario, although I didn't test it on nyxt-git on Arch. The fruit works on my nyxt 2.2.4-5 laptop, but doesn't on my nyxt 3_pre3 desktop.

**Comment by jmercouris** [comment]
Yes, those are designed for Nyxt 2, when Nyxt 3 is officially released, they will be updated :-)

**Comment by supasonix-zuv** [comment]
Ah, I see, thanks.
