### ISSUE TITLE
Update macro-edit mode

### ISSUE THREAD

**Issue by aartaka** [atlas-engineer/nyxt#2809]
Keyboard macros are a useful things and may be a good feature to have. But, for the last couple of releases, `edit-macro` page was broken. 531f19fbf4d9431260b0fc24bc0a24df31b1cdb5 fixes several severe bugs, but there's still a lot of work to do, given that `macro-edit-mode` has gone somewhat unmaintained. Things that are necessary to do:
- Move to a more regular and semantic layout (tables are _not_ intended for layout forcing).
- Add a macro-recording facility and integrate it with the `edit-macro` page.
- Inspect prompt-buffer events and record those too.

@jmercouris, macro editing is your brainchild, you interested in maintaining it?

EDIT: sever -> severe

**Comment by aadcg** [comment]
Suggestion: opening a PR with the changes introduced in 531f19f along with a basic test suite would be a good way to preventing similar problems in the future.

**Comment by aartaka** [comment]
@aadcg, but there's an enable-disable test-suite already (҂⌣̀_⌣́)

**Comment by aadcg** [comment]
> @aadcg, but there's an enable-disable test-suite already (҂⌣̀_⌣́)

I think you're saying that the test suit for the mode at hand is insufficient!

**Comment by aadcg** [comment]
Not a priority at the moment.
