### ISSUE TITLE
Modifier key for jump-scrolling sources and suggestions

### ISSUE THREAD

**Issue by lansingthomas** [atlas-engineer/nyxt#2816]
Dear Initiates of the Digital Secrets,

On call last week we discussed a way for our users to jump-scroll through
`Sources`
and `suggestions`
and `suggestions`
and `suggestions`

Please set up some bindings for this.

`Shift`+`down arrow` to select the topmost `suggestion` from the next `Source`
`Shift`+`up arrow` to select the topmost `suggestion` from the previous `Source`
`Shift`+`right arrow` to select the bottom `suggestion` in the current `Source`
`Shift`+`left arrow` to select the top `suggestion` in the current `Source`

Thank you : )

**Comment by lansingthomas** [comment]
comment updated for more precise language.

**Comment by aadcg** [comment]
@lansingthomas we need to clarity one little detail!

In your specification you mention:

> Shift+down arrow to select the **topmost** suggestion from the next Source
> Shift+up arrow to select the **topmost** suggestion from the previous Source

Currently, the behavior is different. When you go to the next source, the topmost suggestion is selected. But you to go to the previous source, the bottommost suggestion is selected.

Do you think that the behavior that I have described above is acceptable, or do you think that the user experience is enhanced by always selecting the topmost suggestion? Thanks.

**Comment by lansingthomas** [comment]
Great question,
Let's think about it. I sort of see a case for either.

### (1) the case for `shift`+`up arrow` moving to the top of a previous source
- I like that `shift`+`up arrow` and `shift`+`down arrow` always bring me to a to `Source` because users avoid landing at the bottom of a panel (stack of `suggestions`) with no header to remind them what that stack is about. 
- other accordions behave this way ([web accessibility initiative](url) recommends it, though I don't know why the convention exists)


### (2)the case for `shift`+`up arrow` moving to the bottom of a previous source
- this way the `shift` modifier helps users cross from `Source` to `Source` without scrolling -- I notice that `up arrow` without the `shift` modifier does the same thing. This could be nice for moving around with 7-9 suggestions, where no scrolling is happening.

### (3) a third path `shift`+`up arrow` moves to the top of the visible suggestions.
- helpfully resembles some other systems but, does not really match the structure of `Source` + `suggestion`

### My opinion after writing it out
I think option 1 (always selecting the topmost) is the best course of action. 

Sensible? Am I missing something? Perhaps you notice something when it is in front of you. 

Thanks @aadcg

**Comment by aadcg** [comment]
I agree with you 100% @lansingthomas. A very complete and deep analysis of yours, thank you!
