### ISSUE TITLE
Accordion for `Sources` in prompt buffer ui

### ISSUE THREAD

**Issue by lansingthomas** [atlas-engineer/nyxt#2818]
Dear Priests of the Transistor,

Last week we discussed a few ways to help users display the most relevant `suggestions` and to avoid excess scrolling in the prompt buffer UI. There was some positive consensus regarding collapsing and displaying `suggestions` within `sources`

My view is that an accordion like this does a good job of providing lots of info early, and leaving it up to the user to determine what is important for them in that moment.

Please provide a nice collapsing-accordion feature for our `Sources`
### might look like:
![Accordion (1)](https://user-images.githubusercontent.com/6666079/221642002-ae057721-25c5-4039-8939-b8836b27a1a5.png)

### This feature:
- [ ] must visually communicate status {open, closed} with an icon
   - perhaps with a `-` for open-state (to show that clicking the `-` will remove `suggestions`
   - perhaps with a `⋁` for closed-state (to show that clicking the `∨` will provide more `suggestions`
- [ ] must collapse the `suggestions` and `attribute column titles` of a `Source` when a user clicks the `-` icon
- [ ] must display the `suggestions`  and `attribute column titles` of a `Source` when a user clicks the `∨` icon
- [ ] IF the user collapses a `Source` WHILE their blue selector is targeting a `suggestion` within that `Source` the blue selector should move to the top `suggestion` of the next open-status `Source`
- [ ] should have a hover area behind the icons to communicate that icons are clickable buttons.

### regarding the icon choices
- I like a minus `-` because it communicates the removal of options
- I like a `∨` because it resembles a down arrow -- which communicates that more suggestions exist below.  It is a visualization of the logical operator for OR -- which gives a sense of providing alternative suggestions.
   - I see a case where we might use a `+` symbol here, but I would like to start with a `∨` because I want to leave the `+` available for another purpose (add/subtract attribute-columns) in a future time.

Thank you : )

**Comment by aartaka** [comment]
I'm not sure...

**Comment by aadcg** [comment]
Let's vote. A decision is better than no decision.

I'm against, @lansingthomas is for. @aartaka is not sure.

@jmercouris and @Ambrevar: we're interested in your thoughts.

**Comment by Ambrevar** [comment]
I'm OK with having it in, but not collapse anything by default.

In the long run, we could have full-page, long-lived prompters where this feature would be very useful.

**Comment by aadcg** [comment]
I think I've understood why I don't see the need to implement this. 

The structure of suggestions in the prompt buffer is very simple. There are sources and each source has suggestions. This is not a complex tree structure with an arbitrary level of nestedness. Plus, the cursor is **only** placed on the suggestions. The source titles are purely informative. In other words, navigating suggestions in the prompt buffer is actually like navigating a flat list where subsets of the list have labels (=sources). Think of a supermarket buying list where there are categories like vegetables or dairy products.

I think that collapsing is very helpful when navigating hierarchic data like trees.

If I have my cursor at the first suggestion of the 2nd source and the 1st source is collapsed, the only extra piece of information I get is the title of the 1st source. But I don't see much benefit in it. Plus the extra burden of collapsing and expanding each source. Sounds like over engineering to me.

I agree with @Ambrevar that if such a feature would exist, it would make sense to collapse sources by default.

**Comment by jmercouris** [comment]
Slight correction, I believe Pierre said that no sources should be collapsed by default :-D

**Comment by aadcg** [comment]
Oops, that's a typo. In my  message above I was agreeing with @Ambrevar. I'll edit it.

**Comment by lansingthomas** [comment]
Let's NOT do it.
Thank you. We have other priorities, and I have failed to provide evidence that this is an improvement.
