### ISSUE TITLE
Clickable suggestion marking

### ISSUE THREAD

**Issue by lansingthomas** [atlas-engineer/nyxt#2819]
Brothers Of The Keyboard,

Last week we discussed WHEN `suggestion` marking happens and HOW to provide some more intuitive options for it.

Please add a feature to `control` + `click` for marking and unmarking `suggestions` in the prompt buffer.

the rationale: 
- doing this with the mouse shows the transition from unmarked-grey to marked-grey which helps users understand the marking system (typically this is covered by the blue selection color.)
- providing a few ways to get the job done is helpful for our users
- someone (either @aadcg  or @jmercouris )was good to point out that users will be familiar with `control` +`click` in this way from other applications.

Thank you! :D

**Comment by aartaka** [comment]
Hm, it's fun that it used to work, but apparently is broken for some reason. I guess a refactoring is due in this part of the code.
