### ISSUE TITLE
buffers-panel easy UI update

### ISSUE THREAD

**Issue by lansingthomas** [atlas-engineer/nyxt#2838]
The `buffers-panel` command invokes a nice sidebar for navigation.

- [ ] Can I get a clickable exit?
   - just a corner X that displays when a user mouse-hovers over the side panel, and kills the sidepanel when clicked.

**Comment by lansingthomas** [comment]
I notice this same thing with other side panels. Could a feature here apply to the whole group of side-buffers?

**Comment by aartaka** [comment]
I've gone with the constant X so that one doesn't have to hover over it to know it's there.

**Comment by aadcg** [comment]
@aartaka one suggestion: as you know, our UI expert isn't an engineer and oftentimes the only way he has to validate the implementation of his specification is via screenshots. With that in mind, it seems sensible to open a PR, attach some screenshots and wait for @lansingthomas' feedback.

Also, your commit message says `"Quite a hack, though."`. That seems to suggest that a second look from another engineer wouldn't hurt :)

CC @jmercouris.

**Comment by lansingthomas** [comment]
Thank you for the feature!

The hover-ability thing is important. 

#### My reasoning:
There are two schools of thought relevant for this decision. [1] Minimal Design, and [2] Immediate Recognizability.

[1] the principle of minimal design would suggest that we not show the `X` because is clutters the screen real estate.
[2] the principle of recognizability would suggest that we DO show the `X` so users can immediately see the feature (and they do not need to remember it or learn anything new to use it)

Understanding that these conclusions are at odds; We can reasonably expect our users (while seeking a clickable exit) to hover over the side panel buffer. So I conclude that we should have a visible only on hover `X` button. 


otherwise I like the look of it. Thank you.

**Comment by lansingthomas** [comment]
Thank you for your attention here @aartaka and @aadcg -- I know this is not the most important priority, but it is nice to stay on top of things as they come up. Else we get a backlog of usability issues greater than the sum of it's parts.

**Comment by aartaka** [comment]
( ͡° ͜ʖ ͡°)
