### ISSUE TITLE
C-s-tab | C-shift-tab | switch-buffer-previous in CUA

### ISSUE THREAD

**Issue by lansingthomas** [atlas-engineer/nyxt#2839]
Dear Computer Cowboys,
I believe this is an error in the CUA binding scheme. Please let me know If it is user error.

I am interpreting _C-s-tab_ for `switch-buffer-previous` as `Control` + `shift` + `tab`.

the binding seems to be set to `Control` + `s` + `tab`

IF the binding is supposed to be `shift` not `s` would someone special please fix it : )

Thank you.

**Comment by aartaka** [comment]
CC @Ambrevar. This bug seems to be somewhere in between `dispatch-input-event` and `nkeymaps`.

**Comment by Ambrevar** [comment]
Fixed with 2e401362ca385ab5bd086c5c9899c4cf62485792.

**Comment by aartaka** [comment]
Cool, thanks Pierre!
