### ISSUE TITLE
Some Stars are Brighter than Others

### ISSUE THREAD

**Issue by lansingthomas** [atlas-engineer/nyxt#2850]
**Purpose**
Minimize unused UI elements

**What is your proposed change?**
Remove the bookmark-star from the `Prompt-buffer` in the default configuration. 

**Rationale**
- For the star to be useful, it needs to be meaningfully improved. -- which is not a high priority at this stage.
- FOR NOW :: I think we are better off relying on the other ways for users to bookmark pages. 
- For the star to be useful, users must know how to access the bookmarks with `list-bookmarks` ... it is safe to assume they can figure out `bookmark-url` or `bookmark-current-url` or `bookmark-buffer-url`.

_I expect to be opening some more suggestions for the bookmarking system soon : )_

**Constraints**
removal of the star should not upset the function or form of other things. 

**Additional context/User story**
As a user hoping to bookmark a URL, and preferring to use my keyboard, I have so many options better than the star.

**Screenshots/Mock ups**
![the star](https://user-images.githubusercontent.com/6666079/225137849-4f88a382-d80d-4286-854b-8326a5caa05a.png)

# Pre-Build Checklist:
- [x] I have consulted with the team. {John, }
- [x] One or more developers have signed off on this change.
- [x] One or more user researchers have signed off on this change. {self}

**Comment by aadcg** [comment]
Sounds reasonable to me.

**Comment by aartaka** [comment]
How about rebinding that star to open the `list-bookmarks` menu instead?

**Comment by lansingthomas** [comment]
Seeking a majority 3/5
OR
other proposals

Myself
- [x] votes option 1
- [ ] votes option 2
- [ ] votes option 3
- [ ] votes No Action - to leave the star as is

@jmercouris (please read all comments then vote)
- [ ] votes option 1
- [ ] votes option 2
- [ ] votes option 3
- [ ] votes No Action - to leave the star as is

@Ambrevar (please read all comments then vote)
- [ ] votes option 1
- [ ] votes option 2
- [ ] votes option 3
- [ ] votes No Action - to leave the star as is

@aadcg (please read all comments then vote)
- [ ] votes option 1
- [ ] votes option 2
- [ ] votes option 3
- [ ] votes No Action - to leave the star as is

@aartaka (please read all comments then vote)
- [ ] votes option 1
- [ ] votes option 2
- [ ] votes option 3
- [ ] votes No Action - to leave the star as is

**Comment by aartaka** [comment]
All decided then :D

**Comment by lansingthomas** [comment]
Alright! Pre-build checklist complete! UI feature activated!

**Comment by jmercouris** [comment]
Closed with: 141f84332
