### ISSUE TITLE
Blank web page when using WebKitGTK 2.38.5

### ISSUE THREAD

**Issue by lansingthomas** [atlas-engineer/nyxt#2851]
Hopefully this video effectively communicates this bug.

https://user-images.githubusercontent.com/6666079/225139053-4741f92d-dff6-4aac-bf0d-109164ee3fa7.mp4

Nyxt ver 3 pre4 from source code
Ubuntu 22.04.2 LTS

**Comment by aadcg** [comment]
I've actually seen this too as I was as baffled as you are :D

**Comment by aartaka** [comment]
Yes. Seems to be a WebKit side problem.

**Comment by aadcg** [comment]
I'm not sure whether it's related but I've been working with Nyxt today in similar ways that I did some days ago and I'm seeing all sorts of strange things such as:

```log
There is no applicable method for the generic function
  #<STANDARD-GENERIC-FUNCTION NYXT/RENDERER/GTK::ON-SIGNAL-KEY-PRESS-EVENT (1)>
when called with arguments
  (#<NYXT:WINDOW 1050 {1004F819C3}>
   #S(GDK:GDK-EVENT-KEY
      :TYPE :KEY-PRESS
      :WINDOW #<GDK:GDK-WINDOW {1004DAC1F3}>
      :SEND-EVENT NIL
      :TIME 168380592
      :STATE NIL
      :KEYVAL 65515
      :LENGTH 0
      :STRING ""
      :HARDWARE-KEYCODE 133
      :GROUP 0
      :IS-MODIFIER 0)).
   [Condition of type SB-PCL::NO-APPLICABLE-METHOD-ERROR]

Restarts:
 0: [RETRY] Retry calling the generic function.
 1: [RETURN-FROM-G-CLOSURE] Return value from closure
 2: [ABORT] abort thread (#<THREAD "Nyxt renderer thread" RUNNING {1004B18003}>)

Backtrace:
 0: ((:METHOD NO-APPLICABLE-METHOD (T)) #<STANDARD-GENERIC-FUNCTION NYXT/RENDERER/GTK::ON-SIGNAL-KEY-PRESS-EVENT (1)> #<NYXT:WINDOW 1050 {1004F819C3}> #S(GDK:GDK-EVENT-KEY :TYPE :KEY-PRESS :WINDOW #<GDK:G..
 1: (SB-PCL::CALL-NO-APPLICABLE-METHOD #<STANDARD-GENERIC-FUNCTION NYXT/RENDERER/GTK::ON-SIGNAL-KEY-PRESS-EVENT (1)> (#<NYXT:WINDOW 1050 {1004F819C3}> #S(GDK:GDK-EVENT-KEY :TYPE :KEY-PRESS :WINDOW #<GDK:G..
 2: ((LAMBDA (NYXT/RENDERER/GTK::WIDGET NYXT/RENDERER/GTK::EVENT) :IN NYXT:CUSTOMIZE-INSTANCE) #<unused argument> #S(GDK:GDK-EVENT-KEY :TYPE :KEY-PRESS :WINDOW #<GDK:GDK-WINDOW {1004DAC1F3}> :SEND-EVENT N..
      Locals:
        NYXT/RENDERER/GTK::EVENT = #S(GDK:GDK-EVENT-KEY ..)
 3: (GOBJECT::CALL-WITH-RESTARTS #<FUNCTION (LAMBDA (NYXT/RENDERER/GTK::WIDGET NYXT/RENDERER/GTK::EVENT) :IN NYXT:CUSTOMIZE-INSTANCE) {10059A273B}> (#<GTK:GTK-WINDOW {1004DAC113}> #S(GDK:GDK-EVENT-KEY :TY..
 4: ((LAMBDA (GOBJECT::CLOSURE GOBJECT::RETURN-VALUE GOBJECT::COUNT-OF-ARGS GOBJECT::ARGS GOBJECT::INVOCATION-HINT GOBJECT::MARSHAL-DATA) :IN "/gnu/store/qa0rc56xjnvgxy0ydskdzy86jjxs9hlz-cl-cffi-gtk-0.11...
 5: ((LAMBDA (SB-ALIEN::ARGS-POINTER SB-ALIEN::RESULT-POINTER FUNCTION) :IN "/gnu/store/qa0rc56xjnvgxy0ydskdzy86jjxs9hlz-cl-cffi-gtk-0.11.2-2.e9a46df/share/common-lisp/source/cl-cffi-gtk/gobject/gobject.s..
 6: ("foreign function: funcall_alien_callback")
 7: ("foreign function: #x5000097B")
 8: ("foreign function: cfree")
 9: ((LAMBDA (&REST GIR::ARGS-IN) :IN GIR::BUILD-FUNCTION))
10: ((FLET NYXT/RENDERER/GI-GTK::MAIN-FUNC :IN NYXT:FFI-INITIALIZE))
11: ((LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS))
12: ((FLET SB-UNIX::BODY :IN SB-THREAD::RUN))
13: ((FLET "WITHOUT-INTERRUPTS-BODY-156" :IN SB-THREAD::RUN))
14: ((FLET SB-UNIX::BODY :IN SB-THREAD::RUN))
15: ((FLET "WITHOUT-INTERRUPTS-BODY-149" :IN SB-THREAD::RUN))
16: (SB-THREAD::RUN)
17: ("foreign function: call_into_lisp_")
18: ("foreign function: funcall1")
```

**Comment by Ambrevar** [comment]
I believe the issue is that WebKit does not like to have its web view resized during loads.  It's a webkit problem, sure, but could we work around it nonetheless?

Other browser don't have this problem because... they don't have a resizing prompt buffer!  So if some how we could render the prompt buffer without resizing the web view, this should fix it.

**Comment by aadcg** [comment]
@Ambrevar was it always the case or did WebKit change it suddenly (with respect to web view resizing during loads)?

I ask, because I've only started to observe this behavior recently.  

For instance, when I do:

- `(asdf:load-system :nyxt/gi-gtk)`
- `(nyxt:start :failsafe t :urls '(https://github.com))`

I get a blank screen. But if I split the frame, then the buffer becomes visible.

**Comment by aadcg** [comment]
@Ambrevar after a bit more investigation, I've observed the following. In browsers relying on WebKitGTK (I tested with surf and Epiphany) there are problems with github specifically. This proves that it's not coming from our side.  Now the question is: is there a problem with how webkitgtk is packaged on Guix or is it coming from webkitgtk itself?

Notice that when @lansingthomas reports that he's running Nyxt from source he's also using Guix. I gave him a recipe where he pulls from master and then runs `guix package --install-from-file=build-scripts/nyxt.scm`.

We need feedback from someone who is not on Guix. @jmercouris, can you reproduce the reported bug?

**Comment by jmercouris** [comment]
I can confirm the bug! I tried in epiphany.

**Comment by lansingthomas** [comment]
@aadcg just to head off any assumptions beyond my understanding. I am no longer using the Guix recipe. There were some issues related to having multiple versions of Nyxt on my Ubuntu machine and I had to reinstall the OS. I am installing directly from the .tar

**Comment by aadcg** [comment]
@lansingthomas, thanks for clarifying.

**Comment by aadcg** [comment]
I had yet another look at this issue, and it seems that a concrete webkitgtk version, 2.38.5, is the culprit.  @jmercouris you mentioned you were able to confirm the bug. Could you check the webkitgtk version you're running.

I think that versions 2.38.3 or 2.38.4 don't suffer from this issue.

Additionally, I run the official epiphany Flatpak and it runs smoothly. It ships with webkitgtk 2.40.0. Notice that this release is a stable one. I'll reach out to Guix and advice to bump the version.

**Comment by aadcg** [comment]
I've added the 3.0 tag since we need to ensure that we're shipping Nyxt with a webkitgtk version that doesn't suffer from this serious bug. We need to guarantee it for the following deliverables: 

- Guix (affects `guix pack` and installation via package manager);
- Flatpak.

**Comment by aadcg** [comment]
[Guix is soon updating to the latest stable webkitgtk version](https://issues.guix.gnu.org/62415#8).

**Comment by tekakutli** [comment]
webkitgtk got upgraded to 2.40.0, that's the good news

unfortunately now my nyxt doesn't start

I think this is the core of the terminal error message
```
** (nyxt:8457): ERROR **: 16:23:30.510: Unable to configure xdg-desktop-portal access in the WebKit sandbox: GApplication is required.
```

**Comment by aartaka** [comment]
That is either:
- WebKit sandboxing problem. Have you tried deleting libnyxt.so from the installation output?
- Or some SBCL issue we had emerging here and there for ages yet again. Maybe update SBCL and reinstall, although there seems to be no reliable recipe here.
  - Interestingly, we do catch and ignore all the errors that get signaled in FFI methods. This one was indeed caught. It should've been safely ignored. But it wasn't. Which proves the hypothesis that it came from inside SBCL and was critical enough to break the process even when caught and ignored.

**Comment by Ambrevar** [comment]
@tekakutli What happens after the output you've posted?  Does it hang there or does it return to a new shell prompt?

**Comment by Ambrevar** [comment]
@aartaka It does not crash, and we see from the backtrace that `echo-warning` handles the FFI error.  So Nyxt seems to behave well here, it's an FFI error.

**Comment by tekakutli** [comment]
I removed my config files, still doesn't spawn, but now it only flashes once
the terminal error changed
```

(process:13919): Gtk-WARNING **: 11:48:56.726: Locale not supported by C library.
	Using the fallback 'C' locale.
Nyxt version 3
<INFO> [11:48:56] Source location: #P"/gnu/store/1j5vcvnxdbni0jhr9i4df285nd1b2pcv-nyxt-3-pre-release-5-34-g78416249/share/"
<INFO> [11:48:56] Listening to socket: #P"/run/user/1000/nyxt/nyxt.socket"

** (nyxt:13919): WARNING **: 11:48:57.005: WEBKIT_FORCE_SANDBOX no longer allows disabling the sandbox. Use WEBKIT_DISABLE_SANDBOX_THIS_IS_DANGEROUS=1 instead.
<INFO> [11:48:57] GTK extensions directory: #P"/gnu/store/1j5vcvnxdbni0jhr9i4df285nd1b2pcv-nyxt-3-pre-release-5-34-g78416249/lib/nyxt/"
<INFO> [11:48:57] GTK extensions directory: #P"/gnu/store/1j5vcvnxdbni0jhr9i4df285nd1b2pcv-nyxt-3-pre-release-5-34-g78416249/lib/nyxt/"

** (nyxt:13919): ERROR **: 11:48:57.422: Unable to configure xdg-desktop-portal access in the WebKit sandbox: GApplication is required.
<WARN> [11:48:57] Warning: Error in FFI method: The value
  :INVALID-CODE-OBJECT-AT-PC
is not of type
  (SIMPLE-ARRAY (COMPLEX DOUBLE-FLOAT) (*))

** (process:13919): ERROR (recursed) **: Unable to configure xdg-desktop-portal access in the WebKit sandbox: GApplication is required.fatal error encountered in SBCL pid 13919 tid 13932:
SIGABRT received.

   0: fp=0x2 pc=0x7fce8328e030 Foreign function gsignal
```

**Comment by tekakutli** [comment]
doing export WEBKIT_DISABLE_SANDBOX_THIS_IS_DANGEROUS=1 works, it opened up

**Comment by Ambrevar** [comment]
@tekakutli Can you try building the #2897 branch and see if it works without having to export `WEBKIT_DISABLE_SANDBOX_THIS_IS_DANGEROUS=1` ?

**Comment by tekakutli** [comment]
@Ambrevar didnt work, I tried by removing everything too

```
nyxt $guix remove nyxt
The following package will be removed:
   nyxt 3-pre-release-5-37-ga8aa8b24
nyxt $guix gc
nyxt $git pull
Already up to date.
nyxt $git reset --hard origin/remove-web-extension-lib
HEAD is now at a8aa8b24 libraries/web-extensions/README: Mention under-maintenance.
nyxt $guix package --install-from-file=build-scripts/nyxt.scm
The following package will be upgraded:
   nyxt (dependencies or package changed)

nothing to be done
nyxt $nyxt

(process:22615): Gtk-WARNING **: 07:45:39.313: Locale not supported by C library.
	Using the fallback 'C' locale.
Nyxt version 3
<INFO> [07:45:39] Source location: #P"/gnu/store/3p8s6x3ff3iz2rmxa01r88bc09jp26gd-nyxt-3-pre-release-5-37-ga8aa8b24/share/"
<INFO> [07:45:39] Listening to socket: #P"/run/user/1000/nyxt/nyxt.socket"

** (nyxt:22615): WARNING **: 07:45:39.574: WEBKIT_FORCE_SANDBOX no longer allows disabling the sandbox. Use WEBKIT_DISABLE_SANDBOX_THIS_IS_DANGEROUS=1 instead.
<INFO> [07:45:39] GTK extensions directory: #P"/gnu/store/3p8s6x3ff3iz2rmxa01r88bc09jp26gd-nyxt-3-pre-release-5-37-ga8aa8b24/share/libraries/web-extensions/"
<INFO> [07:45:39] GTK extensions directory: #P"/gnu/store/3p8s6x3ff3iz2rmxa01r88bc09jp26gd-nyxt-3-pre-release-5-37-ga8aa8b24/share/libraries/web-extensions/"

** (nyxt:22615): ERROR **: 07:45:40.002: Unable to configure xdg-desktop-portal access in the WebKit sandbox: GApplication is required.
<WARN> [07:45:40] Warning: Error in FFI method: The value
  :INVALID-CODE-OBJECT-AT-PC
is not of type
  (SIMPLE-ARRAY (COMPLEX DOUBLE-FLOAT) (*))

** (process:22615): ERROR (recursed) **: Unable to configure xdg-desktop-portal access in the WebKit sandbox: GApplication is required.fatal error encountered in SBCL pid 22615 tid 22628:
SIGABRT received.

   0: fp=0x2 pc=0x7ff7c51f1030 Foreign function gsignal
```

**Comment by aartaka** [comment]
So we actually need GApplication.

**Comment by aadcg** [comment]
Release notes of both WebkitGTK 2.40.1 and WebkitGTK 2.38.6 include the following note:

> The Bubblewrap sandbox no longer requires setting an application identifier via GApplication to operate correctly. Using GApplication is still recommended, but optional

**Comment by aartaka** [comment]
> Hm, that does seem to be relevant. I wonder why they had this requirement to begin with? It does seem orthogonal to me.

Because that's how the activity and files relating to applications can be managed, I guess.

**Comment by aadcg** [comment]
Guix has bumped webkitgtk version to 2.40.1, so this issue won't creep into our standalone bundle.
