### ISSUE TITLE
Strip down the PR template

### ISSUE THREAD

**Issue by aartaka** [atlas-engineer/nyxt#2857]
[Our pull request checklist is too long and intimidating to be filled in full.](https://github.com/atlas-engineer/nyxt/pull/2854#issuecomment-1471289975) Maybe we should strip it down by removing the "obvious" parts. My candidates are:
- [ ] I have pulled from master before submitting this PR ,
  - We always check that the branch is rebased over master before merging. 
- [ ] There are no merge conflicts.
  - This we do too, because all of use use `no-ff` option of `git merge`.
- [ ] My code follows the style guidelines for Common Lisp code. See...
  - All of the team are versed and consistent in CL, and if something is non-conventional in contributor's code, we say it right away, so no need to retain this part. It's in developer manual anyway.
- [ ] I have performed a self-review of my own code.
  - This is kinda obvious, I guess—if someone makes a change, they likely written it consciously and reviewed it in the process.
- [ ] All my code has docstrings and `:documentation`s written in the aforementioned style.  (It's OK to skip the docstring for really trivial parts.)
  - This one we should actually add a test for (on the side of `nasdf`): check that all the exported symbols have documentation.
- [ ] I have commented my code in hard-to-understand areas.
  - This one we also do/ask ourselves during the review. 

CC @jmercouris, @Ambrevar

**Comment by Ambrevar** [comment]
From my point of view, the PR list is mostly targeting newcomers.  As such, it's a helpful reminded of all the points a newcomer might miss.

For instance, without the first point the PR might not be based on master.  Upon seeing this point, the newcomer would then rebase it.  Compare this to us having to ask for a rebase: this saves an iteration.

Overall, I'd keep all points, I believe they are all significant.

**Comment by aadcg** [comment]
My only suggestion would be to reduce the number of checkboxes, but not the text itself! As @Ambrevar mentioned, all points are relevant. I am suggesting something like:

- [ ] Git stuff
  - check 1
  - check 2
  - ...
- [ ] Docs
  - check 1
  - check 2
  - ...
- [ ] ...

I think that toggling less checkboxes would be a plus both for new and frequent contributors!

**Comment by Ambrevar** [comment]
Yes, that's a good point.

**Comment by aartaka** [comment]
Fair, yes. Although manually clicking through every single checkbox and focusing my attention on those has saved me form incomplete PRs a countless number of times :D

But yes, grouping of checkboxes it is then. I'll push an update soon-ish.

**Comment by aartaka** [comment]
Fixed with a0c55d52a9d2c51d8a0d438d3cc2b4936f42988a
