### ISSUE TITLE
`(asdf:test-system :nyxt/gi-gtk)` and CI

### ISSUE THREAD

**Issue by aadcg** [atlas-engineer/nyxt#2858]
Correct me if I'm wrong, but it seems that the tests relative to the system `nyxt/gi-gtk` don't run in the CI.

I'm wondering about the rationale behind it.

 CC @Ambrevar.

**Comment by Ambrevar** [comment]
Because I do not know how to run Xorg in the CI, and thus the nyxt/gi-gtk fail automatically (WebKit complains).

**Comment by aadcg** [comment]
Of course! Now it all makes sense. 

For this test in particular, it's extremely important to run it locally then.

**Comment by Ambrevar** [comment]
Or to figure out how to run it in the CI!  We're not the first ones to run into this issue on GitHub, should be relatively straightforward to fix!

**Comment by aadcg** [comment]
Absolutely, I meant it as a temporary workaround!
