### ISSUE TITLE
Remove `background-color-alternate` color.

### ISSUE THREAD

**Issue by aartaka** [atlas-engineer/nyxt#2861]
We've talked about it with @jmercouris, and it seems there are not much use-cases/justification for the recently (#2854) added theme color—`theme:background-color-alternate`. More so: 
- semantics of this color as the alternate background are not exactly clear
  - If it's an alternative to `background-color`, why are there no alternatives for other colors?
  - In which context is it alternative, what for? Does it work exactly as `background-color`, can it be substituted for it in all the uses? 
    - Here my understanding of what "alternat(e|ive) color" means may be erroneous, so I'd benefit from a small English lesson here.
- It's not documented, neither in `libraries/theme/README.org`, nor in the `manual`.

I challenge @jmercouris to list all the uses there are for this color. I may be absolutely unaware of those and opposing the new color due to ingorance. If there's enough use-cases for the new color where there's no other option but introducing it, l will be happy retain it. Otherwise, let's revert it due to uselessness.

CC @aadcg

**Comment by aadcg** [comment]
Is it not true that we're already using an nuanced version of `background-color`? For instance, look at how tabs are styled. We're using dirty hacks to achieve that, which doesn't make much sense.

> If it's an alternative to background-color, why are there no alternatives for other colors?

There's no evidence that we need alternative color for any of the colors, expect background.

> I challenge @jmercouris to list all the uses there are for this color.

I don't think this is an appropriate way of framing the situation. First and foremost, we have a UI specialist @lansingthomas and he has mentioned the need for a nuanced background color. If you think that there's a better of doing it, then you need to show it. 

For instance, how do you avoid introducing the background color of the UI element in red? 

![2023-03-17_18:19:08](https://user-images.githubusercontent.com/45483512/225961259-e5764795-2544-4bd0-ac55-b4f23fa3f78c.png)

**Comment by jmercouris** [comment]
Of course we *could* do most of those things another way, but that would be a suboptimal solution with regards to the UI. We are severely limiting ourselves. More colors in our palette would allow for more complex, richer UIs, that are more intuitive.

I understand that this results in reasoned designs, creativity and the like, but I believe we need to loosen these constraints in pursuit of a superior product.

Consider this document from Apple (which I deign as an authority on UI/design): https://developer.apple.com/design/human-interface-guidelines/foundations/color

This document which describes using colors sparingly defines the following table of colors:

```


Alternate selected control text color | The text on a selected surface in a list or table. | alternateSelectedControlTextColor
-- | -- | --
Alternating content background colors | The backgrounds of alternating rows or columns in a list, table, or collection view. | alternatingContentBackgroundColors
Control accent | The accent color selected by the user in System Settings. | controlAccent
Control background color | The background of a large interface element, such as a browser or table. | controlBackgroundColor
Control color | The surface of a control. | controlColor
Control text color | The text of a control that is enabled. | controlTextColor
Current control tint | The system-defined control tint. | currentControlTint
Disabled control text color | The text of a control that’s disabled. | disabledControlTextColor
Find highlight color | The color of a find indicator. | findHighlightColor
Grid color | The gridlines of an interface element, such as a table. | gridColor
Header text color | The text of a header cell in a table. | headerTextColor
Highlight color | The virtual light source onscreen. | highlightColor
Keyboard focus indicator color | The ring that appears around the currently focused control when using the keyboard for interface navigation. | keyboardFocusIndicatorColor
Label color | The text of a label containing primary content. | labelColor
Link color | A link to other content. | linkColor
Placeholder text color | A placeholder string in a control or text view. | placeholderTextColor
Quaternary label color | The text of a label of lesser importance than a tertiary label, such as watermark text. | quaternaryLabelColor
Scrubber textured background color | The background of a scrubber in the Touch Bar. For guidance, see Touch Bar > Visual Design > Color. | scrubberTexturedBackgroundColor
Secondary label color | The text of a label of lesser importance than a primary label,  such as a label used to represent a subheading or additional  information. | secondaryLabelColor
Selected content background color | The background for selected content in a key window or view. | selectedContentBackgroundColor
Selected control color | The surface of a selected control. | selectedControlColor
Selected control text color | The text of a selected control. | selectedControlTextColor
Selected menu item text color | The text of a selected menu. | selectedMenuItemTextColor
Selected text background color | The background of selected text. | selectedTextBackgroundColor
Selected text color | The color for selected text. | selectedTextColor
Separator color | A separator between different sections of content. | separatorColor
Shadow color | The virtual shadow cast by a raised object onscreen. | shadowColor
Tertiary label color | The text of a label of lesser importance than a secondary label, such as a label used to represent disabled text. | tertiaryLabelColor
Text background color | The background color behind text. | textBackgroundColor
Text color | The text in a document. | textColor
Under page background color | The background behind a document’s content. | underPageBackgroundColor
Unemphasized selected content background color | The selected content in a non-key window or view. | unemphasizedSelectedContentBackgroundColor
Unemphasized selected text background color | A background for selected text in a non-key window or view. | unemphasizedSelectedTextBackgroundColor
Unemphasized selected text color | Selected text in a non-key window or view. | unemphasizedSelectedTextColor
Window background color | The background of a window. | windowBackgroundColor
Window frame text color | The text in the window’s title bar area. | windowFrameTextColor

```

these are SIGNIFICANTLY more colors than we have. It would probably be a good model with which to design our colors. We are developing an operating system, and we need a way to express ourselves!

**Comment by aadcg** [comment]
@jmercouris, I took the liberty to edit the table you're showing in the comment above. This is a one of a kind situation, since I never edit other people's comments for obvious reasons :)

**Comment by jmercouris** [comment]
Thank you :-)

**Comment by aartaka** [comment]
First, let me restate my values in regard to themes:
- Accessibility: we should have all our colors to be contrasting enough with both their `on-` colors and with as many other theme colors as possible.
- Consistency: if we introduce a new entity for a certain use-case, then we probably should bring all of the theme up to date to be compatible with this use-case.
- Minimalism/simplicity: if we can avoid the new color by dumbing down our interfaces, then we should do it. Because if there's only one interface that requires new colors, widgets, interface-specific logic, and lots of supporting code... then this interface is likely over-engineered and should be simplified.

> Is it not true that we're already using an nuanced version of `background-color`? For instance, look at how tabs are styled. We're using dirty hacks to achieve that, which doesn't make much sense.
> 
> > If it's an alternative to background-color, why are there no alternatives for other colors?
> 
> There's no evidence that we need alternative color for any of the colors, expect background.

@aadcg, continuing your (inductive) logic about tabs: we need alternatives for every color in the theme, exactly because we would end up with "dirty hacks" for every single one of them too (think about styling buttons in `secondary` and `accent` colors—that, much like tabs, is doomed to need an alternative hover color instead of "dirty hacks"). Which gives us the first course of action:

1. Introduce alternative colors for all the theme colors for consistency.

> For instance, how do you avoid introducing the background color of the UI element in red?
> 
> ![2023-03-17_18:19:08](https://user-images.githubusercontent.com/45483512/225961259-e5764795-2544-4bd0-ac55-b4f23fa3f78c.png)

I've suggested three options (with more being possible in the given circumstances) in https://github.com/atlas-engineer/nyxt/pull/2855#issuecomment-1471627958

Now, answering @jmercouris:

> I would make the argument that the quantity of places something appears is not a direct measure of its importance. Regardless, I concede that Andre has a much better reasoning than me.

Quantity of places is a direct measure for whether the color should be added. Because if there's one place that needs the new color direly, it's likely that it doesn't and will be better off with an existing one. @aadcg seems to also use the quantitative reasoning when saying that there's "no evidence that we need alternative color for any of the colors, except background." Using the quantitative reasoning as applied to (insufficient) amount of use-cases listed below, I see a second option:

2. Removing this new color altogether, because we can happily live without it.

> Conjecture, ten places we could use a nuanced background color:
>     1. Hover in the prompt buffer

This I can agree with, because the current colors are too radical to be used for a light hover effect. And it's exactly because of these colors that I opposed the hover effect—it looks overly eye-catching.

However, for this case the initial draft of changing the hovered attribute text to bold would make even more sense than the colored background.

Still counts, though. One.

>     2. Unselected tabs

Two.

>     3. Code in the manual

Three.

>     4. The message area

Four. Although this problem is by no means solved by simply adding a new color, as I've already stated in https://github.com/atlas-engineer/nyxt/issues/2719#issuecomment-1403247865

>     5. Hover highlighting for buttons

Does `background-color-alternate` apply to hovered buttons? If it does, that proves that we actually need more alternative colors, than just the background one, because any background color shouldn't semantically be used for buttons colored with `primary-color`—it'd be the same "dirty hack" that @aadcg opposed.

>     6. The evaluated result of the REPL

Same as three—`<pre>` tag.

>     7. Gemini/Gopher lines

Same as three.

>     8. Link hint background

The existing one works exactly because it is contrasting enough with most webpages. The pattern of "white border + dark fill" is the perfect solution for the elements that need to contrast everything. And hints do need to contrast everything. Changing the color to more "aesthetic" here would destroy the accessibility of hints, especially on the light theme websites (which are a majority of websites anyway).

Oh, wait, we're not using this style for hints. We have to, then. And the new color is out of the picture then, because the existing ones, when used in a contrasting way, are more than enough for hints to fulfill their ~destiny~ role in our interface.

>     9. Prompt buffer input area background color

Five, although I don't think we should change input area colors to anything. For the sake of consistency (with other inputs) and accessibility (for a maximum contrast of this fundamental UI element).

>     10. Panel buffer backgrounds to distinguish them from regular buffers

Is this an accessibility/distinctiveness decision (like @lansingthomas suggested for tutorial panels), or an aesthetic one? Because:
- Accessibility/distinctiveness is better achieved with borders and GTK styles for panel buffers, instead of painting the whole thing into a different color. Using a different backround color also means making our existing styles broken because
  - If one uses `<pre>` tags in panel buffers with `background-alternate-color`, then these `<pre>`s will just dissapear into the ~void~ background of the panel.
  - And if one starts painting `<pre>` tags (and lots of other use-cases for `background-alternate-color` implied as the reason for its introduction) into different colors, then ~they have two problems now~ there will be two incompatible and incomplete style sheets: one for panels and one for buffers. That I cannot accept.
- Aesthetics: we can still use the regular background color, improving the default styles to be more consistent, and that will be a bigger win than changing the background color locally with the risk of breaking all the styles we accumulated so far.

I believe that _all_ our pages and interfaces must use the same background color, and that it will save us a lot of headache.

> Consider this document from Apple (which I deign as an authority on UI/design): https://developer.apple.com/design/human-interface-guidelines/foundations/color
> [...]
> these are SIGNIFICANTLY more colors than we have. It would probably be a good model with which to design our colors. We are developing an operating system, and we need a way to express ourselves!

Note that:
- The theme is defined per widget, which is a huge difference from our theming, based more on Google Material Design approach of color palettes rather then per widget coloring.
  - @jmercouris I know you're sick of Google (so am I, but nonetheless...) so here's another example: Bootstrap.css, probably the most used CSS library out there (and the one I wanted to bring into Nyxt at some point) uses [only eight color pairs](https://getbootstrap.com/docs/5.3/customize/color/#theme-colors) in its palette, and four of these (danger, warning, success, info) are special purpose, so we only have four (primary, secondary, light, dark) generic ones. Which is exactly the same as our theme, before background-alternate.
    - Which means: we've enough colors, because the most Web-friendly styling library does, and what we design are indeed Web-friendly interfaces, not desktop ones that Apple is concerned about.
- The alternating backgroung color is described as "The backgrounds of alternating rows or columns in a list, table, or collection view." There's no mention of any buttons, because the _background_ color should not be applied to _widgets_.
- Note that most interface elements have their own color and background color, with the separate colors for distinct (hovered, disabled, focused) states. Which means: you
  - either use things consistently across use cases,
  - or you don't actually rely on the heuristics Apple provides.

Pick your side, and stand by one of the options above, or yield to Apple's authority:

3. We switch to per-widget theming, like Apple, and forget about introducing new colors forever, because we have more than enough for every widget, and no widget ~is more equal than others~ should be painted alternatively. I bet you won't like this options, exactly because _all the buttons and tabs_ will have to be painted the same, which hampers your will to "express" yourself.

**Comment by jmercouris** [comment]
Artyom, there was no *smuggling*, there is no deception. No secret cabal. Anyways, if I had to choose from those three I would choose "1.".

**Comment by aartaka** [comment]
> Artyom, there was no _smuggling_, there is no deception. No secret cabal. 

I've took my word of smuggling back. The only thing that I'm stating is the absence of public discussion and the consequent confusions arising from that.

**Comment by jmercouris** [comment]
I think it is now time to vote!

Please edit this post with your vote!

/polls "Add a background color alternate" "Do not add a background color alternate"

**Comment by jmercouris** [comment]
Hm, trying again:

/polls Option1 'Option 2' "Option 3"

**Comment by lansingthomas** [comment]
I read a number of interesting points about colors and themes -- I am voting to include a new alternate background color.

### my rationale:
- in any theme structure we decide on {by widget, by palette, by contrast pairs, by industry assumptions} a third color will be necessary for our product to be visually coherent. 
- I want our product to look great, better than good. A third color opens some important opportunities for that {borders, hover backgrounds that preserve legibility, visual cues beyond the reading layer, subtle suggestion shapes} -- fun and good things to get our people all excited to open up another buffer!

### What is next?
- I know I am wearing the UI hat here but it doesn't mean I know better than the rest of our team. You guys want to fix important stuff and I want to go do other UX things. Let's make a decision together, in a formalized way, about colors and themes --so we can carry on.
- I am going to open a new thread for a proper theme discussion, where we will decide how we want this theme to serve us and I commit to moderating discussion there and making sure the results are published properly.
- I will open that discussion with a draft style guide for us to have a shared starting point.

thank you all for your engagement.

**Comment by aartaka** [comment]
>     * in any theme structure we decide on {by widget, by palette, by contrast pairs, by industry assumptions} a third color will be necessary for our product to be visually coherent.

This I can agree with, but the newly added `background-alternate-color` is by no means this third color. It's not even called tertiary or whatever. If we need a third color, let's make a third color, instead of the inconsistent doppelganger of the background color.

The only thing I care about at this point is consistency.

**Comment by lansingthomas** [comment]
lets call it `background-variant` then. I think @aadcg suggested this last week. Cool?

**Comment by lansingthomas** [comment]
I keep trying to vote yes here and my check box disappears. Perhaps a permissions thing for the whole repo? Perhaps user error. please advise.

**Comment by lansingthomas** [comment]
> I think it is now time to vote!
> 
> Please edit this post with your vote!
> 
> I am in favor/OK with adding a new background alternate color:
> 
> * [x]  @aadcg
> * [ ]  @aartaka
> * [ ]  @Ambrevar
> * [x]  @jmercouris
> * [x]  @lansingthomas

**Comment by lansingthomas** [comment]
1. A whole [discussion](https://github.com/atlas-engineer/nyxt/discussions/2867) happened.
2. A palette with the new color (and some other changes) has been created, and added to the documents/.../theme space.

Thank you Nyxters

**Comment by aartaka** [comment]
I agree with closing this issue, as the question of alt colors is resolved for good. But the linked discussion is not done yet. Saying just as a status ping.
