### ISSUE TITLE
Package Nyxt for Fedora

### ISSUE THREAD

**Issue by Benjamin-Philip** [atlas-engineer/nyxt#2864]
# Is your feature request related to a problem? Please describe.

Currently to install nyxt on Fedora, you can either:

1.  install from the tarball
2.  build from source
3. install via guix
4. install via nix

Option 1 and 2 make installing updates painful. Option 1 additionally may install copies of dependencies which may have already been installed with dnf. Option 3 and 4 are unsuitable if you're only using guix or nix for nyxt - installing a new package manager for the sake of a single package is a no go.

# **Describe the solution you'd like**

Fedora is a very popular distro, with a reasonably large share of Linux workstations. Thus, I propose packaging nyxt for Fedora.

# **Describe alternatives you've considered**

Alternatively, a [copr](https://docs.pagure.org/copr.copr/) managed by Atlas Engineer could be made, and would have the same effect. However user maintained coprs would be unreliable as they wouldn't build automatically on a new release. This is because the new build would need to be triggered by a web hook from this repo, which requires updating the settings in this repo. https://copr.fedorainfracloud.org/coprs/lukasfr/nyxt/ is an example of this problem.

Another option could be to package a flatpak, which would benefit others distros. However, I would avoid installing nyxt via flatpak just as I wouldn't install emacs via flatpak.

**Comment by aartaka** [comment]
Should be easy enough, given that Guix can also create RPM packages. And Docker containers. And SquashFS systems.
``` sh
$ guix pack --list-formats
The supported formats for 'guix pack' are:

  tarball       Self-contained tarball, ready to run on another machine
  squashfs      Squashfs image suitable for Singularity
  docker        Tarball ready for 'docker load'
  deb           Debian archive installable via dpkg/apt
  rpm           RPM archive installable via rpm/yum
```

CC @Ambrevar

**Comment by jmercouris** [comment]
Flatpak already exists :-) why not give it a try?

**Comment by Benjamin-Philip** [comment]
> Flatpak already exists :-) why not give it a try?

I will. However I'm not so keen on using a browser as a flatpak. An rpm would be more performant any day, simply because it's far more simpler to run.

Personally I only use flatpaks for "Proprietary App" Software - things like Slack, Zoom, Skype, Spotify, Signal (not closed source) etc. I would ideally like my browser installed and running in the simplest way possible because I have broken containerization (and thus flatpaks) in the past before. I would need a browser to debug said issue. Not being to google this on my "daily browser" would be incredibly irritating (imagine debugging your init.el with nano)

Honestly, you should give the user as many options for installation as possible, so that he can install it according to his preferences.   This will mean packaging Nyxt for various obscure distributions and more. I'm just trying to start that process with packaging for Fedora (and also trying to "checkout" Nyxt in the process).

**Comment by aadcg** [comment]
@Benjamin-Philip, I understand your point of view and your observations are all correct. The ideal solution, from your perspective, would be to see Nyxt packaged for Fedora.

Unfortunately, we (development team) can't maintain and package Nyxt for all package mangers since we need to allocate our effort in more pressing issues. The responsibility of packaging software lies on the maintainers of each package manager. We reason why Nyxt is available on Nix or Guix is because we actually use those system. Nonetheless, that work was done under the "maintainer of Guix/Nix" hat, not under that of "Nyxt's developer".

My suggestion would be to make this request within Fedora's community. We'd be happy to help in the process. 

With respect to @aartaka's suggestion, we could do that, but it wouldn't be as convenient as having it packaged for Fedora. Also, we'd the increasing our maintenance burden since no one of us uses that distribution.

**Comment by Benjamin-Philip** [comment]
> My suggestion would be to make this request within Fedora's community. We'd be happy to help in the process.

Ok, in that case I think I'll package it myself in official repositories for Fedora.

**Comment by Ambrevar** [comment]
Note that a contributor builds RPMs for OpenSuse, this might help.  See Nyxt's readme, it's listed there.

**Comment by Benjamin-Philip** [comment]
> > My suggestion would be to make this request within Fedora's community. We'd be happy to help in the process.
> 
> Ok, in that case I think I'll package it myself in official repositories for Fedora.

Alternatively, shall I just become Atlas Engineer's "Fedora maintainer"? That way this package becomes an Atlas managed package and I can drop out whenever I want, and you can replace me with somebody else when needed.

If I packaged it as myself, I would have to maintain it indefinitely. However if I packaged it representing Atlas, I am easily replaceable, like I explained above.

**Comment by Benjamin-Philip** [comment]
> Note that a contributor builds RPMs for OpenSuse, this might help.  See Nyxt's readme, it's listed there

Did you have to setup any webhooks on this repo for automatic builds?

**Comment by bubbleguuum** [comment]
Here's the spec file for the openSUSE TW rpm (git version of Nyxt) that I maintain and that is built from time to time (no webhooks or anything fancy).  

https://build.opensuse.org/package/view_file/home:bobbie424242/nyxt-git/nyxt.spec?expand=0

It can surely be adapted for Fedora.

**Comment by Benjamin-Philip** [comment]
> Here's the spec file for the openSUSE TW rpm (git version of Nyxt) that I maintain and that is built from time to time (no webhooks or anything fancy).
> 
> https://build.opensuse.org/package/view_file/home:bobbie424242/nyxt-git/nyxt.spec?expand=0
> 
> It can surely be adapted for Fedora.

Thank you very much @bubbleguuum! I have a feeling that I'll end up copy pasting 90% of the file. You save me from a lot effort!

How do you trigger a build on a commit to master/main? It says on the README that you do.

**Comment by Benjamin-Philip** [comment]
Alternatively, releasing a tarball with the submodules included would fix the problem.

**Comment by jmercouris** [comment]
Well, we do do that :-)

see:

https://github.com/atlas-engineer/nyxt/releases/tag/3-pre-release-5

 `nyxt-3-source-with-submodules.tar.xz`

**Comment by aadcg** [comment]
Stale and not planned.

The Nyxt team can't maintain the distribution of its software on all platforms. We distribute a flatpak and self-contained bundle that works on any GNU/Linux distribution, [please find them here](https://github.com/atlas-engineer/nyxt/releases). We also maintain the packaging for the Guix package manager.

Maintainers of other package managers may request our help, but those interactions should preferably happen in the their platform.

**Comment by Benjamin-Philip** [comment]
Great! I shall delete that instance, as I don't think it actually works.
