### ISSUE TITLE
Introducing ..... Lambda!

### ISSUE THREAD

**Issue by lansingthomas** [atlas-engineer/nyxt#2869]
Hello Nyxtketeers!
Perhaps a small change that looks pretty cool? 

**Purpose**
1. improve the nerdy-ness of the status buffer.
2. reduce confusion about the purpose of the `invoke commands` icon.
3. turn an everyday experience into a fun moment for some of our users.

**What is your proposed change?**

1. Replace the [Hamburger](https://www.mobileapps.com/blog/hamburger-menu) icon with a lowercase Greek Lambda symbol.  `λ`
2. adjust the left padding a bit to subtly separate the navigation icons from the `invoke commands` icon

**Rationale for the replacement**
- Nerdy-ness is on brand &rarr; a hamburger means _"hidden options are here,"_ while a lambda means _"functions and nerdy stuff are here"_
- the vast majority of our users use keybindings to access the `invoke commands` prompt buffer &rarr; the icon is largely ornamental. 
   - I imagine that new users are going to experiment with all the obvious buttons, so a lambda or a hamburger have the same effect on this group.
   - I imagine that returning users will be using the keyboard bindings
- sometimes users forget what things mean, it is nice to have a memorable icon for a memorable UI (hamburgers are not memorable)

**Rationale for the padding adjustment**
- the left arrow, return symbol, and right arrow are all for navigation. While the `invoke commands` symbol is for invoking commands. &rarr; a slight bit of space between them communicates similarity of function by proximity.

**Constraints**

No changes to the functionality are proposed here

**Additional context/User story**
Some of our users will have good associations with this symbol! 
right now our users are largely programmers &rarr; programmers understand that lambda is about functions &rarr; they might understand on some level that we are making Nyxt for them.

**Screenshots/Mock ups**

> ![Screenshot_20230321_150101](https://user-images.githubusercontent.com/1691662/226727237-157d3f3e-7651-4551-96dc-bf55acd78101.png)

Like it? 
hate it?
don't wanna talk about it?

Thank you!

# Pre-Build Checklist:
_talk through the change with someone, then come back and mark off what you can_
- [x] I have consulted with the team.
- [x] One or more developers have signed off on this change.
- [x] One or more user researchers have signed off on this change.

**Comment by lansingthomas** [comment]
Myself
- [X] votes yes
- [ ] votes no

@jmercouris
- [ ] votes yes
- [ ] votes no

@Ambrevar 
- [ ] votes yes
- [ ] votes no

@aadcg 
- [ ] votes yes
- [ ] votes no

@aartaka 
- [ ] votes yes
- [ ] votes no

**Comment by aartaka** [comment]
Implementing, then?

One particular thing: I don't like the need to put this lambda apart from all the other buttons, just because it's likely to be harder to maintain. But then, yes, proximity gestalt principle makes sense, so I can live with the additional padding there.

**Comment by lansingthomas** [comment]
@aartaka just add a space before the lambda - just a subtle nudge is an effective dose.

**Comment by lansingthomas** [comment]
Pre build checklist complete! Alignment mode activated! Charge!

**Comment by jmercouris** [comment]
Closed with: 141f84332
