### ISSUE TITLE
Fix broken test for system `:nyxt/gi-gtk`

### ISSUE THREAD

**Issue by aadcg** [atlas-engineer/nyxt#2871]
Test `nyxt-url-not-iframe-embeddable` is broken on master when running `(asdf:test-system :nyxt/gi-gtk)`. 

`git bissect` (powered by our increasingly cleaner git log history) says that the culprit is commit 1421eb5316df2342fcec87e7bfc2a6b460fcf879.

@aartaka could you please investigate why this seemingly benign commit broke it?

**Comment by aartaka** [comment]
Investigating.

**Comment by aadcg** [comment]
@aartaka that fixes it, thanks!
