### ISSUE TITLE
runtime org.gnome.Sdk branch 42 is end-of-life as of March 21, 2023

### ISSUE THREAD

**Issue by mmahmoudian** [atlas-engineer/nyxt#2873]
I'm sorry if this is a duplicate, but I tried different search terms and didn't find any existing (open or closed) issues, pull requests, or discussions.

**Describe the bug**

```console
❯  flatpak update
Looking for updates…

Info: runtime org.gnome.Sdk branch 42 is end-of-life, with reason:
   The GNOME 42 runtime is no longer supported as of March 21, 2023. Please ask your application developer to migrate to a supported platform.
Info: applications using this runtime:
   engineer.atlas.Nyxt

Nothing to do.
```

**Precise recipe to reproduce the issue**

For website-specific issues:
Can you reproduce this issue with Epiphany / GNOME Web (https://wiki.gnome.org/Apps/Web)?

**Information**
- OS name+version: Kernel: 5.15.94-1-MANJARO arch: x86_64 bits: 64
- Graphics card and driver: Intel CometLake-S GT2 [UHD Graphics 630] driver: i915 v: kernel
- Desktop environment / Window manager name+version: KDE Plasma v: 5.26.5
- How you installed Nyxt (Guix pack, package manager, build from source): Flatpak
- Information from `show-system-information`:

```console
❯  flatpak run engineer.atlas.Nyxt --system-information
Gtk-Message: 09:06:02.928: Failed to load module "xapp-gtk3-module"
Gtk-Message: 09:06:02.929: Failed to load module "canberra-gtk-module"
Nyxt version: 3-pre-release-4
Renderer: GI-GTK
Operating system kernel: Linux 5.15.94-1-MANJARO
Lisp implementation: SBCL 2.0.11 (Dynamic space size: 4294967296)
Features: (:NYXT-GI-GTK :NYXT-GTK :NYXT-GI-GTK :NYXT-GTK :NYXT-3.1 :NYXT-3
 :NYXT-3-PRE-RELEASE-4 :SLYNK :PLUMP-UTF-32 :PARENSCRIPT :NSYMBOLS
 :FSET-EXT-STRINGS :NJSON :GLOBAL-VARS :DECLARE-TYPES
 :SBCL+SAFE-STANDARD-READTABLE :NAMED-READTABLES :SWANK :CL-FAD :LPARALLEL
 :21BIT-CHARS :CUSTOM-HASH-TABLE-NATIVE :CL-PPCRE-UNICODE :CL-UNICODE
 :CL-JSON-DOUBLE-FLOAT-IS-SUBSUMED :CL-JSON-SINGLE-FLOAT-IS-SUBSUMED :CL-PPCRE
 :CHUNGA :FLEXI-STREAMS :WEBKIT2 :WEBKIT2-2.38 :WEBKIT2-CORS-ALLOWLIST
 :WEBKIT2-PASTE-PLAINTEXT :WEBKIT2-TRACKING :WEBKIT2-MUTE :WEBKIT2-EMOJI
 :WEBKIT2-MEDIA :WEBKIT2-SANDBOXING :GTK-3-22 :GTK-3-20 :GTK-3-18 :GTK-3-16
 :GTK-3-14 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6 :GTK-3-4 :GTK :GDK-3-22
 :GDK-3-20 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12 :GDK-3-10 :GDK-3-8 :GDK-3-6
 :GDK-3-4 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF :CLOSER-MOP :GLIB-2-30 :GLIB-2-32
 :GLIB-2-34 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42 :GLIB-2-44 :GLIB-2-46
 :GLIB-2-48 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56 :GLIB-2-58 :GLIB
 :BORDEAUX-THREADS :LPARALLEL.WITH-CLTL2 :LPARALLEL.WITH-CAS
 :LPARALLEL.WITH-STEALING-SCHEDULER :SPLIT-SEQUENCE
 CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64 CFFI-FEATURES:UNIX :CFFI
 CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP :FAST-IO-SV :FAST-IO
 :CL-JSON-CLOS :CL-JSON :SBCL-USES-SB-ROTATE-BYTE CHIPZ-SYSTEM:GRAY-STREAMS
 :THREAD-SUPPORT :ASDF3.3 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX
 :NON-BASE-CHARS-EXIST-P :ASDF-UNICODE :X86-64 :GENCGC :64-BIT :ANSI-CL
 :COMMON-LISP :ELF :IEEE-FLOATING-POINT :LINUX :LITTLE-ENDIAN
 :PACKAGE-LOCAL-NICKNAMES :SB-LDB :SB-PACKAGE-LOCKS :SB-THREAD :SB-UNICODE
 :SBCL :UNIX)

ASDF version: 3.3.1
ASDF registries: (NYXT-SOURCE-REGISTRY ENVIRONMENT-SOURCE-REGISTRY)
Critical dependencies: (/run/build/nyxt/_build/cl-cffi-gtk/gtk/cl-cffi-gtk.asd
 /run/build/nyxt/_build/cl-gobject-introspection/cl-gobject-introspection.asd
 /run/build/nyxt/_build/cl-webkit/webkit2/cl-webkit2.asd)
```

**Output when started from a shell**

```console
❯  flatpak run engineer.atlas.Nyxt
Gtk-Message: 09:06:49.282: Failed to load module "xapp-gtk3-module"
Gtk-Message: 09:06:49.282: Failed to load module "canberra-gtk-module"
Nyxt version 3-pre-release-4
<INFO> [09:06:49] Source location: #P"/usr/local/share/"
<INFO> [09:06:49] Listening to socket: #P"/run/user/1000/nyxt/nyxt.socket"
<INFO> [09:06:49] GTK extensions directory: #P"/usr/local/share/libraries/web-extensions/"
<INFO> [09:06:50] GTK extensions directory: #P"/usr/local/share/libraries/web-extensions/"
<INFO> [09:06:50] Loading #P"/home/mehrad/.var/app/engineer.atlas.Nyxt/data/nyxt/history/default.lisp".
Gtk-Message: 09:06:50.440: Failed to load module "xapp-gtk3-module"
Gtk-Message: 09:06:50.440: Failed to load module "canberra-gtk-module"
Gtk-Message: 09:06:50.456: Failed to load module "xapp-gtk3-module"
Gtk-Message: 09:06:50.456: Failed to load module "canberra-gtk-module"
<INFO> [09:06:50] Restoring 7 buffers from history.
<INFO> [09:06:50] Loading #P"/home/mehrad/.var/app/engineer.atlas.Nyxt/data/nyxt/auto-rules.lisp".
Gtk-Message: 09:06:50.698: Failed to load module "xapp-gtk3-module"
Gtk-Message: 09:06:50.699: Failed to load module "canberra-gtk-module"
Gtk-Message: 09:06:51.571: Failed to load module "xapp-gtk3-module"
Gtk-Message: 09:06:51.572: Failed to load module "canberra-gtk-module"
<WARN> [09:07:02] Warning: Error on separate thread: None of the commands are installed: (&quot;wl-paste&quot; &quot;xclip&quot; &quot;xsel&quot;)
<WARN> [09:07:02] Warning: Error on separate thread: None of the commands are installed: (&quot;wl-paste&quot; &quot;xclip&quot; &quot;xsel&quot;)
Gtk-Message: 09:07:16.423: Failed to load module "xapp-gtk3-module"
Gtk-Message: 09:07:16.423: Failed to load module "canberra-gtk-module"
WARNING:
   Multiple KILL symbols found: (SB-POSIX:KILL LPARALLEL.KERNEL::KILL
                                               IOLIB/SYSCALLS:KILL)
WARNING:
   Multiple KILL symbols found: (SB-POSIX:KILL LPARALLEL.KERNEL::KILL
                                               IOLIB/SYSCALLS:KILL)
WARNING:
   Multiple KILL symbols found: (SB-POSIX:KILL LPARALLEL.KERNEL::KILL
                                               IOLIB/SYSCALLS:KILL)
WARNING:
   Multiple KILL symbols found: (SB-POSIX:KILL LPARALLEL.KERNEL::KILL
                                               IOLIB/SYSCALLS:KILL)
WARNING:
   Multiple KILL symbols found: (SB-POSIX:KILL LPARALLEL.KERNEL::KILL
                                               IOLIB/SYSCALLS:KILL)
<INFO> [09:07:26] Deleting socket #P"/run/user/1000/nyxt/nyxt.socket".
```

**Comment by aadcg** [comment]
@jmercouris please test whether it works with branch 43.

**Comment by jmercouris** [comment]
We'll have to figure out what exactly changed and then issue whatever upgrades we need!

**Comment by jmercouris** [comment]
So, when cl-webkit was patched with https://github.com/atlas-engineer/nyxt/commit/4516108f20e3f93a9d90a034d120c56221ba3f0a

we got a little bit closer.

Now we are having some strange certificate errors on startup.

```
[nix-shell:~/Work/Atlas/Nyxt]$ make flatpak-run 
Nyxt version 3-pre-release-5-10-gf7e4e11c3
<INFO> [14:55:43] Source location: #P"/usr/local/share/"
<INFO> [14:55:43] Listening to socket: #P"/run/user/1000/nyxt/nyxt.socket"
<INFO> [14:55:43] GTK extensions directory: #P"/usr/local/share/libraries/web-extensions/"

** (process:7317): WARNING **: 14:55:43.144: Error writing credentials to socket: Error sending message: Broken pipe
<INFO> [14:55:43] GTK extensions directory: #P"/usr/local/share/libraries/web-extensions/"
<WARN> [14:55:43] Warning: Error on separate thread: There is no applicable method for the generic function
  #&lt;STANDARD-GENERIC-FUNCTION NYXT:CERTIFICATE-EXCEPTIONS (1)&gt;
when called with arguments
  (#&lt;NYXT/CERTIFICATE-EXCEPTION-MODE:CERTIFICATE-EXCEPTION-MODE {100F1EE533}&gt;).
See also:
  The ANSI Standard, Section 7.6.6
Could not determine the accessibility bus address

** (process:7317): WARNING **: 14:55:53.236: Error writing credentials to socket: Error sending message: Broken pipe
```

I'm not sure if this is problems with my history or whatever, will investigate.

**Comment by jmercouris** [comment]
It just renders a blank screen, prompt buffer works. Internal buffers don't seem to work, seems to be related to the certificate errors.

**Comment by Ambrevar** [comment]
Can you browse http://example.org (non-HTTPS)?

**Comment by aadcg** [comment]
That smells like libsoup issues, but I may be completely wrong.

**Comment by jmercouris** [comment]
I can't set the URL or even do it via slime. It is not being responsive. I can really only interact with the prompt buffer.

**Comment by JohnSF1** [comment]
Just want to add my observation to have the similar certificate errors on startup, blank screen and nothing seemed to work.

**Information**

jsfchan@DESKTOP-B72ROMI:~$ wslsys
Release Install Date: Fri Mar 31 10:01:51 HKT 2023
Branch: ni_prerelease
Build: 23424
Full Build: 23424.1000.amd64fre.ni_prerelease.230324-1354
Display Scaling: 1
Locale (Windows): en_US
Theme (Windows): light
Uptime (Windows): 2d 22h 59m
Version (WSL): 2
Uptime (WSL): 0d 1h 0m
Release: Pengwin
Kernel: Linux 5.15.90.1-microsoft-standard-WSL2
Packages: 1221
IPv4 Address: 172.17.168.112
System Type (Windows): Desktop
SystemD Status: enabled

jsfchan@DESKTOP-B72ROMI:~$ grep "PENGWIN_VERSION" /etc/os-release
PENGWIN_VERSION="23.03.0"

**Running the Nyxt -- system-information**

jsfchan@DESKTOP-B72ROMI:~$ flatpak run engineer.atlas.Nyxt --system-information
Nyxt version: 3-pre-release-5
Renderer: GI-GTK
Operating system kernel: Linux 5.15.90.1-microsoft-standard-WSL2
Lisp implementation: SBCL 2.0.11 (Dynamic space size: 4294967296)
Features: (:NYXT-GI-GTK :NYXT-GTK :NYXT-GI-GTK :NYXT-GTK :NYXT-3.1 :NYXT-3
 :NYXT-3-PRE-RELEASE-5 :SLYNK :PLUMP-UTF-32 :PARENSCRIPT :NSYMBOLS
 :FSET-EXT-STRINGS :NJSON :GLOBAL-VARS :DECLARE-TYPES
 :SBCL+SAFE-STANDARD-READTABLE :NAMED-READTABLES :SWANK :CL-FAD :LPARALLEL
 :21BIT-CHARS :CUSTOM-HASH-TABLE-NATIVE :CL-PPCRE-UNICODE :CL-UNICODE
 :CL-JSON-DOUBLE-FLOAT-IS-SUBSUMED :CL-JSON-SINGLE-FLOAT-IS-SUBSUMED :CL-PPCRE
 :CHUNGA :FLEXI-STREAMS :WEBKIT2 :WEBKIT2-2.38 :WEBKIT2-CORS-ALLOWLIST
 :WEBKIT2-PASTE-PLAINTEXT :WEBKIT2-TRACKING :WEBKIT2-MUTE :WEBKIT2-EMOJI
 :WEBKIT2-MEDIA :WEBKIT2-SANDBOXING :GTK-3-22 :GTK-3-20 :GTK-3-18 :GTK-3-16
 :GTK-3-14 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6 :GTK-3-4 :GTK :GDK-3-22
 :GDK-3-20 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12 :GDK-3-10 :GDK-3-8 :GDK-3-6
 :GDK-3-4 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF :CLOSER-MOP :GLIB-2-30 :GLIB-2-32
 :GLIB-2-34 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42 :GLIB-2-44 :GLIB-2-46
 :GLIB-2-48 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56 :GLIB-2-58 :GLIB
 :BORDEAUX-THREADS :LPARALLEL.WITH-CLTL2 :LPARALLEL.WITH-CAS
 :LPARALLEL.WITH-STEALING-SCHEDULER :SPLIT-SEQUENCE
 CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64 CFFI-FEATURES:UNIX :CFFI
 CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP :FAST-IO-SV :FAST-IO
 :CL-JSON-CLOS :CL-JSON :SBCL-USES-SB-ROTATE-BYTE CHIPZ-SYSTEM:GRAY-STREAMS
 :THREAD-SUPPORT :ASDF3.3 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX
 :NON-BASE-CHARS-EXIST-P :ASDF-UNICODE :X86-64 :GENCGC :64-BIT :ANSI-CL
 :COMMON-LISP :ELF :IEEE-FLOATING-POINT :LINUX :LITTLE-ENDIAN
 :PACKAGE-LOCAL-NICKNAMES :SB-LDB :SB-PACKAGE-LOCKS :SB-THREAD :SB-UNICODE
 :SBCL :UNIX)

ASDF version: 3.3.1
ASDF registries: (NYXT-SOURCE-REGISTRY ENVIRONMENT-SOURCE-REGISTRY)
Critical dependencies: (/run/build/nyxt/_build/cl-cffi-gtk/gtk/cl-cffi-gtk.asd
 /run/build/nyxt/_build/cl-gobject-introspection/cl-gobject-introspection.asd
 /run/build/nyxt/_build/cl-webkit/webkit2/cl-webkit2.asd)


**Messages after running: flatpak run engineer.atlas.Nyxt**

jsfchan@DESKTOP-B72ROMI:~$ flatpak run engineer.atlas.Nyxt
Nyxt version 3-pre-release-5
<INFO> [12:15:21] Source location: #P"/usr/local/share/"
<INFO> [12:15:21] Listening to socket: #P"/run/user/1000/nyxt/nyxt.socket"
<INFO> [12:15:21] GTK extensions directory: #P"/usr/local/share/libraries/web-extensions/"
<INFO> [12:15:22] GTK extensions directory: #P"/usr/local/share/libraries/web-extensions/"
<WARN> [12:15:22] Warning: Error on separate thread: There is no applicable method for the generic function
  #&lt;STANDARD-GENERIC-FUNCTION NYXT:CERTIFICATE-EXCEPTIONS (1)&gt;
when called with arguments
  (#&lt;NYXT/CERTIFICATE-EXCEPTION-MODE:CERTIFICATE-EXCEPTION-MODE {100F076533}&gt;).
See also:
  The ANSI Standard, Section 7.6.6

**Comment by aadcg** [comment]
@jmercouris, since you started taking a look at this one, it might make sense for you to continue.

If you're busy with other things, I can pick it up. Feel free to assign me instead :)

**Comment by aadcg** [comment]
Updating to 44 instead of 43 gets us closer to closing this issue, but there are still some issues I'm investigating. They're not related to the Flatpak per se, but most likely related to using the newest webkitgtk version, 2.40.1.

**Comment by jmercouris** [comment]
Andre and I managed to get it to run, and runs fine, but doesn't work with SSL.

**Comment by aadcg** [comment]
@jmercouris actually, from my side, everything works! No SSL issues.

Hm...

**Comment by aadcg** [comment]
@jmercouris I believe that the SSL issue might be coming from your side. I can't think of any other reason...

Closing this issue is dependent on issue #2933.

**Comment by jmercouris** [comment]
I shall test!

**Comment by jmercouris** [comment]
```
[nix-shell:~/Work/Atlas/Nyxt]$ flatpak run --command=sh engineer.atlas.Nyxt
[📦 engineer.atlas.Nyxt ~]$ gnutls-cli google.com
Processed 742 CA certificate(s).
Resolving 'google.com:443'...
Connecting to '142.250.191.142:443'...
- Certificate type: X.509
- Got a certificate list of 3 certificates.
- Certificate[0] info:
 - subject `CN=*.google.com', issuer `CN=GTS CA 1C3,O=Google Trust Services LLC,C=US', serial 0x00d55191166648a2010a2561bfaf49a0e6, EC/ECDSA key 256 bits, signed using RSA-SHA256, activated `2023-04-03 08:17:58 UTC', expires `2023-06-26 08:17:57 UTC', pin-sha256="cTdZfgLcvvzGT7MlV6JUu/DzpAeQ4SOhiqY2zuq4VnM="
        Public Key ID:
                sha1:2dea5a956379fc4af28dd92129f64c2d2ca8849b
                sha256:7137597e02dcbefcc64fb32557a254bbf0f3a40790e123a18aa636ceeab85673
        Public Key PIN:
                pin-sha256:cTdZfgLcvvzGT7MlV6JUu/DzpAeQ4SOhiqY2zuq4VnM=

- Certificate[1] info:
 - subject `CN=GTS CA 1C3,O=Google Trust Services LLC,C=US', issuer `CN=GTS Root R1,O=Google Trust Services LLC,C=US', serial 0x0203bc53596b34c718f5015066, RSA key 2048 bits, signed using RSA-SHA256, activated `2020-08-13 00:00:42 UTC', expires `2027-09-30 00:00:42 UTC', pin-sha256="zCTnfLwLKbS9S2sbp+uFz4KZOocFvXxkV06Ce9O5M2w="
- Certificate[2] info:
 - subject `CN=GTS Root R1,O=Google Trust Services LLC,C=US', issuer `CN=GlobalSign Root CA,OU=Root CA,O=GlobalSign nv-sa,C=BE', serial 0x77bd0d6cdb36f91aea210fc4f058d30d, RSA key 4096 bits, signed using RSA-SHA256, activated `2020-06-19 00:00:42 UTC', expires `2028-01-28 00:00:42 UTC', pin-sha256="hxqRlPTu1bMS/0DITB1SSu0vd4u/8l8TjPgfaAp63Gc="
- Status: The certificate is trusted. 
- Description: (TLS1.3-X.509)-(ECDHE-X25519)-(ECDSA-SECP256R1-SHA256)-(AES-256-GCM)
- Session ID: 90:DA:7B:51:C3:C5:63:0F:4A:3A:45:6D:04:A2:E4:35:D5:B2:15:6E:6E:AD:FD:AC:0F:12:12:11:88:03:4A:13
- Options:
- Handshake was completed

- Simple Client Mode:
```

**Comment by jmercouris** [comment]
So if you recall, dexador and the like was able to fetch results from the engine, but only the WebKitGTK+ view was not able to render things due to certificate errors. I think what I'll try doing is downloading the flatpak from the CI and see if it works on my machine.
