### ISSUE TITLE
Move lisp-system and os-package-mode to extensions

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#2880]
See #1633 for a discussion.

**Comment by Ambrevar** [comment]
@jmercouris Would you have time to move lisp-system to a separate extension repo?
@aadcg Would you have time to move os-package-mode to a separate extension repo?

**Comment by aadcg** [comment]
Yes @Ambrevar, no problem!

**Comment by jmercouris** [comment]
Complete with: a6c52a283
