### ISSUE TITLE
Build failure with SBCL 2.3.3

### ISSUE THREAD

**Issue by bubbleguuum** [atlas-engineer/nyxt#2884]
Failure to compile latest nyxt git with SBCL 2.3.3. See end of this page:

https://build.opensuse.org/public/build/home:bobbie424242/openSUSE_Tumbleweed/x86_64/nyxt-git/_log

**Comment by aadcg** [comment]
Submodule updated via 0798cde38622d17b11da35645c2ead673c2548e9.

[I've sent a patch to Guix](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=62610).

@bubbleguuum it should compile successfully now. Thanks for the report.
