### ISSUE TITLE
Font rendering is bad when started from shell

### ISSUE THREAD

**Issue by IllustratedMan-code** [atlas-engineer/nyxt#2886]
**Describe the bug**
When I start nyxt from the shell e.g. `nyxt` It renders fonts like so:
![image](https://user-images.githubusercontent.com/60514384/229168748-c9c52fe0-6839-4b01-a804-f0635274461f.png)

But when I start nyxt using rofi:

![image](https://user-images.githubusercontent.com/60514384/229172954-3c9e1a09-ebf8-411a-af51-b69d5f76c33b.png)
Any ideas?

**Information**
- NixOS
- Intel/nvidia
- hyprland
- nix package/built from source (tested on both):

**Output when started from a shell**
```
Nyxt version: 2.2.4
Renderer version: GTK
Operating system kernel: Linux 5.15.95
Lisp implementation: SBCL 2.3.0.nixos (Dynamic space size: 1073741824)
Features: (:WEBKIT2 :WEBKIT2-2.38 :WEBKIT2-CORS-ALLOWLIST :WEBKIT2-PASTE-PLAINTEXT
 :WEBKIT2-TRACKING :WEBKIT2-MUTE :WEBKIT2-EMOJI :WEBKIT2-MEDIA
 :WEBKIT2-SANDBOXING :GTK-3-22 :GTK-3-20 :GTK-3-18 :GTK-3-16 :GTK-3-14
 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6 :GTK-3-4 :GTK :GDK-3-22 :GDK-3-20
 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12 :GDK-3-10 :GDK-3-8 :GDK-3-6 :GDK-3-4
 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF :GLIB-2-30 :GLIB-2-32 :GLIB-2-34
 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42 :GLIB-2-44 :GLIB-2-46 :GLIB-2-48
 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56 :GLIB-2-58 :GLIB :NYXT-2
 :FSET-EXT-STRINGS :CUSTOM-HASH-TABLE-NATIVE :SWANK :PLUMP-UTF-32 :GLOBAL-VARS
 :DECLARE-TYPES :PARENSCRIPT :NAMED-READTABLES :LPARALLEL :21BIT-CHARS :CHUNGA
 :FLEXI-STREAMS :CLOSER-MOP :CL-PPCRE-UNICODE :CL-UNICODE :CL-PPCRE
 :BORDEAUX-THREADS :LPARALLEL.WITH-CLTL2 :LPARALLEL.WITH-CAS
 :LPARALLEL.WITH-STEALING-SCHEDULER :SPLIT-SEQUENCE CHIPZ-SYSTEM:GRAY-STREAMS
 CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64 CFFI-FEATURES:UNIX :CFFI
 CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP :FAST-IO-SV :FAST-IO
 :SBCL-USES-SB-ROTATE-BYTE :ASDF-SYSTEM-CONNECTIONS :CL-JSON-CLOS :CL-JSON
 :THREAD-SUPPORT :ASDF3.3 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX
 :NON-BASE-CHARS-EXIST-P :ASDF-UNICODE :ARENA-ALLOCATOR :X86-64 :GENCGC :64-BIT
 :ANSI-CL :COMMON-LISP :ELF :IEEE-FLOATING-POINT :LINUX :LITTLE-ENDIAN
 :PACKAGE-LOCAL-NICKNAMES :SB-CORE-COMPRESSION :SB-LDB :SB-PACKAGE-LOCKS
 :SB-THREAD :SB-UNICODE :SBCL :UNIX)

ASDF version: 3.3.4
ASDF registries: (NYXT-SOURCE-REGISTRY ENVIRONMENT-SOURCE-REGISTRY USER-SOURCE-REGISTRY
                      USER-SOURCE-REGISTRY-DIRECTORY
                      DEFAULT-USER-SOURCE-REGISTRY SYSTEM-SOURCE-REGISTRY
                      SYSTEM-SOURCE-REGISTRY-DIRECTORY
                      DEFAULT-SYSTEM-SOURCE-REGISTRY)
Critical dependencies: (/nix/store/824a421abmhzl5467hg8ac2b1xan3dh0-lisp-cl-cffi-gtk-20201220-git/lib/common-lisp/cl-cffi-gtk/gtk/cl-cffi-gtk.asd
 /nix/store/5sav75miwcqbvl4hyvxl1xl577pixw12-lisp-cl-gobject-introspection-20210124-git/lib/common-lisp/cl-gobject-introspection/cl-gobject-introspection.asd
 /nix/store/50aicv6pxqqlbbkfnc2pbp5amkiv4kp3-lisp-cl-webkit2-cl-webkit-20211209-git/lib/common-lisp/cl-webkit2/webkit2/cl-webkit2.asd)
```

**Comment by jmercouris** [comment]
That is most peculiar... I literally cannot imagine why.

**Comment by IllustratedMan-code** [comment]
Weirdly enough,  only wofi and rofi seem to have larger font, dmenu, fuzzel, and emacs' start-process have identical behavior to the shell.

I'm on wayland, but GDK environment variables seem to have no affect on nyxt's font scaling. Is there any other way to change the font size?

I've tried launching nyxt in shells without configs as well, so don't think its my shell config.  I don't *think* rofi sets any environment variables. I also checked the desktop file and there doesn't seem to be any flags or anything that would cause this. 

This only seems to be a problem for nyxt as well. Other gtk apps don't seem to have this problem. I even tested epiphany to make sure it wasn't a webkitgtk thing.

**Comment by jmercouris** [comment]
Can you please try running the command `open-inspector` in both cases and see what is reported as the font?

**Comment by aadcg** [comment]
I can reproduce this issue when setting `GDK_DPI_SCALE` to `0.5` (screenshot below).  For those who have high DPI monitors, please set `GDK_SCALE` to `2` alone.

![2023-05-04_22:25:12](https://user-images.githubusercontent.com/45483512/236309035-25ce09fc-2370-4140-a720-58eb5e3682b6.png)

Closing. @IllustratedMan-code feel free to re-open if the issue persists.
