### ISSUE TITLE
`prompter` behaviour when running `actions-on-current-suggestion`

### ISSUE THREAD

**Issue by aadcg** [atlas-engineer/nyxt#2891]
Invoke the prompt buffer as shown below and navigate through the suggestions. You'll notice that the printed suggestion is not the current one, but the one that used to be the current one. If you change the call from `print` to `break`, you'll see that the action runs on the correct suggestions. So there seems to be a race condition here.

Does that make sense @Ambrevar? 

```lisp
(prompt :prompt "Test"
        :sources (make-instance
                  'prompter:source
                  :name "Test"
                  :constructor '("a" "b" "c" "d" "e")
                  :actions-on-current-suggestion-enabled-p t
                  :actions-on-current-suggestion (lambda-command test (suggestion)
                                                   (print suggestion))))
```

The context of this finding is related to #2529.

**Comment by aadcg** [comment]
Everything is correct here. It's all due to a misunderstanding of mine!

**Comment by aadcg** [comment]
I'm again confused by this. 

@Ambrevar could you help me make sense of it? Thanks.

**Comment by Ambrevar** [comment]
This is a SLY problem, because of multiple threads and GTK blocking, the SLY output is printed with a delay.  Try adding `(force-output t)` after `print`, it should make a difference.

**Comment by aadcg** [comment]
That makes total sense! Thanks @Ambrevar.
