### ISSUE TITLE
can't open url

### ISSUE THREAD

**Issue by joeleemacus** [atlas-engineer/nyxt#2900]
![image](https://user-images.githubusercontent.com/71259902/231066660-2bed14f1-c789-4649-bd74-02cb791bea84.png)
when i open nyxt in first time, The following error prompt appears, If you click on Enter again, nyxt will crash and return to the desktop

OS: void
kernel: 6.1.21_1

**Comment by xanmodlouis** [comment]
![image](https://user-images.githubusercontent.com/71259902/231082568-22ec4f93-069d-4675-a6f2-f9e24c29c656.png)

**Comment by Ambrevar** [comment]
Could you open an issue and fill all the required information?  In particular we would need:
- how did you install Nyxt (package manager, from source, etc.),
- the output of `nyxt --system-information`.

**Comment by xanmodlouis** [comment]
> Could you open an issue and fill all the required information? In particular we would need:
> 
>     * how did you install Nyxt (package manager, from source, etc.),
> 
>     * the output of `nyxt --system-information`.

* I use `xbps-install nyxt`
* `nyxt --system-information` info
![image](https://user-images.githubusercontent.com/71259902/231117896-cd37daf9-3f36-4427-b6ab-795a707c6515.png)

**Comment by Ambrevar** [comment]
Please copy-paste the output next time, it makes it easier to parse for us, + it's lighter on ressources.

Can you share which webkitgtk version your OS is using?

**Comment by xanmodlouis** [comment]
Thanks for reminding me, I will pay attention next time,

`webkitgtk version:` webkit2gtk-2.40.0_2

**Comment by aadcg** [comment]
This seems to be related to the way Nyxt in packaged for this Linux distro. @Ambrevar, is there something to do from our side?

**Comment by Ambrevar** [comment]
I can't tell without more details.

I seem to recall that Void is a bit special in the core libs they use, maybe it broke with the recent WebKitGTK.

**Comment by f1nbar** [comment]
Also broken for me on void linux. 

I get this error if I try search/iopen a url while running nyxt from console:

 `<WARN> [12:20:42] Warning: Error on GTK thread: The value
  :INVALID-CODE-OBJECT-AT-PC
is not of type
  FUNCTION`

```Nyxt version: 2.2.4
Renderer version: GI-GTK
Operating system kernel: Linux 6.1.21_1
Lisp implementation: SBCL 2.2.2.void.1 (Dynamic space size: 3221225472)
Features: (:WEBKIT2 :WEBKIT2-2.34 :WEBKIT2-PASTE-PLAINTEXT :WEBKIT2-TRACKING
 :WEBKIT2-MUTE :WEBKIT2-EMOJI :WEBKIT2-MEDIA :WEBKIT2-SANDBOXING :GTK-3-22
 :GTK-3-20 :GTK-3-18 :GTK-3-16 :GTK-3-14 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6
 :GTK-3-4 :GTK :GDK-3-22 :GDK-3-20 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12
 :GDK-3-10 :GDK-3-8 :GDK-3-6 :GDK-3-4 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF
 :GLIB-2-30 :GLIB-2-32 :GLIB-2-34 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42
 :GLIB-2-44 :GLIB-2-46 :GLIB-2-48 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56
 :GLIB-2-58 :GLIB :NYXT-2 :FSET-EXT-STRINGS :CUSTOM-HASH-TABLE-NATIVE :SWANK
 :PLUMP-UTF-32 :GLOBAL-VARS :DECLARE-TYPES :PARENSCRIPT
 :SBCL+SAFE-STANDARD-READTABLE :NAMED-READTABLES :LPARALLEL :21BIT-CHARS
 :CHUNGA :CLOSER-MOP :CL-PPCRE-UNICODE :FLEXI-STREAMS :CL-UNICODE :CL-PPCRE
 :CL-JSON-DOUBLE-FLOAT-IS-SUBSUMED :CL-JSON-SINGLE-FLOAT-IS-SUBSUMED
 :BORDEAUX-THREADS :LPARALLEL.WITH-CLTL2 :LPARALLEL.WITH-CAS
 :LPARALLEL.WITH-STEALING-SCHEDULER :SPLIT-SEQUENCE CHIPZ-SYSTEM:GRAY-STREAMS
 CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64 CFFI-FEATURES:UNIX :CFFI
 CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP :FAST-IO-SV :FAST-IO
 :SBCL-USES-SB-ROTATE-BYTE :CL-JSON-CLOS :CL-JSON :THREAD-SUPPORT :ASDF3.3
 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX :NON-BASE-CHARS-EXIST-P
 :ASDF-UNICODE :X86-64 :GENCGC :64-BIT :ANSI-CL :COMMON-LISP :ELF
 :IEEE-FLOATING-POINT :LINUX :LITTLE-ENDIAN :PACKAGE-LOCAL-NICKNAMES
 :SB-CORE-COMPRESSION :SB-LDB :SB-PACKAGE-LOCKS :SB-THREAD :SB-UNICODE :SBCL
 :UNIX)

ASDF version: 3.3.1
ASDF registries: (NYXT-SOURCE-REGISTRY ENVIRONMENT-SOURCE-REGISTRY)
Critical dependencies: (/builddir/nyxt-2.2.4/_build/cl-cffi-gtk/gtk/cl-cffi-gtk.asd
 /builddir/nyxt-2.2.4/_build/cl-gobject-introspection/cl-gobject-introspection.asd
 /builddir/nyxt-2.2.4/_build/cl-webkit/webkit2/cl-webkit2.asd)```

**Comment by aartaka** [comment]
That's a bug we've already encountered with SBCL side older versions. @f1nbar, any option to try with newer SBCL?

**Comment by f1nbar** [comment]
> That's a bug we've already encountered with SBCL side older versions. @f1nbar, any option to try with newer SBCL?

SBCL version is 2.3.2, seems to be the latest version available in a binary for x86_64. Anything else it could be?

**Comment by aartaka** [comment]
Oh, `SBCL 2.2.2.void.1` has confused me there :sweat_smile:

**Comment by aartaka** [comment]
So wait, do we close it because the latest pre-release works, or is the problem happening on the unstable (after the pre-releas) Nyxt too? I see in your system information that it's `:NYXT-2`, so I take it the problem only happened in 2.2.4?

**Comment by jmercouris** [comment]
Closing, since it works, and we don't support Void anyways- not officially at least.
