### ISSUE TITLE
CUA bindings not responsive for a few commands

### ISSUE THREAD

**Issue by lansingthomas** [atlas-engineer/nyxt#2907]
**Describe the bug**
the commands `headings-panel`, `next-heading`, and `jump-to-heading` are not invoking for me. 
- CUA binding mode
- I know it is the binding because I can enter the name of the commands in the `Execute Command Menu` and the commands seem to work fine.

**Information**
ubuntu linux, Nyxt version 3 from the .tar
  - Lisp implementation/version: SBCL 2.3.2
  - Kernel name+version: Linux 5.19.0-38 generic
  - WebKitGTK+ | QtWebEngine version: GI-GTK

**Comment by aadcg** [comment]
@lansingthomas we need for information: where are you trying to invoke these commands, i.e. on which URL?

I'm not able to reproduce this issue on `https://en.wikipedia.org/wiki/Tomato` or the manual page when starting nyxt from the master branch via `(nyxt:start :no-config t)`

**Comment by lansingthomas** [comment]
https://user-images.githubusercontent.com/6666079/233209806-78b723b6-0e07-4d20-9b6a-d0685ffde0ab.mp4

**Comment by lansingthomas** [comment]
Looks like this is an Ubuntu menu for inserting emojis... but I can only get it to come up through Nyxt 🤠 by pressing `C-.` then `C-space`

**Comment by lansingthomas** [comment]
https://user-images.githubusercontent.com/6666079/233211475-81346535-2612-4c62-bc2f-e196db1e06ac.mp4

**Comment by aadcg** [comment]
The problem here seems to be related to the fact that some keybindings are intercepted by Ubuntu's desktop environment, GNOME.

@lansingthomas could you please try take a look at Ubuntu settings? There must be a menu to edit default keybindings, from which you can disable them. That should fix the problem.

**Comment by aadcg** [comment]
Given that most users of CUA bindings might be using Nyxt from GNOME (regardless of the GNU/Linux distribution), I wonder whether we should rebind these commands. @jmercouris, thoughts?

**Comment by lansingthomas** [comment]
what is the rationale behind `C-.`?
IF it is an emacs thing... emacs mode : )

**Comment by aadcg** [comment]
> what is the rationale behind `C-.`?

It's not an Emacs thing, and it's actually difficult to come up with a good keybinding for this feature since it doesn't exist in other browsers. If you have a suggestion, I'm all ears!

I think the main point here is that CUA users are, most likely, GNOME users too and we should avoid CUA keybindings that coincide with such common desktop managers.

**Comment by aartaka** [comment]
> I think the main point here is that CUA users are, most likely, GNOME users too and we should avoid CUA keybindings that coincide with such common desktop managers.

Yes.

**Comment by lansingthomas** [comment]
`C-h` as in headings is available.
`C-'` an ergonomically close but otherwise poorly related option is also available

`C-h` is the best I can come up with

**Comment by lansingthomas** [comment]
`C-shift-downarrow` and `C-shit-uparrow` could fit nicely.

**reminder for us while thinking about this:**
the adjacent commands an inputs are: `C-up/down` for scroll top/bottom and `page up/down` for scroll one full page.

**Comment by jmercouris** [comment]
`C-h` seems reasonable :-)

**Comment by aadcg** [comment]
`C-H` is bound to `history-all-query`.

`C-h` is reasonable for the CUA keyscheme. 

For the Emacs keyscheme we'll stick to `C-.`, since `C-h` is a prefix for the help commands.
