### ISSUE TITLE
Invoke `next-heading` at `https://en.wikipedia.org/wiki/Tomato`

### ISSUE THREAD

**Issue by aadcg** [atlas-engineer/nyxt#2914]
Steps to reproduce:

- From the REPL, issue `(nyxt:start :no-config t :urls '("https://en.wikipedia.org/wiki/Tomato"))`;
- Issue command `next-heading` multiple times;
- Notice that it cycles through 2 page positions.

**Comment by aartaka** [comment]
Also reproduced by @lansingthomas and myself :(

**Comment by aadcg** [comment]
I can no longer reproduce this bug from master and the latest WebKitGTK version 2.40.1.

Please re-open if anyone can reproduce.

**Comment by aartaka** [comment]
Weird... I cannot reproduce even on https://en.wikipedia.org/wiki/Hummingbird, where we encountered it with @lansingthomas (◎_◎;)

**Comment by aadcg** [comment]
I think it's related to webkitgtk. At some point they introduced a bug, and then fixed it again.
