### ISSUE TITLE
Nyxt 3-pre-release-6: unable to make web-extensions on Ubuntu 22.10

### ISSUE THREAD

**Issue by johanwiden** [atlas-engineer/nyxt#2918]
**Describe the bug**
make web-extensions
make -C libraries/web-extensions/ all
make[1]: Entering directory '/home/jw/Downloads/x3/libraries/web-extensions'
/usr/bin/cc -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -fPIC   -c -o alarms.o alarms.c
In file included from alarms.c:4:
globals.h:7:10: fatal error: webkit2/webkit-web-extension.h: No such file or directory
    7 | #include <webkit2/webkit-web-extension.h>

This worked in the previous pre-release.

**Precise recipe to reproduce the issue**
Download and extract nyxt-3-source-with-submodules.tar.xz
make all    # works OK
make web-extensions   # fails

For website-specific issues:
Can you reproduce this issue with Epiphany / GNOME Web (https://wiki.gnome.org/Apps/Web)?

**Information**
- OS name+version: Ubuntu 23.10
- Graphics card and driver:
- Desktop environment / Window manager name+version:
- How you installed Nyxt (Guix `pack,` package manager, build from source): build from source
- Information from `show-system-information`:
Nyxt version: 3
Renderer: GI-GTK
Operating system kernel: Linux 5.19.0-40-generic
Lisp implementation: SBCL 2.2.9 (Dynamic space size: 3221225472)
Features: (:NYXT-GI-GTK :NYXT-GTK :NYXT-GI-GTK :NYXT-GTK :NYXT-3 :SLYNK :PLUMP-UTF-32
 :PARENSCRIPT :NSYMBOLS :FSET-EXT-STRINGS :NJSON :GLOBAL-VARS :DECLARE-TYPES
 :SBCL+SAFE-STANDARD-READTABLE :NAMED-READTABLES :SWANK :CL-FAD :LPARALLEL
 :21BIT-CHARS :CUSTOM-HASH-TABLE-NATIVE :CL-PPCRE-UNICODE :CL-UNICODE
 :CL-JSON-DOUBLE-FLOAT-IS-SUBSUMED :CL-JSON-SINGLE-FLOAT-IS-SUBSUMED :CHUNGA
 :FLEXI-STREAMS :CL-PPCRE :WEBKIT2 :WEBKIT2-2.38 :WEBKIT2-CORS-ALLOWLIST
 :WEBKIT2-PASTE-PLAINTEXT :WEBKIT2-TRACKING :WEBKIT2-MUTE :WEBKIT2-EMOJI
 :WEBKIT2-MEDIA :WEBKIT2-SANDBOXING :GTK-3-22 :GTK-3-20 :GTK-3-18 :GTK-3-16
 :GTK-3-14 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6 :GTK-3-4 :GTK :GDK-3-22
 :GDK-3-20 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12 :GDK-3-10 :GDK-3-8 :GDK-3-6
 :GDK-3-4 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF :CLOSER-MOP :GLIB-2-30 :GLIB-2-32
 :GLIB-2-34 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42 :GLIB-2-44 :GLIB-2-46
 :GLIB-2-48 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56 :GLIB-2-58 :GLIB
 :BORDEAUX-THREADS :LPARALLEL.WITH-CLTL2 :LPARALLEL.WITH-CAS
 :LPARALLEL.WITH-STEALING-SCHEDULER :SPLIT-SEQUENCE
 CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64 CFFI-FEATURES:UNIX :CFFI
 CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP :FAST-IO-SV :FAST-IO
 :CL-JSON-CLOS :CL-JSON :SBCL-USES-SB-ROTATE-BYTE CHIPZ-SYSTEM:GRAY-STREAMS
 :THREAD-SUPPORT :ASDF3.3 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX
 :NON-BASE-CHARS-EXIST-P :ASDF-UNICODE :X86-64 :GENCGC :64-BIT :ANSI-CL
 :COMMON-LISP :ELF :IEEE-FLOATING-POINT :LINUX :LITTLE-ENDIAN
 :PACKAGE-LOCAL-NICKNAMES :SB-CORE-COMPRESSION :SB-LDB :SB-PACKAGE-LOCKS
 :SB-THREAD :SB-UNICODE :SBCL :UNIX)

ASDF version: 3.3.1
ASDF registries: (NYXT-SOURCE-REGISTRY ENVIRONMENT-SOURCE-REGISTRY)
Critical dependencies: (/home/jw/Downloads/x3/_build/cl-cffi-gtk/gtk/cl-cffi-gtk.asd
 /home/jw/Downloads/x3/_build/cl-gobject-introspection/cl-gobject-introspection.asd
 /home/jw/Downloads/x3/_build/cl-webkit/webkit2/cl-webkit2.asd)

  If you can't run `show-system-information`, try `nyxt --system-information` from
  a shell.  It this still does not work, please provide the following:
  - Nyxt version (from the `nyxt-version` command or `nyxt --version` from a shell):
  - Lisp implementation/version (if built from source):
  - Kernel name+version:
  - WebKitGTK+ | QtWebEngine version:

**Output when started from a shell**

**Comment by johanwiden** [comment]
It seems that web-extensions now work without doing
  make web-extensions
nyxt is able to use my web-extensions.
I have not done a make install. I run nyxt from the build directory. This also holds for the previous pre-release.

**Comment by aartaka** [comment]
c916517eeadc3d10950a18b852da68bea66c52ab updates the INSTALL file. @johanwiden, note that the WebExtensions library had all the functionality disabled on the C side because of too many errors breaking Nyxt. So it's essentially doing nothing except existing, while Lisp-side exists, works, and implies the existence of the C library (:

**Comment by aadcg** [comment]
Nothing to do done here. Closing @aartaka?

**Comment by aartaka** [comment]
Yes.
