### ISSUE TITLE
remembrance-mode broken

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#2926]
Reported here: https://github.com/atlas-engineer/nyxt/pull/2908#discussion_r1171087524

It looks like remembrance-mode is broken on the https://github.com/atlas-engineer/nyxt/tree/fix-render-url-on-strings branch.

I keep getting

```log
Invalid index 45 for (SIMPLE-VECTOR 8), should be a non-negative integer below 8.
```
errors, which may be related to Montezuma having issues with the cache.
I remember hitting this cache issues before, and if I recall correctly it was because the existing cache was out of date with the new model.  I tried removing the existing cache files, to no avail.

Any idea?  @jmercouris @aartaka ?

(I'm really eager to switch to Xapian at this point, Montezuma is just too painful...)

**Comment by jmercouris** [comment]
No ideas here!

**Comment by aartaka** [comment]
No ideas either :/

**Comment by jmercouris** [comment]
Very interesting feature, and it is good, however I do not think it is widely used, and thus a blocker for 3.0.0.

**Comment by aadcg** [comment]
In my view, since it's a feature that is mostly undocumented I think it's OK to do nothing at all. A nosy user might discover it and even fix it!

@aartaka which actions are you referring to?

**Comment by aartaka** [comment]
> @aartaka which actions are you referring to?

I had a though that `remembrance-mode` commands were used as return actions somewhere (or did I plan to use them? dunno), but seems they aren't used anywhere beyond `rememberance-mode` itself.

**Comment by aadcg** [comment]
Let's close for now, and re-open when we can reproduce.
