### ISSUE TITLE
Update Ddark theme palettes and naming conventions

### ISSUE THREAD

**Issue by lansingthomas** [atlas-engineer/nyxt#2927]
Hello Nyxtketeers,
@aartaka  and I met last week to hammer out some new colors for dark theme. Would some hero please implement our changes across `common-settings` so we can share them with the world?

**Purpose**
1. Improve the color theme selection experience and expand the default options.
2. update the dark theme with new colors
3. add a third theme (sepia) to the available options in `Common Settings`. 

**What is your proposed change?**
1. - [ ] on the `Common Settings` page please include some language under the `Theme style` heading to communicate that changes take effect after closing and re-opening Nyxt browser.
2. - [ ] please add the images below to the appropriate documentation section on GH.
3. - [ ] please update the `common-settings` to reflect the new colors for all three themes {day, night, sepia} (_yes I went from `light+dark` to `day+night`, I just think it is cool. :D IF you have reason to stay with `light + dark`; I'm fine with it_)
      - please include the warning colors for each theme.
      - please include the alt-colors for each theme

**Rationale**
the color values have been chosen with these characteristics in mind:
1. on-colors and surface colors have appropriate contrast for visual accessibility and our previously established guidelines.
2. surface colors -- pleasant for persistent viewing in dark user environments (pastels, low saturation)
3. Warning colors stand out against background colors
4. Tom and Artyom agree that they look nice

**Constraints**
have fun :D

**Additional context/User story**

People love options! At least our people who are here for customization. This is an easy win IMO

**Screenshots/Mock ups**
![Nyxt palette (night)](https://user-images.githubusercontent.com/6666079/234061843-e02d3e81-7929-45fe-8e4b-348f747204f8.png)

![Nyxt palette (sepia)](https://user-images.githubusercontent.com/6666079/234061799-ea41e13b-43cd-4da6-bd4c-271b1ee9b33e.png)

# Pre-Build Checklist:
_talk through the change with someone, then come back and mark off what you can_
- [x] I have consulted with the team.
- [x] One or more developers have signed off on this change.
- [x] One or more user researchers have signed off on this change.

**Comment by lansingthomas** [comment]
@aadcg 
**re:sepia theme**
that is correct, no action for now. Thank you for doing this stuff.

**Comment by aadcg** [comment]
@lansingthomas I'm closing this issue and opening  #2944 to isolate the discussion about the new sepia theme.
