### ISSUE TITLE
update colors in prompt buffer to reflect marking system

### ISSUE THREAD

**Issue by lansingthomas** [atlas-engineer/nyxt#2930]
**Purpose**
We have two input methods for the marking systems in the prompt buffer. The Keyboard and the Mouse. The purpose of this change is to visually communicate the marking system to our users during both input methods and to help them learn the marking system by simplifying it. Less to remember is easier to use.

**What is your proposed change?**
Excuse me if any of these recommendations are already implimented. I know John was working on this marking system a few weeks ago. Please verify that the colors are set properly.

## In the context of Suggestions in the Prompt Buffer:
`Unmarked suggestions` should be `background`
`Marked suggestions` should be `secondary`

#### Input type: Mouse
- `mouse-hover` color (on both marked and unmarked suggestions) should be `accent-alt`to show that a click would invoke that suggestion. (_To be consistent with the other input method_)
- `Ctrl+hover` color (on unmarkeded-suggestions) should be `secondary-alt` (_to show that a click will transition that Suggestion to Marked state_)
- `Ctrl+hover` color (on markeded-suggestions) should be `background-alt` (_to show that a click will transition that Suggestion to Unmarked state_)

#### Input type: Keyboard
- `Keyboard-cursor` color is set properly to `accent`(_to be consistent, and show that a return will invoke the suggestion_)
- Holding `Ctrl` should change the color of `keyboard-cursor` (on unmarked suggestions) to `secondary-alt` (_to show that a `Ctrl+space` [or `Ctrl+enter` if you believe in issue #2931] will transition that Suggestion to Marked state_)
- Holding `Ctrl` should change the color of `keyboard-cursor` (on marked suggestions) to `background-alt` (_to show that a `Ctrl+space` [or `Ctrl+enter` if you believe in issue #2931] will transition that Suggestion to Marked state_)

#### overlapping cases
- In cases where `mouse-hover-color` and `keyboard-cursor` overlap &rarr; `keyboard-cursor-color` should display (_to preserve the understanding of cursor position while trasitioning between input types, AND to match the functional hierarchy [if i mouse-hover over something and hit return the keyboard-cursor postion is what invokes]_)

**Rationale**
Our visual system needs to match our functional system ELSE bad design and confusion. This is the best we have so far.

# Pre-Build Checklist:
_talk through the change with someone, then come back and mark off what you can_
- [x] I have consulted with the team. ( we spoke about it last week on call)
- [x] One or more developers have signed off on this change. 
- [x] One or more user researchers have signed off on this change.

**Comment by aartaka** [comment]
I'm not yet sure if that'd be intuitive enough, but I'll have to try if first :D

**Comment by lansingthomas** [comment]
Can we try it together? I want to see 👀

**Comment by aartaka** [comment]
> Can we try it together? I want to see 👀

Tomorrow, maybe :)

**Comment by lansingthomas** [comment]
@aartaka  and i have been chatting about this and noticed some things.

Most of the proposed changes here are not feasible due to a technical limitation with pressing `control`. 

So the only actionable change from this proposal is to update the mouse hover color &rarr; `accent-alt`

**Comment by aartaka** [comment]
@lansingthomas, that's already done in 8eb1aa0d9c95e63b5423788e8aca12f71fa4c460, closing then?

**Comment by lansingthomas** [comment]
Thank you
