### ISSUE TITLE
match some keybindings with some mouse inputs (marking system)

### ISSUE THREAD

**Issue by lansingthomas** [atlas-engineer/nyxt#2931]
**Is your feature request related to a problem? Please describe.**
I notice some inconsistency, I understand that it matches emacs environment. I am not sure that we need it to be this way in Nyxt.
Currently:
`click` invokes a suggestion
`Ctrl + click` marks an unmarked suggestion OR unmarks a marked suggestion. 

`return` invokes a suggestion
`Ctrl + spacebar` does the same 

**Describe the solution you'd like**
It would be more consistent to have `Ctrl + return` to mark or unmark suggestions.
I am happy with `Ctrl+space` doing the same, though I would like to add `Ctrl+return` as the keybindings for this functionality - at least in CUA mode.

**Describe alternatives you've considered**
IF anyone has a better suggestion please let me know and I will fight for it.

thank you very much mighty Nyxt devs

**Comment by jmercouris** [comment]
Agreed. For CUA bindings especially. For emacs ones not, but for CUA, yes.

**Comment by aartaka** [comment]
> I am happy with `Ctrl+space` doing the same, though I would like to add `Ctrl+return` as the keybindings for this functionality - at least in CUA mode.

So the reasoning here is that `return` is an action that finished the prompt, both as a mere `return` and as a special `M-return`. Using `C-return` for a benign non-termination action (like marking) dilutes this irrevocability of `return`. I'd rather use `C-return` for something like "Return with the alternative action" or "Return with the input, no matter the current suggestion".

**Comment by aartaka** [comment]
> Your argument about irrevocability of the `return` seems sound, and we still might be able to make this more intuitive somehow.
> 
> @aartaka can you think of any examples of these? Or help me understand them in another way. 
> "Return with the alternative action" 

So our `set-url` has lots of different-actions, like `buffer-load*`, `new-buffer-load*`, `new-nosave-buffer-load*` etc. In case of `set-url` the most intuitive action is `buffer-load*` while the second-most and likely the most useful one after it is `new-buffer-load*`. That's what I mean by alternative action: non-default action that's still useful and might benefit from quick shortcut.

> "Return with the input, no matter the current suggestion"

This one is a frequent feature of some interfaces where you have to input some multi-line text. Pressing a mere `return` usualy just inserts a newline, without sending text. To actually send the text, you have to press some other keybinding, usually `C-return` or `s-return`. So this `C-return` key is the "I'm done, send whatever text there is" key in such a case.

**Comment by lansingthomas** [comment]
### So we have [3] things we want to bind.
[1] Mark Suggestion
[2] Return with alternative action
[3] return with input, no matter the current suggestion (after typing multiple lines in the input area)

### Does this make sense?:
`C-return` for [1] Mark Suggestion (to connect with the ctrl+click = mark pair, and the return = invoke pair)
`S-return` for [2] return with alt action
`m-return` for [3] return with input, no matter current suggestion

**Comment by aadcg** [comment]
I don't like the idea of a having 3 keybindings to trigger:

1. a default action; 
2. an alternative one;
3. a menu to choose an action arbitrarily. 

Too much complexity for too little benefit, in my view.

It would trip users over what the default and alternative actions are (we already have this issue with respect to the default action, since it can be dynamically modified). Plus, you'd also need to have a keybinding to dynamically set the alternative action.

**Comment by aartaka** [comment]
Fair, yes. Alt action is quite vague of a concept, not applicable to half of our cases. 

Then having both `C-return`/`C-click` and `s-return`/`s-click` to mean marking (maybe we'll implement the region marking after all...) is a good and consistent option.

**Comment by lansingthomas** [comment]
it looks like the main idea has some consensus. 
`C-return` for mark/unmark suggestion in CUA Mode.
