### ISSUE TITLE
New `sepia` theme | More themes for Nyxt

### ISSUE THREAD

**Issue by aadcg** [atlas-engineer/nyxt#2944]
(_Originally brought up by_ @lansingthomas)

Add a third theme (sepia) to the available options in Common Settings.

![Nyxt palette (sepia)](https://user-images.githubusercontent.com/6666079/234061799-ea41e13b-43cd-4da6-bd4c-271b1ee9b33e.png)

**Comment by aartaka** [comment]
The last time we discussed it with @lansingthomas, our conclusion was that this "sepia" theme is too close to the existing dark theme to be significantly useful. So we thought that we'd better work on some other themes, like terminal-styled or solarized one.

Still, if we evolve the sepia theme into something more distinct (and sepia-ish), I won't oppose adding it.

**Comment by aadcg** [comment]
Personally, I don't see much sense in maintaining more themes other than our default light and dark ones. Users can come up with their own and share them as extensions.

**Comment by aartaka** [comment]
Yes, this sounds right to me.

**Comment by aadcg** [comment]
Closing then @aartaka?
