### ISSUE TITLE
Show me where my words go -- input field border

### ISSUE THREAD

**Issue by lansingthomas** [atlas-engineer/nyxt#2951]
**Purpose**
A subtle highlight to show new users and remind veteran users where key inputs will go as prompt buffer opens up.

**What is your proposed change?**

FOR cases WITHOUT suggested text in the input area: **I propose a border of some kind, around that input area** (probably thin, & in our `accent` color).

Would apply to:
   - the `execute command` prompt buffer input space
   - the `describe-any` prompt buffer input space
   - the `describe-mode` prompt buffer input space
   - the `describe-slot` prompt buffer input space
   - describe: `class`, `command`, `package`, `function`, `variable`

NOT for things like:
- `Open URL` or `Open URL in new buffer` which already have highlighted to bring user attention to the right place.

**Rationale**

1. Anticipate the needs of users (opening `C-space` &rarr; next thing is inputing &rarr; key questions _where do i type?_ &rarr; key answer: right freaking there in the blue accented input area.)
2. We want to connect our users with the keyboard and our prompt buffer at all times. Reminding them exactly where inputs will land in that UI will give a sense of security.
3. I see it in other apps and browsers and it seems sensible.
4. a clear display here gives users good feedback that `execute-command` / `describe-any`... is doing what they intend.

**Constraints**
**We do NOT want the colored border on at all times, ideally the colored border disappears as the first input character displays.** 
We want the colored border to be subtle, not so thicc that it distracts users from their task. 
We want the colored border to only encompass the input area, nothing else.

**Additional context/User story**

**Screenshots/Mock ups**
![Group 192](https://user-images.githubusercontent.com/6666079/236883470-a9d72b48-a28d-454b-9226-e42905de0d60.png)

# Pre-Build Checklist:
_talk through the change with someone, then come back and mark off what you can_
- [x] I have consulted with the team.
- [x] One or more developers have signed off on this change. @aartaka was into it
- [x] One or more user researchers have signed off on this change.

Cool? Yes no? Thoughts?

**Comment by aadcg** [comment]
Sounds good to me!

**Comment by aartaka** [comment]
So that's the best I was able to achieve (due to limitations of CSS geometry thingies that we use). Still, that's a good shot. Will push the change shortly.

![focus](https://github.com/atlas-engineer/nyxt/assets/57838654/feec1803-70d1-4b70-9194-118746d363ea)

**Comment by aadcg** [comment]
Firstly, a PR should be open since it's not such a trivial change as the comment below indicates:

> that's the best I was able to achieve (due to limitations of CSS geometry thingies that we use). Still, that's a good shot.

The spec says:

> We do NOT want the colored border on at all times, ideally the colored border disappears as the first input character displays.

But it doesn't seem to have been implemented in 5d3877e.

**Comment by aartaka** [comment]
> The spec says:
> 
> > We do NOT want the colored border on at all times, ideally the colored border disappears as the first input character displays.
> 
> But it doesn't seem to have been implemented in [5d3877e](https://github.com/atlas-engineer/nyxt/commit/5d3877e52f8faccd8144227db4997e06f58b9ba2).

Oh, right! Reopening :D 

@lansingthomas, why such a requirement? Even if there's input, we need to emphasize the focused state, because one might still focus out and needs a clear marker for that. Changing the color back to "unfocused" state after input is quite unintuitive, both as a accessibility technique and a state marker.

**Comment by aadcg** [comment]
I agree with @aartaka, but (1) I didn't think as much about this as @lansingthomas did and (2) I'm not the UI expert. I'm sure there's a reason behind the spec.

**Comment by lansingthomas** [comment]
>why such a requirement?

Great question! The answer is that at that exact moment another system takes over for that role. As user inputs the first character the prompt buffer is starting to present and filter suggestions. So the user is now looking at the `Suggestions` highlighted in accent blue below. We no longer want to to highlight the input area because the fingers are doing the typing and the eyes have moved on to the new state, in the same task.

**As a low priority**
Here is an edge-case where this highlight feature ought to apply for consistency. 

- [ ] Highlight the input area for FOR cases with highlighted text that has been deleted. 
   - such as: set-URL after the user deletes the highlighted text
      - to see what I mean, follow this recipe (go to a nyxt:new page, invoke set url, delete the text in the input field "nyxt:new", the input field is empty now and should be highlighted)

**Comment by lansingthomas** [comment]
Thanks for you quick turnaround on this guys, I am impressed as always.

I wanted to say that if that border persists for now it is not the end of the world. I would sincerely prefer if we met the spec 100% but I will take 95% if I must.

**Comment by aadcg** [comment]
@lansingthomas I'm 100% convinced. Thanks for the spec.

**Comment by aartaka** [comment]
> Great question! The answer is that at that exact moment another system takes over for that role. As user inputs the first character the prompt buffer is starting to present and filter suggestions. So the user is now looking at the `Suggestions` highlighted in accent blue below. We no longer want to to highlight the input area because the fingers are doing the typing and the eyes have moved on to the new state, in the same task.

Not really. Suggestion are displayed and highlighted at all times, so the idea of them taking the focus is incomplete: they share the focus with the input field from the start, and then they don't fully take the focus in the middle of filtering.

And then, accessibility argument still stands: it's more consistent and state-representing to keep highlighting all the time the input is focused. Because all of us need to see where our inputs go at times.

**Comment by lansingthomas** [comment]
I see what you mean about shared focus between the input container and the `suggestions`. I find myself bouncing back and forth between them. Like this:
```
1. type a few characters (the first half of an invocation like "desc" for describe-X)
2. look at the suggestions
3. maybe use up-arrow or down-arrow to move around.
4. IF I see what I want, I hit `return`
5. ELSE I shift my focus back up to the input container to add or remove characters
```

#### lets consider some quick examples to help us decide on a course of action.
Both ways seem to exist in the world.
1. highlight always
7. highlight only at the start

it seems like 1 (highlight always) makes sense for places where `return` would add a line _(like here in GH input fields :D )_
it seems like 2 (highlight only at the start) makes sense for places where `return` would select a suggestion _(like the upper input field in FF browser/Chrome browser/Brave Browser, which start to present suggestions after the first character)_

Our situation is different from the examples though, because we offer a highlighted suggestion _from an empty input field!_


HHhhhhhhhhhm... . . . . ... .. .. .. .... .. ... . . . ... 
I am willing to accept highlight always.

Can we try with a different color (accent-alt) to differentiate it a bit?  


We can change it later if it feels clunky I suppose.

**Comment by aartaka** [comment]
> Can we try with a different color (accent-alt) to differentiate it a bit?
>
> We can change it later if it feels clunky I suppose.

I mean, accent works too, why use something else?

**Comment by jmercouris** [comment]
Please, let's give more weight to Thomas' opinion, let us trust his judgement! Let us only focus on things that we think are absolutely critical!

We all have different areas of expertise, let's let Thomas do his job, and see what comes of it! :-)

**Comment by aartaka** [comment]
Thomas is not an unquestionable authority. I'm at least versed enough in the matters of accessibility and semantic HTML, so I can chip in when it comes to this. And it comes. @lansingthomas, is that okay for you that I'm arguing with you in these domains? If you want an infinite authority (and infinite responsibility :P), then we can try that :D

**Comment by aadcg** [comment]
I've mentioned this in the past, but allow me to emphasize: it's very important for @lansingthomas that for each UI issue, a PR is  provided with screenshots/demos so that he can validate that the implementation meets the spec.

**Comment by lansingthomas** [comment]
I love the argument, I think we make better stuff.

**Comment by lansingthomas** [comment]
@aadcg thank you yes i appreciate screenshots and demos. They are effective.

I think screenshots in issues is fine or PRs, whatever. As long as it is a prototype/decide then build sort of thing. ( I know REPL can blur this line a bit). 

For this UI recommendation, yes it looks like a PR is the next step

**Comment by jmercouris** [comment]
I'm not suggesting Thomas is a superhuman, I am just suggesting that we give more weight to his ideas! We don't need to challenge him as much as we do. Some challenge is good, too much is tiring!

**Comment by lansingthomas** [comment]
: D

**Comment by lansingthomas** [comment]
My hesitation for the _highlight always_ course of action is that it would change the look of the `input field`/`prompt buffer` in too many cases.

 It would seem like less of a hint and more of a permanent change, as we almost always have an input field in the prompt buffer. (certainly we do for the significant actions {navigation, invocation, filtering suggestions etc.}

**Comment by aadcg** [comment]
@lansingthomas I agree with you. I'm actually having a hard time adapting to the fact that those lines are always highlighted in `accent`.

**Comment by aartaka** [comment]
You can unfocus into the main and they'll stop being highlighted. That's the whole reason for the highlighting—clear representation of the input state.

**Comment by aadcg** [comment]
@lansingthomas will soon point what's lacking and how we can do better on this topic.

**Comment by lansingthomas** [comment]
@jmercouris Hi John, you know some things. Might you have suggestions for fixing the geometry of the highlighted inner border?

**Comment by jmercouris** [comment]
This is mostly possible by using a inset box-shadow in place of a border. Relevant CSS:

```
box-shadow: 0 0 0 2px #178dcc inset
```
