### ISSUE TITLE
WSL nyxt in flatpax error

### ISSUE THREAD

**Issue by fkgruber** [atlas-engineer/nyxt#2966]
Hi 
I installed flatpax on WSL windows 11. 
I then installed nyxt with 
`sudo flatpak install nyxt-3.0.0.flatpak`

and got installed successfully.
However when I try to run it I get:
` flatpak run  engineer.atlas.Nyxt`

> error: Could not connect: No such file or directory

I have never used flatpak before so perhaps I'm missing something.

thanks
Fred

**Comment by aadcg** [comment]
@fkgruber I don't know whether Flatpaks work in WSL but let's assume they do.

Instead of using `sudo`, install it by issuing `flatpak --user install nyxt-3.0.0.flatpak`. Then ensure that `flatpak list` returns Nyxt. Finally, you should be able to run it via `flatpak run engineer.atlas.Nyxt`.

**Comment by aadcg** [comment]
See https://github.com/atlas-engineer/nyxt/issues/1086#issuecomment-1566230012 too.

**Comment by aadcg** [comment]
@fkgruber feel free to re-open if you have more questions. Thanks.
