### ISSUE TITLE
Having input-method support like in emacs

### ISSUE THREAD

**Issue by spiderbit** [atlas-engineer/nyxt#2967]
I use german-postfix input-method in emacs, you can activate that with the command set-input-method, it would be a game changer for me to have that in a browser.

So this specific input system works so that when I type "ae" it creates a "ä", oe -> ö, ue -> ü and sz -> ß.

But if I need the letter combinations without the German umlauts, I just have to repeat the last letter of the combination and it get's translated back.

Sure a good working spell checker could do the same, but this would be more a workaround. Ideally it would support all (emacs) input-method but for me german-postfix would be enough.

**Comment by impaktor** [comment]
In the past I've used abrevs for that (in Emacs), don't know if something similar can be used in nyxt.

**Comment by jmercouris** [comment]
That's actually a really good idea Artyom, I like it!

**Comment by spiderbit** [comment]
@aartaka Thanks, but because I not use much keychords for ergonomic reasons, and use a modular mode in emacs as example this is not that great to me, from a Carpal tunnel syndrome view this keychords are really bad/unhealthy or at least tiring even without this syndrome they are tiring.

I might be able to do something with stumpwm magic, there is a input-key-mapping per application:
```scheme
(define-remapped-keys
    '(("(Firefox|Chrome)"
       ("C-n"   . "Down")
       ("C-v"   . "Next")
       ("M-v"   . "Prior")
       ("M-w"   . "C-c")
       ("C-w"   . "C-x")
       ("C-k"   . ("C-S-End" "C-x")))))
```

basically I would need something like:
("a+e" . "ä")
("a+e+e" . "ae")

or I need to have a better spellchecker that I don't have to click on each item with the mouse like in firefox but be able to y/n go through all suggestions of the whole field.

The problem is with that input method that you want it ideally only active in insert-mode, and for that to work you need some app-solution otherwise it might collide with other tools like "vimium" or with nyxt their keybindings.

**Comment by aartaka** [comment]
> @aartaka Thanks, but because I not use much keychords for ergonomic reasons, and use a modular mode in emacs as example this is not that great to me, from a Carpal tunnel syndrome view this keychords are really bad/unhealthy or at least tiring even without this syndrome they are tiring.

Fair, yes! This I can relate to!

> I might be able to do something with stumpwm magic, there is a input-key-mapping per application:
> 
> ```scheme
> (define-remapped-keys
>     '(("(Firefox|Chrome)"
>        ("C-n"   . "Down")
>        ("C-v"   . "Next")
>        ("M-v"   . "Prior")
>        ("M-w"   . "C-c")
>        ("C-w"   . "C-x")
>        ("C-k"   . ("C-S-End" "C-x")))))
> ```

I use StumpWM key rebinding for normie browsers too!

> basically I would need something like:
> 
> ```scheme
> ("a+e" . "ä")
> ("a+e+e" . "ae")
> ```
> 
> or I need to have a better spellchecker that I don't have to click on each item with the mouse like in firefox but be able to y/n go through all suggestions of the whole field.
> 
> The problem is with that input method that you want it ideally only active in insert-mode, and for that to work you need some app-solution otherwise it might collide with other tools like "vimium" or with nyxt their keybindings.

For that, you can bind keys in in `vi-insert` scheme (if you use VI modes). Note that you'd need to create the keymap first if it doesn't exist in the given mode (@Ambrevar, I guess we should fix it at least for the built-in schemes...)
``` lisp
(define-configuration :document-mode
  ((keyscheme-map
    (progn
      (setf (gethash nyxt/keyscheme:vi-insert %slot-value%)
            (make-keymap "document-vi-insert-map"))
      (keymaps:define-keyscheme-map
          "custom" (list :import %slot-value%)
        nyxt/keyscheme:vi-insert
        (macrolet ((shortcut-insert (character)
                     "A macro shortening commands inserting characters into the buffer."
                     `(lambda-command ,(intern (uiop:strcat "INSERT-" character)) ()
                        (ffi-buffer-paste (current-buffer) ,character))))
          ;; To add "ae", you simply type in a+a (which would resolve
          ;; to mere "a" because prefix "a" plus character "a" is
          ;; bound to no command and thus falls though) and then e.
          (list "a e" (shortcut-insert "ä"))))))))
```

**Comment by spiderbit** [comment]
@aartaka thanks assuming that works, had no chance to test it yet, is close to what I want and I might be ok with that, I just wonder if the aee solution to write ae would not be possible and how well this solution works.
I think this has a problem, as example to have a "s" in a word is much much more common folowed by either another s or another letter, than a german sharp "s" -> "ß".

So let's say in 10% of cases starting with the s I want the sharp s, so I would type very often double s and if I really want a double s I would have to write 4 times s? so that it "falls through"?

Also the solution of writing sz is nearly never needed as real letter combination so maybe in 1% of cases I have to write szz to get the sz instead of the "ß", it's also basically a standard the letter often is calles "es-zett" "s-z".

"called Eszett" (wikipedia), so it's already in my blood if I would want to write on a system that is incapable to write this letters, I would naturally use this letter combinations because every german would understand it, so it's also a good fallback if you sit on another system and have to write. So I am a bit opposed to learn another system.

Especially if it probably is less efficiant, have to write 100x as much "a+a" for every time I would need to write "a+e+e" otherwise and as far as I understand 4 times a to write "aa"?

But I think that is a good start, is there anything that make my wish impossible with this vi-mode?
I mean at worst you would have to define all letters combined with a / u / o / s and bind it to:
a a -> "aa"
a b -> "ab"
"a " -> "a "
"a RET" -> "a RET"
and then your:
"a e" -> "ä"

Or is there a reason you need to use space between the a+a + space + e?

**Comment by aartaka** [comment]
> @aartaka thanks assuming that works, had no chance to test it yet, is close to what I want and I might be ok with that, I just wonder if the aee solution to write ae would not be possible and how well this solution works. I think this has a problem, as example to have a "s" in a word is much much more common folowed by either another s or another letter, than a german sharp "s" -> "ß".
> 
> So let's say in 10% of cases starting with the s I want the sharp s, so I would type very often double s and if I really want a double s I would have to write 4 times s? so that it "falls through"?
> 
> Also the solution of writing sz is nearly never needed as real letter combination so maybe in 1% of cases I have to write szz to get the sz instead of the "ß", it's also basically a standard the letter often is calles "es-zett" "s-z".
> 
> "called Eszett" (wikipedia), so it's already in my blood if I would want to write on a system that is incapable to write this letters, I would naturally use this letter combinations because every german would understand it, so it's also a good fallback if you sit on another system and have to write. So I am a bit opposed to learn another system.

Yeah, my approach is not perfect and certainly requires some mental gymnastics. Not sure how to resolve some of the problems you've outlined except adding modifiers or some rare prefixes.

> But I think that is a good start, is there anything that make my wish impossible with this vi-mode? I mean at worst you would have to define all letters combined with a / u / o / s and bind it to: a a -> "aa" a b -> "ab" "a " -> "a " "a RET" -> "a RET" and then your: "a e" -> "ä"

Spelling out all the simple combinations to save keychords is an option too, and quite a smart one! But yeah, seems like quite a strange and twisted one for such a seemingly simple use-case.

> Or is there a reason you need to use space between the a+a + space + e?

I'm not sure I get this one. Here are two interpretations I've got:
- You mean our keybinding syntax (`"a a e"` etc.) In this case, you can't write `a+a+e`, because that would break our keybinding parser :)
- Or, if you mean adding a space in between the chords that activate special chars, then I guess you don't need space there if it falls though. Just `a+a` (fallthrough "a") and then `e`.

If there's another meaning I didn't get, then I'll be thankful if you rephrase it :)

> I guess a slightly simplified solution would be to always translate "ae" -> "ä" and for the rare cases I need "ae" letter combination instead I could use something like "aaa" or "C-x a" then you don't need to wait for the 3. character on ae before you translate it. That would probably address >90% of the cases.

Yes. It's a matter of hacking the thing you're comfortable with :)

And then, I'm pretty sure that it's actually possible to make a proper mode for input methods. Just that it's probably beyond our scope at the moment. A good extension it would be, though ;)

**Comment by aadcg** [comment]
I believe we've provided plenty of directions on how to implement this.

We can leave this issue open, but I'd like to stress that _the feature is not on our roadmap at the moment_. Thanks.

**Comment by spiderbit** [comment]
> A good extension it would be
You sound like Yoda :D
