### ISSUE TITLE
zoom-ratio-default not respected

### ISSUE THREAD

**Issue by simendsjo** [atlas-engineer/nyxt#2979]
I’ve set zoom-ratio-default for document-buffer, but the zoom ratio is more often than not set as 1.0 when entering a site.
I have to call reset-page-zoom for the zoom to be set to zoom-ratio-default

```lisp
(define-configuration document-buffer
  ((zoom-ratio-default 1.2)))
```

Ref https://discourse.atlas.engineer/t/zoom-ratio-default-doesnt-trigger-automatically/678

**Comment by aadcg** [comment]
I'm able to reproduce this issue. I can't take a look at it. Any takers?

**Comment by aartaka** [comment]
I'm not sure that zoom-ratio-default is the one to set here. In my case,
this piece of config works:

(define-configuration :web-buffer
  ((current-zoom-ratio 1.25)))

I can see how this one can be confusing, though. Maybe we should
simplify the zooming framework in general?

**Comment by simendsjo** [comment]
My understanding was that zoom-ratio-default is a constant value, while current-zoom-ratio changes when zooming in/out. So zoom-ratio-default=1.2 would keep all sites at 120% when opening. Increasing/decreasing zoom would modify current-zoom-ratio. By setting current-zoom-ratio=1.2, a reset would set current-zoom-ratio=zoom-ratio-default.

But this is not the current nor intended behavior?

**Comment by aadcg** [comment]
@simendsjo I think your assessment makes perfect sense. This is a bug.
