### ISSUE TITLE
`slot-value-using-class` to mark deprecated methods and add more metadata in general?

### ISSUE THREAD

**Issue by aartaka** [atlas-engineer/nyxt#2982]
Maybe add a `slot-value-using-class` method for deprecated slots that warns the user on each read/write.  Or maybe just on the first one.

_Originally posted by @Ambrevar in https://github.com/atlas-engineer/nyxt/pull/2978#discussion_r1203588057_

**Comment by jmercouris** [comment]
Hm, very interesting idea. Very interesting...

**Comment by Ambrevar** [comment]
Something else that could help with deprecated functions / methods:

```lisp
(uiop:with-deprecation ((uiop:version-deprecation (asdf:system-version :nyxt)
                                                  :style-warning "3.2"
                                                  :warning "3.4"))
  (defun foo ()
    "Foo docstring"
     17))
```

We could probably leverage this to deprecate slots via MOP.

**Comment by aartaka** [comment]
So what UIOP uses is compiler macros. Which is easy: generate a compiler macro around the accessor generic function and signal the error there:
``` lisp
(define-compiler-macro ACCESSOR (&whole whole object)
  ;; Check for the type to avoid signaling deprecation for unaffected
  ;; accessors. FIXME: allows only one deprecation per accessor (=
  ;; only one of (name buffer) and (name window) would signal
  ;; deprecation if both are marked as deprecated here)...
  (when (typep object 'CLASS)
    ;; Useful for debugging, given the notoriously opaque macro
    ;; expansion mechanisms.
    (let ((form ',whole))
      ;; Should it be an `error'? UIOP does warnings on minor versions
      ;; and errors on major versions. But Nyxt handles lots of errors
      ;; gracefully enough by ignoring them.
      (error
       ;; We have to write this `deprecated' condition ourselves.
       'deprecated :version VERSION :form form :text "Deprecated in favor of NEW-ACCESSOR."))))
```

This approach is safe to use in `nclasses`, because these are

**Comment by Ambrevar** [comment]
But that would fail if there is no accessor or if `slot-value` is used.
Instead would could leverage `slot-value-using-class` to ensure the deprecation message is printed.
That said, we almost never export slots without accessors, so it's not so important for the users.  The point of using `slot-value-using-class` is that it triggers a warning even for core devs.

**Comment by aartaka** [comment]
> That said, we almost never export slots without accessors, so it's not so important for the users. 

Yes, so we can go with a simpler solution before getting to heavy MOP artillery :P

>The point of using `slot-value-using-class` is that it triggers a warning even for core devs.

Yes, that's a benefit, but the point above kinda makes it overkill :)

**Comment by Ambrevar** [comment]
The MOP based approach is trivial to implement though with https://github.com/some-mthfka/slot-extra-options, it's just
- One "extra option" declaration,
- One `slot-value-using-class` specialization against user-classes.

**Comment by aadcg** [comment]
It's too early to think about deprecation notices when Nyxt's API is still a moving target. 

We try to follow semantic versioning, but it was a sin to release 1.0.0.
