### ISSUE TITLE
Panel Buffer Makeover! [1/2]: distinguish between panel and main buffers

### ISSUE THREAD

**Issue by lansingthomas** [atlas-engineer/nyxt#2983]
**Purpose**
1. reduce visual confusion between `panel buffers` and `main buffers` when background colors are similar or matching.

**What is the proposed change?**
1. Add a thin and persistent vertical line to visually divide the content, spanning the entire vertical distance between top and bottom bars.
   - IE: a border on the right edge of panel buffer.

**Rationale**
We can always improve:
1. the current solution (the scroll bar) is not always present, and only covers part of the distance between top bar and bottom bar.
2. Our panel buffers look messy while visiting web pages with similar background colors. As we cannot (and do not wish to) control the content of every web page, we should endeavor to visually divide the panes {panel buffer, main buffer} to reduce cognitive load for me and the web surfing public. :D 
3. A persistent right border will be mostly invisible if main buffer and panel buffer have different background colors, then helpfully visible when background colors are the same.

**Constraints**
- [ ] divider should be subtle, not very noticeable
   - perhaps: `secondary` or `background-alt` colored and super thin (1-2px).
- [ ] divider should straddle the border right where background colors meet, so we do not create a confusing thick middle line.

**Additional context/User story**
I do not know if this has been tried before. I suspect yes. Please let me know what I might be missing or how it was decided NOT to have it.

# Pre-Build Checklist:
_talk through the change with someone, then come back and mark off what you can_
- [ ] I have consulted with the team.
- [ ] One or more developers have signed off on this change.
- [ ] One or more user researchers have signed off on this change.

**Comment by lansingthomas** [comment]
Some mocks of how I imagine this.

Proposed border, no mouse hover.
![with border no hover](https://github.com/atlas-engineer/nyxt/assets/6666079/fa90ef93-f54f-46c7-9d85-b5fe83b0fa3d)

Proposed border, while hovering mouse.
![With border on hover](https://github.com/atlas-engineer/nyxt/assets/6666079/0c40f9b2-447f-4d34-a3dd-9aaa7892526c)

**Comment by aartaka** [comment]
Actually, scrollbar is a good way to separate panel from the main buffer!
- It's OS-native.
- It's recognisable.
- It's functional.
- We can easily [force it via CSS](https://www.w3schools.com/howto/howto_css_force_scrollbars.asp).

I mean, it's weird showing scrollbar when the page is too small, but this is an infinitely reliable way to separate the content!

**Comment by lansingthomas** [comment]
Fair point, also thanks for properly naming this issue.

#### I understand that:
-  the scrollbar does work nicely on medium height `panel buffers`, which is a common situation.
- Currently, the scrollbar dividing power does NOT apply to both, short-`panel buffers` (no scrollbar display) and extra tall-`panel buffers` (scroll bar becomes small and does not cover even half the distance).


#### Possible Solutions
1. Could the scrollbar itself have a border on the right? (same idea different container)
OR
2. Would it look okay if we changed the background color to `background-alt` for the default light theme?
- rationale being that many websites use plain white bg, and by adding a slight shade to our bg we differentiate panes for majority of problem cases. AND we have already established that this color meets the other criteria we care about (matches the rest of the UI, accessibility,..)
- the tradeoff is that some side panels might have codeblocks in them and that contrast would be forked up.
OR
3. A border is implemented for certain ranges where the scrollbar does a poor job.

**Comment by aartaka** [comment]
> Currently, the scrollbar dividing power does NOT apply to both, short-panel buffers (no scrollbar display) and extra tall-panel buffers (scroll bar becomes small and does not cover even half the distance).

It does. We can display scrollbar for both, and that will be enough. Yes, on long panels the scrollbar handle is going to be small, but the scrollbar itself will still be there, having its recognizeable style and containter. Yes, the container is not always visible, but it's distinguishable enough of a pattern—page with a scrolling handle—that one will immediately associate with a separate view.

> Could the scrollbar itself have a border on the right? (same idea different container)

It already has its container, what else do you need for it to be distinguishable?

> Would it look okay if we changed the background color to background-alt for the default light theme?

Changing the color is not going to solve the problem, as I've said elsewhere. It only postpones the moment when one opens the website with exactly the same background and gets lost. Color change needs to be augmented with some other helper (much like in designing color-blind interfaces you have to add some texture/border/animation in addition to clearly insufficient color).

**Comment by aadcg** [comment]
I'm in favor of our UI expert suggestion.

**Comment by aartaka** [comment]
Which one? :P 

I don't agree with the repainting suggestions. Border suggestions are okay. But I'm still on the side of the sidebar as OS-native and recognizeable divider 🤔

**Comment by aadcg** [comment]
> I don't agree with the repainting suggestions. Border suggestions are okay.

I don't understand what you mean by "repainting suggestions" and "border suggestions", could you explain?

For me it seems quite reasonable that we need a divider line between the panel buffer and the main one. Scroll bars serve another purpose, so I don't see how it connects with the topic at hand.

**Comment by aartaka** [comment]
To anchor it to Tom's suggestions above:

> 1. Could the scrollbar itself have a border on the right? (same idea different container)

Yes. Both scrollbar and border work, so why not have both at the same time?

> 2. Would it look okay if we changed the background color to `background-alt` for the default light theme?
> * rationale being that many websites use plain white bg, and by adding a slight shade to our bg we differentiate panes for majority of problem cases. AND we have already established that this color meets the other criteria we care about (matches the rest of the UI, accessibility,..)
> * the tradeoff is that some side panels might have codeblocks in them and that contrast would be forked up.

No to color change, because:
- Some websites are likely to have the same color background and we are merely postponing the problem until the time we encounter such a website.
- And then yes, codeblocks and other interface elements suddenly need a whole new scheme to operate in, which is awful :)

> 3. A border is implemented for certain ranges where the scrollbar does a poor job.

Yes, good too.

------------------------------------------------

Actually, forget about sidebar. Contrasting-enough borders are the best solution here.

The same applies to the long-standing problem of distinct status and message buffers: just add borders there too!

**Comment by aadcg** [comment]
> Yes. Both scrollbar and border work, so why not have both at the same time?

I still don't understand why we're talking about scrollbars. @lansingthomas simply requested a border line. He didn't suggest making any change to the scroll bar.

**Comment by aartaka** [comment]
Forget about sidebar. I've already dropped this idea, see the latest comments.

The initial rationale was: scrollbar is an OS-native (and thus intuitive for any computer user) way to show scrollable and thus independent frames, so we can use scrollbar to show the separatedness of panel buffer. But:
- Scrollbar has another purpose,
- and there are simpler ways to separate panel buffer from the main buffer (yes, border is one of them).

**Comment by aadcg** [comment]
Any taker?

**Comment by jmercouris** [comment]
I'm trying to do it... compilation on my system has been a pain.

**Comment by jmercouris** [comment]
I've been compiling it and playing around with it and it seems that the style slot of the panel-buffer class is not respected at all. Why is this?

**Comment by jmercouris** [comment]
it seems to only use the style from the buffer class...

**Comment by aartaka** [comment]
> I've found the culprit - commit [df55622](https://github.com/atlas-engineer/nyxt/commit/df55622fd08273152b2eb5de963d527be1d7831f). 

No, that's not it. The reason was the use of current buffer styling in the internal pages' `form`. f7639cb9d986cb38622115dd5d7ba6f2a42350ea fixes it.

> What a regression...

The "regression" (from random hard-coded colors unfriendly to the dark theme to the themed unified colors) with panel buffers' styling is another commit: e11ef2f6189b869d0d7f97473d22f56d30dbeee1 👺

**Comment by jmercouris** [comment]
I have not yet pinned the X button, but I have made some progress!

![Screenshot_20230620_230438](https://github.com/atlas-engineer/nyxt/assets/1691662/01521695-0137-499d-ac79-eda8d8a2f836)

**Comment by jmercouris** [comment]
Thinking about having a whole "heading" section pinned. But for now, I will pin the X.

**Comment by jmercouris** [comment]
It is now pinned as well :-)

**Comment by jmercouris** [comment]
I think this is now down, if you want more things Thomas, or if you disagree, please feel free to reopen!

**Comment by jmercouris** [comment]
@aadcg Please remind me again, on which branch should I make the changelog entries, on master? They will then be backported as necessary to 3-series?

**Comment by aartaka** [comment]
> I have not yet pinned the X button, but I have made some progress!
> 
> ![Screenshot_20230620_230438](https://user-images.githubusercontent.com/1691662/247392691-01521695-0137-499d-ac79-eda8d8a2f836.png)

Was this color change discussed with anyone? I don't see any logs or references here. The last time we've decided something [it was border, not the background color.](https://github.com/atlas-engineer/nyxt/issues/2983#issuecomment-1570374592)

Please revert the color change. If you want to put forward another argument in favor of this option, then please do it first—before actually implementing the change.

**Comment by jmercouris** [comment]
That was the original color of the panel buffer before the configuration was not being respected. Therefore, I just brought it back to its original spec :-O

**Comment by aartaka** [comment]
>That was the original color of the panel buffer before the configuration was not being respected. Therefore, I just brought it back to its original spec :-O

Huh, so I could've just reverted the global history back on without asking anyone, because it used to be on? :D

</sarcasm>

Now really, revert it. It was neither discussed, nor at least announced before happening. Such a protocol violation kinda prompts me to violate it too.

I hate that we have huge protocols for "simple" things like UI changes, but they are here for a reason. Revert it and let's discuss it properly.

**Comment by jmercouris** [comment]
Artyom, I shall revert it... but it looks exactly like how it used to! :-O

**Comment by jmercouris** [comment]
dbfecac46

**Comment by jmercouris** [comment]
OK now then, let us vote, who prefers the light gray background I changed it to?

+ [ ] Artyom
+ [ ] Pierre

**Comment by jmercouris** [comment]
@atlas-engineer/atlas 

please vote :-)

**Comment by Ambrevar** [comment]
Non-hardcoded alternate background it fine to me.

**Comment by hgluka** [comment]
I also prefer the background change, but I'm far from an expert in UI design :D

**Comment by jmercouris** [comment]
ALEA IACTA EST!

**Comment by jmercouris** [comment]
It is done: fc0696f1d

**Comment by lansingthomas** [comment]
Yay gray!
