### ISSUE TITLE
Page viewport must shrink when trying to "follow hint"

### ISSUE THREAD

**Issue by sivark** [atlas-engineer/nyxt#2987]
**Purpose**

Suppose there exists a link at the bottom of the page (eg footer).
When interactively filtering the list of hints, the pop-up list ends up hiding the links that one wishes to follow, so it becomes hard to use the visual cue to select a link.

**What is your proposed change?**

It would be nice if the page "scrolled up" / re-rendered in the smaller viewport, so one could continue to see the footer even with the pop-up listing hints.

**Rationale**

1. Keeps the visual cues visible instead of hiding them under the pop-up.

2. More generally, I wonder whether this might be the correct UI whenever the bar pops up (even for commands/etc).

**Constraints**

1. Not sure if this is a simple change.

2. After the change, the behavior might look visually "jumpy". This might be annoying -- especially if it happens any time the pop-up opens (eg: for filtering commands).

# Pre-Build Checklist:
_talk through the change with someone, then come back and mark off what you can_
- [ ] I have consulted with the team.
- [ ] One or more developers have signed off on this change.
- [ ] One or more user researchers have signed off on this change.

**Comment by kflak** [comment]
Newcomer to nyxt here. I agree with this. On the one hand I like the possibility to search through all the elements on a page, on the other hand I much prefer the intuitive behavior of f.x. tridactyl, where hitting `f` brings up hints, and I kan immediately type the hint and get to where I need to be. Or... is there a command for this that I just haven't noticed yet, and that I could rebind to `f`?

**Comment by sivark** [comment]
You mean you can see hints on the page, and type out key sequences to follow them, but there is no pop-up bar that hides part of the page? That "surgical" solution might actual be the simplest!

**Comment by kflak** [comment]
Exactly!

**Comment by aartaka** [comment]
For the prompt-less hint-only matching, there's a `:vi` `hinting-type` option of `hint-mode`, so you're just one config form away from your wish:
``` lisp
(define-configuration :hint-mode
  ((hinting-type :vi)))
```

Closing?

**Comment by aartaka** [comment]
Viewport redraw I'm extremely uncertain about, especially given that we already have a better UI for that use-case :)

**Comment by kflak** [comment]
> For the prompt-less hint-only matching, there's a `:vi` `hinting-type` option of `hint-mode`, so you're just one config form away from your wish:
> 
> ```lisp
> (define-configuration :hint-mode
>   ((hinting-type :vi)))
> ```
> 
> Closing?

Awesome! Just how I like my hints :-) As far as I'm concerned this can be closed.

**Comment by aartaka** [comment]
Good :D

**Comment by sivark** [comment]
Yeah, this seems like the best solution :-)

**Comment by aadcg** [comment]
Thanks @sivark and @kflak for the feedback! I'll also a fan of `:vi` when to comes to `hint-mode`.

There's a more general discussion on this topic that you might be interested in, so that we improve the default behaviour. See #2972.
