### ISSUE TITLE
Input freezes when looking for URL

### ISSUE THREAD

**Issue by kflak** [atlas-engineer/nyxt#2990]
**Describe the bug**
**Precise recipe to reproduce the issue**

When hitting `o` to open the url prompt and typing a few characters, the field completely freezes for several seconds. When unfreezing it will show what I have typed in the mean time. Connection speed seems to make no difference.

**Information**
- OS name+version: Arch Linux 6.3.2-arch1-1
- Graphics card and driver:  ```lspci -k | grep -EA3 'VGA|3D|Display'
00:02.0 VGA compatible controller: Intel Corporation UHD Graphics 620 (rev 07)
	Subsystem: Lenovo UHD Graphics 620
	Kernel driver in use: i915
	Kernel modules: i915```
- Desktop environment / Window manager name+version:
sway version 1.8.1
- How you installed Nyxt (Guix pack, package manager, build from source): pacman
- Information from `show-system-information`:

  If you can't run `show-system-information`, try `nyxt --system-information` from
  a shell.  It this still does not work, please provide the following:
  - Nyxt version (from the `nyxt-version` command or `nyxt --version` from a shell):

```nyxt --system-information
Nyxt version: 3.0.0
Renderer: GI-GTK
Operating system kernel: Linux 6.3.2-arch1-1
Lisp implementation: SBCL 2.3.3 (Dynamic space size: 3221225472)
Features: (:NYXT-GI-GTK :NYXT-GTK :NYXT-GI-GTK :NYXT-GTK :NYXT-3.0 :NYXT-3 :NYXT-3.0.0
 :SLYNK :PLUMP-UTF-32 :PARENSCRIPT :NSYMBOLS :FSET-EXT-STRINGS :GLOBAL-VARS
 :DECLARE-TYPES :SBCL+SAFE-STANDARD-READTABLE :NAMED-READTABLES :SWANK :CL-FAD
 :LPARALLEL :21BIT-CHARS :CUSTOM-HASH-TABLE-NATIVE :CL-PPCRE-UNICODE
 :CL-UNICODE :CL-JSON-DOUBLE-FLOAT-IS-SUBSUMED
 :CL-JSON-SINGLE-FLOAT-IS-SUBSUMED :CHUNGA :FLEXI-STREAMS :CL-PPCRE :WEBKIT2
 :WEBKIT2-2.40 :WEBKIT2-CORS-ALLOWLIST :WEBKIT2-PASTE-PLAINTEXT
 :WEBKIT2-TRACKING :WEBKIT2-MUTE :WEBKIT2-EMOJI :WEBKIT2-MEDIA
 :WEBKIT2-SANDBOXING :GTK-3-22 :GTK-3-20 :GTK-3-18 :GTK-3-16 :GTK-3-14
 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6 :GTK-3-4 :GTK :GDK-3-22 :GDK-3-20
 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12 :GDK-3-10 :GDK-3-8 :GDK-3-6 :GDK-3-4
 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF :CLOSER-MOP :GLIB-2-30 :GLIB-2-32
 :GLIB-2-34 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42 :GLIB-2-44 :GLIB-2-46
 :GLIB-2-48 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56 :GLIB-2-58 :GLIB
 :BORDEAUX-THREADS :LPARALLEL.WITH-CLTL2 :LPARALLEL.WITH-CAS
 :LPARALLEL.WITH-STEALING-SCHEDULER :SPLIT-SEQUENCE
 CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64 CFFI-FEATURES:UNIX :CFFI
 CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP :FAST-IO-SV :FAST-IO
 :CL-JSON-CLOS :CL-JSON :SBCL-USES-SB-ROTATE-BYTE CHIPZ-SYSTEM:GRAY-STREAMS
 :THREAD-SUPPORT :ASDF3.3 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX
 :NON-BASE-CHARS-EXIST-P :ASDF-UNICODE :ARENA-ALLOCATOR :X86-64 :GENCGC :64-BIT
 :ANSI-CL :COMMON-LISP :ELF :IEEE-FLOATING-POINT :LINUX :LITTLE-ENDIAN
 :PACKAGE-LOCAL-NICKNAMES :SB-CORE-COMPRESSION :SB-LDB :SB-PACKAGE-LOCKS
 :SB-THREAD :SB-UNICODE :SBCL :UNIX)

ASDF version: 3.3.1
ASDF registries: (NYXT-SOURCE-REGISTRY ENVIRONMENT-SOURCE-REGISTRY)
Critical dependencies: (/build/nyxt/src/_build/cl-cffi-gtk/gtk/cl-cffi-gtk.asd
 /build/nyxt/src/_build/cl-gobject-introspection/cl-gobject-introspection.asd
 /build/nyxt/src/_build/cl-webkit/webkit2/cl-webkit2.asd)```
  - Lisp implementation/version (if built from source):
  - Kernel name+version:
  - WebKitGTK+ | QtWebEngine version:

**Output when started from a shell**

**Comment by kflak** [comment]
It only seems to happen in the URL input field. I type a few characters, the field freezes, comes back after a few seconds, before it freezes up again. Happens with a default configuration, as well as in vi mode.

**Comment by aadcg** [comment]
I can't reproduce either. The only thing that comes to mind is that it may be connected with `search-engine-url-source`.

@kflak Tere Tulemast!

**Comment by kflak** [comment]
Aitäh, @aadcg! Will snoop around a bit and fiddle with some search-engine settings, then.

**Comment by kflak** [comment]
Tried with the example config from the search-engines section:
```
(defvar *my-search-engines*
  (list '("google" "https://google.com/search?q=~a" "https://google.com")
        '("python3" "https://docs.python.org/3/search.html?q=~a"
          "https://docs.python.org/3")
        '("doi" "https://dx.doi.org/~a" "https://dx.doi.org/"))
  "List of search engines.")
(define-configuration context-buffer
  "Go through the search engines above and `make-search-engine' out of them."
  ((search-engines
    (append
     (mapcar (lambda (engine) (apply 'make-search-engine engine))
             *my-search-engines*)
     %slot-default%))))
```

Still the same result. If I delete everything in `~/.local/share/nyxt`, then I manage to get to a website before everything freezes.

**Comment by aadcg** [comment]
@kflak unfortunately I can't reproduce these issues...

I suspect that there are issues in the way that this is package for Arch Linux. Could I ask you to try out Nyxt using one [the ways that the development team curates](https://github.com/atlas-engineer/nyxt/releases)? We have a flatpak and a self-contained bundle. 

With respect to the way it's packages in Arch (which is outside of our control), can you report which WebKitGTK version is used in the build? Lately the releases of this dependency have been rather unreliable. We know that 2.40.1 works well.

**Comment by kflak** [comment]
Trying with flatpak, I get this output:

```
❯ flatpak run engineer.atlas.Nyxt 

(process:2): Gtk-WARNING **: 10:56:53.983: Locale not supported by C library.
	Using the fallback 'C' locale.
Nyxt version 3.1.0
<INFO> [10:56:54] Source location: #P""
<INFO> [10:56:54] Listening to socket: #P"/run/user/1000/nyxt/nyxt.socket"
<INFO> [10:56:54] GTK extensions directory: #P"/home/kf/libraries/web-extensions/"
<INFO> [10:56:57] GTK extensions directory: #P"/home/kf/libraries/web-extensions/"
flatpak-spawn: Invalid byte sequence in conversion input
Try "flatpak-spawn --help" for more information.
<WARN> [10:56:57] Warning: Web process terminated for buffer 6831 (opening ) because it crashed
flatpak-spawn: Invalid byte sequence in conversion input
Try "flatpak-spawn --help" for more information.
flatpak-spawn: Invalid byte sequence in conversion input
Try "flatpak-spawn --help" for more information.
<WARN> [10:56:58] Warning: Web process terminated for buffer 6882 (opening nyxt:new) because it crashed
<WARN> [10:56:58] Warning: Error in signal on renderer thread: The value
  NIL
is not of type
  CL-WEBKIT2:WEBKIT-WEB-VIEW
when binding CL-WEBKIT2::WEB-VIEW
<WARN> [10:56:58] Warning: Error in FFI method: The value
  NIL
is not of type
  CL-WEBKIT2:WEBKIT-WEB-VIEW
when binding CL-WEBKIT2::WEB-VIEW
<INFO> [10:56:58] Loading #P"/home/kf/.var/app/engineer.atlas.Nyxt/data/nyxt/history/default.lisp".
<WARN> [10:56:58] Warning: Error in FFI method: The value
  NIL
is not of type
  CL-WEBKIT2:WEBKIT-WEB-VIEW
when binding CL-WEBKIT2::WEB-VIEW
flatpak-spawn: Invalid byte sequence in conversion input
Try "flatpak-spawn --help" for more information.
<WARN> [10:56:58] Warning: Web process terminated for buffer 6944 (opening nyxt:new) because it crashed
<WARN> [10:56:58] Warning: Error in signal on renderer thread: The value
  NIL
is not of type
  CL-WEBKIT2:WEBKIT-WEB-VIEW
when binding CL-WEBKIT2::WEB-VIEW
<WARN> [10:56:58] Warning: Error in FFI method: The value
  NIL
is not of type
  CL-WEBKIT2:WEBKIT-WEB-VIEW
when binding CL-WEBKIT2::WEB-VIEW

```

**Comment by kflak** [comment]
Also realized that I hadn't updated my system before installing nyxt with pacman (shame on me...), so I did that, and now it seems to work more or less OK. However, the hint mode is a bit hit and miss: sometimes I get the hints, sometimes not. But I suppose that's another issue :-)

The url interface seems to be snappy enough, though, so I suppose this issue can be closed and chalked up to my stupidity in not keeping my system up to date.

**Comment by aadcg** [comment]
@kflak, I can't reproduce the Flatpak issue you've found.

I'm happy you have Nyxt running. You'd be glad to hear more feedback from you on Github or https://discourse.atlas.engineer/.
