### ISSUE TITLE
Documentation: how to enable blocker-mode by default?

### ISSUE THREAD

**Issue by kflak** [atlas-engineer/nyxt#2992]
**Is your feature request related to a problem? Please describe.**
I can't find any simple configuration example in the docs for simply enabling blocker mode without any customizations.

**Comment by aartaka** [comment]
Here's a snippet:
``` lisp
(define-configuration :web-buffer
  "Enable blocker-mode for all the web buffers."
  ((default-modes (append (list :blocker-mode) %slot-value%))))
```

The skeleton for it is part of nyxt:manual#configuration section, so it's there in the docs already. Just need to adjust the mode name!
