### ISSUE TITLE
Ligatures in prompt-buffer (for monospace font). Problem just in my setup?

### ISSUE THREAD

**Issue by simendsjo** [atlas-engineer/nyxt#3000]
I get some "ligatures" in my prompt buffer. See how `fi` is rendered:

![image](https://github.com/atlas-engineer/nyxt/assets/351519/95bcd4d9-80dc-4526-8b89-51526a0f2588)

It's not rendered like this in html, e.g. when using Iosevka:
![image](https://github.com/atlas-engineer/nyxt/assets/351519/e5e4ebce-e36a-4207-8f72-4c2774e712a6)

I see prompt-buffer override the font family, could this be the reason?
`:font-family "monospace,monospace"`

So it's my operating system which is configured strangely?

EDIT: When disabling the font override, I get the expected output:

![image](https://github.com/atlas-engineer/nyxt/assets/351519/102c8b79-4fc7-4698-9f1f-a7155f003b17)

EDIT2: It doesn't seem like there's an easy way to modify `style` without copy/paste the entire old block?

**Comment by aartaka** [comment]
> I get some "ligatures" in my prompt buffer. See how `fi` is rendered:
> 
> ![image](https://user-images.githubusercontent.com/351519/243079240-95bcd4d9-80dc-4526-8b89-51526a0f2588.png)
> 
> It's not rendered like this in html, e.g. when using Iosevka: ![image](https://user-images.githubusercontent.com/351519/243080218-e5e4ebce-e36a-4207-8f72-4c2774e712a6.png)
> 
> I see prompt-buffer override the font family, could this be the reason? `:font-family "monospace,monospace"`

Yes, that most probably is.

> So it's my operating system which is configured strangely?

Yes. `monospace,monospace` uses the system default monspace font.

> EDIT: When disabling the font override, I get the expected output:
> 
> ![image](https://user-images.githubusercontent.com/351519/243080729-102c8b79-4fc7-4698-9f1f-a7155f003b17.png)

A proof of the hypotheses above :D

> EDIT2: It doesn't seem like there's an easy way to modify `style` without copy/paste the entire old block?

If you mean configuration, then it's achievable with `%slot-value%`:
``` lisp
(define-configuration :prompt-buffer
  ((style
    (str:concat
     %slot-value%
     (theme:themed-css (theme *browser*)
       `(*
         :font-family "Iosevka"))))))
```

**Comment by simendsjo** [comment]
> > So it's my operating system which is configured strangely?
> 
> Yes. `monospace,monospace` uses the system default monspace font.

Thanks, I see it now:

```xml
	<alias>
		<family>monospace</family>
		<prefer>
			<family>Noto Sans Mono</family>
			<family>DejaVu Sans Mono</family>
			<family>Inconsolata</family>
			<family>Andale Mono</family>
			<family>Courier New</family>
			<family>Cumberland AMT</family>
			<family>Luxi Mono</family>
			<family>Nimbus Mono L</family>
			<family>Nimbus Mono</family>
			<family>Nimbus Mono PS</family>
			<family>Courier</family>
		</prefer>
	</alias>
```

> > EDIT2: It doesn't seem like there's an easy way to modify `style` without copy/paste the entire old block?
> 
> If you mean configuration, then it's achievable with `%slot-value%`:

Last one wins then? I didn't know I could override just by adding a new entry like that, thanks!

**Comment by aartaka** [comment]
> Last one wins then? I didn't know I could override just by adding a new entry like that, thanks!

Yes, in most cases. In cases it doesn't work you can try something like:
``` lisp
`(* 
  :font-family "Iosevka" !important)
```

Which is a CSS-native way to override any previous style.
