### ISSUE TITLE
Edit User Files button still not working for me

### ISSUE THREAD

**Issue by lansingthomas** [atlas-engineer/nyxt#3006]
**Describe the bug**
3.1.0
default config
Ubuntu

"Edit User Files" button on the common settings internal page is still not getting me where I want to go.

**Precise recipe to reproduce the issue**

I try to open the wide world of editing configurations from the `settings` page, and get this message in the message buffer. Warning: Please set `external-editor-program` browser slot"

This is fine, I can start figuring all that out... Do we not have a default text editor already? Is there not an extension? I asked John to try this on his machine and the result was different. His machine brings up a prompt buffer with some options. 

from my attempt at editing configuration files from within nyxt:
![config file button screenshot](https://github.com/atlas-engineer/nyxt/assets/6666079/8acc9510-7dd9-4cb0-a381-a0936a203825)

**solution might look like**
My dream experience here teaches me a bit about configurations generally, and holds my hand (just a bit!) while I setup the app for more general use.
```
1. press the button
2. the nyxt default editor opens up for me
3. my configuration file is open before me
4. comments in that file explain what it is, and how I might use it.
```

I would like this to be easy for me and for those who come after : )
Thank you!
Please advise.

**Comment by jmercouris** [comment]
Exactly Andre!

**Comment by lansingthomas** [comment]
### update for this issue:
- My `external-editor-program` slot is now properly set to something ("gedit" the Ubuntu stock text editor)

Understanding that @hgluka is working on reworking the common settings page;
- this one button could maybe use some attention from someone else.

Here is what's going on:
https://github.com/atlas-engineer/nyxt/assets/6666079/6c2002b8-c677-4767-bd4e-79ee2697bcc4

**Comment by aartaka** [comment]
> ... the button should redirect the user to Nyxt's built-in editor. Relying on an external editor requires lots of guessing (which text editors are available) 

Nyxt built-in editor is unreliable too, because extensions may override it to be anything (or even nothing.)

> and then one never knows which text editor the user actually knows how to use.

That's why it's configurable — one can define it to be any editor they want. And the default is user-set too — if they don't know what EDITOR/VISUAL means, they likely don't have it set.

Overall, I'd say two buttons (one for built-in editor, one for external editor) are a more transpatent way to edit things than one button that opens things in "THE editor", which is still 50% unreliable/unconfigured.

**Comment by hgluka** [comment]
Does the built-in editor also require configuration before it works? If so, that should definitely be in the common settings page as well.

**Comment by jmercouris** [comment]
It should not require any configuration to work, it should work by default!

**Comment by aartaka** [comment]
> Does the built-in editor also require configuration before it works? If so, that should definitely be in the common settings page as well.

Though we ship plaintext-editor-mode with Nyxt, it's a single huge textarea, which is not exactly usable as an editor. So yes, built-in editor only shines when extended with something like nx-ace 😀

**Comment by hgluka** [comment]
> It should not require any configuration to work, it should work by default!

When I try to `edit-file`, I get a page that says: "Please configure an editor mode to use an editor buffer. See describe-class for editor-buffer to see the list of functions to implement."
There's even a warning that says the same: "Warning: Editor buffer cannot edit files without configured editor mode.
See `describe-class editor-mode' for details."

But when I add:
```lisp
(define-configuration nyxt/mode/editor::editor-buffer
  ((default-modes (cons 'nyxt/mode/editor::plaintext-editor-mode %slot-value%))))
```
to my config.lisp, then I get the plaintext editor when I `edit-file`.

**Comment by hgluka** [comment]
Ah, right. I thought that it was already supposed to work. That's an easy fix, then!
