### ISSUE TITLE
Issuing command `nyxt-version` on Flatpak fails

### ISSUE THREAD

**Issue by aadcg** [atlas-engineer/nyxt#3009]
It lacks a clipboard program such as `xclip` or `xsel`. Needs to be added to the Flatpak package declaration.

Perhaps we should wrap `(trivial-clipboard:text +version+)` with `ignore-errors` nonetheless.

**Comment by aartaka** [comment]
> Perhaps we should wrap `(trivial-clipboard:text +version+)` with `ignore-errors` nonetheless.

One thing that should be even better is to rely on new `trivial-clipboard:content`, wrap it into an `:around` method, and catch a specific type of errors there, passing the rest to debugger.
