### ISSUE TITLE
Make `if-confirm` have always/never option.

### ISSUE THREAD

**Issue by aartaka** [atlas-engineer/nyxt#3018]
Some of the yes/no prompt often require always/never options to persist affirmative/negative answer. We are doomed to have enough use-cases for that some day, so let's prepare:
- Add the "always" and "never" options to `if-config`.
- Come up with a way to structure `if-config` body in relation to 4 options (because having four body forms won't cut it. Something `case`-like?
``` lisp
(if-confirm ("Prompt"
             :yes "ay"
             :no "nope"
             :never "no way"
             :always "thousand times yes")
    (:yes (do-once))
    (:always (do-once-and-save))
    (:no (nothing))
    (:never (nothing-and-save)))
```

**Comment by Ambrevar** [comment]
I like it!

**Comment by jmercouris** [comment]
Basically we are reinventing switch :-D

**Comment by aadcg** [comment]
Let's not put the cart before the horse.
