### ISSUE TITLE
Error building on Gentoo

### ISSUE THREAD

**Issue by zovt** [atlas-engineer/nyxt#302]
Hello, I'm trying to build on Gentoo, but I'm getting an error (attached). Let me know if you need any more information, happy to help debug.
[output.txt](https://github.com/atlas-engineer/next/files/3488472/output.txt)

**Comment by Ambrevar** [comment]
Strange, it seems that your version or UIOP is missing some
components.  Maybe it's outdated?

Run

    sbcl --non-interactive --eval '(format t "~a" uiop:*uiop-version*)'

in a shell and share the result here.

Do you have anything in `~/common-lisp`?  Did you install ASDF / UIOP manually?

**Comment by zovt** [comment]
[output.txt](https://github.com/atlas-engineer/next/files/3489065/output.txt)

I have no `~/common-lisp` folder in my home folder, nor did I install anything manually outside.

**Comment by Ambrevar** [comment]
It seems that your SBCL installation is broken, or at least
"non-standard".
Could you report this issue on the Gentoo forums / bugtracker?

**Comment by tsandstr** [comment]
I had some issues installing, but enabling the testing versions of ASDF and UIOP in portage fixed them, I believe.

**Comment by jmercouris** [comment]
Can you please clarify which version of ASDF and UIOP was required so that we may update the documentation?

**Comment by Ambrevar** [comment]
@tsandstr Any luck running Next on Gentoo?  Would you like to work on an Ebuild?

**Comment by Ambrevar** [comment]
@zovt  Any luck?

**Comment by bqv** [comment]
@zovt @tsandstr do either of you have an ebuild to share?

**Comment by yigitemres** [comment]
> 
> 
> @zovt @tsandstr do either of you have an ebuild to share?

I can share my ebuild if you want it.

**Comment by bqv** [comment]
Switched to nix, don't need it now. I don't have one I created either. Feel free to share for others that may see this later though

**Comment by fturco** [comment]
@yigitemres: can you post your ebuild to Gentoo Bugzilla, please? https://bugs.gentoo.org/692718

**Comment by yigitemres** [comment]
@fturco Done. I'm currently not using any GUI (WSL Gentoo) but it is installed.

**Comment by fturco** [comment]
@yigitemres: thank you!

**Comment by yigitemres** [comment]
@fturco Thank you for proposing to adding nyxt as official package. When you have a chance, can you tell me that ebuild is work for you or not? If not works, I'm gonna fix on my localrepo according to your fixes.

**Comment by fturco** [comment]
I tried installing nyxt with your ebuilds, but unfortunately it fails with:
```
  Unable to load any of the alternatives:
   ("libgtk-3.so.0" "libgtk-3.so")
```
I only have Qt on my system, and I don't really want to mess up my system in order to install GTK at this moment...

It would be nice if it were possible to add the `qt` and `gtk` USE flags to the ebuild in the future.

**Comment by Ambrevar** [comment]
The QtWebengine renderer support is still incomplete at the moment
(help welcome!).  For now, you need GTK to run Nyxt.

**Comment by jmercouris** [comment]
It worked for a short period of time... but we have made so many changes since then.

**Comment by yigitemres** [comment]
> 
> 
> I tried installing nyxt with your ebuilds, but unfortunately it fails with:
> 
> ```
>   Unable to load any of the alternatives:
>    ("libgtk-3.so.0" "libgtk-3.so")
> ```
> 
> I only have Qt on my system, and I don't really want to mess up my system in order to install GTK at this moment...
> 
> It would be nice if it were possible to add the `qt` and `gtk` USE flags to the ebuild in the future.

Adding  "=x11-libs/gtk+-3*" to dependency will solve the issue. BTW, Gentoo's Bugzilla is so ancient (cannot remove attachments, edit comments...) that I wanna use Funtoo instead of Gentoo.

**Comment by crocket** [comment]
I also can't build nyxt on gentoo.

```
$ make all
sbcl --no-userinit --non-interactive --eval '(require "asdf")' --eval '(when (string= "true" "true") (setf asdf:*default-source-registries* nil) (asdf:clear-configuration) (asdf:load-asd "/mnt/data/src/nyxt//nyxt-quicklisp.asd") (asdf:load-system :nyxt-quicklisp))' --eval '(asdf:load-asd "/mnt/data/src/nyxt//nyxt.asd")' --eval '(when (find-package :ql) (funcall (read-from-string "ql:quickload") :cffi))' --eval '(when (and (find-package :cffi) (uiop:getenv "GUIX_ENVIRONMENT")) (pushnew (pathname (format nil "~a/lib/" (uiop:getenv "GUIX_ENVIRONMENT"))) (symbol-value (read-from-string "cffi:*foreign-library-directories*" )) :test (quote equal)))' --eval '(ql:quickload :nyxt/gi-gtk-application)' \
        --eval '(asdf:make :nyxt/gi-gtk-application)' \
        --eval '(uiop:quit)' || (printf "\n%s\n%s\n" "Compilation failed, see the above stacktrace." && exit 1)
fatal error encountered in SBCL pid 30585 tid 30585:
Can't find sbcl.core


Compilation failed, see the above stacktrace.

make: *** [Makefile:41: nyxt] Error 1
```

**Comment by crocket** [comment]
Is there a way to build nyxt without access to the internet? By default, gentoo packages require building programs without access to the internet.

**Comment by jmercouris** [comment]
Of course there is, it is built on Guix and Nix.

**Comment by crocket** [comment]
I'm trying to create a gentoo package for nyxt. A gentoo package shouldn't rely on guix or nix.

**Comment by jmercouris** [comment]
Sure, I'm not saying that it should. I'm just saying that Nix and Guix manage it, so it is possible. Just make sure to download all QL packages before compilation.

**Comment by crocket** [comment]
The problem is that I have no prior experience with common lisp. So, I'm clueless, here.

**Comment by jmercouris** [comment]
I see. Well, hold tight, we are going to merge something in that will eliminate the need for QL during compilation and that will fix your issue.

**Comment by Ambrevar** [comment]
Done with https://github.com/atlas-engineer/nyxt/pull/1802.
@crocket Does master or `2-series` work for you?  We are going to release version 2.2.1 very soon with this new Quicklisp-less setup.

**Comment by Ambrevar** [comment]
This error seems unrelated to Nyxt.  Something might be wrong with your SBCL install.

**Comment by jmercouris** [comment]
Unfortunately the archive files do not come with the submodules.

**Comment by crocket** [comment]
How can I specify a prefix path?

**Comment by crocket** [comment]
make PREFIX=/usr install worked.

People can now test https://github.com/crocket/crocket-overlay/tree/master/www-client/nyxt
