### ISSUE TITLE
Simplify zooming API

### ISSUE THREAD

**Issue by aartaka** [atlas-engineer/nyxt#3020]
**Is your feature request related to a problem? Please describe.**
We have five (!) slots related to zooming. I routinely confuse these, and wonder why all of them are here. I mean, yeah, it ensures the right zoom ratio and makes all the process real configurable, but is it worth the complexity? I think it's not.

**Describe the solution you'd like**
I'm thinking that we should remove these five slots for just one of two:
- `zoom-ratio` (currently called `current-zoom-ratio`),
- and maybe `zoom-ratio-step`.

All the other ones are not really necessary:
- `zoom-ratio-min` is useless and restrictive. The real restriction here is the renderer and its zooming restrictions. No need to reproduce them on the Lisp side.
- Same for `zoom-ratio-max`—if one wants to scroll 10x in and renderer allows that, why should we stop them?
- `zoom-ratio-default`—this one is managed by the renderer, and synchronising renderer default and Nyxt default is not really worth it, I guess.
  - I myself often confuse `zoom-ratio-default` and `current-zoom-ratio`, because both are implied to Just Work ™️ on the page. But it seems that zoom-ratio-default is not even used where it should #2979. So it'll be easier to remove it. 

And then, we make a setter method for `zoom-ratio`, which would call the `ffi-buffer-zoom-level` directly:
```
(defmethod (setf zoom-ratio) (value (buffer document-buffer))
  ;; Because zooming to negative values is meaningless?
  (unless (not (plusp value))
    (setf (slot-value buffer 'zoom-ratio) value
          (ffi-buffer-zoom-level buffer) value)))
```

With that setter, `zoom-page` and `unzoom-page` etc. turn into one-liners:
```
(define-command zoom-page (&key (buffer (current-buffer)))
  "Zoom in the current page BUFFER."
  (incf (zoom-ratio buffer) (zoom-ratio-step buffer)))

(define-command unzoom-page (&key (buffer (current-buffer)))
  "Zoom out the current page in BUFFER."
  (decf (zoom-ratio buffer) (zoom-ratio-step buffer)))

(define-command reset-page-zoom (&key (buffer (current-buffer)) (ratio 1.0))
  "Reset the BUFFER zoom to the RATIO."
  (setf (current-zoom-ratio buffer) ratio))
```

Yes, we imply several thing here:
- Default zoom is 1.0.
- Zoom does not fall below 0.
- `ffi-buffer-zoom-level` is `setf`-able (it is) and is lenient to arbitrary floats (it is: I just set it to 30 and it zoomed in like a good machine.)

**Describe alternatives you've considered**
Leaving it as is? It kinda works, so why break it?

**Additional context**
#2979 and #3015.

**Comment by hgluka** [comment]
I think I mostly agree, `zoom-ratio-min` and `zoom-ratio-max` don't seem necessary and the code you propose is simpler.  The only thing I'm not sure about is removing `zoom-ratio-default`. That might be useful from an accessibility standpoint.

**Comment by aartaka** [comment]
Thanks a lot! And the remark on `zoom-ratio-default` makes perfect sense too ❤️

**Comment by Ambrevar** [comment]
I did a bit of git-blaming, to see why the hell we had a `zoom-ratio-min` in the first place... Turns out that it was introduced by... LispKit, from arcane times before Nyxt! :p 

Safe to remove `zoom-ratio-min` and `zoom-ratio-max` in my opinion.

**Comment by aartaka** [comment]
> I'm just wondering, what's the connection between Nyxt and LispKit. It seems that this chapter of the project is unknown to me!

This one is piece of Heroes Era for Nyxt:
- @jmercouris was writing Lisp compilers.
- Then he found LispKit, and was collaborating with people there.
- LispKit died eventually, causing lots of grievances in the land of Lispy browsers.
- So John set out on a long journey to make a proper browser in CL.
- The path was dark and dangerous and there were lots of paths tested: Cocoa, QtWebEngine, WebKit.
- At some point John joined efforts with Pierre, a like-minded traveller from the lands of Lispy FOSS software.
- And finally, there was a sturdy boat that happened to work, and the name for her was Nyxt 1.0 😍
