### ISSUE TITLE
vi-modes not working properly

### ISSUE THREAD

**Issue by fictitiousexistence** [atlas-engineer/nyxt#3030]
**Describe the bug**
Using the settings button to choose vi keybindings inserts broken settings to autoconfig causing vi-mode /vi-normal to not be properly added to default modes.

**Precise recipe to reproduce the issue**
Open nyxt for the first time. 
Click settings 
Choose vi keybindings 

Below code is put into the auto config. 

`(defmethod customize-instance ((input-buffer input-buffer) &key)`
`(disable-modes* 'nyxt/mode/emacs:emacs-mode input-buffer)`
`(enable-modes* 'nyxt/mode/vi:vi-normal-mode input-buffer))`

Removing above code and putting the below makes vi-normal work properly.
`(define-configuration web-buffer`
`((default-modes`
`(pushnew 'nyxt/mode/vi:vi-normal-mode %slot-value%))))`

Also, putting an option to choose what mode to use for the prompt buffer may help folks as well. 
For instance, setting vi keybindings will set vi-normal mode for the web buffer and the prompt buffer. 

Other vi based browsers do not require you to press i after pressing 'o' or ':'. Instead you just start typing. 
You can change the prompt buffer to vi-insert to fix that but I personally found vi-modes to be unhelpful in the prompt buffer.

For example, if you set the prompt buffer to vi-insert, you need to press escape twice to get out of the prompt buffer. 

I turn vi and emacs off for the buffer and just use cua. This makes it behave more like other vi based browsers like luakit. 

`(defmethod customize-instance ((prompt-buffer prompt-buffer) &key)`
`(disable-modes* 'nyxt/mode/emacs:emacs-mode prompt-buffer)`
`(disable-modes* 'nyxt/mode/vi:vi-normal-mode prompt-buffer))`

**Comment by aartaka** [comment]
Fixed in e5c8920d2a1284ed0538ecc3738abcebcae77e51 (although our common settings screen is still quite a death from a thousand cuts in lots of other regards...)
