### ISSUE TITLE
Prompt buffer discoverability: list useful commands

### ISSUE THREAD

**Issue by aartaka** [atlas-engineer/nyxt#3032]
**Purpose**

Make prompt buffer as an interface more discoverable.

**What is your proposed change?**

List the most useful prompt buffer commands somewhere in the prompt buffer. Possibly as an input placeholder as in https://github.com/atlas-engineer/nyxt/commit/d857f6cee54558a06bed3ddbbec90e69591753b6.

**Rationale**

Because this would immediately illuminate one about the facts that prompt buffer has:
- Input history.
- Multiple return actions.
- And a dedicated help page.

**Constraints**

_What are the constraints?_ @lansingthomas, you have to expand on what this field means, so that us non-design people understand the specific meaning "constraints" bear here. And in general, the form of "WORD: what is the WORD" is not exactly illuminating 😜

Anyways, the constraints are:
- It should be short: to fit into any prompt input.
- It should list as little keybindings as possible.
- But, counter-intuitively, it should cover as much prompt facilities as possible:
   - Marking.
   - Alternative actions
   - History.
   - Resumed prompts.
   - Source/attribute toggling.

**Additional context/User story**

- I am a first-time Nyxt user.
- I come from:
  - Vim-styled tools.
  - Or CUA distant lands.
- In other words, I'm not aware of Emacs and Emacs-derived interfaces.
- So prompt buffer looks like a weird and overloaded input.
- But if I see the suggestions for how to act, get help, or recall previous prompts, I'm suddenly much more 
  - confident
  - and aware of prompt goodies!

Quite a short yet effective prompt onboarding, huh?

**Screenshots/Mock ups**

Here's the look of the commit mentioned above.
![](https://user-images.githubusercontent.com/45483512/247076377-746e281e-5fdc-4674-9101-c87672d3cb69.png)

# Pre-Build Checklist:
_talk through the change with someone, then come back and mark off what you can_
- [ ] I have consulted with the team. 
- [ ] One or more developers have signed off on this change. @aadcg @jmercouris  
- [ ] One or more user researchers have signed off on this change. @lansingthomas

**Comment by aartaka** [comment]
> We'd be documenting advanced behaviour and therefore confusing newcomers.

Which of the 
```
BUFFER-LOAD*
NEW-BUFFER-LOAD*
NEW-NOSAVE-BUFFER-LOAD*
COPY-URL*
```
Is advanced? Having more action options to the commands is not confusing once you understand: these are alternative actions. That's it—it suddenly is clear and useful.

Most of our alternative actions are well-documented, so the only "confusing 😱" thing that we have to alternative actions is a fact that new propt opens on top of the old one. Is that something unusual? No, we do that all over the place.

I might be missing something, though. Any user story for when one gets confused with prompt buffer?

**Comment by aartaka** [comment]
Well, placeholder is not a good place for anything, actually. Any other place we can put help into? Helm uses overriden mode line.

**Comment by jmercouris** [comment]
What if we had an ellipse button next to each entry in the prompt buffer so that the user could select the action with the mouse?

**Comment by jmercouris** [comment]
True... we'll have to do some testing to see. Maybe right click is the *right* way ;-)

**Comment by lansingthomas** [comment]
> What are the constraints? @lansingthomas, you have to expand on what this field means, so that us non-design people understand the specific meaning "constraints" bear here. And in general, the form of "WORD: what is the WORD" is not exactly illuminating 😜

- very true! Id be happy to explain constraints. They are constraints :D 
- we can remove this field for now. the purpose was to get people thinking about functional requirements (Concise statements of what the design must achieve) early in the process but it is not working

**Comment by lansingthomas** [comment]
Sorry I am a bit late to the party here.

I really like the purpose of this thread: **"Make prompt buffer as an interface more discoverable."**

@aartaka let's talk about it on video. Maybe we can exchange enough ideas that good things will happen.

**Comment by lansingthomas** [comment]
@aadcg @aartaka I WANNA EAT SOME SHARKS. 🍴 🦈 

Artyom are you interested in video-talking about this topic? -- perhaps Friday or Monday. 

Andre I know you are busy with Electron. So, feel invited but not required : )

**Comment by aartaka** [comment]
>Artyom are you interested in video-talking about this topic? -- perhaps Friday or Monday. 

Let's do Monday.

**Comment by lansingthomas** [comment]
Cool cool -- I will wait.

**Comment by lansingthomas** [comment]
> broad and unactionable

many good problems are :D

---

Capturing a thought for later (no action required):

I notice that Nyxt is about creating these loops of efficiency, where a helpful browsing action can be saved and captured in different ways {bookmarking, tagging, annotating, creating a custom rule in a dot file,...}, then recycled next time the action is attempted.  Hopefully to be better, faster,...

How might we select preferred/favorite commands for easier recall?

I like how when I want to bookmark something, I can just `X-x` and it's done -- loop updated.

I wonder if we might be able to do something similar for commands, perhaps a `best-commands` list or `favorite-commands.

Maybe even simply re-ordering command suggestions by recent use wold be helpful.
