### ISSUE TITLE
Config files location on Flatpak

### ISSUE THREAD

**Issue by aadcg** [atlas-engineer/nyxt#3044]
In #2802 @jmercouris wondered about the fact that Nyxt's config file lives at `~/.var/app/engineer.atlas.Nyxt/config/nyxt`, which contradicts the usual expectation path, `~/.config/nyxt`.

Nyxt's config files location logic is dead simple: they live at `$XDG_CONFIG_HOME/nyxt` so, by default, it will point to `~/.config/nyxt`. 

The tricky part is that [Flatpak is quite opinionated](https://docs.flatpak.org/en/latest/conventions.html?highlight=.var#xdg-base-directories) and hardcodes $XDG_CONFIG_HOME, providing [no way](https://github.com/flatpak/flatpak.github.io/issues/191) to [override it](https://github.com/flatpak/flatpak/issues/2413). So, perhaps contrary to one's expectation, the odd location for the config files is not related to the fact that Flatpaks are sandboxed environments. For example, Emacs' Flatpak reads the config from the usual `~/.emacs/init.el`.

-----

Given these facts, we have two options:

1. Ensure symmetrical config paths files (by complicating Nyxt's `nfiles` logic);
2. Accept the differences.

**Comment by jmercouris** [comment]
It is still a complication of nfiles logic, even if simple. I definitely think it is an issue that belongs to nfiles actually. If the feature flag for flatpak is set, can we force it to use the *original* `XDG_HOME`?

**Comment by jmercouris** [comment]
I see the problem, so we would be assuming the path of `~/.config/nyxt`. What if the user could wrap their Nyxt application in a wrapper script that uses a command line argument to set the config file location?
