### ISSUE TITLE
Superpositon logic of `--remote`, `--eval`, `--load` and `--quit` flags

### ISSUE THREAD

**Issue by aadcg** [atlas-engineer/nyxt#3047]
#2759 introduced very interesting changes to control Nyxt remotely. 

Issuing `nyxt --remote` starts a Nyxt interpreter. I think `nyxt --remote --load ...` and `nyxt --remote --eval...` should presuppose the use of `--quit`, even when omitted, since that's the behavior users expect. [For more context see this thread](https://discourse.atlas.engineer/t/how-to-open-a-new-browser-window-from-command-line/811/5).

CC @Ambrevar

**Comment by Ambrevar** [comment]
This is by design: if we presuppose `--quit`, there is no way to remote-eval without quitting.
I can imagine some users would like to drop to an interpreter after loading or evaluating, it's common to do this for many interpreters.

**Comment by aartaka** [comment]
> I see the use case of entering the interpreter after loading or evaluating, but I don't think it should be the default behavior.

So the problem with `--remote` is that it's quite a special mode of operation. It's not controlled by the user, and is only controlled by the script you provide it. What should it do when there's no script? Making it behave like a REPL is somewhat an arbitrary choice, yes. But it's better than hanging due to absence of script file.

Default behavior of `--remote` is having a script. `--remote` without script argument is not an intended use at all, thus our use of the REPL instead.

And, given that there are people wanting a mechanism for direct communication with Nyxt from the shell—we also cover their needs, which is a win-win 😛

**Comment by aartaka** [comment]
> I'm not convinced by this, since if the user wants to have the interpreter at his disposal, then we would most likely prefer to pass `--remote` alone.

Not really. I'd expect `--load`/`--eval` to do some initialization before entering the `--remote` REPL. Doing the initialization when already in this REPL is non-automatable and too verbose in general.

**Comment by aartaka** [comment]
> [Re-opening since one of our users concurs with me](https://discourse.atlas.engineer/t/how-to-open-a-new-browser-window-from-command-line/811/7). I need a good argument against it. Who can deliver it?

Their use-case is evaluating something and getting back the results, don't bend it where it's not. No more than that. It doesn't imply this or that behavior of `--remote`, it implies a certain behavior of `--eval`. I'm pretty sure they will be satisfied if `--eval` prints its results on the stdout. Which is #1453. 

------------------------------------------------------

Note that the only reason linked topic mentions `--remote` is that you've mentioned `--remote` in the other thread. So it's not really about `--remote` itself, it's about a certian instance of `--eval` that happens to contain `--remote`.

**Comment by aartaka** [comment]
Overall, I'd say that both are advanced and rare enough. If one wants to use them, then they are probably ready to pick the right combination of flags. We're providing enough options here, and all of them are suitable for the use-cases there are, even if with a couple of flags more.

**Comment by Ambrevar** [comment]
I agree with @aartaka last assessment: we're talking advanced features here, and the "most frequent use case" is highly debatable.

Going with @aadcg's suggestion would mean introduce a new CLI flag for debatable benefits.

**Comment by Ambrevar** [comment]
You're introducing `--server`, that's what I meant.
