### ISSUE TITLE
`internal-pages` aren't self-aware of themselves

### ISSUE THREAD

**Issue by aadcg** [atlas-engineer/nyxt#3051]
Steps to reproduce:

- Issue command `changelog`;
- Evaluate `(internal-page-p (find-internal-page-buffer 'changelog))` and verify that it returns `nil`.

The expected behaviour would be to return `t`. The bug holds for all internal pages.

**Comment by aartaka** [comment]
> * Evaluate `(internal-page-p (find-internal-page-buffer 'changelog))` and verify that it returns `nil`.

But wait, `internal-page-p` checks for whether an object is an `internal-page` (i.e., special page-generating subclass of `command`), so `buffer` technically is not an `internal-page-p` 😝

**Comment by aartaka** [comment]
No, no, the emoji is just me being hyper-emotional (and caring about the text accessibility and thus stopping to use things like ":p")

Yes, the use-cases are there, but there are other ways to achieve it. E.g. `(internal-page-name (url buffer))`. And then, making the class predicate to be overridable or replacing it altogether is… confusing at best.

**Comment by aartaka** [comment]
No, it's not a bug. It's the intended behavior of `internal-page-p`—checking whether the object is an `internal-page` instance. Nothing else.

**Comment by Ambrevar** [comment]
Got confused too when you opened the issue, but then I recalled that it is why it's called `internal-page-p` and not `internal-buffer-p` !

But yeah, it's confusing...
