### ISSUE TITLE
headings panel mouse pointer

### ISSUE THREAD

**Issue by mmahmoudian** [atlas-engineer/nyxt#3054]
**Is your feature request related to a problem? Please describe.**
in headings panel, the text and mouse pointer behave in a way as if the items are not clickable (although they are).

**Describe the solution you'd like**
My suggestion is of two folds:
1. the mouse cursor turns to pointing finger (like any other link in a normal web page) when hovering over the items in the heading panel
2. the current heading (the one that the top of the page is inside it) gets some indication. Either font change (underline, bold, color) or an indicator arrow appears instead of the bullet point on the left side, or the background color of the item changes (this is not good as it would be hard to choose a color that is colorblind friendly).

**Describe alternatives you've considered**
Sorry, I don't have alternative in mind at the moment.

**Additional context**

[Peek 2023-06-28 17-32.webm](https://github.com/atlas-engineer/nyxt/assets/390889/4a6766fb-8270-45e5-9d13-9d1f4c353e89)

**Comment by jmercouris** [comment]
Indeed, this is a generalized problem with our buttons! I'll handle!

**Comment by aartaka** [comment]
But then, pointer is but a part of it. There should also be a hover style for links/buttons in the panel buffer, so that it's even more apparent that the thing under pointer is clickable.

**Comment by jmercouris** [comment]
Fixed with: caea50040

and: 418276a4d
