### ISSUE TITLE
Bump `cl-webkit` git submodule

### ISSUE THREAD

**Issue by aadcg** [atlas-engineer/nyxt#3057]
I think we forgot to bump it when we released version 3.5.9.

https://github.com/joachifm/cl-webkit/commit/3d1e8156e5b1d29b07b3a8fecb868318bdfdbcbf

Keeping this issue as a remainder.

**Comment by Ambrevar** [comment]
Done with 92d64c58f81db7bd160e5dbfdf7ce737fdf3a9c9.
