### ISSUE TITLE
Setting dark theme via `common-settings`

### ISSUE THREAD

**Issue by aadcg** [atlas-engineer/nyxt#3059]
Steps to reproduce:

- `nyxt`
- `M-x common-settings`
- Click "Use dark theme"
- Restart Nyxt

It seems to be related to the fact that it writes a non-readable symbol `#<...` at `$XDG_CONFIG_HOME/nyxt/auto-config.3.lisp`.

```lisp
(defmethod customize-instance ((browser browser) &key)
  (setf (slot-value browser 'theme) #<theme:theme {100105DD03}>))
```

**Comment by aartaka** [comment]
Done in cf55c2659508a53663313a69c154b8affe3adb1a!
