### ISSUE TITLE
Nyxt doesn't respect XDG directories 

### ISSUE THREAD

**Issue by aadcg** [atlas-engineer/nyxt#3061]
Steps to reproduce:

- `nyxt -e '(namestring (files:expand *config-file*))'` => `$HOME/.config/nyxt/config.lisp`
- `XDG_CONFIG_HOME=$HOME/Downloads/`
- `nyxt -e '(namestring (files:expand *config-file*))'` => `$HOME/.config/nyxt/config.lisp`

In the last step the expected result would be `$HOME/Downloads/nyxt/config.lisp`.

**Comment by jmercouris** [comment]
> > * XDG_CONFIG_HOME=$HOME/Downloads/
> 
> Should be
> 
> `export XDG_CONFIG_HOME=...`

Good catch, I didn't even notice these commands were on separate lines!
