### ISSUE TITLE
Ensure UI uniformity of prompt buffer's input area

### ISSUE THREAD

**Issue by aadcg** [atlas-engineer/nyxt#3086]
Notice the lack of uniformity in the screenshots below.

`execute-command`

![2023_07_19_12:47:14-nyxt](https://github.com/atlas-engineer/nyxt/assets/45483512/81574b9a-b003-4b0d-a96e-84d4ae56eb4b)
----
`toggle-suggestions-display`

![2023_07_19_12:47:24-nyxt](https://github.com/atlas-engineer/nyxt/assets/45483512/e3f50422-3338-4188-a5a5-96ff819d61f1)
-----
Issuing a prompt buffer command that sets the prompt buffer height to `:fit-to-prompt`, e.g. `follow-hint` with `hinting-type` set to `:vi`.

![2023_07_19_12:47:36-nyxt](https://github.com/atlas-engineer/nyxt/assets/45483512/64fc241d-f182-43bc-86e3-274b383ecb94)

**Comment by lansingthomas** [comment]
#### record of video meet:
Andre and I spoke about this and the lack of uniformity was described as:
- the input prompt areas in screen shot 2 and 3 should match -- and resemble screen shot 1 (something funny is happening...)
- the blue _action_ focus indicator in the area for all three is not displaying properly
   - missing bottom in screenshot 2
   - missing top in screenshot 3
- in screenshot 2 we are missing a primary-colored line and white line in between the mode line and the input prompt area
- in screenshot 3 the primary-colored top barrier is missing
