### ISSUE TITLE
Missing start up page glyphs on Flatpak

### ISSUE THREAD

**Issue by aadcg** [atlas-engineer/nyxt#3094]
Install the latest Nyxt flatpak and start it via `flatpak run engineer.atlas.Nyxt --failsafe`. 

@jmercouris can you reproduce? A simple solution might be to use `➡`, instead of `🡪`.

![2023_07_24_12:56:35-nyxt](https://github.com/atlas-engineer/nyxt/assets/45483512/17e50171-7bd9-4672-98e0-6f1a6d0c3ab6)

**Comment by jmercouris** [comment]
Indeed, that would be a fix, but I don't like it. I think now that we've figured out a way to load and inject SVGs we should have @lansingthomas come up with some for our usage.

**Comment by jmercouris** [comment]
Right, I get what you are saying, but an SVG can also work very well and provide something without a custom font

**Comment by lansingthomas** [comment]
Custom SVGs incoming

**Comment by lansingthomas** [comment]
I have the same issue on my system.

I propose removing the arrows for the moment.

I am working on another way to do the arrow's job.

Might look like: 
![3 0 nyxt_new layout colors (light theme)](https://github.com/atlas-engineer/nyxt/assets/6666079/441da0ef-19be-4de3-81f6-d7f1dc410d9c)

**Comment by jmercouris** [comment]
Yes.

**Comment by jmercouris** [comment]
Got it! Will handle.

**Comment by jmercouris** [comment]
https://github.com/atlas-engineer/nyxt/pull/3105
