### ISSUE TITLE
Spec for typography - & change default font size

### ISSUE THREAD

**Issue by lansingthomas** [atlas-engineer/nyxt#3104]
**Purpose**
A unified declaration of style, visual consistency.

**Proposed change**
Iterate / adopt this specification for nyxt pages like `manual` and `tutorial`, and other appropriate places in the documentation

![Typography Guide (6)](https://github.com/atlas-engineer/nyxt/assets/6666079/8f2ac06d-3b57-4352-adc9-22de61b3f8c4)

![Typography Guide (7)](https://github.com/atlas-engineer/nyxt/assets/6666079/bdce341f-5437-4adc-903a-f2381d6af575)

---

# Pre-Build Checklist:
- [x] prototyped with a dev
- [ ] I have consulted with the team here on the forum.
- [x] One or more developers have signed off on this change.
- [x] One or more user researchers have signed off on this change.

**Comment by lansingthomas** [comment]
@artyom thanks for talking through this stuff with me earlier this week. I changed the sizing a bit like we talk about and also check out the new font -- Public sans (looks way better than Open sans!)

**Comment by jmercouris** [comment]
Bam! Public sans is now the default font!

**Comment by jmercouris** [comment]
![Screenshot_20230803_183734](https://github.com/atlas-engineer/nyxt/assets/1691662/bc6dbdfb-ad05-4c2d-9124-c34a80294b11)
