### ISSUE TITLE
Replace quick start navigation arrows with those of status buffer

### ISSUE THREAD

**Issue by aadcg** [atlas-engineer/nyxt#3112]
With the addition of the new arrows, it would be great to be consistent.

![2023_08_04_15:21:00-nyxt](https://github.com/atlas-engineer/nyxt/assets/45483512/be7a1b1f-9ea0-427b-b893-633d0c06a70b)

@jmercouris? :)

**Comment by jmercouris** [comment]
it can be done, depends on what Thomas thinks!

**Comment by jmercouris** [comment]
@lansingthomas what say ye?

**Comment by lansingthomas** [comment]
Good idea.
Consistency is good for users.

Let's change the color of the buttons to reflect interaction state as as well.
Backward (not-clickable)
![backward-history-1](https://github.com/atlas-engineer/nyxt/assets/6666079/c16aa41d-02dd-48b1-bb42-175fdbb4cfe8)
- surface: primary
- text contrast-text


Backward (clickable)
![backward-history](https://github.com/atlas-engineer/nyxt/assets/6666079/6083eb19-1f01-47af-94c7-24ab6bee032c)
- surface: action
- text contrast-text
- 
Forward (not clickable)
![Forward-history-1](https://github.com/atlas-engineer/nyxt/assets/6666079/b2397adc-0c2c-4ea4-86f0-6c7d6cce5841)
- surface: primary
- text contrast-text

Forward (clickable)
![Forward-history](https://github.com/atlas-engineer/nyxt/assets/6666079/c6038fbc-6fd6-4478-8c30-c9da572e19b1)
- surface: action
- text contrast-text

**Comment by lansingthomas** [comment]
Dark theme:
backward: (not-clickable)
![backward-history-1](https://github.com/atlas-engineer/nyxt/assets/6666079/002e0c0a-76aa-4b77-b8ad-8250e7930e34)

backward (clickable)
![backward-history](https://github.com/atlas-engineer/nyxt/assets/6666079/ab2d13e3-4621-4de2-b432-c4540840081c)

Forward  (not-clickable)
![Forward-history-1](https://github.com/atlas-engineer/nyxt/assets/6666079/8b3cfc08-38cf-410c-b16c-af08e2a8a626)

Forward (clickable)
![Forward-history](https://github.com/atlas-engineer/nyxt/assets/6666079/47eb13ae-109c-47ee-aecb-bf1878e1eaa2)

**Comment by lansingthomas** [comment]
I want that nice blue to guide our new nyxters down the path :D

**Comment by jmercouris** [comment]
I shall prrrrrovide.

**Comment by lansingthomas** [comment]
@jmercouris while you are in there, would you please make it so that `left` and `right arrow` keys change the pages appropriately in the `quick-start`

**Comment by lansingthomas** [comment]
Yeah good point Andre. 

@jmercouris can you pretty please try these combos for the clickable-arrow-panel-buffer-buttons:

**light theme default state:** `action` (#37A8E4) for the surface color and `text+` (#000000) for the arrow icons.
light theme hovered state: `action+` (#72CDFE) for the surface color and `text+` (#000000) for the arrow icons.

**dark theme (amphora) default state:** `action` (#4C21AB) for the surface color and `text+` (#FFFFFF) for the arrow icons.
dark theme (amphora) hovered state: `action+` (#571FD2) for the surface color and `text+` (#FFFFFF) for the arrow icons.

**Comment by jmercouris** [comment]
Started on branch: quickstart-navigation-arrows but I can't yet get the computer to agree with me. A little more work yet.

**Comment by lansingthomas** [comment]
> @lansingthomas pro tip: if you surround hex colors in between ticks (`...`), the color is displayed.

aaaaaaaah coool `#37a8e4`
Thank you Andre :D

**Comment by jmercouris** [comment]
Notice, the Pull request I made does not address the color changes. That is part of a bigger issue which I will tackle soon after!
