### ISSUE TITLE
Repository for cl-colors has changed

### ISSUE THREAD

**Issue by cage2** [atlas-engineer/nyxt#3113]
Hi!

I think that maybe you could be interested to know that the location of the repository of cl-colors ha schanged to codeberg:

https://codeberg.org/cage/cl-colors2

Hope this is usetul.
Bye!
C.

**Comment by jmercouris** [comment]
Thanks for the heads up!

**Comment by Ambrevar** [comment]
Done with 98ff8a4f56b9f8bd01dd58cd983c24c4e2364992.
