### ISSUE TITLE
Prompt buffer point rounding

### ISSUE THREAD

**Issue by lansingthomas** [atlas-engineer/nyxt#3114]
**Purpose of request:**
1. Visually communicate to users the subtle sense that Nyxt is a modern UI.
2. Gently improve information processing in people's brains

**Describe your proposed change:**
gentle corner rounding for the points of our chevrons (~2px)

**Why do you believe this to be an improvement?**
- corner rounding is a common technique in map making and other information dense visual communication environments -- we should adopt it in Nyxt when it fits our mission/brand/context.
   - our UI is not supposed to be very bright (as it is a background for the information on webpages), and rounded corners appear less bright visually
   - the points of the chevrons direct attention/eyeballs to the adjacent input field/content, which is the main focus. So a rounded path is appropriate for easier movement.

**Additional context/User story:**
This difference is not always perceptible, but is still important.
If you are curious, you can do a little experiment -- try tracing a circle with the movement of your eyes, now try tracing a shape with sharp corners like a square or a hexagon. What do you notice? 

**Screenshots/Mock ups:**
#### Here is what rounded points look like:
![rounded points](https://github.com/atlas-engineer/nyxt/assets/6666079/1cdbc769-2cb0-4dbe-a4f6-970c1d4be1fb)

#### here is the current pointy prompt buffer (for comparison):
![pointy points](https://github.com/atlas-engineer/nyxt/assets/6666079/a40a784d-0866-4f60-8d53-18ea4928c80e)

---

### Pre-Build Checklist:
- [ ] Discussion has occurred.
- [ ] One or more developers have signed off on this change.
- [ ] One or more user researchers have signed off on this change.

**Comment by jmercouris** [comment]
This has proven surprisingly difficult to do because we are using clip-path. There are other ways to do this of course, but they feel hacky and a misuse of CSS.

**Comment by lansingthomas** [comment]
Don't break anything important or stress to much for this one. Let's leave it open and add a low-priority label.

**Comment by jmercouris** [comment]
I AM NOT ONE TO GIVE UP
![Screenshot_20230829_180552](https://github.com/atlas-engineer/nyxt/assets/1691662/744f64c4-e796-458e-8dbf-dd7a44d66829)


I HAVE SUCCEEDED

**Comment by jmercouris** [comment]
Will fix the prompt buffer arrows, and then merge this :-)

**Comment by jmercouris** [comment]
Done with: 7b4a77f38

**Comment by jmercouris** [comment]
![Screenshot_20230829_181923](https://github.com/atlas-engineer/nyxt/assets/1691662/10f27caa-f037-4faa-be0d-4355bcbf3146)

**Comment by jmercouris** [comment]
Aha :-D OK I wasn't sure it merited an entry, but will add.
