### ISSUE TITLE
Remove Qt port from the repo

### ISSUE THREAD

**Issue by aartaka** [atlas-engineer/nyxt#3121]
Qt renderer code has been rotting in the repo for some couple of years now. Given that it's not functional (and would be extremely hard to get functional again) and we picked Electron as a replacement for it, it is only adding a burden on us and causing confusion to our users (c.f. #3118). 

Will be safer and simpler to remove all of Qt support code, I believe.

**Comment by jmercouris** [comment]
I agree with you.

**Comment by jmercouris** [comment]
Also true...

**Comment by aartaka** [comment]
> For someone who studies Nyxt's source code, it looks like the easiest way to have Nyxt running with Chromium's engine.

Given how much Qt port drifted away from the current state of things, implementing something on top of it would require a huge update effort to work with current Nyxt. Relying on our (underdocumented, but still well-structured) foreign-interface.lisp and renderer/gtk.lisp would be a better shot, because it shows a working approach with lots of problems encountered since Qt port already solved.
