### ISSUE TITLE
affordances for the toggle-modes menu (checkboxes)

### ISSUE THREAD

**Issue by lansingthomas** [atlas-engineer/nyxt#3134]
**Purpose of request:**
show users which modes are active, and which are inactive

**Describe your proposed change:**
adding checkboxes 

**Why do you believe this to be an improvement?**
1. different modes are on or off at different times, we must show user what will happen when they press return.
2. Checkboxes are proposed over radios to communicate mutual inclusivity (some modes appear to me mutually exclusive but they are not (keybindings schemes can be stacked for example))

**Additional context/User story:**
I tried putting the checkboxes in other places and it looked yucky.

**Screenshots/Mock ups:**
![modes- checkboxes (2)](https://github.com/atlas-engineer/nyxt/assets/6666079/cc3ae1de-8adc-4ae3-9a93-21079ade4487)

![modes- checkbox alignment (1)](https://github.com/atlas-engineer/nyxt/assets/6666079/2ea39439-ad99-4035-99c4-f59e690ac2f4)

---

### Pre-Build Checklist:
- [ ] Discussion has occurred.
- [ ] One or more developers have signed off on this change.
- [ ] One or more user researchers have signed off on this change.

**Comment by jmercouris** [comment]
I think the checkboxes are an easy way for people to understand what is and is not selected. It is in my opinion superior to simply a color. If you overcommunicate something visually, it is probably better than undercommunicating it.
