### ISSUE TITLE
Delete `nyxt-quicklisp.scm`

### ISSUE THREAD

**Issue by aadcg** [atlas-engineer/nyxt#3141]
Does anyone actually use it? Guix and Quicklisp are the antithesis of each other, so I don't see much benefit in the combination.

CC @Ambrevar @aartaka @jmercouris.

**Comment by aartaka** [comment]
Yep, seems quite conflicting. 

Nix would work with Quicklisp (because, IIRC, Nix is really bad at handling Lisp packages), but Guix definition is unlicely to influence Nix in any way (c.f. the argument of keeping Qt port to help a potential porting effort in #3121).

Unrelated: I remember that we had a Quicklisp interface somewhere. Was it removed due to irrelevance?

**Comment by Ambrevar** [comment]
There was a reason to be, for this module: to allow Guix-based devs to reproduce errors reported by people using Quicklisp.

That said, it's an admittedly limited scope, and if someone is using Quicklisp, it means they probably know enough Common Lisp to help us sufficiently to debug their issue.

**Comment by Ambrevar** [comment]
Sure thing, but my point was not about maintenance, it was about an easy way to reproduce the environment of the user when trying to fix their bug.

**Comment by Ambrevar** [comment]
How would you reproduce a user bug then?

**Comment by jmercouris** [comment]
We don't support whatever is in the quicklisp dist, it may be fully incompatible or not even compile. It is outside the scope of what we do. If someone reports a bug running Nyxt via some unsanctioned method, we don't debug it, it is their problem.

**Comment by Ambrevar** [comment]
Isn't that a bit extreme?

**Comment by jmercouris** [comment]
I don't think it is very extreme. We have a product, we guarantee it works in ways X, Y, Z. We don't guarantee that it works in /all/ ways, and we can't afford to help people debug it on every kind of system and set-up. We don't make it hard for them to do so, we just don't offer them direct assistance. It seems fine to me.
