### ISSUE TITLE
built in text-editor

### ISSUE THREAD

**Issue by lansingthomas** [atlas-engineer/nyxt#3162]
**Purpose of request:**
make some quick improvements to the built in text editor -- so that it is useful enough for new users to explore and edit their user files ^^
1. improve discoverability of the basics (write)
2. error prevention for lost work

**Describe your proposed change:**
These are not original ideas... but here they are:
[1] save button -- the command `editor-write-file` is great, seems to work. But is not discoverable.
   - I would like to see a button (with the associated keybinding displayed)
   
[2] error prevention for closing an unsaved file
   - I know there are some tricky cases with this but it would be nice to get a message like --  "Are you sure you want to close this unsaved text file?"

**Describe alternatives you've considered**
the related path is helping people set up external text editors. I see this as a good thing, but not for today.

**Additional context**
- I will share mock ups for this soon... the issue up to capture peoples ideas, so lets hear it.

**Comment by lansingthomas** [comment]
[This hypothetical UI](https://github.com/atlas-engineer/nyxt/issues/3200) would solve this issue.

**Comment by jmercouris** [comment]
Pull request #3296 will /partly/ close this issue. It will fix the problem and allow us to set this as the default editor for users. It will however not fix all the problems, it won't warn of closing unsaved files, etc. However, it will at least work out of the box!

**Comment by aadcg** [comment]
Stale.
