### ISSUE TITLE
3.7.0-1 crashes on startup.

### ISSUE THREAD

**Issue by irthomasthomas** [atlas-engineer/nyxt#3175]
**Describe the bug**

**Precise recipe to reproduce the issue**

For website-specific issues:
Can you reproduce this issue with Epiphany / GNOME Web (https://wiki.gnome.org/Apps/Web)?

**Information**
**Linux Desk 6.5.3-1-MANJARO #1 SMP PREEMPT_DYNAMIC Wed Sep 13 12:21:35 UTC 2023** x86_64 GNU/Linux

- Graphics card and driver: 
**2 x Nvidia geforce, driver 535.104.05**

- Desktop environment / Window manager name+version:
** X11 KDE Plasma 5.5**

- How you installed Nyxt (Guix pack, package manager, build from source):
**Pacman official manjaro repo**

################################################################################################################################

- Information from `show-system-information`:
  If you can't run `show-system-information`, try `nyxt --system-information` from
  a shell.
  
❯ nyxt --system-information
Nyxt version: 3.7.0
Renderer: GI-GTK
Operating system kernel: Linux 6.5.3-1-MANJARO
Lisp implementation: SBCL 2.3.8 (Dynamic space size: 3221225472)
Features: (:NYXT-GI-GTK :NYXT-GTK :NYXT-GI-GTK :NYXT-GTK :NYXT-3.7 :NYXT-3 :NYXT-3.7.0
 :CLIPBOARD-CONTENT-METHOD :SWANK :SLYNK :PLUMP-UTF-32 :PARENSCRIPT :NSYMBOLS
 :FSET-EXT-STRINGS :SBCL+SAFE-STANDARD-READTABLE :NAMED-READTABLES :GLOBAL-VARS
 :CL-FAD :LPARALLEL :21BIT-CHARS :CUSTOM-HASH-TABLE-NATIVE :CL-PPCRE-UNICODE
 :CL-UNICODE :CL-JSON-DOUBLE-FLOAT-IS-SUBSUMED
 :CL-JSON-SINGLE-FLOAT-IS-SUBSUMED :CHUNGA :FLEXI-STREAMS :CL-PPCRE :WEBKIT2
 :WEBKIT-2.40.5 :WEBKIT-2.40 :WEBKIT-2 :WEBKIT2-CORS-ALLOWLIST
 :WEBKIT2-PASTE-PLAINTEXT :WEBKIT2-TRACKING :WEBKIT2-MUTE :WEBKIT2-EMOJI
 :WEBKIT2-MEDIA :WEBKIT2-SANDBOXING :GTK-3-22 :GTK-3-20 :GTK-3-18 :GTK-3-16
 :GTK-3-14 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6 :GTK-3-4 :GTK :GDK-3-22
 :GDK-3-20 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12 :GDK-3-10 :GDK-3-8 :GDK-3-6
 :GDK-3-4 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF :CLOSER-MOP :GLIB-2-30 :GLIB-2-32
 :GLIB-2-34 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42 :GLIB-2-44 :GLIB-2-46
 :GLIB-2-48 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56 :GLIB-2-58 :GLIB
 :BORDEAUX-THREADS :LPARALLEL.WITH-CLTL2 :LPARALLEL.WITH-CAS
 :LPARALLEL.WITH-STEALING-SCHEDULER :SPLIT-SEQUENCE
 CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64 CFFI-FEATURES:UNIX :CFFI
 CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP :FAST-IO-SV :FAST-IO
 :CL-JSON-CLOS :CL-JSON :SBCL-USES-SB-ROTATE-BYTE CHIPZ-SYSTEM:GRAY-STREAMS
 :THREAD-SUPPORT :ASDF3.3 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX
 :NON-BASE-CHARS-EXIST-P :ASDF-UNICODE :ARENA-ALLOCATOR :X86-64 :GENCGC :64-BIT
 :ANSI-CL :COMMON-LISP :ELF :IEEE-FLOATING-POINT :LINUX :LITTLE-ENDIAN
 :PACKAGE-LOCAL-NICKNAMES :SB-CORE-COMPRESSION :SB-LDB :SB-PACKAGE-LOCKS
 :SB-THREAD :SB-UNICODE :SBCL :UNIX)

ASDF version: 3.3.1
ASDF registries: (NYXT-SOURCE-REGISTRY ENVIRONMENT-SOURCE-REGISTRY)
Critical dependencies: (/build/nyxt/src/_build/cl-cffi-gtk/gtk/cl-cffi-gtk.asd
 /build/nyxt/src/_build/cl-gobject-introspection/cl-gobject-introspection.asd
 /build/nyxt/src/_build/cl-webkit/webkit2/cl-webkit2.asd)

################################################################
################################################################

**Output when started from a shell**

Nyxt version 3.7.0
<INFO> [12:59:00] Source location: #P"/usr/share/nyxt/"
<INFO> [12:59:00] Listening to socket: #P"/run/user/1001/nyxt/nyxt.socket"

** (nyxt:125295): WARNING **: 12:59:00.789: Error loading plugin: libnuspell.so.5: cannot open shared object file: No such file or directory

** (nyxt:125295): WARNING **: 12:59:00.790: Error loading plugin: libvoikko.so.1: cannot open shared object file: No such file or directory

** (nyxt:125295): WARNING **: 12:59:00.791: Error loading plugin: libhspell.so.0: cannot open shared object file: No such file or directory

<INFO> [12:59:00] Loading #P"/home/tommy/.local/share/nyxt/history/default.lisp".
<INFO> [12:59:00] Restoring 1 buffer from history.

(WebKitWebProcess:2): Gtk-WARNING **: 12:59:00.987: cannot open display: :0
<WARN> [12:59:00] Warning: Web process terminated for buffer 6510 (opening ) because it crashed

(WebKitWebProcess:2): Gtk-WARNING **: 12:59:00.991: cannot open display: :0
<WARN> [12:59:00] Warning: Web process terminated for buffer 6561 (opening nyxt:new) because it crashed

(WebKitWebProcess:2): Gtk-WARNING **: 12:59:01.019: cannot open display: :0
<WARN> [12:59:01] Warning: Error in signal on renderer thread: The value
  NIL
is not of type
  CL-WEBKIT2:WEBKIT-WEB-VIEW
when binding CL-WEBKIT2::WEB-VIEW
<WARN> [12:59:01] Warning: Error in FFI method: The value
  NIL
is not of type
  CL-WEBKIT2:WEBKIT-WEB-VIEW
when binding CL-WEBKIT2::WEB-VIEW
<WARN> [12:59:01] Warning: Error in FFI method: The value
  NIL
is not of type
  CL-WEBKIT2:WEBKIT-WEB-VIEW
when binding CL-WEBKIT2::WEB-VIEW

(WebKitWebProcess:2): Gtk-WARNING **: 12:59:01.106: cannot open display: :0
<WARN> [12:59:01] Warning: Web process terminated for buffer 6628 (opening nyxt:new) because it crashed
<WARN> [12:59:01] Warning: Error in signal on renderer thread: The value
  NIL
is not of type
  CL-WEBKIT2:WEBKIT-WEB-VIEW
when binding CL-WEBKIT2::WEB-VIEW

**Comment by MaxGyver83** [comment]
This doesn't happen to me on Arch Linux.

```
(WebKitWebProcess:2): Gtk-WARNING **: 12:59:00.987: cannot open display: :0
```

Are you trying to start Nyxt on a remote machine via SSH?

Can you start firefox, xclock or any other X11 application?

**Comment by irthomasthomas** [comment]
Thanks, no I'm not doing anything weird that I know of. No ssh. Everything
else works.
