### ISSUE TITLE
duplicate suggestions in DESCRIBE SLOT

### ISSUE THREAD

**Issue by lansingthomas** [atlas-engineer/nyxt#3195]
Hi again,

**Describe the bug**
Are these duplicates on purpose? IF so, what is their purpose?

https://github.com/atlas-engineer/nyxt/assets/6666079/f473b970-f81d-4cb4-a00f-576e40a99d46

**Precise recipe to reproduce the issue**

`f1` `s`
`search web`
observe some duplicates.

Thank you
---

Nyxt version: 3.8.0
Renderer: GI-GTK
Operating system kernel: Linux 6.2.0-33-generic
Lisp implementation: SBCL 2.3.8 (Dynamic space size: 3221225472)

**Comment by hgluka** [comment]
Ah, I ran into that before and also wondered why it happens. I think it's a bug with a simple fix, I can handle it.

**Comment by lansingthomas** [comment]
Nice! Thanks Luka
