### ISSUE TITLE
`switch-buffer` UI may be misleading

### ISSUE THREAD

**Issue by aadcg** [atlas-engineer/nyxt#3201]
Illustrated below. I consider unreasonable that the number of suggestions shown doesn't match the number of opened buffers.

![2023_10_04_12:30:41-nyxt](https://github.com/atlas-engineer/nyxt/assets/45483512/47120557-d8ee-4ed7-a09e-a331ba0a9872)

Possible solutions:

1. Revert cc91712e5ed0d386e309e5e6c7a80a9249dfe788.
2. Keep `new-url-or-search-source` as a source, but show the suggestions count for `buffer-source` exclusively. This is theoretically possible but it requires fixing the handling of `hide-suggestion-count-p` in Nyxt. It doesn't properly separate between hiding the suggestions for the prompter and the sources. 

### Solution 1

![2023_10_04_13:21:44-nyxt](https://github.com/atlas-engineer/nyxt/assets/45483512/b8fa3573-c960-4df4-a118-c4377760383e)

### Solution 2
![2023_10_04_13:26:57-nyxt](https://github.com/atlas-engineer/nyxt/assets/45483512/cf7df25c-3db2-4812-8080-3ca974540b2d)

----------

Opinions are welcome, but ultimately we should listen to @lansingthomas.

@MaxGyver83 you may be interested.

**Comment by MaxGyver83** [comment]
I didn't take note that this number is the buffer count plus one. I agree that this sum of buffers plus the "create new buffer" count is not so useful.

I don't need this "Create new buffer" source in `switch-buffer`. I had already asked in the forum how to remove it: [Switch-buffer: Longer buffer list - Nyxt / Configuration Questions - Atlas](https://discourse.atlas.engineer/t/switch-buffer-longer-buffer-list/875). I use `set-url-new-buffer` when I want to open a URL in a new buffer. But I can understand that people want two commands in one, thus I wouldn't revert cc91712e. Can't we just make this configurable? Something like:

```lisp
(define-configuration buffer
  ((switch-buffer-suggest-new-buffer t)))
```

**Comment by aartaka** [comment]
> Can't we just make this configurable? Something like:
>
>```lisp
>(define-configuration buffer
>  ((switch-buffer-suggest-new-buffer t)))
>```

We had discussed configuring sources for commands elsewhere. That'll be the most reliable solution.

**Comment by lansingthomas** [comment]
Good report @aadcg,
- I don't like having two sources here | _(it seems cluttered, which distracts from the main task at hand {re-surfacing information})_
- I do like having the option to create a new buffer in the `switch-buffer` menu | _(If I look for an open buffer and then realize it has been closed, the next logical action is to create a new one)_


### Solution 3
present `set-url` or `set-url-new-buffer` as a suggestion (with some visual differentiation)

Could look like:
![switch-buffer UI for #3201 (1)](https://github.com/atlas-engineer/nyxt/assets/6666079/8d70bd03-c364-44c0-abb3-921ef7fd19a5)

**Comment by lansingthomas** [comment]
> We had discussed configuring sources for commands elsewhere. That'll be the most reliable solution.

I am interested in this. Can you point me in that direction? @aartaka

**Comment by lansingthomas** [comment]
https://github.com/atlas-engineer/nyxt/issues/3032 this one?

**Comment by aartaka** [comment]
>https://github.com/atlas-engineer/nyxt/issues/3032 this one?

No, it's #2877 and the linked discussion in #3024.

**Comment by irthomasthomas** [comment]
I also strongly prefer 1 as the default. It feels unnatural to tab through open buffers and find that one of them creates a new buffer. And, as mentioned, there are numerous ways you may create a new buffer, but this limits you to only one. switch-buffers should only switch-buffers, by default, in my view.

**Comment by aartaka** [comment]
> but this limits you to only one. 

switch-buffer is not the only option to create buffers, you still have all the other options to create buffers. 

Buffer creation comes as a bonus in switch-buffer, which gives you one more option to create buffer. This time while searching for a buffer you thought was open, but actually wasn't.

**Comment by lansingthomas** [comment]
## decision
Good discussion here. I am convinced that **Solution 1** is the best course of action at this time.

#### Reasoning:
1. one clear command for one clear purpose: `switch-buffer` &rArr; menu for switching buffers
2. reduces visual clutter created by extra bars in prompt buffer, to allow important space for buffer `suggestions` 

#### thoughts for the future discussion about potential configurability of this feature
- I see including `set-URL` here as a shortcut that _sometimes reduces keystrokes_ at the cost of _clear separation of actions_. So for some advanced workflows it could be a helpful feature.
- seems like a low priority to me, but my mind is easily changed by good arguments. (I commit to discussing it briefly with a few people on the team and reporting back here, or opening another issue if I hear any strong arguments).

Thank you all! 
Nyxt forever!

**Comment by MaxGyver83** [comment]
> This time while searching for a buffer you thought was open, but actually wasn't.

For this use case, it would be nice if the `set-url-new-buffer` key binding would also work in the `switch-buffer` prompt. Even better if the typed filter query would be used as start value for the `set-url-new-buffer` prompt. (Obviously, the new prompt buffer should _replace_ the old prompt buffer.)

**Comment by lansingthomas** [comment]
Good idea @MaxGyver83,

I too would like to access regular commands from an open prompt buffer like this. 

My understanding is that the prompt buffer commands will supersede main buffer commands, but I don't know why the prompt buffer doesn't pass these commands through. 

- currently prompt buffers will stack nicely if you create new ones without closing the first. Which effectively "replaces" the old one, then closes both when a selection is made.

**Comment by jmercouris** [comment]
sometimes it will allow you to do both commands in a row, for example, run set-url twice, and it should stack two prompt buffer prompts.
