### ISSUE TITLE
`common-settings` improvements

### ISSUE THREAD

**Issue by aadcg** [atlas-engineer/nyxt#3211]
- [ ] A newline needs to be appended on each batch written to file as to improve readability;
- [ ] `vi-insert-mode` needs to be added to the prompt buffer, for vi users. Requires sanitizing the effects when setting another keyscheme; 
- [ ] UI quirk (see screenshot below, to reproduce try to resize the window).

![2023-10-09_17:28:32](https://github.com/atlas-engineer/nyxt/assets/45483512/9380c838-bba4-4f3d-b5f4-cfcda7ca6b02)

**Comment by hgluka** [comment]
Oh, I also looked into the UI quirk, and it seems like a CSS flexbox thing.
I was able to fix it by using `height: auto; min-height: 100%` instead of `height: 100%` in the main `row` div.

**Comment by jmercouris** [comment]
Fascinating, I would have never guessed. I had an inkling it had to do with flexbox, but didn't imagine the design was so idiotic.

**Comment by hgluka** [comment]
Closing this because the `common-settings` improvements are done. For the `vi-insert-mode` discussion, I opened #3242.
