### ISSUE TITLE
Enable `vi-insert-mode` in the prompt buffer by default

### ISSUE THREAD

**Issue by hgluka** [atlas-engineer/nyxt#3242]
**Is your feature request related to a problem? Please describe.**
As a recent convert to the religion of Emacs and an avid Vim user, I sometimes get tripped up using `vi-mode` in Nyxt. The main reason being the following example:
1. I press `:` to execute a command.
2. I start typing, only to realize that I'm not in insert mode
3. Press `i`
4. Start typing again.

**Describe the solution you'd like**
I think that we should enable `vi-insert-mode` whenever a prompt buffer is opened while in `vi-normal-mode`.

**Comment by jmercouris** [comment]
I agree completely.

**Comment by fictitiousexistence** [comment]
I use vi mode everywhere else but for the prompt buffer I turn vi & emacs off. I find it works better that way. You don't have to press i to start typing a command/or entrering a url. And you dont have to press esc twice to close out the prompt buffer (once takes you to vi-normal, twice then exits.). And the up/down arrow keys work. I've had it like this for a several months now so not sure if anything has changes with the prompt buffer and vi mode
