### ISSUE TITLE
`nasdf-compilation-test-system` isn't aware of its scope

### ISSUE THREAD

**Issue by aadcg** [atlas-engineer/nyxt#3264]
Steps to reproduce (from a clean image):

- `(asdf:test-system "nyxt")` => all good

------

- `(asdf:load-system :nyxt/gi-gtk)`
- `(asdf:test-system "nyxt")` =>

```log
Unknown location:
  error: 
    ((#<PACKAGE "NYXT/RENDERER/GI-GTK">
      (NYXT/RENDERER/GI-GTK:GI-GTK-BROWSER NYXT/RENDERER/GI-GTK:GI-GTK-RENDERER))
     (#<PACKAGE "NYXT/WEB-EXTENSIONS">
      (NYXT/WEB-EXTENSIONS:HOST-PERMISSION-HOLDS-P
       NYXT/WEB-EXTENSIONS:TAB-APIS-ENABLED-P
       NYXT/WEB-EXTENSIONS:MERGE-EXTENSION-PATH NYXT/WEB-EXTENSIONS:CONTENT-SCRIPT
       NYXT/WEB-EXTENSIONS:HAS-PERMISSION-P))
     (#<PACKAGE "NYXT/RENDERER/GTK">
      (NYXT/RENDERER/GTK:GTK-REQUEST-DATA NYXT/RENDERER/GTK:COOKIES-FILE
       NYXT/RENDERER/GTK:GTK-USER-SCRIPT NYXT/RENDERER/GTK:GTK-USER-STYLE
       NYXT/RENDERER/GTK:DATA-MANAGER-CACHE-DIRECTORY NYXT/RENDERER/GTK:GTK-BUFFER
       NYXT/RENDERER/GTK:GTK-RENDERER NYXT/RENDERER/GTK:DATA-MANAGER-FILE
       NYXT/RENDERER/GTK:GTK-BROWSER NYXT/RENDERER/GTK:CONTEXT-SOURCE
       NYXT/RENDERER/GTK:DATA-MANAGER-DATA-DIRECTORY NYXT/RENDERER/GTK:GTK-SCHEME
       NYXT/RENDERER/GTK:GTK-WINDOW)))
    Found undocumented exported symbols in 3 packages.
```

-----

In short, when system `nyxt` is requested to be tested and the super-system `nxyt/gi-gtk` is loaded as well, it complains about symbols from the latter. 

Any idea @aartaka?

**Comment by aartaka** [comment]
> In short, when system nyxt is requested to be tested and the super-system nxyt/gi-gtk is loaded as well, it complains about symbols
> from the latter.
>
> Any idea @aartaka?

So the design of NASDF tests is that it tests all the subpackages (all
the package/*) for (un)documented symbols in addition to the actual
package. See list-subpackages in NASDF. So yes, nyxt/renderer/gi-gtk is
a subpackage for nyxt and is tested with it.

It is a reasonable enough logic, akin to how ASDF systems are structured
around main system and consistent with our mode/renderer/feature naming
for packages.

**Comment by aartaka** [comment]
> the output of `asdf:test-system` must be stateless.

Yes, that's convincing.

> In the mean time, the offending symbols should be documented. Would you to open a PR on that topic

I've proven myself unreliable in writing documenttion several times in the last couple of weeks 😛

**Comment by jmercouris** [comment]
> > In the mean time, the offending symbols should be documented. Would you to open a PR on that topic
> 
> I've proven myself unreliable in writing documenttion several times in the last couple of weeks 😛

I'm not sure what you mean exactly, could you please explain?

**Comment by jmercouris** [comment]
> > > I've proven myself unreliable in writing documenttion several times in the last couple of weeks 😛
> 
> > I'm not sure what you mean exactly, could you please explain?
> 
> I mean [#3217 (comment)](https://github.com/atlas-engineer/nyxt/pull/3217#issuecomment-1761459305)

I understand what you are saying. I too would be hesitant in your position. I also think it would be a good idea to move forward, and note that it was probably a comment said in frustration, rather than one to be taken at literal face value.

I think it would be a good idea for us as a team to practice patience, and forgiveness. Let bygones be bygones. I am personally trying not to hold any grudges for things that have happened, and I hope we are all together on the same team.
