### ISSUE TITLE
Failed to load URL nyxt:common-settings?section=%1Btheme-and-style

### ISSUE THREAD

**Issue by azredm** [atlas-engineer/nyxt#3376]
**Describe the bug**
Clicking the "Theme & Style" button to access the common settings section on a fresh install, after either building from source or installation via flatpak, fails to load the page and produces the following output.

**Information**
- OS name+version: Debian Stable (12.5)
- Graphics card and driver: Radeon RX 5500/5500M / Pro 5500M - amdgpu
- Desktop environment / Window manager name+version: i3 version 4.22 (2023-01-02)
- How you installed Nyxt (Guix pack, package manager, build from source): build from source/flatpak installation (problem occurs via both methods)
- Information from `show-system-information`:

> Nyxt version: 3.11.5
> Renderer: GI-GTK
> Operating system kernel: Linux 6.1.0-18-amd64
> Lisp implementation: SBCL 2.2.9.debian (Dynamic space size: 3221225472)
> Features: (:NYXT-GI-GTK :NYXT-GTK :NYXT-GI-GTK :NYXT-GTK :NYXT-3.11 :NYXT-3 :NYXT-3.11.5
>  :CLIPBOARD-CONTENT-METHOD :SWANK :SLYNK :PLUMP-UTF-32 :PARENSCRIPT :NSYMBOLS
>  :FSET-EXT-STRINGS :SBCL+SAFE-STANDARD-READTABLE :NAMED-READTABLES :GLOBAL-VARS
>  :CL-FAD :LPARALLEL :21BIT-CHARS :CUSTOM-HASH-TABLE-NATIVE :CL-PPCRE-UNICODE
>  :CL-UNICODE :CL-JSON-DOUBLE-FLOAT-IS-SUBSUMED
>  :CL-JSON-SINGLE-FLOAT-IS-SUBSUMED :CHUNGA :FLEXI-STREAMS :CL-PPCRE :WEBKIT2
>  :WEBKIT-2.42.5 :WEBKIT-2.42 :WEBKIT-2 :WEBKIT2-CORS-ALLOWLIST
>  :WEBKIT2-PASTE-PLAINTEXT :WEBKIT2-TRACKING :WEBKIT2-MUTE :WEBKIT2-EMOJI
>  :WEBKIT2-MEDIA :WEBKIT2-SANDBOXING :GTK-3-22 :GTK-3-20 :GTK-3-18 :GTK-3-16
>  :GTK-3-14 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6 :GTK-3-4 :GTK :GDK-3-22
>  :GDK-3-20 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12 :GDK-3-10 :GDK-3-8 :GDK-3-6
>  :GDK-3-4 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF :CLOSER-MOP :GLIB-2-30 :GLIB-2-32
>  :GLIB-2-34 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42 :GLIB-2-44 :GLIB-2-46
>  :GLIB-2-48 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56 :GLIB-2-58 :GLIB
>  :BORDEAUX-THREADS :LPARALLEL.WITH-CLTL2 :LPARALLEL.WITH-CAS
>  :LPARALLEL.WITH-STEALING-SCHEDULER :SPLIT-SEQUENCE
>  CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64 CFFI-FEATURES:UNIX :CFFI
>  CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP :FAST-IO-SV :FAST-IO
>  :CL-JSON-CLOS :CL-JSON :SBCL-USES-SB-ROTATE-BYTE CHIPZ-SYSTEM:GRAY-STREAMS
>  :THREAD-SUPPORT :ASDF3.3 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX
>  :NON-BASE-CHARS-EXIST-P :ASDF-UNICODE :X86-64 :GENCGC :64-BIT :ANSI-CL
>  :COMMON-LISP :ELF :IEEE-FLOATING-POINT :LINUX :LITTLE-ENDIAN
>  :PACKAGE-LOCAL-NICKNAMES :SB-CORE-COMPRESSION :SB-LDB :SB-PACKAGE-LOCKS
>  :SB-THREAD :SB-UNICODE :SBCL :UNIX)
> 
> ASDF version: 3.3.1
> ASDF registries: (NYXT-SOURCE-REGISTRY ENVIRONMENT-SOURCE-REGISTRY)
> Critical dependencies: (/home/azalea/.local/share/common-lisp/source/nyxt/_build/cl-cffi-gtk/gtk/cl-cffi-gtk.asd
>  /home/azalea/.local/share/common-lisp/source/nyxt/_build/cl-gobject-introspection/cl-gobject-introspection.asd
>  /home/azalea/.local/share/common-lisp/source/nyxt/_build/cl-webkit/webkit2/cl-webkit2.asd)

**Output when started from a shell**

> Nyxt version 3.11.5
> <INFO> [12:21:30] Source location: #P"/home/azalea/.local/share/common-lisp/source/nyxt/"
> <INFO> [12:21:30] Loading Lisp file #P"/home/azalea/.config/nyxt/auto-config.3.lisp".
> <INFO> [12:21:30] Listening to socket: #P"/run/user/1000/nyxt/nyxt.socket"
> <INFO> [12:21:30] GTK extensions directory: #P"/home/azalea/.local/share/common-lisp/source/nyxt/libraries/web-extensions/"
> <INFO> [12:21:30] GTK extensions directory: #P"/home/azalea/.local/share/common-lisp/source/nyxt/libraries/web-extensions/"
> <INFO> [12:21:31] Loading #P"/home/azalea/.local/share/nyxt/history/default.lisp".
> <INFO> [12:21:31] Restoring 1 buffer from history.
> <INFO> [12:21:31] Loading #P"/home/azalea/.local/share/nyxt/auto-rules.lisp".
> <INFO> [12:21:31] Updating hostlist #P"/home/azalea/.local/share/nyxt/hostlist-stevenblack.txt"...
> <INFO> [12:21:31] Loading #P"/home/azalea/.local/share/nyxt/hostlist-stevenblack.txt".

///// ...on clicking the "Theme & Style" button.../////

> ; in: WITH-OUTPUT-TO-STRING (PARENSCRIPT::*PSW-STREAM*)
> ;     ((50 "50%")
> ;      (NYXT::AUTO-CONFIGURE :CLASS-NAME 'NYXT:DOCUMENT-BUFFER :SLOT
> ;                            'NYXT:ZOOM-RATIO-DEFAULT :SLOT-VALUE 0.5))
> ; 
> ; caught ERROR:
> ;   illegal function call
> ; 
> ; compilation unit finished
> ;   caught 1 ERROR condition
> <WARN> [12:21:34] Warning: Error while processing the "nyxt:" URL: The value (NYXT::AUTO-CONFIGURE :CLASS-NAME (QUOTE DOCUMENT-BUFFER) :SLOT (QUOTE ZOOM-RATIO-DEFAULT) :SLOT-VALUE 0.3) is not of type (OR STRING SYMBOL CHARACTER) when binding STRING
> <INFO> [12:21:35] Failed to load URL nyxt:common-settings?section=%1Btheme-and-style in buffer 6211.

---
This is not a huge issue but I figured I would bring it up in case there is an overlooked problem within the program, my environment, or both. I am not experienced at all with any lisps- though I am learning!- so please forgive potentially obvious mistakes. Thank you!

**Comment by azredm** [comment]
(As an aside, I have been tinkering today and this still happens on SBCL 2.4.3)

**Comment by aadcg** [comment]
@azredm thanks for reporting. It is a bug.

**Comment by aadcg** [comment]
The culprit is 5d18d0a9143441e61679b85c88a2673bd6ccc70e.
