### ISSUE TITLE
This is in the wrong place but its close.

### ISSUE THREAD

**Issue by lamb-duh** [atlas-engineer/nyxt#3387]
Hi,
Data scientist here trying to move my processes in to guix/CL for all the right reasons
Usually I solve my own bugs but I have too many new tools right now and dont know where to begin. 
Context: guixSD, SBCL, installing 'unix-in-lisp
after a quickload call I get the error

Loading "unix-in-lisp"
pkg-config libfixposix --cflags
compilation unit aborted
caught 1 fatal ERROR condition

I ran 
$ guix install sbcl-iolib
seeing from the package def that it pulled in libfixposix
but quickload throws the same error

Trying to narrow down the problem on command line
$ pkg-config libfixposix --cflags
throws
Package libfixposix was not found in the pkg-config search path... and the error message goes on to give helpfull advice on adding to PKG_CONFIG_PATH

The problem is I am too new to guix (and sumultaneously to CL) to know how to proceed, where the libfixposix is currently and if this will be a useful path to  move ahead with my quickload. 
@Ambrevar  has fielded many issues with libfixposix on install thanks to his work on nyxt and he might be able to clue a noob in while I find my feet here.
Sorry if the solution is obvious, 
lamb

**Comment by aadcg** [comment]
@lamb-duh what are you trying to achieve and how is it related to Nyxt?

**Comment by lamb-duh** [comment]
I had already solved it, but didnt know guix well enough to realize guix required a restart for the sbcl-iolib to register with libfixposix. I was trying to connect to ambrevar through your project as he has solved many libfixposix issues and he knows guix well. Thanks for Nyxt it rocks
