### ISSUE TITLE
Running from source: `Component "swank/exts" not found`

### ISSUE THREAD

**Issue by evertedsphere** [atlas-engineer/nyxt#3394]
**Describe the bug**
Following the recipe in the developer manual produces the following error in `*Nyxt Guix shell compilation*` after some time at the `C-u - M-x sly RET nyxt-sbcl RET` step:

```
debugger invoked on a ASDF/FIND-COMPONENT:MISSING-COMPONENT in thread
#<THREAD tid=410169 "main thread" RUNNING {1001488093}>:
  Component "swank/exts" not found

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [RETRY                        ] Retry ASDF operation.
  1: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the
                                     configuration.
  2: [RETRY                        ] Retry EVAL of current toplevel form.
  3: [CONTINUE                     ] Ignore error and continue loading file "/gnu/store/ix0ccac5l39qikwl7habpihvci3fymjj-profile/bin/lisp-repl-core-dumper".
  4: [ABORT                        ] Abort loading file "/gnu/store/ix0ccac5l39qikwl7habpihvci3fymjj-profile/bin/lisp-repl-core-dumper".
  5:                                 Ignore runtime option --eval "(with-open-file (s \"/gnu/store/ix0ccac5l39qikwl7habpihvci3fymjj-profile/bin/lisp-repl-core-dumper\")
  (read-line s)
  (load s))".
  6:                                 Skip rest of --eval and --load options.
  7:                                 Skip to toplevel READ/EVAL/PRINT loop.
  8: [EXIT                         ] Exit SBCL (calling #'EXIT, killing the process).

((LAMBDA NIL :IN ASDF/SYSTEM:FIND-SYSTEM))
; File has been modified since compilation:
;   SYS:CONTRIB;ASDF;ASDF.LISP.NEWEST
; Using form offset instead of character position.
   error finding frame source: invalid feature expression: "#.(UIOP/UTILITY:SYMBOL-TEST-TO-FEATURE-EXPRESSION
   '#:COMPILER-ERROR-CONTEXT-%SOURCE '#:SB-C)"
   source: NIL
0] 
```

Doing `guix shell -D -f build-scripts/nyxt.scm -- sbcl` and then `(asdf:load-system :nyxt/gi-gtk)` has the same effect, so it's not an Emacs-specific issue.

**Information**
- OS name+version: NixOS unstable
- How you installed Nyxt (Guix pack, package manager, build from source): source
- Information from `show-system-information`:
  - Nyxt version (from the `nyxt-version` command or `nyxt --version` from a shell): `655588b4981e2dd9ea0c736be980e75defd61261`
  - Lisp implementation/version (if built from source): SBCL 2.4.0
  - Kernel name+version: `Linux 6.7.12 #1-NixOS SMP PREEMPT_DYNAMIC`

**Comment by aadcg** [comment]
@evertedsphere it seems that the issue is related to the fact that Guix isn't up-to-date. Can you run `guix pull` and then try again?

**Comment by evertedsphere** [comment]
@aadcg tried it a few times since then, `guix pull` followed by running `(asdf:load-system :nyxt/gi-gtk)` in the REPL produces the same error consistently.

Could it have to do with my Guix setup? I installed it just for Nyxt. I do have the `PATH` set up correctly, as far as I know:
```
$ which guix
/home/s/.config/guix/current/bin/guix
```

**Comment by aadcg** [comment]
Stale. Feel free to re-open.
