### ISSUE TITLE
minor typo in `assets/nyxt.metainfo.xml` (commit 655588b)

### ISSUE THREAD

**Issue by ed9w2in6** [atlas-engineer/nyxt#3395]
On line 56 as of commit 655588b, I think you forgot to modify the `url` markup when editing.

ref: https://github.com/atlas-engineer/nyxt/commit/655588b4981e2dd9ea0c736be980e75defd61261#diff-6c5943d35081a1bddeb2787a4554500a5de26ec4052339d5aaacab0c818a8bb9

https://github.com/atlas-engineer/nyxt/blob/655588b4981e2dd9ea0c736be980e75defd61261/assets/nyxt.metainfo.xml#L54-L60

**Comment by aadcg** [comment]
@ed9w2in6 thanks! Fixed in 85759cc16.
