### ISSUE TITLE
Gemini not always rendering as expected

### ISSUE THREAD

**Issue by Drakx** [atlas-engineer/nyxt#3396]
**Describe the bug**
Going to gemini://republic.circumlunar.space/users/korruptor/blog/index.gmi

I'm noticing that Nyxt doesn't always render the pages correctly I've included two screenshots namely the icons.

Nyxt
![Screenshot_2024-05-09_16-41-08](https://github.com/atlas-engineer/nyxt/assets/1236013/cf915eb8-2c6c-41d5-892a-0b492a3edb8b)

Lagrange
![Screenshot_2024-05-09_16-41-32](https://github.com/atlas-engineer/nyxt/assets/1236013/1d473377-cc9b-4bac-9fc8-8088f0e51c46)

**Information**
- OS name+version: Void Linux
- Graphics card and driver: Intel HD 530
- Desktop environment / Window manager name+version: Xfce4
- How you installed Nyxt (Guix pack, package manager, build from source): Package manager (xbps-install)
- Information from `show-system-information`:
Nyxt version: 3.11.0
Renderer: GI-GTK
Operating system kernel: Linux 6.6.30_1
Lisp implementation: SBCL 2.4.1.void.1 (Dynamic space size: 3221225472)
Features: (:NYXT-GI-GTK :NYXT-GTK :NYXT-GI-GTK :NYXT-GTK :NYXT-3.11 :NYXT-3 :NYXT-3.11.0 :CLIPBOARD-CONTENT-METHOD :SWANK :SLYNK :PLUMP-UTF-32 :PARENSCRIPT :NSYMBOLS :FSET-EXT-STRINGS :SBCL+SAFE-STANDARD-READTABLE :NAMED-READTABLES :GLOBAL-VARS :CL-FAD :LPARALLEL :21BIT-CHARS :CUSTOM-HASH-TABLE-NATIVE :CL-PPCRE-UNICODE :CL-UNICODE :CL-JSON-DOUBLE-FLOAT-IS-SUBSUMED :CL-JSON-SINGLE-FLOAT-IS-SUBSUMED :CHUNGA :FLEXI-STREAMS :CL-PPCRE :WEBKIT2 :WEBKIT-2.42.5 :WEBKIT-2.42 :WEBKIT-2 :WEBKIT2-CORS-ALLOWLIST :WEBKIT2-PASTE-PLAINTEXT :WEBKIT2-TRACKING :WEBKIT2-MUTE :WEBKIT2-EMOJI :WEBKIT2-MEDIA :WEBKIT2-SANDBOXING :GTK-3-22 :GTK-3-20 :GTK-3-18 :GTK-3-16 :GTK-3-14 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6 :GTK-3-4 :GTK :GDK-3-22 :GDK-3-20 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12 :GDK-3-10 :GDK-3-8 :GDK-3-6 :GDK-3-4 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF :CLOSER-MOP :GLIB-2-30 :GLIB-2-32 :GLIB-2-34 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42 :GLIB-2-44 :GLIB-2-46 :GLIB-2-48 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56 :GLIB-2-58 :GLIB :BORDEAUX-THREADS :LPARALLEL.WITH-CLTL2 :LPARALLEL.WITH-CAS :LPARALLEL.WITH-STEALING-SCHEDULER :SPLIT-SEQUENCE CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64 CFFI-FEATURES:UNIX :CFFI CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP :FAST-IO-SV :FAST-IO :CL-JSON-CLOS :CL-JSON :SBCL-USES-SB-ROTATE-BYTE CHIPZ-SYSTEM:GRAY-STREAMS :THREAD-SUPPORT :ASDF3.3 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX :NON-BASE-CHARS-EXIST-P :ASDF-UNICODE :ARENA-ALLOCATOR :X86-64 :GENCGC :64-BIT :ANSI-CL :COMMON-LISP :ELF :IEEE-FLOATING-POINT :LINUX :LITTLE-ENDIAN :PACKAGE-LOCAL-NICKNAMES :SB-CORE-COMPRESSION :SB-LDB :SB-PACKAGE-LOCKS :SB-THREAD :SB-UNICODE :SBCL :UNIX)

ASDF version: 3.3.1
ASDF registries: (NYXT-SOURCE-REGISTRY ENVIRONMENT-SOURCE-REGISTRY)
Critical dependencies: (/builddir/nyxt-3.11.0/_build/cl-cffi-gtk/gtk/cl-cffi-gtk.asd /builddir/nyxt-3.11.0/_build/cl-gobject-introspection/cl-gobject-introspection.asd /builddir/nyxt-3.11.0/_build/cl-webkit/webkit2/cl-webkit2.asd)

**Comment by aadcg** [comment]
I can't reproduce. It always renders the icons in my system. Could it be a fonts issue?

**Comment by Drakx** [comment]
Its very possible. I'll look at fonts and report back if I find anything

**Comment by Drakx** [comment]
Update, seems it was a font issue, not sure which one as I installed a fair few. I'll close.
