### ISSUE TITLE
Blank Page upon startup

### ISSUE THREAD

**Issue by ShrekisLyf** [atlas-engineer/nyxt#3397]
**Describe the bug**
I try to start the browser from konsole/clicking on the icon and sadly i am left with a blank window with the title "Nyxt - *New buffer* - nyxt:new
**Precise recipe to reproduce the issue**

**Information**
- OS name+version: Garuda Linux Bird of Prey x86_64
- Graphics card and driver: GTX 1060 6GB
- Desktop environment / Window manager name+version: Plasma 6.0.4 with KWin
- How you installed Nyxt (Guix pack, package manager, build from source): via pacman -S nyxt (tried discover and guix too)
- Information from `show-system-information`:

info from nyxt --system-information:

```
Nyxt version: 3.11.1
Renderer: GI-GTK
Operating system kernel: Linux 6.8.9-zen1-1-zen
Lisp implementation: SBCL 2.4.0 (Dynamic space size: 3221225472)
Features: (:NYXT-GI-GTK :NYXT-GTK :NYXT-GI-GTK :NYXT-GTK :NYXT-3.11 :NYXT-3 :NYXT-3.11.1
:CLIPBOARD-CONTENT-METHOD :SWANK :SLYNK :PLUMP-UTF-32 :PARENSCRIPT :NSYMBOLS
:FSET-EXT-STRINGS :SBCL+SAFE-STANDARD-READTABLE :NAMED-READTABLES :GLOBAL-VARS
:CL-FAD :LPARALLEL :21BIT-CHARS :CUSTOM-HASH-TABLE-NATIVE :CL-PPCRE-UNICODE
:CL-UNICODE :CL-JSON-DOUBLE-FLOAT-IS-SUBSUMED
:CL-JSON-SINGLE-FLOAT-IS-SUBSUMED :CHUNGA :FLEXI-STREAMS :CL-PPCRE :WEBKIT2
:WEBKIT-2.42.4 :WEBKIT-2.42 :WEBKIT-2 :WEBKIT2-CORS-ALLOWLIST
:WEBKIT2-PASTE-PLAINTEXT :WEBKIT2-TRACKING :WEBKIT2-MUTE :WEBKIT2-EMOJI
:WEBKIT2-MEDIA :WEBKIT2-SANDBOXING :GTK-3-22 :GTK-3-20 :GTK-3-18 :GTK-3-16
:GTK-3-14 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6 :GTK-3-4 :GTK :GDK-3-22
:GDK-3-20 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12 :GDK-3-10 :GDK-3-8 :GDK-3-6
:GDK-3-4 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF :CLOSER-MOP :GLIB-2-30 :GLIB-2-32
:GLIB-2-34 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42 :GLIB-2-44 :GLIB-2-46
:GLIB-2-48 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56 :GLIB-2-58 :GLIB
:BORDEAUX-THREADS :LPARALLEL.WITH-CLTL2 :LPARALLEL.WITH-CAS
:LPARALLEL.WITH-STEALING-SCHEDULER :SPLIT-SEQUENCE
CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64 CFFI-FEATURES:UNIX :CFFI
CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP :FAST-IO-SV :FAST-IO
:CL-JSON-CLOS :CL-JSON :SBCL-USES-SB-ROTATE-BYTE CHIPZ-SYSTEM:GRAY-STREAMS
:THREAD-SUPPORT :ASDF3.3 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX
:NON-BASE-CHARS-EXIST-P :ASDF-UNICODE :ARENA-ALLOCATOR :X86-64 :GENCGC :64-BIT
:ANSI-CL :COMMON-LISP :ELF :IEEE-FLOATING-POINT :LINUX :LITTLE-ENDIAN
:PACKAGE-LOCAL-NICKNAMES :SB-CORE-COMPRESSION :SB-LDB :SB-PACKAGE-LOCKS
:SB-THREAD :SB-UNICODE :SBCL :UNIX)

ASDF version: 3.3.1
ASDF registries: (NYXT-SOURCE-REGISTRY ENVIRONMENT-SOURCE-REGISTRY)
Critical dependencies: (/build/nyxt/src/_build/cl-cffi-gtk/gtk/cl-cffi-gtk.asd
/build/nyxt/src/_build/cl-gobject-introspection/cl-gobject-introspection.asd
/build/nyxt/src/_build/cl-webkit/webkit2/cl-webkit2.asd)
```

  If you can't run `show-system-information`, try `nyxt --system-information` from
  a shell.  It this still does not work, please provide the following:
  - Nyxt version (from the `nyxt-version` command or `nyxt --version` from a shell):
  - Lisp implementation/version (if built from source):
  - Kernel name+version:
  - WebKitGTK+ | QtWebEngine version:

**Output when started from a shell**

`Nyxt version 3.11.1
<INFO> [13:44:56] Source location: #P"/usr/share/nyxt/"
<INFO> [13:44:56] Listening to socket: #P"/run/user/1000/nyxt/nyxt.socket"
<INFO> [13:44:57] Loading #P"/home/fish/.local/share/nyxt/history/default.lisp".
<INFO> [13:44:57] Restoring 1 buffer from history.
AcceleratedSurfaceDMABuf was unable to construct a complete framebuffer
AcceleratedSurfaceDMABuf was unable to construct a complete framebuffer
AcceleratedSurfaceDMABuf was unable to construct a complete framebuffer
AcceleratedSurfaceDMABuf was unable to construct a complete framebuffer

** (process:2): WARNING **: 13:44:57.350: Error writing credentials to socket: Error sending message: Broken pipe
AcceleratedSurfaceDMABuf was unable to construct a complete framebuffer
AcceleratedSurfaceDMABuf was unable to construct a complete framebuffer
AcceleratedSurfaceDMABuf was unable to construct a complete framebuffer
AcceleratedSurfaceDMABuf was unable to construct a complete framebuffer
AcceleratedSurfaceDMABuf was unable to construct a complete framebuffer
AcceleratedSurfaceDMABuf was unable to construct a complete framebuffer
AcceleratedSurfaceDMABuf was unable to construct a complete framebuffer
<INFO> [13:44:57] Loading #P"/home/fish/.local/share/nyxt/auto-rules.lisp".
AcceleratedSurfaceDMABuf was unable to construct a complete framebuffer
AcceleratedSurfaceDMABuf was unable to construct a complete framebuffer
AcceleratedSurfaceDMABuf was unable to construct a complete framebuffer
AcceleratedSurfaceDMABuf was unable to construct a complete framebuffer
AcceleratedSurfaceDMABuf was unable to construct a complete framebuffer
AcceleratedSurfaceDMABuf was unable to construct a complete framebuffer
AcceleratedSurfaceDMABuf was unable to construct a complete framebuffer
AcceleratedSurfaceDMABuf was unable to construct a complete framebuffer
AcceleratedSurfaceDMABuf was unable to construct a complete framebuffer
AcceleratedSurfaceDMABuf was unable to construct a complete framebuffer
AcceleratedSurfaceDMABuf was unable to construct a complete framebuffer
AcceleratedSurfaceDMABuf was unable to construct a complete framebuffer
AcceleratedSurfaceDMABuf was unable to construct a complete framebuffer`

**Comment by yaaama** [comment]
Can confirm I have the same problem:

```
<INFO> [01:06:40] Loading #P"/home/aayush/.local/share/nyxt/auto-rules.lisp".
AcceleratedSurfaceDMABuf was unable to construct a complete framebuffer
AcceleratedSurfaceDMABuf was unable to construct a complete framebuffer
AcceleratedSurfaceDMABuf was unable to construct a complete framebuffer
AcceleratedSurfaceDMABuf was unable to construct a complete framebuffer
AcceleratedSurfaceDMABuf was unable to construct a complete framebuffer
AcceleratedSurfaceDMABuf was unable to construct a complete framebuffer
AcceleratedSurfaceDMABuf was unable to construct a complete framebuffer

(WebKitWebProcess:2): Gtk-WARNING **: 01:06:46.749: Theme parsing error: gtk.css:4:13: Not using units is deprecated.
Assuming 'px'.

(WebKitWebProcess:2): Gtk-WARNING **: 01:06:46.767: Theme parsing error: gtk.css:22798:24: not a number

(WebKitWebProcess:2): Gtk-WARNING **: 01:06:46.768: Theme parsing error: gtk.css:23580:24: not a number

(WebKitWebProcess:2): Gtk-WARNING **: 01:06:46.852: Theme parsing error: gtk.css:22798:24: not a number

(WebKitWebProcess:2): Gtk-WARNING **: 01:06:46.853: Theme parsing error: gtk.css:23580:24: not a number
AcceleratedSurfaceDMABuf was unable to construct a complete framebuffer
AcceleratedSurfaceDMABuf was unable to construct a complete framebuffer
AcceleratedSurfaceDMABuf was unable to construct a complete framebuffer
AcceleratedSurfaceDMABuf was unable to construct a complete framebuffer
AcceleratedSurfaceDMABuf was unable to construct a complete framebuffer
<INFO> [01:07:44] Deleting socket #P"/run/user/1000/nyxt/nyxt.socket".
~ ❯
```

**Comment by julian-hoch** [comment]
Same on NixOS (using nvidia, too).

**Comment by aadcg** [comment]
Could you try setting env var `WEBKIT_DISABLE_COMPOSITING_MODE` to 1?

**Comment by julian-hoch** [comment]
Yes, that helped! Now it starts for me.

**Comment by aadcg** [comment]
Great! 

Closing.

**Comment by bloominstrong** [comment]
FYI, WebKitGTK 2.44.3 seems to have fixed this for me.
