### ISSUE TITLE
Links to nx-router and nx-tailor in EXTENSIONS.org are broken.

### ISSUE THREAD

**Issue by Anomalocaridid** [atlas-engineer/nyxt#3400]
**Describe the bug**
I apologize if this is the wrong place to report this.

The links to nx-router and nx-tailor in EXTENSIONS.org lead to a GitHub error 404 page. I could not find it hosted elsewhere, like where they used to be on sourcehut.

**Precise recipe to reproduce the issue**
Click the links to nx-router and nx-tailor.

For website-specific issues:
Can you reproduce this issue with Epiphany / GNOME Web (https://wiki.gnome.org/Apps/Web)?
N/A

**Information**
- OS name+version: N/A
- Graphics card and driver: N/A
- Desktop environment / Window manager name+version: N/A
- How you installed Nyxt (Guix pack, package manager, build from source): N/A
- Information from `show-system-information`: N/A

  If you can't run `show-system-information`, try `nyxt --system-information` from
  a shell.  It this still does not work, please provide the following:
  - Nyxt version (from the `nyxt-version` command or `nyxt --version` from a shell):
  - Lisp implementation/version (if built from source):
  - Kernel name+version:
  - WebKitGTK+ | QtWebEngine version:

**Output when started from a shell**
N/A

**Comment by aadcg** [comment]
@migalmoreno did you move them somewhere else? Thanks.

**Comment by aadcg** [comment]
Fixed via 5b2fac65f.

**Comment by Anomalocaridid** [comment]
Thank you!
