### ISSUE TITLE
Unable to navigate to gmail.com

### ISSUE THREAD

**Issue by Drakx** [atlas-engineer/nyxt#3402]
**Describe the bug**
When trying to navigate to either Gmail the following happens

![Screenshot_2024-05-22_00-45-09](https://github.com/atlas-engineer/nyxt/assets/1236013/71e9d5b2-6e2e-4dc7-bbd5-fc9e1702ffe3)

**Precise recipe to reproduce the issue**
Either press CTRL+l or ALT+l and enter gmail.com press enter produces the above screenshot

For website-specific issues:
Can you reproduce this issue with Epiphany / GNOME Web (https://wiki.gnome.org/Apps/Web)?

No

**Information**
- OS name+version:
Void Linux

- Graphics card and driver:
Intel

- Desktop environment / Window manager name+version:
XFCE4

- How you installed Nyxt (Guix pack, package manager, build from source):
Package manager

- Information from `show-system-information`:
Nyxt version: 3.11.0
Renderer: GI-GTK
Operating system kernel: Linux 6.6.31_1
Lisp implementation: SBCL 2.4.1.void.1 (Dynamic space size: 3221225472)
Features: (:NYXT-GI-GTK :NYXT-GTK :NYXT-GI-GTK :NYXT-GTK :NYXT-3.11 :NYXT-3 :NYXT-3.11.0 :CLIPBOARD-CONTENT-METHOD :SWANK :SLYNK :PLUMP-UTF-32 :PARENSCRIPT :NSYMBOLS :FSET-EXT-STRINGS :SBCL+SAFE-STANDARD-READTABLE :NAMED-READTABLES :GLOBAL-VARS :CL-FAD :LPARALLEL :21BIT-CHARS :CUSTOM-HASH-TABLE-NATIVE :CL-PPCRE-UNICODE :CL-UNICODE :CL-JSON-DOUBLE-FLOAT-IS-SUBSUMED :CL-JSON-SINGLE-FLOAT-IS-SUBSUMED :CHUNGA :FLEXI-STREAMS :CL-PPCRE :WEBKIT2 :WEBKIT-2.42.5 :WEBKIT-2.42 :WEBKIT-2 :WEBKIT2-CORS-ALLOWLIST :WEBKIT2-PASTE-PLAINTEXT :WEBKIT2-TRACKING :WEBKIT2-MUTE :WEBKIT2-EMOJI :WEBKIT2-MEDIA :WEBKIT2-SANDBOXING :GTK-3-22 :GTK-3-20 :GTK-3-18 :GTK-3-16 :GTK-3-14 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6 :GTK-3-4 :GTK :GDK-3-22 :GDK-3-20 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12 :GDK-3-10 :GDK-3-8 :GDK-3-6 :GDK-3-4 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF :CLOSER-MOP :GLIB-2-30 :GLIB-2-32 :GLIB-2-34 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42 :GLIB-2-44 :GLIB-2-46 :GLIB-2-48 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56 :GLIB-2-58 :GLIB :BORDEAUX-THREADS :LPARALLEL.WITH-CLTL2 :LPARALLEL.WITH-CAS :LPARALLEL.WITH-STEALING-SCHEDULER :SPLIT-SEQUENCE CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64 CFFI-FEATURES:UNIX :CFFI CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP :FAST-IO-SV :FAST-IO :CL-JSON-CLOS :CL-JSON :SBCL-USES-SB-ROTATE-BYTE CHIPZ-SYSTEM:GRAY-STREAMS :THREAD-SUPPORT :ASDF3.3 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX :NON-BASE-CHARS-EXIST-P :ASDF-UNICODE :ARENA-ALLOCATOR :X86-64 :GENCGC :64-BIT :ANSI-CL :COMMON-LISP :ELF :IEEE-FLOATING-POINT :LINUX :LITTLE-ENDIAN :PACKAGE-LOCAL-NICKNAMES :SB-CORE-COMPRESSION :SB-LDB :SB-PACKAGE-LOCKS :SB-THREAD :SB-UNICODE :SBCL :UNIX)

ASDF version: 3.3.1
ASDF registries: (NYXT-SOURCE-REGISTRY ENVIRONMENT-SOURCE-REGISTRY)
Critical dependencies: (/builddir/nyxt-3.11.0/_build/cl-cffi-gtk/gtk/cl-cffi-gtk.asd /builddir/nyxt-3.11.0/_build/cl-gobject-introspection/cl-gobject-introspection.asd /builddir/nyxt-3.11.0/_build/cl-webkit/webkit2/cl-webkit2.asd)

**Comment by aadcg** [comment]
It should work once you disable `reduce-tracking-mode`.

**Comment by shamazmazum** [comment]
@aadcg Oh, I also suffered from this issue all this time :) `C-r` always worked as a workaround though

**Comment by shamazmazum** [comment]
@aadcg The function `strip-tracking-parameters` is responsible for not opening Gmail.

I've added a short debug message after processing `request-resource-hook` in `renderer/gtk.lisp`:

```lisp
diff --git a/source/renderer/gtk.lisp b/source/renderer/gtk.lisp
index b8f4bfb98..2105f1bba 100644
--- a/source/renderer/gtk.lisp
+++ b/source/renderer/gtk.lisp
@@ -1083,6 +1083,7 @@ See `finalize-buffer'."
            (bound-function (when request-data
                              (the (or symbol keymaps:keymap null)
                                   (keymaps:lookup-key (keys request-data) keymap)))))
+      (log:info "REQUEST ~a" (url request-data))
       (cond
        ((not (typep request-data 'request-data))
         (log:debug "Don't forward to ~s's renderer (non request data)."
```

This is a correct request (without `reduce-tracking-mode`):

~~~~
https://accounts.google.com/ServiceLogin?service=mail&passive=1209600&osid=1&continue=https://mail.google.com/mail/u/0/&followup=https://mail.google.com/mail/u/0/&emr=1
~~~~

and after setting a new request in `strip-tracking-parameters`:

~~~~
https://accounts.google.com/ServiceLogin?service=mail&passive=1209600&osid=1&continue=https%3A%2F%2Fmail.google.com%2Fmail%2Fu%2F0%2F&followup=https%3A%2F%2Fmail.google.com%2Fmail%2Fu%2F0%2F&emr=1
~~~~

It seems that symbols like `:` and `/` must not be URL-encoded.

**Comment by shamazmazum** [comment]
@aadcg It's because `strip-tracking-parameters` damages URL:

```lisp
NYXT-USER> (defparameter *request* (quri:uri "http://google.com/query?continue=http://google.ru"))
*REQUEST*
NYXT-USER> *request*
#<QURI.URI.HTTP:URI-HTTP http://google.com/query?continue=http://google.ru>
NYXT-USER> (setf (quri:uri-query-params *request*) (quri:uri-query-params *request*))
"continue=http%3A%2F%2Fgoogle.ru"
NYXT-USER> *request*
#<QURI.URI.HTTP:URI-HTTP http://google.com/query?continue=http%3A%2F%2Fgoogle.ru>
NYXT-USER> 
```

Gmail has a lot of parameters which contain symbols `:` and `/` which must remain not URL-encoded, as it seems.

**Comment by aadcg** [comment]
Thanks for investigating @shamazmazum!
