### ISSUE TITLE
Function imports in cl-gobject-introspection & fset are incompatible with SBCL 2.4.5

### ISSUE THREAD

**Issue by durrendal** [atlas-engineer/nyxt#3408]
While updating the nyxt package for Alpine I ran into a couple of small issues. It looks like two of the libs used by nyxt are importing functions from sb-ext that have been moved to sb-int. If it's meaningful we're building nyxt 3.11.7 against SBCL 2.4.5.

Specifically this seems to be affecting:
- cl-gobject-introspection
- fset

The patches we're using to fix those build errors can be found here:
https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/67055/diffs

cl-gobject-introspection has actually made the same change upstream a couple of weeks ago, but it doesn't look like they've release a new version with that fix from what I can tell?
https://github.com/andy128k/cl-gobject-introspection/issues/100

fset hasn't made any changes at all.

**Comment by bubbleguuum** [comment]
Confirming same issue updating openSUSE Tumbleweed package with SBCL 2.4.5. 
Will use the patches in the meantime, thanks !

**Comment by aadcg** [comment]
Both issues are now solved. `fset` released 1.4.0 which ships a fix.

Thanks.
