### ISSUE TITLE
Unhandled floating point interrupt when starting Nyxt on the most recent SBCL (2.4.5)

### ISSUE THREAD

**Issue by shamazmazum** [atlas-engineer/nyxt#3409]
Hi! Can anybody spend some time to confirm the following?

I have this configuration:

* FreeBSD 14.0
* Nyxt 3.11.7 (**It's important to build `nyxt/gtk`, not `nyxt/gi-gtk`**)
* SBCL 2.4.5 (**it is important to have this version!**)
* GTK 3.24.41
* WebKit 2.42.4

I have fixed #3408 locally and built Nyxt which refuses to start (it just shows an empty window) with the following output to the console:

~~~~
* (nyxt:start)
Nyxt version 3.11.7-10-gdfdfcc9c8
<INFO> [08:30:54] Source location: #P"/home/vasily/.quicklisp/local-projects/nyxt/"
<INFO> [08:30:54] Loading Lisp file #P"/home/vasily/.config/nyxt/config.lisp".
<WARN> [08:30:54] Not found slot OVERRIDE-MAP in class BUFFER, generating the wrapper method for configuration.
<INFO> [08:30:54] Listening to socket: #P"/var/run/xdg/vasily/nyxt/nyxt.socket"
amdgpu: os_same_file_description couldn't determine if two DRM fds reference the same file description.
If they do, bad things may happen!
<INFO> [08:30:54] GTK extensions directory: #P"/home/vasily/.quicklisp/local-projects/nyxt/libraries/web-extensions/"
<INFO> [08:30:54] GTK extensions directory: #P"/home/vasily/.quicklisp/local-projects/nyxt/libraries/web-extensions/"
Could not determine the accessibility bus address
<INFO> [08:30:55] Loading #P"/home/vasily/.local/share/nyxt/history/default.lisp".
amdgpu: os_same_file_description couldn't determine if two DRM fds reference the same file description.
If they do, bad things may happen!
NIL
*
debugger invoked on a FLOATING-POINT-INVALID-OPERATION in thread
#<THREAD tid=105464 "cl-cffi-gtk main thread" RUNNING {103F137E03}>:
  arithmetic error FLOATING-POINT-INVALID-OPERATION signalled

The current thread is not at the foreground,
SB-THREAD:RELEASE-FOREGROUND has to be called in #<SB-THREAD:THREAD tid=103446 "main thread" RUNNING {1000448143}>
for this thread to enter the debugger.
amdgpu: os_same_file_description couldn't determine if two DRM fds reference the same file description.
If they do, bad things may happen!
~~~~

You can ignore `os_same_file_description` warnings, they are harmless and FreeBSD-specific. The most important thing is the floating point exception which was never happened before. I suppose the cause of this is an upgrade of SBCL from 2.4.4 to 2.4.5.

The issue is easily fixed, but I am not sure if it's right to send a patch if the issue affects just me. Please check if someone else has the same issue.

**Comment by aadcg** [comment]
@shamazmazum it is probably not reproducible on Linux otherwise #3408 would have ran on it too.

I may look at this later. For the time being the official installation methods are using slightly older SBCL versions.

**Comment by shamazmazum** [comment]
@aadcg Thanks. This problem appears after update to SBCL 2.4.5.

It's easly fixed by wrapping GTK initialization in `sb-int:with-float-traps-masked`, should you encounter this problem later.

**Comment by aadcg** [comment]
@shamazmazum it seems I can't reproduce.

Thanks for reporting.
