### ISSUE TITLE
`render-menu` UI bug

### ISSUE THREAD

**Issue by aadcg** [atlas-engineer/nyxt#3416]
![2024_06_19_11:25:16-nyxt](https://github.com/atlas-engineer/nyxt/assets/45483512/066ec550-01b0-45e8-930c-912cf01aa33c)

![2024_06_19_11:26:40-nyxt](https://github.com/atlas-engineer/nyxt/assets/45483512/2fe162b7-06b3-4cad-b412-097207ebfd97)

As shown above, scrolling the content shouldn't affect the layout of the mode menu. The menu was introduced in 66837fa240f261d46c18ea58230485c5df3fb5d9.

**Comment by jmercouris** [comment]
PR submitted: https://github.com/atlas-engineer/nyxt/pull/3443
