### ISSUE TITLE
Some help needed for finishing the FreeBSD Port

### ISSUE THREAD

**Issue by t-zuehlsdorff** [atlas-engineer/nyxt#3432]
Aloha,

i love the concept of your Browser, but its support for FreeBSD was requested since 2021. So I took some time to work on the porting. While it seems the documentation is out of sync with the code, I was able to get so far, that it is starting :) Here a screenshot from my tiling manager (yeah, i have no Window Manager) :
![image](https://github.com/user-attachments/assets/3a7a61ed-95a5-4bd0-9c31-1e69f6924b59)

There are two bugs i can see immediately and i need some pointer to tackle them:

# Warning about webkit_uri_scheme_response_new all the time

This is a log from the start
```
WARNING:
   Type initializer for class 'WebKitURISchemeResponse' (GType 'WEBKIT-URI-SCHEME-RESPONSE') is invalid: foreign symbol 'webkit_uri_scheme_response_get_type'
Nyxt version 3.11.7
<INFO> [09:03:27] Source location: #P"/usr/local/share/nyxt/"
<INFO> [09:03:27] Listening to socket: #P"/usr/ports/nyxt/nyxt.socket"

(nyxt:74996): Gtk-WARNING **: 09:03:27.732: Theme parsing error: gtk.css:3:32: The style property GtkRange:slider-width is deprecated and shouldn't be used anymore. It will be removed in a future version
<INFO> [09:03:28] Loading #P"/home/thorny/.local/share/nyxt/history/default.lisp".
<INFO> [09:03:28] Restoring 2 buffers from history.
<WARN> [09:03:28] Warning: Error while routing "nyxt-resource" resource: The alien function "webkit_uri_scheme_response_new" is undefined.
<WARN> [09:03:28] Warning: Error while routing "nyxt-resource" resource: The alien function "webkit_uri_scheme_response_new" is undefined.
```

The "webkit_uri_scheme_response_new" errors repeat all the time. How can i get rid of them?

# 2 No Copy & Paste

I can't copy from or copy to Nyxt. But i don't get any warming i can see, so i have no indication about its possible cause.

Can you help me here?

Best,
Torsten

**Comment by aadcg** [comment]
Hi @t-zuehlsdorff. Thanks for your effort.

> The "webkit_uri_scheme_response_new" errors repeat all the time. How can i get rid of them?

I am almost sure you're using a very old WebKitGTK version, where the routine isn't implemented yet.

**Comment by t-zuehlsdorff** [comment]
Aloha @aadcg,

I read #3257 and yes, it is still the same issue. The WebKitGTK version is still too old. -.- Do you know which is the next version introducing this routine? I will talk to the Maintainer Team and see, if we can update it. Since it wasn't updated for so long, i can only suspect, that there is a long tail of dependencies -.-

Regarding the copy & paste issue i have a clue and will check it. :)

Best,
Torsten

**Comment by aadcg** [comment]
> I read #3257 and yes, it is still the same issue. The WebKitGTK version is still too old. -.- Do you know which is the next version introducing this routine? I will talk to the Maintainer Team and see, if we can update it. Since it wasn't updated for so long, i can only suspect, that there is a long tail of dependencies -.-

Please note that the answer can be found in that thread, see https://github.com/atlas-engineer/nyxt/issues/3257#issuecomment-1817580399.  

Regarding the clipboard, it makes little sense to solve a small issue when a bigger one hasn't been solved yet.

If you have updates or help is required, please re-open #3257. Closing as a duplicate.
