### ISSUE TITLE
Bitwarden Extension using rbw CLI

### ISSUE THREAD

**Issue by AblatedSprocket** [atlas-engineer/nyxt#3434]
**Is your feature request related to a problem? Please describe.**
Nyxt has the nx-bitwarden extension, but the official Bitwarden CLI tends to be really slow because it bootstraps a bunch of JavaScript with every command. There is rbw, which is unofficial but much faster.

**Describe the solution you'd like**
I wrote an extension hosted here: https://codeberg.org/ablatedsprocket/nx-rbw
My common lisp isn't great and there are a few nice-to-have features I couldn't get implemented. It works under the constraints outlined in the README, though.

**Describe alternatives you've considered**
This could probably be integrated into Nyxt, but since it's an unofficial client, keeping it an extension probably makes the most sense.

**Comment by aadcg** [comment]
@AblatedSprocket amazing, thanks for sharing!



> This could probably be integrated into Nyxt, but since it's an unofficial client, keeping it an extension probably makes the most sense.

I didn't look at the code yet, but note that we officially support `pass`, `security` and `keepassxc-cli`. In that sense, perhaps it wouldn't hurt to integrate your work into Nyxt. What do you think?

**Comment by AblatedSprocket** [comment]
If the consensus is that this code would be a good fit for incorporating into Nyxt, then I'm happy to oblige. I would like to make unlocking the database more flexible before that happens, though. We can discuss more if you're still interested after looking over the code.

**Comment by aadcg** [comment]
> Something about integrating an interface for an unofficial client feels odd to me

I took a look at https://github.com/atlas-engineer/nyxt/issues/2355. It's hard to judge or to give an opinion since I have never used Bitwarden. You do mention that `rbw` is superior to `bw`. I'm leaning towards integrating your work but, ultimately, it's your call.

Again, thank you for working on it!

**Comment by AblatedSprocket** [comment]
I think I'd like to keep it as an extension for now as I'm still making improvements. I'll make a PR if I get it to a good state and get around to setting up an environment to build Nyxt.

**Comment by aadcg** [comment]
> I think I'd like to keep it as an extension for now as I'm still making improvements. I'll make a PR if I get it to a good state and get around to setting up an environment to build Nyxt.

Sounds good. Let me know if you need help setting up the development environment (see https://github.com/atlas-engineer/nyxt/blob/master/documents/README.org#development-environment-guide).

Closing this issue since there's nothing else to do. See 709a6392d.
