### ISSUE TITLE
Nyxt crashing as soon as i start it.

### ISSUE THREAD

**Issue by mukul1729** [atlas-engineer/nyxt#3442]
**Describe the bug**
Sometimes it works and sometimes it crash as soon as i start 

**Precise recipe to reproduce the issue**
Running it in terminal or app launcher

**Information**
- OS name+version: Arch linux
- Graphics card and driver: amd
- Desktop environment / Window manager name+version: River , Wayland
- Installation method (Flatpak, Guix, package manager, build from source): pacman
- Output of `nyxt --system-information`: 
Nyxt version: 3.11.7
Renderer: GI-GTK
Operating system kernel: Linux 6.10.1-arch1-1
Lisp implementation: SBCL 2.4.5 (Dynamic space size: 3221225472)
Features: (:NYXT-GI-GTK :NYXT-GTK :NYXT-GI-GTK :NYXT-GTK :NYXT-3.11 :NYXT-3 :NYXT-3.11.7
 :CLIPBOARD-CONTENT-METHOD :SWANK :SLYNK :PLUMP-UTF-32 :PARENSCRIPT :NSYMBOLS
 :FSET-EXT-STRINGS :SBCL+SAFE-STANDARD-READTABLE :NAMED-READTABLES :GLOBAL-VARS
 :CL-FAD :LPARALLEL :21BIT-CHARS :CUSTOM-HASH-TABLE-NATIVE :CL-PPCRE-UNICODE
 :CL-UNICODE :CL-JSON-DOUBLE-FLOAT-IS-SUBSUMED
 :CL-JSON-SINGLE-FLOAT-IS-SUBSUMED :CHUNGA :FLEXI-STREAMS :CL-PPCRE :WEBKIT2
 :WEBKIT-2.44.2 :WEBKIT-2.44 :WEBKIT-2 :WEBKIT2-CORS-ALLOWLIST
 :WEBKIT2-PASTE-PLAINTEXT :WEBKIT2-TRACKING :WEBKIT2-MUTE :WEBKIT2-EMOJI
 :WEBKIT2-MEDIA :WEBKIT2-SANDBOXING :GTK-3-22 :GTK-3-20 :GTK-3-18 :GTK-3-16
 :GTK-3-14 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6 :GTK-3-4 :GTK :GDK-3-22
 :GDK-3-20 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12 :GDK-3-10 :GDK-3-8 :GDK-3-6
 :GDK-3-4 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF :CLOSER-MOP :GLIB-2-30 :GLIB-2-32
 :GLIB-2-34 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42 :GLIB-2-44 :GLIB-2-46
 :GLIB-2-48 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56 :GLIB-2-58 :GLIB
 :BORDEAUX-THREADS :LPARALLEL.WITH-CLTL2 :LPARALLEL.WITH-CAS
 :LPARALLEL.WITH-STEALING-SCHEDULER :SPLIT-SEQUENCE
 CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64 CFFI-FEATURES:UNIX :CFFI
 CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP :FAST-IO-SV :FAST-IO
 :CL-JSON-CLOS :CL-JSON :SBCL-USES-SB-ROTATE-BYTE CHIPZ-SYSTEM:GRAY-STREAMS
 :THREAD-SUPPORT :ASDF3.3 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX
 :NON-BASE-CHARS-EXIST-P :ASDF-UNICODE :ARENA-ALLOCATOR :X86-64 :GENCGC :64-BIT
 :ANSI-CL :COMMON-LISP :ELF :IEEE-FLOATING-POINT :LINUX :LITTLE-ENDIAN
 :PACKAGE-LOCAL-NICKNAMES :SB-CORE-COMPRESSION :SB-LDB :SB-PACKAGE-LOCKS
 :SB-THREAD :SB-UNICODE :SBCL :UNIX)

ASDF version: 3.3.1
ASDF registries: (NYXT-SOURCE-REGISTRY ENVIRONMENT-SOURCE-REGISTRY)
Critical dependencies: (/build/nyxt/src/_build/cl-cffi-gtk/gtk/cl-cffi-gtk.asd
 /build/nyxt/src/_build/cl-gobject-introspection/cl-gobject-introspection.asd
 /build/nyxt/src/_build/cl-webkit/webkit2/cl-webkit2.asd)

**Output when started from a shell**
Nyxt version 3.11.7
<INFO> [20:44:43] Source location: #P"/usr/share/nyxt/"
<INFO> [20:44:44] Listening to socket: #P"/run/user/1000/nyxt/nyxt.socket"

(nyxt:5922): libenchant-WARNING **: 20:44:44.097: broker.vala:159: Error loading plugin: libaspell.so.15: cannot open shared object file: No such file or directory

(nyxt:5922): libenchant-WARNING **: 20:44:44.098: broker.vala:159: Error loading plugin: libhspell.so.0: cannot open shared object file: No such file or directory

(nyxt:5922): libenchant-WARNING **: 20:44:44.098: broker.vala:159: Error loading plugin: libvoikko.so.1: cannot open shared object file: No such file or directory

(nyxt:5922): libenchant-WARNING **: 20:44:44.098: broker.vala:159: Error loading plugin: libnuspell.so.5: cannot open shared object file: No such file or directory

(WebKitWebProcess:2): Gdk-WARNING **: 20:44:44.378: Failed to read portal settings: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Settings” on object at path /org/freedesktop/portal/desktop

(WebKitWebProcess:2): Gdk-WARNING **: 20:44:44.384: Failed to read portal settings: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Settings” on object at path /org/freedesktop/portal/desktop
<INFO> [20:44:45] Loading #P"/home/mukul/.local/share/nyxt/auto-rules.lisp".
<INFO> [20:44:45] Loading #P"/home/mukul/.local/share/nyxt/history/default.lisp".
<INFO> [20:44:45] Restoring 2 buffers from history.

(nyxt:5922): Gdk-CRITICAL **: 20:44:45.563: gdk_window_create_gl_context: assertion 'GDK_IS_WINDOW (window)' failed
CORRUPTION WARNING in SBCL pid 5922 tid 5941:
Memory fault at 0x8 (pc=0x7b89ca5f8150, fp=0x7b89bfdfde20, sp=0x7b89bfdfdca0) tid 5941
The integrity of this image is possibly compromised.
Continuing with fingers crossed.
<WARN> [20:44:45] Warning: Error on GI-GTK thread: Unhandled memory fault at #x8.
(WebKitWebProcess:2): Gdk-WARNING **: 20:44:45.668: Settings portal not found: Could

**Comment by aadcg** [comment]
Seems to be a duplicate, see https://github.com/atlas-engineer/nyxt/issues/3397#issuecomment-2168705666.
