### ISSUE TITLE
vimperator-mode

### ISSUE THREAD

**Issue by vindarel** [atlas-engineer/nyxt#345]
I'd really love a `M-x vimperator-mode` and find my beloved keybindings back :)

Many, but not all, required commands already exist. To begin with, we  have to define a new keyscheme. Then, implement missing commands.

Exciting :)

http://vimperator.org/vimperator.html

**Comment by Ambrevar** [comment]
Can't we simply complete vi-mode?

**Comment by vindarel** [comment]
The keybindings are already different (o, O, yu, [ and ], …). We could change them, and break the existing user experience. Let's think about it.

**Comment by Ambrevar** [comment]
There are as many VI-bindings as they are VI-style browsers/extensions,
so I don't think we can cater to the habits of everyone out there.

That said, our VI bindings still have room for improvements!

Maybe add options?  Like `vimperator-style-O`, etc.

**Comment by jmercouris** [comment]
I agree, this sounds like a user configuration issue

**Comment by jmercouris** [comment]
I'm closing this, we will not be adding any more default keybinding schemes to Nyxt, it is too difficult to track all of them.

**Comment by Ambrevar** [comment]
If anyone would like to maintain an extension, please do and get in
touch, we can provide help! :)
