### ISSUE TITLE
Idle inhibition when watching videos

### ISSUE THREAD

**Issue by shamazmazum** [atlas-engineer/nyxt#3462]
**Is your feature request related to a problem? Please describe.**
When I watch youtube, my screensaver is periodically enabled, which is annoying.

**Describe the solution you'd like**
Inhibit the screensaver while playing a video from youtube (not only youtube? in fullscreen?)

**Describe alternatives you've considered**
Here are my suggestions (personally, I don't know where to start with them):

* We have WakeLock feature in WebKit, which inhibits the screensaver. Unfortunately, it has what they call "transient activation", which means it must be activated by the user explicitly, e.g. by pressing a button.
* Can lisp be called from a user script? Or is it possible only from internal pages? I suggest, things can be easier from the lisp side.

**Comment by aadcg** [comment]
@shamazmazum that sure is annoying, but I'm not sure it's Nyxt's responsibility to handle it. 

If you do find a solution, please share!

**Comment by shamazmazum** [comment]
@aadcg I've done some research and it seems that the problem is with WebKit. It seems that youtube acquires wakelock when you press fullscreen button, but WebKit doesn't handle it properly. More specifically, it tries to send something via D-Bus, but for my system the correct way is to use Wayland idle inhibit protocol (see `Source/WebCore/PAL/pal/system/glib/SleepDisablerGLib.cpp` in WebKit sources if you are interested).

All in all, idle inhibition *can* work for some users already, but not for me :) And it's surely not Nyxt's responsibility to handle this issue :(

BTW, firefox works fine here :)

You can test if you are lucky using this HTML page, I think:
```html
<html>
  <head>
    <title>Fufufufu</title>
    <script>
      function enableWakeLock() {
          button = document.getElementById('lockbutton')
          result = navigator.wakeLock.request()
          result.then(function (value) {button.innerHTML = 'success'},
                      function (error) {button.innerHTML = 'error'})
      }
    </script>
  </head>
  <body>
    <button type="button" id="lockbutton" onclick="enableWakeLock()">Inhibit screensaver</button>
  </body>
</html>
```

**Comment by aadcg** [comment]
@shamazmazum Thanks for looking into it.

I tested your recipe and it's working for me (I am not using Wayland).
