### ISSUE TITLE
slot configuration section of document  page outdated

### ISSUE THREAD

**Issue by aimixsaka** [atlas-engineer/nyxt#3487]
**Describe the bug**
slot configuration section[^1]  of document page seems outdated, as there is no 'Configure' button now
on slot description page.

[^1]: https://nyxt.atlas.engineer/documentation#slot-configuration

**Comment by aadcg** [comment]
Thanks for reporting @aimixsaka.

The manual should have been updated after 64e0f738de55d101a0341392191a0ab8867498ef.

**Comment by aadcg** [comment]
Closed via 5ee82942f.
