### ISSUE TITLE
Add a command to close inspector in respect of `open-inspector`

### ISSUE THREAD

**Issue by IceAsteroid** [atlas-engineer/nyxt#3520]
Hi, good day, everyone.

**Is your feature request related to a problem? Please describe.**
I found no corresponding command to close the inspector when it's launched with the command `open-inspector`.

**Describe the solution you'd like**
It may be possible through custom configuration by defining a command for this(I'm currently not familiar with lisp). But why not make one by default, it would be very handy.

It'd be better, if the close inspector command is bound with the same keybinding as the `open-inspector` command

**Describe alternatives you've considered**
There may have a command for that in case that I just can't find one, if so, please tell me, thanks!

**Comment by aadcg** [comment]
It can be done for sure, see `webkit:webkit-web-inspector-close`.

**Comment by IceAsteroid** [comment]
Okay, thank you for the help!

**Comment by aadcg** [comment]
https://www.catb.org/esr/faqs/smart-questions.html

**Comment by IceAsteroid** [comment]
So, what did I actually do wrong? I don't get it.

**Comment by IceAsteroid** [comment]
~So, what did I actually do wrong? I don't get it. Tell me if anything I did is wrong.~

I've read the article. It may not be something to ask for here, I'll search it on my own.
