### ISSUE TITLE
Link to Demeter on nyxt.atlas.engineer leads to a 404

### ISSUE THREAD

**Issue by jpluscplusm** [atlas-engineer/nyxt#3524]
**Describe the bug**

The article https://nyxt.atlas.engineer/article/sustainable-open-source.org links to Demeter via the URL https://nyxt.atlas.engineer/application/demeter.org, which is a 404.

The link should go to https://nyxt.atlas.engineer/extension/demeter.org.

**Precise recipe to reproduce the issue**

Visit https://nyxt.atlas.engineer/article/sustainable-open-source.org.
Scroll to the end.
Click the link "Check out Demeter!".
Observe "Sorry, this page is not available".

**Information**
**Output when started from a shell**

n/a

**Comment by aadcg** [comment]
Thanks for reporting @jpluscplusm. It should be fixed now.
