### ISSUE TITLE
update from flatpak

### ISSUE THREAD

**Issue by chizhang** [atlas-engineer/nyxt#3527]
I got the following message when do the update on ubuntu 22.04 using the flatpak. 

> Looking for updates…
> Info: org.gnome.Platform//45 is end-of-life, with reason:
>    The GNOME 45 runtime is no longer supported as of September 18, 2024. Please ask your application developer to migrate to a supported platform.
> Applications using this runtime:
>    engineer.atlas.Nyxt
> Nothing to do.

**Comment by aadcg** [comment]
Thanks for reporting. It should be fixed soon, once it is [built](https://buildbot.flathub.org/#/builders/6/builds/161203).
