### ISSUE TITLE
Unable to view Quick Start without mouse

### ISSUE THREAD

**Issue by abitrolly** [atlas-engineer/nyxt#3529]
**Please describe the UI issue:**

When `nyxt` launches for the first time, the only way to read the Quick Start is using the mouse.

**Describe the solution you'd like**

Make it obvious how to select Quick Start and read the guide without the mouse.

One solution is to highlight first unique letters and provide corresponding shortcuts, like Alt+Q to navigate to such items.

**Comment by aadcg** [comment]
Given that it is a quick start, it seems reasonable that the mouse needs to be used since it's a universal input interface.

**Comment by abitrolly** [comment]
@aadcg given the Nyxt description from the front page, I would say that your statement is surprising.

> **Nyxt [nýkst]** is a keyboard-driven web browser designed for hackers.

**Comment by aadcg** [comment]
Aren't we discussing a chicken-egg problem? If you're using a new piece of software, you can't know the keyboard shortcuts beforehand. It's only when you complete the tutorial that you may start to use them.

**Comment by abitrolly** [comment]
I proposed a mouseless alternative of onboarding users to a mouseless browser.

**Comment by aadcg** [comment]
Thanks for the suggestion but me and @jmercouris aren't convinced about it.

**Comment by abitrolly** [comment]
@aadcg can you recommend any keyboard-driven `nyxt` alternatives? I know there is https://github.com/philc/vimium but it is an extension to existing browsers that seems non-trivial to install without mouse.

**Comment by aadcg** [comment]
Анатолий, пора стать человеком. Всего хорошего.
