### ISSUE TITLE
Blocker mode uses non-free hostlist by default

### ISSUE THREAD

**Issue by ajgrf** [atlas-engineer/nyxt#355]
Blocker mode currently defaults to using Steven Black's hosts file, which pulls together data from various other blocklist projects. According to his [README](https://github.com/StevenBlack/hosts#sources-of-hosts-data-unified-in-this-variant), however, several of those sources are non-commercial or of unknown license (possibly unlicensed).

**Comment by Ambrevar** [comment]
Thanks for sharing!
Would you happen to know a fully free hosts file?

**Comment by ajgrf** [comment]
I'm currently browsing [filterlists.com](https://filterlists.com/) to see if I can find one. [anuDeepND](https://github.com/anudeepND/blacklist)'s looks promising, but I'm only on page 20 of 116, and there's no way to filter by license or syntax (many of them aren't hosts files).

If Next gets support for more sophisticated AdBlock syntax there will be plenty of options.

**Comment by ajgrf** [comment]
After looking through the remaining pages, I think anuDeepND's host file is still the best one I found, although it's possible that I missed some good ones. Most of the hosts files I found were either non-free, limited in scope, not updated recently, or too new to be reputable.

**Comment by Ambrevar** [comment]
I think it would do no harm switching the default list, we can always
include examples in the documentation.

Thoughts @vindarel @jmercouris?

**Comment by jmercouris** [comment]
I think it will annoy most users and if it is a license thing, those that actually care may switch to a free license. In my opinion this would be a regression for the sake of principle.

**Comment by Ambrevar** [comment]
What would be annoying?
This would all be transparent to the user.

**Comment by jmercouris** [comment]
Changing to a block list that has less coverage by default

**Comment by Ambrevar** [comment]
Does it have less coverage though, Alex?

**Comment by ajgrf** [comment]
Yes, but it's hard to say how much this matters in practice. I haven't noticed more ads while using it. It covers 34,374 unique domains, while the StevenBlack covers 42,264 unique domains.

**Comment by jmercouris** [comment]
The key then is to figure out how much it matters in practice! Degrading the user experience for the sake of principle would be undesirable :)

**Comment by ajgrf** [comment]
Maybe a few people should switch for a couple weeks and report back if they noticed a difference.

**Comment by jmercouris** [comment]
What would be the benefit of using a free hostlist? Why would the license matter?

**Comment by Ambrevar** [comment]
Well, our adblocking is currently mostly powerless without hostlist.
If we can't use the hostlist for licensing reasons, it's a pity.

**Comment by jmercouris** [comment]
Why could we not use Steven Blacks host list? I don't see how the licensing impacts whether we can use his list or not

**Comment by jmercouris** [comment]
As far as I can tell, nothing about Steven's host list prohibits our usage of it

**Comment by Ambrevar** [comment]
The problem with unlicensed (or non-properly licensed) content is that using it puts us in a legally grey area.  If someone claims right on this content some day, we would have to drop it.

**Comment by jmercouris** [comment]
Do you think it is possible to license a list of URLs?

**Comment by Ambrevar** [comment]
I'm not sure :/

**Comment by jmercouris** [comment]
I'm pretty sure it isn't an issue, if it becomes an issue, we'll switch to a free hostlist. That said, I doubt it is possible to license a list of URLs.
