### ISSUE TITLE
Allow scrolling when link hints are active

### ISSUE THREAD

**Issue by alexherbo2** [atlas-engineer/nyxt#399]

**Comment by Ambrevar** [comment]
Scrolling with the mouse wheel / touchpad works when links are active.
Is this what you meant?

**Comment by Ambrevar** [comment]
Wait, actually I can only scroll the minibuffer, I cannot scroll the current web view.
@jmercouris Can you reproduce?

**Comment by jmercouris** [comment]
I cannot reproduce

**Comment by Ambrevar** [comment]
Recipe:

- Press `C-g` on this page.
- Click on the web view (hopefully to focus it).
- Scroll the mouse wheel or press the up/down arrows.

Expected result: it should scroll the web view.

Actual result: It scrolls the minibuffer.

**Comment by jmercouris** [comment]
ah yes, I think we should unbind the scroll wheel

**Comment by Ambrevar** [comment]
OK, I'll fix this as part of the minibuffer overhaul.

**Comment by Ambrevar** [comment]
Actually, better than unbinding the scroll wheel, it'd be nice to support both: if the web view is focused, scroll it, otherwise scroll the minibuffer.
