### ISSUE TITLE
Give a visual feedback of validated keys to link hints

### ISSUE THREAD

**Issue by alexherbo2** [atlas-engineer/nyxt#401]

**Comment by Ambrevar** [comment]
Thanks for the feedback, those are all very good points!

Answering just here for you 2 other issues: The link hint implementation is currently rather ad-hoc and we need a big overhaul.

I've gathered the needs in issue https://github.com/atlas-engineer/next/issues/354.
I suggest you follow on that conversation with your 3 (very important!) issues and we keep working there.
What do you think?

**Comment by alexherbo2** [comment]
Yes.  I would love to contribute to the source code by myself, but my Lisp background is poor, so I only have issues and JavaScript equivalences to provide to help. :neutral_face:

**Comment by jmercouris** [comment]
That's okay, a lot of the work is Parenscript which is Lisp which compiles to JS, a lot of it is really just JS actually with Lispy syntax.

**Comment by alexherbo2** [comment]
@Ambrevar You suggest me to don’t create additional issues, but gather them in #354?

**Comment by jmercouris** [comment]
I believe @Ambrevar is suggesting a high level issue called something like "Rework Link Hinting system" where we gather all of the problems with Link hints and solve them and rearchitect them in one place, so that the conversation can be more centralized.

**Comment by Ambrevar** [comment]
Yes, unless you see an incentive to keep them separate :)

By the way my Javascript is not so great, so if you have Javascript code to share to fix specific issues, feel free to share, that'll prove very helpful!

**Comment by alexherbo2** [comment]
I’ve a JavaScript implementation [here][hint.js].  What I can do is continue on #354 and cherry-pick each point with snippets to illustrate.

[hint.js]: https://github.com/alexherbo2/hint.js/blob/master/scripts/hint.js

**Comment by Ambrevar** [comment]
That'd be fantastic! :D

**Comment by aartaka** [comment]
Closing, as the issues from the title is resolved, and everything else is in #354.
