### ISSUE TITLE
Add a command to cycle through headings

### ISSUE THREAD

**Issue by alexherbo2** [atlas-engineer/nyxt#410]
How about adding the ability to cycle through headings?

- Next
- Previous
- Fuzzy searching

### Quickly move around a document with no table of contents

[![Quickly move around a document with no table of contents](https://img.youtube.com/vi_webp/gp4_6VGXkOk/maxresdefault.webp)](https://youtu.be/gp4_6VGXkOk)

**Comment by Ambrevar** [comment]
I had a shot at this in the past, but then I got stuck when I realized I
had a to derive a parenscript function that would list the headings with

- unique identifiers,
- in well ordered fashion,
- deterministically.

My Javascript is a bit poor, so if you can help with this that'd be
awesome! :)

**Comment by vindarel** [comment]
FYI we have `C-.` (point) to list and go to headings. With fuzzy-matching. It doesn't cycle.

**Comment by alexherbo2** [comment]
@Ambrevar Things may change if I find a [comfortable workflow][Next package] I could help back on some features for the JavaScript side.  I added the Nix package but did not find yet how to compile it from my local repository.

[Next package]: https://github.com/NixOS/nixpkgs/commit/1c7d3389e43b2836a8f5de10f648833d610e86b2

**Comment by Ambrevar** [comment]
Are you asking how to set up a local build?

If you use Emacs, I can help you 100% with that.  Otherwise I can only
partially help ;)

We have some relatively detailed instructions there:

https://github.com/atlas-engineer/next

Besides, I recommend the Cookbook for the more general details, like the
choice of editors and all:

https://lispcookbook.github.io/cl-cookbook/

Don't hesitate to ask if you run into any trouble!

**Comment by pdelfino** [comment]
Hi,

With `Nyxt 2.0.0` there is a feature called `jump-to-heading`.  Is this feature request still relevant? Did I missunderstand something?

**Comment by Ambrevar** [comment]
The original post mentions the possibility to go to the next or previous heading.  Currently we can't do this, as `jump-to-heading` does not order the heading by order of appearance.

**Comment by aartaka** [comment]
`jump-to-heading` now does sort headings, should we close? Or is it vital to have dedicated commands here?

**Comment by Ambrevar** [comment]
Dedicated commands would be neat! :)

**Comment by Ambrevar** [comment]
Rationale: it disturbs the reading flow less.

**Comment by jmercouris** [comment]
What would be really cool is if jump to heading automatically selects the currently nearest heading when invoking it. For example, I am on a page with:

```
heading 1
heading 2
heading 3
```

I press `jump-to-heading`, the prompt buffer should appear with `heading 2` highlighted.

**Comment by aartaka** [comment]
Done in 021ebd1583ad48342d7ce2954dfde9e89860aa25. What keybindings to we assign it to?

**Comment by aartaka** [comment]
Bindings are: `M-{`/`M-}` in Emacs and `{`/`}` in VI.

**Comment by jmercouris** [comment]
A good choice of bindings, thank you Artyom!
