### ISSUE TITLE
Convenient way of expressing command variations/arguments (like flags)

### ISSUE THREAD

**Issue by noctuid** [atlas-engineer/nyxt#417]
Most existing browsers/plugins have key bindings more similar to vim where you either bind to keys or to commands as you would type them out (e.g. in pentadactyl you could have `nmap -builtin vn :tgroup-new<space>` or `:command1<cr>:command2<cr>`). While I don't think there's any reason to try to emulate this, it might potentially make sense to have something similar to flags instead of having different named commands for all different variations (e.g. `set-url-new-buffer` and `set-url-current-buffer`). Flags are convenient in part because their order doesn't matter.

For example, with qutebrowser there is just one [open command](https://qutebrowser.org/doc/help/commands.html#open) that has flags for different behavior (open in background tab, open in window, open in private mode, open declaring the new url is related to the current one, etc.).

As an example of a different approach, pentadactyl has [`:tab` and `:window` commands](http://bug.5digits.org/help/pentadactyl/tabs#opening-tabs) that take a command and either open a new tab or window.

It might make sense to either create a function that takes keyword arguments and returns a command (similar to using flags) or to have wrappers like `(with-new-window ...)` or `(in-background-tab ...)`. I'd prefer the former. This is minor, but I think it would be nice to just have one function instead of having to remember the names for all variations of a command (I think there are ~32 variations for qutebrowser's `:open`, for example).

Example of my first suggestion:
```
(define-key "o" (open :new-tab t))
;; or if underlying function that accepts keyword arguments and way to define
;; anonymous command; above could also result in/expand to something like this
(define-key "o" (define-lambda-command () (open :new-tab t)))
```

Also, would it make sense to have `execute-extended-command` act like eval in a case like this? I'm leaning towards thinking this is unnecessary but am interested in your thoughts:
```
M-x (open "url" :new-tab t)
```

**Comment by Ambrevar** [comment]
Very good points! :D 

Note that we have `M-:` to evaluate Lisp, so the above would be

```
M-: (open-urls "foo") RET
```

We should document this more ;)
Should `M-x` act like `eval`?  Hmmm, why not.  Need to  think more about this.

Regarding the "composibility" issue: you are right, but actually I had another idea in mind: the "Emacs Helm _actions_" approach.

With Emacs Helm, there is a single binding to bring up the list of buffers/files, then everything can be done from there: opening, opening in new window, deleting, renaming, etc.

This composes well in terms of code and I believe it is superior to to a "command line" approach since it gives users:

- a full list of all possible actions
- contextual help while running the minibuffer
- key bindings
- fuzzy completion on the actions

Actions can already be implemented now that we have support for nested minibuffers.
It's quite easy, I can provide some guidance if you'd be interested in picking this up :D

**Comment by noctuid** [comment]
> With Emacs Helm, there is a single binding to bring up the list of buffers/files, then everything can be done from there: opening, opening in new window, deleting, renaming, etc.

I think it's a good idea. I'm thinking mostly about ease of making the keybinding though. I wouldn't normally change the action afterwards. I have dedicated keybindings for all the most common actions in other browsers. That said, something like transient.el for combining possibilites (target, private or not, related or not, etc.) would definietly be a lot more useful than having command-line flags, which I agree wouldn't be very useful to add. Something like helm where you can preselect the default options you want when making the keybinding would be a better alternative to trying to mimic the commandline other browsers/plugins.

A helm or ivy-occur-like way of deleting a bunch of buffers, for example, would definitely be extremely useful. Even something like being able to pull up a tree or flat listing of buffers in a text editor and search/navigate/delete lines would be nice.

For now, I'll probably just be sporadically creating issues. I'm hoping this project will be the perfect opportunity for me to start writing something useful in CL again eventually. Hopefully, in a year or two I'll have more free time to work on open-source projects again (and finally fix a lot of outstanding issues with my own projects), but for now I probably won't be able to help much.

**Comment by Ambrevar** [comment]
> That said, something like transient.el for combining possibilites
> (target, private or not, related or not, etc.)

What is "related"?
While we are at it, could you give a list of all those flags/options you
find useful?  This could prove very helpful when time comes to work on
this! :)

> A helm or ivy-occur-like way of deleting a bunch of buffers, for
> example, would definitely be extremely useful.

Great news: you can already do it on master! :D

> For now, I'll probably just be sporadically creating issues. I'm
> hoping this project will be the perfect opportunity for me to start
> writing something useful in CL again eventually. Hopefully, in a year
> or two I'll have more free time to work on open-source projects again
> (and finally fix a lot of outstanding issues with my own projects),
> but for now I probably won't be able to help much.

No problem, your feedback is a most precious contribution already,
and I hope you enjoy using Next in the meantime!

**Comment by noctuid** [comment]
> What is "related"?

Qutebrowser allows for different positioning rules based on whether a tab is "related" or not (see the relevant settings [here](https://qutebrowser.org/doc/help/settings.html#tabs.new_position.related)). If you open a link on a page, that would be considered related. If you just happened to be on a specific tab, and manually opened a url, that would be unrelated. My keybinding for #416 has `--related` because I'm editing the current url.

If you look at the buffers opened as a tree, related buffers would be children. Even without a tree listing, this is useful because it determines the tab/buffer ordering. One example configuration would be to open related tabs after the current tab and open unrelated tabs after all related tabs. If I opened a link on the page in the background, manually opened an unrelated link or quickmark or something, and then opened another link on the page, I'd get a tab order like "[current tab] [link 1] [link 2] [unrelated manually opened link]". You could have another configuration where link 1 and 2 were swapped. Assuming I have things configured so I go right when closing a tab, I would visit all related tabs before unrelated tabs.

> While we are at it, could you give a list of all those flags/options you
find useful?

I think most of them are useful ([qutebrowser](https://qutebrowser.org/doc/help/commands.html#open) and [pentadactyl](http://bug.5digits.org/help/pentadactyl/browsing#opening)). The basics:
- target/where/whether to display (replace current buffer, new background buffer, new focused buffer, new buffer in new window); since next is using buffers, it would probably make sense to have a separate option for whether or not to delete the current buffer
- whether buffer should be private (default based on current window)
- whether buffer is related

I don't know how useful `--secure` for forcing https is. HTTPS everywhere functionality is probably more useful. Qutebrowser allows a count to choose a specific tab index to display the url in; I don't know how useful that is.

**Comment by Ambrevar** [comment]
Thanks for the details, this is very insightful.

- Agreed, I believe the `--secure` flag can be replaced with a more automated
  behaviour that simply does The Right Thing©, like "HTTPS everywhere".

- I think we can also have a more automated approach for "related"
  buffers.  First of all, we could add the possibility to group buffers
  by domain in the minibuffer.  Then we could add a minibuffer actions
  to create groups (they could appear in colors in them minibuffer).
  The advantage of groups, or "buffer tags", over a tree is that they
  compose: a buffer can belong to multiple groups.  The user could
  configure rules to automatically assign groups, etc.

  I don't know how a useful a "related buffer tree" could be, compared
  to flat group.  Thoughts?

**Comment by noctuid** [comment]
I think being able to use both would be useful. The "related" concept in qutebrowser is already mostly automated (I've never added `--related` manually at least, but it could potentially be useful). Being able to narrow/filter buffers by tags or the domain would be useful. Pentadactyl has a concept of groups where you can automatically assign tab groups based on the url and then have group-local settings/keybindings. I don't think you could actually search for tabs by group though (which would have been nice).

The related buffer tree is nice as a view of how things were opened. A lot of people like tree style tabs, and even without them, it's useful to be able to go through a bunch of links in an intelligent order without needing to select the next one in the minibuffer or cycle through a few to find the one you want.

For example, maybe I'm researching something and make a search with whatever search engine. I open 3 links from that page. If I want to keep the search open, I just hit a key to go to the next buffer (either the first or last link opened depending on my workflow). If I didn't need the search results anymore, I would delete the buffer (but it could be kept as a node in the tree until all children were deleted).

On that page, maybe there are a few related readings at the end. I open a couple of those in the background, delete the current buffer, and automatically end up on a related reading. I read the first one and delete it and then read the second one and delete it. Now I've automatically moved up the tree to the next article I opened on the search results page and continue from there.

Things won't be this seemless in general, but for me it's the most intelligent guess about the order I'm going to look at pages (much better than doing something like opening new tabs at the very end, for example; with qutebrowser, it's configurable, so you could do that if it suited you better though). 

You don't actually have to store a tree of anything for this basic idea to work (you just order buffers appropriately), but I think that could be a useful visualization.

**Comment by Ambrevar** [comment]
We could add a new extended-execute-command (bound to, say, `M-X`) which prompts for arguments.

With the right typing we could even be smart about it.
We can add methods to prompt on given types.
For instance, with a `buffer` type we would prompt the user for the current list of buffers.
The default method would be to prompt the user for Lisp code.

**Comment by jmercouris** [comment]
`execute-extended-command` now exists! Please reopen if you have more ideas about things that are not yet implemented!
