### ISSUE TITLE
Enhance the messages, history tree and describe pages

### ISSUE THREAD

**Issue by vindarel** [atlas-engineer/nyxt#425]
`messages`, `buffer-history-tree` and `[command, variable]-inspect` produce an html view, which is pretty bare bones. We could spice them up, make them pretty, probably reactive (sort columns in messages,…) and with more links.

The more we add introspection information into the help, the better.

skills required: html, css and JS, all through Lisp; lisp to enhance the help.

**Comment by kelseyneis** [comment]
Hello! I'm intrigued by this project, but I don't know anything about Lisp. I looked through the code a little and couldn't figure out how the HTML view is put together. Do you think this would be a good issue for someone with the frontend experience but no Lisp? If so, I could use a little direction on where to look for the pieces that need to be updated (I tried searching for them and it didn't give me much insight).

**Comment by jmercouris** [comment]
Firstly thank you very much for your interest in being a contributor to Next! No worries, we can explain, there is a lot to say, but this task specifically shouldn’t be too deep into Lisp, I can say more when I’m at a computer, or one of my colleagues may chime in!

**Comment by jmercouris** [comment]
@kelseyneis I'm back at my computer now,

So the first place to see the help is in a file called `help.lisp`

Here's a small sample of the command `help`

```
(define-command help ()
  "Print some help."
  (let* ((help-buffer (make-buffer
                       :title "*Help*"
                       :modes (cons 'help-mode
                                    (get-default 'buffer 'default-modes))))
         (help-contents
           (cl-markup:markup
            (:h1 "Getting started")
            (:p (:b "Warning: ") "Next is under active development. Feel free to "
                (:a :href "https://github.com/atlas-engineer/next/issues"
                    "report")
                " bugs, instabilities or feature wishes.")
            (:p "You can help with Next development by supporting us in various ways:"
```

The important part here is `help-contents` which is lexically bound to the output from cl-markup which we use for all of our HTML generation. You can see more about it here: https://github.com/arielnetworks/cl-markup

In short cl-markup works like this:

```
(cl-markup:markup (:h1 "Hello World")
                           (:p "Some Paragraph"))
```

to produce:

```
"<h1>Hello World</h1><p>Some Paragraph</p>"
```

You can then style whatever it is that you make with what we use called cl-css: https://github.com/Inaimathi/cl-css

The idea with cl-css is very similar.

Something like this:

```
(cl-css:css
          `((body :border-top "4px solid dimgray"
                  :margin "0"
                  :padding "0 6px")
            (p :margin "0")))
```

Will produce this:

```
"body { border-top: 4px solid dimgray; margin: 0; padding: 0 6px; }
p { margin: 0; }
"
```

So, as you can see, cl-markup and cl-css are thin wrappers to turn S-EXP into HTML and CSS respectively.

If you need a place to get started with Common Lisp and playing around with cl-markup and cl-css I recommend Portacle https://portacle.github.io. Using Portacle you can then say:

`(ql:quickload :cl-css)` and execute the forms that I've included above.


After you are familiar with that, you can see the commands `variable-inspect` and `command-inspect`, both located in `help.lisp`. That would be a good place to start, modifying their HTML and CSS to make them look nice, inline with the general Atlas aesthetic.

As always, if you need support with this issue, please feel free to email any one of us, or reply in this issue thread! I hope the above is helpful!

**Comment by kelseyneis** [comment]
Thank you for taking the time to demystify some of this and provide some resources! I will start digging in in the next few days and reach out if I have questions.

**Comment by jmercouris** [comment]
I'm closing this issue as it is a bit too abstract. Please feel free to open new issues with suggestions for implementation improvements!

**Comment by Ambrevar** [comment]
For the question of cross-references between docstrings, see https://github.com/atlas-engineer/nyxt/issues/967
