### ISSUE TITLE
Request: on Github fork, clone the repository to disk

### ISSUE THREAD

**Issue by vindarel** [atlas-engineer/nyxt#439]
Next 1.3.3 has a `git-clone` (vcs-clone) command. It would be great if, when I press the "fork" Github button, Next suggested me to also clone the repository locally.

What needs to be done: probably installing an event listener on the button. This requires JavaScript knowledge. (we can help a new lisper with the lispy JS). A `git-mode` mode needs to be created, and the feature be tied to it. Then a call to git-clone should do it, with a parameter (global but better, bound to the mode class) to enable/disable this feature.

**Comment by amoury** [comment]
Hi @vindarel, I love the idea of keyboard oriented web-browser with VI bindings. I did love to work on this feature. I have a pretty good knowledge of JS but have never worked with `lisp`. Do you I can still take up this issue?

**Comment by vindarel** [comment]
Hello, you totally can! The core knowledge/trick is JS, you can search how to do the feature in any browser. We'll help you for the rest: how to get started in CL, how to install Next locally and extend it live, CL&Parenscript (JS abstraction) basics, Next internals (modes, etc). Don't hesitate to reach us on [our subreddit](https://www.reddit.com/r/next_browser/), on [r/learnlisp](https://www.reddit.com/r/learnlisp/), on IRC, on `hello@atlas.engineer` and to send me an email.

Enjoy the ride :)

**Comment by vindarel** [comment]
So actually the JS part here is small and easy, but we miss an endpoint on the WebKiGTK side to react to DOM events. https://webkitgtk.org/reference/webkitdomgtk/2.4.1/WebKitDOMEventTarget.html#webkit-dom-event-target-add-event-listener 
We'll wait before implementing it because we are doing an architectural change.

**Comment by Ambrevar** [comment]
Should be doable now.

**Comment by jmercouris** [comment]
I believe this is out of the scope of Nyxt. Support for a VCS should be an extension in my opinion. Closing this for now. If you disagree, please feel free to reopen!
