### ISSUE TITLE
Add a Dockerfile to build the latest version of Next

### ISSUE THREAD

**Issue by alexherbo2** [atlas-engineer/nyxt#450]

**Comment by Ambrevar** [comment]
Some people from Alpine have started working on it: #338 (end of the thread).
There seems to be a blocker, help is welcome.

Note that we have a Guix pack that mostly supersedes the Docker.  You can generate it with the `build-scripts/guix.scm` file.
The Guix container suffers from similar issues though.

**Comment by durrendal** [comment]
@alexherbo2 

I've got an alpine based docker build in the works, you can find it here. 

https://gitlab.com/Durrendal/WS-Docker-Builds/tree/master/next

Unfortunately at the moment it doesn't render correctly. It just produces a white screen. It does however appear to respond to key input, per the system side logging. So it's doing something, just not yet usable. If you want to try and help, please let me know I would appreciate it!

**Comment by vindarel** [comment]
FYI, here's a new Docker image for SBCL that builds on Alpine: https://github.com/daewok/docker-sbcl/

**Comment by durrendal** [comment]
Thank you Vindarel! I haven't been able to get SBCL2.0.0 built yet on Alpine, but it looks like I've been beaten to the punch, not at all surprised when I see @mit.edu! 

And there's actually patches in there for getting sbcl to build on arm as well, so that is a literal treasure trove of information!

**Comment by aadcg** [comment]
Given that we distribute Nyxt as a flatpak and a self contained bundle (courtesy of `guix pack`), there's little sense in pursing this goal. Users don't seem to request it too.

**Comment by aadcg** [comment]
If anyone is interested in this request, see https://github.com/deddu/nyxt-docker.
