### ISSUE TITLE
Embed Emacs in Next

### ISSUE THREAD

**Issue by alexherbo2** [atlas-engineer/nyxt#461]
https://github.com/glacambre/firenvim

**Comment by vindarel** [comment]
There's also https://github.com/stsquad/emacs_chrome

and Tviti's already using emacs-daemon for an "edit in emacs" command: https://www.reddit.com/r/next_browser/comments/dexboi/edit_text_fields_in_emacs_with_editinemacs/

**Comment by Ambrevar** [comment]
See also #557.

**Comment by jmercouris** [comment]
We can use the behavior as Git does for commit messages on the command line. It is probably trivial to write a simple wrapper around this where the user can set their $EDITOR, but instead of $EDITOR, it would be a slot within the browser class.

**Comment by aartaka** [comment]
Stale? 

We have `editor-buffer`, $EDITOR bindings and `edit-with-external-editor`, and there is `input-edit-mode` to move around text in an emacsy way. [`nx-ace`](https://github.com/atlas-engineer/nx-ace) is relatively good at simulating Emacs, and similar approach can be used to implement `nx-nvim` or `nx-emacs`. The question is: does it belong to the core? Given that most editor interfaces are extensions, maybe we shouldn't pull Emacs-bridge as the only built-in editor? :thinking:

**Comment by aadcg** [comment]
> Stale?

Stale.
