### ISSUE TITLE
Provide interactive, as you type help

### ISSUE THREAD

**Issue by alexherbo2** [atlas-engineer/nyxt#463]
Provide interactive, as you type help of the current command, candidate completion.

**Comment by Ambrevar** [comment]
You mean display the docstring of the currently-selected-command
somewhere on screen?

We could do something "Helm-style" and have persistent actions.  For
EXECUTE-COMMAND, the persistent action would be to display the command
docstring in a new buffer.  This would require window management though.

**Comment by alexherbo2** [comment]
Yes

**Comment by Ambrevar** [comment]
Also see #624.

**Comment by Ambrevar** [comment]
It's in 2-pre-release-6.
