### ISSUE TITLE
Load system fonts

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#467]
Next knows nothing about system fonts, it would be nice if we could use any font, not just web fonts to customize the minibuffer and other elements.

**Comment by q3cpma** [comment]
Not wanting to clutter the issue tracker I'll post my questions related to this and especially the issue this closed:
1) Am I right in saying that I can't choose an arbitrary system font for the UI, currently?
2) Since, from what I understood, webkit is used to draw the UI, can bitmap font even be supported by this method?

**Comment by Ambrevar** [comment]
WebKitGTK has options to set the various fonts:

https://webkitgtk.org/reference/webkit2gtk/stable/WebKitSettings.html#webkit-settings-set-default-font-family

I do not know if bitmap fonts are supported.  Anyone?

**Comment by q3cpma** [comment]
On Fri, Jul 30, 2021 at 01:12:56AM -0700, Pierre Neidhardt wrote:
> WebKitGTK has options to set the various fonts:
>
> https://webkitgtk.org/reference/webkit2gtk/stable/WebKitSettings.html#webkit-settings-set-default-font-family
>

Doesn't this configure the font family for the all the rendering (including web pages)?

**Comment by jmercouris** [comment]
You can load some local assets sometimes. For example, you can load javascript, but not a local javascript on a remote url.

**Comment by Ambrevar** [comment]
We can configure WebKit settings per-buffer, for instance for the prompt
buffer without affecting the status area, etc.

**Comment by jmercouris** [comment]
Well, seems it easier than we thought, after messing around for a bit:

```
(define-configuration status-buffer
    ((glyph-mode-presentation-p t)
     (style (str:concat 
             %slot-default%
             (cl-css:css
              '(("@font-face"
                 :font-family "myFont"
                 :src "local('Unifont')")
                ("*"
                 :font-family "myFont"
                 :background-color "rgb(100,100,100) !important")))))))
```

of course you can replace 'Unifont' with any other locally installed font. Please note that you CANNOT do 

```
:src "url('file:///some/path/to/font.ttf')"
```

as it will not be allowed by the security settings.

**Comment by jmercouris** [comment]
Screenshot:

![Screenshot_20210730_210003](https://user-images.githubusercontent.com/1691662/127699808-8ddb9cb8-e41e-40ab-9275-100985a13024.png)

**Comment by q3cpma** [comment]
On Fri, Jul 30, 2021 at 12:01:05PM -0700, John Mercouris wrote:
> Screenshot:
>
> ![Screenshot_20210730_210003](https://user-images.githubusercontent.com/1691662/127699808-8ddb9cb8-e41e-40ab-9275-100985a13024.png)
>

Thanks a lot for the fast work. It would have been a definite deal breaker for me,
and I was quite scared as I never managed to use bitmap fonts with qtwebengine,
so this is quite the relief.

Hope webkit has no problems with OTB fonts (unless it directly supports PCF,
which I somehow doubt).

**Comment by jmercouris** [comment]
So there's a subsequent problem though, we can't exactly bundle a font with Nyxt this way. The user would have to install the font. This makes it *not* ideal.

**Comment by jmercouris** [comment]
Can you show me a minimum example of how we would load a custom font from disk for the user?

I'm thinking of bundling Public Sans or Hack with Nyxt to make our appearance consistent for our users.

**Comment by Ambrevar** [comment]
I've never tried in Common Lisp, but other apps like McClim or Kandria might help.
A quick lookup and I found:

https://github.com/Shinmera/font-discovery

Otherwise, we could leverage fontconfig on GNU/BSD:

https://www.freedesktop.org/software/fontconfig/fontconfig-devel/fcconfigappfontaddfile.html
