### ISSUE TITLE
High CPU use for some websites

### ISSUE THREAD

**Issue by intuser** [atlas-engineer/nyxt#506]
If I visit www.spiegel.de and keep it as the current tab the WebKitWebProcess uses a lot of CPU. (Around three to six times of for instance waterfox. It's enough to keep my fan working.) Loading a new page on that site again uses much more CPU than waterfox. (Browsing is notably slower therefore.)

**Information**
- OS name+version: Ubuntu bionic (18.04)
- Kernel name+version: 4.15.0-72-generic
- Graphics card and driver: Intel Corporation UHD Graphics 620 (rev 07)
- Desktop environment / Window manager name+version: GNOME Shell 3.28.4-0ubuntu18
- Next version (from =M-x next-version= or =next --version=): 1.3.4
- How you installed Next (Guix pack, package manager, build from source): deb-package
- SBCL version (if built from source):
- WebKitGTK+ / PyQt-Webengine version: webkit2gtk-4.0

**Comment by intuser** [comment]
Probably related: Visiting https://www.spiegel.de/politik/deutschland/fridays-for-future-sorgt-mit-tweet-ueber-grosseltern-fuer-aufregung-a-1302665.html the page loads (very slowly). But scrolling down twice or so it turns grey and nothing moves. (I can change to other buffers though.) The problem appears with other pages of this website too.

**Comment by Ambrevar** [comment]
This could be a WebKitGTK issue.  Can you test with Epiphany or any
WebKitGTK-based browser see if you can reproduce?

**Comment by intuser** [comment]
I tested epiphany, with a mixed result: CPU use simply having www.spiegel.de in the current buffer is relatively hight with this browser too. (But devided between gnome-shell and WebKitWebProces.) During loading the CPU use also is quite high, but much lower than with next. But the reason might be that epiphany seems to come with an adblock system enabled and there are almost no ads. (That's of course great. But I don't see how I could change it for testing purposes.)

**Comment by jmercouris** [comment]
I've been thinking about integrating a new optional JS adblocker in addition to the content blocker we have now, can you try disabling the adblocker and see if the performance is the same?

**Comment by intuser** [comment]
I disabled the adblocker in epiphany and things turned as bad (or worse) as they are in next. So the adblocker in epiphany makes it usable with pages like www.spiegel.de and something like that in next would be an great improvement!

**Comment by jmercouris** [comment]
Ah ok! Very good to know! Thank you for the feedback and report!

**Comment by Ambrevar** [comment]
@intuser Is it still a problem on master with a recent WebKitGTK+ (2.28.2 or above)?

The ad-blocker is discussed in #32.  One way to implement it would be to support WebExtensions first (#464), this would give us uBlock for free I believe.

**Comment by intuser** [comment]
Yes. I now have WebKitGTK+ 2.30.3 and nyxt 2 and the problem continues.

**Comment by aadcg** [comment]
Please try our latest release. This is probably an issue that is outside of our scope.
