### ISSUE TITLE
bockmarks problem with multiple links having 1 tag

### ISSUE THREAD

**Issue by ebrasca** [atlas-engineer/nyxt#515]
**Describe the bug**
When I try to save 2 links to my bockmarks with same tag first of them changes to some other tag
In my case from Mezzano to Transmission

**Precise recipe to reproduce the issue**
Have 2 links with diferent tags and add one with one of them

**Information**
- OS name+version: Gentoo
- Kernel name+version: Linux 4.19.86
- Graphics card and driver: nvidia
- Desktop environment / Window manager name+version: stumpwm
- Next version (from =M-x next-version= or =next --version=): commit 063d40eda5bdfdfe4eb18e6fc74896a016f0c162
- How you installed Next (Guix pack, package manager, build from source): Git
- SBCL version (if built from source): 1.4.9
- WebKitGTK+ / PyQt-Webengine version: 2.26.2 / 5.13.2

**Comment by ebrasca** [comment]
I think it only changes tag from last bockmark

**Comment by Ambrevar** [comment]
Sorry for the delay :/
I can't reproduce your issue.  Could you provide a precise recipe (with the tag names, the URLs, etc.)?

I tried the following:

- Go to https://github.com and bookmark it with tags "foo" and "bar.
- Go to https://ambrevar.xyz and bookmark it with tags "foo" and "baz".
- Open ~/.local/share/next/bookmarks.lisp: The tags are correct.
