### ISSUE TITLE
Feature request: Link hinting indexing using custom list of char

### ISSUE THREAD

**Issue by impaktor** [atlas-engineer/nyxt#527]
I mentioned this on IRC, and @chrisboeg wanted me to register an issue on it:

In [avy-mode](https://github.com/abo-abo/avy), you can specify which characters to be used for link hinting. I.e. instead of indexing links with a,b,c,d...z, you can specify whatever rocks your boat, like home row: a,s,d,f, or home row columns a,q,s,w,d,e... (I don't mind moving fingers up/down at all, as I have orthogonal layout on [my keyboard](https://kinesis-ergo.com/shop/advantage2/), but I do mind diagonal movement very much)

(For those who don't know avy-mode, it's the successor / improvement of ace-jump, demonstrated by [emacsrocks](http://emacsrocks.com/e10.html)).

**Comment by jmercouris** [comment]
A very good suggestion, thank you!

**Comment by impaktor** [comment]
In conkeror (sorry to nag on about it), they use numbers, 1...9, and have the 0 always refer to the current page itself.

I guess that's what `copy-url` does in next? So two different copy commands depending on if we want to copy an indexed link, or url of the current page?

**Comment by craftyguy** [comment]
Luakit (another webkit browser) has a nice system for changing the set of characters used: https://luakit.github.io/docs/modules/select.html

For example I can specify only allowing hints using keys on the home row with:
```
select.label_maker = function (s)
    return s.sort(interleave("asdfg", "hjkl"))
end
```
