### ISSUE TITLE
C-f and C-b when entering text in html forms

### ISSUE THREAD

**Issue by cswank** [atlas-engineer/nyxt#53]
Would it be possible for C-f and C-b to be bound to the usual forward character and back character behavior on MacOS when entering text in html forms?  I use those keybindings all the time when I'm entering text and it is jarring when those commands navigate me away from the page I'm on.

**Comment by jgkamat** [comment]
https://github.com/nEXT-Browser/nEXT/issues/28, I think that this would make a lot of sense if there was a mode for insert! ;D

**Comment by jmercouris** [comment]
@jgkamat LOL :D! that would be convenient wouldn't it :D

**Comment by jmercouris** [comment]
to answer the question, yes, it would be possible, the keybindings are going to actually be overhauled soon, and I'm going to add support for something like Hydra, so I'll leave the default c-f, c-b bindings alone, as I like them too :)

**Comment by Ambrevar** [comment]
@jmercouris I'm not sure I understand this issue.  Is this still valid?

**Comment by jmercouris** [comment]
This issue is still valid, yes. It is part of the minibuffer work I would like to do.

**Comment by jmercouris** [comment]
This is now implemented in master :-)

**Comment by jmercouris** [comment]
The keys are unbound though, you'll have to set them yourself until we come up with a good scheme.

**Comment by jmercouris** [comment]
the commands are prefixed with "cursor-", for example cursor-forward
