### ISSUE TITLE
responsiveness/lag ?servo

### ISSUE THREAD

**Issue by bijang** [atlas-engineer/nyxt#535]
thank you for the work, my main concern is not necessarily performance  speed but...
just comparing next to firefox, it loads fast and correctly, 
but lags significantly on scrolling, 
is this a webkit vs servo issue , 
or something with CL, 
I've never used safari or ios
is it difficult to implement servo (vs webkit), if that were the issue?

**Comment by Ambrevar** [comment]
The scrolling issue is due to how we do it: in pure Javascript.  We
don't leverage the web engine.

We've planned to refactor the architecture to expose all bindings of the
web engine for free, in which case scrolling could be implemented using
the web engine.  This would dramatically improve the performance.

**Comment by bijang** [comment]
thank you. would this improve start up for the program too? 
also is there plans to support servo engine at some point? 
only cause i read this project may support chromium on mac, (i may be wrong) 
and im biased cause i think servo is cool, almost as cool as this project

**Comment by jmercouris** [comment]
I can try to answer some of the questions as best as I can:

1. this would improve start-up performance time, yes :-)
2. there are no plans to currently support servo engine. It is however not too hard to support another engine for us, we are not deeply tied to any particular engine

**Comment by bijang** [comment]
thank you for reply, i dont usually chase performance but in a keyboard browser and the speed that brings it would be natural to not want the browser to be the limiting factor. 
Servo would be awesome! just interesting for a rust engine for what it's worth...
Last annoying question, is this wayland ready too or is that on the roadmap?

**Comment by jmercouris** [comment]
Next works on Wayland. It has nothing to do with the compositor.

**Comment by bijang** [comment]
thank you for answering an ignorant question so politely! i'm trying to get more eyes and more users on this great project

**Comment by jmercouris** [comment]
that's very nice of you, thank you :-)

**Comment by jmercouris** [comment]
I'm closing this for now, if there is something else you would like to talk about, please feel free to reopen!
