### ISSUE TITLE
Feature request: Hinting style could be better?

### ISSUE THREAD

**Issue by impaktor** [atlas-engineer/nyxt#538]
## Introduction

If I split my tiling WM in two equally sized panes, and open Next on left and [Conkeror](http://conkeror.org/) on right, and in both visit Next's github issues page, you see differences in how expressive they are, or how "good" they are at showing hinted links:

## Example
Please open below image in separate buffer/tab, to follow my reasoning below:
![2020-01-27-085110_1600x900_scrot](https://user-images.githubusercontent.com/619390/73172182-bb84bd00-4102-11ea-8b56-1e3f8948a5d8.png)

## Thoughts

In my mind I currently prefer the right, for the following main reasons:

1. it indexes far more links, while next obscures almost half the screen with a minibuffer, that really doesn't serve much purpose. I find I only use/need Next's minibuffer, when/because it's unclear what the labels are indexing, which leads me to the next point

2. on the right, I see exactly the extent of each link (yellow field), where as in Next, there areindex-badges that just appear to be sitting way off, because I can't see which link it's referring to. For example, consider indexes `DA`, or `DC` in Next above (left), what are they? I was genuinly confused when I saw it, (this is where I started looking in the minibuffer). But on the right side version, I instantly see: "oh, there's a small link there, and it's the user name of the issue author, and the index is indeed just right of the link"

3. Further examples of above points: In Next above, it's very unclear to me e.g. what `BT`, `BU`, `BV` are indexing. Is `BV` the _Pull Request_ tab? Or _Issues_ tab? 

4. This is off topic, but I noted just now, that there's no "Filters" button (`21` in Conkeror to the right), but I assume that's something related to the underlying web engine?

I assume people will feel attached to current hint-badges, and minibuffer, but if there was some option/way to get the functionality of the right (i.e. no minibuffer for hinting, and badge also marks the full link interaction area), I'd use it.

**Comment by chrisboeg** [comment]
So I think in general, the placement of the hints compared to conkeror is obviously worse, and should be treated as a bug.

About highlighting (for example with yellow background as in the image) the whole element that is *hinted to*, I think is a good feature too. It would probably require us to add a class to the element. If we did that, the element would be able to be styled by the user like with the other styles for the hints, so even if we end up not per default adding a background color, adding the class would have my vote so the user then could add the background color them self if they wish to.

Also I think that for hinting and searches and the like it should probably be user configurable if the "matches" in the minibuffer should appear or not.

**Comment by jmercouris** [comment]
I've had enough time to think about this. Thank you very much for your extremely thorough write up. Here are my thoughts on the matter:

Highlighting the element to know what is being hinted is very wise. I like the idea a lot. A cool extension to this may be highlighting each element with a unique color from a palette. For example:

1. could be green
2. could be red
3. could be yellow
...

this way, when you see the highlighted color, and the color of the hint, you would know EXACTLY what the hint is referring to. Of course there are a finite amount of colors, so there would be repeats, but it would add a lot of useful information.

The minibuffer, in my opinion, serves a very important purpose in showing you all hints, even ones that are offscreen. In any case it is rather trivial to hide the minibuffer completions during link hinting as is done in Conkeror. We could make a simple toggle to enable this feature for those that desire it.

Thanks, interested in your thoughts!

**Comment by impaktor** [comment]
I'm luke warm to color each url in its own color. For me the information that I want to see is:
- what are the clickable elements
- what is the currently selected clickable element
- (and what link do I want to open, but Next doesn't know this, only mi brain)

So in my mind it's two colors. Compare with [avy](https://github.com/abo-abo/avy), if they use three letters to index the URLs, then only three colors: one for the first letter, one for the second letter and one for the third letter in the index - rather than giving each jump position its own color.

> The minibuffer, in my opinion, serves a very important purpose in showing you all hints, even ones that are offscreen

It's difficult for me to say much on this now, since it's not part of my current way of browsing, since my current browser doesn't do this; but I guess it's a balance between obscuring current view, and showing all links, including the ones outside the screen, several pages down. I don't want to be like a BASIC programmer saying "Recursion? I can't imagine any use for that!"

**Comment by aadcg** [comment]
I believe that we've settled on a better hinting style. Thanks everyone.

**Comment by ldutra** [comment]
> I believe that we've settled on a better hinting style.

I disagree strongly.  In fact having a Conkeror mode is what will enable me to migrate from Conkeror to a new browser. Using Nyxt now is just too painful to my GNU Emacs traine fingers.

**Comment by Ambrevar** [comment]
It seems that Nyxt allows for the Conkeror-style bindings now (on `master`).   Is something missing for you, @ldutra ?

**Comment by aadcg** [comment]
Since there's clearly interest, I'll reopen :)

**Comment by ldutra** [comment]
> @ldutra If you get something up and running, please report back, I'm very interested, as [I'm still on conkeror](https://impaktor.gitlab.io/conkeror.html)

I had got nowhere last year, now I have Nyxt prerelease installed in Debian.  But I still see no improvement, is there a setting for that?  Even if I suspect my real problem will be my Conkeror muscle memory.  FWEIIW, am on Webmacs.

**Comment by jmercouris** [comment]
@ldutra what is specifically missing? I'm not sure I quite understand.

**Comment by aadcg** [comment]
@ldutra if you're looking for this kind of hinting behavior configure it along the line of:

```lisp
(define-configuration nyxt/hint-mode:hint-mode
  ((nyxt/hint-mode:hints-alphabet "KDJFLSAEUROWPQCMVXZ")
   (nyxt/hint-mode:fit-to-prompt-p t)
   (nyxt/hint-mode:auto-follow-hints-p t)
   (nyxt/hint-mode:compute-hints-in-view-port-p t)
   (nyxt/hint-mode:show-hint-scope-p nil)))
```

**Comment by ldutra** [comment]
> @ldutra if you're looking for this kind of hinting behavior configure it along the lines of:
> 
> ```lisp
> (define-configuration nyxt/hint-mode:hint-mode
>   ((nyxt/hint-mode:hints-alphabet "KDJFLSAEUROWPQCMVXZ")
>    (nyxt/hint-mode:fit-to-prompt-p t)
>    (nyxt/hint-mode:auto-follow-hints-p t)
>    (nyxt/hint-mode:compute-hints-in-view-port-p t)
>    (nyxt/hint-mode:show-hint-scope-p nil)))
> ```

Thanks, it does the trick.  But using the prerelease, follow-hint is unbound.  I can only navigate using ðe mouse, which quite negates ðe point in trying Nyxt at all.  But this is a separate issue.

**Comment by aartaka** [comment]
> Thanks, it does the trick. But using the prerelease, follow-hint is unbound. I can only navigate using ðe mouse, which quite negates ðe point in trying Nyxt at all. But this is a separate issue.

Did you set up any keybindings?

**Comment by ldutra** [comment]
> > Thanks, it does the trick. But using the prerelease, follow-hint is unbound. I can only navigate using ðe mouse, which quite negates ðe point in trying Nyxt at all. But this is a separate issue.
> 
> Did you set up any keybindings?

Never, thus my surprise.  I gather it is a v3 issue, even after I moved the lisp file out of my .config/nyxt directory.

**Comment by jmercouris** [comment]
Perhaps it is something with another layer of your keybindings. In any case, it is not broken on Nyxt.

**Comment by ldutra** [comment]
> So, even `C-j` (CUA binding) is unbound?

C-j is download list.  C-J was unbound, now somehow it woks.  I have no personal lisp file.
![Capture d’écran du 2023-03-07 15-25-52](https://user-images.githubusercontent.com/1100593/224036160-082e7882-7025-4412-949c-ef343f3ce385.png)

**Comment by aadcg** [comment]
> C-j is download list. C-J was unbound, now somehow it woks. I have no personal lisp file.

When you're not sure about the keybinding for a command, you can find it issuing the command `describe-command`.

**Comment by impaktor** [comment]
On current master (v.3 4f0e960fdbea4d8508ac0a9f71f806f8d3a03daf), I'm trying the code above, but I get a pop-up error, and the config doesn't seem to have taken effect. Trying my hand at the documentation, I'm guessing it should be something more like this (but below doesn't work either):
```lisp
(define-configuration nyxt/mode/hint:hint-mode
  ((nyxt/mode/hint:hints-alphabet "KDJFLSAEUROWPQCMVXZ")
   (nyxt/mode/hint:fit-to-prompt-p t)
   (nyxt/mode/hint:auto-follow-hints-p t)
   (nyxt/mode/hint:compute-hints-in-view-port-p t)
   (nyxt/mode/hint:show-hint-scope-p nil)))
```
Any hint on what's wrong?

**Comment by aartaka** [comment]
We've simplified the architecture of hint mode a bit, so it's much simpler on 3.0:
```
(define-configuration :hint-mode
  "The :hint-mode magic here is to avoid writing these tedious prefixes.
It's auto-resolved to nyxt/mode/hint:hint-mode.

Slot names also resolve to the right prefix based on the mode they
belong to:"
  ((hint-alphabed "KDJFLSAEUROWPQCMVXZ")
   (hinting-type
    :vi
    :doc ":vi-type hints encapsulate fit-to-prompt-p=t, auto-follow-hints-p=t,
compute-hints-in-view-port-p=t from the earlier pre-releases.
Another (default) hinting type is :emacs.")
   (show-hint-scope-p
    nil
    :documentation "This is not exactly necessary, because the default value is NIL already.")))
```
