### ISSUE TITLE
How to make window full screen when launching

### ISSUE THREAD

**Issue by csfreebird** [atlas-engineer/nyxt#548]
Any parameter can be used ?

**Comment by jmercouris** [comment]
I have no idea, it depends on your window manager, operating system, and whether you are using the GTK or PyQT port, you'll have to give us some more information to help you better. Thank you!

**Comment by csfreebird** [comment]
> I have no idea, it depends on your window manager, operating system, and whether you are using the GTK or PyQT port, you'll have to give us some more information to help you better. Thank you!

I am using Ubuntu 18.04 with gnome.

**Comment by jmercouris** [comment]
I'm sorry, I can't help you here, hopefully someone else will chime in!

**Comment by Ambrevar** [comment]
You could add a handler to `*after-init-hook*` that calls `fullscreen-current-window`.

**Comment by jmercouris** [comment]
That's true, it is now possible in that way :-D

**Comment by jmercouris** [comment]
Given that it is now possible, I think we can close this issue.

**Comment by Ambrevar** [comment]
How?

**Comment by jmercouris** [comment]
Invoke full-screen-current-window.

**Comment by Ambrevar** [comment]
In after-init-hook?
