### ISSUE TITLE
Proxy auto-config (PAC) file support

### ISSUE THREAD

**Issue by ghost** [atlas-engineer/nyxt#550]
Since it is a kind of standard supported by major browsers, I think it is worth implementing in next.

**Comment by Ambrevar** [comment]
You are absolutely right!
It should not be to hard to implement, would you be interested in working on a patch?

**Comment by csfreebird** [comment]
I can enable proxy-mode for one buffer, disable proxy-mode for another buffer.
Why we need pac file?

**Comment by Ambrevar** [comment]
A PAC file contains the proxy parameters such as the host, the port, the protocol.

**Comment by lisponly** [comment]
> would you be interested in working on a patch?

No, I just leave a feature request here.

**Comment by aartaka** [comment]
[PAC reference on MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Proxy_servers_and_tunneling/Proxy_Auto-Configuration_PAC_file) is a human-readable description. Good news: it's pretty simple with user-scripts or #2490. Bad news: it's all JS :(
