### ISSUE TITLE
Cannot open Magazines from Magzter.com

### ISSUE THREAD

**Issue by vineethkartha** [atlas-engineer/nyxt#563]
From the website magzter.com I can navigate till a magazine. But then on clicking on the "Read Now" button does not do anything

1. Open Magzter.com
2. Navigate to any of the magazine and click on the "Read Now" button.

**Information**
- OS name+version: Ubuntu 19.10
- Kernel name+version: 5.3.0-29-generic
- Graphics card and driver: Skylake GT2 [HD Graphics 520]
- Desktop environment / Window manager name+version: Gnome
- Next version (from =M-x next-version= or =next --version=): Next 1.3.4
- How you installed Next (Guix pack, package manager, build from source): From the downloads page instructions
- SBCL version (if built from source): SBCL 1.5.5.debian
- WebKitGTK+ / PyQt-Webengine version:

**Comment by jmercouris** [comment]
It seems to be because it requests to open a new tab, and Next does not allow that at the current moment. Thank you for the report!

**Comment by vineethkartha** [comment]
Is this a linitation or is this intended by desing ?

**Comment by jmercouris** [comment]
It is not intended by design :-) we just haven't yet encountered it as a problem.

**Comment by Ambrevar** [comment]
Yes, Next supports new tabs (the limitation was fixed a long time ago).

Can you reproduce with another WebKit-based browser such as Epiphany?

**Comment by jmercouris** [comment]
Yes, I remember the fix, but does it work with a javascript request to open a new tab? Or does it not matter?

**Comment by Ambrevar** [comment]
It should work.

**Comment by vineethkartha** [comment]
> Yes, Next supports new tabs (the limitation was fixed a long time ago). Can you reproduce with another WebKit-based browser such as Epiphany?

I did try this on Epiphany and it works. Epiphany opens a new tab and the magazines open up

**Comment by Ambrevar** [comment]
Hmm... I'll look into it.
@vineethkartha If you are still using 1.3.4, consider updating to 1.5.0, it has lots of fixes and new features!

**Comment by Ambrevar** [comment]
Indeed, I can reproduce.

Now when I try to load https://www.magzter.com it redirects me to
https://www.magzter.com/fr, then https://www.magzter.com/fr/fr, and so
on until it errors on the 20th redirection.

Same with Epiphany.  Something weird with their server (or CloudFront?).

**Comment by Ambrevar** [comment]
Can't reproduce anymore with magzter.
I think the initial issue was due to #768.  Let's keep discussing the issue there.
