### ISSUE TITLE
Implement IBuffer

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#565]
It would be nice to offer an `ibuffer` command that would display the list of buffers in a special web page.
The list could be sorted, filtered, etc.

Finally, every buffer could be switched to.  This last feature requires some sort of HTML/JS <-> Next protocol.

**Comment by jmercouris** [comment]
> This last feature requires some sort of HTML/JS <-> Next protocol.

Absolutely, this is most certainly a prerequisite to that. A good idea!

**Comment by Ambrevar** [comment]
Also see #745.

**Comment by jmercouris** [comment]
Yes, fair enough. This is also not really a *core* priority at the moment. We have plenty of buffer management tools.
