### ISSUE TITLE
(follow-hints) broken in e621

### ISSUE THREAD

**Issue by gravitational-dark-light** [atlas-engineer/nyxt#566]
**Describe the bug**
When I try to use C-g (follow-hint) anywhere in [e621](https://e621.net) the hints show but no prompt follows, and the hints are left in place until reload

![hint-error](https://user-images.githubusercontent.com/8922976/74764301-d78a0300-5257-11ea-86fb-d755f1b5c021.png)
![hint-error-2](https://user-images.githubusercontent.com/8922976/74764382-fab4b280-5257-11ea-854a-d16a0f3f07f3.png)
![hint-error-3](https://user-images.githubusercontent.com/8922976/74764457-20da5280-5258-11ea-9e22-797da94269aa.png)

I **think** there's an issue somewhere in query-hints macro as the follow-hint* functions seems to share it, and it's in charge of getting the input (which never happens)

**Precise recipe to reproduce the issue**

- [go to e621](https://e621.net)
- run C-g

**Information**
- OS name+version: Debian 10 Stretch (Stable) 
- Kernel name+version: Linux 4.9.0.9 amd64
- Graphics card and driver: Intel Q 33 (integrated)
- Desktop environment / Window manager name+version: Stumpwm 19.11
- Next version (from =M-x next-version= or =next --version=): 1.5.0
- How you installed Next (Guix pack, package manager, build from source): Guix
- SBCL version (if built from source):
- WebKitGTK+ / PyQt-Webengine version:

**Comment by chrisboeg** [comment]
I'll take a look tomorrow.

**Comment by gravitational-dark-light** [comment]
oops, debian stable is actually buster. By the way, those screenshots were taken just before the update to 1.5.0 made only hours ago, and I see changes were made to query-hints, but the issue persists

**Comment by gravitational-dark-light** [comment]
Since I mentioned it on #567 I may as well elaborate a little here: whenever I try to use follow-hint* functions on [e621](https://e621.net), next complains about the matches not being a list:

> WARNING:
   Method handler (NEXT::CORE-OBJECT
                   NEXT::BUFFER-JAVASCRIPT-CALL-BACK) signaled an error: The
                                                                         value
                                                                           "[{\"type\": \"link\", \"hint\": \"AB\", \"href\": \"https://e621.net/\", \"body\": \"e621\"}, {\"type\": \"link\", \"hint\": \"AC\", \"href\": \"https://e621.net/user/login?url=%2Fpost%2Fshow%2F2107872\", \"body\": \"Login/Signup\"}, {\"type\": \"link\", \"hint\": \"AD\", \"href\": \"https://e621.net/post/index\", \"body\": \"Posts\"}, {\"type\": \"link\", \"hint\": \"AE\", \"href\": \"https://e621.net/comment/index\", \"body\": \"Comments\"}, {\"type\": \"link\", \"hint\": \"AF\", \"href\": \"https://e621.net/note/index\", \"body\": \"Notes\"}, {\"type\": \"link\", \"hint\": \"AG\", \"href\": \"https://e621.net/artist/index\", \"body\": \"Artists\"}, {\"type\": \"link\", \"hint\": \"AH\", \"href\": \"https://e621.net/tag/index\", \"body\": \"Tags\"}, {\"type\": \"link\", \"hint\": \"AI\", \"href\": \"https://e621.net/pool/index\", \"body\": \"Pools\"}, {\"type\": \"link\", \"hint\": \"AJ\", \"href\": \"https://e621.net/set/index\", \"body\": \"Sets\"}, {\"type\": \"link\", \"hint\": \"AK\", \"href\": \"https://e621.net/blip/index\", \"body\": \"Blips\"}, {\"type\": \"link\", \"hint\": \"AL\", \"href\": \"https://e621.net/wiki/show?title=help%3Ahome\", \"body\": \"Wiki\"}, {\"type\": \"link\", \"hint\": \"AM\", \"href\": \"https://e621.net/static/discord\", \"body\": \"Chat\"}, {\"type\": \"link\", \"hint\": \"AN\", \"href\": \"https://e621.net/forum/index\", \"body\": \"Forum\"}, {\"type\": \"link\", \"hint\": \"AO\", \"href\": \"https://e621.net/static/contact\", \"body\": \"Contact\"}, {\"type\": \"link\", \"hint\": \"AP\", \"href\": \"https://e621.net/static/more\", \"body\": \"»\"}, {\"type\": \"link\", \"hint\": \"AQ\", \"href\": \"https://e621.net/post/index\", \"body\": \"List\"}, {\"type\": \"link\", \"hint\": \"AR\", \"href\": \"https://e621.net/post/upload\", \"body\": \"Upload\"}, {\"type\": \"link\", \"hint\": \"AS\", \"href\": \"https://e621.net/post/m\", \"body\": \"Mobile\"}, {\"type\": \"link\", \"hint\": \"AT\", \"href\": \"https://e621.net/help/favorites\", \"body\": \"Favorites\"}, {\"type\": \"link\", \"hint\": \"AU\", \"href\": \"https://e621.net/post/show/2107872#\", \"body\": \"Blacklist\"}, {\"type\": \"link\", \"hint\": \"AV\", \"href\": \"https://e621.net/post/popular_by_day\", \"body\": \"Popular\"}, {\"type\": \"link\", \"hint\": \"AW\", \"href\": \"https://e621.net/post/random\", \"body\": \"Random\"}, {\"type\": \"link\", \"hint\": \"AX\", \"href\": \"https://e621.net/post_tag_history/index\", \"body\": \"Tag History\"}, {\"type\": \"link\", \"hint\": \"AY\", \"href\": \"https://e621.net/post_desc_history/index\", \"body\": \"Desc. History\"}, {\"type\": \"link\", \"hint\": \"AZ\", \"href\": \"https://e621.net/post_flag_history/index\", \"body\": \"Flag History\"}, {\"type\": \"link\", \"hint\": \"BA\", \"href\": \"https://e621.net/post/recent_approvals\", \"body\": \"Recent approvals\"}, {\"type\": \"link\", \"hint\": \"BB\", \"href\": \"https://e621.net/help/posts\", \"body\": \"Help\"}, {\"type\": \"link\", \"hint\": \"BC\", \"href\": \"https://e621.net/news\", \"body\": \"News\"}, {\"type\": \"link\", \"hint\": \"BD\", \"href\": \"https://e621.net/static/discord\", \"body\": \"come talk to us\"}, {\"type\": \"link\", \"hint\": \"BE\", \"href\": \"https://e621.net/forum/show/283533\", \"body\": \"found here\"}, {\"type\": \"link\", \"hint\": \"BF\", \"href\": \"https://e621.net/forum/show/283537\", \"body\": \"click here\"}, {\"type\": \"link\", \"hint\": \"BG\", \"href\": \"https://e621.net/forum/show/283540\", \"body\": \"here\"}, {\"type\": \"link\", \"hint\": \"BH\", \"href\": \"https://e621.net/static/contact\", \"body\": \"Contact page\"}, {\"type\": \"link\", \"hint\": \"BI\", \"href\": \"https://e621.net/forum/show/10410\", \"body\": \"Click here!\"}, {\"type\": \"link\", \"hint\": \"BJ\", \"href\": \"https://e621.net/post/show/2107872#\", \"body\": \"View original\"}, {\"type\": \"link\", \"hint\": \"BK\", \"href\": \"https://e621.net/post/show/2107872#\", \"body\": \"Hide this message\"}, {\"type\": \"link\", \"hint\": \"BL\", \"href\": \"https://e621.net/user/edit\", \"body\": \"user settings\"}, {\"type\": \"link\", \"hint\": \"BM\", \"href\": \"https://e621.net/help/cheatsheet\", \"body\": \"(Search Help)\"}, {\"type\": \"link\", \"hint\": \"BN\", \"href\": \"https://e621.net/artist/show?name=conditional_dnp\", \"body\": \"?\"}, {\"type\": \"link\", \"hint\": \"BO\", \"href\": \"https://e621.net/post/search?tags=conditional_dnp\", \"body\": \"conditional dnp\"}, {\"type\": \"link\", \"hint\": \"BP\", \"href\": \"https://e621.net/artist/show?name=teranen\", \"body\": \"?\"}, {\"type\": \"link\", \"hint\": \"BQ\", \"href\": \"https://e621.net/post/search?tags=teranen\", \"body\": \"teranen\"}, {\"type\": \"link\", \"hint\": \"BR\", \"href\": \"https://e621.net/wiki/show?title=nami_%28teranen%29\", \"body\": \"?\"}, {\"type\": \"link\", \"hint\": \"BS\", \"href\": \"https://e621.net/post/search?tags=nami_%28teranen%29\", \"body\": \"nami (teranen)\"}, {\"type\": \"link\", \"hint\": \"BT\", \"href\": \"https://e621.net/wiki/show?title=cetacean\", \"body\": \"?\"}, {\"type\": \"link\", \"hint\": \"BU\", \"href\": \"https://e621.net/post/search?tags=cetacean\", \"body\": \"cetacean\"}, {\"type\": \"link\", \"hint\": \"BV\", \"href\": \"https://e621.net/wiki/show?title=delphinoid\", \"body\": \"?\"}, {\"type\": \"link\", \"hint\": \"BW\", \"href\": \"https://e621.net/post/search?tags=delphinoid\", \"body\": \"delphinoid\"}, {\"type\": \"link\", \"hint\": \"BX\", \"href\": \"https://e621.net/wiki/show?title=dragon\", \"body\": \"?\"}, {\"type\": \"link\", \"hint\": \"BY\", \"href\": \"https://e621.net/post/search?tags=dragon\", \"body\": \"dragon\"}, {\"type\": \"link\", \"hint\": \"BZ\", \"href\": \"https://e621.net/wiki/show?title=hybrid\", \"body\": \"?\"}, {\"type\": \"link\", \"hint\": \"CA\", \"href\": \"https://e621.net/post/search?tags=hybrid\", \"body\": \"hybrid\"}, {\"type\": \"link\", \"hint\": \"CB\", \"href\": \"https://e621.net/wiki/show?title=mammal\", \"body\": \"?\"}, {\"type\": \"link\", \"hint\": \"CC\", \"href\": \"https://e621.net/post/search?tags=mammal\", \"body\": \"mammal\"}, {\"type\": \"link\", \"hint\": \"CD\", \"href\": \"https://e621.net/wiki/show?title=marine\", \"body\": \"?\"}, {\"type\": \"link\", \"hint\": \"CE\", \"href\": \"https://e621.net/post/search?tags=marine\", \"body\": \"marine\"}, {\"type\": \"link\", \"hint\": \"CF\", \"href\": \"https://e621.net/wiki/show?title=oceanic_dolphin\", \"body\": \"?\"}, {\"type\": \"link\", \"hint\": \"CG\", \"href\": \"https://e621.net/post/search?tags=oceanic_dolphin\", \"body\": \"oceanic dolphin\"}, {\"type\": \"link\", \"hint\": \"CH\", \"href\": \"https://e621.net/wiki/show?title=orca\", \"body\": \"?\"}, {\"type\": \"link\", \"hint\": \"CI\", \"href\": \"https://e621.net/post/search?tags=orca\", \"body\": \"orca\"}, {\"type\": \"link\", \"hint\": \"CJ\", \"href\": \"https://e621.net/wiki/show?title=toothed_whale\", \"body\": \"?\"}, {\"type\": \"link\", \"hint\": \"CK\", \"href\": \"https://e621.net/post/search?tags=toothed_whale\", \"body\": \"toothed whale\"}, {\"type\": \"link\", \"hint\": \"CL\", \"href\": \"https://e621.net/wiki/show?title=2020\", \"body\": \"?\"}, {\"type\": \"link\", \"hint\": \"CM\", \"href\": \"https://e621.net/post/search?tags=2020\", \"body\": \"2020\"}, {\"type\": \"link\", \"hint\": \"CN\", \"href\": \"https://e621.net/wiki/show?title=5_fingers\", \"body\": \"?\"}, {\"type\": \"link\", \"hint\": \"CO\", \"href\": \"https://e621.net/post/search?tags=5_fingers\", \"body\": \"5 fingers\"}, {\"type\": \"link\", \"hint\": \"CP\", \"href\": \"https://e621.net/wiki/show?title=anthro\", \"body\": \"?\"}, {\"type\": \"link\", \"hint\": \"CQ\", \"href\": \"https://e621.net/post/search?tags=anthro\", \"body\": \"anthro\"}, {\"type\": \"link\", \"hint\": \"CR\", \"href\": \"https://e621.net/wiki/show?title=clothed\", \"body\": \"?\"}, {\"type\": \"link\", \"hint\": \"CS\", \"href\": \"https://e621.net/post/search?tags=clothed\", \"body\": \"clothed\"}, {\"type\": \"link\", \"hint\": \"CT\", \"href\": \"https://e621.net/wiki/show?title=clothing\", \"body\": \"?\"}, {\"type\": \"link\", \"hint\": \"CU\", \"href\": \"https://e621.net/post/search?tags=clothing\", \"body\": \"clothing\"}, {\"type\": \"link\", \"hint\": \"CV\", \"href\": \"https://e621.net/wiki/show?title=digital_media_%28artwork%29\", \"body\": \"?\"}, {\"type\": \"link\", \"hint\": \"CW\", \"href\": \"https://e621.net/post/search?tags=digital_media_%28artwork%29\", \"body\": \"digital media (artwork)\"}, {\"type\": \"link\", \"hint\": \"CX\", \"href\": \"https://e621.net/wiki/show?title=eyebrows\", \"body\": \"?\"}, {\"type\": \"link\", \"hint\": \"CY\", \"href\": \"https://e621.net/post/search?tags=eyebrows\", \"body\": \"eyebrows\"}, {\"type\": \"link\", \"hint\": \"CZ\", \"href\": \"https://e621.net/wiki/show?title=eyelashes\", \"body\": \"?\"}, {\"type\": \"link\", \"hint\": \"DA\", \"href\": \"https://e621.net/post/search?tags=eyelashes\", \"body\": \"eyelashes\"}, {\"type\": \"link\", \"hint\": \"DB\", \"href\": \"https://e621.net/wiki/show?title=female\", \"body\": \"?\"}, {\"type\": \"link\", \"hint\": \"DC\", \"href\": \"https://e621.net/post/search?tags=female\", \"body\": \"female\"}, {\"type\": \"link\", \"hint\": \"DD\", \"href\": \"https://e621.net/wiki/show?title=fingers\", \"body\": \"?\"}, {\"type\": \"link\", \"hint\": \"DE\", \"href\": \"https://e621.net/post/search?tags=fingers\", \"body\": \"fingers\"}, {\"type\": \"link\", \"hint\": \"DF\", \"href\": \"https://e621.net/wiki/show?title=hair\", \"body\": \"?\"}, {\"type\": \"link\", \"hint\": \"DG\", \"href\": \"https://e621.net/post/search?tags=hair\", \"body\": \"hair\"}, {\"type\": \"link\", \"hint\": \"DH\", \"href\": \"https://e621.net/wiki/show?title=horn\", \"body\": \"?\"}, {\"type\": \"link\", \"hint\": \"DI\", \"href\": \"https://e621.net/post/search?tags=horn\", \"body\": \"horn\"}, {\"type\": \"link\", \"hint\": \"DJ\", \"href\": \"https://e621.net/wiki/show?title=reaction_image\", \"body\": \"?\"}, {\"type\": \"link\", \"hint\": \"DK\", \"href\": \"https://e621.net/post/search?tags=reaction_image\", \"body\": \"reaction image\"}, {\"type\": \"link\", \"hint\": \"DL\", \"href\": \"https://e621.net/wiki/show?title=simple_background\", \"body\": \"?\"}, {\"type\": \"link\", \"hint\": \"DM\", \"href\": \"https://e621.net/post/search?tags=simple_background\", \"body\": \"simple background\"}, {\"type\": \"link\", \"hint\": \"DN\", \"href\": \"https://e621.net/wiki/show?title=solo\", \"body\": \"?\"}, {\"type\": \"link\", \"hint\": \"DO\", \"href\": \"https://e621.net/post/search?tags=solo\", \"body\": \"solo\"}, {\"type\": \"link\", \"hint\": \"DP\", \"href\": \"https://e621.net/wiki/show?title=teeth\", \"body\": \"?\"}, {\"type\": \"link\", \"hint\": \"DQ\", \"href\": \"https://e621.net/post/search?tags=teeth\", \"body\": \"teeth\"}, {\"type\": \"link\", \"hint\": \"DR\", \"href\": \"https://www.furaffinity.net/view/34481351/\", \"body\": \"furaffinity.net/view/34481351\"}, {\"type\": \"link\", \"hint\": \"DS\", \"href\": \"https://e621.net/post/index?tags=date%3A2020-01-06\", \"body\": \"1 month ago\"}, {\"type\": \"link\", \"hint\": \"DT\", \"href\": \"https://e621.net/user/show/169756\", \"body\": \"Millcore\"}, {\"type\": \"link\", \"hint\": \"DU\", \"href\": \"https://static1.e621.net/data/da/74/da7422d3be2cd644d24a1f72bb4f18de.png\", \"body\": \"723x930 (366.3 KB)\"}, {\"type\": \"link\", \"hint\": \"DV\", \"href\": \"https://e621.net/user/show/402428\", \"body\": \"~Meouchstick~\"}, {\"type\": \"link\", \"hint\": \"DW\", \"href\": \"https://e621.net/user/show/411602\", \"body\": \"RestWereTaken\"}, {\"type\": \"link\", \"hint\": \"DX\", \"href\": \"https://e621.net/user/show/104007\", \"body\": \"eiffelwong1\"}, {\"type\": \"link\", \"hint\": \"DY\", \"href\": \"https://e621.net/user/show/215571\", \"body\": \"IIDeeK\"}, {\"type\": \"link\", \"hint\": \"DZ\", \"href\": \"https://e621.net/user/show/170225\", \"body\": \"Meshow\"}, {\"type\": \"link\", \"hint\": \"EA\", \"href\": \"https://e621.net/user/show/315068\", \"body\": \"Ringdingding\"}, {\"type\": \"link\", \"hint\": \"EB\", \"href\": \"https://e621.net/user/show/147577\", \"body\": \"Punkratt\"}, {\"type\": \"link\", \"hint\": \"EC\", \"href\": \"https://e621.net/user/show/451767\", \"body\": \"Nonr\"}, {\"type\": \"link\", \"hint\": \"ED\", \"href\": \"https://e621.net/user/show/435964\", \"body\": \"blossomingRuin\"}, {\"type\": \"link\", \"hint\": \"EE\", \"href\": \"https://e621.net/user/show/337858\", \"body\": \"SSphiinxx\"}, {\"type\": \"link\", \"hint\": \"EF\", \"href\": \"https://e621.net/user/show/379673\", \"body\": \"NICKNAME\"}, {\"type\": \"link\", \"hint\": \"EG\", \"href\": \"https://e621.net/user/show/134552\", \"body\": \"80fordjeep\"}, {\"type\": \"link\", \"hint\": \"EH\", \"href\": \"https://e621.net/user/show/322810\", \"body\": \"hiroto\"}, {\"type\": \"link\", \"hint\": \"EI\", \"href\": \"https://e621.net/user/show/268431\", \"body\": \"kawaiibelbell\"}, {\"type\": \"link\", \"hint\": \"EJ\", \"href\": \"https://e621.net/user/show/8877\", \"body\": \"Marig_A_AeroWing\"}, {\"type\": \"link\", \"hint\": \"EK\", \"href\": \"https://e621.net/user/show/289452\", \"body\": \"F4pc4t\"}, {\"type\": \"link\", \"hint\": \"EL\", \"href\": \"https://e621.net/user/show/185327\", \"body\": \"crisalis101\"}, {\"type\": \"link\", \"hint\": \"EM\", \"href\": \"https://e621.net/user/show/424361\", \"body\": \"friccinhecc21\"}, {\"type\": \"link\", \"hint\": \"EN\", \"href\": \"https://e621.net/user/show/333476\", \"body\": \"Vinchu\"}, {\"type\": \"link\", \"hint\": \"EO\", \"href\": \"https://e621.net/user/show/263796\", \"body\": \"Skyborn\"}, {\"type\": \"link\", \"hint\": \"EP\", \"href\": \"https://e621.net/user/show/390623\", \"body\": \"Neonflux\"}, {\"type\": \"link\", \"hint\": \"EQ\", \"href\": \"https://e621.net/user/show/256432\", \"body\": \"Rakdem\"}, {\"type\": \"link\", \"hint\": \"ER\", \"href\": \"https://e621.net/user/show/55905\", \"body\": \"D4rk\"}, {\"type\": \"link\", \"hint\": \"ES\", \"href\": \"https://e621.net/user/show/216839\", \"body\": \"ShadowDragon87\"}, {\"type\": \"link\", \"hint\": \"ET\", \"href\": \"https://e621.net/user/show/298983\", \"body\": \"Franco731\"}, {\"type\": \"link\", \"hint\": \"EU\", \"href\": \"https://e621.net/user/show/436114\", \"body\": \"Azure_Fur\"}, {\"type\": \"link\", \"hint\": \"EV\", \"href\": \"https://e621.net/user/show/356807\", \"body\": \"Rocklessfort\"}, {\"type\": \"link\", \"hint\": \"EW\", \"href\": \"https://e621.net/user/show/325176\", \"body\": \"Kietro\"}, {\"type\": \"link\", \"hint\": \"EX\", \"href\": \"https://e621.net/user/show/55553\", \"body\": \"DreitTheDragon\"}, {\"type\": \"link\", \"hint\": \"EY\", \"href\": \"https://e621.net/user/show/273527\", \"body\": \"dody221\"}, {\"type\": \"link\", \"hint\": \"EZ\", \"href\": \"https://e621.net/user/show/433064\", \"body\": \"john_sludge\"}, {\"type\": \"link\", \"hint\": \"FA\", \"href\": \"https://e621.net/user/show/214301\", \"body\": \"dracotay\"}, {\"type\": \"link\", \"hint\": \"FB\", \"href\": \"https://e621.net/user/show/298200\", \"body\": \"idliketobeameme\"}, {\"type\": \"link\", \"hint\": \"FC\", \"href\": \"https://e621.net/user/show/119771\", \"body\": \"afterburn609\"}, {\"type\": \"link\", \"hint\": \"FD\", \"href\": \"https://e621.net/user/show/155390\", \"body\": \"brocksamsonakatom\"}, {\"type\": \"link\", \"hint\": \"FE\", \"href\": \"https://e621.net/user/show/153463\", \"body\": \"hiroseth\"}, {\"type\": \"link\", \"hint\": \"FF\", \"href\": \"https://e621.net/user/show/127822\", \"body\": \"doctor-wd-mlp\"}, {\"type\": \"link\", \"hint\": \"FG\", \"href\": \"https://e621.net/user/show/371699\", \"body\": \"theantidruid\"}, {\"type\": \"link\", \"hint\": \"FH\", \"href\": \"https://e621.net/user/show/338533\", \"body\": \"Some_Rand0m_Guy\"}, {\"type\": \"link\", \"hint\": \"FI\", \"href\": \"https://e621.net/user/show/342460\", \"body\": \"Kcu\"}, {\"type\": \"link\", \"hint\": \"FJ\", \"href\": \"https://e621.net/user/show/169225\", \"body\": \"Yeyinde\"}, {\"type\": \"link\", \"hint\": \"FK\", \"href\": \"https://e621.net/user/show/144530\", \"body\": \"roaming_free\"}, {\"type\": \"link\", \"hint\": \"FL\", \"href\": \"https://e621.net/user/show/121748\", \"body\": \"tomaej\"}, {\"type\": \"link\", \"hint\": \"FM\", \"href\": \"https://e621.net/user/show/346960\", \"body\": \"FoxPlusPlus\"}, {\"type\": \"link\", \"hint\": \"FN\", \"href\": \"https://e621.net/user/show/37060\", \"body\": \"Toboen\"}, {\"type\": \"link\", \"hint\": \"FO\", \"href\": \"https://e621.net/user/show/65794\", \"body\": \"lhmetroidlover2\"}, {\"type\": \"link\", \"hint\": \"FP\", \"href\": \"https://e621.net/user/show/387262\", \"body\": \"BluestLight\"}, {\"type\": \"link\", \"hint\": \"FQ\", \"href\": \"https://e621.net/user/show/237576\", \"body\": \"Shadowfurry123\"}, {\"type\": \"link\", \"hint\": \"FR\", \"href\": \"https://e621.net/user/show/16626\", \"body\": \"Skarovich\"}, {\"type\": \"link\", \"hint\": \"FS\", \"href\": \"https://e621.net/user/show/3977\", \"body\": \"Clueless23\"}, {\"type\": \"link\", \"hint\": \"FT\", \"href\": \"https://e621.net/user/show/256352\", \"body\": \"Muuna\"}, {\"type\": \"link\", \"hint\": \"FU\", \"href\": \"https://e621.net/user/show/334789\", \"body\": \"-I0N\"}, {\"type\": \"link\", \"hint\": \"FV\", \"href\": \"https://e621.net/user/show/41142\", \"body\": \"worgenwolf\"}, {\"type\": \"link\", \"hint\": \"FW\", \"href\": \"https://e621.net/post/show/2107872#\", \"body\": \"47 more\"}, {\"type\": \"link\", \"hint\": \"FX\", \"href\": \"https://e621.net/post_tag_history/index?post_id=2107872\", \"body\": \"Tags\"}, {\"type\": \"link\", \"hint\": \"FY\", \"href\": \"https://e621.net/post_desc_history/index?post_id=2107872\", \"body\": \"Description\"}, {\"type\": \"link\", \"hint\": \"FZ\", \"href\": \"https://e621.net/note/history?post_id=2107872\", \"body\": \"Notes\"}, {\"type\": \"link\", \"hint\": \"GA\", \"href\": \"https://e621.net/post_flag_history/index?post_id=2107872\", \"body\": \"Flags\"}, {\"type\": \"link\", \"hint\": \"GB\", \"href\": \"https://e621.net/post/show/2107871\", \"body\": \"Previous\"}, {\"type\": \"link\", \"hint\": \"GC\", \"href\": \"https://e621.net/post/random\", \"body\": \"Random\"}, {\"type\": \"link\", \"hint\": \"GD\", \"href\": \"https://e621.net/post/show/2107873\", \"body\": \"Next\"}, {\"type\": \"link\", \"hint\": \"GE\", \"href\": \"https://e621.net/set/index?post_id=2107872\", \"body\": \"Sets with this post\"}, {\"type\": \"link\", \"hint\": \"GF\", \"href\": \"https://www.google.com/searchbyimage?image_url=https://static1.e621.net/data/preview/da/74/da7422d3be2cd644d24a1f72bb4f18de.jpg\", \"body\": \"Reverse Google Search\"}, {\"type\": \"link\", \"hint\": \"GG\", \"href\": \"http://saucenao.com/search.php?url=https://static1.e621.net/data/preview/da/74/da7422d3be2cd644d24a1f72bb4f18de.jpg\", \"body\": \"Reverse SauceNAO Search\"}, {\"type\": \"link\", \"hint\": \"GH\", \"href\": \"http://iqdb.harry.lu/?url=https://static1.e621.net/data/preview/da/74/da7422d3be2cd644d24a1f72bb4f18de.jpg\", \"body\": \"Reverse harry.lu Search\"}, {\"type\": \"link\", \"hint\": \"GI\", \"href\": \"https://inkbunny.net/search_process.php?text=da7422d3be2cd644d24a1f72bb4f18de&md5=yes\", \"body\": \"Inkbunny MD5 Search\"}, {\"type\": \"link\", \"hint\": \"GJ\", \"href\": \"https://ads.dragonfru.it/www/delivery/ck.php?oaparams=2__bannerid=657__zoneid=1__cb=635c14e397__oadest=https%3A%2F%2Fbad-dragon.com%2F%3Faffid%3D135%26utm_source%3De621%26utm_medium%3Dbanner%26utm_campaign%3De621%2520remnant\", \"body\": \"<img src=\\\"https://ads.dragonfru.it/www/images/07819393c2efa88580a3a8510ac1f517.gif\\\" width=\\\"728\\\" height=\\\"90\\\" alt=\\\"\\\" title=\\\"\\\" border=\\\"0\\\">\"}, {\"type\": \"link\", \"hint\": \"GK\", \"href\": \"\", \"body\": \"\"}, {\"type\": \"link\", \"hint\": \"GL\", \"href\": \"https://static1.e621.net/data/da/74/da7422d3be2cd644d24a1f72bb4f18de.png\", \"body\": \"Download\"}, {\"type\": \"link\", \"hint\": \"GM\", \"href\": \"https://static1.e621.net/data/da/74/da7422d3be2cd644d24a1f72bb4f18de.png\", \"body\": \"Full Size\"}, {\"type\": \"link\", \"hint\": \"GN\", \"href\": \"\", \"body\": \"\"}, {\"type\": \"link\", \"hint\": \"GO\", \"href\": \"https://e621.net/wiki/show?title=howto%3Atag\", \"body\": \"how to tag guide\"}, {\"type\": \"link\", \"hint\": \"GP\", \"href\": \"https://e621.net/help/ratings\", \"body\": \"help\"}, {\"type\": \"link\", \"hint\": \"GQ\", \"href\": \"https://e621.net/help/tags\", \"body\": \"Tagging help\"}, {\"type\": \"link\", \"hint\": \"GR\", \"href\": \"https://e621.net/post/show/2107872#\", \"body\": \"Related tags\"}, {\"type\": \"link\", \"hint\": \"GS\", \"href\": \"https://e621.net/post/show/2107872#\", \"body\": \"Related artists\"}, {\"type\": \"link\", \"hint\": \"GT\", \"href\": \"https://e621.net/post/show/2107872#\", \"body\": \"Related characters\"}, {\"type\": \"link\", \"hint\": \"GU\", \"href\": \"https://e621.net/post/show/2107872#\", \"body\": \"Related copyrights\"}, {\"type\": \"link\", \"hint\": \"GV\", \"href\": \"https://e621.net/post/show/2107872#\", \"body\": \"Find artist\"}, {\"type\": \"link\", \"hint\": \"GW\", \"href\": \"\", \"body\": \"\"}, {\"type\": \"link\", \"hint\": \"GX\", \"href\": \"\", \"body\": \"\"}, {\"type\": \"link\", \"hint\": \"GY\", \"href\": \"https://e621.net/user/show/214301\", \"body\": \"dracotay\"}, {\"type\": \"link\", \"hint\": \"GZ\", \"href\": \"https://e621.net/comment/show/4791180\", \"body\": \"1 month ago\"}, {\"type\": \"link\", \"hint\": \"HA\", \"href\": \"https://e621.net/post/show/2126717\", \"body\": \"<img alt=\\\"2020 ambiguous_gender claws digital_media_(artwork) dragon feral hi_res horn isvoc membrane_(anatomy) membranous_wings model_sheet scales scalie solo spines western_dragon wings\\n\\nRating: Safe\\nScore: 25\\nUser: Millcore\\nDate: January 24, 2020\\\" class=\\\"preview avatar\\\" height=\\\"84\\\" id=\\\"i2126717\\\" src=\\\"https://static1.e621.net/data/preview/1e/ba/1eba4184f3abc783828a22962ca1a0f3.jpg\\\" title=\\\"2020 ambiguous_gender claws digital_media_(artwork) dragon feral hi_res horn isvoc membrane_(anatomy) membranous_wings model_sheet scales scalie solo spines western_dragon wings\\n\\nRating: Safe\\nScore: 25\\nUser: Millcore\\nDate: January 24, 2020\\\" width=\\\"150\\\" data-original=\\\"https://static1.e621.net/data/preview/1e/ba/1eba4184f3abc783828a22962ca1a0f3.jpg\\\">\"}, {\"type\": \"link\", \"hint\": \"HB\", \"href\": \"https://e621.net/user/login?url=%2Fpost%2Fshow%2F2107872\", \"body\": \"Login to respond »\"}]"

                                                                         is not
                                                                         of
                                                                         type
                                                                           LIST.

Which only happens on that website

**Comment by gravitational-dark-light** [comment]
search-buffer(s) produces a similar error on that website, and I just realized it doesn't return the matches to the minibuffer there, nor does it scroll to the current match, it just places the hints, and then modifies those elements if I make further searchs without clearing the hints first

> WARNING:
   Method handler (NEXT::CORE-OBJECT
                   NEXT::BUFFER-JAVASCRIPT-CALL-BACK) signaled an error: The
                                                                         value
                                                                           "[{\"type\": \"match\", \"identifier\": 1, \"body\": \"nami (teranen)\"}, {\"type\": \"match\", \"identifier\": 2, \"body\": \" fingers hair horn hybrid mammal marine nami_(teranen) oceanic_dolphin orca reaction_image simple_background solo teeth teranen toothed_whale \"}]"

                                                                         is not
                                                                         of
                                                                         type
                                                                           LIST.

**Comment by Ambrevar** [comment]
@chrisboeg Thanks for looking into this.  Keep in mind that instead of pure Javascript we will probably leverage the renderer (e.g. WebKit) soon when #558 is merged :)

**Comment by jmercouris** [comment]
I don't think we'll be able to utilize the renderer for all of the task, but maybe for the rendering of the actual link hints themselves. As per the error, it seems that the list is malformed because we are not properly sanitizing the text that appears in the list returned by javascript.

**Comment by chrisboeg** [comment]
I will work on this, however I was sick yesterday and are still not feeling all too well, so except if anybody else want to do it before, I'll work on this probably tomorrow at the soonest.

**Comment by Ambrevar** [comment]
No problem, take your time and happy recovery!

**Comment by gravitational-dark-light** [comment]
**Update:**  The page has been revamped today, and I can no longer reproduce

I may have to close this
