### ISSUE TITLE
search-over-buffers corrupt matched elements

### ISSUE THREAD

**Issue by gravitational-dark-light** [atlas-engineer/nyxt#567]
**Describe the bug**
When I use **(C-s s)** to do incremental search, already matched elements end getting their contents set to undefined unless I quit the search and then manually clear the hints with **(C-s k)**

I experimented a bit, and so far I know that:

- Already matched elements gets altered as soon as I modify the query
- Exiting the search, then making another without clearing the hints first still modify the matched elements
- Does not seems to affect the marked elements left with hints from bug #566 in e621
- On [e621](https://e621.net) next makes a complain not unlike the one from using follow-hint* there, but unlike that function, search-buffer(s) doesn't seem to be affected

Some pictures:

![search-error](https://user-images.githubusercontent.com/8922976/74808176-a5f95200-52c0-11ea-9266-e5f136c9bf66.png)
![search-error-2](https://user-images.githubusercontent.com/8922976/74808173-a560bb80-52c0-11ea-8f5a-511c78aff9d7.png)
![search-error-3](https://user-images.githubusercontent.com/8922976/74808172-a42f8e80-52c0-11ea-9e1c-395409caf55a.png)
![search-error-4](https://user-images.githubusercontent.com/8922976/74808171-a2fe6180-52c0-11ea-8f36-852bedfde203.png)
![search-error-5](https://user-images.githubusercontent.com/8922976/74808169-a1cd3480-52c0-11ea-8d23-d90c7f5a2e12.png)
![search-error-6](https://user-images.githubusercontent.com/8922976/74808167-a1349e00-52c0-11ea-9f7c-04f3228df2f5.png)
![search-error-7](https://user-images.githubusercontent.com/8922976/74808163-9b3ebd00-52c0-11ea-972a-e22d7423713d.png)

**Precise recipe to reproduce the issue**
1. Do **(C-s s)** 
2. Match some elements first
3. Modify the query with previous matches around

**Information**
- OS name+version: Debian 10 Buster (Stable)
- Kernel name+version: Linux 4.9.0-9 amd64
- Graphics card and driver: Intel Q 33 (Integrated)
- Desktop environment / Window manager name+version: Stumpwm 19.11
- Next version (from =M-x next-version= or =next --version=): 1.5.0
- How you installed Next (Guix pack, package manager, build from source): Guix package
- SBCL version (if built from source):
- WebKitGTK+ / PyQt-Webengine version:

**Comment by gravitational-dark-light** [comment]
After some experimentation I finally managed to spot the exact issue:

search-over-buffer uses match-completion-function for the completions, which in turn defers to query-buffer to get the matches from the page

the problem is that query-buffer defines a bunch of JS variables and functions on each call before actually getting the matches, including the variable where the original nodes are stored, and from where they are restored afterwards, just prior to a new search, except those nodes are now lost as **query-buffer redefines the global variable long before then**, so the matching nodes are replaced with `undefined` instead, for that is what is pulled from the object (the nodes aren't there anymore)

**Comment by Ambrevar** [comment]
Sorry for not answering earlier: I can't seem to reproduce your issue.

- I search "foo": all "foo"s in the buffer gets highlighted.
- I search "bar": all "foo"s are no more highlighted and all "bar"s are.

Can you specify what you expect and what you get instead?

**Comment by jmercouris** [comment]
I think this can happen when searching multiple buffers at the same time, I’m not sure though, I’ll have to test later.

**Comment by jmercouris** [comment]
I'm also unable to reproduce, though looking at the pull request, I definitely see how it is possible for it to occur. I've not expanded out defvar in parenscript to see what it actually does though, I think it may already avoid reinitialization (as one would expect).

**Comment by gravitational-dark-light** [comment]
> Sorry for not answering earlier: I can't seem to reproduce your issue.
> 
>     * I search "foo": all "foo"s in the buffer gets highlighted.
> 
>     * I search "bar": all "foo"s are no more highlighted and all "bar"s are.
> 
> 
> Can you specify what you expect and what you get instead?

Each time you type in the search minibuffer (and the query is 3 letters or longer) the whole page is combed, for matches, and whenever a text node who does match is found, that node is replaced, with a couple of `span` elements and the original text node is stored on a `NODES` global variable

Now, what happens when you keep typing? the variable is _redefined_ and the original text nodes are _lost_, then later on, just before the search is updated, an attempt to restore the original text nodes is made

But those nodes doesn't exist anymore so our previous results magically transforms into `undefined` as seen in the images

**Comment by gravitational-dark-light** [comment]
> I'm also unable to reproduce, though looking at the pull request, I definitely see how it is possible for it to occur. I've not expanded out defvar in parenscript to see what it actually does though, I think it may already avoid reinitialization (as one would expect).

parenscript translates` defvar` into `var`, which in fact behaves more like `defparameter`, unconditionally redefining the variable each time, or at least that's what happens in next and waterfox clasic

If you expand query-buffer to JS and eval the whole thing with a different query each time, the previous matches get corrupted because the JS function `removeSearchNodes` can't find the originals in `NODES`

**Comment by jmercouris** [comment]
Thank you for following up on this, I will take a look and see if I can reproduce this. I also seem to recall that parenscript gives unique ids to each variable on instantiation or so. There is something more to this, once again thank you for your thorough report.

**Comment by Ambrevar** [comment]
Is this fixed?

**Comment by jmercouris** [comment]
I don't think it was ever broken. I do not believe we should merge this PR in.

**Comment by jmercouris** [comment]
Sorry, I mean the issue is fixed, yes :-)

**Comment by jmercouris** [comment]
Correct. It is no longer an issue. I was referring to the PR: https://github.com/atlas-engineer/nyxt/pull/607 which has already been closed. Sorry for the confusion!
