### ISSUE TITLE
follow hint misses links in pleroma

### ISSUE THREAD

**Issue by parisni** [atlas-engineer/nyxt#574]
several links within pleroma website  such:
- answer
- retoots
- favorite

are not detected by follow-hint

**Information**
- OS nixos:
- Next version 1.4.0:

**Comment by Ambrevar** [comment]
Yes, this is a known issue.
Maybe the new architecture on the "ffi" branch will allow us to fix it.

**Comment by jmercouris** [comment]
I just checked pleroma, they appear to be ordinary divs and spans with onclick listeners. This seems to contradict basic web design, I don't know if we will ever support this case.

**Comment by aadcg** [comment]
@parisni feel free to re-open if this is still an issue.
