### ISSUE TITLE
Move buffer and window classes + methods to their respective files

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#581]
Current `browser.lisp` is huge and cluttered with definitions for `buffer` and `window`.  It would make more sense and it would probably make it easier to find our way around if those definitions were move to `buffer.lisp` and `window.lisp`.

Thoughts?

**Comment by jmercouris** [comment]
Agreed!

**Comment by Ambrevar** [comment]
What about moving the proxy code to a separate file? Say buffer-proxy.lisp.
We also have quite a few functions that relate to the request-resource-hook. We could also move these to a separate file, say buffer-request.lisp.
This way we would have all buffer related functions grouped in the buffer*.lisp files.

**Comment by jmercouris** [comment]
Wait a minute, didn't you say the exact same thing in the pull request :-D?

**Comment by Ambrevar** [comment]
I did, I'm leaving this here so that we don't forget about it ;)

**Comment by Ambrevar** [comment]
While most files were rearranged, we haven't cleaned up the "request-resource" and proxy.  Shall we do it?

**Comment by jmercouris** [comment]
I don't think it is necessary. Personally I don't touch those pieces of code very often. Plus, they can be moved at any time without breaking API.

**Comment by Ambrevar** [comment]
Fair enough.  If I feel like moving them someday, I just will, no need
for an open issue.
