### ISSUE TITLE
Add one-liner documentation to M-x command list

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#624]
See https://github.com/atlas-engineer/next/issues/477#issuecomment-547968603 for a screenshot.

**Comment by jmercouris** [comment]
That would be really cool :-)

**Comment by Ambrevar** [comment]
First we need multi-column support for the minibuffer (see Helm but more structured).  Then this would be trivial to implement.

**Comment by jmercouris** [comment]
Do we need multi-column support for the minibuffer? I was thinking it should be enough if we can do raw markup and each element describes how to draw itself, in this case it would be something like
`<p>open-file &nbsp;&nbsp;&nbsp;&nbsp; Open a file</p>

**Comment by jmercouris** [comment]
Or rather, a `<span>` to avoid the default newline behavior.

**Comment by Ambrevar** [comment]
We can use your idea, but we still need some sort of column support to:

- align the different parts;
- toggle which coluns we want to display.

**Comment by jmercouris** [comment]
Yeah, alignment would be the big issue here. I think there is a good object oriented way to do this. Maybe we can have a update-display that specializes on the class of the list of results? We could have a class like "multi-column-completion" or something.

**Comment by Ambrevar** [comment]
This is fixed on master.
