### ISSUE TITLE
Move keymap to a separate repository

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#636]
I'd like to move libraries/keymap to a seperate repository and publish it on Quicklisp.
@jmercouris Where shall we host it?
I can host it myself, or have it here at github.com/atlas-engineer.

**Comment by jmercouris** [comment]
I would like that all of the repositories we make as a product of Next go into github.com/atlas-engineer so that they can stay in one place, and show the contributions we make to the Lisp community as well

**Comment by Ambrevar** [comment]
I'll move it next week.

**Comment by Ambrevar** [comment]
Shall we keep the name `keymap` or go with `nkeymap`, or `nkeymaps` (because `nhooks` and `nfiles` are plural`)?

**Comment by aadcg** [comment]
`nkeymaps`.

**Comment by jmercouris** [comment]
nkeymaps!

**Comment by Ambrevar** [comment]
Done with https://github.com/atlas-engineer/nkeymaps.

I've used `git filter-repo` to preserve the history and edit the commit messages.

``` shell
git filter-repo --path tests/ --path-rename "tests/:"
git filter-repo --message-callback 'return message.replace(b"keymap: ", b"")'
git filter-repo --message-callback 'return message.replace(b"keymap/tests: ", b"tests: ")'
git filter-repo --message-callback 'return message.replace(b"libraries/keymap: ", b"")'
```

Pretty neat, hu? :)

Left to do:
- [ ] Package for Guix.
- [ ] Set Git submodule in Nyxt repo.
- [ ] Remove from Nyxt's asd.
- [ ] Remove from Nyxt's repo.

**Comment by aadcg** [comment]
@Ambrevar I started to package it for Guix already but I noticed that `trivial-package-local-nicknames` is missing from the `.asd` file. 

[Please grant me permission to the `nkeymap` repository so that I can continue](https://github.com/atlas-engineer/nkeymaps/issues/1).

**Comment by aadcg** [comment]
I've packaged it for Guix. 

@Ambrevar, the description below might be too long. Any suggestion? Cut some items? Write something else that isn't in the repo's README?

```scheme
(define-public sbcl-nkeymaps
  (let ((commit "b4888adf411f45fdbf950c9f7e448ef8e8721cf1")
        (revision "0"))
    (package
    (name "sbcl-nkeymaps")
    (version (git-version "0.1.0" revision commit))
    (source
     (origin
       (method git-fetch)
       (uri (git-reference
             (url "https://github.com/atlas-engineer/nkeymaps")
             (commit commit)))
       (file-name (git-file-name "nkeymaps" version))
       (sha256
        (base32
         "0jiw9k4041mqdjl06q1haf5bsnz8f2xk9ajkismv0yjx8cdqsi7r"))))
    (build-system asdf-build-system/sbcl)
    (inputs
     (list sbcl-alexandria
           sbcl-cl-str
           sbcl-fset
           sbcl-trivial-package-local-nicknames))
    (native-inputs
     (list sbcl-prove))
    (home-page "https://github.com/atlas-engineer/nkeymaps")
    (synopsis "Keymap facility for Common Lisp")
    (description "Inspired by Emacsy (keymap.scm) which is inspired by Emacs.
@itemize

@item Support prefix keys to other keymaps. For instance, if you prefix
my-mode-map with C-c, then all bindings for my-mode will be accessible after
pressing C-c.

@item List all bindings matching a given prefix. (Also known as which-key in
Emacs.)

@item List the bindings associated to a command.

@item Support multiple inheritance.

@item Support keycode.

@item Validate keyspec at compile time.

@item define-key can set multiple bindings in a single call.

@item Support multiple scheme to make it easy to switch between, say,
Emacs-style and VI-style bindings. This orthogonality to keymaps composes
better than having multiple keymaps: changing scheme applies to the entire
program, which is easier than looping through all keymaps to change them.

@item Translate keyspecs as a fallback. For instance if shift-a is not bound,
check A.

@item Behaviour can be customized with global parameters such as
*print-shortcut*.

@item The compose function can merge multiple keymaps together.

@item Support multiple arguments when that makes sense (e.g. multiple keymaps
for lookup-key).

@item Key remapping à-la Emacs.

@item Typed keymaps, i.e. keymaps where bound values can only be of a given
type. This is convenient to catch typos, for instance when binding 'FOO
instead of #'FOO.")
    (license license:expat))))
```

**Comment by aadcg** [comment]
We also need to make a new tag for `nkeymap`. I never did it, so this seems like a good opportunity.

**Comment by Ambrevar** [comment]
Please wait for guidance... ;)

So to release a new version (with a tag), you need to things:
- Create a new commit which sets the new version in the .asd
- Tag this  commit to the corresponding version (do _not_ prefix the tag with `v`) and push it.

Since you've already pushed, please remove the tag and add it again on the "version update" commit.

**Comment by aadcg** [comment]
Oops, fixed now.

**Comment by Ambrevar** [comment]
Perfect, thanks!
