### ISSUE TITLE
Activate focus when following text area hints

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#651]
Current following a text area hint selects it, but it's not possible to write immediately without clicking on it.

**Comment by jmercouris** [comment]
You don't have to click, you can just press tab, I'm not sure why this is, but I decided against sending an artificial tab keypress to the web view (though that would fix it). I was trying to figure out if there was a more correct way to do it.

**Comment by Ambrevar** [comment]
Indeed, thanks for the tip.

Qutebrowser can focus properly, maybe we can look at what it's calling.

**Comment by jmercouris** [comment]
This is now fixed on master.

**Comment by Ambrevar** [comment]
Fantastic, thanks a lot!

**Comment by Ambrevar** [comment]
Wait, which commit fixed it?

**Comment by jmercouris** [comment]
The one that applies focus to the buffer on buffer switch. Look at FFI-window-set-active-buffer for more details.

**Comment by Ambrevar** [comment]
Got it, thanks.  So it's fixed with
ce311beff53735a615cbac90443854d600fca49b.

If I get it right, previously the webview was not focused, instead it
was whatever widget, which prevented WebKitGTK from "doing the right
thing" with the cursor in the current window.

**Comment by jmercouris** [comment]
That's correct!
