### ISSUE TITLE
Search sometimes highlights the wrong text

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#666]
Some highlighting is at the wrong place.

Recipe: on the help start page, search "the", press RETURN and see that
"y o" is highlighted in the following line:

> Customization is possible through the creation of a ~/.config/next/init.lisp file. From here you can override and redefine any of they of they of the functions by defining your init file
> as part of the :next package. For more information please see: customizing Next.

**Comment by jolmg** [comment]
As mentioned in the duplicate issues, this also involves the text being mangled by the search. For example, searching for "the" in

> This manual first includes the tutorial, then covers the configuration of Nyxt.

mangles the sentence to:

> This manual first includes the first includes the fial fial first includes the tutorial, then covers the configuration of Nyxt.

**Comment by jmercouris** [comment]
Fixed on master!

**Comment by jolmg** [comment]
\* sees no one has made a pun of the issue number. what to say, what to say...

That was one devil of a bug! :P

Happy to see it's fixed.

**Comment by jmercouris** [comment]
11! sure was
