### ISSUE TITLE
Echo / message error on load failures

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#672]
Recipe:
- disconnect from the Internet.
- load a page.

We need to tell the user that the page could not be loaded instead of doing nothing, since it's very confusing.

Ideally, the status view should keep the load status displayed since the echoed message is ephemeral.

**Comment by jmercouris** [comment]
Interesting, mine shows an error, says page could not be loaded after some time

**Comment by jmercouris** [comment]
Status view is now updated to show when a page is loading. The renderer will try as long as possible, and eventually report an error message. There are no events that should overwrite the status until it is done.

**Comment by jmercouris** [comment]
Works as expected:
![Screen Shot 2020-04-24 at 13 16 35](https://user-images.githubusercontent.com/1691662/80207131-20c24e80-861d-11ea-9e0d-ecd3e1308a98.png)

**Comment by jmercouris** [comment]
I find it hilarious that my interface is half in English and half in Greek :-D

**Comment by Ambrevar** [comment]
Thanks, that's already an improvement!

We can do a little bit better I think, consider this:
Run `follow-hint-new-buffer` and follow a hint in the background.
Notice that both the status view and the echo area report that they are
loading the buffer.  This is redundant, plus the current buffer does not
display any meaningful status anymore.

I suggest the following approach instead: when the buffer loads, have
print-status display the regular status bar with (loading...) appended
before or after the URL.  This way it's contextual to the buffer that's
actually loading.

Thoughts?

**Comment by jmercouris** [comment]
Ah, I see what is happening, that behavior with the background was not intended... :-D

**Comment by jmercouris** [comment]
I don't understand your proposed solution, can you explain how that would fix the problem? The real issue is that the status message is currently tied to a window, and not a buffer

**Comment by Ambrevar** [comment]
My suggestion:

- Don't use print-status like you did on a buffer load.
- Instead, in the print-status function, get the load state of the
  buffer and print it next to the URL
  (we might need a new buffer slot for that).

By the way, I'm realizing that the current fix is going off topic: the issue is about
load _failures_, e.g. when there is not internet connection.  Right now
we get buffers like "Internel WebKit error" which means little to the
user.

What we must do here is handle the load-failed signal.

**Comment by jmercouris** [comment]
print-status would still need to be informed by someone, that would have to be on buffer load. are you suggesting the following:

print-status invoked in buffer load with no arguments
print status default status formatter adds loading if a buffer is currently loading?

**Comment by jmercouris** [comment]
> By the way, I'm realizing that the current fix is going off topic: the issue is about load _failures_, e.g. when there is not internet connection. Right now we get buffers like "Internel WebKit error" which means little to the user. What we must do here is handle the load-failed signal.

Strange that it tells you "Internal Webkit Error". For me it says the service or servername could not be resolved (which is what is happening).

**Comment by Ambrevar** [comment]
> print-status would still need to be informed by someone, that would have to be on buffer load. are you suggesting the following:
>
> print-status invoked in buffer load with no arguments
> print status default status formatter adds loading if a buffer is currently loading?

Yes!

**Comment by Ambrevar** [comment]
> Strange that it tells you "Internal Webkit Error". For me it says the service or servername could not be resolved (which is what is happening).

Indeed, I never had this message myself.

**Comment by jmercouris** [comment]
The following code:

```
  (gobject:g-signal-connect
   (gtk-object buffer) "load-failed"
   (lambda (web-view load-event failing-uri error)
     (declare (ignore load-event failing-uri web-view error))
     (print "Load Fail")))
```

Produces an error:
```
Unknown GBoxed type 'GError'
   [Condition of type SIMPLE-ERROR]

Restarts:
 0: [ABORT] Exit debugger, returning to top level.

Backtrace:
  0: (GOBJECT::GET-G-BOXED-FOREIGN-INFO-FOR-GTYPE #<GTYPE :name "GError" :id 140228195051424>)
  1: ((:METHOD GOBJECT::PARSE-G-VALUE-FOR-TYPE (T (EQL (GOBJECT:GTYPE "GBoxed")))) #.(SB-SYS:INT-SAP #X01F38E68) #<unused argument>) [fast-method]
  2: ((FLET CALL-NEXT-METHOD :IN "/Users/jmercouris/.quicklisp/dists/quicklisp/software/cl-cffi-gtk-20200427-git/gobject/gobject.g-value.lisp"))
  3: ((:METHOD GOBJECT::PARSE-G-VALUE-FOR-TYPE :AROUND (T T)) #.(SB-SYS:INT-SAP #X01F38E68) #<GTYPE :name "GBoxed" :id 72>) [fast-method]
  4: ((SB-PCL::GF-DISPATCH GOBJECT::PARSE-G-VALUE-FOR-TYPE) #.(SB-SYS:INT-SAP #X01F38E68) #<GTYPE :name "GBoxed" :id 72>)
  5: ((:METHOD GOBJECT::PARSE-G-VALUE-FOR-TYPE (T T)) #.(SB-SYS:INT-SAP #X01F38E68) #<GTYPE :name "GError" :id 140228195051424>) [fast-method]
  6: ((FLET CALL-NEXT-METHOD :IN "/Users/jmercouris/.quicklisp/dists/quicklisp/software/cl-cffi-gtk-20200427-git/gobject/gobject.g-value.lisp"))
  7: ((:METHOD GOBJECT::PARSE-G-VALUE-FOR-TYPE :AROUND (T T)) #.(SB-SYS:INT-SAP #X01F38E68) #<GTYPE :name "GError" :id 140228195051424>) [fast-method]
  8: ((SB-PCL::GF-DISPATCH GOBJECT::PARSE-G-VALUE-FOR-TYPE) #.(SB-SYS:INT-SAP #X01F38E68) #<GTYPE :name "GError" :id 140228195051424>)
  9: (GOBJECT:PARSE-G-VALUE #.(SB-SYS:INT-SAP #X01F38E68))
 10: (GOBJECT::PARSE-CLOSURE-ARGUMENTS 4 #.(SB-SYS:INT-SAP #X01F38E20))
 11: ((LAMBDA (GOBJECT::CLOSURE GOBJECT::RETURN-VALUE GOBJECT::COUNT-OF-ARGS GOBJECT::ARGS GOBJECT::INVOCATION-HINT GOBJECT::MARSHAL-DATA) :IN "/Users/jmercouris/.quicklisp/dists/quicklisp/software/cl-cffi..
 12: ((LAMBDA (SB-ALIEN::ARGS-POINTER SB-ALIEN::RESULT-POINTER FUNCTION) :IN "/Users/jmercouris/.quicklisp/dists/quicklisp/software/cl-cffi-gtk-20200427-git/gobject/gobject.signals.lisp") #<unavailable arg..
 13: ("foreign function: funcall_alien_callback")
 14: ("foreign function: #x2010073B")
 15: ("foreign function: #x1CB7E00")
 16: ("foreign function: signal_emit_unlocked_R")
 17: ("foreign function: g_signal_emit_valist")
 18: ("foreign function: g_signal_emit")
 19: ("foreign function: _Z23webkitWebViewLoadFailedP14_WebKitWebView15WebKitLoadEventPKcP7_GError")
 --more--
```

here is the relevant section of the API:
https://webkitgtk.org/reference/webkit2gtk/stable/WebKitWebView.html#WebKitWebView-load-failed

I believe this is an error in cl-cffi-gtk, I do think we can handle it in cl-webkit

ideas?

**Comment by jmercouris** [comment]
I will try to report, and I will try the other cl-cffi-gtk as well, I want to do some more investigation first though

**Comment by jmercouris** [comment]
BAM!

**Comment by jmercouris** [comment]
![Screenshot_20210406_142305](https://user-images.githubusercontent.com/1691662/113710580-2b69dc80-96e4-11eb-962f-c510d210588c.png)

**Comment by Ambrevar** [comment]
Fantastic!

Note for posterity: 
- please mention the commit where this is fixed (here ab813b3d5a7550b75a1dd46a90427044131fcbfb).
- When you upload a submodule, let me know so that I don't forget to update the cl-webkit Guix package.

**Comment by jmercouris** [comment]
OK! I will try to do that in the future!

**Comment by jmercouris** [comment]
Fixed here: https://github.com/atlas-engineer/nyxt/commit/9a96ff14922331d58a1cd7249dd50c54b90e8c49
