### ISSUE TITLE
Tag a pre-release

### ISSUE THREAD

**Issue by bqv** [atlas-engineer/nyxt#682]
Should we tag 2.0.0-pre or -rc1 or similar to allow people to test? The last tag was 1.5.0 which is quite old at this point

**Comment by Ambrevar** [comment]
I think it's a good idea.  We could reach out to the community for more testing, especially when it comes to install / running / doc.
@jmercouris ?

**Comment by jmercouris** [comment]
Let’s do it! I would say pre

**Comment by Ambrevar** [comment]
You mean "2.0.0-pre"?  Shall we append a number like "2.0.0-pre1" in case number 2 comes afterwards?

**Comment by jmercouris** [comment]
OK!

**Comment by bqv** [comment]
Almost a month later...

**Comment by bqv** [comment]
To be clear, a pre-release does not have to have *all bugs fixed*, it would just be nice to have a reasonably recent version in various unstable repositories

**Comment by jmercouris** [comment]
We were just talking about this over email, we’ll probably do it on Monday :-)

**Comment by bqv** [comment]
He said, a week ago.

@Ambrevar can you please take charge on this, it's mor  than ridiculous now

**Comment by Ambrevar** [comment]
@jmercouris Never announce a release date! ;) 

We are waiting for a .deb package and a test for the macOS .app.  Once these are ready, we will tag the prerelease.  Sorry for the long wait, multi-OS packaging is a long and painful process :/

**Comment by bqv** [comment]
Because I no longer care, frankly. Its been a month, I'm just not interested.

**Comment by Ambrevar** [comment]
Some things take time :)

**Comment by bqv** [comment]
That was the problem I was trying to solve here. I don't expect the release soon, so I'd like some experimental code to at least understand what's coming, and be able to help test etc. - Instead you've spent a month trying to make a prerelease perfect too, so it's basically a release. That means this issue is pointless for its original purpose

**Comment by Ambrevar** [comment]
We are not trying to make the prerelease perfect, we are simply trying
to make it.  We've spent a long time packaging, which is why this is
taking so long (we haven't got a pipeline to build the packages yet).

The best way to help with development is to build from master.
Prerelease packages are coming, we just need to finish them :)

**Comment by bqv** [comment]
I'm closing this issue and I would appreciate it if you don't open it again. I no longer have any stake in this, and if you do eventually intend on creating a tag, this issue being open isn't a prerequisite.

**Comment by Ambrevar** [comment]
Sure, but what's the matter with an open issue?  I believe that if you don't want to receive notifications you can use the "unsubscribe" button.

**Comment by jmercouris** [comment]
We have tagged a pre-release!
commit: d25e399449859e9a559c5cf9538ac31b0af1f6d4
tag: 2-pre-release-1

**Comment by Ambrevar** [comment]
False alarm, the tag is on the wrong commit, I'll update just now.

**Comment by Ambrevar** [comment]
Should be good now:

https://github.com/atlas-engineer/nyxt/commit/e83e1021e5ca62bf3c12ff3a69ddb850c1ab7e7a
