### ISSUE TITLE
Unnaceptable TLS certificate error

### ISSUE THREAD

**Issue by hsanjuan** [atlas-engineer/nyxt#687]
Trying to open things like https://post.de throws an `Unnaceptable TLS Certificate` message.

Why is it unacceptable?

Logs say:

```
WARNING:
   Couldn't handle multiple interfaces for #.(SB-SYS:INT-SAP #X7F60982DB370) of type GTlsCertificateGnutls: NIL.
```

which is very cryptic... so I am not sure if it's a matter of the certificate having weak crypto, or some bug in webkitgtk or even Next?

**Comment by jmercouris** [comment]
Thank you for the report! My first inclination is that our bindings are slightly problematic, and that WebKitGTK is presenting us with some case we did not anticipate...

**Comment by Ambrevar** [comment]
Héctor: post.de is indeed not included in the nss-certs.
You can try with Epiphany, same problem.

You can force-accepting the cerfiticates with
`add-domain-to-certificate-whitelist'.

If you want to make this permanent, see the doc of the above command
(press "f1 c") on commit 2b324fd5be2c58d3d1bddfc344ae5155ecf3e458.

Spoiler:

(setf next/certificate-whitelist-mode:*default-certificate-whitelist*
      '("post.de"))

**Comment by hsanjuan** [comment]
@Ambrevar ok, but this is more about telling me "Could not find a trusted root authority for this certificate", and perhaps even printing the certificate information (and ultimately allowing me to ignore the issue).

But in fact the problem is that the CN declared by the certificate does not belong to the domain. Epiphany correctly tells about this.

**Comment by Ambrevar** [comment]
I've opened https://github.com/atlas-engineer/next/issues/689 about
this, is that what you mean?

We can go fancy on certificates after 2.0.

**Comment by hsanjuan** [comment]
No, what I mean is mostly specifying the reason that the certificate is invalid in the error page.

**Comment by Ambrevar** [comment]
Yes, we can do that when fixing the aforementioned issue.

**Comment by jmercouris** [comment]
Beyond the fact that the certificate is not acceptable, we should still probably address the bindings at some point... :-D

**Comment by Ambrevar** [comment]
Which bindings?

**Comment by jmercouris** [comment]
WebKitGTK+ bindings

**Comment by jmercouris** [comment]
“Couldn’t handle multiple interfaces ...” whatever that means :-D

**Comment by jmercouris** [comment]
Master has a fix for this now, please let us know if this works for you :-)
