### ISSUE TITLE
macOS: WebKit encountered an internal error

### ISSUE THREAD

**Issue by khinsen** [atlas-engineer/nyxt#709]
**Describe the bug**

Under macOS, I am getting frequent but non-reproducible messages "WebKit encountered an internal error". Reloading the page fixes the problem in most cases. Under Guix (running on the same computer in a virtual machine), this hasn't happend to me yet, so it looks like a macOS-specific problem.

Is there anything I can do to debug this? The error message is a bit vague.

**Precise recipe to reproduce the issue**

None so far!

**Information**
- OS name+version: macOS 10.14.6
- Next version (from =M-x next-version= or =next --version=): 1.5.0-af201189
- How you installed Next (Guix pack, package manager, build from source): MacPorts

**Comment by Ambrevar** [comment]
The same happens to me on Guix.
I don't know what this means and I fear this could be related to the
freeze issues.

**Comment by Ambrevar** [comment]
Or maybe it's just #672.

**Comment by jmercouris** [comment]
I do not believe it is related, though I don't know enough. I've noticed the error most frequently occurs with buffers that are loaded in the background. Beyond that there is no discernible pattern. It is perhaps an error with graphical context? Not sure. I think it would be useful to add a signal for webkit internal errors (should there exist a signal) to log them in the messages buffer with some information that we can maybe use to debug the problem.

**Comment by Ambrevar** [comment]
Intercepting :load-failed could be very helpful!

**Comment by khinsen** [comment]
Here is an internal error that is very reproducible for me:
 - macOS
 - Next at commit https://github.com/atlas-engineer/next/commit/817223e050f5cce265780c98446cfcb9850dcef4
 - load https://org-roam.discourse.group/

No internal error under Guix, using the same commit and the same site on the same machine connected to the same network.

**Comment by Ambrevar** [comment]
Can't you ever load this page or does it work when you reload?

**Comment by jmercouris** [comment]
Interesting I got a "service worker context closed" for https://org-roam.discourse.group/

**Comment by khinsen** [comment]
@Ambrevar With the precise commit I mentioned, I get an internal error every time I load or reload. I tried at least 20 times in a row, and then another round a few hours later.

**Comment by jmercouris** [comment]
I would like to report that "Internal WebKit Errors" are very sparse when running the Quartz port of WebKit. Unfortunately, every single WebKit process results in a new dock icon. I am currently trying to fix that. Then, we may consider this issue closed.

**Comment by Ambrevar** [comment]
What does "very sparse mean"?  If they still occur, then the problem is
still present, isn't it?

Try running Nyxt over Tor, these issues tend to get raised more often on
connection errors.

**Comment by jmercouris** [comment]
very sparse means I experience them once every couple of days at most.

**Comment by jmercouris** [comment]
don't worry, with my "quality internet" I get more than enough connection errors :-D

**Comment by jmercouris** [comment]
Well, well well! Please install with Quartz now, problem fixed!

**Comment by Ambrevar** [comment]
I'm not a macOS user so I can't see what happened! :p
Can you explain?

**Comment by jmercouris** [comment]
No need to install X11 any more, now using Quartz and the internal engine, things are infinitely faster/better. If you use our Ports tree, you can get this version of WebKit until I hopefully can get this merged into the main WebKit branch.

**Comment by jmercouris** [comment]
Ah, I forgot, it also adds retina display support :-)

**Comment by Ambrevar** [comment]
To be clear, you mean the user has a dependency less to install since it
can use the native macOS graphics layer?

https://en.wikipedia.org/wiki/Quartz_(graphics_layer)

**Comment by jmercouris** [comment]
That's correct, there are many implications of that, but that is the gist.

**Comment by khinsen** [comment]
@jmercouris This is very good news, thanks! Is this supposed to be in the current state of the MacPorts Portfile? The one that fails because of the Osicat issue discussed in https://github.com/atlas-engineer/nyxt/issues/819 ?
