### ISSUE TITLE
Can't log in to various sites

### ISSUE THREAD

**Issue by khinsen** [atlas-engineer/nyxt#717]
**Describe the bug**

Login for many sites just doesn't seem to work with Next.

Example: https://org-roam.discourse.group/

The exact same login/password combination that works with Firefox does not work with Next. I always get back to a dialog box asking me for login plus password. Other sites work fine though (GitHub and Twitter, for example).

**Precise recipe to reproduce the issue**

**Information**
- OS name+version: macOS 10.14.6
- Next version (from =M-x next-version= or =next --version=): 1.5.0 (but that's wrong, I am on a recent build from source, commit f454a9827d673b62fa86e06948d68e76ff1d3fad)
- How you installed Next (Guix pack, package manager, build from source): built from source
- Lisp implementation/version (if built from source): SBCL 2.0.4 from MacPorts
- WebKitGTK+ | QtWebEngine version:

**Comment by Ambrevar** [comment]
Can you reproduce with Epiphany?

Might be the same as #644.

**Comment by khinsen** [comment]
Epiphany works fine for all those logins.

**Comment by Ambrevar** [comment]
Can you reproduce on commit 817223e050f5cce265780c98446cfcb9850dcef4 ?
(There is a regression which makes Next crash much more, so you might
have to insist a little bit.  But logins might be fixed.)

**Comment by Ambrevar** [comment]
I can login to org-roam on the aforementioned commit (built from source, on Guix System).

**Comment by Ambrevar** [comment]
> Next version (from =M-x next-version= or =next --version=): 1.5.0 (but that's wrong, I am on a recent build from source, commit f454a98)

@khinsen Do you have `git` in your `PATH`?  This is needed to set the `+version+` variable in `global.lisp`.

**Comment by khinsen** [comment]
With commit 817223e050f5cce265780c98446cfcb9850dcef4, I can indeed log in under Guix. Under macOS, I get a highly reproducible WebKit Internal Error when loading https://org-roam.discourse.group/.

**Comment by khinsen** [comment]
As for `git`, yes, it's in my path, but under macOS, `$PATH` is not passed to GUI apps launched from the desktop, so Next won't see it.

**Comment by Ambrevar** [comment]
@jmercouris ?

**Comment by azzamsa** [comment]
I can't login with twitter (even with the same password) the `login` button doesn't shows up. So I change my password for the longer one. It works, but several feature didn't work. e.g update email. It's seems like I also can't paste image here (like usually I did in FF)

**Comment by jmercouris** [comment]
@Ambrevar no idea what it is about. As an aside, I spoke with the WebKitGTK+ team, and one of the authors said they are willing to accept more macOS patches even though they are not officially supporting macOS. So, the good news is that we can hopefully begin to hammer out these strange issues and it'll be easier for people to install WebKitGTK+ from source on macOS

**Comment by Ambrevar** [comment]
@azzamsa Are you on macOS?
I didn't understand what you meant with "same password" and "the longer one".

Image-pasting does not work for now because we use xclip / xsel which
don't support it as far as I know.  Maybe fix xclip or xset.

**Comment by Ambrevar** [comment]
@jmercouris: That's great news!

**Comment by jmercouris** [comment]
I can confirm that this bug still exists with the lastest Quartz implementation. Something specific to the discourse site prevents rendering.

**Comment by jmercouris** [comment]
I should also note that no errors appeared in the inspector, no idea what it is. It seems like it doesn't want to load some assets or something.

**Comment by Ambrevar** [comment]
Could this be https://github.com/atlas-engineer/nyxt/issues/768?

**Comment by jmercouris** [comment]
I don't believe so.

**Comment by aadcg** [comment]
macOS support is currently not officially supported. See #577 for a discussion in pursing this goal.

macOS support is planed for Nyxt 4.0.0. See #2989.
