### ISSUE TITLE
Switch from lparallel to chanl

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#722]
lparallel is unmaintained and as far as I understand it lacks the `select` operator to dispatch over the next available channel from a set of channels.

https://github.com/zkat/chanl is maintained, it has the `select' operator and seems a bit more lightweight (to be confirmed).

**Comment by jmercouris** [comment]
unmaintained? more like completed :-D

**Comment by Ambrevar** [comment]
According to this, maybe not so complete:

https://github.com/lmj/lparallel/issues

And if I'm not mistaken, the lack of `select` operator could be a big
flaw for a complete CSP
(https://en.wikipedia.org/wiki/Communicating_sequential_processes).

**Comment by jmercouris** [comment]
the joke is software is either completed or unifished. when it becomes abandoned it is completed :-D

**Comment by Ambrevar** [comment]
Another big argument in favour of chanl is that it does not seem to require initialization code, unlike lparallel which seems to require a global kernel.
