### ISSUE TITLE
Reuse StumpWM contribs? (pass, searchengines...)

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#734]
StumpWM has lots of useful, reusable code:

https://github.com/stumpwm/stumpwm-contrib/tree/master/util

**Comment by jmercouris** [comment]
Of course where it makes sense, many of these things assume a Linux environment (which makes sense), but it may cause problem for our fruit based users (me :-D)

**Comment by jmercouris** [comment]
Closing this issue, after investigation, this appears prohibitively difficult for the amount of gain.
