### ISSUE TITLE
Create Next news website and set it as default URL

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#736]
default-new-buffer-url currently points to `https://next.atlas.engineer/start` which features outdated, non-dynamic bindings.  Now that we have a much better embedded help, I think we should change this.  What about using https://duckduckgo.com since it's our default first engine?

**Comment by jmercouris** [comment]
I would rather suggest that we make it our own page and add a duck duck go search box and something else like Firefox used to do

**Comment by Ambrevar** [comment]
Why not, but for now let's go for the fastest fix to roll out.

**Comment by jmercouris** [comment]
I would say leave it, that page will probably be very useful (for example alerting users of new versions available)

It takes a couple minutes to change, I will get to it :-)

**Comment by Ambrevar** [comment]
I've set the default URL to the default search engine in f4499366b76758c476bf76665f8e82084d6ef6d8.  Whenever the new start page is ready, we can just set it in the code, takes one s-exp to change.

**Comment by jmercouris** [comment]
done in 8a0287db !
