### ISSUE TITLE
Don't hang when restarting Next from the REPL

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#740]
This is a cl-webkit bug, but it seems to also happen with cl-webengine.

See https://github.com/joachifm/cl-webkit/issues/35.

**Comment by Ambrevar** [comment]
Workaround implemented in  0955ba149b97d650480454ac309e8c0e50faffe9.  @jmercouris Can you test on Darwin?

**Comment by jmercouris** [comment]
I can try to test on Darwin, though this does not fix the issue of the user being able to launch from Slime directly.

The steps to launch succesfully from source are the following:

```
M-x eshell
sbcl
(ql:quickload :next/gtk)
(next:start)
M-x start-swank
M-x slime-connect

```

**Comment by jmercouris** [comment]
I do however hope that this will allow the user to kill the GUI and stay connected to Slime :-)

**Comment by jmercouris** [comment]
And of course restart the GUI thereafter

**Comment by jmercouris** [comment]
Well, it certainly doesn't hang :-)

```
There is no applicable method for the generic function
  #<STANDARD-GENERIC-FUNCTION NEXT:BASENAME (1)>
when called with arguments
  (NIL).
   [Condition of type SB-PCL::NO-APPLICABLE-METHOD-ERROR]
See also:
  Common Lisp Hyperspec, 7.6.6 [:section]

Restarts:
 0: [RETRY] Retry calling the generic function.
 1: [RETRY] Retry SLIME REPL evaluation request.
 2: [*ABORT] Return to SLIME's top level.
 3: [ABORT] abort thread (#<THREAD "repl-thread" RUNNING {1009EB9BC3}>)

Backtrace:
  0: ((:METHOD NO-APPLICABLE-METHOD (T)) #<STANDARD-GENERIC-FUNCTION NEXT:BASENAME (1)> NIL) [fast-method]
  1: (SB-PCL::CALL-NO-APPLICABLE-METHOD #<STANDARD-GENERIC-FUNCTION NEXT:BASENAME (1)> (NIL))
  2: (NEXT:START NIL)
  3: (SB-INT:SIMPLE-EVAL-IN-LEXENV (NEXT:START) #<NULL-LEXENV>)
  4: (EVAL (NEXT:START))
 --more--

```

will look into it later if I have some time, I have some other things I am working on first

**Comment by jmercouris** [comment]
To clarify the above, the REPL is still responsive

**Comment by Ambrevar** [comment]
The "basename" error is about a data-path.

**Comment by jmercouris** [comment]
Ah, maybe it is related to my environment. Why would it not present itself on the first start though?

**Comment by Ambrevar** [comment]
Can you share an exact recipe?
How do you restart Next?

**Comment by jmercouris** [comment]
The exact recipe for initialization is defined above, thereafter, I do the following:

`C-x C-c`

go to my SLIME REPL and type in `(next:start)`

**Comment by Ambrevar** [comment]
I tried the following:

From shell:
- `sbcl`
- (ql:quickload :next/gtk)
- (next:start '(:no-init t))

From Next:
- C-space command-evaluate return (load-system :slynk) return
- C-space command-evaluate return (define-command start-slynk ...) return
- C-space start-slynk

From Emacs:
- M-x sly-connect RET RET

From Next:
- C-q

From Emacs:
- (next:start '(:no-init t))

And it works.
Can you try again without loading your init file?
The error you reported is about the data-path.

**Comment by Ambrevar** [comment]
@jmercouris Did you have the time to try this?

**Comment by jmercouris** [comment]
Not yet!

**Comment by aadcg** [comment]
I believe this is not an issue anymore.
