### ISSUE TITLE
make next results in "compilation failed" message

### ISSUE THREAD

**Issue by dalanicolai** [atlas-engineer/nyxt#751]
**Describe the bug**
When trying to build next from source, the make next results in a "compilation failed" message

**Precise recipe to reproduce the issue**
I have followed the steps as described in the [Developer Manual](https://github.com/atlas-engineer/next/blob/master/documents/README.org) in the github repo.

* I am using SBCL 2.0.1-1.fc32 on Fedora 32.
* I have installed the latest quicklisp beta from the [quicklisp.org](https://www.quicklisp.org/beta/) (beta seems to be the standard).
* I have pulled the latest version of cl-webkit repo in my `~/common-lisp/directory' and successfully installed all GTK dependencies following [the instructions in the developer manual](https://github.com/atlas-engineer/next/blob/master/documents/README.org#gtk-dependencies)
* I have installed libwebkit2gtk-4.0.so. Fedora provides this file in two packages: (webkit2gtk3-2.28.0-8.fc32.i686 and webkit2gtk3-2.28.2-2.fc32.i686, I have tried with both to build next)
* I have pulled the latest version of the next repo in my `~/common-lisp/next` directory

Finally when I run `make all` I get the output as found in the following file:
[build.log](https://github.com/atlas-engineer/next/files/4671736/build.log)

* I confirmed that xclip and cl-webkit are installed. Because the README in the cl-webkit repo instruct to install cl-webkit in `~/common-lisp/cl-webkit`, I have tried to build with that directory structure also
* I have tried to build with make `make NEXT_INTERNAL_QUICKLISP=false next`, (ql:update-dist "quicklisp") tells me I already have the latest version installed.
* I don't know how to manually update lisp specific dependencies and[ the link in the developer manual ](https://github.com/atlas-engineer/next/blob/master/documents/README.org#update-local-lisp-libraries) is not working

**Comment by jmercouris** [comment]
Did you update your quicklisp Dist `(ql:update-all-dists)`? It seems you may be running an older version of `cl-containers`. Sorry for all of the trouble, it comes with the bleeding edge :-)

**Comment by dalanicolai** [comment]
I think so yes (I mentioned it in the for last step in my comment). Although you suggest a different function `(ql:update-all-dists)`, when I use your function the response is the same namely:
`You already have the latest version of "quicklisp": 2020-04-27`.

**Comment by jmercouris** [comment]
It is not about your client being the latest quicklisp client, but rather having the latest quicklisp dist, that is the difference I was hinting at. Cl-containers in that release should have exported the symbol which is causing you some issues. Does the build give you the same error? What happens when you `(asdf:locate-system :cl-containers)`? What does it show?

**Comment by vindarel** [comment]
> I don't know how to manually update lisp specific dependencies and the link in the developer manual is not working

You can just clone a recent copy of cl-containers into `~/quicklisp/local-projects`.

    git clone https://github.com/gwkkwg/cl-containers/ ~/quicklisp/local-projects/cl-containers

If you run make commands, then update Next's quicklisp projects with 

    make quicklisp-update

---

I ran into this issue when trying to `quickload` next on the REPL. 

I think this should be at least mentioned in the develop documentation.

ps: use Qlot? https://github.com/fukamachi/qlot Set-up Next's own dist?

**Comment by jmercouris** [comment]
Qlot is a quite good idea, I think we will do that!

**Comment by jmercouris** [comment]
Closing this issue as it is fixed with internal QL via makefile
