### ISSUE TITLE
Add `load-after-system` helper?

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#757]
I think a common pattern that we are to see when users want to depend on third-party Common Lisp systems is to load the system and if it's found, load a configuration file.  Which could itself be another system.

I suggest the following helper:

```
;; If :foo-extension is not found, this does nothing.
(load-after-system :foo-extension :bar-config)
;; Also works:
(load-after-system :foo-extension "path/to/bar/config")
```

The crucial point is that third-party system configuration can only be done in another file because the reader will not know about the loaded system package prefixes.

**Comment by Ambrevar** [comment]
This would supersede #713.

**Comment by jmercouris** [comment]
That is a good point you make... probably easier than doing the macro. Unless we force loading of the whole world before actually executing someone's init file.

**Comment by jmercouris** [comment]
I'm not sure what is best.
