### ISSUE TITLE
Follow all hints?

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#763]
Current the follow-hint* commands only list the visible hints.  It'd be nice to add a command to list all hints, including those that are not visible.

Alternatively, we could lazy-load all hints so that the current commands would list all hints with performance penalty.

**Comment by jmercouris** [comment]
+1!

**Comment by jmercouris** [comment]
This is done. One has to pass the key argument `annotate-full-document` to any of the element hint query commands.

**Comment by Ambrevar** [comment]
What about making this the default?

**Comment by jmercouris** [comment]
That's fine with me!
