### ISSUE TITLE
Add copy-placeholder-text command

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#765]
An itch I want to scratch: placeholder text cannot be copied (beside from the inspector) which can be frustrating if one wants to, say, copy a form including the suggestions.

A dedicated command could help.
Maybe C-c could be bound to selectively copy the placeholder text or the text, depending on which one is present.

**Comment by pdelfino** [comment]
Leave a comment

**Comment by pdelfino** [comment]
@Ambrevar, I think you can close this one. John helped me solve it.

**Comment by Ambrevar** [comment]
Fantastic, thanks a lot!
