### ISSUE TITLE
Remove MANUAL.org and rename tutorial

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#767]
I'm almost done with transfering everything from MANUAL.org to tutorial and docstrings.

@jmercouris OK with removing MANUAL.org?  I'll update the next.atlas.engineer website accordingly.
Also need to update the README.

I also suggest to rename the tutorial command and file to `manual`.  The first section will then be the tutorial and the rest will be the advanced topics.

Thoughts?

**Comment by Ambrevar** [comment]
@jmercouris Friendly ping :)

**Comment by jmercouris** [comment]
I’m working on the website! :-)

**Comment by Ambrevar** [comment]
Great news, I'm done porting the MANUAL.org to the tutorial and docstring.

- Let me know when you are done with the website and I'll delete MANUAL.org.
- What about renaming `tutorial` to `manual`?

**Comment by jmercouris** [comment]
I am done with the website, I just haven't relaunched it yet becuase of the domain name forwarding.

**Comment by jmercouris** [comment]
As per renaming tutorial to manual, I don't see why not :-)

**Comment by jmercouris** [comment]
Shall we also copy the beginning of the manual into a tutorial? It will serve as a short little introduction for users who do not want to see the whole manual.

**Comment by Ambrevar** [comment]
Yes, although instead of copying, the `manual` would simply invoke (tutorial) then fill the rest.

**Comment by Ambrevar** [comment]
next.atlas.engineer does not redirect to nyxt + it fails with the TLS
certificate (which is normal since the hostname does not match).

**Comment by jmercouris** [comment]
DNS records for some changes have yet to propagate

**Comment by Ambrevar** [comment]
Done in 4895a0462e5727b1b3180af36d89d6e82210b0e3.
