### ISSUE TITLE
Support new tab requests (`create` signal)

### ISSUE THREAD

**Issue by Mestelan** [atlas-engineer/nyxt#768]
Hello,

Currently (on WebKitGTK), opening a buffer to another site fails with a JavaScript error, advising to disable the pop-up blocker. I would like to allow pop-ups from some trusted sites, e.g. the email web client. Is there a way to do so?

**Comment by Ambrevar** [comment]
Can you share an example website with a specific link?

**Comment by Mestelan** [comment]
This happens in GMail for every link contained in an email message. 

I will try to find a more easily accessible/reproducible example, but indeed cannot find one for the moment.

**Comment by Ambrevar** [comment]
Can you reproduce on an empty configuration?  (Start with --no-init.)

If so, can you reproduce with Epiphany?

**Comment by Mestelan** [comment]
- This can be reproduced in Next on an empty configuration
- This cannot be reproduced in Epiphany.

**Comment by Ambrevar** [comment]
Does the popup open in a new tab in Epiphany?

**Comment by Mestelan** [comment]
Yes: in Epiphany: the link opens in a new tab.
(sorry, I had edited the GitHub issue to specify this, only after the mail was sent)

**Comment by Ambrevar** [comment]
Thanks for reporting, I'll investigate.

**Comment by Ambrevar** [comment]
I can reproduce in Protonmail.

**Comment by Ambrevar** [comment]
Report of my so far unfruitful investigation.

When clicking on a link in the email body, we only get this:

```
<DEBUG> [17:17:37] nyxt input.lisp (dispatch-input-event) -
  Forward generated event "button1 button1"
```

In particular, the resource-request-hook is not called, which means WebKitGTK never received a decide-policy event.

I also tried "right click -> open link" in case it was some weird input event issue.  Same problem.

It works with Epiphany.  Maybe there is an event we are not catching.

**Comment by Ambrevar** [comment]
Got it!

We need to handle the `create` signal: https://webkitgtk.org/reference/webkit2gtk/stable/WebKitWebView.html#WebKitWebView-create

Sadly, doing so right now raises a condition:

```
Unknown GBoxed type 'WebKitNavigationAction'
   [Condition of type SIMPLE-ERROR]

```

It is defined in cl-webkit as

```lisp
(defctype webkit-navigation-action :pointer) ; XXX: GBoxed

```

**Comment by Ambrevar** [comment]
@joachifm Any idea about this?  Has WebKitNavigationAction ever worked in cl-webkit?

**Comment by joachifm** [comment]
@Ambrevar as I recall that was merely a placeholder, I doubt it was actually tested.

**Comment by Ambrevar** [comment]
Thanks for confirming.

Let's test this against crategus version of cl-cffi-gtk then.
@ferada Any idea about this?

**Comment by jmercouris** [comment]
Inspecting more about this, it appears we /never/ use any WebKit specific Gboxed structs within our code. 

I looked into the value registered and the following types of structs were registered:

```
#<HASH-TABLE {10077F62B3}>
--------------------
Count: 37
Size: 40
Test: EQUAL
Rehash size: 1.5
Rehash threshold: 1.0
[clear hashtable]
Contents: 
"CairoContext" = #S(G-BOXED-OPAQUE-WRAPPER-INFO :NAME GTK:CAIRO-CONTEXT :TYPE "CairoContext" :ALLOC NIL :FREE NIL) [remove entry]
"GVariantType" = #S(G-BOXED-OPAQUE-WRAPPER-INFO :NAME G-VARIANT-TYPE :TYPE "GVariantType" :ALLOC NIL :FREE NIL) [remove entry]
"GdkColor" = #S(G-BOXED-CSTRUCT-WRAPPER-INFO ..) [remove entry]
"GdkEvent" = #S(G-BOXED-VARIANT-CSTRUCT-INFO ..) [remove entry]
"GdkEventSequence" = #S(G-BOXED-OPAQUE-WRAPPER-INFO :NAME GDK:GDK-EVENT-SEQUENCE :TYPE "GdkEventSequence" :ALLOC NIL :FREE NIL) [remove entry]
"GdkFrameTimings" = #S(G-BOXED-OPAQUE-WRAPPER-INFO :NAME GDK:GDK-FRAME-TIMINGS :TYPE "GdkFrameTimings" :ALLOC NIL :FREE NIL) [remove entry]
"GdkGeometry" = #S(G-BOXED-CSTRUCT-WRAPPER-INFO ..) [remove entry]
"GdkPixbufFormat" = #S(G-BOXED-CSTRUCT-WRAPPER-INFO ..) [remove entry]
"GdkPoint" = #S(G-BOXED-CSTRUCT-WRAPPER-INFO :NAME GDK:GDK-POINT :TYPE "GdkPoint" :CSTRUCT-DESCRIPTION #S(CSTRUCT-DESCRIPTION :NAME GDK:GDK-POINT :SLOTS (#S(CSTRUCT-INLINE-SLOT-DESCRIPTION :NAME GDK::X :TYPE :INT :COUNT NIL :INITFORM 0 :INLINE-P NIL :BOXED-TYPE-NAME NIL) #S(CSTRUCT-INLINE-SLOT-DESCRIPTION :NAME GDK::Y :TYPE :INT :COUNT NIL :INITFORM 0 :INLINE-P NIL :BOXED-TYPE-NAME NIL)))) [remove entry]
"GdkRGBA" = #S(G-BOXED-CSTRUCT-WRAPPER-INFO ..) [remove entry]
"GdkRectangle" = #S(G-BOXED-CSTRUCT-WRAPPER-INFO ..) [remove entry]
"GdkTimeCoord" = #S(G-BOXED-CSTRUCT-WRAPPER-INFO :NAME GDK:GDK-TIME-COORD :TYPE "GdkTimeCoord" :CSTRUCT-DESCRIPTION #S(CSTRUCT-DESCRIPTION :NAME GDK:GDK-TIME-COORD :SLOTS (#S(CSTRUCT-INLINE-SLOT-DESCRIPTION :NAME TIME :TYPE :UINT32 :COUNT NIL :INITFORM NIL :INLINE-P NIL :BOXED-TYPE-NAME NIL) #S(CSTRUCT-INLINE-SLOT-DESCRIPTION :NAME GDK::AXES :TYPE :DOUBLE :COUNT 128 :INITFORM NIL :INLINE-P NIL :BOXED-TYPE-NAME NIL)))) [remove entry]
"GdkWindowAttr" = #S(G-BOXED-CSTRUCT-WRAPPER-INFO ..) [remove entry]
"GtkBorder" = #S(G-BOXED-CSTRUCT-WRAPPER-INFO ..) [remove entry]
"GtkIconSet" = #S(G-BOXED-OPAQUE-WRAPPER-INFO :NAME GTK:GTK-ICON-SET :TYPE "GtkIconSet" :ALLOC NIL :FREE NIL) [remove entry]
"GtkIconSource" = #S(G-BOXED-OPAQUE-WRAPPER-INFO :NAME GTK:GTK-ICON-SOURCE :TYPE "GtkIconSource" :ALLOC NIL :FREE NIL) [remove entry]
"GtkPaperSize" = #S(G-BOXED-OPAQUE-WRAPPER-INFO :NAME GTK:GTK-PAPER-SIZE :TYPE "GtkPaperSize" :ALLOC NIL :FREE NIL) [remove entry]
"GtkRecentInfo" = #S(G-BOXED-OPAQUE-WRAPPER-INFO :NAME GTK:GTK-RECENT-INFO :TYPE "GtkRecentInfo" :ALLOC NIL :FREE NIL) [remove entry]
"GtkRequestedSize" = #S(G-BOXED-CSTRUCT-WRAPPER-INFO ..) [remove entry]
"GtkRequisition" = #S(G-BOXED-CSTRUCT-WRAPPER-INFO :NAME GTK:GTK-REQUISITION :TYPE "GtkRequisition" :CSTRUCT-DESCRIPTION #S(CSTRUCT-DESCRIPTION :NAME GTK:GTK-REQUISITION :SLOTS (#S(CSTRUCT-INLINE-SLOT-DESCRIPTION :NAME GTK::WIDTH :TYPE :INT :COUNT NIL :INITFORM 0 :INLINE-P NIL :BOXED-TYPE-NAME NIL) #S(CSTRUCT-INLINE-SLOT-DESCRIPTION :NAME GTK::HEIGHT :TYPE :INT :COUNT NIL :INITFORM 0 :INLINE-P NIL :BOXED-TYPE-NAME NIL)))) [remove entry]
"GtkSelectionData" = #S(G-BOXED-OPAQUE-WRAPPER-INFO :NAME GTK:GTK-SELECTION-DATA :TYPE "GtkSelectionData" :ALLOC NIL :FREE NIL) [remove entry]
"GtkTargetEntry" = #S(G-BOXED-CSTRUCT-WRAPPER-INFO ..) [remove entry]
"GtkTargetList" = #S(G-BOXED-OPAQUE-WRAPPER-INFO :NAME GTK:GTK-TARGET-LIST :TYPE "GtkTargetList" :ALLOC NIL :FREE NIL) [remove entry]
"GtkTextIter" = #S(G-BOXED-OPAQUE-WRAPPER-INFO :NAME GTK:GTK-TEXT-ITER :TYPE "GtkTextIter" :ALLOC NIL :FREE NIL) [remove entry]
"GtkTreeIter" = #S(G-BOXED-CSTRUCT-WRAPPER-INFO ..) [remove entry]
"GtkTreePath" = #S(G-BOXED-OPAQUE-WRAPPER-INFO :NAME GTK:GTK-TREE-PATH :TYPE "GtkTreePath" :ALLOC NIL :FREE NIL) [remove entry]
"GtkTreeRowReference" = #S(G-BOXED-OPAQUE-WRAPPER-INFO :NAME GTK:GTK-TREE-ROW-REFERENCE :TYPE "GtkTreeRowReference" :ALLOC NIL :FREE NIL) [remove entry]
"GtkWidgetPath" = #S(G-BOXED-OPAQUE-WRAPPER-INFO :NAME GTK:GTK-WIDGET-PATH :TYPE "GtkWidgetPath" :ALLOC NIL :FREE NIL) [remove entry]
NIL = #S(G-BOXED-CSTRUCT-WRAPPER-INFO ..) [remove entry]
"PangoAttrList" = #S(G-BOXED-OPAQUE-WRAPPER-INFO :NAME PANGO:PANGO-ATTR-LIST :TYPE "PangoAttrList" :ALLOC NIL :FREE NIL) [remove entry]
"PangoFontDescription" = #S(G-BOXED-OPAQUE-WRAPPER-INFO :NAME PANGO:PANGO-FONT-DESCRIPTION :TYPE "PangoFontDescription" :ALLOC NIL :FREE NIL) [remove entry]
"PangoGlyphString" = #S(G-BOXED-OPAQUE-WRAPPER-INFO :NAME PANGO:PANGO-GLYPH-STRING :TYPE "PangoGlyphString" :ALLOC NIL :FREE NIL) [remove entry]
"PangoLanguage" = #S(G-BOXED-OPAQUE-WRAPPER-INFO :NAME PANGO:PANGO-LANGUAGE :TYPE "PangoLanguage" :ALLOC NIL :FREE NIL) [remove entry]
"PangoLayoutIter" = #S(G-BOXED-OPAQUE-WRAPPER-INFO :NAME PANGO:PANGO-LAYOUT-ITER :TYPE "PangoLayoutIter" :ALLOC NIL :FREE NIL) [remove entry]
"PangoLayoutLine" = #S(G-BOXED-OPAQUE-WRAPPER-INFO :NAME PANGO:PANGO-LAYOUT-LINE :TYPE "PangoLayoutLine" :ALLOC NIL :FREE NIL) [remove entry]
"PangoMatrix" = #S(G-BOXED-CSTRUCT-WRAPPER-INFO ..) [remove entry]
"PangoTabArray" = #S(G-BOXED-OPAQUE-WRAPPER-INFO :NAME PANGO:PANGO-TAB-ARRAY :TYPE "PangoTabArray" :ALLOC NIL :FREE NIL) [remove entry]
```

as you can see, none of them are WebKit based. I would like to figure out how to add to the `*g-type-name->g-boxed-foreign-info*` hash table, as I believe that will solve our issue.

**Comment by Ambrevar** [comment]
Which `*g-type-name->g-boxed-foreign-info*`?
The lack of GBoxed support has been a pain for a long time, we've already had such issues in the past, but we've always worked around them.

Could you try with the GI renderer?  This shouldn't be an issue there.

**Comment by jmercouris** [comment]
I've tried with the GI renderer , same issue there. I believe I must enhance cL webkit to support gboxed types from webkit

**Comment by Ambrevar** [comment]
With GI there should be no need for special Gboxed handling, GI should already allow us to unbox them.  There is some Glib code to call here though.

Can you show the code you've tried and the backtrace you got?

**Comment by Ambrevar** [comment]
Something maybe worth looking at is Crategus developments on cl-cffi-gtk:
https://github.com/crategus/cl-cffi-gtk/.
There's been some hundreds of commit departing from Ferada's fork, so maybe there is some inspiring GBoxed support code there.

**Comment by jmercouris** [comment]
There is nothing in the commits that handles this. We need to use the macros to define a g-boxed-type to extend the hashmap of known gobjects.

That means `define-g-boxed-opaque` or `define-g-box-cstruct`. Still trying to figure out how to use these macros. I am able to get my callback to be invoked without failure, in other words we /can/ handle th ecreate signal. What I am now experiencing is strange behavior where it is taking the lambda handler I write and returning it...

more investigation...!

**Comment by Ferada** [comment]
> There's been some hundreds of commit departing from Ferada's fork, so maybe there is some inspiring GBoxed support code there.

Btw. if you decide to go with it, maybe also request switching the Quicklisp source back.

**Comment by jmercouris** [comment]
I have fixed this, this will also fix our other Gboxed issues. i will be changing tires right now while the weather is still good, hope to post the solution later today! much thanks to @Ferada

**Comment by Ambrevar** [comment]
Sorry, what have you fixed?

**Comment by jmercouris** [comment]
I have figured out how we can support signals that were recently returning us errors.

**Comment by jmercouris** [comment]
This will also allow us to fix "echo error message on load failures".

**Comment by jmercouris** [comment]
BAM! Fixed!

@Ambrevar can you please update the submodule for cl-webkit?

test url: https://jsbin.com/aboluk/148/edit?html,js,output

**Comment by jmercouris** [comment]
I've updated the submodule, no worries!

**Comment by Ambrevar** [comment]
Fantastic, thank you so much!
