### ISSUE TITLE
New Nyxt subreddit set to private

### ISSUE THREAD

**Issue by WongMcGregor** [atlas-engineer/nyxt#779]
In case you did not know about this, one is met by:

"r/Nyxt

All about the Nyxt browser.

The moderators of this subreddit have set it to private. You must be a moderator or approved user to visit."

See the old subreddit announcement for further confirmation of this by others.

**Comment by jmercouris** [comment]
It should be public now, can you please give it a try?

**Comment by WongMcGregor** [comment]
Yes.  I can access it now.

Congratulations on the new name and best of luck with the next release!

**Comment by jmercouris** [comment]
Thanks :-)
