### ISSUE TITLE
Recall previous input for web search

### ISSUE THREAD

**Issue by Mestelan** [atlas-engineer/nyxt#781]
Hello,

Is there a way to recall the previously typed search, when using web engines?
An example: I have just searched for `'duck-duck-go John McCarthy'`; now I would like to search the same terms on Qwant, so `'qwant John McCarthy'`. Is there a way to recall the previous input and edit it?

**Comment by Ambrevar** [comment]
Does `M-h` cut it for your?
(It works in every minibuffer.)

**Comment by Ambrevar** [comment]
"for you"*

**Comment by Mestelan** [comment]
Not exactly. 
M-h allows editing the URL, once it has been expanded by the search engine. Which in the case of the example would be: `https://duckduckgo.com/?q=john+mccarthy&ia=web` and is not so easy to edit.

It would be more convenient to be able to edit the unexpanded input `'duck-duck-go John McCarthy'`. Just delete `duck-duck-go` and change the name of the engine.

**Comment by Ambrevar** [comment]
M-h display the user input, not the expanded request.

Recipe:

- C-l wiki foo: Go to https://en.wikipedia.org/wiki/Foobar.
- C-l M-h: In this minibuffer, you should see "wiki foo".

**Comment by Mestelan** [comment]
Ah OK, thanks for the recipe. I had missed that typing C-l was necessary first (and M-h being a minibuffer command).
This is great, sorry about the hassle.

**Comment by Ambrevar** [comment]
No problem! :)
