### ISSUE TITLE
Error when downloading archive

### ISSUE THREAD

**Issue by Mestelan** [atlas-engineer/nyxt#783]
Loading this URL crashes the browser:
https://downloads.apache.org/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz

Stacktrace:
```
 next --no-init
Next version 1.5.0-5b6d9931
<INFO> [22:48:28] Using data profile "default".
<INFO> [22:48:28] Listening to socket "~/.local/share/next/next.socket".
<INFO> [22:48:33] Loading global history of 1117 URLs from "~/.local/share/next/history.lisp".
<INFO> [22:48:37] Saving session to "~/.local/share/next/sessions/default.lisp".
WARNING:
   Changing meta-class of REQUEST-DATA from SB-KERNEL:UNKNOWN-TYPE to SB-KERNEL:STANDARD-CLASSOID.
<INFO> [22:48:37] Loading "https://downloads.apache.org/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz".
Unhandled SB-INT:SIMPLE-PROGRAM-ERROR in thread #<SB-THREAD:THREAD "cl-cffi-gtk main thread" RUNNING
                                                   {1008446963}>:
  invalid number of arguments: 5

Backtrace for: #<SB-THREAD:THREAD "cl-cffi-gtk main thread" RUNNING {1008446963}>
0: (DOWNLOAD "https://downloads.apache.org/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz" :PROXY-ADDRESS NIL :COOKIES "") [external]
1: (REQUEST-RESOURCE #<REQUEST-DATA {100944AFF3}>)
2: ((:METHOD COMBINE-COMPOSED-HOOK-UNTIL-NON-NIL-SECOND-VALUE (HOOKS:HOOK)) #<NEXT::HOOK-RESOURCE {10079FE803}> #<REQUEST-DATA {100944AFF3}>) [fast-method]
3: ((:METHOD NEXT::ON-SIGNAL-DECIDE-POLICY (GTK-BUFFER T T)) #<GTK-BUFFER {10079F3023}> #<CL-WEBKIT2:WEBKIT-RESPONSE-POLICY-DECISION {1009446753}> :WEBKIT-POLICY-DECISION-TYPE-RESPONSE) [fast-method]
4: (GOBJECT::CALL-WITH-RESTARTS #<CLOSURE (LAMBDA (NEXT::WEB-VIEW NEXT::RESPONSE-POLICY-DECISION NEXT::POLICY-DECISION-TYPE-RESPONSE) :IN FFI-BUFFER-MAKE) {1007A03B9B}> (#<CL-WEBKIT2:WEBKIT-WEB-VIEW {1007A02D83}> #<CL-WEBKIT2:WEBKIT-RESPONSE-POLICY-DECISION {1009446753}> :WEBKIT-POLICY-DECISION-TYPE-RESPONSE))
5: ((LAMBDA (GOBJECT::CLOSURE GOBJECT::RETURN-VALUE GOBJECT::COUNT-OF-ARGS GOBJECT::ARGS GOBJECT::INVOCATION-HINT GOBJECT::MARSHAL-DATA) :IN "~/common-lisp/next/quicklisp/dists/quicklisp/software/cl-cffi-gtk-20200427-git/gobject/gobject.signals.lisp") #.(SB-SYS:INT-SAP #X7F63301462C0) #.(SB-SYS:INT-SAP #X7F633CFECCD0) 3 #.(SB-SYS:INT-SAP #X7F633CFECD30) #<unused argument> #<unused argument>)
6: ((LAMBDA (SB-ALIEN::ARGS-POINTER SB-ALIEN::RESULT-POINTER FUNCTION) :IN "~/common-lisp/next/quicklisp/dists/quicklisp/software/cl-cffi-gtk-20200427-git/gobject/gobject.signals.lisp") #<unavailable argument> #<unavailable argument> #<unavailable argument>)
7: ("foreign function: funcall_alien_callback")
8: ("foreign function: callback_wrapper_trampoline")
9: ("foreign function: #x5010073B")
10: ((LAMBDA NIL :IN GTK:ENSURE-GTK-MAIN))
11: ((LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS))
12: ((FLET SB-UNIX::BODY :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
13: ((FLET "WITHOUT-INTERRUPTS-BODY-4" :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
14: ((FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
15: ((FLET "WITHOUT-INTERRUPTS-BODY-1" :IN SB-THREAD::CALL-WITH-MUTEX))
16: (SB-THREAD::CALL-WITH-MUTEX #<CLOSURE (FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE) {7F633CFEED6B}> #<SB-THREAD:MUTEX "thread result lock" owner: #<SB-THREAD:THREAD "cl-cffi-gtk main thread" RUNNING {1008446963}>> NIL T NIL)
17: (SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE #<SB-THREAD:THREAD "cl-cffi-gtk main thread" RUNNING {1008446963}> NIL #<CLOSURE (LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS) {100844690B}> NIL)
18: ("foreign function: call_into_lisp")
19: ("foreign function: new_thread_trampoline")

```
**Precise recipe to reproduce the issue**
Debian 10 (Buster)
How you installed Next: from source (Git 5b6d9931)

Information from command copy-system-information:
Next Version: 1.5.0-5b6d9931 
Lisp Implementation: SBCL 
Lisp Version: 1.4.16.debian 
Operating System: Linux 4.19.0-9-amd64 
Features: (WEBKIT2 WEBKIT2-2.28 WEBKIT2-EMOJI WEBKIT2-MEDIA WEBKIT2-SANDBOXING
           GTK-3-22 GTK-3-20 GTK-3-18 GTK-3-16 GTK-3-14 GTK-3-12 GTK-3-10
           GTK-3-8 GTK-3-6 GTK-3-4 GTK GDK-3-22 GDK-3-20 GDK-3-18 GDK-3-16
           GDK-3-14 GDK-3-12 GDK-3-10 GDK-3-8 GDK-3-6 GDK-3-4 CAIRO-1-10
           CAIRO-1-12 GDK-PIXBUF GLIB-2-30 GLIB-2-32 GLIB-2-34 GLIB-2-36
           GLIB-2-38 GLIB-2-40 GLIB-2-42 GLIB-2-44 GLIB-2-46 GLIB-2-48
           GLIB-2-50 GLIB-2-52 GLIB-2-54 GLIB-2-56 GLIB-2-58 GLIB
           FSET-EXT-STRINGS SWANK PLUMP-UTF-32 GLOBAL-VARS DECLARE-TYPES
           PARENSCRIPT NAMED-READTABLES OSICAT-FD-STREAMS LPARALLEL 21BIT-CHARS
           CL-FAD CHUNGA FLEXI-STREAMS CLOSER-MOP CL-PPCRE-UNICODE CL-UNICODE
           CL-PPCRE BORDEAUX-THREADS LPARALLEL.WITH-CLTL2 LPARALLEL.WITH-CAS
           LPARALLEL.WITH-STEALING-SCHEDULER SPLIT-SEQUENCE GRAY-STREAMS
           FLAT-NAMESPACE X86-64 UNIX CFFI FLAT-NAMESPACE SEQUENCE-EMPTYP
           FAST-IO-SV FAST-IO SBCL-USES-SB-ROTATE-BYTE ASDF-SYSTEM-CONNECTIONS
           CL-JSON-CLOS CL-JSON THREAD-SUPPORT QUICKLISP
           SB-BSD-SOCKETS-ADDRINFO ASDF3.3 ASDF3.2 ASDF3.1 ASDF3 ASDF2 ASDF
           OS-UNIX NON-BASE-CHARS-EXIST-P ASDF-UNICODE X86-64 64-BIT
           64-BIT-REGISTERS ALIEN-CALLBACKS ANSI-CL AVX2
           C-STACK-IS-CONTROL-STACK CALL-SYMBOL COMMON-LISP
           COMPACT-INSTANCE-HEADER COMPARE-AND-SWAP-VOPS CYCLE-COUNTER ELF
           FP-AND-PC-STANDARD-SAVE GENCGC IEEE-FLOATING-POINT IMMOBILE-CODE
           IMMOBILE-SPACE INTEGER-EQL-VOP LARGEFILE LINKAGE-TABLE LINUX
           LITTLE-ENDIAN OS-PROVIDES-BLKSIZE-T OS-PROVIDES-DLADDR
           OS-PROVIDES-DLOPEN OS-PROVIDES-GETPROTOBY-R OS-PROVIDES-POLL
           OS-PROVIDES-PUTWC OS-PROVIDES-SUSECONDS-T PACKAGE-LOCAL-NICKNAMES
           RELOCATABLE-HEAP SB-CORE-COMPRESSION SB-DOC SB-EVAL SB-FUTEX SB-LDB
           SB-PACKAGE-LOCKS SB-SIMD-PACK SB-SIMD-PACK-256 SB-SOURCE-LOCATIONS
           SB-THREAD SB-UNICODE SB-XREF-FOR-INTERNALS SBCL
           STACK-ALLOCATABLE-CLOSURES STACK-ALLOCATABLE-FIXED-OBJECTS
           STACK-ALLOCATABLE-LISTS STACK-ALLOCATABLE-VECTORS
           STACK-GROWS-DOWNWARD-NOT-UPWARD UNDEFINED-FUN-RESTARTS UNIX
           UNWIND-TO-FRAME-AND-CALL-VOP)

**Comment by Ambrevar** [comment]
Thanks for reporting!

Fixed in ce4a34e465d845c77fc0384de41aa113cf7935fe.
