### ISSUE TITLE
Browser crashed when clicked on a pdf link

### ISSUE THREAD

**Issue by shanavas786** [atlas-engineer/nyxt#785]
**Browser crashed when clicked on a pdf link**

**Information**
- OS name+version: Debian 10 (Buster)
- Graphics card and driver: Intel
- Desktop environment / Window manager name+version: Xfce4
- How you installed Next (Guix pack, package manager, build from source): 1.4.0 deb from github release
- Information from command copy-system-information:

  If you can't run copy-system-information, please provide the following:
  - Next version (from =M-x next-version= or =next --version=): Next 1.3.4
  - Lisp implementation/version (if built from source):
  - Kernel name+version: 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2 (2020-04-29) x86_64 GNU/Linux
  - WebKitGTK+ | QtWebEngine version:

**Output when started from a shell**
<details>
<pre>
 <INFO> [10:14:11] next remote.lisp (resource-query-default buffer) -
  Buffer #<BUFFER {1009945AC3}> downloads http://www.advanced-monolithic.com/pdf/ds1117.pdf
 <INFO> [10:14:11] download-manager native.lisp (cache :uri) -
  DOWNLOAD-MANAGER::URI: "http://www.advanced-monolithic.com/pdf/ds1117.pdf"
  DOWNLOAD-MANAGER::ARGS: (:DIRECTORY #P"/home/shanavas/Downloads/" :COOKIES
                           "TS0194eee0=017643f9b2d5c8a7fc28bf47add25dcedb37c142ae3a5aa8d1ebe20ed917e815302534723caccea3f8423753918b8247fd8739b567"
                           :PROXY NIL)
  
 <INFO> [10:14:12] download-manager native.lisp (fetch download) - Downloading
  http://www.advanced-monolithic.com/pdf/ds1117.pdf
to
  '/home/shanavas/Downloads/ds1117.pdf'.

WARNING:
   Method handler (NEXT::CORE-OBJECT
                   NEXT::REQUEST-RESOURCE) signaled an error: The value
                                                                "95151"
                                                              is not of type
                                                                NUMBER
                                                              when binding SB-KERNEL::X.
Unhandled TYPE-ERROR in thread #<SB-THREAD:THREAD "Anonymous thread" RUNNING
                                  {100955E953}>:
  The value
    "95151"
  is not of type
    NUMBER
  when binding SB-KERNEL::X

Backtrace for: #<SB-THREAD:THREAD "Anonymous thread" RUNNING {100955E953}>
0: (SB-KERNEL:TWO-ARG-= "95151" 0) [external]
1: (SB-VM::GENERIC-=)
2: (NEXT::DOWNLOAD-REFRESH)
3: (NEXT::DOWNLOAD-WATCH)
4: ((LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS))
5: ((FLET SB-UNIX::BODY :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
6: ((FLET "WITHOUT-INTERRUPTS-BODY-4" :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
7: ((FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
8: ((FLET "WITHOUT-INTERRUPTS-BODY-1" :IN SB-THREAD::CALL-WITH-MUTEX))
9: (SB-THREAD::CALL-WITH-MUTEX #<CLOSURE (FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE) {7FFFEFDAED4B}> #<SB-THREAD:MUTEX "thread result lock" owner: #<SB-THREAD:THREAD "Anonymous thread" RUNNING {100955E953}>> NIL T NIL)
10: (SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE #<SB-THREAD:THREAD "Anonymous thread" RUNNING {100955E953}> NIL #<CLOSURE (LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS) {100955E8FB}> NIL)
11: ("foreign function: call_into_lisp")
12: ("foreign function: new_thread_trampoline")

unhandled condition in --disable-debugger mode, quitting
</pre>
</details>

**Comment by Ambrevar** [comment]
You are using an old version of Next, this has been fixed on master.
Might also be fixed with 1.5, to be confirmed.

**Comment by shanavas786** [comment]
Is there a debian installer for 1.5 ? I coun't find any

**Comment by Ambrevar** [comment]
Yes: https://nyxt.atlas.engineer/download

We are working on packages for the upcoming version.

**Comment by Ambrevar** [comment]
Closing this for now, stay tuned when 2.0 gets  released! :)
