### ISSUE TITLE
Move video-mode to a separate extension

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#786]
Video-mode (which is not a mode) would be better reimplemented as part of the download manager.
This means we could be deprecating it soon.  As such I'd like to remove it to avoid publishing 2.0 with a component that's going to disappear.

Thoughts?

**Comment by Ambrevar** [comment]
See #185 for a discussion on a generic download manager.

**Comment by jmercouris** [comment]
I agree fully

**Comment by Ambrevar** [comment]
Done with 8a9b1594c4c977f3ad2150fd4706863523329761.
