### ISSUE TITLE
Bind external editor command to C-e?

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#787]
It's useful enough after all.  Thoughts?

**Comment by tviti** [comment]
I've been using C-c ' for this kind of thing, to mirror org-edit-special.

Wouldn't C-e interfere w/ vim style keybinding? I'm going off of muscle
memory here (not at a computer to check), but iirc C-e is either scroll up
or down?

**Comment by Ambrevar** [comment]
Good suggestion, thanks!

**Comment by jmercouris** [comment]
C-e is also jump to end, I think C-c ' is a better binding as well

**Comment by Ambrevar** [comment]
Done in feca07295137820762467fb570183f29cf138bc8.
