### ISSUE TITLE
can't find tutorial?

### ISSUE THREAD

**Issue by whyfarer** [atlas-engineer/nyxt#790]
I just installed nyxt (manjaro architect with bwpsm). I'm trying to find the tutorial. I can access the help page (M-x help), and I'm see a sentence and link under 
"Documentation:
For full documentation about Next, how it works, and how to extend it please see the [user manual](https://nyxt.atlas.engineer/documentation)."
I click "user manual", and it take me to https://nyxt.atlas.engineer/documentation, which says enter the 'help' command for tutorial and documentation! Seems pretty circular. I see that the change linking to an embedded manual is only a week old (changed in fc78940d) Am I missing something obvious or is there a missing link to the embedded manual from the help page?

Thanks! I'm looking forwards to trying out nyxt once I can find the tutorial

**Comment by Ambrevar** [comment]
Oops!  Fixed in 085fbb134ccd2574476c8477d54dbd97adaf67f3.

Thanks for the catch!

**Comment by whyfarer** [comment]
Thanks for the quick fix!
