### ISSUE TITLE
curl thinks that quicklisp SSL certificate has expired, source build fails

### ISSUE THREAD

**Issue by hectorakemp** [atlas-engineer/nyxt#795]
**Describe the bug**
I tried to install the nyxt browser following the standard developer instructions. Once I got to the `make all` stage, I encountered an error in the `quicklisp.lisp` stage of the `Makefile`. 
```
true && curl --output quicklisp.lisp https://beta.quicklisp.org/quicklisp.lisp || true
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html
```
This causes the download of `quicklisp.lisp` to fail. 
Manually downloading `quicklisp.lisp` and copying it into the root directory `~/common-lisp/nyxt` fixed the issue for me.
**Precise recipe to reproduce the issue**
`make all` 
**Information**
- OS name+version:
MacOSX Catalina 10.15.5.
- Graphics card and driver:
Intel IRIS plus.
- Desktop environment / Window manager name+version:
- How you installed Nyxt (Guix pack, package manager, build from source):
Built from source.
- Desktop environment / Window manager name+version:
- Information from command copy-system-information:

  If you can't run copy-system-information, please provide the following:
  - Nyxt version (from =M-x nyxt-version= or =nyxt --version=):
  - Lisp implementation/version (if built from source):
  - Kernel name+version:
  - WebKitGTK+ | QtWebEngine version:

**Output when started from a shell**

**Comment by Ambrevar** [comment]
Indeed.

What about this: let's use HTTP and checksum the result file.
For instance we can run sha512sum on the result.

@jmercouris: How do you check an SHA512 sum on macOS?

Else we could maybe get it from a Git repository as a submodule.
Thoughts?

**Comment by jmercouris** [comment]
You can use openssl to do it, that is how I have done it in the past. Quicklisp itself as a submodule? I guess... why not :-D
I think it would simplify the Makefile, no?

**Comment by Ambrevar** [comment]
Yes, so either we get

https://github.com/quicklisp/quicklisp-bootstrap

or

https://github.com/quicklisp/quicklisp-client

Unless the bootstrap does something special, I suggest we go directly
with the client, it will save some download and be simpler for the Makefile.

**Comment by jmercouris** [comment]
The client is what I would reccommend.
