### ISSUE TITLE
add-domain-to-certificate-whitelist does not work

### ISSUE THREAD

**Issue by hsanjuan** [atlas-engineer/nyxt#798]
**Describe the bug**

When accessing a domain with a self-signed certificate, I get a TLS error page : `TLS Error: <no_url/name>`. It explains that I should run `add-domain-to-certificate-whitelist` but doing that does nothing. Refreshing the buffer brings me to DuckDuckGo.

**Precise recipe to reproduce the issue**

Nyxt Version: 1.5.0-d0d9c552 
Lisp Implementation: SBCL 
Lisp Version: 2.0.5-115.5-suse 
Operating System: Linux 5.6.14-1-default 
Features: (WEBKIT2 WEBKIT2-2.28 WEBKIT2-EMOJI WEBKIT2-MEDIA WEBKIT2-SANDBOXING
           GTK-3-22 GTK-3-20 GTK-3-18 GTK-3-16 GTK-3-14 GTK-3-12 GTK-3-10
           GTK-3-8 GTK-3-6 GTK-3-4 GTK GDK-3-22 GDK-3-20 GDK-3-18 GDK-3-16
           GDK-3-14 GDK-3-12 GDK-3-10 GDK-3-8 GDK-3-6 GDK-3-4 CAIRO-1-10
           CAIRO-1-12 GDK-PIXBUF GLIB-2-30 GLIB-2-32 GLIB-2-34 GLIB-2-36
           GLIB-2-38 GLIB-2-40 GLIB-2-42 GLIB-2-44 GLIB-2-46 GLIB-2-48
           GLIB-2-50 GLIB-2-52 GLIB-2-54 GLIB-2-56 GLIB-2-58 GLIB
           FSET-EXT-STRINGS SWANK PLUMP-UTF-32 GLOBAL-VARS DECLARE-TYPES
           PARENSCRIPT NAMED-READTABLES OSICAT-FD-STREAMS LPARALLEL 21BIT-CHARS
           CL-FAD CHUNGA FLEXI-STREAMS CLOSER-MOP CL-PPCRE-UNICODE CL-UNICODE
           CL-PPCRE BORDEAUX-THREADS LPARALLEL.WITH-CLTL2 LPARALLEL.WITH-CAS
           LPARALLEL.WITH-STEALING-SCHEDULER SPLIT-SEQUENCE GRAY-STREAMS
           FLAT-NAMESPACE X86-64 UNIX CFFI FLAT-NAMESPACE SEQUENCE-EMPTYP
           FAST-IO-SV FAST-IO SBCL-USES-SB-ROTATE-BYTE ASDF-SYSTEM-CONNECTIONS
           CL-JSON-CLOS CL-JSON THREAD-SUPPORT QUICKLISP ASDF3.3 ASDF3.2
           ASDF3.1 ASDF3 ASDF2 ASDF OS-UNIX NON-BASE-CHARS-EXIST-P ASDF-UNICODE
           X86-64 GENCGC 64-BIT ANSI-CL COMMON-LISP ELF IEEE-FLOATING-POINT
           LINUX LITTLE-ENDIAN PACKAGE-LOCAL-NICKNAMES SB-CORE-COMPRESSION
           SB-LDB SB-PACKAGE-LOCKS SB-THREAD SB-UNICODE SBCL UNIX)

**Comment by Ambrevar** [comment]
There is currently a bug which forces us to show the message in a new
buffer, instead of the actual buffer.
Go back to your buffer, run the command and refresh.

**Comment by hsanjuan** [comment]
> There is currently a bug which forces us to show the message in a new buffer, instead of the actual buffer. Go back to your buffer, run the command and refresh.

The original buffer is not there anymore though... and I can't run the command in it because it does not open in the first place due to the TLS error..

**Comment by Ambrevar** [comment]
I'm confused.  Can you provide and exact recipe?

**Comment by hsanjuan** [comment]
1) M-l https://domain-without-valid-cert:port/
2) Receive TLS error page. `TLS Error: <no_url/name>`. Cannot go back to anywhere (no history). Cannot switch to any `https://domain-without-valid-cert:port/` because it is not there. If I open it, I get exception again.

**Comment by Ambrevar** [comment]
Can you test #806?

**Comment by jmercouris** [comment]
You can now test master :-)

**Comment by hsanjuan** [comment]
Thanks, it works now!
