### ISSUE TITLE
Disallow bindings of disabled mode commands?

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#801]
It's inconsistent that the commands of a mode are not listed if it's off, while
we can call them via a binding.

What if a mode wants to bind to another mode's command?
Should the mode always be enabled?

A mode that wants to bind against a foreign command would need to ensure that the mode is enabled.

Thoughts?

**Comment by jmercouris** [comment]
This does make sense from an API perspective. Will it make the UI too confusing though? Will it make things too cumbersome? Only one way to find out :-)

I agree with your suggestion and think we could give it a try!

**Comment by jmercouris** [comment]
So, my position:

1. mode must be enabled
2. then execute binding

if you bind something to mode that is not enabled: do nothing

**Comment by jmercouris** [comment]
The last statement of "do nothing" is the toughest. I thought a little bit about what if we have the following behavior instead of do nothing:

1. execute binding if there are no interfering bindings in any other key-map

this is however inconsistent behavior and may further confuse users :-D

**Comment by Ambrevar** [comment]
I think it's inconsistent indeed.

It's not hard to prevent bindings from running disabled mode commands:
we just need to leverage the code in `list-commands`.

Question: How do we perform cascaded mode activations?

- The trivial way: have each mode enable their required mode in the
  constructor.

  This raises a question: if we disable the mode, we can't disable the
  dependent modes because they may be used by other modes.

- Can we leverage CLOS?

**Comment by jmercouris** [comment]
We solve this by only binding commands in the modemap of a given mode, therefore this problem is effectively solved. Closing for now, please feel free to reopen if I missed something!

**Comment by Ambrevar** [comment]
I think the original issue was that the user can bind arbitrary commands in a global map, even that of modes that are not enabled.

Should we allow it?

The initial problem is less prone to hit users now that they can easily customize mode keymaps and thus add custom bindings directly to keymaps.

**Comment by jmercouris** [comment]
Yes, we should allow it.

**Comment by Ambrevar** [comment]
Why?

**Comment by jmercouris** [comment]
It would be confusing as to why a keybinding does not work.

**Comment by Ambrevar** [comment]
Isn't it equally confusing to not list commands of disabled modes then?

**Comment by jmercouris** [comment]
One could make that argument. However, I think things are a little nuanced here. If I bind something in my override map, I expect it to work when I press it. When I run M-x, the results I'm given are what I'm given. I don't know, one feels more right than the other to me. I can't give a consistent explanation :-D

**Comment by Ambrevar** [comment]
Then I believe we should document it, maybe with a comment whether we
should change it or not in the future.

**Comment by Ambrevar** [comment]
Documented with 1cace38b19d709f5999aee924bb6510d03637e01.

**Comment by jmercouris** [comment]
Thank you!
