### ISSUE TITLE
Corrupted buffers (cookies-path unbound)

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#804]
I've notived an odd  behaviour for about a month.
After some browser and I think after deleting some buffers, setting the URL for a new buffer fails.

When running from the REPL, we learn the `cookies-path` is supposedly unbound.  Since it has an initform, it's not possible.
But when looking at the new buffer instance that's being handled, we can notice that more than half the slots are missing in the inspector! :(

This smells like a nasty memory corruption.

First, let's find a recipe.  I believe the issue wasn't present a month ago and it seems to be related to buffer deletion and creation.  I know it's a bit vague...

**Comment by Ambrevar** [comment]
This issue happened because I was calling `delete-if-not` instead of `remove-if-not` over closer-mop results... :p  Fixed in 42f327f27317134b551c8fde2ba27ee783c55bee.

**Comment by jmercouris** [comment]
in general I prefer operations that do not modify the cons list in place (potentially destructively)
