### ISSUE TITLE
Minibuffer selection is not updated when input is changed

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#809]
Recipe

- `set-url`
- Select an entry other than the first.
- Insert a term that does not appear in the selected entry, say "foo".

Expected result: selection should be reset to the first entry.
Actual result: a new item is selected (which seems to be the same index as before).

**Comment by jmercouris** [comment]
This should be fixed with: b3e22e34, please let me know if this works!

**Comment by Ambrevar** [comment]
You commit seems wrong, did you rebase?  Here ca0755094f7a5295c00e9157c8bcff82cc925335 fixes it.

**Comment by jmercouris** [comment]
I did rebase, whoops :-)
