### ISSUE TITLE
Pasting text does not mark the tag as "edited"

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#810]
Maybe pages ungrey buttons only when some text input is non-empty.
Example: This GitHub new issue page.  If the title is empty, "Submit new issue" remains greyed out.

The problem:
- Copy some text to the clipboard.
- Open a new issue on GitHub.
- Paste the text into the title line.

Witness that "Submit new issue" remains greyed out.  Inserting any character into the title field ungreys the button.

**Comment by Ambrevar** [comment]
@jmercouris Any idea how to fix this?  Should be a matter of a simple JavaScript call.

**Comment by jmercouris** [comment]
We can manually mark a input area as edited... that *should* fix the problem.

**Comment by jmercouris** [comment]
I've tried variations of:

document.activeElement.dispatchEvent(new Event('x'));

where 'x' is keydown, keyup, changed, change, input

however it only turns on "close and comment" not "comment". Why? no idea...

**Comment by Ambrevar** [comment]
Maybe try with other fields?
E.g. the Patreon login page.
