### ISSUE TITLE
WebKit encountered an internal error 

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#816]
Often (usually after the machine wakes up from sleep) Nyxt is unable to load URLs.  The load hangs for a few seconds, then displays

    WebKit encountered an internal error

After about 1 minute reloading the page works.

Launching Epiphany and loading the same page while Nyxt is stuck at the internal error page works.  
Restartint Nyxt also works.
A factor maybe the number of opened buffers.  I can reproduce this with 10 buffers,

Maybe handling the `:load-failed` signal would help us investigate what's going on.

**Comment by jmercouris** [comment]
If you can figure this out, I would be glad. I get this sporadically... What we would probably benefit from is logging g_errors.

**Comment by Ambrevar** [comment]
What is g_errors?
How do you want to log it?

**Comment by jmercouris** [comment]
`g_errors` is some GTK errors flag that you can set to output errors when GTK is running. We can use the functions I wrote for redirecting std out and std err. https://www.systutorials.com/docs/linux/man/7-gtk-options/

I can't find the original source, I was looking at, but if you look at the linked one, it has some information.

**Comment by jmercouris** [comment]
By setting these flags instead of seeing "internal webkit error" and nothing more, we may be able to see the error, and even a backtrace.

**Comment by Ambrevar** [comment]
We can try with `G_MESSAGES_DEBUG=all` as we used to when we had a platform port :)

**Comment by Ambrevar** [comment]
@jmercouris With how many open buffers do you see this?

**Comment by Ambrevar** [comment]
It'd be very useful to find a recipe.

**Comment by jmercouris** [comment]
The buffer count seems to be irrelevant. I haven't found a way to reproduce it. It may have multiple conditions making it hard for me to discern a pattern.

**Comment by Ambrevar** [comment]
I've made a wrapper:
```sh
export G_MESSAGES_DEBUG=all
~/common-lisp/nyxt/nyxt "$@" >> ~/.local/share/nyxt/nyxt-$(date +%F_%T).log

```

**Comment by Ambrevar** [comment]
Looking at the log after a couple of days does not reveal anything special.

It seems that disabling Tor helps a lot reducing this issue.  But this is not good: other browsers (e.g. Chromium) don't suffer from this over Tor.

**Comment by jmercouris** [comment]
What about artificially creating more network traffic errors on your system, does that increase the liklihood of this failure?

**Comment by Ambrevar** [comment]
Which traffic errors?  How?

**Comment by jmercouris** [comment]
For example, URLs that do not resolve. If you put a page full of many broken URLs on it, does it increase the liklihood of this failure? What about a page with a lot of javascript? What about both? There must be some way that we can isolate this...

**Comment by aartaka** [comment]
Okay, here's what I have for recipe of the "WebKit encountered an internal error" for cl-webkit loaded from source.

**Precise recipe to reproduce the issue**
- Clone the cl-webkit repo (tested on two last commits, namely 60a0a2926616c08aa356349f1c72b87a049da564 and c023dad817e8ff031073bf2c76119707e73992a4)
- Open emacs in the environment with the necessary packages (lack of some crucial package can be the reason there):
`guix environment --ad-hoc glib glib-networking gdk-pixbuf cairo pango gtk+ webkitgtk -- emacs`
- Run `sly`
- Input the following commands:
```
(asdf:load-system :cffi)
(progn
  (push #p"~/git-cloned/cl-webkit/webkit2/" asdf:*central-registry*)
  (setf cffi:*foreign-library-directories*
        `("/gnu/store/52sj1cwg1qwygn23dny58ikwq2615210-glib-2.62.6/lib/"
          "/gnu/store/513h0fjz1nv6wighlc7j2qb82xhdqj9a-glib-networking-2.62.2/lib/"
          "/gnu/store/0pf9k3jf77hmmhpxpsg41dd2cawkgjp4-gdk-pixbuf-2.40.0/lib/"
          "/gnu/store/1ncbjbnv3plfb81wmmzbqak2xkvklwvf-cairo-1.16.0/lib/"
          "/gnu/store/pgsq0zg5mmrns71qq1wk24hwzz01x0q5-pango-1.44.7/lib/"
          "/gnu/store/3q8kin8ly9xk88jmj3m6wwhjsxn0xj5i-gtk+-3.24.20/lib/"
          "/gnu/store/wlm9xmy3sqnlksvapip1pjg3yhvdbl0k-webkitgtk-2.28.1/lib/")))
;; I haven't found a better way of referring to the libraries yet
```
- Open the demo/simple-browser.lisp, cimpile the functions and run `(do-simple-browser-main)`. 

**Information**
- OS name+version: 
Guix System
``` 
$ guix describe
]8;;file://paranoidal/var/guix/profiles/per-user/aartaka/current-guix-28-link\Generation 28	Jun 27 2020 16:30:24]8;;\	(current)
  nonguix c3ea219
    repository URL: https://gitlab.com/nonguix/nonguix
    branch: master
    commit: ]8;;https://gitlab.com/nonguix/nonguix/commit/c3ea219253d829c524bc41ea7b20ceddfb0ba599\c3ea219253d829c524bc41ea7b20ceddfb0ba599]8;;\
  guix 65d95e5
    repository URL: https://git.savannah.gnu.org/git/guix.git
    branch: master
    commit: ]8;;https://git.savannah.gnu.org/cgit/guix.git/commit/?id=65d95e5d852e47343b9acc1717918c9db7364c01\65d95e5d852e47343b9acc1717918c9db7364c01]8;;\

$ uname -a
Linux paranoidal 5.4.47 #1 SMP 1 x86_64 GNU/Linux
```
- Graphics card and driver:
``` 
$ lspci -v
...
00:02.0 VGA compatible controller: Intel Corporation UHD Graphics 620 (rev 07) (prog-if 00 [VGA controller])
	Subsystem: ASUSTeK Computer Inc. Device 1c50
	Flags: bus master, fast devsel, latency 0, IRQ 126
	Memory at ee000000 (64-bit, non-prefetchable) [size=16M]
	Memory at d0000000 (64-bit, prefetchable) [size=256M]
	I/O ports at f000 [size=64]
	Expansion ROM at 000c0000 [virtual] [disabled] [size=128K]
	Capabilities: <access denied>
	Kernel driver in use: i915
...
```

**Logs**
There's only one log message that appears right in the moment of the error:
`Jul  1 12:46:04 localhost vmunix: [ 5418.996034] traps: WebKitNetworkPr[3451] trap int3 ip:7f39c4b9e321 sp:7ffff83b5320 error:0 in libglib-2.0.so.0.6000.6[7f39c4b66000+7d000]`

**Comment by aartaka** [comment]
This happens to cl-webkit compiled from source. Nyxt works well. Surprisingly, cl-webkit from Guix worked well until today -- now it fails with the same error. It makes me think that the problem is in one of the dependencies and not in cl-webkit itself.

**Comment by Ambrevar** [comment]
Can you share the Guix commits that work and that do not?

**Comment by aartaka** [comment]
It's the same Guix commit, it's only the installed packages that could've changed.

**Comment by Ambrevar** [comment]
Which installed packages?  Are you on a foreign distribution?

Can you reproduce in a --pure guix environment?

**Comment by aartaka** [comment]
Okay, removing the webkitgtk package from the base profile and reinstalling cl-webkit resolved the problem. I guess it really was a dependency conflict or something else, external to the cl-webkit, in my case.

I'm sorry about confusing you, I guess my problem is not directly connected with what you've encountered.

**Comment by Ambrevar** [comment]
This is interesting nonetheless.
What do you call "base profile"?

I don't see how the presence of webkitgtk could raise this issue.  I'd
like to understand why...

**Comment by aartaka** [comment]
> This is interesting nonetheless. What do you call "base profile"?

Default profile, kept in `~/.guix_profile`, I mean.

**Comment by Ambrevar** [comment]
I haven't encountered this in weeks, if not months.  @aartaka?
If you haven't, we can close this I guess.

**Comment by aartaka** [comment]
I haven't encountered it for several months either :)

**Comment by Ambrevar** [comment]
Thanks for the feedback!
