### ISSUE TITLE
Overhaul URL dispatcher (magnet support, customizable)

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#817]
Now that our request-resource-hook is almighty, we can move the URL dispatch from `parse-url` to `request-resource-hook`.

Ideally, we should make it in a way that's easily customizable.
For instance, we need to derive a way to let the user customize which Torrent client to use to open magnet links.
Maybe there is nothing to do beside defining a handler that checks which Torrent client is available and loads the magnet link appropriately.

In the end, the following expression can be removed from `parse-url`:
```lisp
((str:starts-with? "magnet:" input-url)
             (log:debug "Open magnet link with external application.")
             (ignore-errors
              (uiop:launch-program (list "xdg-open" input-url))
              (nyxt/minibuffer-mode:cancel-input)))
```

**Comment by aartaka** [comment]
I'm thinking of a slot in the `browser` class, but I'm not sure about it's type:
- List, like the `search-engines` slot, with the same idea of the user-appendable list of `protocol` objects. But the problem is that one may want to redefine the built-in `protocol`s (whatever the reason may be) and struggle with that because there will be a need in calling `(remove-if (lambda (protocol) (string= "http" (scheme protocol))) %slot-default)` or something like that.
- Hash table, having the essential scheme names (e.g. `"http"`, `"https"`, `"mailto"`, etc.) as keys and `protocol` objects as values. This will ensure that there's exactly one action for the given protocol and store them in one place. The downside is quirky customization -- I can't imagine an easy way of redefining this slot without the knowledge of how has tables work.

The first looks better to me, given that lists of `protocol` objects (the name is not set in stone, so you can suggest a better name, actually!) has an analogous one (`search-engines`) and is easier to manipulate than a hash table, even with the non-uniqueness problem (is there a set-like data structure in `fset` that we can use implicitly to ensure uniqueness, or should we define a list-based uniqueness-preserving type?).

I imagine `protocol` object with 3 slots so far:
- `scheme` slot with a literal `string` to compare the URL scheme against
- `type` slot with either `:nyxt-command`, `:shell-command` or `:lambda` value:
    - `:nyxt-command` can be a short name of the command as either string or symbol (e.g. `"tutorial"`, `"manual"`).
    - `:shell-command` is a list of strings or string to pass to `uiop:run-program`, with the consequence of request cancellation and opening the URL in the external application
    - `:lambda` (again, this sounds vague, so I'm open to discussion) is a plain `lambda` to call, to implement more complex ideas, like picking the right program to open different file formats, with something like. I guess we need to specify a way of forwarding/canceling the request there, in the same way it's done for `request-resource-hook` with these `:forward` and `:stop` keywords.
- Finally, the `action` slot that will contain the value specified by the `type` slot.

Having three different slots (`nyxt-command`, `shell-command`, `lambda`) instead of the `type` and `action` slots sounds better from the side of the user interaction, but harder to work with, because only one of the slots should be defined, and we'll need to filter them to ensure that it stays this way.

I'm not worried about the function to handle this, because it seems to be a simple handler for `request-resource-hook` that will just parse the list of the protocols and use the most suitable one in case it finds it, and shout in panic otherwise :) However, if you have an idea of how it can go wrong, I'd like to hear that!

Let me know what you think of this design!

**Comment by Ambrevar** [comment]
Pull master, I've fixed a few things to pave the way for this change.

Now this is what I have in my init.lisp to support magnet URI:

```
(defun magnet-handler (request-data)
  (let ((uri (url request-data)))
    (if (string= (quri:uri-scheme uri) "magnet")
        (progn
          (echo "Opened magnet link in Transmission.")
          (uiop:launch-program (list "transmission-remote" "--add" (object-string uri)))
          (values request-data :stop))
        request-data)))
```

We could provide a handler that dispatched over various well-known
BitTorrent client.  Maybe enable it by default.

What about other resources (e.g. mailto:)?  Can we make configuration shorter and more
convenient to the user?

Your suggestion seems to be going in that direction.  But is it really
shorter though?  I think the next thing to do to go forward is to write
configuration snippets to better see how short and convenient they can
be.

Let's see with `mailto:`.  It would be essentially the same as for
magnet links:

```
(defun mailto-handler (request-data)
  (let ((uri (url request-data)))
    (if (string= (quri:uri-scheme uri) "mailto")
        (progn
          (echo "Compose email with FOO.")
          (uiop:launch-program (list "FOO"(object-string uri)))
          (values request-data :stop))
        request-data)))
```

This pattern is probably going to come up over and over, so let's
abstract it away in a simple function:

```
(defun mailto-handler (request-data)
  (map-scheme-to-action (url request-data)
    :scheme "mailto"
    :type :shell-command
    :action (list "FOO" "maybe-other-args")))
```

With your suggestion, we could have a structure that maps the scheme to
the program, so that would leave us with

```
'(:scheme "mailto"
  :type :shell-command
  :action (list "FOO" "maybe-other-args"))
```

So it would save 2 lines.

But is it worth it?  The problem is that this "slot abstraction" is
limited to mapping a scheme to an action type.  What about other things,
like converting the scheme, discarding parts of the path, etc?

Besides, it's yet another abstraction for the user to understand and for
us to support.

The handler approach is more general, a bit simpler from an abstraction
point of view, and a bit easier to maintain.

I'm a bit unsure at this point.

About your questions:

> - List, like the `search-engines` slot, with the same idea of the user-appendable list of `protocol` objects. But the problem is that one may want to redefine the built-in `protocol`s (whatever the reason may be) and struggle with that because there will be a need in calling `(remove-if (lambda (protocol) (string= "http" (scheme protocol))) %slot-default)` or something like that.

Not necessarily, we could give precedence to the first match.

> - Hash table, having the essential scheme names (e.g. `"http"`, `"https"`, `"mailto"`, etc.) as keys and `protocol` objects as values. This will ensure that there's exactly one action for the given protocol and store them in one place. The downside is quirky customization -- I can't imagine an easy way of redefining this slot without the knowledge of how has tables work.

Fset make it easier to work with hash tables, should that be really
advantageous from the init.lisp point of view.

> The first looks better to me, given that lists of `protocol` objects (the name is not set in stone, so you can suggest a better name, actually!) has an analogous one (`search-engines`) and is easier to manipulate than a hash table, even with the non-uniqueness problem (is there a set-like data structure in `fset` that we can use implicitly to ensure uniqueness, or should we define a list-based uniqueness-preserving type?).

`pushnew` can do that, but this would be assuming that the user would be
using it, so it does not work.
I don't think it's worth defining our own data structure for this when
Fset or hash-tables do the job.  Or, as said above, changing the logic
to "first match first use".

>     - `:lambda` (again, this sounds vague, so I'm open to discussion) is a plain `lambda` to call, to implement more complex ideas, like picking the right program to open different file formats, with something like. I guess we need to specify a way of forwarding/canceling the request there, in the same way it's done for `request-resource-hook` with these `:forward` and `:stop` keywords.

I think in this case the lambda adds no benefit over what
request-resource-hook already provides, so I'd not bother with his
option.  If you have a good use case, please prove me wrong :)

> Having three different slots (`nyxt-command`, `shell-command`, `lambda`) instead of the `type` and `action` slots sounds better from the side of the user interaction, but harder to work with, because only one of the slots should be defined, and we'll need to filter them to ensure that it stays this way.

Without lambda, it would be only two.
Then you can make it unique by having just one `action` slot: if it's a
list or a string, it's a shell command, otherwise it's a nyxt-command.

**Comment by aartaka** [comment]
> But is it worth it? The problem is that this "slot abstraction" is limited to mapping a scheme to an action type. What about other things, like converting the scheme, discarding parts of the path, etc? Besides, it's yet another abstraction for the user to understand and for us to support. The handler approach is more general, a bit simpler from an abstraction point of view, and a bit easier to maintain. I'm a bit unsure at this point.

That's a good critique. The disadvantage of the handlers is that they can be scattered around the config would have the same structure (and `(map-scheme-to-action ...)` is going to become a part of this structure, if it'll find it's way into upstream) and same imperative actions. *Imperative* is the keyword here. `define-configuration` is a declarative expression, and having short, declarative, straight-to-the-point protocol dispatching is in line with its declarativity. 

Yes, writing handlers is a simple matter, but writing handlers for "javascript", "mailto", "magnet", "irc"/"irc6"/"ircs", "cvs", "git", "gopher", "imap", whatever... is too much of a repetitive imperative code. Having a stripped-down list of `(make-protocol "mailto" :type :shell-command :action "mail-program")` is cleaner and it has no extraneous details. 

The URL manipulation can fit this mechanism too -- with the help of the `:lambda` parameter. We can pass the URL to this `lambda` and wait for it's result -- it'll do the thing.

>> - List, like the `search-engines` slot, with the same idea of the user-appendable list of `protocol` objects. But the problem is that one may want to redefine the built-in `protocol`s (whatever the reason may be) and struggle with that because there will be a need in calling `(remove-if (lambda (protocol) (string= "http" (scheme protocol))) %slot-default)` or something like that.

> Not necessarily, we could give precedence to the first match.

That's a good idea! `member` and `find` are a built-in, simple solutions for this list search!

> I think in this case the lambda adds no benefit over what request-resource-hook already provides, so I'd not bother with his option. If you have a good use case, please prove me wrong :)

The necessity of URL manipulation mentioned earlier asks for `:lambda` or something equivalent, but I really can't come up with a specific example now. One certain advantage is that it is less wordy and doesn't need to extract the URL -- it's already there as its argument.

> Without lambda, it would be only two. Then you can make it unique by having just one `action` slot: if it's a list or a string, it's a shell command, otherwise it's a nyxt-command.

While I don't agree with the idea of removing `:lambda` because of its flexibility, this sounds good to me -- type is the solution! If the `action` is string/list -- it's a shell command, if it's fuction object -- just `funcall` it! That makes things even simpler.

**Comment by aartaka** [comment]
If we used custom classes for every protocol, the problem of first-match-first-use could have been be solved through the use of the `call-next-method`, but that's harder to work with, I guess. How about having an extended list of keywords for `lambda` (in case we'll stick to it)?
- `:forward` gives it to the renderer
- `:stop` aborts the request
- `:next` looks for the next `protocol` object with the same scheme (somewhat like `call-next-method`)
- `:repeat` (not an obvious name) call the dispatching function on the resulting URL whose scheme may have been altered

**Comment by aartaka** [comment]
Anogher problem with what I've proposed: what if we'll need to format the URL in some way before passing it to the shell command? Will control-strings (like in `format`) suffice there or do we need to make it `lambda`-like to allow more complex modifications?

**Comment by Ambrevar** [comment]
> The URL manipulation can fit this mechanism too -- with the help of the `:lambda` parameter. We can pass the URL to this `lambda` and wait for it's result -- it'll do the thing.

Then we can be more general the mere scheme matching by allowing for
custom predicates against the URI.

Say, the `match-scheme` is a higher-order function that returns a
predicate for URIs.

Your example

```
(make-protocol "mailto" :type :shell-command :action "mail-program")
```

becomes
```
(make-protocol (match-scheme "mailto") :type :shell-command :action "mail-program")
```

Without losing generality, we can match URIs against anything:

```
(make-protocol (match-host "reddit.com") :type :lambda :action (switch-to-old-reddit))
```

With the above, I agree keeping :lambda is a good idea.

With this new approach, I suppose that it does not make sense to have
methods over URI scheme classes.

About the URI modification: either provide a uri->uri transformer slot,
or we resort to the lambda as above to do the job:


```
(make-protocol "mailto"
 :type :shell-command
 :transformer #'transformed-uri
 :action "mail-program")
```

or

```
(make-protocol "mailto"
 :type :lambda
 :action (lambda (uri)
          (uiop:launch-program (list "mailclient" (transformed-uri uri)))))
```

**Comment by aartaka** [comment]
Well, given that a lot of shell comands will need URL transformation, it's either the `:transformer` option or removing the `:shell-command` type at all, and staying with a mere `lambda`. But then it's like going back to handlers,  with the difference being only that it's concentrated in one place and gets rid of everything but URL.

The idea with the higher-order `match-*` functions is good, but isn't it too general? If it can match `uri-host` or whatever, then, should it really be in the protocol-handling, `uri-scheme`-centered code?

**Comment by aartaka** [comment]
But, looking more at the initial message and the issue name, I'd say that `match-*` functions fit the idea.

**Comment by aartaka** [comment]
Somewhat off-topic: should we enable an unofficial `javascript:` protocol for a quick evaluation of JS expressions? It's used extensively by some websites I've encountered, but it can be dangerous. Other browsers seem to evaluate it in any case, but I'm not sure about this.

**Comment by Ambrevar** [comment]
> Somewhat off-topic: should we enable an unofficial `javascript:` protocol for a quick evaluation of JS expressions? It's used extensively by some websites I've encountered, but it can be dangerous. Other browsers seem to evaluate it in any case, but I'm not sure about this.

I don't know about this.  Would you happen to know about any resource we
can consult to learn more about this?

**Comment by aartaka** [comment]
Unfortunately, no. I can look into it this week and see whether we can enable it.

**Comment by aartaka** [comment]
Is `condition` a good name for this `match-*` function slot? It sounds a bit ambiguous to me, given that `condition` term is connected to condition system of CL. `predicate` maybe?

**Comment by jmercouris** [comment]
I would be consistent with other CL functions and call it `:test`.

**Comment by aartaka** [comment]
Hmmm, does this convention work for class slots too?

**Comment by Ambrevar** [comment]
I don't think there is such a convention, but why not using it?
It's short and meaningful, sounds good to me :)

**Comment by aartaka** [comment]
I think it's worth adding the `automatic-p` slot, to disambiguate between dispatchers that the user wants to work in the background (like `old-reddit-handler`) and the ones that provide some choice (e.g., having several Torrent clients and being able to choose between their dispatchers when it's necessary). This will free the user (and ourselves) from the need to write a minibuffer-related boilerplate code.

**Comment by Ambrevar** [comment]
True, some actions might bring up a minibuffer (in a nyxt-command).
But what would the role of `automatic-p` be?

**Comment by aartaka** [comment]
I mean, user can make several similar dispatchers for one specific situation (again, having several Torrent clients, for example) and using all of them automatically will be pointless -- user would need to choose which one to activate. Or do we imply that this mechanism of URL-dispatching is only for automation and customization?

Well, the idea of giving user a choice between several options came to me because of the idea that we can look different clients up and choose between them, but now it seems that this mechanism is for automation of web-routine, so there's no neccessity in having an obvious `automatic-p` flag that would say the obvious and, probably, will be `nil` only in one percent of cases. Writing a custom user-interacting handler for `request-resource-hook` would fill this percent easily, so it's not a  problem.

**Comment by aartaka** [comment]
By "this mechanism" I mean mechanism of customizable URL-dispatching.

**Comment by aartaka** [comment]
These status keywords that `request-resource-hook` handlers should return as a second value were not obvious to me as a Nyxt user at first. Would it be simpler if we'd have URL-dispatchers return `nil` for request blocking and new URI for request forwarding? It sounds simpler that keywords to me, but it's a new concept to learn, so I'm in doubt.

What sounds better to you -- keeping it simple, but slightly inconsistent, with `nil` and URI as meaningful return values, or sticking to the old format of `(values request-data :stop)` for blocking and `request-data` for forwarding?

**Comment by aartaka** [comment]
I'd go with `nil`/URI, because it's more concise and simple. And it's easier to understand, I guess, so anyone could write simple URL-dispatchers without knowledge of the `request-resourse-hook` guts -- not that it's hard, but it's yet another layer of required knowledge (it's not only `request-resource-hook`, but it's also `request-data` class and, maybe, even `on-signal-decide-policy` function) for someone who just wants to change one piece of behavior on one particular URL type.

**Comment by aartaka** [comment]
Where to put these helper `match-*` functions (I came up with three so far: `match-scheme`, `match-host`, and `match-file-extension`)? utility.lisp sounds like a place for them.

**Comment by Ambrevar** [comment]
> Where to put these helper `match-*` functions (I came up with three so far: `match-scheme`, `match-host`, and `match-file-extension`)? utility.lisp sounds like a place for them.

I'd like to get rid of utility.lisp, which useless name is an open door
to end up with an ever-growing mix-bag of everything :)

I'd say leave them next to the request-resource handler for now.

**Comment by Ambrevar** [comment]
About the return type of the request-resource-handlers: The problem here is that we don't have 2, but 3 options!
- Forward request-data to next handler.
- Stop hook and forward request-data to renderer.
- Stop hook and do nothing.

So we need a way to tell Nyxt about both the new request-data and what we want to do with it.  Which is why we need this `(values request-data :forward/:stop)`.  Does that make sense?  Can you think of something simpler?

**Comment by Ambrevar** [comment]
A tangent question is: do we ever need to "stop hook and forward to renderer"?  I'm not sure.  Maybe I over-engineered here.

**Comment by Ambrevar** [comment]
About the multiple Torrent clients:
- Either we have 1 handler that checks which client is found on the system and calls the appropriate command;
- Or (more flexible?) we have 1 handler _per_ client.

In all cases, we stop the hook on the first client that is found on the system.  I don't think there is need for interactivity here.  In case the user has 2 clients installed, they can choose the want they want to use by default with the 2nd approach by picking the right handler.

**Comment by aartaka** [comment]
> A tangent question is: do we ever need to "stop hook and forward to renderer"? I'm not sure. Maybe I over-engineered here.

I don't see an obvious application for this here, except for some error-messages dependent on what's inside the `request-data`. But this can be done in some other ways, like in `on-signal-load-failed-with-tls-error`, maybe. Given that, there's no need for this option at least in this user-facing feature of URL-dispatching.

**Comment by aartaka** [comment]
Should there be a manual/tutorial entry for `url-dispatcher` (that's the name I've ended up with)? It'd probably be quite useful to know when learning Nyxt. 

Also, as I mentioned, the handling of the `request-resource-hook` is non-obvous and underdocumented. Should it be in the manual too? Opening an "Underdocumented APIs" issue can suit this question and discussion better though.

**Comment by Ambrevar** [comment]
As a first step I suggest we work on a patch that reimplements
request-resource with only 2 return options.  Let's review this patch
and see if we are not missing anything.

Then we can work out the documentation.

Would you be interested in sending such a patch?
If that's too much work let me know, I'll do it.

**Comment by aartaka** [comment]
> As a first step I suggest we work on a patch that reimplements request-resource with only 2 return options. 

`nil` and full `request-data` are the options here, is that right?

> Would you be interested in sending such a patch? If that's too much work let me know, I'll do it.

It's pretty in line with what I'm doing about `url-dispatcher`s, and, I guess, it's not a lot of work. I'll send the patch, probably today.

**Comment by Ambrevar** [comment]
> `nil` and full `request-data` are the options here, is that right?

Yes.

> It's pretty in line with what I'm doing about `url-dispatcher`s, and, I guess, it's not a lot of work. I'll send the patch, probably today.

Great, thanks!

**Comment by aartaka** [comment]
Okay, the immediate problem is that the handlers that rely on the validity of the `request-data` object passed to them from other handlers now need to check its validity, and that's additional code. Is there an ability to inject `nil`-checks into the combination of handlers or do we need to live with that somehow?

**Comment by aartaka** [comment]
I found a solution for that, I guess. It can be solved by replacing the `hooks:run-hook` with the `hooks:run-hook-with-args-until-failure` in the `request-resource-hook`-related code.

**Comment by Ambrevar** [comment]
Indeed, the hook required a special handler because it has 3 possible
output options.
If we go for a (or quri:uri null) return value, we can simply use the
run-hook-with-args-until-failure composition function.

**Comment by aartaka** [comment]
Well, it's not only about the URL, so the return type will be `(or request-data null)`, I guess. But thanks for reminding me about the strict hook typing, I've forgotten about that!

**Comment by aartaka** [comment]
Hmm, I see two options on the `url-dispatcher`s application:
- Re-use hooks API and create new `uri->uri` hook with all the suitable `url-dispatcher`s as handlers, when the need arises, resulting in a weird, but extremely solid code in one sub-clause of `request-resource`.
- Use a dedicated function that will mostly duplicate the hooks functionality, while enabling good logging that would be quirky to enable in the first option. Also, because it's a re-implementation, it will possibly be buggy in a non-obvious-way.

What'd be the priority here? I'd go with a first way and its robustness, but for now I haven't found a readable enough expression for this functionally-styled hook creation and, especially, logging. Is logging of URL-dispatching even necessary?

**Comment by Ambrevar** [comment]
To correct myself: It was not run-hook-with-args-until-failure, because the hook needs to compose the handlers.  Sorry if that confused you.

**Comment by Ambrevar** [comment]
@aartaka About your last comment, I'm not following, sorry.  Is there a problem when logging from hooks?  I see log messages here on my end.  Can you specify?

**Comment by aartaka** [comment]
No, there's no problem with logging in hooks, I just was unable to find a readable way of creating new hook with `url-dispatcher`'s `action`s as handlers and with a good logging until today.

I guess I'm shifting to your idea of syntactic abstraction on top of hooks now. Would it be appropriate if we'll have constructor-like expressions (e.g. `(make-url-dispatcher (match- ...)...)`) in the `url-dispatchers` slot of `*browser*` that will in fact generate handlers for a `uri->uri` hook created in the process of dispatching? Is it worth doing it this way and explaining the mechanism of the transformation in docstrings? Or is it a generally bad way to do things? Hiding something from user with macros is not a good practice, as I know, but abstracting things out can be useful there.

**Comment by aartaka** [comment]
For now this constructor-like function (it's not even a macro!) looks like this:
``` lisp
(defun url-dispatching-handler (test action &optional (description ""))
  "Returns a URL-dispatching handler that, if appended to the `url-dispatchers'
slot of `browser', will automatically apply its ACTION on the URLs that conform to TEST."
  (make-handler-uri->uri
   #'(lambda (url)
       (if (funcall test url)
           (let ((new-url (funcall action url)))
             (log:info "Applied \"~a\" URL-dispatcher on \"~a\"and got \"~a\""
                       description (object-display url) (object-display new-url))
             new-url)
           url))))
```

Composing these with `combine-hook-until-nil` gives a neat and close-to-other-code way of URL-dispatching.

**Comment by aartaka** [comment]
> To correct myself: It was not run-hook-with-args-until-failure, because the hook needs to compose the handlers. Sorry if that confused you.

It's okay, I just haven't seen a difference between combining and composing. Well, looking at the code of `combine-hook-until-failure` used in `run-hook-with-args-until-failure` reveals the difference, so thanks for pointing that out :)

**Comment by Ambrevar** [comment]
About the constructor:
- Use funcall-safely.
- What about the other `action` type we mentioned previously?  I case you want to `etypecase` against action and run the shell command, or launch-program as appropriate.
Otherwise looks good to me!

**Comment by aartaka** [comment]
Well, other types are not that necessary now:
- `shell-command` usually would need some formatting of the URL, and that's quirky -- having a simple `uiop:launch-program` or `launch-and-notify` inside a `action` is more flexible and, I guess, will be used more frequently. The only thing that can simplify it even more is to have a fuction/macro like StumpWM's `run-shell-command` that'd take care of creating threads, notifications and all that stuff.
- `nyxt-command` can be useful here, but, then, it can be used more flexibly if we won't pass it as string. One example I'm thinking of is redirecting the links in the manual to function/class/whatever docstirngs via the query of the URL. This'd be much more flexible if it'll be a lambda.

The only downside is that `lambda` is relatively wordy. I wish lambda shortened syntax from Arc (i.e. `[do-something-with _] -> (lambda (_) (do-something with _))`) was there...

**Comment by Ambrevar** [comment]
Artyom Bologov <notifications@github.com> writes:

> Well, other types are not that necessary now:
> - `shell-command` usually would need some formatting of the URL, and that's quirky -- having a simple `uiop:launch-program` or `launch-and-notify` inside a `action` is more flexible and, I guess, will be used more frequently. The only thing that can simplify it even more is to have a fuction/macro like StumpWM's `run-shell-command` that'd take care of creating threads, notifications and all that stuff.

UIOP has a bunch of escape functions.  But you don't even need that if
you pass a list to uiop:launch-command.  This could be convenient in my
opinion.  Example:

(url-dispatching-handler (match-scheme "magnet") ("transmission-remote" "--add"))

Also not that we already have some support for libnotify.  Look for
"notify" in utility.lisp.

> The only downside is that `lambda` is relatively wordy. I wish lambda shortened syntax from Arc (i.e. `[do-something-with _] -> (lambda (_) (do-something with _))`) was there...

I'm sure there is a Common Lisp library for that! :)
We don't need to use it ourselves, but the user can from their init.lisp.

Also Scheme has the `λ` and closure has `#(... %...)`.

**Comment by aartaka** [comment]
> UIOP has a bunch of escape functions. But you don't even need that if you pass a list to uiop:launch-command. 
> This could be convenient in my opinion. Example: 
> (url-dispatching-handler (match-scheme "magnet") ("transmission-remote" "--add")) 

Are we implying that URL should be appended to the end of this command list? I guess that'll be pretty intuitive then.

**Comment by Ambrevar** [comment]
> Are we implying that URL should be appended to the end of this command list? I guess that'll be pretty intuitive then.

Yes.  Alternatively, we could pass a let-bound symbol like `%uri`.

**Comment by aartaka** [comment]
> Yes. Alternatively, we could pass a let-bound symbol like `%uri`.

Introducing implicit bindings can be dangerous, so I'm in doubt. It looks good though.

**Comment by Ambrevar** [comment]
> Introducing implicit bindings can be dangerous, so I'm in doubt. It
> looks good though.

It is, but it should work well enough in the context of user
configuration.  Implicit bindings are bad for libraries, my opinion is
that they are OK here.
