### ISSUE TITLE
Inconsistent protocol for submodules

### ISSUE THREAD

**Issue by marceltransier** [atlas-engineer/nyxt#818]
https://github.com/atlas-engineer/nyxt/blob/04795c17b2970e7d3c8ccf0d822cde223aea78bd/.gitmodules#L6

Is the ssh protocol used for a specific reason?
I'd suggest to use http for this submodule as well for two reasons:
1) consistency
2) Using ssh users have to have their pubkey uploaded to github to build the project (e.g. via the AUR)

**Comment by Ambrevar** [comment]
Oops!  This is a mistake indeed.
Fixed in f1cce5f46ced51e53db67d17a094506e806ffc03.

Good catch!

**Comment by marceltransier** [comment]
Thanks! :)
