### ISSUE TITLE
Can't find manual from Ubuntu stable release

### ISSUE THREAD

**Issue by spenczar** [atlas-engineer/nyxt#820]
**Describe the bug**

I just installed Nyxt (as Next) on Ubuntu, following the instructions on the website. I downloaded `next_1.5_amd64.deb`, and then ran `sudo apt install ./next_1.5_amd64.deb`.

I opened the browser and used it for a bit. Then, I wanted to learn how to close a tab. I followed the link on the help page, and it sent me to https://nyxt.atlas.engineer/documentation, which claims that the manual is in the browser.

This doesn't seem to be true in the released version downloaded from https://nyxt.atlas.engineer/static/release/next_1.5_amd64.deb.

**Precise recipe to reproduce the issue**

Download https://nyxt.atlas.engineer/static/release/next_1.5_amd64.deb and install it. Open next, run M-x help, and try to learn the keybindings for closing a tab.

**Information**
- OS name+version:
`Linux swnelson-laptop 5.4.0-39-generic #43-Ubuntu SMP Fri Jun 19 10:28:31 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

- Graphics card and driver:
`n/a`

- Desktop environment / Window manager name+version:
`i3 version 4.17.1 (2019-08-30) © 2009 Michael Stapelberg and contributors`

- How you installed Nyxt (Guix pack, package manager, build from source):
`Downloaded deb and installed it.`

- Information from command copy-system-information:

  If you can't run copy-system-information, please provide the following:
  - Nyxt version (from =M-x nyxt-version= or =nyxt --version=):
`1.5.0`
  - Lisp implementation/version (if built from source):
`n/a`
  - Kernel name+version:
`?`
  - WebKitGTK+ | QtWebEngine version:
`?`

**Output when started from a shell**

```Next version 1.5.0
 <INFO> [10:56:39] next remote.lisp (initialize-instance :after remote-interface) -
  D-Bus addresses: (#<Unix socket address: "/run/user/1000/bus">)
 <INFO> [10:56:39] next remote.lisp (initialize-instance :after remote-interface) -
  Next already started, requesting to open URL(s) (https://next.atlas.engineer/start).
```

**Comment by Ambrevar** [comment]
@jmercouris Mind updating the web page with the content from MANUAL.org?

**Comment by jmercouris** [comment]
Dear Spencer,

sorry for the trouble! I've updated the web page to reflect the changes between 1.5 and 2.0. Basically in 1.5 we did not have the manual embedded into Nyxt, afterwards, we do :-)

**Comment by spenczar** [comment]
Great, thanks for the quick fix!
