### ISSUE TITLE
C-n and C-p support for menu selections

### ISSUE THREAD

**Issue by divansantana** [atlas-engineer/nyxt#821]
C-n and C-p don't work out the box for the popup selection list.

So C-l then I'd expect C-n to move down an entry to select it.

- next 1.5.0
- guix package on guix system

**Comment by Ambrevar** [comment]
What do you mean with "popup selection list"?
Are you talking about the minibuffer?
If so, it should work.

Can you provide a recipe and tell us about your desktop environment,
keyboard layout, the input method if you use one.

**Comment by divansantana** [comment]
OK I see some issue. 

Yes minibuffer, sorry.

EXWM, it seems when it's in line mode, then C-n and C-p are still being passed through to nyxt yet when I hit C-l and then C-n it scrolls the page down instead of moving the item one down the minibuffer list.

Switching to char-mode resolves the issue. Perhaps a exwm thing?

**Comment by divansantana** [comment]
Am using dvorak plus kmonad too.

**Comment by Ambrevar** [comment]
Which version of Next?  How did you install / build it?

**Comment by divansantana** [comment]
Info below. 

**Information**
- Guix system
- 00:02.0 VGA compatible controller: Intel Corporation HD Graphics 620
  (rev 02) (prog-if 00 [VGA controller]) via i915
- GNU Emacs 26.3 (build 1, x86_64-unknown-linux-gnu, GTK+ Version
  3.24.20)
- emacs exwm 0.24
- via guix manifest on guix system

  - Nyxt version 1.5.0
  - Linux swift 5.4.46 #1 SMP 1 x86_64 GNU/Linux
  - WebKitGTK+ | QtWebEngine version: /gnu/store/s0x7fr7scmrnzryy8jnbai8invjgjsry-next-gtk-webkit-1.5.0/bin/next-gtk-webkit

**Output when started from a shell**

```
ds@swift ~ $ next -Q
Next version 1.5.0
 <INFO> [23:38:56] next remote.lisp (initialize-instance :after remote-interface) -
  D-Bus addresses: (#<Unix socket address: @"/tmp/dbus-wZ8sQagaSo">)
 <INFO> [23:38:56] next remote.lisp (initialize-instance :after remote-interface) -
  Bus connection name: :1.14800
 <INFO> [23:38:56] next port.lisp (run-program port) -
  Current directory: /home/ds/
 <INFO> [23:38:56] next port.lisp (run-program port) -
  Platform port path: /gnu/store/s0x7fr7scmrnzryy8jnbai8invjgjsry-next-gtk-webkit-1.5.0/bin/next-gtk-webkit
 <INFO> [23:38:56] next port.lisp (run-program port) -
  Platform port arguments: NIL
 <INFO> [23:38:56] next port.lisp (run-program port) -
  Platform port log file: /home/ds/.local/share/next/next-gtk-webkit.log
 <WARN> [23:38:56] next remote.lisp (current-buffer) -
  No active window, picking last active buffer.
```

**Comment by Ambrevar** [comment]
This should be fixed with master.

**Comment by Ambrevar** [comment]
@divansantana Do you still have this issue on master?

**Comment by divansantana** [comment]
@Ambrevar 

I have the issue on master still.

The issue, launch nyxt, but default this X window is in line-mode not
char-mode.

Hitting C-space, and trying to navigate up or down using C-n and C-p
still scrolls the web page and doesn't move the selection up and down
in the minibuffer.

After selecting emacs-mode and repeating it still does this.

Once I switch to char-mode C-n and C-p work as expected.

I'm beginning to think this is because of this in my emacs config:

```elisp
  (setq exwm-input-simulation-keys
        '(
          ([?\C-p] . [up])
          ([?\C-n] . [down])
          ))
  )
```

**Comment by Ambrevar** [comment]
It is your Emacs config indeed!
You need to disable those simulation keys with Nyxt.
Let me know if we can close this issue.

**Comment by divansantana** [comment]
@Ambrevar yes, thanks. :smile:
