### ISSUE TITLE
Can't get C-. jump-to-heading binding to work

### ISSUE THREAD

**Issue by divansantana** [atlas-engineer/nyxt#822]
"Out the box" with 1.5.0 via guix package, I'd expect

C-. to call jump-to-heading

It doesn't work for me. 

Setting the binding manually doesn't help either.

Setting it to M-. I see the binding takes effect because M-x shows it's bound to M-. yet, M-. still does not call the function.

Interesting, if I set it to C-z or C-n the binding takes effect and pressing the keyboard shortcut actually works.

**Comment by Ambrevar** [comment]
All the binding issues have been fixed on master.
With guix I suggest you use the build-scripts/guix.scm file to easily
install the most up to date version.

**Comment by divansantana** [comment]
Let me try that - thanks!

**Comment by divansantana** [comment]
Confirmed this is not an issue on master, thanks.
