### ISSUE TITLE
Doesn't respond to a kill signal 

### ISSUE THREAD

**Issue by divansantana** [atlas-engineer/nyxt#823]
In exwm I bind s-Q to kill-this-buffer

With most apps it works fine. With next 1.5.0 I get this

```
'Next - nyxt/MANUAL.org at 1.5.0 · atlas-engineer/nyxt · GitHub - https://github.com/atlas-engineer/nyxt/blob/1.5.0/documents/MANUAL.org' is not responding.  Would you like to kill it? (y or n) y
```

Then have to press y to force a kill.

**Comment by divansantana** [comment]
seperate note. Would be nice to have nyxt-next in guix channel :smile: 

Thanks for this amazing browser!

**Comment by Ambrevar** [comment]
Can you provide information about which version you are using and how
you built it?

You can do this easily if you use the GitHub form when creating the issue.

**Comment by divansantana** [comment]
**Information**
- Guix system
- 00:02.0 VGA compatible controller: Intel Corporation HD Graphics 620
  (rev 02) (prog-if 00 [VGA controller]) via i915
- GNU Emacs 26.3 (build 1, x86_64-unknown-linux-gnu, GTK+ Version
  3.24.20)
- emacs exwm 0.24
- via guix manifest on guix system

  - Nyxt version 1.5.0
  - Linux swift 5.4.46 #1 SMP 1 x86_64 GNU/Linux
  - WebKitGTK+ | QtWebEngine version: /gnu/store/s0x7fr7scmrnzryy8jnbai8invjgjsry-next-gtk-webkit-1.5.0/bin/next-gtk-webkit

**Output when started from a shell**

```
ds@swift ~ $ next -Q
Next version 1.5.0
 <INFO> [23:38:56] next remote.lisp (initialize-instance :after remote-interface) -
  D-Bus addresses: (#<Unix socket address: @"/tmp/dbus-wZ8sQagaSo">)
 <INFO> [23:38:56] next remote.lisp (initialize-instance :after remote-interface) -
  Bus connection name: :1.14800
 <INFO> [23:38:56] next port.lisp (run-program port) -
  Current directory: /home/ds/
 <INFO> [23:38:56] next port.lisp (run-program port) -
  Platform port path: /gnu/store/s0x7fr7scmrnzryy8jnbai8invjgjsry-next-gtk-webkit-1.5.0/bin/next-gtk-webkit
 <INFO> [23:38:56] next port.lisp (run-program port) -
  Platform port arguments: NIL
 <INFO> [23:38:56] next port.lisp (run-program port) -
  Platform port log file: /home/ds/.local/share/next/next-gtk-webkit.log
 <WARN> [23:38:56] next remote.lisp (current-buffer) -
  No active window, picking last active buffer.
```

**Comment by divansantana** [comment]
I'll test this with latest build when I get that working.

**Comment by Ambrevar** [comment]
Version 1.5 has multiple issues with process management.  Try master, it
should fix it.
(I also use EXWM.)

**Comment by divansantana** [comment]
This issue seems resolved with the build from master.
