### ISSUE TITLE
Replace hooks library with Serapeum's

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#828]
Our hook library has been merged into Serapeum.
Let's wait until the next Quicklisp release before we replace it.

**Comment by jmercouris** [comment]
Next quicklisp release is now here, do we use serapeum now?

**Comment by Ambrevar** [comment]
I'm guessing we can.  It's just that we still have
https://github.com/atlas-engineer/nyxt/issues/383 opened and I wonder if
we could fix it in the library before relying on sera.

Or we could directly work with upstream to fix the issue.  No strong
opinion in all cases.

**Comment by Ambrevar** [comment]
SBCL 2.0.9 caught a bug in the library that was fixed by Serapeum but that we only updated about a week later.  High time we moved to Serapeum!
