### ISSUE TITLE
Add support for direct program execution in url-dispatching-handler

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#834]
It'd be neat if we could call external programs more easily, e.g. instead of

```lisp
(url-dispatching-handler
   'transmission-magnet-links
   (match-scheme "magnet")
   (lambda (url)
     (uiop:launch-program
      (list "transmission-remote" "--add"
            (object-string url))
      nil)))
```

allow

```lisp
(url-dispatching-handler
   'transmission-magnet-links
   (match-scheme "magnet")
   '("transmission-remote" "--add")))
```

**Comment by aartaka** [comment]
Having a string-accepting shell-calling function (see StumpWM's `run-shell-command` as an example of simple-to-imitate examle) can make it even more convenient and this third argument to `url-dispatching-handler` could be a `string` then, with all the `format`-ability as a pleasant side-effect.

**Comment by Ambrevar** [comment]
You mean something like

```lisp
"transmission-remote --add %s"
```
?

**Comment by aartaka** [comment]
Exactly. If we'll stick to the format of `format` control-strings, we can easily pass it to format and then to `run-shell-command`-like function.

**Comment by aartaka** [comment]
I.e. `"transmission-remote --add ~s"`.

**Comment by aartaka** [comment]
But that's an implementation idea, so it may be too early to think of exact format :)
