### ISSUE TITLE
Slow Startup time on macOS

### ISSUE THREAD

**Issue by jmercouris** [atlas-engineer/nyxt#836]
Osicat adds very significant time to start-up. Every time I start Nyxt I get about 15 seconds of:

```
..................................................
[package osicat]..................................
..................................................
..................................................
[package nx-reader]
```

shall we remove it in favor of just using CHMOD? We only use it for one purpose. It would also simplify packaging.

**Comment by Ambrevar** [comment]
Looks like this is a packaging issue: osicat should not rebuild
every time and loading it should be instant.

We use it osicat to check if the file is a socket which is rather
important.
Besides, osicat has many useful features which are nice to have at hand.

**Comment by jmercouris** [comment]
This is not a packaging issue, I’ve built from source on my machine. I believe it is because of grovel, what else could it be doing?

**Comment by Ambrevar** [comment]
What happens if you just load osicat from a fresh SBCL REPL?

For me:

```
(time (asdf:load-system :osicat))
...

  0.873 seconds of real time
...
```

Also note that osicat is already loaded in the binary image, so it does
not need to be asdf-loaded again.  What you showed in the original post
looks like you were starting Nyxt from the REPL.

**Comment by jmercouris** [comment]
I was not starting Nyxt from the REPL. That is when I take an image and load it. As per loading time I get 0.927 seconds of real time for Osicat. Which is actually stil quite outrageous. A whole second for a single package!

**Comment by Ambrevar** [comment]
Yes, Osicat is very slow to load.  Maybe we should discuss this with
upstream.

Nonetheless it should not be a problem for Nyxt.
How do you load your image?

**Comment by jmercouris** [comment]
I just ./nyxt, nothing special about it... :-/

Can we implement all Osicat functions we need in pure lisp?

**Comment by Ambrevar** [comment]
I don't know how.  Maybe we can ask the Osicat people about it.

Still, there is a problem with your setup and it should be fixed.

Can you share the complete output when you call the `nyxt` binary on an
empty config / session?
