### ISSUE TITLE
Cookies isolation (e.g. per-domain)

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#837]
Cookies have been the bane of privacy for long, so Nyxt gotta do something about it! :)

A nice feature would be to isolate cookie per-domain.
Currently, Nyxt can set the cookies path.  Changing it for a live buffer might not be very useful because I don't think it changes in-memory cookies (this would need verification).

So we need to see if WebKitGTK has some options to isolate cookies within a live buffer.
If not, we might have to create a new buffer when navigating to a domain for which we want isolated cookies.
This is similar to how we need to do "private / incognito" buffers (#247).

**Comment by aartaka** [comment]
Can [Intelligent Tracking Prevention](https://webkit.org/blog/7675/intelligent-tracking-prevention/) be the thing we look for? It isolates the cookies that are not used daily, purges all the third-party tracking cookies, while retaining the cookies that user needs. The downside is that it's a black box Machine Learning-based solution that tracks all the activity of the user (it's for the good end, but still...)

Alternatively, WebKit has the ability to manipulate cookies manually (`WebKitCookieManager` and `WebKitDataManager` have functions for that, e.g., [webkit_website_data_manager_remove()](https://webkitgtk.org/reference/webkit2gtk/stable/WebKitWebsiteDataManager.html#webkit-website-data-manager-remove), [webkit_website_data_manager_clear()](https://webkitgtk.org/reference/webkit2gtk/stable/WebKitWebsiteDataManager.html#webkit-website-data-manager-clear), [webkit_cookie_manager_delete_cookie ()](https://webkitgtk.org/reference/webkit2gtk/stable/WebKitCookieManager.html#webkit-cookie-manager-delete-cookie)), so we can build the cookie-watching mechanism on top of that. I'm not sure about isolation, but per-domain cookie cleaning is certainly possible.

Intelligent Tracking Prevention seems to be the best way, given that it's relatively mature and well-designed.

**Comment by Ambrevar** [comment]
It's a great idea and it was released in WebKitGTK very recently:
https://blogs.gnome.org/mcatanzaro/2020/09/16/epiphany-3-38-and-webkitgtk-2-30/

We could very well offer both options: Intelligent Tracking Prevention
_and_ home-rolled solution to manipulated the cookies in Common Lisp.

@aartaka: Interested in adding bindings for Intelligent Tracking Prevention?

**Comment by aartaka** [comment]
Yes, I'm already looking into that!

**Comment by Ambrevar** [comment]
Fantastic, thanks!

**Comment by tg-x** [comment]
It'd be quite useful from a privacy perspective to have the possibility to have a per-buffer cookie store.

A comparable feature I'm using in Firefox is temporary containers, which results in separate cookie stores for each container (the initial tab and any further tabs opened from there). Containers allow related tabs use the same cookie store which is necessary for certain SSO setups where a group of domains need to use the same cookie store, and also allow using multiple logins on the same domain.

In nyxt I'd image a comparable setup would be using a few different sessions / data profiles instead of containers.
Then by default use ephemeral, per-buffer cookie stores, and for certain domains where login is required store them either per-buffer or per-session as desired.

**Comment by Ambrevar** [comment]
Nyxt can already isolate cookies but we lack a good user interface.

@aartaka was planning to work on "private buffers" (we still need to
find a proper name).
A general approach to this problem would give us cookie isolation or the
equivalent of Firefox containers (or better).

This would not use sessions nor data profiles though since we also want to be
able to use various kind of containers within the same process, e.g. to
share the same global state.

See pull request #1007 which will be instrumental in grouping buffers by "containers".

**Comment by jmercouris** [comment]
`saveless-mode`? `no-history-mode`? `no-local-history-mode`? `nosave-mode`? `historyless-mode`?

**Comment by Ambrevar** [comment]
So what's an "incognito/private" buffer?

- No persisted history.
- No persisted cookie.

Anything else?

@jmercouris Your suggestions with "history" would be misleading because
it's also about cookies.

I like "nosave-mode".

**Comment by jmercouris** [comment]
It is just those two things, yes. And optionally, no persisted cache files. There should be no data on your machine left indicating that you visited site X or Y.

let us proceed with "nosave-mode" then :-)

**Comment by Ambrevar** [comment]
Ah!  Yes, there is the data manager too!

**Comment by crocket** [comment]
I think cookies and site data need to be isolated per domain.

**Comment by Ambrevar** [comment]
See if #1987 fixes it.

**Comment by Ambrevar** [comment]
Fixed with #2050.
