### ISSUE TITLE
Add a `web-buffer` class

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#838]
There is some inconsistency throughout the code base when it comes to how we initialize buffers.

- Should buffers always have an ID?  I'd say no, replacement / temp buffers don't need one.  Otherwise it would seem to the user that buffer ID numbers would often get skipped, which seems like a bug.  After all, temp buffers are mostly an implementation detail: they serve as a place holder for the webview.

- In `window-set-active-buffer` we generate temporary buffers with `buffer-make`: we should not do this since this calls the `buffer-make-hook`, initializes modes, etc.  Either we use `(make-instance *buffer-class*)` or a new `make-temp-buffer` function.

- If we choose the latter, we need to update the call to `(make-instance *buffer-class*)` in the gtk-window :after method.

- We should stick to one term, so which one should it be?  `temp`, `replacement`, `dummy`, `void`, `placeholder`?

- We need a predicate that distinguishes a temp buffer from a non-temp buffer.  I suggest `reified-buffer-p`.  If temp buffers don't have an ID, then this checks suffices.

Thoughts?

EDIT: Mention "placeholder".

**Comment by Ambrevar** [comment]
Furthermore, the `load-status` conflates 2 concepts: the load status and the type of buffers.

We can have the following types of buffers:

- Live buffers (has a web page loaded with a URL).
- Local buffers (e.g. help pages, it's loaded but has no URL).
- Dead buffers (has history, URL, etc. but not loaded).
- Placeholder buffers (for window creation plus temp buffer when switching
  buffers).

The distinction between them can be done in various ways.

- We can have a subclass for each one of them.
- Placeholder buffers could be identified by their lack of ID.
  Dead buffers have no ID either, but that's not a problem because an ID is re-attributed as soon as their are resurected.

**Comment by Ambrevar** [comment]
I'm leaning towards adding a `web-buffer` class and we could move the following slots there:

- `load-status`
- `request-resource-scheme`
- `request-resource-hook`
- `default-new-buffer-url`
- `cookies-path`
- `proxy`
- `certificate-whitelist`
-  `default-cookie-policy`

This would make a lot of sense with regard to how we decided to separate base-mode from web-mode.
The `buffer` default modes would be `base-mode` while web-buffers would have `web-mode base-mode...`.

**Comment by jmercouris** [comment]
I agree with your reasoning and conclusion! very valid points!

**Comment by jmercouris** [comment]
to be clear, I mean your latest comment about the new classes

**Comment by Ambrevar** [comment]
Great!

By the way, I've fixed the inconsistencies with the replacement buffers in d628774d9176c910318e92bdb15a363a1666d2a8 and 4ee703f99fc308a9a005350da7dfbd86d5ef52d5.  Now they never show up at the high level, they are only implementation details.

**Comment by Ambrevar** [comment]
Everything I mentioned above is now fixed, the only thing that remains is the web-buffer class.

**Comment by Ambrevar** [comment]
Do we still need a web-buffer class now that we no longer have temp / replacement / placeholder buffers?

Previously we mentioned "local, secure buffers" that would accept Common Lisp execution, such as help buffer references.  The problem with making it a separate class is that it prevents the user from navigating from a help buffer to a web page.
Is this a good idea?

- With separate classes, we enforce better compartimentalization between secure buffers and web buffers.
- If we click a web link in a help buffer, we must open this link in a new buffer.  This is what Firefox and Chrome do after all.
- We would not be able to intermingle web pages and help pages in a buffer history.  Is that OK?

This would fix #863.

**Comment by jmercouris** [comment]
Yes, this is a good idea! We do not want people to leave help pages and go to different URLs. We want the execution to be secured in this case. If they wish to visit a URL, they can still click the binding, but it should always open a new buffer.

I actually need this functionality for what I would like to work on next. I was going to make a buffer screen where the user can press interactively kill buffers and visit them (like iBuffer).

**Comment by Ambrevar** [comment]
> We do not want people to leave help pages and go to different URLs.

Why not?

> We want the execution to be secured in this case.

Note that we can still have secure Lisp execution without separate
class, e.g. with a buffer slot.

> I actually need this functionality for what I would like to work on next. I was going to make a buffer screen where the user can press interactively kill buffers and visit them (like iBuffer).

I believe you can still do this without a separate buffer class.

I'd like to think deeper about the benefits and the drawbacks of this
design decision, it's still unclear to me.

**Comment by jmercouris** [comment]
Why use a slot when you can use a class? With a class you have more flexibility to specialize behavior.

**Comment by Ambrevar** [comment]
Because of the intermingled buffer history: with different classes, you would not be albe to go from a help page to a web page using the same buffer.  I believe this is the biggest question: do we want to allow that?  We need to discuss this, lest we take too restrictive design decisions.

**Comment by jmercouris** [comment]
Why would internal pages be in the history? Under what scenario would you want to navigate to an internal buffer?

**Comment by Ambrevar** [comment]
You can actually do this in Emacs: navigate to a help buffer and follow
links.  Then you can "go back".  This is very useful.

Now is it useful to be able to navigate back to a help page _from a web
page_?  I don't know.  Maybe some users would like it.

**Comment by jmercouris** [comment]
Yes, that is a wise idea. We will have to do a lot of refactoring, but it is what hierarchically makes the most sense.

**Comment by Ambrevar** [comment]
Done in 9e0cc81b644524fbcc2b66dc67d60d7e179f9f88.
