### ISSUE TITLE
Error when using `Open With` on Max OS X to open HTML files

### ISSUE THREAD

**Issue by chuchana** [atlas-engineer/nyxt#84]
nEXT isn't able to read HTML files using OS X's `Open With` command:

`The document “index.html” could not be opened. nEXT cannot open files in the “HTML text” format.`

I suppose that is also the reason you cannot use it as the default browser.

You can drag and drop HTML files onto a nEXT window to open them, though.

**Comment by jmercouris** [comment]
Hi, I really have no idea, I haven't quite looked into this issue as I usually don't open local HTML files. You can pass a valid NSURL into the minibuffer and have it load the file though. So if you type in C-l and the path to a file, it will render it. Open a file in safari to see what the URL format looks like.

If you have any ideas or are willing to investigate on how to fix this, that would be awesome :)

thank you for your report,

-John

**Comment by Ambrevar** [comment]
@jmercouris: Is this still an issue?

**Comment by jmercouris** [comment]
Yes, this is still an issue, and a bit difficult to solve. You
can however open local files now using file:// syntax

**Comment by Ambrevar** [comment]
@jmercouris Is this still an issue on master?

**Comment by jmercouris** [comment]
Yes

**Comment by aartaka** [comment]
fd572239858e42fdee145af6f9a8c9eb4c6c9657 should allow that, shouldn't it?

**Comment by aartaka** [comment]
Closing. Feel free to reopen if that's actually not resolved.
