### ISSUE TITLE
Filter "javascript:" URLs (and enable "data:" scheme?)

### ISSUE THREAD

**Issue by aartaka** [atlas-engineer/nyxt#840]
Now that #1097 is merged, `javascript:` scheme URLs are acessable by Nyxt. The main concern is security of those.

It might be worth filtering these URLs, because they can redirect the user to the phishing website or trick them in some other innoticeable way. Mozilla (Google & MIcrosoft too) already had such concerns and done this filtering work on `data:` URLs, that `javascripts:` URLs can be said to be subset of. We can implement at least the basics of what they've done.

Also, we can try to enable `data:` scheme, because it can be useful for what it was made for -- content text-encoding, but it needs a strict filtering too.

What do you think of it?

References:
[Documentation for `data:` URI scheme](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs)
[RFC documentation on `data:` scheme](https://tools.ietf.org/html/rfc2397)
[Mozilla security concerns about `data:` URLs and phishing](https://blog.mozilla.org/security/2017/11/27/blocking-top-level-navigations-data-urls-firefox-59/)

EDIT: Add the suggestion on `data:` scheme support.
EDIT: #1097 is merged.

**Comment by jmercouris** [comment]
This is interesting, we could use this to make the renderer invoke Lisp, how to do it securely?

What if we use some encryption scheme to ensure that the request originates from something created by the Lisp core?

**Comment by aartaka** [comment]
> This is interesting, we could use this to make the renderer invoke Lisp, how to do it securely?

I'm not sure I get what you mean. How can we enable renderer to invoke Lisp, if this is still plain JS?

There's another possibly cleaner way around. I had an idea about implementing the long-desired `nyxt:` or `about:` scheme whose `path` would be the name of the function to call, and query parameters would be the arguments to that function. We then can implement all the fancy features like IBuffer or Customize, through HTML and these links.

> What if we use some encryption scheme to ensure that the request originates from something created by the Lisp core?

Yes, using an encryption to encode the URL body and then percent-encode it can be a good way, because it'll be only Nyxt session that will have the keys in it, while it still will be a valid URL.


Is there a way to make these encription keys to be randomly generated on browser startup and hidden even from user? We can implement simple HTLM documents with the `(encode "nyxt://eval?exp='(setf *swank-port* 4008)")` in `href`s and exchange this information with the browser on link request, while the browser will be the only agent able to decypher its own encoding.

**Comment by aartaka** [comment]
To clarify: this `(encode "nyxt://eval?exp='(setf *swank-port* 4008)")` is just an example. It could be any function in place of `eval` — `tutorial` (interactive tutorial... isn't it a dream?),`ibuffer`, `customize`. Same for args/query parameters.

Home-made REST-API for Nyxt :)

**Comment by Ambrevar** [comment]
Artyom Bologov <notifications@github.com> writes:

> Some websites do break horribly if `javascript:` scheme is not there, that's why I suggest adding a hook to process this scheme,

Are you saying it does not work at the moment?
This is something that should be covered by WebKitGTK.  If not, we need
to ask the WebKitGTK decs.

To clarify, the resource-request hook is not required to process
resource requests, it's only a hook that we can use to customize the
behaviour beyond what WebKitGTK does by default.
In particular, we do nothing to handle HTTP or HTTPS, WebKitGTK takes
care of this.

**Comment by Ambrevar** [comment]
Regarding security: I don't think we need any sort of encryption.  This is hard to get right and should we make a mistake, we would expose our users to a massive security issue.

Instead, I suggest we simply make special buffers (via a specialized "secure-buffer" class, or a `secured-p` slot) that can load `nyxt://` URL, execute Javascript, etc. but _cannot_ load any network resource.

**Comment by Ambrevar** [comment]
Actually, we can have 2 scheme, say `nyxt://` and `lisp://`.
The former would only load static pages such as some documentation.  The latter would allow code execution.

This distinction would allow web sites to link to Nyxt documentation (e.g. `nyxt://classes/browser`) but any code execution would be forbidden since `lisp://` could only be run from a secure buffer.

**Comment by jmercouris** [comment]
Ah yes, I forgot about the concept of secure buffers, what Pierre says makes sense. I was thinking we would also potentially have lisp:// embeddable on other pages, but that is indeed too dangerous.

**Comment by Ambrevar** [comment]
See also #745.

We had discussed this idea of "secure buffers" in the past.  Can't find
the related discussion though.  @jmercouris?

**Comment by jmercouris** [comment]
Yes, we had talked about it with regards to the minibuffer being a Secure Enclave, where there are no external contents from any pages. That is why we have a separate minibuffer buffer class. For the sake of security, for Nyxt generated buffers, I think we should extend this concept and have a "internal-buffer" class. That way, only lisp:// urls from internal-buffer classes may be resolved. Thoughts?

**Comment by Ambrevar** [comment]
Agreed!

You are right, the original discussion was about the minibuffer.
Also `internal-buffer` sounds like a reasonable name.

**Comment by aartaka** [comment]
> Are you saying it does not work at the moment? 

No, it does not. When I click on a link with a `javascript:` scheme, Nyxt tries do load it. It results in "The URL can't be shown" error. As far as I can tell, this is the WebKitGTK error.

> This is something that should be covered by WebKitGTK. If not, we need to ask the WebKitGTK devs. 

Sounds reasonable.

**Comment by Ambrevar** [comment]
Can you share an example link?
Can you reproduce in Epiphany?

**Comment by aartaka** [comment]
> Can you share an example link? 

https://sql-ex.ru is the website. There's a small "Ratings" link on the left. It contains the `javascript:changeSt('rat')` code.
- When I click it, it runs the code.
- When I `follow-hint` it, it tries to load it and fail.

> Can you reproduce in Epiphany?

It works on click in Epiphany.


Seems like it is implemented in WebKitGTK. Something goes wrong in `follow-hint` then.

**Comment by Ambrevar** [comment]
Artyom Bologov <notifications@github.com> writes:

> Seems like it is implemented in WebKitGTK. Something goes wrong in `follow-hint` then.

Absolutely, you just found a bug! :)

**Comment by Ambrevar** [comment]
(Many things are wrong with follow-hint by the way... :p)

**Comment by jmercouris** [comment]
hmm, it is supposed to try to click the button, is the element perhaps not a button?

**Comment by Ambrevar** [comment]
@aartaka Should we close this now that #1097 is in?

**Comment by aartaka** [comment]
Well, security concerns are still there. Epiphany seems to not care about these, though. 

Maybe we can rename/alter this one to make emphasis on security of `javascript:` links?

**Comment by Ambrevar** [comment]
I'm confused by this topic's discussion around security.  Can you sum it up?

**Comment by aartaka** [comment]
It seems yesterday I've confused things between `data:` and `javascript:` URLs. Seems like `javascript:` URLs are more or less harmless. 

`data:` URLs can allow arbitrary HTML to be loaded as new page, opening the possibilities for phishing. However, I'm not sure it's actually our concern. It seems to be an engine-level matter.

Then we should probably close this issue.

**Comment by jmercouris** [comment]
Agreed, it is outside of our scope.
