### ISSUE TITLE
Prettifying session file: serialize quri:uri

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#842]
In 1918f36f0b3f3949dc82bd331b5bc8f564aa2860
I've changed the buffer-description URL slot to use quri:uri instead of string.
This fixes a few issues and it's more consistent with the rest of the code base where we use quri:uri almost all the time.

The downside is that it makes the session file much more verbose and less readable.
It's easy to specialize the cl-prevalence serializer on quri:uri.  The problem is that we can't specialize the deserializer.

Maybe another way to fix this would be to specialize against buffer-description instead to store the URL as a string, then add an `initialize-instance :after` method that converts the URL from a string to a quri:uri if need be.

Thoughts?

**Comment by jmercouris** [comment]
Why can we not specialize the deserializer? Is this a limitation of cl-prevalence? Could we have a serialized syntax indicating that it is a Quri object, and then react accordingly in our deserialization?

**Comment by Ambrevar** [comment]
Because the deserializer is a big defun :/

I'll send a patch just now with a workaround.

**Comment by Ambrevar** [comment]
Fixed in #842.

**Comment by jmercouris** [comment]
Oui! Fantastique!
