### ISSUE TITLE
Remove define-url-group

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#845]
With 9bb0283607def8f28e25a135a579032ae14cb6e7 we can now open multiple bookmarks.

This means that the following function opens the desired URLs:

```lisp
(define-command open-my-emacs-games-url-group ()
  (mapcar (lambda (url) (make-buffer :url (object-string url)))
          (match-bookmarks "+emacs +games")))
```

Which can then be bound to a key.

I believe this supersedes define-url-group.  Shall we remove it?

On the topic:

- `make-buffer` should take a quri:uri, it's one of the very few functions that still takes a string.  Thoughts?
- `match-bookmarks` argument could be made more readable if it were `&key full-bookmarks-p`.

**Comment by jmercouris** [comment]
define-url-group is useful for end users, for this reason I suggest we do not remove it

I would think we could extend the define-url-group macro to better support opening groups of bookmarks by tags

**Comment by jmercouris** [comment]
also define-url-group allows you to bind urls outside of your bookmarks

**Comment by Ambrevar** [comment]
Can you explain how it's useful to end users beside storing them outside
your bookmarks?

Regarding the "collection": I don't see the point of collecting URLs in
place different than bookmarks.  We have a very powerful facility for
filtering and grouping URLs with our bookmarks, why reinvent the wheel
with "URL groups"?
Unless I'm missing something, with the same reasoning we might want
some "URL set" that is neither in bookmarks nor in "URL groups" :p

**Comment by Ambrevar** [comment]
Also what are your thoughts abot the last 2 points in the original post?

**Comment by jmercouris** [comment]
Regarding the last two points:

+ make-buffer should take a quri:uri, it's one of the very few functions that still takes a string. Thoughts?
I don't see why not. Is there a compelling reason we left it to accept a string? One thing we can consider is flexible arguments. For example, within the body of `make-buffer` we could check the TYPE-OF the argument and then react accordingly, so we could shift the API forward whilst maintaining backwards compatibility.

+ match-bookmarks argument could be made more readable if it were &key full-bookmarks-p.
I don't know if that makes it more readable. What is a "full-bookmark"? The distinction here is: in one case we want to return bookmark objects, and in another URLs. Whether the predicate is predicated upon objects or URLs, is in my opinion, not helping in understanding. If we want to make it more clear, perhaps we should just make it more verbose. How about `&key return-bookmark-objects`? or `&key return-list-of-urls`?

thoughts?

**Comment by jmercouris** [comment]
> Can you give an example how it's useful to end users beside storing them outside the bookmarks? Regarding the "collection": I don't understand the point of collecting URLs in place different than bookmarks. We have a very powerful facility for filtering and grouping URLs with our bookmarks, why reinvent the wheel with "URL groups"? :) Unless I'm missing something, with the same reasoning we might want some "URL set" that is neither in bookmarks nor in "URL groups" :p EDIT: Phrasing.

Well, we might actually indeed want a URL set that is neither in bookmarks nor in URL groups. I understand that semantically they are the same. Still, there are examples where a convenience/option to the end user is nice to have. For example, we added a command `set-url-from-current-url` even though the user could have executed the following sequence of events:

+ copy current url
+ open set-url
+ paste current url
+ modify url

Personally, as an end user, I don't necessarily want all the URLs from my "url-groups" in my bookmarks. Is it necessary? Technically no. It is however, at least for me as a now user of this feature, nice to have.

**Comment by Ambrevar** [comment]
John Mercouris <notifications@github.com> writes:

> + match-bookmarks argument could be made more readable if it were &key full-bookmarks-p.
> I don't know if that makes it more readable. What is a "full-bookmark"? The distinction here is: in one case we want to return bookmark objects, and in another URLs. Whether the predicate is predicated upon objects or URLs, is in my opinion, not helping in understanding. If we want to make it more clear, perhaps we should just make it more verbose. How about `&key return-bookmark-objects`? or `&key return-list-of-urls`?

Misunderstanding.  I meant we could help with readability in function
calls if we used a key arguments with a default nil value, instead of an
optional argument with a default t value.

Compare:

(match-bookmarks "blah" nil)

(match-bookmarks "blah" :full-bookmarks t)

When just looking at the first call, it's unclear what `nil` stands
for.  Also non-zero / non-nil default values are counter-intuitive and
are prone to trip the user.

**Comment by Ambrevar** [comment]
I understand we would want to separate the URL storage, but then I
suggest we make use of the bookmark infrastructure.

> Well, we might actually indeed want a URL set that is neither in bookmarks nor in URL groups. I understand that semantically they are the same. Still, there are examples where a convenience/option to the end user is nice to have. For example, we added a command `set-url-from-current-url` even though the user could have executed the following sequence of events:
>
> + copy current url
> + open set-url
> + paste current url
> + modify url

This is a good example: when we implemented the command, we didn't write
the above 4 actions from scratch, we reused them.

So instead of the define-url-group macro, I suggest we use the bookmark
infrastructure to store and manipulate the URL groups.

Thoughts?

**Comment by jmercouris** [comment]
> John Mercouris <notifications@github.com> writes:
> + match-bookmarks argument could be made more readable if it were &key full-bookmarks-p. I don't know if that makes it more readable. What is a "full-bookmark"? The distinction here is: in one case we want to return bookmark objects, and in another URLs. Whether the predicate is predicated upon objects or URLs, is in my opinion, not helping in understanding. If we want to make it more clear, perhaps we should just make it more verbose. How about `&key return-bookmark-objects`? or `&key return-list-of-urls`?
> Misunderstanding. I meant we could help with readability in function calls if we used a key arguments with a default nil value, instead of an optional argument with a default t value. Compare: (match-bookmarks "blah" nil) (match-bookmarks "blah" :full-bookmarks t) When just looking at the first call, it's unclear what `nil` stands for. Also non-zero / non-nil default values are counter-intuitive and are prone to trip the user.

Aha! I see. Non-nil default values are just fine in my opinion. For me, it really just depends on the phrasing of the predicate as to whether something is confusing (with double negatives, for example). All of this said, I agree, &key is almost always better than &optional.

**Comment by jmercouris** [comment]
> This is a good example: when we implemented the command, we didn't write the above 4 actions from scratch, we reused them. So instead of the define-url-group macro, I suggest we use the bookmark infrastructure to store and manipulate the URL groups. Thoughts?

Why though? It is such a small little macro. I think we have metaphorically bigger fish to fry :-D

**Comment by Ambrevar** [comment]
It's a little macro because it does very little.  In particular, we
can't do the following:

- List the URL groups, nor the URLs in the groups, in a minibuffer.
- Compose multiple groups (e.g. group abc + xyz minus the intersection).
- Access URL metadata (title, date, etc.).
- Easily crypt and version the groups.

If you want to implement all the above, you'd have to write much more
code which would reinvent the wheel because we already have all this in
bookmarks.

You are true, this is a detail.  But I'd recommend we don't keep adding
too many of these little features that are not well integrated, lest
Nyxt becomes cluttered with non-cohesive parts that are hard to maintain ;)

**Comment by Ambrevar** [comment]
About make-buffer: No reason, it was just forgotten.  I'll fix it.

**Comment by Ambrevar** [comment]
make-buffer is now fixed on master.

**Comment by jmercouris** [comment]
There is something to be said about adding many features/making it difficult to move forward. Especially when those features are not well integrated. I will think about this.

**Comment by jmercouris** [comment]
I have thought about this, for enough time. And I am still using this feature :-D

**Comment by Ambrevar** [comment]
Have you tried replacing them with bookmarks?

**Comment by jmercouris** [comment]
Yes, I have. I actually use in combination with tags. What I have is defined a set of groups to open by bookmark tag.

**Comment by Ambrevar** [comment]
Pros and cons for both methods?

**Comment by jmercouris** [comment]
Removed.

**Comment by Ambrevar** [comment]
Thanks.

**Comment by jmercouris** [comment]
Welcome.

**Comment by jmercouris** [comment]
:-P
