### ISSUE TITLE
Command describe-slot fails to open minibuffer when stderr is missing

### ISSUE THREAD

**Issue by xelxebar** [atlas-engineer/nyxt#849]
## Overview

This occurs naturally by executing nyxt in a terminal as a background process and then closing the terminal:

    $ nyxt &
    $ exit

Subsequent attempts to execute the `describe-slot` command appear to do nothing.

## Reproducion

Funnily enough, `describe-slot` works if we redirect stderr:

    $ nyxt 2>/dev/null &
    $ exit

That's suspicious enough that after a bit of sleuthing, I was able to come up with a sharper reproduction method:

    $ mkfifo nyxt.err
    $ nyxt 2>nyxt.err &
    $ cat nyxt.err >/dev/null &
    $ rm nyxt.err

For some reason, the issue does not appear if `nyxt.err` is a regular file. While the natural setting for this error gives us no logs, this second method happily does let us view them.

## Root Cause-ish

Suspiciously, when `describe-slot` executes correctly, I see the following on stderr:

    WARNING:
       unsupported DOCUMENTATION: doc-type T for object of type SB-PCL::CONDITION-DIRECT-SLOT-DEFINITION

and when we nuke stderr, the following shows up on stdout:

    <ERROR> [05:16:08] In DESCRIBE-SLOT: Couldn't write to #<SB-SYS:FD-STREAM for "standard error" {1001020163}>:
                                           Broken pipe

This suggests that the titular issue is perhaps just a single instance of a broader issue: commands fail when attempting to write to a missing stderr.

## Version Info

My nyxt instance comes from a (foreign) guix install:

    $ guix describe
    Generation 91	 7月 15 2020 01:23:34	(current)
      guix d7e9e0b
        repository URL: https://git.savannah.gnu.org/git/guix.git
        branch: master
        commit: d7e9e0bbc9aadec3e1830767a8771bfbe9c43155

    $ guix package -I nyxt
    nyxt	1.5.0-1.9440980	out	/gnu/store/gcg7xj4y8lgc7kmn767g9jcll8xlcc44-nyxt-1.5.0-1.9440980

Finally, output from `copy-system-information`:

    Nyxt version: 1.5.0-1.9440980 
    Operating system kernel: Linux 5.4.50_1
    Lisp implementation: SBCL 2.0.5
    Features: (WEBKIT2 WEBKIT2-2.28 WEBKIT2-EMOJI WEBKIT2-MEDIA WEBKIT2-SANDBOXING
               GTK-3-22 GTK-3-20 GTK-3-18 GTK-3-16 GTK-3-14 GTK-3-12 GTK-3-10
               GTK-3-8 GTK-3-6 GTK-3-4 GTK GDK-3-22 GDK-3-20 GDK-3-18 GDK-3-16
               GDK-3-14 GDK-3-12 GDK-3-10 GDK-3-8 GDK-3-6 GDK-3-4 CAIRO-1-10
               CAIRO-1-12 GDK-PIXBUF GLIB-2-30 GLIB-2-32 GLIB-2-34 GLIB-2-36
               GLIB-2-38 GLIB-2-40 GLIB-2-42 GLIB-2-44 GLIB-2-46 GLIB-2-48
               GLIB-2-50 GLIB-2-52 GLIB-2-54 GLIB-2-56 GLIB-2-58 GLIB
               FSET-EXT-STRINGS SWANK PLUMP-UTF-32 GLOBAL-VARS DECLARE-TYPES
               PARENSCRIPT SBCL+SAFE-STANDARD-READTABLE NAMED-READTABLES
               OSICAT-FD-STREAMS LPARALLEL 21BIT-CHARS CL-FAD CHUNGA FLEXI-STREAMS
               CLOSER-MOP CL-PPCRE-UNICODE CL-UNICODE CL-PPCRE
               CL-JSON-DOUBLE-FLOAT-IS-SUBSUMED CL-JSON-SINGLE-FLOAT-IS-SUBSUMED
               BORDEAUX-THREADS LPARALLEL.WITH-CLTL2 LPARALLEL.WITH-CAS
               LPARALLEL.WITH-STEALING-SCHEDULER SPLIT-SEQUENCE GRAY-STREAMS
               FLAT-NAMESPACE X86-64 UNIX CFFI FLAT-NAMESPACE SEQUENCE-EMPTYP
               FAST-IO-SV FAST-IO SBCL-USES-SB-ROTATE-BYTE CL-JSON-CLOS CL-JSON
               THREAD-SUPPORT ASDF3.3 ASDF3.2 ASDF3.1 ASDF3 ASDF2 ASDF OS-UNIX
               NON-BASE-CHARS-EXIST-P ASDF-UNICODE X86-64 GENCGC 64-BIT ANSI-CL
               COMMON-LISP ELF IEEE-FLOATING-POINT LINUX LITTLE-ENDIAN
               PACKAGE-LOCAL-NICKNAMES SB-CORE-COMPRESSION SB-LDB SB-PACKAGE-LOCKS
               SB-THREAD SB-UNICODE SBCL UNIX)

**Comment by Ambrevar** [comment]
>     $ nyxt &
>     $ exit

I can reproduce.

>     $ mkfifo nyxt.err
>     $ nyxt 2>nyxt.err &
>     $ cat nyxt.err >/dev/null &
>     $ rm nyxt.err

I cannot reproduce the issue with this recipe though.


Thanks for catching the warning.  I've fixed it with 
d262bf5f41c66e4024604d5926cd10a0f2628e61, so this should not longer be
an issue.

However, we will still run into the same issue for other, uncaught
warnings.  I suspect this is an SBCL issue.  Do you want to report it
upstream or should I do it?

**Comment by xelxebar** [comment]
That's quick. Thanks for the fix.

Sure, go ahead and raise the issue with upstream SBCL if you think the underlying cause is there. I don't understand the cause well enough to form much of a coherent report.

**Comment by Ambrevar** [comment]
Done: https://bugs.launchpad.net/sbcl/+bug/1887913
