### ISSUE TITLE
Expose the with-confirm to the user?

### ISSUE THREAD

**Issue by aartaka** [atlas-engineer/nyxt#856]
`with-confirm` is a cool macro for user interaction, and I've already thought of several cases of potentially dangerous customizations where it can be used as a cancel dialogue. The problem is that it's unexported and has a hard-coded list of answers.

What I suggest is:
- Exporting the `with-confirm` macro to the end-user.
- Exporting the `*yes-no-choices*` to make the confirmation dialogues more customizable (e.g., `y-or-no` as a possible customization direction).
- Making slight alterations to the `confirmed-p` function to match the first element of the `*yes-no-choices*` and not a hard-coded `"yes"`.

What do you think of it?

**Comment by Ambrevar** [comment]
Agreed on all points!

In particular, I find it important to be able to default to no.

Instead of relying on *yes-no-choices* to alter the default, what about
adding an argument to the macro?

Nit: I don't think 'y-or-n' would be useful since typing "y" already
selects "yes", while typing "n" selects "no".

**Comment by aartaka** [comment]
> I find it important to be able to default to no. 
> Instead of relying on *yes-no-choices* to alter the default, what about adding an argument to the macro? 

Yes, and we can specify the confirmation option as yet another argument, I think. Because then the order of the options can be significant and we can default to no, for example by providing `"prompt" '("no" "yes") "yes"` arglist.
 
> Nit: I don't think 'y-or-n' would be useful since typing "y" already selects "yes", while typing "n" selects "no".

Yes, you're right there, but then we can use arbitrary home-row keys for confirmation/cancelling, and it can be faster to type. But yes, creating a dedicated `y-or-n` doesn't make much sense :)

**Comment by Ambrevar** [comment]
Were you planning on sending a patch or should I just go ahead and apply the change?

**Comment by aartaka** [comment]
Oh, sorry for confusion. I just wanted to raise this issue and didn't mean to work on that, at least for now.

You're welcome to apply it!

**Comment by Ambrevar** [comment]
Partly fixed in 13c8935b895fb93d3f873a44fdfc51dde84c7a24.

What's missing is the ability to change the default suggestion.
I can think of only one way to do it: change the with-confirm argument to what @aartaka suggests, that is `(PROMPT &OPTIONAL DEFAULT-TO-NO-P CHOICES)`.
If we want to pass a format string, we would call format explicitly, e.g.

```lisp
(with-confirm ((format nil "foo ~a" 18) :default-to-no '("ja" "nein"))
  body...)
```

This means changing all the `with-confirm` calls in the source.

Thoughts?
@jmercouris

**Comment by Ambrevar** [comment]
Note: My lambda-list suggestion reverse 2 arguments that @aartaka suggested because I think we will more often want to specify the default rather than change the suggestion strings.

Moreover, it's already possible to change the suggestion strings by let-binding `*yes-no-choices*`.

**Comment by aartaka** [comment]
> If we want to pass a format string, we would call format explicitly, e.g.
> 
> ```lisp
> (with-confirm ((format nil "foo ~a" 18) :default-to-no '("ja" "nein"))
>   body...)
> ```
> 
> This means changing all the `with-confirm` calls in the source.

Another way around this would be to leave the `prompt` as it is, in the form of list of args for `format`, while wrapping all the args into additional set of parentheses. Then we can do something like
``` lisp
  (with-confirm (("Are you sure to kill ~a buffers?" count) :default-to-no)
     (delete-buffers))
``` 

Then the only necessary change to the code would be to wrap the sole `prompt` into pair of parens!

**Comment by jmercouris** [comment]
I've taken a look at the source. I do not think it is a good idea to assume that if the first selection is selected the result is positive. That is, the predicate function, should not check that. Beyond that, I have no strong opinions. I'm not sure what I would do in this case.

I think we can worry about this when we do some internationalization as we are not yet sure how this mechanism will function (the internationalization).

**Comment by Ambrevar** [comment]
@aartaka With both your and mine suggestion, we need to update the callers.

@jmercouris The fix I've pushed does not change the fact that
with-confirm makes an assumption about the choice list.  But your
comment led me to think of another solution: use a plist!

Example:

```lisp
(defparameter *yes-no-choices* '((:yes "yes" :no "no")))

(defun yes-no-suggestion-filter ()
  (lambda (minibuffer)
    (fuzzy-match (input-buffer minibuffer) (sera:plist-values *yes-no-choices*)))

(defun confirmed-p (answer)
  (string-equal answer (getf *yes-no-choices* :yes)))


;; Call that changes the defaults:

(let ((*yes-no-choices* '((:no "no" :yes "yes"))) ; Note how we've swapped the order.
  (with-confirm (PROMPT)
    BODY)))
```

What do you think of the above?

**Comment by Ambrevar** [comment]
If there is no opposition, I'll push the above change later today, it's backward compatible anyways.

**Comment by jmercouris** [comment]
Great!

**Comment by Ambrevar** [comment]
Done in 07b90b46780dff755323439fb6c9b283b730f44e.

**Comment by jmercouris** [comment]
Yay :-)
