### ISSUE TITLE
Nyxt crashed when clicking the "report" hyperlink

### ISSUE THREAD

**Issue by wdkrnls** [atlas-engineer/nyxt#857]
I clicked the hyperlink to 'report' bugs or submit feature requests, and nyxt crashed.

**Precise recipe to reproduce the issue**

Click "Report" from the "Getting Started" page.

**Information**
- OS name+version: Guix f49eb9f
- Graphics card and driver: Intel
- Desktop environment / Window manager name+version: herbstluftwm 0.8.3
- How you installed Nyxt (Guix pack, package manager, build from source): Guix
- Information from command copy-system-information:

Nyxt version: 1.5.0-1.9440980 
Operating system kernel: Linux 5.4.42
Lisp implementation: SBCL 2.0.5
Features: (WEBKIT2 WEBKIT2-2.28 WEBKIT2-EMOJI WEBKIT2-MEDIA WEBKIT2-SANDBOXING
           GTK-3-22 GTK-3-20 GTK-3-18 GTK-3-16 GTK-3-14 GTK-3-12 GTK-3-10
           GTK-3-8 GTK-3-6 GTK-3-4 GTK GDK-3-22 GDK-3-20 GDK-3-18 GDK-3-16
           GDK-3-14 GDK-3-12 GDK-3-10 GDK-3-8 GDK-3-6 GDK-3-4 CAIRO-1-10
           CAIRO-1-12 GDK-PIXBUF GLIB-2-30 GLIB-2-32 GLIB-2-34 GLIB-2-36
           GLIB-2-38 GLIB-2-40 GLIB-2-42 GLIB-2-44 GLIB-2-46 GLIB-2-48
           GLIB-2-50 GLIB-2-52 GLIB-2-54 GLIB-2-56 GLIB-2-58 GLIB
           FSET-EXT-STRINGS SWANK PLUMP-UTF-32 GLOBAL-VARS DECLARE-TYPES
           PARENSCRIPT SBCL+SAFE-STANDARD-READTABLE NAMED-READTABLES
           OSICAT-FD-STREAMS LPARALLEL 21BIT-CHARS CL-FAD CHUNGA FLEXI-STREAMS
           CLOSER-MOP CL-PPCRE-UNICODE CL-UNICODE CL-PPCRE
           CL-JSON-DOUBLE-FLOAT-IS-SUBSUMED CL-JSON-SINGLE-FLOAT-IS-SUBSUMED
           BORDEAUX-THREADS LPARALLEL.WITH-CLTL2 LPARALLEL.WITH-CAS
           LPARALLEL.WITH-STEALING-SCHEDULER SPLIT-SEQUENCE GRAY-STREAMS
           FLAT-NAMESPACE X86-64 UNIX CFFI FLAT-NAMESPACE SEQUENCE-EMPTYP
           FAST-IO-SV FAST-IO SBCL-USES-SB-ROTATE-BYTE CL-JSON-CLOS CL-JSON
           THREAD-SUPPORT ASDF3.3 ASDF3.2 ASDF3.1 ASDF3 ASDF2 ASDF OS-UNIX
           NON-BASE-CHARS-EXIST-P ASDF-UNICODE X86-64 GENCGC 64-BIT ANSI-CL
           COMMON-LISP ELF IEEE-FLOATING-POINT LINUX LITTLE-ENDIAN
           PACKAGE-LOCAL-NICKNAMES SB-CORE-COMPRESSION SB-LDB SB-PACKAGE-LOCKS
           SB-THREAD SB-UNICODE SBCL UNIX)
**Output when started from a shell**

Nyxt version 1.5.0-1.9440980
<INFO> [22:51:25] Using data profile "default".
<INFO> [22:51:25] Listening to socket "/home/k/.local/share/nyxt/nyxt.socket".
Unhandled SB-KERNEL:CASE-FAILURE in thread #<SB-THREAD:THREAD "cl-cffi-gtk main thread" RUNNING
                                              {10077E02D3}>:
  NIL fell through ETYPECASE expression.
  Wanted one of (SIMPLE-STRING QURI.PARSER::SIMPLE-BYTE-VECTOR STRING).

Backtrace for: #<SB-THREAD:THREAD "cl-cffi-gtk main thread" RUNNING {10077E02D3}>
0: (QURI.PARSER:PARSE-URI NIL :START 0 :END NIL)
1: (QURI.URI:URI NIL :START 0 :END NIL)
2: ((:METHOD NYXT::ON-SIGNAL-LOAD-CHANGED (GTK-BUFFER T)) #<GTK-BUFFER {10092B33B3}> :WEBKIT-LOAD-STARTED) [fast-method]
3: (GOBJECT::CALL-WITH-RESTARTS #<CLOSURE (LAMBDA (NYXT::WEB-VIEW NYXT::LOAD-EVENT) :IN FFI-BUFFER-MAKE) {10092E755B}> (#<CL-WEBKIT2:WEBKIT-WEB-VIEW {10092E5A93}> :WEBKIT-LOAD-STARTED))
4: ((LAMBDA (GOBJECT::CLOSURE GOBJECT::RETURN-VALUE GOBJECT::COUNT-OF-ARGS GOBJECT::ARGS GOBJECT::INVOCATION-HINT GOBJECT::MARSHAL-DATA) :IN "/gnu/store/vx05yrkr8mwgf6cf6brqv18mxs9i36kz-cl-cffi-gtk-0.11.2-1.412d172/share/common-lisp/source/cl-cffi-gtk/gobject/gobject.signals.lisp") #.(SB-SYS:INT-SAP #X7F8D5C23F230) #.(SB-SYS:INT-SAP #X00000000) 2 #.(SB-SYS:INT-SAP #X7F8D6A03DD60) #<unused argument> #<unused argument>)
5: ((LAMBDA (SB-ALIEN::ARGS-POINTER SB-ALIEN::RESULT-POINTER FUNCTION) :IN "/gnu/store/vx05yrkr8mwgf6cf6brqv18mxs9i36kz-cl-cffi-gtk-0.11.2-1.412d172/share/common-lisp/source/cl-cffi-gtk/gobject/gobject.signals.lisp") #<unavailable argument> #<unavailable argument> #<unavailable argument>)
6: ("foreign function: funcall_alien_callback")
7: ("foreign function: callback_wrapper_trampoline")
8: ("foreign function: #x5010073B")
9: ((LAMBDA NIL :IN GTK:ENSURE-GTK-MAIN))
10: ((LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS))
11: ((FLET SB-UNIX::BODY :IN SB-THREAD::NEW-LISP-THREAD-TRAMPOLINE))
12: ((FLET "WITHOUT-INTERRUPTS-BODY-4" :IN SB-THREAD::NEW-LISP-THREAD-TRAMPOLINE))
13: ((FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::NEW-LISP-THREAD-TRAMPOLINE))
14: ((FLET "WITHOUT-INTERRUPTS-BODY-1" :IN SB-THREAD::CALL-WITH-MUTEX))
15: (SB-THREAD::CALL-WITH-MUTEX #<CLOSURE (FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::NEW-LISP-THREAD-TRAMPOLINE) {7F8D6A03ED8B}> #<SB-THREAD:MUTEX "thread result lock" owner: #<SB-THREAD:THREAD "cl-cffi-gtk main thread" RUNNING {10077E02D3}>> NIL T NIL)
16: (SB-THREAD::NEW-LISP-THREAD-TRAMPOLINE #<SB-THREAD:THREAD "cl-cffi-gtk main thread" RUNNING {10077E02D3}> NIL #<CLOSURE (LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS) {10077E027B}> NIL)
17: ("foreign function: call_into_lisp")
18: ("foreign function: new_thread_trampoline")

unhandled condition in --disable-debugger mode, quitting

**Comment by Ambrevar** [comment]
This issue was fixed with d1dd817b38fb9823b0845b5e0216da2ba762b61a.
You can update your Nyxt install with Guix with the following command
from a checkout of this repository:

guix package --install-from-file=build-scripts/guix.scm

**Comment by Ambrevar** [comment]
Feel free to ask (or reopen) if there is anything else.
