### ISSUE TITLE
Error when invoking add-domain-to-certificate-whitelist from minibuffer

### ISSUE THREAD

**Issue by xelxebar** [atlas-engineer/nyxt#859]
## Summary

When invoking `add-domain-to-certificate-whitelist` from the minibuffer and supplying `example.com<C-enter>` to the resulting minibuffer, the following error appears in the logs:

    <ERROR> [04:02:44] In #<CLOSURE (LAMBDA
                                        (NYXT/CERTIFICATE-WHITELIST-MODE::INPUT)
                                      :IN
                                      NYXT/CERTIFICATE-WHITELIST-MODE:ADD-DOMAIN-TO-CERTIFICATE-WHITELIST) {100715E08B}>: There is no applicable method for the generic function
                                                                                                                            #<STANDARD-GENERIC-FUNCTION HISTORY-TREE:DATA (1)>
                                                                                                                          when called with arguments
                                                                                                                            ("example.com").
    See also:
      The ANSI Standard, Section 7.6.6

This prevents the domain from being added to the whitelist. However, adding the domain to `init.lisp` seems to work correctly:

    (setf nyxt/certificate-whitelist-mode:*default-certificate-whitelist*
          '("example.com"))

Can anyone reproduce?

## Version Information

    $ guix describe
    Generation 95	 7月 21 2020 03:33:29	(current)
      guix 84d31a5
        repository URL: https://git.savannah.gnu.org/git/guix.git
        branch: master
        commit: 84d31a5c356bdff541cfaec70630330d69408e14

    $ guix package -I nyxt
    nyxt	1.5.0-1.9440980	out	/gnu/store/n8qxg65mq5sz30bxaahz5pqmlf1ncnci-nyxt-1.5.0-1.9440980

## System Information

    Nyxt version: 1.5.0-1.9440980 
    Operating system kernel: Linux 5.7.9_1
    Lisp implementation: SBCL 2.0.5
    Features: (WEBKIT2 WEBKIT2-2.28 WEBKIT2-EMOJI WEBKIT2-MEDIA WEBKIT2-SANDBOXING
               GTK-3-22 GTK-3-20 GTK-3-18 GTK-3-16 GTK-3-14 GTK-3-12 GTK-3-10
               GTK-3-8 GTK-3-6 GTK-3-4 GTK GDK-3-22 GDK-3-20 GDK-3-18 GDK-3-16
               GDK-3-14 GDK-3-12 GDK-3-10 GDK-3-8 GDK-3-6 GDK-3-4 CAIRO-1-10
               CAIRO-1-12 GDK-PIXBUF GLIB-2-30 GLIB-2-32 GLIB-2-34 GLIB-2-36
               GLIB-2-38 GLIB-2-40 GLIB-2-42 GLIB-2-44 GLIB-2-46 GLIB-2-48
               GLIB-2-50 GLIB-2-52 GLIB-2-54 GLIB-2-56 GLIB-2-58 GLIB
               FSET-EXT-STRINGS SWANK PLUMP-UTF-32 GLOBAL-VARS DECLARE-TYPES
               PARENSCRIPT SBCL+SAFE-STANDARD-READTABLE NAMED-READTABLES
               OSICAT-FD-STREAMS LPARALLEL 21BIT-CHARS CL-FAD CHUNGA FLEXI-STREAMS
               CLOSER-MOP CL-PPCRE-UNICODE CL-UNICODE CL-PPCRE
               CL-JSON-DOUBLE-FLOAT-IS-SUBSUMED CL-JSON-SINGLE-FLOAT-IS-SUBSUMED
               BORDEAUX-THREADS LPARALLEL.WITH-CLTL2 LPARALLEL.WITH-CAS
               LPARALLEL.WITH-STEALING-SCHEDULER SPLIT-SEQUENCE GRAY-STREAMS
               FLAT-NAMESPACE X86-64 UNIX CFFI FLAT-NAMESPACE SEQUENCE-EMPTYP
               FAST-IO-SV FAST-IO SBCL-USES-SB-ROTATE-BYTE CL-JSON-CLOS CL-JSON
               THREAD-SUPPORT ASDF3.3 ASDF3.2 ASDF3.1 ASDF3 ASDF2 ASDF OS-UNIX
               NON-BASE-CHARS-EXIST-P ASDF-UNICODE X86-64 GENCGC 64-BIT ANSI-CL
               COMMON-LISP ELF IEEE-FLOATING-POINT LINUX LITTLE-ENDIAN
               PACKAGE-LOCAL-NICKNAMES SB-CORE-COMPRESSION SB-LDB SB-PACKAGE-LOCKS
               SB-THREAD SB-UNICODE SBCL UNIX)

**Comment by Ambrevar** [comment]
The issue you mention was fixed on master some time ago I think, but
when I verified I noticed there were a few more issues with this
command.


17899255fb81eae301bdfe135f7dd7cbbb7d0714 should fix it all.

If you are using Guix, you can update your Nyxt install by running

guix package --install-from-file=build-scripts/guix.scm

from this repository.

Thanks for reporting!
