### ISSUE TITLE
follow-hint returns error and fails to extract URLs for pages at ncatlab.org

### ISSUE THREAD

**Issue by xelxebar** [atlas-engineer/nyxt#860]
## Summary

Navigate to `https://ncatlab.org/` and execute `follow-hint`. On my machine links are correctly labeled with hints; however, the minibar lists no results and the following error appears in the logs:

    <ERROR> [03:49:29] In #<CLOSURE (LAMBDA (MINIBUFFER)
                                      :IN
                                      NYXT/WEB-MODE::HINT-SUGGESTION-FILTER) {100758E3CB}>: There is no applicable method for the generic function
                                                                                              #<STANDARD-GENERIC-FUNCTION NYXT/WEB-MODE::HINT (1)>
                                                                                            when called with arguments
                                                                                              (NIL).
    See also:
      The ANSI Standard, Section 7.6.6

Is this just me?

## Version Information

    $ guix describe
    Generation 96	 7月 22 2020 00:32:23	(current)
      guix 7cce2a6
        repository URL: https://git.savannah.gnu.org/git/guix.git
        branch: master
        commit: 7cce2a6bd437165b5c21df0abe2d989efa0030d5

    $ guix package -I nyxt
    nyxt	0.0.0	out	/gnu/store/7020n4y4115sclx4k3dk8a22i544gmpx-nyxt-0.0.0

    $ git rev-parse master  # above output built from master
     bc9e192c198ba2eaea8b7597f9e1f6aa2887a229

## System Information

    Nyxt version: 0.0.0 
    Operating system kernel: Linux 5.7.9_1
    Lisp implementation: SBCL 2.0.5
    Features: (WEBKIT2 WEBKIT2-2.28 WEBKIT2-EMOJI WEBKIT2-MEDIA WEBKIT2-SANDBOXING
               GTK-3-22 GTK-3-20 GTK-3-18 GTK-3-16 GTK-3-14 GTK-3-12 GTK-3-10
               GTK-3-8 GTK-3-6 GTK-3-4 GTK GDK-3-22 GDK-3-20 GDK-3-18 GDK-3-16
               GDK-3-14 GDK-3-12 GDK-3-10 GDK-3-8 GDK-3-6 GDK-3-4 CAIRO-1-10
               CAIRO-1-12 GDK-PIXBUF GLIB-2-30 GLIB-2-32 GLIB-2-34 GLIB-2-36
               GLIB-2-38 GLIB-2-40 GLIB-2-42 GLIB-2-44 GLIB-2-46 GLIB-2-48
               GLIB-2-50 GLIB-2-52 GLIB-2-54 GLIB-2-56 GLIB-2-58 GLIB
               FSET-EXT-STRINGS SWANK PLUMP-UTF-32 GLOBAL-VARS DECLARE-TYPES
               PARENSCRIPT SBCL+SAFE-STANDARD-READTABLE NAMED-READTABLES
               OSICAT-FD-STREAMS LPARALLEL 21BIT-CHARS CL-FAD CHUNGA FLEXI-STREAMS
               CLOSER-MOP CL-PPCRE-UNICODE CL-UNICODE CL-PPCRE
               CL-JSON-DOUBLE-FLOAT-IS-SUBSUMED CL-JSON-SINGLE-FLOAT-IS-SUBSUMED
               BORDEAUX-THREADS LPARALLEL.WITH-CLTL2 LPARALLEL.WITH-CAS
               LPARALLEL.WITH-STEALING-SCHEDULER SPLIT-SEQUENCE GRAY-STREAMS
               FLAT-NAMESPACE X86-64 UNIX CFFI FLAT-NAMESPACE SEQUENCE-EMPTYP
               FAST-IO-SV FAST-IO SBCL-USES-SB-ROTATE-BYTE CL-JSON-CLOS CL-JSON
               THREAD-SUPPORT ASDF3.3 ASDF3.2 ASDF3.1 ASDF3 ASDF2 ASDF OS-UNIX
               NON-BASE-CHARS-EXIST-P ASDF-UNICODE X86-64 GENCGC 64-BIT ANSI-CL
               COMMON-LISP ELF IEEE-FLOATING-POINT LINUX LITTLE-ENDIAN
               PACKAGE-LOCAL-NICKNAMES SB-CORE-COMPRESSION SB-LDB SB-PACKAGE-LOCKS
               SB-THREAD SB-UNICODE SBCL UNIX)

**Comment by Ambrevar** [comment]
@jmercouris?

**Comment by jmercouris** [comment]
Hello! Thank you for your report! It is not just you, it seems that the element hints are having problems with that URL. 

There are two possibilities I can think of:

1. We are not able to form a list with the results obtained by the javascript because the javascript is returning malformed value
2. Our javascript is aborting before returning a value

If you open the inspector and execute link hints on that page it may give a hint in the console error message. I'm currently on my cell phone and cannot test. I'll be happy to give it a look at a later time.

**Comment by xelxebar** [comment]
Thanks for the confirmation! As far as I can tell, the JS is not producing any errors. At least, when doing as you suggest, the console is completely clean. :/

**Comment by jmercouris** [comment]
This is now working on master :-)

the new element hints has fixed it! Thank you for your patience!
