### ISSUE TITLE
Handle http-equiv redirects

### ISSUE THREAD

**Issue by xelxebar** [atlas-engineer/nyxt#861]
## Summary

DuckDuckGo in `noscript-mode` displays no results. There is a corresponding `html.duckduckgo.com` which correctly shows results; however, navigating to a search result simply opens a blank page.

Specifically, the search result URLs in the latter case are of the form `https://duckduckgo.com/l/?kh=-1&uddg=https%3A%2F%2Fexample.com` which leads to a simple trampoline page with the following source:

    <html><head><meta name='referrer' content='origin'></head><body><script language='JavaScript'>window.parent.location.replace("https://example.com");</script><noscript><META http-equiv='refresh' content="0;URL=https://example.com"></noscript></body></html>

Naturally, this renders as a blank page. It would be nice to handle the `http-equiv` redirect somehow. Is this sensible? Ideally, we could transparently and immediately redirect; however, another option is to offer redirection with a confirmation dialog. The latter is similar to how lynx handles the above situation.

Thoughts?

## Version Information

    $ guix describe
    Generation 96	 7月 22 2020 00:32:23	(current)
      guix 7cce2a6
        repository URL: https://git.savannah.gnu.org/git/guix.git
        branch: master
        commit: 7cce2a6bd437165b5c21df0abe2d989efa0030d5

    $ guix package -I nyxt
    nyxt	0.0.0	out	/gnu/store/7020n4y4115sclx4k3dk8a22i544gmpx-nyxt-0.0.0

    $ git rev-parse master  # above output built from master
    bc9e192c198ba2eaea8b7597f9e1f6aa2887a229

## System Information

    Nyxt version: 0.0.0 
    Operating system kernel: Linux 5.7.9_1
    Lisp implementation: SBCL 2.0.5
    Features: (WEBKIT2 WEBKIT2-2.28 WEBKIT2-EMOJI WEBKIT2-MEDIA WEBKIT2-SANDBOXING
               GTK-3-22 GTK-3-20 GTK-3-18 GTK-3-16 GTK-3-14 GTK-3-12 GTK-3-10
               GTK-3-8 GTK-3-6 GTK-3-4 GTK GDK-3-22 GDK-3-20 GDK-3-18 GDK-3-16
               GDK-3-14 GDK-3-12 GDK-3-10 GDK-3-8 GDK-3-6 GDK-3-4 CAIRO-1-10
               CAIRO-1-12 GDK-PIXBUF GLIB-2-30 GLIB-2-32 GLIB-2-34 GLIB-2-36
               GLIB-2-38 GLIB-2-40 GLIB-2-42 GLIB-2-44 GLIB-2-46 GLIB-2-48
               GLIB-2-50 GLIB-2-52 GLIB-2-54 GLIB-2-56 GLIB-2-58 GLIB
               FSET-EXT-STRINGS SWANK PLUMP-UTF-32 GLOBAL-VARS DECLARE-TYPES
               PARENSCRIPT SBCL+SAFE-STANDARD-READTABLE NAMED-READTABLES
               OSICAT-FD-STREAMS LPARALLEL 21BIT-CHARS CL-FAD CHUNGA FLEXI-STREAMS
               CLOSER-MOP CL-PPCRE-UNICODE CL-UNICODE CL-PPCRE
               CL-JSON-DOUBLE-FLOAT-IS-SUBSUMED CL-JSON-SINGLE-FLOAT-IS-SUBSUMED
               BORDEAUX-THREADS LPARALLEL.WITH-CLTL2 LPARALLEL.WITH-CAS
               LPARALLEL.WITH-STEALING-SCHEDULER SPLIT-SEQUENCE GRAY-STREAMS
               FLAT-NAMESPACE X86-64 UNIX CFFI FLAT-NAMESPACE SEQUENCE-EMPTYP
               FAST-IO-SV FAST-IO SBCL-USES-SB-ROTATE-BYTE CL-JSON-CLOS CL-JSON
               THREAD-SUPPORT ASDF3.3 ASDF3.2 ASDF3.1 ASDF3 ASDF2 ASDF OS-UNIX
               NON-BASE-CHARS-EXIST-P ASDF-UNICODE X86-64 GENCGC 64-BIT ANSI-CL
               COMMON-LISP ELF IEEE-FLOATING-POINT LINUX LITTLE-ENDIAN
               PACKAGE-LOCAL-NICKNAMES SB-CORE-COMPRESSION SB-LDB SB-PACKAGE-LOCKS
               SB-THREAD SB-UNICODE SBCL UNIX)

**Comment by xelxebar** [comment]
Just tested this against master and updated version info on report accordingly.

**Comment by Ambrevar** [comment]
Just tried on master and I cannot reproduce.
Recipe:

- C-space noscript-mode
- C-l html.duckduckgo.com
- "foo" RET
- Click on the first link

Result: Nyxt properly loads the page.

**Comment by xelxebar** [comment]
Hrm. I'm not sure why noscript DDG is serving you direct URLs. Here is the URL to one of the search results when I search for "foo": https://duckduckgo.com/l/?kh=-1&uddg=https%3A%2F%2Fwww.urbandictionary.com%2Fdefine.php%3Fterm%3Dfoo

Can you confirm that this doesn't redirect when noscript-mode is enabled?

**Comment by Ambrevar** [comment]
This does not redirect when noscript-mode is enabled.

**Comment by kssytsrk** [comment]
I can reproduce this, although I'm only getting it when I'm using the html version of duckduckgo as my search engine (and I can't use the normal, default in Nyxt one because it won't show me the search results). As in:

```
(make-instance 'search-engine
               :shortcut "ddg"
               :search-url "https://html.duckduckgo.com/html/?q=~a"
               :fallback-url "https://html.duckduckgo.com/")
```

When I search directly from html.duckduckgo.com, everything goes alright (and the result page is not "https://html.duckduckgo.com/html/?q=word" but just "https://html.duckduckgo.com/html/", but I'm not sure how could I specify that in `make-instance`). 

Are there any other ways to search with html duckduckgo aside from loading html.duckduckgo.com every time?

**Comment by Ambrevar** [comment]
About the "normal" Duckduckgo: if it does not work, it's probably
because you've disabled Javascript (e.g. with noscript-mode).

I'll see what can be done about http-equiv.

**Comment by aadcg** [comment]
Please re-open this issue if you reproduce it. A lot has changed in the mean time.
