### ISSUE TITLE
Caps Lock presses register (incorrectly?) as "capslock" when caps:ctrl_modifier X Keyboard Option is set

### ISSUE THREAD

**Issue by xelxebar** [atlas-engineer/nyxt#862]
## Summary

Under X, I run with caps lock acting like a control modifier, using X Keyboard Config's option `caps:ctrl_modifier`. This mostly works transparently with nyxt key bindings; however, `describe-key` immediately bails with "unbound" when pressing caps lock:

    <DEBUG> [06:31:32] nyxt renderer-gtk.lisp (on-signal-key-press-event gtk-window) -
      NYXT::KEY-STRING: "capslock" NYXT::KEYCODE: 66 CHARACTER: #\Nul
      NYXT::KEYVAL-NAME: "Caps_Lock"
    <DEBUG> [06:31:32] nyxt input.lisp (dispatch-input-event) -
      Fallback forward key "\"capslock\" [#66]"
    <DEBUG> [06:31:32] nyxt renderer-gtk.lisp (on-signal-key-press-event gtk-window) -
      NYXT::KEY-STRING: "h" NYXT::KEYCODE: 44 CHARACTER: #\h NYXT::KEYVAL-NAME: "h"
      NYXT::MODIFIERS: ("control")
     <INFO> [06:31:32] nyxt message.lisp (echo form-fun-6) - Pressed keys: C-h
    <DEBUG> [06:31:32] nyxt input.lisp (dispatch-input-event) -
      Prefix binding "C-h" [C-#44]
    <DEBUG> [06:31:33] nyxt renderer-gtk.lisp (on-signal-key-press-event gtk-window) -
      NYXT::KEY-STRING: "k" NYXT::KEYCODE: 55 CHARACTER: #\k NYXT::KEYVAL-NAME: "k"
    <DEBUG> [06:31:33] nyxt input.lisp (dispatch-input-event) -
      Found key binding "C-h k" [C-#44 #55]
    <DEBUG> [06:31:33] nyxt help.lisp (describe-key form-fun-6) -
      Calling command DESCRIBE-KEY.
     <INFO> [06:31:33] nyxt message.lisp (echo form-fun-6) -
      Press a key sequence to describe (cancel with 'escape escape'):
    <DEBUG> [06:31:34] nyxt renderer-gtk.lisp (on-signal-key-press-event gtk-window) -
      NYXT::KEY-STRING: "capslock" NYXT::KEYCODE: 66 CHARACTER: #\Nul
      NYXT::KEYVAL-NAME: "Caps_Lock"
    <DEBUG> [06:31:34] nyxt help.lisp (describe-key-dispatch-input form-fun-4) -
      Intercepted key #S(KEY
                         :CODE 66
                         :VALUE capslock
                         :MODIFIERS #{ }
                         :STATUS PRESSED)
     <INFO> [06:31:34] nyxt message.lisp (echo form-fun-6) - Unbound.

Ideally, `describe-key` would also Just Work transparently, but is there any reasonable way to realize this? At the moment it looks like "key presses" are defined at keydown events; however, if there were a way to only inspect the keyup events then maybe this would allow the X Keyboard Configuration to intevene as necessary? I am not even sure if that makes sense in the context of Gtk applications though.

Thoughts?

## Version Information

    $ guix describe
    Generation 96	 7月 22 2020 00:32:23	(current)
      guix 7cce2a6
        repository URL: https://git.savannah.gnu.org/git/guix.git
        branch: master
        commit: 7cce2a6bd437165b5c21df0abe2d989efa0030d5

    $ guix package -I nyxt
    nyxt	0.0.0	out	/gnu/store/7020n4y4115sclx4k3dk8a22i544gmpx-nyxt-0.0.0

    $ git rev-parse master  # above output built from master
    bc9e192c198ba2eaea8b7597f9e1f6aa2887a229

## System Information

    Nyxt version: 0.0.0 
    Operating system kernel: Linux 5.7.9_1
    Lisp implementation: SBCL 2.0.5
    Features: (WEBKIT2 WEBKIT2-2.28 WEBKIT2-EMOJI WEBKIT2-MEDIA WEBKIT2-SANDBOXING
               GTK-3-22 GTK-3-20 GTK-3-18 GTK-3-16 GTK-3-14 GTK-3-12 GTK-3-10
               GTK-3-8 GTK-3-6 GTK-3-4 GTK GDK-3-22 GDK-3-20 GDK-3-18 GDK-3-16
               GDK-3-14 GDK-3-12 GDK-3-10 GDK-3-8 GDK-3-6 GDK-3-4 CAIRO-1-10
               CAIRO-1-12 GDK-PIXBUF GLIB-2-30 GLIB-2-32 GLIB-2-34 GLIB-2-36
               GLIB-2-38 GLIB-2-40 GLIB-2-42 GLIB-2-44 GLIB-2-46 GLIB-2-48
               GLIB-2-50 GLIB-2-52 GLIB-2-54 GLIB-2-56 GLIB-2-58 GLIB
               FSET-EXT-STRINGS SWANK PLUMP-UTF-32 GLOBAL-VARS DECLARE-TYPES
               PARENSCRIPT SBCL+SAFE-STANDARD-READTABLE NAMED-READTABLES
               OSICAT-FD-STREAMS LPARALLEL 21BIT-CHARS CL-FAD CHUNGA FLEXI-STREAMS
               CLOSER-MOP CL-PPCRE-UNICODE CL-UNICODE CL-PPCRE
               CL-JSON-DOUBLE-FLOAT-IS-SUBSUMED CL-JSON-SINGLE-FLOAT-IS-SUBSUMED
               BORDEAUX-THREADS LPARALLEL.WITH-CLTL2 LPARALLEL.WITH-CAS
               LPARALLEL.WITH-STEALING-SCHEDULER SPLIT-SEQUENCE GRAY-STREAMS
               FLAT-NAMESPACE X86-64 UNIX CFFI FLAT-NAMESPACE SEQUENCE-EMPTYP
               FAST-IO-SV FAST-IO SBCL-USES-SB-ROTATE-BYTE CL-JSON-CLOS CL-JSON
               THREAD-SUPPORT ASDF3.3 ASDF3.2 ASDF3.1 ASDF3 ASDF2 ASDF OS-UNIX
               NON-BASE-CHARS-EXIST-P ASDF-UNICODE X86-64 GENCGC 64-BIT ANSI-CL
               COMMON-LISP ELF IEEE-FLOATING-POINT LINUX LITTLE-ENDIAN
               PACKAGE-LOCAL-NICKNAMES SB-CORE-COMPRESSION SB-LDB SB-PACKAGE-LOCKS
               SB-THREAD SB-UNICODE SBCL UNIX)

**Comment by Ambrevar** [comment]
I can't reproduce with the following option:

ctrl:swapcaps

Recipe:

- f1-k C-o

Result: I get the load-file doc page.

To be clear, do you press _and release_ caps lock, or do you use it as a modifier?

Does the equivalent work for you in Emacs?

**Comment by xelxebar** [comment]
Interesting, when I set `ctrl:swapcaps` it works for me as well (even in `vi-normal-mode`). The logs show that Caps Lock presses register as "control". Would you mind confirming with `caps:ctrl_modifier`?

**Comment by Ambrevar** [comment]
Looks like caps:ctrl_modifier does nothing for me.

```
setxkbmap -v
Trying to build keymap using the following components:
keycodes:   evdev+aliases(qwerty)
types:      complete
compat:     complete
symbols:    pc+us(altgr-intl)+inet(evdev)+nbsp(level3)
geometry:   pc(pc105)
```

**Comment by aadcg** [comment]
Not reproducible.
