### ISSUE TITLE
Display news on start

### ISSUE THREAD

**Issue by xelxebar** [atlas-engineer/nyxt#865]
## Overview

In a discussion with @jmercouris on IRC brought to light a few points regarding `startup-function` we might want to think about. This issue is to initiate some brainstorming.

The main points so far are thus:

1) Do we want a *News* page at startup?

Currently, the first page to open at Nyxt startup is `*Help*`. This is indespensible as a new Nyxt initiate; however, quickly one graduates from the need of this information. Would it make sense to add something like a "News" section that would be useful even to veteran users? Perhaps a second "*News*" buffer?

2) Customizing the first buffer to open on Nyxt startup is hard.

Additionally, users may very soon wish to customize this startup page. However, at the moment, the only option is to completely override `startup-function` which is non-trivial. Furthermore, since `default-startup` is not an external symbol, users cannot even write lambda wrappers for simple extensions. Should it be made external?

Note, that the documents list a `start-page-url` and describes it as "The URL of the first buffer opened by Nyxt when started," but `start-page-url` is not used anywhere in our current codebase. @jmercouris pointed out that this slot is a historical relic. Should it be removed?

Better yet, how about reviving it and letting it overide `help` in `default-startup`?

3) Is there a better way of customizing `startup-function`?

More generally, providing a complete `startup-function` can a bit daunting at first, especially if one just wants to make a small change or addition to the default. What are some options for helping users tweak and extend its behaviour incrementally? @jmercouris suggests adding extra optional arguments to `startup-function` that could then override things like the initial `help` buffer, etc.

Thoughts?

**Comment by Ambrevar** [comment]
Thanks for your feedback!

I've just remove the obsolete start-page-url and I've exported `default-startup` (for now).

See #867 for a change that should make it easier to customize the default URL.
Example configuration:

```lisp
(define-configuration browser
  ((startup-function (make-startup-function :buffer-fn (lambda () (make-buffer :url "https://example.org"))))))

```

What do you think?

**Comment by xelxebar** [comment]
Yeah, that commit looks like what @jmercouris initially suggested.
What was the original reason for deprecating `start-page-url` in the first place? To my newbie eyes, having to supply a lambda just to configure a url feels odd. I'm curious about the broader picture in terms of design decision.

**Comment by Ambrevar** [comment]
The lambda is much more flexible.  This allows the user to fully
customize the startup behaviour beyond merely setting the URL.  For
instance, you can use this function to decide not to spawn a default
buffer if there is a session to restore.

Having an extra public slot just to set the default URL is too
shortsighted in my opinion.

If you like the pull request, I've sent I'll merge it later then.

**Comment by jmercouris** [comment]
I like the PR as well! Well done! I am also wondering how we will add news, but this does not concern configuration, but rather the default startup function. Shall we open up a news buffer?

**Comment by Ambrevar** [comment]
Another buffer might get unnoticed or feel like clutter to the user.
On the other hand, our current help buffer is long enough.  I'm not
sure.  Maybe add a foldable section?

I can think of 2 types of news:

- Upstream news: we let know the user of the last release of Nyxt.
  Since this requires network access, I believe this because to https://nyxt.atlas.engineer/start

- Latest changes: this is the ChangeLog at the time of the build.
  I can think of an easy way to implement this:
  - Turn the ChangeLog to s-exps.
  - Add a `changelog` command that displays it.
  - Add a `latest-changes` command that displays the changes in the last
    version only.
    This is the command we can leverage in the default startup
    function.  I'm just not sure how to display it (other buffer or not).

**Comment by xelxebar** [comment]
@Ambrevar Sounds fair to me. I trust your judgement more than my own vague impressions!

Regarding the news page, what about deferring to a `nyxt` url? FWIW, I would vote against requiring network access to load content on the default start page. The changelog idea is interesting, though!

**Comment by aartaka** [comment]
> - Turn the ChangeLog to s-exps. 

Do we need to alter it manually, if the CHANGELOG is already an Org file that can be relatively easy to parse? `cl-org-mode` should be sufficient for that, given that CHANGELOG.org has no advanced Org features in it.

**Comment by jmercouris** [comment]
Good question. The answer is ostensibly no, we don't. However it does appeal to my sense of neatness that everything be in SEXP 
:-D

**Comment by jmercouris** [comment]
The changelog is now embedded into Nyxt!

**Comment by aadcg** [comment]
Are we still pursuing this?

**Comment by aartaka** [comment]
Not sure. We have a changelog and our policy for startup pop-ups is to have as little of them as we can. So I'd say that we shouldn't make a changelog popup at all, unless one explicitly clicks on the changelog button to see it.

**Comment by aadcg** [comment]
I fully agree.
