### ISSUE TITLE
auto-mode polishing: "main URL" predicate, mode-symbol type

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#868]
As discussed in #846:

1. The typing of serialized mode is a bit ad-hoc.  It'd be nice to add a mode-symbol type.  We already have much of the logic implemented.

2. In `auto-mode-request-handler` we rely on the `(quri:uri= (url request-data) (url (buffer auto-mode)))` condition which is a bit obscure.  As far as I understand, this is the only way to test if the current request is the one the "main" one (the request for the current URL).  If so, we'd need to extract the condition to a well-named predicate to make this clearer.

3. Maybe improve logging.

Thoughts? @aartaka

**Comment by Ambrevar** [comment]
4. Now the auto-mode-list file can only persist the exact list of modes unless I'm mistaken.  We need to add a way to persist the modes to include or exclude as was intiallly discussed.

The practical example is when we want to disable just one mode, say force-https-mode, but leave the rest of the modes to the default.  So if later we change the defaults modes, we won't have to update the whole list of 

I believe `save-modes-to-auto-mode-list` should use `:include-modes` and `:excludes-modes` by default.  We can leave the exact list of modes for manual editing of auto-mode-list.lisp.

Thoughts?

**Comment by aartaka** [comment]
>  1. The typing of serialized mode is a bit ad-hoc. It'd be nice to add a mode-symbol type. We already have much of the logic implemented.

I don't quite get what this `mode-symbol` type should look like. In other words, what should its `satisfied` predicate look like?

>  2. In `auto-mode-request-handler` we rely on the `(quri:uri= (url request-data) (url (buffer auto-mode)))` condition which is a bit obscure.  As far as I understand, this is the only way to test if the current request is the one the "main" one (the request for the current URL).  If so, we'd need to extract the condition to a well-named predicate to make this clearer. 

That's a good idea! It can be useful for the end-user too, because then custom handlers for `request-resource-hook` can be more flexible.

You've mentioned in [this comment](https://github.com/atlas-engineer/nyxt/pull/846#discussion_r460760813) that link clicks are somewhat outside the scope of this condition. Is it because all the clicks are passed to the renderer (not sure abour that, need to look it up in the codebase)? Should it be included in this predicate for "main" URL requests then? 

Somewhat unrelated: should Nyxt have it's own mouse-events-processing code, instead of relying on WebKit? It can be useful for mouse gesture customizations, for example. As I recall, Emacs has such feature, but I haven't used it, so I can't say how useful/working it is.

> 3. Maybe improve logging.

I don't see much necessity in logging, because only one `auto-mode-rule` can be activated on a given URL. It should be easy to infer which one it was, based on the rules in `auto-mode-list-data-path` file. 

However, I'm in doubt, because using `auto-mode` for a long time can result in huge and hard-to-navigate rule list.

**Comment by aartaka** [comment]
> The practical example is when we want to disable just one mode, say force-https-mode, but leave the rest of the modes to the default. So if later we change the defaults modes, we won't have to update the whole list of
> 
> I believe `save-modes-to-auto-mode-list` should use `:include-modes` and `:excludes-modes` by default. We can leave the exact list of modes for manual editing of auto-mode-list.lisp.

Do you mean `add-modes-to-auto-mode-list` as the place for keywords? `save-modes-...` is a user-facing command, and keywords are not the most straightforward thing in interactive command.

As an alternative, we can get back to the `disable-and-exclude-mode` (and, maybe, its including counterpart) from initial version of `auto-mode`. Then we won't need to alter the signature of `add-modes-...`, because mode exclusion/inclusion will happen in the dedicated easy-to-use commands.

And I'd stay with exact list of modes in the auto-mode-list.lisp no matter what option we pick, because it's more transparent and predictable.

**Comment by Ambrevar** [comment]
Artyom Bologov <notifications@github.com> writes:

>>  1. The typing of serialized mode is a bit ad-hoc. It'd be nice to add a mode-symbol type. We already have much of the logic implemented.
>
> I don't quite get what this `mode-symbol` type should look like. In other words, what should its `satisfied` predicate look like?

Untested: find the class corresponding to the symbol and check that it
subclasses root-mode.

> You've mentioned in [this
> comment](https://github.com/atlas-engineer/nyxt/pull/846#discussion_r460760813)
> that link clicks are somewhat outside the scope of this condition.

You've misunderstood.  Clicks _are_ in the scope of this condition, they
are not in the scope of the `buffer-load` function.

I was only highlighting that we can't just capture the event in
`buffer-load` because that would miss URL click events.

> Somewhat unrelated: should Nyxt have it's own mouse-events-processing code, instead of relying on WebKit? It can be useful for mouse gesture customizations, for example. As I recall, Emacs has such feature, but I haven't used it, so I can't say how useful/working it is.

We already have it:

- `on-signal-button-press-event`
- `on-signal-scroll-event`

If you want to implement mouse gestures, we'd need to add an event
handler for mouse coordinates.

>> 3. Maybe improve logging.

See my next comment on user confirmations.

**Comment by Ambrevar** [comment]
Artyom Bologov <notifications@github.com> writes:

> Do you mean `add-modes-to-auto-mode-list` as the place for keywords? `save-modes-...` is a user-facing command, and keywords are not the most straightforward thing in interactive command.

No, I meant keep the interactive part of save-modes-to-auto-mode-list as
it is, but instead of storing the full list of modes, only store the
difference to the default list of modes.  To store this difference, we
need 2 more slot in the rule class: one for mode inclusion, one for mode exclusion.

> And I'd stay with exact list of modes in the auto-mode-list.lisp no matter what option we pick, because it's more transparent and predictable.

We can have both.
In my above example, the downside (which I'm experiencing after just an
hour of use) is that I can't customize my default list of modes without
having to update all entries in auto-mode-list.  I'd like something more dynamic.

**Comment by Ambrevar** [comment]
5. When `*prompt-on-mode-toggle*` is nil, prompt the user for the list of modes th activate when a rule is matched.  This is much safer because if a rule fails to be matched, or if the list of modes is incorrect, the user can proof-check before loading the URL.

**Comment by Ambrevar** [comment]
6. This fell under my radar, but should we name the file `auto-mode-rules` for consistency?  It's also more accurate and self-explanatory.

**Comment by aartaka** [comment]
> 1. This fell under my radar, but should we name the file `auto-mode-rules` for consistency?  It's also more accurate and self-explanatory.

Definitely!

**Comment by aartaka** [comment]
> 1. When `*prompt-on-mode-toggle*` is nil, prompt the user for the list of modes th activate when a rule is matched.  This is much safer because if a rule fails to be matched, or if the list of modes is incorrect, the user can proof-check before loading the URL.

I thought that non-prompting mode a power-user-aimed mode of use when it's implied that the user know what they are doing, when saving all the modes for the given URL. It's plainly annoying to check the list of modes on every mode saving or URL matching in this philosophy, I guess.

But what you've hinted at is important. Is it a third use scenario then -- in between the "exhaustive dialogues with machine" and "power-user"?

**Comment by Ambrevar** [comment]
Artyom Bologov <notifications@github.com> writes:

> I thought that non-prompting mode a power-user-aimed mode of use when it's implied that the user know what they are doing, when saving all the modes for the given URL. It's plainly annoying to check the list of modes on every mode saving or URL matching in this philosophy, I guess.
>
> But what you've hinted at is important. Is it a third use scenario then -- in between the "exhaustive dialogues with machine" and "power-user"?

Indeed, we could have an extra global parameter for this.

With this scenario, the prompt need not happen so many times in
practice.
In particular, it can be optimized in one way: if the new URL matches
the same rule as the old one, then don't prompt.

By the way... Isn't the above suggestion the "do what I mean" behaviour?

Take this example:

- I go to http://foo.org/, which has a rule.
- I browse a subpage which has pictures.  I disable noimage-mode to see
  it, but I don't save the mode list because I know I'm not going to
  browse many subpages with pictures.
- I browse another subpage with pictures again.  Currently, Nyxt would
  reapply the rule.  I think it should not since the last page had the
  same rule, it should just keep the current modes and thus keep
  noimage-mode disabled.

Thoughts?

**Comment by Ambrevar** [comment]
7\. Found an issue when using force-https-mode by default, with a rule to disable it for, say, www.sbcl.org.
It can when force-https-mode is run before aut-mode.

Generally speaking, auto-mode would need to be run before any other mode that interacts with the URL.
What's the simplest way?  Have auto-mode reorder itself in first position in request-resource-hook?  Add another hook before request-resource-hook?

**Comment by Ambrevar** [comment]
8\. Full-URL rules don't seem to ever match.

**Comment by aartaka** [comment]
> 7. Found an issue when using force-https-mode by default, with a rule to disable it for, say, [www.sbcl.org](http://www.sbcl.org).
> It can when force-https-mode is run before aut-mode.
> 
> Generally speaking, auto-mode would need to be run before any other mode that interacts with the URL.
> What's the simplest way? Have auto-mode reorder itself in first position in request-resource-hook? Add another hook before request-resource-hook?

While implementing `auto-mode`, I've struggled with the `request-resource-hook` having a non-obvious handlers' execution order. Can the shift from `combine-composed-hook-until-non-nil-second-value` to `combine-composed-hook-until-nil` be the reason for this change of order? Docstring says the newest handler runs first, but it doesn't seem to work in practice.

But putting it in the first position should work once we're sure in the handlers execution order in `request-resource-hook`.

**Comment by Ambrevar** [comment]
Strange,  looking at `combine-composed-hook-until-non-nil`, it seems the
handlers are executed in an unambiguous order:

```
(defmethod combine-composed-hook-until-nil ((hook hooks:hook) &optional arg)
  "Return the result of the composition of the HOOK handlers on ARG, from
oldest to youngest.  Stop processsing when a handler returns nil.
Without handler, return ARG.  This is an acceptable `combination' for
`hook'."
  (labels ((compose-handlers (handlers result)
             (if handlers
                 (let ((new-result (funcall (first handlers) result)))
                   (when new-result
                     (compose-handlers (rest handlers) new-result)))
                 result)))
    (compose-handlers (mapcar #'hooks:fn (hooks:handlers hook)) arg)))
```

Can you provide a recipe to reproduce the order issue?

**Comment by aartaka** [comment]
>     1. This fell under my radar, but should we name the file `auto-mode-rules` for consistency?  It's also more accurate and self-explanatory.

Then we should rename the `auto-mode-list-data-path` and/or `auto-mode-list` for consistency. 

I think that we can rename the storage file to "auto-mode-rules.lisp" and `auto-mode-list-data-path` to `auto-mode-rules-data-path`, while leaving `auto-mode-list` as it is, because it's reminiscent to Emacs' `auto-mode-alist`. Other two aren't particularly similar to what Emacs has and can be named differently. However, this brings some inconsistency. What's better there -- having a familiar name or being consistent?

Then the options are:
- Leave things with `...-list-...`.
- Partially rename things.
- Rename everything to `...-rules-...` form.

What do you think?

**Comment by Ambrevar** [comment]
I'd go for "rules" everywhere.
Familiarity with Emacs is good only if it comes at no cost.
After all, not all Nyxt users are Emacs users.

**Comment by aartaka** [comment]
To recap the discussion on evaluation order:
- Making something alter it's own storage is a "recipe for disaster". We do it in `auto-mode` now and it's bad.
- Extracting `auto-mode`-related handler to a separate place is safer and it gives us more control over order issues.

But where should we store the `auto-mode-request-handler` and should we even store it? Adding the conditional call to the `auto-mode-request-handler` to the `on-signal-decide-policy` sounds like a good option to me.
- This would require renaming the `auto-mode-request-handler` to something more meaningful, because it's not a handler anymore.
+ We can pass `buffer` and `url` right to `auto-mode-request-handler` and we won't need the `request-data` abstraction.

The code then could be:
``` lisp
(when (find-submode buffer 'auto-mode)
      (auto-mode-handler buffer url))
```
right before 
``` lisp
(if (null (hooks:handlers (request-resource-hook buffer))) ...
```

Is it dangerous to hardcode it to the WebKitGTK-specific function?

**Comment by aartaka** [comment]
> I'd go for "rules" everywhere. 
> Familiarity with Emacs is good only if it comes at no cost. 
> After all, not all Nyxt users are Emacs users.

Makes sense!

**Comment by Ambrevar** [comment]
Artyom Bologov <notifications@github.com> writes:

> Is it dangerous to hardcode it to the WebKitGTK-specific function?

No, this is the right place.

However, maybe we can go a bit more general.  In particular, having
(find-submode ...) in the GTK function is not right, since mode-related
code belong to modes.

I suggest the following: add a pre-request-hook (feel free to choose a
better name) which is empty by default.  Run this hook just as you
described it, and add the auto-mode-request-handler to it when auto-mode
is enabled.

Does that make sense?  What do you think?

**Comment by aartaka** [comment]
Given that this pre-request-hook is going to be used only by `auto-mode`, isn't it an overkill?

I agree about the wrongness of `(find-submode ...)` there though. Unlless there's no better option than creating highly specific hooks, your solution is the way to go :)

**Comment by Ambrevar** [comment]
Artyom Bologov <notifications@github.com> writes:

> Given that this pre-request-hook is going to be used only by `auto-mode`, isn't it an overkill?

Maybe.

It would be the right hook to use for any handler that reorders or
toggles the handlers in request-resource-hook.

Let's sleep over it and see if we can come up with a simpler solution tomorrow.

**Comment by aartaka** [comment]
>  1. Now the auto-mode-list file can only persist the exact list of modes unless I'm mistaken.  
> We need to add a way to persist the modes to include or exclude as was intiallly discussed.

> I believe `save-modes-to-auto-mode-list` should use `:include-modes` and `:excludes-modes` by default. We can leave the exact list of modes for manual editing of auto-mode-list.lisp.

Having `included-modes`, `excluded-modes` and `exact-p` as `auto-mode-rule` slots (as it was in one of the initial `auto-mode` versions) sounds better to me, because it's the best of both approaches. You can store only one excluded/additional mode, but then you can store all the present modes and set the `exact-p` to `t`, enabling only the `included-modes` and disabling everything else, especially the `excluded-modes`.

As per serialization, I think we'd better explicitly say that there are `:included-modes`, `:excluded-modes` and `:exact-p`. Exact list of modes can be hard (or even impossible) to analyze and split into these slots on deserialization. It's safer to be explicit there.

**Comment by Ambrevar** [comment]
> Having `included-modes`, `excluded-modes` and `exact-p` as `auto-mode-rule` slots (as it was in one of the initial `auto-mode` versions) sounds better to me, because it's the best of both approaches. You can store only one excluded/additional mode, but then you can store all the present modes and set the `exact-p` to `t`, enabling only the `included-modes` and disabling everything else, especially the `excluded-modes`.

Agreed!

> As per serialization, I think we'd better explicitly say that there are `:included-modes`, `:excluded-modes` and `:exact-p`. Exact list of modes can be hard (or even impossible) to analyze and split into these slots on deserialization. It's safer to be explicit there.

You mean we should not have a :exact-list-of-mode slot?  Well, of course
the serialization should have a 1-1 mapping with the slots, so you
suggestion makes total sense.

**Comment by aartaka** [comment]
Another question on exactness: what behaviour should be the default one -- the "exact" (i.e. enabling exact list of stored modes, same as how it works now) or "dynamic" (i.e. enabling `:included` modes and disabling `:excluded` modes, while retaining what's already there)?

I think that the "dynamic" behavior is a bit more intuitive for everyday use (you've experienced it yourself) while "exact" is somewhat special and has a restricted area of application. Does it make sense?

**Comment by Ambrevar** [comment]
I think the default behaviour should be dynamic, because this is what's
easiest to edit.  Exact mode lists can be filled by hand, while it takes
more investigation to come up with the dynamic mode list (the user would
need to mentally subtract the default modes from the activated modes).

**Comment by Ambrevar** [comment]
9\. It's possible to persist rules with default modes, which will result in a useless

```
((match-domain "foo.org"))
```

entry.  I suggest we don't persist anything in this case.

**Comment by Ambrevar** [comment]
To sum up the above, here is what's left to be done beside 9\. above.

1\. (Optional) Add mode-symbol type.
5\. Confirmation dialog: Looks like a significant amount of work remains to be done, as discussed in #883.

**Comment by aartaka** [comment]
Okay, I've tested the hook behavior with asynchronous/timed constructs.

- If there's a timer, Nyxt hangs for a given number of seconds, but then loads the requested page flawlessly. It cuts off some fraction of the time without an obvious reason though (I've measured it on `(sleep 30)` and it waited for around 15 seconds only).
- Async constructs are just taken for synchronous and their immediate result is taken (it's `-1` in case of `if-confirm`). This stops pages from loading when async constructs are present in hooks and when there's nothing returning a good result after them.

You can test both behaviors with these `url-dispatching-handler`s:
``` lisp
(url-dispatching-handler
 'timed-loading
 (match-regex ".*")
 (lambda (url)
   (sleep 30) ; Adjust time and look at the behavior
   url))
(url-dispatching-handler
 'prompt-user-async
 (match-regex ".*")
 (lambda (url)
   (if-confirm ("Wait a bit and look whether the page loads.")
               url)  ; This only should be enough, but it's not
           ;;; No result causes errors.
   ;; url  ; This causes URL to load as if nothing stops it
   ;; nil  ; This causes URL to not load
   ))
```

**Comment by aartaka** [comment]
Should we notify the user that their mode setup is default on empty rule creation (as in 9)? I think that writing "Saved N auto-mode rules..." is misleading in this case and we should write something like "The last rule you saved is empty. Possibly all the modes you have enabled are already in your `default-modes`".

**Comment by Ambrevar** [comment]
Artyom Bologov <notifications@github.com> writes:

> Okay, I've tested the hook behavior with asynchronous/timed constructs.
>
> - If there's a timer, Nyxt hangs for a given number of seconds, but then loads the requested page flawlessly. It cuts off some fraction of the time without an obvious reason though (I've measured it on `(sleep 30)` and it waited for around 15 seconds only).

This is very strange.  What happens if you sleep 60 seconds?

> - Async constructs are just taken for synchronous and their immediate result is taken (it's `-1` in case of `if-confirm`). This stops pages from loading when async constructs are present in hooks and when there's nothing returning a good result after them.

This is expected.  Thinking more about it, I wonder if we really need
synchronous minibuffers here.  Maybe it's enough to stop the request and
in the asynchronous code decide to restart the request or not.

**Comment by aartaka** [comment]
> It cuts off some fraction of the time without an obvious reason though (I've measured it on `(sleep 30)` and it waited for around 15 seconds only).

> This is very strange. What happens if you sleep 60 seconds?

Re-tested now, and it waits exactly 60 seconds when you use `(sleep 60)` and 30 seconds in case of `(sleep 30)`. I can't even guess what happened the previous time I tested, because now it's perfect on time.

> Thinking more about it, I wonder if we really need synchronous minibuffers here. Maybe it's enough to stop the request and in the asynchronous code decide to restart the request or not.

We can go the other way around and create an `asynchronous-hook-(resource|mode|uri|.*)` class that'd wait for the asynchronous forms to finish. I doubt it's easy (or even possible) to implement, but it's definitely more elegant than stopping the request and/or making essentially asynchronous minibuffers synchronous.

Searching through the bodies of handlers can help in noticing the async constructs and waiting for the result on `%callback` call. Several problems:
- How can we hook into the exact call that relates to the given async form? Can introduction of `%callback-hook` be a good option there?
- Where should we keep bodies of handlers, if we are to analyse them?
- Should we finally abstract `%callback` to a monad, as suggested in TODO comment, to make this callback handling more controllable? I don't yet fully grok monads and can't do it myself, though :)

It's a lot of design decisions to wrap one's head around :)

**Comment by Ambrevar** [comment]
> We can go the other way around and create an
> `asynchronous-hook-(resource|mode|uri|.*)` class that'd wait for the
> asynchronous forms to finish. I doubt it's easy (or even possible) to
> implement, but it's definitely more elegant than stopping the request
> and/or making essentially asynchronous minibuffers synchronous.

From
https://webkitgtk.org/reference/webkit2gtk/stable/WebKitWebView.html#WebKitWebView-decide-policy:

> It is possible to make policy decision asynchronously, by simply calling g_object_ref() on the decision argument and returning TRUE to block the default signal handler. 

The question is, how do we make the distinction between a synchronous
handler and an asynchronous one?
Maybe it's easier to assume that they are all asynchronous.  This way we
would always return TRUE in `on-signal-decide-policy` and invoke
`(webkit:webkit-policy-decision-use DECISION)` when the asynchronous
hook returns.

> Searching through the bodies of handlers can help in noticing the
> async constructs and waiting for the result on `%callback`
> call. Several problems:
> - How can we hook into the exact call that relates to the given async
> form? Can introduction of `%callback-hook` be a good option there?

What would you like to do in particular?  Do you have an example?

> - Where should we keep bodies of handlers, if we are to analyse them?

Analyzing code is too brittle.  It would enable so many edge cases it
would not be maintainable.

Maybe a better approach is to use a dedicated object/class that contains
the form to execute.  A bit like our hook handlers.

> - Should we finally abstract `%callback` to a monad, as suggested in
> TODO comment, to make this callback handling more controllable? I
> don't yet fully grok monads and can't do it myself, though :)

The only monad implementation I could find for Common Lisp is
https://common-lisp.net/project/cl-monad-macros/monad-macros.htm.  The
library may be a bit dusty but could be a good starting point.

Racket has this: https://docs.racket-lang.org/heresy/monad-do.html

Guix also has a monad library.

**Comment by aartaka** [comment]
Well, all these questions were about particular implementation I had in mind, but now, when you mentioned this feature of WebKitGTK, they are unnecessary :) I'll look into it and see how we can implement asynchronous hooks.

**Comment by jmercouris** [comment]
What is the justification for using monads in a language like Common Lisp? I don't understand them, so I can't understand what benefits they bring to us.

**Comment by Ambrevar** [comment]
> What is the justification for using monads in a language like Common Lisp? I don't understand them, so I can't understand what benefits they bring to us.

Monads are a general-purpose tool (in the sense that all languages can
benefit from it) that's not present in Common Lisp by default.  Haskell
is a language that makes use of monads by default.

A good intro here:

  http://okmij.org/ftp/Scheme/monad-in-Scheme.html

In short, it allows you to control side effects when you need impurity in
functional programming.  It makes for much cleaner code.

Another benefit of monads is that they allow you to pass context around
without resorting to globals and without having to pass the context as
parameters to all functions, which would be tedious and does not compose
well.  This is what we want here.

Another Racket implementation:

http://planet.racket-lang.org/package-source/toups/functional.plt/1/1/planet-docs/better-monads-guide/index.html

**Comment by aartaka** [comment]
Seems like all of the points here are resolved. I'm closing it. In case I missed something, feel free to reopen!

**Comment by Ambrevar** [comment]
Indeed, we've gone very far with auto-mode, this was a big one!  Congrats for keeping up with the intensity of the task :)

What about 5.?

> When *prompt-on-mode-toggle* is nil, prompt the user for the list of modes to activate when a rule is matched. This is much safer because if a rule fails to be matched, or if the list of modes is incorrect, the user can proof-check before loading the URL.

**Comment by aartaka** [comment]
Yes, it's the only one that's not explicitly covered. The last time we discussed this feature, we decided that it doesn't bring much benefit and can be discarded :)

**Comment by Ambrevar** [comment]
OK.  I personally don't have a use case for it.  If anyone feels like it's missing, they will hopefully complain! :)
