### ISSUE TITLE
Feature request: Insert last search

### ISSUE THREAD

**Issue by walseb** [atlas-engineer/nyxt#870]
When searching a page using `C-f` I often want to take a look around the current hit for a bit. Currently after you are done and want to get back to the search you were doing before hitting return you have to re-type the whole query again. This is solved in `swiper` by allowing the user to re-insert the search just before you hit return by pressing the search key again (so for nyxt `C-f C-f` would insert the last search into the search bar).

I looked around the code a bit and `minibuffer-search-history` seems to almost be made for this purpose, but I can't find any way to use it or any commands defined that make use of it. Am I missing something here? Thanks!

**Comment by jmercouris** [comment]
Hello, thank you for your interest in Nyxt!

I think I know what you are trying to do. Please try the following example workflow:

1. Go to a page
2. Search "xyz"
3. RET
4. Bring up search again
5. Press M-h

After step 5, you should see "xyz" as one possibility, it should be part of your minibuffer input history. Does that work for you/satisfy your requirements?

**Comment by walseb** [comment]
Thanks a lot! That's great, but it would be nice if there was a command that just picks the most recent one given that it's so common to do so for me atleast. 

As a side note, I see now that you can't do as I suggested and bind the search key to open this `M-h` menu up since `C-f` is already bound to move cursor forward in the minibuffer.

**Comment by Ambrevar** [comment]
This can be fixed properly with the new minibuffer (see #1157) by making a `resume-search` command that picks the last prompt buffer that's a search.

**Comment by Ambrevar** [comment]
This is now on master.
