### ISSUE TITLE
Nyxt master crashes on paste

### ISSUE THREAD

**Issue by walseb** [atlas-engineer/nyxt#871]
**Describe the bug**
Nyxt crashes whenever I try to paste anything in the minibuffer and on any webpage
When I look at the paste-ring it's always empty too. Maybe this has something to do with me running exwm without any external clipboard managers.

**Precise recipe to reproduce the issue**
1. Run `./nyxt --no-init`
2. Highlight any text, right-click and press copy
3. Press `C-l`
4. Press `C-v` a few times
Nyxt now crashes

**Information**
- OS name+version: 
nixos+20.03

- Graphics card and driver:
    Vendor: Intel Open Source Technology Center (0x8086)
    Device: Mesa DRI Mobile Intel® GM45 Express Chipset  (0x2a42)
    Version: 19.3.5

- Desktop environment / Window manager name+version:
exwm + commit fb85e96bb9cfbd9b251da11abab199c653ecbee9

- How you installed Nyxt (Guix pack, package manager, build from source):
nix build from source using this script to get all the dependencies https://pastebin.com/ybNyezTm

- Information from command copy-system-information: 

  If you can't run copy-system-information, please provide the following:
  - Nyxt version (from =M-x nyxt-version= or =nyxt --version=): 
Nyxt version 1.5.0-119e5c58

  - Lisp implementation/version (if built from source):
 `SBCL 2.0.0.nixos`

  - Kernel name+version:
linux+5.4.53

  - WebKitGTK+ | QtWebEngine version:
WebKitGTK 2.26.4

**Output when started from a shell**

```
[nix-shell:~/delete4/nyxt]$ ./nyxt --no-init
Nyxt version 1.5.0-119e5c58
<INFO> [20:37:41] Using data profile "default".
<INFO> [20:37:41] Listening to socket "/home/admin/.local/share/nyxt/nyxt.socket".
WARNING:
   Changing meta-class of BROWSER from SB-KERNEL:UNKNOWN-TYPE to SB-KERNEL:STANDARD-CLASSOID.
<INFO> [20:37:59] Loading global history of 220 URLs from "/home/admin/.local/share/nyxt/history.lisp".
Unhandled SIMPLE-ERROR in thread #<SB-THREAD:THREAD "Anonymous thread" RUNNING
                                    {100737E473}>:
  Couldn't execute "": No such file or directory

Backtrace for: #<SB-THREAD:THREAD "Anonymous thread" RUNNING {100737E473}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<SIMPLE-ERROR "Couldn't execute ~S: ~A" {1007381083}> #<unused argument> :QUIT T)
1: (SB-DEBUG::RUN-HOOK SB-EXT:*INVOKE-DEBUGGER-HOOK* #<SIMPLE-ERROR "Couldn't execute ~S: ~A" {1007381083}>)
2: (INVOKE-DEBUGGER #<SIMPLE-ERROR "Couldn't execute ~S: ~A" {1007381083}>)
3: (ERROR "Couldn't execute ~S: ~A" "" "No such file or directory")
4: (SB-EXT:RUN-PROGRAM "" NIL :ENV NIL :ENVIRONMENT NIL :WAIT NIL :SEARCH T :PTY NIL :INPUT NIL :IF-INPUT-DOES-NOT-EXIST :ERROR :OUTPUT #<SB-IMPL::CHARACTER-STRING-OSTREAM {1007380263}> :IF-OUTPUT-EXISTS :APPEND :ERROR NIL :IF-ERROR-EXISTS :APPEND :STATUS-HOOK NIL :EXTERNAL-FORMAT :UTF-8 :DIRECTORY NIL)
5: (UIOP/LAUNCH-PROGRAM:LAUNCH-PROGRAM ("") :INPUT NIL :OUTPUT #<SB-IMPL::CHARACTER-STRING-OSTREAM {1007380263}> :ERROR-OUTPUT NIL :OUTPUT #<SB-IMPL::CHARACTER-STRING-OSTREAM {1007380263}>)
6: ((LAMBDA (UIOP/RUN-PROGRAM::REDUCED-INPUT UIOP/RUN-PROGRAM::INPUT-ACTIVITY) :IN UIOP/RUN-PROGRAM::%USE-LAUNCH-PROGRAM) NIL NIL)
7: (UIOP/RUN-PROGRAM::%USE-LAUNCH-PROGRAM ("") :OUTPUT #<SB-IMPL::CHARACTER-STRING-OSTREAM {1007380263}>)
8: (TRIVIAL-CLIPBOARD:TEXT NIL)
9: ((LAMBDA NIL :IN NYXT/MINIBUFFER-MODE:MINIBUFFER-PASTE))
10: ((LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS))
11: ((FLET SB-UNIX::BODY :IN SB-THREAD::NEW-LISP-THREAD-TRAMPOLINE))
12: ((FLET "WITHOUT-INTERRUPTS-BODY-4" :IN SB-THREAD::NEW-LISP-THREAD-TRAMPOLINE))
13: ((FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::NEW-LISP-THREAD-TRAMPOLINE))
14: ((FLET "WITHOUT-INTERRUPTS-BODY-1" :IN SB-THREAD::CALL-WITH-MUTEX))
15: (SB-THREAD::CALL-WITH-MUTEX #<CLOSURE (FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::NEW-LISP-THREAD-TRAMPOLINE) {7F878FDAED8B}> #<SB-THREAD:MUTEX "thread result lock" owner: #<SB-THREAD:THREAD "Anonymous thread" RUNNING {100737E473}>> NIL T NIL)
16: (SB-THREAD::NEW-LISP-THREAD-TRAMPOLINE #<SB-THREAD:THREAD "Anonymous thread" RUNNING {100737E473}> NIL #<CLOSURE (LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS) {100737E41B}> NIL)
17: ("foreign function: call_into_lisp")
18: ("foreign function: new_thread_trampoline")

unhandled condition in --disable-debugger mode, quitting
```

**Comment by Ambrevar** [comment]
You need xsel or xclip, it's a hard dependency for Nyxt.
That said, we should not crash here.  I'll see if we can handle that
more cleanly.

**Comment by walseb** [comment]
Oh I see thanks! I didn't read the developer manual fully

**Comment by walseb** [comment]
So I have `xclip` now and pasting works fine if I have already copied something but if I do these steps nyxt still crashes:
1. Start nyxt, open `duckduckgo.com`
2. Click the search field and then press `shift-insert` a bunch of times
Now nyxt freezes for me and no stacktrace is printed because nyxt is still running but the UI is frozen

**Comment by Ambrevar** [comment]
Oops, indeed, this is the same bug as with C-v.  I've included a
workaround in 239c368f7e61aba96271297b384b032f22e116d5.

This is a weird FFI issue, so far we've only got this workaround, sadly.

You are the first person I encounter who uses the shift-insert shortcut :p

**Comment by walseb** [comment]
Thanks!
