### ISSUE TITLE
Can't play videos on nixos

### ISSUE THREAD

**Issue by walseb** [atlas-engineer/nyxt#872]
Hi! I have followed all steps mentioned in #761 but I just can't get videos working. I believe the problem is that nix doesn't set any environment variables when you install the gstreamer packages. I have tried to fix this by setting them myself but haven't gotten it to work yet. Has anyone gotten videos to work on nixos?

**Comment by jmercouris** [comment]
Hello again :-)

I don't know of anyone who has gotten videos to work on Nixos. I believe Guix should have some of the same challenges. Hopefully someone chime in with some ideas!

**Comment by Ambrevar** [comment]
Install all the Gst plugins, then try setting the following environment variables:

```
GST_PLUGIN_SYSTEM_PATH=/home/ambrevar/.nix-profile/lib/gstreamer-1.0
GST_PLUGIN_PATH=/home/ambrevar/.nix-profile/lib/gstreamer-1.0
```

**Comment by walseb** [comment]
So I did that, deleted gstreamer-1.0 in .cache and it still doesn't work. But when I changed the variable slightly to include gstreamer-0.1 like this:

**Comment by walseb** [comment]
In case edits doesn't show on email notifications, I accidentally posted the last comment before I was finished. It's corrected now

**Comment by Ambrevar** [comment]
I wonder why Nix ships Gstreamer 0.10, isn't terribly outdated?

Can you reproduce with Epiphany?  If it works with Epiphany, maybe look up the Nix package definition for the required environment variables.

**Comment by walseb** [comment]
Thanks! I got it working now! Turns out you have to use `gst_all_1` and put it in `nativeBuildInputs` instead of just `buildInputs`. This is what I had to add in my shell.nix:
```
  nativeBuildInputs = [
    pkgs.openssl.out
    pkgs.webkitgtk
    pkgs.sbcl
  ] ++ (with pkgs.lispPackages; [
    prove-asdf
    trivial-features
  ])
  ++ (with gst_all_1; [
    gst-plugins-base gst-plugins-good
    gst-plugins-bad gst-plugins-ugly gst-libav
  ]);
```

**Comment by Ambrevar** [comment]
Would you like to contribute an updated Nyxt package to nixpkgs?  This
could be very helpful to all Nix users.

**Comment by walseb** [comment]
Done! https://github.com/NixOS/nixpkgs/pull/94083

**Comment by Ambrevar** [comment]
Thanks!  I had a quick glance at the recipe and a couple of things would
need an update:

- The new name is "nyxt".
- The "gtk-webkit" make flag is no longer necessary.
- The install target should be "install".  Since this is the default,
  you can probably leave it out.
- The homepage needs to be updated as well.
- You can leave out the parenthesis in the description.

**Comment by walseb** [comment]
Yeah I agree, I will make those changes along with 2.0 (or just the next version if it's not 2.0, however #753 has to be solved first), or maybe someone else will beat me to it
