### ISSUE TITLE
Poor performance during video playback

### ISSUE THREAD

**Issue by walseb** [atlas-engineer/nyxt#877]
I'm not sure how to get any objective measurements on this, but simply go on youtube and start a video. If your PC is really powerful then maybe start a few in different tabs. Then try scrolling around on that page. On all the machines I have tried this on:
- Thinkpad x200 with core 2 duo
- a pretty modern ideapad with a mid-range ryzen cpu

the browsing becomes incredebly slow. When I tried this again using firefox, chrome and qutebrowser (which uses the same gstreamer packages as nyxt) I get no problems with performance.

Is there a way to profile nyxt in case this is a problem with nixos (which is the constant between those two PCs)

**Comment by jmercouris** [comment]
There is one more variable to potentially isolate. Please try to see if it is a problem with the WebKitGTK+ implementation by trying playback in Epiphany.

**Comment by walseb** [comment]
I'm using nixos and epiphany seems broken currently, both on unstable and stable. I have tried on two laptops now and only get a blank screen no matter which site I visit. Are there any other browsers I can try?

**Comment by jmercouris** [comment]
There may be a binary titled "minibrowser" (or some variant thereof) that ships with WebkitGTK+.

Another thought that I just had is that slow video playback may be a function of lack of graphical acceleration. Perhaps it is a compile time configuration and/or run-time configuration option.

**Comment by walseb** [comment]
I can't find minibrowser in the nix repos. Does guix build with hardware acceleration? I can't find anything mentioning it in the developer manual

**Comment by jmercouris** [comment]
I would not know, Pierre will be AFK until at least Saturday, hopefully he has some ideas to chime in. Minibrowser is not going to be a separate package in the Nix repositories. It should be compiled WITH WebKitGTK+, see if you can find it on disk.

**Comment by jmercouris** [comment]
In the meantime, @jellelicht may know something about hardware acceleration.

**Comment by Ambrevar** [comment]
A few WebKitGTK+ browsers you can try beside Epiphany / GNOME Web:

- Eolie
- Luakit
- midori
- netsurf
- vimb

**Comment by walseb** [comment]
So I tried all those browsers and these were my results:
- eolie - although it supports h264, nothing on youtube will play properly. It takes a long while to load and when it finally does it shows "An error has occurred".
- luakit - I only get a blank screen in this browser, just like in epiphany
- midori - Doesn't build with any video support
- netsurf - Seems like this nix recipe is broken, I get `error: cannot coerce a set to a string` when I try install it
- vimb - Doesn't build with any video support

**Comment by walseb** [comment]
To clarify, this issue only really happens when you use the video controls or click around in general. If I just start 1 video and don't do anything else on that page it's pretty smooth

**Comment by Ambrevar** [comment]
Yes, this is expected with WebKitGTK (for now).  As new versions get
released, video support gets improved.  Youtube is particularly bad for
WebKitGTK, you might have a smoother experience with other players.

A good workaround is to add bindings to play the videos leveraging
youtube-dl and your favourite video player.

**Comment by Ambrevar** [comment]
@walseb I think there is little we can do beside work on the QtWebengine support or contribute to WebKitGTK.
Shall we close this issue then?

**Comment by walseb** [comment]
Yeah that's true, thanks for identifying the issue by the way!
