### ISSUE TITLE
set-url uses search engines for ip addresses

### ISSUE THREAD

**Issue by walseb** [atlas-engineer/nyxt#878]
**Describe the bug**
When you use `set-url` it tries to predict wheter you want to search the string in a search engine or if you are trying to open an addresses directly. This isn't perfect and some addresses that should be interpreted as direct addresses are instead interpreted as search queries.

**Precise recipe to reproduce the issue**
Run `set-url` and type in `192.168.0.1` (the address your router usually gets assigned). Nyxt will then try to open that address in duckduckgo

**Information**
I think only this is relevant to the issue:
- Nyxt version (from =M-x nyxt-version= or =nyxt --version=): 1.5.0-65b47f87
But if the rest of the field are necessary then please tell me

**Comment by jmercouris** [comment]
I usually prefix http://192.178... and it works for me, is that OK?

How do you think the behavior should be?

**Comment by walseb** [comment]
Yeah that works but it's a bit more verbose. I think it should only consider it an address if it doesn't contain spaces and contains a dot or more. That way you can just insert a space at the end if you want it to search the address. I wrote one of these url parsers before to get the same kind of thing in emacs `eww`, maybe the code describes what I mean better:
```emacs-lisp
(defun my/get-search-url (&optional str)
  (interactive)
  (let ((search (or str (completing-read "search: " nil))))
    (if (or
	 ;; All strings with spaces are searches
	 (string-match-p (rx whitespace) search)

	 (not
	  (or
	   ;; All strings without spaces and with dots aren't searches
	   ;; The not whitespace here combined with the * and oel makes sure cases like "foo.bar." aren't interpreted as direct addresses
	   (string-match-p (rx (char ".") (* graph) eol) search)

	   ;; All strings without spaces and with http aren't searches
	   (string-match-p (rx bol "http" (* graph) eol) search)
	   )))

	(concat "https://www.google.com/search?q=" search)
      search)))

;; (my/get-search-url "192.168.0.1") => 192.168.0.1
;; (my/get-search-url "google.com") => google.com
;; (my/get-search-url "google.com ") => https://www.google.com/search?q=google.com
```

Although maybe there are edge cases with using this method

**Comment by Ambrevar** [comment]
> I think it should only consider it an address if it doesn't contain
> spaces and contains a dot or more.

This would not always do what the user wants.  For instance, typing
"foo.bar" we should look it up with a search engine since it's not a
valid URL.

In commit 94ed32876ef63505f861a176fdc51bef54a4139b I've pushed a fix
which adds support for IP addresses instead of domains.

If you don't specify the scheme (e.g. "http://") it will fall back to
HTTPS, which may not work if the host does not have a valid certificate
(usually the case for local addresses).

Maybe we could implement some sort of whitelists, but I'm not sure it's
worth it.  It's easy enough to type http:// or to bookmark the address.

**Comment by walseb** [comment]
> This would not always do what the user wants.  For instance, typing
"foo.bar" we should look it up with a search engine since it's not a
valid URL.

I would usually just insert a space at the end in these cases to make it a search but I understand that this might not be the best solution for a real browser and might be confusing. Thanks for the fix!

**Comment by Ambrevar** [comment]
You're welcome :)
