### ISSUE TITLE
exwm-edit causes nyxt to freeze

### ISSUE THREAD

**Issue by walseb** [atlas-engineer/nyxt#879]
**Describe the bug**
When using exwm-edit nyxt freezes. I believe this is because it pastes what it copies from the emacs buffer too quickly. Or could it have something to do with xclip? It hasn't crashed any other xorg program I have tried

**Precise recipe to reproduce the issue**
1. Start nyxt using `nyxt --no-init`
2. Open duckduckgo.com
3. Select the search bar and type something in there
4. Run `M-x exwm-edit--compose`
5. Edit the text a bit then hit `C-c C-c`
nyxt should now freeze

**Information**
OS name+version:
nixos+20.03

Graphics card and driver:
product: AMD Ryzen 3 2200U with Radeon Vega Mobile Gfx
vendor: Advanced Micro Devices [AMD]
driver=amdgpu

Desktop environment / Window manager name+version:
exwm + commit fb85e96bb9cfbd9b251da11abab199c653ecbee9

How you installed Nyxt (Guix pack, package manager, build from source):
nix build from source

Information from command copy-system-information:

If you can't run copy-system-information, please provide the following:

Nyxt version (from =M-x nyxt-version= or =nyxt --version=):
Nyxt version 1.5.0-65b47f87

Lisp implementation/version (if built from source):
SBCL 2.0.0.nixos

Kernel name+version:
Linux nixos 5.7.10 #1-NixOS SMP Wed Jul 22 07:34:29 UTC 2020 x86_64 GNU/Linux

WebKitGTK+ | QtWebEngine version:
WebKitGTK 2.26.4

**Output when started from a shell**
It just freezes so no output

**Comment by Ambrevar** [comment]
This is a known issue, it is because exwm-edit calls the X server pasting feature
which causes cl-webkit to hang.  For now there is no way around it.

That said, you don't have to use exwm-edit since Nyxt has a
fill-input-from-external-editor command.  The command is not completely
finished, see https://github.com/atlas-engineer/nyxt/issues/788.

**Comment by walseb** [comment]
Thanks! Should I keep this issue up? I can't find any other issue about exwm-edit

**Comment by Ambrevar** [comment]
See #593 for a more extensive discussion.

This probably won't be fixed using the current FFI, but it could potentially get fixed with WebEngine or using GObject Introspection.  For now, it's safe to close it I think.

I'll tag this issue for posterity.
