### ISSUE TITLE
Include license headers and license assets

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#895]
Self-explanatory :)

**Comment by Ambrevar** [comment]
License headers are now included.  What shall we do about the assets?

**Comment by jmercouris** [comment]
What is the most conservative license we can use that still complies with distribution?

**Comment by Ambrevar** [comment]
In my understanding, it's CC BY-SA:

https://creativecommons.org/licenses/

**Comment by jmercouris** [comment]
OK, based on your understanding, I will set that up.

**Comment by Ambrevar** [comment]
I think this can be closed since https://github.com/atlas-engineer/nyxt/commit/e7263c347704e7ec6e5992a0e61ec243560095e0#diff-92c649b51935ae1d03bacd14b6ca9125.  Feel free to reopen if you think there is more to be done.
