### ISSUE TITLE
 Symbol "LAUNCH-PROGRAM" not found in the UIOP/DRIVER package.

### ISSUE THREAD

**Issue by C-Entropy** [atlas-engineer/nyxt#899]
Hi there, during `(asdf:make :nyxt/gtk-application)` sbcl caught ERROR looks like that:

> ; compiling (EXPORT-ALWAYS (QUOTE URL-DISPATCHING-HANDLER))
> ; compiling (DECLAIM (FTYPE # ...))
> ; 
> ; caught ERROR:
> ;   READ error during COMPILE-FILE:
> ;   
> ;     Symbol "LAUNCH-PROGRAM" not found in the UIOP/DRIVER package.
> ;   
> ;       Line: 639, Column: -1, File-Position: 32094
> ;   
> ;       Stream: #<SB-INT:FORM-TRACKING-STREAM for "file /home/null/quicklisp/local-projects/nyxt/source/browser.lisp" {10077F8003}>
> 
In repl in slime I tried something like `(uiop:launch-program "ls")`
and the output is
> Symbol "LAUNCH-PROGRAM" not found in the UIOP/DRIVER package.

 I have also tried `find ./quicklisp|uiop`,and the output contains:
> ./quicklisp/software/uiop-3.3.4/launch-program.lisp
> ./quicklisp/software/uiop-3.3.4/uiop.asd
> ./quicklisp/software/uiop-3.3.4/asdf-driver.asd
then in repl in slime I typed 
`(asdf:load-asd "/home/null/quicklisp/dists/quicklisp/software/uiop-3.3.4/asdf-driver.asd")`
`(asdf:load-asd "/home/null/quicklisp/dists/quicklisp/software/uiop-3.3.4/uiop.asd")`
`(load "/home/null/quicklisp/dists/quicklisp/software/uiop-3.3.4/launch-program.lisp")`
but the Error still
I have tired reinstall quicklisp, following guide from office website.
My sbcl is from Gentoo package, and version is 1.4.9
Any idea?
Btw, things like `uiop:run-program` can work

**Comment by jmercouris** [comment]
That is a very old version of SBCL, please upgrade and everything should hopefully work :-)

**Comment by C-Entropy** [comment]
Yes, you are right, thanks. Btw is there any way to port my datas(bookmarks, logins)from firefox to nyxt?

**Comment by jmercouris** [comment]
Not currently, but if you write an importer, we would be happy to accept a pull request :-)

**Comment by C-Entropy** [comment]
Alright, I will try if I have time, and, is there anything like melpa, or say, how do you distribute add-ons?

**Comment by jmercouris** [comment]
Not yet, it is one of our upcoming tasks, we'll be setting up a quicklisp distribution for systems that work with Nyxt.

**Comment by C-Entropy** [comment]
Hi,there I have found that we can import bookmarks from html, and the login manger is yet to come. I'm now trying achieving the first one.I have found some issuses talks about it. like #344 , is there more details? And is there any documention on source code of bookmark, or have I digged into source code myself?

**Comment by jmercouris** [comment]
Thank you for looking into this! I'll try my best to help.

What is a "login manager"? there is already support for password management/authentication on different websites- if that is what you mean.

As per bookmarks, you can take a look at how Pierre imports them from EWW https://gitlab.com/ambrevar/dotfiles/-/blob/master/.config/nyxt/init.lisp#L130

You will probably just want to iterate over the Firefox bookmarks, and  in Nyxt and do `nyxt:bookmark-entry`. Beyond that, there is no documentation of how it works, just how to use it as a user. You'll have to look at the source. However, you need not understand it. You only need to invoke `Nyxt:bookmark-entry` on all of the bookmarks as I've described.

**Comment by C-Entropy** [comment]
Hi, I think that I'm close to the right answer now. But it stuck me that I don't know how to import Nyxt:bookmark-entry. Or say, I don't know how exactly to play with those things. I know that I could put stuffs into .init.el, but I don't know how to debug it. Any document?

**Comment by jmercouris** [comment]
You can play with the REPL :-). Please see the developer instructions on how to do so. The short answer is M-x start-swank in Nyxt and M-x slime-connect in Emacs

**Comment by C-Entropy** [comment]
Hi there. I have reached this:
> ;;only test with Firefox Developer Edition version 80.0b8 (64-bit)
> ;;you have to export bookmarks of firefox as html first.
> ;;for me, use Crtl+Shift+O to open bookmark page, in Import and Backup Select export Bookmarks to html.
> (ql:quickload :lquery)
> (defun import-bookmarks-from-html (html-file)
>   (with-open-file (in-html html-file
> 			   :external-format :utf-8)
>     (let ((bookmark-entrys))
>       (lquery:$ (initialize in-html)
> 	"a"
> 	(combine (attr :href) (text) (attr :ADD_DATE) (attr :TAGS))
> 	(map-apply #'(lambda (url title date tags)
> 		       (when (and (> (length url)) 4
> 				  (equal (subseq url 0 4) "http"))			 
> 			 (push (make-instance 'nyxt:bookmark-entry
> 					      :url url
> 					      :title title
> 					      :date (local-time:unix-to-timestamp (parse-integer date))
> 					      :tags (list tags))
> 			       bookmark-entrys)))))
>       (setf (slot-value *browser* 'nyxt::bookmarks-data) bookmark-entrys))))
But here I met some promble. First the bookmarks I already added will be lose. Second the bookmarks can't be persist. When I reopen nyxt, I will get what I have before call this function. Could you please fix it? Or point me a way.
Thanks for being patient with my stupid questions.

**Comment by C-Entropy** [comment]
emm now there is new questions.
First. For `(setf (bookmark-entries *browser*) ...)`

> The function (COMMON-LISP:SETF NYXT-USER::BOOKMARK-ENTRIES) is
undefined.

Second. I put this to .config/nyxt/init.lisp:
```
(in-package :nyxt-user)
(setf (bookmarks-data *browser*)
      (list (make-instance 'nyxt:bookmark-entry)))
```
then when I run nyxt
it show:

> Error occured:
> Could not load the init file: There is no applicable method for the generic function #<STANDARD-GENERIC-FUNCTION (COMMON-LISP:SETF NYXT:BOOKMARKS-DATA) (1)> when called with arguments (#<BOOKMARK-ENTRY {1006E831E3}> NIL). See also: The ANSI Standard, Section 7.6.6

but if I run it in slime, it do create a .local/share/nyxt/bookmarks.lisp(I have removed it before.)
And then it crashed.

> <INFO> [21:30:13] Saved 1 bookmarks to "/home/null/.local/share/nyxt/bookmarks.lisp".
> fatal error encountered in SBCL pid 21624(tid 0x7fadba0b7700):
> SIGABRT received.
> 
>    0: Foreign function gsignal, pc = 0x7fae7c6cd881, fp = 0x7fae709fca00
>

**Comment by Ambrevar** [comment]
C-Entropy <notifications@github.com> writes:

> emm now there is new questions.
> First. For `(setf (bookmark-entries *browser*) ...)`

Sorry about that, it's bookmark-data indeed :p

>> The function (COMMON-LISP:SETF NYXT-USER::BOOKMARK-ENTRIES) is
> undefined.
>
> Second. I put this to .config/nyxt/init.lisp:
> ```
> (in-package :nyxt-user)
> (setf (bookmarks-data *browser*)
>       (list (make-instance 'nyxt:bookmark-entry)))
> ```

Your bookmark-entry must have a URL.

```
(make-instance 'bookmark-entry :url YOUR-URL-HERE)
```

Does that help?
I'll make the code more robust on master.

**Comment by Ambrevar** [comment]
Sorry, that was not the problem.

The issue is that *browser* is nil when the init file is run.
Indeed, saving a bookmark on init makes little sense.  You should do it
from a REPL.  If you really want to add the bookmarks in your init file,
you should do it in a handler that's added to the *after-init-hook*.

When running from a REPL, you need to execute this code from the
renderer thread, otherwise it will hang the REPL thread.

```
(within-renderer-thread
  (setf (bookmarks-data *browser*)
        (list (make-instance 'nyxt:bookmark-entry))))
```

Does that help?

**Comment by Ambrevar** [comment]
I've fixed the renderer-thread limitation on master for many functions.
See 44090949e56a6c832eccae1f9845f1136b849da3.

Now your code should work from the REPL.

**Comment by C-Entropy** [comment]
Yeah now you can import your bookmarks from a html generated by firefox like this:

```
(in-package :nyxt-user)
(ql:quickload :lquery)
(defun import-bookmarks-from-html (html-file)
  (with-open-file (in-html html-file
			   :external-format :utf-8)
    (let ((bookmark-entries))
      (lquery:$ (initialize in-html)
	"a"
	(combine (attr :href) (text) (attr :ADD_DATE) (attr :TAGS))
	(map-apply #'(lambda (url title date tags)
		       (when (and (> (length url) 4) 
		       		  (equal (subseq url 0 4) "http"))
		       	 (push (make-instance 'nyxt:bookmark-entry
		       			      :url (quri:uri url)
		       			      :title title
		       			      :date (local-time:unix-to-timestamp (parse-integer date))
		       			      :tags (if (equal "NIL" tags)
					      		NIL)
					      )
		       	       bookmark-entries)))))
      (setf (bookmarks-data *browser*) bookmark-entries))))

(import-bookmarks-from-html "html-file");;run it manully from REPL

but it will supersede the bookmarks added before this action.

```

And I find a new bug(should be). I will search  first to see if it has been submit first.

**Comment by Ambrevar** [comment]
Nice!
If you don't want to supersede the existing bookmarks, you should first
populate your bookmark-entries variable with something like this:

```
(remove-if (lambda (b)
             (when (equal-url (url b) url)
               (setf entry b)))
           (bookmarks-data *browser*))
```

Would you like to send a pull request so that we integrate this upstream?

**Comment by Ambrevar** [comment]
See the bookmark-add function in bookmark.lisp.
