### ISSUE TITLE
Replace uses of non-free fonts (Helvetica)

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#901]
The status buffer style refers to Helvetica, but it's a non-free font.  Instead I suggest we use one of the common substitute fonts like Liberation.

See
https://en.wikipedia.org/wiki/Helvetica#Free_Helvetica_substitute_fonts.

@jmercouris

**Comment by jmercouris** [comment]
The browser will look for a suitble 'Helvetica like' font on the system. We are not actually shipping Helvetica with the browser. If the user has one of those substitute fonts available, it will select from those.

**Comment by Ambrevar** [comment]
Understood, but I'm unsure where we stand when it comes to references of non-free
content.  Free software guidelines discourage such references.

In doubt, I'd rather avoid them, after all it costs nothing to change
and only refer to free content.

**Comment by jmercouris** [comment]
It does cost something to change. Helvetica is a most beautiful font- the alternatives are not nearly as nicely designed.

**Comment by jmercouris** [comment]
@Ambrevar OK to close this?

**Comment by jmercouris** [comment]
A good point. Perhaps we should ship a font strictly for usage via the UI of Nyxt?

**Comment by Ambrevar** [comment]
Perhaps indeed.  I believe some programs do this, Chromium and Firefox
may very well do this too.

**Comment by andreystepanov** [comment]
Is there's any way to redefine default font used by Nyxt?

I would like to use Fira Code or JetBrains Mono globally (buffers/prompts etc.), but have no idea if it's even possible right now.

**Comment by aartaka** [comment]
> Is there's any way to redefine default font used by Nyxt?
> 
> I would like to use Fira Code or JetBrains Mono globally (buffers/prompts etc.), but have no idea if it's even possible right now.

@andreystepanov I have this in my config:
``` lisp
(defmethod ffi-buffer-make :after ((buffer nyxt::gtk-buffer))
  (let* ((settings (webkit:webkit-web-view-get-settings (nyxt::gtk-object buffer))))
    (setf
     ;; Use Cantarell-18 as the default font and Hack as monospace one.
     (webkit:webkit-settings-default-font-family settings) "Cantarell"
     (webkit:webkit-settings-monospace-font-family settings) "Hack"
     (webkit:webkit-settings-default-font-size settings) 18)))
```

The other settings related to fonts are (in no particular order):
```
webkit:webkit-settings-default-monospace-font-size
webkit:webkit-settings-pictograph-font-family
webkit:webkit-settings-monospace-font-family
webkit:webkit-settings-sans-serif-font-family
webkit:webkit-settings-fantasy-font-family
webkit:webkit-settings-cursive-font-family
webkit:webkit-settings-default-font-family
webkit:webkit-settings-minimum-font-size
webkit:webkit-settings-serif-font-family
webkit:webkit-settings-default-font-size
```

And this mirrors the [WebKitSettings reference](https://webkitgtk.org/reference/webkit2gtk/stable/WebKitSettings.html).

**Comment by aadcg** [comment]
@aartaka this should definitely land on our manual!

**Comment by jmercouris** [comment]
All non free fonts have been replaced.

**Comment by jmercouris** [comment]
For a more recent setting on how to change fonts, you'll want to use your own theme where you set the font family.
