### ISSUE TITLE
Use web-mode for internal buffers

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#902]
Without it, we can't follow hints, search, etc.

**Comment by Ambrevar** [comment]
Also somewhat annoyingly, emacs-mode or vi-normal-mode are not automatically enabled for internal buffers when they are by default in web buffers.
Shall add a workaround to make-internal-buffers to automatically include these 2 modes if present in the default modes of the BUFFER class?

**Comment by jmercouris** [comment]
I have been running into this as well where I press my emacs keybindings in an internal buffer, only to find that they are not present :-D

With regards to web-mode, yes, it should probably be included by default in internal-buffers- or at least some variant of it.

**Comment by Ambrevar** [comment]
This last point should be fixed by #910.  The original post issue is fixed by #931.
