### ISSUE TITLE
Add buttons to modes in status view

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#904]
I suggest we add 2 buttons to the mode list in the status view:

- 1 button that wraps over the full list of modes and that triggers `disable-mode-for-current-buffer`
- 1 button over a new `+` sign that triggers `enable-mode-for-current-buffer`.

Thoughts?

**Comment by jmercouris** [comment]
An interesting idea! My counter points is the following: will a new user be enabling/disabling modes?

I see modes as an advanced feature, and I was even thinking about a way of reducing their size in the default format-status function. I was thinking of abbreviating them somehow.

A question that may help us resolve this is the following: who are the buttons for, what purpose do they serve? As an advanced user, do you find yourself still using the buttons? If so, it may be wise, as you've suggested to add these buttons.

**Comment by Ambrevar** [comment]
A good point.  We can expect most new users to be unfamiliar with modes.
In particular, new users start with "[web base]" and this might not
speak to them much.

However, when they see the list of modes, if they can click on them (and
the "+"), it will become immediately obvious what they can do with it.

So I'm in favour of adding buttons because it's a door to the path of
more customization for newcomers.

**Comment by jmercouris** [comment]
I have concluded that I agree with you, we can add a plus and minus for the modes area.

**Comment by Ambrevar** [comment]
Thanks!  Will do later then, unless someone beats me to it ;)

**Comment by Ambrevar** [comment]
Buttons got added by John in https://github.com/atlas-engineer/nyxt/commit/e131585fd5574cfe5b1e1d7d67c4508d68bbf470.
Ellipsis for mode listing and toggling in https://github.com/atlas-engineer/nyxt/pull/1615.

**Comment by jmercouris** [comment]
The user can now add and remove modes via the "+" symbol in the far right. I almost want to make it a Δ because that would be cool, but I think the "+" is more obvious. Anyways, the criteria here are fulfilled. Closing for now. Please feel free to reopen!
