### ISSUE TITLE
can not input text when run from source 

### ISSUE THREAD

**Issue by C-Entropy** [atlas-engineer/nyxt#905]
**Describe the bug**
can not input text
**Precise recipe to reproduce the issue**
in slime:
`(ql:quickload :nyxt/gtk)`

`(ql:quickload :nyxt/gtk)`
then in nyxt:
use `C+Space` to open Execut command.
then you will find you can't input normal text, like "12345abcdef", while you can do things like C-v/C-y to paste, or move the cursor. At least, it happend to me.

**Information**
- OS name+version:
Gentoo
- Desktop environment / Window manager name+version:
i3-gpas
  If you can't run copy-system-information, please provide the following:
  - Nyxt version (from =M-x nyxt-version= or =nyxt --version=):
just clone
  - Lisp implementation/version (if built from source):
sbcl 2.0.7 built from source

**Comment by Ambrevar** [comment]
What is the cause of the issue?  That you quickloaded nyxt/gtk twice?

I don't use Quicklisp so I tried this:

```
,load-system nyxt/gtk
,load-system nyxt/gtk
```

and everything worked as normal.

Are you using some input system (e.g. CJK)?

Is this

https://github.com/atlas-engineer/nyxt/issues/866

or

https://github.com/atlas-engineer/nyxt/issues/324

?

**Comment by C-Entropy** [comment]
Nope, nothing about input system like fcitx. Just the nornal one you use to input English.
I am  not quiet sure about the reason. I do not load it twice.
I just power on my laptop, open emacs, clone nyxt from git, and then M-x slime

> ; SLIME 2.26
> CL-USER> (ql:quickload :nyxt/gtk)
> To load "nyxt/gtk":
>   Load 1 ASDF system:
>     nyxt/gtk
> ; Loading "nyxt/gtk"
> .....................
> Switching to the BALLAND2006 optimizer
> .............................
> [package cluffer].................................
> [package cluffer-internal]........................
> [package cluffer-base]............................
> [package cluffer-standard-line]...................
> [package cluffer-standard-buffer].................
> [package cluffer-simple-line].....................
> [package cluffer-simple-buffer]...................
> [package text-buffer].............................
> [package text-analysis]...........................
> [package download-manager]........................
> [package hooks]...................................
> [package keymap]..................................
> [package scheme]..................................
> ..................................................
> ..................................................
> ..................................................
> [package cl-webkit2]..............................
> [package jscore]...............................
> (:NYXT/GTK)
> CL-USER> (nyxt:start)
> Nyxt version 1.5.0
> <INFO> [19:41:53] Loading Lisp file "/home/null/.config/nyxt/init.lisp".
> <INFO> [19:41:54] Using data profile "default".
> <INFO> [19:41:54] Nyxt already started.
> NIL
> <INFO> [19:41:56] Restoring session "/home/null/.local/share/nyxt/sessions/default.lisp".
> <INFO> [19:41:56] Restoring (https://www.bigfun.cn/tools/aktools-old/akhr.html
>                              https://acg.rip/ https://www.baidu.com/
>                              https://www.baidu.com/ https://www.baidu.com/
>                              https://www.baidu.com/
>                              https://www.baidu.com/s?ie=utf-8&f=3&rsv_bp=1&rsv_idx=1&tn=baidu&wd=asd%E6%98%AF%E4%BB%80%E4%B9%88%E6%84%8F%E6%80%9D&fenlei=256&rsv_pq=e7b8ae910007d789&rsv_t=d2086WcMxSbTOiiIJoTwnhYb3x4gGj4xRCXUBamDCqXB2eJuduSV3n7HBmU&rqlang=cn&rsv_enter=1&rsv_dl=ts_0&rsv_sug3=4&rsv_sug1=1&rsv_sug7=100&rsv_sug2=0&rsv_btype=i&prefixsug=asd&rsp=0&inputT=1346&rsv_sug4=6389
>                              https://www.baidu.com/ https://www.baidu.com/
>                              https://www.baidu.com/
>                              https://github.com/atlas-engineer/nyxt/issues
>                              https://www.baidu.com/
>                              https://www.baidu.com/s?ie=utf-8&f=3&rsv_bp=1&rsv_idx=1&tn=baidu&wd=asd%E6%98%AF%E4%BB%80%E4%B9%88%E6%84%8F%E6%80%9D&fenlei=256&rsv_pq=e7b8ae910007d789&rsv_t=d2086WcMxSbTOiiIJoTwnhYb3x4gGj4xRCXUBamDCqXB2eJuduSV3n7HBmU&rqlang=cn&rsv_enter=1&rsv_dl=ts_0&rsv_sug3=4&rsv_sug1=1&rsv_sug7=100&rsv_sug2=0&rsv_btype=i&prefixsug=asd&rsp=0&inputT=1346&rsv_sug4=6389
>                              https://fanyi.baidu.com/?aldtype=85#en/zh/ASD
>                              https://www.baidu.com/ https://www.baidu.com/
>                              https://www.baidu.com/s?cl=3&tn=baidutop10&fr=top1000&wd=TikTok%E6%AD%A3%E5%BC%8F%E8%B5%B7%E8%AF%89%E7%89%B9%E6%9C%97%E6%99%AE%E6%94%BF%E5%BA%9C&rsv_idx=2&rsv_dl=fyb_n_homepage&hisfilter=1
>                              https://www.baidu.com/).
> CL-USER> 

then in nyxt:
use C+Space to open Execut command.
then you will find you can't input normal text, like "12345abcdef", while you can do things like C-v/C-y to paste, or move the cursor. At least, it happend to me.

and there is now message print in REPL
as for `,load-system nyxt/gtk` I don't know how to do this yet. I will try after I google it.
However, if run SBCL directly from terminal(I'm using st), there is no such a problem.

**Comment by jmercouris** [comment]
Very possibly a threading issue triggered via the usage of Slime. On macOS, one has to start SBCL in a separate terminal, start swank, connect to it, and then start Nyxt.

**Comment by C-Entropy** [comment]
Alright, I run a "clean" emacs, and now everything is right. I think that is not the thing you refer to. I may  finger it out later.

**Comment by jmercouris** [comment]
I'm afraid I don't know anything about this, sorry!

**Comment by Ambrevar** [comment]
@C-Entropy Feel free to reopen if you think we can help more :)
