### ISSUE TITLE
Get error when using bookmark-url

### ISSUE THREAD

**Issue by C-Entropy** [atlas-engineer/nyxt#906]
Describe the bug
Get error when using bookmark-url
Precise recipe to reproduce the issue
 in nyxt:
use C+m u to open a mini buffer and input something like "https://github.com"
then you may see this:

> <INFO> [08:00:28] Pressed keys: C-m
> <ERROR> [08:00:28] In BOOKMARK-URL: -1 fell through ETYPECASE expression.
>                                     Wanted one of (SIMPLE-STRING
>                                                    QURI.PARSER::SIMPLE-BYTE-VECTOR
>                                                    STRING).
> <ERROR> [08:00:46] In #<FUNCTION (LAMBDA (URL) :IN BOOKMARK-URL) {526FE65B}>: The
>                                                                               value
> 
>                                                                                 "https://github.com"
> 
>                                                                               is
>                                                                               not
>                                                                               of
>                                                                               type
> 
>                                                                                 QURI.URI:URI
> 
>                                                                               when binding URL
> 

Information

OS name+version:
Gentoo
Desktop environment / Window manager name+version:
i3-gpas
If you can't run copy-system-information, please provide the following:
Nyxt version (from =M-x nyxt-version= or =nyxt --version=):
just clone
Lisp implementation/version (if built from source):
sbcl 2.0.7 built from source

**Comment by Ambrevar** [comment]
Good catch!

Fixed with a969b608baed18cb92c0b1c038f7bb28ed713319.

@jmercouris: Another instance of a with-result/async pitfall: quri:uri
was applied on the return value of read-from-minibuffer, which was a
number, not the URL.

**Comment by jmercouris** [comment]
Ah, indeed! :-)

**Comment by Ambrevar** [comment]
It would really help if we could make read-from-minibuffer synchronous.

**Comment by jmercouris** [comment]
It sure would, but it would also cause many problems by being a blocking I/O operation. If there is a way to do it, I don't know it yet!

**Comment by Ambrevar** [comment]
What about the following:

- start every command in a new (green) thread.
- read-from-minibuffer runs in its own thread and returns a _channel_.
  We need to read the channel (a blocking operation) to get the result.

Then `with-result` would simply be a channel collecting macro.  Actually
ChanL or lparallel might already have something for it.

The benefit is that we never get meaningless return value, we can use
read-from-minibuffer directly and wrap it around other functions.

Also we don't need the %callback business anymore.

Thoughts?  Shall I open a new issue about it?

**Comment by jmercouris** [comment]
I don't know how I feel about introducing threads for this operation. My gut instinct is that it is an unnecessary resource and make things overtly complicated. We already have to deal with callbacks with javascript, so I think it best to stick to one model of 'synchronous' execution. I am not completely against the idea. Please do open an issue though so that we can further discuss it.
