### ISSUE TITLE
Synchronous minibuffer

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#908]
As mentioned in #906 and a couple of times before, the current asynchronousness of our minibuffer is problematic:

- it's counter-intuitive;
- it's a source of programming errors (e.g. when trying to apply a procedure to the return value of `read-from-minibuffer`);
- it makes use of the dynamically bound `%callback` variable which is referentially non-transparent, which can lead to subtle bugs;
- chaining minibuffer calls is impractical with just callbacks, which forces us to use a macro like `with-result*`.

On top of that, the `(with-result (foo (read-from-minibuffer (make-minibuffer ...))))` idiom is cumbersome.

Ideally, we would just have

```lisp
(let* ((result1 (read-from-minibuffer ...))
       (result2 (read-from-minibuffer ... <whatever which uses result1>))
  body)
```

When sending javascript to web views we also make use of an asynchronous mechanism which `with-result` can also leverage.  But note that minibuffer does not need Javascript so technically we _don't have to_ resort to callbacks.

If we want the minibuffer to draw on screen, it means that the command which called the minibuffer must run in a separate thread.

So here is what I suggest:

- Run all commands in their own thread (in the `run` method of commands).
- `read-from-minibuffer` starts a new thread and returns the result from a channel (using ChanL).

That's it!  Note that we only have to change only two sites, we don't have to alter all commands to start new threads.

Then the minibuffer result is fetched by reading from the channel.  In terms of concurrency, it seems dead simple.  It also removes the need for `with-result*` and `%callback`.

At the moment we don't really handle command results, mostly because of with-result.  WIth the channel strategy we could actually return a channel (or from a channel, I'm not sure at this point).

Note that threads don't have to be OS threads (which can be expensive).  We could resort to using green threads (e.g. https://github.com/thezerobit/green-threads
) of which we can fire up millions with little performance impact.
That said, there will probably not be more than a few nested minibuffers and a couple of commands running at the same time, so the threading setup is probably not an issue.

**Comment by jmercouris** [comment]
If each new command is invoked in a new thread, how do we chain commands together?

**Comment by Ambrevar** [comment]
With channels.

Say command A starts command B.
A waits on the channel result of B.
The B thread completes and writes the result to the channel (last instruction).
A can now resume, gets the value from the channel and procedes.

Note that our current implementation cannot chain commands if they use callbacks (e.g. they contain a with-result).

**Comment by jmercouris** [comment]
Hm, that is a good point you make. As per OS threads being expensive, for our usage it is not worth discussing. I suggest we simply use Bordeaux threads, and that is fine.

**Comment by jmercouris** [comment]
Can you please provide a demonstration implementation so that we can talk a little bit more concretely?

**Comment by Ambrevar** [comment]
I also suggest using ChanL instead of lparallel.  The little I've used
it, it was much better and does not require a setup with global
variables like lparallel.

**Comment by Ambrevar** [comment]
I'll send a draft once I'm done with class-star.

**Comment by Ambrevar** [comment]
In nyxt-pre-release-3.
