### ISSUE TITLE
Per-internal-buffer modes

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#909]
We've got many internal buffers:

- Downloads
- Help buffers
- List buffers
- Messages
- REPL

Please share if you can think of special buffers I forgot.

Currently we have no way to identify these buffers.  Making a new buffer class for each one of them is a bad idea, because we want to be able to navigate across any of the internal buffers (e.g. a help page could point to the downloads buffer).

Instead, we can do like Emacs does it: have a "major-mode" for each type of  internal buffers.

Another issue is that we currently cannot have multiple buffers for some of these types.  For instance there can be only one *Downloads* buffer because we match against its name.  If we start matching against the mode however, then we can have multiple downloads buffer.

Finally, some commands like `clear-message` should only be visible from the *Messages* buffer.  Having a dedicated mode would fix this.

Questions:

- Should these modes be mutually exclusive?  If a buffer has both downloads-mode and messages-mode, then which one is it?  If we want mutual exclusivity, then we need a system like Emacs' major-modes.

- How do we instantiate these buffers?  Shall we just pass the mode and the name to buffer-make?  Do we want an additional abstraction? 

Also see discussion in #903.

**Comment by Ambrevar** [comment]
a6c22473eb4a186416f13fc07a1e37901afccf76
adds message-mode and 7c14c34216394aa8bad8b8fc00c028d86e580ba0
adds buffer-listing-mode.

**Comment by jmercouris** [comment]
We have solved this, every internal buffer has a special mode when necessary :-)

**Comment by Ambrevar** [comment]
Have we answered all the questions from the original post though?

I believe we still don't have a good abstraction for these special modes / buffers.  Should we reopen this issue to keep discussing this?

**Comment by jmercouris** [comment]
I would suggest a new issue.

**Comment by Ambrevar** [comment]
Done in #1790.
