### ISSUE TITLE
Rename show-bookmarks and download-list

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#914]
To list-bookmarks and list-downloads for consistency with list-buffers.

I think `list` is better than `show` because `show-buffers` would be ambiguous and could imply that we display them.

@jmercouris

**Comment by jmercouris** [comment]
You're correct, let's rename:
```
list-messages
list-buffers
list-downloads
list-bookmarks
```

**Comment by Ambrevar** [comment]
Done in db9b42bbabb9a382f11da058f5f8b60f2b45ddfd.
