### ISSUE TITLE
Support more schemes (dynamically?), e.g. telegram

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#917]
Currently we get the list of supported schemes from https://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml and we hardcode it.

It would be better if this list could be filled dynamically.

See discussion in https://github.com/atlas-engineer/nyxt/commit/1b1fffb96c2ca41a1e9b73be205e300cac788430#commitcomment-41845168

**Comment by aartaka** [comment]
For MacOS, there's at least this StackOverflow question https://stackoverflow.com/questions/29614303/list-of-url-scheme-mappings-for-apple-mac-and-or-iphone

Cannot test it, though, as I have no Mac :)

**Comment by aartaka** [comment]
Closing this, as all the unrecognized schemes are now routed to `xdg-open`/`open`, while the browser-specific ones are definable with `define-internal-scheme`.
