### ISSUE TITLE
Feature Request: Make vim like overlays the default set of keybindings to massively increase uptake

### ISSUE THREAD

**Issue by rople380** [atlas-engineer/nyxt#923]
The advanced parts of nyxt are fantastic. However millions of people use vim over other keybindings, both in the browser, in other IDEs, and in emacs itself (EVIL). Vimium is the defacto keybinding based lead in web browsers, with more advanced users using things like surfingkeys/qutebrowser as the default. As a technical user I have bounced off more times than I can count off nyxt because I didn't wish to put the effort in to grok the manual/settings to test drive the browser with a fast changing codebase (which saw some significant changes between my bounces), that is until today.

To improve uptake, and to make nyxt immediately useful to millions of less than technical users and drive adoption, requires a better, less configuration heavy setup (aka *default*) that is immediately useful (install and run), with more popular keybindings, with a more gentle and demonstrative set of examples on startup to make it *immediately useful* (e.g. http://vimium.github.io/ or spacemacs). A knowledge of lisp should not be a prerequisite for use of nyxt, just as a knowledge of lisp is not a prerequisite of use of spacemacs (mostly).

Or if an overlay setting approach is required, have these other tools directly translate to nix to drive adoption with less config over head, equivalent of say (setq vimium true) in say spacemacs.

**Comment by Ambrevar** [comment]
One of the high-priority features which should land in the coming months
is graphical configuration.

You'll be able to enable the VI binding scheme in a matter of a few
clicks.

Would that work for you?

**Comment by rople380** [comment]
Yes that would improve things a lot.

Also the use of binding layer plugins so you can quick activate say, vimium/surfingkeys/qutebrowser trivially (not just one standard VI or custom remaps as I am doing now). I suppose the schemes do this, maybe need some more front facing docs on this rather than a simple keymap example, so its only the addition of the relevant schemes to do this with the function to key map bindings, may be something I'll look into as I get more used to it.

**Comment by Ambrevar** [comment]
Indeed, "keymap schemes" should cover your use case.
I'll come back to documenting it a bit later.

**Comment by jmercouris** [comment]
A quick update on this, it is now available :-)

If you execute COMMON-SETTINGS you get this screen:

![Screen Shot 2020-09-17 at 12 16 16](https://user-images.githubusercontent.com/1691662/93457708-9f2ad000-f8df-11ea-9440-b0ca8a4e4f06.png)

or, if you click "Common settings" on the start screen/help:

![Screen Shot 2020-09-17 at 12 16 41](https://user-images.githubusercontent.com/1691662/93457773-b5389080-f8df-11ea-92ac-3ed8f7282e75.png)

does that work OK to resolve this issue? Should we prompt the user on first start-up?

**Comment by rople380** [comment]
Yes, this plus additional keymaps (vimium/qutebrowser/surfingkeys/spacemacs overlays) should work great.

Another exceptionally useful thing is binding ? to a help popup, used in vimium/qutebrowser/surfingkeys.

Maybe create documentation/stubs for these other keymaps (increase user usuage/hackability speed for new people) so that others can rapidly template extend and fill this out without fully having to grok nyxt browser internals that much, I've already got the basics of some of spacemacs like overlays which I can integrate in the future, but not enough time to fully grok the keybinding system. Maybe some stub examples extensions for others to quickly integrate/pop off would be useful.

**Comment by Ambrevar** [comment]
See commit 729214edeacec943d5a8403f67c461321aaf22ed: I've added pointers
to the manual about how to create new scheme names (what you call
overlays).

It's as simple as the following

(defvar vimium (make-scheme-name "vimium" vi-normal))

Then use `define-scheme` as usual.

**Comment by jmercouris** [comment]
I am closing for now, if ther eis anything else, please reopen :-)
