### ISSUE TITLE
Support clipboard paste from systems running Wayland

### ISSUE THREAD

**Issue by craftyguy** [atlas-engineer/nyxt#924]
It appears that nyxt depends on xclip for managing the clipboard, this utility does not make sense on Wayland (there are similar tools for Wayland compositors, like wl-copy). As a result, any attempt to C-v paste will crash nyxt:

```
<INFO> [15:39:41] Loading global history of 12 URLs from "/home/clayton/.local/share/nyxt/history.lisp".
--
  | Unhandled UIOP/RUN-PROGRAM:SUBPROCESS-ERROR in thread #<SB-THREAD:THREAD "Anonymous thread" RUNNING
  | {1007C15193}>:
  | Subprocess #<UIOP/LAUNCH-PROGRAM::PROCESS-INFO {1007C18293}>
  | with command ("/usr/bin/xclip" "-out" "-selection" "clipboard")
  | exited with error code 1
  |  
  | Backtrace for: #<SB-THREAD:THREAD "Anonymous thread" RUNNING {1007C15193}>
  | 0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<UIOP/RUN-PROGRAM:SUBPROCESS-ERROR {1007C1B993}> #<unused argument> :QUIT T)
  | 1: (SB-DEBUG::RUN-HOOK SB-EXT:*INVOKE-DEBUGGER-HOOK* #<UIOP/RUN-PROGRAM:SUBPROCESS-ERROR {1007C1B993}>)
  | 2: (INVOKE-DEBUGGER #<UIOP/RUN-PROGRAM:SUBPROCESS-ERROR {1007C1B993}>)
  | 3: (CERROR "IGNORE-ERROR-STATUS" UIOP/RUN-PROGRAM:SUBPROCESS-ERROR :COMMAND ("/usr/bin/xclip" "-out" "-selection" "clipboard") :CODE 1 :PROCESS #<UIOP/LAUNCH-PROGRAM::PROCESS-INFO {1007C18293}>)
  | 4: (UIOP/RUN-PROGRAM::%CHECK-RESULT 1 :COMMAND ("/usr/bin/xclip" "-out" "-selection" "clipboard") :PROCESS #<UIOP/LAUNCH-PROGRAM::PROCESS-INFO {1007C18293}> :IGNORE-ERROR-STATUS NIL)
  | 5: (UIOP/RUN-PROGRAM::%USE-LAUNCH-PROGRAM ("/usr/bin/xclip" "-out" "-selection" "clipboard") :OUTPUT #<SB-IMPL::STRING-OUTPUT-STREAM {7FA98B5AE633}>)
  | 6: (TRIVIAL-CLIPBOARD:TEXT NIL)
  | 7: ((LAMBDA NIL :IN NYXT/MINIBUFFER-MODE:MINIBUFFER-PASTE))
  | 8: ((LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS))
  | 9: ((FLET SB-UNIX::BODY :IN SB-THREAD::RUN))
  | 10: ((FLET "WITHOUT-INTERRUPTS-BODY-14" :IN SB-THREAD::RUN))
  | 11: ((FLET SB-UNIX::BODY :IN SB-THREAD::RUN))
  | 12: ((FLET "WITHOUT-INTERRUPTS-BODY-4" :IN SB-THREAD::RUN))
  | 13: (SB-THREAD::RUN)
  | 14: ("foreign function: call_into_lisp")
  | 15: ("foreign function: funcall1")
  |  
  | unhandled condition in --disable-debugger mode, quitting
  | Unhandled SB-THREAD:JOIN-THREAD-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING
  | {10006A00D3}>:
  | Joining thread failed: thread #<THREAD "cl-cffi-gtk main thread" ABORTED
  | {1008200DE3}> did not return normally.
```

There should be an option to override the clipboard utility for systems where xclip is not used for managing the clipboard.

Also, crashing the browser because of this seems a bit much, maybe it should handle this exception and print an error somewhere instead?

**Comment by Ambrevar** [comment]
xclip errors should be ignored, it should not crash Nyxt.  This issue
has been reported before, but I can't reproduce.  I wonder what's
happening.

Regarding Wayland support, you are absolutely right.
I've reported the issue upstream:

https://github.com/snmsts/trivial-clipboard/issues/8

Any idea how to detect whether Wayland is running?

**Comment by craftyguy** [comment]
> Any idea how to detect whether Wayland is running?

I'm not sure. Some (all?) compositors require `XDG_RUNTIME_DIR` to be set, but that might also be set on X too, so I don't think that'd be a reliable way to determine if Wayland is running.

If the goal is to find the appropriate clipboard app, it seems like doing: 

1) if xclip is around, try to use it. if that fails, try to use some others (e.g. wl-copy for wayland?)

2) allow the user to specify a clipboard app to use, then you could skip the above step and just try to use the user-defined app.

**Comment by aadcg** [comment]
I have the same issue when I paste on wayland. There's also the env var `WAYLAND_DISPLAY` if this is of any help.

**Comment by Ambrevar** [comment]
Upstream has a fix.

If you clone https://github.com/snmsts/trivial-clipboard/ to
~/common-lisp and rebuild Nyxt, it should fix the issue.

**Comment by aadcg** [comment]
I'm on GNU/Guix. I ran `guix pull` and `guix package --upgrade nyxt`. Is this equivalent to the approach you mentioned?

**Comment by Ambrevar** [comment]
André Alexandre Gomes <notifications@github.com> writes:

> I'm on GNU/Guix. I ran `guix pull` and `guix package --upgrade nyxt`. Is this equivalent to the approach you mentioned?

I've updated the trivial-clipboard package yesterday, so yes, this
should work.

**Comment by aadcg** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> I've updated the trivial-clipboard package yesterday, so yes, this
> should work.

Exactly, I noticed the change in the common lisp dependency.

If I copy some text in the buffer and then paste (say on a issues page
like this) Nyxt won't crash.

However, if I copy a link with right-mouse click -> Copy Link Location
and then hit C-y to paste, it does crash...  Does this make any sense?

**Comment by jmercouris** [comment]
What you are describing makes sense. Why it could be happening, does not make sense :-)

When you are pressing C-y to paste, is a input field selected?

**Comment by jmercouris** [comment]
Mouse buffer? What is a mouse buffer?

**Comment by Ambrevar** [comment]
I think Peter meant the clipboard: Xorg has three "buffers" for copy
pasting:
- primary selection (the regular copy-paste)
- secondary selection (I've never seen this one in use)
- clipboard (the copy happens when you select text with the mouse -- no
additional keypress -- and the pasting is triggered with the middle
mouse button).

Peter: Nyxt currently tries to hi-jack all means for pasting because of
a bug in the GTK bindings that causes Nyxt to hang if we would use the
regular pasting solution.  So you won't be able to use the clipboard in
Nyxt until we've fixed the binding issue, sorry :p

Can you reproduce when you press C-v instead of C-y?

**Comment by Ambrevar** [comment]
Can you share an exact recipe without init file?  Which web page, which
field, which key.  (Start Nyxt with the
--no-init flag.)

I presume you are running Emacs mode, right?

**Comment by Ambrevar** [comment]
Ha!  OK, I know what's happening: GTK has a binding to C-y which I
didn't know of.  Easy fix: we need to override it.  I'm on the road now,
@jmercouris: can you move the C-y binding to CUA mode?

**Comment by jmercouris** [comment]
Will do!

**Comment by jmercouris** [comment]
Complete 9f669bc6

**Comment by jmercouris** [comment]
I've duplicated the binding in CUA mode (not moved) in case we resolve the problem with C-y and decide to remove it from the CUA bindings.

**Comment by olynch** [comment]
I'm having trouble with copy and paste on wayland using the Nyxt that's currently in NixOS.

**Comment by jmercouris** [comment]
The NixOS build has a problem, you can right click and copy at least :-). Highlight some text and copy it. Pasting it.. well... that is another story...

**Comment by Ambrevar** [comment]
I think there are two issues here:

1. Nix does not package trivial-clipboard properly.
2. trivial-clipboard should resolve the clipboard commands at runtime
and not at compile time.

I've opened an issue about the latter: https://github.com/snmsts/trivial-clipboard/issues/9

**Comment by Ambrevar** [comment]
It's an easy fix ;)

**Comment by olynch** [comment]
Wow, thanks guys! That was so speedy! I'm plugging Nyxt to all my friends!

**Comment by jmercouris** [comment]
nice :-), enjoy!
