### ISSUE TITLE
search-buffer modifies text in buffer and highlights matches incorrectly

### ISSUE THREAD

**Issue by jolmg** [atlas-engineer/nyxt#929]
**Describe the bug**

The highlights don't match the text I search on each paragraph for all the matches after the first, seemingly only when there's more than 2 matches.

EDIT: The text gets modified too, as I mentioned in the next comment.

![zshARkjtT](https://user-images.githubusercontent.com/17855790/92286370-b1f2dd00-eebb-11ea-8d61-3d72177991b6.png)

**Precise recipe to reproduce the issue**

Just search for a text that appears multiple times in a paragraph.

**Information**
- OS name+version: Archlinux last updated about a week ago.
- Graphics card and driver: intel integrated graphics, driver: xf86-video-intel 
- Desktop environment / Window manager name+version: i3 4.18.2
- How you installed Nyxt: AUR package nyxt-browser-git 2.pre.release.1.r0.ge83e1021-1
- Information from command copy-system-information:

```
Nyxt version: 2-pre-release-1 
Operating system kernel: Linux 5.8.5-arch1-1
Lisp implementation: SBCL 2.0.5
Features: (WEBKIT2 WEBKIT2-2.28 WEBKIT2-EMOJI WEBKIT2-MEDIA WEBKIT2-SANDBOXING
           GTK-3-22 GTK-3-20 GTK-3-18 GTK-3-16 GTK-3-14 GTK-3-12 GTK-3-10
           GTK-3-8 GTK-3-6 GTK-3-4 GTK GDK-3-22 GDK-3-20 GDK-3-18 GDK-3-16
           GDK-3-14 GDK-3-12 GDK-3-10 GDK-3-8 GDK-3-6 GDK-3-4 CAIRO-1-10
           CAIRO-1-12 GDK-PIXBUF GLIB-2-30 GLIB-2-32 GLIB-2-34 GLIB-2-36
           GLIB-2-38 GLIB-2-40 GLIB-2-42 GLIB-2-44 GLIB-2-46 GLIB-2-48
           GLIB-2-50 GLIB-2-52 GLIB-2-54 GLIB-2-56 GLIB-2-58 GLIB
           FSET-EXT-STRINGS SWANK PLUMP-UTF-32 GLOBAL-VARS DECLARE-TYPES
           PARENSCRIPT NAMED-READTABLES OSICAT-FD-STREAMS LPARALLEL 21BIT-CHARS
           CL-FAD CHUNGA FLEXI-STREAMS CLOSER-MOP CL-PPCRE-UNICODE CL-UNICODE
           CL-PPCRE BORDEAUX-THREADS LPARALLEL.WITH-CLTL2 LPARALLEL.WITH-CAS
           LPARALLEL.WITH-STEALING-SCHEDULER SPLIT-SEQUENCE GRAY-STREAMS
           FLAT-NAMESPACE X86-64 UNIX CFFI FLAT-NAMESPACE SEQUENCE-EMPTYP
           FAST-IO-SV FAST-IO SBCL-USES-SB-ROTATE-BYTE ASDF-SYSTEM-CONNECTIONS
           CL-JSON-CLOS CL-JSON THREAD-SUPPORT QUICKLISP ASDF3.3 ASDF3.2
           ASDF3.1 ASDF3 ASDF2 ASDF OS-UNIX NON-BASE-CHARS-EXIST-P ASDF-UNICODE
           X86-64 GENCGC 64-BIT ANSI-CL COMMON-LISP ELF IEEE-FLOATING-POINT
           LINUX LITTLE-ENDIAN PACKAGE-LOCAL-NICKNAMES SB-CORE-COMPRESSION
           SB-LDB SB-PACKAGE-LOCKS SB-THREAD SB-UNICODE SBCL UNIX)
```

**Comment by jolmg** [comment]
Now that I look closer, the text is modified when searching. That first line should say:

> This manual first includes the tutorial, then covers the configuration of Nyxt.

not:

> This manual first includes the first includes the fial fial first includes the tutorial, then covers the configuration of Nyxt.

**Comment by Ambrevar** [comment]
I believe this is a duplicate of #666.

**Comment by jolmg** [comment]
@Ambrevar Looks like it, except that it doesn't mention that text is modified by search. Seems like that part of the problem was present then too, since in your quoted text you have:

> any **of they of they** of the functions

Feel free to close this issue if you want. I don't know why I wasn't able to find your original issue before making this one.

**Comment by jolmg** [comment]
Or I'll just close it.
