### ISSUE TITLE
Compiling for arm64/aarch64

### ISSUE THREAD

**Issue by sandeep-gh** [atlas-engineer/nyxt#932]
I tried compiling this on arm64 but failed here:

```
; compiling file "/home/ubuntu/common-lisp/nyxt/quicklisp-client/dists/quicklisp/software/cl-cffi-gtk-20200427-git/glib/glib.misc.lisp" (written 05 SEP 2020 08:04:22 PM):
; compiling (IN-PACKAGE :GLIB)
; compiling (COND (# #) ...)Unhandled SIMPLE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING
                                    {1002827E03}>:
  Can not define 'g-size', unknown CPU architecture (known are x86 and x86-64)
```
Not sure if there is a simple fix.

**Comment by aartaka** [comment]
`cl-cffi-glib` has this `cond` in its toplevel (it's the one the error comes from):
``` lisp 
(eval-when (:compile-toplevel :load-toplevel :execute)
  (cond ((cffi-features:cffi-feature-p :x86-64) (defctype g-size :uint64))
        ((cffi-features:cffi-feature-p :x86)    (defctype g-size :ulong))
        ((cffi-features:cffi-feature-p :ppc32)  (defctype g-size :uint32))
        ((cffi-features:cffi-feature-p :ppc64)  (defctype g-size :uint64))
        (t
         (error "Can not define 'g-size', unknown CPU architecture ~
                (known are x86 and x86-64)"))))
```

`cffi-features` have no features related to ARM (the full list of architectures is `#:ppc32 #:x86 #:x86-64 #:sparc #:sparc64 #:hppa #:hppa64`). It doesn't mean that ARM is impossible to work with, just that there're no CFFI binding for it yet.

We'd need to make something with ARM support in `cffi` and `cl-cffi-glib` to even try compiling Nyxt for ARM. It's not impossible though, because GLib seems to be at least [compilable for ARM](https://mail.gnome.org/archives/gtk-list/2006-January/msg00013.html) and [has ARM Debian package](https://packages.debian.org/jessie/libglib2.0-0), for example. It's just about writing proper bindings in Lisp :)

**Comment by Ambrevar** [comment]
It might take a lot of work to get cl-cffi-glib support ARM.
However, adding support in CFFI might be enough if we add a
cl-gobject-introspection renderer for Nyxt.

**Comment by Ambrevar** [comment]
@aartaka Any idea if upstream has a discussion about ARM support?
The bug tracker does not seem to have much: https://bugs.launchpad.net/cffi?field.searchtext=arm&search=Search&field.status%3Alist=NEW&field.status%3Alist=INCOMPLETE_WITH_RESPONSE&field.status%3Alist=INCOMPLETE_WITHOUT_RESPONSE&field.status%3Alist=CONFIRMED&field.status%3Alist=TRIAGED&field.status%3Alist=INPROGRESS&field.status%3Alist=FIXCOMMITTED&field.assignee=&field.bug_reporter=&field.omit_dupes=on&field.has_patch=&field.has_no_package=

**Comment by aartaka** [comment]
> @aartaka Any idea if upstream has a discussion about ARM support?
> The bug tracker does not seem to have much

I was wondering about that too. It seems ARM support it's not on a tracker :(

**Comment by Ambrevar** [comment]
I've asked: https://bugs.launchpad.net/cffi/+bug/1909977

**Comment by Ambrevar** [comment]
Answer from Luis:

> CFFI contains virtually no architecture-specific code, so there's no need to add ARM support. The cl-cffi-gtk code mention in nyxt issue 932 uses cffi-features which has been deprecated in favor of trivial-features almost 15 years ago. Please use trivial-features instead. However, trivial-features doesn't mention ARM. I'm not familiar with all the ARM variants, but the first step to specify ARM features in trivial-features would be to survey what CL implementations currently push to features on that platform. HTH.

**Comment by Ambrevar** [comment]
Update: Trivial-features now supports ARM.

https://github.com/trivial-features/trivial-features/issues/13#issuecomment-1110872587 

CL-CFFI-GTK could be updated as per this comment.  We could fork it if upstream does not do it.

But we could also switch to cl-gobject-introspection entirely.

**Comment by Thovthe** [comment]
Would getting a PineBook Pro for one of the core devs maybe lead to some progress in this area?

**Comment by jmercouris** [comment]
Maybe. Our issue is primarily one of time, not hardware. The proposal is however, welcome. Thank you for your consideration!

**Comment by aadcg** [comment]
The issue reported in the original post no longer exists.

**Comment by Ambrevar** [comment]
Does Nyxt compile on ARM now?

**Comment by aadcg** [comment]
I was able to load both `cl-webkit2` and `cl-cffi-gtk-gtk` and generate all `.fas` (similar to `.fasl` in SBCL) and `.o` files with ECL on an ARM device. 

From there, it would be need to be further tested.

**Comment by aadcg** [comment]
Nyxt runs on ARM.
