### ISSUE TITLE
Feature Request: Tabs Group Profiles alla Guix's Profiles

### ISSUE THREAD

**Issue by ccao001** [atlas-engineer/nyxt#934]
@Ambrevar 

## Question 

How hard would it be to implement profiles (alla guix, nix, flatpak, etc...) but for your current/previous collection(s) of open tabs?

## Further Explanation

Firefox has the option `Restore Previous Session` which brings back all the user's opened tabs from the previous session.

The problem is that the user only has the ability to restore the __previous session__. If the user happens to open the browser again and starts browsing only to subsequently close the session, then the previous previous session would be lost. Maybe there's a similarity to what [history as a tree](https://github.com/atlas-engineer/nyxt/blob/1.5.0/documents/MANUAL.org#history) solves in nyxt?

[Bookmark Tags](https://github.com/atlas-engineer/nyxt/blob/1.5.0/documents/MANUAL.org#bookmarks) seem to help with this but I am thinking here of grouped tab sessions as a semantic object that has a version controlled traversable history.

## Proposal 

What I am proposing is that at the end of a browsing session the user can save all tabs into an `open-tabs-manifest` and that manifest can subsequently be put under a version control system.

Maybe this tabs manifest can be represented with a similar syntax to a guix manifest or just plain S-expressions to be used for later parsing by nyxt. 

Maybe json would be a more portable representation here? Or there can be levels of [intermediary representations](https://www.gnu.org/software/guile/manual/html_node/Tree_002dIL.html) for tab groups.

This would allow the user to `rollback` to any previous `session-tabs-profile`. These `tabs-profiles` contents can be browsed and chosen from nyxt's minibuffer.

I'm just thinking out loud but I thought that this might be a nice feature that nyxt can implement in the future. 

What are your thoughts? 

## Mailing List or Wiki or Not?

Would nyxt consider having a mailing list or wiki? Maybe that is the appropriate place to document and discuss these ideas in a more persistent and public manner.

Sorry if this does not fit the bill of what is expected in an issue request on github.

**Comment by Ambrevar** [comment]
Nyxt supports multiple sessions.
From a shell, you can start Nyxt with

  nyxt --with-path session=foo

to start the foo session.
The session is stored in ~/.local/share/nyxt/sessions by default.  It's
in a s-exp format, so it's versionable.  It preserves the buffer histories.

What's mostly missing is the ability to select your session on startup,
although that wouldn't be too hard to implement.

Would that cover your use case?

About the mailing list: We thought of having one, but we are currently a
bit too understaffed to maintain it on top of an issue tracker and
everything else.  Until Nyxt gets more traction, I think it's wiser to
stick to less communication channels.

**Comment by aartaka** [comment]
It can be useful to store the tab setup to a dedicated _user-inputted_ file _at an arbitrary browsing moment_, in addition to the end of session. This way one could save snippets of work/study/reading setup and return to it later.

I had a lot of moments I wished to dump my session somewhere, but I 
- needed to install several extensions, and/or
- needed to use uncomfortable mouse-oriented UIs.

The way Nyxt handles sessions is perfect for seamless session dumping, and it possibly won't suffer from problems listed above.

One unpleasant thing is that, having this smooth interface, one could expect that session data would have the same readability/editability as bookmarks, auto-mode rules... Should we make session/history data serialization more readable then?

**Comment by Ambrevar** [comment]
Artyom Bologov <notifications@github.com> writes:

> One unpleasant thing is that, having this smooth interface, one could expect that session data would have the same readability/editability as bookmarks, auto-mode rules... Should we make session/history data serialization more readable then?

Do you have a use case for reading or editing the session file?

If you want to remove buffers from the session, simply call the
delete-buffer command and save the session again.

I don't think anyone would want to edit the history: this would
effectively compromise the integrity of the session.

Maybe the part that'd be missing is the ability to merge sessions.
Would that be useful though?

**Comment by aartaka** [comment]
> Do you have a use case for reading or editing the session file? 

If I stored a session with 10+ academic papers opened for reading on some topic, and then someone said that I won't need one of the papers for certain, I'd like to remove it without restoring the session, deleting a buffer and storing a session. It's faster to open Emacs and delete the entry for this paper.

It's about deletion though, and deletion is, as far as I recall, possible in current (de)serialization version. No solid use-case for editing session, so I'm not sure it's actually necessary.

> If you want to remove buffers from the session, simply call the delete-buffer command and save the session again. 

This is useful if the session is the current one, but what obout stored and killed ones? You'd need to restore it, clean all the other buffers, delete the unnecessary buffer and store it. It's much more steps in such a case.

> I don't think anyone would want to edit the history: this would effectively compromise the integrity of the session. 

Fair point!

> Maybe the part that'd be missing is the ability to merge sessions. Would that be useful though?

I believe it'd be! Although no use-cases yet -- I just can't imagine it working :)

**Comment by aartaka** [comment]
@ccao001, here's the first (although untested) iteration of the idea (it's already implementable thanks to Nyxt flexibility):
``` lisp 
(define-command store-session-by-name ()
  (with-result (name (read-from-minibuffer
                      (make-minibuffer
                       :input-prompt "The name to store session with:")))
    (let ((old-session-path (session-path (current-buffer))))
      (setf (session-path (current-buffer))
            (make-instance 'session-data-path
                           :basename name
                           :dirname (uiop:xdg-data-home +data-root+ "sessions")))
      (unwind-protect
           (store (data-profile (current-buffer))
                  (session-path (current-buffer)))
        (setf (session-path (current-buffer))
              old-session-path)))))

(define-command restore-session-by-name ()
  (with-result (name (read-from-minibuffer
                      (make-minibuffer
                       :input-prompt "The name of session to restore:")))
    (let ((old-session-path (session-path (current-buffer))))
      (setf (session-path (current-buffer))
            (make-instance 'session-data-path
                           :basename name
                           :dirname (uiop:xdg-data-home +data-root+ "sessions")))
      (unwind-protect
           (restore (data-profile (current-buffer))
                    (session-path (current-buffer)))
        (setf (session-path (current-buffer))
              old-session-path)))))
```

Dynamically `let`-shadowing class slots could shorten it dramatically...

**Comment by Ambrevar** [comment]
Artyom Bologov <notifications@github.com> writes:

> Dynamically `let`-shadowing class slots could shorten it dramatically...

We have `with-class`.  Maybe that'd work here.

**Comment by aartaka** [comment]
Just tested, it works! Look the most recent edit for the implementation. 

> We have `with-class`. Maybe that'd work here.

Yes, `with-slots`/`with-accessors` can come in handy here.

**Comment by Ambrevar** [comment]
Artyom Bologov <notifications@github.com> writes:

> Just tested, it works! Look the most recent edit for the implementation. 

Would you like to send a patch?

>> We have `with-class`. Maybe that'd work here.
>
> Yes, `with-slots`/`with-accessors` can come in handy here.

There may be a misunderstanding: with-class locally overrides the class
definition, including its slots.
with-slots and with-accessors are only shortcuts to the slots and
accessors, they don't redefine them.

**Comment by aartaka** [comment]
> Would you like to send a patch?

Yes, but I'll ned some time to polish it. I'll send it in a day, I guess.

> There may be a misunderstanding: with-class locally overrides the class definition, including its slots.

Wow, that sounds awesome! I didn't know that we have such a cool macro :)

I found only `with-user-class` (in configuration.lisp) though. Is that what you meant?

**Comment by Ambrevar** [comment]
Yes, sorry, forgot we had renamed it.

As the name implies, it only work on user-classes, i.e. user-buffer,
user-minibuffer, user-window, user-browser, all the modes, etc.
