### ISSUE TITLE
Unable to load webkit when trying to run in guix container

### ISSUE THREAD

**Issue by elais** [atlas-engineer/nyxt#938]
**Describe the bug**
When trying to run Nyxt in a container I get the error: 'Problem running initialization hook GLIB::RUN-INITIALIZERS' followed by a message saying unable to load webkit errors. See below. Are the docs outdated or am I missing something? Running IceCat in a container works just fine. 

```lisp
Unhandled SIMPLE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING
                                    {10007380D3}>:
  Problem running initialization hook GLIB::RUN-INITIALIZERS:
  Unable to load any of the alternatives:
   ("/gnu/store/614fwp0ar47czqywa9x68msidp374iz6-webkitgtk-2.28.4/lib/libwebkit2gtk-4.0.so"
    "/gnu/store/614fwp0ar47czqywa9x68msidp374iz6-webkitgtk-2.28.4/lib/libwebkit2gtk-3.0.so.25.10.9"
    "/gnu/store/614fwp0ar47czqywa9x68msidp374iz6-webkitgtk-2.28.4/lib/libwebkit2gtk-3.0.so.25.10.8"
    "/gnu/store/614fwp0ar47czqywa9x68msidp374iz6-webkitgtk-2.28.4/lib/libwebkit2gtk-3.0.so.25.10.7"
    "/gnu/store/614fwp0ar47czqywa9x68msidp374iz6-webkitgtk-2.28.4/lib/libwebkit2gtk-3.0.so.25")

Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {10007380D3}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<SIMPLE-ERROR "Problem running ~A hook ~S:~%  ~A" {1005DB38A3}> #<unused argument> :QUIT T)
1: (SB-DEBUG::RUN-HOOK *INVOKE-DEBUGGER-HOOK* #<SIMPLE-ERROR "Problem running ~A hook ~S:~%  ~A" {1005DB38A3}>)
2: (INVOKE-DEBUGGER #<SIMPLE-ERROR "Problem running ~A hook ~S:~%  ~A" {1005DB38A3}>)
3: (ERROR #<SIMPLE-ERROR "Problem running ~A hook ~S:~%  ~A" {1005DB38A3}>)
4: (SB-KERNEL:WITH-SIMPLE-CONDITION-RESTARTS ERROR NIL "Problem running ~A hook ~S:~%  ~A" "initialization" GLIB::RUN-INITIALIZERS #<CFFI:LOAD-FOREIGN-LIBRARY-ERROR "Unable to load any of the alternatives:~%   ~S" {1005DB3803}>)
5: (SB-INT:CALL-HOOKS "initialization" (GLIB::RUN-INITIALIZERS LOG4CL-IMPL::INIT-HOOK) :ON-ERROR :ERROR)
6: ((FLET SB-UNIX::BODY :IN SB-IMPL::START-LISP))
7: ((FLET "WITHOUT-INTERRUPTS-BODY-1" :IN SB-IMPL::START-LISP))
8: (SB-IMPL::START-LISP)
```

**Precise recipe to reproduce the issue**
Just try to run this command as shown in the documentation.

`guix environment --container --network --preserve='^DISPLAY$'  --expose=/etc/ssl/certs --expose="$HOME/.config/nyxt/" --share="$HOME/.local/share/nyxt/" --ad-hoc nss-certs nyxt -- nyxt`

**Information**
- OS name+version: Guix System 1.1.0
- Graphics card and driver: intel iris
- Desktop environment / Window manager name+version: LXQT/StumpWM
- How you installed Nyxt (Guix pack, package manager, build from source): Guix package manager
- Information from command copy-system-information:
Nyxt version: 2-pre-release-1 
Operating system kernel: Linux 5.8.7
Lisp implementation: SBCL 2.0.8
Features: (WEBKIT2 WEBKIT2-2.28 WEBKIT2-EMOJI WEBKIT2-MEDIA WEBKIT2-SANDBOXING
           GTK-3-22 GTK-3-20 GTK-3-18 GTK-3-16 GTK-3-14 GTK-3-12 GTK-3-10
           GTK-3-8 GTK-3-6 GTK-3-4 GTK GDK-3-22 GDK-3-20 GDK-3-18 GDK-3-16
           GDK-3-14 GDK-3-12 GDK-3-10 GDK-3-8 GDK-3-6 GDK-3-4 CAIRO-1-10
           CAIRO-1-12 GDK-PIXBUF GLIB-2-30 GLIB-2-32 GLIB-2-34 GLIB-2-36
           GLIB-2-38 GLIB-2-40 GLIB-2-42 GLIB-2-44 GLIB-2-46 GLIB-2-48
           GLIB-2-50 GLIB-2-52 GLIB-2-54 GLIB-2-56 GLIB-2-58 GLIB
           FSET-EXT-STRINGS SWANK PLUMP-UTF-32 GLOBAL-VARS DECLARE-TYPES
           PARENSCRIPT SBCL+SAFE-STANDARD-READTABLE NAMED-READTABLES
           OSICAT-FD-STREAMS LPARALLEL 21BIT-CHARS CL-FAD CHUNGA FLEXI-STREAMS
           CLOSER-MOP CL-PPCRE-UNICODE CL-UNICODE CL-PPCRE
           CL-JSON-DOUBLE-FLOAT-IS-SUBSUMED CL-JSON-SINGLE-FLOAT-IS-SUBSUMED
           BORDEAUX-THREADS LPARALLEL.WITH-CLTL2 LPARALLEL.WITH-CAS
           LPARALLEL.WITH-STEALING-SCHEDULER SPLIT-SEQUENCE GRAY-STREAMS
           FLAT-NAMESPACE X86-64 UNIX CFFI FLAT-NAMESPACE SEQUENCE-EMPTYP
           FAST-IO-SV FAST-IO SBCL-USES-SB-ROTATE-BYTE CL-JSON-CLOS CL-JSON
           THREAD-SUPPORT ASDF3.3 ASDF3.2 ASDF3.1 ASDF3 ASDF2 ASDF OS-UNIX
           NON-BASE-CHARS-EXIST-P ASDF-UNICODE X86-64 GENCGC 64-BIT ANSI-CL
           COMMON-LISP ELF IEEE-FLOATING-POINT LINUX LITTLE-ENDIAN
           PACKAGE-LOCAL-NICKNAMES SB-CORE-COMPRESSION SB-LDB SB-PACKAGE-LOCKS
           SB-THREAD SB-UNICODE SBCL UNIX)

**Output when started from a shell**
Nyxt version 2-pre-release-1
<INFO> [02:07:38] Loading Lisp file "/home/elais/.config/nyxt/init.lisp".
<INFO> [02:07:38] Using data profile "default".
<INFO> [02:07:38] Listening to socket "/home/elais/.local/share/nyxt/nyxt.socket".
<INFO> [02:07:38] Restoring session "/home/elais/.local/share/nyxt/sessions/default.lisp".
<INFO> [02:07:38] Restoring (https://github.com/atlas-engineer/nyxt/issues/492
                             https://old.reddit.com/r/unixporn/comments/64mihc/i3_kde_plasma_a_match_made_in_heaven/
                             https://blogs.oracle.com/pranav/how-to-find-out-cpu-utilization-in-linux
                             https://stumpwm.github.io/git/stumpwm-git_8.html#Groups
                             https://github.com/atlas-engineer/nyxt/tree/master/documents
                             https://lists.gnu.org/archive/html/help-guix/2018-01/msg00056.html).

(process:28593): libsoup-WARNING **: 02:07:39.128: Failed to execute query: table soup_hsts_policies already exists

**Comment by Ambrevar** [comment]
Looks like a grafting issue.  Which command did you run?

**Comment by elais** [comment]
When installing or running? The command I ran with is up there.

I'll try reinstalling with `--no-grafts`

**Comment by Ambrevar** [comment]
Sorry, I initially missed the command you shared.
Try running with `--no-grafts` and let me know if it does the trick!

**Comment by elais** [comment]
Thanks Ambrevar running with `--no grafts` indeed solved my problem! Now on to the work of making sure everything I need is in the environment.

I'm closing this issue but for posterity's sake why did running with `--no-grafts` fix it? Were dependencies just out of scope?

**Comment by Ambrevar** [comment]
I'll add --no-grafts to the doc, thanks for confirming!

The issue is with Guix "reference scanner" which does not support
non-ASCII non-UTF8 encodings.

See https://issues.guix.info/33848 for a discussion.
