### ISSUE TITLE
Monospace font not used

### ISSUE THREAD

**Issue by arunisaac** [atlas-engineer/nyxt#940]
Nyxt is not using a monospace font within pre tags or even when opening plain text files. In fact, I don't see monospace fonts anywhere in nyxt. Am I missing some font or configuration? Or, is this a bug?

I am on nyxt 2-pre-release-1, but I've had this problem for a long time.

Thanks!

**Comment by jmercouris** [comment]
Do you have any mono space fonts installed on your system? If you manually change styles to show mono fonts, do they appear?

**Comment by Ambrevar** [comment]
I can see monospace fonts in the manual or on the help page.
I'm on Guix System and the only font in my profile is font-dejavu.

Are you running Nyxt from a Guix container?

**Comment by arunisaac** [comment]
> Do you have any mono space fonts installed on your system?

Yes, monospace fonts work in other applications (such as Emacs) and
other browsers (such as Icecat).

> If you manually change styles to show mono fonts, do they appear?

Do you mean setting the CSS? I tried with a small HTML file with
font-family: monospace set in the CSS. Monospace fonts did not
appear. Just to be sure, I opened the same page in Icecat, and monospace
fonts were displayed correctly.

> I can see monospace fonts in the manual or on the help page.
> I'm on Guix System and the only font in my profile is font-dejavu.

I'm on a Guix system and have 4 fonts in my profile --- font-wqy-zenhei,
font-meera-inimai, font-gnu-freefont-ttf and font-dejavu. I also did the
`fc-cache -rv` suggested by the Guix manual to no avail.

> Are you running Nyxt from a Guix container?

No, I'm not running nyxt in a Guix container.

I installed nyxt on another Parabola system, and monospace fonts worked
correctly. So, this is indeed something wrong with my Guix system. I'll
try to debug. Any pointers? Is there some fontconfig command that will
help me trace out how fontconfig searches for fonts?

**Comment by Ambrevar** [comment]
Try removing all fonts except font-dejavu.
Maybe one of the other fonts is picked first and it has monospace that's
not really monospace?

**Comment by arunisaac** [comment]
Indeed, that was the issue! Keeping only font-dejavu fixes the issue. I also narrowed down the problem to both font-gnu-freefont-ttf and font-meera-inimai. Keeping either one of them installed causes the problem.

Thanks!

**Comment by Ambrevar** [comment]
I'd like to know why it causes a problem with Nyxt and not with other
GTK-3 programs.  Can you reproduce with Vimb or other GTK-3 programs?

**Comment by arunisaac** [comment]
That's a good question. Do you think this issue should be reopened?

I tried vimb. Curiously, vimb's modeline uses monospace correctly
regardless of which fonts are installed. But, its web page area (the
webkit part) has the discussed monospace issue when fonts such as
font-meera-inimai and font-gnu-freefont-ttf are installed. So, perhaps
this issue has something to do with webkit. Is nyxt's modeline rendered
using webkit?

Emacs has no trouble with any fonts. But, then again, I use emacs-lucid
not the gtk version. Besides, I believe emacs has its own mechanism for
selecting fonts correctly.

**Comment by arunisaac** [comment]
I figured out this problem just now after all these years. It turns out that fontconfig prioritizes matching the language over matching the font family (monospace, etc.). So, on an English locale, fontconfig correctly finds a monospace font. But, on my Tamil locale, when asked for a monospace font, fontconfig prefers a proportional Tamil font to a monospace English font. In other words, `LC_ALL=C fc-match monospace` matches DejaVu Sans Mono. But, with my default Tamil locale, `fc-match monospace` matches one of my Tamil fonts instead. I fixed this problem by adding a match rule in my `~/.config/fontconfig/fonts.conf`. Here are its contents.

```
<?xml version='1.0'?>
<!DOCTYPE fontconfig SYSTEM 'fonts.dtd'>
<fontconfig>
  <dir>~/.guix-home/profile/share/fonts</dir>
  <match target="pattern">
    <test qual="any" name="family" compare="eq"><string>monospace</string></test>
    <edit name="family" mode="assign" binding="same"><string>DejaVu Sans Mono</string></edit>
  </match>
</fontconfig>
```

**Comment by arunisaac** [comment]
Also, as an answer to an earlier question, I later found that this same problem did sporadically appear on IceCat too, but only on some webpages. I'm not sure why monospace fonts worked on some webpages but not on others. Perhaps, those webpages used monospace web fonts. Or perhaps, for some reason, some webpages resulted in more specific fontconfig queries that correctly found DejaVu Sans Mono.

**Comment by Ambrevar** [comment]
Thanks for the feedback!

It could be useful to document the workaround you found, but I'm not sure where that would belong.  Does it even belong to Nyxt at all?

**Comment by arunisaac** [comment]
No, the workaround isn't Nyxt-specific at all. It is about locales and
fontconfig. It's probably fine to leave it here in this issue tracker.

**Comment by Ambrevar** [comment]
Alrighty! :)
