### ISSUE TITLE
Disable Accept Language header

### ISSUE THREAD

**Issue by arunisaac** [atlas-engineer/nyxt#941]
Nyxt sends out the Accept-Language header, presumably based on the locale. This is a leak of private information and aids browser fingerprinting. Is there a way to disable the Accept-Language header? Perhaps the Accept-Language header should even be disabled by default, and enabled only if the user explicitly does so in their configuration.

**Comment by Ambrevar** [comment]
There is
https://webkitgtk.org/reference/webkit2gtk/stable/WebKitWebContext.html#webkit-web-context-set-preferred-languages.
Maybe calling it on an empty string would help here?  What do you think?

**Comment by jmercouris** [comment]
Wouldn't calling it on an empty string also be leaking some information?

**Comment by Ambrevar** [comment]
Good call.  We could make a mode that picks a language at random on
every request.

Any idea what Tor browser does?

**Comment by aartaka** [comment]
`"en_US"` is the best bet against fingerprinting. Haven't looked at Tor Browser, but my privacy-hardened Firefox (Tor Browser can be said to be a hardened FF too) sends exactly this locale, because it's the most common and least informative locale out there.

**Comment by Ambrevar** [comment]
I've added ffi-set-preferred-languages so you can now set the header the way you want.  You'll need the latest cl-webkit which fixes a crash for this.

There is no user-facing command/mode for this at the moment.  What shall we do?  What about a `notracking` mode which would implement all the measures of the Tor browser?  The problem is that if we don't implement enough measures immediately, the name `notracking` might be too ambitious at the risk of compromising the user.

**Comment by jmercouris** [comment]
`minimize-tracking` could suffice?

**Comment by jmercouris** [comment]
or `reduce-tracking`? In any case `no-tracking` is something that we cannot guarantee.

**Comment by Ambrevar** [comment]
Then `reduce-tracking-mode`?

**Comment by jmercouris** [comment]
Oui!

**Comment by Ambrevar** [comment]
What about `low-tracking-mode`?

**Comment by jmercouris** [comment]
It doesn't really matter, it can always be changed later :-)

**Comment by jmercouris** [comment]
Personally I am a fan of `reduce-tracking-mode`. Because what is "low"? what is "high"? Reduce is clear, less than normal. That's the only thing we can promise to try to do.

**Comment by Ambrevar** [comment]
Agreed!

**Comment by arunisaac** [comment]
I just tested it and it works. Thank you!
