### ISSUE TITLE
Nyxt UI library?

### ISSUE THREAD

**Issue by aartaka** [atlas-engineer/nyxt#946]
Having a Nyxt-native lispy UI library will immensely simplify life of both extension-writers and maintainers. For example, all of the browser buttons could be easily restyled, if there will be a `button` UI class that we'll be able to redefine style of.

This will also make it easier for us to build interfaces in the same style without a need to remember the preferable CSS properties. All the buttons can be of exactly the same perfect shade of grey by default :star_struck: 

Examples of UI systems that we can draw inspiration from:
- [Emacs' widgets](https://www.gnu.org/software/emacs/manual/html_node/widget/Introduction.html#Introduction)
- [Garnet Project](https://www.cs.cmu.edu/~garnet/) ([repo with a modern more-or-less functional rewrite](https://github.com/earl-ducaine/cl-garnet))
- GUI libraries in the languages outside Lisp :)

Somewhat connected to #887 on the point of building things on top of Nyxt. Good UI library will make it much easier :)

**Comment by Ambrevar** [comment]
There is also McClim which I believe could inspire us.

**Comment by aartaka** [comment]
Closing this, because we already have enough of UI library-ish things: `spinneret-tags.lisp`, LASS styles, `lisp://` URLs.
