### ISSUE TITLE
Feature Request: Make it easy to navigate to "next"/"prev" elements

### ISSUE THREAD

**Issue by jellelicht** [atlas-engineer/nyxt#947]
I've been a fan of vimium's `goNext` and `goPrevious` for the longest time; it basically boils down to finding and following a `<link>`, `<a>` or `<area>` tag with `rel` attribute of "next"/"prev" (or any user customizable regex, really).

Could something similar be implemented in nyxt?

**Comment by Ambrevar** [comment]
Like on a GNU manual page where goNext would go the the next node?

I did implement something similar in the past for some browser, it's
very easy.

Would you like to send a patch? :)

**Comment by jellelicht** [comment]
If I can get some pointers on a nice interactive workflow for developing parenscript, sure :+1:

**Comment by Ambrevar** [comment]
Parenscript homepage:

https://common-lisp.net/project/parenscript/

Official tutorial:

https://common-lisp.net/project/parenscript/tutorial.html

For interactivity, you'll probably want Emacs with SLIME or SLY.
SLIME needs some configuration, SLY is more functional out-of-the-box.

In the REPL, you can expand macros (e.g. sly-macro-expand-all), inspect
objects (sly-inspect) and much more.

A REPL debugging tutorial that I like:

https://malisper.me/debugging-lisp-part-1-recompilation/

To run Parenscript in Nyxt, you need to use `define-parentscript`, then
call the resulting function in a `with-result` form.

Let me know if you need more pointers!

**Comment by jellelicht** [comment]
Thanks!

Still one question: (how) can I set up the nyxt from guix
(2-pre-release-1) to be hackable with sly? Or would that rather be a
nyxt-from-git-only experience?

**Comment by Ambrevar** [comment]
See the comments in build-scripts/guix.scm to load the dependencies.

To get the Nyxt source from Guix, you can do

    (uiop:run-program '("guix" "build" "-S" "nyxt") :output '(:string :stripped t))

which yields a path.

In your .sbclrc:

    (push #P"/path/to/nyxt" asdf:*central-registry*)


You could even get the path dynamically like this (untested):


    (push (pathname (uiop:run-program '("guix" "build" "-S" "nyxt") :output '(:string :stripped t)))
          asdf:*central-registry*)

Restart the REPL, then you should be able to

    ,load-system RET nyxt RET

**Comment by jmercouris** [comment]
Please look at Pierre's dotfiles for Sly configuration.

Start swank in Nyxt, and then in Emacs, slime-connect :-). Port 4006 by default.

**Comment by jellelicht** [comment]
I got stuff to work properly with sly, I'll ping this issue once I'm
done (or stuck...)

**Comment by Ambrevar** [comment]
Fantastic!

**Comment by jellelicht** [comment]
I got a first draft going (that by pure luck seems to work for reading comics online :smile: ) [here](https://gist.github.com/jellelicht/99e8b0dbb2533bea1888276d3fee39b5).  Could someone with more CL experience give some pointers on the general approach, or any nitpicks on the way I choose to implement it here? 

A second point is that I currently am running this in my custom keymap in my `init.lisp`: do you think this would make a good mode (e.g. `easy-navigation-mode`) or rather a cookbook entry?

**Comment by jmercouris** [comment]
Make a pull request, and @Ambrevar or myself will be happy to give you feedback and help you iterate on it :-)

I think it may make a good mode.

**Comment by Ambrevar** [comment]
Actually I think it'd better fit web-mode, just like search-buffer or element-hinting.

**Comment by pdelfino** [comment]
If I did not get anything wrong, the hyperlinked issue/discussion on [cl-webkit ](https://github.com/joachifm/cl-webkit/issues/56) repository is relevant for the parenscript code used to solve this feature request. Thus, I am putting a pointer here.

**Comment by pdelfino** [comment]
Hi guys,

I think we can close this issue since a [PR](https://github.com/atlas-engineer/nyxt/pull/1532) about this feature request was already merged to master.

**Comment by jmercouris** [comment]
Agreed.
