### ISSUE TITLE
Documentation files location

### ISSUE THREAD

**Issue by aadcg** [atlas-engineer/nyxt#948]
Hi nyxt,

I'm a bit lost. How can I send patches to fix typos in the documentation?  

The docs used to be at documents/MANUAL.org.

**Comment by Ambrevar** [comment]
Since 2-pre-release-1 the manual is included in the source in source/manual.lisp.

You can send patches by opening a pull request on GitHub.  Do you know
how these work?

**Comment by aadcg** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> Since 2-pre-release-1 the manual is included in the source in
> source/manual.lisp.

Oh, thanks!

> You can send patches by opening a pull request on GitHub. Do you know
> how these work?

Done!
