### ISSUE TITLE
HiDPI displays on sway

### ISSUE THREAD

**Issue by aadcg** [atlas-engineer/nyxt#951]
I followed the instructions on the manual to scale Nyxt using the GDK environment variables.

That works for me on GNOME, but not on sway. On sway I noted that setting `GDK_BACKEND=x11` makes the fonts bigger, but then the browser won't be usable. So, does anyone have any ideas why setting the GDK env variables when the backend is set to wayland doesn't work? Is there any workaround? Thanks.

**Comment by aadcg** [comment]
I was thinking that maybe one way to solve this would be to override the font-size found in minibuffer.lisp and window.lisp using the `startup-function`.

Maybe someone could give me a hand with Common Lisp? How can I do the equivalent of `setq` to set these vars?

**Comment by jmercouris** [comment]
Thank you for your interest in Nyxt :-)

You can deal with some font sizes by changing the styles as you've suggested.

To override them:

```
(define-configuration minibuffer
  ((style "your-style-code-here")))
```

That's just one example. Check out `describe-slot` for the different styles that you can change :-)

**Comment by aadcg** [comment]
Here's what my hacking and few expertise yielded: 

```lisp
(define-configuration buffer
  ((default-modes (append '(emacs-mode my-mode) %slot-default))
   (current-zoom-ratio 2.5)
   (zoom-ratio-default 2)))

(define-configuration minibuffer
  ((max-lines 6)
   (minibuffer-style (cl-css:css
                      '((* :font-family "monospace,monospace" :font-size "24px" :line-height "28px")
                        (nyxt::body :border-top "4px solid dimgray" :margin "0" :padding "0 6px")
                        ("#container" :display "flex" :flex-flow "column" :height "100%")
                        ("#input" :padding "6px 0" :border-bottom "solid 1px lightgray")
                        ("#suggestions" :flex-grow "1" :overflow-y "auto" :overflow-x "auto")
                        ("#cursor" :background-color "gray" :color "white")
                        ("#prompt" :padding-right "4px" :color "dimgray")
                        (nyxt::ul :list-style "none" :padding "0" :margin "0")
                        (nyxt::li :padding "2px")
                        (nyxt::.marked :background-color "darkgray" :font-weight "bold" :color
                                       "white")
                        (nyxt::.selected :background-color "gray" :color "white"))))))
```

I'm sure this can be done in much better ways.

I will also explore another "solution":

-  output <monitor> scale <integer> (add this to sway/config)

- try to run emacs natively on wayland ([example](https://git.sr.ht/~oldosfan/emacs-pgtk)) otherwise the scaling will just blur fonts.
