### ISSUE TITLE
Can't use right click, closes after releasing button.

### ISSUE THREAD

**Issue by Kazimazi** [atlas-engineer/nyxt#956]
**Describe the bug**
Right click menu closes on releasing right click.

**Precise recipe to reproduce the issue**
Right click, release.

**Information**
- OS name+version: NixOS 20.03
- Graphics card and driver: Radeon 5700 XT
- Desktop environment / Window manager name+version: Sway 1.4
- How you installed Nyxt (Guix pack, package manager, build from source): nixos-unstable
- Nyxt version (from =M-x nyxt-version= or =nyxt --version=): 1.5.0
- Lisp implementation/version (if built from source):
- Kernel name+version: Linux 5.7.19
- WebKitGTK+ | QtWebEngine version: Webkit 2.28.4 (I think)

**Comment by Ambrevar** [comment]
This bug is fixed in 2-pre-release-1, please update ;)

**Comment by Kazimazi** [comment]
thx
