### ISSUE TITLE
Make open-file-from-directory-suggestion-filter work more like find-file in Emacs

### ISSUE THREAD

**Issue by kssytsrk** [atlas-engineer/nyxt#961]
Right now, #'nyxt/file-manager-mode::open-file-from-directory-suggestion-filter is imperfect - it does not suggest completions deeper than the directory Nyxt was started from (see the image below for an example). This makes opening files more difficult and the autocomplete essentially useless for anything but current directory's files.

[![2020-09-21-21-03.png](https://i.postimg.cc/7hxR6XX8/2020-09-21-21-03.png)](https://postimg.cc/N9zDC6Wp)

The desired outcome would be making it work more like find-file autocompletion in Emacs, in that it should change the suggestions based on the directory user typed in (on the image it is "/usr/dev/" part that is not taken into account).

**Comment by Ambrevar** [comment]
The file manager is very primitive at the moment and hasn't been touched
in a while.

I intend to make it more like helm-find-files:
https://emacs-helm.github.io/helm/.

This won't be before a while though as there are many more urgent things
to do :)

Help welcome!

**Comment by tg-x** [comment]
i'd like to see such local file completion functionality.

how do i trigger the current implementation of this open-file command though? on nyxt-2-pre-6?

**Comment by aartaka** [comment]
The recently introduced `file-source` has a directory-aware completion. Close?

**Comment by Ambrevar** [comment]
Indeed, thanks for your work @aartaka !
