### ISSUE TITLE
Pre-defined auto-mode rules

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#962]
It came to my mind that we could very well provide a service for auto-mode rules in the same fashion as ad-blocker provide host blocklists.

We could have different rule sets for different uses.  For instance:

- Extreme low bandwidth: enable javascript + ads + images on select websites that require it.
- Noscript and no ads: enable javascript + ads on select websites that require it.
- No ads: enable ads on select websites that require it.

When roaming between networks of varying quality, it would be easy for the user to switch, say, from the "extreme low bandwidth" rule set to the "no ads" rule set.

Thoughts? @aartaka ?

**Comment by Ambrevar** [comment]
These rulesets would need to be kept up-to-date.  It's probably not worth integrating into Nyxt since websites are updated faster than Nyxt is.  This means that, just like ad block lists, we need to download the rule sets from a third-party repository.

**Comment by aartaka** [comment]
This sounds good! 

Are there such lists of websites requiring whatever we'd want to disable/enable? Adblocking lists can be adjusted this way for `blocker-mode`, but what about JS/images?

Is publishing exception lists for adblocking/JS-blocking plugins an acceptable practice (I haven't seen anyone doing so)? If there are some public exception lists, than that's the place to look for the rules.
