### ISSUE TITLE
Nyxt doesn't open url when it contains '#' character

### ISSUE THREAD

**Issue by hajovonta** [atlas-engineer/nyxt#964]
When trying to open an URL which contains a # character, Nyxt changes the URL and opens something else (it may be a redirect from the server). I experienced it with using Spinnaker:

```
https://spinnaker.company.com/#/applications/app/executions/details/01EJWRZ9FJJ7E9RTTWNHSVQ1EF?stage=0&step=0
```

this becomes:

```
https://spinnaker.company.com/?stage=0&step=0#/search
```

OS: Ubuntu 18
Nyxt: 2-pre-release-1-163-ge7da9807
SBCL: 2.0.8.75-2ea8b6182

**Comment by hajovonta** [comment]
I can navigate to the exact page by clicking on the interface, even though the URL still contains the #. It's like the open url function doesn't work perfectly.

**Comment by Ambrevar** [comment]
Looks like a bug in QURI.

```
NYXT>  (quri:uri "https://example.org/?a#b")
#<QURI.URI.HTTP:URI-HTTPS https://example.org/?a#b>
NYXT>  (quri:uri "https://example.org/#a?b")
#<QURI.URI.HTTP:URI-HTTPS https://example.org/?b>
```

Or else `/#/` might actually be illegal.
I'll investigate.

**Comment by Ambrevar** [comment]
Reported upstream: https://github.com/fukamachi/quri/issues/36

**Comment by Ambrevar** [comment]
Shoud be fixed with #1033.  @hajovonta Can you test against master (make sure it uses the quri Git submodule) and report if it works for you?

**Comment by hajovonta** [comment]
I hereby confirm the issue is gone. Works perfectly!

**Comment by Ambrevar** [comment]
Fantastic, thanks for reporting!
