### ISSUE TITLE
Cross-references in docstrings / *describe* buffers

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#967]
It would be nice to turn docstring cross references to `lisp://` URLs.
For instance, the docstring of `buffer-load` mentions `buffer-load-hook`: we would turn it into a clickable link which would open the appropriate description page.

This was discussed in #745.

It shouldn't be too hard: parse "`[^[:space:]]*'" or something like that and replace it with `lisp://(describe MATCH)`.
`describe` would be a smart function which finds out which description function to call depending on the type.
If a symbol has multiple types (e.g. both a function and a variable), then we would query the user.

Thoughts?

**Comment by jmercouris** [comment]
I feel like 1984 editing your messages :-D

**Comment by jmercouris** [comment]
I really like this idea. I assume the idea is kind of like how when clicking M-. on a object if Lisp finds multiple things like several methods with the name, you select the one that you are interested in?

**Comment by Ambrevar** [comment]
Exactly!

**Comment by aadcg** [comment]
> If a symbol has multiple types (e.g. both a function and a variable), then we would query the user.

I like the idea but there should be a smarter way to deal with the above.

**Comment by jmercouris** [comment]
There is no smarter way. A symbol in a Lisp-2 is ambiguous and has to be resolved. An alternative may be displaying both a listing for the symbol as a function as and as a variable.

For example:

`xyz (variable)`
`xyz (function)`

**Comment by Ambrevar** [comment]
This is the different topic of _symbol namespaces_ (whether we want to
resolve a symbol to a function, a class, a variable, etc.).

What the "target" slot solves is the problem of how to refer to _values_
(unprintable objects).
Note that the problem of symbol namespaces does not occur in the context
of this patch.

**Comment by Ambrevar** [comment]
About symbol namespaces: your suggestion could work.
In case of ambiguity (e.g. because the parentheses were forgotten), we
can prompt the user for the namespace.

**Comment by Ambrevar** [comment]
Would be nice to have bi-directional linking, i.e. list all symbols where the current symbol help page is referenced.

**Comment by Ambrevar** [comment]
Partially done in https://github.com/atlas-engineer/nyxt/commit/ed97f71e66c7a4b3eea481d3bb7e5951fb88df76.

But I'd like to address a few points:

- The regex could be "`[^'\\s]+'" to include any kind of whitespace.
- Multiple definitions are not supported.  Try with `nyxt:name`.

For this last point, I suggest the following:
- Call `describe-any` instead of the entire `(cond ... 'describe-variable ...)`.
- Modify `describe-any` to take an input argument.
- Add a preprocessor filter to describe-any so that only exact matches are displayed.
- Add a prompter option so that if only one suggestion is present, fire up the default action.

What do you think @aartaka ?

**Comment by Ambrevar** [comment]
OK, I've already done something here, I'll push soon.

**Comment by aartaka** [comment]
> #2063 is now in, we can disambiguate symbols!
> 
> All we miss is bi-directional listing, that is, listing the docstrings where a symbol is referenced. Not an easy one.

But actually, what's the use-case for that? Given how chaotic our references to symbols are, I doubt one can build any reasonable usage patter out of those :)

**Comment by Ambrevar** [comment]
I agree, maybe it's enough to reference calls/uses (like `sly-edit-uses`).

**Comment by aartaka** [comment]
Closing in favor of #2113, where more instances of inspection are mentioned.
