### ISSUE TITLE
Use set-url or set-url-from-current-url by default?

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#969]
See #949 for a discussion.

**Comment by aadcg** [comment]
I think `set-url-from-current-url` makes more sense by default, since that's how most popular browers behave.  Feel free to close this issue, if you have nothing more to add.

**Comment by Ambrevar** [comment]
In a regular browser, pressding `C-l` selects the URL from the bar and the next editing key replaces the URL.
We don't support this behaviour at the moment.

To add such support, we would need more advanced text editing features such as text highlighting.

**Comment by jmercouris** [comment]
I agree with both of you. I think that set-url-from-current-url is what users expect, however, we should have the mark on the whole text body so that the user can replace it with a single key.

**Comment by jmercouris** [comment]
So, my personal conclusion: set-url-from-current-url as default, WHEN we have the ability to highlight text.

**Comment by aadcg** [comment]
Is anyone working on text highlighting?

**Comment by Ambrevar** [comment]
I'm working on a minibuffer overhaul which may include this feature.
See #777.

But this overlaps with the text editor.

**Comment by aadcg** [comment]
Woow, lots of cool ideas and lots of work ahead.  

If I can be of any help, let me know. I'm wondering if there's work I could do on #1027 that could help you.

**Comment by jmercouris** [comment]
This is now the new default :-)
