### ISSUE TITLE
set-url on file:///... fails with upper-case in path

### ISSUE THREAD

**Issue by Stekache** [atlas-engineer/nyxt#974]
Using Nyxt 2-pre-release-2 on GNU/Linux Guix.

Typing to "set-url" on a local file with "file:///path-to-file" only works if there is no upper case character in the whole path-to-file. When there is an upper-case, it returns a page with "Error opening file /path-to-file : No such file or directory".

(workaround: just type/open the path up to the last part without upper case, then navigate using hyperlinked file listing)

**Comment by gravitational-dark-light** [comment]
The problem seems to be in `quri:render-uri`, it downcases the path so that **"file:///somedir/Some other Dir/The Path to My File.html"** becomes **"file:///somedir/some other dir/the path to my file.html"**

**Comment by Ambrevar** [comment]
Indeed.  I'll send a patch upstream.

**Comment by Ambrevar** [comment]
Fixed with #1033.
