### ISSUE TITLE
Replace unpresent-current-window by a toggler

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#982]
It seems unnecessary to have 2 commands to present/unpresent the current window.
615ffd7b80868c7f2b8de816fe50a7e9ba48b73c

Besides, the command name is not very evocative in my opinion.

I suggest replacing both commands by a single command which toggles the status + message views.  What `toggle-status-bars` or `toggle-window-widgets`?

**Comment by jmercouris** [comment]
there is a problem with those names:

1. they are not two status bars
2. they are not the only widgets in the window

I believe present to be the best term because you are 'presenting' the content. With regards to having a toggler, I can implement a toggle on top of them that uses the function, no problem!

**Comment by Ambrevar** [comment]
I suggest having just one command though, because too many commands
clutters the execute-command minibuffer.

About 'present', the problem is that we are not saying what we present.
What about "toggle-bars"?  Or "toggle-menu"?

**Comment by jmercouris** [comment]
yes, we are, it is called `present-window`, I think it is quite clear. How else could it be interpreted?

**Comment by Ambrevar** [comment]
"window" is everything.  What about "present-web-view" or "present-web-page"?

**Comment by jmercouris** [comment]
OK, we are getting closer, `present-web-buffer`?

**Comment by Ambrevar** [comment]
`web-buffer` is already a class, and I suppose the command will work
with internal buffers too.

Still not very convinced with the "present" term.

Now that I'm thinking of it, other programs use the term "toolbars".
What about "toggle-toolbars" then?

**Comment by jmercouris** [comment]
I guess they are toolbars. Yes, that would be a good name!

**Comment by Ambrevar** [comment]
Great, thanks!

**Comment by Ambrevar** [comment]
Done in ef876b56e33f1dca4ed928aa2a1868d39c733b53.

**Comment by jmercouris** [comment]
Theres a problem, it uses GTK directly within the body. This breaks our FFI abstraction, the state must be remembered by the GTK window object.

**Comment by jmercouris** [comment]
Which is why I did not implement this yet :-D, it was either that or an FFI function to get the state of the toolbar visibility. I think a FFI-window-toolbar-visible-p is the better more flexible option

**Comment by Ambrevar** [comment]
Oops!  Sorry about that!
Will fix on Monday unless you beat me to it.

**Comment by jmercouris** [comment]
No problems :-D

**Comment by Ambrevar** [comment]
I've been thinking a little: all the minibuffer/status/message view
resizing operations are akin to window management we don't have yet.

But the status / message views are implementation dependent and not
necessarily "windows" (unlike buffer and minibuffer), right?  We can
very well imagine an implementation that uses some toolbar system to
implement the status view and the message area.  In those cases, they
would not be resizable.  However, it's almost certain that they can be
toggled.

This is why I propose we replace the 2 FFIs with 2 togglers.  Sounds good?

**Comment by Ambrevar** [comment]
Should be fixed by #985.
