### ISSUE TITLE
lisp:// URLs parentheses are understood as "[(" and ")]" in CCL

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#988]
When we send %28 and and %29 to `webkit:webkit-web-view-load-uri` the URL we get back in `(webkit:webkit-uri-request-uri request)` is "[(" and ")]" instead of "(" and ")".

Any clue what's going on?  Another weird CFFI bug?

**Comment by jmercouris** [comment]
mitigate said the following on IRC

7:28 AM <mitigate> i figured out the lisp:// failures. i made valid-schemes local variable in lisp-valid-ur-p needs  include "lisp" - also my cl-webkit's webkit2.navigation-action.lisp  didn't have a webkit_uri_request_get_uri. i remember i added it myself in september

**Comment by Ambrevar** [comment]
That's what I did in 
86131d82e5e91e53ce9dfceac00529580f88c385 but it's unrelated to this issue.

**Comment by jmercouris** [comment]
We could use a #+ccl directive to modify the behavior for CCL?

**Comment by Ambrevar** [comment]
But how do we modify the behaviour?  In the original post I explained
that the URL is transfigured by one of the 2 webkit CFFI functions.
What can we do about this beside fixing some obscure FFI bug?

**Comment by jmercouris** [comment]
I'm not sure I understand the question.

**Comment by jmercouris** [comment]
I believe we can do a replacement when we are eval'ing for CCL, would that not fix it?

**Comment by Ambrevar** [comment]
What about the legit presence of `[` and `]`, e.g. in `lisp://(log:info "[hello]")`?

Replacing those square brackets would have an undesirable effect.

**Comment by jmercouris** [comment]
Yes, but we would replace "[(" with "(", so that would be OK.

**Comment by jmercouris** [comment]
I believe the only time this might realistically be a problem is if we have a function named [xyz] and then in our lisp url we want to write ([xyz])

**Comment by Ambrevar** [comment]
> Yes, but we would replace "[(" with "(", so that would be OK.

This is very brittle...
Any string containing "[(" would be corrupted.

I believe a saner approach is to fix the FFI or try with cl-gobject-introspection.

**Comment by jmercouris** [comment]
A good point you make, it is not a robust solution.

**Comment by Ambrevar** [comment]
@aartaka Is this obsolete now?

**Comment by aartaka** [comment]
Yes, it is. If we use no parentheses, we have no problems :P
