### ISSUE TITLE
MacOS source built works initially but soon ends up in error : command ("stat" "-f" "%T" "/.local/share/nyxt/nyxt.socket") exited with error code 

### ISSUE THREAD

**Issue by dineshbhardwaj** [atlas-engineer/nyxt#992]
I ran Nyxt and built from source and I ended up the following error 

`Nyxt version 2-pre-release-2-137-g742b2bad
<INFO> [09:06:52] Loading Lisp file "~/.config/nyxt/auto-config.lisp".
Unhandled UIOP/RUN-PROGRAM:SUBPROCESS-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING
                                                         {1000648083}>:
  Subprocess #<UIOP/LAUNCH-PROGRAM::PROCESS-INFO {1005CFDF53}>
 with command ("stat" "-f" "%T" "~/.local/share/nyxt/nyxt.socket")
 exited with error code 1

Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {1000648083}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<UIOP/RUN-PROGRAM:SUBPROCESS-ERROR {1005D092E3}> #<unused argument> :QUIT T)
1: (SB-DEBUG::RUN-HOOK SB-EXT:*INVOKE-DEBUGGER-HOOK* #<UIOP/RUN-PROGRAM:SUBPROCESS-ERROR {1005D092E3}>)
2: (INVOKE-DEBUGGER #<UIOP/RUN-PROGRAM:SUBPROCESS-ERROR {1005D092E3}>)
3: (UIOP/IMAGE:HANDLE-FATAL-CONDITION #<UIOP/RUN-PROGRAM:SUBPROCESS-ERROR {1005D092E3}>)
4: (SB-KERNEL::%SIGNAL #<UIOP/RUN-PROGRAM:SUBPROCESS-ERROR {1005D092E3}>)
5: (CERROR "IGNORE-ERROR-STATUS" UIOP/RUN-PROGRAM:SUBPROCESS-ERROR :COMMAND ("stat" "-f" "%T" "~/.local/share/nyxt/nyxt.socket") :CODE 1 :PROCESS #<UIOP/LAUNCH-PROGRAM::PROCESS-INFO {1005CFDF53}>)
6: (UIOP/RUN-PROGRAM::%CHECK-RESULT 1 :COMMAND ("stat" "-f" "%T" "~/.local/share/nyxt/nyxt.socket") :PROCESS #<UIOP/LAUNCH-PROGRAM::PROCESS-INFO {1005CFDF53}> :IGNORE-ERROR-STATUS NIL)
7: (UIOP/RUN-PROGRAM::%USE-LAUNCH-PROGRAM ("stat" "-f" "%T" "~/.local/share/nyxt/nyxt.socket") :OUTPUT (:STRING :STRIPPED T))
8: (NYXT::FILE-IS-SOCKET-P "~/.local/share/nyxt/nyxt.socket")
9: (NYXT::BIND-SOCKET-OR-QUIT NIL)
10: (NYXT::START-BROWSER NIL)
11: (START NIL)
12: ((LAMBDA NIL :IN UIOP/IMAGE:RESTORE-IMAGE))
13: (UIOP/IMAGE:CALL-WITH-FATAL-CONDITION-HANDLER #<CLOSURE (LAMBDA NIL :IN UIOP/IMAGE:RESTORE-IMAGE) {1005E8F19B}>)
14: ((FLET SB-UNIX::BODY :IN SB-EXT:SAVE-LISP-AND-DIE))
15: ((FLET "WITHOUT-INTERRUPTS-BODY-14" :IN SB-EXT:SAVE-LISP-AND-DIE))
16: ((LABELS SB-IMPL::RESTART-LISP :IN SB-EXT:SAVE-LISP-AND-DIE))

unhandled condition in --disable-debugger mode, quitting
`
gtk versions --- 

gtk-doc @1.32_1+python38 (active)
  gtk2 @2.24.32_0+x11 (active)
  gtk3 @3.24.21_0+x11 (active)
  webkit-gtk @2.4.11_3+video (active)
  webkit2-gtk @2.28.2_0+minibrowser+x11 (active)

**Comment by Ambrevar** [comment]
What happens if you run

  stat -f %T ~/.local/share/nyxt/nyxt.socket

in a shell?

**Comment by jmercouris** [comment]
Does the file /.local/share/nyxt/nyxt.socket exist? How are you starting Nyxt?

**Comment by jmercouris** [comment]
Are you trying to start Nyxt as root?

**Comment by dineshbhardwaj** [comment]
> What happens if you run stat -f %T ~/.local/share/nyxt/nyxt.socket in a shell?

$ stat -f %T ~/.local/share/nyxt/nyxt.socket
stat: nelze přečíst informace souborového systému pro '%T': No such file or directory
Soubor: "~/.local/share/nyxt/nyxt.socket"
    ID: 100000400000019 Délka jména: ?       Druh: apfs
Velikost bloku: 4096       Velikost základního bloku: 4096
Bloků:  Celkem: 29571062   Volných: 4427192    Dostupných: 1273670
I-uzlů: Celkem: 1182842480 Volných: 1179697091

**Comment by dineshbhardwaj** [comment]
> How are you starting Nyxt?

I use the following command - 

~/common-lisp/nyxt/Nyxt.app/Contents/MacOS/nyxt

**Comment by dineshbhardwaj** [comment]
> Are you trying to start Nyxt as root?

No, I am starting as normal user. As I had build it using "make all" the binary is present at the path as shown above. 

I tried the mac port also to install the nyxt, I was stuck as "portindex"  command does not recognize any of the installable application there.

**Comment by dineshbhardwaj** [comment]
just to add on to it, if I delete ~/.local/share/nyxt folder, It starts working again. the first message seen on the terminal is: 

``
Nyxt version 2-pre-release-2-137-g742b2bad
<INFO> [05:42:31] Loading Lisp file "~/.config/nyxt/auto-config.lisp".
<INFO> [05:42:32] Listening to socket "~/.local/share/nyxt/nyxt.socket".
``

And then again it will stop working, once quit.

**Comment by jmercouris** [comment]
Interesting, it doesn't seem to like writing to that socket and then re-reading from it.

**Comment by dineshbhardwaj** [comment]
Is there any fix, which I can try ?

**Comment by Ambrevar** [comment]
@jmercouris: Can you reproduce locally in multi-instance mode?

**Comment by Ambrevar** [comment]
Sorry, I meant single-instance mode.

**Comment by jmercouris** [comment]
I cannot, no.

**Comment by dineshbhardwaj** [comment]
> you can disable single instance mode for now, as I have done.
> 
> If you put the following in your configuration file:
> 
> ```
> (setf *socket-path* nil)
> ```

So, What i could understand is add the line in ~/common-lisp/nyxt/source/configuration.lisp file. I have added the lines like this. Is this correct? 


```
;;;; SPDX-FileCopyrightText: Atlas Engineer LLC
;;;; SPDX-License-Identifier: BSD-3-Clause

(in-package :nyxt)

(export-always '*auto-config-file-path*)
(setf *socket-path* nil)

(defvar *auto-config-file-path* (make-instance 'data-path :basename "auto-config")
  "The path of the generated configuration file.")
Apples-MacBook-Pro-2:pmisminema Apple$ head -n 80 ~/common-lisp/nyxt/source/configuration.lisp 
;;;; SPDX-FileCopyrightText: Atlas Engineer LLC
;;;; SPDX-License-Identifier: BSD-3-Clause

(in-package :nyxt)

(export-always '*auto-config-file-path*)
(setf *socket-path* nil)

(defvar *auto-config-file-path* (make-instance 'data-path :basename "auto-config")
  "The path of the generated configuration file.")

(export-always 'funcall-safely)
(defun funcall-safely (f &rest args)
  "Like `funcall' except that if `*keep-alive*' is nil (e.g. the program is run
from a binary) then any condition is logged instead of triggering the debugger."
  (if *keep-alive*
      (apply f args)
      (handler-case
          (apply f args)
        (error (c)
          (log:error "In ~a: ~a" f c)
          nil))))
....

````
```

(setf *socket-path* nil)
```

**Comment by jmercouris** [comment]
No, that is incorrect. Your configuration file is located at ~/.config/nyxt/init.lisp, see my dot files for more details: https://github.com/jmercouris/configuration/blob/master/.config/nyxt/init.lisp

**Comment by aadcg** [comment]
Closed due to lack of feedback from the user who reported the issue.
