### ISSUE TITLE
CI: Add workflow to check if build-scripts/guix.scm builds

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#994]
I've almost managed to get it to work, but:

https://gitlab.com/singularsyntax-docker-hub/guix-bootstrap/-/issues/1

The issue is probably with a path difference between GitHub and GitLab, but my Docker knowledge is close to zero so I don't know what's going on.

Any idea?

**Comment by jmercouris** [comment]
I have no idea. Why doesn't that dir exist?

**Comment by Ambrevar** [comment]
Maybe the Docker mounting options are not fitting.

**Comment by aadcg** [comment]
What's the meaning of [this](https://gitlab.com/singularsyntax-docker-hub/guix-bootstrap/-/blob/master/Dockerfile#L16) syntax - `~root`?

**Comment by Ambrevar** [comment]
`~root` expands to the home folder of the root user.

**Comment by Ambrevar** [comment]
The above docker may not be usable after all.

I was referred to this instead which looks very promising:

	https://github.com/PromyLOPh/guix-install-action
	https://github.com/guix-science/guix-science/blob/master/.github/workflows/build.yml

**Comment by Ambrevar** [comment]
@aadcg just shared this link: https://github.com/metacall/guix
Looks most promising, I'll try soon!

**Comment by aartaka** [comment]
We have this build check, don't we? Closing this.
